- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/vendor/javascripts/can.map.backup.js
This is a clone of PR #2034 from the develop mainline, being brought over as a hotfix since it isn't been generating errors and is needed to solve CORE-864
#resolve
> CORE-864 merge conflict resolution for v0.9.0

- src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache
If he is the assignee. The code used to check if the person is an assignee of a task or task group, but checking the assignee (contact) field of the cycle task might make more sense.
> CORE-882 WF Member should be able to reassign a task

- src/ggrc_workflows/assets/javascripts/models/helpers.js
> Fixes link in review notification email

- src/ggrc_gdrive_integration/assets/mustache/responses/gdrive_upload_evidence.mustache
> new documentation response modal spaced nicely

- src/ggrc/assets/mustache/sections/tier2_content.mustache
Sections didn't have unmap links when expected and there was code duplication.
> sections should have unmap link

- src/ggrc_gdrive_integration/assets/javascripts/controllers/gdrive_workflows_controller.js
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache
- src/ggrc_gdrive_integration/assets/mustache/responses/gdrive_upload_evidence.mustache
@bmomberger-reciprocity I stole this story from you, sorry :)
I had a weird issues with `that.on()` - if I called it in the `extended_folders` deferred it threw an exception. There were also some odd things going on if I left `that.on()` the way it was, but removing it weirdly resolved the issues I was having...
> CORE-887 Default to folder in extended_folders mapping

- src/ggrc/services/common.py
Later, server-side processing can be optimized too by having `filter_resource()` not retrieve the other fields to being with.
> __fields API parameter to return specific object properties

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/responses/tree.mustache
CORE-693
Mustache helper to truncate arbitrary strings to length N, or just the first line by default.
> Titles of multiline requests get truncated

- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree.mustache
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/dashboard/object_nav_actions.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree_footer.mustache
> CORE-860 Make inactive workflows non-editable in setup.

- src/ggrc/assets/javascripts/controllers/modal_selector_controller.js
@Swizec I think your fix works well in modal_controller, but not in modal_selector_controller. setTimeout is the only solution I was able to find.
> CORE-966 Autocomplete in mappings modal not adding values to inputs

- src/ggrc/assets/javascripts/dashboard.js
- src/ggrc/assets/mustache/base_objects/contacts.mustache
- src/ggrc/assets/mustache/base_objects/general_info.mustache
- src/ggrc/assets/mustache/base_objects/info.mustache
- src/ggrc/assets/mustache/base_objects/notes.mustache
- src/ggrc/assets/mustache/base_objects/notes_and_code.mustache
- src/ggrc/assets/mustache/base_objects/urls.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/mustache/objectives/info.mustache
- src/ggrc/assets/mustache/people/info.mustache
- src/ggrc/assets/mustache/policies/info.mustache
- src/ggrc/assets/mustache/processes/info.mustache
- src/ggrc/assets/mustache/products/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/sections/info.mustache
- src/ggrc/assets/mustache/systems/info.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_footer.scss
- src/ggrc/assets/stylesheets/_header.scss
- src/ggrc/assets/stylesheets/_lhs.scss
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc/templates/layouts/dashboard.haml
> redesign info widgets

- doc/Modals.md
- doc/application.js.md
> Add more Brad notes to doc, especially Modals

- src/ggrc/assets/javascripts/controllers/modals_controller.js
Arrived at this fix wile pairing with @bmomberger-reciprocity.
It's essentially a clone of PR #2155.
Fixes CORE-975.
> Add value to input after modal autocomplete

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/mustache/base_objects/filters/advanced_search_filter_actions.mustache
- src/ggrc/assets/mustache/base_objects/filters/modal_filter_actions.mustache
- src/ggrc/assets/mustache/base_objects/form_restore.mustache
- src/ggrc/assets/mustache/dashboard/modal_preload.mustache
- src/ggrc/assets/mustache/modals/confirm_buttons.mustache
- src/ggrc/assets/mustache/modals/delete_cancel_buttons.mustache
- src/ggrc/assets/mustache/modals/done_buttons.mustache
- src/ggrc/assets/mustache/modals/save_cancel_buttons.mustache
- src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
- src/ggrc/assets/mustache/modals/unmap_cancel_buttons.mustache
- src/ggrc/assets/mustache/search/advanced_search_base_modal.mustache
- src/ggrc/assets/mustache/selectors/base_modal.mustache
- src/ggrc/assets/mustache/selectors/multitype_base_modal.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_modal.scss
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/audit_modal.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/base_modal.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/object_detail.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/option_column.mustache
- src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_base_modal.mustache
- src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_option_column.mustache
- src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_option_items.mustache
- src/ggrc_workflows/assets/mustache/selectors/object_selector_base_modal.mustache
CORE-781 Redesigning all modals:
- create/edit modals
- authorisation modals
- mapping modals
> CORE-781 modals redesign

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_setup.scss
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc/assets/stylesheets/_workflow.scss
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_entries/tree.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_objects/tree.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/tree.mustache
- src/ggrc_workflows/assets/mustache/cycles/tree.mustache
- src/ggrc_workflows/assets/mustache/dashboard/object_nav_actions.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree_footer.mustache
- src/ggrc_workflows/assets/mustache/wf_people/tree_footer.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
CORE-780 Redesigning all workflow widgets:
- setup widget
- people widget
- info widget
- active cycle widget
- history widget
> CORE-780 workflow redesign

- src/ggrc/assets/mustache/base_objects/tree_footer.mustache
- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/mustache/sections/tier2_content.mustache
- src/ggrc/assets/stylesheets/_modal.scss
- src/ggrc_workflows/assets/mustache/selectors/object_selector_option_items.mustache
- src/ggrc_workflows/assets/mustache/wf_people/people_items.mustache
- src/ggrc_workflows/assets/mustache/workflows/confirm_start_buttons.mustache
redesign improvements for:
- workflow modals
- workflow history
- "convert to object" moved
> redesign improvements

- src/ggrc/assets/stylesheets/_flash.scss
- src/ggrc/assets/stylesheets/_layout.scss
- src/ggrc/templates/layouts/dashboard.haml
fixing spacing for all dashboard widgets
> fixing spacing for all dashboard widgets

- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
CORE-541 task types names fixed
> CORE-541 task types names fixed

- src/ggrc/assets/mustache/base_objects/view_link.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache
- src/ggrc_workflows/assets/mustache/tasks/tree.mustache
- src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
workflow and tasks tree redesign when on object page
> workflow and tasks tree redesign when on object page

- src/ggrc/assets/mustache/base_objects/tree_view_filters.mustache
- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/filters.mustache
Redesign of custom filters is done. Few things needed:
- In filter title "Filter" there should be object type. For example "Filter Systems" or "Filter Programs".
- JS for show/hide filters. Same as for top nav, default state is shown, user can hide it, that user choice should be remembered in local settings.
> CORE-752 custom filters redesign

- src/ggrc/assets/javascripts/controllers/info_widget_controller.js
- src/ggrc/assets/mustache/dashboard/info/info.mustache
- src/ggrc/assets/mustache/dashboard/info/my_audits.mustache
-Removed log message from mustache file
-Removed msg field when no over-due message 
-Removed script error on task-filter
> Script error and other minor fixes, part of CORE-991

- src/ggrc/assets/stylesheets/_header.scss
tasks counter fix when there is no tasks
> tasks counter fix when there is no tasks

- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/mustache/events/object_list.mustache
- src/ggrc/assets/mustache/people/object_list.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/roles/object_list.mustache
- src/ggrc/assets/stylesheets/_widget.scss
Styled all admin dashboard widgets
> Admin dash styling

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/custom_attributes/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/stylesheets/_widget.scss
custom attributes styling in info widget
> custom attributes styling in info widget

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc_workflows/assets/mustache/base_objects/approval_link.mustache
Buttons not yet submitting though. Working on that next.
> Buttons now showing up when they should and not when they shouldn't.

- src/ggrc/assets/javascripts/dashboard.js
- src/ggrc/assets/mustache/custom_attribute_definitions/subtree.mustache
- src/ggrc/assets/mustache/custom_attribute_definitions/tree.mustache
- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/stylesheets/_modal.scss
- src/ggrc/assets/stylesheets/_widget.scss
custom attributes styled, info widget advanced fix, object_area height fix
> custom attributes styled, info widget advanced fix, object_area height fix

- src/ggrc/assets/mustache/audits/tree.mustache
- src/ggrc/assets/mustache/base_objects/general_info.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/documents/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/requests/info.mustache
- src/ggrc/assets/mustache/responses/info.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_setup.scss
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
CORE-1024 status and state coloring
> CORE-1024 status and state coloring

- src/ggrc/models/mixins.py
db.session.commit() caused the slug field to not be properly set in
some cases.
> CORE-1030 Objects cannot be created

- src/ggrc/assets/mustache/dashboard/info/my_audits.mustache
CORE-1020 css fixes for dashboard widgets
> CORE-1020 css fixes for dashboard widgets

- src/ggrc/assets/mustache/dashboard/object_widget.mustache
CORE-1050 temporary hide column options in widget header
> CORE-1050 temporary hide column options in widget header

- src/ggrc/assets/mustache/dashboard/lhn.mustache
CORE-1043 lhn hierarchy update
> CORE-1043 lhn hierarchy update

- src/ggrc/assets/mustache/audits/tree_footer.mustache
- src/ggrc/assets/mustache/base_objects/tree_footer.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/controls/tree_footer.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/directives/tree_footer.mustache
- src/ggrc/assets/mustache/documents/tree.mustache
- src/ggrc/assets/mustache/documents/tree_footer.mustache
- src/ggrc/assets/mustache/meetings/tree_footer.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/objectives/tree_footer.mustache
- src/ggrc/assets/mustache/people/tree_footer.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc/assets/mustache/sections/tree_footer.mustache
- src/ggrc/assets/mustache/systems/tree_footer.mustache
CORE-1044 removed 'No mapped' message
> CORE-1044 removed 'No mapped' message

- src/ggrc/assets/mustache/policies/modal_content.mustache
Just a typo created all the mess.
> Policy modal, state dropdown issue fixed, CORE-1100

- src/ggrc/assets/mustache/search/advanced_search_option_items.mustache
- src/ggrc/assets/mustache/search/advanced_search_people_items.mustache
> Advanced search display fix, CORE-1119

- src/ggrc/assets/javascripts/controllers/info_widget_controller.js
CORE-1062 typo fixed on dashboard in error message text.
> CORE-1062 typo fixed

- src/ggrc/assets/mustache/clauses/modal_content.mustache
- src/ggrc/assets/mustache/contracts/modal_content.mustache
- src/ggrc/assets/mustache/controls/modal_content.mustache
- src/ggrc/assets/mustache/data_assets/modal_content.mustache
- src/ggrc/assets/mustache/facilities/modal_content.mustache
- src/ggrc/assets/mustache/markets/modal_content.mustache
- src/ggrc/assets/mustache/objectives/modal_content.mustache
- src/ggrc/assets/mustache/org_groups/modal_content.mustache
- src/ggrc/assets/mustache/people/owners_modal_connector.mustache
- src/ggrc/assets/mustache/policies/modal_content.mustache
- src/ggrc/assets/mustache/processes/modal_content.mustache
- src/ggrc/assets/mustache/products/modal_content.mustache
- src/ggrc/assets/mustache/projects/modal_content.mustache
- src/ggrc/assets/mustache/regulations/modal_content.mustache
- src/ggrc/assets/mustache/sections/modal_content.mustache
- src/ggrc/assets/mustache/standards/modal_content.mustache
- src/ggrc/assets/mustache/systems/modal_content.mustache
- src/ggrc/assets/mustache/vendors/modal_content.mustache
- src/ggrc/assets/stylesheets/_common.scss
CORE-1064 modal add owner styling
> CORE-1064 modal add owner styling

- src/ggrc/assets/stylesheets/_modal.scss
Moved the line below the button at @prasannav7's [request](https://reciprocitylabs.atlassian.net/browse/CORE-1031).
> Move search modal line below button per CORE-1031 fix

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/audits/tree.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/people/popover.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/requests/tree.mustache
Add icons in inner tree-view only.
> Add icons in inner tree only, CORE-1106

- src/ggrc/assets/mustache/base_objects/page_header.mustache
- src/ggrc/assets/mustache/people/page_header.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/programs/page_header.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_header.scss
> CORE-1149 header icon fix

- provision/roles/ggrc/tasks/main.yml
- provision/roles/ggrc/vars/main.yml
this is a workaround for downgrading gems.
> downgrading ruby gems because of performance issues

- src/ggrc/assets/mustache/search/advanced_search_base_modal.mustache
- src/ggrc/assets/stylesheets/_modal.scss
- src/ggrc/assets/stylesheets/_tree.scss
CORE-1146 search results styling in modals
> CORE-1146 search results styling in modals

- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/js_specs/models/cacheable_spec.js
- src/ggrc/assets/js_specs/spec_helpers.js
> Test coverage around Cacheable model with breakage notes

- src/ggrc/assets/mustache/custom_attributes/info.mustache
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
CORE-1108 custom attributes title as checkbox label
> CORE-1108 custom attributes title as checkbox label

- src/ggrc/assets/stylesheets/_modal.scss
CORE-1114 mapping modal object checkbox fix
> CORE-1114 mapping modal object checkbox fix

- src/ggrc/assets/mustache/modals/confirm_buttons.mustache
- src/ggrc/assets/mustache/modals/done_buttons.mustache
- src/ggrc/assets/mustache/modals/save_cancel_buttons.mustache
- src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
- src/ggrc/assets/mustache/selectors/base_modal.mustache
- src/ggrc/assets/mustache/selectors/multitype_base_modal.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/audit_modal.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/base_modal.mustache
- src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_base_modal.mustache
- src/ggrc_workflows/assets/mustache/selectors/object_selector_base_modal.mustache
CORE-1201 modal buttons color change
> CORE-1201 modal buttons color change

- src/ggrc/assets/mustache/audits/modal_content.mustache
CORE-1142 icons removed from labels
> CORE-1142 icons removed from labels

- src/ggrc/assets/mustache/audits/extended_info.mustache
- src/ggrc/assets/mustache/base_objects/extended_info.mustache
- src/ggrc/assets/mustache/programs/extended_info.mustache
- src/ggrc_workflows/assets/mustache/tasks/extended_info.mustache
- src/ggrc_workflows/assets/mustache/workflows/extended_info.mustache
CORE-1175 arrow removed from LHN popover
> CORE-1175 arrow removed from LHN popover

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/responses/modal_content.mustache
Added mapped name for Person object in response modal.
> Hotfix/add mapped person name,  core 1151

- src/ggrc/assets/mustache/documents/pbc_tree.mustache
CORE-1155 adding URL for attached documents
> CORE-1155 adding URL for attached documents

- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/mustache/people/object_list.mustache
CORE-1116 adding new column for people widget
> CORE-1116 adding new column for people widget

- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/views/__init__.py
> Break up the non-production warning into two lines

- src/ggrc/assets/mustache/dashboard/object_widget.mustache
CORE-1217 tasks header column fix
> CORE-1217 tasks header column fix

- src/ggrc/assets/javascripts/apps/dashboard.js
- src/ggrc/assets/mustache/dashboard/object_widget.mustache
CC @vladan-mitevski re. the temporarily hidden code.
> Audit list column title rename Owner -> Asignee. Fix CORE-1278.

- src/ggrc/assets/stylesheets/_pin.scss
CORE-1252 removed bottom border
> CORE-1252 removed bottom border

- src/ggrc/assets/mustache/events/object_list.mustache
- src/ggrc/assets/mustache/people/object_list.mustache
- src/ggrc/assets/stylesheets/_tree.scss
CORE-1094 widget footers fixed
> CORE-1094 widget footers fixed

- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
Sometimes it stuck out a bit after loading, sometimes it didn't. I've seen it before even though I wasn't able to replicate right now. This will make sure that can't happen.
> make sure sure LHN is hidden when it's supposed to be

- src/ggrc_workflows/assets/assets.yaml
- src/ggrc_workflows/assets/mustache/cycles/info.mustache
-Added new cycle/info.mustache
> Added proper file for cycle/workflow instance, CORE-1256

- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/requests/tree.mustache
CORE-1262 request items counter
> CORE-1262 request items counter

- src/ggrc/assets/mustache/base_objects/tier2_content.mustache
- src/ggrc/assets/mustache/controls/tier2_content.mustache
- src/ggrc/assets/mustache/directives/tier2_content.mustache
- src/ggrc/assets/mustache/documents/tier2_content.mustache
- src/ggrc/assets/mustache/objectives/tier2_content.mustache
- src/ggrc/assets/mustache/people/tier2_content.mustache
- src/ggrc/assets/mustache/programs/tier2_content.mustache
- src/ggrc/assets/mustache/sections/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
There is still a chance for false positives, but this was the best I could do with just mustache.
> Don't show cog icon if nothing in dropdown

- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_setup.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache
CORE-1153 status color updates
> CORE-1153 status color updates

- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache
CORE-1220 fixed gdrive label showing in info and modals
> CORE-1220 fixed gdrive label showing in info and modals

- src/ggrc_workflows/assets/mustache/task_groups/info.mustache
CORE-1253 removed state from setup tab
> CORE-1253 removed state from setup tab

- src/ggrc/assets/mustache/modals/confirm_buttons.mustache
CORE-1223 discard modal changes buttons fix
> CORE-1223 discard modal changes buttons fix

- src/ggrc/assets/mustache/audits/tree.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/documents/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
CORE-1128 utility links improvements
> CORE-1128 utility links improvements

- src/ggrc/assets/mustache/audits/modal_content.mustache
> Add gDrive folder picker to Audit modals

- src/ggrc/assets/mustache/base_objects/tier2_content.mustache
- src/ggrc/assets/mustache/controls/tier2_content.mustache
- src/ggrc/assets/mustache/directives/tier2_content.mustache
- src/ggrc/assets/mustache/documents/tier2_content.mustache
- src/ggrc/assets/mustache/objectives/tier2_content.mustache
- src/ggrc/assets/mustache/people/tier2_content.mustache
- src/ggrc/assets/mustache/programs/tier2_content.mustache
- src/ggrc/assets/mustache/sections/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
Reverts reciprocity/ggrc-core#2356
> Revert "Reverting changes by pull request 2353, CORE-1310"

- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
- src/ggrc/assets/javascripts/models/display_prefs.js
This fixes a bunch of script errors for users with no access.
> Lhn fixes for no access users

- src/ggrc/assets/mustache/base_objects/tier2_content.mustache
- src/ggrc/assets/mustache/controls/tier2_content.mustache
- src/ggrc/assets/mustache/directives/tier2_content.mustache
- src/ggrc/assets/mustache/objectives/tier2_content.mustache
- src/ggrc/assets/mustache/people/tier2_content.mustache
- src/ggrc/assets/mustache/programs/tier2_content.mustache
- src/ggrc/assets/mustache/sections/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
@Smotko now all good?
I'm assuming the `_N_context` thing  is zero indexed
> #if is not optional for CORE-1199

- src/ggrc/assets/stylesheets/_widget.scss
CORE-1317 utility links fix vertical align
> CORE-1317 utility links fix vertical align

- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
instance does not have lenght.
> CORE-1187 - add tasks icon and count

- src/ggrc/assets/mustache/dashboard/info/my_tasks.mustache
CORE-1135 my tasks gear button styling
> CORE-1135 my tasks gear button styling

- src/ggrc/assets/mustache/base_objects/contacts.mustache
- src/ggrc/assets/stylesheets/_common.scss
CORE-1178 multiple owner list fix spacing
> CORE-1178 multiple owner list fix spacing

- src/ggrc/assets/stylesheets/_pin.scss
- src/ggrc/assets/stylesheets/_widget.scss
> CORE-1264 help icon fix

- src/ggrc/assets/javascripts/apps/quick_search.js
- src/ggrc/assets/javascripts/controllers/recently_viewed_controller.js
- src/ggrc/assets/mustache/dashboard/lhn.mustache
- src/ggrc/assets/mustache/dashboard/recently_viewed_list.mustache
-Initialized recently-viewed-controller
-Changed the icon color from black -> color, because black icons don't load for person model type.
> Added recently viewed object to LHN, CORE-1049

- src/ggrc/assets/stylesheets/_lhs.scss
CORE-1060 popover items fix styling
> CORE-1060 popover items fix styling

- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
@UDuong found a bug, we fixed it. Happy testing.
> if no mouse position, don't close lhn

- src/ggrc/assets/stylesheets/_common.scss
CORE-1063 select field height fix
> CORE-1063 select field height fix

- src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
- src/ggrc/assets/stylesheets/_setup.scss
pending=gray, inprogress=orange, finished=blue, verified=green
> Fixed coloring for stages

- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/templates/welcome/index.haml
> CORE-1270 welcome page fixes

- .gitignore
- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
Fixes menu toggling, for some unknown reason `{window} click` was triggered on `click` event. We should figure out why and fix it.
> CORE-1342 

- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
@zidarsk8 I think your code for highlighting the default item from a tree view is messing with mine.
Where is your code that does this?
> CORE-1282: highlight response after creating

- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
If there is no object associated, still show the start and end dates for task.
> Added task start-end date, CORE-1357

- src/ggrc_workflows/assets/javascripts/controllers/dashboard_page.js
- src/ggrc_workflows/assets/mustache/dashboard/widgets.mustache
This issue was caused by my refactoring yesterday, but testers haven't created a story for it yet
> Fix script error on admin dashboard

- src/ggrc/assets/mustache/people/tier2_content.mustache
- src/ggrc/assets/mustache/search/advanced_search_people_items.mustache
- src/ggrc_workflows/assets/mustache/selectors/object_selector_base_modal.mustache
- src/ggrc_workflows/assets/mustache/wf_people/people_items.mustache
CORE-1337 fixing tier2 info in mapping selector
> CORE-1337 fixing tier2 info in mapping selector

- src/ggrc/assets/mustache/dashboard/object_widget.mustache
- src/ggrc/assets/mustache/requests/tree.mustache
CORE-1354 fixing widget header columns and one line
> CORE-1354 fixing widget header columns and one line

- src/ggrc/assets/mustache/responses/info.mustache
- src/ggrc/assets/mustache/responses/modal_content.mustache
CORE-1318 removed assignee from response
> CORE-1318 removed assignee from response

- src/ggrc/assets/mustache/responses/modal_content.mustache
CORE-1269 fixing attachments in response modal
> CORE-1269 fixing attachments in response modal

- src/ggrc/assets/stylesheets/_tree.scss
fixing widget list bottom spacing
> fixing widget list bottom spacing

- src/ggrc/assets/mustache/base_objects/open_close.mustache
> CORE-1343 status coloring fix

- src/ggrc/assets/mustache/search/advanced_search_option_items.mustache
- src/ggrc/assets/mustache/search/advanced_search_people_items.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_widget.scss
CORE-1321 adding arrow to advanced search list
> CORE-1321 adding arrow to advanced search list

- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache
> people list go-to link fixed

- src/ggrc/assets/javascripts/generated/ggrc_filter_query_parser.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/parser/parser.pegjs
- filter by long title works
- use momentjs to allow MM/DD/YYYY format
- the filter keys are now case insensitive.
> fix date and title

- src/ggrc_workflows/assets/mustache/cycle_task_entries/tree.mustache
CORE-1373 comments status colors fix
> CORE-1373 comments status colors fix

- src/ggrc/assets/stylesheets/_widget.scss
fixing filter expression icon position
> fixing filter expression icon position

- src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache
CORE-1397 functionality removed for deleted objects
> CORE-1397 functionality removed for deleted objects

- src/ggrc/assets/javascripts/controllers/tree_filter_controller.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
* green expression icon on "order by" statement - order by title 
* don't throw a type error if trying to filter a huge list before it's even populated.
> some minor filter fixes

- src/ggrc/assets/mustache/base_objects/open_close.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_setup.scss
- src/ggrc/assets/vendor/javascripts/can.jquery.js
CORE-1400 fixing status colors
> CORE-1400 fixing status colors

- src/ggrc/assets/mustache/audits/tree_header.mustache
- src/ggrc/assets/mustache/base_objects/tree_header.mustache
- src/ggrc/assets/mustache/people/tree_header.mustache
- src/ggrc/assets/mustache/requests/tree_header.mustache
- src/ggrc/assets/vendor/javascripts/stickyfill.js
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree_header.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_header.mustache
- src/ggrc_workflows/assets/mustache/cycles/tree_header.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree_header.mustache
the filter element does not have a parent when. Not sure if the same can happen to header element but for now, this works
> Fix script error on object deletion

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/vendor/javascripts/lodash.js
@Smotko I made a pull request.
> lodash makes life easier

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/models/mappings.js
Yay, First PR for the Grapes release!
Please ignore the fact that the branch name is wrong. It should be `feature/core-1355` not `feature/core-1347`
> CORE-1355 Show Controls in Audits

- src/ggrc/assets/mustache/controls/tree_footer.mustache
- src/ggrc/assets/mustache/objectives/tree_footer.mustache
- src/ggrc/assets/mustache/systems/tree_footer.mustache
> Moved map tooltip for controls, objectives, systems

- src/ggrc/assets/mustache/people/object_list.mustache
> Display "No Access" in Admin People list when no Authorizations

- src/ggrc/assets/stylesheets/_modal.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/option_column.mustache
> Make the role label a proper label in User Role Assignments modal

- doc/developer_guide.md
Thanks @Smotko. CC @prasannav7.
> Add Anze' cookbook recipes

- src/ggrc_workflows/models/task_group.py
cloned task groups need context
> CORE-1472 - fix SyntaxError

- src/ggrc/assets/mustache/base_objects/open_close.mustache
- src/ggrc_workflows/models/workflow.py
This solves multiple stories:
CORE-1343
CORE-1257
CORE-1377
CORE-499
> Properly color status label for objects

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/builder/json.py
- src/ggrc/converters/base_row.py
- src/ggrc/migrations/versions/20150311102738_4ceda387a468_constrains_object_owners.py
- src/ggrc/models/object_owner.py
I based my migration on this article, since we needed a way to to get rid of the duplicates, and I wanted to avoid making a second "fake" table:
* http://www.mikeperham.com/2012/03/02/deleting-duplicate-rows-in-mysql/
* http://www.pythian.com/blog/trivial-mysql-variable-of-the-day/
> CORE-1470: Owner duplication and error while updating control

- src/ggrc/assets/mustache/requests/tree.mustache
CORE-1478 changing icon based on request type
> CORE-1478 changing icon based on request type

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/controllers/modal_selector_controller.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
This PR improves our deep linking functionality. The idea is that adding something from a modal updates the hash fragment and navigating around tree views does the same.
Tickets: CORE-1078, CORE-1421, CORE-1496
> Deep linking

- src/ggrc/assets/javascripts/apps/business_objects.js
The widget configs are a mess. This is an attempt to make them sliiiiightly better.
> Make widget configs a bit better

- src/ggrc_workflows/assets/mustache/dashboard/info/my_audit_requests.mustache
- src/ggrc_workflows/assets/mustache/dashboard/info/my_tasks.mustache
- src/ggrc_workflows/assets/mustache/dashboard/info/workflow_progress.mustache
CORE-1325 changing message body
> CORE-1325 changing message body

- src/ggrc/assets/mustache/directives/tree.mustache
> CORE-1532 Directives don't show child lists

- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
I don't even know what to say. This was almost as terrible as the retina scrolling bug.
> CORE-1461: LHN should render correctly despite browser rendering optimisations

- src/ggrc/assets/stylesheets/_pin.scss
- src/ggrc/assets/stylesheets/_styleguide.scss
- src/ggrc/static/mockups/js/audit-revamp/info.js
- src/ggrc/static/mockups/mustache/audit-revamp/control-assessments.mustache
- src/ggrc/static/mockups/mustache/audit-revamp/issues.mustache
- src/ggrc/templates/mockups/audit-revamp/info.html
- src/ggrc/templates/mockups/audit-revamp/issues.html
control assessment improvement and automation mockups
> control assessment improvement and automation mockups

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/controllers/modal_selector_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
This PR also includes a fix for Add Selected button in mappings modal
> Add a CA to the CA list on Audit page

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/models/mappings.js
- src/ggrc/migrations/versions/20150321212421_56bda17c92ee_clean_responses_mapped_to_responses.py
This seems to work, but I'm suspicious of my fix in `mappings.js`. I'm not sure if it breaks anything, but it looks like it might. However, I wasn't able to find any instances where it would.
Also if this fix is in fact correct, would it make sense to remove the lines further down that look like `related_X_responses: ...`?
> CORE-1381: users shouldn't map responses to responses

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/models/mappings.js
This reverts commit 2c17e3bf0f8eab6ea4dde2ac1157e61256f68fee.
> Revert "remove dead related_responses code"

- src/ggrc/assets/stylesheets/_styleguide.scss
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc/static/mockups/js/audit-revamp/info.js
- src/ggrc/static/mockups/mustache/audit-revamp/control-assessments.mustache
- src/ggrc/templates/mockups/audit-revamp/info.html
CORE-1549 replacing icons with dropdown
> CORE-1549 replacing icons with dropdown

- doc/javascript_conventions.md
@hyperNURb Feel free to improve this document.
> Adding Dan's coding styles to the docs

- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/plugins/canjs_extensions.js
- src/ggrc/assets/mustache/base_objects/info-pin.mustache
- src/ggrc/assets/stylesheets/_tree.scss
CORE-1563 ability for closing info pane
> CORE-1563 ability for closing info pane

- src/ggrc/assets/stylesheets/_common.scss
CORE-1584 fix icons backround position
> fix icons backround position

- src/ggrc/static/mockups/js/audit-3.0/info.js
- src/ggrc/static/mockups/mustache/audit-3.0/control-assessments.mustache
- src/ggrc/templates/mockups/audit-3.0/info.html
CORE-1575 adding interim step for generating assessments
> CORE-1575 adding interim step for generating assessments

- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_styleguide.scss
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc/static/mockups/js/audit-3.0/info.js
- src/ggrc/static/mockups/mustache/audit-3.0/control-assessments.mustache
- src/ggrc/static/mockups/mustache/audit-3.0/info.mustache
- src/ggrc/templates/mockups/audit-3.0/info.html
> assessments improvements

- src/ggrc/assets/stylesheets/_widget.scss
> CORE-1628 fixing spacing

- src/ggrc/assets/javascripts/controllers/modal_selector_controller.js
- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
- src/ggrc/assets/javascripts/models/join_models.js
- src/ggrc/assets/javascripts/models/mappers.js
- src/ggrc/assets/javascripts/models/mappings.js
- src/ggrc/assets/javascripts/models/refresh_queue.js
- src/ggrc/assets/mustache/search/advanced_search_option_items.mustache
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_option_items.mustache
- src/ggrc_workflows/models/cycle_task_group_object.py
This should reduce the number of requests when mapping objects. In my tests it reduces the number of requests when mapping 20 objects from ~2000 to ~25.
> CORE-1001 Decreases the number of requests when mapping

- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/control_assessments/info.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/objectives/info.mustache
- src/ggrc/assets/mustache/policies/info.mustache
- src/ggrc/assets/mustache/processes/info.mustache
- src/ggrc/assets/mustache/products/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/requests/info.mustache
- src/ggrc/assets/mustache/responses/info.mustache
- src/ggrc/assets/mustache/sections/info.mustache
- src/ggrc/assets/mustache/systems/info.mustache
- src/ggrc/assets/stylesheets/_tree.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/info.mustache
- src/ggrc_workflows/assets/mustache/cycles/info.mustache
- src/ggrc_workflows/assets/mustache/task_groups/info.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tier2_content.mustache
- src/ggrc_workflows/assets/mustache/tasks/info.mustache
CORE-1640 moving up gear icon inside info pane
> CORE-1640 moving up gear icon inside info pane

- src/ggrc/assets/javascripts/controllers/assessment_generator.js
- src/ggrc/assets/javascripts/mustache_helper.js
@Smotko asked me if I could fix it for assesments generator as well, because we had simillar issues and _search_ would help us in that case.
> CORE-1601: Fixes generating titles for assesments and audits.

- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_styleguide.scss
- src/ggrc/static/mockups/js/audit-3.0/info.js
- src/ggrc/static/mockups/mustache/audit-3.0/control-assessments.mustache
- src/ggrc/templates/mockups/audit-3.0/info.html
CORE-1663 hf mockups improvements
> CORE-1663 hf mockups improvements

- src/ggrc/assets/stylesheets/_widget.scss
making widget header icons less gray
> making widget header icons less gray

- src/ggrc/assets/mustache/roles/object_list.mustache
roles widget items fix structure
> CORE-1667: Roles widget items fix structure

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/control_assessments/info.mustache
- src/ggrc/assets/mustache/requests/tree_header.mustache
This also adds the ability to map control assessments to requests.
> CORE-1686 Fix Audit Request to Control mapping

- src/ggrc/assets/mustache/base_objects/description.mustache
- src/ggrc/assets/mustache/base_objects/notes_and_code.mustache
- src/ggrc/assets/mustache/base_objects/test_plan.mustache
- src/ggrc/assets/mustache/control_assessments/info.mustache
CORE-1639 fixing styling for inline notification message
> CORE-1639 fixing styling for inline notification message

- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
CORE-756 adding hide functionality to workflow folder
> CORE-756 adding hide functionality to workflow folder

- src/ggrc/assets/mustache/dashboard/internav_list.mustache
prevent showing close icon for non closing nav elements
> CORE-747 Prevent showing close icon for non closing nav elements

- src/ggrc/assets/mustache/base_objects/states.mustache
- src/ggrc/assets/stylesheets/_popover.scss
- src/ggrc/assets/stylesheets/_widget.scss
CORE-1680 styling popover for tasks list
> CORE-1680 styling popover for tasks list

- src/tests/ggrc/__init__.py
Running tests on travis sometimes fails because the sorted tables aren't
sorted by foreign key constraints, so this is a work around to make sure
all tables get propperly cleared.
> CORE-1705 Fix tests on travis. - grapes

- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
- src/ggrc/assets/stylesheets/_lhs.scss
CORE-1090 improved styling for reset LHN search trigger
> CORE-1090 improved styling for reset LHN search trigger

- src/ggrc/assets/javascripts/dashboard.js
Moved PR to release branch as per @Smotko
> CORE-1671 Don't error out when browser submits import form

- src/ggrc/assets/stylesheets/_modal.scss
removed redundant link from selector modal list
> removed redundant link from selector modal list

- src/ggrc_workflows/notification/notification_handler.py
- Fix adding notifications for existing workflows.
- Make sure that all new notification objecs are added in the add_notif
function. This will be useful for automatically duplicating
notification objecs for instant notifications.
> Clean up notification handler

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/models/mappings.js
This is the first step of refactoring mappings - having mappings.js and business_objects.js better formatted will help with the refactoring process. 
I want to avoid having a huge commit, so CORE-1603 will be a bunch of smaller ones. This is the first of many.
> CORE-1603 Start refactoring mappings

- src/ggrc/assets/mustache/clauses/modal_content.mustache
- src/ggrc/migrations/versions/20150504125712_41bd73114fd9_add_date_fields_to_clause.py
- src/ggrc/models/section.py
Missing fields are added into modal. Check and add respective fields into DB.
Fields that are added:
- Clause URL
- Effective date
- Stop date
> CORE-1719 Added missing fields in Clauses modal

- src/ggrc/assets/javascripts/models/mappings.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/models/control.py
This adds the fixes made for 0.9.1 to 0.9.2-Grapes
> Feature/merge 0.9.1 to 0.9.2

- src/ggrc_workflows/notification/data_handler.py
- src/ggrc_workflows/templates/notifications/email_digest_content.html
Some minor fixes for digest notifications
> CORE-1779 Modify digest notifications

- src/dev-requirements.txt
- src/ggrc/app.py
- src/ggrc/settings/development.py
Add the flask extension to help with development and profiling.
> QUICK-FIX Add flask-debugtoolbar to dev enviroment

- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc_workflows/assets/javascripts/controllers/dashboard_page.js
- src/ggrc_workflows/assets/mustache/dashboard/info/workflow_progress.mustache
- src/ggrc_workflows/assets/mustache/dashboard/widgets.mustache
My Workflows widget from My Work info is now moved into widget below and
it's now inside 3rd tab.
Resolve: CORE-1781
> CORE-1781: Move 'My Workflows' to be 3rd tab

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/dashboard.js
- src/ggrc/assets/mustache/base_objects/page_header.mustache
- src/ggrc/assets/stylesheets/_header.scss
- src/ggrc/templates/base_objects/_page_header.haml
Real-time email can be checked only when Dialy email is selected
> CORE-1762 Fix notification checkbox behaviour

- src/ggrc/assets/mustache/base_objects/page_header.mustache
- src/ggrc/assets/stylesheets/_header.scss
- src/ggrc/templates/base_objects/_page_header.haml
Real time message is moved bottom and indented little bit. It it
disabled untill 'Daily email digest' checkbox is checked. Only than real
time message checkbox can be clickable.
JS if working already but partialy. I've tried to fix it but without
success. Need someone else to take a look at this and solve JS part of
the work.
Resolve: CORE-1762
> CORE-1762: Update notification messages from user dropdown menu

- src/ggrc/assets/stylesheets/_setup.scss
It used to be the same as draft state, but it's supposed to be yellow.
> CORE-1679 Fix declined state indicators' color

- src/ggrc_workflows/templates/unstarted_cycles.haml
- src/ggrc_workflows/views/__init__.py
The new view is available @ /admin/unstarted_cycles
> CORE-1807 Add view to manually start unstarted cycles

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
Info pin is not loaded on import pages, which caused a script error.
> CORE-1810 Fix script error on import pages

- src/ggrc_workflows/views/__init__.py
Nightly cron jobs shoud run all jobs even if previous jobs fail.
- clean up imports
- add email notification for any failed nightly cron jobs
- add logging for the same errors
> QUICK-FIX Fix nightly_cron_endpoint

- src/ggrc/templates/layouts/dashboard.haml
This makes sure the checkbox is never checked
> QUICK-FIX Fix email now checkbox

- src/ggrc/assets/stylesheets/_popover.scss
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc/static/mockups/js/common.js
- src/ggrc/static/mockups/js/reporting.js
- src/ggrc/static/mockups/mustache/reporting.mustache
Reporting prototype is now fully improved
> CORE-1803: Improve reporting prototype

- src/ggrc_workflows/assets/mustache/cycle_task_entries/tree_footer.mustache
Add missing Add-Comment button to tree footer for cycle_task_entries
> CORE-1787 Fix task-comment issue

- src/ggrc/services/common.py
I just want to figure out if our benchmark request time will match the time in the trace.
As an example, [this trace](https://console.developers.google.com/project/grc-test/clouddev/trace/661b0f6fbdade8fc59815d32644877e4#TIMELINE) is 3s, but [our logs](https://console.developers.google.com/project/grc-test/logs?expandAll=true&filters=request_id:5560b4d400ff03a5452c40f0a00001737e6772632d74657374000131000100&key1=default&key2=1&service=appengine.googleapis.com&logName=appengine.googleapis.com%2Frequest_log&minLogLevel=0&timezone=Europe%2FParis&lastVisibleOffset=5560b4d400ff03a5452c40f0a00001737e6772632d74657374000131000100&lastVisibleTimestampNanos=1432401111257000000) only log ~ 0.27s. The dispatch request log should in theory match 3s.
> QUICK-FIX Benchmark dispatch request

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/requests/modal_content.mustache
> CORE-1750 Fix script error when creating a request from CA

- src/ggrc_workflows/notification/data_handler.py
- Make sure we don't have any extra slashes in the url.
- Move get_url functions together
- Remove slash at the end of cycle_task_group_id
> CORE-1861 Add propper url join for notifications

- src/ggrc_workflows/templates/notifications/email_digest_content.html
- Remove first paragraph.
- make sure all objects have sigular and plural form.
> CORE-1880 Update digest email template

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/converters/__init__.py
- src/ggrc/utils.py
- src/tests/ggrc/test_utils.py
- Add mapping rules to python utils that should be the same as in business_object.js
- Add tests for those mappings
- Fix the erros found by the test: Objective should not have ControlAssesment mapping
> QUICK-FIX Add mapping rules to the back-end

- doc/deployment.md
- src/ggrc/views/__init__.py
Pull request submitted for information clean up.
> CORE-1898 cleanup information from repository

- src/ggrc/models/relationship.py
This allows for easy lookup of relationships between two known objects without
respect to the direction of the mapping.
I'm using this in several places in my automapping code but I decided to put it 
into a separate pull request since @zidarsk8 requires it for his work too. 
This is my first PR touching python code so please be harsh :smile:
> QUICK-FIX Add find_related to the Relationship model

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/login/appengine.py
- src/ggrc/login/noop.py
- src/ggrc/templates/layouts/dashboard.haml
- src/ggrc/templates/welcome/index.haml
- src/ggrc/utils.py
- src/ggrc/views/__init__.py
@sasmita514 can you make sure your code works with this change?
> CORE-1897 Fix dashboard blank screen

- src/ggrc/assets/javascripts/generated/ggrc_filter_query_parser.js
- src/ggrc/assets/js_specs/generated/ggrc_filter_query_parser_spec.js
- src/parser/generate_parser.js
- src/parser/parser.pegjs
Make filter queris work with "!~ some random text"
> CORE-1504 add exclude text searh to filters

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc_workflows/assets/javascripts/controllers/dashboard_page.js
- src/ggrc_workflows/assets/mustache/dashboard/widgets.mustache
-Remove my-task and audit-requests from my-work/info tab
-Add audit-requests as a tab in my-work view
> CORE- 1985 Move audit-requests to my-work view

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
And in process replace the ad-hoc jQuery with computed parameters for the templates.
> CORE-1999 Right-align nested tree view nodes

- src/ggrc/assets/mustache/base_objects/page_header.mustache
- src/ggrc/assets/mustache/dashboard/info/get_started.mustache
- src/ggrc/templates/base_objects/_page_header.haml
- Add new title menu All Objects
- Add button All Objects from my-work/info page
- Change title Object Browser to All Objects
> CORE-20001 Add access to All Objects from title- menu, info/button & dropdown-menu

- src/ggrc_basic_permissions/converters/handlers.py
Use correct values for Program reader, editor and owner when exporting
Programs.
> QUICK-FIX Fix program export

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This workaround disables lazy rendering whenever the tree view controller has a corresponding element that is not attached to DOM. The net effect is no lazy rendering in info pin.
The underlying problem is that tree view controller cannot find the scroll element (info pin) while initializing since there is no info pin yet. I find this solution better than a soup of deferreds and timeouts. 
For a clean solution we need a major refactoring of the tree view. Some day.
> CORE-2010 & CORE-2019: Disable lazy rendering in info pin

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers.py
- src/ggrc_basic_permissions/converters/handlers.py
- src/tests/ggrc/converters/test_csvs/full_good_import_no_warnings.csv
- src/tests/ggrc/converters/test_import_comprehensive.py
This is one PR of many for the issue CORE-2012.
This is just to unblock the tester. Csv imports should not throw script errors no matter how bad the data is.
> CORE-2012 Fail gracefully on bad csv files

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/requests/tree.mustache
- src/ggrc/assets/mustache/requests/tree_header.mustache
Update attribute list for request model
Update request tree-view-header and tree-view
Fix second-tier display
> CORE-1989, Fix audit-request tree view

- src/ggrc/assets/javascripts/models/cacheable.js
And add support for "modified date" because it is mentioned in the help.
> CORE-1661 Fix tree view filtering by date

- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/js_specs/models/cacheable_spec.js
We will need this to implement filtering by owner properly. User will expect that an item matches if **any** of it's owners match. So the deep property won't be `owners.0.name|email` but rather `owners.GET_ALL.name|email` and this PR adds the needed support in `get_deep_property`.
> QUICK-FIX Add multi-get support to get_deep_property

- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
- src/ggrc/converters/base_block.py
- src/ggrc/models/reflection.py
- src/ggrc/views/converters.py
- src/tests/ggrc/converters/test_export_csv.py
* Add select all/none links
* Fix exports with no selected attributes to export an empty block.
> CORE-2114 Fix attribute selection on export

- src/ggrc/assets/mustache/sections/tree_add_item.mustache
> CORE-1943 Fix Create Section/Clause issue for Program Reader role

- src/ggrc/assets/mustache/audits/tree_add_item.mustache
Now that anyone has create permissions we need to check for update on
parent instance
> CORE-1956 Fix create Audit button for Creator

- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/converters/__init__.py
- src/ggrc/models/reflection.py
- Remove Option object since it's not a user facing object.
- Add user_role to list of known columns.
> QUICK-FIX Fix import export lists

- src/ggrc/converters/base.py
- Add headers to data grid.
- Make sure something gets exported even if one of the objects (not anchor object) does not return anything.
> CORE-2127 Fix data grid export

- src/ggrc/assets/javascripts/controllers/assessment_generator.js
This changes the way Control Assessments are generated. Instead of throwing 600 requests at the server and getting timeouts, we now create the next Control Assessment only after the previous one has been successfully created.
> CORE-1859 Make sure CA generation is daisy chained

- src/ggrc/assets/javascripts/controllers/tree_filter_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
This is temporary fix, we should use attributes for this in future.
> CORE-2104 Add filtering by request object

- src/ggrc_workflows/converters/handlers.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/relationship_helper.py
- src/tests/ggrc_workflows/converters/test_workflow_export_csv.py
Parts of the ticket added in this PR
* cycle - cycle task group
* cycle task group - cycle task
* cycle task - cycle task object
> CORE-2182 Add extra mapping filters support

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
- src/tests/ggrc_workflows/workflow_cycle_calculator/test_monthly_workflow.py
Fix cycle task editing validation; Mark cycle as finished if all cycle tasks get deleted; Fix calculation to only take into account valid cycles
> QUICK-FIX Fix cycle task validation, cycle ending, calculations involving partial cycles

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/assets/mustache/cycle_task_entries/tree_add_item.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_entries/tree_footer.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/tree.mustache
- src/ggrc_workflows/assets/mustache/dashboard/info/my_tasks.mustache
This fixes CORE-2235 and CORE-2227 as well.
> CORE-2238 Add frontend checks for Workflow state changes

- src/ggrc/converters/handlers.py
- src/ggrc/models/relationship_helper.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_basic_permissions/models.py
- src/ggrc_risk_assessments/__init__.py
- src/ggrc_risk_assessments/models/relationship_helper.py
This fixes the "relevant to person" part of CORE-2182.
I covered `WithContact`, `ObjectOwner`, `UserRole`, `ra_counsel`, `ra_manager` and `ObjectPerson` in this PR.
Worflow "No Access" users also work but I haven't had the time to figure out which part of the existing code grabs them. 
This may conflict with #3036 - I'll fix the potential conflict when one of them is merged.
> CORE-2182 relevant to person

- src/ggrc/services/common.py
Also fixes CORE-2236, CORE-2256, CORE-2258
> CORE-2264 Add test for creator's own relationships

- src/ggrc/models/relationship_helper.py
Check if the model has `WithContact` mixin was mising in this control path.
I also fixed the indentation of the file.
> CORE-2292 Fix filtering by relevant contact

- src/ggrc/services/common.py
If a creation fails with an `IntegrityError` on `uq_relationships` ignore the
insert error and just return the existing object.
This is a workaround to fix race condition between requests to different
back-ends (that may include auto mappings)
> CORE-2281 Make relationship POST idempotent

- src/ggrc_workflows/assets/mustache/cycle_task_entries/tree_footer.mustache
> CORE-2089 Fix Reviewer RBAC check for Add comment button

- src/ggrc/converters/query_helper.py
- src/ggrc_workflows/converters/handlers.py
This implements export of dates on workflow (not cycle!) tasks and fixes import of tasks to accept exported csv.
> CORE-2318 & CORE-2320 task dates on import/export 

- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/converters/query_helper.py
- src/ggrc/models/custom_attribute_value.py
This adds support for custom attributes when filtering items on export or in the tree view.
> CORE-2333 filter by custom attributes

- src/ggrc/assets/javascripts/components/relevant_filters.js
- src/ggrc/assets/mustache/import_export/export.mustache
Depends on https://github.com/google/ggrc-core/pull/3080
> CORE-2336 Show all models in relevant filters

- src/ggrc/converters/handlers.py
- src/ggrc_workflows/converters/handlers.py
Propagate `context_id` when importing.
also includes #3091 because it depends on it, so that should be merged first
> QUICK-FIX import context

- src/ggrc_workflows/converters/handlers.py
I still need to discuss with prasanna whether or not the Creator should always become the manager of the workflow he created.
> CORE-2330 Add missing column check to workflow frequency

- src/ggrc/assets/mustache/base_objects/general_info.mustache
Can someone check if this is correct mustache helper. Idea is to show "State" only if exist.
> CORE-1480 Add mustache if helper for State check

- src/ggrc/models/mixins.py
This is not a perfect solution to the problem, but it's the best we can do in the given timeframe. I have created a JIRA ticket to improve this: https://reciprocitylabs.atlassian.net/browse/CORE-2349
> CORE-2311 Increment slug id on slug conflicts

- src/ggrc_risks/assets/mustache/risks/modal_content.mustache
- src/ggrc_risks/migrations/versions/20150917201527_39518b8ea21d_add_notes_to_risk.py
- src/ggrc_risks/models/risk.py
Layout suggestions for the Risk modal much appreciated.
> ZGOOG-26 Add notes to Risk

- src/ggrc/assets/mustache/control_assessments/info.mustache
- src/ggrc/assets/mustache/control_assessments/modal_content.mustache
- src/ggrc/migrations/versions/20150908175600_2d8a46b1e4a4_make_notificationconfig_unique_on_per_.py
- src/ggrc/migrations/versions/20150911131818_29dca3ce0556_change_conclusion_dropdowns_options_in_.py
- src/ggrc/models/control_assessment.py
Fixes also this ticket:
https://reciprocitylabs.atlassian.net/browse/CORE-2285
> ZGOOG-4 Change conclusion dropdown values

- src/ggrc_basic_permissions/__init__.py
I am reverting this because of an issue on grc-test.
> Revert "CORE-2358 Make sure Auditor role propagates permissions"

- src/ggrc/converters/base.py
- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/handlers.py
- src/ggrc/models/relationship.py
- src/ggrc/models/response.py
Support MappedObjects and Documents
> ZGOOG-6 Enhance import/export of responses

- src/ggrc/assets/mustache/requests/modal_content.mustache
Related to [ZGOOG-15](https://github.com/google/ggrc-core/pull/3123) but seems to got missed/lost.
> CORE-2385 Add Control Assessment to Audit Request modal

- src/ggrc/assets/javascripts/apps/business_objects.js
Fix Contract tree view error that pops up when opening tree view
with Contract.
> QUICKFIX Fix Contract tree view issue

- src/ggrc_workflows/converters/handlers.py
- src/tests/ggrc_workflows/converters/test_import_workflow_objects.py
Fix import of one-time workflow and add test for verifying correct
import of values for tasks for various workflow frequencies.
> CORE-2445 Fix import of one-time workflow

- src/ggrc/converters/query_helper.py
- src/ggrc/models/audit.py
- src/ggrc_risks/models/risk.py
- src/ggrc_risks/models/threat_actor.py
- src/ggrc_workflows/models/workflow.py
- src/tests/ggrc/converters/test_export_csv.py
This implements the last missing export filters.
It also enables the catch-all test that make this feature future-proof. 
It already caught the newly added risk models. :smile:
> CORE-2268 export filters

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
> CORE-2441 Fix a script error in tree view

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/components/relevant_filters.js
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
> Revert "CORE-2495 Filter out relevant dropdown list"

- src/ggrc/converters/query_helper.py
- src/ggrc_workflows/converters/handlers.py
Also some other import export fixes that I found.
> CORE-2507 Add a warning for a missing Task Type field

- src/ggrc/assets/javascripts/models/save_queue.js
- src/ggrc/services/common.py
- src/tests/ggrc/services/test_common.py
This batches up model `save` into one request per model (for POSTs)
> CORE-1892 collection post

- src/ggrc_basic_permissions/migrations/versions/20150805105543_99925466d6e_add_roles_order_column.py
- src/ggrc_risk_assessments/migrations/versions/20150716192442_5b29b4becf8_add_slug_to_risk_assessment.py
- src/ggrc_workflows/migrations/versions/20140612212947_4157badaef20_add_cycle_task_entries.py
> QUICK-FIX Add headers to migrations

- src/ggrc/fulltext/mysql.py
- src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
It seems like we missed this one.
> QUICK-FIX Merge one fix from Plum

- src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js
@hyperNURb you worked on this issue so please review. 
The issue was that `child_options.0` in `risk_assessments/info.mustache:42` was not defined.
> CORE-2479 Fix risk_assessments documents mappings

- src/ggrc/migrations/versions/20151016174806_27684e5f313a_make_request_first_class_object.py
Only one statement per execute is allowed
> QUICK-FIX Fix migration on appengine

- src/ggrc/assets/javascripts/application.js
- src/ggrc/assets/javascripts/plugins/ajax_extensions.js
> QUICK-FIX Statusmsgs is undefined

- src/ggrc/assets/javascripts/models/mixins.js
It works, but not sure if I missed something. Please review.
> CORE-2605 Auto populate ownables with current user

- src/ggrc/assets/mustache/people/owners_modal_connector.mustache
- src/ggrc_risks/assets/javascripts/apps/risks.js
- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/mustache/risks/modal_content.mustache
- src/ggrc_risks/assets/mustache/threats/modal_content.mustache
Please test this, it freezes my machine when trying to edit a Risk object.
> CORE-2605 Add multiple owners to Risks and Threats

- src/ggrc/assets/javascripts/application.js
- src/ggrc/assets/mustache/base_templates/attachment_list.mustache
- src/ggrc/assets/mustache/base_templates/mapped_objects.mustache
- src/ggrc/assets/mustache/requests/info.mustache
- src/ggrc/assets/mustache/requests/subtree.mustache
- src/ggrc/assets/stylesheets/_pin.scss
This PR will cover one more JIRA ticket:
https://reciprocitylabs.atlassian.net/browse/CORE-2782
> CORE-2786 & CORE-2782 Make Evidence, URL and Mapped object lists consistet

- src/ggrc/assets/javascripts/controllers/comment_controller.js
- src/ggrc/assets/mustache/requests/info.mustache
Grab the right request instance instead of relying on the page instance.
> CORE-2592 Fix request commenting on non-request page

- src/ggrc_basic_permissions/roles/ProgramAuditEditor.py
- src/ggrc_basic_permissions/roles/ProgramAuditReader.py
Needs work, waiting for @arraystudio input whether Program Readers should also be able to add comments
> CORE-2731 User with Creator role can create comments, Readers can view comments

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/base_objects/general_info.mustache
This is not very aesthetically pleasant, if you have a better solution let me know.
> CORE-2723 Un-CamelCase workflow task status

- src/ggrc/assets/javascripts/controllers/modals_controller.js
I stumbled upon the second script error randomly and I think we don't have a ticket for it. Here are the steps to reproduce:
Steps to reproduce the script error:
1. Click + Add Auditor button in info pane
2. Click Edit Audit
3. Add an Auditor in the Edit Audit Modal
4. Click Save & Close
> CORE-2811 Fix two script errors with admin modal

- .travis.yml
- bin/run_travis_tests
- src/ggrc/assets/javascripts/apps/base_widgets.js
- src/ggrc/utils.py
- test/unit/ggrc/test_utils.py
Unit tests are failing on develop but our travis build is still passing. 
~~This breaks the build.~~ I merged in @zidarsk8's fix for the tests as well.
> QUICK-FIX Set the travis script to fail-fast mode

- src/ggrc/models/request.py
This request doesn't address custom attributes at this moment, that will be a separate #3273 is merged.
> CORE-2609 Move Request back to "In Progress" on any modal field change

- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree_add_item.mustache
- src/ggrc_workflows/assets/mustache/base_objects/approval_link.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/current_tg_tree_footer.mustache
Firstexists mustache helper checks if the element has
a lenght property and therefore only works on strings or lists,
but not integers.
> CORE-2834 Replace firstexist with firstnonempty for int parameters

- src/ggrc/assets/javascripts/controllers/info_widget_controller.js
This is a fix for the main menu on "my work page", The fix adds "risk" and "threat" to the "create new object" dropdown menu on my work page.
> QUICK-FIX Add Risks & Threats to Create new object dropdown list

- src/ggrc/assets/javascripts/controllers/quick_form_controller.js
- src/ggrc_basic_permissions/roles/ProgramAuditEditor.py
I've also fixed a small issue that prevented the add url form from closing.
> CORE-2892 CORE-2893 Add read comment permission to Program Audit Editor

- src/ggrc/converters/handlers.py
This makes sure to cache all the email queries even if they already
exist in the database.
> QUICK-FIX Update import cache for people

- src/ggrc/assets/javascripts/components/people_list.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/join_models.js
- src/ggrc/assets/mustache/base_templates/people_group.mustache
- src/ggrc/assets/mustache/base_templates/people_list.mustache
Make verifiers optional and block request creation until all required fields are entered
> CORE-2611 CORE-2628 Make verifiers optional and verify assignee+requester fields

- src/ggrc/models/mixins.py
Short circuit in order to not rely on types of values
> QUICK-FIX Fix assignee relationships attribute validator

- src/ggrc/converters/base.py
- src/ggrc/converters/import_helper.py
- src/ggrc/models/reflection.py
- src/ggrc_workflows/converters/handlers.py
- src/ggrc_workflows/models/task_group_task.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc_workflows/converters/test_csvs/workflow_small_sheet.csv
- test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Make sure that the options are set for dropdown and checkbox tasks with the correct values from the decscription.
> CORE-2906 Fix task group task imports

- src/ggrc_workflows/notification/data_handler.py
- src/ggrc_workflows/templates/notifications/email_digest_content.html
- src/ggrc_workflows/templates/notifications/style.html
> CORE-2920 Revert "CORE-2487 Improve daily digest email notification"

- src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/base_modal.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/option_column.mustache
https://github.com/google/ggrc-core/pull/3392 against the zucchini branch.
@plamut I have tried to write a unit test for this, but because the changed function relies on the DOM it has proven more difficult than expected.
> CORE-2915 Fix loading selected user role in UserRolesModalSelector

- src/ggrc_workflows/converters/handlers.py
This only contains #3406 and #3415 but we're ignoring them since they only
provide a hot fix that is already properly fixed in develop.
*Note*:
produced using 
git merge upstream/release/0.9.4-Plum --strategy=ours
> QUICK-FIX Merge Plum

- src/ggrc_basic_permissions/__init__.py
I need this to determine how big of a performance impact permission query caching will have on the app. Please review/merge asap so that I'll have more data :)
> QUICK-FIX Add benchmark for load permissions

- src/ggrc/models/relationship.py
Use built-in `__mro__`
See comments on #3381
> QUICK-FIX Simplify RelationshipAttr's validation gathering

- src/ggrc/migrations/versions/20151016174806_27684e5f313a_make_request_first_class_object.py
Here's @uskudnik's comment from before:
---
Before, we had `request -> response <-> (via relationship table) object` mapping - with new request object the concept of responses is not directly translatable to the comments and therefore there can be a conflict if the there are two responses that have the same object(s) mapped to them. With this PR we ensure that only a single mapping gets created from the request to object.
Before:
`request -> (via FK) response` + `response <-> (via relationship table) object`
After:
`request <-> comment` (document text) + `request <-> object`
We cannot use `comment <-> object` mapping at the moment because we only use that for URLs (documents) and that would require changes to app itself.
> QUICK-FIX Persist only unique relationships

- src/ggrc/assets/mustache/requests/info.mustache
Reviewer: When merging this please redeploy our grc-test server (https://ci.reciprocitylabs.com/view/OC%20Instances/job/GGRC_Test/) and let @jmakov know about the new commit hash that he needs to test.
> CORE-2984 Allow adding comments on a finished request

- .eslintignore
- .eslintrc
The first step towards making the incremental linting strategy to work...
> CORE-2997 Update ESLint configuration rules

- Makefile
This fixes url timeout when running make setup_dev.
> QUICK-FIX Fix ansible provisioning

- src/ggrc/migrations/versions/20160113150536_4003827b3d48_drop_unused_tables.py
We have migrated these tables to the relationships table and are therefore no longer in use.
> QUICK-FIX Drop unused tables

- bin/jenkins/run_code_style
This script joins our linters into a single test runner for jenkins.
> QUICK-FIX Add jenkins lint runner script

- bin/check_flake8_diff
- bin/jenkins/functions.sh
- bin/jenkins/run_code_style
- bin/jenkins/run_integration
- bin/jenkins/run_selenium
- bin/jenkins/run_unittests
- test/selenium/bin/chrome_karma.py
This PR adds test runners for integration and unit tests. Unittests combine python unittests and js karma tests.
> QUICK-FIX Add new jenkins test runnes

- src/ggrc/assets/javascripts/models/mappers.js
i've treaded very lightly here, all i did was remove unused local variables, refactored the nearby code and terminated some statements. there are a lot of additional problems that i did not touch:
* there are implied globals on lines 115, 292, 367, 709, 1176, 1299, 1428 and 1560. @zidarsk8 told me not to touch those or things break.
* formatting is broken in all sorts of places but i expect this will be fixed in the linting process
karma tests pass (there's `mappers_spec.js` file)
> QUICK-FIX Remove dead code, refactor

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Thanks @zidarsk8 for pointing this out!
> QUICK-FIX Improve checking for forbidden mappings

- .eslintrc
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
will rebase after done, this PR is for visibility
started at 947 errors
> QUICK-FIX Lint tree view controller

- src/ggrc/assets/javascripts/components/relevant_filters.js
- Cycle Task Entry
- Cycle Task Group Object
> CORE-3082 Blacklist some types from related filter on export

- src/ggrc_workflows/models/relationship_helper.py
- test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Added missing helper since the ticket was reopened.
> CORE-3001 Add indirect rel. helper for CTG <-> object

- doc/advanced_query_api.md
This is a start of the expected query api we need for datagrid.
> CORE-2974 Update advanced query API doc

- src/ggrc/converters/errors.py
- src/ggrc_workflows/converters/handlers.py
- test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
The the workflow task does not have a specified type it should show a
different warning than if the task type is not valid.
> CORE-2559 Update task type import warnings

- src/ggrc/models/mixins.py
Calling e.g. `/api/programs/1` now includes `revisions` fields which has stubs of revisions pertaining to `Program 1`.
> QUICK-FIX Expose revisions of business objects

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/mustache_helpers/revisions_diff_spec.js
- src/ggrc/assets/mustache/requests/change_log.mustache
- src/ggrc/assets/mustache/requests/info.mustache
This PR is meant for previewing the current work on [CORE-3078](https://reciprocitylabs.atlassian.net/browse/CORE-3078)
On the other hand, it can also be merged right away, because it is already fully functional, and the remaining polishing/improvements can be done in separate and thus more manageable pull requests. Since the current ticket is a bit too general, I will open a few other tickets as discusses with @hyperNURb , with each covering one specific improvement that probably still needs to be done.
> CORE-3078 Display Request's change history

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/lhn.py
- test/selenium/src/lib/page/modal/create_new_object.py
- test/selenium/src/lib/page/modal/edit_object.py
- test/selenium/src/lib/page/widget/admin_roles.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/lib/test_helpers.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_admin_dashboard_page.py
- test/selenium/src/tests/test_people_groups_page.py
- test/selenium/src/tests/test_risk_threats_page.py
Depends on https://github.com/google/ggrc-core/pull/3592
> CORE-3180 Integrate admin dasboard roles tests

- src/ggrc/converters/handlers/custom_attribute.py
- test/integration/ggrc/converters/test_ca_import_export.py
Add tests and fix export of objects with custom attributes.
> CORE-3153 Fix custom attribute exports

- src/ggrc/assets/javascripts/apps/quick_search.js
- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/controllers/assessment_generator.js
- src/ggrc/assets/javascripts/controllers/delete_modal_controller.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/services/common.py
Please wait until CORE-3214/CORE-3215 are accepted before merging this, so that Kostya can verify the fix solves the issue.
> QUICK-FIX Merge XSS fix from Zucchini

- bin/jenkins/functions.sh
- bin/jenkins/run_checkstyle
- bin/jenkins/run_code_style
- bin/jenkins/run_integration
- bin/jenkins/run_selenium
- bin/jenkins/run_unittests
Move all the code that runs tests into functions.sh, which will make it easier to use for for creating run_all runner that will run all tests on the develop branch.
> QUICK-FIX Refactor jenkins test runners

- bin/init_env
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/regex.py
- test/unit/test_selenium/__init__.py
- test/unit/test_selenium/test_constants_regex.py
This PR contains changes from https://github.com/google/ggrc-core/pull/3593. This PR should have a needs work label until the other PR is merged.
> QUICK-FIX Update widget class

- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
This pull request is an independent part of the ticket CORE-2377, which is needed for the notifications to work even for imported objects.
Main reason for this PR is making sure that post commit signals get sent too.
> CORE-2377 Update converters

- test/integration/ggrc/api_helper.py
- test/integration/ggrc/models/test_revision.py
- test/integration/ggrc_basic_permissions/test_creator_program.py
- test/integration/ggrc_workflows/notifications/test_deleted_objects.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_annually_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_monthly_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_one_time_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_quarterly_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_weekly_workflow.py
This is a small part from the ticket CORE-2377. The code itself deos not have anything to do with the ticket but the refactor was done when I needed the api helper.
The PR is very independent and cleans up unused codbase.
> CORE-2377 update test api helper

- src/ggrc/app.py
The jasmine imports broke the app if the dev-requirements were not
installed. This fix moves the jasmine imports down and makes sure that
there are no warnings for bad import order, by putting those imports in
a function.
> QUICK-FIX Ignore jasmine imports on production environment

- test/selenium/src/lib/base.py
This PR should solve the problem where selenium tests randomly fail e.g. in https://github.com/google/ggrc-core/pull/3605#issuecomment-193214400
> CORE-3292 Wait for listed elements to load

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/fulltext/mysql.py
- src/ggrc/services/common.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_basic_permissions/roles/Creator.py
- test/integration/ggrc_basic_permissions/test_assignable.py
This is still a WIP as I need to lint the files that got touched by this PR and add finish up the tests. 
I'd appreciate if anyone has the iron will to figure out how the `objects_via_assignable_query` works, so that we can have a conversation on how to make the code more understandable and possibly faster.
> CORE-2959 Add RBAC for assignable mixin

- src/ggrc_basic_permissions/__init__.py
Using OR to JOIN on dest and source was causing a full table scan
across the relationship table. Splitting this into two queries causes
mysql to use indexes.
@edofic can you check if this removes the major slowdown in bigger graphs?
The old query explained:
```
+----+--------------+------------+--------+------------------------------------------------------------------------+----------------------+---------+-----------------------+-------+------------------------------------------------+
| id | select_type  | table      | type   | possible_keys                                                          | key                  | key_len | ref                   | rows  | Extra                                          |
+----+--------------+------------+--------+--------------------------------- …
```
> CORE-3279 Replace OR with UNION in relationship RBAC query

- src/ggrc/assets/javascripts/apps/custom_attributes.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/models/cacheable_spec.js
- src/ggrc/assets/mustache/audits/tree.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/custom_attribute_definitions/modal_content.mustache
- src/ggrc/assets/mustache/custom_attributes/info.mustache
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/requests/tree.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc/converters/handlers/custom_attribute.py
- src/ggrc/fulltext/mysql.py
- src/ggrc/migrations/versions/20160225131127_1e2abee7566c_add_object_id_to_custom_attributes.py
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/mixins.py
- src/ggrc/models/person.py
- src/ggrc/models/relationship_helper.py
- test/integration/ggrc/converters/test_ca_import_export.py
- test/integration/ggrc/converters/test_csvs/product_with_all_custom_attributes.csv
Implemented by adding general mapping type and enabling it for `Person`.
> CORE-2968 Add person to custom attribute types

- README.md
Created with https://github.com/dkhamsing/frankenstein
Was | Now 
--- | --- 
http://www.vagrantup.com/ | https://www.vagrantup.com/ 
Was | Now 
--- | --- 
http://www.ansible.com/home | https://www.ansible.com/ 
https://code.google.com/p/compliance-management/ | https://code.google.com/archive/p/compliance-management 
https://code.google.com/p/ggrc-core | https://code.google.com/archive/p/ggrc-core
> QUICK-FIX Update README URLs based on HTTP redirects

- src/ggrc/models/revision.py
- src/ggrc/utils.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/converters/test_imported_api_requests.py
Updated tests to find workflow related performance issues. In the process discovered an issue in `Revision` so I fixed that as well.
I also moved `QueryCounter` so it can be used for profiling code that is not in tests more easily when debugging such performance issues.
> CORE-3348 eager queries for Workflow and Revision

- src/ggrc/fulltext/mysql.py
- src/ggrc_basic_permissions/__init__.py
- test/integration/ggrc_basic_permissions/test_creator_audit.py
Allow Auditors read access to all objects mapped to the Audit and write access to all Assessments and Issues mapped to the Audit.
> CORE-2955 Update Audit RBAC

- src/ggrc/assets/javascripts/components/assessment_attributes.js
- src/ggrc/assets/javascripts/components/tests/add_template_field_spec.js
- src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache
- src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
This also fixes a typo in the component's HTML tag.
> CORE-3308 Allow to select the Person custom attribute type

- Makefile
> CORE-3414 Revert "CORE-3277 Update appengine SDK from 1.9.3 to 1.9.35"

- src/ggrc/assets/javascripts/models/cacheable.js
Changed the date converter function to use the UTC offset at the moment in time rather than the current UTC offset.
> CORE-3131 Fix datetime rendering for summer/winter times

- src/ggrc/assets/mustache/base_objects/dropdown_menu_tier2.mustache
- src/ggrc/assets/mustache/dashboard/info/get_started.mustache
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_add_item.mustache
This adds several Create Task buttons across the app. Jost's PR should be merged before this one so please add needs work or something.
> CORE-3420 Add create Task buttons

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
- src/ggrc/assets/stylesheets/modules/_modal.scss
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/migrations/versions/20160405161533_38af92d913dc_make_task_group_task_id_nullable_on_.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_one_time_workflow.py
~~This has some TODOs left in there that still need to be resolved.~~
~~There is also a weird glitch if you on create task modal instead of selecting a workflow just write the name in the filed and leave it, it breaks the app.~~ fixed it by changing name="workflow" to name="workflow."
This works better if there is a on-time workflow called "Backlog" active in the app, because the modal auto selects it.
The creation of the Backlog workflow will be taken care of with Tomaz's PR #3720 
This one also takes care of a bit of CORE-3422 (notifications don't get updated, other things seem to work)
> CORE-3418 Quick task creation modal

- bin/jenkins/functions.sh
Log file has changed it's name so we need to update the selenium test function to reflect this.
This should make selenium show up on graphs in ggrc_develop_build jenkins job.
> QUICK-FIX Fix selenium import file for jenkins test runner

- src/ggrc/assets/mustache/dashboard/info/wf_owner.mustache
- src/ggrc/fulltext/mysql.py
- src/ggrc/models/context.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/assets/mustache/cycle_task_groups/tree.mustache
- src/ggrc_workflows/assets/mustache/cycles/tree.mustache
- src/ggrc_workflows/assets/mustache/dashboard/object_nav_actions.mustache
- src/ggrc_workflows/assets/mustache/wf_people/tree_add_item.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
- src/ggrc_workflows/migrations/versions/20160404115153_851b2f37a61_add_kind_column_to_workflows.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/workflow.py
- src/ggrc_workflows/views/__init__.py
- test/integration/ggrc_workflows/test_backlog_workflows.py
This will probably need some work but It's good if i get feedback sooner.
Note: this builds on functionality that allows you to create a task in an existing cycle (which will be added in another PR) meaning you can only review code (or give a suggestion, find bugs,..)
Someone please label it as On hold or something.
> CORE-3421 Add Backlog workflow

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessments/tree.mustache
- src/ggrc/assets/mustache/audits/search_result.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/dashboard/object_list.mustache
- src/ggrc_risk_assessments/assets/mustache/dashboard/lhn_search_result_risk_assessments.mustache
- src/ggrc_workflows/assets/mustache/tasks/extended_info.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
Removed all lock icons. The ticket was just to remove it for a program's first tier but it looks like the private/lock field is no longer used??
> CORE-3360 Remove lock icons from program's first tier

- src/ggrc/assets/javascripts/modules/widget_descriptor.js
I'm not sure if the field I changed will affect other expanding lists but it's the only one that seems to make it work?
> CORE-3250 Make child objects be displayed under control

- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
- src/ggrc/assets/javascripts/models/audit_models.js
- Workflows,
- Audit,
- Assessment Template,
- Assessment and
- Request
> CORE-2966 Prevent generating assessment for all objects

- src/ggrc/assets/mustache/base_templates/header.mustache
- src/ggrc_basic_permissions/roles/Editor.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_add_item.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
This one contains multiple small issues that were found either during PR review of #3722 or during testing of the feature itself.
Note that the testing was done with the Global Editor role.
> CORE-3431,CORE-3445,CORE-3446,CORE-3447,CORE-3448,CORE-3449,CORE-3458: workflow after merge fixes

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/reminder.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/migrations/versions/20160412134448_11cee57a4149_add_assessor_reminder_notification.py
- src/ggrc/models/assessment.py
- src/ggrc/models/mixins_reminderable.py
- src/ggrc/notifications/common.py
- src/ggrc/notifications/data_handlers.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/notifications/test_reminderable.py
Adds reminders mixin and first reminder functionality for Assessment object.
Needs work until #3662 is merged since it's based on @zidarsk8 latest work.
> CORE-3393 Add remind for assessors on Assessment object

- src/ggrc_basic_permissions/__init__.py
cherry-picked the fix for ZEN-2732
> CORE-3514 Enable people to comment on backlog tasks

- src/ggrc/migrations/versions/20160427045741_4db7ea2a47e9_update_relationship_attr_constraints.py
- src/ggrc/models/relationship.py
Make sure that relationship attributes do not prevent relationships from
being deleted.
> CORE-3020 Update relationship attr constraints

- src/ggrc/services/common.py
- src/ggrc_basic_permissions/roles/Editor.py
- src/ggrc_basic_permissions/roles/Reader.py
- test/integration/ggrc_basic_permissions/test_creator.py
In order to show object history log to non-admin users
> CORE-3411 Fix revision RBAC

- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- src/ggrc_workflows/migrations/versions/20160422075916_4fa163aa5dc4_cascade_delete_workflow_objects.py
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/cycle_task_entry.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/task_group.py
- src/ggrc_workflows/models/task_group_object.py
- src/ggrc_workflows/models/task_group_task.py
- src/ggrc_workflows/models/workflow_person.py
I fixed the issue by configuring the workflow models to perform a cascade delete. I suggest reviewing this on a per-commit basis, because the last commit contains only the linting changes.
While linting the modified files, I skipped writing a couple of missing method docstrings - I am not familiar enough with workflows, and thus didn't want to risk writing something that could end up being misleading or even plain wrong.
> CORE-3396 Fix deleting a workflow

- src/ggrc/assets/javascripts/components/assessment_generator.js
- src/ggrc/models/hooks/assessment.py
Default to current user. This does not affect manual assessment creation.
> CORE-3541 Set default creator/assessor if generating w/o template

- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
Notice the nice "copy-paste" pattern...
> QUICK-FIX: Fix a couple of mustache helpers closing tags

- doc/commit_guidelines.md
- doc/css_guidelines.md
- doc/git_management.md
- doc/pull_request_reviews.md
While reading docs I've noticed some spelling errors. This PR aims to fix those errors. Hope this would be useful to make documentation better :smirk:
> QUICK-FIX Fix spelling errors in documentation

- src/ggrc/assets/javascripts/components/tabs.js
- src/ggrc/assets/javascripts/components/tabs_spec.js
Note: this fixes a _different_ cause of a similar issue than #3848
> CORE-3582 Fix occasional script error on rapid tab changes

- doc/commit_guidelines.md
- doc/developer_guide.md
Noticed some spelling typos. This PR aims to fix those typos.
> QUICK-FIX Fix spelling typos in documentation

- src/ggrc/migrations/versions/20160510122526_44ebc240800b_remove_response_relationships.py
Remove some remaining references to response object that was missed in the original [pull request](https://github.com/google/ggrc-core/pull/3788)
> CORE-3358 Remove responses references

- src/ggrc/cache/cachemanager.py
> QUICK-FIX Fix CacheManager.update_collection syntax error

- src/ggrc/models/hooks/assessment.py
- test/unit/ggrc/models/hooks/__init__.py
- test/unit/ggrc/models/hooks/test_assessment.py
Note: Some of the issues mentioned in the ticket have already been resolved by other pull requests.
> CORE-3501 Use Audit auditors as default Assessment assessors

- src/ggrc/assets/javascripts/application.js
- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/components/assessment_generator.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/save_queue.js
- src/ggrc/assets/stylesheets/modules/_notifications.scss
- src/ggrc/models/background_task.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/services/common.py
- src/queue.yaml
I still need to iron out the frontend part, but the main backend work is already complete.
> CORE-3589 Background assessment generation

- src/ggrc/models/assessment.py
> CORE-3584 Fix exporting assessments when using a filter

- src/ggrc/views/__init__.py
> QUICK-FIX Load only unique ca definition title and types

- src/ggrc/assets/javascripts/components/mapped_tree_view.js
- src/ggrc/assets/javascripts/components/people_list.js
- src/ggrc/models/mixin_autostatuschangable.py
- test/integration/ggrc/generator.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/test_mixin_autostatuschangable.py
This should fix everything but deletion of URLs (which is a separate ticket CORE-3564).
This does NOT fix [CORE-3495](https://reciprocitylabs.atlassian.net/browse/CORE-3495) at the moment.
> CORE-3120 Fix revert of state to in progress

- src/ggrc/notifications/notification_handlers.py
- fixes "Returns" typo in docstring
> updates notification_handlers.py

- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/dashboard/index.haml
- src/ggrc/views/__init__.py
> QUICK-FIX Prevent full person object loading on object pages

- src/ggrc/cache/cache.py
> CORE-3623 Fix error when updating custom attributes

- src/ggrc/models/hooks/assessment.py
The program relationship was being created multiple times and failing a uniqueness constraint on the table.
> CORE-3605 Fix error when creating an assessment

- src/ggrc/assets/javascripts/models/audit_models.js
No test, because, you know, _"critical!!!!111one"_ (and hating myself).
> CORE-3615 Make an Audit mandatory to create an Assessment

- src/ggrc_risk_assessments/assets/assets.yaml
- src/ggrc_risk_assessments/assets/javascripts/apps/risk_assessments.js
- src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree.mustache
Note: All fields showing correct values in tree view except Risk Manager and Risk Counsel. I would appreciate if someone can help me to fix this.
> CORE-3568 Add correct fields into dropdown

- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/migrations/versions/20160414223705_7a9b715ec504_add_slug_to_assessment_template.py
- src/ggrc/models/assessment_template.py
- test/integration/ggrc/__init__.py
This is the first part of the bigger PR https://github.com/google/ggrc-core/pull/3784
I am breaking that PR down for easier reviews. Once this is merged I will rebase the other PR to clean up the history.
This code here is also need for other work with importing the templates themselves.
> CORE-3391 Add code to Assessment template

- src/ggrc/models/document.py
- src/ggrc_workflows/notification/data_handler.py
This fixes email notifications for any task that has a document mapped to it.
> CORE-3660 Email notifications fix

- src/ggrc_basic_permissions/roles/Editor.py
This PR is on hold untill I get a spec confirmation from @prasannav7.
> CORE-3064 Remove editor rights to create Person objects

- src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
This was wrongly removed when removing Response object.
I produced this commit with reverting 96027749c151acbae464164b36f57e2df85c41e8 and picking only cycle task template.
EDIT:  there is now additional cleanup contained in here
> CORE-3561 Bring back workflow cycle task responses

- src/ggrc/assets/mustache/base_templates/comment_subtree.mustache
- src/ggrc/models/hooks/__init__.py
As suggested by @Smotko I changed the comments' edit widget from input to rich textarea (I did not have time to properly test it, but he assured that it works fine).
I also incorporated two minor fixes suggested under #3973 , but could not update it on time because that PR was merged right before I wanted to push those changes.
> QUICK-FIX Minor comment fixes

- src/ggrc/assets/javascripts/models/save_queue.js
The way the save queue currently works is that new mappings are pushed to server in batches and then the new mappings are 'saved' client side. This causes a bunch of stuff to be loaded after each batch cycle which takes ages. I found that pushing all the saves to the server and then doing the client-side 'saving' after takes ~30% of the time.
Saving 700 mappings takes ~1 minute. It takes ~42s to push the 700 items in batches of 100 to the server and then ~18s to 'save' client-side.
To speed it up further we could push all the new mappings in one go to the server and then parallelize the saving. The client-side saving will be able to be sped up once the new tree-view is finished as all saved mappings will not need to be 'saved' locally.
> CORE-3576 Speed up mapping lots of objects

- src/ggrc/services/common.py
I want to see what exactly makes some of our `collection get` queries very slow.
Here is an [example of a trace](https://console.cloud.google.com/traces/details/1cbc039d71e17dc4f093d8516f65ec1d?project=grc-dev#TIMELINE) where Query database for resources took 15.0865s, but I don't see a single slow query.
> QUICK-FIX Split "Query database for resources" into multiple benchmarks

- src/ggrc/converters/base_block.py
- src/ggrc/views/converters.py
This makes exports about twice as fast, for object properties. Until we
have an eager query that works on relationships, the performance
increase will be lower it we also export all the mappings data.
> CORE-3683 Improve export performance

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
Fixed hide required fields on create Assessment modal
> CORE-3303 Fix visibility required fields on Assessment modal

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
Removed Audit from Map Object for Request and duplicated assets from assets.yaml
> CORE-3539 Removed Audit from Map Object for Request

- src/ggrc/assets/stylesheets/layout/_no-js.scss
Fixed visibility titles on HNB after refresh page when HNB width less than sum width all tabs.
> CORE-3658 Fix visibility titles in HNB

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
As discussed with @Smotko undo the changes from #3706 as it's probably causing issues for new accounts.
> QUICK-FIX Revert changes from #3706 PR

- src/ggrc/assets/mustache/assessments/header.mustache
> QUICK-FIX Fix copy permalink for Assessments

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
- src/ggrc/assets/mustache/mixins/stateful.mustache
Fixed validation mandatory CA after reset value and disable change status buttons at the blank mandatory fields. By user bug 28985992
> QUICK-FIX Fix validation mandatory CA after reset value

- src/ggrc/assets/javascripts/components/assessment_attributes.js
- src/ggrc/assets/javascripts/components/tests/add_template_field_spec.js
- src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache
- src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Map:Person should be renamed to "Person" on New assessment template.
> CORE-3485 Rename Person on new assessment template

- src/ggrc_basic_permissions/__init__.py
* split the function into multiple smaller functions
* benchmark all the functions
* increase cache duration from 30 minutes to 60 minutes
This will help us debug performance issues with our permissions query.
> QUICK-FIX Add benchmarks for every step in load_permissions_for

- src/ggrc/assets/javascripts/components/assessment_attributes.js
- src/ggrc/assets/javascripts/components/tests/add_template_field_spec.js
- src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache
- src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/stylesheets/_common.scss
Frontend does not check for duplicate CustomAttribue names on Assessment Templates.
> CORE-3453 Fix checking for duplicate CA names

- src/ggrc/__init__.py
- src/ggrc/__main__.py
- src/ggrc/bootstrap.py
- src/ggrc/utils/__init__.py
- src/ggrc/utils/benchmarks.py
> CORE-3704 Improve benchmark context managers

- src/ggrc/models/audit.py
> QUICK-FIX Fix Audit eager_query

- src/ggrc_basic_permissions/__init__.py
The user object in the session is not eagerly loaded and the
user.object_owners always triggered a new query. The main bottleneck
here was serialization of a lot of objects, not the query itself. This
commit does not change the behaviour of the function but only gets rid
of the object generation overhead.
Benchmarks (on local instance) before and after for 3k owner objects:
- avg  0.11570 - max:  0.18693  - min:  0.08616
- avg  0.03412 - max:  0.10563  - min:  0.01692
PS: This seems like micro optimization and I'm not sure if we need to move down this path yet.
> CORE-3704 Improve permissions loading performance

- src/ggrc/converters/handlers/handlers.py
- test/integration/ggrc/converters/test_csvs/import_with_all_warnings_and_errors.csv
- test/integration/ggrc/converters/test_csvs/program_audit.csv
- test/integration/ggrc/converters/test_import_comprehensive.py
This PR builds on top of https://github.com/google/ggrc-core/pull/4063 So I'm putting it on hold until that one get's merged and this one gets rebased.
> CORE-3149 Fix date format check

- src/ggrc/assets/javascripts/application.js
- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
- src/ggrc/assets/mustache/base_objects/open_close.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
- src/ggrc/assets/stylesheets/modules/_tree-content.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache
- src/ggrc_risk_assessments/assets/javascripts/apps/risk_assessments.js
- src/ggrc_risks/assets/javascripts/apps/risks.js
Subtrees not loading in some cases.
> QUICK-FIX Fix subtrees loading 2nd/3rd tiers

- src/ggrc/assets/javascripts/mustache_helper.js
The second commit is mostly about linting, thus I suggest reviewing this on a per-commit basis.
> CORE-3363 Display "Program Owner" role as "Program Manager"

- src/ggrc_basic_permissions/__init__.py
Global Editor can not create new task under audit due to validation issue. 
This issue is already fixed in develop branch PR #3920. As discussed with @Smotko picking these changes for release branch.
> CORE-3667 Fix create task validation permission issue

- src/ggrc/assets/javascripts/components/object_history/object_history.js
- src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/document.js
Adds display_type method and renders it in object history.
> CORE-3444 Render display type instead of raw type value

- src/ggrc/assets/javascripts/controllers/tests/tree_view_node_controller_spec.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
I want to try and delegate `add_child_lists_to_child` and expand item logic.
I think it will give us a minor performance boost as well.
> CORE-3571 Improve tree view performance

- src/ggrc/assets/javascripts/components/people_list.js
- create an audit;
- create a request (the current user is assigned as a requester and assignee);
- edit the request and add another assignee;
- remove the current user from assignees.
Incorrect behavior: the current user is removed from both requesters and assignees.
> CORE-3096 Fix people list component

- src/ggrc_risks/assets/javascripts/apps/risks.js
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree.mustache
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/task_groups/info.mustache
Remove tree view from the info pane.
I didn't implement reordering but instead hidden the arrows as reordering was not working (CORE-3560 - changes do not persist). I also updated CORE-3560 to bring back reordering (with persistence of course)
> CORE-3559 Stabilise Workflow setup

- src/ggrc/assets/javascripts/apps/quick_search.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
- src/ggrc/templates/layouts/dashboard.haml
This should speed up most page loads by about 1.5s.
> QUICK-FIX Improve initial load on the frontend

- src/ggrc_risks/assets/javascripts/apps/risks.js
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
This old PR #3782 of mine broke the workflow people mapping. This new PR seems to fix both issues but the mapping stuff is pretty hard to follow so whoever reviews this please check that I'm doing this right!
> CORE-3677 Make mapped people work for workflows

- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/assets/javascripts/components/csv/import.js
- src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js
- src/ggrc/assets/javascripts/models/display_prefs.js
This should improve the load time for most pages by another 750ms-1s.
> QUICK-FIX Improve initial load on the frontend  #2

- src/ggrc/assets/javascripts/plugins/autocomplete.js
- src/ggrc/assets/javascripts/plugins/tests/autocomplete_spec.js
The second commit is about linting, thus I recommend reviewing this on a per-commit basis.
> QUICK-FIX Fix a potential script error when closing a modal

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/mustache/assessment_templates/tree_add_item.mustache
With this PR we do following:
- Prevent mapping to AT
- Allow creating (defining) new AT
> QUICK-FIX Prevent mapping to Assessment template

- src/ggrc/assets/javascripts/components/people_list.js
- src/ggrc/assets/javascripts/components/tests/people_list_spec.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/services/common.py
This is a proper implementation of people-list manipulations.
> QUICK-FIX Refactor people list component

- src/ggrc/assets/javascripts/components/people_list.js
QUICK-FIX Adding people to an empty list (assessors, verifiers)
> QUICK-FIX Fix adding people to list

- src/ggrc/settings/default.py
The development branch has received quite a lot of quince features already. I think it's time we bump the version :)
> QUICK-FIX Bump version to 0.9.7-Quince

- src/ggrc/assets/javascripts/components/add_comment/add_comment.js
Per discussion with @edofic and @zidarsk8 Map should be safe enough to use. If anyone has any objections, please let me know.
> QUICK-FIX Fix comment role design

- src/ggrc/models/mixins.py
**Fix for deletion of assessments.**
The problem is that the current implementation of `custom_attribute_definitions` is loading the custom attributes definitions with definition_id=None(which means these attributes are global custom attributes). That causes problems(IntegrityError) when trying to delete a particular object. 
When deleting an assessment it tries to delete related custom_attribute_definitions and custom_attribute_values using `cascade=all, delete-orphan ` which means it will try to delete the custom attributes definitions as soon as they will be de-associated from the parent and try to delete records with NULL value in definition_id filed (global custom attributes). 
The fix marks current `custom_attribure_definitions` property as `viewonly=True`, so that the relationship …
> QUICK-FIX Fix assessment deletion

- src/ggrc/assets/javascripts/pbc/workflow_controller.js
Part of https://github.com/google/ggrc-core/pull/4129 PR
> QUICK-FIX Fix WF controller for update AT

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/dashboard.js
Removes an unneeded request from every page load at the expense of a tiny lag loading current state of email notifications when opening the user dropdown.
> QUICK-FIX Defer notification config

- src/ggrc/assets/javascripts/components/people_list.js
- src/ggrc/assets/javascripts/controllers/automapper_controller.js
**Details:** 
Log in as GR and navigate to https://ggrc-sandbox.appspot.com/programs/110#assessment_widget/assessment/2516
Add reader@labs as a Verifier (via assessment’s info panel)
Do not refresh page
Remove reader@labs from being the Verifier
_Actual Result:_ Error "Uncaught TypeError: Cannot read property 'destroy' of undefined" appears
_Expected Result:_ no errors, user removed
PS. For reproduce this issue need to remove user very quickly.
> QUICK-FIX Fix destroy error

- src/ggrc/assets/javascripts/components/object_history/object_history.js
- src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/components/object_history/object_history.mustache
Display correct assignee role that the user held when performing various actions.
> CORE-3202 Display assignee role in object history log

- src/ggrc/fulltext/mysql.py
These two changes will result in a slight performance gain on most search queries.
> QUICK-FIX Improve /search performance

- test/integration/ggrc/builder/test_json.py
Open Source submit by Ken Lynch, CEO of Reciprocity.
> QUICK-FIX Enable builder integration tests

- pylintrc
- test/integration/ggrc/__init__.py
- test/integration/ggrc/services/test_query.py
This is the basis for the new query api tests.
More tests should be added when api get's updated.
> QUICK-FIX Add example test for query api

- src/ggrc_workflows/assets/javascripts/models/task_group.js
- src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
It removes exception on start/end date selection
and also fixes date validation of one time workflows.
> QUICK-FIX Fix task modal window

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree_pagination/tests/tree_pagination_spec.js
- src/ggrc/assets/javascripts/components/tree_pagination/tree_pagination.js
- src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/tree_pagination/_tree_pagination.scss
- src/ggrc/assets/stylesheets/dashboard.scss
Add pagination widget for future pagination functionality
> FEATURE Pagination widget

- src/ggrc/assets/javascripts/permission.js
In #4248 @xferra raised a good point that we could use a comment on conditions. This PR adds said comment.
> Add comment on conditions to _is_allowed_for

- src/ggrc/assets/javascripts/components/tree_pagination/tests/tree_pagination_spec.js
- src/ggrc/assets/javascripts/components/tree_pagination/tree_pagination.js
Add `inProgress` flag to avoid spamming server with pagination request
> FEATURE Improve tree pagination component with inProgress flag

- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/controllers/quick_form_controller.js
@zidarsk8 I've updated commit message according to guidelines.
Please merge it as separated PR, old one (#4228) was closed.
> ISSUE-1.58 Fix adding new users at workflow tasks page

- src/ggrc/assets/mustache/modals/mapper/base.mustache
**Subject**: "Add Selected" button should be "Map Selected"
**Details**: 
- Open any Program page
- Navigate to Control tab
- Click “Map Control to this Program” tree view button
- Look at button that map selected controls to Program
**Actual Result**: Button text is Add Selected
**Expected Result**: Button text should be Map Selected
> ISSUE-1.146 "Add Selected" button should be "Map Selected"

- src/ggrc/converters/query_helper.py
- src/ggrc/services/query.py
This PR adds a flag to disable CA for pagination and unblock PR #4222.
> Disable CA filters for pagination

- src/ggrc/assets/javascripts/components/person/person.js
- src/ggrc/assets/javascripts/components/person/tests/person_spec.js
Problem (and the majority of the fix) was pointed out by @Smotko.
Issue was occurring when we didn't have `person-id` nor `person-obj`
> QUICK-FIX Fix person component

- src/ggrc/models/comment.py
The previous implementation assumed a CA value object is just created and deleted and is never updated. This is not true after refactoring to CA storing logic.
This PR uses logic similar to `latest_revision` from CAV model to store the id of the most recent Revision for the CAV object.
> QUICK-FIX Fix CA revision id in Comments

- src/ggrc/services/query_helper.py
> QUICK-FIX Fix invalid field name in query API doc

- src/ggrc/converters/handlers/handlers.py
2. Map a couple of people.
3. Add them different permissions: Editor, Reader.
4. Export the program.
5. Edit CSV to unmap people via `unmap:person` column.
6. Import CSV.
7. Go to the program page on "people" tab—the people are still there.
1. When a person is mapped to a program, they doesn't have any role.
2. When a role is given to the person, `UserRole` object is created within the program context.
3. When the person is unmapped from the program using `unmap:person` column of CSV, the role is still there.
The fix is a bit hackish, because it uses `UserRole` model from `ggrc_basic_permissions`. But it is the only way I found to fix the issue, without massive refactoring. Since `ggrc_basic_permissions` is an optional extension, here I use `getattr(all_models, …
> QUICK-FIX Unmap people via import

- src/ggrc/assets/javascripts/models/audit_models.js
Remove primary and secondary contact columns from assessment tab
> ISSUE-1.186 Remove unnecessary columns

- src/ggrc/assets/javascripts/apps/business_objects.js
Audits should have the following order of the related objects tabs:
> _"ok Audit order need to change as follows.. assessments, requests, issues, templates, everything else.."_
> QUICK-FIX Swap Requests and Templates object tabs for Audits

- src/ggrc/assets/javascripts/components/assessment/inline.js
- src/ggrc/assets/javascripts/components/mapped_tree_view.js
- src/ggrc/assets/javascripts/ggrc_base.js
Addition to PR (https://github.com/google/ggrc-core/pull/4317)
> ISSUE-1.208 Fix error notification on failed change CA

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
Part of pagination PR (https://github.com/google/ggrc-core/pull/4222). Just a util methods for working with Query API needed for other developers right now.
> QUICK-FIX Add helper for work with Query API

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/plugins/canjs_extensions.js
I've also made sure Assignee property works good
> ISSUE-1.209 Validate audit lead is person instance

- src/ggrc_workflows/assets/javascripts/models/helpers.js
- src/ggrc_workflows/assets/javascripts/models/workflow.js
Subject: Workflow Task is not shown in Workflow Task tab and tree view under GR role
Details: 
Create a program under Global Reader
Submit it for review (Set assignee any of the admin users)
Click Add->Select Workflow Task
Go to Workflow Tasks tab: Workflow Task is not shown
Actual Result: Workflow Task is not shown in Workflow Task tab and tree view under GR role
Workaround: refresh the page
>  ISSUE-1.212 Refresh program after cycle task creation

- src/ggrc_gdrive_integration/assets/javascripts/apps/gdrive.js
> QUICK-FIX Remove fileable document

- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
This fixes regression introduced by #4321
> QUICK-FIX Set transient contact for Cycle Task

- src/ggrc_basic_permissions/roles/Creator.py
Creator should be allowed to read control options unconditionally.
> 1.203 Fix creator option permissions in controls

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
Subject: Script error "Uncaught TypeError: Cannot read property 'is_custom_attributable' of undefined" appears when auditor tries to reach an audit
Details:  
As an admin create an audit and assign a GC user as an auditor
Log in as an auditor and try to reach that page
Actual Result: Script error "Uncaught TypeError: Cannot read property 'is_custom_attributable' of undefined" appears when auditor tries to reach an audit
Expected Result: no errors should appear
> ISSUE-1.346 Fix is custom attributable check

- src/ggrc/migrations/versions/20160905122805_4450e7d1e441_replace_event_action_enum_value.py
1. Convert IMPORT to BULK
2. Fix action = "" and resource_type IS NOT NULL to action = "GET"
3. Fix action = "" and resource_type IS NULL to action = "BULK"
> QUICK-FIX Add migration for events.action field

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
Improvements for working with different operations, not only relevant
> QUICK-FIX Improve Query API utils for work with any operations

- karma.conf.js
- src/ggrc/assets/javascripts/plugins/component_registry.js
- src/ggrc/assets/javascripts/plugins/tests/component_registry_spec.js
How to reproduce:
Go to Assessment page and check the details panel, titles should be empty
How it should look like:
> ISSUE-1.371 Fix getting @ values from element attribute

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-item.js
- src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-list.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/mustache/components/mapped-objects/mapped-objects.mustache
- src/ggrc/assets/mustache/components/reusable-objects/reusable-objects-item.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/flexbox-layout/_flexbox-layout.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/reusable-objects/_reusable-objects.scss
- src/ggrc/converters/query_helper.py
- test/integration/ggrc/models/mixins/test_with_similarity_score.py
This PR is intended to fix P0 bug (description is below) and add multiple improvements required for Assessment UX improvements v2: 
- performance improvements
- pagination
- extra styling
This changes are dependant on previous [PR](https://github.com/google/ggrc-core/pull/4349)
1.125  Bug (P0)
Subject: The app hangs showing errors in the console when navigating to the assessment tab and when switching the page with related assessments 
Details: 
Login as reader@reciprocitylabs.com (engage007) and navigate to https://grc-dev.appspot.com/audits/1514#assessment_widget/assessment/13698 
Actual Result: the app hangs up and doesn’t respond. Sometimes page crashes, sometime it shows script error
Expected Result: the app should continue working, no errors in the console or UI are allowed
> IMPROVEMENT Related assessments tab

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment/controls-toolbar/controls-toolbar.js
- src/ggrc/assets/javascripts/components/ca-object/ca-object-modal.js
- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/mustache/components/assessment/controls-toolbar/controls-toolbar.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal.mustache
- src/ggrc/assets/mustache/components/simple-modal/simple-modal.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/ca-object/_ca-object-modal.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/reusable-objects/_reusable-objects.scss
- src/ggrc/assets/stylesheets/components/simple-modal/_simple-modal.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
Additional changes required for Assessment UX changes v2 
- User should have possibility to open modal window with all related assessments with click on Prior Responses button 
This PR is dependant on #4381
> FEATURE Add Prior Responses functionality 

- src/requirements-selenium.txt
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/tests/test_admin_dashboard_page.py
This smoke test verify following items:
- event has at least one record
- all records at the page have appropriate text forma (text by <user> on <datetime>
- header is displayed and has appropriate text (Events)
Note: selenium driver and pytest plugin version are updated to increase stability of UI tests
> Add basic test for Event widget at admin dashboard

- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls.js
- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-related-information.js
- src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls-popover.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-related-information.mustache
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects-popover.scss
Scope of this PR is to reuse base mapped object component and extend it with filtering feature.
> IMPROVEMENT Add multiple improvements to Mapped Objects Component

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/converters/query_helper.py
- test/integration/ggrc/converters/test_csvs/sorting_with_ca_setup.csv
- test/integration/ggrc/services/test_query.py
This fix won't work untill https://github.com/google/ggrc-core/pull/4341 is merged.
> QUICK-FIX Add CA sorting to query API

- src/ggrc/assets/mustache/assessments/info.mustache
Change positions of Test Plan and Description
> IMPROVEMENT Change placeholders of test plan and description

- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/stylesheets/_z_index.scss
- src/ggrc/assets/stylesheets/modules/_info-pin.scss
- src/ggrc/assets/stylesheets/modules/_object-header.scss
As @andrei-karalionak pointed out, with #4403 I've introduced a regression where we can overflow a description when title is too big.
> ISSUE-1.3 Improve sticky header in info pane

- src/ggrc/converters/query_helper.py
- src/ggrc/services/query_helper.py
- src/ggrc/utils/query_helpers.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
1. Fixing the My Tasks to return the right numbers with Query API
2. Some benchmarks for Query API added
3. Fixed doc strings to comply with Google style guide
**UPD:** The tests will be added in a separate PR, as we need this for Quince release
> QUICK-FIX Query API tasks and benchmarks

- src/ggrc/converters/query_helper.py
- src/ggrc/services/query_helper.py
This fix moves limit counting to SQL. And will speed up pagination part.
> Move query limit to SQL

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**1.421  Bug (P0)**
**Subject**: Recurring cycle of queries at Request tab after creating a request
**Details**: 
Create  an Audit
Create a Request: Look at Request’s first tier 
_Actual Result_: Recurring cycle of queries at Request tab after creating a request
_Expected Result_: No error displayed. Assessor should be added to Assessment.
_Workaround_: N/A
_Note_: Check such a behavior for all objects at My Work page after mapping or creating an object.
> ISSUE-1.421 Fix recycle of queries after create Request

- doc/javascript_conventions.md
- doc/python_conventions.md
If I missed something, please let me know and I'll amend the commit.
> QUICK-FIX Add Python conventions

- test/integration/ggrc/services/test_query.py
This PR adds several integration tests for the `limit` parameter of Query API.
> QUICK-FIX Tests for limit

- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/stylesheets/components/collapsible-panel/_collapsible-panel.scss
- src/ggrc/assets/stylesheets/components/flexbox-layout/_flexbox-layout.scss
Add Conclusions Section to the right Details Panel on the Assessment Info Pane
> IMPROVEMENT Add Conclusions Section

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/view-object-button/view-object-button.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessments/tree.mustache
- src/ggrc/assets/mustache/audits/tree.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/components/view-object-button/view-object-button.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/documents/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/people/object_list.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/requests/tree.mustache
- src/ggrc/assets/mustache/search/advanced_search_option_items.mustache
- src/ggrc/assets/mustache/search/advanced_search_people_items.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/view-object-button/_view-object-button.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
**Subject**: Replace arrow button
**Actual result**:
**Final result**:
> IMPROVEMENT - UX Change arrow button

- src/ggrc/models/hooks/assessment.py
**Details:** 
* Create an assessment under an audit
* Navigate to the Events log
**Actual Result:**  Events list doesn't show automapping of newly created/generated assessment to the Audit.
**Expected Result:** Events log should show the entry for assessment automapping to audit
> ISSUE-1.129 Fix logging event of Assessment mappings

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
> ISSUE-1.423 Uncaught TypeError: Cannot read property 'findInCacheById' of undefined

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Addition to PR https://github.com/google/ggrc-core/pull/4469
> ISSUE-1.433 Fix refresh tree view after create/map object

- src/ggrc/models/mixins/autostatuschangeable.py
_(section 2, bug 1.132 - P1)_
This PR fixes automatic state transitioning when editing Assessment's custom attributed (thanks to @zidarsk8 for hints).
The warning dialog for the state change is missing (not sure if we even had one before for the CAs?), if that is a blocker, please let me know, otherwise we can merge this PR and resolve other things in a separate PR (including e.g. a test for the change).
- create an assessment on audit page
- click complete button
- update a CA field when the assessment in “Ready for Review” state 
The assessment doesn’t change its state to “in progress”
The assessment should change its state to “in progress” from ‘Ready for Review’ or ‘verified’ 
when the following attributes are changed …
> ISSUE-1.132 Fix Assessment's auto state transtion on CA edit

- src/ggrc/converters/base_block.py
- test/unit/ggrc/converters/test_base_block.py
Added unittests for [code](https://github.com/google/ggrc-core/pull/4479) as we discussed with @egorhm and @plamut.
> Add unittests for issue 1.445 solution.

- src/ggrc_workflows/converters/handlers.py
- test/integration/ggrc/converters/test_csvs/importing_task_group_task_warnings_and_errors.csv
- test/integration/ggrc/converters/test_import_comprehensive.py
bug description
> Subject: Script error "import failed due to server error " appears when tried to import a csv file with tasks
> Details: 
> Navigate to import page
> Import the csv: https://docs.google.com/spreadsheets/d/1sfNXxw_kmiw1r-Qfzv1jUM48mpeZNjIAnLdSxiCQSsI/edit?pli=1#gid=627526582
> Actual Result: Script error "import failed due to server error " appears 
> Expected Result: No script error displayed. The app shows the warnings and errors upon parcing the csv file
> Workaround: NA
> ISSUE-1.454 Fix tasks import

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
- src/ggrc/models/mixins/clonable.py
- test/integration/ggrc/models/test_clonable.py
P1 User Bugs **V4**
Program Reader role can see and press "Clone Audit" button on audit's info pane (Nothing happens after, only 403 error in console).
> Add permission check to audit clone button

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/regex.py
- test/selenium/src/lib/constants/ux.py
- test/selenium/src/lib/page/extended_info.py
- test/selenium/src/lib/page/modal/delete_object.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_object_mapping.py
This PR depends on https://github.com/google/ggrc-core/pull/4222 thus putting it on hold until that is merged.
> Enable tests for LHN mapping and batch control deletion

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/dashboard/info/info.mustache
- src/ggrc/assets/mustache/help/filters_helper_content.mustache
- src/ggrc/assets/mustache/people/autocomplete_result.mustache
- src/ggrc/assets/mustache/people/info.mustache
- src/ggrc/assets/mustache/people/object_list.mustache
- src/ggrc/assets/mustache/people/popover.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/search/advanced_search_people_items.mustache
- src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_list.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/option_column.mustache
- src/ggrc_workflows/assets/mustache/dashboard/widgets.mustache
- src/ggrc_workflows/assets/mustache/wf_people/people_items.mustache
**1.487  Bug (P0)**
**Subject**: Rename "No Access" program scope role to "No Role" role w/appropriate role description 
**Details**:
Open person widget at Program page
Select any user and edit program scope role
_Actual Result_: No Access role is displayed
_Expected Result_: No Role role w/appropriate description should be displayed
> ISSUE-1.487 Rename "No Access" program scope role to "No Role"

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**Subject**: Request is not shown in Requests tab after creating
**Details**: 
- Create an Audit
- Go to Audit page
- Create Request
- Look at Requests tab: newly created Request is not shown
**Actual Result**: Request is not shown in Requests tab after creating
**Expected Result**: Requests are shown in Requests tab after creating
**Workaround**: refresh the page
**Note**: the actual result is that list becomes (sometimes) empty after creating a new request.
> ISSUE-1.460 Request is not shown in Requests tab after creating

- src/ggrc/assets/javascripts/models/join_models.js
- src/ggrc/assets/javascripts/models/mappers/tree-page-loader.js
- src/ggrc/assets/javascripts/models/person.js
**Subject:** Can not unmap a person from a program
**Details:**
- Go to People tab
- Map a person to a program
- Click on first view tier of mapped person
- Click 3 bb’s button on People’s Info pane
- Select unmap
**Actual Result:** Can not unmap a person from a program
**Expected Result:** A person should be unmapped from a program and not displayed at People tab 
**Workaround:** NA
> ISSUE 1.491 Fix unmap a person from a program

- src/ggrc/assets/javascripts/apps/base_widgets.js
- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/apps/dashboard.js
- src/ggrc/assets/javascripts/apps/quick_search.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc_risks/assets/javascripts/apps/risks.js
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
**1.452  Bug (P1)**
**Subject**: People count is wrong on program page
**Details**: 
Navigate to a program page = > People tab 
_Actual Result_: People count is wrong on program page
_Expected Result_: people tab should show correct number of people
**NOTE**: And also tab's count moved on Query API
> ISSUE-1.452 People count is wrong on program page

- src/ggrc/models/reflection.py
This PR is just to pull change done to quince that are missing in the develop branch, to avoid any merge conflicts.
> QUICK-FIX Add local CA dropdown description

- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_ca_import_export.py
This is a redo of this pr https://github.com/google/ggrc-core/pull/4487 because that was merged into the wrong branch.
> GGRC-15 Ca dropdown description

- src/ggrc/converters/base_row.py
- test/integration/ggrc/converters/test_import_csv.py
Creating and updating objects with imports must set the correct modified
by user.
> QUICK-FIX Add modified by to imported objects

- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_ca_import_export.py
- test/integration/ggrc/converters/test_csvs/custom_attribute_update_tests.csv
The issue was caused by unicode characters in CAD dropdown options.
> GGRC-132 Fix internal server error on export page

- src/ggrc/models/hooks/assessment.py
This PR is a copy of #4451 but is done into the release branch.
> GGRC-11 Log assessment automappings

- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
- src/ggrc/assets/mustache/components/assessment/controls-toolbar/controls-toolbar.mustache
- src/ggrc/assets/mustache/components/simple-modal/simple-modal.mustache
> GGRC-43 Modify Modal Title from the 'Prior Responses' to 'Prior Audit Responses'

- src/ggrc/converters/query_helper.py
- test/integration/ggrc/converters/test_csvs/querying_with_unicode.csv
- test/integration/ggrc/services/test_query.py
* Create a program
* Create an audit
* Fill in non ASCII symbols in Filter field (e.g. “фильтр”)
* Click Filter button: 500 error is displayed in Console
> GGRC-6 Fix unicode errors on search

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/regex.py
- test/selenium/src/lib/constants/ux.py
- test/selenium/src/lib/page/extended_info.py
- test/selenium/src/lib/page/modal/delete_object.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_object_mapping.py
This PR is copy of following PR https://github.com/google/ggrc-core/pull/4278 to quince release branch.
It enables following tests:
- deletion multiple control records form widget tab
- mapping via LHN
> Enable skipped selenium tests

- src/ggrc/assets/javascripts/components/rich_text/rich_text.js
Uncaught TypeError: Cannot read property 'editor' of null(…)
Create New Program
Create Audit
Create Assessment
Navigate to Assessment’s Info pane in Audit page
Go to Comments tab
Add comment
Click Add button
Create the second Assessment
Navigate to Assessment’s Info pane in Audit page
Go to Comments tab
Add comment
Click Add button
Actual Result: / Uncaught TypeError: Cannot read property 'editor' of null(…)
Expected Result: No error displayed and comment is added to Assessment's info pane
> GGRC-2 Uncaught TypeError: Cannot read property 'editor' of null(…)

- src/ggrc/assets/javascripts/components/people_list.js
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/base_templates/people_group.mustache
- src/ggrc/assets/mustache/base_templates/people_list.mustache
- src/ggrc/assets/stylesheets/modules/_label-list.scss
In order to associate a person with a particular role in an object, you have to:
1. Know to hover over the text for the role, such as A assignees(s) in the Request object. A little + sign appears to the left of the A assignees text string.
2. Click on +. A field appears.
3. Click inside the field.
4. Type in the name of a requestee and know that its going to do a search for an object.
5. Click on the object representing the person who you want to assign the request.
Instead, you could just make an editable field next to assignees(s) and people would know that they could click in it and add an assignee (instead of having figure out that you need to hover over the text string).
> GGRC-45 Always show the plus button to add person to the list

- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/mixins/customattributable.py
> Revert "GGRC-211 Fix customattributable date setter"

- src/ggrc/services/common.py
1. Create Assessment template with several CA (e.g. ATTRIBUTE TYPE - dropdown, attribute values - yes, no)
2. Go to Assessment’s tab
3. Generate assessment using the created Assessment template by clicking Generate Assessment icon
4. Navigate to Assessment’s Info pane
5. Select the added CA 
6. Select the value “no” from the dropdown
7. Select the value “yes” from the dropdown
8. Go to Assessment Log tab
9. Look at the Assessment Log: not capturing all changes
Assessment Log not capturing all changes
Assessment Log should capture all changes
If an object has been updated, but only its custom attributes have been changed, then this object will not be added into `cache.dirty` set. So that its revision will not be created. I added `force_obj` flag into `log_event` function. It solve the …
> GGRC-145 Fix assessment log

- src/ggrc/assets/javascripts/models/audit_models.js
> QUICK-FIX Remove dead mixin

- src/ggrc/assets/mustache/base_templates/people_list.mustache
Change assessor field name in assessments to assignee
> GGRC-101 Change conflict roles message

- src/ggrc/assets/javascripts/models/save_queue.js
- src/ggrc/login/__init__.py
- test/integration/ggrc/api_helper.py
- test/selenium/src/lib/service/rest/client.py
This should resolve:
1. GGRC-154 - JS error is displayed while clicking on people tab in HNB from Program page by user w/no access role
2. GGRC-155 - JS error is displayed while creating new audit by user w/no access role
Steps:
1. Login as admin and grand GR access to user#1
2. Login as user#1 and create program
3. In different (incognito) browser tab login as admin set No Access system role for user#1
4. Do whatever is in the title of the ticket
Actual Result: User#1 got JS error message
We now show a red error prompting the user to verify if they are logged in.
> GGRC-15{4,5} Fix multiple issues when user looses role while working with the app

- src/ggrc/models/assessment.py
- src/ggrc/models/object_document.py
- src/ggrc/models/request.py
This is a cherry pick of https://github.com/google/ggrc-core/pull/4482
> GGRC-284 Add csv description

- src/ggrc/cache/cache.py
- src/ggrc/migrations/versions/20160728140921_2a5a39600741_add_snapshot_model.py
- src/ggrc/models/all_models.py
- src/ggrc/models/snapshot.py
- src/ggrc/services/__init__.py
Initial migration to add snapshot objects to database.
> FEATURE/SNAPSHOT Add Snapshot model migration

- src/ggrc/models/relationship_helper.py
This is a cosmetic and a performance improvement for creating a union of
a list of possible relation queries.
> QUICK-FIX Update the related queries union function

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/snapshotter/scope-update.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
- src/ggrc/assets/mustache/modals/confirm_cancel_buttons.mustache
> GGRC-121 Update all to latest version (3bbs menu item)

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/ggrc_base.js
Minor fix of error message text.
To check for the incorrect message try to create an AT:
*   Create AT.
*   Open edit modal for this AT.
*   Add CA with the same title as exist global CA for Assessment
*  Try to save.
Result: In the end of error message we can see unnecessary text (error, BAD REQUEST etc.)
> GGRC-185 Fix error message

- src/ggrc/snapshotter/__init__.py
- src/ggrc/snapshotter/datastructures.py
- src/ggrc/snapshotter/indexer.py
- src/ggrc/snapshotter/rules.py
- src/ggrc/views/__init__.py
Add indexing support for snapshots.
While I have tests (see #4237), those are not useful until we include full snapshotter into develop. However, indexing is needed to speed up the development of Query API support for snapshots.
> [FEATURE/SNAPSHOTS] Indexer

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
This PR replaces Object field and required validation with Map Object control on Add/Edit Assessment dialog.
> GGRC-189 Replace Object field with Map Object control

- src/ggrc/assets/javascripts/controllers/comment_controller.js
- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- src/ggrc_workflows/assets/javascripts/components/end_cycle.js
Merge Release to Develop branch
>  Merge Release/0.9.7 quince

- src/ggrc/converters/query_helper.py
- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/models/relationship_helper.py
- src/ggrc/models/snapshot.py
- test/integration/ggrc/services/test_query_snapshots.py
This is a continuation of https://github.com/google/ggrc-core/pull/4677. Please merge that one first, or just review the last 5 commits in this PR.
Note: This PR removes code debt on how we handle queries for custom attributes and that is why after merging we must re-index the fulltext index table. for that just login and run `$.post('/admin/reindex')`.
> GGRC-419 Fix snapshot query search

- src/ggrc/assets/javascripts/components/datepicker/datepicker.js
**Details**:
1.Go to One time WF page
2. Open Setup tab
3. Open Task group info pane
4. Click on Create task [+] button
5. Input title
6. Choose start date more than Due date
_Actual result:_ Save&Close button is inactive while the value in Due Date datepicker changes.
_Expected result:_ Save&Close button should be available
> GGRC-31 Fix validation dates on Create New Task modal

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/converters/pre_commit_checks.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/notification/notification_handler.py
- test/integration/ggrc_workflows/converters/test_csvs/cycle_task_group_object_task_active_update.csv
- test/integration/ggrc_workflows/converters/test_cycle_task_group_object_task_import_update.py
**Was implemented:**
- update existing cycle-tasks via import + integration tests,
- necessary validations for cycle-tasks bulk updates.
Here is the [link](https://docs.google.com/spreadsheets/d/1VwIUiVJMwOPsUhBwQUUKUeGmOaw2R7KUcmiByIO1yTo/edit#gid=562740592) with common workflow scenario which describes changes.
**Integration tests for validations part will be in next PR.**
> Make possible to update cycle-tasks with import

- src/ggrc/assets/javascripts/components/datepicker/datepicker.js
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/stylesheets/modules/_assessment.scss
- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/converters/pre_commit_checks.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/notification/notification_handler.py
- test/integration/ggrc_workflows/converters/test_csvs/cycle_task_group_object_task_active_update.csv
- test/integration/ggrc_workflows/converters/test_cycle_task_group_object_task_import_update.py
This PR fixes yet another merge conflict that was caused by an addition of unrelated imports in base_row.py both in Quince and develop.
> Fix merge conflict between Quince and develop

- src/ggrc/assets/javascripts/components/assessment_attributes.js
- src/ggrc/assets/javascripts/components/tests/template_attributes_field_spec.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
Copy of https://github.com/google/ggrc-core/pull/4693 in correct branch
> GGRC-449 Fix values with dot in AT CA of dropdown type

- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache
- src/ggrc/assets/stylesheets/components/custom-attributes/_custom-attributes.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
Sorry, it looks like I've mistakenly created PR on develop branch instead of master
> GGRC-256 Update to Fix Layout issue of Assessment Info Pane

- src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
1. Set a text CA of an Assessment to "Some value 123".
2. Open the unified mapper to map objects to any other object (say, a Program).
3. Choose "All objects" in "Object type" dropdown, type in "Some value 123" into the search input. Click "Search".
**Expected result:** the assessment edited in step 1 is shown in the results.
**Actual result:** the assessment edited in step 1 is not shown.
> GGRC-50 Make possibility to search via Query API in unify mapper

- src/ggrc/migrations/versions/20161123124848_1f5c3e0025da_remove_control_id_column_from_.py
Cannot delete control "Key Validation",not even as an admin, despite the app telling me that it succeeded.
> GGRC-308 Cannot delete control

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/constants/url.py
- test/selenium/src/lib/entities/__init__.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/file_ops.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_admin_dashboard_page.py
Tests verify following:
1. 1st tree view items at Custom Attribute tab
2. Possibility to create all different field types of Custom Attributes for random definition type
> Create global Custom Attributes tests

- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
Make search field working by hitting Enter on the keyboard on unified mapper
> GGRC-319 Made work search by Enter on unified mapper

- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/mixins/customattributable.py
- test/integration/ggrc/models/test_control.py
- test/integration/ggrc/models/test_snapshot.py
**This PR builds on top of: https://github.com/google/ggrc-core/pull/4756**
This tickets fixes most of the fields on a snapshot.
The fix will only work on new items since the old ones will have to get their revisions updated to add the missing data. But that is out of scope of this ticket.
Adding please review because it's needed for tuesday release and there will be other PRs that depend on this that update the revisions.
> GGRC-487, GGRC-490 Snapshot content

- src/ggrc/converters/query_helper.py
- src/ggrc/services/query_helper.py
This PR optimizes the Query API in the following way:
1. Split the queries to the DB so that filtering returns just the ids and full entities are returned in a separate query built with `eager_query`.
2. Remove `Last-Modified` header for `"type": "count"` and `"type": "ids"` queries to minimize the amount of data fetched from the DB. The header has no use at the moment.
***Benchmarks:***
Each query was performed in a separate POST request and was built like the following:
```json
{ "object_name": "Assessment (Control, Program)",
"limit": "[0, count]",
"type": "values (ids)",
"filter": {"expression": {}} }
```
The database cache was disabled.
Average time and std over 10 iterations for every query is shown.
**Type: values**
Objects | Time unoptimized | Time optimized …
> GGRC-492 Optimize Query API serialization

- src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
Fix for JS Errors on Unified Mapper Search
> QUICK-FIX Update in-scope filtering to support Query API

- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
This PR fixed info pane animation on expanding/collapsing/closing the panel.
> GGRC-573 Fix info pane expand/collapse animation

- src/ggrc/fulltext/recordbuilder.py
Snapshots created via POST api with relationships or snapshots request
are indexed by the fulltext indexer. That must now support adding
additional fields to the record for snapshot content.
> GGRC-536 Fix indexing of individual snapshot objects

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
This PR will also fix several issues:
- GGRC-579
- GGRC-552
- GGRC-580
> GGRC-579 Hide treeView child items for snapshots

- src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This PR fixes JS error on opening certain tree view items and scrolling the page.
> Fix js error on opening tree view items

- src/ggrc/assets/mustache/requests/tree_header.mustache
This PR adds dropdown to requests tree view header.
> GGRC-593 Add tree header dropdown to requests tree view

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/view-object-buttons/view-object-buttons.js
- src/ggrc/assets/mustache/assessments/tree.mustache
- src/ggrc/assets/mustache/audits/tree.mustache
- src/ggrc/assets/mustache/base_objects/tree.mustache
- src/ggrc/assets/mustache/components/view-object-buttons/view-object-buttons.mustache
- src/ggrc/assets/mustache/controls/tree.mustache
- src/ggrc/assets/mustache/directives/tree.mustache
- src/ggrc/assets/mustache/documents/tree.mustache
- src/ggrc/assets/mustache/objectives/tree.mustache
- src/ggrc/assets/mustache/people/tree.mustache
- src/ggrc/assets/mustache/programs/tree.mustache
- src/ggrc/assets/mustache/search/advanced_search_option_items.mustache
- src/ggrc/assets/mustache/search/advanced_search_people_items.mustache
- src/ggrc/assets/mustache/sections/tree.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree.mustache
This PR adds open/view buttons for all objects in tree views across the application.
> GGRC-522 Add open/view buttons for all objects in tree views

- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
This PR will fix several issues:
- 552
- 562
> GGRC-562 Avoid putting snapshots in cache

- src/ggrc/assets/javascripts/models/audit_models.js
This PR will fix 2 issues:
- 572
- 578
> GGRC-578 Show Assessment Template tab for audit by default

- src/ggrc/assets/mustache/requests/tree.mustache
This PR add open/view buttons to requests tree view.
> Add open/view buttons to requests tree view

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/base_templates/header.mustache
Remove Unmap Button for Assessment, Assessment Template and Issue from three BB dropdown menu
> GGRC-608 Remove Unmap Button for Assessment, Assessment Template and Issue

- src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
- src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
- src/ggrc/assets/mustache/controls/tree_add_item.mustache
- src/ggrc/assets/mustache/directives/tree_add_item.mustache
- src/ggrc/assets/mustache/documents/tree_add_item.mustache
- src/ggrc/assets/mustache/import_export/import_export_buttons.mustache
- src/ggrc/assets/mustache/objectives/tree_add_item.mustache
- src/ggrc/assets/mustache/sections/tree_add_item.mustache
- src/ggrc/assets/mustache/systems/tree_add_item.mustache
Pass parent id and type to unified mapper.
> GGRC-620 Fix in scope search and mapping

- src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
1. Go to my Work page
2. Select an object from HNB (e.g. Controls)
3. Click Map in the first tree view
4. Select an object type to map (e.g. Programs)
5. Click Search: query 2.3 min 
Actual Result: Performance degradation in Unified mapper window while searching
Expected Result: improve performance degradation
> GGRC-553 Fix performance degradation in Unified Mapper

- src/ggrc/assets/mustache/base_templates/url_list.mustache
- src/ggrc/assets/mustache/components/assessment/urls-list.mustache
Precondition:
Created program, audit, assessment
1. Go to audit page-> Assessment tab
2. Navigate to Assessment's Info pane
3. Enter URL but not do not click Add button
4. Click Complete button: confirm error message occurs
Actual Result: "Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': ' verify_event' is not a valid attribute name" 
Expected Result: no error displayed. Assessment changes the status from In progress to Completed
> GGRC-626 Fix js error on Assessment info pane

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
1. Go to https://grc-dev.appspot.com
2. Go to All Objects page: confirm the error is displayed
_Actual Result:_ "Uncaught RangeError: Maximum call stack size exceeded" error occurs on All Objects page in dev branch
_Expected Result_: no error displayed. All Objects are displayed
> GGRC-455 Fix js error on All Objects page

- src/ggrc/assets/javascripts/controllers/modals_controller.js
Assignee resets to the current user email when creating the task group by clicking "Save & Add Another" button
> GGRC-613 Save contact for Task Group after Save&Add Another

- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
This PR fixes undefined instance object issue in unified mapper.
> GGRC-653 Fix undefined instance object in unified mapper

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
- src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
- src/ggrc/assets/mustache/base_objects/unmap.mustache
- src/ggrc/assets/mustache/base_templates/header.mustache
- src/ggrc/assets/mustache/issues/info.mustache
This fix should also resolve GGRC-608
> GGRC-641 Hide unmap button from Audit info pane

- src/ggrc/templates/welcome/index.haml
This PR changes gGRC label to GGRC on login page.
> GGRC-602 Change gGRC label to GGRC on login page

- bower.json
- src/requirements-dev.txt
Now that we upgraded canjs we can upgrade some of other dependencies as well.
> QUICK-FIX Upgrade frontend dependencies and factory-boy

- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/mustache/issues/modal_content.mustache
> GGRC-720 Add validation and remove duplication of Audit field

- src/ggrc/models/hooks/assessment.py
GGRC-712: Assessments' title generation was moved to backend.
This is quick-fix for assessment generation performance
improvement.
> GGRC-712: Improve performance in assessment generation

- src/ggrc/notifications/common.py
This PR changes gGRC label to GGRC in notification emails subject
> GGRC-602 Change gGRC label in notification emails subject

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/textarea-array/textarea-array.js
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
2. My Tasks
3. Click on first tier of any task
4. Select Edit task from 3 bb's menu: confirm error is displayed
Actual Result: "Uncaught TypeError: val.split is not a function" error occurs while opening Edit Task modal window on My Work page
Expected Result: no error displayed while opening Edit Task modal window
> GGRC-707 Fix response_options for Tasks

- src/ggrc/assets/javascripts/models/issue.js
Fix preselection of current audit if creating an issue from the left menu.
> GGRC-720 Preselect current Audit for new Issue

- src/ggrc/migrations/utils/strip_text_field.py
- src/ggrc/migrations/versions/20161229191611_4fcaef05479f_strip_titles_spaces.py
- src/ggrc/models/clause.py
- src/ggrc/models/document.py
- src/ggrc/models/meeting.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/option.py
- src/ggrc/models/section.py
- src/ggrc_risk_assessments/migrations/versions/20161229192040_237ccd7c769c_strip_titles_spaces.py
- src/ggrc_risks/migrations/versions/20161229191851_440149c856a2_strip_titles_spaces.py
- src/ggrc_workflows/migrations/versions/20161229192346_216e496dabe_strip_titles_spaces.py
Don't have access to jira now, I will copy description here soon.
> GGRC-378 Remove trailing/leading spaces from titles

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/object-selection/object-selection-item.js
- src/ggrc/assets/javascripts/components/object-selection/object-selection.js
- src/ggrc/assets/javascripts/components/snapshot-loader/snapshot-loader-item.js
- src/ggrc/assets/javascripts/components/snapshot-loader/snapshot-loader.js
- src/ggrc/assets/mustache/components/object-selection/object-selection-item.mustache
- src/ggrc/assets/mustache/components/snapshot-loader/snapshot-loader-item.mustache
- src/ggrc/assets/mustache/components/snapshot-loader/snapshot-loader.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/object-selection/_object-selection.scss
Precondition:
Created program, audit, at least 10 controls
2. Select Generate assessment in 3 bb's menu 
3. Click Search controls
4. Select several Controls in Search list, go to another page, select a control, return to the previous page: confirm that already selected checkbox is not marked
Actual Result: Already selected checkbox is not marked if return on previous page in Unified mapper 
Expected Result: Already selected checkbox should be marked if return on previous page in Unified mapper
> GGRC-725 Already selected checkbox is not marked if return on previous page in Unified mapper

- src/ggrc/assets/javascripts/apps/business_objects.js
1. Click on user's Email in right top corner
2. Select My Assessments in dropdown list: confirm no info is shown and the app freezes
_Actual Result_: The app freezes while opening My Assessment page
_Expected Result_: User's Assessments should be shown on My Assessment page
> GGRC-751 Fix assessment view page

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/js_specs/models/cacheable_spec.js
Remove deprecated and redundant functionality. Fix minor linting errors.
> QUICK-FIX Clean up mixins and cacheable Models

- src/ggrc/migrations/versions/20170106080358_353e5f281799_remove_invalid_revision_hash.py
- src/ggrc/migrations/versions/ggrcdev_ggrc.sql
This PR fixes the data corruption described here: https://github.com/google/ggrc-core/pull/4760#issuecomment-270307168
> QUICK-FIX Fix alembic revision hash

- bin/db_migrate
- bin/validate_database.py
- src/ggrc/migrations/utils/validation.py
This script checks for any Issues and Assessments that are in an invalid
state. That means that they do not have exactly one Audit mapped to
them.
> GGRC-772 Add Assessment and Issue check script

- README.md
- docs/source/conf.py
- src/ggrc/migrations/utils/migrator.py
- src/ggrc/migrations/versions/20160208143508_1839dabd2357_custom_attributes_should_be_unique.py
Some files were missed in this PR: https://github.com/google/ggrc-core/pull/4939
> QUICK-FIX Update license years

- src/ggrc/assets/javascripts/apps/base_widgets.js
- src/ggrc/assets/javascripts/components/snapshot-loader/snapshot-loader.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
Precondition:
Created program, snapshotable object (e.g. Access Group), Control, Audit
1. Go to Assessment tab on Audit page
2. Click Edit Button
3. Click Map object in Assessment modal window
4. Search (e.g. Access Group) for mapping in scope of audit
Actual Result: All the objects are shown in search list in Unified modal window while mapping an object in ASMT modal window 
Expected Result: Objects that are in scope of the audit are shown in search list in Unified modal window while mapping an object in ASMT modal window
> GGRC-505 All the objects are shown in search list in Unified modal window while mapping an object in ASMT modal window

- src/ggrc/assets/mustache/people/object_list.mustache
- src/ggrc/assets/stylesheets/_helpers.scss
- src/ggrc/assets/stylesheets/modules/_tree-content.scss
3. Click on first tree view on control's tab: confirm first tree view is not grayed along the edges 
Actual Result: first tree view is not grayed along the edges 
Expected result: First tree view should be grayed fully
> GGRC-513 First tree view is not grayed along the edges 

- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Unit tests for revision comparer component
> GGRC-768 Add tests for revision comparer

- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
Precondition:
2. Return to the program page and make changes in Control (e.g. change the title)
4. Navigate to Control's Info pane: confirm "Compare with the latest version" link is displayed
5. Click "Compare with the latest version" and look at title of the window: confirm the incorrect title is shown
Actual Result: "Compare with the latest version" window contains the incorrect title
Expected Result: the title should correspond to the link that is shown in Info pane: e.g. "Compare with the latest version"
> GGRC-803 Change title in diff modal window

- bin/validate_database.py
- src/ggrc/migrations/utils/validation.py
- src/ggrc/migrations/versions/20161220161315_275cd0dcaea_migrate_assessments_issues_data.py
I'm adding `critical` since #4877 is blocked because of this.
> QUICK-FIX Remove Request from Assessment and Issue migration chain

- src/ggrc/assets/mustache/components/assessment/urls-list.mustache
Need to show a confirm Dialog when an assessment is moved from "Ready for Review" to "In Progress"
> GGRC-717 Confirm Dialg on assessment status chnge

- src/ggrc/assets/stylesheets/modules/_file-controls.scss
Cherry-pick https://github.com/google/ggrc-core/pull/5003 to release branch
> GGRC-583 Fix blinking header info panel

- src/ggrc/assets/javascripts/components/assessment/custom-attributes.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/assessments/info.mustache
Precondition:
created GCA with any type for Assessment, program, audit
3. Fill in GCA in Info pane: no result
Actual Result: CA values are not saved in Assessment's Info pane
Expected Result: CA values should be saved in Assessment's Info pane
> GGRC-820 CA values are not saved in Assessment's Info pane

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
- src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
- src/ggrc/assets/mustache/modals/mapper/base.mustache
2. Click Add tab-> Control
3. Click Create New Control in Unified mapper
4. Fill in all the mandatory fields-> Save and Close
5. Look at Search results in Unified mapper: newly created Control is not shown
Actual Result: Object is not shown in Search results in Unified mapper after creation
Expected Result: Object should be shown in Search results in Unified mapper after creation
> GGRC-568 Object is not shown in Search results in Unified mapper after creation

- test/integration/ggrc/converters/__init__.py
- test/integration/ggrc/converters/test_ca_import_export.py
- test/integration/ggrc/converters/test_export_csv.py
- test/integration/ggrc/converters/test_import_assessment_templates.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_automappings.py
- test/integration/ggrc/converters/test_import_block_order.py
- test/integration/ggrc/converters/test_import_comprehensive.py
- test/integration/ggrc/converters/test_import_csv.py
- test/integration/ggrc/converters/test_import_delete.py
- test/integration/ggrc/converters/test_import_special_objects.py
- test/integration/ggrc/converters/test_import_unmapping.py
- test/integration/ggrc/converters/test_import_update.py
- test/integration/ggrc/converters/test_imported_api_requests.py
- test/integration/ggrc/converters/test_multi_import_csv.py
- test/integration/ggrc/models/test_snapshot.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc/notifications/test_comment_notifications.py
- test/integration/ggrc/notifications/test_data_handlers.py
- test/integration/ggrc/object_owner/test_comment.py
- test/integration/ggrc/services/test_query.py
- test/integration/ggrc/snapshotter/__init__.py
- test/integration/ggrc_basic_permissions/test_audit_rbac.py
- test/integration/ggrc_basic_permissions/test_user_role_column_handler.py
- test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
- test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
> QUICK-FIX test cleanup part 2

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/audits/summary.mustache
- src/ggrc/assets/stylesheets/_modules.scss
- src/ggrc/assets/stylesheets/modules/_audit-summary.scss
Modify chart on Audit Summary tab
UX mockups: https://drive.google.com/corp/drive/u/1/folders/0BxUZsNDMuM58MWgtSVVOMHlUY00
> GGRC-876 Modify audit summary chart

- src/ggrc/assets/javascripts/components/snapshot-loader/snapshot-loader.js
- src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
This PR fixes adding mappings when creating new assessment.
Precondition:
created program, audit
2. While creating a new assessment map object and save assessment
> GGRC-815 Fix mapping new objects on creating new instances

- test/integration/ggrc_workflows/notifications/test_deleted_objects.py
On delete notifiable instances all notifications,
related to that objects should be deleted
> Add unit test assertion

- src/ggrc/assets/javascripts/apps/dashboard.js
- src/ggrc/assets/javascripts/controllers/automapper_controller.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- src/ggrc_workflows/assets/javascripts/components/end_cycle.js
- src/ggrc_workflows/assets/javascripts/components/workflow_active.js
1. Open Program
2. Map Standard to a Program
_Actual result:_ automapped objects tabs don't refresh
_Expected result:_ automapped objects tabs must update counts
_Workaround_: refresh page
> GGRC-410 Refresh counts after automapping

- src/ggrc/assets/stylesheets/modules/_assessment.scss
Quick fix for assessment tabs in https://github.com/google/ggrc-core/pull/5088
> GGRC-909 Quick fix for assessment tabs

- src/ggrc/assets/mustache/base_objects/page_header.mustache
- src/ggrc/assets/mustache/import_export/import_export_buttons.mustache
Open "Import" and "export" in new tabs.
Changes are related to "tree-view" and "header" of page.
> GGRC-1009 Open Data import/export window in new tab

- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/stylesheets/modules/_assessment.scss
**Place additional text to Tooltips**
"Input assesm..." text remove, and question with tooltip "Respond to assessment here. Use comments on the right for free text responses."
> GGRC-910 Add note tooltip for assessment CA

- src/ggrc/converters/query_helper.py
- src/ggrc/migrations/versions/20170203150557_7471e16ebb76_fix_vendors_columns_data_type.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/utils/__init__.py
- test/integration/ggrc/services/test_query_snapshots.py
Precondition:
created program, at least two controls with Effective/Stop Dates, audit
2. Filter control by date (Effective/Stop Date date): no result
Actual Result: Filter is not working correctly for dates in the snapshots on the Audit page
Expected Result: Filter is working correctly for dates (e.g. Effective/Stop Dates) in the snapshots on the Audit page
> GGRC-536 Fix date filtering for Snapshots

- src/ggrc/assets/javascripts/components/datepicker/datepicker.js
Cherry-pick https://github.com/google/ggrc-core/pull/5070 into release branch
> GGRC-382 Fix required label in datepicker

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/mustache/audits/summary.mustache
- src/ggrc/assets/stylesheets/modules/_audit-summary.scss
- src/ggrc/assets/stylesheets/modules/_top-nav.scss
2. Look at Add tab: confirm at the right
3. Create assessment
4. Look at Add tab: confirm moves to the left
_Actual Result_: Add tab moves to the left if add assessment to audit
_Expected Result:_ Add tab should not move to the left if add assessment to audit and should be at the right part
> GGRC-993 Fix issues with HNB on audit page

- test/integration/ggrc_workflows/notifications/test_deleted_objects.py
After notifiable instance deletion, its notifications
updated object_id value to 0, but they should be deleted.
This fix add check for existence of notifications with object_id
equal to instance id or equal to 0.
After instance deletion they should not exist.
> QUICK-FIX Fix unit test with delete notifiable object

- src/ggrc/assets/stylesheets/_z_index.scss
Commit 79568dc set header zindex to 1 from 100 - this sets it back to 100.
> QUICK-FIX Fix dropdown menu

- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
Fix of merge trouble with 'getCounts' function
> QUICK-FIX Fix merge trouble with getCounts function

- src/ggrc/models/relationship_helper.py
- src/ggrc/snapshotter/rules.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/services/test_query_snapshots.py
We decided to cherry-pick back-end part of the #5061 due to:
- @zidarsk8 is unavailable for small amount of time.
- Front-end part of the #5061 is not stable enough.
- Front-end guys need back-end part from #5061 ASAP.
> GGRC-847 Copy of the #5061 back-end part

- src/ggrc/assets/javascripts/apps/base_widgets.js
> GGRC-847 Cherrypick FE changes #5061

- src/ggrc/assets/javascripts/components/show-related-assessments-button/show-related-assessments-button.js
- src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
- src/ggrc/assets/mustache/components/show-related-assessments-button/show-related-assessments-button.mustache
- src/ggrc/assets/mustache/components/tree/tree-node-actions.mustache
- src/ggrc/assets/stylesheets/modules/_info-pin.scss
- src/ggrc/assets/stylesheets/modules/_object-header.scss
- test/selenium/src/lib/constants/locator.py
Add Show Related Buttons for Controls and Objectives Info Pane Pages
> GGRC-1065 Show Assessments button for controls and objectives Info Pane

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-item-details.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-item.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item-details.mustache
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item.mustache
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
Merge https://github.com/google/ggrc-core/pull/5122 first!
This PR adds new preview for mapper items.
> GGRC-1039 new mapper preview

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-item.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item.mustache
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results.mustache
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
This PR adds related assessments button for controls and objectives to the mapper.
> GGRC-1064 mapper related assessments

- src/ggrc/models/inflector.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
- test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
fix human singular/plural & title singular/plural
> GGRC-501 Rename 'Cycle Task Group Object Task' to 'Cycle Task'

- src/ggrc/models/mixins/autostatuschangeable.py
- test/integration/ggrc/models/mixins/test_autostatuschangable.py
Include 'Ready to Review' in Assignable edits in AutoStatusChangeable
> GGRC-599 Bounce Ready to Review Assessment to In-Progress on adding Verifier

- src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
"None" is displayed for related assessments on Dashboard Page
> GGRC-1153 Update Mapped Objects Component to correctly define Query API operation

- src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/mustache/assessments/tree_add_item.mustache
- src/ggrc/assets/mustache/audits/tree_add_item.mustache
- src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-related-information.mustache
- src/ggrc/assets/mustache/documents/tree_add_item.mustache
- src/ggrc/assets/mustache/modals/mapper/base.mustache
- src/ggrc/assets/mustache/modals/mapper/component.mustache
- src/ggrc/assets/mustache/snapshots/tree_add_item.mustache
Conflicts:
src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
> Merge release/0.10-Raspberry into develop

- src/ggrc/utils/__init__.py
- test/unit/ggrc/utils/test_mapping.py
Typo fix, remove unmap:control from assessment
> GGRC-1166 del unmap:control from assessment tmpl

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/tests/test_audit_page.py
This PR fix existing test "test_asmts_generation" according to new assessment generation modal window.
> Change Page Objects according to new assessment generation modal

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls-popover.js
- src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
- src/ggrc/assets/javascripts/components/object-list-item/comment-list-item.js
- src/ggrc/assets/javascripts/components/object-list-item/detailed-business-object-list-item.js
- src/ggrc/assets/javascripts/components/object-list-item/person-list-item.js
- src/ggrc/assets/javascripts/components/object-list/object-list-item.js
- src/ggrc/assets/javascripts/components/object-list/object-list.js
- src/ggrc/assets/javascripts/components/object-popover/object-popover.js
- src/ggrc/assets/javascripts/components/object-popover/related-assessment-popover.js
- src/ggrc/assets/javascripts/components/related-objects/related-comments.js
- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls-popover.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-related-information.mustache
- src/ggrc/assets/mustache/components/object-list-item/comment-list-item.mustache
- src/ggrc/assets/mustache/components/object-list-item/detailed-business-object-list-item.mustache
- src/ggrc/assets/mustache/components/object-list-item/person-list-item.mustache
- src/ggrc/assets/mustache/components/object-list/object-list.mustache
- src/ggrc/assets/mustache/components/object-popover/object-popover.mustache
- src/ggrc/assets/mustache/components/object-popover/related-assessment-popover.mustache
- src/ggrc/assets/stylesheets/components/action-button/_action-button.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/components/object-popover/_object-popover.scss
This PR is a part of the epic for improvements of Related Assessments Popup. 
This PR is based on [PR](https://github.com/google/ggrc-core/pull/5111) and should be merged after it.
> GGRC-892 Add extra component for Comment History

- src/ggrc/converters/base_block.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
- test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
it's new required change request
> GGRC-1028: Add ability to change assignee in cycle tasks via import 

- src/ggrc/converters/base_block.py
- src/ggrc/converters/handlers/snapshot_instance_column_handler.py
- src/ggrc/migrations/versions/20170104100418_4aa9f2ee7969_reattach_urls_evidences_from_comments_.py
- src/ggrc/migrations/versions/20170215144723_2f1cee67a8f3_add_default_assessment_notifications_.py
- src/ggrc/models/comment.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/models/test_assessment.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc_workflows/converters/test_csvs/cycle_task_warnings.csv
- test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Resolved conflicts and update develop migration chain.
Conflict was with renaming "cycle task group object task" to "cycle
task" and adding new tests for "cycle task group object task". The
conflict was resolved by also renaming the new tests.
Conflicts:
test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
> QUICK-FIX Merge raspberry to develop

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-status-filter.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-status-filter.mustache
- src/ggrc/assets/mustache/components/unified-mapper/mapper-toolbar.mustache
- src/ggrc/assets/mustache/modals/mapper/base.mustache
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper-toolbar.scss
This PR adds Active - Draft - Deprecated filter on Unified Mapper
> GGRC-900 filter unified mapper

- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/javascripts/components/show-related-assessments-button/show-related-assessments-button.js
Show Assessments button for SNAPSHOTS of controls and objectives
> GGRC-1156 Assessment button for Snapshots

- src/ggrc_basic_permissions/__init__.py
This PR removes a few unreferenced functions from `ggrc_basic_permissions`.
> QUICK-FIX Remove dead permissions-related code

- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/_helpers.scss
- src/ggrc/assets/stylesheets/modules/_tree-content.scss
**Cannot see in-progress task color**
Color to #E79D2A, font weight to medium
> GGRC-1230 Change workflow task status color

- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
QuickFix: Show filter for Issues and Hide for Audit.
> GGRC-1093 Improve Active/Deprecated/Draft filter

- src/ggrc/assets/javascripts/components/add-object-button/add-object-button.js
- src/ggrc/assets/mustache/audits/summary.mustache
- src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache
- src/ggrc/assets/mustache/components/add-object-button/add-object-button.mustache
1. Go to Audit Summary page
2. Hover on the Create assessment/Create Template: several tooltips are shown
Actual Result: Several tooltips are shown if hover on the Create assessment/Create Template buttons
Expected Result: One tooltip is shown if hover on the Create assessment/Create Template buttons
> GGRC-999 Several tooltips are shown if hover on the Create assessment/Create Template

- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/mappers/mappings-ggrc.js
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/stylesheets/modules/_assessment.scss
- src/ggrc/assets/stylesheets/modules/_attachment-list.scss
- src/ggrc/models/issue.py
- src/ggrc_gdrive_integration/assets/javascripts/apps/gdrive.js
- test/integration/ggrc/converters/test_import_helpers.py
User needs ability to attach documents in issue object (similar to assessments).
> GGRC-1188 Add evidence list to Issue

- src/ggrc/assets/mustache/products/modal_content.mustache
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/migrations/versions/20170213060017_531090f74bb8_update_roles_in_options_table.py
- src/ggrc/migrations/versions/20170222151635_2e049f7d3b0b_update_roles_in_options_table.py
- src/ggrc/models/product.py
replace product_type to product_kind
remove code patch from handler & update options table
> GGRC-863 data migration patch, import-csv product related

- src/ggrc/assets/javascripts/plugins/can_control.js
- src/ggrc/assets/javascripts/plugins/tests/can_control_spec.js
Set empty string for oldText if el[0] is undefined
> QUICK-FIX  for PR #5255. Check element before get an innerHTML

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/migrations/versions/20170219221807_4e7fda17abc7_fix_assessment_contexts.py
- src/ggrc/migrations/versions/20170224202800_341f8a645b2f_fix_assessment_contexts_again.py
This was already merged to master, but adding to the release branch as well. https://github.com/google/ggrc-core/pull/5259
> QUICK-FIX Fix assessment context

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/pbc/workflow_controller.js
- src/ggrc/assets/mustache/assessments/related_issues.mustache
When raising an issue inside assessment it should be mapped to Audit, Assessment and ALL snapshots that are mapped to the assessment.
> GGRC-1206 Fix mapping for related issues

- src/ggrc/converters/query_helper.py
- test/integration/ggrc/services/test_query.py
- test/integration/ggrc/test_csvs/sorting_with_ca_setup.csv
Resolve conflict between CA & Object Attributes
Resolve the CA name clash with Object Attribute name, prefer CA over Attribute
> GGRC-1187  Resolve the CA name clash with Object Attribute name, prefer CA

- src/ggrc/converters/query_helper.py
- test/integration/ggrc/services/test_query.py
- test/integration/ggrc/test_csvs/sorting_with_ca_setup.csv
Reverts google/ggrc-core#5264
This introduces a huge regression with showing Snapshots.
> Revert "GGRC-1187  Resolve the CA name clash with Object Attribute name, prefer CA"

- src/ggrc/models/audit.py
- src/ggrc/models/background_task.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc_risks/models/risk.py
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc/converters/test_ca_import_export.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/generator.py
Add description for status, needed in CSV header
Add the allowed values in the header for status column for all Stateful objects.
> GGRC-1163 Add description for status, needed in CSV header

- src/ggrc/assets/javascripts/components/tree_pagination/tree_pagination.js
This PR fixes changing page issue when typing the page number manually and pressing enter.
> GGRC-1128 Fix paging on enter

- src/ggrc/assets/javascripts/components/dropdown/multiselect-dropdown.js
- src/ggrc/assets/mustache/base_objects/tree_view_filter.mustache
- src/ggrc/assets/mustache/components/dropdown/multiselect_dropdown.mustache
- src/ggrc/assets/stylesheets/components/multiselect-dropdown/_multiselect-dropdown.scss
- src/ggrc/assets/stylesheets/components/tree_pagination/_tree_pagination.scss
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper-toolbar.scss
- src/ggrc/assets/stylesheets/modules/_filters.scss
According to the discussion with K. Koltun the following improvements should be made in dropdown multi select filter:
1. Filter button: regular weight
2. Reset button: border, white color inside
3. Minimize filter
4. Question icon: Black 70 percentage 
5. Background color
6. Minimize controls 
7. Text color + size
8. Highlight color while selecting a value in dropdown
9. White text if hover
10. Rounded corners of the filter and dropdown list
11. Dropdown should overlaps on filter
One more small fix in scope of this ticket - #5268
There are minor UI issues with multiselect control scaling
> GGRC-1324 Improve dropdown multi select filter

- src/ggrc/assets/javascripts/components/modal-connector.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/tests/assessment_model_spec.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_snapshots_spec.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/stylesheets/modules/_tree-content.scss
1. Create a program and map some types of objects 
2. Create Audit 
3. Open create Assessment modal and click Map Objects 
4. Select some object and click Map Selected 
_Actual result_: Titles in Mapped Objects section are empty and after save Asmt you can see links instead of titles in the Edit Modal 
_Expected_: Mapped objects show correct
> GGRC-948 Incorrect display of mapped objects in Edit Assessments modal

- test/integration/ggrc/converters/test_import_assessments.py
This adds tests for the code in commit 42ad1d1fc.
> GGRC-1373 Add import tests for assessment and document context

- README.md
Fixes an obsolete filename in README.md
> DOCS Fix requirements filename in docs

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/templates/admin/index.haml
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/dashboard/index.haml
Last Updated column should be visible by default on My Assessments page in tree view
> GGRC-1280 Last Updated visible by default on My Assessments page

- src/ggrc/converters/query_helper.py
1. Create a GCA with name "Type" on any object
(tested Access groups, GCA type Dropdown)
2. Go to objects tree view, open any object
3. Try to update GCA value on the object's info pane
Actual result: the value updates with an error, see attached screenshots
Expected result: no error
4. On the tree view: try to sort or search by Type
Actual result: getting an error, see attached screenshots
Expected result: no error
> GGRC-1187 GCA named "Type" causes errors on saving, searching and sorting

- src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/models/mappers/sub-tree-loader.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
My Objects and My Work - do not show “Show object not directly mapped”
> GGRC-1357 Dont show sub tree expander for My work/My assessments/All object pages

- DEPLOYMENT.md
> QUICK-FIX Fix outdated version number in a doc

- src/ggrc/assets/javascripts/components/tests/mapper-model_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
Check mapping rules on FE according to [Mapping rules doc](https://goo.gl/rNvqJo)
> GGRC-1233 Unit tests for check mapping rules

- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/mustache/modals/mapper/base.mustache
This PR changes the message for snapshots creation in the mapper.
> GGRC-1125 Change the message for snapshots creation in the mapper

- src/requirements-selenium.txt
- test/selenium/pytest.ini
This PR update requirements for selenium container that decrease test execution time and increase test stability
> QUICK-FIX Update requirements file for selenium container

- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/mustache/modals/mapper/base.mustache
This PR adds auto-refresh on a global search and after changing object type in the dropdown.
> GGRC-1396 Mapper auto refresh

- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
1. Go to My assessments page
2. Look at the tree view: First tier is partially shown
Actual Result: First tier is partially shown in tree view on My assessments page
Expected Result: Objects First tier should shown in tree view on My assessments page
> GGRC-1356 First tier is partially shown in tree view on My assessments page

- src/ggrc/fulltext/sql.py
- src/ggrc/models/mixins/__init__.py
~Depends on #5182~
make it a searchable state Verified
fix filter for Verified~false/true
> GGRC-1137 Assessment: fix VERIFIED state filter

- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
1. Create at least 2 assessments on the audit page
2. Make one of the assessments in Verified state
3. Select Verified in dropdown multi select filter: confirm there is no search results
_Actual Results_: Dropdown multi select filter for Verified state doesn't work
_Expected Result_: Dropdown multi select filter for Verified state should work
Also this PR contains fix for jira-ticket #1319
_Note_: This PR related to PR #5272
> GGRC-1321 Dropdown multi select filter for Verified state doesn't work

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/assessments/tree.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/audits/tree-item-attr.mustache
- src/ggrc/assets/mustache/base_objects/general_info.mustache
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
- src/ggrc/assets/mustache/base_templates/header.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
- src/ggrc/assets/mustache/directives/tree-item-attr.mustache
- src/ggrc/assets/mustache/objectives/tree-item-attr.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
- src/ggrc/assets/mustache/sections/tree-item-attr.mustache
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
**Object state: show it in color**
> GGRC-1136 Change status color for all objects

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree/tree-no-results.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/mustache/components/tree/tree-no-results.mustache
- src/ggrc/assets/stylesheets/modules/_tree-content.scss
1. On my work page select any object and select any state in multi select dropdown
2. If there is no object exist inform a user
> GGRC-1355 Inform users that there is no objects selected filtered in multi select dropdown filter

- src/ggrc/notifications/data_handlers.py
- test/integration/ggrc/notifications/test_data_handlers.py
This PR merges the latest changes from the Raspberry release branch into develop.
Conflicts resolved:
* src/ggrc/notifications/data_handlers.py
> QUICK-FIX Merge raspberry into develop

- src/ggrc/fulltext/attributes.py
- src/ggrc/fulltext/mixin.py
- src/ggrc/fulltext/mysql.py
- src/ggrc/fulltext/recordbuilder.py
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
- test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
- test/integration/ggrc_workflows/models/factories.py
Add filter to cycle by: 
group (title/slug)
group_assignee (name/email)
group_due_date 
task (title/slug)
task_assignee (name/email)
task_due_date
Add filter to cycle task group by: 
task (title/slug)
task_assignee (name/email)
task_due_date
This is new change request.
> GGRC-930 Add custom filter to the cycle and cycle task

- src/ggrc/fulltext/sql.py
This was accidentally re added in a merge conflict resolution.
> QUICK-FIX Remove benchmark in create_record

- bin/check_js_diff_eslint
Check a diff of JS files by using ESLINT
> QUICK-FIX Script for ESLINT check.

- src/ggrc/assets/javascripts/components/assessment/add_comment.js
- src/ggrc/assets/mustache/components/assessment/comment/controls.mustache
- src/ggrc/assets/stylesheets/components/comment/_comment-control.scss
**Scenario:**
1) Align Send Notification checkbox to the left.
2) By default, have the Send Notification checked checked.
> GGRC-1176 Assessments: Move "Send Notification" checkbox to align left and by default checked

- src/ggrc/models/assessment_template.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv
- test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
> GGRC-1364 Rename Default Assessor to Default Assignee

- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/hooks/assessment.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/api_helper.py
- test/integration/ggrc/converters/test_import_csv.py
- test/integration/ggrc/converters/test_import_issues.py
- test/integration/ggrc/models/test_assessment.py
- test/integration/ggrc_basic_permissions/test_audit_rbac.py
- test/integration/ggrc_basic_permissions/test_creator.py
- test/integration/ggrc_basic_permissions/test_reader.py
- test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
- test/integration/ggrc_workflows/notifications/test_monthly_wf.py
To verify this PR try to change mapped audit on Issues and Assessments in any possible way, and it should not be possible.
This PR is dependent on #5356
> GGRC-1114 Prevent Audit field changes on Assessments and Issues

- src/ggrc/assets/mustache/assessments/modal_content.mustache
1) Move Test Plan box under Title field
2) Move Description box under Notes Field
> GGRC-1173 Move description and test plan fields

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/controllers/tests/tree_view_controller_spec.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_query_api_spec.js
- src/ggrc/assets/javascripts/plugins/utils/query-api-utils.js
- src/ggrc/assets/mustache/base_objects/sub_tree_all_related_link.mustache
- src/ggrc/assets/stylesheets/components/sub-tree-expander/_sub-tree-expander.scss
Max number of numbers of 20 items - after 20 we should have a link - to see all -
if listing 10 - if make it more performant we will go with 10
> GGRC-1250 UX: More button on 2d 3d level - show 20 and more

- src/ggrc/models/issue.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/test_csvs/data_for_export_testing.csv
- test/integration/ggrc_basic_permissions/test_csvs/audit_rbac.csv
The test plan field on issues has been update to "remediation plan" and
the change must also be reflected in imports, exports and in filters.
> GGRC-1472 Update Issue test plane field name.

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/directive_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/section.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/mustache/audits/extended_info.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/audits/modal_content.mustache
- src/ggrc/assets/mustache/controls/modal_content.mustache
- src/ggrc/assets/mustache/issues/modal_content.mustache
- src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js
- src/ggrc_risks/assets/javascripts/models/threat.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
- test/selenium/src/lib/constants/element.py
1. Create control
2. Got to Control tab and check header for control title
3. Try to filter by name
_Expected:_ Filter attribute names should be match with column headers
_Scope of this task:_
- revise all filters and column names - and update UI column names to match internal filter name.
> GGRC-519 Filter attribute names schould be match with column headers

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/page/lhn.py
- test/selenium/src/tests/test_audit_page.py
This PR add test that check:
- Snapshoted version of object not found in LHN
- Actual snapshotable object is present in LHN
> QUICK-FIX Test to search snapshots via LHN

- src/ggrc/models/comment.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc/converters/test_export_assessments.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
- test/integration/ggrc_workflows/models/factories.py
~depends on: https://github.com/google/ggrc-core/pull/5444~
1. Navigate to Task Info pane
2. Add comment in Comments tab (e.g. "comment")
3. Filter by "comment": no result
Actual Result: Filter is not working for comments
Expected Result: Filter should work for comments
> GGRC-1248: Filter by comments

- src/ggrc/assets/javascripts/apps/base_widgets.js
In the All objects screen:
There is no selection criteria for Issues
> GGRC-1471 Issue Tab does not exist in all objects

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/mustache/assessments/tree_header.mustache
- src/ggrc/assets/mustache/audits/tree_header.mustache
- src/ggrc/assets/mustache/base_objects/tree_column_selector.mustache
- src/ggrc/assets/mustache/base_objects/tree_column_selector_3bbs.mustache
- src/ggrc/assets/mustache/base_objects/tree_column_selector_body.mustache
- src/ggrc/assets/mustache/base_objects/tree_header.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_header.mustache
- test/selenium/src/lib/constants/locator.py
This PR is related to PR #5192
> GGRC-1302 3bb menu: duplicate "Set visible fields .." back in 3 bb menu

- src/ggrc/models/mixins/__init__.py
Note: @pod2metra will add integration tests for this change in a separate PR, we need this PR to complete #5421 from the user's standpoint.
> QUICK-FIX Add aliases to ChangeTracked mixin

- src/ggrc/converters/autocast.py
- test/integration/ggrc/converters/test_export_assessments.py
depends on: https://github.com/google/ggrc-core/pull/5457
> QUICK-FIX Add tests to filter by Last Updated and Created On aliases

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
> QUICK-FIX Sorting by assignee

- src/ggrc/models/mixins/assignable.py
- test/integration/ggrc/services/test_query/test_basic.py
Contains small fix in assignable.py, in fetching assignees_by_type
Depends on: QUICK-FIX sort_by subproperty add into Person #5470
> QUICK-FIX Add test for sorting Assessments by assignees.

- src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
Preconditions
Audit, Program and Assessment with mapped Control.
Steps:
1) Open Audit page
2) Open Controls tab 
3) Open Control info pane
Actual result: no Assessments button on the pane.
Expected result: Assessments button should be shown on the pane.
> GGRC-1325: Show Assessments button for Snapshots of Controls and objectives

- pylintrc
- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_export_assessments.py
- test/integration/ggrc/converters/test_export_controls.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
~depends on: https://github.com/google/ggrc-core/pull/5485~
> GGRC-1768 control snapshot filter by updated_at and its aliases

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-filter.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-columns-configuration.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-item-attrs.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-items-header.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-filter_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-item-details_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-item_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-items-header_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-toolbar_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper_spec.js
This PR adds unit tests for the Unified mapper.
Closes GGRC-1197 and all sub-tasks: GGRC-1198, GGRC-1236 - GGRC-1239.
> GGRC-1197 Unified mapper tests

- src/ggrc/assets/javascripts/apps/dashboard.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/javascripts/controllers/automapper_controller.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_query_api_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/query-api-utils.js
Preconditions: 
Existing Program, Standard with mapped Section (Program was not mapped to Standard previously)
1) Open Program page.
2) Map Standard to Program.
Actual result: Sections tab was not shown.
Expected result: Sections tab should appear.
> GGRC-410 Retrieve object counts for widgets after mapping

- test/integration/ggrc/converters/test_ca_import_export.py
I could not reproduce the bug described in the ticket but I have added tests for the described bug.
If I have missed anything please let me know how to update the tests to catch the actual bug.
> GGRC-1777 Add test for imports for people CA

- src/ggrc/assets/javascripts/apps/dashboard.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/query-api-utils.js
Looks like karma unit tests started randomly failing: https://github.com/google/ggrc-core/pull/5505
GGRC.Components.modalMapper ".modal-footer .btn-map click" handler sets false to mapper.is_saving FAILED
We won't be able to merge any new PR until this is resolved^
So it's a bit of a blocker
Unit Tests to modified code should be added with a separate [PR](https://gojira.corp.google.com/browse/GGRC-1798)
> GGRC-1788 Failed unit tests

- Dockerfile-selenium
- src/requirements-selenium.txt
This PR specify exact image version of standalone selenium chrome node that aligns w/selenium requirement version and update requirements for selenium docker container.
> QUICK-FIX Update selenium requirements and image version

- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/services/test_query/test_snapshots.py
1. Create a Control.
2. Create global CA of type Map:Person for Controls titled "my custom attribute".
3. Fill in this CA with "user@example.com"
4. Create a Program, map Control to it.
5. Create an Audit in the Program.
6. Navigate to Audit page Controls tab.
7. Filter by `"my custom attribute" = user@example.com`.
Expected result: the Snapshot is displayed.
Actual result: nothing is displayed.
> GGRC-1687 GGRC-944 GGRC-1514 Index Person CA for Snapshots

- Dockerfile-selenium
- src/requirements-selenium.txt
This PR revert back changes merged by this PR #5508 to avoid socket timeout problem in selenium executor.
> QUICK-FIX Revert back version update for selenium container

- src/ggrc/assets/mustache/components/page-header/page-header.mustache
- src/ggrc/assets/stylesheets/modules/_menu.scss
- src/ggrc/templates/base_objects/_page_header.haml
- test/selenium/src/lib/page/dashboard.py
Top menu: Export button - move back into user menu
> GGRC-1791 Move Export button into user menu

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tree_view.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/test_snapshots.py
- Refactored TreeView component for working correctly with the Unified Mapper modal;
- Added pack of methods for working with the TreeView entities on the Unified Mapper modal;
- Added a test for checking that Unified Mapper search not looking for snapshots.
> QUICK-FIX Unified mapper searching test

- src/ggrc/models/control.py
- src/ggrc/models/object_document.py
- src/ggrc/services/common.py
- src/ggrc_gdrive_integration/__init__.py
- src/ggrc_gdrive_integration/models/object_file.py
- src/ggrc_gdrive_integration/models/object_folder.py
- test/integration/ggrc/converters/test_import_controls.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_imported_api_requests.py
- test/integration/ggrc/test_csvs/controls_no_warnings.csv
Allow adding folder to control.
Allow attaching files to this folder.
UX: https://drive.google.com/corp/drive/u/1/folders/0B7_NYFVmb896Z2ZNMWpVay15alE
> GGRC-1806 BE: Allow attachments in Control

- src/ggrc/models/__init__.py
- src/ggrc/models/all_models.py
- src/ggrc/models/inflector.py
- src/ggrc_basic_permissions/models.py
> GGRC-919 Fix model inflector registration

- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_export_assessments.py
- test/integration/ggrc/converters/test_export_controls.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py
This PR is opened bacuse two other opened PR rely on the same commit, and so that they will not block each other, this is now a separate PR that can be merged before either of those other PRs (#5552, #5487)
- Fix import helper function,
- Rename badly named function to match our style guides,
- Fix export help function.
> QUICK-FIX Fix integration test helper functions

- README.md
- src/requirements-dev.txt
This PR was merged into develop: https://github.com/google/ggrc-core/pull/5065
> QUICK-FIX Add ipdbplugin

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/notification/notification_handler.py
This pull request removes recursive calls to DB for cycle task groups and cycle tasks on update.
> GGRC-1868 Performance on cycle task object task start stop procedure

- src/ggrc/assets/mustache/assessments/related-assessments.mustache
Hotfix for Related Assessments tab on Assessment Info page
> GGRC-1808 Update Spinner Loading Indication for Related Assessments

- src/ggrc/snapshotter/helpers.py
> QUICK-FIX Update admin panel snapshot log

- src/ggrc/fulltext/mysql.py
- src/ggrc/models/assessment_template.py
- src/ggrc/models/event.py
- src/ggrc_risk_assessments/models/risk_assessment.py
- src/ggrc_risks/models/risk.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/task_group_task.py
- src/ggrc_workflows/models/workflow.py
Copy of #5023 that was already merged into develop.
> QUICK-FIX Model cleanup 

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
Refresh audit summary page only if total count changed + reduce amount of cycles in JS logic.
Area: Audit
Env: local, ~1400 assessments
Baseline: 6210ms (Scripting time)
Improved: 6138ms (Scripting time)
Diff: ~72ms
When opening Summary tab twice - diff ~ 6s (tab is not reloaded, no extra api requests performed).
> GGRC-1724 Audit Summary rendering takes long time

- src/ggrc/assets/mustache/dashboard/info/get_started.mustache
> GGRC-436 [Create new object] button disappears on My Work page under GR/GE roles

- src/ggrc/assets/mustache/components/page-header/page-header.mustache
- src/ggrc/assets/stylesheets/modules/_header-content.scss
- src/ggrc/assets/stylesheets/modules/_menu.scss
- src/ggrc/templates/base_objects/_page_header.haml
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/dashboard.py
Changes in top bar: 
- replace entity icon with entity type name,
- make title smaller (18px),
- make entity name gray (opacity: 0.5),
- remove icons for items in top bar menu (right side of top bar),
- move administration menu item into dropdown menu,
- fix some issues with improper background for menu items in dropdown
> GGRC-1491 Top Bar redesign

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
There is no way to add/change authorizations on people tab at the program level. User is added to the program by the admin, however cannot assign any roles.
> GGRC-1906 Unable to add role to user in People tab at Program level 

- Dockerfile-selenium
- src/requirements-selenium.txt
This fixed address following items:
- update chrome version to 58
- update chrome driver version to 2.29
- update python packages for testing
> QUICK-FIX Update standalone-chrome and requirements

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
Snapshot tree view menu must have export link that navigates to export page.
> GGRC-1793 Add export link to snapshot tree view 

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
> Revert "GGRC-1793 Add export link to snapshot tree view "

- src/ggrc/models/document.py
- test/integration/ggrc/fulltext/test_total_reindex.py
- test/integration/ggrc/models/test_document.py
* add indexed query to Document model 
* add test on update Document instance using api
> GGRC-1844 update URL title

- src/ggrc/access_control/role.py
- src/ggrc/access_control/roleable.py
- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/handlers/acl.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/reflection.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_acl_import_export.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_imported_api_requests.py
This PR is dependent on #5468 and will be rebased once that one is merged.
Functionality is finished and the only two tests failing are currenly the performance query checks.
> GGRC-1524 Add import and export for people collection CA

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree/tree-item-status-for-workflow.js
- src/ggrc/assets/mustache/components/tree/sub-tree-item.mustache
- src/ggrc/assets/mustache/components/tree/tree-item-status-for-workflow.mustache
- src/ggrc/assets/mustache/components/tree/tree-item.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
2. Add task to Task Group
3. Activate WF
4. On the Active Cycles tab start, finish, verify task
5. Look at the tree view
Actual Result: Workflow: State bubbles are absent on Active Cycles tab in tree view
Expected Result: Workflow: State bubbles should be present on Active Cycles tab in tree view
> GGRC-2001 Workflow: State bubbles are absent on Active Cycles tab in tree view

- src/ggrc/assets/mustache/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc/assets/mustache/components/tree/sub-tree-models.mustache
- src/ggrc/assets/mustache/components/tree/tree-header.mustache
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper-toolbar.scss
- src/ggrc/assets/stylesheets/modules/_import-export.scss
- src/ggrc/assets/stylesheets/modules/_tree-header.scss
- src/ggrc/templates/base_objects/_page_header.haml
- src/ggrc/templates/directives/_import.haml
- src/ggrc/templates/help/_import.haml
- src/ggrc/templates/systems/_import.haml
- src/ggrc/templates/welcome/index.haml
- test/selenium/src/lib/constants/locator.py
2. Create control and map it to the program
3. Go to Controls tab and open "Set visibility dialog"
4. Look at the dialog: "Set fields" button is not shown
5. Hover over the place where button should be: confirm the button appears
Actual Result: "Set fields" button disappears if user doesn't hover over the button
Expected Result: "Set fields" button should be shown and should not disappear
> GGRC-2023 "Set fields" button disappears if user doesn't hover over the button

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unmap-button/unmap-button.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/mustache/base_objects/unmap.mustache
- src/ggrc/assets/mustache/components/assessment/attachments-list.mustache
- src/ggrc/assets/mustache/components/assessment/urls-list.mustache
- src/ggrc/assets/mustache/components/unmap-button/unmap-button.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/modules/_object-header.scss
1. Create control
2. Create program, 
3. Map Conrol to program
4. Go to Control's tab> Info pane> Click 3 dot's menu
Actual Result: Unmap button is not displayed in 3 dot's menu on Info pane
Expected Result: Unmap button should displayed in 3 dot's menu on Info pane
> GGRc-1887 Show unmap button in 3 dots menu

- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
1. have program, control, audit, assessment which is generated based on control
2. On the program page go to Controls tab
3. Expand sublevel and expand "Show objects not directly related"
4. Click on Assessment tier
Actual Result: "Uncaught TypeError: Cannot read property 'map' of undefined" error occurs if click on Assessment in sublevel
Expected Result: no error is shown
> GGRC-2041 "Uncaught TypeError: Cannot read property 'map' of undefined" error occurs if click on Assessment in sublevel

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/controls/contacts.mustache
- src/ggrc/assets/mustache/controls/info.mustache
This makes sure revisions with old contacts are displayed correctly in snapshots. It also addresses a minor issue with URL displays in control info panes.
> GGRC-2025 Fix legacy contacts

- README.md
> QUICK-FIX Fix requirements filename in docs

- src/ggrc/assets/javascripts/components/tree/tree-item-map.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/mustache/components/tree/tree-item-map.mustache
1. On the audit page create assessment
2. Click Map button twice in the first tier: confirm Unified Mapper window is duplicated
_Actual Result_: Unified mapper window is duplicated if click twice on Map button
_Expected Result_: Unified mapper window should not duplicated if click twice on Map button
> GGRC-1199 Unified mapper window is duplicated if click twice on Map button

- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
Change title `comments` in cycle task view to `task comments`
> GGRC-2000 Frontend: Change title `comments` in cycle task view

- src/ggrc/settings/default.py
This is a late version update missed after the previous release.
> QUICK-FIX Bump version to 0.10.15-Raspberry

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/javascripts/components/unmap-button/unmap-person-button.js
- src/ggrc/assets/javascripts/controllers/automapper_controller.js
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
Test Case 1.
2. Go to People tab and Map person to program
3. Navigate to Person Info pane and select Unmap in 3 bb's menu
4. Click Unmap
Actual Result: If click unmap button to unmap newly mapped Person, query is not run and Person is not unmapped from program. See screenshot-1.png
Expected Result: If click unmap button to unmap mapped Person, Person should be unmapped from program.
Note: after mapping a new person page refresh is needed to unmap person
Test case 2.
2. Go to People tab and Map person to program
3. Refresh the program page
4. Navigate to Person Info pane and select Unmap in 3 bb's menu
5. Click Unmap button
Actual Result: A message that person is unmapped successfully is displayed but Info pane of …
> GGRC-2035 Fix issues with unmap person

- src/ggrc/assets/javascripts/components/assessment/attachments-list.js
- src/ggrc/assets/javascripts/components/assessment/tests/attachments-list_spec.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/js_specs/components/gdrive_picker_launcher_spec.js
- src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
1. Create assessment on the audit page
2. Add verifier
3. Fill all the mandatory fields if any and complete assessment 
4. When assessment is "ready for review", add evidence
Actual Result: There is no message that assessment moves from "ready for review" to "in progress" while attaching evidence
Expected Result: Should be a message that assessment moves from "ready for review" to "in progress" while attaching evidence
> GGRC-1762 There is no message that assessment moves from "ready for review" to "in progress" while attaching evidence 

- src/ggrc/assets/mustache/components/assessment/attachments-list.mustache
- src/ggrc/assets/mustache/components/assessment/urls-list.mustache
- src/ggrc/assets/stylesheets/components/action-toolbar/_action-toolbar.scss
- src/ggrc/assets/stylesheets/components/flexbox-layout/_flexbox-layout.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
The url/text comes out of the assigned instead of wrapping or shown in a more cleaner way. We are seeing several of this instances occurring, developer and QA team needs to ensure long text/urls are tested through the app
> GGRC-2126 Overflow of text in fields

- src/ggrc/automapper/__init__.py
- src/ggrc/builder/__init__.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/models/assessment_template.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/comment.py
- src/ggrc/models/mixins/autostatuschangeable.py
- src/ggrc/models/mixins/clonable.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/services/common.py
- src/ggrc/services/signals.py
- src/ggrc/snapshotter/listeners.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/notification/__init__.py
Just housekeeping stuff.
Moved out of #5614 as there are no dependencies with it.
> QUICK-FIX Reduce cyclic imports

- src/ggrc/assets/javascripts/tests/permission_spec.js
Relates to this PR https://github.com/google/ggrc-core/pull/5648
> GGRC-2059 Unit tests for RBAC at FE - "Unable to add role to user in People tab at Program level" 

- src/ggrc/assets/mustache/issues/modal_content.mustache
The UI field name was updated to test plan but not in the helptext
> GGRC-2022 Field for issues corrected but not in helptext 

- src/ggrc/app.py
- src/ggrc/converters/query_helper.py
- src/ggrc/services/common.py
- src/ggrc/services/search.py
- src/ggrc/utils/error_handlers.py
- test/integration/ggrc/models/mixins/test_with_similarity_score.py
- test/integration/ggrc/services/test_collection_post.py
- test/integration/ggrc/services/test_common.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/services/test_response_codes.py
- test/integration/ggrc/services/test_search.py
- test/integration/ggrc_workflows/test_api_calls.py
> GGRC-525 Return JSON in HTTP400

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/regex.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/factory.py
- test/selenium/src/lib/page/modal/set_fields.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest/template/custom_attribute_definition.json
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_admin_dashboard_page.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_people_groups_page.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_risk_threats_page.py
- test/selenium/src/tests/test_snapshots.py
- test/selenium/src/tests/test_unified_mapper.py
- test/unit/test_selenium/test_constants_regex.py
This PR redesign exists 4 test-cases to parametrized scheme in scope of  **test_audit_contains_snapshotable_control** and **test_update_snapshotable_control_to_latest_ver** and add new 4 test-cases for Controls with all types of Custom Attributes parametrized.
```Python
src/tests/test_snapshots.py::TestSnapshots::test_audit_contains_snapshotable_control[Audit contains snapshotable Control after updating Control]
src/tests/test_snapshots.py::TestSnapshots::test_audit_contains_snapshotable_control[Audit contains snapshotable Control after deleting Control]
src/tests/test_snapshots.py::TestSnapshots::test_audit_contains_snapshotable_control[Audit contains snapshotable Control after updating Control with CAs]
src/tests/test_snapshots.py::TestSnapshots::test_audit_contains_snapshotable_control[ …
```
> QUCIK-FIX Parametrized test of shapshotable control with custom attributes all types

- src/ggrc/fulltext/recordbuilder.py
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/cycle_task_group.py
Speed up assessment generation. 
single assessment at master: 
single assessment at PR:
> GGRC-2174 improve performance for assessment generation 

- test/integration/ggrc/api_helper.py
- test/integration/ggrc_basic_permissions/test_auditor_filter.py
relates to frontend fix https://github.com/google/ggrc-core/pull/5662
> GGRC-2131 Integration tests: GC as Auditor in Audit and doesn't see Audit in Global Search

- src/ggrc/assets/mockups/mockup_base_templates/info_panel/issues_list.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/audits/modal_content.mustache
- src/ggrc/assets/mustache/audits/summary.mustache
- src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache
- src/ggrc/assets/mustache/base_templates/url_list.mustache
- src/ggrc/assets/mustache/components/add-issue-button/add-issue-button.mustache
- src/ggrc/assets/mustache/import_export/create_template.mustache
- src/ggrc/assets/mustache/import_export/export.mustache
- src/ggrc/assets/mustache/import_export/import.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/components/action-button/_action-button.scss
- src/ggrc_gdrive_integration/assets/mustache/gdrive/auth_button.mustache
- src/ggrc_risks/assets/mustache/risk_objects/tree_footer.mustache
- src/ggrc_workflows/assets/mustache/wf_objects/tree_footer.mustache
Remove + and other icons in buttons.
> GGRC-1412 Button colors (update of styles)

- src/ggrc/assets/javascripts/components/sort_by_sort_index/tests/sort_by_sort_index_spec.js
- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/controllers/tests/summary_widget_controller_spec.js
- src/ggrc/assets/javascripts/models/tests/isOverdue_mixin_spec.js
Precondition:
have program, control, audit, at least 5 assessments created on the audit page
1. Go to audit summary page and look at the pie chart
Actual Result: Pie chart is cut off 
Expected Result: Pie chart should not be cut off
> GGRC-2011 Audit summary page: Pie chart is cut off

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_snapshots.py
This PR depends add 1 parametrized test (3 test-cases) in a scope of Assessment generation procedure via UI.
```Python
src/tests/test_audit_page.py::TestAuditPage::()::test_asmts_generation[Assessments generation without Assessment Template]
src/tests/test_audit_page.py::TestAuditPage::()::test_asmts_generation[Assessments generation based on Assessment Template without LCAs]
src/tests/test_audit_page.py::TestAuditPage::()::test_asmts_generation[Assessments generation based on Assessment Template with LCAs]
```
> QUICK-FIX Test parametrized assessments generation
