src/ggrc/assets/javascripts/models/mappings.js
Typo was causing errors when attempting to map Contracts to Clauses
=> CORE-686 fix _canonical key for Clause mappings

src/ggrc_workflows/notification/__init__.py
If there were no overdue tasks the API failed with an error.
=> CORE-888 notify_emaildigest API call was failing

src/ggrc/assets/mustache/requests/modal_content.mustache
This makes the assignee field in the request modal the same as the assignee field in the request tree.
=> CORE-854 Auditor should be able to reassing Request

src/ggrc_workflows/__init__.py
This solves the issue in the story and makes creating new cycles more consistent (cycle is created if start_date <= today < end_date), but we are far away from the having the behaviour in Kostya's updated sheet: https://docs.google.com/a/reciprocitylabs.com/spreadsheet/ccc?key=0Avyi_GigOIL5dGlMVlBOT0VST2U2UjNXQUF3dVRPaXc&usp=gmail#gid=122
=> CORE-795 Workflow cycles sometimes don't activate

src/ggrc_basic_permissions/migrations/versions/20141217235626_51e046bb002_ensure_all_audit_leads_have_program_.py
We need this in the patch because otherwise we'll need to reverse migrations in the next release...
From https://github.com/reciprocity/ggrc-core/pull/2119:
This moves the 'Ensure all Audit Leads have Program Editor role or better' migration from the ggrc into ggrc_basic_permissions. This is because running db_migrate on an empty db fails to execute the delete clause because the user_roles table does not exist yet.
=> db_migrate was failing because roles table was not created

README.rst
this was removed by accident when updating the readme file for ansiblethis was removed by accident when updating the readme file for ansible.
=> put back the first line to readme file

src/ggrc_workflows/assets/javascripts/apps/workflows.js
@sasmita514 this should fix the issue you were having - you can merge it because it's against your branch.
By the way, I think your code will a lot more readable if you don't write callbacks like:
```
dfd.then(function(s){
s.refresh().then(function(refreshed_s){
...
})
})
```
but
```
dfd.then(function(s){
return s.refresh()
}).then(function(refreshed_s){
...
});
```
Or in your case
```
GGRC.Models.Search.search_for_types('', ['Workflow'], {contact_id: GGRC.current_user.id})
.then(function(result_set){
var wf_data = result_set.getResultsForType('Workflow');
//FIX ME Load data 10 each time
var refresh_queue = new RefreshQueue();
refresh_queue.enqueue(wf_data);
refresh_queue.trigger().then(function(options){
var wf, i, tasklist;
for (i = 0; i < options.length; i++){
wf=options[i]; …
```
=> Fix task mappings

src/ggrc/assets/mustache/requests/tree.mustache
@bmomberger-reciprocity Do you agree with this change. I considered adding auditor_states into if_can_edit_request, but I think auditor should be able to edit request in all states, can you confirm?
**Please don't merge this yet** We need to finish regression testing first.
=> CORE-919 External auditor can see "Submit responses" button

src/ggrc/services/common.py
In the interest in tracking down why responses from the server take multiple seconds while the underlying query and serialization take half a second, I'm adding benchmarking to the creation of the response.
=> Add benchmarking for response creation/dispatch

src/ggrc/converters/systems.py
My PR https://github.com/reciprocity/ggrc-core/pull/2128 caused this regression. This change should make sure model_class is properly set for both system and process.
=> CORE-957 System import on Program page fails

src/ggrc/assets/javascripts/models/mappings.js
This bug was caused by: https://github.com/reciprocity/ggrc-core/pull/2154 which removed the `program_authorizations` line from mappings.js.
=> CORE-976 Script error when creating audit

src/ggrc/assets/mustache/dashboard/object_widget.mustache
Dashboard page shouldn't have info header.
=> my-work/dashboard header fix, CORE-994

.gitignore
Some editors (like my emacs setup) automatically compile sass files. This produces some debris.
=> gitignore sass autocompilation cruft

src/ggrc_basic_permissions/__init__.py, src/ggrc_basic_permissions/contributed_roles.py, src/ggrc_basic_permissions/migrations/versions/20150123215041_3bb32fb65d47_make_audit_role_implications_to_private_.py
This PR creates context implications under thses circumstances:<br>* A Response is mapped to a private program<br>* The private program is not the same program as the Audit's program<br>* An implication does not already exist to this Program from the Audit<BR><BR>The implication grants ProgramReader for all authorized people to the source Program, and AuditProgramReader for all authorized people in the Audit containing the mapped Response.<BR><BR>When all mappings from all Reponses in the parent Program to the other Program are destroyed, the context implication is removed.
=> CORE-323 grant private Program read permissions when mapped from a Response

src/ggrc/fulltext/mysql.py
I forgot to add this in when adding secondary contact columns to objects.  This extends the My Work search query to also check when user is the secondary contact.
=> CORE-329 add objects to My Work when user is secondary contact

src/ggrc/assets/mustache/people/modal_content.mustache
It's not a required attribute.
=> Removed the asterisk next to name for person modal.

src/ggrc/assets/javascripts/controllers/dashboard_controller.js
@vladan-mitevski The script error was caused because dropdown_height is not defined anywhere. I have tried adding $dropdown.height(), but the .mid-pos class just breaks positioning when there is no vertical space, so I removed it completely.
=> Fix script error when top nav dropdown is shown

src/ggrc/assets/javascripts/controllers/info_widget_controller.js, src/ggrc/assets/mustache/dashboard/info/info.mustache, src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache, src/ggrc/assets/stylesheets/_common.scss
This code
- Filters workflows with current cycle/tasks
- Sorts list of currect-workflows ascending  order  w.r.t first end date.
- Shows only first 5 workflows initially
- Have a show/hide link to show all workflows, if the workflows are less than 5, this option is hidden
-minor % bug fixes
=> Updated code to show only top 5 workflows in dashboard, CORE-959

src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_objects/tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_groups/tree.mustache
I've added the needs work label because we are planning to discuss these changes later today.
=> Show Cycle Tasks above Cycle Objects in Cycle view

src/ggrc/assets/mustache/base_objects/page_header.mustache, src/ggrc/assets/mustache/programs/page_header.mustache
The original  text "My Dashboard" was not covered by the current title. Removed the original text which is not used anywhere.
=> Fixed title issue-CORE-1026

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/js_specs/generated/ggrc_filter_query_parser_spec.js, src/ggrc/assets/js_specs/models/cacheable_spec.js, src/ggrc/assets/js_specs/models/display_prefs_spec.js, src/ggrc/assets/js_specs/models/local_storage_spec.js, src/ggrc/assets/js_specs/models/mappers_spec.js, src/ggrc/assets/js_specs/spec_helpers.js
more to go but this is a good start
Also, can.Model.Cacheable.refresh() (as distinct from can.Model.Cacheable.prototype.refresh) was removed since it didn't work at all.
=> Partial tests around can.Model Cacheable

src/ggrc_gdrive_integration/assets/js_specs/models/gdrive_models_spec.js
This test should be fixed, but since it just randomly fails, i have been unable to fix it.
Removing this test will make sure there are no random alarms on PR by travis.
=> Remove gdrive test that randomly fails

provision/roles/ggrc/tasks/main.yml
Installing npm packages fails in certain circumstances (see #2118). Moving these sections to the end prevents aborting subsequent provisioning operations.
I've tested this on Windows and provisioning worked well, right up before failing to install npm modules. Since those were at the end anyway, there's no longer a need to comment out the npm sections, and if we figure out what causes the npm install failure, we won't have to uncomment them.
Here's the log.
```
Welcome to your Vagrant-built virtual machine.
Last login: Fri Sep 14 06:23:18 2012 from 10.0.2.2
vagrant@precise64:~$ echo 'localhost ansible_connection=local' >/tmp/local-inventory
vagrant@precise64:~$ sudo apt-get update
Ign http://us.archive.ubuntu.com precise InRelease
[...]
Get:65 http://us.archive.ubuntu.com …
```
=> Move npm sections to end of tasks main.yml

src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/javascripts/models/display_prefs.js, src/ggrc/assets/js_specs/models/display_prefs_spec.js
@arraystudio wouldn't it make more sense to allow sorting of the navbar, but preserve the order through page refreshes?
(fixes CORE-1081)
=> horizontal navbar is now nicely sortable

src/ggrc_workflows/services/workflow_date_calculator.py, src/tests/ggrc/test_workflow_date_calculator.py
An alternate approach to #2268 as a solution for CORE-1098.
In summary, when the workflow has no tasks None will be returned for start date.
All other methods that take starting or relative dates will return None when the basedate/start_date, etc. is None (which will be the case when calculating for a workflow with no tasks).
=> Handle case when workflow has no tasks.

src/ggrc/assets/mustache/dashboard/object_widget.mustache
Hey @vladan-mitevski some of these icons were removed in https://github.com/reciprocity/ggrc-core/pull/2248 was there a reason for removing them?
=> CORE-1159 Re-adding missing icons for widget headers

src/ggrc/assets/javascripts/controllers/info_widget_controller.js, src/ggrc/assets/mustache/dashboard/info/info.mustache
This change makes sure task filters are inserted into DOM after the
tasks are loaded.
=> CORE-1033 Fix Script on my dashboard

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/stylesheets/_modal.scss, src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache, src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
Debugging CORE-1194 reveals the cause to be the markup of the `ggrc-gdrive-folder-picker`: a `<label>` is needed  instead of the `h6`. Making the change looks great in the modal, but the same `ggrc-gdrive-folder-picker` is used in info tabs and tree info panes, whose field labels are h6's - [CORE-1220](https://reciprocitylabs.atlassian.net/browse/CORE-1220).
Hence the surgical fix of putting the `label` just around the icon, instead of it replacing the `h6`.
=> Cosmetic changes + fix CORE-1194

src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/mustache/audits/info.mustache
This fixes the script error in gdrive modals and adds audit/info.mustache to audit info page instead of base_objects/info.mustache.
=> CORE 1213 and some other audit fixes

src/ggrc/assets/javascripts/controllers/quick_form_controller.js, src/ggrc/assets/mustache/requests/info.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
quick_form was refreshing every instance by default which makes no sense inside tree views. This change makes quick_form force a refresh only inside info.mustache files.
With this PR I got the number of requests made by the new my dashboard with 250 tasks from 500+ to a bit over 100 - a significant improvement, but I think this can be further improved by investigating how the workflows are being loaded. There are still a bunch of /api/cycle requests not being batched together.
=> CORE-1195 Reduce the number of requests sent on my dahsboard

src/ggrc/assets/javascripts/apps/business_objects.js
Only lines 275 and 397-405 are significant. The reordering of hash keys is just to match the order in the `base_widgets_by_type.Audit` array.
=> Rename and reorder Audit tabs. Fix CORE-1283.

src/ggrc/assets/mustache/base_objects/tier2_content.mustache, src/ggrc/assets/mustache/controls/tier2_content.mustache, src/ggrc/assets/mustache/directives/tier2_content.mustache, src/ggrc/assets/mustache/documents/tier2_content.mustache, src/ggrc/assets/mustache/objectives/tier2_content.mustache, src/ggrc/assets/mustache/people/tier2_content.mustache, src/ggrc/assets/mustache/programs/tier2_content.mustache, src/ggrc/assets/mustache/sections/tier2_content.mustache, src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
Advanced search and all map modals can't load the file with "\" in the tier-2 content file.
Instead of {{#if_helpers "\
#is_allowed" "view_object_page" instance "\
or" options.allow_mapping "\
or #is_allowed" "update" instance}}
it is advised to write a mustache helper for the purpose.
=> Reverting changes by pull request 2353, CORE-1310

src/ggrc/assets/mustache/base_objects/tier2_content.mustache, src/ggrc/assets/mustache/controls/tier2_content.mustache, src/ggrc/assets/mustache/directives/tier2_content.mustache, src/ggrc/assets/mustache/objectives/tier2_content.mustache, src/ggrc/assets/mustache/people/tier2_content.mustache, src/ggrc/assets/mustache/programs/tier2_content.mustache, src/ggrc/assets/mustache/sections/tier2_content.mustache, src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
Ok so this is now a mess. We need somebody with high git-fu to fix it. @zidarsk8 or @Smotko maybe?
1) All these changes are needed: https://github.com/reciprocity/ggrc-core/pull/2353
2) But this PR killed them: https://github.com/reciprocity/ggrc-core/pull/2356
So now there is a merge conflict.
PS: @sasmita514 making a new mustache helper for this use-case doesn't solve anything because we've already got `if_helpers` and its replacement wouldn't be any easier to use.
PPS: if I do a rebase locally, all changes from the original PR vanish because, well, that's what the tree says. Git just fast-forwards because hey, it looks fast forwardable.
=> CORE-1199: don't show cog icon when not needed

src/ggrc/assets/stylesheets/_common.scss
- When total % becomes 100%, there is no space for right margin. So removed the right margin.
=> Dashboard task-progress bar fix, CORE-1315

src/ggrc/assets/mustache/dashboard/object_widget.mustache
toggle buttons really shouldn't navigate away from the current page
=> update href links to javascritp://

src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js
After the refactor, it no longer makes sense for filter hiding code to stay in the dashboard widgets controller.
=> filter hiding code belongs in TreeView now

src/ggrc/assets/javascripts/mustache_helper.js
Removed 'Response Contact' label and changed wording of 'Contact' to 'Audit Lead' for audit dashboard
=> Fixed for audit dashboard

src/ggrc/assets/mustache/audits/info.mustache, src/ggrc/assets/mustache/base_objects/contacts.mustache
This fix doesn't work for Program objects. 
Program will be handled in a separate issue CORE-600.
=> Added (Disabled) keywords next to disabled owners in the info widget

src/ggrc/assets/javascripts/controllers/modal_selector_controller.js, src/ggrc/assets/mustache/base_objects/tree_header.mustache, src/ggrc/assets/mustache/controls/tree_footer.mustache, src/ggrc/assets/mustache/objectives/tree_footer.mustache, src/ggrc/assets/mustache/sections/tree_footer.mustache, src/ggrc/assets/mustache/systems/tree_footer.mustache
@arraystudio what do we do with sections? They have two different sets of import/export links. For Clauses and for Sections.
=> CORE-962: move import/export links to header

src/ggrc/assets/javascripts/controllers/info_pin_controller.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js
I found two separate issues:
Commit 1: Fixes the case when the tree list is loaded, but the active tab has changed.
Commit 2: Fixes the case where the users switches tabs before the animation completes.
=> CORE 1392 Info pane not going away on tab change

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js
having full objects in the filters broke full text search. 
full text search now handles just text.
=> skip objects

src/ggrc/migrations/versions/20150227143259_1f7d8208aff2_add_control_assessments.py, src/ggrc/models/all_models.py, src/ggrc/models/control_assessment.py, src/ggrc/models/mixins.py
This adds a control assessment object on the db side, but it doesn't hook it up on the frontside. We might also need a control_assessment_objects table to store all the mappings. Look at any other object in the app to see how all of this could be accomplished.
The PR also contains the TestPlanned mixin that should be added to a bunch of other objects.
Hint: for generating a table based on the object you can use the command `python ggrc/migrate.py ggrc revision --autogenerate -m "Add Control Assessments"`, but be warned that this will add columns/fixes that you don't want, so make sure you edit the created migration file.
=> Add ControlAssessment object

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/base_objects/tree_header.mustache
As per Kostya:
> here is the full list of the pages with the object types that should be imported/exported:
> 1. Regulation page
> – Sections
> – Controls
> – Objectives
> 2. Contract pate
> – Clauses
> – Controls
> – Objectives
> 3. Policy page
> – Clauses
> – Controls
> – Objectives
> 4. Standard page
> – Sections
> – Controls
> – Objectives
> 5. Program page
> – Controls
> – Objectives
> – Systems
=> CORE-962: finally proper correct import/export buttons

src/ggrc_workflows/services/workflow_date_calculator.py
breaks when activating a one time workflow with the following task groups and tasks
=> fix invalid dates while starting a one time cycle

src/ggrc/services/common.py
before, the app said "If-Match is required." even if "If-Match" was present and only "If-Unmodified-Since" wasn't in the headers.
=> response should tell you which header item is missing

src/ggrc/assets/javascripts/controllers/advanced_search_controller.js, src/ggrc/assets/javascripts/controllers/modal_selector_controller.js
This fixes the two huge regressions caused by https://github.com/reciprocity/ggrc-core/pull/2557
@hyperNURb please review this and also be more diligent when refactoring code - adding that var was the right thing to do, but it caused a major breakage elsewhere in the app - a simple search/grep would prevent this from happening.
=> CORE-1581 Script error when searching for objects to map

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/stylesheets/_widget.scss
This should help with action list breaking into multiple lines, but it
might also make titles too small in some cases (subtrees without any
actions). See CORE-1588 for a longer discussion. 
@vladan-mitevski do you have any better ideas?
=> CORE-1588 Makes action list larger instead of the title

src/app.yaml.dist
Based on the discussion with @prasannav7, basic scaling might be a better fit for our app. Main benefits: no 60s limit for http requests, no 10min limit for task queues.
More info here: https://cloud.google.com/appengine/docs/python/modules/#scaling_types
This PR is deployed here: https://grc-epic-2.appspot.com/
=> Experimental move from automatic scaling to basic scaling

src/ggrc_gdrive_integration/assets/javascripts/controllers/gdrive_workflows_controller.js
We do some undocumented stuff when opening the dialog for gDrive pickers. This broke when, I'm assuming, Google ran uglify on their source again. 'picker.A' became 'picker.Ab'.
Our hack should now be more future proof.
=> CORE-1627: script error when opening gDrive picker

src/ggrc/migrations/versions/20150411175351_4d690ff85863_add_get_to_event_table.py, src/ggrc/models/event.py
trying to login with a new user and email, creates a an entry in the events table with empty action column. 
and it's showing annoying warinings while testing
/vagrant-dev/opt/dev_virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py:435: Warning: Data truncated for column 'action' at row 1
cursor.execute(statement, parameters)
ps: i'm not sure of the correct fix would be to remove the get entries from the events table, but this fix makes more sense, since creating a new user can be done with GET and not POST.
=> Add GET method to action column in events table

bin/run_pytests, src/tests/ggrc/__init__.py
This PR changes two things:
- before each test runs, the test db is emptied
- the test db actually contains all the tables it's supposed to
=> Improve how tests handle database

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/controllers/modal_selector_controller.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/save_queue.js, src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_base_modal.mustache
This PR basically transforms this:
Into this:
The benefit is that the server is not spammed by over 9000 POST/PUT requests. Now the app will dispense up to 3 requests at a time and only fire new ones when those were resolved.
This also opens the door for us to create a new api endpoint that handles POST/PUT requests in batch. But this feature is out of scope for now.
=> CORE-1002 Add SaveQueue for batching POST/PUT requests

src/ggrc/assets/javascripts/models/mappings.js
Users were not able to map some object types via LHN.
ref: CORE-1649
=> CORE-1649 Fix canonical mappings for Issue object

src/ggrc/assets/mustache/control_assessments/modal_content.mustache, src/ggrc/models/control_assessment.py
This isn't pretty but it works, because our client side verification checks only if the audit attr exists.
ref: core-1643
=> CORE-1643 Fix edit control assessment modal

README.md
The link should point to the develop branch, not the last branch that got pushed to the repository.
=> Fix travis link in README.md

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/controllers/info_pin_controller.js, src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache, src/ggrc/assets/mustache/base_objects/info.mustache, src/ggrc/assets/mustache/controls/info.mustache, src/ggrc/assets/mustache/objectives/info.mustache, src/ggrc/assets/mustache/policies/info.mustache, src/ggrc/assets/mustache/processes/info.mustache, src/ggrc/assets/mustache/products/info.mustache, src/ggrc/assets/mustache/programs/info.mustache, src/ggrc/assets/mustache/sections/dropdown_menu.mustache, src/ggrc/assets/mustache/sections/info.mustache, src/ggrc/assets/mustache/systems/info.mustache
When a `Reader` user was given permissions to toy with a Program, they couldn't access the menu to unmap objects they mapped. Now they can.
=> CORE-1632 Let users unmap objects they mapped

src/ggrc/assets/javascripts/controllers/quick_form_controller.js
This happens because we send multiple requests at the same time. I've talked to @Smotko and @arraystudio and we agreed that solution should be like on Github checkboxes - disable them until request is successful.
=> CORE-1676: Allows checking one task at the time.

src/app.yaml.dist
We don't have the `/_ah/start` endpoint set up so this setting in not needed.
=> QUICK-FIX Disable request warmup

src/ggrc_workflows/notification/data_handler.py, src/tests/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py
- Add the declined task data to the main notifications object
- Add test for declined notifications.
=> CORE-1704 Add declined tasks data to notifications

src/ggrc_workflows/notification/__init__.py, src/ggrc_workflows/notification/data_handler.py, src/ggrc_workflows/templates/notifications/email_digest_content.html
Since workflows can have any number of owners and not just one, we need
to make sure all of them will get the correct notifications. We also
removed the "by xyz" part in the notifications until it is decided if
that part should display just one owner or list them all.
=> CORE-1741 Fix notifications for multiple workflow owners

src/ggrc/assets/javascripts/models/mappings.js
We need to filter out those requests that don't have the control mapped.
=> CORE-1754 Fix Control -> Requests mappings

src/ggrc/models/control.py
Audit object wasn't cascading properly on delete which caused deletion
of controls to fail. We could just add cascade = 'all, delete-orphan'
on the audit_objects relationship, but it's cleaner to just add the
auditable mixin which basically does exactly that.
=> CORE-1759 Fix Control deletion

src/ggrc_workflows/notification/notification_handler.py, src/tests/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py
Notication dates should be compared to current date not current time.
That can cause todays notifications to skip creation because they would
appear overdue.
- Make notification handler compare only the date part of current time
- Fix tests to include times different than 00:00:00
Fixes: CORE-1717 and CORE-1718
=> CORE-1718 Fix notifications for end date change

src/ggrc/assets/mustache/control_assessments/modal_content.mustache, src/ggrc/assets/mustache/issues/modal_content.mustache
Missing fields are added into modals. Check and add respective fields into DB.
Fields that are added:
- Assessment URL / Issue URL *(respectively)*
- Reference URL *(for both objects)*
- Effective date *(for both objects)*
- Stop date *(for both objects)*
=> CORE-1715 Adding missing fields in Assessments and Issues modal

src/ggrc_workflows/notification/data_handler.py, src/ggrc_workflows/views/__init__.py, src/tests/ggrc_workflows/notifications/test_deleted_objects.py, src/tests/ggrc_workflows/notifications/test_middle_level_one_time_wf.py, src/tests/ggrc_workflows/notifications/test_recurring_cycles.py, src/tests/ggrc_workflows/test_api_calls.py, src/tests/ggrc_workflows/test_basic_workflow_actions.py
If the object was delete after notification entry was created the entry
is invalid and should be ignored.
=> CORE-1777 Fix notifications for deleted objects

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/mustache/base_objects/description.mustache, src/ggrc/assets/mustache/base_objects/test_plan.mustache, src/ggrc/assets/mustache/control_assessments/info.mustache, src/ggrc/assets/mustache/issues/info.mustache
Missing fields are added into info widget.
Fields that are added:
- Test plan *(for Assessment and for Issues info widget)*
- URLs
- Notes
- Description
=> CORE-1714 Added missing fields into info widget for Assessments and Issus

src/dev-requirements.txt, src/ggrc/notification/__init__.py, src/ggrc_workflows/views/__init__.py, src/requirements.txt
Freezegun seems to cause key errors with handling dates even when it's not
used, so we will only have it in the dev enviroment for testing.
This commit will break the dates in show pending notifications, which
will not be relative to the send date anymore. That is still better than
having server errors while trying to send digest notifications.
=> CORE-1783 Remove freezegun from production requirements

src/ggrc/assets/javascripts/mustache_helper.js
@Swizec I think I finally understood what went wrong with `_transient`. My understanding was that it automatically was `can.Observe` instance but it isn't.Could you please confirm this works?
Thanks!
=> CORE-1771 Prevent infinite recursion when opening New Audit modal

src/ggrc/assets/javascripts/models/mappers.js
If you deleted object A that was mapped to object B,
then tried to delete object B without refreshing the page
it caused an error because there was a hanging reference left.
Now get_instance_from_mapping returns undefined when
a hanging reference is encountered instead of erroring out.
This is be easier for the calling code to deal with.
=> CORE-1775 Fix script error when deleting objects

bin/run_pytests
Sniffer and freezegun do not work together. The first sniffer run, the
tests pass, after a file change on the second run, freezegun fails to
import and datetime.timedelta is gone.
=> QUICK-FIX Replace sniffer for running tests

src/cron.yaml, src/ggrc_workflows/views/__init__.py
We need to make sure one cron job is executed after the previous one has
finished. Instead of doing that with an arbitrary time gap, we should
just run them in one cron endpoint and make sure we call all the cron
jobs in the rigth order.
=> QUICK-FIX Add all nightly cron jobs to one endpoint

src/ggrc/assets/javascripts/dashboard.js, src/ggrc/templates/layouts/dashboard.haml
Cancel all click events as soon as they happen, make sure the javascript doesn't pick up on the checkbox being there, and make it appear translucent so users can tell it's disabled.
=> QUICK-FIX Disable instant notification checkbox

src/ggrc/notification/__init__.py
This code vas done for future releases where you can not have real time
updates without having email digest first. In grapes the real time
updates are disabled and this is a fix to ignore all flags that users
already have in the database.
=> QUICK-FIX Ignore real time updates flag

src/ggrc/assets/javascripts/controllers/dashboard_controller.js
Changing the URL called set_active_widget, this then called show_active_widget,
this then reset info pin from scratch. There is no need to reset active widget
when setting to the same as before. As a result this fixes info pin jumpines.
=> CORE-1800 Fix info pin jumpines

src/ggrc/assets/mustache/responses/tree_footer.mustache
The code is still refering to tree_footer.mustache file.
Empty template file gives script error, so add copywrite header info
=> CORE-1825 Fix script error

src/ggrc/assets/stylesheets/_import-export.scss, src/ggrc/templates/mockups/import-export/index.html
This fix is for progress bar and header. Width of progress bar is
reduced so it won't go into second row.
In header "Import" was missing so it was added and "Hide Menu" was
renamend into "Menu".
=> CORE-1824 Fix bugs on import prototypes

src/ggrc/converters/__init__.py, src/ggrc/converters/base_row.py, src/ggrc/converters/common.py, src/ggrc/converters/import_helper.py, src/ggrc/models/audit.py, src/ggrc/models/control.py, src/ggrc/models/control_assessment.py, src/ggrc/models/data_asset.py, src/ggrc/models/directive.py, src/ggrc/models/document.py, src/ggrc/models/facility.py, src/ggrc/models/issue.py, src/ggrc/models/market.py, src/ggrc/models/mixins.py, src/ggrc/models/object_owner.py, src/ggrc/models/object_person.py, src/ggrc/models/objective.py, src/ggrc/models/org_group.py, src/ggrc/models/person.py, src/ggrc/models/product.py, src/ggrc/models/program.py, src/ggrc/models/project.py, src/ggrc/models/reflection.py, src/ggrc/models/section.py, src/ggrc/models/system.py, src/ggrc/models/vendor.py, src/ggrc/views/converters.py, src/tests/ggrc/converters/test_helpers.py, src/tests/ggrc/converters/test_import_helpers.py
All importable object types should have working downloadable templates at url like
http://localhost:8080/_service/export_csv/Program 
object types with spaces "Org Group" should also work, but they have additional url endpoint with underscore
http://localhost:8080/_service/export_csv/org_group
http://localhost:8080/_service/export_csv/control_assessment
resolves: CORE-1863, CORE-1776, CORE-977
=> CORE-1863 Add endpoint to generate csv import template

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
As discussed, we need to have a list of pre-defined widths for different
counts of selected attributes in the tree view. This commit should not
change the display_option widths, it should only refactor the code to
make it easyer to support more selected attributes.
=> QUICK-FIX Add a list of predefined widths for selected attrs

src/ggrc/assets/javascripts/models/audit_models.js
Add unique title validation for control assessment object
When user tabs out from the title field, the validation triggers and
save buttons are activated
=> CORE-1838 Unique-title validation for CA

src/ggrc/assets/javascripts/models/mappings.js
This fixes clashes in mapping mixins and thus mapping of vendors in
- Issue page under vendor widget
- LHN when an issue is open
=> CORE-1833 Fix mapping vendors to issues

src/ggrc_workflows/assets/javascripts/models/task_group.js
Submitting a system for review from tree of search results on admin dashboard
caused a script error. This was due to buggy workflow boundary check. The code
doing the check was redundant anyway so I just removed it.
=> CORE-1858 Fix script error in search in admin dashboard

src/ggrc_workflows/notification/__init__.py, src/ggrc_workflows/notification/notification_handler.py, src/tests/ggrc_workflows/generator.py, src/tests/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py, src/tests/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py
Notifications should be disabled for inactive cycles, no matter how the
cycle ended (by finishing all tasks or manually ending it).
=> CORE-1903 Stop notifications for inactive cycles

src/ggrc/assets/javascripts/controllers/delete_modal_controller.js
This change makes sure the instance is refreshed before trying to
delete the object. This is necessary because before we added the delete
button to the gear menu, deleting objects was only possible from the
edit modal and the edit modal forced a refresh when it opened.
=> QUICK-FIX Fix delete button in gear menu

src/ggrc_workflows/notification/__init__.py, src/ggrc_workflows/notification/data_handler.py
This fix is to stop and due date notification for a task that in a cycle
that was already manually stopped. There is already a fix to stop
creating such notifications and this is a quick patch for the old
notifications.
=> QUICK-FIX Stop existing due notifications for ended cycles

bin/run_pytests
Remove .pyc files before running tests to ensure clean slate of files
=> Remove .pyc files before running tests

src/ggrc/assets/javascripts/controllers/tree_filter_controller.js
The expression indicator should be green only when entering a complex
query and not on text searches. That includes both text searches for
containig and absent text.
=> QUICK-FIX Fix the filter expression indicator

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This is a quick and dirty fix for the script error thrown when switching tabs in my work. I will investigate the underlying issue.
The quick solution is to just ignore visible nodes without attached controllers. This will only waste a millisecond of scripting time computing the visible nodes.
=> QUICK-FIX Fix script error in my work

src/ggrc/assets/javascripts/mustache_helper.js
If a person is both an owner and a contact two person icons
used to show up in the tree view. Now one icon with a tooltip
with all the roles will show up
=> QUICK-FIX Remove duplicate person icon in tree views

src/ggrc/assets/stylesheets/_tree.scss
Nodes in nested tree views have slightly different look. This added styling
makes the respective placeholders look appropriately to maintain the illusion.
=> CORE-2000 Add styling for nested tree view placeholders

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Presort lists before inserting into tree view.
This costs about a second on a tree view with 1000 elements but greatly improves insertion.
Our insertion sort goes from `O(n^2)` to `O(n)` in most cases since the list is already sorted. Without any cost in terms of constant factors. In the worst case (reversed input) the sorting took a few minutes before and now it takes a few seconds since it's only appending to the DOM.
I can still shave off constant factors quite a bit but this is enough for now since there are other bottlenecks.
=> QUICK-FIX Tree view sorting

.travis.yml, src/dev-requirements.txt, src/requirements.txt
This improves travis build speed for a minute or even two if you're lucky and supposedly reduces the queue time (I didn't measure).
Only real configuration change is to `pip` install locally for user not globally. This drops requirement for `sudo` and enables use to use the not-deprecated container-based infrastructure on travis. 
As a side effect we can drop the custom `PYTHONPATH`.
I also needed to freeze versions of all dependencies to get everything to work but I think this is a good idea in general.
=> QUICK-FIX Switch travis to containers

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Since this is the second bug cause by wrong order of events/method-calls I'm assuming the optimization of timeouts in tree view was a bit too aggressive. 
But I'm not confident I will not cause more regressions if I try to fix it now. So I just try to short circuit if the problematic computation should not be running yet (if indicated by missing values). 
Although I'm not quite comfortable with this approach either is worked for me for now. And the small changes (like in this PR) cannot break anything else. 
This PR exposes more script errors on audit page and those are incidentally fixed by #2874. I really don't think copy-pasting code into this PR is a good idea so I propose we don't merge this one until #2874 is merged (the scrip errors are not blocking, just annoying and may confuse …
=> CORE-1990 Fix a script error on audit's response widget

src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Having multiple widgets, each with several thousand items in its tree view, will make the app unbearably slow and eventually crash the browser.
=> QUICK-FIX Unload tree views when widget is hidden

src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/models/simple_models.js, src/ggrc/assets/mustache/base_objects/create_objective_dropdown_option.mustache
`Regulation -> Section -> Convert to objective` now renamed to `Create objective from section` and fixed to use `Relationship` instead of custom join that does not exist anymore.
Auto-mappings fire as expected.
=> CORE-1630 & CORE-2008 Fix "Create objective from section"

src/ggrc/assets/mustache/audits/tree_header.mustache, src/ggrc/assets/mustache/base_objects/tree_header.mustache, src/ggrc/assets/mustache/base_objects/tree_view_filter.mustache, src/ggrc/assets/mustache/control_assessments/tree_header.mustache, src/ggrc/assets/mustache/people/tree_header.mustache, src/ggrc/assets/mustache/requests/tree_header.mustache, src/ggrc/assets/stylesheets/_common.scss, src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree_header.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_header.mustache, src/ggrc_workflows/assets/mustache/cycles/tree_header.mustache, src/ggrc_workflows/assets/mustache/task_groups/tree_header.mustache
As a side effect the tree view can now be scrolled to the bottom.
=> QUICK-FIX Fix sticky filter and tree header

pylintrc
This is the default file generated by pylint. The only tweet that I made was to change the `indent-string` to two spaces.
=> QUICK-FIX Add a config file for pylint

.codeclimate.yml, README.md
Since this is an open source project CodeClimate will run analysis for free. I'd like to have this badge showing the status of our code and provide a quick link to a list of potential issues. 
Sadly we cannot have this on PRs without a subscription. 
We can however enable the [linthub](http:/linthub.io) bot to comment on our PRs providing feedback on style issues.
=> QUICK-FIX Add a CodeClimate badge

src/ggrc/assets/javascripts/mustache_helper.js
In case the CA has no audits mapped. A proper long-term fix will be to always ensure that a CA has exactly one audit mapped. But this may prove to be quite tricky. 
A short explanation of this bug because I find it interesting
When there were no audits the helper behaved like it returns a stringified JSON and defaulted to `"{}"`. But when there was an audit (the normal case) it called its continuation with the stringified JSON as a parameter and returned the result. 
I fixed it by returning `""` (which is now an html string, not json) in the edge case and thus not rendering anything audit-related.
=> CORE-2078 Fix gear icon dropdown on CA page

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
A check if the controller is attached to DOM was missing.
=> CORE-2101 Fix a script error on workflow tasks page

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/js_specs/models/cacheable_spec.js
This effectively brings back `instance.get_deep_property` but it now works on
pre-parsed property strings which allows for big speedups when plucking deep
properties on a collection of items.
We need `get_deep_property` to be accessible from outside the tree view controller
in order to use it to fix filtering. And of course the tree view controller does not seem 
like the right home for such a function :smile:
=> QUICK-FIX Move get_deep_property into Cacheable

src/ggrc_basic_permissions/converters/handlers.py
Owner missing warnings should not be displaye on empty program reader
and program editor columns.
=> CORE-1994 Prevent wrong warnings on program import

src/ggrc_workflows/assets/javascripts/models/cycle_models.js
This uncovers an unrelated bug: where there is no mapped object the sorting is not consistent when changing direction. This is a  problem in the new sorting logic and I'll fix it in a separate PR.
=> CORE-2092 Fix tree view task sorting by workflow/object

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
In some cases the `parent_model_name` will be just `Cacheable`. There will be no
definition for it's sub tree, so the filtering will fail.
I added a fallback to parent instance type. And in case even this fail skip
filtering. It's better to ignore filtering and display too much than to throw a
script error and leave the user hanging.
=> CORE-2118 Fix third level tree view rendering

src/ggrc/converters/handlers.py, src/ggrc/converters/import_helper.py
We have to add propper prefixes for non standard attributes such as
mappings and custom attributes. Without unique prefixes, custom
attributes with the same name as original attributes would be hidden and
ignored when importing objects. Example would be if we had a custom
attribute with the name "Title". then imports would fail for that
object.
=> QUICK-FIX Add prefixes to keys of attribute definitions

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This short-circuit failed to trigger post-load events and left the spinner
running indefinitely. I think doing a bit of extra work for the empty `items` is
better than duplicating logic for a proper short circuit so I just removed the
short circuit.
Note: there are still cases of comments not showing up, but this is a separate
issue (on the back end). This commit only fixes the indefinite spinner.
=> CORE-2098 Fix infinite spinner for comments under tasks

src/ggrc/converters/column_handlers.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers.py, src/tests/ggrc/__init__.py, src/tests/ggrc/converters/test_csvs/full_good_import_no_warnings.csv
The issue CORE-2137 is to big for one PR. Here I've only fixed last two items. Others are comming up.
=> CORE-2105, CORE-2137 Add missing column handlern to Controls

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This disables lazy loading in the comments under a cycle task.
The placeholders in there were not styled (at all) and this botched the size
calculations and messed up rendering completely. The end result: displaying only
one comment.
I don't think we need yet another placeholder style since the volume of comments
is rather low so I just disabled lazy loading and this fixes the problem.
Please do let me know if there is a valid reason to have lazy loading of comments.
=> CORE-2088 Make tree view for cycle entries strict

src/ggrc/assets/javascripts/plugins/tooltip.js
`_tooltip_show` will short-circuit if there is no content or the tooltip is
disabled. This means that the new `show` we're overriding it with should also
short-circuit because the state of the tooltip will not be as expected
otherwise.
=> CORE-2157 Fix script error on tooltips

src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
We do not allow deleting people at this time (not even on the Admin page).
=> CORE-1945 Remove delete button from people info

src/ggrc/rbac/permissions_provider.py
After a Creator was given a Program specific role he was able to access any Program other programs in the systems - even the ones he had no access to. The issue was a missing context permission check.
=> QUICK-FIX Fix rbac check for Creators with Program access

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
I've also factored the comparator out of the `temp_list`'s sort - this keeps all
the sorting logic in one place and leaves just the optimization at the call
site.
=> QUICK-FIx Tree view string sorting ignore case

src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_objects/tree.mustache
Because we can't differentiate between the object being deleted and not
having access to the object we are now displaying a no access error
instead of a deleted flag.
=> CORE-1964 Fix error text when object instance is not available

src/ggrc/assets/stylesheets/_widget.scss
Make relevant filters show in a single line. like everywhere else.
=> QUICK-FIX Fix relevant mappings filter for exports

src/ggrc_workflows/migrations/versions/20150812104803_1a4241cfd4cd_make_task_group_id_nullable.py
The sql table structure should match our models. The column
task_group_id can be null in CycleTaskGroup model but not in the
cycle_task_groups table. We need to make the column nullable so that our
database does not fall into some incosistent state where task_group_ids
have values of non existent task groups.
To show the issue create a WF and start a cycle, then delete the TG and
you should see a warning in the console.
=> QUICK-FIX Make task_group_id nullable

src/ggrc_basic_permissions/converters/handlers.py
Because context was not set, memcache did not properly delete the
context, causing user_roles to disappear from program page.
=> CORE-2197 Fix memcache issue when importing user_roles

src/ggrc/automapper/__init__.py, src/ggrc/converters/handlers.py, src/ggrc/utils.py
This makes for a less noisy log, especially on imports. It also makes imports
faster as logging a ton of lines is a major slowdown.
=> QUICK-FIX Silence automapper on import and drop step logs

src/ggrc/automapper/__init__.py
Fix the related query to use indices. Mysql is dump enough to not do index merge
when using `or` so two queries merged manually with union are needed.
=> QUICK-FIX Speed up automappings

src/ggrc/models/relationship_helper.py
Add support for special mappings audit and assignee.
This works much better with #3033 that add the missing fields to request export.
=> CORE-2210 Fix relevant filters on export for Request

src/ggrc_workflows/converters/handlers.py
The handler expects a field of form `Program: PROGRAM-18` and crashes if the
colon is missing or if object type is wrong. This prevents the crashes and
reports the errors.
=> CORE-2245 Add error handling on task groups object import

src/ggrc/assets/javascripts/components/csv/export.js, src/ggrc/converters/column_handlers.py, src/ggrc/converters/handlers.py, src/ggrc/models/response.py
This is the last missing object type for import/export.
I was not sure about exposed attributes since responses seem "a bit polymorphic but not that much" and it's hard to figure out what the normal form should be. Feedback welcome but we can still tune that later now that we have at least something for all object types.
=> CORE-1998 Add import/export of responses

src/ggrc/converters/query_helper.py, src/ggrc/models/audit.py, src/ggrc/models/categorization.py, src/ggrc/models/context.py, src/ggrc/models/control.py, src/ggrc/models/control_assessment.py, src/ggrc/models/mixins.py, src/ggrc/models/object_owner.py, src/ggrc/models/product.py, src/ggrc/models/program.py, src/ggrc/models/section.py, src/ggrc/models/system.py, src/ggrc_risk_assessments/models/risk_assessment.py, src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/models/cycle_task_group.py, src/ggrc_workflows/models/cycle_task_group_object_task.py, src/ggrc_workflows/models/task_group.py, src/ggrc_workflows/models/task_group_task.py, src/ggrc_workflows/models/workflow.py, src/tests/ggrc/converters/test_export_csv.py, src/tests/ggrc/converters/test_import_helpers.py, src/tests/ggrc_workflows/converters/test_workflow_export_csv.py
This is for export filters (and eventually search) that are not simple entries in the database table but foreign keys and additional logic is needed to process them.
This PR does a small refactor of the query builder and adds a bunch of filters. Currently they are scattered around the models, this might change (to deduplicate code) in the future but probably not in time for this PR.
I also added a test that tries to export every single object type and filter on every single field. This is still  but since the PR is quite big and I'll just be adding filters I'm opening it already so it can be reviewed properly.
=> CORE-2149 Filter by special fields

src/ggrc/converters/query_helper.py, src/ggrc/views/converters.py
Currently user gets a generic sounding `Export failed due to server error` if
she makes a typo in a field name in her filter query. This replaces the error
with a more helpful `Bad query: object Program does not have attribute owner`
It also fixes text search by using the special filters and ignoring fields.
=> CORE-2293 Improve error handling on export filters

src/ggrc/assets/javascripts/components/mapper.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Prior to this change creators and readers were not able to map People
to their Programs / Workflows and other objects.
=> QUICK-FIX Allow Creators / Readers to map people to their Objects

src/ggrc/assets/javascripts/plugins/autocomplete.js, src/ggrc/assets/mustache/audits/modal_content.mustache, src/ggrc/assets/mustache/control_assessments/modal_content.mustache, src/ggrc/assets/mustache/sections/modal_content.mustache
If a modal dropdown creates a mapping we should only show results that
the user can update.
=> CORE=2291 Add update filter to some modal dropdowns

src/ggrc/assets/mustache/modals/save_cancel_buttons.mustache, src/ggrc_workflows/assets/javascripts/controllers/approval_workflow_controller.js
Maybe this could be made better. Instead of just renaming button text, can we say if this is "Submit for Review" modal, button should have text "Submit"?
Can someone help me with this?
=> CORE-1518 Rename Submit for Review modal button

src/ggrc/converters/handlers.py
Risk assessments are missing a foreign key on program (to be fixed) so when
program id is invalid the program will be `None`. This is the best we can do
since the mapped program does not exist.
=> CORE-2323 Fix export of risk assessments with corrupt data

src/ggrc_workflows/converters/handlers.py
~~This is a poorman's `INSERT IGNORE`. Just looking at
`self.row_converter.obj.task_group_objects` is not enough.~~
~~Better ideas are much appreciated.~~
Check existing task group objects (there may be some if this is an update) and skip that objects.
=> CORE-2332 Fix imports where task groups have duplicate objs

src/ggrc/models/relationship_helper.py, src/ggrc_workflows/models/relationship_helper.py
This adds a few helpers to make "relevant to" filtering on export more consistent. It still does not implement the full ticket but it forms a logical unit so I'd like to have it merged and not wait to implement everything.
=> CORE-2269 Relevant filters

src/ggrc/assets/javascripts/mustache_helper.js
using the refresh_all function makes sure the audit is
properly refreshed and reified before trying to refresh
the program attr.
=> CORE-2280 Fix script error when audit is yet loaded

src/ggrc_basic_permissions/roles/Creator.py
DELETE requests on appengine were not working for the creator because
he was not able to access the background task object created for the
DELETE request
=> CORE-2254 Add ability to read BackgroundTasks to creator

src/ggrc_workflows/services/workflow_cycle_calculator/annually_cycle_calculator.py, src/ggrc_workflows/services/workflow_cycle_calculator/cycle_calculator.py, src/ggrc_workflows/services/workflow_cycle_calculator/monthly_cycle_calculator.py, src/ggrc_workflows/services/workflow_cycle_calculator/quarterly_cycle_calculator.py, src/ggrc_workflows/services/workflow_cycle_calculator/weekly_cycle_calculator.py, src/tests/ggrc/api_helper.py, src/tests/ggrc_workflows/workflow_cycle_calculator/test_quarterly_workflow.py
Quarterly bug - in certain cases (multiple tasks spanning
multiple quarters) certain tasks' reified values could be before
actual first task, resulting in wrong reified dates.
Workflow test suite - due to at this time unknown underlying
issue test cases could lose sessions information - this fixes it
by reinitializing login if 302 redirect is returned.
Rewrite quarterly relative day to date calculator to use 
transformation matrix to convert from base date to a reified 
value in current quarter.
=> CORE-2325 Fix quarterly bug; Fix workflow test suite session bug

src/ggrc/assets/javascripts/components/csv/export.js, src/ggrc/cache/memcache.py, src/ggrc/converters/base.py, src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/converters/column_handlers.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers.py, src/ggrc/models/audit_object.py, src/ggrc/models/reflection.py, src/tests/ggrc/converters/test_import_helpers.py
This implements the special `delete` column in imports. Valid values are `yes` and `true` (case insensitive).
Deletes will not cascade - this is an error during import. 
There is now a "deleted" counter in the import UI.
I would really like some feedback especially on the non-cascading part.
*NOTE* dry-run might be broken now since it doesn't take deletions into account. That would be really hard to properly simulate. I'm working on a simplified dry run that just does the import and then reverts it. That will trivially support deletion too.
=> CORE-2216 import delete

src/ggrc/converters/query_helper.py
In case of empty "Relevant-to" filter report this as an error instead of just saying server error.
For better UX we would have to handle this on the frontend but there are several possibilities and none is as straightforward as this one. So I propose we do a user-friendlier fix for the next release, this server-side check will not hurt anyway.
=> QUICK-FIX Add error reporting to export relevant filter

src/ggrc_workflows/assets/javascripts/apps/workflows.js, src/ggrc_workflows/models/__init__.py
Another PR for ZGOOG-41
Sorry, this is ungly - workflows extension needs to be aware of the risks
extension because imports mutate state of the rest of the application. This can
go away when we have proper stateless extension imports.
**note** this depends on #3111 which fixes the mapping ui
**another note** this still does not complete ZGOOG-41 - still bugs left
=> ZGOOG-41 Integrate workflows and risks

src/ggrc_risks/assets/javascripts/apps/risks.js
I also removed the duplicate `related_objectives` key to clean up the file a
bit.
=> ZGOOG-53 Sort widgets on Risk/Threat Actor  pages

bower.json, src/ggrc/assets/assets.yaml, src/ggrc/assets/stylesheets/_modal.scss
It turns out that our app is using jquery 1.11 and jquery ui 1.10. When I naively updated jquery ui to 1.11 it broke autocomplete. This now reverts jqeury ui back to 1.10, but we need to make a proper fix for this.
=> QUICK-FIX Fix Autocomplete dropdowns

src/ggrc/assets/javascripts/controllers/dashboard_controller.js
I am not sure why the :not(id=) part was added back in 2013, but it
causes a script error on export page in jQuery 1.11.3 (but not in
1.11.0).
=> QUICK-FIX Remove an invalid jQuery expression

src/ggrc/converters/handlers.py, src/ggrc/models/request.py
Since it is mandatory in the DB import will silently fail otherwise. Also add
reporting for this in the dry run.
=> CORE-2360 Make assignee mandatory when importing a request

src/ggrc_basic_permissions/__init__.py
Auditor role has the audit context id and not the program context id.
Because of this we need to find all the context implications from
Program to Audit and check those contexts in addition to the program
context.
=> CORE-2358 Make sure Auditor role propagates permissions

README.md
Since the app cannot be deployed without a recent ansible version which isn't mentioned in the readme or docs, I opened a hotfix branch. Users should now be able to deploy ggrc-core following the Quick Start guide.
=> QUICK-FIX Update readme

src/ggrc_basic_permissions/converters/handlers.py
I found that export of Auditors is always blank because of a missing handler (it managed to fail silently) while writing filters for Auditors. 
I think this is quite important so this PR is against Plum.
=> CORE-2413 Add an import/export handler for Audit->Auditors

src/app.yaml.dist
Include MYSQLdb library for GAE. Future `DATABASE_URI` should be:
````
GGRC_DATABASE_URI: "mysql+mysqldb://root@/<database-name>?unix_socket=/cloudsql/<CLOUD SQL instance>?charset=utf8"
````
=> CORE-2365 Include MySQLdb library on GAE

src/ggrc/converters/query_helper.py
Checked for string properties (lexicographic comparison) and date properties.
Relative dates *are broken* - but this is not an expected use case.
Also fixed a bug in `autocast`.
Tree view filters already support '<' and '>' and the search modal only has full text search.
=> CORE-2416 Add '<' and '>' to export filters

src/ggrc/automapper/rules.py, src/tests/ggrc/automapper/test_automappings.py
Nested objectives are already covered by the `mapping to objective` rule.
This is compatible with the rule sanity checker as it obeys the implicit tree structure and is thus guaranteed to not explode.
=> CORE-2421 Add automappings for nested controls

src/ggrc/assets/javascripts/pbc/workflow_controller.js, src/ggrc/models/audit.py, src/ggrc_basic_permissions/converters/handlers.py, src/tests/ggrc/converters/test_import_special_objects.py
Instead of expanding our role propagation query with context implications we just add a program reader role when an auditor is created.
=> CORE-2358 Create a reader role when auditor is added

src/ggrc_workflows/models/relationship_helper.py
Adds a relationship helper for the indirect relationships between tasks and task group objects of the relevant task group.
=> CORE-2422 export objects relevant to tasks

src/ggrc_risks/models/risk.py
bring back the Noted mixin that was accidentally removed in a refactor
=> QUICK-FIX Risk notes

src/ggrc/models/mixins.py, src/ggrc/services/custom_attribute_service.py, src/tests/ggrc/converters/test_csvs/multi_word_object_custom_attribute_test.csv, src/tests/ggrc/converters/test_import_with_custom_attributes.py
Fix multiple-word object name export of custom attributes by
converting object name from camel case to snake case on custom
attribute search
=> CORE-2439 Fix multiple-word object name export of custom attributes

src/ggrc_basic_permissions/converters/handlers.py
Admin is the only role that has its own context. Other roles either
don't have contexts or take the objects context.
=> QUICK-FIX Fix Admin context on user imports

src/ggrc/assets/javascripts/components/mapper.js, src/ggrc/assets/javascripts/models/mappings.js
Relevant filters must take into account both source and destination in
the mappings table. In case of audits, we have to avoid searching for
related objects as source.
=> CORE-2486 Fix relevant mappings

src/ggrc/models/section.py
Implement filter by directive using a join on the relationships table as this is
now just a convenience import field.
(I also cleaned-up imports and indentation to make the file PEP8 clean)
A short explanation is in order:
I enabled the export filters test on a pull request and everything worked (tests passed) but before it was merged the Section object changed in develop leading to failures post-merge. This implements the missing filter to make everything green again.
=> QUICKFIX filters for section (failing build)

src/ggrc/models/response.py
Mixin init logic fired at the wrong time after abstracting the mixin into
the common parent. Fixed by manually inlining.
=> CORE-2473 response documents

src/ggrc/assets/javascripts/controllers/modals_controller.js
This issue was caused when we implemented saving of hidden fields. The issue is that not all of our modals have a model in the options, an example of this is the Activate Workflow dialog on Workflow page.
@sasmita514 can you review this and double check that the same assumption was not made elsewhere in the code? Thanks!
=> QUICK-FIX Fix modals whith no model

src/ggrc/builder/json.py, src/ggrc/migrations/versions/20151016102822_45693b1959f7_add_relationship_attrs.py, src/ggrc/models/all_models.py, src/ggrc/models/relationship.py, src/tests/ggrc/models/test_relationship.py
This implements extensible relationship attributes that finally allow dropping of all special mapping tables. 
I wrote it as a part of [assignable mixin](https://github.com/edofic/ggrc-core/tree/feature/CORE-2375-assignable-mixin) but I think it's better to consider it a standalone thing.
Relationship attributes have to be white listed (example of this is the assignable mixin - will be another PR) and thi PR does not white list any so there arent any major differences in the API: you get an `attr` field that is always an empty dict and you cannot post anything to it - you would get `Bad request: invalid attribute <x>`
=> QUICK-FIX add relationship attributes

src/ggrc/models/mixins.py
This adds the `Assignable` mixin that is pretty much just a validation for relationship attributes and a shortcut to retrieve assignees. 
I also cleaned up the whole mixins file - sorry for the noise.
=> CORE-2375 Assignable mixin

src/ggrc/migrations/versions/20151023130018_4cd52e0a17b8_add_comments.py, src/ggrc/models/all_models.py, src/ggrc/models/comment.py, src/ggrc/services/__init__.py
This adds a standalone `Comment` object as well as a `Commentable` mixin that provides the necessary relationships.
Permissions for these objects are not set up yet so only admin has access. I will implement this once we have a commentable object.
=> CORE-2376 Add Comment(able)

src/ggrc/automapper/__init__.py, src/ggrc/automapper/rules.py, src/tests/ggrc/automapper/test_automappings.py
This now triggers for manually created relationships between audits and
requests. These will be automatically created once Requests are first class.
=> CORE-2497 request automapping

src/ggrc/migrations/versions/20151029104859_29b63100d61c_drop_commentable_from_comments.py, src/ggrc/models/comment.py
Just use relationships to link comments to objects.
=> QUICK-FIX Remove `commentable` from Comment

src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
If the user tried to click save on the permissions modal without
changing the role, both the delete and create requests would fire
trying to delete and create the same join object. If create was
processed before delete the unique constraint would fail and a new
object would not be created, but the old one would still be deleted,
and the user would end up with no access role.
To reproduce this on your local machine toggle device mode in chrome and set the network 3G.
=> CORE-2491 Wait for join delete to finish before creating a new join

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/simple_models.js
Our custom serialize function caused a serious regression when we upgraded
from canjs 2.0.9 to 2.2.9. From what I can tell (ac7112ab, 5f71b7c), we implemented a custom serialize
function when we weren't using stubs in lists in order to prevent update events going out of control.
The only difference in the output of our serialize and canjs's
serialize is that canjs's function also serializes the instance class.
=> QUICK-FIX Fix performance regression in canjs 2.2.9

src/ggrc/converters/base_row.py, src/ggrc/migrations/versions/20151107123018_1bad7fe16295_make_person_email_not_null.py, test/integration/ggrc/converters/test_csvs/people_test.csv, test/integration/ggrc/converters/test_import_csv.py
People imports must notify a user if an email is missing and that line must be ignored. 
Importing people without emails worked and it broke the admin panel, so an email can't be added to that person from within the app.
=> CORE-2576 Fix people imports

src/ggrc/migrations/versions/20151016174806_27684e5f313a_make_request_first_class_object.py
Fix "Make request FCO" migration by skipping over relationships
when source/destination object doesn't exist anymore.
=> QUICK-FIX Fix Make request FCO migration

src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
if_task_group_assignee_privileges was in a endless loop refreshing the
workflow which prevented edit/add buttons from rendering. Now the
workflow will only refresh itself if it's not already in cache.
=> CORE-2570 Only refresh workflow when needed

src/ggrc/notification/__init__.py, test/unit/ggrc/notification/__init__.py, test/unit/ggrc/notification/test_init.py
This is just a fix for the show_pending helper view, that can display
emtpy email notifications. The underlying cause for this is that
mandatory assignees or contacts can be missing. These emails would not
get sent in any case since there is no recipient, but we should stop
them from showing to avoid confusion during testing.
=> CORE-2606 Hide empty email notifications

src/ggrc/models/relationship_helper.py
Request object uses relationships for most of its mappings now so we
have to remove the special cases in the relationship_helper.
=> CORE-2586 Remove Special request mappings

src/ggrc/assets/javascripts/models/mappings.js
Because we can't add related_risks and related_threats to the
Multi list we are using a blacklist instead of a whitelist
=> CORE-2769 Show Risks and Threats under mapped objects in request info

src/ggrc/assets/mustache/requests/modal_content.mustache
Only show Audits where the current user has edit permissions because otherwise
we'll throw forbidden errors.
=> CORE-2795 Limit audits in the request modal to editable

src/ggrc/assets/javascripts/controllers/modals_controller.js
Deferred bindings need to be resolved before we resolve the save
deferred.
=> CORE-2800 Wait for deferred bindings when saving

src/ggrc/converters/base_row.py, src/ggrc/converters/handlers.py, test/integration/ggrc/converters/test_multi_import_csv.py
The error messages on imports should always display user facing names
and not actual model keys that are used on the back end.
=> CORE-2716 Correct import error messages

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/mustache/custom_attributes/expanded_attrs.mustache, src/ggrc/assets/mustache/requests/info.mustache
While custom attributes were added on the backend, we forgot to include them on the front end. This PR fixes that.
=> QUICK-FIX Add custom attributes to request object

src/ggrc/rbac/permissions_provider.py
When mapping a person we only need to check if we have
update permissions on the object we are mapping the person
to.
=> CORE-2794 Skip permission check on person object when mapping a person

test/integration/ggrc/automapper/test_automappings.py
This was causing a bogus warning in the test output.
=> QUICK-FIX Update request automapping test with valid status

src/ggrc_basic_permissions/roles/Creator.py, src/ggrc_basic_permissions/roles/ProgramAuditReader.py
Creator should only be able to create requests for audits for which she has
update access. So she does not need a general Request create permission since
she inherits permission form the audit context.
=> CORE-2675 Constrain Requests from Creator to owned audits

src/ggrc_basic_permissions/roles/Auditor.py
This allows the auditor to map objects to the audit but not to unmap them while
not giving him edit permissions on the audit.
=> CORE-2778 Allow auditor to create relationship in context

src/ggrc/automapper/__init__.py, src/ggrc/services/common.py, test/integration/ggrc/automapper/test_automappings.py
This triggers auto-mappings based on the request-audit direct mapping. It is necessary because this mapping has not been transitioned to relationships in Zucchini.
=> CORE-2688 Trigger request auto-mappings

src/ggrc_basic_permissions/roles/Auditor.py
So they can respond on requests
Also see #3265
=> QUICK-FIX Allow auditors to CR comments in context

src/ggrc/migrations/versions/20151110134605_3c1619ff36e8_migrate_data_to_request_fco.py
On review, possible problems and request for comments:
* too much python
* use of `fetchall`
* select for every insert to get back IDs
=> CORE-2608 Migrate assignee and requestors to relationships table

AUTHORS, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/debugger_spec.js
It now works even if invoked with more than one argument (no error is thrown), e.g. by invoking it like the following in a template:
```js
{{debugger 1 2 foo="bar" 4 baz="qux"}}
```
=> QUICK-FIX: Fix Mustache debugger helper (multiple arguments)

.travis.yml, bin/run_karma
This makes the output of karma tests the same as the output of all our
other tests.
=> QUICK-FIX Use dots reporter for karma tests

src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
If the user role modal is closed without changing the role the app will
no longer delete a user_role and try to create a new one.
=> CORE-2747 Prevent recreation of existing user_roles

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/services/common.py, test/integration/ggrc/converters/test_import_block_order.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/converters/test_import_special_objects.py, test/integration/ggrc/converters/test_import_update.py, test/integration/ggrc/converters/test_multi_import_csv.py, test/integration/ggrc/services/test_common.py, test/integration/ggrc_basic_permissions/test_creator.py, test/integration/ggrc_basic_permissions/test_creator_program.py, test/integration/ggrc_basic_permissions/test_reader.py, test/integration/ggrc_workflows/converters/test_import_workflow_objects.py, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py, test/integration/ggrc_workflows/notifications/test_one_time_wf.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py, test/unit/ggrc/test_utils.py
If None is in the contexts read_contexts_for will return None and not a
list of context_ids including None.
=> CORE-2779 CORE-2888 Fix relationship access filter for creator

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/get_permalink_for_object_spec.js, src/ggrc/assets/mustache/base_objects/dropdown_menu_tier2.mustache, src/ggrc/assets/mustache/base_objects/tier2_content.mustache, src/ggrc/assets/mustache/controls/tier2_content.mustache, src/ggrc/assets/mustache/directives/tier2_content.mustache, src/ggrc/assets/mustache/documents/tier2_content.mustache, src/ggrc/assets/mustache/objectives/tier2_content.mustache, src/ggrc/assets/mustache/people/tier2_content.mustache, src/ggrc/assets/mustache/programs/tier2_content.mustache, src/ggrc/assets/mustache/requests/tier2_content.mustache, src/ggrc_workflows/assets/mustache/tasks/tier2_content.mustache, src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
This PR removes a bunch of tier2 templates, so that the default template in base_objects is used.
"Get permalink" doesn't yet work as expected.
=> CORE-2825 Update tier2 menu in search

src/ggrc/assets/mustache/audits/modal_content.mustache
If an evidence upload folder is set, it is now correctly linked with the Audit object that has just been created.
The Audit's `modal_content.mustache` template was the only one that did not set the `instance="instance"` attribute of the `<ggrc-modal-connector>` element, and consequently the `deferred_update()` handler was not able to link the GDrive folder with the new Audit instance, because it [couldn't find it](https://github.com/google/ggrc-core/blob/develop/src/ggrc/assets/javascripts/controllers/modals_controller.js#L1025) (it was `null`).
=> CORE-2875: Fix setting the upload folder for new Audits

src/ggrc/assets/javascripts/pbc/workflow_controller.js
When creating a control assessment we need to add a context
or else the creator will not see the mappings correctly
=> CORE-2624 Add audit context to mapped control/audit

src/ggrc_basic_permissions/migrations/versions/20151126161109_3bf028a83e79_fix_logs_when_assigning_admin_user_role.py, src/ggrc_basic_permissions/models.py
GRC Admin and Superuser contexts (contexts with id 0 and 1) does not
have a related object. This caused logs to show `UserRole created`
instead of `GRC Admin mapped to user` when adding/removing GRC Admin
authorizations to users
=> CORE-2859 Fix user role name when context has no related_object

src/ggrc/converters/handlers.py, src/ggrc/rbac/permissions.py, src/ggrc/services/common.py
Use create (in context) to handle cases where the user is allowed to create
mappings but not to update the target object (e.g. Auditor)
=> CORE-2886 Fix direct mapping permission check in import

src/ggrc_risks/assets/javascripts/apps/risks.js
Update related objects descriptors for risk extension objects (risk & threat) to
show the `+` icon on right hand side in tree view.
=> CORE-2878 Add missing "map to this" in tree view for risk objects

src/ggrc/assets/javascripts/models/mappings.js, src/ggrc/assets/mustache/base_templates/attachment_list.mustache
This fix has been completely revamped. The fix for uploading the evidence files to the correct GDrive folder (as set on the Audit) has been stripped down to the bare essentials - it's just a different click handler that is now executed (`trigger_upload_parent` instead of `trigger_upload`).
On top of that and as per @Smotko's suggestion, the upload evidence button is now only displayed if an evidence upload folder is actually set on the Audit, otherwise an error message is displayed.
~~Files are not uploaded to GDrive root anymore, but to the directory specified
in the audit's settings.~~
~~Not test for this, unfortunately, because after a lot of researching and digging, me and @edofic eventually concluded that some of the objects that the `trigger_upload()` method uses would be very …
=> CORE-2819 Upload request evidence to the correct folder

src/ggrc/assets/javascripts/controllers/assessment_generator.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/control_assessments/info.mustache
We are moving away from directly mapped controls to control assessments
in plum jelly, but until we do we need to support both directly mapped
controls and controls mapped via relationships table. This commit makes
sure we either set the directly mapped control or the first control
mapped via relationships.
=> CORE-2633 Use the first related control if directly mapped control is null

src/ggrc/converters/base.py
A pleasant side effect of this is that you can now have single line comments in
the import as they will be considered headers for blocks.
=> CORE-2912 Ignore blocks with no data rows on import

src/ggrc/assets/mustache/base_templates/attachment_list.mustache
If the user doesn't have access to attached audit folder we will now print an error with a link for requesting access.
=> QUICK-FIX Add message when user doesn't have access to folder

src/dev-requirements.txt, src/requirements.txt
Update the six library as it's required by pylint and update freezegun
so it works with the new six lib.
=> QUICK-FIX Add pylint to dev-requirements

src/ggrc_workflows/converters/handlers.py, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Only list "No Access" users by filtering out users with roles on that workflow.
=> CORE-2268 Fix No Access column on workflow export

src/ggrc_workflows/models/task_group_task.py, test/unit/ggrc_workflows/models/test_task_group_task.py
The validats decorator depends on the order of edits. Start date has to
be set before end date. If that's not the case it might miss an error,
which is fine because imports make sure that the order of editing is
correct. This decorator is used mostli for displaying the correct
warning to the user during import of csv files. The real check happens
with schema.CheckConstraint which should work in all cases, but the
error is not user friendly.
=> CORE-2694 Fix task date validation

src/ggrc_gdrive_integration/assets/javascripts/controllers/gdrive_workflows_controller.js
This fix makes sure that all the existing upload folders of an Audit
are first transparently unlinked from it, before the Audit is linked to
a new upload folder that the user has just picked.
The fix first refreshes the list of Audit's upload folders, so that they are properly removed before a new upload folder is linked to the Audit.
Sadly no unit tests, because it is a lengthy legacy method that would require extensive mocking in test  fixtures, and should be refactored into smaller parts first.
~~**Update:** I just discovered that _deleting_ an Audit folder is quirky, too - it executes a slightly different piece of code, which also needs to be fixed - but probably in a separate PR? Do we already have a ticket for that?~~
**Update 2:** Actually, the ticket is also about deleting, I will …
=> CORE-2513 Prevent setting multiple Audit upload folders

src/ggrc/assets/mustache/base_templates/people_list.mustache
The hiding functionality relies on the presence of the `hidable` CSS class which this PR adds to the corresponding Verifier(s) filed on the Request edit form.
=> CORE-2911 Fix hiding the optional Verifier(s) form field

src/ggrc/converters/handlers.py, src/ggrc_workflows/converters/handlers.py, src/tests/ggrc/converters/test_csvs/full_good_import_no_warnings.csv, src/tests/ggrc_workflows/converters/test_csvs/simple_workflow_test_no_warnings.csv, src/tests/ggrc_workflows/converters/test_import_workflow_objects.py
Make sure that workflow tasks are imported propperly
- start and end date are set correctly.
- Comma separated values are stored if task type is Checkboxes or Dropdown.
=> QUICK-FIX Patch workflow task imports for Plum

src/ggrc/assets/javascripts/controllers/comment_controller.js, src/ggrc/assets/mustache/base_templates/attachment.mustache, src/ggrc/assets/mustache/base_templates/mapping_tree_view.mustache, src/ggrc/assets/mustache/base_templates/people_group.mustache, src/ggrc/assets/mustache/base_templates/urls.mustache, src/ggrc_basic_permissions/roles/Auditor.py
Reopened https://github.com/google/ggrc-core/pull/3407 against the zucchini branch.
=> CORE-2897 Audit Lead and Auditor cannot remove Evidence, URL, Mapped Objects

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/plugins/autocomplete.js
When "create new" is selected we have to wire the new object callback with the
autocomplete event and prevent navigation to the page of the newly created user.
=> CORE-2783 Fix a script error for request user autocomplete

src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
The corresponding option does not appear in the Audit view's action menu anymore (when in the context of the Program page, of course).
=> CORE-2908 Prevent an Audit to be unmapped from a Program

src/ggrc_workflows/models/workflow.py
Query generation is silently broken when there are two layers of EXISTS nesting
so the workaround is to rely on a context_id available from WorkflowPeople since
it should be the same as the one in the Workflow and is available just one layer
of nesting away.
This now allows you to correctly export `all plum workflows containing no access users` using this query `title ~ plum and "no access" ~ "@"`.
=> CORE-2268 Fix export filtering on Workflow -> No Access

src/ggrc/utils.py
This is a quick fix for allowing mapping of risks and threats to all
other models in the app. The propper fix should come later when these
rules are read from each individual module.
Making this fix instead of the propper fix is just for the zucchini
release, and we don't want to change too much code and create any extra
bugs.
=> CORE-2719 Allow risks and threat mappings in import/export

src/ggrc/assets/stylesheets/_lhs.scss
NOTE: this fix reveals another issue, the ticket for the latter can be found [here (CORE-2933)](https://reciprocitylabs.atlassian.net/browse/CORE-2933).
=> CORE-2929 Display the object tooltip above the modal window

bin/check
This is a helper script for running pylint on modified files that are
tracked by git. Other checkers should eventually be added to this
script.
=> QUICK-FIX Add helper script for pylint

src/ggrc/assets/javascripts/models/cacheable.js
Missing length check caused the instance to be refreshed prematurely
which caused an error when creating an object with global creator role
=> CORE-2938 Check _pending_joins length when resolving deferred bindings

Dockerfile, README.md, Vagrantfile, bin/setup, docker-compose.yml, provision/docker/01_start_mysql.sh, provision/docker/inventory, provision/inventory, provision/roles/ggrc/tasks/main.yml, provision/roles/ggrc/templates/.bashrc.j2, provision/roles/ggrc/vars/main.yml
~~Completely Dockerfile based provisioning that does not break existing Vagrant VMs using Ubuntu 12.04.~~ Dockerfile that uses the same Ansible provisioning as the Vagrant setup. Also updated Vagrant to use ubuntu 14.04.
This may not be idiomatic Docker setup since mysql is running in the same container but I find it very convenient because it let's me run multiple containers with independent databases without manually linking containers together. 
If we're willing to drop this it's quite easy to drop the database and link in a *mysql service* in the `docker-compose.yml` 
I'm not sure about the development workflow using docker. Currently `docker-compose up` will locally build the image (takes 5-10min) if not present. If `requirements.txt` changes you will likely want to rebuild the …
=> CORE-2449 Add Dockerfile based dev environment

src/ggrc/assets/javascripts/mustache_helper.js
(inspired by the comments on #3404)
The complexity of the multiple if-else-if statements is shifted to the mapping
object, making is less likely to introduce a bug when modifying the code, as
well as making it more readable and manageable, because the resulting mapping
is now completely flat, albeit somewhat longer.
**NOTE:** The PR sent to the main development branch, because it is simply a non-necessary refactoring and as such not immediately needed in Zuccini.
=> QUICK-FIX Refactor the file_type Mustache helper

src/ggrc_gdrive_integration/assets/javascripts/controllers/gdrive_workflows_controller.js, src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
Moving modals from zIndex 1050 to 2050 caused our gdrive modals to show
behind our edit modals.
=> CORE-2947 Fix gdrive zIndex setting

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/audits/tree.mustache, src/ggrc/assets/mustache/base_objects/tree.mustache, src/ggrc/assets/mustache/control_assessments/tree.mustache, src/ggrc/assets/mustache/controls/tree.mustache, src/ggrc/assets/mustache/directives/tree.mustache, src/ggrc/assets/mustache/documents/tree.mustache, src/ggrc/assets/mustache/objectives/tree.mustache, src/ggrc/assets/mustache/people/tree.mustache, src/ggrc/assets/mustache/programs/tree.mustache, src/ggrc/assets/mustache/requests/tree.mustache, src/ggrc/assets/mustache/responses/tree.mustache, src/ggrc/assets/mustache/sections/tree.mustache
In the top level of the tree the icon is not needed, since we have an icon in the objects tab already.
=> CORE-2862 Show object icons in subtrees only

src/ggrc/assets/mustache/base_objects/notes.mustache, src/ggrc/assets/mustache/programs/modal_content.mustache
- Wrapping notes in a div so we can compare the notes content with what
we wrote in the modal field.
- Add description test id for wysiwyg.
=> QUICK-FIX Update test id tags for selenium tests

src/ggrc/assets/mustache/base_templates/add_comment.mustache, src/ggrc/assets/mustache/base_templates/attachment_list.mustache, src/ggrc_gdrive_integration/assets/javascripts/controllers/gdrive_workflows_controller.js
1. Comment now correctly uploads to the folder set in the audit.
2. When Audit folder is not set, files will be uploaded to the
persons's root folder.
3. Redesigned the no audit folder warning - now a warning icon with a
tooltip
=> CORE-2950 Fix Request Comment folder upload

bin/db_reset
The old db_reset script only worked if the database was empty. Running
it twice in a row would cause it to crash the second time. This commit
makes db_reset script useful and reusable for importing db data.
=> QUICK-FIX Update db_reset script

Dockerfile-selenium, README.md, docker-compose.yml, provision/docker/mysql/default_utf8.cnf, provision/docker/selenium.bashrc.j2, test/selenium/.gitignore, test/selenium/resources/ggrc_test_local.yaml, test/selenium/setup.cfg, test/selenium/src/run_selenium.py
We wish to move away from vagrant and this pull requst make sure we can run selenium tests inside docker containers.
These tests will run, but they will also fail untill we merge https://github.com/google/ggrc-core/pull/3371.
=> QUICK-FIX Add selenium docker container

src/ggrc/migrations/versions/20151216132037_5410607088f9_delete_background_tasks.py, src/ggrc/models/types.py
Even though we have a blob field to store compressed types, we still get
a warning from the database about some invalid utf8 characters. This is
just to remove that warning.
Since delete is the only operation that uses bacground tasks, we are not
worried about clearing the database before changing this model. And
performance is not affected much since most of the parameters that are
stored in the compressed type are tiny.
=> QUICK-FIX Remove zlib from compressed type

test/integration/ggrc/automapper/test_automappings.py
The request in test still returns 201 status code, which shadows the actual error. There was a warning though, @Smotko knows about it.
=> QUICK-FIX Update obsolete request status in test

src/ggrc/assets/javascripts/models/audit_models.js
The script error occurs on pages where GGRC.page_model is not defined
(Import, Export, Admin etc).
=> CORE-2978 Fix request modal error when page_model is not defined

src/ggrc/assets/javascripts/components/csv/export.js, src/ggrc/assets/mustache/base_objects/page_header.mustache, src/ggrc/assets/mustache/import_export/export.mustache, src/ggrc/converters/base.py, src/ggrc/templates/base_objects/_page_header.haml, src/ggrc/templates/import_export/export_content.haml, src/ggrc/views/converters.py
The old data grid export is broken and needs to be fully replaced, This
is a cleanup that is much easier now than it will be once the new data
grid object is fully implemented.
=> CORE-2972 Remove old Data Grid export

src/ggrc/assets/javascripts/models/notification_config.js, src/ggrc/assets/mustache/base_objects/page_header.mustache, src/ggrc/services/__init__.py, src/ggrc/templates/base_objects/_page_header.haml
Two things:
1. I have removed the real-time updates checkbox as we don't have real-time email notifications implemented yet.
2. I had to rename our notification_config service endpoint to notification_configs as otherwise the POST request was failing.
steps to reproduce 2.: 
1. Make sure your current user has no rows in the notification_configs table (this is not the same as not having any notifications enabled). If the user already has a row in notification_configs table PUT request will be sent and not POST.
2. Try to disable email digest notifications.
=> CORE-2992 Fix email checkboxes

src/ggrc/cache/cachemanager.py
@Smotko from collections import OrderedDict seems to be an unnecessary import
=> QUICK-FIX Remove unnecessary import

provision/roles/ggrc/tasks/main.yml
There is no need to install python packages globally we install them
to the virtual env in a later step
=> QUICK-FIX Remove install packages task

.gitignore, Makefile, src/app.yaml.dist, src/ggrc/assets.py
This should fix broken font loading on appengine and it also makes sure that static/images/ static/flash and static/fonts folders are loaded by appengine as static files instead of them being handled by flask.
I still need to figure out why I can't simply add the whole /ggrc/static folder as a static asset. I have tried this, but I started getting server errors from our asset bundler:
```
File "/base/data/home/apps/s~grc-dev/1.389836182148955331/packages.zip/webassets/bundle.py", line 227, in get_version
'determined dynamically, because: %s') % (self, reason))
BundleError: Cannot find version of <Bundle output=dashboard-%(version)s.css, filters=(), contents=('dashboard.css', 'wysihtml5/bootstrap-wysihtml5-0.0.2.css', 'jquery/jquery-ui.css')>. There is no manifest which knows the version, …
```
=> CORE-2003 Add static file handler to app.yaml

bin/check_eslint_diff
NOTE: this PR requires the `ESLint` to be installed, and thus depends on #3463 to be merged first.
=> CORE-2999 Add a script for checking the PR's ESLint issue diff

bin/check_eslint_diff
The PR fixes the following:
* handling empty option values
* empty string is printed instead of 0 when no issues found
* inconsistent indentation
=> QUICK-FIX Fix minor issues in ESLint check script

src/ggrc/services/common.py, src/ggrc_basic_permissions/__init__.py
You can test these changes locally by running `launch_gae_ggrc`. 
From my testing there seems to be a visible improvement when testing locally:
Without permissions cache:
With permissions cache:
But I believe the performance improvement on appengine will be even grater, because without caching grc-dev looks like this:
And I have verified that the bulk of the time in these 17s requests is spent inside the load_permissions_for function that this PR is going to cache:
=> CORE-2403 Cache permissions query

doc/commit_guidelines.md
A rendered version of the submitted document can be [found here](https://github.com/plamut/ggrc-core/blob/feature/core-2944/doc/commit_guidelines.md).
The old version - [link](https://github.com/google/ggrc-core/blob/develop/doc/commit_guidelines.md).
=> CORE-2944 Add guidelines for code checks before issuing a PR

Dockerfile, bin/run_selenium, docker-compose-testing.yml, docker-compose.yml
This makes sure that any user with any uid can run the run_selenium
script in a clean repo clone without and always get the correct results.
=> QUICK-FIX Enable multi tenant docker

src/ggrc/automapper/__init__.py, src/ggrc/converters/handlers/handlers.py
This massively improves performance of auto mappings, especially in imports where there may be a lot of them. 
The problematic CSA import mentioned in the ticket doesn't finish in about 3 days (aborted after that much time) and successfully completes in about 5 minutes on this branch.
I cannot compare the results since before and after this change since nobody managed to import the file on develop but I did compare the results before and after adding the cut optimization - no changes (which is good).
I suggest reviewing this commit-by-commit since I tried to logically separate optimizations and add some minimal documentation in form of comments.
=> CORE-2546 Improve auto mapping performance

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/pbc/workflow_controller.js
To reproduce the original issue run the app locally with `launch_gae_ggrc`. The issue was that the relationship were created at the same moment as owners which caused relationships to fail.
=> CORE-2794 Make sure _create_relationship calls run after pending_joins

src/ggrc/assets/javascripts/models/audit_models.js
This fixes script error on Control Assessment editing.
=> QUCIK-FIX Set CA audit program only in new form

README.md, bin/check_eslint_diff, bin/check_flake8_diff, bin/check_pylint_diff, bin/jenkins/run_eslint, bin/jenkins/run_flake8, bin/jenkins/run_integration, bin/jenkins/run_pylint, bin/jenkins/run_selenium, bin/jenkins/run_unit, bin/run_integration, bin/run_unit, doc/commit_guidelines.md, setup.cfg, src/dev-requirements.txt
Since most scripts in bin folder are meant to be run inside the vm or a container, I think it's wrong that we have scripts for running on the host machine there as well. This PR just moves all scripts that should be run on the host machine into bin/jenkins since that is the primary reason for those scripts.
The name bin/jenkins may be missleading since people can run those on their machines too, and I'm open for better suggestions.
relates to: CORE-2999
=> QUICK-FIX Update jenkins runners

src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache, src/ggrc_workflows/assets/mustache/cycles/info.mustache
If the cycle being viewed is not a current one (e.g. on the workflow's History tab), the delete icon is simply not displayed.
=> CORE-1966 Prevent deleting objects under a non-current Cycle

.eslintrc
Note that this PR will increase the number of ESLint issues found. Do not mind if the build fails solely because of the failed linting check.
=> QUICK-FIX Enable ESLint warnings for non-camelCase names

bin/check_pylint_diff, bin/jenkins/run_code_style, bin/jenkins/run_selenium
Running scripts in bin/jenkins folder as root causes permission issues
inside docker containers. This fix changes the permissions of the shared
folder to match the vagrant user inside the containers.
=> CORE-2999 Fix permissions for jenkins runners

src/ggrc/assets/javascripts/components/relevant_filters.js
Since there is indirect relevancy implemented on the backend export code you must be able to pick some types that you cannot directly see as a widget. 
Currently there is no easy way to get the list of supported indirect mappings on the back end so I opted for listing all widget types. 
We could restructure the indirect mapping helpers and serve the meta-data but it think this is not of great benefit until we're also serving mapping rules from the back-end (for everything).
=> CORE-3001 Show more object types on export relevant dropdown

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/get_default_attr_value_spec.js, src/ggrc/assets/mustache/requests/tree.mustache
The cause of the bug was in a Mustache helper, which has now been fixed.
The linting- and refactoring-related changes are in a separate commit for easier reviewing.
=> CORE-2930 Fix updating the tree view data on Request changes

bin/check_eslint_diff, bin/check_pylint_diff
Linters that compare code from differnt commits should not just checkout
commits on docker volume, since a user might still be working or another
checker might need the current code. Also results of running these
linters is a detached head which is not nice for developers.
This commit makes sure we move everytihng needed for running lint test
to a temp folder before running any tests.
=> QUICK-FIX Make sure lint checks can be run simultaniously

bin/jenkins/functions.sh, bin/jenkins/run_code_style, bin/jenkins/run_integration, bin/jenkins/run_selenium, bin/jenkins/run_unittests
This PR adds option to run jenkins runners with "-p" parameter which
will set the project name to the parent folder of the repo. This should
be used on jenkins to allow concurrent builds which will have workspaces
marked with cosecutive numbers in the folder name.
=> QUICK-FIX Allow custom project names for jenkins runners

test/integration/ggrc/converters/test_import_helpers.py, test/unit/ggrc/converters/test_import_helpers.py
This is mostly due to the typo in the class name, which should not even
exist.
=> QUICK-FIX Clean up python test code

.editorconfig
NOTE: Even though the settings are currently the same for all our source files types (Javascript, CSS, Python), I left them as separate config blocks for a slightly better readability (IMO), and because they are still short enough to easily fit into a single screen page.
=> QUICK-FIX: Update .editorconfig rules 

bin/check_pylint_diff
- Only check modified files.
- Hide double status output on success (-q option on grep).
- List which files will be checked by pylint for users.
=> QUICK-FIX Update pylint checker

src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/models/cycle_task_group.py, src/ggrc_workflows/models/cycle_task_group_object_task.py
This makes user that number of database lookups is not dependent on the ammount of cycle task groups that are related to cycle (or cycles) that we're trying to fetch.
=> CORE-3105 Reduce sql queries on cycle requests

src/ggrc/models/mixins.py
On CSV export, slug's description is missing spaces.
=> QUICK-FIX Add missing spaces in slug's description

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Trampoline the rendering loop instead of setting the same timeout for all rows.
This renders them one by one, giving immediate feedback. But it also causes problems on initial rendering when row rendering is intertwined with place holder rendering. Therefore the special case for first render pass - do is synchronously.
=> CORE-3108 Make tree view render rows one by one

src/ggrc/assets/javascripts/models/business_object_models.js, src/ggrc/assets/javascripts/models/control.js, src/ggrc/assets/javascripts/models/directive_models.js, src/ggrc/assets/javascripts/models/section.js, src/ggrc/assets/javascripts/models/simple_models.js, src/ggrc/assets/javascripts/models/system.js
Implemented by removing default settings - just defaults to all.
To test this open the app in incognito window or reset local storage (`localStorage.clear()` in js console) to clear saved preferences.
=> CORE-2464 Show all object types in sub trees by default

test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
The main part for this commit, is making sure these tests can be run on
a non clean database. Running test_workflow_export worked only because
of the correct test order and if the database was dropped before.
This was relying on the auto-increment id column to start with 1 for
cycles and other objects.
The script 'run_pytests' does not catch it since the database is always
clean and test order never changes. To see this bug you must run the
workflow export tests a couple times in a row.
Changes in this commit include:
- Make tests independent off mysql auto-increment id.
- Fix testing of exported object types. Values should be surrounded with
commas to avoid false negatives.
- Fix indentation.
- Add basic docstrings.
=> QUICK-FIX Clean up workflow export tests

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/models/revision.js
_(please give this a slightly higher priority, because it is blocking other work on the ObjectHistoryLoader feature)_
---
This object is needed as an API client for fetching the revision history from the server, needed by the upcoming ObjectHistoryLoader.
Since this object will not be visible to the users, it has no associated controller and view metadata, just the bare essentials. Please let me know if any other essential part/attribute needs to be defined, or if it still contains something redundant.
No tests, because there's nothing to test really (unless we test the methods that are auto-generated based on the object model's configuration?).
=> CORE-3135 Define a read-only Revision object on the client.

bin/check_pylint_diff, pylintrc
Our evaluation function should prevent the issue count from rising no
matter how many lines of code are added.
This PR is mostly made because I saw that @edofic's PR https://github.com/google/ggrc-core/pull/3550 passed the tests when it should not have
=> QUCK-FIX Update pylint evaluation function

setup.cfg
This prevents flake8 from showing a "No such file or directory" error
which can occur when running automated checks on deleted files.
This commit is already in https://github.com/google/ggrc-core/pull/3546 but we can't wait on that commit, because selenium pr is blocked by this issue.
=> QUICK-FIX Ignore non existing files with flake8

doc/pull_request_reviews.md
**NOTE:** There are still two pieces missing - the section on Docker and on reviewing the PRs containing DB migration scripts. Both are marked with a TODO comment. I need help on this, as I have almost no experience with either. Please send any pull request to my `fix-pr-guide` branch, thanks!
----
For convenience, here's the link to the rendered version of the new file - https://github.com/plamut/ggrc-core/blob/fix-pr-guide/doc/pull_request_reviews.md
The existing file - https://github.com/google/ggrc-core/blob/develop/doc/pull_request_reviews.md
=> QUICK-FIX Update the PR review guide

bin/check, bin/check_flake8_diff, bin/check_pylint_diff
- Add a missing license header.
- Add help texts.
- Allow flake8 checker to specify what branch to check.
- Fix flake8 chekc on a normal commit. Now it checks the current commit
instead of the previous one.
=> QUICK-FIX Update python checker scripts

bin/check_flake8_diff, bin/check_pylint_diff
The if statement was broken, causing all flake8 checks to pass. This
makes sure that the conditions in the if statement work as intended.
This was the result before:
https://jenkins.reciprocitylabs.com/job/ggrc_code_style/261/console
=> QUICK-FIX Fix flake8 checks

bin/run_karma
Specify to use our karma and not system default (which doesn't
have additional modules that we need)
=> QUICK-FIX Explicitly set which karma to use

src/ggrc/migrations/versions/20151015124337_1ef8f4f504ae_remove_relationship_types.py, src/ggrc/migrations/versions/20160113150536_4003827b3d48_drop_unused_tables.py, src/ggrc/migrations/versions/20160113152055_1abb0a2e8ca0_rename_control_assessments.py, src/ggrc/migrations/versions/20160203143912_6bed0575a0b_migrate_assessment_to_assignable_mixin.py
With https://github.com/google/ggrc-core/commit/3f5d9653b648dd76de86e76da0337e7bccb8e1a7 we broke the migrations for existing databases, this fixes those migration to only execute certain actions if needed.
=> CORE-3163 Fix migrations

bin/init_env, bin/launch_ggrc_test, bin/run_behave, bin/run_integration, bin/run_pytests, bin/run_travis_tests
Due to recent reversal of dependencies between the workflows and gdrive
extensions, the gdrive extension should be loaded after the workflows
extension.
=> QUICK-FIX Update extensions load order, refactor

bower.json, src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/date_spec.js, src/ggrc/assets/mustache/base_templates/attachment.mustache, src/ggrc/assets/mustache/base_templates/dates_list.mustache
This PR renders times in local time but it has issues with times that go across winter/summer time. Winter/summer label (CET/CEST) gets render correctly but the rendering sets offset from UTC per current offset and not offset at the time of post - this means that a post made during the winter at 4:35 PM CET (3:35 PM UTC) get rendered as 5:35 PM CET during summer when +2 offset is in play for CEST.
Per discussion with Prasanna that is not an issue for now (since we save in UTC anyway and it's only a rendering issue), created a ticket for technical debt.
=> CORE-2803 Render datetime in local time

src/ggrc/assets/javascripts/models/mappings.js, src/ggrc/models/request.py
This PR depends on #3550 - since it was blocked, it was based on it, thus it includes the change set from #3550 
The ListLoader described in the [ticket](https://reciprocitylabs.atlassian.net/browse/CORE-3077) was not created, because it turned out that is not needed.
=> CORE-3077 Add revision history property to Request object

bin/check_pylint_diff
Since pylint sometimes doesn't pick up results from a previous run.
=> QUICK-FIX Manually compute pylint score diff

bin/check_flake8_diff, bin/check_pylint_diff
- Use branch argument on flake8 check only if it's actually set.
- Hide git clean messages from pylint checker.
If you take a look at the code style result here https://jenkins.reciprocitylabs.com/job/ggrc_code_style/300/console
you'll see that no file changes were found for flake8 and the pylint has teh ugly remove messages for non tracked files. This PR just fixes these two issues.
=> QUICK-FIX Update python linters

src/ggrc/migrations/versions/20160128111512_4e989ef86619_add_connected_objects_to_revisions.py, src/ggrc/models/mixins.py, src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py
This stores connected objects in revisions for join objects so you can fetch revisions of join objects given only object type and id.
Still needs some work, but I'd like some feedback on naming and overall design.
TODO:
=> CORE-3074 CORE-3076 Search revisions of join objects

package.json
Karma unit tests were not reported correctly by jenkins because of the missing dependency.
```
Running karma tests
Initializing environment
[33m15 02 2016 13:16:57.031:WARN [reporter]: [39mCan not load "junit", it is not registered!
Perhaps you are missing some plugin?
```
=> QUICK-FIX Add karma-junit-reporter to package.json

src/ggrc/services/common.py
Without this fix, mappings between objects, created by a user in a Creator role are persisted in the DB but not shown correctly on the frontend. E.g. if one creates a mapping between two objects as a Creator and (hard) refreshes the page the mapping just created vanishes.
With changes, behavior is as expected.
Originally, this was @phyro's contribution.
=> QUICK-FIX Fix permissions check for the Creator role

bin/check_eslint_diff, bin/check_pylint_diff
Since we have diff checks for js and python linters, we have to compare
the results from different commits. This commit makes sure that we
always perform these checks on a clean repo and that checkouts never
fail.
=> QUICK-FIX Clean current repo before running linters

bin/init_env, bin/jenkins/run_code_style, package.json
Es lint checks were broken due to missing dependecies and missing node path. Hopefully this PR fixes all eslint issues.
=> QUICK-FIX Add eslint checks back

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/revisions_diff_spec.js
Snatch attribute names from exports and hide non-exportable fields.
=> CORE-3203 Use display names in request log

src/ggrc/assets/javascripts/apps/quick_search.js, src/ggrc/assets/javascripts/bootstrap/modal-form.js, src/ggrc/assets/javascripts/controllers/assessment_generator.js, src/ggrc/assets/javascripts/controllers/delete_modal_controller.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/services/common.py
We were creating alert boxes by concatenating strings of html along with the error message. This fix makes sure the error message is properly escaped before appending it to the DOM (using jQuery.text()).
=> CORE-3214 CORE-3215 Prevent XSS attack in script error alert

pylintrc
This commit addresses these warnings when running pylint:
- option profile is obsolete and it is slated for removal in Pylint 1.6.
- option comment is obsolete and it is slated for removal in Pylint 1.6.
- option required-attributes is obsolete and it is slated for removal in
Pylint 1.6.
- option ignore-iface-methods is obsolete and it is slated for removal
in Pylint 1.6.
- option zope is obsolete and it is slated for removal in Pylint 1.6.
=> QUICK-FIX Remove obsolete options from pylintrc

bin/check_eslint_diff
If not given, the `$TARGET_BRANCH` variable is empty, resulting in a missing part of the sentence in the output. This PR fixes that by making the output sentence generic.
=> QUICK-FIX Fix empty branch name in ESLint check script

src/dev-requirements.txt
The pytest selenium 1.0 has a bug that always throws this warning:
```
======================= pytest-warning summary =======================
WI1 /vagrant-dev/opt/dev_virtualenv/local/lib/python2.7/site-packages/
pytest_selenium/pytest_selenium.py:90 'pytest_runtest_makereport' hook
uses deprecated __multicall__ argument
```
Upgrading to version 1.1 will make sure that our tests can pass without
a warning.
=> QUICK-FIX Update pytest-selenium package

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/revisions_diff_spec.js
The commit also updates the `revisionDiff` helper method's docstring. Meant as the missing part of the already merged #3587
=> QUICK-FIX Add more tests for the revisions_diff helper

bin/check_pylint_diff
Running pylint checker when you only add a single python file will fail
since the file does not exist on the previous commit.
Blocking https://github.com/google/ggrc-core/pull/3611
=> QUICK-FIX Fix pylint checker script

src/ggrc_basic_permissions/roles/Creator.py
The condition was always false becasue we don't
assign object owners to documents anywhere.
Additionally, the owners condition prevented read
permission from audit contexts from propagating.
=> CORE-3261 Attached evidence isn't shown in the comments section under the a request

src/ggrc/assets/stylesheets/_setup.scss
When there is no `px` unit in `$baseFontSize` variable we are having some issues in application.
=> CORE-3289 Fix font variable value

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
When linting the merge from zucchini, I accidentally broke tree view rendering when scrolling. This fixes the regression caused.
=> QUICK-FIX Fix script error caused by linting

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/apps/base_widgets.js, src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/bootstrap/modal-ajax.js, src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/javascripts/components/mapper.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/mappings.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/pbc/workflow_controller.js, src/ggrc/assets/javascripts/plugins/lodash_helpers.js, src/ggrc/assets/javascripts/plugins/tests/lodash_helpers_spec.js, src/ggrc/assets/js_specs/models/assessment_template_spec.js, src/ggrc/assets/js_specs/mustache_helpers/model_info_spec.js, src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache, src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache, src/ggrc/assets/stylesheets/_common.scss, src/ggrc/assets/stylesheets/layout/_container.scss, src/ggrc/assets/stylesheets/modules/_modal.scss, src/ggrc/cache/cache.py, src/ggrc/migrations/versions/20160225114925_1894405f14ef_add_assessmenttemplate.py, src/ggrc/models/all_models.py, src/ggrc/models/assessment_template.py, src/ggrc/services/__init__.py, src/ggrc/views/__init__.py, src/ggrc_basic_permissions/roles/ProgramAuditOwner.py, src/ggrc_basic_permissions/roles/Reader.py
This is the first working version of the PR. It is now possible to open an AssessmentTemplate modal (from the Audit's info pane only) and create a new AssessmentTemplate.
It probably needs more polishing, e.g. conditionally enabling/disabling form fields based on their values. 
We probably also need a way to edit an existing Audit's AssessmentTemplate, but to my knowledge we don't have UI mockups to see how an Audit's existing (if any) AssessmentTemplate should be shown. Might be better to resolve this under a separate ticket...
I am also not sure about the status of the custom attributes functionality, please ping @hyperNURb for that.
**Update:** It seems that there are a lot of failed and erroneous Selenium/integration tests, lots of timeout errors in the Jenkins build log. Not sure …
=> CORE-3154 Add AssessmentTemplate entity

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/plugins/component_registry.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/component_registry_spec.js
This will allow us to register CanJS components, making it possible for the tests suites to obtain references to them, and hence test them.
=> CORE-3270 Add component registry

src/ggrc/migrations/script.py.mako, src/ggrc_basic_permissions/migrations/script.py.mako, src/ggrc_gdrive_integration/migrations/script.py.mako
This PR modifies the template used for generating DB migration scripts. While it doesn't make the generated files code style-compliant out of the box (that would require patching Alembic's methods for the auto-generated code), it nevertheless removes at least some of the current annoyances by the following:
* The Copyright info header is now automatically added
* The revision numbers are removed from the module's docstring  - these were frequently forgotten to be updated, and they are obvious anyway from the corresponding module-level variables
* The imports have been moved to the top of the file where they should be, right after the module docstring,
* The pylint's "invalid name" warning is automatically silenced - the complaints about the invalid module name and Alembic variables' names …
=> QUICK-FIX Reduce lint errors in migration script templates

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/if_string_spec.js, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/models/assessment_template.py
This PR makes the AssessmentTemplate's `info.mustache` template useful. It also adds transparent (de)serializiation of the the `default_people` JSON field.
**Note:** Due to time constraints the actual users are not show, only their IDs. I primarily wanted to unblock @Smotko because he will need this info when working on a related feature.
=> CORE-3304 Display AssessmentTemplate's info on the info pane

src/ggrc/app.py, src/requirements.txt
When SQLALCHEMY_RECORD_QUERIES is enabled we will now run EXPLAIN on
queries that ran longer than 0.5s. This will allow us to see potential
bottlenecks in logs on cloud console.
=> QUICK-FIX Explain queries that ran for more than 0.5s

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/js_specs/models/assessment_template_spec.js, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
This populates AssessmentTemplate's the add/edit form, establishes proper two-way bindings between the form fields and the model, and basically makes the whole thing usable for editing existing objects.
Depends on #3657
=> CORE-3310 Enable editing an existing AssessmentTemplate

bin/check, bin/check_pylint_diff, pylintrc
The check_pylint_diff script used wrong commits while running
'check_pylint_diff develop' on a feature branch. This fix makes sure
that running that on a feature branch works as the help suggests and is
the same as running 'check_pylint_diff' on a merge commit from that
branch. And we want all pylint checks to display the same message template with
error codes.
=> QUICK-FIX Update pylint

bin/check, bin/check_pylint_diff, pylintrc
Reverts google/ggrc-core#3665 because it broke pylint warning logging on the develop jenkins job.
=> Revert "QUICK-FIX Update pylint"

src/ggrc/converters/handlers/handlers.py, src/ggrc/converters/handlers/related_person.py, src/ggrc_basic_permissions/converters/handlers.py
This fixes incorrect usages of `super()`. If any of the affected classes were subclassed, and their subclass would call `super(ChildClass, self).__init__()`, a _maximum recursion depth exceeded_ error would occur.
The reason is that when invoking `super(self.__class__, self)` in one of these classes, `self` would actually be an instance of `ChildClass`. Python would search for the right class, but starting from `self.__class__`, i.e. the `ChildClass`!
It would found the parent class, invoke its method, encountering and invoking `super(self.__class__, self).__init__()` again, causing an infinite recursion.
=> QUICK-FIX Prevent potential infinite recursion bugs

src/ggrc/app.py
The EXPLAIN query is failing on appengine and additional info is needed
to figure out what is causing the failure.
=> QUICK-FIX Log failed EXPLAIN queries instead of returning a 500 error

src/ggrc_workflows/assets/javascripts/apps/workflows.js
There was an issue on the export page, where it didn't break anything, but it produced a console error. This fixes the console error.
=> QUICK-FIX: Add cycle task to subtrees only if they are defined

src/ggrc/assets/javascripts/controllers/comment_controller.js
The problem was, that scope.attachments was always empty, so I changed it to use the same thing as the comment attachment preview is using for displaying the objects, since it's only used to determine if there are any attachments.
=> CORE-3235 Fix evidence comments

src/ggrc/assets/stylesheets/_custom_font_awesome_icons.scss
The icon does not look intuitive to me, but @vladan-m confirmed that this is indeed the correct pick according to the specs.
=> CORE-3306 Add an icon for the AssessmentTemplate widget

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/migrations/versions/20160322211955_9db8d85e82b_add_title_to_assessmenttemplate.py, src/ggrc/models/assessment_template.py
The title says it all.
The title is not  required to be unique, because users might not even know what other AssessmentTemplates exist when creating their owns for their Audits, thus they probably shouldn't guess which AssessmentTemplate titles are already taken (makes sense?).
=> CORE-3312 Add title field to the AssessmentTemplate object

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js, src/ggrc/assets/mustache/components/object_history/object_history.mustache
I also refactored the history component to use plain JS objects and arrays
insted of the CanJS counterparts since some CanJS magic was modifying the data
and I don't think CanJS wrappers are needed here.
=> CORE-3201 Show users with popover in request log

src/ggrc/assets/mustache/components/object_history/object_history.mustache
This is safe because we clean out the values when storing them.
=> CORE-3378 Show formated values in request log

src/ggrc_risks/assets/javascripts/apps/risks.js
Related issue: ZEN-2391
Basically if someone else creates a risk you won't see it on the all objects page. You will see only your risks, which is wrong since this is the ALL objects page.
=> QUICK-FIX: Show all risks and threats on all objects page

src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/mappings.js, src/ggrc/assets/javascripts/pbc/workflow_controller.js, src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache, src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/migrations/versions/20160314155056_39aec99639d5_add_defintion_id_to_ca_definitions.py, src/ggrc/models/custom_attribute_definition.py
This saves custom attribute definitions from assessment template to the database. It should be enough to unblock @hyperNURb's CORE-2966, but editing the assessment template is not yet functional.
=> CORE-3155 Object level custom attribute definitions

src/ggrc/services/common.py
There is at least one handler that executes in between an item being added to
cache and log_event happening. This is
`Slugged#ensure_slug_after_flush_postexec`. As a result revision entry stores
a stale slug which looks like corrupted data to the user inside the object
history log. By not using the cached value and recomputing the json we can
avoid this at minimal cost.
=> QUICK-FIX Use fresh json for logging revisions

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Using `date` mustache helper to be consistent with other dates.
I listed other date fields that are not (yet!) present on the Request object to catch future use cases.
=> CORE-3204 Format date fields in request log 

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js, src/ggrc/assets/mustache/components/object_history/object_history.mustache, src/ggrc/models/relationship.py
In this PR:
- fetch mapped objects and use `display_name`s for human-friendlines
- fix `Relationship` to store `attrs` in `Revision`
- unify `change` format between fields and mappings (for more flexibility and cleaner template)
- display assignee roles in mappings history
- access mapping history (already fetched) to show original value for assignee roles
=> CORE-3367 Show object display names in request log mappings

src/ggrc_gdrive_integration/assets/javascripts/controllers/gdrive_workflows_controller.js, src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
Now ggrc will only have access to publicly accessible files
in GDrive and files created or shared with the app. The app
will no longer have full access to user's GDrive.
=> CORE-3395 Limit permission scope for GDrive

src/ggrc/assets/javascripts/models/mappings.js, src/ggrc/assets/mustache/modals/mapper/base.mustache
Not the most elegant solution (added a special case for AssessmentTemplates to the base mapper modal template), but according to @hyperNURb the most sensible case to do nevertheless.
There is a slight issue with previewing AssessmentTemplate objects in the modal (sometimes it does not work), but I was told this is outside the scope of this PR, since it seems to be a bug in the multimapper itself - the important thing is that creating new AssessmentTemplates and mapping them to an Audit now works.
=> CORE-3305 Allow picking AssessmentTemplate in multimapper

src/ggrc/assets/javascripts/components/object_history/object_history.js
A change between `undefined` and `null` should not be shown as a change since
both is `—` for the user.
=> CORE-3400 Hide empty diff entries in request log

src/ggrc/assets/mustache/assessments/info.mustache
Show revision history on Assessments.
*NOTE*: this PR does not intend to cover any additional cases introduced by Assessments, it just enables the log. Any additional features should go into separate tickets
=> CORE-3404 Assessment log

src/ggrc/assets/mustache/requests/info.mustache, src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
Disable warning when moving from `Open` to `In Progress` when attaching evidence.
=> CORE-3392 Disable warning when attaching evidence

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/autocomplete/autocomplete.js, src/ggrc/assets/javascripts/components/autocomplete/tests/autocomplete_spec.js, src/ggrc/assets/javascripts/components/person/person.js, src/ggrc/assets/javascripts/components/person/tests/person_spec.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/js_specs/models/assessment_template_spec.js, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/assets/mustache/components/autocomplete/autocomplete.mustache, src/ggrc/assets/mustache/components/person/person.mustache, src/ggrc/assets/stylesheets/modules/_modal.scss
This PR adds the `autocomplete` and `personItem` components, because the existing autocomplete widgets found in other modals were not useful, unfortunately - they want to do too much magic behind the scenes, e.g. mapping the picked item to the modal's underlying instance, but we don't want that for Assessment Templates, those Person items shouldn't be mapped to them.
The `autocomplete` component uses the existing autocomplete internally, but with an added hack to the `modals_controller` which breaks the `autocomplete`'s tight coupling with the latter.
=> CORE-3307 Add Persons live search to AssessmentTemplate modal

src/ggrc_workflows/assets/javascripts/models/cycle_models.js
Current default info is pretty useless, we showed basically just workflow.
=> CORE-3419 Show assignee and start_date by default on treeview for tasks

src/ggrc/assets/javascripts/components/assessment_attributes.js
This is relevant to #3709 since wrong CA type causes it to not render in the generated assessment edit modal.
=> QUICK-FIX Fix Person type custom attr in assessment template

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js, src/ggrc/assets/javascripts/components/tabs.js, src/ggrc/assets/javascripts/components/tabs_spec.js, src/ggrc/models/object_document.py
This does multiple things:
- enables fetching of indirect mappings (currently coded here, not exploring mappings.js)
- enables indexing of `ObjectDocument` join objects
- fixes a bug in the tab switches
- introduces tests for the tab switcher
=> CORE-3382 show evidence in the change log

doc/branch_management.md
The branch documentation is obsolete since we moved to forks instead of all of us working on the same repo.
That's why it does not make sense to force everyone to use feature/ prefix for the branches.
This PR si meant as an open discussion on the topic.
=> QUICK-FIX Update branch management documentation

.eslintrc, src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/apps/dashboard.js, src/ggrc/assets/mustache/assessments/tree_header.mustache, src/ggrc/templates/assessments_view/index.haml, src/ggrc/views/__init__.py
This PR adds a new and distraction-free `/assessments_view` view that only displays thel Assessments assigned to the current user's, without any other unnecessary page elements such as LHN, the widgets bar etc.
The PR also lints the `apps/dashboard.js` file, thus I recommend reviewing this on a commit-to-commit basis to see what has changed in there in terms of business logic.
=> CORE-3394 Simplifiy Assessor User Experience

src/ggrc/assets/javascripts/models/join_models.js, test/selenium/src/lib/constants/locator.py
`people_list_widget` which was not visible and therefore not clickable
causing the selenium test to fail.
This should make the custom attributes test pass, but I expect the selenium tests to fail because of   another issue (waiting for redirect when clicking save & add another).
-  [x] Fix creation of objects (this was not a Selenium test issue, but an issue introduced by 5ecef933e400fafa8234d778cb92a86590eccc7c
```
request = <SubRequest 'selenium' for <Function 'test_app_redirects_to_new_risk_page'>>
capabilities = {'browserName': 'Chrome', 'platform': 'Any'}
@pytest.fixture
def selenium(request, capabilities):
"""Returns a WebDriver instance based on options and capabilities"""
from .driver import start_driver
>       driver = start_driver(request.node, capabilities) …
```
=> QUICK-FIX Fix selenium tests

src/ggrc/assets/javascripts/components/assessment_attributes.js
The list of possible choices is now in line with the similar list on the Admin panel's custom attribute definitions page.
**Note:** A few things from the ticket that need additional clarification, such as maybe adding the Radio type and changing how Checkbox type behaves, are intentionally omitted from this PR. I will open separate tickets for these as discussed with @Smotko
=> CORE-2508 Adjust AssessmentTemplate's custom attribute types

src/ggrc/assets/mustache/assessment_templates/info.mustache
**Note:** the trash icon (i.e. the Delete button) is still being displayed next to the user name, but that will change when @hyperNURb finishes the ticket he is currently working on - that ticket will alter the behavior of the `<person>` component, hiding the Delete button by default unless an `on-delete` handler is provided. I thus didn't address that in this PR.
=> CORE-3440 Display full usernames on AssessmentTemplate info

README.md
Python cache breaks building packages installed by pip so reprovisioning doesn't work if the repo isn't clean.
=> QUICK-FIX Update docker provisioning in the project readme file

src/ggrc/assets/javascripts/plugins/autocomplete.js
The script was erroring because the autocomplete_select function wasn't being called from the correct context
=> CORE-3043 Fix uncaught script error while creating program

src/ggrc/assets/javascripts/apps/base_widgets.js, src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/models/mappings.js, src/ggrc/models/hooks/assessment.py, src/ggrc/utils.py, test/unit/ggrc/test_utils.py
As part of CORE-3387 I had to create all possible mappings to Audit and I noticed the app did not allow mapping Directives + Objectives and that creating Assessments without a template failed.
=> QUICK-FIX Fix Audit mappings

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/mustache/assessments/modal_content.mustache, src/ggrc/assets/mustache/base_templates/add_comment.mustache, src/ggrc/assets/mustache/base_templates/attachment_list.mustache, src/ggrc/assets/mustache/mixins/stateful.mustache
**depends on** #3709
Implements handling of mandatory comments and attachments on assessments:
- disable finish button
- show notifications that you should make a comment or attach evidence
Still needs polishing (and is blocked by #3709 merge)
=> CORE-2964 Handling mandatory comments and attachments

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
If you create an object (DataAsset for instance) with a creator and then go to create Request modal window and try to map it you will not be allowed to map that DataAsset. The same thing happens when trying to map objects on cycletask create modal.
Also do you guys think it would be safer to check if ```source.type``` is undefined? Does anyone know of a case where sourceContext would be undefined and you would not be on create modal window?
=> QUICK-FIX mapping permissions for Creator/Reader

src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
This hides the add new cycle task button in the cycle view also on quarterly workflows.
=> QUICK-FIX: Add quarterly to list of ignored workflows for add task button

src/app.yaml.dist, src/ggrc/settings/default.py
In production the fonts are not loading (chrome is canceling the request). This is a potential fix for the problem.
Deployed here: https://nostatic-dot-grc-dev.appspot.com/
=> QUICK-FIX Use flask's static file handler

src/ggrc/assets/mustache/events/object_list.mustache, src/ggrc/assets/mustache/people/object_list.mustache
Next and previous buttons were being hidden by page footer
=> CORE-3474 Make pagination visible in admin page

src/ggrc_basic_permissions/__init__.py
I noticed some requests were still taking more than 2s on grc-dev. I have removed the OR clause and replace it with the UNION to improve performance.
=> CORE-3387 Replace OR with UNION in _join_filter

src/ggrc/assets/mustache/base_objects/tree.mustache
This removes the tooltips as suggested in a [comment](https://reciprocitylabs.atlassian.net/browse/CORE-3509?focusedCommentId=26444&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26444) under the ticket.
The other issue (highlighting the clicked tree item) will be dealt with in a [separate ticket](https://reciprocitylabs.atlassian.net/browse/CORE-3515).
=> CORE-3509 Remove tooltips when hovering tree view title bars

src/ggrc_workflows/__init__.py
The issue was caused by `task_group_task` being `None`, added additional check for that case.
(without a test, same reason as in #3789 :/ )
=> CORE-3370 Fix starting particular Workflow tasks

src/ggrc_workflows/assets/javascripts/models/cycle_models.js
What we get when creating a new task is not always a proper stub, but just id and Type and maybe something else, so we can't always check it with can.Stub
=> QUICK-FIX: Check if we don't get the full workflow instance on form populate

test/integration/ggrc/automapper/test_automappings.py, test/integration/ggrc/notifications/test_assignable_notifications.py
The PR https://github.com/google/ggrc-core/pull/3801 was missing this change and it causes warnings to appear in the integration tests. 
See: https://jenkins.reciprocitylabs.com/job/ggrc_integration/1158/console
=> QUICK-FIX Change status from Open to Not Started

src/ggrc/assets/javascripts/controllers/tests/tree_view_controller_spec.js, src/ggrc/assets/javascripts/controllers/tests/tree_view_node_controller_spec.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/mustache/base_objects/tree.mustache
The issue was caused if something triggered a refresh of the active tree node, causing it to render itself with the vanilla template, but there was nothing that applied the `active` CSS class to it.
This fix computes the `isActive` flag upon rendering, sending it to the tree node template's scope, allowing it to render itself properly.
=> CORE-3515 Fix highlighting of the active tree view node

README.md
1. Make the docker dev env the default
2. Add a link to docker toolbox for users using osx/widnows
3. Mention docker-machine start for users using osx/windows
=> QUICK-FIX Update the quickstart portion of the readme

src/ggrc/assets/javascripts/models/audit_models.js
When you create a request from the assessment info page, there is an internal server error because the frontend tries to add a relationship: Control <--> Requests. Because Control is not mapped to the Assessment, the source in the relationship is `null`. Which crashes a subscriber to the POST Relationship event at the backend.
=> CORE-3499: Error message on request creation from assessment

src/ggrc_workflows/assets/mustache/workflows/info.mustache
There is a clone icon in font awesome, we should use it?
=> QUICK-FIX Fix Workflow clone icon

test/integration/ggrc/notifications/test_assignable_notifications.py
Fixes #3807 edits to attributes instead of hard coded strings.
=> QUICK-FIX Replace hard coded strings with object states

src/ggrc/assets/javascripts/controllers/tests/tree_view_node_controller_spec.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js
The TreeNode controller now correctly determines whether the node is currently expanded or not.
Also, a small improvement has been added, preventing a subtree from being unnecessarily reloaded when selecting an already selected (i.e. active) node.
=> CORE-3529 Fix loading subtrees when expanding collapsed node

src/ggrc_workflows/__init__.py, src/ggrc_workflows/services/workflow_cycle_calculator/cycle_calculator.py, src/requirements-dev.txt, test/unit/ggrc_workflows/test_ggrc_workflows.py
The cause of the bug was an attempt to compare a `date` object with a `datetime` object, because somewhere in the code a workflow's `non_adjusted_next_cycle_start_date` was was set to a `datetime` instance (instead of the expected `date`).
The easiest way to verify this is to try to finish a workflow with a `NULL` `non_adjusted_next_cycle_start_date` column before and after the fix.
Alternatively, one can use the ggrc-dev server's DB dump and try to finish the active cycle of the workflow 1259, just as described in the ticket.
<sub>No unit tests, sadly, because it is likely that some non-trivial refactoring would have to take place to avoid disproportionally large fixtures. :/</sub>
=> CORE-3405 Fix finishing particular workflow cycles

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js, src/ggrc/models/mixins.py
This does multiple changes
- update custom attribute saving backend logic to use the ORM and not directly create objects (enables next step)
- store custom attribute values as part of revisions
- store custom attribute definitions as part of revisions (to freeze field names & types in time)
- wires up auto refresh of the change log on instance update to better integrate with inline edits
=> CORE-3399 Show custom attributes in the change log

src/ggrc/assets/javascripts/models/audit_models.js
=> CORE-3493 Remove "Owner" column from Assessment's tree view

src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/assessments/reusable_objects.mustache, src/ggrc/assets/mustache/base_templates/mapping_tree_view.mustache, src/ggrc/assets/mustache/base_templates/subtree.mustache, src/ggrc/assets/mustache/requests/reusable_objects.mustache, src/ggrc/assets/stylesheets/modules/_attachment-list.scss
List of mapped objects is now displayed like:
=> CORE-3491 Fix broken display of relevant assessments

provision/docker/vagrant.bashrc
Provisioning steps do not create the proper symbolic links needed for
the dev environment to work. This also applies after cleaning the repo
and reprovisioning or if a user manually deletes these links. This fix
makes sure that once a user enters the dev environment it works as
expected.
This is a fix for the issue https://github.com/google/ggrc-core/issues/3838.
=> QUICK-FIX Fix dev environment

src/ggrc/automapper/__init__.py
This adds an instance cache so that the app does not fetch the instance while considering implicit mappings.
From my tests this more than halves the number of executed selects on the database, in my test case with 110 mapped controls and 10 mapped objectives I got the following results:
```
Total queries with optimization: 188
Total queries without optimization: 428
```
There is still a problem with this query: https://github.com/google/ggrc-core/blob/develop/src/ggrc/automapper/__init__.py#L205 which is still executed 120 times. I'll be looking in ways to remove this query now, but this might not be done before the potential push to prod later today, so please merge this if you don't find any issues.
=> CORE-3579 Reduce the number of SELECTs executed by automappings

src/ggrc/automapper/__init__.py
Removed the hook that fires on Audit PUT event since we are not supporting
editing of the program anyway (not even via the API) so this will not introduce
any consistency issues.
This makes Audit editing fast even if the underlying program has many mapped objects.
=> QUICK-FIX Disable AutomapperGenerator on Audit edit

src/ggrc/automapper/__init__.py
This makes the check more pessimistic but it turns out that a bigger `INSERT IGNORE` + more python run time is much cheaper than a large number of SQL queries.
This is critical because this has a big impact on Audit creation times.
Also see CORE-2546 - I noticed about 25% improvements (on my machine) in that case as well.
=> QUICK-FIX Reduce # of sql queries in automapper

src/ggrc/automapper/__init__.py, src/ggrc_basic_permissions/__init__.py, src/ggrc_workflows/models/workflow.py
With some data sets it's impossible to map existing programs to existing controls (from the control info page, program widget). Could not reproduce with clean db but easily with grc-dev dump.
This fixes multiple issues and unblocks the mapping.
=> QUICK-FIX Fix mapping programs to controls

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/models/assessment_template.py, src/ggrc/models/hooks/assessment.py, test/unit/ggrc/models/hooks/test_assessment.py
~~The ticket says to add this option to the Default Verifier dropdown list, but I presume it needs to be added to the Default Assessors dropdown as well (to date both dropdowns have had identical options to select).~~
~~**Update:** There is no business logic for an Assessor to be an auditor, thus this needs to be updated.~~
**Update 2:** The lack of special business logic does not imply that an option should not be present in the dropdown, it was confirmed that it is fine if both dropdowns remain identical.
**Note:** This PR is based on #3861 I suggest to review and merge the latter first.
=> CORE-3578 Add "Auditors" to the default people option

src/ggrc/models/assessment_template.py, src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/mixins.py, src/ggrc/views/__init__.py
Having 2000+ custom attribute definitions injected into the base
template increased the page load by multiple seconds. This fix should
greatly increase page load times on system with a big amount of custom
attribute definitions on the object level.
=> QUICK-FIX Fix custom attribute loading

src/ggrc/models/hooks/assessment.py, src/ggrc/services/common.py
This should reduce the number of queries per assessment by about 25%
=> CORE-3575 Reduce queries when generating assessments

src/ggrc_workflows/assets/javascripts/models/cycle_models.js
This PR auto populates the cycle task creation modal with default dates. Currently you can only make a cycle task for one time workflows, that's why logic is done only for this frequency.
=> CORE-3527 Prepopulate cycletask default dates

pylintrc, src/ggrc/services/common.py
Linting caused a name collision with the obj variable and caused
collection_post to fail.
=> QUICK-FIX Fix cache manager issue after linting common.py

src/ggrc/assets/javascripts/components/assessment_generator.js, src/ggrc/assets/javascripts/models/save_queue.js
=> QUICK-FIX Background task improvements

src/ggrc/services/common.py
Set attributable_id to parent object instead of to custom
attribute value's ID (which is obj.id in the scope of the loop
after recent linting changes).
=> QUICK-FIX Fix `set_ids_for_new_custom_attributes`

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js
This fixes entries for `Recipients` on `Assessments` by treating a list of empty values as an empty list.
=> CORE-3399 Handle list type fields in change log

src/ggrc/assets/javascripts/models/audit_models.js
I was not able to reproduce this issue locally, even after discussing it with Kostya yet again, but by seeing it on the test server I was able to create the fix.
See the comments under the ticket for the link to an Assessment where the issue can be observed.
=> CORE-3467 Fix script error when loading an Assessment

src/ggrc/models/__init__.py, src/ggrc/utils/__init__.py, src/ggrc/utils/html_cleaner.py, test/unit/ggrc/test_utils.py
This now also handles cases with nested script tags, for example
```
<<script>s<script>c<script>r<script>i<script>p<script>t<script>>alert(1)<script>/<script>s<script>c<script>r<script>i<script>p<script>t<script>>
```
=> QUICK-FIX Fix backend rich text cleaner

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/mustache/assessments/tree.mustache, src/ggrc/assets/mustache/audits/tree.mustache, src/ggrc/assets/mustache/base_objects/open_close.mustache, src/ggrc/assets/mustache/base_objects/tree.mustache, src/ggrc/assets/mustache/controls/tree.mustache, src/ggrc/assets/mustache/custom_attribute_definitions/tree.mustache, src/ggrc/assets/mustache/directives/tree.mustache, src/ggrc/assets/mustache/documents/tree.mustache, src/ggrc/assets/mustache/objectives/tree.mustache, src/ggrc/assets/mustache/people/object_list.mustache, src/ggrc/assets/mustache/people/tree.mustache, src/ggrc/assets/mustache/programs/tree.mustache, src/ggrc/assets/mustache/requests/tree.mustache, src/ggrc/assets/mustache/search/advanced_search_people_items.mustache, src/ggrc/assets/mustache/sections/tree.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_objects/tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_groups/tree.mustache, src/ggrc_workflows/assets/mustache/cycles/tree.mustache, src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_option_items.mustache, src/ggrc_workflows/assets/mustache/selectors/object_selector_option_items.mustache, src/ggrc_workflows/assets/mustache/workflows/tree.mustache
Changed the way items are scheduled for rendering by scheduling them all
upfront instead of chaining them. This makes them render faster but isn't as
smooth.
Stopped replacing a rendered item with a placeholder when it is no
longer visible. This decreases the amount of re-rendering for the browser
but risks increasing the memory use. This seemed to not affect performance
for ~750 objects but needs some more testing.
Decreased the delay between the user stopping scrolling and the item
rendering starting.
Sped up template rendering of each item by switching open_close
template to use 'renderLive' instead of 'render'. Serializing the
context in the 'render' function was taking about 40% of the rendering
time. It is still taking ~30ms to draw each item.
=> CORE-3571 Speed up tree view item rendering

src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/migrations/versions/20160524154938_4e9b71cece04_remove_custom_attribute_checkbox_options.py
Removed multi_choice_options which aren't really applicable for checkboxes.
I'll look into creating a new multi-choice component if wanted (waiting on reply from Akhil in Jira ticket)
=> CORE-3620 Remove multi choice options from checkbox

src/ggrc/assets/javascripts/models/audit_models.js
This changes the way the issue was resolved in #3890 - the latter PR only fixed the symptom, but no the cause itself, which was that custom attributes data has not been loaded yet when needed.
This PR also reverts the fix done in #3890 because if there happens to be another bug, we want to make it loud and explicit, thus the `!definition` condition has been removed (that just fixed the symptom, but then the checks for mandatory stuff would not  work).
=> CORE-3467 Wait for Assessment custom attributes data to load

src/ggrc/assets/javascripts/models/audit_models.js
This now _really_ fixes the issue, previously the instance itself was refreshed instead of its bindings.
=> CORE-3467 Correctly refresh Assessment's custom attributes

src/ggrc/assets/javascripts/models/audit_models.js
=> QUICK-FIX Fix a typo in Assessment's binding name

src/ggrc/assets/javascripts/models/audit_models.js
This actually fetches Person instance instead of malformed object that `get_instance` returns if you put in wrong types of parameters.
=> QUICK-FIX Fix Assessment creation

.eslintrc
**Note:** this will increase the reported number of ESLint issues.
**Note 2:** I added an exception to allow using double quotes to avoid quotes escaping, so that strings like _"Arnold said: I'll be back"_ are permitted. If this is not desirable, I will change the config.
=> QUICK-FIX Turn on ESLint warnings for quote styles

src/ggrc/assets/javascripts/bootstrap/modal-form.js
This displays the right error message (and doesn't hang) in cases like the one #3899 is fixing.
=> QUICK-FIX Fix script error when assessment creation fails

src/ggrc/assets/javascripts/components/add_comment/add_comment.js
When adding a comment on an Assessment where the user is the creator, the comment would have a type label 'none'.
=> QUICK-FIX Add Creator assignee type to comments

src/ggrc/models/comment.py
The validator was too eager and complained when it got empty role names. Note that the validator will still complain about strings containing whitespace only, because that might indicate a different problem (e.g. incorrect role values set), but if that is not desired, I can change its behavior.
Of course the question remains why some Assessments ended up having their `recipients` DB field set to `",,"` in the first place, but this PR does not attempt to resolve that.
=> CORE-3639 Make validate recipients to ignore empty values

Makefile
If we want to force the make bower_components command with -B flag it
should bass and make sure all components exist.
=> QUICK-FIX Fix forcing of make bower_components

src/ggrc/models/mixins.py
Using in_ query with empty array causes warnings and performance issues
and should be avoided if possible.
Look at the first line of the test results here: https://jenkins.reciprocitylabs.com/job/ggrc_integration/1534/console
This issue was introduced with: https://github.com/google/ggrc-core/pull/3884
=> QUICK-FIX Stop using in_ query on empty array

src/ggrc_basic_permissions/roles/Editor.py
This allows Global Editors to access UserRole objects. This
allows access to e.g. Auditors on Audit objects.
=> CORE-3593 Fix access to UserRole objects for Editors

src/ggrc/models/custom_attribute_definition.py, src/ggrc_workflows/models/task_group_task.py, test/unit/ggrc/models/test_table_args.py
Every database model that is `Identifiable` should use `_extra_table_args`
instead of `__table_args__` so it can be extended through mixins.
=> CORE-3276 Fix __table_args__ definitions

src/ggrc_workflows/models/workflow.py
Attributes of Cycle Tasks are also needed when doing a collection `GET` to `/api/workflows` so they need to be undeferred (query counting confirms this).
=> CORE-3205 Update eager_query for Workflows

src/ggrc_risks/assets/javascripts/apps/risks.js
Risk and Threat objects haven’t been fully initialised, with this we 
1) Add them to `GGRC.tree_view.base_widgets_by_type`
2) Create Risk and Threat entries with mappable values in 
`GGRC.tree_view.base_widgets_by_type`
3) Set up `GGRC.tree_view.basic_model_list`
4) Set up `GGRC.tree_view.sub_tree_for`
This allows GGRC.Utils.allowed_to_map to recognise the existence of 
widgets (`hasWidget`’s _.contains check).
Setting up just base_widgets_by_type is not enough because `ggrc_workflows` extension [fails here](https://github.com/google/ggrc-core/blob/develop/src/ggrc_workflows/assets/javascripts/apps/workflows.js#L349).
=> CORE-3262 Fully set up Risk and Threat objects

src/ggrc/assets/javascripts/controllers/info_pin_controller.js
Fixed console error after refresh on Audit tab, because sometimes took offset from a hidden element
=> CORE-3668 Fix console error after refresh on Audit tab

README.md
This fixes the fonts when creating a fresh container. Since the fix for
missing system links, bower components does not run as soon as you login
to the container. With -B flag, we force bower_components to rebuild
even if the link already exists.
=> QUICK-FIX Force rebuilding of bower components

src/ggrc_workflows/assets/mustache/wf_objects/approval_modal_content.mustache
There was an icon missing on the date picker in a model for submitting an object for a review.
=> CORE-3556 Fix missing calendar icon on a date picker

src/ggrc/assets/javascripts/application.js, src/ggrc/assets/stylesheets/modules/_notifications.scss
We use flash messages all over the app to deliver message of fail, success and notifications. Unfortunately sometimes it's not obvious they appeared.
I asked Dragan how can we improve it and he came up with this temporary solution until we handle it properly for next release.
=> QUICK-FIX Improve flash messages visibility 

src/ggrc/assets/javascripts/plugins/autocomplete.js
Fixed script error appears if scroll down the list of the objects/people when creating an Assessment
=> QUICK-FIX Fix scroll error when creating an Assessment

src/ggrc/models/assessment.py, test/integration/ggrc/converters/test_import_helpers.py
The Assessments model should match the actual table in the database.
Since the title is not a unique field, the model itself should reflect
that.
This a part of CORE-3391. I am breaking that ticket up into smaller logical chunks so it can be reviewed and merged faster.
=> QUICK-FIX Make _title_uniqueness false on Assessments

Dockerfile-clean, bin/db_reset, docker-compose-clean.yml, src/ggrc/settings/development.py
This adds new Dockerfile and docker-compose files to build a thiner ggrc container. It's not quite ready for prime time yet, but it should unblock @akhilp1.
To use the new Dockerfile use:
```
docker-compose -f docker-compose-clean.yml up
docker exec -it ggrccore_cleandev_1 bash
```
In part 2, we'll replace the default current Dockerfile if everyone agrees. 
ps: @edofic can you let me know how much slower the default mysql container is compared to the in memory fat container?
=> CORE-3684 Clean docker, part 1

src/ggrc/assets/javascripts/bootstrap/modal-ajax.js, src/ggrc/assets/javascripts/bootstrap/modal-form.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Closing the modal window after filling in assessor and/or verifier fields doesn't trigger discarding changes confirmation modal.
Please note that this works only if we click on backdrop (overlay). If we directly click on `x` this won't work
=> CORE-3309 Trigger discarding changes confirmation when closing a modal

src/ggrc/assets/mustache/modals/mapper/base.mustache
GC should be allowed to create new objects if he has any of the Audit contexts already available. The same as the logic for LHN menu (e.g. 'Create New Request' button should be available when any of  audits were created).
=> CORE-3702 Fix GC cannot create new Request

src/ggrc_workflows/models/workflow.py
The database can contain some cycle tasks without an end_date. That
causes api calls for any object on that task to fail. The main
difference in the code here is the check if task.end_date is None right
before the date < today check. The rest is just a trivial performance
improvement since we only need to check if any such task exists.
The underlying problem for this will need to be found and solved in a
different PR. The point if this commit is to make sure invalid database
state does not break the app.
See:
https://grc-dev.appspot.com/workflows/316#current_widget/cycle/280/cycle_task_group/313/cycle_task_group_object_task/699
To reproduce the bug, just select all sections in the unified mapper modal. When the request gets to the section mapped to the above task, server returns a 500 and …
=> QUICK-FIX Fix getting object state for invalid objects

src/ggrc_risk_assessments/assets/javascripts/apps/risk_assessments.js
Don't show children at all since nothing else can be mapped to Risk Assessments.
=> CORE-3546 Hide Documents in Risk Assessment subtree

src/ggrc/models/section.py
The slugged mixin includes the Base mixin, which must be last. Otherwise
eager queries in the mixins after it are ignored.
This Pr increased get performance for sections by a factor of 3. That is on my local machine with ram database, and we should expect greater performance on deployed instances.
=> TRL-cRE6rwjY Fix section mixin ordering

src/ggrc/assets/mustache/base_objects/autocomplete_result.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
PR applies temporary workaround for workflow as discussed with @akhilp1.
1) remove "create new" for workflow field
2) label "Active Workflow" + tooltip for the user "An active workflow should be created in advance."
=> QUICK-FIX Disallow create WF from new Task modal

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/javascripts/components/unified_mapper/tests/mapper_model_spec.js
NOTE: The Reference type is still available when defining object filters, it has only been removed from the "main" object type dropdown.
=> CORE-3521 Remove the "References" option from the unified mapper modal

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
The issue is caused by [enqueue_items](https://github.com/google/ggrc-core/blob/320985733edf31f3daf08e6cc2a2afd43d3b53fc/src/ggrc/assets/javascripts/controllers/tree_view_controller.js#L304) and then [insert_items](https://github.com/google/ggrc-core/blob/320985733edf31f3daf08e6cc2a2afd43d3b53fc/src/ggrc/assets/javascripts/controllers/tree_view_controller.js#L375) being triggered twice. The first happens when the mapper save queue [adds a new item](https://github.com/google/ggrc-core/blob/320985733edf31f3daf08e6cc2a2afd43d3b53fc/src/ggrc/assets/javascripts/controllers/tree_view_controller.js#L1002) to the original list and the second happens when the mapper modal [triggers a refresh](https://github.com/google/ggrc-core/blob/70953a2d810acc087a91ce4098136b14810b8b77/src/ggrc/assets/javascrip …
=> CORE-3624 Mapping a control to the Audit duplicates the control's title in the tree view

src/ggrc/assets/javascripts/controllers/modals_controller.js
**Subject**: "Uncaught can.Map: Object does not exist" error is displayed while selecting object on New Assessment modal window
**Description**:
Create a program.
Create an audit for that program.
Navigate to newly created audit and display Assessments tab.
Display browser's console.
*Note:* Next 2 steps should be performed quickly WHILE CREATING the Assessment.
You need to enter a value in the new assessor input  for the contextual search and select the user as assessor.
Click into Object field and select any object.
**Actual Result:** "Uncaught can.Map: Object does not exist" error is displayed while selecting object on New Assessment modal window
**Expected Result:** No errors displayed
**Workaround:** Wait before step 6.
=> QUICK-FIX Fix js error while selecting object on New Assessment modal

src/ggrc/assets/javascripts/bootstrap/modal-form.js, src/ggrc/assets/javascripts/components/assessment_generator.js
The app doesn't redirect user to the assessments tab after generating assessments from controls tab on audit page. 
Steps:
- create a program and map a control to the program
- create an audit under the program and navigate to the audit page
- go to Controls tab on audit page
- click magic wand icon and generate the assessment
- click "See results" when the assessment is generated
*Actual Result:* the app shows controls tab instead of redirecting you to Assessments tab after the click
*Expected Result:* the app should redirect you to Assessments tab after the click
=> CORE-3635 Fix assessment generation redirect

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/plugins/canjs_extensions.js, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/models/assessment_template.py, src/ggrc/services/common.py
Add validation to default people lists on assessment template creation form in case the user chooses 'Others' in the default assessors/verifiers dropdowns.
=> CORE-3459 Make default people lists mandatory

src/ggrc/assets/javascripts/controllers/quick_search_controller.js
This gets rid of `/search` request on most object pages (`Search` mapper is a different source).
=> QUICK-FIX Defer LHN's /search request until LHN is opened

src/ggrc_basic_permissions/__init__.py
This is for a clearer log entries for debugging performance issues with
object owner permissions.
=>  CORE-3704 Split benchmark for object owners

src/ggrc_basic_permissions/__init__.py, test/integration/ggrc_basic_permissions/test_creator_audit.py
Instead of querying all the contexts based on roles and implications we
use the context data we have already fetched and stored in the
permissions object.
The new query propagates permissions of the current object context to
all the objects mapped via the relationships table.
The only side effect of this is that the Auditor role which used to
have read permission on all the mapped objects and update/delete
permission on assessments, requests, issues no longer automatically
have update/delete permissions because their audit context scope is
read only.
I have discussed this use case with prasanna & akhil and they agreed
that is an acceptable compromise for better performance. Auditor can
still get update/delete permissions by becoming assignees/verifiers.
Note: I still need to remove the …
=> CORE-3705 Improve related objects permission query

src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
Previously you needed to edit authorizations and change it to "No Access" for any user. This is now no longer required.
@Smotko Do you know of any reasons why this was needed? Per my testing it didn't cause issues. Even if you unmap all managers, admin can still visit program and promote someone to a manager.
=> CORE-3062 Remove "No Access" requirement for unmapping people from programs

src/ggrc/assets/javascripts/components/csv/export.js, src/ggrc/assets/javascripts/components/csv/import.js
The flash errors and warnings have their own formatting and should only
display clear text.
To reproduce this, just try to import a jpeg file and look at the flash message.
=> QUICK-FIX Remove html tags from flash messages

src/ggrc/assets/javascripts/models/audit_models.js
**Details**: 
Create a program with audit 
Navigate to audit page and create an assessment 
*Actual Result:* Tree view doesn’t show created assessment on Assessments tab on audit page. Page refresh is needed.
*Expected Result:* Assessment should be shown on Assessments tab on audit page without page refresh.
=> QUICK-FIX Assessment is not shown up after creation on audit page

src/ggrc/assets/javascripts/controllers/modals_controller.js
**Subject**: Script error “Uncaught TypeError: Cannot read property 'model' of undefined” appears after a try to open assessment template’s 2nd tier on mapping window
**Details**: 
Create a program with an audit
Navigate to audit page → assessment templates tab
Click (+) button in the top of the content area
Click a triangle in one the found assessment templates’ 1st tier
**Actual result**: the script error “Uncaught TypeError: Cannot read property 'model' of undefined” appears 
**Expected result**:  no errors!
=> QUICK-FIX Fix Save & Add Another button

src/ggrc/assets/javascripts/application.js, src/ggrc/assets/javascripts/apps/dashboard.js, src/ggrc/assets/stylesheets/modules/_tree-content.scss
This fixes the blocker issue on admin dashboard and I have also made a quick ninja UX improvement to restore the click area to the whole `.openclose` element. The caret icon was way too narrow to comfortably click and it would frustrate users.
=> QUICK-FIX Fix people list in admin panel

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/mustache/assessment_templates/tier2_content.mustache
**Subject**: Script error “Uncaught TypeError: Cannot read property 'model' of undefined” appears after a try to open assessment template’s 2nd tier on mapping window
**Details**: 
Create a program with an audit
Navigate to audit page → assessment templates tab
Click (+) button in the top of the content area
Click a triangle in one the found assessment templates’ 1st tier
**Actual result**: the script error “Uncaught TypeError: Cannot read property 'model' of undefined” appears 
**Expected result**:  no errors!
=> QUICK-FIX Fix js error map assessment template modal

src/ggrc/assets/stylesheets/_common.scss, src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js, src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_file.mustache
<sup>NOTE: Since the second commit contains a lot of linting changes I suggest reviewing this on a per-commit basis.</sup>
A couple of notes:
* This is needed before Monday (preferable: today), thus please review it with a bit higher priority, thanks!
* I noticed that there are two different ways (read: methods) of handling file picking - one for when an instance has extended_folders mapped, and one for when it doesn't. This fix only addresses the latter case.
If we need the extended folders case to be fixed as well, please let me know (and explain what these actually are, and where they can be seen in action in the app, thanks).
* No unit tests, unfortunately, because IMO a disproportionate amount of mocking would be required (all the modals etc.), or refactoring the method into smaller …
=> CORE-3513 Prevent opening multiple file picker modals

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/models/cacheable.js
- create an assessment, add some users as creators, assessors and verifiers
- open a modal to edit this assessment
- open Network tab in developer tools
- add a user as a creator, verifier or assignee
- remove one of the creators, verifiers or assignees
(possibly you need to continue adding and deleting people until the bug takes effect)
Bug behavior: the application starts sending requests on `api/people?id__in=...` for every person present in people lists in a loop, redrawing every people list several times a second.
This fix adds a way to break the `update list_mapped` - `callback on list_mapped update` - `update list_mapped` loop.
=> QUICK-FIX Stop request spam from people list

src/ggrc/assets/mustache/base_objects/relevance_action.mustache
Subject: The app unmapps the Assessment if clicked "mare relevant" checkbox in assessment's first tier on audit page
Details: 
Create a program with an Audit and an Assessment 
Click the checkbox in the 1st tier of the assessment
Actual Result: the app unmaps the Assessment
Expected Result: The make relevant checkboxes should be removed from the 1st tier of the assessment
=> QUICK-FIX: Update "make relevant" logic

src/ggrc/assets/mustache/custom_attributes/info.mustache
This is waiting for editable comments (CORE-2840, #3941) so that inline edit component gets readonly property.
=> CORE-3670 Mark custom attributes read only if user doesn't have permission

src/ggrc/assets/mustache/base_templates/subtree.mustache
As discussed remove 3bbs and unmap completely from ui for mapped objects tree view.
=> QUICK-FIX Fix remove unmap link from mapped tree view

src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_file.mustache, src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_comment_attachment.mustache
Simply replacing it with the `<spinner>` component did the trick because of a different CSS `display` property (not `fixed` anymore).
=> CORE-3267 Fix spinner overlapping with the attach evidence button

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/ca_validation_error_spec.js, src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
Ticket description:
> Add validation message for mandatory Custom Attribute in Assessment (now when you do not fill it and press Save, nothing is showed to the user, no reaction)
**Notes:**
* There are some minor styling issues like spacing between the error message and the corresponding UI widget, but since they do not represent a blocker in any way, this PR does not try to address them. If needed, this can probably be delegated to Vladan (can be done independently from the other tasks).
* If there multiple validation errors for a single field, only the first one is shown - showing all of them would clutter the form.
=> QUICK-FIX Add error messages for required custom attributes

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/services/common.py
- create a request, make Example User a creator and assignee;
- open this request for editing;
- remove Example User from creators (add new creators as needed);
- add Example User as a verifier;
- save the form.
Expected result: Example User is made assignee and verifier.
Possible actual results: Example User is unassigned from all lists, or Example User is assigned as creator, assignee and verifier (there is a race condition between the addition and deletion).
This fix allows saving such reassignments.
=> QUICK-FIX fix people list saving after change

src/ggrc/assets/mustache/base_objects/extended_info.mustache, src/ggrc/assets/mustache/base_objects/filters/filter_by_relevance.mustache, src/ggrc/assets/mustache/mapper/relevant_filter.mustache, src/ggrc/assets/mustache/programs/extended_info.mustache, src/ggrc_workflows/assets/mustache/tasks/extended_info.mustache
This PR renames a few things in the UI to make them consistent throughout the app, namely:
* FILTER BY MAPPING RELEVANCE --> FILTER BY MAPPING
* Relevant to --> Mapped to
=> CORE-3481 Make the "relevant to" UI texts consistent

src/ggrc/assets/javascripts/components/tabs.js, src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/mustache/requests/info.mustache
The issue was caused because the `title`attribute the tab component used is also used by browsers. The fix was to simply use a different attribute name for the tab title.
=> QUICK-FIX Remove tooltip when hovering over tab contents

src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache
When defining a dropdown custom attribute field (e.g. in the create AssessmentTemplate modal), its possible values are entered into the provided input field containing instructions as a placeholder text.
Since the input field is too small, the placeholder text does not fit in, thus I added a tooltip displaying the very same text. This seemed a better option than (excessively) extending the input field's size, since the instructions are simply too long for that.
=> QUICK-FIX Add tooltip to comma-separated values input field

src/ggrc/services/common.py
BE fix instead of PR #4086 that should be just closed.
Subject: Assessment tab: Mapped objects are not displayed on 2nd tier - user have to refresh page
Details: 
- Create Program
- Create Audit
- Create Assessment object for any control
- Expand to see 2nd tier
Actual Result: Only mapped people are displayed on 2nd tier
Expected Result: All mapped objects should be displayed. In this case Program, Control, Audit
Workaround: Refresh the page
=> QUICK-FIX Fix mapped objects are not shown

src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache, src/ggrc/assets/stylesheets/_common.scss
This fixes the vertical alignment issue with the dropdown's list of options on the edit AssessmentTemplate modal (the custom attributes section).
If the possible choices for a custom attribute of type dropdown have looooong naaaaames, their text was wrapped into multiple lines, causing a vertical alignment mismatch with the checkboxes in the next two columns (they all fit into a single line) - it became difficult for the users to see which checkbox corresponds to a particular dropdown's option.
=> QUICK-FIX Prevent dropdown custom attribute's options wrap

src/ggrc/assets/mustache/assessments/tree_header.mustache, src/ggrc/assets/mustache/base_objects/tree_view_filter.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_footer.mustache
**Subject:** Delete assessment from My Work dashboard gives an error: Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
**Details:** 
Ensure one assessment is assigned to current user
Navigate to My work page > Assessment tab
Open info panel >3dots button 
Click delete item
_Actual Result:_ Error message is displayed: Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
_Expected Result:_ Error message should not be displayed, assessment should be deleted.
_Workaround:_ click one of the tabs
=> QUICK-FIX Fix delete assessment on My Work page

doc/developer_guide.md
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> QUICK-FIX Convert readthedocs links for their .org -> .io migration for hosted projects

src/ggrc/models/mixins.py, test/integration/ggrc/converters/test_imported_api_requests.py
Before this fix loading a lot of assessments with per-object custom attributes caused a lot of db queries. 
Use [SQLALCHEMY_RECORD_QUERIES](https://github.com/google/ggrc-core/blob/develop/src/ggrc/settings/development.py#L17) to verify.
=> QUICK-FIX Update eager_query for CustomAttributables

src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_csvs/duplicate_object_person.csv, test/integration/ggrc/converters/test_csvs/duplicate_object_person_objective_error.csv, test/integration/ggrc/converters/test_import_csv.py
Two ObjectPerson objects were being created in the same row converter and the session wasn't being flush in-between which resulted in an integrity error.
I resized the original test file to make testing the error easier. See the Jira ticket to get the smaller file.
=> CORE-3693 Fix import CSV error

src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
**Subject:** Script error "Uncaught TypeError: Cannot read property 'editor' of undefined" appears if  Save & Add Another button is clicked when creating a template with all types of fields
**Details:** 
Start creating an Assessment Template on audit page
Add all the types of CA fields to the template
Click Save & Add another button
_Actual result:_ Script Error "Uncaught TypeError: Cannot read property 'editor' of undefined" appears
=> QUICK-FIX Hide Save & Add Another button from AT modal

src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/mustache/assessment_templates/attribute_add_field.mustache, src/ggrc/assets/stylesheets/_common.scss
**Ticket description:**
> When defining a new custom attribute of type Dropdown, the tooltip help over the possible values input field appears only after some delay. It is thus not obvious to the user that such help exist.
> 
> An icon should be added next to the input field, and the tooltip should be triggered by hovering over it.
> 
> The existing input field tooltip should be removed.
=> CORE-3708 Improve custom attribute values help's visibility

src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/pbc/workflow_controller.js
Assessment Template: When we edit custom attribute with dropdown type, the checkboxes for Attachment, Comment, Mandatory are not saved.
=> QUICK-FIX Save CA values on AT

src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
1. Open editing modal of any Assessment.
2. Remove the title, make sure the title field is marked with a red validation box.
Expected result: Save & Close button is grayed out and unclickable.
Actual result: Save & Close button is active and green, but clicking it makes nothing.
This PR just re-adds a conditional "disabled" class of the Save & Close button that has been lost some commits ago accidentally.
=> QUICK-FIX Add Save button disabler

src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/pbc/workflow_controller.js
The app doesn't save "mandatory" checkbox for CA field for the first time when creating Assessment template from Audit's info tab
=> QUICK FIX Save edited CA after creating AT

src/ggrc/assets/javascripts/components/inline_edit/inline.js, src/ggrc/assets/javascripts/components/inline_edit/tests/inline_edit_spec.js, src/ggrc/assets/javascripts/controllers/info_pin_controller.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/mustache/base_templates/people_list.mustache, src/ggrc/assets/mustache/custom_attributes/info.mustache, src/ggrc/models/mixin_autostatuschangable.py, src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
**Subject:** In Completed assessment, if user modifies any attribute (except comment), assessment status should change to "In Progress". 
**Details:** 
Create  Assessment under the Audit using an Assessment Template with some CA fields
Complete the Assessment
Change Assessment’s CA field value in Assessment’s info panel
_Actual Result:_  Assessment’s status remains “Completed”
_Expected Result:_ Assessment’s status should be changed to “In Progress” (Need to add the same popup warning message, as we do when user adds an evidence attachment.)
=> QUICK-FIX Reset assessment status after change CA

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/sort_by_sort_index/sort_by_sort_index.js, src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree.mustache, src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache, src/ggrc_workflows/assets/mustache/task_groups/info.mustache
This re-implements reordering outside tree view. 
Sadly I couldn't remove the reordering code from tree view since it's still used for task groups and I don't know how to ingrate it there - suggestions welcome.
=> CORE-3560 Bring back task reordering

src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache
This reverts commit ca620e8e05d1b8da843f41b446cda4099ce84282 since person
component was having issues:
- errors when rendering without a person
- sometimes not updating after an edit
=> QUICK-FIX fix showing risk assessments

src/ggrc/assets/javascripts/bootstrap/modal-form.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/models/audit_models.js
- generate an assessment with a mandatory text CA
- open a modal to edit it (the mandatory CA is highlighted red by the validators)
- enter something into that CA (the mandatory CA red box disappears)
- close the modal without saving
- open a modal to edit the same assessment.
Expected result: the mandatory CA field is highlighted red, "save" button is disabled.
Actual result: the mandatory CA field is not highlighted red, "save" button is not disabled.
This PR also fixes the same issue with empty mandatory people lists (assessors, creators, requesters, assignees), to test this case you need to manually remove the relationship between the only creator (assessor, or any mandatory role) and the assessment.
=> QUICK-FIX Fire validation on every editing modal open

src/ggrc/assets/mustache/assessments/header.mustache
This PR removes the _"send reminder to Assessors"_ link from the Assessment's ellipsis menu if the user doesn't have permissions to do so (having resulted in an HTTP 403 error before the fix).
This is issue 150 in the part A bug list.
=> QUICK-FIX Add permissions check for remind assessors link

src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/mustache/base_templates/mapping_tree_view.mustache
- Add a comment with URL on Assessment
- Refresh the page
- Check mapped URL's showing _Invalid date_
=> QUICK-FIX Fix getting reified instances in mapping treeview

src/ggrc/assets/javascripts/models/audit_models.js
Script error "Uncaught TypeError: Cannot read property 'multi_choice_options' of undefined" appears when updating Assessment status for the other user
as GE user: 
- Create an audit
- Assign the GC user as the auditor
- Create an Assessment 
- Set GE user as the assessor and leave Verifier blanc
- Log in as GC user and navigate to Audit page -> Assessments tab
- Confirm you see the same status under both users
As GE user complete the assessment
- As GC user click the 1st tier of the assessment in the tree view list
Script error "Uncaught TypeError: Cannot read property 'multi_choice_options' of undefined" appears
No errors should appear
=> ISSUE-139 CA has no definition and no value

src/ggrc/assets/javascripts/bootstrap/modal-ajax.js, src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Script error: Uncaught TypeError: Cannot read property 'name' of undefined appears when trying to change the order of custom attributes when creating a new Assessment Template
=> QUICK-FIX CA drag exception

src/ggrc/assets/javascripts/bootstrap/modal-form.js
This fixes the regression that makes it impossible to close a mapping modal.
=> QUICK-FIX Fix regression on mapping modal close

src/ggrc/assets/javascripts/models/audit_models.js
This PR fixes a problem with CA validation.
1. Create an Assessment with a mandatory custom attribute, assign GR as a verifier.
2. Login as the GR-verifier, open the quick view pane of the Assessment in the dashboard.
3. Fill in the mandatory custom attribute.
Expected result: the user should have "Complete" (and, if the Assessment is in "Ready for Review" state, "Reject"/"Verify") buttons active and clickable.
Actual result: "Complete" ("Reject", "Verify") buttons are disabled, an error about empty mandatory custom attributes is displayed on hovering over that buttons.
=> QUICK-FIX Fix getting definitions from values

src/ggrc/assets/javascripts/pbc/workflow_controller.js
custom_attribute_definitions list contained old values that were
not getting refreshed when the save modal was opened after a save.
=> QUICK-FIX Fix custom attributue definitions cache

src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
**Issue description:**
> Remove "Map object to this person" (+) button from the first tier of the person on program page
This PR, in fact, removes the said button from all pages where a Person appears in a tree view. This is consistent with the tabs on a Person page, where it is not possible to map any new objects to a person, but just viewing them.
=> QUICK-FIX Prevent mapping objects to a Person in tree view

src/ggrc/assets/javascripts/controllers/quick_form_controller.js
This fixes an issue about a Global Reader who is an Assignee (creator, assessor, verifier) of an Assessment, but can't add an URL to it.
1. Create an Assessment, assign GR as an assessor.
2. Log in as GR.
3. Click "Add URL"  on the Assessment quick view pane
4. Type in some url
5. Click "Add".
Expected result: an URL object is created and mapped to the Assessment, the url is listed in the "URL" section.
Actual result: an URL object is created but is not mapped, FORBIDDEN error is printed, the url is not listed in the "URL" section.
=> Store current user as owner of newly created URL

src/ggrc/assets/mustache/assessments/modal_content.mustache
**Details:**
- start creating a new Assessment via LHN
_Actual Result:_ "Notifications" section on New Assessment modal doesn't have "hide" link
_Expected Result:_ "Notifications" section on New Assessment modal should have "hide" link
=> CORE-3649 Add hide link for Notifications block

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/tests/cacheable_model_spec.js
After defining custom attributes on the create Assessment Template modal, and saving it, the custom attribute order is not preserved. Instead, the custom attributes are sorted alphabetically when the Assessment Template is reopened for editing.
This PR makes sure that the custom attributes are displayed in the order they were defined.
This is `ISSUE 164` in the bug spreadsheet.
=> QUICK-FIX Honor custom attributes creation order

src/ggrc/assets/javascripts/components/people_list.js
**Subject: Hard to reproduce:** Tree view glitch is back: after editing Assessment the tree view is messed up
**Details:** 
- Create an assessment
- Click add a verifier
- Click trash can icon next to verifier’s email and hover his email while the app removing the email.
_Actual Result:_  User info tooltip stays after user email is removed
_Expected Result:_ Tooltip should be removed together with user’s email
_PS: Reproduced if configure a slow connection in Network conditions(Chrome DevTool)_
=> QUICK-FIX Turn off popover for the removed person

src/ggrc_basic_permissions/roles/ProgramAuditOwner.py
As agreed with @Smotko just a temporary solution to let users test CAD under GR/GC roles.
=> QUICK-FIX Temp fix for  program audit owner to create CAD

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/custom_attribute.py
If an object level CA exists and does not belong to the current object,
we ignore the value and show a warning.
Please note that this does not fix the import warnings when doing the import tests. It may say that everything is fine, and then give a bigger number of ignored objects
=> CORE-3709 Fix bad object ca imports

src/ggrc/assets/javascripts/pbc/workflow_controller.js
Restore previous functionality that was broken during merge conflict(was already working). As discussed we need to give users an ability to test custom attributes until we prepare BE fix. Discussed with Akhil and @egorhm.
=> QUICK-FIX Fix save mandatory checkboxes

src/ggrc/fulltext/mysql.py
This change makes sure we only return the key and type of the query and
not the content/property fields.
In my local tests this change reduced the query run time from
~0.80066299 to ~0.07371902.
=> QUICK-FIX Improve /search query

src/ggrc/assets/javascripts/components/people_list.js
1. Open modal to edit Assessment.
2. Add Example User as a Creator and as an Assessor.
3. Remove Example User from Assessors.
4. Remove Example User from Creators.
Expected result: Example User is removed from Creators and Assessors.
Actual result: A js error 'Cannot read property 'join' of undefined' is shown.
=> QUICK-FIX Fix removing person from two people lists

src/ggrc/assets/mustache/assessments/reusable_objects.mustache, src/ggrc/assets/mustache/base_templates/attachment.mustache, src/ggrc/assets/mustache/base_templates/urls.mustache, src/ggrc/assets/mustache/requests/reusable_objects.mustache, src/ggrc_basic_permissions/roles/Reader.py
This disallows GR to map evidences to an object he doesn't have permissions to edit.
1. Create an Assessment A1 with GR as Assessor.
2. Create an Assessment A2 without GR assigned.
3. Map a common control to both A1 and A2. (needed to make A1 and A2 related)
4. Log in as GR.
5. Attach an evidence to A1. (or you can add an URL, they are processed the same way)
6. Navigate to A2, open "Related Assessments" tab.
7. Check the evidence from A1 to reuse, click "Reuse".
Expected results: GR shouldn't map an evidence (URL) to an Assessment he doesn't have permission to edit.
Actual results: the evidence (URL) is mapped successfully.
This PR both forbids the mapping on the backend, and disables the checkboxes to reuse the evidences on the frontend.
=> QUICK-FIX Disallow GR reuse evidences

src/ggrc/assets/javascripts/pbc/workflow_controller.js
Subject: Reader cannot see "Edit", "Unmap", “Delete” options under 3bbs button in Assessment’s info pane right after creating an Assessment. Only after page refresh.
Details: 
Log in as GR create a program and an audit
Create new Assessment on audit page (do not reload the page)
Click 3bbs button
Actual Result:  Assessment state is changed to “IN PROGRESS”
Expected Result: User should not be able to reuse evidence for other user’s object.
Additional info: The same happens to the Request - delete item misses in the dropdown
=> QUICK FIX permissions after assessment creation

Dockerfile
The phusion:baseimage has changed to ubuntu 16:04 even though the doc on
docker hub says otherwise. This breaks our build and the develop
environment.
see: https://github.com/phusion/baseimage-docker/blob/rel-0.9.19/image/Dockerfile
PS: we should really fix/freeze most of our deps, and update them manually to avoid weird bugs.
=> QUICK-FIX Freeze docker base image to use ubuntu 14.04

src/ggrc_basic_permissions/roles/Reader.py
The title says it all.
If I understood correctly, we can safely grant  Readers this permission, because they will still not be allowed to create mappings.
=> QUICK-FIX Allow Readers to create Assessment Templates

src/ggrc/models/relationship.py, test/integration/ggrc/models/test_relationship.py
Note: this was reproduced only on local appengine emulation. However, this error may some day occur on any installation of GGRC. I make this PR into the develop branch because I feel bad about changing the validators for Relationship model on the day of UAT release.
1. Open Assessment creation modal.
2. Add a user as a Creator and as a Verifier.
3. Click 'save'.
Expected result: the Assessment is created.
Actual result: http 500 is returned from the backend as RelationshipAttr object validation fails.
The reasons behind this error are the following:
- when we assign a person to an object (say, Assessment), we `POST` a `Relationship` with following fields:
1. source == Person
2. destination == Assessment
3. attrs == {'AssignmentType': 'Creator,Assessor'}  (any assigned …
=> QUICK-FIX Fix 500 on relationship with attrs creation

src/ggrc/assets/mustache/custom_attributes/info.mustache, src/ggrc/models/hooks/assessment.py
**Issue description:**
> Generate an Assessment using an Assessment template (the latter should have a few custom attributes defined). The order of custom attributes displayed on the generated Assessment's info pane should be the same as defined in the Assessment Template (currently the custom attributes arr sorted alphabetically).
There were two reasons for an incorrect order:
* When generating an Assessment from an Assessment Template, custom attribute definitions were not stored in the database in the correct order.
* The Mustache template rendering the custom attributes did not wait for the custom attribute sorting to complete - instead, it rendered the (unsorted) Assessment's custom attributes list immediately. This was fixed by wrapping the CA list rendering block into a …
=> QUICK-FIX Render custom attributes on info pane sorted by ID

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/mustache/assessments/header.mustache, src/ggrc/assets/mustache/mixins/stateful.mustache
1. Create an assessment, add yourself as Creator and Assessor, but not Verifier.
2. Open Quick view pane for this assessment.
3. Add yourself as Verifier.
4. Click "Complete" button.
Expected result: the assessment is moved into "Ready for review" state, clickable "Verify"/"Reject" buttons are displayed.
Actual result: the assessment is moved into "Completed" state (which is invalid, as the final state in case verifiers are defined is "Verified").
=> QUICK-FIX Update Complete button on verifiers change

src/ggrc/cache/cache.py
This is reproducible only on memcache-enabled instances of our app. Thus, to test it on localhost, run `launch_gae_ggrc`.
1. Create an Assessment, add yourself as Creator and Assignee.
2. Add a comment to it with text 'Yet unedited text'.
3. Edit the comment to make it 'Edited and saved text', save it, don't refresh the page. It should be saved and rendered correctly ('Edited and saved text').
4. Refresh the page.
Expected result: the comment is loaded as 'Edited and saved text'.
Actual result: the comment is loaded as 'Yet unedited text'.
The problem is that when we PUT the new Comment object, it is not updated in the memcache. This PR registers the model so the update-memcache-after-PUT logic works for the Comment model.
=> QUICK-FIX Store updates to comments in memcache

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Subject: Custom Attributes tab is empty after switching back to it from Event tab on admin dashboard page.
Description:
- Navigate to Admin dashboard
- Open Custom Attributes tab
- Open Events tab
- Switch back to Custom Attributes
Actual Result: Custom Attributes tab has no content
Expected Result: Custom Attributes should show the tree view with the items
Workaround: Refresh the page
=> CORE-3124 Fix rerender tree view on admin dashboard

src/ggrc/assets/javascripts/components/object_counter/object_counter.js
If you logout (or visit the login screen directly), a script error occurs in the ObjectCounter component's definition, because there is no current user available to read his/her id.
This is the issue #95 in the bug spreadsheet, under the _Quince_ tab.
No test, unfortunately, because all components get registered before the tests run. Changing this and loading components conditionally would most likely require way too much refactoring at this point.
=> QUICK-FIX Fix script error in ObjectCounter if no user

src/ggrc/converters/base_row.py
Some assessments might not have all custom attributes and when exporting
those, we should return an empty value.
=> QUICK-FIX Fix exporting for object level custom attributes

src/ggrc/models/mixins.py
This should fix saving custom attribute values on assessments.
=> QUICK-FIX Fix custom attribute definition deletion

src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/mustache/base_templates/url_list.mustache
The URLs attached to an assessment are not sorted by date added.
Steps to reproduce on localhost:
- Create an assessment.
- Open its details page.
- Add an url with text 'url1' to the assessment.
- Add an url with text 'url2' to the assessment.
- With mysql client, set `creation_date`s in past for url2 and in future for url1 manually.
```sql
update documents set created_at='2000-01-01 00:00:00', updated_at='2000-01-01 00:00:00' where title='url2';
update documents set created_at='2020-01-01 00:00:00', updated_at='2020-01-01 00:00:00' where title='url1';
```
- Refresh the page.
- Add an url with text 'url3' to the assessment.
Expected result: the urls are sorted by creation dates (the order is url2, url3, url1).
Actual result: the urls are sorted by their ids or something (the order is …
=> QUICK-FIX Sort urls list by creation date

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/base_templates/subtree.mustache, src/ggrc_workflows/assets/javascripts/models/cycle_models.js
This PR replaces the "arrow" links to the object view page by changing the objects' titles themselves into links.
> **Details:**
- Navigate to the audit page -> Assessments tab
- Click the assessment’s 1st tier
- Open Related Assessments tab in info panel
> **Actual Result:** the arrows are shown for the related objects
> **Expected Result:** Remove the arrows and make the object titles hyperlinks
This is issue in `1.24` under `Section 2` in the bug description document.
NOTE:
For consistency, the links are changed everywhere where the template `base_objects/subtree.mustache` is used to render the list of related objects.
If this behavior is not desired, a new specialized template should be created, and used only at specific places (perhaps in a separate PR?).
P.S.: The helper is …
=> QUICK-FIX Change object titles to links in related objects lists

src/ggrc/migrations/versions/20160707132122_1269660b288b_remove_ca_duplicate_values.py, src/ggrc/models/custom_attribute_value.py
This is just the first part of refactors to backend code, before we can start working on propper post collection requests.
PS: this PR breaks imports that try to update custom attributes (no warning is shown, but they silently fail and are not updated). Fix for this is waiting on PJ merge. see: https://reciprocitylabs.atlassian.net/browse/CORE-3711
=> CORE-3710 Fix custom attribute duplicate values

src/ggrc/assets/stylesheets/modules/_attachment-list.scss
This is a follow up on #4177, it fixes the vertical alignment of the items in related objects lists to match the alignment of the list's bullet.
/cc @zidarsk8
=> QUICK-FIX Vertically align items in related objects lists

src/ggrc/models/assessment.py, src/ggrc/models/audit.py, src/ggrc/models/audit_object.py, src/ggrc/models/background_task.py, src/ggrc/models/category.py, src/ggrc/models/clause.py, src/ggrc/models/context.py, src/ggrc/models/control.py, src/ggrc/models/deferred.py, src/ggrc/models/directive.py, src/ggrc/models/document.py, src/ggrc/models/help.py, src/ggrc/models/mixins.py, src/ggrc/models/object_document.py, src/ggrc/models/object_person.py, src/ggrc/models/option.py, src/ggrc/models/person.py, src/ggrc/models/product.py, src/ggrc/models/program.py, src/ggrc/models/request.py, src/ggrc/models/section.py, src/ggrc/models/system.py, src/ggrc/models/track_object_state.py, src/ggrc_gdrive_integration/models/object_event.py, src/ggrc_gdrive_integration/models/object_file.py, src/ggrc_gdrive_integration/models/object_folder.py, src/ggrc_risk_assessments/models/risk_assessment.py, src/ggrc_risks/models/risk.py, src/ggrc_risks/models/risk_object.py, src/ggrc_workflows/models/workflow.py
The deferred wrapper is used in all our models and mixins and having it
in the mixins.py file causes circular imports which are resolved by
having import statements inside functions. We should avoid that and this
is a step to moving all of our import statements to the top of python
files.
This is a side product of my work for custom attribute value fixes needed for collection post refactor.
=> QUICK-FIX Move deferred wrapper to its own module

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js
Subject: “Uncaught TypeError: Cannot read property 'display_name' of undefined” error is displayed while trying to display Request Log tab on request page
Details: 
Create an audit for that program
Create request. While creating request map all available Requests in the system.
Save the Request
Click Request Log tab
Actual Result:  “Uncaught TypeError: Cannot read property 'display_name' of undefined” error is displayed.
Expected Result: Request log contains corresponding information.
=> QUICK-FIX view log data in Request log tab

src/ggrc/models/mixins/customattributable.py
The modified code is only valid for Assessment templates. When creating
a new assessment the id is none and custom attributes for that template
do not exist, so in that case we can safely remove the redundant db
commit call.
=> QUICK-FIX Remove redundant session commit calls

src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Now that saving is all done on the backend we can enable ordering of custom attribute definitions in the edit assessment template modal.
=> QUICK-FIX Enable CAD ordering in edit AT modal

src/ggrc/utils/benchmarks.py
This commit adds option for the benchmark manager to only output the
summary of requests. If there's enough text to be displayed the output
can affect the benchmark results.
With this modification developers can check which parts of a function
are slow and the overall results only by changing the GGRC_BENCHMARK
environment variable to one of possible options: all, last, only, and
only_last.
Ps: To review these options and changes you can just do
```bash
export GGRC_BENCHMARK=all  # or last, only, only_last 
```
=> QUICK-FIX Update benchmark context manager

src/ggrc/assets/javascripts/pbc/workflow_controller.js
This fixes a bug where editing an object with custom attribute
definitions removed all custom attribute definitions on that
object until a page refresh.
=> QUICK-FIX Only clear CAD for assessment templates

src/ggrc/assets/javascripts/components/people_list.js
This FIXME describes the current implementation of pending joins manipulation logic and is thus not needed any more.
=> QUICK-FIX Remove obsolete FIXME in people_list.js

src/ggrc/services/common.py, src/ggrc/utils/__init__.py
Current versions of python work normally weather the key is a unicode
string or not, so the wrapper to convert all keys to unicode is
redundant.
=> QUICK-FIX Remove unicode dict wrapper

test/integration/ggrc/services/__init__.py, test/integration/ggrc/services/test_collection_post.py, test/integration/ggrc/services/test_common.py
This is a refactor of collection post test to better cover all use cases needed for the rafactor.
In this PR the only new test is for duplicate relatioships posted. See https://github.com/google/ggrc-core/pull/4194/commits/67c4b8140bd8db337ce572eea5ebfc7d00e8cebb
Note: The whole collection post refactor will be split into several smaller PRs for easier PR review process. In the pull requests that update and add tests, please make sure that we actually test what we want the end behaviour to be and that the tests themself actually fail when needed.
=> QUICK-FIX Collection post tests

README.md
The issue stats label is usually out of sync and the like is broken most of the time, so it's better to just remove it.
=> QUICK-FIX Remove issue stats label from README.md

src/ggrc/services/common.py
We must split the collection_post_step function into smaller independent
chunks that can be reused once collection_post_step function is removed.
=> QUICK-FIX Refactor collection post checks

src/ggrc/assets/javascripts/controllers/info_pin_controller.js
Add check if element and header are present
In hard-to-reproduce and quite rare cases (but quite often encountered when editing files) header is not present when executing `ensureElementVisible` on page load, in which case there is an error thrown:
````
"cannot access top of undefined” on headerTop = $header.offset().top 
````
call. After that error infopin expansion dies.
This silently ignores that and just skips the execution on page load (no noticeable issues with that) while still allowing info pin expansion for later use.
=> QUICK-FIX Fix expand control visibility

src/ggrc/assets/javascripts/bootstrap/modal-form.js, src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/javascripts/controllers/modals_controller.js
Subject: Deleting Assessment CA fields from Assessment template modal without saving the changes results in weird CA fields behavior on  Assessment template modal
Details: 
Edit the Assessment template 
Delete a CA field from the list but do not save the changes, just close the modal by clickig “X” button or clicking outside the modal
Open Edit Assessment template modal again
Actual Result: the app shows that another field has been removed
Expected Result:  the changes weren’t saved so the app should show all the fields after reopening edit modal
=> QUICK-FIX Reset instance after modal close

src/ggrc/converters/errors.py, src/ggrc_workflows/converters/handlers.py, test/integration/ggrc_workflows/converters/test_csvs/workflow_malformed_task_dates.csv, test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Imported task of quarterly/annually workflow requires dates
to be in format MM/DD, but the most spreadsheet editors
automatically format such dates into MM/DD/YYYY.
The commit mitigate these rules, so dates in format MM/DD/YYYY
will able to be imported without errors, but with only warnings.
=> QUICK-FIX Mitigate rules for date format of imported task

src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/converters/query_helper.py, src/ggrc/notifications/common.py, src/ggrc/services/query_helper.py, src/ggrc/views/__init__.py, test/unit/ggrc/converters/test_query_helper.py
This PR contains @zidarsk8's refactorings to `query_helper` module of `converters` and basic functionality for an endpoint for generic object querying. The API mostly conforms to the specification in [advanced query api document](https://github.com/google/ggrc-core/blob/develop/doc/advanced_query_api.md).
=> FEATURE Add basic functionality for /query endpoint

src/ggrc/assets/mustache/dashboard/internav_list.mustache
No needed close icon on force-showed tabs in Audit page
=> QUICK-FIX Remove close icon from force-showed tabs

src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js, src/ggrc/assets/javascripts/components/unified_mapper/tests/mapper_results_spec.js
_(bug 1.34 under Section 2)_
This fixes the issue in the unified mapping modal where the same mapped object can be shown multiple times. This occurs because the `entries` list is not initialized upon component instantiation, causing the `{scope.entries} add` event handler to be invoked multiple times. On the other hand, properly initializing the list assures that it is free of any existing event handlers.
- Navigate to a Program page
- Open controls tab in horizontal menu and click (+) button
- Create a new Control via unified mapping modal and map it to the program
- Open mapping modal window again by clicking (+) button and create another Control from within it
The Control’s title is shown multiple times in the OBJECTS FOUND section (once for …
=> ISSUE-115 Fix showing duplicate objects in mapper modal

src/ggrc_basic_permissions/migrations/versions/20131206002015_c460b4f8cc3_place_all_public_pro.py, src/ggrc_workflows/migrations/versions/20140722203407_4b3316aa1acf_move_existing_workflows_to_new_contexts.py, test/integration/ggrc/memcache/benchmark_concurrent.py
This just clears all pep8 errors from worst offending files.
The only code changes in these files are not used vars removed and a few print statemens removed. Other than that, all changes are pure PEP8 compatibility changes.
=> QUICK-FIX Lint python files

src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache
_(Section 2, bug 1.42)_
This PR makes sure that the generate assessments magic wand icon is now shown if the user doesn't have permissions for the action.
- Create an Audit.
- Create assessment and set Global Reader as assessor. Use reader@reciprocitylabs.com. 
- Login under Global Reader 
- Display Audit -> Assessments tab
**Actual Result:** “Generate Assessments” icon is available under Assessor (Global Reader)
**Expected Result:** “Generate Assessments” icon is not available under Assessor (Global Reader)
=> ISS-117 Hide generate assessments icon for Readers

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This pull request reverts the PR #4202 that caused problems with opening tree view subtiers.
- Open a tree view, e.g. the Audits tab on the Dashboard.
- Expand the top-tier audit.
- Expand that Audit's sub-tier
- Expand another Audit's sub-tier
**Expected result:** The sub-tier is expanded
**Actual result:** The while top tier gets collapsed
Note that this PR will re-introduce the issue fixed in #4202, i.e. the CA values do not get refreshed in tree view when editing then in the tree view's item info panel. In an offline discussion we concluded that it's best to wait for the CA backend changes before solving any of the issues related to them - if they still happen to exist at that point.
@hyperNURb When this gets merged, can you just please mark the issue fixed by …
=> QUICK-FIX Undo the CA refresh fix

src/ggrc/assets/javascripts/components/datepicker/datepicker.js
EFFECTIVE DATE and STOP DATE  fields cannot be blank once value is selected
=> QUICK-FIX Unsetting datepicker value

src/ggrc/converters/query_helper.py, src/ggrc/services/query_helper.py, test/integration/ggrc/services/test_query.py
This PR adds "total" field to the query response which holds the total number of filtered objects and adds "order_by" parameter to sort the results by column values (at the moment it sorts only by a single column).
Also there is some refactoring to break `converters.query_helper` querying logic into smaller parts.
=> FEATURE Enhance query_helper for pagination

src/ggrc/assets/javascripts/models/mappings.js
Issue tab was empty on both my work and all objects page. Now the tab will contain either a list of issues relevant to the current user or all the issues in the system.
=> Fix issue tab on my work/all objects page

src/ggrc/automapper/__init__.py, src/ggrc/models/revision.py, src/ggrc/services/common.py, test/integration/ggrc/services/test_collection_post.py
~~This is continuation of https://github.com/google/ggrc-core/pull/4209 and will be rebased once that PR is merged.~~
~~When reviewing just checks commits from "Change CA set_ids return condition" on.~~
~~PS: this PR should improve collection post performance when batching multiple objects~~
Most notable change in this PR is that collection post no longer fails on single bad object and adds all the good ones, but rather if any object in the collection is bad, none of them get inserted. This is the main source of the performance improvements, by batching multiple operations and queries.
Please pay attention to all object generatios, revision generation (on admin panel), lhn entries, and anything else you can think of.
Testing this is mostly, creating a lot of objects and checking that they …
=> QUICK-FIX Split collection post loop

src/ggrc/models/revision.py
Revisions table has indexes set up correctly (#3537, commit 344e58e198575358ffaccf5bad6997f9b1ba00fd) but the index are not in the
model which can cause issues with alembic (alembic would add
`drop_index` statements to autogenerated migrations).
=> QUICK-FIX Add db.Index statements to revisions table

src/ggrc/models/relationship.py
Previously we only returned `set` if no `types_` was specified - this will consolidate return type to a set.
=> QUICK-FIX Fix return type to be a set instead of list

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/tests/request_model_spec.js
Original error USER-BUG-1.17 was fixed for quince already, however I found another issue with deleted mapped requests.
If a mapped request gets deleted, opening request log for
non-deleted requests throws an error (`.length of undefined`). This
outputs a string with deleted request's ID and a marking that it
was deleted.
=> QUICK-FIX Fix error when opening request log with deleted mapped requests

src/ggrc/converters/query_helper.py, src/ggrc/services/query_helper.py, test/integration/ggrc/services/test_query.py
This PR adds two features to the query api:
- Support for "ids" and "count" query types (the query should contain a field `"type": "ids"` or `"type": "count"` to use it):
- if type is `"ids"`, the result won't contain `"values"`, but instead will contain a list of object ids in `"ids"`;
- if type is `"count"`, the result won't contain `"values"` or `"ids"`, but will contain only the `"count"` of filtered objects;
- Support for multiple query objects in a single POST request as per the advanced query api spec.
This PR also fixes a regression with unavailable text_search that appeared after my refactoring of `converters.query_helper`.
There are tests included for most of the current functionality of the query API.
=> FEATURE Extend query api with "ids" and "count"

src/ggrc/assets/javascripts/permission.js
Please confirm that if GGRC.permissions.[action].[object_type].conditions are not specified we can check permissions based on GGRC.permissions.[action].[object_type].contexts and current object.context.id.
=> ISSUE-1.63 Allow GE to edit owned objects

src/ggrc/assets/javascripts/permission.js, src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache, src/ggrc/assets/mustache/sections/dropdown_menu.mustache
This issue was caused by PR #3990 which disabled deletion of objects
Person/Cycle objects, but it mishandled permission checks without
conditions.
This commit also reverts the changes made in PR #4233 as the fix is no
longer needed
=> Frontend permission fixes

src/ggrc/assets/mustache/base_objects/tier2_content.mustache
Subject: "Map Access Group to Assessment" inified mapper: add description into object info when you expand the line in search result list.
Details: 
Create an Audit
Display Assessments tab
Create  Assessment object
Click + icon to map objects (Unified mapper is displayed with list of available Access Groups)
Click triangle icon before access group title to expand the object’s details
Observe Description field
Actual Result:  Description field is missing on the expanded Access Group object.
Expected Result: Description field is available on the unified mapper. 
Workaround: Edit the object from unified mapper to see the Description field.
=> ISSUE-1.107 Add description field in unified mapper tree view

src/ggrc/assets/javascripts/components/person/person.js, src/ggrc/assets/javascripts/components/person/tests/person_spec.js, src/ggrc/assets/javascripts/models/person.js, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/assets/mustache/audits/extended_info.mustache, src/ggrc/assets/mustache/components/inline_edit/person.mustache, src/ggrc_workflows/assets/mustache/base_objects/approval_link.mustache
Can JS has a known issue with components named with a single word - they might not be rendered and initialised correctly.
=> QUICK-FIX Rename Person component

src/ggrc/converters/handlers/default_people.py, test/integration/ggrc/converters/test_csvs/assessment_template_with_warnings_and_errors.csv, test/integration/ggrc/converters/test_import_assessment_templates.py
It fixes exporting values of "Default Assessors" and "Default Verifier" from Assessment Template, that does not work at all. It also fixes import of the same fields in case them contain list of user emails.
=> QUICK-FIX assessment_template import/export

src/ggrc/assets/mustache/custom_attribute_definitions/tree_header.mustache
_(issue 1.48, section 2)_
This fixes the issue with filtering under the admin panel's custom attributes tab.
Since fixing the filtering functionality would be time-consuming, and because the list of custom attributes is relatively short, it was decided that simply removing the filtering functionality would be the best option.
---
- Go to Admin Dashboard
- Open Custom Attributes tab HNB
- Type “co” into filter textbox and click Filter button
**Actual Result:** Script error _"Uncaught TypeError: Cannot read property 'toLowerCase' of undefined"_ appears.
**Expected Result:**  Inform user properly that user use incorrect values in filter textbox or disable filter button till user fix existing filter criteria (the same as we use for mandatory fields validation)
_NOTE: …
=> ISS-2-1.48 Remove filtering from custom attributes list

src/ggrc/assets/stylesheets/modules/_workflow.scss, src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/mustache/cycle_task_entries/tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_entries/tree_footer.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
_(bug 1.11, section 2)_
Despite the bug description, the broken layout was primarily caused by non-comment objects rendered under the _comments_ section in CycleTaskGroupObjectTask's info pane. This PR makes sure that only comments (i.e. cycle task "entries") are displayed there, and adds a minor styling fix on top of that.
The "official" steps to reproduce the issue seem like an overkill and have nothing to do with user roles. The actual steps are roughly as follows: 
- Open the _Requests_ tab under an Audit (other objects would probably work, too)
- In the Requests tree view, select a request to open its info pane
- Click the "Create Task" option under the the ellipsis (3bbs) menu, fill in the required fields and create a new task
- Add a few comments under the task. To do that, visit …
=> ISS-2-1.11 FIx broken task info panel layout

src/ggrc_workflows/assets/javascripts/components/end_cycle.js
_(bug 1.141, section 2)_
The issue was caused by adding the `'use strict'`directive during  refactoring, causing the browser to strictly complain about the variable `binding` (it was declared without the `var` keyword due to a semicolon instead of a comma in the preceding line).
- Create a one time workflow under admin
- Create a task
- Activate workflow
- Click “End Cycle” button on the Active Cycles tab
_"Uncaught ReferenceError: binding is not defined"_ error is displayed.
No error occurs.
=> ISS-2-141 Fix script error when ending a Workflow Cycle

src/ggrc_workflows/assets/mustache/cycle_task_entries/tree.mustache
This fixes a temporary rendering glitch when the comment's `created_at` field is not available yet due to the comment still being fetched from the server.
**Steps to reproduce:** 
- Create a one time workflow under admin
- Create a task
- Activate workflow
- Add a comment to the task
**Actual Result:** _"Modified by on Invalid date"_ is briefly displayed after adding a comment (in the comments section)
**Expected Result:** A correct time stamp is displayed.
=> ISS-2-1.142 Fix temporarily displaying "invalid date" under comments

src/ggrc/services/common.py, test/integration/ggrc/services/__init__.py, test/integration/ggrc/services/test_collection_post.py, test/integration/ggrc/services/test_common.py, test/integration/ggrc/services/test_response_codes.py
This PR makes sure that we don't return 403 (Forbidden) for invalid requests and such.
The PR  is build on top of https://github.com/google/ggrc-core/pull/4212 and will be rebased once that one is merged.
=> QUICK-FIX Update api response codes

src/ggrc/assets/javascripts/models/join_models.js, src/ggrc/assets/javascripts/models/simple_models.js
Subject:
Script error "Uncaught TypeError: Cannot read property 'apply' of undefined" occurs while adding an auditor in Audit's Info panel
Details: 
Navigate to Audit’s Info panel -> Add Editor -> click on Add
Actual Result:
Script error "Uncaught TypeError: Cannot read property 'apply' of undefined" occurs while adding an auditor in Audit's Info panel
No error. An auditor should be added in Audit's Info panel
**Note:** It's add _Auditor_, not _Editor_
=> ISSUE-1.149 Script error occurs when adding new auditor

src/ggrc/models/custom_attribute_value.py, src/ggrc/models/mixins/customattributable.py
This PR fixes the problem that `CustomAttributable` mixin defines backrefs `{0}_custom_attributable`, but `CustomAttributeValue` model tries to use the same backrefs under the name `{0}_attributable`, thus making `attributable` property non-functional.
This PR also fixes another problem that appears after fixing this one: the code like `self._custom_attribute_values.append(CustomAttributeValue(attributable=self))` appends the new CAV object to `self._custom_attribute_values` twice: on `append` call and on `attributable=self` assignment.
~~I haven't tested `_add_ca_values` setter; it can possibly have the same issue as `_add_ca_value_dict`.~~
The double-addition problem was fixed in both variants of `custom_attribute_values.setter`.
=> QUICK-FIX Fix CustomAttributable backref

src/ggrc/services/common.py
We should serialize all objects when they are still in the session. This
change removes linear number of database queries for all collection post
requests.
query count for posting 90 relationships:
before: 1275
after: 1095
=> QUICK-FIX Move collection post serialization

src/ggrc/assets/javascripts/models/save_queue.js
Now that we have a better collection_post implementation on the
backend it's safe to increase the number of objects batched.
This will decrease the time needed for creating more than 100
objects since the backend API will not need to load permissions
multiple times.
=> Increase BATCH_SIZE for post requests

src/ggrc/assets/javascripts/models/save_queue.js, src/ggrc/assets/javascripts/models/tests/save_queue_spec.js
This PR fixes the issue in `SaveQueue` that didn't clear the saved responses in a bucket after processing them. This resulted in unnecessary processing of old responses.
---
- Create a program, visit the Audits tab
- Create a few Audits without refreshing the page
You will notice in browser's Network tab that each created Audit results in several permission GET requests - the N-th created Audits causes the permissions to be fetched N times.
The same issue probably affected other Cacheable models as well, because using the SaveQueue is baked into the `can.Model.Cacheable.save()` method.
=> QUICK-FIX Prevent multiple redundant permission GETs

src/ggrc/assets/javascripts/mustache_helper.js
**Subject:** "Uncaught TypeError: instance.get_mapping is not a function" error is displayed while mapping Access Group to Assessment object
**Details:** 
- Create an audit
- Create assessment object
- Click + to map objects
- Select Access Groups in dropdown
- Click Search button -> about 10 objects are found
- Expand each object (click triangle before title)
**Actual Result:** While expanding the objects details following error is displayed: "Uncaught **TypeError:** instance.get_mapping is not a function". Error is not displayed for all found objects.
**Expected Result:** No errors displayed.
**Workaround:** N/A
=> QUICK FIX exception displayed while mapping Access Group to Assessment object

src/ggrc/assets/mustache/dashboard/info/get_started.mustache
This mimics the behavior in the LHN (search_actions.mustache).
Do note that the creator will only see the Create Request link AFTER an Audit was created.
_Subject: Global creator user cannot create a Request from My Work page via "Create new object" button
Details: 
log in as progcreator@reciprocitylabs.com
go to my work page
click "Create new object" button
Actual Result: there is no Request item in the dropdown list
Expected Result: Request item should be in the dropdown list
Workaround: go to audit page and create a request there_
=> 1.51 Fix create permissions for the get started buttons

src/ggrc/assets/javascripts/controllers/modals_controller.js
**Subject**: Script error "Uncaught TypeError: Cannot read property 'editor' of undefined" appears if Save & Add Another button is clicked when creating Control on program page
**Details**: 
- Add Controls tab
- Click + to map Controls
- Click Create new Control
- Fill in title and click Save & Add another
**Actual Result**: Script error "Uncaught TypeError: Cannot read property 'editor' of undefined" appears
**Expected Result**: Control is saved.
Notes: Please try to reproduce it for Control with custom attribute type:RichText.
=> ISSUE-1.157 Cannot read property 'editor' of undefined"

src/ggrc/assets/javascripts/apps/business_objects.js
**Subject:** "Uncaught TypeError: Cannot read property 'findInCacheById' of undefined" error occurs when create an assessment in dashboard
**Details:**   Go to dashboard
Click on assessments icon
Click [+] to map Assessment->Click on Create New
**Actual Result:** "Uncaught TypeError: Cannot read property 'findInCacheById' of undefined" error occurs while mapping an object in Create New task form
**Expected Result:** No error. Assessment should be created. 
UPDATE:
Need remove [+] button from Assessment tab on My Page
=> ISSUE-1.175 Fix mapping to Person

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
**Subject**: "Uncaught TypeError: Cannot read property 'has_binding' of null" error appears when click Search in Admin Dashboard page
- Go to Admin Dashboard page
- Click Search page
- Look at Search page: an error is displayed
**Actual Result**:  "Uncaught TypeError: Cannot read property 'has_binding' of null" error appears when click Search in Admin Dashboard page
**Expected Result**: No error displayed
=> ISSUE-1.172 Cannot read property 'has_binding' of null

src/ggrc/models/comment.py, src/ggrc/models/custom_attribute_value.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/models/mixins/validate_on_complete.py, test/integration/ggrc/api_helper.py, test/integration/ggrc/converters/test_imported_api_requests.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py, test/integration/ggrc/models/mixins/test_validate_on_complete.py
~~This PR depends on #4270 that fixes a related bug and is not functional without that bug fix.~~
This PR introduces fields that can be used to disable "Complete" button on Assessment page on the frontend.
The new JSON representation of an Assessment with several CA values with the new fields is as follows:
```js
"assessment": {
"custom_attribute_values": [
{
// a dropdown with missing mandatory comment
"attribute_value": "some value that requires a mandatory comment",
"preconditions_failed": ["comment"],  // this list contains every failed precondition; its items can be "comment", "evidence" and "value"
// other CAV fields
}
],
"preconditions_failed": true,  // this field is true if any precondition of any CA value failed
// other Assessment fields
}
```
`Assessment.preconditions_failed` …
=> FEATURE preconditions_failed fields

src/ggrc/assets/javascripts/apps/custom_attributes.js, src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/javascripts/components/inline_edit/inline.js, src/ggrc/assets/javascripts/components/inline_edit/tests/inline_edit_spec.js, src/ggrc/assets/javascripts/plugins/component_registry.js, src/ggrc/assets/mustache/base_templates/effective_dates.mustache, src/ggrc/assets/mustache/components/datepicker/datepicker.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache, src/ggrc/assets/mustache/custom_attributes/info.mustache, src/ggrc/assets/mustache/custom_attributes/modal_content.mustache, src/ggrc/assets/mustache/programs/modal_content.mustache, test/selenium/src/lib/constants/locator.py
So overall problem is following:
- If I fix how we set attributes on scope d8d279654e8f1380b3463093cc575dfa21423b98 and we have old CA rendering logic, we will get an stack overflow. With this fix our Unified mapper and all components get events triggered properly
- I've used this opportunity to clear CA logic a bit, because with old logic all inner components break due to scope visibility
I can probably split this into two separate PR's.
I need some feedback on this, prolly @Smotko the most
P.S. Kudos to @zidarsk8 for all the answers and simplifying our life with new CA
P.P.S. @zidar I couldn't find any regressions related to CA
=> QUICK-FIX Simplify CA rendering

src/ggrc/converters/base_row.py, src/ggrc/services/common.py, src/ggrc_basic_permissions/__init__.py
**Steps to reproduce:** 
* Log as Global Reader
* Create a program -> Create an audit -> Save
* Look at the console (F12)
**Actual Result:** Error "Failed to load resource: the server responded with a status of 403" in the console occurs while creating an audit under GR role
**Expected Result:** No error. An audit is created under GR role.
The bug is not reproduced in development environment without cache.
=> ISSUE-1.138 Fix cached permissions for audit create

src/ggrc/assets/javascripts/components/person/person.js, src/ggrc/assets/javascripts/components/person/tests/person_spec.js
When the user object is not in cache we need to user the refresh
queue instead of the findOne call in order to prevent multiple
request being sent to the server.
=> Use refresh queue to fetch the user object in person-info 

src/ggrc/assets/javascripts/components/inline_edit/inline.js, src/ggrc/assets/mustache/custom_attributes/info.mustache
**Subject:** "Uncaught TypeError: scope.needConfirm.confirm is not a function" error occurs while edit in People's Info panel 
**Details:**   
- Navigate to People tab
- Navigate to People’s Info panel
- Edit a value in any editable field
**Actual Result:**  "Uncaught TypeError: scope.needConfirm.confirm is not a function" error occurs while edit in People's Info panel 
**Expected Result:** No errors displayed/ Should be the possibility to edit editable fields. 
**Workaround:** Navigate to People’s Info page and edit.
=> QUICK FIX scope.needConfirm.confirm exception

src/ggrc/builder/json.py, src/ggrc/services/common.py
This Pr removes all queries for deserializing reltionship object in collection post.
Query count for colleciton post with 90 object:
before: 1275
after: 1097
=> QUICK-FIX Cache objects on request

src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
_(section 2, bug 1.174)_
This PR fixes an issue with creating a Task for an Audit.
The error was caused by the unspecified `through` property of the relevant pending join object for the Task under creation, thus the name of the mapping is now passed to the `ggrc-modal-connector` component.
If there are any use cases when this name should be dynamic, please let me know to change the fix. So far it seems that creating a new Task and later editing it both work as expected.
- Create a Program
- Create an Audit under that Program
- Navigate to Audit’s Info panel -> Click on 3bb’s button -> Select Create a task
- Map an object or two to the Task, and also make sure to remove the Audit from the "mapped object(s)" list
- Fill in the mandatory fields and click the "Save and …
=> ISSUE-1.174 Fix Audit Task creation issue with mapped objects

src/ggrc/models/custom_attribute_value.py
This PR fixes storing empty Map:Person CAVs.
Steps to reproduce: make a PUT request for an Assessment with Person CAD with `custom_attribute_values = [{"custom_attribute_id": "<CAD_id>", "attribute_value": null, "attribute_object": null}]`.
Expected results: the empty value is stored and is returned in response with `"attribute_value": null, "attribute_object": null`.
Actual results: error 500 is returned because of an uncaught `AttributeError`.
=> QUICK-FIX Fix storing empty values for Map:Person

src/ggrc/templates/admin/index.haml
**Subject**: "Uncaught TypeError: Cannot read property 'id' of undefined" error occurs while maping an object to task in Admin Dashboard
- Go to Admin Dashboard
- Click Search
- Select Object type “Program”> Search program (e.g. prog562)
- Click triangle near the program in Objects found list
- Click 3 bb’s button>Create a task
- Fill TASK SUMMARY and ACTIVE WORKFLOW
- Click Map Objects button  
**Actual Result**: "Uncaught TypeError: Cannot read property 'id' of undefined" error occurs while maping an object to task in Admin Dashboard
**Expected Result**: No error. Objects should be mapped to the task
=> ISSUE-1.180 "Uncaught TypeError: Cannot read property 'id' of undefined"

src/ggrc/assets/mustache/controls/tier2_content.mustache, src/ggrc/assets/mustache/directives/tier2_content.mustache, src/ggrc/assets/mustache/objectives/tier2_content.mustache, src/ggrc/assets/mustache/programs/tier2_content.mustache, src/ggrc/assets/mustache/requests/tier2_content.mustache, src/ggrc/assets/mustache/sections/tier2_content.mustache, src/ggrc_workflows/assets/mustache/workflows/tier2_content.mustache
**Subject**: Add Control description in the preview window (unified mapping modal)
**Details**: 
-  go to Program page and open Controls tab
-  click Search button to see the controls in OBJECTS FOUND section
- Click grey triangle in a Control’s first tier in OBJECTS FOUND section
**Actual Result**: the app doesn’t show description in Control’s 2nd tier on unified mapping modal window
**Expected Result**: Add the control description to the unified mapper modal window
**Notes**: Description field should be visible for all types of objects
=> ISSUE-1.56 Add Control description in the preview window

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/tests/cacheable_model_spec.js
**Subject**: "Uncaught TypeError: Cannot read property 'sort' of undefined" error is displayed on Workflow's Active Cycle tab
- Open any activated Workflow (https://grc-dev.appspot.com/workflows/689#current_widget/cycle/976)
- Display Active cycles tab
- Click on active cycle 1st tier
**Actual Result**: "Uncaught TypeError: Cannot read property 'sort' of undefined" error is displayed
**Expected Result**: No errors displayed. Info pane is displayed
=> ISSUE-1.192 Cannot read property 'sort' of undefined"

src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
_(section 2, bug 1.171)_
In the mapper modal, a newly created Assessment did not appear in the list of objects to select and map to the target object, and this PR fixes that.
A test turned out to be a bit too complicated to write with the current state of the code, the  `form` method of `ajax-modal` would need to be refactored into smaller composable parts for that. :/
- Create a program under GE role
- Click Add-> Assessments-> Click [Create New Assessments] button in Unified mapper window
- Fill in the obligatory fields->Save and Close
The created Assessment does not appear in the list of "results" in the mapper modal while adding through Unified mapper window  
The created Assessment is displayed in the list of "results" …
=> ISSUE-1.171 Fix mapping new Assessments in mapper modal

src/ggrc/assets/javascripts/components/assessment/add_comment.js
**Subject:** Comment from assessor has N icon
**Details:**   
- Create program, audit and assessment by user#1
- Set user#2 as assessor, set user#3 as verifier
- Open assessment page for created as sessment and leave comment by each user
**Actual Result:** Comment from assessor displayed with N icon
**Expected Result:** Comments should have appropriate icon for each assessment role (A - for assessor)
=> ISSUE-1.184 Fix icon in comment from assessor

src/ggrc/assets/javascripts/plugins/component_registry.js, src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
Subject: "Maximum call stack size exceeded" error is displayed while creating new task on Workflow's Setup tab
Details:   
Create a one time Workflow
Click + to create new task on Setup tab
Actual Result: "Maximum call stack size exceeded" error is displayed
Expected Result: No errors displayed. Task could be created
=> ISSUE-1193 Maximum call stack size exceeded when creating new task

src/ggrc_workflows/assets/mustache/selectors/object_selector_option_items.mustache
_(section 2, bug 1.194)_
This fixes an issue with automatically selecting a checkbox in the mapper modal after creating a new object in it.
The problem is that if there is a conditional block in a Mustache template that conditionally creates an attribute, and that block contains whitespace, that is parsed by CanJS just by splitting the block at `=` character, resulting in e.g. the following (note the leading/trailing whitespace:
- Attribute name: `'  attr-foo'`
- Attribute value: `'bar  '`
CanJS then internally tries to set an attribute with a name `' attr-foo'` on a DOM element, which browser refuses because of an invalid attribute name (it must not contain whitespace).
**Lesson:** Be very careful when using Mustache blocks for managing DOM elements' attributes, it can easily result in …
=> ISSUE-1.194 Fix error when checking a checkbox in mapper modal

src/ggrc/models/custom_attribute_value.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py
~~This PR depends on #4275 and can't be merged before it.~~
This PR enables mandatory evidence check on the backend and makes preconditions check on the frontend unneeded.
The logic of mandatory evidence check is the same as it used to be on the frontend: mandatory evidence preconditions fails for every CAV requiring evidence if the number of evidences required is greater than the number of evidences provided. This is a temporary solution until we make a decision on how Evidence - CA mapping should behave, what can be mapped to what and how will evidence reuse work in this case.
=> FEATURE Mandatory evidence check

src/ggrc/assets/javascripts/mustache_helper.js
This prevents `"Uncaught TypeError: Cannot read property '0' of undefined" occurs while Raising an Issue in Assessment's Info panel under GC role` from happening by disabling the create request/raise an issue button from showing if the the user doesn't have permission to map all objects.
=> 1.179 Fix raise issue button

src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc_risk_assessments/assets/javascripts/apps/risk_assessments.js, src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree_add_item.mustache
**Subject**: "Cannot read property 'model_singular' of undefined" error is displayed while mapping Risk Assessment to program
- Click Add+ >Select Risk Assessments
- Click + Add New Rule
**Actual Result**: "Cannot read property 'model_singular' of undefined" error is displayed
**Expected Result**: No error displayed.
**Notes**: 
- @Smotko noted that adding Risk Assessments to Program should behave as Audits (Add instead of Map). This fix also enables this behaviour.
- Well known issue: Risk Assessment could not be saved (button is disabled). We agreed with QA team that it will be fixed in scope of another issue.
=> ISSUE-1.190 Cannot read property 'model_singular' of undefined

src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
_(section 2, bug 1.219)_
This PR fixes a script error that occurs when trying to edit user's permissions. The cause was incorrectly raising a missing context error, even if the page instance's context was not even expected to be present (e.g. when that instance is a Person object when on the admin panel).
**Details:**
- Go to Admin Dashboard, People tab
- Select any person -> Click grey triangle -> Click 3 bbs button ->Edit Authorizations
_"Uncaught Error: `context` is required for Assignments model"_ error occurs when select Edit Authorizations for a person in Admin Dashboard
No error displayed. Authorizations for a person in Admin Dashboard should be edited.
=> ISSUE-1.219 User edit auth error

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
Subject: CA value isn’t updated in the tree view after editing
Details: 
Navigate to Program page and open Controls tab in HNB
Click “gear” icon and make the CA field visible in the tree view
Click the 1st tier of a control in the tree view
Edit a CA value via info panel
save
Actual Result: the app confirms that changes are saved but the new CA value isn’t shown in the tree view.
Expected Result: the new CA value should be shown in the tree view right after updating it and saving it in info panel.
Workaround: refresh the page
=> ISSUE-1.50 CA value isn’t updated in the tree view after editing

src/ggrc/assets/javascripts/components/reminder.js, src/ggrc/assets/javascripts/components/tests/reminder_spec.js
_(section 2, bug 1.165 - P0)_
This PR fixes an error when trying to send reminders to Assessment's assessors.
- Create an Audit
- Create assessment object/Define assessment template->generate assessment
- Navigate to Assessment Info/navigate to generated assessment
- Click 3bbs button and click _"Send reminder to assessors"_
_"PUT https://grc-dev.appspot.com/api/assessments/13846 428 ()"_ is displayed in console. Modal window is not displayed.
Notifications are created, the PUT request succeeds.
=> ISSUE-1.165 Fix HTTP 428 error on sending Assessment reminders

extras/deploy_settings_local.sh
It fixes `DATABASE_URI` variable that currently points to invalid host in clean dev environment (i.e. environment created using `docker-compose-clean.yml`).
=> QUICKFIX GAE settings for clean dev environment

src/ggrc_basic_permissions/roles/Reader.py, src/ggrc_gdrive_integration/assets/javascripts/apps/gdrive.js, src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js, src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js, src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
Subject: GReader is not able to Attach evidence - message no folder for Audit is displayed even if folder is assigned to Audit and Reader have edit rights on it
Details: 
Create Program
Create Audit
Create  Assessment object with GReader as assessor 
As Reader, navigate to page of newly created assessment
Open info tab 
Confirm red alert triangle is displayed next to the Attach evidence button
Click attach evidence button
Select and upload any file
Actual Result:  Attached file is not displayed, several error messages are displayed on JS console
=> ISSUE-1.116 Reader with Assessor permissions can attach evidence

src/ggrc/services/common.py
1. Go to Import page.
2. Download assessment csv template.
3. Fill only Audit column.
4. Click Choose CSV file to import button and select this file.
5. Click Import.
Actual result is an error message "Import failed due to server error." and server responses with 400 status code. This fixes the server error.
The bug is not reproduced locally with disabled cache.
=> ISSUE-1.147 Fix empty import error

src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/javascripts/controllers/tests/inner_navigation_controller_spec.js, src/ggrc/assets/javascripts/modules/widget_descriptor.js, src/ggrc/assets/javascripts/modules/widget_list.js, src/ggrc/assets/mustache/dashboard/internav_list.mustache, src/ggrc_risks/assets/javascripts/apps/risks.js, src/ggrc_workflows/assets/javascripts/apps/workflows.js
_(Buganizer issue 28426058, for those with access)_
The user wanted a modified order of the tabs in the horizontal navigation bar (currently sorted alphabetically). The new order of the mapped object types should be as follows:
- Standard
- Regulation
- Contract
- Section
- Objective
- Control
- everything else (opted to keep that in alphabetical order)
BTW, this new order does not apply to Workflows AFAIK - please let me know in case this assumption is incorrect.
BTW 2, this change also affect the order of the items in the HNB's "Add..." menu (it uses the same collection for rendering), but when discussed with @Smotko we concluded that this is probably just fine and a different (read: alphabetical) order is not required there.
=> FEATURE Mapped objects tabs order

src/ggrc/assets/javascripts/components/assessment/inline.js, src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/javascripts/ggrc_base.js, src/ggrc/assets/javascripts/models/cacheable.js
**Subject**: User gets non-informative error message when he doesn't have permissions to update the Assessment
**Details**: Create an assessment and assign a Global Reader as an assignee
Make sure GR user is added to the program with Program Reader Role
Log in as GR and remove yourself from assignee
Do not refresh the page
Try inline editing one of the CAs on Assessment’s info pane
_Actual Result:_ the red error message “There was a problem saving” appears
_Expected Result:_ the error should say “you have no permissions to edit the assessment”
=> ISSUE-1.208 Use error message from server-side

src/ggrc/assets/javascripts/components/unified_mapper/mapper_checkbox.js, src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
**Subject**: Checkboxes are filled while Selecting None in Generate Assessment window
- Create an Audit
- Map several new Controls to Audit 
- Navigate to Assessments tab and Click to Generate Assessments
- Select Object type “Controls” mapped to the created Audit->Click on Search button
- Select All objects
- Select None: checkboxes are still filled
**Actual Result**: Checkboxes are filled while Selecting None in Generate Assessment window
**Expected Result**: Checkboxes should not be filled while Selecting None in Generate
=> ISSUE-1.177 Checkboxes are filled while Selecting None

src/ggrc/assets/mustache/base_templates/mapped_objects.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
**Subject**: “Map Objects” button is active in finished task’s info panel
**Details**: 
Navigate to WF -> Active cycle tab
Finish the task
Open task’s info panel
_Actual Result_: confirm you see active “Map Objects” button and can map an object to finished task
_Expected Result_:  “Map Objects” button shouldn’t be visible or active, it shouldn’t be possible to map objects to the task that is finished
=> ISSUE-1.100 Hide Map object button on finished tasks

src/ggrc/converters/query_helper.py, src/ggrc/models/assessment.py, src/ggrc/models/mixins/with_similarity_score.py, src/ggrc/models/request.py, src/ggrc/utils/similarity_options.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
This PR adds logic to determine "related Assessments/Requests" (renamed to "similar Assessments/Requests" to avoid confusion with objects being related via Relationship object) to the backend.
This feature can be invoked through Query API by adding a special filter: `{"op": {"name": "similar"}, "object_name": "Assessment", "id": 42}`, which will return all objects of requested type (not necessarily Assessments) that have mappings similar to Assessment with id = 42.
The only types allowed in `"object_name"` here are Assessment and Request.
To sort by the measure of similarity you should provide `"order_by": ["name": "__similarity__"]` with optional `"desc": true` (to get most similar objects returned first, as the current implementation on the frontend does). This ordering is a special …
=> FEATURE Related assessments on backend

doc/git_management.md
This change just makes it easier for users to properly set their
upstream push url. Now copy paste should work without having to change
the <nick> placeholder.
=> QUICK-FIX Update git management doc

src/ggrc/assets/javascripts/apps/dashboard.js, src/ggrc/assets/mustache/base_objects/page_header.mustache, src/ggrc/assets/stylesheets/modules/_menu.scss, src/ggrc/templates/base_objects/show.haml, src/ggrc/templates/dashboard/index.haml, src/ggrc_workflows/views/__init__.py
_(buganizer issue 29927456, P1)_
This PR changes the way the My Tasks count is displayed.
**Description:**
_"The task count in the header should be gray if there are no overdue tasks. Currently it's red if there is more than one task. It should be red only if at least one task is overdue."_
Note that the task count color is not updated automatically when the "overdue" condition changes, a page refresh is needed. @Smotko said that that's fine for the time being, and thus I just opened a post-release issue for it.
During the testing you might notice that when you add a new task (under the Tasks tab), it does not appear immediately in the tree view, a page refresh is needed. This issue is unrelated to this PR, it already exists in the current develop branch.
=> BUG-29927456 Show My Tasks count in red only when overdue tasks

pylintrc, src/ggrc/migrations/versions/20160824005517_31fbfc1bc608_strip_spaces_around_old_cad_dropdown_.py, src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/custom_attribute_value.py, test/integration/ggrc/generator.py
While the frontend code strips the spaces around options of new dropdown CADs, the CADs already stored in the DB can have `multi_choice_options = "one, two , three"` (and the new CAVs can have `attribute_value = "two"`, without spaces, which will be diagnosed as an invalid dropdown value). This PR has a migration that strips the enclosing spaces of options in `multi_choice_options`. There are also SQLAlchemy-level validators that strip the spaces from `CAD.multi_choice_options` and `CAD.multi_choice_mandatory` stored into the DB and `CAV.attribute_value` stored through `CustomAttributable` objects.
1. Create an Assessment with CAD with `multi_choice_options = "one, two , three"` (you should do it manually with SQL or use a CAD defined before a PR that started stripping …
=> ISSUE-1.198 Strip spaces from CAD dropdown options

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/localize_date_today_spec.js, src/ggrc_workflows/assets/javascripts/controllers/dashboard_page.js, src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache, src/ggrc_workflows/models/workflow.py
**Subject**: Workflow: Task Due today but listed as overdue
- Create workflow
- Create task w/due date today
- Activate workflow and go to active cycles tab
**Actual Result**: task with due date equals today is displayed as overdue
**Expected Result**: task should be displayed “Today” text. Task and Workflow shouldn’t be marked as overdue (red colour)
**Notes**: I also introduced some ToDo's to refactor 'overdue detection' in the future.
Please also note that changes in Python code were discussed with @alieh-rymasheuski .
=> ISSUE-1.182 Task Due today but listed as overdue

src/ggrc/services/common.py, test/integration/ggrc/services/test_common.py
This PR fixes a problem when the can.js parser breaks on errors in plaintext, thus disabling error handling functionality.
=> QUICK-FIX Send error message in JSON on 409 and 428

src/ggrc/converters/base_block.py, src/ggrc/migrations/versions/20160901125710_173b800a28f3_update_event_enum_field.py, src/ggrc/models/event.py, src/ggrc/services/common.py, test/integration/ggrc/converters/__init__.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/converters/test_import_update.py
This PR makes sure that all new import objects have their own entry in the revisions table. Fix for existing objects without revisions will come at a later point.
This PR also causes some performance degredation on imports, but that will be fix with imporved logging in the future.
=> QUICK-FIX Enable revisons for imported objects.

src/ggrc/converters/query_helper.py, src/ggrc/models/mixins/with_similarity_score.py, src/ggrc/services/query.py, src/ggrc/services/query_helper.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py, test/integration/ggrc/services/test_query.py
Short description of what was done in scope of this PR:
1. Ordering in query API was moved to the DB side.
2. Ordering by several fields was added.
3. Ordering by mapped-with-foreign-key objects (like `contact` for program, `program` for audit) was implemented (by `title` for `Titled` objects, by name or email for `Person` objects).
4. Ordering by `__similarity__` was moved to the DB side. Now we have same subqueries for filtering and for sorting.
To sort an Audit by its related Program title, pass `"order_by": [{"name": "program"}]` in the query. Ordering by an arbitrary field of a Program was not implemented intentionally but is technically possible.
=> FEATURE Enhanced ordering for Query API

src/ggrc/migrations/versions/20160901125710_173b800a28f3_update_event_enum_field.py
This is so that we don't lose data for all existing import events.
=> QUICK-FIX Leave IMPORT as valid event action

src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js, src/ggrc_risk_assessments/assets/mustache/risk_assessments/modal_content.mustache
**Subject**: Save and Close button/ Save and Add Another button are disabled after filling all the mandatory fields in New Risk Assessment window  
**Details**: 
- Click Add -> Select Risk Assessments
- Click Create New Risk Assessment in unified mapper
- Fill all the mandatory fields
- Click Save and Close button/ Save and Add Another button: are disabled   
**Actual Result**: Save and Close button/ Save and Add Another button are disabled after filling all the mandatory fields in New Risk Assessment window  
**Expected Result**: Save and Close button/ Save and Add Another button should be enabled after filling all the mandatory fields in New Risk Assessment window 
**NOTES**: This fix for 1.210 & 1.91
=> ISSUE-1.210 Save and Close buttons are disabled for New Risk Assessment

src/ggrc/assets/javascripts/components/csv/export.js, src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
**Subject**: JS is displayed by clicking Select All/None attributes link at Export Data page
- Go to Data Export page
- Select Controls in Export Object Types ddl
- Click None link for Attributes
**Actual Result**: JS error appears and not all attributes unchecked
**Expected Result**: all attributes should be unchecked by clicking None for Attributes, all attributes should be checked by clicking Select All for Attributes
**Note**: The roots is that CA attribute could contains "." which is incorrectly used in combination with view bindings.
=> ISSUE-1.331 JS error is displayed by clicking Select All/None

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/plugins/openclose.js, src/ggrc/assets/mustache/base_objects/tree.mustache
**Subject**: Tree view collapses when opening the 3rd tier of some objects
**Details**: 
Go to https://grc-dev.appspot.com/assessments/13635#audit_widget/audit/1476/assessment_template   as admin and open Audit’s 2nd tier in the tree view so you see the list of the objects mapped to the audit
Now open 3rd tiers for the objects
_Actual Result_: the tree view collapses when opening the 3rd tier for a Template and for the Issue
_Expected Result_: template’s tree view should be empty, Issue’s treeview should show the objects directly mapped to the issue object
=> ISSUE-1.87 Fix collapsing treeview

src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/models/custom_attributes.js, src/ggrc/assets/javascripts/models/tests/custom_attribute_definition_model_spec.js, src/ggrc/assets/mustache/custom_attribute_definitions/modal_content.mustache
_(section 2, issue 1.339 - P2)_
This PR prevents creating a Dropdown custom attribute without specifying at least one possible value to choose from.
- Open Custom Attribute tab at Admin Dashboard page
- Open Any attribute section and click Add Attribute button
- Fill Attribute title and select attribute type as Dropdown
- Leave possible values empty or fill spaces and click Save & Close button
Attribute was saved
field with possible values should have mandatory mark and Save & Close button should be disabled until valid values will be provided into possible values field
=> ISSUE-1.339 Make the list of values for Dropdown CAs mandatory

src/ggrc/converters/query_helper.py, src/ggrc/fulltext/__init__.py, src/ggrc/fulltext/mysql.py, src/ggrc/fulltext/recordbuilder.py, src/ggrc/models/custom_attribute_value.py, src/ggrc/views/__init__.py, test/integration/ggrc/converters/test_ca_import_export.py, test/integration/ggrc/converters/test_import_assessments.py
This PR adds global and object level custom attribute filters to query helper that is used in exports and pagination.
From my inital tests the performance degredation is negligible, but keep an eye out for anomilies.
Note: you will have to reindex the full text table for the filters to work.
=> QUICK-FIX Fix custom attribute value filters on export and pagination

src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/mustache/cycle_task_entries/tree.mustache
*Subject:*
attachments not showing up if added to cycle task comment
*Details:*
- Create an active cycle under a WF
- Add a gDrive folder to the WF
- Leave a comment under the task on Active cycle task
- Upload a file to the comment
*Actual Result:*
attached to the comment file isn’t show
attached to the comment file should be show instantly after attaching it
=> ISSUE-1.223 Show task entry mapped documents

src/ggrc/assets/javascripts/plugins/canjs_extensions.js, src/ggrc/assets/javascripts/plugins/tests/canjs_extensions_spec.js
@hyperNURb If you believe tests should behave differently or that I shouldn't throw type error but silently convert to string or return `''` let me know.
=> QUICK-FIX Add type check for spaceCamelCase

src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/mustache/requests/modal_content.mustache
*Subject:*
"Starts On" and "Due On" mandatory date pickers are not validated when creating a request
*Details:*
Start reating a Request under an audit
*Actual Result:*
the save buttons are active though mandatory "Starts On" and "Due On" date pickers aren’t filled in
the save buttons should be inactive until all mandatory fields are filled in
=> ISSUE-1.200 Fix request start and end date

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/components/tests/people_list_spec.js, src/ggrc/assets/javascripts/models/cacheable.js
**Subject**: Single Creator and Assessor are deleted from Assessment from Assessment Edit modal window by deleting Verifier
**Details**: 
- Login as admin
- Create control from LHN menu
- Create program from LHN menu
- Open program page, click at Control tab and map created control to program
- Click at Audit tab and create Audit for program
- Open Audit page
- Click at ASMT template tab and create ASMT template based on control
- Click at Assessment tab and Generate assessment based on created control and asmt template
- Open Edit Assessment modal window and hover mouse over Verifier and delete current logged user
**Actual Result**: User was deleted from Creator and Assessor too
**Expected Result**: Verifier should be deleted only.
**Notes**: Sometimes it's really hard to reproduce this …
=> ISSUE-1.90  Single Creator and Assessor are deleted by deleting Verifier

src/ggrc/app.py, src/ggrc/converters/base_block.py, src/ggrc/models/mixins/__init__.py, src/ggrc/notifications/common.py, src/ggrc/notifications/data_handlers.py, src/ggrc/services/common.py, src/ggrc/services/log_event.py, src/ggrc/utils/benchmarks.py, src/ggrc_workflows/notification/data_handler.py
I have found multiple issues:
1. Deleted requests were not deleted from the notifications table (isn't reproducible) and there are no app engine logs from the date when the Request was deleted.
2. Cycle tasks can have a NULL contact_id in the database so we can't assume the contact will always be there.
3. Comment might not be mapped to an Assignable object.
I have created post quince tasks for all of these cases, but for now I think this PR should unblock people trying to test notifications.
=> 1.153 Fix erros in data handlers

src/ggrc/assets/javascripts/components/autocomplete/tests/autocomplete_spec.js, src/ggrc/assets/javascripts/components/person/tests/person_spec.js, src/ggrc/assets/javascripts/plugins/component_registry.js
I found out that using `scope.attr` in init function propagates attribute to parent scope and causes problem. This should fix that issue.
=> QUICK-FIX Prevent casting scope values to parent scope

src/ggrc/assets/javascripts/plugins/component_registry.js
If we return new can.Map, can.compute doesn't get bind to the map object itself and it throws an error - this PR fixes this issue.
=> QUICK-FIX Component should create its own map object

karma.conf.js
This fixes a temporarily commented-out setting that slipped through in #4378
=> QUICK-FIX Re-enable the majority of frontend tests

src/ggrc/models/reflection.py
This piece of code does not seem to be used anywhere and can be safely removed.
=> QUICK-FIX Remove dead python code

src/ggrc/assets/mustache/components/ca-object/ca-object-title.mustache, src/ggrc/assets/mustache/components/ca-object/ca-object.mustache
1.344  Bug (P1) 
Subject: GR is able to Add comment without PE role in Assessment's Info panel  
Details:  
Create an audit>Navigate to audit tab
Create Assessment with CA fields
Log as Global Reader
Open the created Assessment
Navigate to Assessment’s Info panel-> Add comment into CA field: pop up window is displayed for adding a comment
Actual Result:  GR is able to Add comment without PE role in Assessment's Info panel  
Expected Result: GR is not able to Add comment without PE role in Assessment's Info panel
=> QUICK-FIX GR is able to Add comment without PE role in Assessment's Info panel

src/ggrc/assets/mustache/assessments/header.mustache
1.353  Bug (P1)
Subject: Assessment's state "Complete" isn't shown in info panel
Details: 
Log in as auditor and navigate to an audit page with assessments
Assessment shouldn’t have Verifiers
Complete the assessment clicking “complete” button
Actual Result: Assessment's state "Complete" isn't shown in info panel
Expected Result: Assessment's state "Complete" should be shown in info panel
=> QUICK-FIX Assessment's state "Complete" isn't shown in info panel

src/ggrc/assets/javascripts/client_record_replay.js
The code was comparing the result of `typeof` with a variable named `undefined`.
As typeof returns a string it should compare to `'undefined'`
=> QUICK-FIX Correct check for undefined variable

src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
Subject: Script error "Uncaught TypeError: Cannot read property 'length' of undefined" appears when adding a comment with the attachment under a request https://grc-test.appspot.com/admin/unstarted_cycles url
Details: 
Navigate to request tab on audit page
Open request’s info panel
Add a comment with attachment
Actual Result: script error appears upon adding a comment
Expected Result: No error displayed. 
This is a leftover from #4309 and #4365
=> ISSUE-1.374 Remove fileable deferred

src/ggrc/assets/javascripts/components/person/person.js, src/ggrc/assets/javascripts/components/person/tests/person_spec.js
I've figured out I've missed this case. Easiest way to reproduce it to provide person object with fully data and watch refresh que get triggered.
=> QUICK-FIX Person model should always be set

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
*Subject:*
Extra Control mapped while creating and mapping a new Control via unified mapper window
*Details:*
- Create/Go to Audit
- Go to Control tab-> Map Control to this Audit: confirm that 1 object selected for mapping is displayed in Unified mapper window 
- Click Create New Control-> Fill the mandatory fields-> Save and Close: confirm that 2 objects selected for mapping is displayed in Unified mapper window
- Click [x] to Close Unified mapper window
- Open Unified mapper window to Map Control to this Audit once again
- Create New Control-> Fill the mandatory fields-> Save and Close: confirm that 3 objects selected for mapping is displayed in Unified mapper window 
- Click Map selected: extra Control mapped while creating and mapping a new Control
*Actual Result:* Extra Control …
=> ISSUE-1.365 Reset entries and selected items in unified mapper

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/if_current_user_spec.js, src/ggrc/assets/mustache/mixins/stateful.mustache
Subject: Verifier doesn't see "Reject" / "Verify" buttons if he just added himself a verifier role under an Assessment
Details: 
Create an Assessments and make yourself an Assessor
Assign another user as the verifier
Click complete button
Now add yourself to the verifiers
Actual Result: "Reject" / "Verify" buttons aren’t visible immediately
Expected Result: "Reject" / "Verify" buttons should appear right after user became a verifier
Screenshot: N/A
=> ISSUE-1.26 Dynamically check for related verifiers

src/ggrc/assets/javascripts/components/object_history/object_history.js, src/ggrc/assets/javascripts/components/object_history/tests/object_history_spec.js
This issue can be reproduced on dev: [assessment](http://localhost:8080/audits/1477#assessment_widget/assessment/13639)
=> QUICK-FIX Assessment Log tabs hangs in case of incorrect related persons data 

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/services/common.py
_(section 1, issue 377 - P0)_
This PR fixes navigating the pages of Users on the admin panel.
(no tests, unfortunately, as that would require quite some refactoring of the `makeFindPage()` method :/ )
- Navigate to admin page => users tab
- Click “""NEXT PAGE"" link at the bottom
The app shows empty page, error 406 appears in the console
The app should show the 2nd page of the list of the people registered in the system
=> ISSUE-1.377 Fix navigating to the next page of users

src/ggrc/converters/handlers/custom_attribute.py, test/unit/ggrc/converters/handlers/__init__.py, test/unit/ggrc/converters/handlers/test_custom_attribute.py
_(section 2, issue 1.372 - P1)_
This PR assures that exporting and re-importing the same object works as expected. It changes the format of the exported values for checkbox custom attributes to match what the import expects (literal strings 
_"FALSE"_ and _"TRUE"_ instead of numeric `0` and `1`, respectively).
- Navigate to export page and export an Assessment with checkbox CA
- During the export, the checked checkbox CAs are exported with a value 1
- Try to import the same CSV file
the import expects a string TRUE, thus ignoring the record previously exported.
The import should either support few values (eg True, 1, yes etc) and clearly specified to the user in the column title cell or there should be only one allowed value …
=> ISSUE-1.372 Change exported checkbox CA values format

src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js
There is no reason to trigger widgets_updated event in the draw_widget
function. This improves performance of the initial page load by 10s in
some cases.
Regulation page load time BEFORE:
Regulation page load time AFTER:
=> Improve page load performance

src/ggrc/assets/mustache/base_templates/attachment.mustache
_(section 2, issue 1.366 - P1)_
This PR fixes links to attached evidence files.
- Attach an evidence to a Request via import (NOTE: simply uploading the evidence through the application seems to work as well)
- open Request info panel on Audit page
- Click the evidence link
the browser cannot reach the evidence file because file address is duplicated (see the screenshot)
the link to the file should be correct
=> ISSUE-1.366 Fix URL to attached evidence files

src/ggrc/assets/javascripts/components/add_comment/add_comment.js, src/ggrc/assets/mustache/base_templates/add_comment.mustache
Subject: "Uncaught TypeError: Cannot read property 'find' of null" error is displayed while navigating to Request Log in Request's Info panel
Details: 
Navigate to Request’s Info panel
Go to Comments and Responses tab
Enter comment and while comment is saving click on Request Log tab: an error is displayed 
Actual Result: "Uncaught TypeError: Cannot read property 'find' of null" error is displayed while navigating to Request Log in Request's Info panel
Expected Result: No error displayed. 
=> ISSUE-1.382 Fix setting and getting values from textarea
