src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/javascripts/components/object-list/object-list.js, src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-item.js, src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-list.js, src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js, src/ggrc/assets/javascripts/components/spinner/spinner.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/components/assessment/controls-toolbar/controls-toolbar.mustache, src/ggrc/assets/mustache/components/mapped-objects/mapped-objects.mustache, src/ggrc/assets/mustache/components/object-list/object-list.mustache, src/ggrc/assets/mustache/components/reusable-objects/reusable-objects-item.mustache, src/ggrc/assets/mustache/components/simple-modal/simple-modal.mustache, src/ggrc/assets/mustache/components/spinner/spinner.mustache, src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss, src/ggrc/assets/stylesheets/components/object-list/_object-list.scss, src/ggrc/assets/stylesheets/components/reusable-objects/_reusable-objects.scss
1.387  Bug (P1)
Subject: There are no spinners or loading animation so the users see this for the first 5-10s while related objects are loading
Details: 
Go to assessment page and open Related assessments tab on info panel
Actual Result:  There are no spinners or loading animation so the users see this for the first 5-10s while related objects are loading
=> IMPROVEMENT Add Spinner on Loading of Related Requests   

bower.json, src/ggrc/assets/javascripts/components/datepicker/datepicker.js
This fixes a deprecation warning and upgrades moment.js to the latest version. We need to upgrade moment because 2.10 has a known vulnerability.
=> QUICK-FIX Upgrade momentjs

src/ggrc/assets/mustache/base_templates/attachment.mustache, src/ggrc/assets/mustache/base_templates/mapping_tree_view.mustache
_(section 2, issue 1.375 - P1)_
This PR fixes displaying the attached evidence info - the problem was that the Document instance was not properly refreshed in the template, thus the latter did not have all the data available.
NOTE: The changes in `attachment.mustache` were made during the debugging, but ultimately turned out to be unnecessary - I nevertheless kept them in for better template readability, but if somebody really doesn't like it, I can kick that out. :smile: 
**Details:**
- Navigate to request tab on audit page
- Open Request’s info panel
- Add a comment with attachment
- Add another comment with the attachment
- Reload the page
""Invalid date"" is shown instead of the 2nd file name on Request's info panel
the file title should be …
=> ISSUE-1.375 Fix the rendering of uploaded Request evidence

src/ggrc/assets/mustache/assessments/modal_content.mustache
Subject: There is no a message about changing Assessment's status when editing it
Details: 
Navigate to an Assessment in Not Started state
Edit it
Actual Result: There is no a message about changing Assessment's status when editing it
Expected Result: the message should warn the user that Assessment's state will be changed upon saving
=> ISSUE-1.379 Add status change warning

test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py, test/integration/ggrc/models/test_clonable.py
Setting related attributes should be done with objects as the ORM
expects. This fixes errors when upgrading to sqlalchemy to 1.0.1.
=> QUICK-FIX Fix CA preconditions tests

src/ggrc/assets/mustache/custom_attributes/info.mustache
**Subject**: GCA Dropdowns lost their values on info panels/tabs
**Details**: 
- Create a GCA dropdown field with values for regulation object type
- Create a regulation and navigate to its page
- Click edit icon next to dropdown CA field
**Actual Result**: dropdown field has no values
**Expected Result**: values should be present in the dropdown
=> ISSUE-1.406 GCA Dropdowns lost their values on info panels/tabs

src/ggrc/services/common.py
It fixes 1.90 and 1.385 bugs. They are about cache with people doesn't
update when new assessment generates.
**1.90  Bug (P1)**
**Subject:** Single Creator and Assessor are deleted from Assessment from Assessment Edit modal window by deleting Verifier
**Details:**
- Login as admin
- Create control from LHN menu
- Create program from LHN menu
- Open program page, click at Control tab and map created control to program
- Click at Audit tab and create Audit for program
- Open Audit page
- Click at ASMT template tab and create ASMT template based on control
- Click at Assessment tab and Generate assessment based on created control and asmt template
- Open Edit Assessment modal window and hover mouse over Verifier and delete current logged user
**Actual Result:** User was deleted from Creator …
=> ISSUE: 1.90/1.385: Fix memcache issue with assessment generation

src/ggrc_workflows/assets/javascripts/models/workflow.js
Subject: The app doesn't redirect user to Setup tab after WF creation
Details: 
Create a WF via LHN
Actual Result:  The app doesn't redirect user to Setup tab after WF creation
Expected Result:  The app should redirect user to Setup tab after WF creation
Workaround: refresh the page
=> ISSUE-1.369 Workflow should redirect to setup tab after creation

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
**Subject**: wrong validation message when hovering Complete button on Assessment info panel
**Details**: 
- Navigate to Assessment with mandatory and empty CA  
- Hover over Complete button
**Actual Result**: The message says there are many fields mentioned in the tooltip though the assessment has only 3 CA fields marked as mandatory on info panel
**Expected Result**: EITHER only mandatory fields should be shown in the tooltip message upon hovering the Complete button OR the fields should be marked as mandatory in Info panel
=> ISSUE-1.394 Wrong validation message when hovering Complete button

src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
_(section 2, bug 1.395 - P1)_
This PR fixes the jumpy UI behavior which can be very distracting for the users. The issue seems to be caused by the `display: flex` CSS styling of the mapped objects list container. The behaviour was first observed [here](https://github.com/google/ggrc-core/commit/9650baa7b8539cfcc634eafee395166a2b9cd916).
@andrei-karalionak - the fix seems to work fine, but are there any additional implications of removing  the `flex` display rule?
- Navigate to Assessments tab on Audit page
- Open Assessment’s info panel
- Change the size of the info panel
- Hover few times over any CA fields in the info panel (make sure that the info panel's vertical scrollbar is _not_ position at the very top.
the whole info panel flicks (see …
=> ISSUE-1.395 Fix info panel flickering when hovering over CAs

src/ggrc/models/custom_attribute_definition.py, test/integration/ggrc/models/test_cad.py
Editing global custom attribute definitions must allow titles to stay
the same.
=> ISSUE-1.401 Fix modifying global CAD

src/ggrc/assets/javascripts/controllers/modals_controller.js
**Subject:** Script error "Uncaught TypeError: Cannot read property '0' of null" appears when deleting a request from audit
**Details:** 
Navigate to Requests tab on audit page and open Request’s info panel
Click 3bbs button → Edit
Click Delete button on Edit modal then confirm deletion
_Actual Result:_ Script error "Uncaught TypeError: Cannot read property '0' of null" appears when deleting a request from audit
_Expected Result:_ no errors should appear upon Requests deletion
_Workaround:_ na
=> ISSUE-1.412 Fix script error when deleting a request from audit

src/ggrc/assets/stylesheets/components/custom-attributes/_custom-attributes.scss, src/ggrc/assets/stylesheets/modules/_assessment.scss
1.409  Bug (P0)
Subject: Long CA fields' labels should be wrapped on info panels
Details: 
Give a long title to a CA field (eg 50-70 characters)
Create an object with this CA
Open object’s info panel
Actual Result: long CA fields titles overlap
Expected Result: titles shouldn’t overlap
=> QUICK-FIX Add Wrap Behavior for Custom Attributes Titles

src/ggrc/converters/query_helper.py, test/integration/ggrc/services/test_query.py
This PR enables searching by `text_search` to use the fulltext index, not just `LIKE` by every possible field on a model.
To use it, type some text without a field name into the search field, like `"some value"` (in contrast to `title = "some value"`). It should search for `"some value"` in every indexed field, like `title`, `notes`, `description` and every local and global CA.
=> QUICK-FIX Use fulltext index for text search

src/ggrc/assets/javascripts/controllers/modals_controller.js
**1.389  Bug (P0)**
**Subject**: Global custom attributes aren’t shown when creating a new object
**Details**: 
Create a new object of the obj. type that has global custom attribute
_Actual Result_: Global custom attributes aren’t shown when creating a new object until object is created and its info panel is opened
_Expected Result_: To be discussed
_Workaround_: N/A
=> ISSUE-1.389 Fix showing CAD on create/edit modal

src/ggrc/assets/javascripts/bootstrap/modal-ajax.js, src/ggrc/assets/mustache/base_objects/edit_object_link.mustache
_(section 2, bug 1.410 - P0)_
This PR fixes a script error that can happen in some cases when saving an object through the add/edit modal. It also adds a "fire alarm" (i.e. a user warning) in case the cause of the issue (changed DOM attributes) happens again.
Sadly, skipping tests here in light of the current situation ( :/  ), as this needs to be merged **today**.
- Log as admin
- Create an Audit > Navigate to Audit page
- Create an Assessment (note: this also applies to other object types)
- Navigate to Assessment’s Info panel->Click 3 bb’s button -> Select Edit Assessment
- Click [x] button-> Click Cancel in Discard Changes window
- Click Save and Close button
_""Uncaught TypeError: Cannot read property 'replace' of …
=> ISSUE-1.410 Fix modal script error

src/ggrc/converters/query_helper.py, test/integration/ggrc/services/test_query.py
This PR enables sorting by owners. ATM it does only sorting by the first owner assigned if several owners present.
To sort by owners, add this to a query: `"order_by": [{"name": "owners"}]`. You can add `"desc": true` inside that `"order_by"` item to reverse the sorting order.
There are no tests for this functionality yet.
=> QUICK-FIX Order by owner

src/ggrc/converters/handlers/handlers.py, src/ggrc/models/request.py, test/integration/ggrc/converters/test_csvs/request_with_warnings_and_errors.csv, test/integration/ggrc/converters/test_import_requests.py, test/unit/ggrc/converters/handlers/test_date_column_handler.py
_(section 2, issue 1.357  - P1)_
This PR changes the way the empty dates are interpreted by default on import (no longer converted to the current date) in  order to make them consistent with the Assessment add/edit modal.
It does, on the other hand, set default values for the required date fields on the `Request` model. As per an offline discussion, setting them independently from each other is fine, even though the result might not be what the user might expect - but that is considered a user error, and it is his/her responsibility to provide values for those required fields in the first place.
**Details:**
- Create assessment
- Export it to CSV file
- Ensure that Due On date is empty
- Import CSV file
Finished, Verified, Due On dates are populated with current date …
=> ISSUE-1.357 Do not set current date as default on import

src/ggrc/assets/stylesheets/modules/_object-header.scss
Fixes regression from #4407 on Admin panel. Three dot menu couldn't be clicked because of z-index.
=> ISSUE-1.3 Fix tier info dropdown z-index

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
**1.415  Bug (P0)**
**Subject**: Filtering doesn’t work at controls tab on the all objects page
**Details**: 
Navigate to Controls tab on All object page 
Filter controls by visible fields (by owner like example) 
Click Filter button
_Actual Result_: the app doesn’t filter records
_Expected Result_: records should be filtered according to filtering criteria correctly
_Workaround_: N/A
=> ISSUE-1.415 Fix filter on All Objects page

src/ggrc/assets/javascripts/models/assessment.js
*Subject:*
the Control isn't show in the Assessment's info tab after Assessment creation
*Details:*
- Navigate to audit page
- Create an assessment manually
- Open Assessment’s info panel
*Actual Result:*
the Control isn't show in the Assessment's info tab after Assessment creation
the Control should be show in the Assessment's info tab after Assessment creation
*Workaround:*
page refresh
=> ISSUE-1.335 Fix Assessment related objects creation

src/ggrc_workflows/models/task_group.py, test/unit/ggrc_workflows/models/test_task_group.py
**Bug 1.99:** Cloned WF TG doesn't have assignee assigned after cloning
**Details:**
•	Create a WF with the task group (TG)
•	Click 3bbs button in TG’s info panel
•	Select clone
•	Uncheck “Also clone the People in this Task Group”
•	Click “Proceed”
**Actual Result:** the task group is created without an assignee.
**Expected Result:**  the task groups should be cloned with WF manager as assignee
**Workaround:** n/a
=> ISSUE-1.99: Assign assignee to cloned WF TG

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/ggrc_base.js, src/ggrc/assets/javascripts/models/join_models.js, src/ggrc/assets/javascripts/mustache_helper.js
**1.420  Bug (P0)**
**Subject**: "Uncaught TypeError: Cannot read property 'status' of undefined" occurs while adding Assessor in New Assessment window 
**Details**: 
Create  an Audit
While Creating Assessment select Assessor (other than Creator) from drop down list: confirm that JS error occurs in console
_Actual Result_: "Uncaught TypeError: Cannot read property 'status' of undefined" occurs while adding Assessor in New Assessment window 
_Expected Result_: No error displayed. Assessor should be added to Assessment.
=> ISSUE-1.420 Fix error notification

src/ggrc/assets/javascripts/components/rich_text/rich_text.js, src/ggrc/assets/mustache/components/assessment/comment/input.mustache
**Subject**: Carriage returns removed for Comments
Create program and audit
Go to audit page and create assessment
Open created assessment in tree info and comments with 2 lines and click Add button
**Actual Result**: 2 lines joined into 1 line
**Expected Result**: Format of lines in view comment control should be the same as in edit comment control. Rich Text should be in all places where comment is entered/ edited.
**Additionaly** in current rich-text component there's no placeholder implementation.
=> ISSUE-1.183 Carriage returns removed for Comments

src/ggrc/assets/javascripts/components/assessment/add_comment.js
When we changed the textarea into a rich text field we also changed how
we get value from the element. The rich text field requires the text()
function instead of the val().
=> Fix comment required dialog

src/ggrc/assets/mustache/access_groups/modal_content.mustache, src/ggrc/assets/mustache/assessments/modal_content.mustache, src/ggrc/assets/mustache/audits/modal_content.mustache, src/ggrc/assets/mustache/base_templates/effective_dates.mustache, src/ggrc/assets/mustache/base_templates/people_list.mustache, src/ggrc/assets/mustache/clauses/modal_content.mustache, src/ggrc/assets/mustache/contracts/modal_content.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache, src/ggrc/assets/mustache/data_assets/modal_content.mustache, src/ggrc/assets/mustache/facilities/modal_content.mustache, src/ggrc/assets/mustache/issues/modal_content.mustache, src/ggrc/assets/mustache/markets/modal_content.mustache, src/ggrc/assets/mustache/objectives/modal_content.mustache, src/ggrc/assets/mustache/org_groups/modal_content.mustache, src/ggrc/assets/mustache/policies/modal_content.mustache, src/ggrc/assets/mustache/processes/modal_content.mustache, src/ggrc/assets/mustache/products/modal_content.mustache, src/ggrc/assets/mustache/programs/modal_content.mustache, src/ggrc/assets/mustache/projects/modal_content.mustache, src/ggrc/assets/mustache/regulations/modal_content.mustache, src/ggrc/assets/mustache/sections/modal_content.mustache, src/ggrc/assets/mustache/standards/modal_content.mustache, src/ggrc/assets/mustache/systems/modal_content.mustache, src/ggrc/assets/mustache/vendors/modal_content.mustache, src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache, src/ggrc_risks/assets/mustache/risks/modal_content.mustache, src/ggrc_risks/assets/mustache/threats/modal_content.mustache
**Subject:** Not all optional fields are displayed New Audit modal window by default
**Details:** 
Login under your account
Open New Modal window for program/audit/etc. from LHN menu
Click Hide all optional fields
Enter required data and save modal window
Open New Modal window once again and check displayed fields
**Actual Result:** Not all fields are displayed in modal window.
**Expected Result:** By default all fields (required and optional) should be displayed or application should remember user choices and display only required fields only
**Workaround:** click show all optional fields
=> ISSUE-1.89 Not all optional fields are displayed in New entity modal window by default

src/ggrc/converters/query_helper.py
In order not to make additional query for the total (query.count) in case when limit start greater than end - return 400 error.
=> QUICK-FIX Fix limit start greater than end

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
_(section 2, bug 1.432 - P0)_
This PR fixes a script error that occurs in the tree view when loading Workflow Task Groups that had a task deleted from them.
The cause was that that in these cases [resolving a deferred](https://github.com/google/ggrc-core/blob/develop/src/ggrc/assets/javascripts/controllers/tree_view_controller.js#L1840) failed because the deferred is, for some reason, [deleted first](https://github.com/google/ggrc-core/blob/develop/src/ggrc/assets/javascripts/controllers/tree_view_controller.js#L1675). Adding a simple check like the one just a [few lines above](https://github.com/google/ggrc-core/blob/develop/src/ggrc/assets/javascripts/controllers/tree_view_controller.js#L1823) did the trick.
I noticed that it is not possible to end a cycle without any tasks (the button …
=> ISSUE-1.432 Fix loading Cycles in tree view with deleted Tasks

src/ggrc/assets/javascripts/mustache_helper.js
**1.428  Bug (P0)**
**Subject**: "Uncaught TypeError: Cannot read property 'custom_attribute_id' of undefined" error occurs while setting visible fields for Assessment 
**Details**: 
Log as Admin
Go to Admin Dashboard -> CA
Go to Assessments-> Create several Global CA (e.g. first: “name” - Rich text type, second: “name1” - dropdown type with values)
Create an Audit> Go to Audit page
Create Assessment
Select Global CA fields in Set visible fields for Assessment widow> Set fields
_Actual Result_: "Uncaught TypeError: Cannot read property 'custom_attribute_id' of undefined" error occurs while setting visible fields for Assessment 
_Expected Result_: No error displayed. Should be the possibility to set visible fields. The title of Visible fields are displayed above …
=> ISSUE-1.428 Fix get_custom_attr_value helper

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_import_helpers.py
We do not support deleting of users and that column should not exist in
the csv template.
Issue 449 on MIT.
=> QUICK-FIX Remove delete column from Person csv template

src/ggrc/assets/mustache/people/object_list.mustache, src/ggrc/assets/mustache/people/tree.mustache, src/ggrc/assets/mustache/search/advanced_search_option_items.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_list.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache, src/ggrc_workflows/assets/mustache/selectors/object_selector_option_items.mustache
_(section 2, issue 1.399 - P1)_
This PR fixes an issue that caused the user's email to not be rendered if that user's username was not empty.
In general we prefer displaying a username over an an email (if the former exists), but this does not make sense in grid views where there is a dedicated `email` column. The PR fixes the problem both on the admin panel, and at a few other places where `grep` found the problematic pattern in the templates.
It might be the case that this fix either missed some of the occurrences (due to e.g. a different markup), or overzealously "fixed" this in places where it actually shouldn't have - if so, please let me know.
- Navigate to Admin Dashboard
- Click to People tab
- Click + to Add person
- Enter Email in New Person window> Save …
=> ISSUE-1.399 Display user's email even if name is not empty

src/ggrc/assets/javascripts/components/relevant_filters.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/plugins/autocomplete.js, src/ggrc/assets/mustache/base_objects/autocomplete_result.mustache, src/ggrc/assets/mustache/import_export/export.mustache, src/ggrc/assets/mustache/mapper/relevant_filter.mustache
**Subject:** Script error "Uncaught can.view: No template or empty template:/static/mustache/cycles/modal_content.mustache" appears when creating a new cycle while exporting data from the app
**Details:** 
- Log as Admin
- Navigate to Export page
- Click “+ Add New Rule” in FILTER BY MAPPING section
- Select Cycle in the dropdown
- at the bottom of the autocompletion list click “Create new” 
**Actual Result:** Script error "Uncaught can.view: No template or empty template:/static/mustache/cycles/modal_content.mustache" appears 
**Expected Result:** no errors should appear. I believe the  “Create new” option should be removed from the export page for all types of the objects, since there is no need in object creation when exporting.
**Workaround:** na
=> ISSUE-1.426 Remove creation new item in list in export page

src/ggrc/converters/query_helper.py
This PR adds a special case for counting `total` without a DB query if fetched result set is smaller than `page_size` (@egorhm already tried to implement this optimization in #4440).
=> QUICK-FIX Add a special case for total

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
**Subject**: "Uncaught TypeError: Cannot read property 'findInCacheById' of undefined" error occurs while clicking Create new Risk/Threats in unified mapper window at My Work page
**Details**: 
- Log as admin
- Go to My work page
- Go to Risk/Threats tab
- Click + to map Risk/Threats to person
- Click +Create New: confirm that an error is displayed
**Actual Result**: "Uncaught TypeError: Cannot read property 'findInCacheById' of undefined" error occurs while clicking Create new Risk/Threats in unified mapper window at My Work page
**Notes**: Related issues: 424, 430. 
Expected result: [+ Map Risks/Threats to this person] buttons should not exist at Risks/Threats tabs at My Work page
=> ISSUE-1.423 Uncaught TypeError: Cannot read property 'findInCacheById' of undefined

src/ggrc/converters/query_helper.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
This PR fixes the code so that a warning from SQLAlchemy "IN-predicate was called with an empty sequence" mentioned in #4455 that is raised in case when the filter should return an empty result set no longer appears.
Doing the filter like `ids = query_for_ids.all() ; id.in_(ids)` is slightly faster than doing it like `id.in_(query_for_ids)`. This difference increases with the size of the result set.
=> QUICK-FIX Fix SQLAlchemy warning in similar filter

src/ggrc/models/reflection.py
**1.435  Issue (P1)**
**Subject:** AR: custom attribute with a non ascii character causes an data issue
**Details:** 
- Create custom attribute with non ASCII character in title
- Click on Data export menu item
**Actual result:** Stack trace on the screen and in console.
**Expected result:** Export page should be opened.
=> ISSUE-1.435: Add custom attribute's nonASCII characters support

src/ggrc/converters/query_helper.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
This PR fixes a minor issue with the similarity mechanism in Query API.
1. POST two queries in a single request: the first of query does a filter by similarity, the second one does sorting by similarity without filtering.
Expected result: HTTP 400 should be returned (as the second query is invalid).
Actual result: Two result sets are returned, the second one can have some sorting applied.
This case is covered in an integration test in this PR.
=> QUICK-FIX Clear similarity filter query

src/ggrc/models/mixins/with_similarity_score.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
This PR adds a special case to the similarity computation code for Requests as the Request model is mapped to Audit model with a foreign key, not through Relationship objects.
=> QUICK-FIX Fix similar requests query

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**1.433  Bug (P0)**
**Subject**: KC: Newly mapped/created object aren't shown in the tree view (refresh needed)
**Details**: 
Create a new program object
Open a tab in HNB (eg Controls)
Create a new control
_Actual Result_: Newly mapped/created object aren't shown in the tree view
_Expected Result_: Newly mapped/created object should be shown in the tree view
_Workaround_: refresh the page
**NOTE**: I listen changes on parent instance, because some part of objects after the change it trigger the `change` event on `related_source` and `related_destinations` arrays, and the rest trigger `property name` event, in my opinion that it because of that we recreate arrays, but I need time for investigate this issue and make code analysis. It is fast fix for release and I've created issue in Post …
=> ISSUE-1.433 Fix refresh tree view after create/map object

src/ggrc/assets/javascripts/bootstrap/modal-form.js
**1.437  Bug (P0)**
**Subject:** "Uncaught can.Map: Object does not exist" occurs after saving an Objective with the already existent title 
**Details:** 
Log as Admin
Go to LHN
Create an Objective
Navigate to Objective’s Info pane> Click 3 bb’s button to Edit objective.
Enter description
Click [x] button to close the window
Click  Discard
Enter already existent title > Save and Close
**Actual Result**: "Uncaught can.Map: Object does not exist" occurs after saving an Objective with the already existent title 
**Expected Result**: No error displayed. “The value 'no xxxx' is already used for another title; title values must be unique” message should be exist (as example).
=> QUICK-FIX-1.437 "Uncaught can.Map: Object does not exist"

src/ggrc/assets/javascripts/apps/custom_attributes.js, src/ggrc/assets/javascripts/components/inline_edit/inline.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/business_object_models.js, src/ggrc/assets/javascripts/models/control.js, src/ggrc/assets/javascripts/models/directive_models.js, src/ggrc/assets/javascripts/models/issue.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/models/person.js, src/ggrc/assets/javascripts/models/section.js, src/ggrc/assets/javascripts/models/simple_models.js, src/ggrc/assets/javascripts/models/system.js, src/ggrc/assets/mustache/custom_attributes/info.mustache, src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js, src/ggrc_risks/assets/javascripts/models/risk.js, src/ggrc_risks/assets/javascripts/models/threat.js, src/ggrc_workflows/assets/javascripts/models/workflow.js
**1.438  Bug (P0)**
**Subject**: CA field with dropdown type is shown as rich text and CA filed with rich text is shown as dropdown in Workflow's Info pane after edit   
**Details**: 
Create a Workflow
Go to Workflow Info page
Navigate to Workflow's Info pane
Edit any CA (e.g. MY_TITLE4 ): CA looks like rich text instead of chekbox. 
_Actual Result_: Mandatory CA field with dropdown type is shown as rich text and CA filed with rich text is shown as dropdown in Workflow's Info pane  
_Expected Result_: CA fields are displayed according to Attribute type  
_Workaround_: NA
**Note**: check all the CA fields according to Attribute type
=> ISSUE-1.438 Fix mix CA after edit

src/ggrc/converters/base_block.py, src/ggrc/converters/errors.py
Issue 1.445 is hot fix for Quince v3. In Raspberry app should
support import objects with multibyte custom attributes titles.
As we discussed with @akhilp1 on 09/28/2016 evening offline.
**1.445  Bug (P2)**
**Subject:** Incorrect error message occurs while importing an object with CA title that contains non ASCII characters
**Details:** 
- Log in as Admin 
- Go to Admin Dashboard-> Custom Attributes 
- Create CA for WF with Non ASCII characters in title
- Create WF1
- Export the created WF
- Edit CSV file: remove CODE and rename WF1 (e.g. WF2)
- Import CSV file
**Actual Result:** Incorrect error message occurs while importing an object with CA title that contains non ASCII characters
**Expected Result:** Correct error message occurs (e.g.): “Non ASCII characters forbidden while importing”
=> ISSUE1.445: Fix multibyte characters error message

src/ggrc/models/mixins/autostatuschangeable.py, test/integration/ggrc/models/mixins/test_autostatuschangable.py
This makes the objects like Assessment to automatically transition to the "In Progress" state on edit even when they are in a DONE state (or in any of the FINAL states, as before).
This PR is closely related to the [other PR](https://github.com/google/ggrc-core/pull/4473) that adresses automatic state transitioning, but it fixes a different cause of the problem.
To reproduce, open a Statusable object (e.g. an Assessment), put it into a DONE (but not FINAL) state, e.g. the "Ready to Review" state. Then modify a custom attribute on that Assessment's info panel, and the Assessment does not go into the "In Progress" state automatically (and does after the fix).
The test will be added in a follow-up pull request that will also add the state transition confirmation dialog. 
**Edit:** Well, it …
=> QUICK-FIX Enable auto state transition for all DONE states

src/ggrc/models/assessment.py, src/ggrc/models/object_document.py, src/ggrc/models/request.py
Bug description:
> Subject: add the hint explaining what should be put into Evidence column in CSV Request/Assessment template
> Details: 
> Download CSV import template
> Actual Result: Evidence column title doesn’t contain explanation what should be 
> Expected Result: users should have the hint how to field fields properly
These descriptions are duplicated because of improper use of
documentable mixin, where the descriptions would otherwise belong.
=> ISSUE-1.364 Add URL and evidence descriptions to CSV templates

src/ggrc/assets/javascripts/components/assessment_generator.js
1.453  Bug (P0)
Subject: "Uncaught TypeError: Cannot read property 'serialize' of undefined" error occurs while generating Assessment Mapped to Control 
Details: 
Go to audit page-> Create Control->Create Assessment template 
Go to Assessment tab-> Click Generate Assessment
Select created Assessment template
Select Mapped to Control in FILTER BY MAPPING section
Search-> Select Control from the search list (e.g. 1 test control dfdf)
Click Generate Assessment: an error occurs
The link: https://grc-test.appspot.com/audits/53#assessment_widget
Actual Result: "Uncaught TypeError: Cannot read property 'serialize' of undefined" error occurs while generating Assessment Mapped to Control  
Expected Result: No error displayed. Assessment Mapped to Control should be …
=> ISSUE-1.453 "Uncaught TypeError: Cannot read property 'serialize' of undefined" error occurs while generating Assessment Mapped to Control

src/ggrc/models/mixins/autostatuschangeable.py
This is a follow-up on #4483, updating the docstring to more accurately reflect what the `AutoStatusChangeable` mixin does.
=> QUICK-FIX Improve the AutoStatusChangeable mixin's docstring

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**Subject**: Script error "Uncaught TypeError: Cannot read property 'top' of undefined" appears after deleting an object that is mapped to an Assessment
**Details**: 
- Navigate to assessments tab on audit page 
- Open assessment’s 2nd tier with mapped objects
- Click on mapped object’s 1st tier to open its info panel
- Click 3bbs button and select delete button
- Confirm deletion
**Actual Result**: Script error "Uncaught TypeError: Cannot read property 'top' of undefined" appears after deleting an object that is mapped to an Assessment
**Expected Result**: no errors!
=> ISSUE-1.449 "Uncaught TypeError: Cannot read property 'top' of undefined"

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
1.396  Bug (P1)
Subject: Objects' titles aren't shown immediately after adding them into Controls and 
RELATED INFORMATION sections on Assessment's info panel
Details: 
Navigate to Assessments tab on Audit page
Open assessment’s info panel
Map a control using (+) button in controls section on the info panel (or map any object in 
RELATED INFORMATION via the same (+) button)
Actual Result: Objects' titles aren't shown immediately after adding them
Expected Result: Objects' titles should be shown immediately after adding them
=> ISSUE-1.396 Objects' titles aren't shown immediately after adding them into Controls and  RELATED INFORMATION sections on Assessment's info panel

src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js
1. Navigate to a program page.
2. Open "Controls" tab.
3. Click "map" plus button if the mapper does not open automatically.
4. In the mapper, click "Create new control".
5. Fill in the form, click "save". (the new control is displayed in the result list)
6. Scroll the list down.
Expected result: Nothing happens as there is only one item in the list, there is nowhere to scroll.
Actual result: The new control is duplicated.
The bug occures because the method `drawPage` that is triggered on scrolling event tries to refresh items in `this.scope.entries[this.scope.page*20, (this.scope.page+1)*20]` and append them to the list that is rendered. Since `this.scope.page` is initialized to `0` and is not updated on new control creation, items from `this.scope.entries[0, 20]` are …
=> QUICK-FIX Duplicate item in unified mapper

src/ggrc/assets/javascripts/components/relevant_filters.js
P2
**Subject**: "Audit" is missing in object type dropdown on Export page
**Details**: 
Create assessment object
Click icon to export assessments
**Actual Result**: "Audit” is missing in object type dropdown on Export page
**Expected Result**: Object type dropdown should contain “Audit”
**Workaround**: N/A
=> ISSUE-1.116 "Audit" is missing in object type dropdown on Export page

src/ggrc/assets/javascripts/plugins/autocomplete.js
**Subject**: "Uncaught TypeError: Cannot read property 'appendChild' of null" error occurs when scrolling objects in drop down menu at Export Objects page 
**Details**: 
- Log as Admin 
- Go to Data Export page
- Click “+ Add New Rule” in FILTER BY MAPPING section
- Select an object (e.g. Assessment, Workflow, Access Group) in the dropdown menu
- Type in field the first letter and scroll the created objects: error occurs
**Actual Result**: "Uncaught TypeError: Cannot read property 'appendChild' of null" error occurs when scrolling objects in drop down menu at Export Objects page 
**Expected Result**: No error displayed. 
**Note**: bug is reproduced temporary
**Trace**:
```
dashboard.js:26043 TypeError: Cannot read property 'appendChild' of null
at Object.can.appendChild …
```
=> ISSUE-1.443 Uncaught TypeError: Cannot read property 'appendChild' of null

src/ggrc/assets/javascripts/components/sort_by_sort_index/sort_by_sort_index.js, src/ggrc_workflows/assets/mustache/task_groups/info.mustache
**1.446  Bug (P1)**
**Subject**: Tasks are not ordered by date in Task Group Info pane
**Details**: 
Create WF
Go to Setup tab
Create Task Group
Navigate to Task Group Info pane
Create Tasks with different titles, assignees and dates (e.g. 10 tasks)
Go to another tab and return to Task Group Info pane once again
Look at the created tasks: confirm tasks are not sorted alphabetically
_Actual Result_: Tasks are not ordered by date in Task Group Info pane
_Expected Result_: Tasks should be ordered by date in Task Group Info pane
=> ISSUE-1.446 Change sort rule for list of tasks

src/ggrc/assets/mustache/base_templates/people_list.mustache
**Subject**: KC: LHN tooltip says "Assignee and Verifier cannot be the same person!" when hovering over an Assessment in LHN though the assessment has Assessor instead of Assignee, error message for blank Assessor (Assignee is required)
**Details**:
- Go to LHN
- Open Assessment’s accordion
- Hover over an Assessment with Assessor such as Verifier: confirm Assignee and Verifier cannot be the same person! message is displayed
**Actual Result**: KC: LHN tooltip says "Assignee and Verifier cannot be the same person!" when hovering over an Assessment in LHN though the assessment has Assessor instead of Assignee, error message for blank Assessor (Assignee is required)
**Expected Result**: Assessor and Verifier cannot be the same person! message is displayed
=> ISSUE-1.473 Change a warning message for Assessments

src/ggrc/assets/javascripts/bootstrap/modal-form.js
**1.447  Bug (P2)**
Subject: Program page is displayed after edit Assessment in Audit tab
**Details:** 
Create a Program
Go to Audit page and create an Assessment
Go to Program page-> Audit page
Navigate to first tree vier tier-> Click grey triangle
Select Assessment-> Navigate to Assessment’s Info pane-> click 3 bb’s button->Edit Assessment
Click [x] in Edit Assessment’s window-> Click Discard: confirm that the app. redirects to Program tab
**Actual Result:** Program page is displayed after edit Assessment in Audit tab
**Expected Result:** Audit tab should be displayed after adit Assessment
=> ISSUE-1.447 Program page is displayed after edit Assessment

src/ggrc/converters/handlers/custom_attribute.py
Since we're storing CA values for all definitions even if the value has
not been set, we should support exporting empty person CA.
This is a data issue and not a filter issue as the bug description says.
P0 issue not in issue finder:
> Error appeared after a try to export all assessments using "GLOBAL CA"= 3 as a filter
Please note that this is just a bugfix and the whole get_value needs to be refactored as part of performance tickets for raspberry.
=> QUICK FK Fix export with empty person CA

src/ggrc/converters/handlers/boolean.py, src/ggrc/converters/handlers/handlers.py, src/ggrc/models/control.py
**P0 for V4**
bug description:
> Subject: the app says that Significance column contains invalid data if "True" and "False" is used though the app exports values "True" and "False" for existing controls objects
> Details: 
> Navigate to export page
> Export 3 controls with different values for Significance field
> Reimport csv file you’ve just exported
> Actual Result: the app says that Significance column contains invalid data
> Expected Result: data should be ok, we’ve just exported them
> Workaround: NA
>
=> ISSUE-1.455 Fix control export

src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/join_models.js, src/ggrc/assets/javascripts/models/mappers/tree-page-loader.js
**Subject:** URBAN: cannot unmap a person from WF
**Details:** 
- Create Workflow
- Go to People tab at Workflow Info page
- Click + to map Person to this WF (e.g. reader@reciprocitylabs.com)
- Navigate to Person’s Info panel> Click 3 bb’s button
- Click Unmap: Person is not unmapped
**Actual Result:** cannot unmap a person from WF
**Expected Result:** person should be unmapped from WF
=> 1.440 Fix unmap person from workflow

src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
The fields that must be filled in before save button is enabled must
have the proper required red star next to them.
=> Add required flag to task start and end dates

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/assessments/related_issues.mustache, src/ggrc/assets/mustache/assessments/related_requests.mustache, src/ggrc/assets/mustache/requests/related-requests.mustache, src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
This PR should fix these 2 bugs: 
1.463  Bug (P2)
Subject: Created Requests are not shown at Related Requests tab in Assessment's Info pane
Details: 
Create an Audit
Create Assessment
Navigate to Assessment’s Info pane
Go to Related Requests tab
Click Create Request button to Create Request
Look at Related Requests tab: newly created request is not shown
Actual Result: Created Requests after are shown at Related Requests tab in Assessment's Info pane
Expected Result: Requests after creating are shown at Related Requests tab in Assessment's Info pane
Workaround: refresh is needed
1.464  Bug (P2)
Subject: The second and the next created Issues are not shown at Related Issues tab in Assessment's Info pane
Details: 
Create an Audit
Go to …
=> QUICK-FIX Add correct behaviour after adding Related Issues/Requests 

src/ggrc/assets/javascripts/components/assessment/inline.js, src/ggrc/assets/javascripts/components/ca-object/ca-object-value-mapper.js, src/ggrc/assets/javascripts/components/rich_text/rich_text.js
1.425  Bug (P1)
Subject: Spaces are considered to be a value in mandatory CA fields
Details: 
Navigate to Assessments tab on audit page
Open Assessment’s info panel and enter spaces into mandatory field
Actual Result: the app accepts spaces as actual value and allows to complete the Assessment
Expected Result: spaces shouldn’t be considered as a value in mandatory text fields
Workaround: na
=> ISSUE-1.425 Fix issue with empty values for Rich Text and Text Inputs

src/ggrc/assets/javascripts/components/assessment/inline.js, src/ggrc/assets/javascripts/components/inline_edit/inline.js, src/ggrc/assets/javascripts/components/inline_edit/tests/inline_edit_spec.js, src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/models/tests/autoStatusChangeable_mixin_spec.js, src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache, src/ggrc/assets/mustache/custom_attributes/info.mustache
This is a follow-up on #4473. It adds a confirmation dialog about automatic state transition when editing a custom attribute on Assessment's/Request's info pane (note - to see it in action, the Assessment/Request object must **not** be in the _"In Progress"_ state).
If you can, please review this with a bit higher priority, I only have time to apply any needed changes tomorrow (but even that is not guaranteed).
A couple of notes:
- We have two separate implementations of the inline-edit widget component (Assessments use their own implementation). I did not have time to refactor and unify these two components, thus duplicating the `enableEdit()` method. We should nevertheless make the unification after the release.
- In the modal dialog, the Confirm/Cancel buttons are colored red and …
=> QUICK-FIX Confirm status change on edit

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js
The filter keys and mappings were used for accessing object properties
on the frontend by the Javascript filters. Since these filters are now
done with the query API, these variables aren't used anymore. The code
that used them was removed in one of the previous commits but these were
forgotten.
This is cleaning up dead code after this PR: https://github.com/google/ggrc-core/pull/4505
=> QUICK-FIX Remove legacy code

src/ggrc/assets/mustache/custom_attributes/info.mustache
Other objects don't have the needed handler which resulted
in a script error. We ignore assessments here because those
are handled by assessment/custom-attributes.mustache.
=> Make sure confirmBeginEdit event is only fired for Requests

src/ggrc/fulltext/recordbuilder.py, src/ggrc/fulltext/sql.py
Filtering by Map:Person CAV is not functional.
1. On the dashboard open a tab with objects that have Person-type CA (you may have to define a new CA).
2. Set that CA value to "user@example.com" in one of the objects.
3. (for a CA titled CA_PERSON): type `CA_PERSON ~ "user@example.com"` into the filter, press enter.
Expected results: the object edited in step 2 is shown.
Actual results: an empty list is shown.
This PR adds the name and the email of a person to the fulltext index that is used to search by CA values. You may need to do a reindex to make these changes work on every Person-type CA in the system.
=> ISSUE-1.465 Index Map:Person CAV

src/ggrc/fulltext/sql.py
This PR fixes an issue where every fulltext index entry for an objects gets removed on a CA update.
1. Open info pane of an object with at least two CA defined (say, text fields CA1 and CA2, but their names and values do not matter).
2. Set CA1 to "hello".
3. Enter `CA1 = "hello"` in the filter, press enter. The edited object should be shown in the tree view.
4. Set CA2 to "break the index".
5. Enter `CA1 = "hello"` again in the filter, press enter.
Expected result: the same edited object is shown in the tree view.
Actual result: the edited object is not shown (but CA1 has still value "hello" stored).
You may need to force reindex to make sure the broken index records are recreated.
=> QUICK-FIX Fix updating fulltext index for CA

src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-item.js, src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-list.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/components/reusable-objects/reusable-objects-item.mustache, src/ggrc/assets/mustache/requests/related-requests.mustache
1.416  Bug (P1)
Subject: Checkbox for Reuse evidences is still available for already reused evidences at Related Assessment tab in Assessment's Info panel 
Details: 
Go to audit page
Create Assessment > Navigate to Info panel and attach an evidence
Create second Assessment> Navigate to Info panel>go to Related assessments tab> Reuse the above mentioned evidence to Assessment
Create third Assessment-> Navigate to Info panel-> Go to Related assessments tab> Reuse the above mentioned evidence to Assessment
Actual Result: Checkbox for Reuse evidences is still available for already reused evidences at Related Assessment tab in Assessment's Info panel 
Expected Result: Checkbox for Reuse evidences should be disabled for already reused evidences at Related …
=> ISSUE-1.416 Checkbox for Reuse evidences is still available for already reused evidences at Related Assessment tab in Assessment's Info panel

src/ggrc/assets/javascripts/models/mappers/tree-page-loader.js, src/ggrc/assets/javascripts/models/person.js
**1.471  Bug (P0)**
**Subject**: No Access AUTHORIZATIONS is displayed as default and is not changed to another program roles
**Details**:
Go to People tab: confirm No Access role is displayed as default
Click + to Map Person to this program
Map selected Person
Navigate to Person’s Info pane
Click 3 bb’s button -> Edit Authorizations
Change user role -> Save
Look at Person first tree view:  Authorizations are not updated
_Actual Result_: No Access AUTHORIZATIONS is displayed as default and is not changed to another program roles
_Expected Result_: AUTHORIZATIONS should be displayed according the program roles 
Workaround: na
=> ISSUE-1.471 Show person roles in tree view

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**1.466  Bug (P0)**
**Subject**: Filter is not function for CA with Date type and 400 error is displayed in Console
**Details**: 
Log as Admin
Go to My Work page
Select Sections type in HNB
Try to Filter CA with Date type: error is displayed
_Actual Result_: Filter is not function for CA with Date type and 400 error is displayed in Console
_Expected Result_: error message to user is shown and table is not freezed
=> ISSUE-1.466 Add error handler for incorrect filter

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
**1.469  Bug (P1)**
**Subject**: User roles aren't updated on program page on people tab
**Details**:
Go to People tab
Click + to Map Person to this program
Map selected Person
Navigate to Person’s Info pane
Click 3 bb’s button -> Edit Authorizations
Change user role -> Save
Look at Person first tree view:  Authorizations are not updated
_Actual Result_: user roles aren't updated on program page on people tab
_Expected Result:_ user roles should be updated on program page on people tab
_Workaround_: na
Note: refresh can not solve the problem
=> ISSUE-1.469 Update tree page after update roles

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/assessments/related_issues.mustache, src/ggrc/assets/mustache/assessments/related_requests.mustache
1.485  Bug (P1)
Subject: Program Info page: Assessments are shown at Related Requests/Related Issues tab in Assessment's Info pane
Details:
Create an Audit
Create at least 2 Assessments
Create at least 2 Requests
Go to Program Info page
Open Assessment’s tab
Navigate to Assessment’s Info pane
Open Related Request tab: confirm Assessments are shown
Actual Result: Program Info page: Assessments are shown at Related Requests/Related Issues tab in Assessment's Info pane
Expected Result: Program Info page: Requests/Issues are shown at Related Requests/Related Issues tab in Assessment's Info pane
Workaround: NA
Note: Check for Related Issues tab following the above mentioned steps too under admin and GR roles
=> ISSUE-1.485 Program Info page: Assessments are shown at Related Requests/Related Issues tab in Assessment's Info pane

src/ggrc/assets/javascripts/models/person.js, src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
**1.469  Bug (P1)**
**Subject**: User roles aren't updated on program page on people tab
**Details**:
Go to People tab
Click + to Map Person to this program
Map selected Person
Navigate to Person’s Info pane
Click 3 bb’s button -> Edit Authorizations
Change user role -> Save
Look at Person first tree view:  Authorizations are not updated
_Actual Result_: user roles aren't updated on program page on people tab
_Expected Result:_ user roles should be updated on program page on people tab
_Workaround_: na
Note: refresh can not solve the problem
=> ISSUE-1.469 Update tree page after update roles 

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_ca_import_export.py
The import template should list possible options for dropdown custom
attribute definitions.
bug description:
> Subject: add description for the dropdown CA fields in CSV template (requests and assessments)
> Details: 
> Create a global CA dropdown field for a request / assessment
> Export CSV template
> Actual Result: dropdown field’s title is listed in CSV template but there is no dropdown items listed.
> Expected Result: show dropdown items in CSV template 
> Workaround: NA
=> ISSUE-1.361 Add description for CA dropdown fields

src/ggrc/assets/javascripts/models/person.js
Steps:
1.Create a program
2. Go to People tab: confirm No Access role is displayed as default
3. Click + to Map Person to this program
4. Map selected Person
5. Navigate to Person’s Info pane
6. Click 3 bb’s button -> Edit Authorizations
7. Change user role -> Save
8. Look at Person first tree view: Authorizations are not updated
Actual Result: No Role authorization is displayed as default and is not changed to another program roles
Expected Result: Authorization should be displayed according to the program roles
=> GGRC-57 Fix roles on people tab on program

src/ggrc/converters/query_helper.py, src/ggrc_workflows/models/relationship_helper.py
The new `related_people` filter doesn't return people mapped through `workflow_people` table.
1. Create a workflow.
2. Navigate to its people tab.
3. Map a person.
4. Refresh the page. (this step may be not needed, it is a separate frontend-side issue)
Expected result: the people counter in the tab is incremented by 1, the mapped person is shown in the list.
Actual result: the counter is incremented by 1, the mapped person is not shown in the list.
=> QUICK-FIX Fix related people for workflows

src/ggrc_workflows/__init__.py, src/ggrc_workflows/views/__init__.py, test/integration/ggrc_workflows/test_workflow_revisions.py
It fixes creating revisions for cycle tasks and related objects.
This how to reproduce the bug on local dev machine:
1. Create a weekly workflow.
2. Create a task that should start tomorrow.
3. Activate workflow.
4. Change system time on tomorrow.
5. Touch [CRON endpoint](http://localhost:8080/nightly_cron_endpoint)
6. Go to workflow active cycles - new cycle should be activated
7. Go to [event list](http://localhost:8080/admin#events_list_widget) on admin dashboard - there is no event about new cycle.
8. Execute the following query in MySQL console:
```sql
select * from revisions where resource_type = 'CycleTaskGroupObjectTask' \G
```
There is no revision for newly created cycle task.
It is also fixed SQL error in [start unstarted cycles …
=> QUICK-FIX Cycle revisions

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/assessments/related_issues.mustache, src/ggrc/assets/mustache/assessments/related_requests.mustache
**Subject:** Program Info page: Assessments are shown at Related Requests/Related Issues tab in Assessment's Info pane
**Details:**
- Create an Audit
- Go to Audit page
- Create at least 2 Assessments
- Create at least 2 Requests
- Go to Program Info page
- Open Assessment’s tab
- Navigate to Assessment’s Info pane
**Open Related Request tab:** confirm Assessments are shown
**Actual Result:** Program Info page: Assessments are shown at Related Requests/Related Issues tab in Assessment's Info pane
**Expected Result:** Program Info page: Requests/Issues are shown at Related Requests/Related Issues tab in Assessment's Info pane
**Workaround:** NA
**Note:** Check for Related Issues tab following the above-mentioned steps too under admin and GR roles
=> GGRC-29 Assessments are shown at Related Requests/Related Issues tab in Assessment's Info pane

src/ggrc/models/person.py
This makes sure that the user is logged out when they loose a system
wide role. Before this change the user was still able to access the app
until they manually logged out.
=> GGRC-5 Fix is_authenticated in person class

src/ggrc/assets/mustache/people/object_list.mustache, src/ggrc/assets/mustache/people/tree.mustache, src/ggrc/assets/mustache/search/advanced_search_option_items.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_list.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_tree.mustache, src/ggrc_workflows/assets/mustache/selectors/object_selector_option_items.mustache
**1.399  Bug (P1)**
**Subject**: Item is not displayed in the first tier in People tab while adding a person without Name
**Details**: 
Navigate to Admin Dashboard
Click to People tab
Click + to Add person
Enter Email in New Person window> Save and Close
Find the created person via filter
Look at tree view
_Actual Result_:  Item is not displayed in the first tier in People tab while adding a person without Name
_Expected Result_: Item should be displayed in the first tier in People tab
=> GGRC-16 Display user's email even if name is not empty

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_query_api_spec.js, src/ggrc_workflows/assets/javascripts/apps/workflows.js
This PR fixes the queries for "Active Cycles" and "History" tabs on Workflow info page.
1. Open the info page for Workflow with at least one active Cycle and at least one inactive Cycle.
2. Open "Active Cycles" tab.
3. Open "History" tab.
Expected result: "Active Cycles" shows only active Cycles, each row has "End Cycle" button (if the user has permissions to do so). "History" shows only inactive Cycles, no row has "End Cycle" button.
Actual result: both "Active Cycles" and "History" show the same list of Cycles which is a mix of active and inactive Cycles.
=> GGRC-37 Hide inactive cycles

src/ggrc_workflows/assets/mustache/cycle_task_entries/tree.mustache
**Subject:** [Delete comment] button is absent in Task's Info pane at Active Cycles tab
**Details:**
- Create WF
- Go to setup tab
- Navigate to Task Group’s Info pane
- Create Task
- Click Activate Workflow button
- Go to Active Cycles tab
- Click grey triangle to Navigate to second tree view-> Task’s Info pane
- Add comment
- Click gear icon to delete comment: Delete button is absent
**Actual Result:** [Delete comment] button is absent in Task's Info pane at Active Cycles tab
**Expected Result:** [Delete comment] button should be in Task's Info pane at Active Cycles tab 
Workaround: NA
=> GGRC-8 Fix displaying delete button for comments for tasks

src/ggrc/models/hooks/assessment.py
This issue caused a regression where assessment generation got broken. I have been working on a fix for this here, but I'm not sure if we want to include this fix in the release branch as well: https://github.com/google/ggrc-core/pull/4553
=> Revert "GGRC-11 Log assessment automappings"

src/ggrc/models/assessment.py, src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/hooks/assessment.py, src/ggrc/models/relationship.py
This issue was caused by PR #4451. After this PR the person object was
sometimes returning LocalProxy as the source_type when generating
assessments. This caused an error in our memcache invalidation as
LocalProxy is not a valid object type.
I have set the `value.type` as the default value for both
destination_type and source_type instead of `value.__class__.__name__`,
but because this might cause a regression, I have left this as the
default value.
Subject: Assessment generation has failed error occurs while generating Assessment Mapped to Control 
Details: 
Go to Assessment tab-> Click Generate Assessment
Select an Assessment template
Search-> Select Control from the search list (e.g. test control 002aa)
Click Generate Assessment: an error occurs
The link: …
=> GGRC-4 Fix generating assessments

src/ggrc/models/custom_attribute_definition.py, test/integration/ggrc/models/test_cad.py
Assessment template custom attribute names must not match assessment custom attribute names because it causes conflicts when generating assessments.
Create global assessment custom attribute with name "gca"
create assessment template with custom attribute named "gca"
try to create assessment using the previous template.
=> GGRC-110 Assessment cad uniqueness

test/integration/ggrc/__init__.py, test/integration/ggrc/converters/test_import_comprehensive.py, test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
This is prep work for fixing request import warnings.
This pull request will make it easier to have setup objects and the actual test objects in the same csv in different blocks.
=> QUICK-FIX Update csv tests

src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/models/tests/autoStatusChangeable_mixin_spec.js
When editing a custom attribute on a `Not Started` object, the automatic status change confirmation dialog is not wanted, and this PR fixes that.
- Create a new Assessment or Request (make sure that at least one custom attribute is defined for that object type). The object's state will be set to _"Not Started"_.
- Try to inline edit a custom attrbute on that object's info panel.
The custom attribute can be edited without any distractions.
A dialog appears asking  the user to confirm automatic status change if the CA value gets modified.
=> GGRC-170 Disable status change popup for Not Started state

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/javascripts/controllers/tests/tree_view_controller_spec.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**1.468  Bug (P1)**
**Subject**: First tree view of the Mapped Person is not shown in People's tab
**Details**:
- Go to People tab
- Click + to Map Person to this program
- Map selected Person
- Look at People tab: First tree view is not shown
**Actual Result:** First tree view of the Mapped Person to a program is not shown in People's tab
**Expected Result:** First tree view of the Mapped Person to a program is shown in People's tab
**Note:** Check the behavior for all objects at People tab
**Workaround:** refresh is needed
=> GGRC-25 Fix update tree view after map people

src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/mustache/requests/related-requests.mustache
**Subject:** "Uncaught TypeError: Cannot read property 'id' of null" occurs while cllicking on Request log/Related Requests tab
**Details:** 
- Navigate to Request’s Info pane
- Add URL
- Go to Request log/Related Requests tab
**Actual Result:** "Uncaught TypeError: Cannot read property 'id' of null" occurs while clicking on Request log/Related Requests tab
**Expected Result:** No error displayed.
**Workaround:** N/A
=> GGRC-174 "Uncaught TypeError: Cannot read property 'id' of null" occurs while cllicking on Request log/Related Requests tab

src/ggrc/builder/json.py, src/ggrc/models/custom_attribute_value.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/utils/__init__.py
This PR enables date format conversion for custom attributes: the values are stored in `YYYY-MM-DD` format in the DB, but are sent to the frontend and received back in `MM-DD-YYYY` format. It is done to avoid changes to Date CA logic on the frontend.
=> GGRC-130 Custom serializer for CA dates

src/ggrc/assets/javascripts/bootstrap/modal-form.js
This PR cherry-picks the fix done in #4478 to apply it to the Quince branch. Thanks @Smotko for the hint that this issue has already been fixed in `develop` branch!
- Log as Admin
- Go to Admin Dashboard-> Custom Attributes
- Click on grey triangle on the first tier
- Select GCA and click on Edit icon
- Make changes (e.g. in Attribute title field)
- Click on x button to close-> Discard
Redirecting to People's tab after making changes in CA on Admin Dashboard
Should not be redirecting to People's tab after making changes in CA on Admin Dashboard
=> GGRC-147 Fix auto-tab switch when dismissing CA changes

src/ggrc/migrations/versions/20161020082501_53206b20c12b_unify_ca_date_format.py
This PR fixes the format of Date-type CAVs in the DB. At the moment the formats are `MM/DD/YYYY` (set by the frontend) and `YYYY-MM-DD 00:00:00` (set by the imports some time ago).
The migration in this PR makes every date formatted as `YYYY-MM-DD`. The downgrading part of the migration reverts the formats to `MM/DD/YYYY`.
~~On hold until every other part of GGRC-34 is ready.~~
On hold until #4566 and #4579 are merged because until they are merged there is a possibility to store the data in the format this migration gets rid of.
=> GGRC-93 Add a migration to unify CA dates format

src/ggrc/converters/query_helper.py, test/integration/ggrc/converters/test_csvs/sorting_with_ca_setup.csv, test/integration/ggrc/services/test_query.py
This PR is a trimmed down version of #4535 and features just Query API specific logic for filtering by CA dates.
Steps to test:
0. Make sure you performed reindex after running the migration in #4564.
1. Open a tree view of Assessments. They should have at least one Date-type CA.
2. Try typing this into the filter (`ca_field` is the name of your Date-type CA):
- `ca_field = 2016-10-24`
- `ca_field < 2016-10-24`
- `ca_field > 2016-10-24`
- `created_at = 2016-10-24` (won't be effective as `created_at` is a datetime field, most probably nothing will match)
- `created_at < 2016-10-24`
- `created_at > 2016-10-24`
`ca_field ~ 2016` and `created_at ~ 2016` are not implemented. There is no valid case why it should be allowed (the user can do `ca_field > 12/31/2015 AND ca_field < 1/1/2017` …
=> GGRC-169 Query API CA date conversion

src/ggrc/assets/javascripts/models/join_models.js, src/ggrc/assets/javascripts/models/tests/join_models_spec.js
**Details:**
Create New Program
Create Audit
Map several controls to this Audit
Refresh page
Navigate to Control's Info pane in Audit page
Click 3bbs button and select Unmap button
**Actual result:** nothing happens
**Expected result:** Control should be unmaped from Audit and tree view should be refreshed
=> GGRC-178 Fix unmap controls from Audit

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
**Details:**
1. Open Section tab at Dashboard page
2. Filter by CA field w/datetime type with incorrect value (like example ca_date>01/01/0001)
3. Click Reset filter or apply new filter
_Actual Result_: app shows empty list
_Expected result_: app should reset filter and display actual list of entities
_Workaround_: reload page
=> GGRC-205 Fix filter after incorrect query

src/ggrc/assets/mustache/base_objects/general_info.mustache, src/ggrc/assets/stylesheets/_colors.scss, src/ggrc/assets/stylesheets/_modules.scss, src/ggrc/assets/stylesheets/modules/_snapshot.scss
=> GGRC-65 Styling for snapshot info pane

src/ggrc/assets/javascripts/bootstrap/modal-ajax.js, src/ggrc/assets/mustache/dashboard/internav_list.mustache
_(I do not have access to Jira yet, thus don't know the exact ticket number... but it's 1.506 in the old bug list document, P2)_
This PR is the same as  #4586, just opened against a correct branch. It fixes unwanted mapper modal being displayed when opening new tabs, even when the target object type is not allowed to be mapped to the current page instance(meaning, among other things, that there is also no `(+)` button in the corresponding tree view's header).
It also fixes a related issue, i.e. the 1st issue @Smotko mentioned in his [comment](https://github.com/google/ggrc-core/pull/4586#issuecomment-256341257). Now, when clicking Add... Audits in LHN on Program page, the Add Audit modal is automatically displayed.
(BTW, the `GGRC.register_modal_hook()` method had to be linted for the …
=> GGRC-139 Hide mapper modal if needed on opening People tab

src/ggrc/converters/handlers/document.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_csvs/request_full_no_warnings.csv, test/integration/ggrc/converters/test_import_requests.py
Exports should support unicode characters for all fields.
To reproduce the bug, create a request and map a document to it with a uniced character and try to export that request.
=> QUICK-FIX Fix document and URL exports

src/ggrc/models/mixins/customattributable.py
_(don't know the Jira issue number, sorry)_
This PR fixes editing AssessmentTemplates with custom attribute definitions that have an RBAC context. It assures that the context is not just a plain `dict`, but instead a full `Context` instance, preventing the ORM machinery from complaining.
BTW, if you wonder why this has not been handled by the JSON builder - the builder only de-serializes top-level attributes of our ORM models, thus e.g. `Audit.context` does get de-serialized to a `Context` instance. With AssessmentTemplates, however, the `context` is an attribute of elements in the `AssessmentTemplate.custom_attribute_defintiions` list, and the builder can't really know that it needs to de-serialize a specific "deep" attribute.
---
**Details:**
- Open Audit 1422
- Open Assessment …
=> GGRC-144 Fix updating an AssessmentTemplate with CAs

src/ggrc/converters/handlers/document.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_csvs/request_full_no_warnings.csv, test/integration/ggrc/converters/test_import_requests.py
Exports should support unicode characters for all fields.
=> Fix document and URL exports

src/ggrc/migrations/versions/20161020125620_1db61b597d2d_remove_bad_ca_names.py
This migration removes all assessment template custom attribute
definition names that match any of the assessment global custom
attributes.
Resolves: GGRC-26, GGRC-111
=> GGRC-26 Add migration for fixing bad CA names

src/ggrc/models/custom_attribute_value.py, src/ggrc/models/mixins/customattributable.py
If the CAV is being created in CustomAttributable (no value was ever stored for the CAD for the object), no date formatting is applied and the date is stored into the DB in invalid format (MM/DD/YYYY instead of YYYY-MM-DD) and becomes unsearchable with the filter. If the value is changed (or removed and then filled again), the date is formatted correctly and is searchable.
1. Create an Assessment (I'm assuming Assessments have at least one global CAD of type Date).
2. Fill in the Date CA for this Assessment.
3. Try to search for this Assessment with Filter by the Date CA (e.g. `"My Date CA" = 11/01/2016` if you set it to 11/01/2016).
Expected result: the Assessment is shown in the result set.
Actual result: the Assessment is not shown in the result set.
This PR moves …
=> GGRC-211 Fix customattributable date setter

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/mustache/base_templates/people_group.mustache, src/ggrc/assets/mustache/base_templates/people_list.mustache
1. Go to Assessment Modal window or Assessment info page
2. Hover mouse over plus button for creator/verifier/assignee
3. Hover mouse over delete button for creator/verifier/assignee
4. Hover mouse over entered person for for creator/verifier/assignee
5. Click plus button and hover mouse over close button
Expected results: tooltip should display corresponding info message not the word "title" only
=> GGRC-207 Fix tooltip in people list

src/ggrc/assets/javascripts/models/assessment.js
Assessment: Asssesor/Assginee field needs to be autopopulated with Audit Lead value from the audit. This is for assessment without a template.
=> GGRC-128 Add audit lead as assessor for new assessment

src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_csvs/full_good_import_no_warnings.csv, test/integration/ggrc/converters/test_csvs/risk_missing_mandatory_description.csv, test/integration/ggrc/converters/test_import_comprehensive.py, test/integration/ggrc/converters/test_import_helpers.py
1. Go to import page.
2. Download a template for Risk object.
3. Fill in title and every other mandatory field except Description for a single Risk object.
4. Import that CSV.
Expected result: the CSV template has an asterisk after "Description" column header; the import ignores the CSV line with missing Description; an error message about empty Description column is displayed.
Actual result: the CSV template has no asterisk after "Description" column header; the import ignores the CSV line with missing Description; no error message is shown, just a note that n'th line is ignored.
=> GGRC-18 Make description of Risk mandatory

src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/custom_attribute_value.py, src/ggrc/utils/html_cleaner.py
This PR adds the following fields for HTML sanitation:
1. CAD - Dropdown options (Assessment Templates and global CAs)
2. CAD - Inline Help (global CAs)
3. CAD - Placeholder (global CAs)
4. CAV - Attribute value (local and global CAs for every type of CAD)
Item 4 could have narrower scope (only values for Text and Rich Text custom attributes), because values with dangerous HTML tags are disallowed for dates and checkboxes and will be disallowed in scope of item 1 for dropdowns. However, I picked a wider scope and chose to sanitize values for every type of definition to be safe if definition types are extended or something changes in non-text CA logic.
=> GGRC-35 HTML sanitation for custom attributes

src/ggrc/models/custom_attribute_definition.py
This PR changes text for error messages returned on CAD name conflict.
Preparation:
1. Go to Admin panel, add a global CA for Assessment with title "Global".
2. Go to an Audit, define an Assessment Template with CA titled "Local".
Cases:
1. In Admin panel, try to add a global CA for Assessment with title "Global".
2. In Admin panel, try to add a global CA for Assessment with title "Local".
3. In Admin panel, try to add a global CA for Assessment with title "Title".
4. In an Audit, try to save an Assessment Template with CA with title "Global".
5. In an Audit, try to save an Assessment Template with CA with title "Local". (this is the only case that should succeed)
6. In an Audit, try to save an Assessment Template with CA with title "Title".
For every case, check that the error message: …
=> GGRC-184 Add more descriptive messages on CA name clash

src/ggrc/assets/javascripts/components/assessment_generator.js, src/ggrc/assets/mustache/modals/mapper/base.mustache
This PR changes wording on generate assessment dialog from
"assessment(s) will be generated"
to
"assessment(s) will be generated for each selection"
=> GGRC-192 Change wording on generate assessment dialog

src/ggrc/assets/mustache/assessments/tree.mustache, src/ggrc/assets/mustache/audits/tree.mustache, src/ggrc/assets/mustache/base_objects/tree.mustache, src/ggrc/assets/mustache/controls/tree.mustache, src/ggrc/assets/mustache/directives/tree.mustache, src/ggrc/assets/mustache/documents/tree.mustache, src/ggrc/assets/mustache/meetings/tree.mustache, src/ggrc/assets/mustache/objectives/tree.mustache, src/ggrc/assets/mustache/requests/tree.mustache, src/ggrc/assets/mustache/sections/tree.mustache, src/ggrc/assets/stylesheets/modules/_snapshot.scss, src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree.mustache
(Please note that existing styling issue with selected items (margin) is not fixed in scope of this PR)
=> GGRC-119 Show snapshots in list (blue)

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc_workflows/assets/javascripts/apps/workflows.js
Counts for History and Active Cycles tabs should differ, but they are based on the same object name.
This PR adds an ability to specify additional data (custom name for counts map, additional filter) for initCounts function.
It is still possible to use this function in the "old way" passing object names in array.
=> GGRC-114 Fix invalid counts for History and Active Cycles tabs on Workflow page

src/ggrc/assets/stylesheets/modules/_object-header.scss, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
**Subject:** Unmap button is available for unmapping a person in People’s tab of Audit page that was added at Program page
**Details:** 
- Go to People’ s tab
- Map a person to the program with Program Reader role
- Create an audit
- Go to Audit page -> People’s tab
- Navigate to the first tree veiw of the added person 
- Click on 3 bb’s button in Person’s Info pane
**Select Unmap:** Unmap button is available for unmapping
**Actual Result:** Unmap button is available for unmapping a person in People’s tab of Audit page that was added at Program page
**Expected Result:** There is the possibility to unmap the person only in Program page. In this case unmap button should not exist.
**Workaround:** NA
=> GGRC-137 Hide unmap button from People tab of Audit page

src/ggrc/assets/mustache/base_templates/add_comment.mustache
~~Just discovered this while fixing some issue. Created a separate PR, because it turned out that this change will not be included in the PR with an actual fix, and I don't want to bloat the latter.~~
UPDATE: There was an issue discovered, causes by fixing the markup. It seems that some functionality relies on the old broken markup. Details below (thanks @alieh-rymasheuski for providing them, and opening the ticket)
---
**Title:**
GGRC-406 Add Comment form lacks a label for the Send Notifications checkbox at Request page
1. Go to a Request page.
2. Scroll to the Add Comment form.
**Expected result:** there is a labeled checkbox to Send Notifications at the bottom of the form.
**Actual result:** there is a checkbox without a label at the bottom of the form.
=> GGRC-406 Close a tag in base add comment template

src/ggrc/migrations/utils/fix_dates.py, src/ggrc/migrations/versions/20161020082501_53206b20c12b_unify_ca_date_format.py, src/ggrc/migrations/versions/20161104072614_2105a9db99fc_redo_ca_date_formatting.py
This PR duplicates the migration to format CA date values because not every source of invalid date formats was fixed previously.
=> QUICK-FIX Repeat CA date formatting migration

src/ggrc/assets/assets.yaml, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/assets/mustache/audits/info.mustache, src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache, src/ggrc/assets/mustache/base_objects/info.mustache, src/ggrc/assets/mustache/controls/info.mustache, src/ggrc/assets/mustache/issues/info.mustache, src/ggrc/assets/mustache/objectives/info.mustache, src/ggrc/assets/mustache/policies/info.mustache, src/ggrc/assets/mustache/processes/info.mustache, src/ggrc/assets/mustache/products/info.mustache, src/ggrc/assets/mustache/programs/info.mustache, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache, src/ggrc/assets/mustache/systems/info.mustache, src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache, src/ggrc_risks/assets/mustache/risks/info.mustache
(Please note 'Update snapshot' menu item is not in scope of this PR)
=> GGRC-136 Update 3bbs menu items for snapshot panel

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/cacheable.js
**Previous:** Assessor/Assignee field is not auto populated with Audit Lead value if Audit Lead equals assessment creator
**Issue**: If Current User is audit lead so he isn't populating as Assessor/Assignee
**Fix**: Now he populated as Assessor/Assignee
=> GGRC-128 Fix adding current user as assignee

src/ggrc/assets/javascripts/components/assessment_templates/assessment_templates.js, src/ggrc/assets/javascripts/components/assessment_templates/tests/assessment_templates_spec.js, src/ggrc/assets/mustache/modals/mapper/base.mustache
This PR changes the generate Assessments modal, so that by default, the first available AssessmentTemplate is selected in the corresponding dropdown.
**Details:**
- Open an Audit, go to the Assessment Templates tab.
- If needed, define a couple of Assessment Templates for different object types (some of the ATs should have the same object type set).
- Go to  the Assessments tab and click the magic wand icon (just above the tree view, on the right).
In the modal, the first available Assessment Template should be preselected in the corresponding dropdown (if such template exists, of course)
No Assessment Template is selected in the dropdown by default.
P.S.: The branch name is incorrect, the issue number is indeed GGRC-191.
=> GGRC-191 Preselect the First Assessment Template when generating Assessments

src/ggrc/migrations/versions/20161109010604_4afe69ce3c38_remove_invalid_person_objects.py
The InterviewResponse object was not properly removed from all tables
when the model was deleted. Memcache then tried to remove this non
existent model, which resulted in an exception. This migration makes
sure that such bad data is properly purged from our database.
To reproduce this issue, try to create an assessment on the audit 503 from the grc-test database.
Expected: you should be able to make an assessment
Actual result: You get a script error for non existent type "InterviewResponse"
PS: this commit is a monkey patch for Qunice-PATCH3 so the head commit is the one from the patch3 tag.
=> GGRC-431 Remove bad data form object_people table

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/js_specs/models/assessment_template_spec.js, src/ggrc/converters/handlers/default_people.py, src/ggrc/models/assessment_template.py, test/integration/ggrc/models/factories.py
1. Open an Audit page.
2. Open new Assessment Template definition modal.
3. Type in a title.
4. Add a CA with title "CA3" (or the title of any other global Assessment CA present in the system).
5. Click "Save & Close". An error "Invalid Custom attribute name" should be displayed.
6. Click "Save & Close" once again (without any changes).
Expected result: the POST request is sent again, the error "Invalid Custom attribute name" is displayed again.
Actual result: error "Uncaught TypeError: current._get is not a function" is displayed in the console, no request is sent.
=> GGRC-185 Fix JS error in AT modal

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/snapshotter/individual-update.js, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
=> GGRC-120 Update to latest version (3bbs menu item)

src/ggrc/converters/base_block.py, src/ggrc_workflows/__init__.py
This pull request is prep work for making cycle tasks editable via imports.
The thing is for cycle tasks to be properly importable, the pre commit signals have to work properly and all have to be called before the first flush statement.
=> QUICK-FIX Fix import signals

src/ggrc/automapper/__init__.py, src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/services/common.py
This pull request adds event to `*_after_commit` signals. This is required for the snapshotter to avoid ugly [`get_event`](https://github.com/google/ggrc-core/pull/4237/files#diff-30b7bbcf03f429d63ac005af5be076c1R108) call to retrieve (likely) event that caused snapshotter to run and create/update snapshots.
For testing: If tests pass this should be good, however, to be double short, the person that merges it should run `git grep` to ensure that all signal senders attach event and all signal receivers expect event. Do note - event only makes sense for `_after_commit` signals since it is only at that point that we actually have event.
=> QUICK-FIX Add event to signals 

src/ggrc/automapper/__init__.py, src/ggrc/automapper/rules.py, test/integration/ggrc/automapper/test_automappings.py
We are beginning our transition to snapshots and no longer need
Audit - Program automappings.
=> [Feature/Snapshotter] Remove Program - Audit - Program Objects automappings

src/ggrc/assets/stylesheets/modules/_snapshot.scss, src/ggrc_workflows/assets/mustache/base_objects/approval_link.mustache
Implemented according to requirements (disable edit functionality for snapshots).
=> GGRC-70 Disable editing for snapshots

src/ggrc/assets/mustache/base_objects/tree.mustache
Users encountered a problem when clicking on a tree view item to "select" it and show its info pane.
If an object represented by a tree item had an attribute whose value was rendered with a hyperlink, clicking on that link took the user to different page, even though the intent was to highlight a tree view item. This PR resolves this inconvenience by removing links from tree view items.
To reproduce, open a program and navigate to its Assessments tab. The STATE field showing the Assessment's status is a hyperlink. With the fix applied, you should see that the STATE is not a hyperlink anymore, but instead just a plain text.
P.S.: The issue seems to only affect Assessments, other objects types (e.g. Audits) already had their statuses rendered as plain text.
=> GGRC-217 Remove hyperlinks from tree view item's fields

src/ggrc/notifications/common.py, src/ggrc_workflows/notification/__init__.py, src/ggrc_workflows/notification/data_handler.py, test/integration/ggrc_workflows/notifications/test_one_time_wf.py
Users do not want to receive cycle notifications when they are assigned as No Role on the workflow tab.
I'm adding a question label as I'm not 100% sure how we should handle No Role people that are also assignees on a cycle task. Currently we send an email notification about the task being overdue/decline, but I need to check with akhil if No Role should mute those as well.
=> GGRC-53 Do not send email notification if user has No Role on workflow

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc_workflows/assets/javascripts/apps/workflows.js, src/ggrc_workflows/assets/javascripts/components/end_cycle.js
This PR fixes issue about widget counters that are not updated after workflow actions: activate workflow, end cycle.
It also fixes issue about active cycles tree is not updated after ending cycle .
=> GGRC-390 Fix counters and tree are not refreshed after workflow actions

src/ggrc/assets/javascripts/controllers/comment_controller.js
_(don't know the Jira issue number...)_
This PR fixes an issue that prevented a non-admin Assessment assignee from editing his/her own comments without refreshing the page. For that, permissions need to be refreshed for new comments.
Initially I triggered refreshing the permission refresh [here](https://github.com/google/ggrc-core/blob/develop/src/ggrc/assets/javascripts/components/assessment/add_comment.js#L107), but the template already starts rendering the new comment at that point, causing the latter to be briefly uneditable (until the permissions are updated). I thus decided to move refreshing the permissions to an earlier point.
No test, because an integration / end-to-end test would make more sense here, and that is a complex task currently worked on by QA (AFAIK).
---
**Details:** …
=> ISSUE-1.505 Allow Assessment assignee to edit own comments

src/ggrc/utils/query_helpers.py
**Subject:** The #s of visible objects in LHN doesn't match the # of accessible objects for user
**Details:** 
- Log in as auditor and navigate to an audit page (audit should have a control mapped to it via program)
- Open LHN All objects tab and find the control mapped to the audit
- Open My objects tab in LHN and try to find the same control
**Actual Result:** control isn’t shown in the LHN accordion
**Expected Result:** The control should be visible on My objects tab in LHN menu
P.S. I'd prefer to put this on hold till Sprint 4 to add some tests and let QA team do a proper testing and not be in rush.
=> GGRC-17 Fix search/query API to handle auditor related objects

src/ggrc/converters/query_helper.py
_get_last_modified function in services/query_helper was fetching the
updated_at column from the database for every object in the loop. For
the object count query on all objects page on grc-test this resulted in
over 14k queries to the database just to fetch the updated_at column
for every object.
I believe this simple code change will reduce the request time for
fetching object counts from minutes to just a couple of seconds at most.
Some quick benchmarks:
In my local env it took 20.12s to load the counts:
After the change:
grc-test is even worse, it's currently taking 1.7minutes to load the all object page:
I'll post a benchmark for grc-test after this is merged.
=> GGRC-215 Improve performance of /query count queries

src/ggrc/assets/mustache/import_export/import.mustache
This fix makes picking a CSV file for import more user friendly, because it automatically sets the filter on the browser's select file dialog to `*.csv` files.
Note that this is just a convenience for the user, nothing is enforced on the server, and the user can even select a different file type in the dialog (although I'm not sure if there is a use case for that, but anyway...).
=> QUICK-FIX Limit import file dialog to *.csv files

src/ggrc/fulltext/sql.py
This is a revert and a proper fix for the work done in this PR https://github.com/google/ggrc-core/pull/4524
The PR mentioned above added an sqlalchemy warning and possible performance degradation.
The issue was caused because custom attributes deleted all entries and added just one. The rest of this fix would be to make a unique index over all three columns (including tags) for uniqueness check and referring to all three columns every time we add or delete a record.
To test this PR, test the working of  https://github.com/google/ggrc-core/pull/4524 and make sure no warnings are shown when running python tests.
PS: also have a look if this change could be too risky to put into quince and if it would be more appropriate to merge it to develop instead.
=> QUICK-FIX Fix fulltext indexer

test/integration/ggrc/__init__.py, test/integration/ggrc/generator.py, test/integration/ggrc/models/factories.py, test/integration/ggrc_basic_permissions/test_creator_audit.py, test/integration/ggrc_basic_permissions/test_creator_program.py, test/integration/ggrc_workflows/generator.py, test/integration/ggrc_workflows/models/factories.py, test/integration/ggrc_workflows/notifications/test_cycle_start_failed_notifications.py, test/integration/ggrc_workflows/notifications/test_deleted_objects.py, test/integration/ggrc_workflows/notifications/test_enable_disable_notifications.py, test/integration/ggrc_workflows/notifications/test_recurring_cycles.py, test/integration/ggrc_workflows/test_basic_workflow_actions.py
The object generator for testing added a default owners and title fields
to posted data. On objects that do not have these fields such as
Comments and Relationships this caused an error. The second bug that hid
that error was that owners contained invalid data unless the test was
run on a clean database with a person with id 1.
The first commit fixes both of the above issues.
To test this issue just run the following commands on develop and on this PR.
```bash
$ cd test/
$ db_reset 
$ nosetests integration.ggrc.notifications.test_comment_notifications:TestCommentNotification.test_notification_entries
```
The rest of the commits just organize and clean up the testing code.
=> QUICK-FIX Update integration test framework

src/ggrc/assets/javascripts/components/assessment_templates/tests/assessment_templates_spec.js
This PR silences a warning printed to the console by one of the karma unit tests. I got a feedback that it might look confusing to some people, even though all the tests pass.
With the fix, the following warning no longer show during the karma test run:
> 'GGRC.Components.assessmentTemplates: An empty template group encountered, possible API error'
Thanks @alieh-rymasheuski for the suggestion! :)
=> QUICK-FIX Silence a particular warning message in karma test

src/ggrc/assets/javascripts/components/csv/import.js, src/ggrc/assets/javascripts/components/csv/test/import_spec.js
This PR disables the "Import data" button on the import page if there is nothing to import.
To verify, go to the `/import` page and upload an empty CSV file (you can get one by downloading the import template file from the same page). If the row count for all blocks (i.e. object types) is zero, the button must be disabled. The same if there are non-empty blocks, but have all their rows ignored because of errors (e.g. missing values for required attributes).
However, if the uploaded CSV file contains at least one block with a row that will not be ignored, the import button must of course be enabled.
=> GGRC-255 Disable the Import button if there is nothing to import

src/ggrc/app.py, src/ggrc/models/audit.py, src/ggrc/models/snapshot.py, src/ggrc/snapshotter/__init__.py, src/ggrc/snapshotter/datastructures.py, src/ggrc/snapshotter/helpers.py, src/ggrc/snapshotter/listeners.py, src/ggrc/views/__init__.py, test/integration/ggrc/converters/test_csvs/snapshotter_create.csv, test/integration/ggrc/converters/test_csvs/snapshotter_update.csv, test/integration/ggrc/snapshotter/__init__.py, test/integration/ggrc/snapshotter/test_indexing.py, test/integration/ggrc/snapshotter/test_snapshoting.py
This adds snapshot generator and adds tests for core generator and for indexing that was left missing from #4654.
To test you should verify all the object that should be snapshotted (per rules) are actually snapshotted and set to correct (latest) revision. You can also perform various PUT to audit/snapshot to verify what bulk/individual updates have gone through. See tests for examples. If you believe there is a missing test scenario, please point it out.
All of aforementioned verification will have to be performed in database since frontend cannot properly fetch snapshots until @zidarsk8 finishes his Query API work.
=> [FEATURE/SNAPSHOTS] Core snapshot generator

src/ggrc/assets/javascripts/components/view-object-button/view-object-button.js, src/ggrc/assets/javascripts/controllers/info_pin_controller.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/mustache/assessments/header.mustache, src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache, src/ggrc/assets/mustache/base_objects/dropdown_menu_tier2.mustache, src/ggrc/assets/mustache/base_objects/info_header.mustache, src/ggrc/assets/mustache/base_objects/states.mustache, src/ggrc/assets/mustache/base_objects/tree.mustache, src/ggrc/assets/mustache/base_objects/view_link.mustache, src/ggrc/assets/mustache/base_templates/header.mustache, src/ggrc/assets/mustache/components/view-object-button/view-object-button.mustache, src/ggrc/assets/mustache/controls/object_list.mustache, src/ggrc/assets/mustache/dashboard/object_list.mustache, src/ggrc/assets/mustache/people/object_list.mustache, src/ggrc/assets/mustache/sections/dropdown_menu.mustache, src/ggrc/assets/mustache/sections/tier2_content.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/authorizations_by_person_list.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache, src/ggrc_workflows/assets/mustache/cycles/info.mustache, src/ggrc_workflows/assets/mustache/workflows/info.mustache
This PR adds view button that opens assessments in maximized mode. It also hides open buttons in subtree items and changes wording of "View" menu items across the project.
From Jira description:
On the assessment tree view, the user prefer not clicking the open button, rather maximizing the modal, however maximizing is not clear as the open button. UX suggestions are needed to making maximizing more prominent.
To implement the following:
1. Add new button "View" to open modal window. 
2. Remove "Open" button for rows in the tree; View is more popular action; a user still can open an object via [...] 3dot menu.
3. Rename action in the 3dot menu from View to Open.
=> GGRC-171 open view buttons

src/ggrc/assets/mustache/custom_attribute_definitions/subtree.mustache
This PR fixes the UI glitch that did not remove a (sub)tree item when a Custom Attribute Definition was deleted (putting `on hold`, please remove the label once the QA testing  of the release branch finishes).
The issue was caused by the subtree DOM items missing essential `data-*` attributes that the tree view controller uses for locating and removing elements from the DOM (the internal state of the tree view controller and the database were fine, it was just the DOM element that wasn't removed).
**Details:**
- Open Admin Dashboard
- Navigate to Custom Attributes tab
- Select object type (e.g. Audit) and expand it
- Add a new custom attribute definition to that type
- Click Edit next  to the Custom Attribute Definition
- Click Delete button
- Look at Custom Attributes tab
**Actual …
=> GGRC-249 Fix UI update on CA definition deletion

src/ggrc/assets/javascripts/models/comment.js, src/ggrc/assets/javascripts/models/tests/comments_model_spec.js
This PR fixes the way Comments are displayed in object history logs. The default `display_name()` method as inherited from `can.Model.Cacheable` did not suit them well, thus I overrode it.
Note that there might be a UX problem when displaying lengthy comments in the log, but this is probably out of scope of this PR. We can perhaps open separate ticket to automatically cut off too long texts in the object history log, if we don't already handle such cases.
**Details:**
- Navigate to Assessment tab -> Navigate to Assessment’s Info panel 
- Leave a comment
- Open Assessment Log
comment has (DELETED) status on assessment's log tab after comment's creation (see screenshot)
comment shouldn’t have (deleted) status in log since it wasn't even created yet by …
=> GGRC-291 Fix display names of Comment objects

src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/models/simple_models.js
This PR removes the "required" asterisks from Effective Date and Stop Date fields in Program modal.
`On hold` until a tag for PATCH4 is made.
=> GGRC-450 Make program dates non mandatory

src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
Regression issue, this menu item still should not be visible for Audit (without snapshot backend).
=> QUICK-FIX Hide 'Update Scope' menu item if object not is_snapshotable

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/mustache/assessments/tree_add_item.mustache, src/ggrc/assets/mustache/audits/tree_add_item.mustache, src/ggrc/assets/mustache/base_objects/tree_add_item.mustache, src/ggrc/assets/mustache/modals/mapper/base.mustache, src/ggrc/assets/mustache/modals/mapper/component.mustache
- Hide map button for snapshots;
- Unified mapper search results contains only 'in-scope' objects;
=> GGRC-69 Snapshot In-Scope Mappings

src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/stylesheets/modules/_assessment.scss
**Details**: 
Create an assessment under an audit
Open assessment’s info panel
_Actual Result_: there is no Assessment's slug (code) in assessment's info panel on audit page
_Expected Result:_ please confirm that slug (code) should be visible on assessment info panel on audit page (we are still able to see slug when editing assessment)
_Workaround_: na
=> GGRC-256 Add slug on Assessment info pane

src/ggrc/automapper/__init__.py, src/ggrc/models/snapshot.py, test/integration/ggrc/snapshotter/test_snapshoting.py
This adds support for creating snapshots from the unified mapper.
For the api request specs, please take a look at the added integration test.
=> GGRC-474 Snapshot post api

src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/javascripts/components/tests/template_attributes_field_spec.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
**Precondition**: 
1. Created program and audit
1. Go to Audit page
2. Add Tab-> Assessment template
3. During Assessment template creating add LCA with dropdown type and attribute values that contain points
3. Click Save and Close button: confirm error is displayed
_Actual result:_ "Uncaught can.Map: Object does not exist" error message occurs while creating Assessment template with dropdown LCA with dots in options
_Expected result:_ no error displayed. Should be the possibility to have dots in LCA dropdown options.
=> GGRC-449 Fix values with point in AT CA

src/ggrc/assets/javascripts/apps/base_widgets.js, src/ggrc/templates/layouts/base.haml
Make sure to use GGRC.config object only if it was loaded. The index page does not load all configs and causes a script error before it could load.
This PR removes the blocker caused by https://github.com/google/ggrc-core/pull/4701/files#diff-9642b862bb4f2f86483c36f4b95fb62eR11 
~I have checked and could not find any negative side effects of this change, but I would like to get at least 2 confirmations that this can not cause any blockers in the future. If there is any issue found in this fix we will fix issue linked above with a static list copy pasted from the backend before a proper solution is found.~
PS: we should also investigate why Selenium tests did not find the original issue.
=> QUICK-FIX Only use config if it's available

src/ggrc/assets/javascripts/components/snapshotter/individual-update.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- Update the PUT request call for snapshots to match what the
backend expects.
- The content of the snapshot model should never refer to the original
objects. This causes problems when refreshing a snapshot of the object
that was already deleted.
- The other fix here is to always use correct links and not mix up ids of
the original objects and snapshots, which will create invalid links.
This fixes all script errors when navigating the tree views for snapshotted objects and when trying to update a single snapshot instance.
Marking this as please review because it's needed for the demo.
=> QUICK-FIX Fix update snapshots

src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/snapshotter/rules.py, src/ggrc/views/__init__.py
~This PR is still work in progress.~
Solution implemented here works, but I'd like some feedback on the code. The `audit` should be in a constant elsewhere and those if statements in the data loop are not nice, but I'd like to hear if there's anything else that I'm missing.
The one issue that I find is that Objective counts are wrong. The query and results are correct, and I have verified that the correct number is stored in `widgetsCounts` for the `Objectives` model, but no matter what is in there, the widget shows a 0.
=> QUICK-FIX Fix counts for snapshotted objects

src/ggrc/assets/javascripts/components/effective-dates/effective-dates.js, src/ggrc/assets/javascripts/models/control.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/models/simple_models.js, src/ggrc/assets/mustache/components/effective-dates/effective-dates.mustache
This PR removes unnecessary "required" asterisks from "Effective date" and "Stop date" fields from all objects' modals.
This PR also removes the per-model configuration mechanism for "Effective date" and "Stop date" fields in the modals since no model that uses `<effective-dates>` component has custom labels/mandatory options for these fields.
The per-model configuration mechanism required that the config objects were stored for each instance of the models, and these config objects just increased memory usage for no functional difference.
`On hold` due to the code freeze.
=> GGRC-468 Remove asterisks from effective/stop dates

src/ggrc/models/mixins/customattributable.py
1. Create a global CA for Assessment named 'My CA'.
2. Create an Assessment Template with a CA named 'My other CA'. Save.
3. Edit the Assessment Template, add a CA named 'My CA' (same as the global one). 
4. Click Save.
Expected result: no changes to CADs is done.
Actual result: the old CADs get deleted from the Assessment Template (you can refresh the page and open the editing modal to check it).
This PR removes the `commit` from the CAD update method and does exactly what `commit` would do (flush the session and expire all objects) without actually ending the DB transaction.
`on hold` until PATCH4 is tagged.
=> GGRC-445 Leave old CADs in AT on unsuccessful update

src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache, src/ggrc/assets/stylesheets/components/custom-attributes/_custom-attributes.scss, src/ggrc/assets/stylesheets/modules/_assessment.scss
Fix Invalid positioning of Description list and URL list in Assessment's Info pane
1. Navigate to Assessment's Info pane
2. Look at Description list and open URL list
=> GGRC-256 Update to Fix Layout issue of Assessment Info Pane

src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/javascripts/components/tests/template_attributes_field_spec.js, src/ggrc/assets/javascripts/components/tests/template_attributes_spec.js, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
This PR fixes the issue in the Assessment Template edit modal that caused the lists of Custom Attribute Definitions in the DOM and in the code out of sync, which resulted in an odd behavior.
**Details:**
- Edit the Assessment template 
- Delete a CA field from the list but do not save the changes, just close the modal by clickig “X” button or clicking outside the modal
- Open Edit Assessment template modal again
the app shows that another field has been removed
the changes weren’t saved so the app should show all the fields after reopening edit modal
=> GGRC-277 Fix odd behavior in edit modal when removing a CA without saving

src/ggrc/models/mixins/customattributable.py
This commit fixes the regression caused by https://github.com/google/ggrc-core/pull/4683/commits/7b69a5a54c0ab709ba001492ab44e7e30127578e because we did
not change the fulltext property name everywhere. This fixes the invalid
property name is used for custom attribute values.
To test this just try to set and then edit any custom attribute value on any object that still uses the old custom attribute API. (anything that's not assessments)
The real fix would be to remove the old CA API and just update the entire froned, but this is good enough for now, and we already have a ticket for that.
=> GGRC-491 Fix updating CAs with the old API

src/ggrc/assets/mustache/custom_attributes/info.mustache
1. Create GCA for an object (e.g. Regulations)
2. Create program
3. Create Control
4. Create Regulations-> Enter the value into the created CA field in Regulations Info pane
5. Create Audit
6. Go to Audit page-> Regulations tab-> Navigate to Regulations Info pane
7. Try to edit CA field: confirm the field is editable
Actual Result: CA field is editable after snapshot
Expected Result: CA field should not be editable after snapshot
=> GGRC-488 Disable editing GCA for snapshots

src/ggrc_basic_permissions/assets/javascripts/controllers/contributions.js
1. Log as Admin
2. Go to Admin Dashboard-> People’s tab
3. Click grey triangle on the first tier
4. Click 3 bb’s button in Info pane
5. Select Edit Authorizations
6. Change user role for the selected person-> Save
Actual Result: User role is not changed in the tree view.
Expected Result: User role should be changed.
=> GGRC-311 Refresh user role after update in /admin

src/ggrc/assets/javascripts/controllers/modals_controller.js
Create GCA with any type for assessment, created program and audit
1. Go to Assessment Template tab on Audit page
2. Add title
3. Add LCA with a title that is not exist for assessment-> Save and Close
5. Open the created Assessment template to edit
6. Add LCA with the title as GCA has from precondition-> Save and Close
_Actual Result:_ "There was an error" occurs in Edit Assessment template modal while saving LCA with the title equal GCA 
_Expected Result:_ no error displayed. A warning that invalid Custom attribute name should be displayed
=> GGRC-518 Fix error message  after update instance in modal

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/assignee_types_spec.js, src/ggrc/assets/mustache/assessments/dates_list.mustache, src/ggrc/assets/mustache/assessments/urls.mustache, src/ggrc/assets/mustache/base_templates/comment_subtree.mustache, src/ggrc/assets/stylesheets/components/collapsible-panel/_collapsible-panel.scss, src/ggrc/assets/stylesheets/modules/_label-list.scss
Comments from UX Designer:
We already show labels in People section (Verifier, Creator etc). No need for additional icons as we do not show them for other labels /categories. 
Comments section: it's quite unclear what icons mean (a letter means a role). Instead, I would suggest using Role after a person name 
Delete icon:
Currently, this icon appears with a delay and at the left - what is not common behavior. I'd suggest showing "trash" icon on mouse hover at the right. On hover - in order not to "promote" delete action in People section.
Some more UI issues for this page:
- Control to add URL and People are different
- different paddings after a category label and  icon
- icons have different colors: e.g. for  and  icons
- different label format
- separator between section disappears …
=> GGRC-45 UX changes in people list

src/ggrc/assets/mustache/base_objects/general_info.mustache, src/ggrc/assets/stylesheets/_colors.scss, src/ggrc/assets/stylesheets/modules/_snapshot.scss
1. Open control tabs for snapshoted audit
2. Click snapshoted control in tree view
3. Check header for info page
Expected: version of snapshot should be displayed in header box for info page
=> GGRG-503 Add version of snapshot in header

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/mustache/import_export/import_export_buttons.mustache
Precondition:
1. Created program, control, snapshotable object (e.g. Access group), audit
1. Go to Access Group tab on Audit page
2. Look at tree view tool bar: confirm export/import icon is not hidden 
Actual Result: export/import button is not hidden in tree view tool bar
Expected Result: export/import button should be hidden in tree view tool bar
=> GGRC-495 Hide import and export buttons for snapshots

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Precondition:
1. Created program, control, audit, snapshotable object (e.g. Access Group)
1. Go to  Access Group tab on Audit page
2. Click gray triangle on the first tree view: confirm the second tree view is not displayed
Actual Result: Snapshotable object's second tree view is not displayed on Audit page
Expected Result: Snapshotable object's second tree view should be shown on Audit page
**NOTE:** This fix will show parent object (on the second level) of snapshot, then objects that are mapped to parent object (third level). It should be confirmed by @akhilp1 .
**NOTE2:** We can proceed and show it next Monday to Akhill, and fix if any change will be requested.
I hope that this behavior is more logical, because user can't change mappings for snapshot but only for …
=> GGRC-506 Show second level of treeView for snapshots

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/mustache/dashboard/object_widget.mustache, src/ggrc/assets/stylesheets/modules/_spinner.scss
This PR displays a spinner when switching to another object tab (using the HNB) until the tree view is actually loaded and starts loading its own data.
This gives users a way to distinguish between the cases when the tab content is still being loaded, and when the tab content has finished loading, but possibly resulting in no content displayed (e.g.  because of no relevant data to display).
Note that the initial spinner looks differently than the tree view's own spinner while loading content, but this PR does not try to address this UI inconsistency, it just uses the standard spinner component we use throughout the app.
No unit tests, because an integration test would make much more sense here, but that is being worked on as a part of a different story.
P.S.: The ticket mentions that _"we …
=> GGRC-412 Display spinner while tab content is loading

src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/javascripts/controllers/tree_filter_controller.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/dashboard/internav_list.mustache, src/ggrc_workflows/notification/data_handler.py, test/selenium/src/lib/constants/locator.py, test/unit/ggrc_workflows/notification/__init__.py, test/unit/ggrc_workflows/notification/test_data_handler.py
This PR improves the links to users' tasks in daily digest emails. It adds a filter query to the URLs, so that only the relevant WF Cycle is displayed in the tree view, making it much easier for the user to find the actual task linked from the email.
One way to test this is to create some WF tasks for various people and then preview the daily digest email (hint: URL path `/_notifications/show_daily_digest`). These links now automatically apply a tree view filter, as mentioned above.
**NOTE:**
Adding a query parameter to the URL introduced an inconvenience when switching between tabs in HNB, the filter tended to stick around and filtering tree views on other tabs, because only the hash part of the URL was changed.
To avoid this, this PR also prepends the `href` attributes of the tabs with …
=> GGRC-421 Auto-select correct WF Cycle when using email links

src/ggrc/assets/javascripts/components/inline_edit/inline.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/js_specs/models/cacheable_spec.js, src/ggrc/fulltext/recordbuilder.py, src/ggrc/models/mixins/customattributable.py
When we clear the custom attribute we set obj.attribute_object_id to 0,
but the check 0 is not None was returning True. If we omit the is not
None part we fix the issue because bool(0) == False and bool(None) ==
False.
=> GGRC-463 Fix server error when clearing person custom attribute

src/ggrc_basic_permissions/roles/Auditor.py, test/integration/ggrc_basic_permissions/test_creator_audit.py
Subject: Auditor isn't able to create an Assessment under an audit
Details: 
- Create a program as Admin
- Create an audit as Admin and assign GC as auditor
- Navigate to Audit page-> Create Assessment and assign Creator as GC  and assessor as GC  -> Save and Close
- Log as GC
- Navigate to audit page-> Try to Create 1 Assessment: an error 403 is displayed in Console
- Create second Assessment: confirm that an error is displayed
=> GGRC-12 Auditor isn't able to create an Assessment under an audit

src/ggrc/models/hooks/comment.py
This PR fixes the regression when adding a comment became non-functional.
0. Run the app as `launch_gae_ggrc`.
1. Open an Assessment page.
2. Try to add a comment.
Expected result: the comment is added.
Actual result: HTTP500 is returned, the comment is not added.
Marking `please review` as it's a blocking issue (even for the `develop` branch).
**UPD**: added a note to test this with GAE emulation.
=> GGRC-167 Fix regression with adding comments

src/ggrc/assets/mustache/assessments/tree_header.mustache, src/ggrc/assets/mustache/audits/tree_header.mustache, src/ggrc/assets/mustache/base_objects/tree_header.mustache, src/ggrc/assets/mustache/people/tree_header.mustache, src/ggrc/assets/mustache/requests/tree_header.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_header.mustache
This PR removes the object type info from the tree view's Title column header, because that was causing a confusion when using a filterr (I presume users were trying to filter by an incorrect column name). The label of the "title" column in tree view is now simply `"TITLE"` instead of `"{object_type} TITLE"`.
The original ticket description:
> Update the title column header without the object name - Assessment Title to Title - Causing confusion in Filter
=> GGRC-417 Remove object type from Title header in tree view

src/ggrc/assets/mustache/base_objects/general_info.mustache
1. Update message to "click here if you want to check for latest version and update"
2. Word "Click here" is a link that opens "Update to latest version" window
=> GGRC-507 Update message for outdated version of snapshot

src/ggrc/assets/stylesheets/_colors.scss, src/ggrc/assets/stylesheets/modules/_snapshot.scss
1. Create Audit and map control
2. Change control title and go to Control tab at Audit page
3. Snapshoted control displayed in blue color in tree-view (for first level of tree-view)
4. If tree view is selected the blue color should be deeper
=> GGRC-502 Show snapshots in blue color in treeView

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/control.js, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/assets/mustache/assessments/header.mustache, src/ggrc/assets/mustache/assessments/modal_content.mustache, src/ggrc/assets/mustache/controls/info.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache
There were still some places in the app where the obsolete _"Assessor"_ term was used instead of the _"Assignee"_.
The change can be seen (at least) at the following places, mostly form labels and input field placeholder texts:
- Control's edit modal and info pane (check the Advanced section)
- Assessment Template's edit modal and info pane
- Assessment's info pane - the "remind people" link and the text in the notification dialog that appears.
I have noticed that there are some texts in the `notification_types` table, too, but it was not clear what should be changed there, if anything. For example, the record with the ID 22 contains both the `"Assessor"` and the `"Assignee"` words, thus I was not sure what the semantics of an `"Assessor"` are in that context, and decided to not change …
=> GGRC-438 Rename "Assessor" to "Assignee"

src/ggrc/assets/mustache/components/assessment/attachments-list.mustache, src/ggrc/assets/stylesheets/modules/_assessment.scss
A user reported that when attaching evidence to an Assessment, the upload silently (?) fails if trying to attach more than 10 files at once. This seems to be a GDrive account limitation, as I successfully uploaded 11 files in a batch locally.
Anyway, in order for the users to not be confused, this limitation needs to be presented to them, and @akhilp1 confirmed that displaying an informative text on the form would already suffice. This PR thus adds such text to the Assessment info pane, right under the "Attach Evidence" button.
=> GGRC-413 DIsplay max Assessment evidence upload batch size

src/ggrc/views/__init__.py
The Role object is not searchable and is also not indexed by default
when a new application instance is created. That is why the reindexer
should also ignore this object.
=> QUICK-FIX Exclude Role from reindex

src/ggrc/assets/javascripts/controllers/dashboard_controller.js
This PR fixes the regression with being unable to close HNB tabs.
1. Go to dashboard.
2. Click "Add tab", add a tab.
3. Click the close button to delete the added tab.
Expected result: the tab is closed.
Actual result: a JS error is raised, the tab is not closed.
=> QUICK-FIX Fix close tab regression

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_csvs/all_snapshottable_objects.csv, test/integration/ggrc/models/test_snapshot.py
This is prep work for snapshot content fixes. Because we're using imports for set up stage for tests, we must make sure that they set all the revision content properly.
Adding please review, because this is needed for the tuesdays pilot release.
To test this: 
- import an new object that has custom attributes. 
- check that the custom attribute values are stored in the content of the revisions table (you have to check manually)
=> GGRC-487, GGRC-490 Import revisions fix

src/ggrc/assets/stylesheets/modules/_inline-edit.scss
**Steps to reproduce:** 
Navigate to Assessment’s Info pane
Navigate to any CA field to edit: confirm Assessment's title blinks
_Actual Result_: Assessment's title blinks if navigate to CA field in Assessment Info pane
_Expected Result_: Assessment's title should not blink if navigate to CA field in Assessment Info pane
_Workaround_: na
=> GGRC-402 Fix blinking header of info-pin

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
1. Log as admin
2. Go to My Work or All objects page
3. Select e.g. Access Groups tab from HNB
4. Click on gray triangle in the first tree view: confirm extra [Map] button appears
Actual Result: extra [Map] button is displayed after opening the second tree view on My Work/All objects pages
Expected Result: Extra [Map] button should not be shown after opening the second tree view on My Work/All objects pages
=> GGRC-458 Remove duplicate of Map button in tree view

src/ggrc/assets/javascripts/components/unified_mapper/mapper_results.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
This reverts commit 38f2edbd880d9d29a21d7b1df57fdc2cf6ae03d0.
The commit caused a severe performance degredation in the unified
mapper modal because the /query API is not optimized for returning
non paginated results.
Querying for controls on the grc-test database took more than
1min on my local machine and it executed 42978 sql statements.
=> Revert "Make possibility to search via Query API in unify mapper"

test/selenium/src/lib/entities/entities_factory.py
This PR resolve last comment from @zidarsk8 in [this PR](https://github.com/google/ggrc-core/pull/4690) about improving scalability/extendibility of Custom Attribute factory by replacing `@staticmethod` to `@classmethod`.
=> QUICK-FIX Update factory methods and docstrings

src/ggrc/models/mixins/clonable.py, src/ggrc/snapshotter/__init__.py, test/integration/ggrc/models/test_clonable.py
Create exact same clone of audit scope as on the original object.
Fixed: @Smotko Per my understanding (and testing) of #4490 moving to model_posted_after_commit (e82468a84f22e2433747318def4bdf7742a57213) should not be problematic - do you see any problems with this change that could cause a regression?
=> GGRC-64 [FEATURE/SNAPSHOTS] Audit cloning

src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
This PR fixes the issue of a required field becoming hidden in the create Task modal when clicking the _"Hide all optional fields"_ button.
2. Navigate to Task's Group Info pane on Setup tab
3. Click + to create task
4. Click [Hide all optional fields] button: confirm that mandatory "Assignee" field is hidden
Mandatory "Assignee" field hides while clicking [Hide all optional fields] button in Create New Task modal
Mandatory "Assignee" field is not hidden while clicking [Hide all optional fields] button in Create New Task modal
=> GGRC-469 Unmark Assignee field as optional in Task modal

src/ggrc/assets/javascripts/components/ca-object/ca-object.js, src/ggrc/assets/javascripts/components/tests/ca-object_spec.js
This PR fixes issue that "Saved" message is not displayed after edit Person CA field in Assessment's Info panel. The problem is that "Map person" CA field type has specific value.
=> GGRC-296 Fix Saved message is not displayed after mapping a person

src/ggrc/assets/javascripts/components/assessment_attributes.js, src/ggrc/assets/javascripts/components/tests/template_attributes_spec.js
Create GCA with any type for assessment, created program and audit
1. Go to Assessment Template tab on Audit page
2. Add title
3. Add LCA with the title as GCA has from precondition
4. Add LCA with a title that is not exist for assessment
5. Click trash icon to delete GCA: confirm all CA disappear
_Actual Result:_ Additional LCA is deleted while deleting LCA in New Assessment Template modal
_Expected Result:_ Only selected CA for removal should be deleted while clicking on trash icon in New Assessment Template modal
**NOTE**: 
1. You can open any AT modal (create or edit)
2. Add several new CA with any names
3. Remove any of created CA
_Actual_: removed 2 CA instead of 1 selected
_Expected_:  Removed only selected CA
=> GGRC-515 Fix removing new CA in AT modal

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This PR fixes the button for closing the "visible fields" dialog used with tree views.
It turned out that the fix also fixes the issue GGRC-467.
(tests skipped, b/c an end-to-end Selenium test would make the most sense, and that is being worked on as a part of a different issue)
---
**Steps to reproduce (GGRC-443):**
1. Go to Assessment tab (or any tab where Set Visible fields/Select child tree dialogs exist)
2. Click on Set Visible fields icon/Select child tree icon
3. Click on [x] to close the dialog
close [x] button is disabled on Set Visible fields/Select child tree dialogs
close [x] button should close the Set Visible fields/Select child tree dialogs
---
**Steps to reproduce (GGRC-467):**
1. Go to My Work Page
2. Select any tab from HNB (e.g. …
=> GGRC-443, GGRC-467 Fix close button in visible fields dialog

src/ggrc/assets/stylesheets/modules/_assessment.scss
This PR adjusts the color of the `(?)` icon to match the color of other icons.
To see the change in action, open an object, switch to one of the object tabs that have Custom Attributes (e.g. Assessments), and select one of the Assessments in the tree view (create one if necessary).
You will see that on the info pane, the formerly black `(?)` icons next to (some) custom attributes now match the color of e.g. the `(+)` icon for adding an URL (at the bottom of the info pane's gray area).
You also check the following [screenshot](https://lh3.googleusercontent.com/-z8YutKRjoBs/WDV55LX3GVI/AAAAAAAAAUk/-0WLvzTUlusFW2v2s9nybCkUbtE7JtHZQCL0B/h1572/2016-11-23.png) for a better picture.
=> GGRC-471 Unify icon colors on info pane

src/ggrc/utils/revisions.py, src/ggrc/views/__init__.py
**This PR builds on top of: #4757** 
The previus PR fixes content for all new revisions and this is just a migration to update revisions for all existing objects.
Added please review because it's needed for tuesdays release.
To test this, you can manually mess up and revision content of an existing object and just run
```javascript
$.post('/admin/refresh_revisions')
```
=> GGRC-487, GGRC-490 Revision content update

src/ggrc/assets/stylesheets/modules/_menu.scss
See attached screenshots
_Actual Result:_ The red circle in My tasks section in top nav bar is too small, the third digit is not visible
_Expected Result:_ all 3 (or more) digits should be visible
=> GGRC-353 Fix the size of the circle for the number of tasks

src/ggrc/assets/mustache/assessments/modal_content.mustache, src/ggrc/assets/mustache/components/effective-dates/effective-dates.mustache
**Preconditions**:
1. Created program and audit
2. Add tab->Assessment
3. During Assessment creation click on [Hide all optional fields button]-> Save and Add Another
4. Look at New Assessment modal: additional optional fields are displayed
_Actual Result:_ Additional optional fields are displayed in New Assessment modal after click Save and Add Another button
_Expected Result:_ Additional optional fields should not displayed in New Assessment modal after click Save and Add Another button
=> GGRC-457 Restore modal state after save

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
1. Filter any WF from LHN
2. Click the link to open WF
3. Look at the screen: JS error is displayed
Actual Result: "Uncaught TypeError: (intermediate value).attr(...).attr is not a function" occurs if open WF
Expected Result: no error displayed if open WF
This issue is a regression caused by [PR](https://github.com/google/ggrc-core/pull/4771) - one edge case is missing. Tree View Controller is not initialised correctly.
This modification is only a quick fix - the best solution should be to unify interface for Tree View Controller and pass only well known and defined set of parameters.     
Also in a scope of this PR extra minor improvements were implemented by a separate commit.
=> GGRC-576 Update Tree View Controller to correctly render Workflows widgets

src/ggrc/settings/default.py, src/ggrc/templates/assessments_view/index.haml, src/ggrc/templates/layouts/dashboard.haml
In order for the analytics script to appear in the page, the `GGRC_GOOGLE_ANALYTICS_ID` environment variable must be set.
This PR can be verified by inspecting the page footer, i.e. the part where the copyright and version info is.
(added the `on hold` label due to code freeze)
=> GGRC-153 Add configurable Google Analytics script

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/dashboard.js, src/ggrc/assets/mustache/assessments/tree_header.mustache, src/ggrc/assets/mustache/audits/tree_header.mustache, src/ggrc/assets/mustache/base_objects/filter_trigger.mustache, src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache, src/ggrc/assets/mustache/base_objects/sub_tree_type_selector.mustache, src/ggrc/assets/mustache/base_objects/tree_column_selector.mustache, src/ggrc/assets/mustache/base_objects/tree_header.mustache, src/ggrc/assets/mustache/import_export/import_export_buttons.mustache, src/ggrc/assets/mustache/people/tree_header.mustache, src/ggrc/assets/stylesheets/modules/_tree-header.scss, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_header.mustache, src/ggrc_workflows/assets/mustache/cycles/tree_header.mustache, src/ggrc_workflows/assets/mustache/task_groups/tree_header.mustache
This PR moves action icons from the tree view header to the 3-dot dropdown menu.
Design screens are available at jira issue.
=> GGRC-473 Move tree header action icons to dropdown menu

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
This PR fixes unwanted automatic collapses of info pane.
The cause was the logic in the tree view controller that too eagerly reacted to every remove/unmap event. This fix adds some heuristics to skip refreshing the info pin if an object has been removed  in the latter, and not within the tree view itself.
**Disclaimer:**
Mind that a fix is really not that pretty, and the heuristics might fail in a few cases. Fixing this properly, however, would require to implement a consistent and reliable communication channel between the tree view and the info pane, but paying off that technical debt would be way too big of a task in scope of this fix, the tree view controller is just too patchy.
If anybody know a better solution, please do tell! I would be very happy to hear alternative suggestions. …
=> GGRC-307 Prevent info pin from collapsing when removing URL

src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
**(Temporary)** Hide "Get permalink" and "View <Object>" menu items as far as snapshot view still not exists.
=> GGRC-566+567 Hide unnecessary menu items for snapshot

src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
when creating a task with checkboxes, the checkboxes on cycle tasks are not label-clickable
=> GGRC-380 Fix label on checkboxes

src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/javascripts/components/tests/datepicker_spec.js
**Subject**: Effective Date and Stop Date fields automatically insert previously deleted values
**Details**: 
Click +Create New to create new program
Select Effective date and then Stop date
Delete value from Effective date field
Delete value from Stop date
Click outside of the date fields (anywhere on the modal window)
_Actual Result:_ Effective date is automatically filled with previously deleted value
_Expected Result:_ Effective date is not selected automatically
_Workaround_: NA
=> GGRC-366 Fix auto insert date in Effective date

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
This PR fixes bug in Unified Mapper when hitting enter key doesn't search with matching term correctly.
=> QUICK-FIX Search by Enter key in Unified Mapper

src/ggrc/assets/javascripts/controllers/tree_view_controller.js
1. Create wf
2. Go ti Setup tab and create Task
3. Activate WF
4. Go to Active Cycles tab
5. Click on grey triangle on first tier: confirm the second tier is not shown
_Actual Result:_ Second tier is not displayed for Active Cycles on WF page
_Expected Result:_ Second tier should be displayed for Active Cycles on WF page
=> GGRC-581 Fix second tier for Active Cycles tab

src/ggrc/automapper/__init__.py, test/integration/ggrc/automapper/test_automappings.py
This PR is an update of cherry-picked branch from #4569.
If you map a Section to an Audit (so that a Snapshot is created and mapped to the Audit and the Section is mapped to the Program), not all Relationships are logged yet.
=> GGRC-97 Fix automapper revisions

src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
This PR removes the minimum date restriction when selecting Workflow Task dates from the date picker widget.
1. Create a one time WF
2. Select a Task Group, click the `(+)` button in its info pane to create a new Task
3. Try to select Start date in the past - can only be done by manually changing the filed contents
Start/End Dates can be changed only manually in Task modal window, if the dates are related to past/present period
Start/End Dates can be selected from the calendar in Task modal window if the dates are related to past/present period
=> GGRC-397 Allow picking past dates for Tasks in date picker

src/ggrc/assets/javascripts/controllers/modals_controller.js
1. Create an Assessment Template with CA "one".
2. Open the editing modal for this Assessment Template.
3. Add a CA "two", don't save.
4. Close the modal, click "discard".
5. Open the editing modal for this Assessment Template again.
_Expected result:_ only CA "one" is displayed.
_Actual result:_ CAs "one" and "two" are displayed (note that "two" doesn't exist in the DB).
=> GGRC-462 Reset not saved CAD in AT

src/ggrc/assets/javascripts/controllers/modals_controller.js
**Subject**: Assignee is not selected on the first try from the dropdown list in New task window 
**Details**: 
Create WF
Go to setup tab
Navigate to Task’s group Info pane
Click + to Create New Task
Delete a default value in Assignee field
Select Assignee from drop down list: Assignee is not selected on the first try 
_Actual Result_: Assignee is not selected on the first try from the dropdown list in New task window 
_Expected Result:_ Assignee should be selected on the first try from the dropdown list in New task window 
_Workaround_: NA
=> GGRC-388 Fix selecting Assignee in New Task modal

src/ggrc/models/snapshot.py, src/ggrc/snapshotter/__init__.py
Relationships between snapshots must match relationships between the parent objects that were snapshotted.
Currently this is only visible in the database.
=> GGRC-584 Add relationships between snapshots

src/ggrc/templates/layouts/base.haml, src/ggrc_risks/templates/layouts/base.haml
**Update:** The  PR has been rebased onto the develop branch, thus there was nothing left to revert, just the existing GA script templates have been updated (which is the actual net effect of the changes in #4716 and this PR).
---
This PR merges the changes from #4716 with the existing Google Analytics script configuration. It essentially removes most of the #4716, but uses the latter's small change of the GA script template.
To verify the change, one should make sure the `GGRC_GOOGLE_ANALYTICS_ID` environment variable is set (to some Google Analytics ID), and the GA script will appear in the page source. On the other hand, if the variable is not set, the script is not inserted into the page as well.
=> QUICK-FIX Remove duplicate Google Analytics script config

bin/run_integration, src/ggrc/automapper/__init__.py, test/integration/ggrc/automapper/test_automappings.py
This function was causing a warning in our integration tests.
After some discussion and investigations we concluded that
creating automappings between Audit - Program - Request
is no longer necessary and all handlers need to be removed.
This PR was based on @zidarsk8 comments here https://github.com/google/ggrc-core/pull/4782#issuecomment-265856159.
=> QUICK-FIX Remove handle_relationship_post

src/ggrc/assets/mustache/dashboard/internav_list.mustache
This PR (probably) solves an issue with the object count missing in HNB (i.e. just an empty pair of parentheses is displayed).
The issue is difficult to reproduce, but it seems that it can only occur when the object count is zero, thus we simply display a zero by default. The ellipsis placeholder has been removed, because it seems like it is not used anywhere anymore (at least I haven't seen it for a long  time now).
---
**Steps to reproduce (if lucky :smile: ):**
2. Create an Audit
3. Go to Audit page
4. Look at HNB
Objects tabs are displayed without numbers in brackets at Audit tab
Objects tabs are displayed with numbers in brackets at Audit tab
=> GGRC-398 Show a zero in a tab if object count not available

src/ggrc/notifications/data_handlers.py, src/ggrc/templates/notifications/email_digest_content.html, src/ggrc/utils/__init__.py, src/ggrc_workflows/notification/__init__.py, src/ggrc_workflows/notification/data_handler.py
**Subject:** the daily digest says the request "starts 1 day ago"
**Details:**   
The daily digest sends weirdly formatted message mixing tenses.
**Actual Result:** the daily digest says the request "starts 1 day ago"
**Expected Result:** the daily digest should say the request "started 1 day ago"
**Workaround:** NA
=> GGRC-289: Fix date-related tenses in email digest

src/ggrc/converters/base_block.py, src/ggrc/converters/errors.py, src/ggrc_workflows/models/cycle_task_group_object_task.py, test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
**GGRC-500** Show warning for all values that can't be changed during import by user
- Prepare 2 historical tasks and 2 active tasks
- Add non importable columns and import updated csv file
- Check that only one warning message is displayed for all restricted columns
**Example:** csv file w/cycle tasks contains non importable fields (e.g. status, delete, map: program)
During import the next warning should be shown: "Only next columns are importable: title, description, start/end/finish/verified dates. All the others columns will be ignored"
---
**How to reproduce the issue:**
1.  Create Workflow/Task Group/Tasks.
1. Activate workflow. (Wait until new cycle-tasks will be created.)
1. Export existing cycle-tasks. Choose any non-importable fields for cycle-tasks. This is any other except …
=> GGRC-500 Replace bulk of warnings with only one

src/ggrc/models/mixins/with_similarity_score.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
_`needs work` is added because tests are still missing but if we absolutely must merge for tuesdays demo I believe it's ready to be merged and I can add tests later._
This finds all related objects by:
1) finding all mapped snapshots
2) join with snapshots (left_snapshots) to find child_type and
child_id of all mapped snapshots
3) join witn snapshots (right_snapshots) to find all snapshots
of the same objet
4) find all mapped objects to right_snapshots
This prepares the following SQL statement:
````
SELECT right_relationship.source_type AS similar_type, right_relationship.source_id AS similar_id, right_snapshot.child_type AS related_type
FROM relationships AS right_relationship, snapshots AS right_snapshot,
(SELECT snapshot_ids.snapshot_left_id AS snapshot_ids_snapshot_left_id, …
```
=> GGRC-447 Add support for finding related objects via snapshots table

docs/source/guidelines/git/reviewing_pull_requests.rst
This PR updates the guidelines to include the more recent GitHub labels, and updates the section on approving/merging pull requests to take new GitHub features into account.
**Tip:**
You can see the docs in action by running `build_docs` from inside your container, and then open the local `docs` folder in a browser. If you get import errors when building the documentation, try running the ` pip install -r src/requirements-dev.txt` command first.
=> QUICK-FIX Update the docs on Github labels and PR reviews

src/ggrc/snapshotter/__init__.py, src/ggrc/snapshotter/helpers.py
A bit overdue task from my TODO - marking as `critical` because it would be really nice to know when there are missing revisions in production.
=> QUICK-FIX Add logging warnings for missing revisions

src/ggrc/assets/javascripts/components/assessment_generator.js, src/ggrc/assets/javascripts/components/relevant_filters.js, src/ggrc/assets/javascripts/components/snapshot-loader/snapshot-loader.js, src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/mustache/mapper/relevant_filter.mustache, src/ggrc/assets/mustache/modals/mapper/base.mustache, src/ggrc/models/hooks/assessment.py, test/unit/ggrc/models/hooks/test_assessment.py
This is an expension of https://github.com/google/ggrc-core/pull/4838.
This PR makes the audit relevant filter read only, because removing the relevant filter makes no sense and it actualy causes the fronend to send an invalid query.
The frontend creates an invalid query if there is no additional filter specified (text filter or relevant filter) so making the relevant filter as read only is the best quick fix for that since we already discussed this with the UX people.
Second thing this PR does is fixing the default people lists specified in the template. Please note that if the values are missing in the snapshot, they will also be missing here, but that might be a bug in the revisions code and not in the setter for default people.
@andrei-karalionak I have cherry-picked your commit into …
=> GGRC-614 Assessment generation with inscope objects

src/ggrc/assets/stylesheets/modules/_comments.scss, src/ggrc/assets/stylesheets/modules/_tree-content.scss, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
This PR fixes a displaced "comment actions" menu for Cycle Task comments. This was caused by a missing CSS class that prevented for some necessary styles to be applied.
One thing that I noticed is that if a context menu is opened for the last comment (need to have at least 3 of them, I think), a vertical scroll bar appears because the context menu expands the comment list `<div>`, and the latter's height is restricted to 240 px (the context menu is a part of that div).
One way around it would be to lift the height restriction and set the `overflow-y` property to `auto`, but that causes other issues, namely the height of the info pane's contents to explode if there are too many comments and/or objects mapped to the Task.
The latter seemed like a worse option, thus I did not opt for it, and …
=> GGRC-393 Fix task comments' context menu positionig

src/ggrc/migrations/versions/20160728140921_2a5a39600741_add_snapshot_model.py, src/ggrc/migrations/versions/20161123124848_1f5c3e0025da_remove_control_id_column_from_.py
The develop branch should only add migrations on top of any chain that
has already been deployed.
=> QUICK-FIX Fix migration chain on develop

src/ggrc_workflows/assets/javascripts/components/end_cycle.js, src/ggrc_workflows/assets/javascripts/components/workflow_active.js
This PR fixes active cycles count is not refreshed when starting the workflow from other tabs. It also fixes issue for active cycles tree is not updated.
=> GGRC-114 Fix counts are not refreshed after starting the workflow

src/ggrc/models/hooks/assessment.py
The validator for custom attribute names needs to have the link between
the assessment and the custom attribute definition to work properly.
This is done by sqlalchemy on flush. In some cases the flush gets called
in the check_permissions step, but this ensures we have all the data
flushed before generating the needed links for assessments.
Ticked description:
> Precondition:
> Created program, control, audit
> 1. Go to audit page
> 2. Create Assessment template with custom attributes
> 3. Create assessment
> 4. Select Generate Assessments in 3 dots menu
> 5. Select Assessment template and Control for generation: Assessment generation failed
> Actual Result: Assessment generation failed if select Assessment template for generation
> Expected Result: Assessment should be generated if …
=> GGRC-629 Fix assessment generation with templates

src/ggrc/assets/javascripts/components/datepicker/datepicker.js
**Details**: 
Click +Create New to create new program
Select Effective date and then Stop date
Delete value from Effective date field
Click on Stop Date field
_Actual Result_: We still have the restriction in 'minDate'
_Expected Result_: We shouldn't have the restriction  in 'minDate' or 'maxDate' if sibling field is empty
=> GGRC-366 Fix min/max date after change value in datepicker

src/ggrc/snapshotter/__init__.py, test/integration/ggrc/snapshotter/test_snapshoting.py, test/integration/ggrc_basic_permissions/test_creator_program.py
_Adding `needs work` since I want to see all tests will die because of this_
Replace base object -> snapshot mappings with audit -> base object since original was just data duplication that will be removed in the near future.
=> QUICK-FIX Save Audit -> object relationships

src/ggrc/assets/javascripts/components/object_counter/object_counter.js, src/ggrc/assets/javascripts/components/object_counter/tests/object_counter_spec.js, src/ggrc/assets/mustache/base_objects/page_header.mustache, src/ggrc/assets/mustache/components/object_counter/object_counter.mustache, src/ggrc/assets/stylesheets/modules/_menu.scss
This PR fixes live updating of the My Tasks counter color when the number of overdue tasks changes from zero to non-zero (or vice  versa).
---
1. Go to My work page
2. Select Tasks tab in HNB
3. Change one of your own task's task due date, so that an overdue task becomes not overdue (or vice versa - a not overdue task becomes overdue)
My task balloon (in the top navigation bar) doesn't change the color from grey to red and vice versa while changing the task due date
My task balloon should be change the color from red to grey while changing the task due date.
Balloon should be red if at least one of task is overdue, otherwise grey
=> GGRC-385 Live update Task counter color

src/ggrc/migrations/versions/20161215004956_587e41a1593d_add_missing_snapshot_relationships.py
This adds the missing relationships between original objects and audits,
that are being generated since the PR #4855.
=> QUICK-FIX Add missing snapshot relationships

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
2. Click Autogenerate button in Audit summary page
3. Click Enter 
_Actual Result_: "Uncaught TypeError: Cannot read property 'getResults' of undefined" error occurs while clicking enter in Unified mapper
_Expected Result_: no error displayed
=> GGRC-652 Fix js error on generate assessment modal

src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/templates/admin/index.haml
**Steps**:
1. Open Assessment tab at Audit page
2. Click Select Child Tree Object Type and select any checkboxes
3. Go to Admin dashboard page
_Expected results_: the admin dashboard is shown.
_Actual results_: the page freezes with spinner, no controls are shown, JS error "Uncaught can.Map: Object does not exist" is reported in the console.
Workaround (to make admin dashboard working):
1. With the app opened, open Developer tools
2. Go to Application tab
3. Choose Local Storage -> the server you encountered this problem on (for instance, grc-test.appspot.com)
4. Delete every line with "display prefs" prefix.
=> GGRC-405 Fix error on admin dashboard page

src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/javascripts/models/audit_models.js
This PR adds an ability to re-fetch objects list based on the url hash flag.
This allows to redirect user by url from object creation modal dialogs to the objects list + refreshing it to get actual list state.
Fixes assessment templates are not refreshed after adding assessment template from info widget tab.
=> GGRC-452 Add refetch url hash option. Fix assessment templates are not refreshed.

src/ggrc/assets/javascripts/controllers/modals_controller.js
This PR fixes an issue with the comment rich text box not being cleared after clicking the `"Save & Add Another"` button in the add comment modal.
(no unit tests, because an e2e test would make more sense here, and those are being developed in a separate development path)
---
Have an active WF with Task
1. Navigate to Task’s Info pane at Active Cycles tab
1. Click Add comment button
1. Enter comment into comment field
1. Click Save and Add Another button: confirm Comment field is not cleaned
Comment field in New comment window is not cleaned after clicking Save and Add Another button when add a comment to Task
Comment field in New comment window should be cleaned after clicking Save and Add Another button …
=> GGRC-394 Reset comment field on clicking Save & Add Another

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
The custom_attributes field has been replaced with
custom_attribute_values to better match the actual response content that
the front-end should receive.
For verification:
Check that custom attribute values are correct on snapshots (Ignore the date value).
after merging, wait for deployment and then run 
```javascript
$.post('/admin/refresh_revisions')
```
=> GGRC-670 Remove obsolete attribute from revision content

src/ggrc/assets/javascripts/controllers/tree_view_controller.js, src/ggrc/assets/mustache/audits/search_result.mustache, src/ggrc/assets/mustache/base_objects/search_result.mustache, src/ggrc/assets/mustache/people/search_result.mustache, src/ggrc/assets/mustache/programs/search_result.mustache, src/ggrc/assets/stylesheets/modules/_spinner.scss, src/ggrc/templates/layouts/base.haml, src/ggrc_workflows/assets/mustache/workflows/search_result.mustache
This PR fixes a UX inconvenience that caused users to see two spinners while waiting for the tab content to load.
The fix, however, does not remove the existing tree items loading spinner, because the latter is still useful for pagination, etc. Instead, it styles it along the tab content spinner, so that both look like a single spinner to end user.
Also, the main tree loading spinners in LHN have been updated as well, although the PR does not attempt to update each and every spinner in the app (the ticket does not mention it, nor was this mentioned in the updates). But if unifying just about every spinner out there is in scope of this PR (please confirm with somebody), then please let me know, and also update the time estimate on the ticket. Or, alternatively, make sure a separate ticket …
=> GGRC-529 Unify main spinners

src/ggrc_basic_permissions/migrations/versions/20161209093634_89d8ca4c1267_make_user_roles_context_id_a_fk.py
This PR removes the context-less roles from the DB (since they can't be reused any more) and adds a FK constraint on `context_id`.
This migration doesn't conflict with Alembic upgrade and migration conflict PRs.
=> GGRC-607 Make user_role.context_id a FK

src/ggrc/models/mixins/customattributable.py
We must make sure to delete all GCA properties when using the legacy
API. This includes special property names for person GCA fields.
To test this:
Edit any object (except assessment) with person GCA value set.
=> GGRC-491 Fix CA indexing on the old API

src/ggrc/assets/javascripts/components/csv/import.js
Errors should be before warnings during file importing
1. Export active WF w/tasks
2. Change for assignee for 1 task
3. Add new task
4. Login as GC and try to import this file
Expected results: Error is displayed on top, warning is displayed below error message
=> GGRC-499 Change order of warnings and errors in /import

src/ggrc/assets/javascripts/components/view-object-buttons/view-object-buttons.js, src/ggrc/assets/mustache/components/view-object-buttons/view-object-buttons.mustache
This PR disabled opening info pane and changing url hash when opening objects with open button in a new tab.
=> GGRC-530 Disable changing url hash on opening object in a new tab

src/ggrc/assets/javascripts/models/person.js
1. Create a new program
2. Got to people tab, click map and click search in the Unified mapper
3. Map a new person to the program
4. Refresh the page: a script error appears
_Actual Result_: "Uncaught TypeError: Cannot read property 'reify' of undefined" error occurs if refresh the page after mapping a current user to program
_Expected Result_: no error displayed after refreshing a page
**NOTE**: I couldn't reproduce this issue locally. Only on grc-epic-1 server
=> GGRC-672 Fix js error on people tab

src/ggrc/assets/mustache/mixins/stateful.mustache
This PR hides undo action button when Assessment returns to In Progress state after editing CA fields.
=> GGRC-496 Hide undo button when Assessment returns to In Progress state

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Precondition:
1. Go to audit page-> Assessment teplate tab
2. While Assessment teplate creating open dropdown list with Objects under Assessment: confirm the list contains not snapshotable objects (e.g. People, Issues, Programs)
Actual Result: Object under assessment dropdown list contains not snapshotable objects in Assessment template modal window
Expected Result: Object under assessment dropdown list should contains only snapshotable objects in Assessment template modal window
=> GGRC-640 Exclude not snapshotable objects under assessment

src/ggrc/models/mixins/with_similarity_score.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
This fixes the issue with join where wrong table was being references, adds support weighting by object instead of weighting by type and adds tests that were missing from #4833 .
=> GGRC-447 Relavant objects for snapshots tests

src/ggrc/models/mixins/customattributable.py
Test that snapshot content contains all CAV values except dates
This should work if object is created or edited via API or imports.
Fixes: GGRC-670, GGRC-561
=> GGRC-670 Fix snapshot cav

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache
Created Program, Control, at least 2 Regulations, Audit
1. Go to the audit page->Assessment's tab
2. Generate at least 2 Assessments based on Control
3. Generate at least 2 Assessments based on 2 Regulation
4. Navigate to Assessment's Info pane one of the generated Assessments-> Related Assessments tab
5. Look at the list: real objects are shown (e.g. Program, Audit)
Actual Result: Snapshots of mapped to Assessment objects are not shown in Related Assessments tab in Info pane
Expected Result: Snapshots of mapped to Assessment objects should be shown in Related Assessments tab in Info pane
=> GGRC-685 Snapshots of mapped to Assessment objects are not shown in Related Assessments tab in Info pane

test/integration/ggrc/converters/test_import_helpers.py
All column definition tests should use the test helper function that
also verifies for non expected mandatory and unique columns. In the case
of Audit tests the missing mandatory column was Status.
The first commit in this PR fixes a test that should have failed in https://github.com/google/ggrc-core/pull/4890
=> QUICK-FIX Update column definition tests

src/ggrc/services/common.py, src/ggrc/utils/revisions.py, test/integration/ggrc/converters/test_csvs/policy_basic_import.csv, test/integration/ggrc/converters/test_csvs/policy_basic_import_update.csv, test/integration/ggrc/converters/test_import_update.py
Note: This is not a nice solution so I am open for any suggestions of a better implementations. 
This PR fixes object owners on snapshots of newly created objects. The owners will now appear in the tree view and in the snapshots info pin.
=> GGRC-487 Display object owners in snapshots

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Precondition:
2. Create at least 2 Assessments
3. Add URL in Assessment's Info pane one of the Assessments 
4. Navigate to Assessment's info pane of second Assessment-> Related Assessments tab
5. Look at Evidence column: URL is not displayed
Actual Result: Evidence is not shown in Related Assessments tab in Assessment's Info pane
Expected Result: Evidence should be shown in Related Assessments tab in Assessment's Info pane
=> GGRC-723 Evidence is not shown in Related Assessments tab in Assessment's Info pane

src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-item.js, src/ggrc/assets/javascripts/components/snapshot-loader/snapshot-loader.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Precondition:
Created program, audit, at least 10 controls
2. Select Generate assessment in 3 bb's menu 
3. Click Search controls
4. Select several Controls in Search list, go to another page, select a control, return to the previous page: confirm that already selected checkbox is not marked
Actual Result: Already selected checkbox is not marked if return on previous page in Unified mapper 
Expected Result: Already selected checkbox should be marked if return on previous page in Unified mapper
=> GGRC-725 Already selected checkbox is not marked if return on previous page in Unified mapper

src/ggrc/assets/stylesheets/modules/_inline-edit.scss
1. Navigate to audit page and open Assessment’s info panel
2. Add a comment
3. Find your comment in comments list below (page refresh may be needed)
4. Edit your comment inline
_Actual Result_: accept and close icons are off their places (see the screenshot)
_Expected Result:_ fix the look of the control icons (eg as on the second screenshot)
=> GGRC-355 Fix styling buttons for confirm inline edit 

src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
This PR fixes audit is not refreshed on the info panel after editing it in edit modal.
Ticket description:
Subject: Audit folder is not removed from Audit's Info panel after Edit Audit
Details:   
Create program
Create an Audit> Assign folder while creating an Audit> Save and Close
Navigate to Audit’s Info panel> Click 3 bb’s button> Edit Audit
Click trash icon to delete folder> Save and Close
Look at Audit’s Info panel: Audit folder is not removed from Audit's Info panel
Actual Result: Audit folder is not removed from Audit's Info panel after Edit Audit
Expected Result: Audit folder should be removed from Audit's Info panel after Edit Audit
Workaround: Refresh the page
=> GGRC-287 Fix audit folder is not refreshed after edit

src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
This PR fixes js error after changing date on wf create task modal.
1. Create one-time WF
2. Go to Setup tab
3. While creating a task change start date to date later (e.g. yesterday)-> Save and Close
Actual Result: "Uncaught TypeError: instance.errors is not a function" error is displayed while creating a task in WF
Expected Result: no error displayed. A task is created and displayed in Task's Group Info pane
=> GGRC-708 Fix js error after changing date on wf create task

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
Precondition
Created program, Control, audit
1. Go to Audit pag
3. Click Map button on the first tier of the tree view
4. Select any object-> Search -> Select an object from the Search List
5. Map Selected: confirm error occurs
Actual Result: 'NoneType' object has no attribute 'type' error is displayed while mapping an object in scope of the audit to Assessment/Issue
Expected Result: no error displayed while mapping
=> GGRC-729 'NoneType' object has no attribute 'type' error is displayed while mapping an object in scope of the audit to Assessment/Issue

src/ggrc/assets/mustache/components/inline_edit/inline.mustache, src/ggrc/assets/mustache/custom_attributes/info.mustache
This PR changes inline edit title attribute name to avoid collision with html tag attribute.
1. Navigate to admin dashboard => people tab
2. Open user’s 2nd tier by clicking grey triangle in the 1st tier
3. Hover over the editing CA field on object’s info panel
Actual Result: weird global CA field title “cad.title” is shown when hovering mouse over CA field editing field on info panel
Expected Result: either it should show CA’s title (eg label) or show nothing
=> GGRC-349 Change attribute name to avoid collision

src/ggrc_workflows/assets/mustache/cycle_task_entries/tree_footer.mustache
This PR fixes the bug that prevented the Add Comment button from being shown on Task's info pane. Essentially it uses "instance" in the template instead of "parent_instance" that no longer (?) exists.
This issue has the `Blocker` priority, hence the `critical` label.
---
Active WF with Task
- Navigate to Task’s Info pane at Active Cycles tab
- Look at Add comment button: is not shown
[Add comment] button is not shown in Task's Info pane
[Add comment] button is shown in Task's Info pane
=> GGRC-709 Restore missing "Add Comment" button for WF Tasks

src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/mustache/components/assessment/inline/date.mustache, src/ggrc/assets/mustache/components/inline_edit/datepicker.mustache
This PR assures that the date picker calendar is closed after choosing a date from it.
Note that there are two different inline edit widgets in use, one for Assessments and one for other object types. When verifying, please make sure to check both.
* Navigate to Assessment with the date field
* Try to edit date value via info panel
The custom attribute date field shows the date picker after choosing a date
the date picker should disappear after picking a date
=> GGRC-363 Close datepicker calendar after choosing a date

src/ggrc/assets/javascripts/components/csv/export.js
1. Go to Admin Dashboard
2. Data Export
3. Select any object type for export (e.g. Programs)
4. Select mapped to any Object (e.g. Access Group) and don't select the title of the Access Group (but dropdown list is shown)
5. Click on Export Objects button: confirm JS error displayed
_Actual Result_: an error occurs while clicking Export Objects button if the object's title is not selected from dropdown list
_Expected Result_: no error displayed
_Tech details_: The server returns HTTP400 with the error because the "relevant" object is not chosen in the search field. The UI should either forbid clicking "export objects" when no "relevant" object is chosen, or not include the "relevant" filter for this type in the request to the server.
=> GGRC-510 Fix empty filter on export page

src/ggrc/assets/javascripts/controllers/info_pin_controller.js
This PR fixes blank info pane after deleting object from 3bb dropdown menu.
1. Navigate to assessments tab on audit page 
2. Open assessment’s 2nd tier with mapped objects
3. Click on mapped object’s 1st tier to open its info panel
4. Click 3bbs button and select delete button
5. Confirm deletion: Blank Info panel is displayed
Actual Result: Blank Info pane is displayed in Assessment tab after deleting an object that is mapped to an Assessment
Expected Result: Blank Info pane should not displayed in Assessment tab after deleting an object that is mapped to an Assessment
=> GGRC-387 Fix blank info pane after deleting object

src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
1. Create annual WF
2. Click = to create a task in Task's group Info pane: confirm JS error is displayed
Actual Result: "Uncaught TypeError: Cannot read property 'relative_start_day' of undefined" error is displayed while creating a task for annual WF
Expected Result: no error is displayed while creating a task
=> GGRC-714 Fix js error on annual tasks

src/ggrc/settings/default.py
When we decided to bump the minor version so that we could update the patch version for our patches we forgot to update the version displayed in the app itself. This PR corrects this.
=> QUICK-FIX Update raspberry version to 0.10.0

src/ggrc/assets/javascripts/controllers/tree/list_view_controller.js, src/ggrc/assets/mustache/people/filters.mustache, src/ggrc/services/common.py, test/integration/ggrc/services/test_common.py
1. Go to Admin Dashboard
2. People's tab
3. Open "By roles" filter  and select no role: confirm admin can't filter user with no-role permissions
**Actual Result:** admin can't filter user with no-role permissions
**Expected Result:** admin should filter user with no-role permissions and No role permission should exist in drop down list in "By roles" filter
Provided solutions is ugly. But it could be improved a little bit with moving hardcoded things into model part. Front-end part should send **GET** request via next link:
http://localhost:8080/api/people?__sort=name%2Cemail&__page=1&__page_size=50&_=1481893854715&__no_role=true
@egorhm already reviewed this PR's solution and proposed to add new user_role: **no_role**.
Highly appreciate any proposals about how to …
=> GGRC-370: Add "No Role" user filtering into back-end

src/ggrc/models/mixins/autostatuschangeable.py, test/integration/ggrc/models/mixins/test_autostatuschangable.py
This PR fixes automatic transitions to "In Progress" state for Assessments (and other AutoStatusChangeable objects) upon editing a Person CA.
---
* Create GCA type Person for Assessment
* Create Assessment
* Change status to "Ready for Review" or "Verified"
* Open inline edit for GCA (press confirm in modal), change value and Save
Assessment Status not changed
Assessment's status should be changed
(screencast: http://www.screencast.com/t/gmkMPnEUVWHI)
=> GGRC-459 Fix Assessment status change on Person CA edit

src/ggrc_workflows/migrations/versions/20161227105336_e807dc2ce1a_remove_cycle_task_group_objects.py, src/ggrc_workflows/models/cycle_task_group.py
This PR removes an obsolete table from the DB.
The data from this table is migrated in `ggrc_workflows:1263c1ab4642` (see #3605).
=> QUICK-FIX Remove cycle_task_group_objects

src/ggrc/assets/mustache/audits/search_result.mustache
This PR removes obsolete behavior for opening My Work page on clicking the Audit link in LHN.
Preconditions:
1. Created program, audit, assessment with assignee (progcreator@reciprocitylabs.com)
1. Log as progcreator@reciprocitylabs.com (engage007)
2. Open LHN and search the created audit
3. Click on the audit in LHN after search: confirm My Work page is displayed
Actual Result: My Work page is displayed after search for an audit in LHN and click on it under GC role
Expected Result: Audit Info page is displayed after search for an audit in LHN and click on it under GC role
=> GGRC-456 Fix obsolete link for view audit on LHN

src/ggrc/converters/query_helper.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
Currently similarity query is performing unstable sort - this should sort by weight first and ID second and as such should return the same results always.
Not critical since we have a fix for test that performs comparison by weight but this is the proper solution so I'm opening PR nonetheless.
=> QUICK-FIX Add stable sort for similarity

src/ggrc_basic_permissions/roles/Reader.py
Readers should not have the permission to create user roles unless they
get the permission from a different source (e.g. they are program
owners).
=> GGRC-268 Prevent Readers from creating UserRoles

src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/javascripts/components/inline_edit/inline_datepicker.js, src/ggrc/assets/javascripts/components/tests/datepicker_spec.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/mustache/components/assessment/inline/date.mustache, src/ggrc/assets/mustache/components/datepicker/datepicker.mustache, src/ggrc/assets/mustache/components/inline_edit/datepicker.mustache, src/ggrc/builder/json.py, src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/converters/query_helper.py, src/ggrc/models/custom_attribute_value.py, test/integration/ggrc/models/test_snapshot.py
This PR that attempts to unify the date formats used on the frontend.
Date strings must now be in ISO format and are assumed to be in UTC timezone (just like on the server), and are transparently converted to a different format only when and where required for presentation purposes. Also, the backend now only accepts ISO dates only (workarounds for date CustomAttributeValues have been removed) - need at least @zidarsk8 (or his drop-in replacement) to review that part, and maybe to advise on updating the integration tests as well, since I do not know exactly what parts of the code are just a temporary CA Date value workarounds.
The two main sources where string <---> Date conversions happen on the frontend (often incorrectly because of local time zones) are date pickers and serialization …
=> GGRC-624 Unify date string representations on frontend

src/ggrc_workflows/models/cycle_task_group_object_task.py, src/ggrc_workflows/models/task_group_task.py
1. Create a one-time Workflow.
2. Go to Active Cycles tab.
3. Click "Create New".
4. Select "Dropdown" (or "Checkbox") in task type dropdown, leave "Selection Response Options" textarea empty.
5. Click "Save & Close".
Expected result: the task is created, no errors occur.
Actual result: the task is created, JS error `(this.attr(...) || []).join is not a function` occurs.
=> GGRC-661 Fix default values of response options

src/ggrc/assets/javascripts/components/tree/tree-type-selector.js
**Description**:
- From My Work page open any tab
- on Tree-View press 3bb's -> Select Child Tree Object Type
_Actual_: get error "Uncaught TypeError: Cannot read property 'display_list' of undefined"
_Expected_: no error
=> GGRC-730 Fix error on Select Child Tree Object Type menu

src/ggrc/services/common.py, src/ggrc/utils/revisions.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/converters/test_import_update.py, test/integration/ggrc/snapshotter/test_snapshoting.py, test/integration/ggrc_basic_permissions/test_creator.py
This commit reverts the functionality from https://github.com/google/ggrc-core/pull/4893/commits/c5c610f87a3de8843ed46d7682c2f9d43ff97913
The reverted commit caused a regression where editing object owners via
import would also edit other values in the revision, and with that break
our snapshots functionality. The result of this commit is that on object
owner edits there is an extra event logged for original object
modification.
The difference in the log can be seen here:
To test this PR you should verify the ticket GGRC-487
- make sure object owners appear in snapshots for new object, that are created via web UI or with imports.
- make sure correct object owners are displayed after editing the object (ui and imports)
=> GGRC-724, GGRC-487 Revert amend last revision with owners

src/ggrc/assets/javascripts/models/directive_models.js
This PR fixes GCA field update on Regulation entities.
Precondition:
1. Created GCA with e.g. rich text type, checkbox for Regulation, created program, Regulation and audit
1. Navigate to Regulation's Info pane on Program page
2. Fill in GCA field from precondition: confirm the error occurs
3. Refresh the page and look at GCA: the values are not saved
Actual result: "There was a problem saving" error occurs while filling GCA field in Regulation's Info pane
Expected Result: no error displayed. The value in GCA field is saved
=> GGRC-726 Fix setting GCA value on Regulations

src/ggrc/migrations/versions/20170103101308_42b22b9ca859__fix_audit_empty_status.py, src/ggrc/models/audit.py
**Details:** 
Navigate to https://grc-dev.appspot.com/programs/4051#audit_widget/audit/1477 
**Actual Result:** one of the audits has no status
**Expected Result:** all the audits should have the status
**Workaround:** change the status manually
**Additional info:** most likely this audit was created during the time when we had the issue with status dropdown but we need to check it one time more to make sure the issue like this won’t leak to UAT.
=> GGRC-362 Audit with no status exists on DEV

src/ggrc/utils/revisions.py
This PR adds logic to insert lost revisions:
1. For a lost object with no "deleted" revision, create a copy of this object's last revision with `action="deleted"`.
2. For an object with no revisions and `created_at == updated_at`, create a new revision with `action="created"` and `content=obj.log_json()`.
3. For an object with no revisions and `created_at != updated_at`, create a new revision with `action="modified"` and `content=obj.log_json()`.
=> GGRC-33 Add logic to recreate lost revisions

src/requirements-dev.txt
Bring factory-boy requirements into epic/snapshots branch.
This is needed for #4942
=> QUICK-FIX Update factory-boy in epic/snapshots branch

src/ggrc/migrations/versions/20161221084829_1aa39778da75_migrate_requests_to_assessments.py
This PR adds a migration to create Assessments from Requests.
~I'm putting this PR `on hold` until the next migration that cleans the Request data from the DB is ready to be merged as well.~
This PR can be safely merged even before the cleanup migration is merged (as long as we don't perform downgrades on the dev servers before applying the cleanup migration later on).
=> GGRC-590 Migrate Requests to Assessments

src/ggrc_risks/models/risk.py
This PR adds a missing backref that caused `ObjectPerson.log_json()` to log a warning when `ObjectPerson.personable_type == 'Risk'`.
=> GGRC-749 Fix Risk_personable backref

src/ggrc/assets/javascripts/models/cacheable.js
This PR fixes an error when serializing a Task object of type "dropdown" that has not response option selected. It was caused by a bug in the generic model serializer when serializing Array elements that are `undefined` or `null`.
No unit tests, because refactoring the `serialize()` method should probably be done first, i.e. splitting it into multiple smaller methods, as an already existing code comment suggests.
NOTE:
If any (?) of the workflow's Task Groups contains more than one task, you might not  be able to review this PR due to another issue in the `tasksSortList` component (sorting by dates that are ISO strings. This will be handled in a separate PR.
---
Activated annually WF with at least one Task of type "dropdown"
1. Go to Active Cycles …
=> GGRC-737 Fix script error when commenting on Dropdown Task

src/ggrc/assets/javascripts/components/assessment/inline.js
1. Navigate to Assessment Info pane in audit page
2. Change the value in GCA field with Person type from precondition: confirm Assessment changes the status to In progress
3. Click Complete button
4. Click Verify button
5. Change the value in GCA field 
**Actual**: Saved message and spinner are displayed if edit and don't save the changes in GCA field with Person type in Assessment's Info pane
**Expected**: Saved message and spinner should not displayed if edit and don't save the changes in GCA field with Person type in Assessment's Info pane
=> GGRC-596 Fix save input data on cancel

src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache, src/ggrc/assets/mustache/custom_attributes/info.mustache
CA are edited in snapshotable objects on audit page
Precondition:
Created any GCA for Control, program, control with the value in GCA, audit
2. Edit GCA value in Control's Info pane: confirm GCA value is edited and "There was a problem saving" is displayed
Actual Result: CA are edited in snapshotable objects on audit page
Expected Result: CA should not be edited in snapshotable objects on audit page
=> GGRC-771 Disable editable custom attributes

src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/javascripts/models/cacheable.js
This PR fixes app freeze on delete mapped object.
Precondition:
2. Create Assessment and map several objects to assessment through unified mapper (e.g. Access Group)
3. In Assessment's tab open second tier in tree view and select the mapped object (Access Group)
4. Expand 3 bb's menu in Access Group Info pane
5. Click Delete button: the system freezes
6. Click Delete button once again: "access group not found." error message is displayed
Actual Result: The app freezes if delete mapped object to audit from second tier in Assessment tab
Expected Result: The app should not freeze if delete mapped object to audit from second tier in Assessment tab. The objected is deleted form the tree view.
=> GGRC-740 Fix app freeze on delete mapped object

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
Precondition:
Created mandatory GCA with person type for assessment, program, audit
1. Go to audit page-> Assessment's Info pane
2. Create assessment and add a Verifier
3. Fill in all GCA in Assessment's Info pane->Click Complete button
4. Remove a person from mandatory GCA with person type: confirm Complete button is not disabled
Actual Result: Complete button is not disabled in Assessment's Info pane if mandatory GCA is not filled in
Expected Result: Complete button should be disabled in Assessment's Info pane if mandatory GCA is not filled in
=> GGRC-750 Complete button is not disabled in Assessment's Info pane if mandatory GCA is not filled in

src/ggrc/assets/javascripts/components/tree/tree-type-selector.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/mustache/base_objects/sub_tree_type_selector.mustache
1. From My Work page open any tab
2. On Tree-View press 3bb's -> Select Child Tree Object Type
3. Look at "Select child tree object type for" field: is empty
Actual Result: Widget title is not selected by default in Select child tree dialog
Expected Result: Widget title should be selected by default in Select child tree dialog
Note: if "Select child tree object type for" field is not selected and click on Select all -> Set Visibility -> "Uncaught Error: can.Map: Object does not exist" error is displayed
=> GGRC-761 Fix select child tree dialog

src/ggrc/assets/javascripts/components/assessment_attributes.js
1. Go to audit page->Assessment template tab
2. While assessment template creation add attribute title and do not select attribute type
3. Click Add field
_Actual Result_: Uncaught TypeError: Cannot read property 'name' of undefined error is displayed while adding LCA without type in New AT modal window
_Expected Result_: no error displayed. Attribute type should be selected by default.
=> GGRC-778 Fix default dropdown's value in AT modal

src/ggrc/assets/javascripts/components/assessment/inline.js, src/ggrc/assets/javascripts/components/ca-object/ca-object-validation-icon.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js, src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache
Precondition:
Created mandatory GCA for assessment, program, audit
2. Create Assessment-> Navigate to Info pane
3. Fill in the GCA field form precondition: confirm is marked as unfilled
Actual Result: Filled mandatory CA is marked as unfilled in Assessment's Info pane. Refresh is needed.
Expected Result: Filled mandatory CA should be marked as filled (e.g. [^Filled mandatory CA field.png]) in Assessment's Info pane
=> GGRC-713 Filled mandatory CA is marked as unfilled in Assessment's Info pane

src/ggrc/converters/query_helper.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
Reverts google/ggrc-core#4889 that causes a regression with non-functional "Related Assessments" tab.
=> GGRC-779 Revert "QUICK-FIX Add stable sort for similarity"

src/ggrc/migrations/env.py, src/ggrc/migrations/utils/__init__.py, src/ggrc/migrations/utils/migrator.py, src/ggrc/migrations/utils/resolve_duplicates.py, src/ggrc/migrations/versions/20161117114904_142272c4a0b6_migrate_audits_for_snapshots.py, src/ggrc/migrations/versions/20161220161315_275cd0dcaea_migrate_assessments_issues_data.py
Test cases that **_have_** to be performed by the reviewer (if more, the merrier):
* usual and correct program and audit with some snapshottable objects
* getting warnings if assessments/issues are mapped to multiple audits
* getting warnings if assessments/issues are orphaned (mapped to 0 audits)
* if assessment/issue is mapped to snapshottable objects that ARE NOT in program scope - ensure object is mapped to program after migration and that snapshot of that object exists
* if assessment/issue is mapped to snapshottable objects that ARE NOT in audit scope - ensure object is snapshotted and relationship between object and program exists after migration and that snapshot of that object exists
* if assessment/issue is mapped to snapshottable objects that ARE NOT in BOTH audit AND program …
=> GGRC-465 Create snapshots for existing audits and assessments and issues

src/ggrc/assets/javascripts/components/object-list/object-list.js, src/ggrc/assets/mustache/components/object-list/object-list.mustache
2. Create or generate at least 10 assessments (in order to have opportunity to follow to the next page in Related Assessments tab)
3. Navigate to Assessment's Info pane -> Related Assessments tab
4. Confirm Related Assessments are displayed and follow to the next page, then return to the 1st page
5. Confirm spinners are circled endlessly
_Actual Result_: Spinners in Related Assessments tab are circled endlessly 
_Expected Result:_ Spinners in Related Assessments tab should not be circled endlessly 
**Note**: For this reason there is no opportunity to reuse evidence/url
=> GGRC-785 Fix infinite spinner for evidences

src/ggrc/migrations/utils/__init__.py, src/ggrc/migrations/versions/20161117114904_142272c4a0b6_migrate_audits_for_snapshots.py, src/ggrc/migrations/versions/20161220161315_275cd0dcaea_migrate_assessments_issues_data.py, src/ggrc/migrations/versions/20161221084829_1aa39778da75_migrate_requests_to_assessments.py
Join multiple insert statements into one
We want to manually create a single big insert statement for migrations
because the biggest bottleneck is database latency. This is the best way
of reducing the time needed for the migrations.
There is no user defined data in the relationships and all types can
only contain valid model names, thus reducing the danger of a possible
sql injection enough that we don't have to worry.
Before: 2+ hours - DNF
After: real	1m51.905s
Note: before merging this, you should revert grc-dev database to a version without this migrations run.
=> GGRC-787 Improve performance of Audit snapshots migration.

src/ggrc/migrations/versions/20161117114904_142272c4a0b6_migrate_audits_for_snapshots.py
Because we restore snapshots for every object one migration before this
one, the error thrown here is only because of phantom objects ->
objects that were deleted from the database, but still have left over
relationships.
We will remove such relationships in a separate PR.
=> GGRC-789 Remove missing revisions exception

src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls-popover.mustache
Precondition:
Created program, control, regulations/objectives that are mapped to control audit
2. Generate assessment based on control from precondition
3. Navigate to Assessment's Info pane
4. Click on mapped control in Info pane
Expected Result: Disable the pop up that shows objectives/regulations in Assessment's Info pane
=> GGRC-793 Disable the pop up that shows objectives/regulations in Assessment's Info pane

src/ggrc/utils/revisions.py
Because we create new assessments from requests we also need to create
new revisions for those assessments.
PS: Memory footprint did not go up a lot. Testing on the grc-test database, processing 6k assessments did not push virtual memory above 600MB, maybe around 50MB more than without processing assessments.
=> GGRC-798 Fix revisions for assessments

src/ggrc/migrations/versions/20170112112254_177a979b230a_update_revision_content_field.py, src/ggrc/models/revision.py, src/ggrc/models/types.py, test/integration/ggrc/models/test_revision.py
Ticket description
> Precondition:
> Created GCA for Assessment with e.g. "Rich text" type, program, audit
> 1. Go to audit page-> Assessments tab
> 2. Create Assessment-> Navigate to Info pane
> 3. Fill in the value into GCA from precondition
> 4. Confirm "There was an error" message is displayed and 500 error in console
> Actual Result: "There was an error" message is displayed while saving the value in CA in Assessment's Info pane and CA is not saved
> Expected Result: no error displayed. The value in CA is saved
> 
> Link to assessment: https://grc-test.appspot.com/audits/722#assessment_widget/assessment/11227
> Note: max length of json request is 65534 bytes
> 
> 
> note this will happen if create any object with 65534 characters long description.
=> GGRC-794 Update revision content lenght

src/ggrc/notifications/common.py, test/unit/ggrc/notification/test_should_receive.py
The server error was caused by a task_group on grc-test that did not have an assignee. I have added a check for this case in `should_receive` and wrote a comprehensive test for it as well.
=> GGRC-799 Fix server error in notifications

src/ggrc/migrations/versions/20170112013716_421b2179c02e_update_fulltext_index.py, test/integration/ggrc/converters/test_csvs/querying_with_unicode.csv, test/integration/ggrc/fulltext/__init__.py, test/integration/ggrc/fulltext/test_mysql.py, test/integration/ggrc/services/test_query.py
This ticket covers 2 different cases when custom attribute name is too long.
searching and sorting on custom attributes with too long names
- create CA for any object with name: (could be any name longer than 66 characters)
"abcd abcd abcd abcd abcd abcd abcd abcd abcd abcd abcd abcd 1"
- create an object with some value in that CA and try to filter on it.
Expected: filter should work
Actual: filter acts as if that CA name does not exist
Second part of this is if we create another long CA with the same prefix:
- create second ca:
"abcd abcd abcd abcd abcd abcd abcd abcd abcd abcd abcd abcd 2"
- try to create an object with values in both CA fields
Expected: object should be created without an error
Actual: object is created but error shows up, The object itself exists, but does not show …
=> GGRC-791 GGRC-792 Index fixes for custom attributes with long names

bin/validate_database.py, src/ggrc/migrations/utils/validation.py, src/ggrc/migrations/versions/20161117114904_142272c4a0b6_migrate_audits_for_snapshots.py
Run edge-case SQL queries before running migrations to ensure no invalid data is present in database.
Invalid data that this PR covers:
* Assessment Templates mapped to multiple Audits
* Requests, Issues and Assessments mapped to anything not snapshottable (Programs, Audits, etc.)
=> QUICK-FIX Add additional checks to database validation

src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/javascripts/models/tests/CycleTaskGroupObjectTask_model_spec.js, src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
This PR fixes incorrectly enabled/disabled checkboxes and dropdowns for completed Workflow Tasks.
---
**Steps to reproduce GGRC-754:**
- Create a Workflow
- On the Setup tab, define a Task of type Dropdown with a few options
- Activate the workflow, visit the Active Cycles tab
- Select a Task in the tree view (3rd tier) to open its info pane
The "response options" dropdown is disabled and its value cannot be modified unless the Task is in Done or Verified state.
The "response options" dropdown is enabled and its value can be modified, except if the Task has been completed or verified.
---
**Steps to reproduce GGRC-769:**
- Create a Workflow
- On the Setup tab, define a Task of type Checkbox with a few options
- Activate the workflow, visit the …
=> GGRC-754, GGRC-769 Fix incorrectly enabled/disabled WF task widgets

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/comment/comment-list-helper.js, src/ggrc/assets/mustache/base_templates/comment_list.mustache
1. Navigate to Assessment's Info pane on audit page
2. Go to comment tab and add comment-> Save
3. Look at the added comment: comment displayed with blank field above
Actual Result: blank fields are displayed after adding a comment in Assessment's Info pane
Expected Result: a comment without additional records is displayed in Assessment's Info pane
**NOTE**: It's really hard to reproduce. This PR will also fix comments duplications.
=> GGRC-597 Blank fields are displayed after adding a comment in Assessment's Info pane

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/localize_date_spec.js
2. Create at least 2 assessments
3. Navigate to Assessment's Info pane -> Related Assessments tab
4. Look at Date column: "Invalid" date is displayed
_Actual Result_: "Invalid" date is displayed in Related Assessments tab
_Expected Result_: Date of Assessment's creation should be displayed in Date column
=> GGRC-784 Fix invalid date on related assessments

src/ggrc/migrations/utils/validation.py
Snapshot is a valid object to be mapped to Issues and Assessment after
the Audit snapshot migration. Requests are excluded since they are
deprecated and removed.
=> QUICK-FIX Add Snapshot object to database checks

src/ggrc/app.py, src/ggrc/converters/query_helper.py, src/ggrc/services/common.py, src/ggrc/services/search.py, src/ggrc/utils/error_handlers.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py, test/integration/ggrc/services/test_collection_post.py, test/integration/ggrc/services/test_common.py, test/integration/ggrc/services/test_query.py, test/integration/ggrc/services/test_response_codes.py, test/integration/ggrc/services/test_search.py, test/integration/ggrc_workflows/test_api_calls.py
The frontend guys requested JSON values to be returned for HTTP400 errors to be able to parse the error messages easily. This PR defines basic JSON error logic: return `{"code": 400, "message": exc.message}` in the body of HTTP400.
This PR enables some frontend enhancements, so I'm marking it with `please review`.
=> GGRC-525 Return JSON in HTTP400

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js
Precondition:
- Created program, audit
3. Click Map in tree view in Assessment's tab
4. Select different objects types from Object type dropdown list and click Search: confirm the selected objects are duplicated and the list icreases
Actual Result: When using a mapper modal and clicking Search for several different object types, the list of Object Type dropdown options increases and duplicates entries appear in it
Expected Result: When using a mapper modal and clicking Search for several different object types, the list of Object Type dropdown options should not increase and duplicate entries appear in it
=> GGRC-817 Update Mapper Model to fix duplication issue

src/ggrc/assets/stylesheets/modules/_file-controls.scss
**Steps to reproduce:** 
1. Navigate to Assessment’s Info pane
2. Navigate to any added URL/Evidence: confirm Assessment's title blinks
_Actual Result:_ Assessment's title blinks if navigate to added URL/Evidence in Assessment Info pane
_Expected Result:_ Assessment's title should not blink if navigate to added URL/Evidence in Assessment Info pane
=> GGRC-583 Fix blinking header info panel

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
Precondition:
2. Return to the program page and make changes in Control (e.g. change the title)
4. Navigate to Control's Info pane and click on the "Compare with the latest version" link: confirm several windows are displayed
Actual Result: "Compare with the latest version" window is duplicated if click twice on the "Compare with the latest version" link
Expected Result: "Compare with the latest version" window should not duplicated if click twice on the "Compare with the latest version" link
=> GGRC-804 Fix duplication of comparer on double click

src/ggrc/assets/javascripts/components/assessment/inline.js, src/ggrc/assets/javascripts/components/inline_edit/inline.js
3. Navigate to Control's Info pane
4. Select any GCA field to edit and click on outside without any changes: confirm "Save" message is displayed
Actual Result: "Saved" message is shown even if nothing was changed in GCA field
Expected Result: "Saved" message should not appear even if nothing was changed in GCA field
=> GGRC-575 "Saved" message is shown even if nothing was changed in GCA field

src/ggrc/assets/javascripts/controllers/tests/tree_view_controller_spec.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js
This PR fixes JS error on deleting old mapped objects (not reproduced on freshly created).
Precondition:
2. Create Assessment and map several objects to assessment through unified mapper (e.g. Access Group)
3. In Assessment's tab open second tier in tree view and select the mapped object (Access Group)
4. Expand 3 bb's menu in Access Group Info pane
5. Click Delete button: the system freezes
6. Click Delete button once again: "access group not found." error message is displayed
Actual Result: The app freezes if delete mapped object to audit from second tier in Assessment tab
Expected Result: The app should not freeze if delete mapped object to audit from second tier in Assessment tab. The objected is deleted form the tree …
=> GGRC-740 Fix JS error on delete mapped objects

src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls-popover.js, src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls.js, src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-related-information.js, src/ggrc/assets/javascripts/components/assessment/mapped-objects/tests/mapped-controls-popover_spec.js, src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls-popover.mustache
Created program, control, regulations/objectives that are mapped to control audit
2. Generate assessment based on control from precondition
3. Navigate to Assessment's Info pane
4. Click on mapped control in Info pane: confirm pop up appears
5. Click on triangle to show RELATED OBJECTIVES AND REGULATIONS: are not shown
Actual Result: Regulations and objectives that are mapped to control are not shown in the pop up that shows objectives/regulations in Assessment's Info pane
Expected Result: Regulations and objectives that are mapped to control should be shown in the pop up that shows related objectives/regulations in Assessment's Info pane
=> GGRC-788 Regulations and objectives mapped to control are not shown in the pop up that shows objectives/regulations in Assessment's Info pane

src/ggrc/assets/mustache/base_objects/general_info.mustache, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
Snapshot RBAC should be checked based on parent object so that
context implication checks work as intended.
=> GGRC-818 Fix RBAC controls for snapshot on frontend

src/ggrc/assets/mustache/components/assessment/urls-list.mustache
Precondition:
3. Fill mandatory CA if any-> Click complete button
4. Add a Verifier
5. Click Complete and Verify button
6. Add url: confirm incorrect message is displayed
Actual Result: Incorrect message is displayed if Assessment moves from Complete status to In progress
Expected Result: The following message should be shown: e.g. "You are about to move assessment from "Completed" to "In Progress" - are you sure about that?"
=> GGRC-715 Incorrect message is displayed if Assessment moves from Complete status to In progress

src/ggrc/assets/mustache/base_templates/people_list.mustache, src/ggrc/assets/stylesheets/modules/_label-list.scss
**Subject**: Change a warning message and a style in Info panel for Assessments
**Details**: 
Create a program with audit and map a control to the program
Navigate to audit page and create an assessment template with mandatory fields
Generate assessment using control and the template
Navigate to Info panel for Assessments
Look at the text of the message in red box
_Actual Result:_ The error message occurs in red box if navigate to Info panel for Assessments   
_Expected Result:_ If navigate to Info panel for Assessments the error message should be in yellow box and should contain the text: ”Please be informed that Assignee and Verifier are the same person”    
_Workaround_: NA
=> GGRC-352 Change styling of info message in people list

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
"Uncaught TypeError: Cannot read property 'id' of undefined" error is displayed while clicking on "Compare with the latest version" link
Precondition:
created program, object (e.g. "Data Assets"), audit
1. Go to audit page: confirm that "Data Assets" is displayed in HNB
2. Return to program page and make changes in "Data Assets" (e.g. change title, description)
3. Return to audit page
4. Refresh the page
5. Navigate to "Data Assets" Info pane and click on "Compare with the latest version"
Actual Result: "Uncaught TypeError: Cannot read property 'id' of undefined" error is displayed while clicking on "Compare with the latest version" link
Expected Result: no error displayed. "Compare with the latest version" dialog appears
=> GGRC-801 - Fix undefined id of Data Asstes in revision diff

src/ggrc/assets/assets.yaml, src/ggrc_risks/assets/javascripts/apps/risks.js, src/ggrc_workflows/assets/javascripts/apps/workflows.js
This PR enables CanJS stache plugin that will allow us to start using stache templates (default in CanJS 3.x) and replace the deprecated mustache templates.
The commits were cherry picked from #4979 which is unfortunately `on hold` for the time being (waiting for spinner UI mockups).
The exact strategy of migrating from mustache to stache is yet to be discussed, but preliminary findings show that we can already start using stache for self-contained application building blocks, e.g. Components or independently compiled internal templates of Controls (#4979 contains one such example).
---
Requested a review from @andrei-karalionak since he was the one who proposed to enable stache without (unnecessarily) waiting for the spinners PR - which makes sense IMO, too.
=> QUICK-FIX Enable CanJS stache plugin

src/ggrc/assets/javascripts/controllers/tree/tree-loader.js, src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js
1. Create one-time WF
2. Create a task at the Setup page
3. Activate WF
4. Try to expand the Second tier
_Actual Result:_ WF's Second tier is not expanded in Active Cycle's tab
_Expected Result:_ WF's Second tier should be expanded in Active Cycle's tab. Task Group, tasks, mapped to task object should be shown.
=> GGRC-838 Fix sub-tree on WF page and draw several batches in sub-tree

src/ggrc/fulltext/mysql.py, src/ggrc/models/all_models.py, src/ggrc/models/assessment_template.py, src/ggrc/models/event.py, src/ggrc_risk_assessments/models/risk_assessment.py, src/ggrc_risks/models/risk.py, src/ggrc_workflows/models/cycle_task_group.py, src/ggrc_workflows/models/cycle_task_group_object_task.py, src/ggrc_workflows/models/task_group_task.py, src/ggrc_workflows/models/workflow.py
This is a cleanup of our models to better match the database.
Simple way to test these changes is to check the differences between the autogenerated alembic migrations and by running:
```python
from ggrc import app, db
db.Model.metadata.create_all(db.engine)
```
=> QUICK-FIX Model cleanup

src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-item.js
**Subject**: Checkbox for Reuse evidence is unchecked while following to the next page at Related Assessment tab in Assessment's Info panel 
**Details**: 
Go to audit page
Create Assessment > Navigate to Info panel and attach an evidence
Create Assessments > Navigate to Info panel>go to Related assessments tab> Select checkbox to Reuse evidence and follow to the next page
Return to the previous page
_Actual Result_: Checkbox for Reuse evidence is unchecked while following to the next page at Related Assessment tab in Assessment's Info panel 
_Expected Result_: Checkbox for Reuse evidence should be checked while following to the next page
_Workaround_: N/A
=> GGRC-244 Fix checked reused evidence after change page

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js, src/ggrc/assets/stylesheets/modules/_modal.scss
Precondition:
2. Return to the program page and make changes in Control (e.g. change the title, description, the value in GCA)
4. Navigate to Control's Info pane and click on the "Compare with the latest version" link
5. Look at the window: confirm GCA are displayed randomly
Actual Result: GCA fields are shown as not in line in the "Compare with the latest version" window after updates
Expected Result: GCA fields are displayed in line in the "Compare with the latest version" window after updates
=> GGRC-805 Fix mismatch of lines of CA in revision diff

src/ggrc/models/hooks/assessment.py
GGRC-920: Assessment generation failed cause nonASCII
character appears in control title
created program, audit, at least 1 control with nonASCII character in title
1. Go to Audit page
2. Create Assessment template
3. Go to Assessments tab and generate assessment based on the assessment template and 3 controls: confirm an error is displayed
**Actual Result:** "Assessments generation has failed" error is displayed while generating assessments
**Expected Result:** no error displayed. Assessments should be generated and displayed in Assessment tab
=> GGRC-920 [release] "Assessments generation has failed" error is displayed while generating assessments

src/ggrc/assets/javascripts/components/modal-connector.js, src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/mustache/assessments/modal_content.mustache
Precondition:
2. Create assessment 
3. Open Edit Assessments modal window
4. Click Map object button and map Control to assessment: confirm the selected Control is not shown in modal window
Actual Result: Objects are not mapped to Assessment in Edit Assessment modal window
Expected Result: Objects should be mapped to Assessment in Edit Assessment modal window and a message is shown that <object> is mapped to assessment
=> GGRC-814 Add default Mapping type for Assessment Edit Modal

src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/if_target_modal_match_spec.js, src/ggrc/assets/mustache/assessment_templates/tree_add_item.mustache, src/ggrc/assets/mustache/assessments/tree_add_item.mustache, src/ggrc/assets/mustache/audits/tree_add_item.mustache, src/ggrc/assets/mustache/base_objects/autocomplete_result.mustache, src/ggrc/assets/mustache/base_objects/search_actions.mustache, src/ggrc/assets/mustache/base_objects/tree_add_item.mustache, src/ggrc/assets/mustache/dashboard/info/get_started.mustache, src/ggrc/assets/mustache/dashboard/internav_list.mustache, src/ggrc/assets/mustache/documents/autocomplete_result.mustache, src/ggrc/assets/mustache/issues/tree_add_item.mustache, src/ggrc/assets/mustache/meetings/tree_add_item.mustache, src/ggrc/assets/mustache/modals/mapper/base.mustache, src/ggrc/assets/mustache/objectives/autocomplete_result.mustache, src/ggrc/assets/mustache/org_groups/autocomplete_result.mustache, src/ggrc/assets/mustache/people/autocomplete_result.mustache, src/ggrc/assets/mustache/people/filters.mustache, src/ggrc/assets/mustache/sections/tree_add_item.mustache, src/ggrc/assets/mustache/vendors/autocomplete_result.mustache, src/ggrc_gdrive_integration/assets/mustache/people/gplus_actions.mustache, src/ggrc_risk_assessments/assets/mustache/dashboard/lhn_search_actions_risk_assessments.mustache, src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree_add_item.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_add_item.mustache, src/ggrc_workflows/assets/mustache/selectors/multitype_multiselect_base_modal.mustache, src/ggrc_workflows/assets/mustache/task_groups/tree_add_item.mustache
<sup>_(this issue has the "critical" priority)_</sup>
This PR changes the type of modal displayed when adding the Sections tab from the Regulations page.
Unit tests for the fix in the modals controller were omitted, because that method is convoluted beyond any reasonable threshold and would have to be significantly refactored first.
---
- Create Regulation
- Click (+) Add Tab buton in HNB and select Sections
Unified mapper window is displayed after clicking Add and selecting Section on Regulation page
New Section modal window is displayed after clicking Add and selecting Section on Regulation page
UPDATE: And  the same for the following objects - Policy / Regulation / Standard / Contract
UPDATE 2: Also, the "Map" buttons …
=> GGRC-199 Show add new modal if adding Section to Regulation

src/ggrc/assets/javascripts/controllers/modals_controller.js
This PR makes sure that before the form is rendered, the current Person object data is fully loaded so that the initial for validation passes (it used to fail because of the incomplete data of the default Audit lead, i.e. empty email address).
No tests, because and end-to-end Selenium test would make more sense... a unit test would just test an implementation detail (partially undecided on this, though... if deemed needed, I will add such test).
The downside might be that a Person object is fetched unnecessarily if the modal form does not use it, but I could not find other good ways to fix it, e.g. by hooking on some _"autocomplete field initial value loaded"_ event or something, and trigger manual form re-validation there.
NOTE: The PR does not try to handle the case when …
=> GGRC-844 Fix disabled Save button on create Audit form

src/ggrc/assets/javascripts/apps/custom_attributes.js, src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js, src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/stylesheets/modules/_modal.scss
Precondition:
2. Return to the program page and make changes in Control (e.g. change the values in "Principal Assignee", "Secondary Assignee", "KIND/NATURE", "EFFECTIVE DATE", "STOP DATE", "ASSERTIONS", "FREQUENCY", "CATEGORIES", "TYPE/MEANS", “STATE”, “OBJECT REVIEW”)
4. Navigate to Control's Info pane and click on the "Compare with the latest version" link
5. Look at the comparison window: confirm that the updates are not shown
Actual Result: Comparison window doesn't contain the updates for the fields
Expected Result: Comparison window should contain the updates for the fields
=> GGRC-811 Fix displaying of missing fields in revision diff

src/ggrc/assets/javascripts/components/unified_mapper/mapper.js, src/ggrc/assets/javascripts/controllers/mapper.js, src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/mustache/assessments/info.mustache
Description
by default when map objects to assessment is invoked, object type should be pre-selected to control. There should also be a filter preset that shows only the objects related to the current audit. This visually is important for the user understanding
- Create control and program and map them 
- Create audit
- Open new asmt modal window and click map object button 
- Check mapper window
Actual: Access group is selected by default and mapping filter is empty 
Excepted: Controls is selected by default and non-edible mapping filter to this audit is applied
**Note**: 
- this is expected behavior for all mapper windows from assessment page/modal window/info pane (view/create/edit modes)
- Risks and Threats breaks the default (disabled) filter - it will be fixed in scope of another …
=> GGRC-858 - Apply default setting for mapper modal window when it is invoked from assessment page

src/ggrc_basic_permissions/__init__.py
**GGRC-295:** This commit gives Assessment assignee rights
to delete Documents mapping
1.39
1. Create an Audit.
2. Create assessment and set Global Reader as assessor. Use reader@reciprocitylabs.com. 
3. Add URL on assessment info pane
4. Login under Global Reader 
5. Display created assessment info pane
6. Delete added URL
7. Refresh the page
**Actual Result:** URL is not deleted.
**Expected Result:** URL is deleted.
During fix checking you will see issue **GGRC-823**, it will be fixed in another PR by UI team part.
=> GGRC-295: Update Assessment assignee permissions for delete

README.md, src/requirements-dev.txt
This helps when debugging failures/errors in python unit/integration tests.
=> QUICK-FIX Add ipdbplugin

src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/mustache/dashboard/internav_list.mustache, src/ggrc/assets/stylesheets/modules/_top-nav.scss
Separate tabs for audit summary, info and assessments with a different color and the rest scoping and other information towards the right with different color (Note: Mockup was created for this in the past)
UX mockups: https://drive.google.com/corp/drive/u/1/folders/0BxUZsNDMuM58MWgtSVVOMHlUY00
=> GGRC-878 Change styling of tabs on Audit page

src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/javascripts/components/tests/datepicker_spec.js
Created GCA with date type for Assessment, program, audit
1. Go to audit page-> Assessment's tab
3. Navigate to Assessment's Info pane
4. Fill in GCA with date type with incorrect value (e.g. "space", "#$@") and click save
**Actual Result**: "There was an error!" message is displayed while saving CA with date type with incorrect value in Assessment's Info pane
**Expected Result**: no error displayed. Incorrect values should be ignored in GCA or LCA with date types. GCA or LCA fields should not contain "invalid date". "None" is displayed.
=> GGRC-783 Fix invalid date sending to backend

src/ggrc/models/mixins/notifiable.py
Deletion Notifiable instances will not remove related to this instance notifications.
1) create notifiable instance (for example Workflow)
2) create notifications for current instances 
3) delete this instance
**Actual Result:**  
"Warning: Column 'object_id' cannot be null"
**Expected Result:** 
Related notifications should be deleted
=> GGRC-845 Remove the missing object_id issue introduced in PR 4725

src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/controllers/tests/modals_controller_spec.js
This PR fixes an error that can occur when opening the create Assessment modal, but the currently logged-in user is not yet in cache. The fix makes sure that the Person cache is always warm.
---
1. Log as Global reader and create program, audit
2. Log as admin and go to the audit page of the created audit by GR
3. Open Assessment tab and lick the "Create" button
no error, the Add Assessment modal opens
a script error occurs "Cannot read property reify of undefined" ... something like that, you've seen it
NOTE: the currently logged in user must not be associated with an Audit in any way. The bug can be reproduced by visiting an Audit that you have not created by yourself, nor you are assigned to it in any way (e.g. as an Audit …
=> GGRC-976 Fix error when opening create Assesment modal

src/ggrc/assets/javascripts/controllers/mapper.js, src/ggrc/assets/mustache/assessments/modal_content.mustache
Precondition:
2. Generate Assessment based on the control from precondition
3. Go to assessment tab and click Open in the first tier
4. Add any widget on Assessment Info page (e.g. "Regulation")
Actual Result: "Uncaught TypeError: Cannot read property 'cache' of undefined" error is displayed while adding a new widget on Assessment Info page
Expected Result: no error displayed while adding
=> GGRC-992 "Uncaught TypeError: Cannot read property 'cache' of undefined" error is displayed while adding a new widget on Assessment Info page

src/ggrc/assets/javascripts/components/datepicker/datepicker.js
**Subject**: Optional fields are marked as mandatory fields in New Workflow window
**Details**: 
Open New Workflow window
Click Hide all optional fields -> Show optional fields
Look at optional field (e.g.”date-1” ): is marked as mandatory field 
_Actual Result:_ Optional fields are marked as mandatory fields in New Workflow window
_Expected Result:_ Optional fields are not marked as mandatory fields in New Workflow window
**Note**: Check the asterisks in all the modal windows
Workaround: NA
=> GGRC-382 Fix required label in datepicker

src/ggrc/migrations/versions/20170104100418_1aa46a8e3460_reattach_urls_evidences_from_comments_.py
We used to have logic to attach URLs/Evidences to Comments for Requests.
Now when there are no Requests and no such logic, we should reattach the URLs/Evidences from Comments to the respective Assessments.
Also this migration removes (sequentially):
1. Mappings between Comments and non-Assessments (only Assessment is Commentable now).
2. Mappings between Documents and Comments with no mapped Assessments.
3. Unmapped Documents.
4. Unmapped Comments.
5. ObjectOwners that refer to missing Documents and Comments.
=> GGRC-760 Reattach Documents from Comments to Assessments

src/ggrc/utils/similarity_options.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
2. The related assessments popup (and tab) should list all assessment mapped to the same parent control or same parent objective of the snapshots to which the assessment is mapped to. All other related must be removed from the list
=> GGRC-871 Update related assessments

src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/stylesheets/modules/_assessment.scss
Move attach evidence and url up in a gray box (CA will follow below it).
The whole Details section – whole section GO to inside comments tab, name Attributes
=> GGRC-911 Move details and evidence on assessment page

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
GCA fields are shown as not in line in the "Compare with the latest version" window after updates
2. Return to the program page and make changes in Control (e.g. add several owners)
4. Navigate to Control's Info pane and click on the "Compare with the latest version" link
5. Look at the window: confirm GCA are displayed randomly
**Actual Result**: GCA fields are shown as not in line in the "Compare with the latest version" window after updates
**Expected Result**: GCA fields are displayed in line in the "Compare with the latest version" window after updates
=> GGRC-805 Add waiting for owners refresh before highlight

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_current_page_spec.js, src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js, src/ggrc/assets/mustache/base_objects/sub_tree_expand.mustache, src/ggrc/assets/mustache/base_objects/tree_child_show.mustache
_(this issue has the priority of "Critical")_
This PR changes the text of one of the options in the tree view's 3BB menu, and the corresponding titles of subtree headers.
NOTE: The change depends on the hash part of the URL to be present when the corresponding tab in HNB is selected. If this is not the case, determining the object type will fail, but IMO this is something that should be fixed in the internal app router or in the URL missing  the tab info, thus the PR does not try to handle such cases (if they can even happen, that is...).
---
Original description;
> Change text for the below:
3BBs
Current: Show mapped to all parents in child tree
New: Objects not directly related to this (object type)
>
> Tree View
Current: Show mapped to this parent object
New: Show objects not directly …
=> GGRC-958 Change a tree view menu option's text

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js, src/ggrc/assets/javascripts/plugins/wysiwyg.js, third_party/wysihtml5/wysihtml5-0.4.0pre.js
Precondition:
Created GCA with Person type for Control, program, control with the value in GCA, audit
2. Return to the program page and make changes in Control (e.g. change the title, description, the value in any GCA except Person type)
4. Navigate to Control's Info pane and click on the "Compare with the latest version" link
5. Look at the GCA with Person type: confirm Person is marked as updated
Actual Result: The values in GCA that were not updated are shown as updated in the "Compare with the latest version" window
Expected Result: The values in GCA that were not updated should not be marked as updated in the "Compare with the latest version" window (e.g. marked with a color)
Note: the issue …
=> GGRC-806 Fix highlighting of unchanged attributes in diff

src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/stylesheets/modules/_assessment.scss
Improvements to Assessment Page.
Place and Style Comment Stream to the right
Instead of Details section - we move section named "Response Comments" to the right panel
=> GGRC-909 Move comments to the right side in assessments

src/ggrc/assets/mustache/dashboard/info/get_started.mustache
1. Log as GR/GE
2. Look at [Create new object] button at My Work page: disappears while My Work page is loading
Actual result: [Create new object] button disappears on My Work page under GR/GE roles
Expected result: [Create new object] button should exist on My Work page
=> GGRC-436 [Create new object] button disappears on My Work page under GR/GE roles

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/last-assessment-date/last-assessment-date.js, src/ggrc/assets/javascripts/models/control.js, src/ggrc/assets/mustache/controls/tree.mustache
=> GGRC-1022 Add last-assessment-date component to Control's treeview

src/ggrc/assets/javascripts/components/mapped_tree_view.js
UI issue.
1) Create Assessment from Admin user.
2) Add new URL on Info Pane.
3) Delete URL on Info Pane.
Expected Result: list of URLs should be cleaned.
Actual Result: URL left in list. If try to delete it once again user will see JS error about 'mapping'.
Workaround: refresh the page, deleted URL disappear.
=> GGRC-823 Assessment Info Pane is not refreshed properly

src/ggrc/models/mixins/__init__.py
_I **think** this was discussed as a blocker so I'm adding `critical` - if I'm mistaken, somebody please remove it (but verify in Jira first)._
Add status field to full text search properties. In order to see the changes you will have to run `$.post("/admin/reindex");` from console to issue reindex command.
=> GGRC-946, GGRC-1086 Add status field to full text search properties

src/ggrc/snapshotter/indexer.py, src/ggrc/utils/__init__.py, src/ggrc/views/__init__.py
Load snapshots to be indexed in chunks by 1000.
Before optimization peak memory footprint was around 1 GB.
After optimization peak memory footprint is around 300 MB.
=> QUICK-FIX Optimize snapshot indexer

src/ggrc/models/__init__.py, src/ggrc/models/all_models.py, src/ggrc/models/inflector.py, src/ggrc_basic_permissions/models.py
This PR reverts a commit that introduced a regression with model_name -> model data not available for some models for some requests.
1. Open the dashboard.
Expected result: no HTTP500 received.
Actual result: HTTP500 received.
This is a good example of why side effects and lazy computation blow up sometimes when mixed.
Description of GGRC-919:
2. Add tab (e.g. Controls)
3. Click Search in Unified Mapper: confirm 500 error is displayed in console
Actual Result: 500 error is displayed in console while searching an object in Unified mapper
Expected Result: no error displayed. Objects are displayed in Search list if exist
=> GGRC-919 Fix model inflector registration

src/ggrc_workflows/migrations/versions/20150707143127_44047daa31a9_add_non_adjusted_next_cycle_start_date.py
After new attributes addition to WF model, found that migration failed cause old migration imports WF model from GGRC sources: 20150707143127_44047daa31a9_add_non_adjusted_next_cycle_start_date.py
=> GGRC-1059: Impossible to add new attribute to existing WF model

src/ggrc/models/hooks/assessment.py
This PR removes backend code that creates a mapping to Program on Assessment creation.
`critical` as it is related to data corruption that breaks grc-test deployment.
=> QUICK-FIX Remove Assessment<->Program mapping

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Created program, regulation, objective, audit
2. Create assessment template
3. Generate assessment based on control and template
4. Map regulation and objective to assessment
5. Go to assessment Info page and open regulation, objective and controls tabs: object is not shown in tree view
_Actual Result:_ Mapped object to assessment is not shown in tree view on Assessment Info page
_Expected Result_: Mapped object to assessment should be shown in tree view on Assessment Info page
**Note**: Object is shown in tree view after refreshing the page several times. But if refresh the page after an object appears the object disappears form tree view again.
=> GGRC-1068 Fix shown snapshot objects in tree-view

src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache, src/ggrc/assets/mustache/components/mapped-objects/mapped-objects.mustache, src/ggrc/assets/stylesheets/modules/_assessment.scss
Hide Controls expander icon and add "None" text in case no mapped controls
=> GGRC-908 Remove Controls expander icon in Assessment

src/ggrc/assets/javascripts/components/assessment/attachments-list.js, src/ggrc/assets/javascripts/components/ca-object/ca-object.js, src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/mustache/assessments/info.mustache, src/ggrc/assets/mustache/base_templates/mapping_tree_view.mustache, src/ggrc/assets/mustache/components/assessment/attachments-list.mustache, src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache, src/ggrc/assets/stylesheets/_colors.scss, src/ggrc/assets/stylesheets/components/ca-object/_ca-object.scss, src/ggrc/assets/stylesheets/modules/_assessment.scss, src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
Style assessment page component according to mockup
- Attributes tab styling (two columns)
- buttons styling 
("Prior Audit Responses" button must be actually the color `#4B898B` instead of color on the mockup)
- Evidence styling
- Responses/ Comments (change title from response comments)
- Assessment Attributes (change title from attributes)
- Comments bottom fadeout (not like on the screenshot)
=> GGRC-1048 Additional UX styling in Assessment page

src/ggrc/assets/javascripts/models/assessment.js
~~_(not sure whether the related Jira issue has been created yet)_~~
Comment notifications for Assessments should be enabled by default, which is governed by the relevant setting on the Assessment object. This PR makes sure that this setting is enabled by default when creating a new Assessment.
---
1. Go to Audit's summary tab
1. Click the "create assessment" button (a modal opens - look at the _"Enable notifications on comments"_ checkbox group)
1. Fill in the required fields and click Save
1. On the created Assessment's info pane look at the RESPONSE COMMENTS column on the right.
- The "send notifications" checkbox under the comment rich text field is checked by default.
- The aforementioned checkboxes on the modal form are all checked by …
=> GGRC-1074 Enable Assessment comment notifications by default

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
2. Return to the program page and make changes in Control (e.g. change description)
3. Refresh audit page and update Control to the latest version: error is displayed
**Actual Result**: Uncaught TypeError: instance.refresh is not a function error is displayed while updating object to the latest version
**Expected Result**: no error is shown while updating an object to the latest version
=> GGRC-1118 Fix updating to latest revision

src/ggrc/converters/query_helper.py
Steps to reproduce (from Jira):
2. Click Map in Control's tab and map one more Control to audit
Actual Result: HTTP500 is returned, the mapped object is not shown in tree view
Expected Result: The mapped object is shown in tree view
Second case (more general):
1. Go to any tree view with Snapshots (for instance, Control tab on Assessment page).
2. Try to sort by any column.
Expected result: the data is sorted (note: sorting by owner doesn't work yet, see GGRC-587)
Actual result: HTTP500 is returned, the tree view is empty.
=> GGRC-1071 Fix ordering of snapshots

src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache, src/ggrc/assets/stylesheets/components/ca-object/_ca-object.scss, src/ggrc/assets/stylesheets/modules/_assessment.scss
**Formating is broken if attach evidence/URL with a long title**
2. Generate assessment based on control
3. Navigate to Assessments Info panel
4. Add evidence/URL with a long title
**Actual Result**: Formating is broken if attach evidence/URL with a long title
**Expected Result**: Formating should not be broken if attach evidence/URL with a long title
=> GGRC-1120 Fix styles in assessment with long attributes

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/assessment/controls-toolbar/controls-toolbar.js, src/ggrc/assets/javascripts/components/state-colors-map/state-colors-map.js, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/components/assessment/controls-toolbar/controls-toolbar.mustache, src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache, src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss, src/ggrc/assets/stylesheets/components/tree_pagination/_tree_pagination.scss, src/ggrc/assets/stylesheets/modules/_filters.scss
Some short list of improvements:
- Assessment State Column at the beginning + color indication for state (with the same colors as on pie chart on Audit Summary)
- put Assessment Finish Date to the second column
- update title (button also) - "Related Assessments"
- Put Paging Info Closer to paging control
=> GGRC-1066 Related Assessments popup: minor updates

src/ggrc/assets/javascripts/models/display_prefs.js, src/ggrc/assets/javascripts/plugins/utils/state-utils.js
1. Go to My Work page and open Audit tab
2. Look at Audit statuses: differ from Active - Deprecated - Draft 
Actual Result: States for assignable objects are differ from Active - Deprecated - Draft states
Expected result: Remove filter from assignable objects: Assessments, Issues, Workflow, Tasks, Cycle Tasks + Person and Asmt template
=> GGRC-1093 Improve Active - Deprecated - Draft filter for assignable objects

src/ggrc/migrations/versions/20170207134238_562ec606ff7c_add_assessment_updated_notification_type.py, src/ggrc/models/assessment.py, src/ggrc/models/comment.py, src/ggrc/notifications/data_handlers.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/templates/notifications/email_digest_content.html
_(a V2 release ticket, hence a higher priority)_
This PR adds a notification record when an (active) Assessment is modified, and includes it into the daily digest email.
When reviewing, please especially mind / focus on the following:
- Is the list of attributes to ignore, when deciding whether there was a change or not, correct?
- The exact notification content has not been defined yet, thus I opted for a generic message for the time being.
- No (integration) tests yet, I would first like to check whether the overall structure and logic of the change is sound. We might also have to postpone them until the exact notification content is known (to have a clearly defined "output") - we might want to create a separate subtask for that in order to not block the main development of the new …
=> GGRC-1084 Add notification about changed Assessments

test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/tests/test_audit_page.py
1. Update PO according to the latest application changes (checkboxes were removed from assessment widget).
2. Skip asmt generation test due changes in asmt generation modal window
=> QUICK-FIX Update filter for assessment PO

src/ggrc/services/common.py, test/integration/ggrc/snapshotter/test_snapshoting.py
This PR adds a COMMIT after calling `_copy_snapshot_relationships` via sending `model_put_after_commit` event.
2. Create a control, map it to the program.
3. Create an audit for the program.
4. Create an assessment in the audit, map it to the control's snapshot.
5. Create an objective, map it to the control **and to the program** (it's not automapped!).
6. Open assessment info page, click on the control snapshot preview, open "related objectives and regulations": it should be empty (same as objective tab in the audit, the objective is not snapshotted yet).
7. Open audit info page, click "Update objects to latest version" in the dropdown menu.
8. Open assessment info page, click on the control snapshot preview, open "related objectives and …
=> GGRC-1103 Fix "Update all snapshots in the audit" feature

src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree.mustache, src/ggrc_workflows/assets/mustache/workflows/tree.mustache
This fixes regressions caused by 232a726 that was part of #5122.
2. Create task to Task Group and Activate WF
3. Open Active Cycles tab and expand sub level for Task Group
Actual Result: JS error occurs in WF while expanding tasks in Active Cycles tab
Expected Result: No error displayed
Same error was also present on two other pages:
1. Workflow tree view on any object page with an active workflow attached (care the initial count on object page will be zero, even though workflows are mapped)
2. Risk Assessment tree view on Program page
=> GGRC-1143 Fix script error in certain tree views

src/requirements-dev.txt, src/requirements.txt
add cached-property==1.3.0 to prod requirements
and remove it from dev requirements
=> QUICK-FIX: python requirements

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js, src/ggrc/assets/javascripts/components/unified-mapper/mapper.js, src/ggrc/assets/javascripts/controllers/mapper.js, src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/mustache/assessments/tree_add_item.mustache, src/ggrc/assets/mustache/audits/tree_add_item.mustache, src/ggrc/assets/mustache/base_objects/tree_add_item.mustache, src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache, src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-related-information.mustache, src/ggrc/assets/mustache/documents/tree_add_item.mustache, src/ggrc/assets/mustache/modals/mapper/base.mustache, src/ggrc/assets/mustache/modals/mapper/component.mustache, src/ggrc/assets/mustache/snapshots/tree_add_item.mustache
As right now we use default `relevantTo` read-only property to define Snapshot Scope Object it causes regressions still using this references in the Unified Mapper Component and Tree View
=> GGRC-1150 Incorrect value in disabled field (Controls -> Asmt tab -> Click map in treeView)

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-columns-configuration.js, src/ggrc/assets/javascripts/components/unified-mapper/mapper.js, src/ggrc/assets/mustache/assessments/tree_add_item.mustache, src/ggrc/assets/mustache/base_objects/tree_add_item.mustache, src/ggrc/assets/mustache/components/unified-mapper/mapper-results-columns-configuration.mustache, src/ggrc/assets/mustache/dashboard/internav_list.mustache
1. Created a program
3. Click map on the Control's first tier
4. Select Assessment in Unified mapper and Search: error is displayed
_Actual Result:_ "Uncaught TypeError: eventName.indexOf is not a function" occurs while Searching Assessments in Unified mapper
_Expected Result:_ no error displayed while searching assessments
**Note:** 
1. "Uncaught Error: can.Map: Object does not exist" if search "Products" in Unified mapper
2. "Uncaught Error: can.Map: Object does not exist" if search "Threats" in Unified mapper
**Result**
- Assessments are hidden from the Mapper modal.
- `can.Map: Object does not exist` error was reproduced for objects which have the CA with point in the name. - fixed
=> GGRC-1160 Fix JS error on Mapper modal

src/ggrc/assets/javascripts/components/mapping-controls/mapping-type-selector.js
**Steps for reproduce:**
- open Access Group tab
- click `Map` button in tree view
- make sure that Object Type dropdown is empty
- click on `Search` or `Create` button
_Actual result:_ JS error
_Expected result:_ Object Type dropdown shouldn't be empty
=> QUICK-FIX Fix Access Group's Mapper modal

src/ggrc/migrations/versions/20170131171323_4e43a2374e2c_delete_notification_with_0_object_id.py
This is required for clean up data. After object deletion its
notifications updated object_id to 0 value. Now this problem
solved and notifications should be deleted with object instance.
This migration delete invalid notifications from database.
=> GGRC-1014 Remove notification with '0' object id 

src/ggrc/assets/javascripts/components/relevant_filters.js
**"Uncaught TypeError: Cannot read property 'constructor' of undefined" error is displayed if click map button on the assessment's first tier** 
2. Assessments tab
3. Click map button on the first tier: error is displayed
**Actual Result**: "Uncaught TypeError: Cannot read property 'constructor' of undefined" error is displayed if click map button on the assessment's first tier 
**Expected Result**: no error is shown. Unified mapper is displayed.
=> GGRC-1180 Fix error with cache in unified mapper

src/ggrc/migrations/versions/20170130060409_57940269e30_migrate_requests_change_logs.py
This PR marks revisions for Requests as if they belong to their respective Assessments.
=> GGRC-757 Migrate Request revisions to Assessment revisions

src/ggrc/migrations/versions/20170104100418_4aa9f2ee7969_reattach_urls_evidences_from_comments_.py, src/ggrc/migrations/versions/20170130060409_57940269e30_migrate_requests_change_logs.py
Since merged release branch into develop, all migrations that were added
to develop branch must now be applied on top of any migration in the
release branch.
**Note: before merging this into develop!**
The grc-dev database needs to be reverted to the state before the
"reattach urls evidences from comments" migration was run.
=> QUICK-FIX Merge release/0.10-Raspberry into develop

src/ggrc/models/mixins/with_similarity_score.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
This fixes the the query for similar objects of different types,
for example Issues and assessments.
to test this, map the same control snapshot to an issue and an assessment and similar query for the given assessment should return the similar issue.
=> GGRC-1146 Fix similarity query on the backend

src/ggrc/assets/mustache/components/assessment/inline/checkbox.mustache, src/ggrc/assets/stylesheets/components/ca-object/_ca-object.scss
1. Log as admin and go to Admin Dashboard
2. Add GCA for an object (e.g. Assessment) with checkbox type and type a title for the checkbox
3. Create audit and Assessment on the audit page
4. Navigate to Assessment's Info pane and look at the GCA with the checkbox type
Actual Result: The description of the checkbox repeats the title.
Expected Result: Do not repeat the description for the checkbox.
_Note_: Do not repeat the description for the checkbox for local custom attributes with the checkbox type as well.
_before fix_
_after_
=> GGRC-825 Do not repeat the description for the checkbox

src/ggrc/assets/mustache/base_objects/info.mustache, src/ggrc/assets/mustache/controls/info.mustache, src/ggrc/assets/mustache/issues/info.mustache, src/ggrc/assets/mustache/policies/info.mustache, src/ggrc/assets/mustache/processes/info.mustache, src/ggrc/assets/mustache/products/info.mustache, src/ggrc/assets/mustache/programs/info.mustache, src/ggrc/assets/mustache/systems/info.mustache, src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache, src/ggrc_risks/assets/mustache/risks/info.mustache
1. Open audit;
2. Open Controls widget;
3. Open any item in TreeView;
4. You can see "Show advanced" collapse.
The content of this collapse should be displayed without the expand/collapse.
The second commit contains a redesign of number of columns on 'Advanced' section.
I think Info pane looks better after this.
Look at following screenshots:
**Risk pane**
_before_
_after_
**Issue page**
_before_
_after_
The second commit could be reverted if that redesign is not valid.
=> GGRC-963 Show Advanced to be removed from all panes, Show all the fields & attributes without the expand/collapse

src/ggrc/assets/mustache/base_objects/page_header.mustache, src/ggrc/assets/mustache/dashboard/info/get_started.mustache, src/ggrc/templates/base_objects/_page_header.haml, test/selenium/src/lib/constants/locator.py
This PR fixes the issue with the _"Objects not directly related to..."_ option text in the 3bb tree view menu when navigating to the All Objects page directly.
The cause of the issue was a missing hash part of the URL - the latter is used to determine the current tab's object type.
---
1. Go to the dashboard
1. Click the "All Objects" link in the page header
1. When on the (default) Regulations tab, open the 3 dots menu on the right, just above the tree view.
The last option's text in the menu says _"Objects not directly related to this Regulation"_
The last option's text in the menu says _"Objects not directly related to this"_
=> GGRC-1085 Explicitly set default All Objects tab in links

src/ggrc/models/mixins/customattributable.py, test/integration/ggrc/models/test_snapshot.py, test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
We didn't properly store custom attribute definitions in revisions of two-word objects (Access Groups and Data Assets) which resulted in snapshots not showing any custom attributes for those objects.
To reproduce: have custom attributes on two-word objects, create program with those objects in program scope, create audit, visit snapshots of two-word objects.
To see changes you will have to re-index revisions (run `$.post("/admin/refresh_revisions");` in console).
=> GGRC-727 Custom attributes for two word objects

src/ggrc/migrations/versions/20170212143951_1e65abd56ccb_add_notification_types_for_assessment_.py, src/ggrc/notifications/data_handlers.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/templates/notifications/email_digest_content.html, src/requirements.txt, test/integration/ggrc/notifications/test_assignable_notifications.py
This PR adds notifications to daily digest email if Assessment's status is changed. All user roles assigned to the Assessment (Creator, Assignees, Verifiers) get notified.
This can probably be considered as a "beta PR", thus adding the `needs work` label. The code should be probably be refactored a bit, and there is a state transition clash between two notification types, namely "Assessment declined" and "Assessment reopened". Plus more thorough testing needs to be done.
**Edit:**
The notification email templates used are generic for now. Some modest changes need to be done, which is covered by a different subtask.
=> GGRC-852 Add Assessment state change notifications

src/ggrc/migrations/versions/20170215144723_2f1cee67a8f3_add_default_assessment_notifications_.py, src/ggrc/models/comment.py, src/ggrc/notifications/notification_handlers.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/models/test_assessment.py
This is a follow-up to #5107 that synchronizes the default Assessment notification settings when using imports with how the Assessment's "Create new" modal behaves.
**Steps to verify:**
- Go to the `/import` page and download the Assessment import template (or use an existing one)
- Fill in the required fields in the downloaded template, make sure to leave the `Code`, `Recipients`, and `Send by default` columns blank.
- Import the template, a new Assessment should get created
- Open the created Assessment in the application, open a modal to edit it
Look at the "Enable notifications on comments" checkbox group - all checkboxes should be checked, just like they are checked when opening a modal to create a new Assessment.
Also, on that Assessment's info pane, the "Send …
=> GGRC-1074 Add default Assessment notification settings

src/ggrc/converters/handlers/snapshot_instance_column_handler.py
This removes the sqlalchemy warning for the empty in statement that can
be a potential performance regression.
This is a fix for the integration tests warning that was introduced in https://github.com/google/ggrc-core/pull/5100#issuecomment-279669965
=> GGRC-1186 Remove empty in_ query

src/ggrc/notifications/notification_handlers.py, test/integration/ggrc/models/test_assessment.py, test/integration/ggrc/notifications/test_assignable_notifications.py
This PR fixes a missing state transition notification when an Assessment is completed / sent to review directly from the "Not Started" state, skipping the "In Progress" state.
---
1. Create assessment on the audit page
1. Make sure that there is no required fields in Assessment's Info pane (best to create a fresh Assessment  without any custom attributes defined for Assessments)
1. Complete Assessment: assessment moves from Not Started state to Completed without In progress state
Notification should be sent in daily digest to Creator, Assignee, Verifier in a daily digest
Notification is not sent if Assessment moves from Not Started to Completed directly
NOTE:
The PR also fixes the case when an Assessment is sent from Not …
=> GGRC-1195 Add notification if skipping "In Progress" state

src/ggrc/assets/javascripts/components/quick_form/quick_add.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/isInAuthList_spec.js, src/ggrc/assets/mustache/audits/info.mustache
This PR prevents assigning the same person as an Auditor twice on the same Audit.
The original ticket description (below) required an error message to be improved, but we instead opted to prevent the error from happening in the first place.
---
2. Create an audit
3. Add a user1 as an Auditor
4. Add a user1 as an Auditor once again
Incorrect message is displayed while adding a user that already exist to an object
"TBD" message is displayed while adding a user that already exist to an object
UPDATE: It has later been decided, that the proper fix would be to prevent a person from being added twice, thus the "Add" button should be disabled in such cases. For user's convenience, a tooltip has been added with an …
=> GGRC-812 Prevent assigning the same Auditor twice

src/ggrc/assets/javascripts/components/object-list/object-list.js, src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/components/object-list/object-list.mustache, src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
Add "No Related Assessments were found" in Related Assessments window
1. Navigate to assessment's Info panel
2. Open Related Assessments window
**Expected Result**: "No Related Assessments were found" is displayed if there is no related assessments
**On hold** until https://github.com/google/ggrc-core/pull/5146 is merged
=> GGRC-1154 Add empty message in related assessments

src/ggrc/notifications/notification_handlers.py
This PR disables checking for custom attributes changes on Assessments for the time being.
Detecting CA changes by using SQL ALchemy's attribute history is unreliable and  can lead to false positives / false negatives.
Since CA changes on Assessments are already not detected, adding the `_custom_attribute_values` attribute to the ignore list will not cause additional issues.
---
- Go to the admin panel and make sure there are no required Custom Attributes defined for Assessments (but there should still be a few CAs defined)
- Go to the Audit page, Assessments tab and create an Assessment
- On the Assessment's info pane, click the COMPLETE button, directly completing an Assessment from the "Not Started" state
An "Assessment completed" (or "is …
=> QUICK-FIX Ignore Assessment CA changes for notifications

src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
This PR increases paging description font by 1px to match the "Page x of x" label as on the ux screens.
2. Open any tab in HNB (e.g. "Controls")
3. Click Map in first tier-> Search any object
4. Look at the count of found items: are too small
Actual Result: Counts are too small in Unified mapper
Expected Result: Improve counts in Unified mapper
=> GGRC-1147 Increase paging description font size

src/ggrc/assets/javascripts/components/last-assessment-date/last-assessment-date.js, src/ggrc/assets/javascripts/components/last-assessment-date/last-assessment-date_spec.js, src/ggrc/assets/mustache/controls/tree-item-attr.mustache, src/ggrc/assets/mustache/objectives/tree-item-attr.mustache
created program, control, objective, audit, assessment on the audit page
1. Navigate to assessment's Info pane on the audit page and Complete assessment
2. Go to Controls/Objectives tabs
3. Look at LAST ASSESSMENT DATE column: assessment's finish date empty
_Actual Result_: LAST ASSESSMENT DATE column for snapshots: Controls/Objectives is empty
_Expected Result_: Hide LAST ASSESSMENT DATE column for snapshots.
=> GGRC-1144 Show LAST ASSESSMENT DATE column for snapshots

src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/issues/modal_content.mustache
**NOTE**: Tests will be implemented in a separate PR - as soon as we will have an answer for GGRC-1206.
GGRC-1097 Newly created issue is not displayed in "Related Issues" tab
Precondition:
created program, audit, assessment on the audit page
1. Go to Assessment tab on the audit page
2. Navigate to Assessment’s Info panel 
3. Open Related issues tab
4. Create a new issue
Actual Result: Newly created issue is not displayed in "Related Issues" tab
Expected Result: Newly created issue should be listed on Related issues tab immediately
It also will fix:
GGRC-1098 Extra fields appear in New/Edit Issue modal while creating through Related Issues tab
Precondition:
created program, audit, assessment on the audit page
1. Go to Assessment tab on the audit page …
=> GGRC-1097 Newly created issue is not displayed in "Related Issues" tab 

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
This PR fixes search params are not resetted on the next search issue.
2. Open object in LHN (e.g. "Regulations")
3. Click map button in the first tier and select object type in Unified mapper (e.g. "Controls"
4. Click Search and go to next page in search results
5. Input filter value (e.g. title) and click Search: no results
Actual Result: Filter doesn't work in Unified mapper if filter and search object on the second and next pages
Expected Result: Filter should work in Unified mapper if filter and search object on the second and next pages
=> GGRC-1178 Fix search params are not resetted on the next search

.gitignore, test/integration/ggrc/test_csvs/.~lock.pci_program.csv#
A [LibreOffice lock file](https://github.com/google/ggrc-core/pull/5197/files/4d50524b18b6073b314b77532b0a1565dd407df4#diff-1044ef177a2e71200e763767a80c09d6) slipped past our code review recently. This PR removes the lock file and updates `.gitignore` to prevent adding lock files in future.
=> QUICK-FIX Remove libreoffice lock file

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
This PR fixes fields order was not applied in columns configuration of the unified mapper.
2. Regulations tab
3. Click map in the first tier and select Controls/Objectives object type
4. Open Config for Search results: look at the Set visible fields dialog
Actual Result: Make Last assessment date field after State field in Set visible fields dialog
Expected Result: "Last assessment date" field should be after "State" field in Set visible fields dialog
=> GGRC-1149 Fix fields order in columns config

src/ggrc/assets/mustache/base_objects/states.mustache, src/ggrc/assets/stylesheets/_helpers.scss, src/ggrc/assets/stylesheets/modules/_tree-content.scss
Change text color to `#ffab40` according to ticket 35380747 in Buganizer
=> Change status text color in workflow

src/ggrc/assets/javascripts/controllers/mapper.js
This PR fixes mapping snapshots on the create object popup.
1. On the audit page go to Assessments tab
2. Click Create New and look at the Map button: is disabled
Actual Result: Map button doesn't open Unified mapper in New Assessment modal
Expected Result: Map button should open Unified mapper in New Assessment modal and should be the possibility to map objects from the audit scope to Assessment
=> GGRC-1184 Fix mapping snapshots for the new objects

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/tests/assessment_model_spec.js, src/ggrc/migrations/versions/20170219221807_4e7fda17abc7_fix_assessment_contexts.py
1. Create a new assessment via the create new dialog (this issue is not reproducible when generating assessments) as an admin.
2. Attach evidence.
3. Add a global creator user as an Auditor to the Assessment's aduit
4. Login as the creator user and see if see the evidence list.
Expected: The attached file from step 2 should be there
Actual: The attached file is missing
=> GGRC-1158  Auditor (Global Creator) cannot see the file in the assessment by assessor

src/ggrc/assets/javascripts/plugins/tooltip.js
Steps:
1. Open any page with treeview
2. Open info pane
3. Play with "Maximize/Minimize" button (click 5, 10, 20 ... times; try to click in 500ms when hovering target element)
Actual: Sometimes tooltip becomes frozen (and not hidden)
=> GGRC-1135 Tooltip that don’t go away

src/ggrc/assets/javascripts/components/add-object-button/add-object-button.js, src/ggrc/assets/mustache/audits/summary.mustache, src/ggrc/assets/mustache/components/add-object-button/add-object-button.mustache
Incorrect Data is Passed to Create New Object Modal which case regression:
- Navigate to Audit Summary Page
- Click on Create Assessment Button 
- Input Some Mandatory fields
- Try to Click Save button
=> QUICK-FIX Fix issues with create assessment button on info page

src/ggrc/converters/handlers/handlers.py, src/ggrc/models/reflection.py
This PR adds rules for audit and audit scope object mappings with imports.
Things to check:
- "map: Audit", "map: Issue", "map: Assessment" columns are ignored on any normal object import.
- "map: [anyobject]" should be ignored on audit imports.
known bugs that will be solved in a different ticket (please don't test this):
- multiple audits can be mapped to an assessment (please don't test this or delete the assessment after)
- Issues don't have an audit column and can be imported without an audit mapping
=> GGRC-1218 Fix errors on import mappings to audits and assessments

test/unit/ggrc/utils/__init__.py, test/unit/ggrc/utils/test_mapping.py
`tests.unit.ggrc.utils.*` never got run by `run_unit` because of missing `__init__.py`.
#5197 broke a unit test but it went unnoticed.
=> QUICK-FIX Fix unit tests for ggrc.utils

bin/db_migrate
validate_database.py regularly blocks grc-test deployment because of Assessment-Issue mappings that are in fact allowed. I disabled it until the time when it is updated.
=> QUICK-FIX Disable db validator

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js, src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js, src/ggrc/assets/mustache/components/unified-mapper/mapper-results.mustache, src/ggrc/assets/mustache/components/unified-mapper/mapper-toolbar.mustache, src/ggrc/assets/mustache/modals/mapper/base.mustache, src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper-toolbar.scss, src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
This PR moves total objects found next to the Search button. That also reduces modal height a bit.
Also fixes spinner issue: #GGRC-1061
And modal height issue: #GGRC-929
=> GGRC-1134 Move total objects count next to the Search button

src/ggrc/assets/javascripts/components/object-list/object-list.js, src/ggrc/assets/mustache/components/object-list/object-list.mustache
Object List Component doesn't update it state in case primitive type is used as rendering flag
=> QUICK-FIX Add extra computed property to Object List Component to fix rendering issues   

src/ggrc/snapshotter/helpers.py
Displays generation of snapshots and relationships between snapshots and objects in admin log.
=> QUICK-FIX Display snapshot revision generation in admin event log

src/ggrc/assets/javascripts/plugins/can_control.js
1. Create program, audit
2. On the audit page create assessment
3. Navigate to assessment's Info pane and click [+] button to attach evidence
4. Look at Add evidence [+] button: is not shown after adding evidence
_Actual Result_: Add evidence [+] button disappears after adding evidence
_Expected Result_: Add evidence [+] button should not disappear after adding evidence
_Note_: add evidence [+] button is shown after page refresh.
=> GGRC-1229 Add evidence [+] button disappears after adding evidence

src/ggrc/services/common.py, test/unit/ggrc/services/test_common.py
change the order of revision log creation 
create should be at first 
delete - at last 
modified  - in the middle
=> GGRC-1043 Fix corrupted order of revisions 

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/dropdown/multiselect-dropdown.js, src/ggrc/assets/javascripts/components/tests/multiselect_dropdown_spec.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/javascripts/controllers/tree/tree_filter_controller.js, src/ggrc/assets/javascripts/plugins/utils/state-utils.js, src/ggrc/assets/mustache/base_objects/tree_view_filter.mustache, src/ggrc/assets/mustache/components/dropdown/multiselect_dropdown.mustache, src/ggrc/assets/stylesheets/_components.scss, src/ggrc/assets/stylesheets/components/multiselect-dropdown/_multiselect-dropdown.scss, src/ggrc/assets/stylesheets/modules/_filters.scss, test/selenium/src/lib/base.py, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/page/widget/generic_widget.py
New approach should be applied to all tables - drop-down with multiselect
By default - None selected
1) Show selected options in "Input" of dropdown
2) Option to select all states
Filter applied after closing the DDL: e.g. click out the filter
=> GGRC-1132 Assessments tree view filter: show special Assessment states instead of Active - Draft - Deprecated

src/ggrc/fulltext/__init__.py, src/ggrc/fulltext/recordbuilder.py, test/integration/ggrc/fulltext/test_mysql.py
-	Create a CA with name "type" all lowercase letters not "Type" or anything like that.
-	Try to create an object with value inside the "type" custom attribute
expected: everything works
actual: server error
=> GGRC-1241 CA with name "type" can not be saved

src/ggrc/assets/javascripts/components/relevant_filters.js, src/ggrc/assets/mustache/mapper/relevant_filter.mustache
This PR hides readonly objects from the dropdown in filter by mapping.
Precondition:
1. Go to audit page-> Assessment's tab
2. Create New 
3. Click map objects button in New Assessment modal
4. Click + Filter by mapping: expand dropdown list
Actual Result: Audit is shown in dropdown list when open Filter by mapping
Expected Result: Audit should not be shown in dropdown list when open Filter by mapping
=> GGRC-1243 Hide readonly objects from the dropdown in filter by mapping

src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
This PR adds configuration for default mapping objects.
For objective -> controls (default value)
For section -> objective (default value)
For regulation -> section (default value)
For Products -> system (default value)
For standard -> Section (default value)
For contract -> clauses (default value)
=> GGRC-1157 Add configuration for default mapping objects

src/ggrc/assets/javascripts/plugins/can_control.js, src/ggrc/assets/javascripts/plugins/tests/can_control_spec.js
Create program, audit
On the audit page create assessment
Navigate to assessment's Info pane and click [+] button to attach evidence
Look at Add evidence [+] button: is not shown after adding evidence
Actual Result: Add evidence [+] button disappears after adding evidence
Expected Result: Add evidence [+] button should not disappear after adding evidence
Note: add evidence [+] button is shown after page refresh.
=> GGRC-1229 Update of "bindXHRToButton" function. Unit tests

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/migrations/versions/20170219221807_4e7fda17abc7_fix_assessment_contexts.py, src/ggrc/migrations/versions/20170224202800_341f8a645b2f_fix_assessment_contexts_again.py
Our javascript model callbacks are broken, before_create/before_save gets called after the POST is already made. 
As a temporary solution I am adding the call to before_create into assessment's form_preload.
Because this is a production issue I have made sure the migrations are also rerun.
This fixes https://github.com/google/ggrc-core/pull/5194
=> HOT-FIX Fix assessment context

src/ggrc/assets/stylesheets/modules/_assessment.scss
1. Navigate to Assessment's Info pane 
2. Look at the + Add evidence button: in gray rectangle
**Actual Result**: Add evidence button is shown with a gray color
**Expected Result**: Add evidence button should be green
=> GGRC-1287 Fix evidence button color

src/ggrc/assets/javascripts/controllers/tests/tree_view_controller_spec.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js
Mapped object is not shown in tree view and tab is not increased by one after mapping on Assessment Info page
Created program, at least 2 controls, audit
2. Create assessment and go to assessment Info page
3. Open Controls tab and click Map in tree view
4. Select one control that is mapped to audit and map: confirm the selected control is not displayed in tree view
**Actual Result**: Mapped object is not shown in tree view after mapping on Assessment Info page. Refresh is needed
**Expected Result**: Mapped object should be shown in tree view after mapping on Assessment Info page and tab should increase by one
=> GGRC-1025 Refresh tree view after mapping of snapshot

src/ggrc/assets/javascripts/controllers/mapper.js
This PR fixes a typo in code causing relevant filter to be not disabled.
Precondition:
created program, audit
1. Go to the audit page-> Assessments tab
2. Click create new
3. Click Map object button in New assessment modal: confirm the field with audit is not disabled
Actual Result: Audit is not disabled by default if map object through New Assessment window
Expected Result: Audit should be disabled by default if map object through New Assessment window
=> GGRC-1261 Fix relevant filter is not disabled

src/ggrc/assets/stylesheets/modules/_top-nav.scss
2. Look at the widgets in HNB: gray colored
_Actual Result:_ The widgets in HNB are gray and users think this is disabled
_Expected Result:_ Make color for the widgets in HNB in darker fonts. E.g., make them black
UX for Navigation Line: https://drive.google.com/corp/drive/u/1/folders/0B7_NYFVmb896d1ZOMEtqYWZ4Z0k
Navigation line is re-designed.
We still leave opacity 70% for non selected tabs to increase contrast between selected and non-selected.
Heigh is increased to 40px
Background is white
Black Tabs Specs:
«Current» State - #000000, Bold.
«Normal State» - #000000, Opacity 70%, Regular
Blue Tabs Specs:
«Current» State - #0277BD, Bold.
«Normal State» - #0277BD, Regular
=> GGRC-923 Make color for the widgets in HNB in darker fonts

src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
**"Script error" message is displayed while moving to the audit page**
**Precondition**: 
Log as Global creator, create program, control, audit
1. Go to audit page: confirm an error is displayed
**Actual Result**: "Script error" message is displayed while moving to the audit page
**Expected Result**: no error displayed
**Note**: the issue is reproduced from case to case
To catch the bug it necessary to refresh the page with Audit Summary and quickly switch to another tab in browser (as soon as audit summary page started loading)
=> GGRC-921 Fix script error on audit summary

src/ggrc/assets/javascripts/pbc/workflow_controller.js
Precondition:
2. Issues tab-> Create an issue
Actual Result: Cannot map issue to audit: "Uncaught TypeError: Cannot read property 'map' of undefined" occurs in console
Expected Result: no error displayed. Issue should be mapped to audit.
NOTE: There are no mapped snapshots when creating an Issue outside Assessment.
=> GGRC-1306 Cannot map issue to audit

src/ggrc/assets/javascripts/plugins/utils/state-utils.js
User can filter an Audits by Status
=> GGRC-1139 Tree view filter: show special object states instead of Active - Draft - Deprecated for Audits

src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
Precondition:
2. Create issue
3. Map issue from precondition to issue
4. Go to the issue page > Control's tab > click Map button
Actual Result: "Uncaught Error: Required Data for In Scope Object is missing - Original Object is mandatory" error occurs if Map Controls to Issue on the Issue page
Expected Result: no error displayed if click Map button in Control's tab on the issues page
**Please perform deep regression testing for this issue.**
=> GGRRC-1311 "Uncaught Error: Required Data for In Scope Object is missing - Original Object is mandatory"

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/audits/summary.mustache, src/ggrc/assets/mustache/components/add-object-button/add-object-button.mustache, src/ggrc/assets/mustache/import_export/import_export_buttons.mustache
1. Create a program and add GC (progcreator@reciprocitylabs.com (engage007) as a program reader to the program
2. Create an audit
3. Log as a program reader (progcreator@reciprocitylabs.com (engage007)
4. Go to Audit summary page: confirm Create Assessment and Autogenerate buttons are present and there is a possibility to create and generate assessment
5. Go to Assessment tab-> Open 3 bb's menu: confirm import button is shown
_Actual Result:_ Global Creator as Program Reader/Global Reader can create/generate/import objects and map it to the Audit
_Expected Result:_ Global Creator as Program Reader/Global Reader cannot create/generate/import objects and map it to the Audit.
=> GGRC-853 Hide create and import buttons if user doesn't have permissions

src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
This PR sets Controls to be default object for assessments mapping.
By default when map objects to assessment is invoked, object type should be pre-selected to control. 
1. Create control, program and map them
3. Open new asmt modal window and click map object button
4. Check mapper window: Control is not selected by default
5. Create assessment and click Map button in first tier
6. Check mapper window: Control is not selected by default
Actual: Access group is selected by default
Excepted: Controls is selected by default and non-edible mapping filter to this audit is applied
Note: this is expected behavior for all mapper windows from assessment page/modal window/info pane
=> GGRC-1295 Set Controls to be default object for assessments mapping

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_import_csv.py
The columns for mapping audit, issue, and assessments are not importable
and the user should see a warning that those will be ignored.
=> GGRC-1216 Add import warning for some mapping columns

src/ggrc/templates/notifications/email_digest_content.html
~~_(there might have been a Jira ticket opened, but I do not know about it)_~~
This PR implements the proposal by Prasanna to slightly change the email text for the created Assessments notifications, i.e. from present to past tense.
=> GGRC-1317 Change tense for "Assessment created" notification

src/ggrc/assets/javascripts/components/unified-mapper/mapper.js, src/ggrc/assets/mustache/modals/mapper/base.mustache
This PR adds search-on-open behavior for mapping actions to the mapper.
From jira issue:
...first page should get loaded asynchronously in mapping modal from assessment.
=> GGRC-1296 Mapper search on open

src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
As "Verified" is an intermediate state is needed to improve the text in the Legend: "Completed and Verified"
The following statuses should be shown:
- Not Started
- In Progress
- Ready for Review
- **Completed and Verified**
- **Completed  (no verification)**
=> GGRC-1138 Fix status title in chart legend

src/ggrc/fulltext/mysql.py, src/ggrc/fulltext/recordbuilder.py, src/ggrc/fulltext/sql.py, src/ggrc/migrations/versions/20170214101700_ff4ebc0d89c_add_column_to_fulltext_records_table.py, test/integration/ggrc/services/test_query.py, test/integration/ggrc/services/test_query_snapshots.py, test/integration/ggrc/test_csvs/sorting_with_ca_setup.csv
This PS covers also GGRC-1050 "Filter doesn't work for "Person" GCA"
Precondition:
Created GCA field for control (e.g. person, date, text, dropdown types), program, at least two controls with the value in GCA field with date type, audit
2. Filter control by the value in GCA field from precondition (e.g. GCA = "1/27/2017"): no result
3. Create Assessment template with LCA (e.g. Person type) and Generate Assessment based on the control and Assessment template
4. Go to Assessment and try to filter by the value in LCA (Person type): no result
Actual Result: Filter is not working correctly for CAs for the snapshots
Expected Result: Filter is working correctly for snapshots on Audit page (by values in GCA, dates, person and etc. using …
=> GGRC-944 GGRC-1050 Filter is not working correctly for CAs for the snapshots

src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
This PR fixes mapper grid formatting issue.
Precondition:
2. Add objectives
3. Click search in Unified mapper
4. Look at the results list: confirm formatting is broken
Actual Result: Formatting is broken in Unified mapper
Expected Result: Formatting should nor be broken in Unified mapper
=> GGRC-1310 Fix mapper formatting

src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
**Add verified assessments to pie chart**
created program, audit, assessment on the audit page 
1. Navigate to Assessment's Info panel and Verify/Complete Assessment
2. Go to Audit Summary page
3. Look at the legend: assessment in verified state is not increased by one
**Actual Result**: Verified assessment is not shown in Legend on Audit Summary page
**Expected Result**: Verified and Completed assessment should be shown in Legend on Audit Summary page
Note: Legend "Completed" should show Assessments that are in Completed but Not Verified state. E.g. In progress->Completed
=> GGRC-1140 Add verified assessments to pie chart

src/ggrc/assets/javascripts/helpers/mapping_helpers.js, src/ggrc/assets/mustache/components/assessment/attachments-list.mustache
Created program, audit, assessment on the audit page
1. Navigate to Assessment's Info panel on the audit page 
2. Attach at least two evidences and refresh the page
3. Click trash icon to delete evidence: extra evidence appears
_Actual Result_: Extra evidence appears in Assessment's Info panel after refreshing the page and delete the evidence
_Expected Result_: Extra evidence should not appear in Assessment's Info panel after refreshing the page and delete the evidence
_Note_: to delete all the evidences after the steps mentioned above refresh the page is needed
=> GGRC-1109 Extra evidence appears in Assessment's Info panel after refreshing the page and delete the evidence

src/ggrc/assets/javascripts/apps/base_widgets.js, src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/controllers/dashboard_controller.js, src/ggrc/assets/javascripts/controllers/tests/inner_navigation_controller_spec.js, src/ggrc/assets/mustache/dashboard/internav_list.mustache, src/ggrc/assets/stylesheets/modules/_top-nav.scss, src/ggrc_risks/assets/javascripts/apps/risks.js, src/ggrc_risks/assets/javascripts/models/risk.js, src/ggrc_risks/assets/javascripts/models/risk_join_models.js, src/ggrc_risks/assets/javascripts/models/threat.js, src/ggrc_workflows/assets/javascripts/apps/workflows.js
**GGRC-1024**
Fix tab order for non-audit related objects for audit page according to changes in GGRC-1171, but Assessment, Issue, Program should be at first
**GGRC-1045**
Tabs color: change blue to snapshots on the right and grey fro objects on left
Left tabs should not collapse if not enough space for it, only right part should collapse
Mockups: https://goo.gl/BR0hVV
**GGRC-1171**
Scenario:
The screenshot shows standards after products tab. Hierarchy in program is:
Standards,Regulations,Sections,Objectives,Risks,Controls, Products, Systems,Process,Audit,People, AND (alphabetical order after this)
=> GGRC-1024/1045/1171 - Changes for HBN

src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
We have a query to QueryAPI on all pages that is used to hide objects not directly mapped to the current context from the second tier of tree views.
The query is done like this:
[{"object_name": "AccessGroup", "fields": ["id"], "filter": {...}}, {"object_name": "Control", "fields": ["id"], ...}, ...]
The correct form of this query is:
[{"object_name": "AccessGroup", "type": "ids", "filter": {...}}, {"object_name": "Control", "type": "ids", ...}, ...]
The reason behind the bad performance of the first format of the query for ids is that when we perform a query with "type": "values" (default), we query whole objects from the database, serialize them and leave only fields specified in "fields" list before sending them to the frontend. When we perform a query with "type": "ids", we query only …
=> GGRC-1337 Fix inefficient query for ids on all pages

src/ggrc/assets/javascripts/components/quick_form/quick_add.js, src/ggrc/assets/mustache/components/assessment/urls-list.mustache
**URL duplicates if click Add button twice**
created program, audit
1. Go to audit page and create assessment
2. Navigate to assessment's info pane
3. Click + to add URL
4. Fill url and click twice on Add button: URL duplicates
**Actual Result**: URL duplicates if click Add button twice
**Expected Result**: URL should not be duplicated if click Add button twice
=> GGRC-1119 Fix duplicating of url on double click Add button

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/permission.js
1. Log as progcreator@reciprocitylabs.com (engage007)
2. Create program, control, audit
3. Go to audit page, create assessment 
4. On assessment's Info pane map control
5. Open Related Issues tab: Raise an Issue button is not shown
Actual Result: There is no Raise an Issue button under Global creator/reader/editor. There is no possibility for users with such roles to raise an issue
Expected Result: Raise an Issue button is displayed under Global creator/reader/editor roles when map control to assessment
The fix does not fix the issue with the auditor role (auditors still won't see the button).
=> GGRC-1328 Global creator/reader/editor can not see Raise an Issue button after mapping a control to Assessment

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
This PR fixes wrong relevant filter is ignored on search in the unified mapper.
Please see #7 here:
https://github.com/google/ggrc-core/pull/5122#issuecomment-278882297
=> GGRC-1126 Fix wrong relevant filter is ignored on search

src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/mustache/base_templates/attachment.mustache, src/ggrc/assets/mustache/base_templates/mapping_tree_view.mustache, src/ggrc/assets/mustache/base_templates/people_group.mustache, src/ggrc/assets/mustache/base_templates/urls.mustache, src/ggrc/assets/mustache/components/assessment/urls-list.mustache, src/ggrc/assets/mustache/components/person/person.mustache, src/ggrc/assets/stylesheets/modules/_attachment-list.scss, src/ggrc/assets/stylesheets/modules/_label-list.scss, src/ggrc/assets/stylesheets/modules/_modal.scss
1. Unify controls in order to add URL and People
2. Trash icon behavior according to the future design
=> GGRC-470 Unify trash icon, evidence and controls in order to add URL, People and Evidance

src/ggrc/automapper/rules.py, test/integration/ggrc/automapper/test_automappings.py
This PR removes an Automapping rule that results in Assessment-NonAuditScope direct mappings.
=> QUICK-FIX Remove Assessment automapping

src/ggrc/notifications/notification_handlers.py, test/integration/ggrc/notifications/test_assignable_notifications.py, test/unit/ggrc/notification/test_notification_handlers.py
This PR fixes the issue with detecting CA changes on Assessments.
~~Integration tests are still missing, although there is a separate ticket for that (GGRC-1131) - I can add them in the scope of this PR (for the CA changes), or in a separate PR, it's up to you.
(maybe better to add them separately so that they can be written in parallel while the QA verifies the fix itself?)~~
---
created GCA for assessment, program, control, audit, assessment template with LCA
1. Generate Assessment based on Control and assessment template on the audit page and move
Assessment to In Progress state
2. Add/Update GCA or LCA value
3. Go to https://grc-test.appspot.com/_notifications/show_daily_digest or
https://grc-test.appspot.com/_notifications/show_pending …
=> GGRC-1205 Add change notification when Assessment CA changes

DEPLOYMENT.md, src/ggrc/models/mixins/customattributable.py
Previouly all custom attribute values in full text search table
of certain type were deleted - this should limit the deletion
query to affected objects only.
To the best of my testing this happens if you edit two objects of the same type (via e.g. inline edit) - only the last one has the custom attribute values saved in full text search table. This should prevent this from happening again. We should also run `$.post("/admin/reindex");` on deployment.
- create two objects of the same type with custom attributes (e.g. date custom attribute)
- set custom attribute to whatever (e.g. `date-1 = 2/13/2017`)
- edit both of the objects via inline edit, set custom attribute to the same value (e.g. `date-1 = 2/14/2017`)
- start mapping them to another object
- open mapper model
- …
=> GGRC-634 Fix search key deletion of custom attribute values

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/audit_models.js
_Steps to reproduce:_ 
 2. Create an audit and grand Auditor to audit (e.g. "user1")
 3. Go to audit page 
4. Invoke New assessment modal window: "user1" should be displayed as verifier 
_Expected Result_: If user is added to Audit as Auditor such user should be displayed as verifier in New Assessment modal window
_Clarified and confirmed questions by Prasanna_: 
1. If added two auditors to audit, two Verifiers should be shown in New Assessment modal. 
2. If a user as Auditor has been deleted from Audit such user should not be deleted as Verifier from created assessment. If a user as Auditor has been added to Audit such user should not be added as Verifier to created assessment. This is a one time behavior. 
3. In New Assessment template modal window make default …
=> GGRC-1304 Verifier should default to auditor

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/mustache/base_objects/mapper-item-description.mustache, src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item-details.mustache, src/ggrc/assets/mustache/people/dropdown_menu.mustache, src/ggrc/assets/mustache/people/mapper-item-description.mustache, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
This PR improves people result grid in the unified mapper.
GGRC-1274:
Confirmed with NK: hide CA columns for people
GGRC-1275:
Confirmed with NK: make Company the only field in Person's description for the mapper
GGRC-1276:
Confirmed with NK: the dropdown should be the same as in the Info pane
=> GGRC-1274/1275/1276 Unified mapper people improvements

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
1. On the Audit page invoke new Assessment modal window
2. Click Map object button
3. Click Select all in Unified mapper
Actual Result: "Uncaught TypeError: Cannot read property 'Snapshot' of undefined" error occurs if Select all in Unified mapper 
Expected Result: no error displayed after click select all in Unified mapper
=> GGRC-1365 Fix mapper error on “select all” action for new objects

test/selenium/pytest.ini, test/selenium/src/lib/base.py, test/selenium/src/lib/utils/selenium_utils.py, test/selenium/src/tests/test_audit_page.py
This PR improve stability of selenium tests by waiting when all JS are loaded.
Note: This improvement has drawback - test execution time is increased
=> QUICK-FIX Fix stability of selenium tests

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/base_objects/open_close.mustache
**Workflow - Status color error**
Overdue tasks has in correct icon color
It is critical for the team to see workflow status, task group status and task status in an easy and intuitive way. Hence status coloring is important to this functionality. ie RED for past due
See screenshot: https://screenshot.googleplex.com/NHepX0WyQSH.png
Task past due (we know that gGRC considers DUE TODAY as past due), but the workflow, task group and task status are all GREY.
Expected result: color bubbles accurately reflect current task status
Out of scope - due today bugs not to be addressed in this bug
1) if task OVERDUE - dot should be red
2) if task has red date - dot should be red
3) if task is red - task group and cycle should have red dot
=> GGRC-1249 Fix dot color in tasks

src/ggrc/converters/handlers/handlers.py, src/ggrc/migrations/versions/20170307131717_1a5ec1ed04af_fix_audit_context.py, src/ggrc_basic_permissions/migrations/versions/20170311142655_3ab8b37b04_clear_user_roles_with_invalid_context.py, src/ggrc_gdrive_integration/migrations/versions/20170311201102_5405cc1ae721_fix_audit_context_on_folders.py, test/integration/ggrc/converters/test_import_csv.py
When importing an audit, it will get the program context_id instead of it's own context_id. This Id then propagates through to any audit related object and thus we must fix that.
To verify the RBAC bug, we can import an audit, and then any auditor will get edit access to the parent program (which should not happen)
Objects that still have program context:
=> GGRC-1383 Fix audit contexts

src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/control.js, src/ggrc/converters/query_helper.py, src/ggrc/fulltext/__init__.py, src/ggrc/fulltext/recordbuilder.py, src/ggrc/fulltext/sql.py, src/ggrc/models/assessment.py, src/ggrc/models/audit.py, src/ggrc/models/clause.py, src/ggrc/models/control.py, src/ggrc/models/directive.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/mixins/assignable.py, src/ggrc/models/object_owner.py, src/ggrc/models/option.py, src/ggrc/models/org_group.py, src/ggrc/models/track_object_state.py, src/ggrc/snapshotter/indexer.py, src/ggrc/views/__init__.py, src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js, src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/javascripts/models/task_group.js, src/ggrc_workflows/assets/mustache/task_groups/tree_header.mustache, test/integration/ggrc/services/test_query.py, test/integration/ggrc_workflows/notifications/test_middle_level_one_time_wf.py, test/selenium/src/lib/constants/locator.py
At the moment we can't use fulltext index to search for everything typed into "Filter" field by the user.
We should index every user-searchable field.
UPD (Aleh): every field that has multiple subproperties (any person and any list field) has an additional `__sort__` subproperty in the index; it is used only for sorting by that field.
=> GGRC-1359 Add all user-visible searchable fields to the fulltext index

src/ggrc/notifications/notification_handlers.py, test/integration/ggrc/notifications/test_assignable_notifications.py
This PR fixes detecting changes to an Assessment in the following cases:
~~Writing integration tests is in progress and will later update the PR with them.~~
---
1. Create assessment on the audit page
1. Complete assessment
1. Do one of the following:
- Add/Remove Verifier (or Assignee) to assessment
- Add/remove Assessment URL
- Add/remove Assessment evidence
- Modify the  `Conclusion: operation` field (under  the `Conclusions` collapsible section)
Assessment change notification to be added when a change is made to an Assessment
(best to check the daily digest email - `<host>/_notifications/show_daily_digest`, all people assigned to the Assessment should have it)
Assessment change notification is not added.
=> GGRC-1318 Fix detecting changes on Assessments

src/ggrc_basic_permissions/roles/ProgramAuditEditor.py
**GGRC-856:** get request to '/permissions' endpoint caches
permissions. Assessment Template cannot be POSTed after it
because permissions are come from cache. Cache should be
cleared out before performing checks for POST operation or it should contain appropriate context for new AssessmentTemplate.
1. Create a program and map GC (progcreator@reciprocitylabs.com (engage007) as Program Editor
2. Create an audit
3. Log as Program Editor (progcreator@reciprocitylabs.com (engage007)
4. Go to audit and create Assessment template: confirm Program Editor gets a permission error
**Actual Result:** Creator Program Editor gets a permission error trying to save an Assessment Template
**Expected Result:** Creator Program Editor should be able to create an Assessment Template …
=> GGRC-856 Creator Program Editor gets a permission error trying to save an Assessment Template

src/ggrc/assets/javascripts/apps/base_widgets.js, src/ggrc/assets/javascripts/apps/business_objects.js, src/ggrc/assets/javascripts/components/tests/mapper-model_spec.js, src/ggrc/assets/javascripts/models/mappers/mappings-ggrc.js, src/ggrc/assets/stylesheets/modules/_top-nav.scss, src/ggrc_risks/assets/javascripts/apps/risks.js, src/ggrc_risks/assets/javascripts/models/risk.js, src/ggrc_risks/assets/javascripts/models/threat.js
This PR also fixes [GGRC-1181](https://gojira.corp.google.com/browse/GGRC-1181)
Precondition:
1. Go to Assessment tab on the audit page
2. Select Generate assessment in 3 bb's menu
3. Select "Threats" Object type: confirm audit is not appear by default
4. Select "Controls": confirm audit is not appear by default as well
Actual Result: Audit is not shown in Disabled field in Unified mapper 
Expected Result: Audit should be shown in Disabled field in Unified mapper
=> GGRC-1161 Audit is not shown in Disabled field in Unified mapper - for Risks/THreats

src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js, src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
1. Select Regulations widget on My work page
1. Click Map on the first tree view
3. In unified mapper set "Active" in dropdown filter> Click Search
3. Close unified mapper then click map again
Actual: "Active" state is displayed in multi select dropdown filter by no applied
Expected: "Active" state is displayed in multi select dropdown filter by should be applied in Unified mapper
=> GGRC-1368 Fix status filter is not applied on search after opening the mapper

src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
1. Generate assessment on the audit page based on control
2. Navigate to assessments Info pane and add verifier (progcreator@reciprocitylabs.com (engage007) in People list
3. Log as verifier (progcreator@reciprocitylabs.com (engage007)
4. Fill in mandatory CA fields if any and Complete/verify assessment
5. Click on Related Assessment/Issues/Assessment Log tabs: confirm assessment changes status from Completed/Verified Assessment to In progress
**Actual Result**: Completed/Verified Assessment moves to In progress state if press Related Assessment/Issues/Assessment Log tabs
**Expected Result**: Completed/Verified Assessment should not move to In progress state if press Related Assessment/Issues/Assessment Log tabs
=> GGRC-1240 Fix changing status on tab switching in assessment

src/ggrc/models/mixins/__init__.py, src/ggrc/utils/__init__.py, test/integration/ggrc/models/test_snapshot.py
This fixes snapshot rendering of `kind`, `means` and `verified_frequency`, however it doesn't address `Categories` and `Assertions` because those two create separate revisions. That will probably require refactoring of control type to convert to option attribute or move it to class which is probably outside of scope of this ticket.
=> GGRC-1465 Add Option stubs to Revision content

test/appengine/base.py, test/unit/appengine/test_memcache_decorator.py
It's required for activate appengine memcache for unit and integration tests
=> GGRC-1201 add ability for testing with memcache

src/ggrc/fulltext/sql.py, src/ggrc/views/__init__.py
Reindex logging on grc-test was doing way too many useless log outputs:
This PR removes the useless outputs and adds some useful ones.
=> QUICK-FIX Fix reindex logging

src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/javascripts/plugins/utils/state-utils.js
Default value in assessments page should be filtered on "**Not Started**" and "**In Progress**"  (for "**My Assessments**" and "**Assessments**" page).
Comment from @xferra :
1. For the rest - "Select ALL" checkbox should be selected by default (Now it's empty). 
2. When entering custom filter - behave as AND with State filter
3. Consistent behavior with Audit Summary numbers
3* Verify all combinations of filters
Note: Second point (_When entering custom filter - behave as AND with State filter_) has already fixed in PR #5294
=> GGRC-1297 Default State filters for assessments

src/ggrc/assets/javascripts/components/object-list-item/detailed-business-object-list-item.js, src/ggrc/assets/javascripts/components/tests/detailed_business_object_list_item_spec.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js
**Precondition**: 
created program, control, audit 
**Steps to reproduce** :
1. Generate assessment based on control on the audit page 
2. Navigate to assessment's Info pane and click on control mapped to assessment 
3. Click on Control's link: confirm the link doesn't redirect to original control 
_Actual Result_: Assessment's Info pane: link in Control's pop up doesn't work
_Expected Result_: Link in Control's pop up should redirect to original control page
=> GGRC-1220 Assessment's Info pane: link in Control's pop up doesn't work

src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache, src/ggrc/assets/mustache/assessments/related-assessments.mustache
Precondition:
Created program, control, audit, at least 10 generated assessments based on control with different Finish/Create dates
1. Navigate to Assessment's Info panel on the audit page
2. Open Related assessments window
3. Look at the sorting by ASSESSMENT CREATE DATE: is not sorted in descending order
Actual Result: Sorting by ASSESSMENT CREATE DATE is not working in Related assessments  
Expected Result: Sorting by ASSESSMENT CREATE DATE should work in descending order in Related assessments  
Note: First sort by finish date if not exist then sort by create date.Finished Dated and Created Date in descending order.
=> GGRC-1179 Sorting by ASSESSMENT CREATE DATE is not working in Related assessments

src/ggrc/converters/query_helper.py, test/selenium/src/tests/test_audit_page.py
1. Create a Program, map a Control to it.
2. Create an Audit in this Program.
3. Change the base Control.
4. Go to the Control's Snapshot, click "Compare to the latest version".
Expected result: Snapshot comparison window is displayed.
Actual result: The backend doesn't retrieve Revisions as the Query filters them by id (`id = one_id OR id = another_id`).
`critical` as it blocks the following PRs: #5330 #5318
=> GGRC-1405 Allow direct filter by id (which is not indexed)

src/ggrc/models/snapshot.py, test/integration/ggrc/snapshotter/__init__.py, test/integration/ggrc/snapshotter/test_snapshoting.py
1. Create a Control.
2. Open the Unified Mapper for it.
3. Select Audit as mapped object type, click search.
4. Select at least two Audits for mapping, click "Map".
Expected result: The Control is mapped to the respective Programs, Snapshots are created for the checked Audits.
Actual result: HTTP500 is returned, nothing is mapped or snapshotted.
Tech details: prior to this PR we used to have an assertion that we map to just a single Audit. Now it is gone and multiple Programs can be mapped (quite safely due to INSERT IGNORE).
=> GGRC-1203 Allow creating Snapshots in several Audits at once

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/base_objects/open_close.mustache
Overdue tasks has in correct icon color
It is critical for the team to see workflow status, task group status and task status in an easy and intuitive way. Hence status coloring is important to this functionality. ie RED for past due
Task past due (we know that gGRC considers DUE TODAY as past due), but the workflow, task group and task status are all GREY. 
Expected result: color bubbles accurately reflect current task status
Out of scope - due today bugs not to be addressed in this bug
1) if task OVERDUE - dot should be red
2) if task has red date - dot should be red
3) if task is red - task group and cycle should have red dot
=> GGRC-1249 Fix status color for overdue tasks

src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/mappers/sub-tree-loader.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/mustache/base_objects/open_close.mustache, src/ggrc/assets/mustache/components/tree/tree-node-actions.mustache, src/ggrc/assets/stylesheets/_common.scss, src/ggrc/assets/stylesheets/modules/_tree-content.scss
**Fixes GGRC-1117, GGRC-1115, GGRC-625, GGRC-1358**
**Fix tree view for snapshots**
Tree view for snapshots:
1. for snapshot line -  no Map button
2. snapshot item should NOT be expanded (remove arrow)
3. For Assessment and Issue lines in tree view - when expand - we show original relationships objects (audit program etc) and mapped snapshots (everywhere) (snapshot of control, no original object)
**Assessment info page, Control tree view: tree view second tier doesn't show any mappings for a Control snapshot**
1. Go to audit page and generate assessment based on Control
2. Go to Control page -> Assessment tab
3. Click map and Search for Controls: Controls snapshots are shown in Unified mapper that are not related to …
=> GGRC-1358 Display snapshot in second tier of tree view

src/ggrc_basic_permissions/roles/ProgramAuditEditor.py
allowed to read, update and delete permissions for assessment templates to ProgramAuditEditor role
=> GGRC-1479 Fix permissions for ProgramAuditEditor

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/js_specs/mustache_helpers/is_overdue_spec.js
**"Uncaught TypeError: Cannot read property 'hash' of undefined" error is displayed if open any widget with overdue object in tree view**
1. Go to All objects/ My objects page
2. Open e.g. "Objectives" widget in HNB
**Actual Result**: "Uncaught TypeError: Cannot read property 'hash' of undefined" error is displayed
**Expected Result**: No error displayed
=> GGRC-1475 Fix empty status in is_overdue

src/ggrc/assets/javascripts/components/quick_form/quick_add.js
1. Create a program and add GC as Program reader into program
3. Create an audit and add auditor to audit
Actual Result: "Uncaught TypeError: Cannot read property 'value' of undefined" error is displayed while adding GC as auditor to audit
Expected Result: no error displayed. GC as Auditor should be added to audit
=> GGRC-1464 "Uncaught TypeError: Cannot read property 'value' of undefined" error

src/ggrc/assets/mockups/mockup_base_templates/info_panel/info_panel_utility.mustache, src/ggrc/assets/mockups/quick-workflow/info.mustache, src/ggrc/assets/mockups/request/info.mustache, src/ggrc/assets/mustache/assessments/header.mustache, src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache, src/ggrc/assets/mustache/base_objects/dropdown_menu_tier2.mustache, src/ggrc/assets/mustache/base_templates/header.mustache, src/ggrc/assets/mustache/mapped_objects/dropdown_menu_tier2.mustache, src/ggrc/assets/mustache/people/dropdown_menu.mustache, src/ggrc/assets/mustache/people/object_list.mustache, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache, src/ggrc/assets/stylesheets/_common.scss, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache, src/ggrc_workflows/assets/mustache/cycles/info.mustache, src/ggrc_workflows/assets/mustache/task_groups/info.mustache, src/ggrc_workflows/assets/mustache/workflows/info.mustache
2. Select any object's tab from HNB (e.g. Controls)
3. Click on 3 dots menu: confirm Hide Filter is not grayed
_Actual Result_: Hide Filter is not grayed in 3 dots menu
_Expected Result_: Tree view tools should be one color in 3 dots menu. So it should be grayed
_need to implement_: remove show/hide filter option at all.
=> GGRC-959 Ungrey the 3bbs menu options

src/ggrc/assets/javascripts/components/paginate.js, src/ggrc/assets/mustache/base_objects/paginate.mustache
Precondition:
- created program, audit
3. Make changes for Assessment: e.g. fill values in GCA if any, complete assessment, map any objects to Assessment, attach evidence/urls
4. Go to Assessment Log and ensure that log contains at least two pages
5. Click "Next" link: confirm is not followed to the next page
Actual Result: Pagination doesn’t work in Assessment Log in Assessment's Info pane
Expected Result: Pagination should work in Assessment Log in Assessment's Info pane if click on "Next" and "Previous" links
=> GGRC-809 Pagination doesn’t work in Assessment Log in Assessment's Info pane

src/ggrc/models/mixins/__init__.py, src/ggrc/snapshotter/indexer.py, test/integration/ggrc/models/test_snapshot.py
1. Run reindex.
Expected result: reindex is finished without errors.
Actual result: reindex fails with SQL syntax error.
Also this PR fixes fulltext index for Options, displaying Options in "update to latest version" popup and fulltext index for boolean fields in Snapshots (all in a hacky way).
1. Create a Control with "kind" = "Corrective".
2. Map the Control to a Program, create a Program in the Audit.
3. Go to the Audit, open Controls tab, try to filter by "kind = Corrective".
4. Edit the original Control, set "kind" = "Preventative" and "Fraud related" = "False".
5. Go to the Audit, open Controls tab, update the Snapshot to the latest version.
6. Try to filter by "kind = Preventative" and '"Fraud related" = False'.
Expected results: on 3 and 6, …
=> GGRC-1483 GGRC-1468 GGRC-1480 Fix index of Options in Snapshots

src/ggrc/automapper/__init__.py, src/ggrc/services/__init__.py, src/ggrc/services/relationship_resource.py
The old hack to create Snapshots by POSTing to `/api/relationships` created a Relationship and Snapshot for requests to map Audits to Snapshottables.
The new hack just creates Snapshots on JSON deserialization.
=> GGRC-1269 Avoid creating a Relationship on Snapshottable-Audit mapping

src/ggrc/notifications/data_handlers.py, test/integration/ggrc/notifications/test_data_handlers.py
This PR makes sure that Assessment declined notifications are sent to all people assigned to an Assessment, not just to Assignees.
---
1. Create assessment on the audit page 
1. Make sure that creator, assignee and verifier exist in People list 
1. Change assessment's states: complete, update, ready for review, reject, verify, reopen assessment 
1. Add new Creator, Assignee, Verifier to assessment 
New added Creator and Verifier don't get notification that assessment has been declined 
Notification to be added when a new creator, assignee, verifier are added to assessment
=> GGRC-1318 Fix sending declined notifications to all Assessment roles

test/integration/ggrc_basic_permissions/test_audit_rbac.py
Add permission test for get and put action to assessment_temaplate handle. 
~depend on: https://github.com/google/ggrc-core/pull/5368~
=> GGRC-1263 add tests assessment template

src/ggrc/assets/javascripts/pbc/workflow_controller.js, src/ggrc/assets/mustache/assessments/tree_add_item.mustache, src/ggrc/models/hooks/assessment.py, src/ggrc_basic_permissions/roles/Auditor.py
Auditor should not be able to create relationships in the audit
context. The only exceptions to this are the relationships that map
Issue/Assessment to the Audit, but those will be handled separately.
=> GGRC-1484 GGRC-1501 Remove create Relationship permission for Auditor

src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js, src/ggrc/assets/javascripts/plugins/utils/state-utils.js
1. Open Search Unified mapper
2. Select "Assessment" in object type
3. Apply filter by "In progress" or "Not Started"> Search: no results
4. Apply filter by "Completed"> Search: works
_Actual Results_: Multi select dropdown filter is not applied in Unified mapper if state contains two words or more
_Expected Result_: Multi select dropdown filter should be applied in Unified mapper if state contains two words or more
=> GGRC-1463  Multi select dropdown filter isn't applied in Unified mapper if state contains two words or more

src/ggrc/assets/javascripts/controllers/summary_widget_controller.js, src/ggrc/assets/mustache/audits/summary.mustache, src/ggrc/assets/stylesheets/modules/_audit-summary.scss
The following improvements have been confirmed:
1. Assessments are show without numbers in brackets
2. Three columns: state, count, percent
3. Total:
=> GGRC-1347 Change style of pie-chart

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/tests/assessment_model_spec.js
1. As auditor go to the issues tab and open an issue info pane.
2. After step 1, anytime you click the create assessment button, a script error is thrown.
Auditor does not have access to the program so the program property on
the audit might not be set. Because we do not map assessments to
programs anymore it’s safe to just remove the check and prevent
assigning the program variable on the assessment.
=> GGRC-1487 Fix script error when create assessment button is clicked

src/ggrc/services/relationship_resource.py, test/integration/ggrc/snapshotter/test_snapshoting.py
This PR fixes a typo that breaks Snapshot generation on Audit-Snapshottable Relationship POST when `source` is Snapshottable and `destination` is Audit.
1. Create a Control.
2. Create a Program.
3. Create two Audits in the Program.
4. Open a tree view with the Control, click "map" button on it.
5. Select both Audits in the unified mapper, click "map".
Expected result: the Control is mapped to the Program, Snapshots of the Control are created in both Audits.
Actual result: the Control is mapped to the Audits directly.
=> GGRC-1203 Fix a copy-paste issue

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_import_helpers.py
This filed shouldn't be mandatory on import and export actions to Assessment Template
=> GGRC-1376 Default Verifier does not required 

src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/models/assessment_template.py
**GGRC-1375 "Default Verifier" field marked as mandatory in New Assessment template modal window**
1. On the audit page invoke New Assessment template modal window
2. Look at the "Default Verifier" field
_Actual Result_: "Default Verifier" field marked as mandatory in New Assessment template modal window
_Expected Result_: "Default Verifier" field should not marked as mandatory in New Assessment template modal window
**GGRC-1377 Allow "Default Verifier" field be empty in New Assessment template modal window**
1. On the audit page invoke New Assessment template modal window
2. Expand dropdown for the "Default Verifier" field: confirm it cannot be empty
_Actual Result_: the "Default Verifier" field cannot be empty in New Assessment template modal …
=> GGRC-1375/GGRC-1377 "Default Verifier" field marked as mandatory in New Assessment template modal window

test/selenium/src/lib/base.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/string_utils.py, test/selenium/src/tests/conftest.py, test/selenium/src/tests/test_audit_page.py, test/selenium/src/tests/test_people_groups_page.py, test/selenium/src/tests/test_program_page.py, test/selenium/src/tests/test_risk_threats_page.py
This PR ~depends on #5348~ and add 1 test case:
Check that audit contains snapshotable control after delete original control.
=> QUICK-FIX Test snapshotable control after delete original

src/ggrc/assets/javascripts/components/relevant_filters.js, src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
1. Open Search Unified mapper and click filter by mapping: preselected object is not displayed
2. Select object from dropdown list (e.g. Audit), enter text to search audit, then select audit from list and click search: results are displayed in search results
3. Delete audit title and click Search: search results are the same
4. Change audit title but don't select from dropdown list (type audit title): search results are the same
Expected result: 
1. If click Filter by mapping preselected object should display. In this case "Access Group" 
2. Search results should correspond according to selected title of the object
=> GGRC-1126 Fix mapper relevant control autocomplete issues

src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
**"Script error" message is displayed while moving to the audit page**
**Precondition**: 
Create program, control, audit, several assessments.
It is necessary to have at least one empty state in legend
(line with zero count, for example Not Started .......... 0)
1. Go to Audit Summary
2. Go to assessment widget and add new Assessment in Not Started state
3. Go to audit page, over mouse to legend items: confirm an error is displayed
**Actual Result**: "Script error" message is displayed while moving to the audit page
**Expected Result**: no error displayed
=> GGRC-921-additional Unbind event from pie chart legend

src/ggrc/assets/mustache/components/dropdown/multiselect_dropdown.mustache, src/ggrc/assets/stylesheets/components/multiselect-dropdown/_multiselect-dropdown.scss, src/ggrc/assets/stylesheets/modules/_filters.scss
As discussed with Kseniya Koltun the ticket is reopened due to the following:
1. Filter by State: should be 12 font size, #969696.
2. Padding between question icon and Filter by state should be 30.
3. Filter by state in Unified mapper should be with rounded corners.
4. Filter in blue button - should be regular weight.
5. If click Filter by state blue line around the filter is shown. Should be the same in Unified mapper.
**NOTE**: Point #4 is not implemented, because we need to discuss this with Kseniya
=> GGRC-1324 Improve dropdown multi select filter

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/components/tests/people_list_spec.js, src/ggrc/assets/javascripts/components/tree/tests/tree-assignee-field_spec.js, src/ggrc/assets/javascripts/components/tree/tree-assignee-field.js, src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
Precondition:
- have program, audit
1. Create assessment on the audit page and add assignee and verifier (make sure that creator, assignee, verifier are shown in People list)
2. Look at Assessment's tree view first level: creator, assignee, verifier are shown
Actual Result: currently creator, assignee, verifier are not shown in tree view first level
Expected Result: creator, assignee, verifier are shown are shown in tree view first level
=> GGRC-1281 Show assessors, creators and verifiers in tree view

src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/mustache/base_objects/tree_view_filter.mustache, src/ggrc/assets/stylesheets/modules/_tree-header.scss, src/ggrc_workflows/assets/mustache/cycles/tree_header.mustache
The PR fixes **GGRC-1525**, **GGRC-1503**
**GGRC-1525**
**User doesn't get notification in Active Cycles that active workflow will start in future**
1. Create weekly WF
2. Create task and set start date in future (e.g. if today Monday - set Wednesday - Friday)
3. Activate workflow and go to Active Cycles tab
**Actual Result**: User doesn't get notification in Active Cycles that active workflow will start in future
**Expected Result**: User should get notification in Active Cycles that active workflow will start in future
**GGRC-1503**
**Tree view collapses if open audit widget**
1. As admin go to My work page
2. Open All objects page
3. Open Audit widget
Actual Result: Tree view collapses if open audit widget
Expected Result: Tree view should …
=> GGRC-1525 (GGRC-1503) Fix notification in active cycles tab

src/ggrc/services/common.py, src/ggrc/snapshotter/indexer.py, test/integration/ggrc/snapshotter/test_snapshoting.py
Precondition:
have a program, control with GCA (e.g. text type), audit
2. Return back to program and fill GCA 
3. Go to audit page and update control to the latest version
4. Try to filter by GCA in Control: no result
Actual Result: While updating snapshots to the latest version search index is not updated 
Expected Result: While updating snapshots to the latest version search index should be updated
=> GGRC-1384 While updating snapshots to the latest version search index is not updated

src/ggrc/converters/base.py, src/ggrc/converters/base_block.py, src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/converters/handlers/handlers.py, src/ggrc/models/control.py, src/ggrc/models/option.py, src/ggrc/views/converters.py, src/ggrc_basic_permissions/converters/handlers.py, test/integration/ggrc/converters/test_base_block.py
Exporting 2K objects with a lot of mappings caused app-engine to timeout and throw an error.
This PR fixes currently the biggest bottleneck in exports with mappings.
Benchmarks (mapping cache for 2k regulations and around 100 different mappings):
before: 18.4923s
after: 0.3593s
Additional benchmark (exporting all Programs, Controls and regulations from grc-test db):
before: 169.3381 seconds - 98001 queries
after: 39.4760 seconds - 14502 queries 
after 5f7937b: 38.9554 seconds - 9485 queries
after 0d302d0: 34.9496 seconds - 3433 queries
=> GGRC-1493 GGRC-1626 Improve export performance

src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
1) Create Assessment Template
2) Navigate on Assessment Template 
OR
Navigate on Audit page and open Assessment Templates tab
3) Open Edit Assessment Template dialog
Actual: no Audit data in the dialog window.
Expected: Audit name is provided in Edit Assessment Template dialog.
=> GGRC-85 Add Audit name on Edit Assessment Template modal window

src/ggrc/converters/query_helper.py, src/ggrc/models/object_owner.py, test/integration/ggrc/services/test_query/test_snapshots.py
This PR removes special logic to search by Owners. Since Owners are indexed correctly, the default search via fulltext table works both on the original objects and on Snapshots.
2. Create a Control with User1 as Owner and map it to the Program.
3. Create an Audit in the Program.
4. Open the Audit, go to Controls tab.
5. Search for "owners = User1" or "owner = User1".
Expected result: the Snapshot is displayed both times.
Actual result: the Snapshot is not displayed on "owner = User1".
~Depends on #5395~
=> GGRC-587 Fix filtering by Owners of Control Snapshots

src/ggrc/assets/javascripts/models/issue.js
1. On the audit page create Issue and add Issue URL while creating
2. Open Set visibility dialog and mark Issue url> Set fields
_Actual Result_: "Issue" field instead of "Issue URL" is displayed in tree view and Set visibility dialog
_Expected Result_: "Issue URL" is displayed in tree view and Set visibility dialog
=> GGRC-1682 "Issue" field instead of "Issue URL" is displayed in tree view and Set visibility dialog

src/ggrc/snapshotter/indexer.py
If fulltextattr class set up as fulltextattr then take it's alias on
reindex snaphsot procedure
=> QUICK-FIX: Fix Snapshot indexer

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/mustache/assessments/modal_content.mustache
**Possibility unmap assessment from audit**
1. On the Audit page create assessment
2. Map control to audit and map this control to assessment
3. Open Edit Assessment modal window
4. Click trash icon to unmap audit from assessment: success
**Actual Result**: There is a possibility to unmap assessment from audit in Edit Assessment modal window
**Expected Result**: Removing the mapping of assessment to audit is not
allowed. So there cannot be unmap against an audit.
=> GGRC-1367 Disable ability to unmap audit from assessment

src/ggrc/assets/javascripts/models/assessment.js
**GGRC-1366**
**Control and control's snapshot are shown in Edit Assessment modal window**
1. On the Audit page create assessment
2. Map control to audit and map this control to assessment
2. Open Edit Assessment modal window
3. Look at mapped objects to assessment: Control and control's snapshot are shown
**Actual Result**: Control and control's snapshot are shown in Edit Assessment modal window
**Expected Result**: Only control's snapshot that is mapped to assessment should be shown in Edit Assessment modal window and marked with a blue color
**GGRC-1628**
**Edit Assessment - remove mapped comments**
=> GGRC-1366 (GGRC-1628) Remove objects and comments from edit assessment

src/ggrc/assets/mustache/audits/tree_add_item.mustache
This PR removes the Map button from the tree view on an Audit tab if the parent object's type is "Assessment".
The way I understood the ticket is to just remove the button. _Enforcing_ a backend check that an Assessment could not get mapped to multiple Audits is probably a whole different story.
---
created program, control, audit, assessment
1. Go to Assessment Info page
2. Audit tab: Map button in tree view is shown
Map button in Audit tab is shown on Assessment Info page
Assessment Info page: Remove [Map] button in tree view in audit tab. There should not be the possibility to map assessment to another audit
=> GGRC-1307 Remove Map button from Assessment's Audits tab

src/ggrc/converters/base_block.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc/test_csvs/data_for_export_testing_directives.csv, test/integration/ggrc/test_csvs/data_for_export_testing_program.csv, test/integration/ggrc/test_csvs/data_for_export_testing_program_audit.csv, test/integration/ggrc/test_csvs/data_for_export_testing_program_contract.csv, test/integration/ggrc/test_csvs/data_for_export_testing_program_policy_contract.csv, test/integration/ggrc/test_csvs/data_for_export_testing_relevant_previous.csv, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
~This PR is just an improvement on the tests refactor from https://github.com/google/ggrc-core/pull/5404.~
~It will be rebased once the original PR is merged.~
This PR is just for performance improvement in tests, but also includes fixes export cache. 
Export tests average runtime
on current raspberry branch: 54.904s
~on PR #5404: 194.893s~
on this PR: 33.329s
Edit: the original PR had the refactor commit removed and I have cherry picked it into this PR.
=> QUICK-FIX fix export caching and improve fixtures for export integration tests

src/ggrc/assets/javascripts/components/dropdown/multiselect-dropdown.js
1. Go to My Work page and Open Search Unified mapper
2. Select "Program" in object type and choose "Active" in Multi select dropdown filter > Search
3. Select another object "Assessment"
4. Look at field in Multi select dropdown filter: active state is applied to Assessment that doesn't have Active state
_Actual Result:_ Multi select dropdown filter is not cleaned if object that contains the states differ from Active, Draft, Deprecated is selected 
_Expected Result:_ Multi select dropdown filter should be cleaned if object that contains the states differ from Active, Draft, Deprecated is selected
=> GGRC-1461 Multi select dropdown filter is not cleaned if object that contains the states differ from Active, Draft, Deprecated is selected

src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js, src/ggrc/assets/javascripts/controllers/tree/tree-view.js, src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js, src/ggrc/assets/javascripts/plugins/utils/state-utils.js
1. Go to My work page and open e.g. "Assessment" widget
2. Click Map button in the first tier
3. Look at dropdown filter
_Actual Result:_ States are not preselected in multi select dropdown filter in Unified mapper/Global Search as for tree view
_Expected Result_: States should be preselected in multi select dropdown filter in Unified mapper/Global Search as for tree view
=> GGRC-1583 States should be preselected in multi select dropdown filter in Unified mapper/Global Search as for tree view

src/ggrc/assets/mustache/import_export/export.mustache, src/ggrc/assets/stylesheets/modules/_import-export.scss
Move Export Object button to the left side of Add object type button, so that the user doesnt have to move their mouse on each side.
=> GGRC 1175 Move export objects button to the left "Add another object type" button

src/ggrc/assets/mustache/components/assessment/urls-list.mustache, src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
Precondition: Created program, audit
3. Fill mandatory CA if any > Click complete button
4. Add a Verifier
5. Click Complete and Verify button
6. Add evidence: confirm incorrect massage is displayed ("Request" instead of "Assessment" was shown)
=> GGRC-715  Fix incorrect message if Assessment moves from Complete state to In progress

src/ggrc/assets/mustache/base_objects/contacts.mustache
**Blank field is displayed if open third tier in tree view**
1. On My work page select Sections widget
2. Select Section with "Active" state and click gray triangle to open subtree
3. For the object in the second tier (e.g. "Objective") click gray triangle to open third tier
**Actual Result**: Blank field is displayed if open third tier in tree view
**Expected Result**: No blank field is displayed if open third tier in tree view
=> GGRC-1369 Fix using of #each helper with #using helper

src/ggrc/converters/autocast.py, src/ggrc/converters/custom_operators.py, src/ggrc/converters/exceptions.py, src/ggrc/converters/query_helper.py, src/ggrc/fulltext/attributes.py, src/ggrc/models/mixins/__init__.py, src/ggrc/services/query.py, src/ggrc/services/query_helper.py, src/ggrc/utils/date_parsers.py, src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/models/cycle_task_group.py, src/ggrc_workflows/models/cycle_task_group_object_task.py, test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
Implements a custom handler for `=` operator for datetime values and a custom parser for partial datetime values in filter query.
Cases covered:
`updated_at = 2017`
`updated_at = 2017-12`
`updated_at = 2017-12-01`
`updated_at = "2017-12-01 13"`
`updated_at = "2017-12-01 13:45"`
`updated_at = "2017-12-01 13:45:55"`
`updated_at = 12/2017`
`updated_at = 12/01/2017`
`updated_at = "12/01/2017 13"`
`updated_at = "12/01/2017 13:45"`
`updated_at = "12/01/2017 13:45:55"`
Note: all dates entered are supposed to be in UTC. Timezone conversion will be added in a separate PR.
=> GGRC-1432 Add filtering by date, datetime and their partials

src/ggrc/assets/stylesheets/_common.scss, src/ggrc_workflows/assets/mustache/cycles/tree_header.mustache, src/ggrc_workflows/assets/mustache/workflows/info.mustache
**Archived WF displayed as active**
1. Create annual WF
2. Set start date in future
3. Archive WF
**Excepted**:
a. WF status displayed as Archived not as Active
b. Notification message at active tab shouldn't be displayed
=> GGRC-1573 Add status label for archived WF

test/integration/ggrc/models/mixins/test_autostatuschangable.py, test/integration/ggrc/notifications/test_assignable_notifications.py
This PR adds even more integration tests on top of the existing ones for Assessment notifications. Some of them cover a few extra edge cases when modifying Assessments through the API, while the rest focus on testing notifications when interacting with Assessments through imports.
The tests that have discovered issues and would otherwise fail were marked as skipped, as fixing the corresponding issues is out of scope of this PR, namely:
- changing Assessment people through imports
- changing Assessment URLs through imports
- attaching Assessment evidence through imports
- modifying Assessment's custom attribute values
- creating "assessment reopened" notification when editing Assessment people through imports
- creating "assessment reopened" notification when editing Assessment URLs …
=> GGRC-1131 More tests for Assessment notifications

test/selenium/src/lib/base.py, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/page/modal/unified_mapper.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/filter_utils.py, test/selenium/src/tests/test_audit_page.py, test/selenium/src/tests/test_snapshots.py
This PR address 2 things:
1. Split snapshot tests and regular audit tests
2. Add test `test_filter_of_snapshotable_control` to check that filtering in scope of Audit works by snapshoted version of object (not actual)
=> QUICK-FIX Test Snapshot filtering

src/requirements-dev.txt
This update fixes re-running tests with sniffer.
To test this PR, run sniffer inside `test/unit` and save any python test file. On the second run the unittests with freezegun begin failing.
=> QUICK-FIX Update freezegun python package

src/ggrc/assets/javascripts/components/mapped_tree_view.js, src/ggrc/assets/javascripts/components/tests/mapped_tree_view_spec.js, src/ggrc/assets/mustache/base_templates/comment_list.mustache
**Improve comments ordering in Assessment's Info panel**
1. Navigate to assessment's Info panel
2. Add at least 3 comments
3. Look at the comments ordering: new comment is shown below the previous one
**Actual Result**: New comment is shown below the previous one
**Expected Result**: New added comment should be displayed above the previous one
=> GGRC-1049 Change comment order

src/ggrc/fulltext/attributes.py, test/integration/ggrc/services/test_assessments.py
Ordering didn't work because there is no "" or "\_\_sort\_\_" indexed subproperty.
=> GGRC-1683 fulltext sorting fix

test/selenium/src/lib/base.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/tests/test_unified_mapper.py
This PR address 2 things:
1. Fix StaleElementException during selecting object in Unified Mapper window that caused by list refreshing after search
2. Fix unstable list comparison that caused by ordering problem of excepted and actual list of object (because we doesn't specify order for queryApi call we can't rely on default ordering by object id)
=> QUICK-FIX Test Fix stability of unified mapper test

src/ggrc/models/assessment.py, src/ggrc/models/object_owner.py, src/ggrc/models/person.py
To make all multiple person attributes indexed correctly and in the same way.
Depends on: QUICK-FIX Test Fix stability of unified mapper test #5467
And should work fine then.
=> QUICK-FIX sort_by subproperty add into Person

src/ggrc/models/mixins/__init__.py, test/integration/ggrc/converters/test_export_assessments.py
It's required for filtering verified_date and finished_date for assessments 
~depends on: https://github.com/google/ggrc-core/pull/5480~
=> GGRC-1767 finished and verified date as datetime

src/ggrc/assets/javascripts/components/add_comment/add_comment.js, src/ggrc/assets/mustache/assessment_templates/info.mustache, src/ggrc/assets/mustache/assessment_templates/modal_content.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache
1. Invoke New Control modal window
_Actual Result_: Principal Assessor and Secondary Assessor fields are displayed
_Expected Result_: Principal Assignee and Secondary Assignee fields are displayed in New/Edit Control modal window
**Note**: change Assessor to Assignee across the application
=> GGRC-1770 Rename Principal Assessor/Secondary Assessor to Principal Assignee/Secondary Assignee in Control modal window and across the application

src/ggrc_workflows/assets/javascripts/models/cycle_models.js, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree_header.mustache
Tree view column names on My Tasks tab are out of sync with Task info pane labels.
_Proposed renames:_
1. Title -> Task title
2. Workflow -> Cycle title
3. State -> Task state
4. Assignee -> Task assignee
5. Start date -> Task start date
6. End date -> Task due date
7. Last updated -> Task last updated
The values of **attr_sort_fields** match the column titles.
Related to PR #5480
=> GGRC-1758 Update tree view columns on My Tasks tab

src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/mustache/base_objects/general_info.mustache, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
3. Create an audit and add auditor to audit (progcreator@reciprocitylabs.com)
4. Log as auditor (progcreator@reciprocitylabs.com (engage007) and go to audit page
5. Open Control widget and click 3 bb's button on Info pane
Actual Result: "View original Control" link is shown in 3bb's menu on Control's snapshot Info pane under GC as auditor
Expected Result: GC as auditor in audit should not be able to see "View original Control" link
In addition this PR also hides update to latest revisions links if the user does not have access to the parent object.
=> GGRC-1488 Hide View original object link for auditors

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/tests/assessment_model_spec.js
This PR fixes a script error that can occur when opening the Assessments section in LHN. Assigned @xferra because he made a few of the latest changes changes in the affected code.
I'm not completely sure what is meant by "broken" in the ticket description, though, is it about the script error?
(UPDATE: It was confirmed that this ticket is just about the script error.)
I have noticed once or twice that when opening the Assessments section, the list of items was empty, even though the count in the section header suggested otherwise. I'm not sure if this is the same issue, or should that behavior be investigated as a part of a different story...
---
1. Open LHN
2. Expand Assessments accordion: Assessments view is broken
Assessments view in LHN is …
=> GGRC-1202 Fix script error when opening Assessments in LHN

src/ggrc/assets/javascripts/plugins/ggrc_utils.js
IMPORTANT: If we decide, based on the risk assessment, that we will not include this fix in the upcoming release, please apply the `on hold` label to the PR on my behalf, thanks.
---
This PR fixes a problem with exporting large amount of data (i.e. more than ~1.4 MB).
The root cause was handling the data on the frontend after downloading it. The data was first URL-encoded and then set as a value of the temp DOM element's `href` attribute using the "data:" protocol. In Chrome at least, the maximum permitted size of that attribute is 2 MB, and large CSV data hits that limit.
This PR changes the way data is handled. It creates a temporary file using the browser's virtual file system API, and then points to that temporary file using the `'filesystem:<host>/temporary/<filename.csv>` link.
The …
=> GGRC-1493 Fix downloading large exported data sets

src/ggrc/assets/assets.yaml, src/ggrc/assets/mustache/controls/contacts.mustache, src/ggrc/assets/mustache/controls/info.mustache, src/ggrc/assets/mustache/controls/urls.mustache
**Comment by User:**
_Can we move:_
1) "Principle Assignee" to the spot of "Primary Contact", and
2) "Secondary Assignee" to the spot of "Secondary Contact"?
Since we are using control "owner" field in a different way now and will be named "admin". It would be more useful to see the principle and secondary assignees in the main popup window instead of having to click "show advanced" button. The principal assignee being the real world control owner, and secondary assignee being the real world control oversight owner.
=> GGRC-1495 Move assignees to contacts in the control popup

src/ggrc/assets/javascripts/controllers/tree/tree-view.js
Precondition: have program, control, audit, assessment with mapped control to assessment 
1. Go to My assessments page
2. Expand second level for assessment
Actual Result: Mapped Control is not shown in the second level as Control doesn't have states as applied in filter for assessment
Expected Result: Multi select dropdown filter should be applied for objects first tier. In this case multi select dropdown filter should be applied only for Assessment, not for Control which is mapped to Assessment. Control should be shown if expand second level.
=> GGRC-1584 Apply multi-select dropdown filter for objects first tier only

src/ggrc/assets/javascripts/components/inline_edit/inline.js
Preconditions:
1. Create GCA with person type for Control
2. Created program, Control
1. Navigate to Control's Info pane
2. Add person to GCA (e.g. "Person1") 
3. Save it 
4. Click edit icon to edit GCA "Person1"
5. Click ''X' without any changes
Actual result: value is hidden in GCA field with person type after closing GCA without changes in Object's Info pane
Expected result: Value is shown in GCA field with person type after closing GCA without changes in Object's Info pane
=> GGRC-839 Fix GCA visibility after discarding changes in it

src/ggrc/assets/javascripts/components/state-colors-map/state-colors-map.js, src/ggrc/assets/javascripts/components/state-colors-map/tests/state-colors-map_spec.js
**Unify colors for assessment states in tree view/audit summary page/related assessments tab**
1. Create at least 5 assessments on the audit page
2. States for the created assessments should be: Not Started, In Progress, Ready for Review, Completed and Verified, Completed (no verification)
3. Navigate to Info panel one of the assessment and open Related Assessments window
4. Look at ASSESSMENT STATE
**Actual Result**: ASSESSMENT STATE color in Related Assessments tab is differ from the color in pie chart (e.g. "In progress" is colored with orange, should be in blue color) and there is no dot marked as state color
**Expected Result**: Unify colors for assessment states in tree view/audit summary page/related assessments tab
=> GGRC-1533 Change status color in Related Assessments

src/ggrc/assets/stylesheets/components/tree_pagination/_tree_pagination.scss, src/ggrc/assets/stylesheets/modules/_filters.scss
1. Open Section widget on My Work page
2. Look at pagination: "xxx" of "xxx" items
3. Follow to the next page
_Actual Result_: "Item" is displayed out of field
_Expected Result_: "Item" should not displayed out of field
=> GGRC-1370 "Item" is displayed out of field

src/ggrc/assets/mustache/people/filters.mustache, src/ggrc/assets/stylesheets/modules/_filters.scss
1. Log as admin and open People tab on admin dashboard
2. Look at filters By Name and By Roles
_Actual Result_: Filters By Name and By Roles are broken in People tab on Admin Dashboard
_Expected Result_: Filters By Name and By Roles should not be broken in People tab on Admin Dashboard
=> GGRC-1380 UI: Fix filters by Name and Roles in People tab on Admin Dashboard

src/ggrc/assets/mustache/dashboard/object_widget.mustache
**Add text "Audit Summary" to Audit Summary page**
1. Go to Audit Summary page
2. Look at page: text "Audit Summary" is absent
**Actual Result**: Text "Audit Summary" in Audit Summary page is not shown
**Expected Result**: Text "Audit Summary" is shown in Audit Summary page
=> GGRC-997 Add title in Audit Summary widget

src/ggrc/assets/javascripts/components/datepicker/datepicker.js, src/ggrc/assets/javascripts/components/tests/datepicker_spec.js, src/ggrc/assets/mustache/components/effective-dates/effective-dates.mustache, src/ggrc/assets/mustache/custom_attributes/modal_content.mustache, src/ggrc_risk_assessments/assets/mustache/risk_assessments/modal_content.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache, src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
1. Create mandatory GCA with date type for program
2. On My work page click Start a new program
3. Look at the mandatory field with date type: mandatory date fields are missing the red star
_Actual Result_: Mandatory date fields are missing the red star
_Expected Result_: Mandatory date fields should have the red star
=> GGRC-1268/GGRC-382 Mandatory date fields are missing the red star mark

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/snapshotter/open-original-link.js, src/ggrc/assets/javascripts/components/tests/open_original_link_spec.js, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache, src/ggrc/assets/mustache/snapshots/open_original_link.mustache, src/ggrc/assets/stylesheets/_common.scss, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/element/widget_info.py, test/selenium/src/lib/page/modal/update_object.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/selenium_utils.py, test/selenium/src/tests/test_snapshots.py
1. Create program, control, audit
2. Go to audit page and make sure that control's snapshot is displayed in the audit page
3. Return to program page and delete control
4. Return to audit page, refresh and in Control's Info pane select View original Control from 3 bb's menu
_Actual Result_: "Control not found" is shown if delete original control and from control's snapshot "view original Control"
_Expected Result_: If original control has been deleted "view original Control" link should be disabled
=> GGRC-1196 "Control not found" is shown if delete original control and from control's snapshot "view original Control"

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
This is frontend task. Make created_at (or It's alias) field visible on frontend (as part of tree view or/and as part if field dialog).
=> GGRC-1769 "CREATE DATE" field is not shown in tree view and set visible field dialog. (Assessments view)

src/ggrc/models/assessment.py, src/ggrc/models/document.py, src/ggrc/models/object_document.py, test/integration/ggrc/services/test_query/test_basic.py, test/integration/ggrc/test_csvs/assessment_full_no_warnings.csv
filter for original objects - doesn’t work
Evidence, URL
Tech note: Evidence is a Document mapped via ObjectDocuments table, URL is a Document mapped via Relationships table (both m2m mappings).
=> GGRC-1538 Filter by Evidence, URL doesn't work

src/ggrc_basic_permissions/migrations/versions/20170405162826_5a7fd43e43ae_remove_invalid_context_implications.py
The Audit Program context implications were used in the past and were
deprecated. The new Audits do not create those implications any more,
but we still need to delete the ones that were created before the RBAC
changes.
=> GGRC-1786 Remove invalid context implications

src/ggrc_workflows/assets/mustache/cycle_task_groups/tree.mustache
There is no "Undo" in Task Group's 1st tier after clicking control buttons
=> GGRC-333 Return the Undo button in task group

src/ggrc/assets/javascripts/design.js, src/ggrc/assets/javascripts/models/audit_models.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/javascripts/models/simple_models.js, src/ggrc/assets/js_specs/models/assessment_template_spec.js, src/ggrc/assets/mockups/request/assessment_modal.mustache, src/ggrc/assets/mustache/base_objects/contacts.mustache, src/ggrc/assets/mustache/base_objects/mapper-item-description.mustache, src/ggrc/assets/mustache/components/object-list-item/detailed-business-object-list-item.mustache, src/ggrc/assets/mustache/people/owners_modal_connector.mustache, src/ggrc/models/assessment_template.py, test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv, test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/page/modal/base.py, test/selenium/src/lib/service/webui_service.py
_Comment by user:_
Since we are using control "owner" field in a different way now and will be named "admin". It would be more useful to see the principle and secondary assignees in the main popup window instead of having to click "show advanced" button. The principal assignee being the real world control owner, and secondary assignee being the real world control oversight owner.
Change wording "owner" to "admin" in all objects across the application.
=> GGRC-1582 Change wording "owner" to "admin" in all objects across the application

src/ggrc/assets/mustache/controls/tree-item-attr.mustache, src/ggrc/assets/mustache/objectives/tree-item-attr.mustache
Avoid using of "last_assessment_date" component for original Controls and Objectives.
**NOTE**: this PR depends on PR #5409
=> GGRC-1699 Frontend: Sorting and Filtering doesn't work for "Last assessment date" column for Controls/Objectives

src/ggrc/assets/javascripts/mustache_helper.js
_Precondition_:
1. Generate assessment on the audit page based on control
2. Navigate to assessment's Info pane and add assignee (e.g. reader@reciprocitylabs.com)
3. Log as assignee (reader@reciprocitylabs.com (engage007) and leave a comment in assessment 
_Actual Result_: Assessment Info pane: Assessor instead of Assigne is shown in comments
_Expected Result_: Assessment Info pane: Assignee is shown instead of Assessor in comments
=> GGRC-1258 Assessment Info pane: Change Assessor to Assignee in comments

src/ggrc/assets/javascripts/controllers/tree/tree-view.js
1. Open https://grc-test.appspot.com/dashboard#assessment_widget/assessment/11259 link and expand third tier
2. Click on the object that is not marked in blue color (in this case title of the object is "at_v_1")
_Actual Result_: "Uncaught Error: First argument must be an object." error occurs if click on third tier
_Expected Result_: no error is shown
=> GGRC-1580 "Uncaught Error: First argument must be an object." error occurs if click on third tier

src/ggrc_workflows/__init__.py
When a user approves/rejects an object. A different users shows up as approver after click the approve button.
Please check out the attachment. This is the only screen this happens on, and believe this might be part of the state change.
1. Log as "user-1"
2. Create Standard
3. Click Submit for review, add reviewer ("user-2") and select a date
4. Log as "user-2"
5. Click Approve button
Actual Result: When user approves/rejects an objects (standard), a different user (not approver - "user-1") is shown as approver.
Expected Result: When user approves/rejects an objects (standard) reviewer should be shown as approver
=> GGRC-1532 When user approves/rejects an objects (standard), a different users is shown as approver

src/ggrc/models/snapshot.py
This flag should be used to show or hide links to original objects on
snapshot page.
This is a performance fix for this line
https://github.com/google/ggrc-core/blob/release/0.10-Raspberry/src/ggrc/assets/javascripts/components/snapshotter/open-original-link.js#L45
that should not be called on every info pin load.
=> GGRC-1804 Add original_object_deleted flag to snapshots

src/ggrc/assets/javascripts/controllers/tree/tree-view.js
The functionality needs to be implemented on active cycle tab, the sorting on tasks needs to occur on due date (sorting in ascending order)
=> GGRC-1591 Tasks are not ordered by date in Active Cycles tab (subtreeview)

src/ggrc/assets/javascripts/plugins/tests/current-page-utils_spec.js, src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js, src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
**GGRC-1821 Dropdown filter is not applied for "Not Started"/"In progress" states by default on My Assessments page**
Steps t reproduce:
1. Open My Assessments page
2. Look at the dropdown filter
Actual Result: All the assessment states are applied in dropdown filter
Expected Result: Dropdown filter should be applied for "Not Started"/"In progress" states by default on My Assessments page
**GGRC-1822
"Last updated" column is not displayed by default on My assessments page**
1. Open My Assessments page
2. Look at tree view 
Actual Result: "Last updated" column is not displayed by default on My assessments page
Expected Result: "Last updated" column should be displayed by default on My assessments page
**GGRC-1823
"Show objects not directly related to this object" link …
=> GGRC-1821/1822/1823 Dropdown filter is not applied for "Not Started"/"In progress" states by default on My Assessments page

src/ggrc/assets/mustache/controls/contacts.mustache, src/ggrc/assets/mustache/help/filters_helper_content.mustache
Since we are using control "owner" field in a different way now and will be named "admin". It would be more useful to see the principle and secondary assignees in the main popup window instead of having to click "show advanced" button. The principal assignee being the real world control owner, and secondary assignee being the real world control oversight owner.
Change wording "owner" to "admin" in all objects across the application except Workflow
=> GGRC-1582 Change wording "owner" to "admin" in all objects across the application except Workflow

src/ggrc/assets/javascripts/components/rich_text/rich_text.js, src/ggrc/assets/stylesheets/components/ca-object/_ca-object.scss
This PR fixes rich text editor styles issue and also improves processing of urls while typing in rich text editor. (Improvement: no need to write the whole url followed by a whitespace, now it is possible to type, f.e. "google.com" and then move the cursor and prepend it with "http://" and the link will be converted).
1. Create GCA or LCA with Rich text type for e.g. "Assessment'
2. Navigate to assessment's Info pane and enter a link to CA with Rich Text
3. Save the updates: the link should be clickable
Expected Result: If enter a link into Rich Text CA, once saved - it should be clickable
=> GGRC-1279, GGRC-1288, GGRC-1631 Rich text editor fixes

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/components/tests/people_list_spec.js, src/ggrc/assets/mustache/base_templates/people_group.mustache, src/ggrc/assets/mustache/base_templates/people_list.mustache
GCA field with person type for Assessment, created program, audit, created assessment on audit page, assessment is in Ready for review status
1. Navigate to Assessment's Info pane
2. Add a person to GCA field with person type: confirm Ready for review status is not changed to In progress
3. Add a Verifier in People's list: confirm Ready for review status is not changed to In progress
Actual Result: There is no message when assessment moves from Ready for review status to In progress if add a person to CA field/add a Verifier
Expected Result: Should be the message when assessment moves from Ready for review status to In progress if add a person to CA field/add a Verifier
=> GGRC-1244 Show confirmation message for Assessment status change

src/ggrc/assets/javascripts/models/issue.js
1. On the audit page create Issue (fill one or more CA)
2. Click map button on the issue first tier
_Actual Result_: "Uncaught TypeError: Cannot read property 'updateScopeObject' of undefined" error occurs if click map button on Issue first tier
_Expected Result_: no error displayed
=> GGRC-1851 "Uncaught TypeError: Cannot read property 'updateScopeObject' of undefined" error occurs if click map button on Issue first tier

src/ggrc/assets/javascripts/components/quick_form/quick_update.js
_Precondition_:
Activated one-time WF, a task with Dropdown Task type with values
1. Go to Active Cycles tab
2. Navigate to Task's Info pane
3. Choose the value in Response options field and quickly change the value: confirm the selected value changes to the previous one
_Actual Result_: The selected value in Response options field for dropdown is changed to the previous one in Task's Info pane
_Expected Result_: The selected value in Response options field for dropdown should not be changed to the previous one in Task's Info pane
=> GGRC-905 The selected value in Response options field for dropdown is changed to the previous one in Task's Info pane

src/ggrc/models/mixins/__init__.py, test/integration/ggrc/converters/test_export_assessments.py, test/integration/ggrc/services/test_query/test_snapshots.py, test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
In this ticked back-end changes of 'created_at' alias were needed only.
Frontend already fixed.
=> GGRC-1850 Rename "Created on date" filter to "Created Date" on backend

src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js, src/ggrc/assets/javascripts/components/info-pin-buttons/info-pin-buttons.js, src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
Precondition:
created CAs for assessment with all the types, program, control, audit
1. Go to audit page and generate assessment based on control
2. Go to assessment page
3. Look at the assessment Info page: CAs are not displayed
Actual Result: CAs are not displayed on the Assessment page
Expected Result: CAs are should be displayed on the Assessment page
Extra solved issues:
- JS Error on missed Tooltip text on Assessment Info Pane "open/close" status changes
- Improved CA fields updates to avoid users input data losses
- Remove redundant Assessment CA refreshes
=> GGRC-1910 CAs are not displayed on the Assessment page

test/integration/ggrc/__init__.py
Single CSV cell can contain multiple lines, so using the csv module is
safer than manually splitting lines.
This contains just a fix needed for snapshot export tests, and since it's an unrelated issue the commit is put into a separate PR to make reviews easier.
=> QUICK-FIX Fix export_parsed_csv to support multi-line fields

src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js, src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
_Precondition_:
Log as GC (progcreator@reciprocitylabs.com (engage007),
create program, object (e.g. "Data Assets"), audit
1. Go to audit page: confirm that "Data Assets" is displayed in HNB
2. Return to program page and make changes in "Data Assets" (e.g. change title, description)
3. Return to audit page
4. Refresh the page
5. Navigate to "Data Assets" Info pane and click on "Compare with the latest version"
_Actual Result:_ JS error is displayed while GC as program manager clicking on "Compare with the latest version" link	
_Expected Result:_ no error displayed. "Compare with the latest version" dialog appears.
=> GGRC-840 JS error is displayed while GC as program manager clicking on "Compare with the latest version" link

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js, src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/javascripts/models/mixins.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/mustache/assessments/related_issues.mustache, src/ggrc/assets/mustache/components/add-issue-button/add-issue-button.mustache
Precondition:
created program, control, audit, generated assessment based on control
1. Go to Assessment tab on the audit page
2. Navigate to Assessment’s Info panel 
3. Open Related issues tab
4. Look at "Raise an Issue" button
Actual Result: "Raise an Issue" button is disabled in Related Issues tab if Control is mapped to Assessment
Expected Result: "Raise an Issue" button should not be disabled in Related Issues tab if Control is mapped to Assessment
=> GGRC-1927 "Raise an Issue" button is disabled in Related Issues tab if Control is mapped to Assessment

src/ggrc/assets/javascripts/components/people_list.js, src/ggrc/assets/javascripts/components/tests/people_list_spec.js
Steps:
1. Go to assessment info pane.
2. Add some user to assignees (People attribute).
3. Click on trash icon of added user to delete him.
4. Quickly click again on trash icon.
Actual result: JS error is displayed while deleting assignee.
Expected result: no errors displayed, assignee is deleted.
=> GGRC-1673 JS error message when trying to delete an assignee 

src/ggrc/assets/javascripts/application.js, src/ggrc/assets/javascripts/controllers/modals_controller.js, src/ggrc/assets/javascripts/controllers/tests/modals_controller_spec.js, src/ggrc/assets/javascripts/ggrc_base.js, src/ggrc/assets/javascripts/models/cacheable.js, src/ggrc/assets/js_specs/models/cacheable_spec.js
1. Log as "user-1"
2. Create Standard
3. Click Submit for review, add reviewer ("user-2") and select a date
4. Log as "user-2" and Invoke Edit Standard modal window, make any changes (e.g. in Notes field) and do not Save changes (leave modal window open)
5. Log as "user-1"> Invoke Edit Standard make any changes (e.g. in Notes field) and Save
6. Log as "user-2" and click Save and close
Actual result: Closes modal and shows warning about success update, but actually not updated.
Expected result: Shows next warning without closing modal: "There was a conflict while saving. Your changes have not yet been saved. Please refresh the page and try saving again."
=> GGRC-1900 Changes are not saved if update Standard under several users

src/requirements-dev.txt
Importing from a flask extension breaks silently breaks pylint. This fix
makes sure that pylint will not fail when the integration ggrc init file
is edited.
Here is an example of the error that this PR fixes:
https://jenkins.reciprocitylabs.com/job/ggrc_code_style/6991/console
=> GGRC-1940 Fix pylint false warnings and errors

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/related-objects/related-assessment-item.js, src/ggrc/assets/javascripts/components/related-objects/related-assessment-list.js, src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache, src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
Should be only one spinner for one page loading (no loading indicators for URLS, Attachments, Audits, Controls and Objectives)
=> GGRC-1808 Update Spinner Loading Indication for Related Assessments

src/ggrc/assets/stylesheets/_common.scss
**Unify colors for assessment states in tree view/audit summary page/related assessments tab**
1. Create at least 5 assessments on the audit page
2. States for the created assessments should be: Not Started, In Progress, Ready for Review, Completed and Verified, Completed (no verification)
3. Navigate to Info panel one of the assessment and open Related Assessments window
4. Look at ASSESSMENT STATE
**Actual Result**: ASSESSMENT STATE color in Related Assessments tab is differ from the color in pie chart (e.g. "In progress" is colored with orange, should be in blue color) and there is no dot marked as state color
**Expected Result**: Unify colors for assessment states in tree view/audit summary page/related assessments tab
=> GGRC-1533 Fix status label in Related Assessment

src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
have Regulation and map to Regulation any control, program
1. On My work page go to Regulations tab and find created Regulation
2. Type any filter query into Search box (e.g. "title ~ "xxx")
3. Once filter is applied, hover over Regulation first tier and expand sub tree
4. Look at the tree view
Actual Result: Mappings are not shown in tree view if Search box contains filter
Expected Result: Mappings should be shown in tree view if Search box contains filter
Note: the behavior effects not only "Regulation" but also Assessments and other objets
=> GGRC-1945 Mappings are not shown in tree view if Search box contains filter

src/ggrc/models/audit.py, src/ggrc/models/mixins/__init__.py, src/ggrc_risks/models/risk.py, src/ggrc_risks/models/threat.py, src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/models/cycle_task_group_object_task.py, src/ggrc_workflows/models/task_group.py, src/ggrc_workflows/models/task_group_task.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/services/test_query/test_snapshots.py, test/integration/ggrc/test_csvs/all_snapshottable_objects.csv, test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py
Contact fields on models inherited from "WithContact" mixin should be able to filter by "PRIMARY CONTACT" alias. 
Secondary contact fields on models inherited from "WithContact" mixin should be able to filter by "Secondary CONTACT" alias. 
Except:
Task Group (`Assignee` as alias to `contact`; `secondary_contact` isn't aliased)
Task Group Task (`Assignee` as alias to `contact`; `secondary_contact` isn't aliased)
Cycle (`Cycle Assignee` as alias to `contact`; `secondary_contact` isn't aliased)
Cycle Task Group (`Group Assignee` as alias to `contact`; `secondary_contact` isn't aliased)
Cycle Task Group Object Task  (`Task Assignee` as alias to `contact`; `secondary_contact` isn't aliased)
=> GGRC-1941 add aliases on contact and secondary_contact fields

src/ggrc/assets/javascripts/components/access_control_list/access_control_list.js, src/ggrc/assets/mustache/access_groups/modal_content.mustache, src/ggrc/assets/mustache/clauses/modal_content.mustache, src/ggrc/assets/mustache/components/access_control_list/access_control_list.mustache, src/ggrc/assets/mustache/contracts/modal_content.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache, src/ggrc/assets/mustache/data_assets/modal_content.mustache, src/ggrc/assets/mustache/facilities/modal_content.mustache, src/ggrc/assets/mustache/issues/modal_content.mustache, src/ggrc/assets/mustache/markets/modal_content.mustache, src/ggrc/assets/mustache/objectives/modal_content.mustache, src/ggrc/assets/mustache/org_groups/modal_content.mustache, src/ggrc/assets/mustache/policies/modal_content.mustache, src/ggrc/assets/mustache/processes/modal_content.mustache, src/ggrc/assets/mustache/products/modal_content.mustache, src/ggrc/assets/mustache/projects/modal_content.mustache, src/ggrc/assets/mustache/regulations/modal_content.mustache, src/ggrc/assets/mustache/sections/modal_content.mustache, src/ggrc/assets/mustache/standards/modal_content.mustache, src/ggrc/assets/mustache/systems/modal_content.mustache, src/ggrc/assets/mustache/vendors/modal_content.mustache, src/ggrc/assets/stylesheets/components/access-control-list/_access-control-list.scss, src/ggrc_risks/assets/mustache/risks/modal_content.mustache, src/ggrc_risks/assets/mustache/threats/modal_content.mustache
This is a follow-up to the #5468 that has now been merged into the release branch, but a few commits were not included there, as they were not merged to the topic branch in time. This PR contains these missing commits.
It fixes/improves the following things:
- It disables editing custom roles on object info panes if a user does not have the "update" permission on the object (rule of thumb - when the user does not see the "Edit ..." link in the info pane three dots menu in thus cannot open the edit modal).
Mind, however, that a user _can_ edit custom roles in the new object modal (opening the modal implies that the user has the "create" permission).
- Fix removing just-added roles in the new object modal.
To test, start creating a new Roleable model, then in a modal, assign a few roles to …
=> QUICK-FIX Polishing Custom Roles

src/ggrc/assets/javascripts/components/unified-mapper/mapper.js, src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper_spec.js, src/ggrc/assets/mustache/modals/mapper/base.mustache
1. Open Global Search 
2. Speedily select objects from "Object type" dropdown
Actual Result: "Uncaught TypeError: Cannot read property 'serialize' of null" error occurs while speedily selecting object type in Global Search
Expected Result: no error is displayed while speedily selecting object type in Global Search
=> GGRC-1943 JS error occurs while speedily selecting object type in Global Search

src/ggrc/assets/javascripts/bootstrap/modal-form.js, src/ggrc/assets/javascripts/components/modal-connector.js, src/ggrc/assets/javascripts/components/tests/modal-connector_spec.js, src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/models/tests/assessment_model_spec.js
**Window with "Discard Changes" is displayed if there is no changes made**
1. On the audit page invoke New Assessment modal window
2. Click [x] to close the window
**Actual Result**: Window with "Discard Changes" is displayed if there is no changes made
**Expected Result**: Window with "Discard Changes" should display if some changes were made in New Assessment modal window
Note: such behavior should be for other new modal windows
=> GGRC-1391 - Disable discard modal if no changes were made

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/object-popover/object-popover.js, src/ggrc/assets/javascripts/components/show-more/show-more.js, src/ggrc/assets/javascripts/components/show-more/tests/show-more_spec.js, src/ggrc/assets/mustache/components/object-popover/related-assessment-popover.mustache, src/ggrc/assets/mustache/components/show-more/show-more.mustache, src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
Have program, control, audit, at least 2 generated assessment based on the control on the audit page
1. On the assessment's Info pane open Related Assessments window
2. Open More Info pop up and click on Show more links
Actual Result: Show more links don't work in More Info pop up 
Expected Result: Show more links should work in More Info pop up
=> GGRC-1678 Add Show More button for More Info popup

src/ggrc/assets/javascripts/components/access_control_list/access_control_list.js, src/ggrc/assets/mustache/access_groups/modal_content.mustache, src/ggrc/assets/mustache/base_objects/contacts.mustache, src/ggrc/assets/mustache/clauses/modal_content.mustache, src/ggrc/assets/mustache/components/access_control_list/access_control_list.mustache, src/ggrc/assets/mustache/contracts/modal_content.mustache, src/ggrc/assets/mustache/controls/contacts.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache, src/ggrc/assets/mustache/data_assets/modal_content.mustache, src/ggrc/assets/mustache/facilities/modal_content.mustache, src/ggrc/assets/mustache/issues/modal_content.mustache, src/ggrc/assets/mustache/markets/modal_content.mustache, src/ggrc/assets/mustache/objectives/modal_content.mustache, src/ggrc/assets/mustache/org_groups/modal_content.mustache, src/ggrc/assets/mustache/policies/modal_content.mustache, src/ggrc/assets/mustache/processes/modal_content.mustache, src/ggrc/assets/mustache/products/modal_content.mustache, src/ggrc/assets/mustache/projects/modal_content.mustache, src/ggrc/assets/mustache/regulations/modal_content.mustache, src/ggrc/assets/mustache/sections/modal_content.mustache, src/ggrc/assets/mustache/standards/modal_content.mustache, src/ggrc/assets/mustache/systems/modal_content.mustache, src/ggrc/assets/mustache/vendors/modal_content.mustache, src/ggrc/assets/stylesheets/components/access-control-list/_access-control-list.scss, src/ggrc_risks/assets/mustache/risks/modal_content.mustache, src/ggrc_risks/assets/mustache/threats/modal_content.mustache
This PR improves a few UX things (listed below) related to custom roles as suggested by the UX team. Please refer to the Jira [ticket](https://gojira.corp.google.com/browse/GGRC-1926) for screenshots, if necessary.
Change list:
Things left to do (perhaps optional, debatable - please give feedback):
We might want to fix this in a separate ticket, though, if such use cases are improbable and/or the resulting appearance is not considered severe
=> GGRC-1926 Polish custom roles UX

src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
3. Open adit page
Actual Result: "Uncaught TypeError: query.getCounts is not a function" error occurs on the Audit Summary page
Expected Result: no errors are shown while opening Audit summary page
=> GGRC-1987 "Uncaught TypeError: query.getCounts is not a function" error occurs on the Audit Summary page

src/ggrc/assets/javascripts/components/access_control_list/access_control_list.js, src/ggrc/assets/mustache/components/access_control_list/access_control_list.mustache, src/ggrc/assets/stylesheets/components/access-control-list/_access-control-list.scss
This PR is a follow-up to #5608 and it prevents triggering custom role changes while another action (grant/revoke) is in progress.
The [UX Jira ticket](https://gojira.corp.google.com/browse/GGRC-1926) did not specify any of this, but I added this improvement nevertheless, in order to avoid any issues that might arise due to race conditions. Mind that this change applies to info panes only, because in modals, no actions take place in the background and thus locking the Custom Roles UI is not needed.
**Steps to verify:**
1. Open an object instance that has a few Custom Roles defined (if not, define a few in the admin panel)
1. On the info pane, try assigning/revoking a role to/from a person.
While the change is pending (i.e. the server has not responded yet), the trash …
=> QUICK-FIX Disable accessControlList UI when action pending

src/ggrc/assets/javascripts/components/tree/tree-header-selector.js, src/ggrc/assets/javascripts/components/tree/tree-widget-container.js, src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js, src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js, src/ggrc/assets/mustache/components/tree/tree-item-extra-info.mustache, src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache, src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss, src/ggrc/assets/stylesheets/components/tree/_tree-view.scss, src/ggrc/assets/stylesheets/modules/_tree-content.scss, test/selenium/src/lib/page/widget/generic_widget.py
**GGRC-1523**
The following issues should be fixed in accordance with mockups:
1. Make padding smaller between two rows while wrapping title
2. Sort controls should be gray by default. While clicking on sort controls it should be black
3. [Open Tasks] button in popup. Capital letter "Tasks"
4. [Set visibility] button - should by white color of font
5. Make the possibility to add rich text columns into tree view
6. Make default columns on all assessment lists: 
Title, state, assessors, verifiers, last updated
7. If there is no object in tree view make as in mockup. See screenshot screenshot-1.png
**GGRC-475 Improve My Assessments Page**
1. Disable 3 dots menu for the screen
2. No need of second tier - just a simple list
3. Default columns: Title, state, assessors, verifiers, last updated …
=> GGRC-1523/475/1931/1528 UX and styling changes around the tree view in accordance with mockups

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/related-objects/related-issues.js, src/ggrc/assets/javascripts/components/related-objects/related-objects.js, src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache, src/ggrc/assets/mustache/components/related-objects/related-issues.mustache, src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
1. Create program, control, audit
2. Go to audit page and generate assessment based on control
3. Go to program page> Controls tab and Open related Assessment window
4. On the audit page go to Controls tab and invoke Related assessments window clicking on "Assessments" button on Control's Info pane
Actual Result: Related Assessments are not shown in Related Assessments window if open the window via Controls/Objectives Info pane 
Expected Result: Related Assessments should be shown in Related Assessments window if open the window via Controls/Objectives Info pane
=> GGRC-1939 Related Assessments are not shown in Related Assessments window if open the window via Controls/Objectives Info pane 

src/ggrc/assets/javascripts/components/access_control_list/access_control_list.js, src/ggrc/assets/javascripts/components/person/person.js, src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js, src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_snapshots_spec.js
This PR fixes a few quirks with Custom Roles when displaying them on Snapshots.
Changes:
1. Custom Roles cannot be edited on snapshots
1. Custom Roles are displayed correctly on the Snapshot info pane (by fixing the `access_control_list` attribute in object instances generated from Snapshots.
1. Fixed highlighting of differences in custom role assignments on the "compare revisions" pane.
There are no tests for the revision diff pane changes, as they do not exist yet and a holistic end-to-end approach should probably be taken, but that is outside of the scope of this PR.
NOTE: For now, the PR only highlights the role grants that have been added/revoked, but it does not try to vertically align the same people in the old and new lists. In other words, no empty vertical placeholders are …
=> GGRC-1993 Fix displaying Custom Roles on snapshots

src/ggrc/assets/javascripts/components/tree/tree-item-actions.js, src/ggrc/assets/mustache/components/tree/tree-item-actions.mustache, src/ggrc/assets/mustache/components/tree/tree-item.mustache
2. Add task to Task Group
3. Activate WF
4. On the Active Cycles tab click Edit this object in tree view Cycle and Task Group
Actual Result: "Uncaught Error: can.view: No template or empty template:/static/mustache/cycles/modal_content.mustache" error occurs on Active Cycles tab if click Edit this object in tree view Cycle and Task Group
Expected Result: edit action should be forbidden for Cycles and Cycle Task Groups
=> GGRC-2003 Workflow: JS Error on click "Edit" button in tree view Cycle and Task Group

src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc/assets/javascripts/plugins/ggrc_utils.js, src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js, src/ggrc/assets/javascripts/plugins/tests/utils/tree-view-utils_spec.js, src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js, src/ggrc/assets/mustache/components/tree/tree-item.mustache, src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item-attrs.mustache, src/ggrc/assets/stylesheets/components/tree/_tree-view.scss, src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
PLEASE DO NOT MERGE YET
---
This PR adds an option to display Custom Roles in tree view in the same way as regular instance attributes  and Custom Attributes can be selected to be displayed in tree items.
Things to do:
=> GGRC-1838 Display custom roles in tree views

src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
There is no way to add/change authorizations on people tab at the program level. User is added to the program by the admin, however cannot assign any roles.
The ticket is reopened due to "Edit authorizations" link appears on the object's page. It shouldn't be.
=> GGRC-1906 Unable to add role to user in People tab at Program level 

src/ggrc_gdrive_integration/models/__init__.py
1. Go to a Program with an Audit without a folder assigned.
1. Open the Audit info pane.
2. Assign a new folder to it (check that it's displayed correctly).
3. Close the info pane.
4. Open the Audit's info pane again.
Expected result: the folder is still there.
Actual result: A message "Warning: You need permission to access Audit folder. Request access." is displayed instead of the folder, an HTTP500 is returned from the backend.
=> GGRC-2052 Fix gdrive folder assigning

src/ggrc/assets/javascripts/components/csv/export.js, src/ggrc/assets/javascripts/components/csv/test/export_spec.js, src/ggrc/assets/javascripts/components/tree/tree-widget-container.js, src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache, src/ggrc/assets/mustache/import_export/import_export_buttons.mustache
Snapshot tree view menu must have export link that navigates to export page with all proper filters set and selected.
The filters that will need to be set are blocked and defined in GGRC-201.
This ticket should also hmake sure that empty snapshot type is not available when doing the "manual" export.
=> GGRC-1793 Add export link to snapshot tree view 

src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
1. On the audit page create at least 2 assessments
2. Type any query to find assessment (e.g. "CREATED DATE" =, <, > "xxx") and click enter button
Actual Result: Filter is not applied if click [enter] button after typing search query into search box
Expected Result: Filter should be applied if click [enter] button after typing search query into search box
=> GGRC-1888 Filter is not applied if click [enter] button

src/ggrc/models/assessment.py, src/ggrc/models/mixins/assignable.py, src/ggrc_basic_permissions/__init__.py, test/integration/ggrc/api_helper.py, test/integration/ggrc_basic_permissions/test_assessment_document.py
1. Have program, audit, created assessment
2. Go to Audit Info page and assign folder to which verifier (globcreator@gmail.com (engage007) has an access
3. Go to Assessment tab> Info pane> add Verifier (globcreator@gmail.com (engage007) to People list
4. Attach evidence to which Verifier has an access to Assessment from the assigned folder
5. Log as Verifier globcreator@gmail.com (engage007)
6. Go to audit Info page: "No folder for this Audit." is shown
7. Navigate to assessment's Info pane and look at the attached evidence: is not shown
Actual Result: Verifier doesn't see evidence and folder to which verifier has an access
Expected Result: Verifier should see evidence and folder to which verifier has an access
Note: Global Creator as Auditor and Verifier in Audit sees …
=> GGRC-2097 Assessments: Verifier doesn't see evidence and folder to which verifier has an access

src/ggrc/assets/mustache/components/page-header/page-header.mustache
Fix incorrect spelling in TopBar for Org Group Info page
=> GGRC-1491 Fix incorrect title for Org Groups

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/object-popover/object-popover.js, src/ggrc/assets/javascripts/components/object-popover/related-assessment-popover.js, src/ggrc/assets/javascripts/components/related-objects/related-attachments-and-urls.js, src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache, src/ggrc/assets/mustache/assessments/related-assessments.mustache, src/ggrc/assets/mustache/components/object-popover/object-popover.mustache, src/ggrc/assets/mustache/components/object-popover/related-assessment-popover.mustache, src/ggrc/assets/stylesheets/components/object-popover/_object-popover.scss
1. insert Assessment Title column as first one in related assessment modal
2. Attachment and URL - move into one column,
3. replace MoreInfo icon with an appropriate one.
=> GGRC-1478 Related Assessment popup and table redesign

src/ggrc/assets/assets.yaml, src/ggrc/assets/javascripts/components/tree/tree-people-list-field.js, src/ggrc/assets/javascripts/components/tree/tree-people-with-role-list-field.js, src/ggrc/assets/mustache/audits/tree-item-attr.mustache, src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache, src/ggrc/assets/mustache/base_objects/tree.mustache, src/ggrc/assets/mustache/components/tree/tree-item.mustache, src/ggrc/assets/mustache/controls/tree-item-attr.mustache, src/ggrc/assets/mustache/directives/tree-item-attr.mustache, src/ggrc/assets/mustache/objectives/tree-item-attr.mustache, src/ggrc/assets/mustache/programs/tree-item-attr.mustache, src/ggrc/assets/mustache/sections/tree-item-attr.mustache, src/ggrc/assets/stylesheets/components/tree/_tree-view.scss, src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree-item-attr.mustache, src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache, src/ggrc_workflows/assets/mustache/task_group_tasks/tree-item-attr.mustache, src/ggrc_workflows/assets/mustache/task_groups/tree-item-attr.mustache, src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
Controls tree view:
- Shorten urls and contacts columns to 20 characters width.
=> GGRC-1955: Shorten contact and url columns for Controls in tree-view

src/ggrc/models/mixins/statusable.py, src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_import_assessments.py
1. Go to Import page
2. Select any object e.g. "Controls" and download template
3. Open csv file, look at the header of the "State" field: there is no possible states to be added by user
Actual Result: there is no possible choices for "States" for user 
Expected Result: Add possible States for all the objects in csv file (e.g. Controls: "Active", "Draft", "Deprecated"/ Audit: Planned, In progress, Manager Review, Ready for External Review, Completed)
=> GGRC-1163 Add possible States for the objects in csv file

src/ggrc_basic_permissions/__init__.py, test/integration/ggrc_basic_permissions/test_audit_rbac.py
1.39
1. Create an Audit.
2. Create assessment and set Global Reader as assessor. Use reader@reciprocitylabs.com. 
3. Add URL on assessment info pane
4. Login under Global Reader 
5. Display created assessment info pane
6. Delete added URL
7. Refresh the page
Actual Result: URL is not deleted.
=> GGRC-295 URL could not be deleted under Global Reader (Assessor)

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js, src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc/assets/javascripts/mustache_helper.js, src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
2. Go to people tab
3. Open Info pane for current user
4. Click on 3 bb's menu
Actual Result: "Edit authorizations" link is not shown in 3 bb's menu
Expected Result: "Edit authorizations" link is shown in 3 bb's menu
Relates to GGRC-2055, GGRC-2060, GGRC-2054
=> GGRC-1906/2054/2055/2060 "Edit authorizations" link is not shown in 3 bb's menu

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js, src/ggrc/assets/javascripts/components/unified-mapper/mapper.js, src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
_Precondition_:
have program, audit
1. On the audit page invoke new assessment modal window
2. Map object to assessment via modal window
3. Click Map objects once again and look at search results in Unified mapper 
_Actual Result_: already mapped snapshot is marked as non mapped
_Expected Result_: already mapped snapshot is marked as mapped (with filled checkbox)
=> GGRC-1725 Already mapped snapshot is shown in Unified mapper as non mapped to assessment

src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js, src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
1. Create program and add GC (globcreator@gmail.com (engage007) to program with "no role" role
3. Create assessment on the audit page and add GC as assignee to assessment
4. Log as GC (globcreator@gmail.com (engage007) and open Global search
5. Insert audit's title into Filter box and click Search: no result
_Actual Result_: GC as Assignee in Assessment and no role in program doesn't see Audit in Global Search
_Expected Result_: GC as Assignee in Assessment and no role in program should see Audit in Global Search
**Comment from @pod2metra** : "In global search send request that filter objects only with "update" permission, but it should filter them by "read" permission."
=> GGRC-2113 GC as Auditor in Audit and doesn't see Audit in Global Search

src/ggrc/assets/javascripts/models/assessment.js, src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
Make default columns on all assessment lists: 
Title, state, assessors, verifiers, last updated
=> GGRC-1523 Default columns for assessment tree view

src/ggrc/models/mixins/customattributable.py, test/integration/ggrc/models/test_assessment.py
local and global custom attributes
order - the way as it was submitted
it shouldn't be alphabetical order - it should be how admin create on dashboard
local - in order they were cerated
first local then global
—
assessment template order - should be supported
will affect new assessments - and will not affect existing assessments
=> GGRC-1845 Local Custom Attributes after Assessment generation are displayed out of order in Assessment's Info pane

bin/jenkins/functions.sh, bin/jenkins/run_checkstyle, bin/jenkins/run_code_style, bin/jenkins/run_integration, bin/jenkins/run_unittests
This PR makes sure we don't build `selenium` container in jobs for unit tests, integration tests and style checks.
=> QUICK-FIX Build fewer containers

src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache, src/ggrc/assets/mustache/issues/info.mustache
**GGRC-2200**
1. On the audit page create Issue
2. On the Issues tab click on first tier in tree view
Actual Result: "Uncaught TypeError: Cannot read property 'get_mapping_deferred' of null" error is displayed if click on Issues first tier 
Expected Result: no errors is shown. Info pane is not expanded and the app freezes.
*NOTE:* also, "Uncaught TypeError: Cannot read property 'get_mapping_deferred' of null" error is displayed if open "Issue" via LHN. Issues info page is not opened.
**GGRC-2202**
1. Have audit and control snapshot mapped to audit
2. Create assessment template with LCA dropdown type with comment or evidence required
3. Generate assessment based on control and assessment template
4. Navigate to Assessment's Info …
=> GGRC-2200/2202 Fix shown evidences on issues and assessments CA

README.md
We are moving away from publicly accessible Jenkins so having the build
flag in the README.md no longer makes sense.
It currently shows up as a broken image:
=> QUICK-FIX Remove build flag in README.md

src/ggrc/converters/handlers/snapshot_instance_column_handler.py, src/requirements.txt
This PR updates SQLAlchemy to 0.9.8 as it's required in #5614.
2. Create an Audit.
3. Try to import an Assessment for this Audit with "map:control" column present and empty.
Expected result: the Assessment is imported.
Actual result: on real import (not dry run) an SQLAlchemy OperationalError is raised:
OperationalError: (OperationalError) (1052, "Column 'id' in field list is ambiguous") 'SELECT id \nFROM controls, (SELECT snapshots.child_id AS child_id, snapshots.id AS id \nFROM snapshots, (SELECT relationships.id AS id, relationships.source_id AS source_id, relationships.source_type AS source_type, relationships.destination_id AS destination_id, relationships.destination_type AS destination_type, relationships.automapping_id AS automapping_id, …
=> GGRC-2204 Update SQLAlchemy to 0.9.8

src/ggrc/assets/javascripts/components/modal-connector.js, src/ggrc/assets/javascripts/components/tests/modal-connector_spec.js
1. Open Assessment page 
2. Add at least 3 URLs
3. Open Edit Assessment modal window
4. Look at Mapped objects: urls are shown
Actual Result: URLs are shown as mapped objects in Edit Assessment modal window
Expected Result: URLs, evidences, comments should not be shown as mapped objects in Edit Assessment modal window. Only audit and snapshots that are mapped to assessment are shown.
=> GGRC-2051 URLs are shown as mapped objects in Edit Assessment modal window 

src/ggrc/assets/javascripts/modules/widget_descriptor.js, src/ggrc/assets/javascripts/modules/widget_list.js
1. Open link of 'All object' widget.
2. Click to + "Add tab" and try to find and add "Audits" tab to represent under widget.
Actual result:
Audits tab doesn't exist under 'All object' widget
Audits tab have to be exist under 'All object' widget.
=> GGRC-1891 Audits tab doesn't exist under 'All object / My Work' widget
