google/ggrc-core

- src/ggrc/access_control/list.py
- src/ggrc/access_control/roleable.py
- src/ggrc/migrations/versions/20170517162818_59a7bd61e36a_add_index_on_access_control_list.py
- src/ggrc/models/mixins/customattributable.py
make sql query less on reindex procedure (from 1019 to 20 for 1000 instances)  
add index on access_control_list on complex FK fields (object_type and object_id) 
make sql query less on import custom attributable objects (validate on import 1 assessment in my env from 1559 to 4)
> GGRC-2169 500 Server error is shown while importing Assessment csv file

- src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js
- src/ggrc/assets/javascripts/components/add-issue-button/tests/add-issue-button_spec.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
1. On the audit page create assessment
2. Navigate to assessment's Info pane> Related Issues tab
3. Click Raise an Issue button to create Issue
4. After creating issue go to Issues tab: confirm newly created Issue is displayed
5. Repeat steps 3-4. The second and the third Issue is not displayed in Issues tab
**Actual Result:** Newly created Issue is not displayed in Issues tab if issue was created via Related Issues tab on Assessment's Info pane
**Expected Result:** Newly created Issue should be displayed in Issues tab if issue was created via Related Issues tab on Assessment's Info pane
**Note:** refresh is needed
**Fix overview:**
As widgets on inactive tabs don't listen models changes Issue counts update
can be perfomed from add-issue-button component with the …
> GGRC-1935 Fix bug with improperly update of Issue widget

- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
The ticket is reopened due to rich text field is not displayed in tree view after setting the field in "Set visibility" dialog.
> GGRC-1528 Display rich text in tree view

- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/templates/import_export/export.haml
- src/ggrc/templates/import_export/import.haml
1. Go to Import/Export pages
2. Click on [Global Search] button
Actual Result: "Uncaught TypeError: Cannot read property 'type' of undefined" error occurs if click [Global Search] button on the Import page. No objects are displayed in the list, if Global Search is opened from 'Import' page and object type = Cycle Task Group Object Tasks
Expected Result: no error is displayed. Objects are displayed in Search Result
> GGRC-2201 JS error occurs if click [Global Search] button on the Import/Export pages 

- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/service/rest/template_provider.py
- test/selenium/src/tests/test_snapshots.py
This PR add test from Smoke test suite regarding possibility to map Control object to existing Audit:
- check that snapshot of control is mapped to audit
- check that program mapped to this control
> QUICK-FIX Test to check object mapping to existing audit

- src/ggrc/access_control/role.py
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/mixins/attributevalidator.py
- test/integration/ggrc/access_control/test_access_control_role.py
- test/integration/ggrc/models/test_attributevalidator.py
- test/integration/ggrc/models/test_cad.py
This adds validation to access control names so that the name does not clash with object attributes and global custom attributes.
> GGRC-1959 Access control role name validation

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
2. Create Assessment template with LCA dropdown type with comment required and marked as mandatory field
3. Generate assessment based on control and assessment template
4. Open assessment Info pane and select the value with required comment from LCA
5. Fill comment and Save
6. Look at the LCA field: is marked as required info
Actual Result: LCA with comment required is marked as Add required info while comment was already added. Users have no opportunity to complete assessment.
Expected Result: Once required comment or evidence are filled or attached LCA should be marked with green icon and Add required info disappears
Second part: comment should be added and linked together with the Custom Attribute name.
> GGRC-2214 LCA with comment required is marked as Add required info while comment was already added

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-item-details.js
- src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
1. Have program, control, audit
2. On the program page update control (e.g. description)
3. Go to audit page> Assessments tab
4. Select Generate assessments in 3 bb's menu
5. Select Control that was updated on the program page in Umapper and click triangle
6. In 3 bb's menu click "Get the latest version"
Actual Result: "Uncaught TypeError: Cannot read property 'url' of undefined" occurs if click "Get the latest version" link in Unified mapper
Expected Result: no error is shown while clicking "Get the latest version" in Unified mapper
As discussed w/Akhil "Get the latest version" should be removed from Unified Mapper due to it was a regression caused by TreeView redesign.
> GGRC-2161 JS error occurs if click "Get the latest version" link in Unified mapper

- src/ggrc/assets/javascripts/components/tree/tests/tree-item-extra-info_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item-extra-info.js
- src/ggrc/assets/mustache/components/tree/tree-item-extra-info.mustache
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-item-extra-info.scss
The ticket is reopened due to "i" icon is not correspond to requirements: 
"i" icon should be red for mapped to task object if task is overdue
"i" icon is grey for mapped to task object if task is assigned, in progress, finished, declined, verified.
Also , In progress state should be shown in blue color in Info popup.
> GGRC-2001 Workflow: Add State bubbles and State column on Active Cycles tab in tree view

- src/ggrc/assets/mustache/components/tree/tree-header.mustache
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
Tree-header component styles look broken on Controls widget in specific cases (long titles in custom attributes).
1. Add several very long custom attributes for controls
2. Navigate to Controls widget
3. Add long custom attributes via Set visible fields for Control
2. Look at Controls widget
**Actual Result:** Titles in the header are improperly aligned with text in the table columns.
**Expected Result:** Titles in the header should be properly aligned with text in the table columns.
**Fix overview:**
The reason is flexbox item overflow and improper width 100% of the titles' container.
Now the containers' width takes into account its sibling width (tree-header-selector element).
> GGRC-1930 Fix bug with flexbox overflow on Controls widget

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unmap-button/unmap-person-button.js
**Test Case 1**.
2. Go to People tab and Map person to program
3. Navigate to Person Info pane and select Unmap in 3 bb's menu
4. Click Unmap
_Actual Result_: If click unmap button to unmap newly mapped Person, query is not run and Person is not unmapped from program. See screenshot-1.png
_Expected Result_: If click unmap button to unmap mapped Person, Person should be unmapped from program.
_Note_: after mapping a new person page refresh is needed to unmap person
**Test case 2.**
2. Go to People tab and Map person to program
3. Refresh the program page
4. Navigate to Person Info pane and select Unmap in 3 bb's menu
5. Click Unmap button
_Actual Result_: A message that person is unmapped successfully is …
> GGRC-2035 Improve Unmap button behavior on the People tab

- docs/source/guidelines/git/reviewing_pull_requests.rst
When a migration PR is merged, all other migration PRs currently open must update their DB migration chain, and it is a good practice that the authors of those PRs get informed about it.
(the documentation update assumes no DB migration chain branching here...)
> DOCS Add additional notes on merging migration PRs.

- src/ggrc/access_control/role.py
This fixes the issue discovered by @ahetmanski in https://github.com/google/ggrc-core/pull/5638#discussion_r118198024
> GGRC-1959 Fix attribute validator name check

- src/ggrc_risks/migrations/versions/20151112161029_62f26762d0a_add_missing_constraints_for_threats.py
Migrations should not use ggrc models and the ones that do should be
disabled after they are run on prod. This fixes issues with creating new
models whose tables do not yet exist.
This change is safe because the migration has already been run on all
deployed instances, and when doing a migration for a fresh database
there can not be any duplicates so the commented line can be ignored.
> GGRC-2294 Edit old Threats migration

- src/ggrc/automapper/__init__.py
- test/integration/ggrc/models/test_assessment.py
Comment from Prasanna:
1. Last updated date on assessments should change when a comment is added.
Precondition:
Have audit and assessment created some time ago
1. Go to audit page> Assessments tab and add LAST UPDATED field into tree view through Set visible dialog
2. Navigate to Assessment's Info pane and add comment
Actual Result: LAST UPDATED date is not changed if add comment to Assessment 
Expected Result: Last updated date on assessment should change on comments
> GGRC-1421 Last updated date on assessment should change on comments

- src/ggrc/fulltext/attributes.py
- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/snapshotter/indexer.py
- src/ggrc/views/__init__.py
- test/integration/ggrc/services/test_query/test_snapshots.py
The search filter box in the generate assessments popup doesn't work.
Search should work. Tried with the same syntax as outlined in the search query help.
What is the impact if it is not fixed / implemented?
Unable to efficiently create assessments. Annually, we create 1500+ assessments. It means that we'd resort to using a trix to track what assessments need to be generated, manually.
1. Have audit with mapped Control snapshot with filled Principal Assignee
2. Go to Assessment tab > Click Generate Assessments in 3 bb's menu 
3. Once Unified Mapper displayed type filter query into Search box e.g. "Principal Assignee" = Siarhei
4. Look at filter results
Actual Result: Filter is …
> GGRC-2197 Audit Module - FN - filter/search box to generate assessment not working

- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-related-information.js
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-related-information.mustache
- src/ggrc/assets/stylesheets/modules/_assessment.scss
1. Navigate to Assessment Info panel
2. Look at Related Information section
**Actual Result:** Expander icon for Related Information section is _visible_ on Assessment's Info panel.
**Expected Result:** Expander icon for Related Information section is _hidden_ on Assessment's Info panel.
**Fix overview:**
Collapsible functionality was removed from mapped-related-information component and its template.
> GGRC-1130 expander icon for Related Information on Assessment's Info panel

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
_The issue is reproduced with the following steps:_
1. My work page > Regulation widget
2. Hover over Regulation first tier and select map to this object
3. Map any object to Regulations (e.g. Sections, select at least 3 Sections)
4. Hover over Regulation first tier and select Expand tree: tree view becomes grey and then collapses
_Actual Result_: tree view becomes grey and then collapses
_Expected Result_: tree view should not collapse
> GGRC-342 Second tree view collapses in Assessment tab

- src/ggrc/assets/javascripts/plugins/tests/utils/tree-view-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
Acceptance criteria
1. Task Due column should be shown by default on:
My Tasks page; 
Global Search modal window when 'Cycle Task Group Object Tasks' object is selected. 
'Workflow Tasks' tab on Person page; 
'Workflow Tasks' tab on object page. 
2. User should be able to hide 'Task Due Date' column if uncheck 'Task Due Date' checkbox on 'Set visible fields for' pop up.
> GGRC-1967 My Work - My Tasks - add def column Task Due Date 

- src/ggrc/assets/mustache/components/cycle-task-actions/cycle-task-actions.mustache
ACCEPTANCE CRITERIA:
1. Hide START / FINISH / DECLINE / VERIFY / UNDO buttons from task group level on Workflow - Active Cycles page.
2. Task Group statuses should be kept.
3. Task Group statuses should be changed in accordance with the following rules:
If GGRC-1779 is implemented:
* all tasks = ASSIGNED, then task group = ASSIGNED.
* at least one task = IN PROGRESS, then task group = IN PROGRESS.
* all tasks = FINISHED, then task group = FINISHED.
If GGRC-1779 is NOT implemented:
use current logic
> GGRC-1778 RMC - Workflow: Hide Task Group Start/Finish/Verify button

- test/selenium/src/lib/constants/locator.py
This PR improve procedure of get CAs from info pages and info panels in a part of excluding of get CAs scopes from invisible source objects's info tabs.
> QUICK-FIX - Improve procedure of get CAs from info widgets

- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
The bottom border is agreed with the UX
> GGRC-1523 Fix border for empty tree view

- src/ggrc/assets/mustache/assessments/modal_content.mustache
1. On the audit page Invoke new Assessments modal window
2. Fill in required fields and click Save and Add another button
3. Once new Assessments modal window appears type title and click Map objects button
_Actual Result:_ "Uncaught TypeError: CMS.Models[item.type] is not a constructor at Constructor." error occurs if click Map objects button on New Assessments window
_Expected Result:_ no error is displayed. Unified mapper is displayed to map snapshot to Assessment
> GGRC-2296 Fix JS error on create new Assessment modal

- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/models/tests/isOverdue_mixin_spec.js
- src/ggrc_workflows/assets/javascripts/controllers/dashboard_page.js
2. Create task with Due date "today"
3. Activate WF
4. At Active Cycles tab look at the Task's first tier and "i" icon: is shown as overdue
Actual Result: If "Task due date" is today it is shown as overdue in WF
Expected Result: If "Task due date" is today "i" icon should be gray and task should not be overdue
> GGRC-2287 If "Task due date" is today it is shown as overdue in WF

- src/ggrc/models/notification.py
- src/ggrc/notifications/common.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- src/ggrc_workflows/migrations/versions/20170522102213_30ea07e9d452_add_task_overdue_notifications.py
- src/ggrc_workflows/notification/data_handler.py
- src/ggrc_workflows/notification/notification_handler.py
- test/integration/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py
- test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
NOTE: It seems that the ticket [GGRC-1594](https://gojira.corp.google.com/browse/GGRC-1594) also covers tickets [GGRC-1600](https://gojira.corp.google.com/browse/GGRC-1600) and [GGRC-1601](https://gojira.corp.google.com/browse/GGRC-1601).
---
This PR changes the behavior of Workflow Task overdue notifications - the latter are now sent in every day (in the daily digest) until a task is complete (i.e. Verified), and not just on the day when a task becomes overdue.
Two related Jira tickets are `GGRC-1600` and `GGRC-1601`, and they are also handled in the scope of this PR, since `GGRC-1594` essentially covers them, too.
NOTE: The Jira ticket descriptions are kind of incomplete/obsolete, I asked the QA team to check all the points below, and then update the ticket descriptions as necessary. …
> GGRC-1594 Keep sending task overdue notifications until done

- src/ggrc/assets/mustache/components/object-popover/related-assessment-popover.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/components/action-button/_action-button.scss
- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
- src/ggrc/assets/stylesheets/components/simple-modal/_simple-modal.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-item-extra-info.scss
1. Decrease padding between rows in Assessment title and Assessment state.
2. Evidence/URLs should be shown in one row and cut off with 3 dots.
3. Make "Show more" link for ATTACHMENTS / URLS.
4. Underline "Show more"/"Show less" link when hover over it in Info popup in Attributes and Comments.
5. Improve formatting for Custom attributes in Info pop up.
7. "There was" an error is shown while opening "Comments" in Info popup.
8. Field is not marked as required in Info popup.
9. Improve formatting of Evidence/URLs in Related Assessment if open it on Controls/Objectives.
10. Assessments title is not shown as a link in Related Assessment window if open it via on Controls/Objectives tree view.
> GGRC-1529 Related Assessments popup improve

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree/tree-people-list-field.js
- src/ggrc/assets/javascripts/components/tree/tree-people-with-role-list-field.js
- src/ggrc/assets/javascripts/components/view-models/tree-people-base-vm.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
1. Have at least 10 assessment with Creators, Assignees, Verifiers on the audit page
2. Go to Assessments tab
3. Set visible fields Creators, Assignees, Verifiers
4. Refresh the page and look at the People loading: appear with latency
_Actual Result:_ People in tree view appear with latency 
_Expected Result:_ improve performance of people display in tree view
***Note:*** such behavior concerns not only original objects but snapshots as well. E.g. Controls - too slow display in tree view of Principal/Secondary assignees, Primary/Secondary contacts
> GGRC-2181 People in tree view appear with latency

- src/ggrc/access_control/role.py
- test/unit/ggrc/models/test_access_control_roles.py
Validating object_type property was accidentally changing it's value to
the name of the the role.
The regression was caused by https://github.com/google/ggrc-core/pull/5638
> GGRC-2308 Fix access control role validation

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js
- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
Asynchronous rendering of templates slow and really impact on time of showing of page.
After investigating of performance charts was noticed that lots of time during the loading of pages spending on initialization of widgets
Reduce the time loading of pages and implement lazy initialization of widgets.
**Results:**
Performance statistics from Chrome are given on the [GGRC-2292](https://gojira.corp.google.com/browse/GGRC-2292) in screenshots and [performance grid
](https://docs.google.com/spreadsheets/d/1Rp-yAFGpxtUeEt85sevhBgGeGDy-Cb6XqqYamjVm0lc/edit#gid=1005607088)
> GGRC-2292 Lazy initialization of widgets

- src/ggrc/notifications/common.py
- src/ggrc_workflows/notification/data_handler.py
- test/unit/ggrc/notification/test_init.py
This PR improves the performance of generating daily digest emails.
While not a blocking issue in production (email generation happens in background), it does affect developers and QA engineers using the `/_notifications/show_daily_digest` view - waiting for minutes on every page load is a bit too much.
This is a pre-existing issue that got magnified when "task overdue" notifications were introduced, and created for all existing Workflow Tasks. The thing is that the notifications code processes each notification record from the database separately, fetching related data as needed, resulting in a lot of DB queries.
The fix in this PR pre-fetches Tasks and their related objects, producing a temporary object cache that email generation function can use. Performance gains are significant, the …
> GGRC-2323 Improve performance of generating daily digest emails

- src/ggrc/models/object_document.py
- test/integration/ggrc/services/test_query/test_document.py
~depends on https://github.com/google/ggrc-core/pull/5667~ 
1) Check evidences are shown as part of QueryAPI selection array of "relevant filter";
2) Check evidences are only items selected by QueryAPI call "relevant" + document_type == "EVIDENCE";
3)  Add relationship object to "related_destinations" array of business objects to indicate relationship between actual evidence and business object;
4) Remove redundant "document_evidence" and "document_url" arrays from business object;
5) Check availability work of revision comparer functionality for controls in cases when new revision was created by attaching of new evidence.
> GGRC-2256 modify backend contract for Evidence 

- test/selenium/src/tests/test_admin_dashboard_page.py
This PR exclude of random GCAs for Assessments by UI test "test_add_global_ca" until PR #5738 will not be merged.
> QUICK-FIX Exclude of random GCAs for Assessments by UI test

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
Relationship creation requires Update permission on source and destination so we need to add the current user to a list of owners of the document object for them to get Update permissions. 
We did not have this permission issue when we used the object_documents table because the object_documnets table did not have the same permission check as relationships.
> GGRC-2372 Make sure we add owners when creating documents

- src/ggrc/assets/javascripts/models/mappers/tree-base-loader.js
- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/javascripts/models/tests/person_model_spec.js
- src/ggrc/assets/javascripts/models/tests/tree-base-loader_spec.js
2. Go to People’s tab
3. Map people to the program with Program Editor and Program Reader Roles
4. Create an Audit-> Add auditor
5. Go to Audit page-> People’s tab
6. Look at AUTHORIZATIONS column: AUTHORIZATIONS except Auditor role are not displayed
**Actual Result:** AUTHORIZATIONS except Auditor role are not displayed in People's tab at Audit Info page
**Expected Result:** Program-level roles + Auditor are displayed in People's tab at Audit Info page 
**Fix overview:**
Additional check was added for Audit: from now program's user roles should be displayed
in Authorizations column in People's tab at Audit Info page in case of person doesn't
have any audit role.
> GGRC-140 Fix bug with audit roles

- src/ggrc/models/audit.py
- src/ggrc/models/object_document.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/services/test_audits.py
- test/integration/ggrc/test_csvs/program_audit.csv
Attachments to audit object
What is the impact if it is not fixed / implemented? 
Scope and bounds assertion may change every adit and including it at the audit level is the appropriate approach. Current approach of tracking at program level does not enable us to keep track of how the document evolved across multiple audits
1. Create Program
2. Create Audit for the program
3. Navigate to Audit's Info pane
Expected Result: Should be the possibility to add Attachments and URLs to audit object
Requires front-end changes
> GGRC-1975 Include attachment and URLs for audits

- src/ggrc/fulltext/__init__.py
This PR enables reindex of `Document` model on full reindex procedure.
The issue resulted in the fact that old Evidences/URLs were not shown in Evidences/URLs fields since the queries for these components rely on `Document.document_type` field being indexed.
> QUICK-FIX Add Document model to fulltext index

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/controllers/tests/summary_widget_controller_spec.js
Steps to reproduce: 
1. Create at least 5 assessments on the audit page and move it to different states: Not started, In progress, Completed, Ready for review, Completed 
2. Go to Audit summary page 
Actual Result: Assessments states are updated in pie chart after page refresh 
Expected Result: Pie chart should contain actual info as soon as assessment changes a state w/o page refresh
> GGRC-1998 Assessments states are updated in pie chart after page refresh

- src/ggrc/templates/notifications/email_digest_content.html
This PR changes the text in the daily digest email for declined workflow tasks.
NOTE: I created the [task](https://gojira.corp.google.com/browse/GGRC-24) description myself based on the comments under the task. If there are grammatical errors in the wording, please let me know, and I will update accordingly.
---
- Create a workflow with a few task groups and tasks in it
- Start a cycle
- Start, finish, then decline a few of those tasks
- Open the daily digest page (`/_notifications/show_daily_digest`) and look for the "task declined" section of the tasks assignee's email
The title above the list of declined tasks should say _"The following tasks assigned to you, got declined"_
The title above the list of declined tasks says …
> GGRC-24 Change the title of declined tasks list in daily digest

- src/ggrc/assets/javascripts/components/assessment/controls-toolbar/controls-toolbar.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/components/assessment/controls-toolbar/controls-toolbar.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
1. Have mandatory GCAs with all the types for assessment
2. Have audit with control snapshot and created assessment template that contains mandatory LCAs with all types
3. Generate assessment based on snapshot and assessment template
4. Navigate to assessment Info pane and fill GCAs/LCAs
5. Click "Complete" button
6. Look at the values in GCAs/LCAs: are not shown
7. Refresh the page: the values are displayed
Actual Result: CAs are shown w/o values on Assessment Info pane after clicking "Complete" button
Expected Result: CAs should contain values on Assessment Info pane after clicking "Complete" button
> GGRC-2377: Load CAs after Assessment state change

- src/ggrc/access_control/role.py
- src/ggrc/migrations/versions/20170605110159_17e1b92055da_add_field_mandatory_to_acr.py
- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_import_issues.py
New field 'mandatory' was added to access_control_roles table and AccessControlRole model. This field is used for creation of ACL definitions
> GGRC-2370 Add 'mandatory' flag to ACR

- src/ggrc/notifications/data_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- src/ggrc/templates/notifications/style.html
- src/ggrc/utils/__init__.py
- test/integration/ggrc/notifications/test_comment_notifications.py
- test/unit/ggrc/utils/test_util_functions.py
As requested by users, this PR changes the comment notifications a bit. In the daily digest email, comments are now grouped by the object they were posted on. On top of that, the comment creation date has been added, too.
NOTE: As discussed in an offline, the majority of the users live in the `US/Pacific` time zone, thus this is the time zone the UTC datetime from the database are converted to, as we currently have no good way of knowing what time zone a particular user uses on the backend.
---
To test, one should post a few comments under different Assessments a particular user is assigned to. (make sure the "Send Notifications" checkbox is ticked when posting them). When visiting the daily digest email link (`/_notifications/show_daily_digest`), the comments should be grouped by their …
> GGRC-1702 Group comments by parent object and add creation times in daily digest

- src/ggrc/assets/javascripts/components/info-pin-buttons/info-pin-buttons.js
- src/ggrc/assets/javascripts/plugins/tooltip.js
- src/ggrc/assets/mustache/components/info-pin-buttons/info-pin-buttons.mustache
Steps to reproduce: 
1. Navigate to Assessment's Info pane and Minimize/Maximize info pane
2. Close Info pane
 Actual Result: Tooltip is still shown after closing Info pane 
Expected Result: Tooltip should not be shown after closing info pane
> GGRC-1727 Tooltip is still shown after Closing info pane

- src/ggrc/assets/stylesheets/components/attachment-upload-control/attachment-upload-control.scss
Evidence triangle:
- show only on mouse over of attach button.
- do not show it by default.
> GGRC-1498 Audit Module - UI - evidence (bold red font) and red exclamation icon is confusing because it is not a required question

- src/ggrc/notifications/notification_handlers.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
This PR removes some noise from the daily digest email, sending much fewer "update" notifications for a particular object.
The new behavior is as follows:
1. If multiple Assessment state transitions have occurred for the same object, only the last one is included in the daily email, and not each and every state transition anymore.
1. The "assessment updated" notifications is only included in the email if there are no "state change" notifications for a particular object.
---
**The changes can be tested as follows (part 1):**
- Create an assessment (possibly with a Verifier assigned) and change its state a couple of times - move it to "in progress", submit it for a review, decline it, complete it, etc.
- Open the daily digest test page (`/_notifications/show_daily_digest`)
_Expected …
> GGRC-1706 Send only the last status change notification for an object

- src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
 1. Have assessment on the audit page
 2. Navigate to Assessment Info pane and add a verifier
 3. Log as verifier and move assessment to the "Ready for review" state 
4. Look at the "Verify" button: is broken 
Actual Result: Verify button is broken on Assessment Info pane
 Expected Result: Verify button should not be broken on Assessment Info pane
> GGRC-2403 Verify button is broken on Assessment Info pane

- src/ggrc/migrations/versions/20170607150019_3220cbaaaf1a_update_assessor_assignee_in_assessment_.py
The issue can be reproduced on Assessment templates created earlier (approximately 25 days ago).
Default people for such assessments with are "Assessor" instead of "Assignees".
During assessment generation using Assessment template "Assessment generation failed" error massage is displayed.
> GGRC-2261 Create migration for Assessment templates where Default people are "Assessors"

- src/ggrc/assets/javascripts/components/mapped-counter/mapped-counter.js
- src/ggrc/assets/mustache/components/tree/tree-item-extra-info.mustache
2. Add task to task group and activate WF
3. Once redirecting to Active Cycles tab expand tree with Task Group 
4. Hover over "i" icon and look at the screen
**Actual Result:** "There was an error" message is displayed with 500 error in console while hovering over task group first tier on Active Cycles tab. Info popup with mapped tasks to Task Group is not displayed.
**Expected Result:** no error is shown. If hover over "i" icon for task group tier, info popup with mapped tasks should be displayed
> GGRC-2426 Fix info popover for TaskGroup

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/click-filter.js
- src/ggrc/assets/javascripts/components/tests/click-filter_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item-map.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/audits/tree_add_item.mustache
- src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
- src/ggrc/assets/mustache/base_templates/mapped_objects.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-related-information.mustache
- src/ggrc/assets/mustache/components/tree/tree-item-actions.mustache
- src/ggrc/assets/mustache/components/tree/tree-item-map.mustache
- src/ggrc/assets/mustache/controls/object_list.mustache
- src/ggrc/assets/mustache/documents/list.mustache
- src/ggrc/assets/mustache/documents/tree_add_item.mustache
- src/ggrc/assets/mustache/people/tree_add_item.mustache
- src/ggrc/assets/mustache/snapshots/tree_add_item.mustache
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/wf_objects/autocomplete_result.mustache
- src/ggrc_workflows/assets/mustache/wf_objects/tree_footer.mustache
- src/ggrc_workflows/assets/mustache/wf_people/tree_add_item.mustache
1. On the audit page create assessment 
2. Hover over Assessment first tier and click "Map to this object" twice
3. Look at the Unified mapper 
**Actual Result:** Unified mapper duplicated if click "Map to this object" in Assessment first tier twice 
**Expected Result:** Unified mapper should not duplicated if click "Map to this object" in Assessment first tier twice
> GGRC-1944 Unified mapper duplicated if click "Map to this object" in Assessment first tier twice 

- src/ggrc/access_control/role.py
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/mixins/attributevalidator.py
- src/ggrc/models/revision.py
- test/unit/ggrc/models/test_revision.py
For older revisions there isn't `access_control_list` key and value. 
This values required for snapshot indexing and select roles on assessment_generation. 
To fix it required to add `populated_content` property in revision. In that property should be generated `access_control_list` values based on `primary_contact`, `secondary_contact`, `primary_assignee`, `secondary_assignee` fields.
> GGRC-2388 generate ACL content for revisions 

- docs/source/guidelines/git/reviewing_pull_requests.rst
This PR adds a description of the recently introduced `code freeze` label.
> DOCS Add docs for "code freeze" label.

- src/ggrc/converters/custom_operators.py
- src/ggrc/models/relationship_helper.py
Creating a relationships helper class was a wrong design decision
because we never bind any data to the class. This commits changes the
relationship helper from class to module for clarity.
Hint: for cleaner diff view use https://github.com/google/ggrc-core/pull/5779/files?w=1
> QUICK-FIX Remove relationship helper class

- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/snapshotter/test_indexing.py
~depends on https://github.com/google/ggrc-core/pull/5754~ 
Filters for custom roles do not work on snapshots.
to test this try "principal assignees" filter on control snapshots tree view.
Please pay attention to test this with snapshots that are have principal assignees and are older than 1 month)
Preconditions
Audit with control snapshots that have principal assignees. Some snapshots must be new and some must be older than 1 month.
Steps to reproduce
1 try to filter by principal assignees.
Actual: no results are displayed
Expected: filter should display matching results
> GGRC-2220 Filter for custom roles on snapshots

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/controllers/tests/summary_widget_controller_spec.js
Pie chart is not updated automatically if attach evidence or url and assessment changes state.
1. Have assessment that "completed and verified"
2. Attach evidence or add url: assessment moves to "In progress" state 
3. Go to Audit Summary page: assessment's state is not updated in legend and pie chart.
Expected Result: Pie chart should contain actual info as soon as assessment changes a state w/o page refresh
> GGRC-1998 Assessments states are updated in pie chart after page refresh 

- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
**Precondition:** have program, control, audit, created assessment 
1. Go to Assessment tab
2. Expand sub tree for assessment 
3. Hover over first tier and select Map to this object 
4. Map control snapshot to assessment
5. Look at the tree view: mapped control is not shown
6. Collapse subtree and expand subtree once again: mapped control is not shown 
**Actual Result:** Mapped control is not shown in subtree after mapping. Refresh is needed to see mapped control. 
**Expected Result:** Mappings should be displayed in tree view without page refresh after Mapping via Unified mapper
> GGRC-1947 Mappings should be displayed in tree view without page refresh after Mapping via Unified mapper 

- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
In scope of this task, we need to extend the logic of the 'allow_change_state' flag.
Need to add a check that the Cycle (which includes that task) is in active status (Cycle.is_current = true) to avoid extra requests to BE from FE side.
> GGRC-2413 Improve logic of 'allow_change_state' flag

- test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
The tests started failing because the flask session expired. We log
in with freeze time on 2017-05-15 and we keep the session active for 1
month. The tests started failing 2017-06-15. 😂
> QUICK-FIX Fix flaky workflow notification tests

- src/ggrc/assets/javascripts/components/tree/tree-people-list-field.js
1. On the audit page go to Assessment tab and Set visible fields: Creator/Assignee/Verifier
2. Invoke New Assessment modal window
3. Fill all the required fields and add verifier> Save
4. Look at the tree view
_Actual Result_: Creator/Assignee/Verifier are not displayed in tree view after newly created assessment
_Expected Result_: Creator/Assignee/Verifier should be displayed in tree view after newly created assessment
> GGRC-2449 Creator/Assignee/Verifier are displayed in tree view after newly created assessment

- src/ggrc/migrations/versions/20170608130300_56108297b924_add_assessment_started_state_transition.py
- src/ggrc/notifications/data_handlers.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- test/integration/ggrc/notifications/test_assignable_notifications.py
This PR adds a new notification type "Assessment started", which is sent when Assessment is moved from the "not started" to "in progress" state,
**Steps to verfiy:**
1. Create Assessment on the Audit page
2. Edit Assessment: confirm state moves from Not Started to In progress
Notification is not sent if Assessment moves from Not Started to In Progress state
Notification should be send if Assessment moves from Not Started to In Progress state
NOTE: Notifications can be checked by visiting the `/_notifications/show_daily_digest` page.
> GGRC-1411 Notification is not sent if Assessment moves from Not Started to In Progress state

- src/ggrc/assets/javascripts/components/rich_text/rich_text.js
1. Have audit, control's snapshot and Assessment template that contains LCAs with all the types (text, rich text, dropdown, checkbox, date, person)
2. Generate assessment based on the control's snapshot and assessment template
3. Navigate to assessment's info pane > LCA with rich text type
4. Type space and save
5. Fill other LCAs and Save
6. Refresh the page and look at the LCAs values: are not saved
*Actual Result*: If type space into LCA rich text type, error is shown in console and all the values in other LCAs are not saved
*Expected Result:* If type space into LCA rich text type should not be error in console and all the values in other LCAs should be saved
[Related Issue](https://github.com/quilljs/quill/issues/1134)
> GGRC-2485 If type space into LCA rich text type, error is shown in console and all the values in other LCAs are not saved

- src/ggrc/converters/base_row.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/assessment.py
- test/integration/ggrc/converters/test_import_assessments.py
Test case 1.
1. Go to Import page and Download Assessment template
2. Fill the fields required in csv file and Save
3. Import Assessment
Actual Result: "Import failed due to unknown error." error is displayed while importing assessment
Expected Result: Assessment should be imported and displayed on the Audit info page
> GGRC-2493 "Import failed due to unknown error." error is displayed while importing assessment

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_snapshots_spec.js
Audit archiving flag was not properly updated when audit was archived/unarchived causing multiple bugs.
In the offlines we decided to make this issue critical as it needs to go into the 0.10.20 release, that is why I have added the critical label and why I am omitting the code freeze label.
> GGRC-2457 GGRC-2461 Update archived flag in snapshot content when audit is archived

- src/ggrc/assets/javascripts/permission.js
- src/ggrc/assets/javascripts/tests/permission_spec.js
This commit changes how we check permissions on the frontend.
Up until the archiving feature we never had any conditions on
the null context, but because a global editor can edit an audit
only when it's not archived we need to add a check for permissions
on the null context as well (otherwise the editor will not be able
to edit the audit - this was the bug the commit fixed).
⚠️ **Because this PR changes how we check for permissions on the frontend, we will need to test it thoroughly to make sure it doesn't cause any regressions.**
> GGRC-2475 Check conditions for null context on the frontend

- src/ggrc/assets/javascripts/components/modal-connector.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
1. On the audit page invoke New Assessment modal window
2. Click Map object button and map a control
3. Click Control's link to view original control
**Actual Result:** Incorrect link on snapshot for view original control in New Assessment modal window. If click on link it doesn't open Controls page
**Expected Result:** If click on Control's link, original Control's page should be displayed
> GGRC-1387 Link on snapshot in New Assessment modal window doesn't open original control page 

- src/ggrc/assets/javascripts/components/auto-save-form/fields/rich-text-form-field.js
1. Have GCA with rich text for assessment
2. Have audit with assessment in scope of this audit
2. Expand Assessment's Info pane
3. Copy any text and insert into GCA with Rich text type: is not saving and Save changes button is disabled
4. Refresh the page and look at the value in GCA with rich text: is not saved
_Actual Result_: if copy text and insert into Rich text field text is not saved and Save Changes button is disabled
_Expected Result_: Data in rich text field should be saved if copy paste it and insert into rich text field
> GGRC-2293 Assessment: if copy text and insert into Rich text field text is not saved and Save Changes button is disabled

- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper_spec.js
2. Go to Peoples tab and Click Map button
3. Select a person in Search results and click Map selected button twice
4. Look at the screen: JS error is shown
_Actual Result_: "Uncaught TypeError: Cannot read property 'find' of null" error is shown if click Map selected button twice in Unified mapper
_Expected Result_: no error is shown while clicking Map selected button in Unified mapper
**Note**: error occurs if map not only people but objects via Unified mapper using steps mentioned above
> GGRC-2520 "Uncaught TypeError: Cannot read property 'find' of null" error is shown if click Map selected button twice in Unified mapper

- src/ggrc/assets/javascripts/components/tree/sub-tree-item.js
- src/ggrc/assets/javascripts/components/tree/tree-item-extra-info.js
- src/ggrc/assets/mustache/components/tree/sub-tree-item.mustache
- src/ggrc/assets/mustache/components/tree/tree-item-extra-info.mustache
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item-status.mustache
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-item-extra-info.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
UX: https://drive.google.com/corp/drive/folders/0BxUZsNDMuM58dV8tSGphTkFGRW8
AC1. Add 'Overdue' word next to task state.
AC2. Add 'Overdue' word next to task group state.
'Overdue' flag should be added to a task group if task group has at least one overdue task.
AC3. 'Overdue' word should be red.
AC4. Make changes on the following pages:
Workflow page - Active Cycles;
My Work page - Tasks;
Person page - Workflow Tasks;
<snapshottable object> page - Workflow Tasks;
Program page - Workflow Tasks;
Assessment page - Workflow Tasks;
Issue page - Workflow Tasks;
Global search - Cycle Task Group Object Tasks.
> GGRC-2328 RMC - Workflow - Status Color - Add Overdue

- src/ggrc/assets/stylesheets/_z_index.scss
- src/ggrc/assets/stylesheets/components/attachment-upload-control/attachment-upload-control.scss
- src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
1. Have audit with unassigned folder
2. Have assessment on the audit page with LCA dropdown and required evidence
2. On the Assessment Info pane select the value from LCA dropdown with required evidence
3. Hover over [Attach] button: red triangle is cut off
_Actual Result_: Red triangle is cut off in the popup with required evidence
_Expected Result_: Red triangle should not be cut off in the popup with required evidence
> GGRC-2494 Assessment: Red triangle is cut off in the popup with required evidence

- src/ggrc/assets/javascripts/components/object-list/object-list.js
- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache
- src/ggrc/assets/mustache/components/object-list-item/editable-document-object-list-item.mustache
- src/ggrc/assets/mustache/components/object-list/object-list.mustache
- src/ggrc/assets/mustache/components/simple-modal/simple-modal.mustache
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
- src/ggrc_gdrive_integration/assets/js_specs/components/gdrive_picker_launcher_spec.js
- test/selenium/src/lib/constants/locator.py
Description
1. Have audit, control's snapshot, assessment template with mandatory LCA dropdown where comment and evidence are required
4. Generate assessment based on control snapshot and assessment template
3. Navigate to assessment info pane, select the value that required comment, evidence from LCA dropdown, red mark is shown
4. Add comment and attach evidence by clicking "attach" button
5. Look at the info pane: evidence is not shown
Actual Result: Required Evidence is not displayed automatically if attach evidence via required comment and evidence popup and there is no spinner for attaching evidence
Expected Result: Required Evidence should be displayed automatically in Assessment info pane if attach evidence via required comment and evidence popup
NOTE: evidence …
> GGRC-2521 Required Evidence is not displayed automatically on Assessments info pane if attach evidence via required comment and evidence popup

- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/components/read-more/_read-more.scss
- src/ggrc/assets/stylesheets/modules/_rich-text.scss
**Comment by User:**
_What is the problem / issue?_
If my browser window is sized to use up less of my screen, sometimes I cannot click on the "Read More" or "Read Less" links (see attached screen recording). I've also seen this happen to the "Add" button where it won't let me click to add a comment unless I expand the screen.
_What is the expected result / outcome?_
I should be able to click to reduce/expand the text regardless of my browser window size.
_What is the impact if it is not fixed / implemented?_
It's a minor annoyance. I have to expand my window to make it work.
> GGRC-2290 Cannot click "Read More" in Response/Comment section if browser window is too narrow

- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_file.mustache
- src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
Description
1. Have audit and created assessment
2. Navigate to assessment's info pane and click attach button to attach evidence
3. Select evidence and attach selected
4. Click Attach button while the app is processing to save evidence and look at the attached evidence: delete events causes the a corrupt list
Actual Result: Attaching items while the app is processing delete events causes the a corrupt list
Expected Result: Disable [Attach] button on Assessment's Info pane while evidence is attached to Assessment
> GGRC-2634 Disable [Attach] button on Assessment's Info pane while evidence is attached to Assessment

- src/ggrc/notifications/data_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- test/unit/ggrc/notification/test_data_handlers.py
This PR adds information to daily digest notifications on what time a change has occurred.
Even though the task only mentions adding timestamps to Assessment status change notifications, I added it to the Assessment updated notification, too, since adding a timestamp is a recent trend with email notifications (it was e.g. added to "comment created" notifications a few days ago).
Since we generally do not test notification email content with our integration tests, I did not add any here, as a Selenium end-to-end test might be a better choice here (QA add will add it at some point). If I am mistaken, please let me know.
---
To test the change, open an Assessment and modify it, then visit the `/_notifications/show_daily_digest` test page. The notification about the change should have a time …
> GGRC-2421 Add date and time when Assessments state was changed

- src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
1. Have audit with control's snapshot
2. Generate assessment based on control's snapshot
3. Archive Audit
4. Go to Assessment Info page > Control's tab
5. Navigate to control's Info pane and open 3 bb's menu: Unmap is displayed
*Actual result:* "Unmap" button is not hidden when audit is archived 
*Expected Result:* "Unmap" button should be hidden when audit is archived
> GGRC-2461 Add permission check for unmap button in snapshot dropdown

- src/ggrc/assets/mustache/components/tree/tree-item-actions.mustache
1. Log as globcreator@gmail.com (engage007)
2. Create a program
3. Add Objectives tab and invoke new objective modal window
4. Fill in all the fields required and click [Save and Add another button]
5. Click [x] to close New Objective modal window and click [Map Selected] in Unified mapper
6. Hover over gear icon of objective first tier in tree view
**Actual Result:** Several controls are absent in dropdown menu: e.g. "View Info, Open in a new tab, Map to this object, Edit object"
**Expected Result:** All the controls are shown in dropdown menu while hovering gear icon according to New redesign of TreeView. See GGRC-1382
> GGRC-1957 TreeView: several controls are not displayed in dropdown menu if create object under Global Creator

- src/ggrc/notifications/common.py
- src/ggrc/notifications/data_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- test/integration/ggrc/notifications/test_comment_notifications.py
- test/unit/ggrc/notification/test_common.py
NOTE: Based on #5789, please wait until the latter has been merged.
(I built this fix on top of it to preemptively resolve a merge conflict that would otherwise invariably occur if both PRs were submitted separately.
---
This PR order the comments in email notifications in the same way as they are displayed in the UI, i.e. newest on top.
To test, open an Assessment in progress with a few people assigned to it, and add a few comments under that Assessment on its info pane (make sure that "Send Notifications" checkbox is checked). Then open the `/_notifications/show_daily_digest` test page, and verify that comments in the notification emails are indeed listed in the required order.
> GGRC-2422 Sort comment notifications - most recent first

- test/selenium/src/lib/dynamic_fixtures.py
This PR improve of exist webui fixtures' dynamic generation procedure and allow to avoid of creating extra copies of webdriver's instances.  It's affected cases like this: https://github.com/google/ggrc-core/pull/5797
> QUICK-FIX Improve of webui fixtures' dynamic generation procedure

- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/snapshotter/test_indexing.py
If ACR instance is already removed, don't index ACL referring to it by id (it currently breaks reindex on ggrc-qa).
Copy of #5845
> GGRC-2635 Index ACR only if it exists in db

- src/ggrc/settings/default.py
We now merge the version bump into dev immediately after the PR to release is merged, this is according to the new steps in the [deployment doc](https://docs.google.com/document/d/1cB1LqaoD9o7rh6Tum0ZRLE1xY7JX9G5Pi2VCwUKXilA).
> QUICK-FIX Bump version to 0.10.21

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tree_view.py
- test/selenium/src/lib/element/tree_view_item.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/factory.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_snapshots.py
This PR cover smoke test scenario and verify following items:
- there is no possibility to unmap snapshot from audit
- there is no possibility to map some object to snapshot from tree view in scope of audit page
> QUICK-FIX Test mapping rules for snapshots in audit

- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
When one cycle task is deleted, linked context field in UserRole shouldn't be updated to None.
> GGRC-2647 Disable context update for UserRole after cycle task removing

- README.md
The commit adds alternative command invocation for older versions of the `nmcli` command line utility.
This is probably only applicable to Goobuntu-based systems, as they use an older version of `nmcli`.
> DOCS Update Docker gotchas section README.

- src/ggrc/assets/stylesheets/components/collapsible-panel/_collapsible-panel.scss
- src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
- src/ggrc/assets/stylesheets/components/read-more/_read-more.scss
1. Have program, control, objective that is mapped to control, regulation that is mapped to control
2. Add description to control, objective, regulation
3. Create audit and go to Audit page
4. Create assessment and map control's snapshot to assessment
5. Navigate to assessment's Info pane and open Control's popup view
6. Look at the description of objectives and regulations: is not shown 
Actual Result: Description/Notes not shown in Control's popup view on Assessment's Info pane for Objectives and Regulations
Expected Result: Description/Notes should be shown in Control's popup view on Assessment's Info pane for Objectives and Regulations
> GGRC-2646: Description/Notes are not shown in Control's popup view on Assessment's Info pane for Objectives and Regulations

- src/ggrc/assets/stylesheets/_widget.scss
1. On the audit page create assessment and go to Assessment Info page
2. Look at the "Created at/ Modified by" information at the bottom of Assessment Info page
**Actual Result:** Formatting of "Created at/ Modified by" information is broken at the bottom of Assessment Info page
**Expected Result:** Formatting of "Created at/ Modified by" information should not be broken at the bottom of Assessment Info page
> GGRC-1919 Formatting of "Created at/ Modified by" information is broken at the bottom of Assessment Info page

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/controllers/tree/tree_filter_controller.js
1. On the audit page create audit
2. Open Edit Audit modal window and hide optional fields 
3. Put cursor into the "Title" field and click [Tab] button to navigate to the next field which internal audit lead
4. Click out of field: Save and close button is disabled
**Actual Result:** Save and close button is disabled if user navigates to the internal audit lead field by clicking tab button. User has to pick the suggested value from dropdown, otherwise save and close is not enabled.
**Expected Result:** Save and close button should not be disabled if user navigates to the internal audit lead field by clicking tab button.
> GGRC-2433 Audit Module - BUG - cannot create a new audit with custom audit title

- src/ggrc/assets/javascripts/components/page-header/page-header.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
Currently rendering of page_header.mustache template takes a lot of time.
Need to reduce this time and avoid the use of construction like:
can.view(template_path, options).then();
because these renders in async mode and lead to performance issues.
**Steps to measure:**
1. Open Chrome's DevTool
2. Go to Performance tab
3. Refresh page
4. See timings on chart:
_Expected result:_ scripting time should decrease
> GGRC-2442 Reduce time of rendering header

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
Mapping 1000 controls to an audit makes 1000+ query calls to the backend and freezes the chrome window and makes the server extremely slow.
> GGRC-2497 Reduce number of "query" calls when mapping objects to audits

- src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js
- src/ggrc/assets/javascripts/components/add-issue-button/tests/add-issue-button_spec.js
 1. Have audit with created assessment 
2. Go to Assessment tab and expand Info pane
 3. Go to Related Issues tab and click Raise an Issue button 
4. Fill all the fields required in New Issues modal window and click Save and Add another button 
5. Once new Issue modal window appears click [x] and Discard 
6. Look at the Related Issues tab: new issue is not shown and Issues tab is not increased by one 
Actual Result: Issue in Related Issues tab is displayed after refreshing a page if click Save and Add another button 
Expected Result: Issue in Related Issues tab should be displayed after Save and Add another button
> GGRC-2282 Issue in Related Issues tab is displayed after refreshing a page if click Save and Add another button 

- src/ggrc/assets/javascripts/components/access_control_list/access_control_list.js
- src/ggrc/assets/javascripts/components/modal-connector.js
- src/ggrc/assets/javascripts/components/tests/modal-connector_spec.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/directive_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/models/section.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/javascripts/models/system.js
- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/javascripts/models/threat.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
**Overview:**
This is how a post request for a control with a title and 5 people mapped to it looks:
https://gist.github.com/zidarsk8/801799f03a3f597a2fb0272399b6044f
This is a normal control, and Person object has a few custom attributes defined on it.
- People sent to the backend should be stubs not full objects.
- fields with "_" prefix should be omitted: "_transient", "_pending_joins" and any other like that
- obsolete attributes should be removed: contact (it's already sent with ACL)
- "attribute_name" field in custom attribute definitions array when creating assessment templates.
- "changes" field when creating an audit
- all cases of custom attribute definitions that are not in obj["custom_attribute_definitinos"] ... one such example is in custom attribute values property "cad" it …
> GGRC-2518 Remove unneeded data from post requests

- src/ggrc/assets/javascripts/components/tree/tree-item-map.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/mustache/components/tree/tree-item-map.mustache
- src/ggrc/assets/stylesheets/modules/_modal.scss
1. On the audit page create assessment
2. Hover over Assessment first tier and click "Map to this object" twice
3. Look at the Unified mapper
**Actual Result:** Unified mapper duplicated if click "Map to this object" in Assessment first tier twice
**Expected Result:** Unified mapper should not duplicated if click "Map to this object" in Assessment first tier twice
> GGRC-1944 Unified mapper duplicated if click "Map to this object" in Assessment first tier twice

- src/ggrc/assets/javascripts/components/tree/tree-people-list-field.js
- src/ggrc/assets/javascripts/components/tree/tree-people-with-role-list-field.js
1. Go to admin dashboard> Custom roles tab
2. Add custom role field for Control
3. Create a control
4. Go to My work page> Control's tab
5. Set visible field for added Custom role field in tree view
6. On Control's Info pane add person to Custom role field and look at the tree view
**Actual Result:** Custom role value in tree view is updated after page refresh
**Expected Result:** Custom role value in tree view should be updated automatically
**NOTE**: fixed for any role (not only custom role) of snapshotable objects
> GGRC-2030 Custom role value in tree view is updated after page refresh

- src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-item.js
- src/ggrc/assets/javascripts/components/reusable-objects/reusable-objects-list.js
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/mustache/components/assessment/controls-toolbar/controls-toolbar.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
In scope of this PR GGRC-2627 and GGRC-2628 are fixed
**GGRC-2627 Reused evidence appears on Assessment's info pane after page refresh**
1. Have at least 2 related assessments on the audit page
2. Attach evidence to one of the assessment
3. Navigate on Assessment's info pane of the second assessment and be open Related assessments window
4. Select evidence to reuse and click Reuse button> Close Related assessments window
5. Look at the Assessment's info pane: reused evidence is not shown
**Actual Result**: Reused evidence doesn't appear on Assessment's info pane. Refresh is needed.
**Expected Result**: Reused evidence should appears on Assessment's info pane after reusing
**GGRC-2628 Checkbox is active after reusing evidence in Related Assessments Window**
Steps to …
> GGRC-2627 Reused evidence appears on Assessment's info pane after page refresh

- src/ggrc/assets/mustache/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc_gdrive_integration/assets/mustache/workflows/gdrive_folder_picker.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
UX: https://drive.google.com/corp/drive/folders/0BxUZsNDMuM58dV8tSGphTkFGRW8
*A1. Add 'Need Verification' switch on Workflow level.*
*A2. Do not allow user to check/uncheck 'Need Verification' checkbox after Workflow activation.*
*A3. Workflow created for 'Submit for Review' functionality should have 'Need Verification' checkbox checked by default.*
*A4.  Task completion if Verified = false:*
4.1 Cycle(s) / Cycle Task Group(s) / Cycle Task(s) should have the following states:
- ASSIGNED;
- IN PROGRESS;
- FINISHED.
See more: https://docs.google.com/spreadsheets/d/1pgz231cnqsQ05g1bkfEwBfi2aQskMJWwmC8P2D8ePgY/edit#gid=0
4.2 Cycle should be moved to history if all cycle tasks have 'Finished' state.
4.3 ASSIGNED and IN PROGRESS cycle tasks should become Overdue if cycle …
> GGRC-1779 RMC - Workflow: Hide/Disable Verify button for workflow task

- src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
- src/ggrc/assets/mustache/components/tree/tree-filter-input.mustache
- src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache
Hide Advanced search for the following objects:
1. Person; 
2. CycleTaskGroupObjectTask;
3. AssessmentTemplate;
4. Workflow;
5. TaskGroup;
6. Cycle.
> GGRC-2673 Disable Advanced Search for Workflow Related (Cycles, Workflows, Tasks, Tasks Group), Assessment Template,  People  Tree Views

- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
1. Go to My Work page > Control's widget
2. Click "advanced search" icon on the right of search box
3. Look at the "Advanced Search Filter" popup
	font is too large;
	"Add Group Expression" should be in blue color
Actual Result: Formatting in Advanced Search Filter is broken
Expected Result: Improve formatting in Advanced Search Filter according to mockups https://drive.google.com/corp/drive/folders/0B7_NYFVmb896RmQwYXFiNzhQcU0
> GGRC-2682 Improve formatting in Advanced Search Filter

- src/ggrc/models/reflection.py
Any newly added column should be together with all the other primary columns on export page and in the exported CSV.
This ticket was created because the PR for GGRC-2451 was already merged and this slipped past the pull request review (and same for other similar objects)
steps to reproduce
- export a wf template
Expected: all primary coulumns included "need verificiation" need to be grouped together
Actual: "need verfiation" and a few other columns are after Custom attributes.
> GGRC-2679 Fix columns order for workflow import 

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
- src/ggrc_workflows/migrations/versions/20170626123211_55501ef0f634_add_workfloweditor_role.py
- src/ggrc_workflows/roles/WorkflowEditor.py
- src/ggrc_workflows/roles/WorkflowOwner.py
- test/integration/ggrc_workflows/roles/__init__.py
- test/integration/ggrc_workflows/roles/test_global_editor_reader.py
Global Administrators can remove any task (active and non-active), WorkflowOwners can remove only active tasks, users with other roles can't remove tasks at all
> GGRC-1593 Disable cycle task deletion by assigned users

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
2. Type into search box any query (e.g. admin = "xxx")
3. Click "advanced search" icon on the right of search box
4. Select Filter by Mapping and add filter query > Apply filter
Actual Result: "There was an error" is displayed with 500 error in console while applying advanced filter in parallel with query in search box 
Expected Result: no error is displayed while applying advanced search filter and search results according to filter queries are displayed in tree view
> GGRC-2684 "There was an error" is displayed with 500 error in console while applying advanced filter in parallel with query in search box

- docs/source/guidelines/git/reviewing_pull_requests.rst
This PR adds a description of the `missing tests` label to the guideline.
> DOCS Describe "missing tests" label in the guideline

- src/ggrc/notifications/common.py
- src/ggrc/templates/notifications/email_digest_content.html
- src/ggrc_workflows/notification/data_handler.py
- test/unit/ggrc_workflows/notification/test_data_handler.py
This PR changes the email text for the "cycle completed" notifications.
---
To test, create a Workflow with a few tasks, activate it, and then finish and Verify all the tasks. Visit the daily digest test page `/_notifications/show_daily_digest` and check the text for the "workflow cycle completed" notification.
Old notification message:
> All tasks completed in the following cycle(s)
> - Completed cycle of <Workflow title>.
**New** notification message:
> All tasks for the following workflow cycle(s) are now completed and/or verified. The following workflow cycle(s) will end on `today date`: 
> - [cycle slug] of [Workflow title with embedded link to workflow cycle]
Singular or plural form should be used for the word "cycle" depending on the number of items in the list.
Besides the text …
> GGRC-1608 Change the WF Cycle completed text in daily digest

- src/ggrc/models/hooks/audit.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/model_factory.py
- test/integration/ggrc_basic_permissions/models/factories.py
- test/integration/ggrc_basic_permissions/test_issue_mapping.py
- test/integration/ggrc_workflows/models/factories.py
The description of the issue is not correct, the map button should not be hidden, instead we should allow mapping objects to issues even when the audit is archived.
> GGRC-2469 Skip archived permission test when mapping objects to Issues

- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/revision.py
- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/snapshotter/test_indexing.py
- test/integration/ggrc/snapshotter/test_snapshoting.py
- test/integration/ggrc_basic_permissions/test_audit_archiving.py
- test/unit/ggrc/models/test_revision.py
Add processing of old revisions
> GGRC-2667: Send "populated_content" instead of "content" to the frontend for revisions 

- src/ggrc_workflows/converters/handlers.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/data_for_export_testing.csv
Frequency in Workflows needs same "value mapping" solution as boolean fields. Because of one value: "one_time", which is passed to backend as "one_time" and indexed ad "one_time" but users search as "one time"
~depends on: #5839~
> GGRC-2629 Workflows are not filtered by Frequency value "one time"

- src/ggrc/services/query.py
- test/integration/ggrc/services/test_query/test_basic.py
1. Go to My work page > Assessments tab
2. Select any assessment in tree view that contains a snapshot 
3. Click on the first tier to expand info pane
4. Look at the screen
Actual Result: Script error "Cannot read property "values" of null" is displayed while expanding Assessments Info pane on My work page
Expected Result: no error is displayed while expanding assessment's info pane
NOTE: the issue is not reproduced in ggrc-dev and ggrc-qa and reproduced locally
> GGRC-2699 Locally: Script error "Cannot read property "values" of null" is displayed while expanding Assessments Info pane on My work page

- src/ggrc/assets/javascripts/models/assessment.js
After editing a normal field on an assessment (not mapping a new object to it)
the frontend triggers 3 requests
PUT Assessmnet
GET Assessment
POST query for related snapshots
Since GET Assessmnet returns the exact same data as the PUT requests we do not need it and it should be avoided.
Since editing attribute on an assessment can not change mappings to snapshots and those have already been loaded when the info pin was first loaded, we should not be making the query request for data that is already on the frontend.
> GGRC-2534 Remove redundant GET request after Assessment edit

- src/ggrc/converters/snapshot_block.py
- src/ggrc/fulltext/attributes.py
- src/ggrc/models/categorization.py
- src/ggrc/models/category.py
- src/ggrc/models/control.py
- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/integration/ggrc/test_csvs/data_for_export_testing.csv
Original objects:
1. Open Controls widget
2. Change values of "Categories" and "Assertions" fields to a few Controls
3. Order by both fields one-by-one in both directions, notice some (or all) results have wrong ordering.
3. Filter might work for "Categories"and "Assertions" before
Snapshots: (Note: Comparison window should work properly for "Categories" and "Assertions" after this ticket is done GGRC-1486)
1. Map few Controls to Audit
2. Change values of "FRAUD RELATED" and "SIGNIFICANCE" fields to a few Controls
3. Update all mapped to Audit objects.
4. Go to Controls widget under the Audit
5. Order by both fields one-by-one in both directions, notice some (or all) results have wrong ordering.
6. Filter might work for "Categories"and "Assertions" before
NOTES: 
- …
> GGRC-1466 Fix filtering and sorting by "Categories", "Assertions" fields

- src/ggrc/converters/custom_operators.py
- test/integration/ggrc/services/test_query/test_basic.py
Applying several "relevant" filters to assessment lead to queryAPI failing (HTTP500). Backend error looked like following:
`OperationalError: (OperationalError) (1066, "Not unique table/alias: 'ids'") 'SELECT assessments.id AS assessments_id \nFROM assessments, (SELECT DISTINCT anon_1.relationships_id AS relationships_id, anon_1.relationships_source_id AS relationships_source_id \nFROM (SELECT DISTINCT relationships.id AS relationships_id, relationships.source_id AS relationships_source_id \nFROM relationships, (SELECT DISTINCT snapshots.id AS id \nFROM snapshots \nWHERE snapshots.parent_type = %s AND snapshots.child_type = %s AND snapshots.child_id != snapshots.child_id) AS snapshot \nWHERE relationships.destination_id = snapshot.id AND relationships.destination_type = %s AND …
> GGRC-2651 Fix queryAPI failing (HTTP500) if multiple "relevant" filters applied

- src/ggrc/assets/mustache/access_control_roles/subtree.mustache
**ACCEPTANCE CRITERIA**
AC1. Admin as custom role should be by default in Admin Dashboard:
- mandatory;
- non-editable.
This PR contains commit from #5745 (return "mandatory" property from server)
> GGRC-2369 Custom roles should be able to be mandatory and non-editable

- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
Performance research:
https://github.com/google/ggrc-core/pull/5489/commits/86be6ccd2f26f1b61e53b19c656d4c4b8a50f920#r110023039
> zidarsk8 16 hours ago • edited Collaborator
>
> We should really try to avoid making requests that are not needed. Switching between two snapshots now always trigers an extra query which is quite bad.
> Since revisions are immutable it would be best to always check if the current Id exists in cache before sending this query. ~CMS.Models.Revision.cache.indexOf(revisionDi)
> GGRC-1797 Switching between two snapshots now always trigers an extra query

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
1. Have assessment with verifier
2. Log as verifier and complete and verify assessment
3. Click "undo" button near 3 bb's menu
4. Look at the assessment state: it returns back ti verified state and then to Completed again
**Actual Result:** If assessment is completed and verified, "Undo" doesn't return assessment to Ready for review state
**Expected Result:** If assessment is completed and verified, "Undo" should return assessment to Ready for review state
> GGRC-2407 If assessment is completed and verified, "Undo" doesn't return assessment to Ready for review state

- src/ggrc/migrations/versions/20170628101923_55575f96bb3c_add_assessment_type.py
- src/ggrc/models/assessment.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/models/test_assessment.py
**Functional Requirements:**
1. All mapped snapshot(s) of type X should be displayed on top of Assessment info pane/page if 'Assessment type' = X. (Use Cases 1-3)
2. All mapped snapshot(s) of type that is not equal to the type specified in 'Assessment type' for the assessment should be displayed at the bottom of Assessment info pane / tab. (Use Cases 1-3)
3. 'Assessment Type' attribute should be auto-populated based on user selection for 'Object Type' on 'Generate Assessment' mapper, if Assessment is generated without template. (Use Case 4)
**USE CASE 1** for Assessment that is created
1. User goes to GGRC.
2. User goes to Audit.
3. User goes to 'Assessments' tab.
4. User clicks CREATE button to open 'Add Assessment' pop-up.
5. User selects any value in 'Assessment object' dropdown, for …
> GGRC-1526 Add Assessment Type to Assessment

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
Steps:
1) Have assigned folder to audit which does not belongs to user;
2) Go to assessments tab and try attach evidences to assessment;
Actual result: no error, infinite spinner, Attach button is disabled.
Expected result: Show permission error, no spinner, Attach button is active.
> GGRC-1654 Issues with Gdrive attachments in GGRC

- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/document.py
- src/ggrc/models/issue.py
- src/ggrc/models/mixins/customattributable.py
- src/ggrc/services/common.py
- test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py
Performance of 'PUT' request is improved. This PR mostly focuses on improvement of save operation for assessments with custom attributes (especially with comments and evidences)  as reported performance issues are usually reproduced on such type of assessments.
Performance tests:
Assessment with 600 custom attributes (100 of each type):
Before: put 23.39s
After: put 3.75s
> GGRC-2111: Improve Performance of Assessment Model Save operation 

- src/ggrc/assets/javascripts/components/effective-dates/effective-dates.js
- src/ggrc/assets/javascripts/design.js
- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/directive_models.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/javascripts/models/system.js
- src/ggrc/assets/mustache/base_objects/info.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/mustache/policies/info.mustache
- src/ggrc/assets/mustache/processes/info.mustache
- src/ggrc/assets/mustache/products/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/systems/info.mustache
- src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js
- src/ggrc_risks/assets/mustache/risks/info.mustache
*Acceptance Criteria*
1. Change 'Stop Date' label into 'Last Deprecated Date' label.
2. Make changes for the following objects:
- Program
- Standard
- Regulation
- Control
- Product
- System
- Process
- Access Group
- Clause
- Contract
- Data Asset
- Facility
- Issue
- Market
- Org Groups
- Policy
- Project
- Risk
- Threat
- Vendor
- Risk Assessment
3. Make changes on the following places:
- <Object> info page;
- <Object> info pane;
- 'New <object>' modal window;
- 'Edit <object>' modal window.
- 'Set visible fields for <object>' pop-up (on widget and unified mapper)
- name of the column on <object> tab.
- name of the column on Unified Mapper.
- name of the column on Global Search.
- name of the column on 'Generate Assessment' mapper.
- pop-up on Assessment info page.
**NOTE:** for …
> GGRC-2668 Display "end_date" field with "Deprecated Date" label

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/constants/regex.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/test_admin_dashboard_page.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_people_groups_page.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_risk_threats_page.py
- test/selenium/src/tests/test_snapshots.py
- test/selenium/src/tests/test_unified_mapper.py
**This PR contains new design of TAF in a part:**
- extend assertion for "equal" and "contains" operations with human readable diff info:
**equl:**
obj1 = obj2,
[objs1] = [objs2]
**contains:**
obj in [objs]
- add conversion of strings to datetime format;
- fully improve entity in a part unify repr, equal, less code and e.t.c.;
- improve entities factory as a part improving data parsing;
- actualize of REST interaction procedures of TAF with app
- other...
**EQUAL ASSERTIONS:**
**Before:**
**After:**
> QUICK-FIX Design TAF's extended unified equal procedure and human readable entities' comparison

- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
- src/ggrc/assets/js_specs/models/object_state_spec.js
- src/ggrc/models/issue.py
- test/integration/ggrc/converters/test_import_issues.py
- test/integration/ggrc/models/test_issue.py
- test/selenium/src/lib/constants/element.py
- test/unit/ggrc/models/test_states.py
Two more states should be added for Issue:
	Fixed (no verification);
	Fixed and Verified.
**ACCEPTANCE CRITERIA**
A1. User should be able to set 'Fixed' / 'Fixed and Verified' state for Issue.
A2. User should be able to see 'Fixed' / 'Fixed and Verified' states on Issue info pane, tree view, unified mapper, global search
A3. User should be able to filter Issues by 'Fixed' / 'Fixed and Verified' state.
A4. User should be able to see 'Fixed' / 'Fixed and Verified' state in Issue export spreadsheet.
A5. User should be able to import 'Fixed' / 'Fixed and Verified' state for an issue.
> GGRC-1972 Issues object need new states

- src/ggrc/assets/javascripts/controllers/tree/tree-loader.js
Task part from description was already solved. So i fixed bug from this comment:
How to reproduce bug:
1. Go to Administration -> Custom attributes page
2. Add a new custom attribute, name it "Last". It will get added to the bottom. This is correct.
3. Refresh the page. Last is now going to be on the top of the list. This is incorrect.
> GGRC-829 Local Custom Attributes after Assessment generation are displayed out of order in Assessment's Info pane

- docker-compose-clean.yml
- src/ggrc/settings/default.py
> QUICK-FIX Minor development environment improvements

- src/ggrc/notifications/common.py
- src/ggrc/templates/notifications/email_digest_content.html
- src/ggrc_workflows/notification/data_handler.py
- src/ggrc_workflows/notification/notification_handler.py
- test/integration/ggrc_workflows/notifications/test_task_due_notifications.py
This PR changes the email text for the "cycle task due today" notifications.
---
How to test:
- create a Workflow (best to use one-time WF) with a few tasks, with some of them scheduled to be finished _tomorrow_, i.e. current date + 1 day.
- Activate workflow
- Change system time to tomorrow and visit the daily digest preview page `/_notifications/show_daily_digest`.
- Search for the "due on" text
The tasks due on fake "today" (i.e. real current date + 1 day) are indeed listed, there is no ambiguous word _"today"_ - instead, the actual date (in US format) the tasks are due on is displayed.
NOTE:
Singular or plural form should be used for the word "task" depending on the number of items in the list.
NOTE 2:
Notification should not be sent if is relevant for a past …
> GGRC-1603 Show exact date in task due today notification

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
As per user request, this PR makes sure that an object's info pane is automatically maximized when an object is selected in a tree view.
Open question:
Is this applicable for _all_ objects or just "my assessments" as seen in the screenshot attached to the [Jira ticket](https://gojira.corp.google.com/browse/GGRC-2431)?
cc: @akhilp1
> GGRC-2431 Maximize info pane on selecting a tree view item

- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
**GGRC-1486** 
Add categories and assertions in compare modal of control-revisions
**GGRC-2508**
When getting info about Control Snapshot front-end goes for revision data, then does two requests for assertions and categories. Which are obsolete and wrong, since this data is already stored in revision content.
Relates to: https://github.com/google/ggrc-core/pull/5879
> GGRC-2508 GGRC-1486 Front-end: Make the values in "Categories" and "Assertions" fields to be displayed in Comparison window

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/mustache_helpers/validation_error_spec.js
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/page/modal/base.py
- test/selenium/src/lib/service/webui_service.py
Whenever the auditors create a new assessment, it is assigned to the default auditor. It seems like the default template does not let this be blank by default. As we have many audits with a variety of people working, the default value should be able to be blank. The assignee should be required; but it does not need to have a default value.
_Expected result:_ Default assignee should be blank
_Notes:_ The value is still required before submission but it doesnt need to be pre populated, the user should select the assignee.
> GGRC-1666 Default Assessment "Default Assignee" should be able to be blank

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
Single assessment info page makes a query to fetch all ids from related original objects.
That query should not be needed since we must only use snapshots on assessment page.
Additionally if the data is actually needed, we should discuss on why it could not be retrieved from snapshots themselves since they contain all data on their original objects.
> GGRC-2530 Remove query for related original object ids on initialization of  page

- src/ggrc/models/hooks/assessment.py
Prefetch objects when generating assessments
ps: this PR will get a proper ticket number.
Generating 20 assessments:
before:
Total queries: 904
after
Total queries: 885
This PR reduces queries by number of generated assessments
> QUICK-FIX Use audit cache when generating assessments

- src/ggrc/migrations/utils/cleanup.py
- src/ggrc/migrations/versions/20170719165433_1e3f798a4cc6_remove_request_model.py
- src/ggrc_risks/migrations/versions/20170719165534_55f583313670_remove_request_relationships.py
- src/ggrc_workflows/migrations/versions/20170719165612_59aaa4750320_remove_request_relationships.py
This a cherry-picked PR to finally remove the Request remains from the DB.
> GGRC-678 Remove Request model and relationships from the DB

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-control-related-objects.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/stylesheets/components/simple-modal/_simple-modal.scss
1. Have program and Control, Objective, Regulation with long title created on the program page
2. Map Objective, Regulation to Control
3. Create audit 
4. Go to audit page and create Assessment template
5. Generate assessment based on control's snapshot and assessment template
6. Navigate to assessment's info pane and open Control's popup view
7. Look at Control's/Objective's/Regulation's title in the modal popup 
_Actual Result_: Control's/Objective's/Regulation's long title is not cut off in Control's popup view
_Expected Result_: Control's/Objective's/Regulation's long title should be cut off in Control's popup view
_Note_: also, snapshot label is displayed on two rows
> GGRC-2660 Control's/Objective's/Regulation's long title is not cut off in Control's popup view

- src/ggrc/assets/javascripts/components/comment/comment-add-form.js
1. Have audit and assessment 
2. Go to Assessment tab> Expand Info pane and add a comment into comment box > click Add button
3. Invoke Edit assessment modal window and make changes (e.g. change test plan > Save
4. Look under the comment box in Assessment's Info pane: spinner Spinner is turning around endlessly and Add button is absent
_Actual Result:_ Spinner is turning around endlessly and [Add] comment button is not displayed after Saving changes in Edit Assessment modal window
_Expected Result:_ Spinner should not turn around endlessly and [Add] comment button should be displayed after Saving changes in Edit Assessment modal window
> GGRC-2732 Spinner is turning around endlessly and [Add] comment button is not displayed after Saving changes in Edit Assessment modal window

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/element/widget_bar.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/test_asmts_workflow.py
This PR add new automation test-case **"Test of adding comment to Assessment via Info Panel"** as a part of GGRC's smoke test.
```Python
@pytest.mark.smoke_tests
def test_add_comment_to_asmt_via_info_panel(
self, new_program_rest, new_audit_rest, new_assessment_rest, selenium
):
"""Check via UI of possibility to correctly add comment  to Assessment via
Info Panel.
Preconditions:
- Program created via REST API.
- Audit created under Program via REST API.
- Assessment created under Audit via REST API.
Test parameters: None
"""
expected_asmt = new_assessment_rest
expected_asmt_comments = [entities_factory.CommentsFactory().
create().repr_ui()]
(expected_asmt.
update_attrs(comments=expected_asmt_comments, updated_at=None).repr_ui())
assessments_service = …
```
> QUICK-FIX Test of adding comment to Assessment via Info Panel

- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/models/issue.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc_risks/models/risk.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_issues.py
Currently the backend provides the counts:
- created
- modified
- deleted
We should provide an additional count:
- deprecated: count of objects with state moved to Deprecated in this request
The format can still be changed to more general.
> GGRC-2823 BE: Return count of objects to be marked Deprecated in Import response

- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/plugins/tests/advanced-search-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/advanced-search-utils.js
2. Click advanced search icon and filter by "Last deprecated date" "Lesser than" "2016" and add a space
3. Click apply and look at the screen
*Actual Result:* "There was an error" message is displayed if date contains a space in Advanced Search filter
*Expected Result:* no error is displayed while filter by date using advanced search filter
> GGRC-2793 "There was an error" message is displayed if date contains a space in Advanced Search filter

- src/ggrc/assets/javascripts/components/effective-dates/effective-dates.js
- src/ggrc/assets/mustache/components/effective-dates/effective-dates.mustache
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/test/modal_create_new.py
- test/selenium/src/lib/page/modal/base.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/utils/test_utils.py
- test/selenium/src/tests/test_program_page.py
**NOTE:** Relates to https://github.com/google/ggrc-core/pull/5954
Remove 'Stop Date' / 'Last Deprecated Date' from:
- 'New <object>' pop-up;
- 'Edit <object>' pop-up.
> GGRC-2744 Make "Last deprecated date" field non-editable on the frontend

- src/ggrc/models/background_task.py
This commit removes any background task related headers from the request
that generates a background task. This enables us to start a new
background task from an already existing background task.
> Assessment generation does not work.
> 1. generate one or more assessments
> 
> Expected: Generation works and green status is displayed
> Actual: an error is shown
> GGRC-2861 Clean up request headers for background tasks

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/components/csv/import.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/plugins/utils/controllers.js
- src/ggrc/assets/javascripts/plugins/utils/modals.js
- src/ggrc/assets/mustache/base_objects/confirm_delete.mustache
- src/ggrc/assets/mustache/base_objects/confirm_warning.mustache
- src/ggrc/assets/mustache/import_export/import.mustache
- src/ggrc/assets/mustache/modals/confirm_button.mustache
DELETE SYSTEM / PROCESS / PRODUCT (ACTION BUTTON):
*Variant 1*
1.1a User clicks 'Delete' link for Product / System /Process from 3 dots menu on <object> info pane / page:
- warning pop-up should be shown.
1.2a User clicks 'X' on a warning message:
- warning pop-up should be closed;
1.3a User types 'i confirm' and clicks 'Confirm' button:
- warning pop-up should be closed;
- deletion / depreciation should be performed in GGRC.
- related Questionnaires should be deprecated in GGRCQ (already implemented and tested).
*Variant 2*
1.1b User clicks 'Delete' button on 'Edit <object>' pop-up for Product / System /Process:
- warning pop-up should be shown.
1.2b User clicks 'X' on a warning pop-up:
- warning pop-up should be closed;
- 'Edit <object>' pop-up should be still opened.
1.3b User types 'i …
> GGRC-2769 Show warning message on deleting/deprecating of Product/System/Process

- test/integration/ggrc_workflows/test_api_calls.py
Now it's tested under test_create_one_time_workflows with the repeat_only and unit default values of None
> QUICK-FIX Add test for one time Workflow creation

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/mixins.py
- src/ggrc_workflows/notification/notification_handler.py
- test/integration/ggrc_workflows/test_api_calls.py
If is_verification_needed flag is active then cycle should be moved to history if cycle status is Verified.
If is_verification_needed flag is not active then cycle should be moved to history if cycle status is Finished.
> GGRC-2725 Moved to history cycle if status is in inactive_state

- src/ggrc/assets/stylesheets/components/simple-modal/_simple-modal.scss
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
- src/ggrc_workflows/assets/assets.yaml
- src/ggrc_workflows/assets/javascripts/apps/workflow-config.js
- src/ggrc_workflows/assets/javascripts/components/repeat-on-button-wrapper.js
- src/ggrc_workflows/assets/javascripts/components/repeat-on-button.js
- src/ggrc_workflows/assets/javascripts/components/repeat-on-summary.js
- src/ggrc_workflows/assets/javascripts/components/tests/repeat-on-button-wrapper_spec.js
- src/ggrc_workflows/assets/javascripts/components/tests/repeat-on-button_spec.js
- src/ggrc_workflows/assets/javascripts/components/tests/repeat-on-summary_spec.js
- src/ggrc_workflows/assets/javascripts/models/helpers.js
- src/ggrc_workflows/assets/javascripts/models/workflow.js
- src/ggrc_workflows/assets/mustache/base_objects/repeat-on-button.mustache
- src/ggrc_workflows/assets/mustache/base_objects/repeat-on-options.mustache
- src/ggrc_workflows/assets/mustache/base_objects/repeat-on-summary.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
1. Add button and modal dialog for setting up repeat options.
2. Show repeat summary in user-friendly way (ex., 'Repeat Off', 'Repeat every month', 'Repeat every 2 days', etc.):
* on create-edit dialog,
* on WF info page,
* on 'Workflows' tab (tree-view),
* in unified mapper and global search.
> GGRC-2881: Add ability to change repeat options for Workflow

- src/ggrc/migrations/utils/url_util.py
As a follow up to #5889 , this PR removes dead code in DB migration utils.
> QUICK-FIX Remove dead code from DB migration url utils

- src/ggrc_workflows/assets/mustache/cycles/info.mustache
Show repeat summary in user-friendly way in Cycle Info pane:
- Repeat Off,
- Repeat every month,
- Repeat every 2 months, etc.
> GGRC-2886: Add ability to see repeat on options for Cycles

- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
Remove Assignee prepopulation logic from all places for Task creation
> GGRC-2888: Remove logic for populating Assignee with currently logged in user on task creation

- src/ggrc/models/mixins/__init__.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_import_controls.py
- test/integration/ggrc/models/test_control.py
~depends on https://github.com/google/ggrc-core/pull/5998~
> GGRC-2669 GGRC-2754 Make "Last Deprecated Date" non editable on frontend and set it to current date when status is Deprecated

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/tests/cacheable_model_spec.js
1. Create a program and add GC (progcreator@reciprocitylabs.com) as Program reader into program
3. Create an audit and add auditor to audit (progcreator@reciprocitylabs.com)
4. Log as auditor (progcreator@reciprocitylabs.com (engage007) and go to audit page
5. Click Create assessment
**Actual Result:** Creator is not selected by default 
**Expected Result:** Creator should be selected by default
> GGRC-1440 Global Creator Auditor (no Program role) doesn't get autopopulated into Creators in Assessment creation modal

- src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
Create button should be available on TGT tree-view for one-time workflows only.
> GGRC-2903: Hide 'Create' button for recurrent workflows

- src/ggrc/assets/javascripts/components/object-generator/object-generator.js
1. Have audit with control snapshot and assessment template
2. Go to assessments tab > select Generate assessments from 3 bb's menu in tree view
3. Select a control in generate assessments popup and click "Generate assessments" button
4. Click [x] to close generate assessments popup
***Actual Result:*** "Uncaught TypeError: Cannot read property 'find' of null" error is displayed if close "generate assessments" popup while assessment generation
***Expected Result:*** no error is displayed if close "generate assessments" popup while assessment generation
> GGRC-2816 JS error is displayed if close "generate assessments" popup while assessment generation

- src/ggrc/assets/javascripts/models/system.js
- src/ggrc/assets/mustache/processes/modal_content.mustache
This PR fixes the modal content template for Process modal form.
It replaces legacy URL input fields with Reference URLs widget. It also makes sure that if reference URLs are changed when editing a Process, the reference URL list on the info pane gets refreshed after a save.
(hint: open a Process info pane and click select "edit process" from the info pane menu to observe the refresh in action)
> GGRC-2904 Add reference URLs widget to Process modal form

- src/ggrc/views/__init__.py
- test/integration/ggrc/services/test_query/test_snapshots.py
Re-index clears the full text index table and populates it with all
objects. The computed attributes are not part of current objects and so
the recompute job must be run after every reindex, so that the computed
values themselves are also indexed correctly.
> GGRC-2922 Add compute attributes to reindex job

- src/ggrc/data_platform/attributes.py
- src/ggrc/migrations/versions/20170728112941_191c7cc1fed8_add_unique_constraint_on_attributes_.py
> Computed attributes contain duplicate values and might show wrong results (randomly)
> 
> To check this run $.post('/admin/compute_attributes') and check for duplicates in the attributes table.
> GGRC-2923 Fix attribute table indexes and constraints

- src/ggrc/assets/javascripts/components/assessment/attach-button.js
This fixes the page freeze issue when opening the Assessment info pane on my work/my assessment/assessment info pages. We never really needed to fetch the whole audit just to get the folder id, we can simply do a GET to the object_folders API and just fetch the list of folders from there - the response from object_folders is never going to be as complex as the response from /audit and the page freeze will now no longer happen.
⚠️ **Note:** We still fetch the full audit for **NO REASON** when we click the attach button (so the app will still freeze when the user tries to attach evidence). This is bad and needs to be fixed as well, but is unfortunately out of scope of this PR.
> GGRC-2893 Remove audit GET request from findFolder

- src/ggrc/models/directive.py
- src/ggrc/models/system.py
This PR fixes creating revisions for polymorphic types, resulting in missing reference URLs on those objects' snapshots.
This is a blocker for the upcoming release, hence the `critical` label.
---
1. Have a program with mapped Standard
1. Add Reference URL to Standard
1. Create an Audit and go to the Audit page
1. Go to Standards tab and expand Standard's Info pane
1. Look at the Reference URL
**Actual Result:** Reference URLs are not shown on snapshots
**Expected Result:** Reference URLs should be shown on snapshots
Mind: This bug was affecting all polymorphic types, i.e. Directive types (Contract, Policy, Regulation, Standard) and SystemOrProcess (System, Process) types.
> GGRC-2900 Fix Reference URLs revisions for polymorphic types

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/__init__.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/constants/templates.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest/query.py
- test/selenium/src/lib/service/rest/template/count.json
- test/selenium/src/lib/service/rest/template/query.json
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/help_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_objective.py
- test/selenium/src/tests/test_snapshots.py
This PR add 3 parametrized test-cases of exporting snapshoted Control from Audit, Issue's, Assessment's Info Pages.
**Test-case:**
```Python
@pytest.mark.xfail(strict=True)
@pytest.mark.smoke_tests
@pytest.mark.parametrize(
"dynamic_object, dynamic_relationships",
[(None, None),
("new_issue_rest",
"map_new_issue_rest_to_new_control_rest_snapshot"),
pytest.mark.xfail(reason="Issue GGRC-1909", strict=True)(
("new_assessment_rest",
"map_new_assessment_rest_to_new_control_rest_snapshot"))],
ids=["Export of snapshoted Control from Audit's Info Page "
"via mapped Controls' Tree View",
"Export of snapshoted Control from Issue's Info Page "
"via mapped Controls' Tree View",
"Export of snapshoted Control from Assessment's Info Page "
"via mapped Controls' Tree View"],
indirect=["dynamic_object", …
```
> QUICK-FIX Test exporting of snapshoted Control from Audit's, Issue's, Assessment's Info Pages

- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
The pull request contains fixes for 2 related issues.
GGRC-2726:
1. Have program, at least 4 controls, audit with control's snapshots
2. On the program page delete one original control
3. Go to audit page and update audit to the latest version
4. Open assessment in a new tab
5. Go to Audit widget > expand subtree for audit > click " Show objects not directly related to this Assessment"
6. Look at the mapped controls snapshots: three controls snapshots instead of four are displayed in sublevel
Actual Result: Incorrect number of control's snapshots is displayed in audit sublevel on the Assessment Info page
Expected Result: All controls snapshots should be displayed in audit sublevel on the Assessment Info page
GGRC-2727:
1. Have program, at least 4 …
> GGRC-2726 / GGRC-2727 Incorrect number of control's snapshots is displayed on the Assessment Info page

- src/ggrc/views/__init__.py
This PR just reverts the code changes from https://github.com/google/ggrc-core/pull/6034
The reindex job failed after snapshots on ggrc-qa, and we are hoping that this revert will fix the change.
> GGRC-2935 Revert #6034

- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
1. Go to my work page > Controls tab
2. Open advanced search popup
3. Click ESC
4. Click advanced search icon once again: popup is not displayed
*Actual Result:* Advanced search popup is not opened after clicking ESC, refresh is needed
*Expected Result:* Advanced search popup should be displayed after clicking ESC, refresh is needed. TBD
> GGRC-2738 Advanced search popup is not opened after clicking ESC, refresh is needed

- src/ggrc/assets/javascripts/components/quick_form/quick_add.js
- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/models/document.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
1. Log as Global Creator (globcreator@gmail.com (engage007)
2. Create control
3. Add Reference url to control
This issue was caused in https://github.com/google/ggrc-core/pull/5745. One Document instance was updated (https://github.com/google/ggrc-core/pull/5745/files#diff-d85d909fa174cbf4f1978d1f761fe00f) but there were other places where we created a new Document instance where the update was not made. The change in this PR makes sure that and admin role is set by default whenever we create an document instance.
> GGRC-2947 Fix document permission issue

- src/ggrc/settings/app_engine_demo.py
This file has not been used in any of our current deployments, and is
now being repurposed for performance testing with locust.
> QUICK-FIX Modify demo settings file

- src/ggrc/models/revision.py
NOTE: This PR is provisional, we need to discuss whether we really want it in the upcoming release. If not, it should be re-opened against the `develop` branch.
---
This PR fixes a backend issue with handling reference URLs for old revisions. It makes sure that revisions containing empty reference URL data treat that data as non-existent, and do not sent empty reference URL objects to the frontend.
- Find a snapshoted object containing such reference URL data in its revision. One example is a regulation G111 on Audit 1029 (at least on ggrc-qa database)
- Select that object snapshot in tree view to open its info pane
- Look at the "Reference URL" widget
"Invalid date" is displayed and no reference URL link
Nothing is displayed …
> GGRC-2933 Send correct reference URL data for snapshots

- src/ggrc/assets/javascripts/models/cacheable.js
Currently Global Custom Attributes are not saved anywhere (Assessment use updated format) due to BE contract modification
> GGRC-2949 Global Custom Attributes are not saved on any Object (only Assessments)

- src/ggrc/rbac/permissions.py
We should avoid permission queries and building the permission dict if
we can. One such case is read permissions, if a user has global read
access.
The biggest improvement seen with this can be seen after merging https://github.com/google/ggrc-core/pull/6048 for users with global read permissions.
> GGRC-2930 Update read permission checks

- src/ggrc/query/assessments_summary_handler.py
- src/ggrc/query/builder.py
- src/ggrc/query/views.py
- test/unit/ggrc/query/test_assessments_summary_handler.py
Local benchamark on audit with 300 assessments and 2500 snapshots
```
before: 7.170 s average
After:  0.209 s average  (from this 0.162 s was permissions query which will be removed after ACL)
```
This PR also serves as an example for specific query API request improvements.
> GGRC-2930 Improve audit summary query

- src/ggrc/utils/__init__.py
If we have conflicts in notification we should still send out anything
we can.
> QUICK-FIX Silently fail notification conflicts

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/comment/comment-add-form.js
- src/ggrc/assets/javascripts/components/quick_form/quick_add.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
After adding a URL or Evidence to an assessment the last three requests we run are:
POST: /query [related Snapshots and Documents]
GET: /api/assessments?id__in=1
GET: /api/documents?id__in=1
And all the information is already was already present on the frontend before these requests.
We should investigate why they occur and if there is no need for them, they should be removed
**Result:**
- GET request on objects will be removed in scope of GGRC-2798
- In scope of this issue was removed only request on Snapshot, that really not needed. Request on Documents need for make sure that URL/Evidence was added
> GGRC-2616 Remove redundant requests after adding URL and Evidence to Assessment

- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/mixins/customattributable.py
- test/integration/ggrc/models/test_assessment.py
1. Have mandatory GCA for assessment with Person type
2. Have audit with control snapshot
3. On the audit page create assessment template with mandatory person LCA
4. Generate assessment based on control snapshot and assessment template
5. Navigate to assessment info pane and fill LCA and GCA with person type, save values
6. Remove values from LCA and GCA with person type, save
7. Fill LCA and GCA with person type once again and save values
8. Look in Console: 500 error is displayed and value is not saved
Actual Result: 500 error is displayed in console while saving value in mandatory person type LCA/ GCA and value is not saved. Assessment couldn't be completed if mandatory CA is not filled or value is not saved
> GGRC-2351 Fix Assessment: 500 error while saving empty person type LCA/GCA

- src/ggrc/models/revision.py
- test/unit/ggrc/models/test_revision.py
This PR fixes "invalid date" sometimes shown on snapshot info panes under the object's reference URLs. 
It's a follow up to #6052 and fixes an issue that was subsequently discovered for what seem to be some very old object revisions containing reference URLs. While the old fix handled skipping empty reference URL data, this fix handles non-empty data by explicitly providing created/updated at dates for every reference URL data object sent to the client.
---
1. Select a snapshotted object in a tree view to open its info pane. If using a recent ggrc-qa database, an example of such object suffering from the problem is the following: `<host>/audits/4182#control_widget`, a control snapshot titled "Startupsum 128".
2. Look at the object's reference URLs.
**Actual …
> GGRC-2933 (part2) Explicitly provide created/updated date for URLs

- src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/stylesheets/components/action-button/_action-button.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
The following Improvements for Related Assessments popup should be done according to the mockups:
1. Underline "Show All"/"Show less" link when hover over it in Info popup in Attributes and Comments in Related Assessments tab;
2. Cut off Assessment and Audit titles to 2 lines in Releated Assessments view.
> GGRC-2319: Improvements for Related Assessments popup

- src/ggrc/converters/snapshot_block.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_snapshot_block.py
- test/integration/ggrc/test_csvs/control_snapshot_data_multiple.csv
- test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
- test/selenium/src/tests/test_snapshots.py
1. Have program, control with Custom role field (e.g. "Primary Contacts"), audit with control snapshot
2. On the audit page go to Controls tab and Export controls
3. Open csv file and look at the custom role field: "Primary Contacts" is not shown
Actual Result: If export control snapshot custom roles are absent in csv file 
Expected Result: If export control snapshot custom roles should be displayed in csv file 
https://ggrc-qa.appspot.com/audits/4160#control_widget
on hold untill https://github.com/google/ggrc-core/pull/5933 is merged.
> GGRC-2750 Fix absence of AC roles in exported csv file for snapshots

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
1. Have audit with Assessment template
2. Go to the Assessment template tab and invoke Edit Assessment template modal window
3. Add custom attribute and Save 
4. Invoke Edit Assessment template modal window once again and look at the custom attributes: custom attribute is not saved
Cannot add custom attribute in Edit Assessment template
**Expected Result**:
User should have the possibility to edit/add custom attributes into Edit Assessment template modal window
> GGRC-2981 Cannot add custom attribute in Edit Assessment template

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
1. Have program
2. Add audit tab and invoke new audit modal window
3. Look at the "Internal Audit Lead" field: is empty
***Actual Result:*** Internal Audit Lead is not preselected by default in New audit modal window
***Expected Result:*** Internal Audit Lead should be preselected by default in New audit modal window
> GGRC-2675 Internal Audit Lead is not preselected by default in New audit modal window

- src/ggrc/assets/javascripts/components/read-more/read-more.js
- src/ggrc/assets/javascripts/components/read-more/tests/read-more_spec.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/description.mustache
- src/ggrc/assets/mustache/base_objects/notes.mustache
- src/ggrc/assets/mustache/base_objects/test_plan.mustache
- src/ggrc/assets/mustache/base_templates/notes.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/auto-save-form/auto-save-form-field-view.mustache
- src/ggrc/assets/mustache/components/read-more/read-more.mustache
- src/ggrc/assets/mustache/components/related-objects/related-issues.mustache
- src/ggrc/assets/mustache/issues/remediation_plan.mustache
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/read-more/_read-more.scss
- src/ggrc/assets/stylesheets/modules/_inline-edit.scss
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/info.mustache
- src/ggrc_workflows/assets/mustache/cycles/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
**GGRC-2126**
The url/text comes out of the assigned instead of wrapping or shown in a more cleaner way. We are seeing several of this instances occurring, developer and QA team needs to ensure long text/urls are tested through the app
**GGRC-2958**
Have the description for control expanded by default
**GGRC-2763**
_Comment by User:_
_What is the problem / issue?_
When my comment is in the truncated view, things like " " appear and the line breaks are off. When I click "Read more", the formatting is correct.
_What is the expected result / outcome?_ (ie What should happen?)
The text should look the same in the show more/show less views.
_What is the impact if it is not fixed / implemented_? (Quantify the impact, eg, # of hours)
Minimal
> GGRC-2126/GGRC-2958/GGRC-2763 Overflow of text in fields/Assessment UX - read more - expand by def/Assessment: Comment text shows coding

- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
1. Have audit, have Assessment with CA with dropdown type (comment, evidence is required)
2. Expand Assessment's Info pane
3. Update LCA with required comment and save
4. Look at the screen
_Actual Result_: JS error is displayed while updating LCA with dropdown type for Assessment
_Expected Result_: no errors are displayed while updating CAs on assessment info pane, values should be saved
> GGRC-2983 JS error is displayed while updating LCA with dropdown type for Assessment

- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/mixins/customattributable.py
Nested class is replaced by function as lookup for nested class causes error during pickling:
PicklingError: Can't pickle : attribute lookup ggrc.models.custom_attribute_definition.MultiChoiceMandatoryFlags failed
> GGRC-2979 "Failed to fetch data for person 229." error message is displayed while expanding Assessment's Info pane	

- src/ggrc/snapshotter/indexer.py
This reverts commit 995f9b9ca4373b1f7ba127286d7a7b0b88ffa3b5.
The reverted commit updates snapshot indexer to support splitted global and local custom attributes on snapshots, but no snapshottable object should have any local custom attributes, so the changes there should be redundant by default.
> GGRC-3008 Revert "Snapshot indexer based on splited CADs"

- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
Over "tree-view" component, cursor looks like pointer now.
> GGRC-2954 Cursor when hovering over lines doesn’t make it clear the rows are clickable

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/task_group_task.py
- test/integration/ggrc_workflows/test_api_calls.py
- test/unit/ggrc_workflows/models/test_task_group_task.py
* Add validator for TGT model: start_date <= end_date on POST/PUT requests.
* Cover new validator with positive/negative integration tests.
> GGRC-2924 Add validator for TGT model

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
- src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
There is some confusion between the status of the object (marked active / draft/ deprecated) in GGRC to the actual status of the underlying system of product.
_Expected result:_
The tool tip should be added for status attribute on tree view of products or system:
Tool tip text is "The state represents the state of this object information within GGRC. It does not indicate the state of the underlying product or system"
> GGRC-2192 Add a tooltip to clarify object status in GGRC

- .eslintignore
- src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-filter.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-filter_spec.js
- src/ggrc/assets/javascripts/generated/ggrc_filter_query_parser.js
- src/ggrc/assets/js_specs/generated/ggrc_filter_query_parser_spec.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-filter.mustache
- src/parser/parser.pegjs
Original PR: [6096](https://github.com/google/ggrc-core/pull/6096)
GGRC-1535:
Create assessment with a title that contains one of the following special symbols: _%\
Try to filter assessment by title (e.g. "title_")
Actual Result: Filter is not applied if searchable value contains some special symbols (e.g. _%)
Expected Result: Filter should be applied if searchable value contains some special symbols (e.g. _%)
GGRC-2980:
Have a program
Go to the Objectives tab and create Objective with title 'test%objective'
In Search box enter query: title ~ test%
Look at the search results: filter is not applied for the created objective
Open advanced search and filter by query: 'test%'
Look at the search results: created objective is displayed in Search results …
> GGRC-1535/2980 Re-apply Filter is not applied if searchable value contains some special symbols (e.g. _%\) / Incorrect search by special symbols

- src/ggrc/models/revision.py
- test/unit/ggrc/models/test_revision.py
This PR is semantically the same as the later-reverted #6082 with merge conflicts resolved when cherry-picking it on top of the `dev` branch.
Assigned @zidarsk8 as he was also the assignee of the original PR.
---
1. Select a snapshotted object in a tree view to open its info pane. If using a recent ggrc-qa database, an example of such object suffering from the problem is the following: `<host>/audits/4182#control_widget`, a control snapshot titled "Startupsum 128".
2. Look at the object's reference URLs.
"Invalid date" string is displayed under the items in the reference URLs list.
The actual date in US format is displayed under each item in the reference URLs list.
> GGRC-2933 (re-submitted) Explicitly provide created/updated date for URLs

- src/ggrc/models/mixins/with_similarity_score.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/mixins/test_with_similarity_score.py
Depends on #5859
AC1. Only snapshots of assessment type should be included in 'Related Assessments' calculation.
AC2. Related Issues should be also calculated based on Assessment Type.
DETAILED REQUIREMENTS
https://docs.google.com/spreadsheets/d/1ey_DaVnsVvDQuBykipquE9s717GfOYYjtAIuis6XdFU/edit#gid=0
DIAGRAMS
Attached below. 
1. Related Assessments. See Diagrams: 1.1 - 1.3; Diagram 2 will be implemented in GGRC-2447.
2. Related Issues. See Diagrams: 1.1-1.2, 2. Diagram 3 will be implemented in GGRC-2141.
> GGRC-2700 Calculate related Assessments based on Assessment Type

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tree/tree-item-custom-attribute.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/mustache_helpers/get_custom_attr_value_spec.js
- src/ggrc/assets/mustache/components/tree/tree-item-custom-attribute.mustache
- src/ggrc/assets/mustache/components/tree/tree-item.mustache
1. Have GCA with rich text type for Control 
2. Go to My work page > Control's tab 
3. Set Rich text column to be displayed in tree view 
4. Fill GCA field with rich text type on Info pane 
5. Look at the Control's first tier in tree view: data in rich text is not shown
> GGRC-2232 Tree view is not automatically refreshed if fill CAs with rich text type

- src/ggrc/cache/cache.py
- src/ggrc/services/common.py
Cycle task group status isn't deleted from memcache after cycle task updating (put).
Steps of reproduction:
1. Create workflow.
2. Add a task to task group.
3. Activate workflow.
4. Press 'Start' for task.
Result: task group status is 'InProgress'.
5. Press 'Undo" for task.
Result:  task group status is 'InProgress'.
Expected result: task group status is 'Assigned'.
> GGRC-2969 FE: Task Group showing as overdue even when all milestones completed (refresh helps)

- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
This PR fixes occasionally broken (read: misaligned) tree views displaying the reference URLs field.
As a bonus, if having multiple shorter reference URLs, these are rendered one below the other, making them all visible to the user (well, up to two of them at least, before running out of vertical space).
1. Have program with mapped control
1. Add long reference url to control
1. Set "Reference url" field to visible in tree view options
4. Look at the reference url in tree view
Data is not aligned if "Reference url" contains a long link
Data should be aligned if "Reference url" contains a long link
NOTE: Locally I wasn't always able to reproduce this issue despite long URLs. it might be the case that an objects listed in the …
> GGRC-2765 Prevent occasional misaligned tree view columns

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
1. Have audit with control snapshot with long title
2. Generate assessment based on the control snapshot
3. Expand assessment's Info pane and look at the mapped control snapshot: text overlap of "More Information" link
_Actual Result:_ Text overlap of "More Information" link of snapshot on the Assessment's Info pane
_Expected Result:_ Text should not overlap of "More Information" link of snapshot on the Assessment's Info pane
> GGRC-3022 Text overlap of "More Information" link of snapshot on the Assessment's Info pane

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
Original PR: GGRC-2675 https://github.com/google/ggrc-core/pull/6042
> GGRC-2675 Re-apply Internal Audit Lead is not preselected by default in New audit modal window

- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
1. Open info pane of Snapshot, whose original object was changed
2. Open Revision comparer (see request on revision in DevTool)
3. Close revision comparer
4. Open again (request on revision shouldn't be sent)
> GGRC-3035 Remove redundant requests on Revisions if it already cached on FE

- src/ggrc_workflows/assets/javascripts/models/workflow.js
Remove 'Frequency' column from Workflows tree-view cause it is not searchable for now.
> GGRC-3038: Remove 'Frequency' column from Workflows tree view

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/modal/base.py
- test/selenium/src/lib/page/modal/edit_object.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_snapshots.py
Adding test to verify Assessment states flow.
```Python
def test_check_asmt_state_change(
self, new_program_rest, new_audit_rest, dynamic_object_w_factory_params,
action, expected_initial_state, expected_final_state, selenium
):
"""Check Assessment workflow status change to correct state.
Preconditions:
- Program created via REST API.
- Audit created under Program via REST API.
- Assessment created and updated under Audit via REST API.
"""
expected_asmt = dynamic_object_w_factory_params
assessments_service = webui_service.AssessmentsService(selenium)
getattr(assessments_service, action)(expected_asmt)
actual_asmt = assessments_service.get_obj_from_info_page(expected_asmt)
Test.extended_assert_w_excluded_attrs(
expected_asmt.update_attrs(status=expected_final_state.title(), …
```
> QUICK-FIX [Asmts Workflow] Assessments status changes

- src/ggrc/assets/javascripts/components/show-related-assessments-button/show-related-assessments-button.js
- src/ggrc/assets/javascripts/components/tree/tree-item-actions.js
- src/ggrc/assets/mustache/components/tree/tree-item-actions.mustache
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-item-extra-info.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/modules/_tree-content.scss
- The user journey for new workflow module UI is a little bit confusion for regular gGRC users.
User Journey summary:
Newly implemented Workflow UI requires user to hover over to the corresponding "workflow / task group / task" line item for a wheel shape button to appear on screen. User needs to hover over to the wheel shape button in order for a menu to display with function to expand on workflow where user can expand upon to view the existing task group detail. 
User needs to hover over to the line for another wheel to appear and hover over to the wheel to click on the expand function to see the underlying tasks.
A few things that can improve to provide a more intuitive UI for …
> GGRC-2329 RMC - Workflow: Active Cycle UI - Hovering workflow expansion

- src/ggrc_workflows/__init__.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
* Cycle should not be generated if setup date is in future
* Add test for this case
* Fix other tests
> GGRC-3034 Cycle generation logic update

- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
2. Click Add tab button > Controls
3. Click Map button in the tree view
4. Select Control from the Search results and click [Map selected]
5. Click [x] button 
6. Look at the screen: JS error occurs
***Actual Result:*** "Uncaught TypeError: Cannot read property 'find' of null" error is displayed if close Unified Mapper while mapping an object
***Expected Result*:** no errors are shown while clicking [x] button during mapping an object
***NOTE:*** the issue is reproduced on the audit page while mapping an object to the audit taking into account the steps mentioned above (4-5)
> GGRC-3024 JS error is displayed if close Unified Mapper while mapping an object

- src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/mixins.js
Precondition:
created program, audit
1. Go to Audit summary page
2. Click Create assessment button and create assessment
3. Look at tree view: once redirected to Assessments tab created assessment is not shown and the tab is not increased by one
Actual Result: Assessment created from Audit summary page is not shown in Assessments tree view and tab is not increased by one
Expected Result: Assessment created from Audit summary page should be shown in Assessments tree view and tab should be increased by one
Note: refresh is needed
> GGRC-1107 Assessment created from Audit summary page is not shown in Assessments tree view and tab is not increased by one

- src/ggrc/assets/javascripts/components/assessment/custom-attributes.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/inline-item.js
- src/ggrc/assets/javascripts/components/auto-save-form/fields/dropdown-form-field.js
- src/ggrc/assets/javascripts/components/dropdown/dropdown.js
- src/ggrc/assets/javascripts/components/dropdown/tests/dropdown_spec.js
- src/ggrc/assets/javascripts/components/inline/inline.js
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/inline-item.mustache
- src/ggrc/assets/mustache/components/auto-save-form/fields/dropdown-form-field.mustache
- src/ggrc/assets/mustache/components/inline/inline.mustache
- src/ggrc/assets/mustache/components/inline/readonly-inline-content.mustache
1. Have GCA with dropdown type (3 possible values) for assessment
2. Have audit with created assessment
3. Expand Assessment's Info pane and select any value from GCA with dropdown type > Save
4. Look at the screen: selected value is not displayed 
_Actual Result_: If user select a value from GCA with dropdown type and save it, value is not shown on the Assessment's Info pane
_Expected Result_: If user select a value from GCA with dropdown type and save it, value should be shown on the Assessment's Info pane
> GGRC-3039 Incorrect behavior of GCA with dropdown type

- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
Now field is hide if the Test Plan is empty, showing only if non-empty.
> GGRC-2963 Assessment UX - do not show test plan if empty

- src/ggrc_workflows/assets/mustache/workflows/info.mustache
'Archived' state label should be shown on Workflow Info page only for recurrent objects.
> GGRC-2905: Show 'Archived' state label for recurrent workflows only

- src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/annually_cycle_calculator.py
- src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/cycle_calculator.py
- src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/google_holidays.py
- src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/monthly_cycle_calculator.py
- src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/quarterly_cycle_calculator.py
- src/ggrc_workflows/migrations/utils/task_group_task_date_calculator/weekly_cycle_calculator.py
- src/ggrc_workflows/migrations/versions/20170727144648_47d42c67207f_old_tgt_relative_dates_to_absolute.py
We need each TGT to obtain concrete start/end dates (not relative ones) in it's setup, to implement the new algorithm of CycleTask dates generation.
All the details in jira
depends on #6016
> GGRC-2902 Migrate old TGT setup to new one

- src/ggrc_workflows/migrations/versions/20170724180338_545d1c7adca5_update_workflow_patch1_related_tables.py
- src/ggrc_workflows/models/workflow.py
It is needed for 'My Tasks' page. When user presses "Create Task" button he filters by "One Time" workflow frequency. 
**FE sends next request:**
Request URL:https://ggrc-qa.appspot.com/search?q=&types=Workflow&extra_params=Workflow%3Astatus%3DActive%2Cfrequency%3Done_time
Request Method:GET
So to not break it I've decided to add hybrid property.
> GGRC-3021 [BE] Add filtering by 'unit' field (via Search API)

- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
Change text label on Assessment info panel:
* Evidence -> Evidence file
* URL -> Evidence URL
> GGRC-2957: Rename Evidence and URL on Assessment Info panel

- src/ggrc/assets/javascripts/components/datepicker/datepicker.js
- src/ggrc/assets/mustache/components/datepicker/datepicker.mustache
- src/ggrc/assets/stylesheets/modules/_datepicker.scss
- src/ggrc_workflows/assets/javascripts/apps/workflow-config.js
- src/ggrc_workflows/assets/javascripts/components/tests/repeat-on-button_spec.js
- src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
Replace 'daily' option in RepeatOn component with 'weekday' and update appropriate summary message.
Allow weekdays in 'Start Date' and 'Due Date' in Tasks setup for Daily Workflows, restrict datepicker input from keyboard.
> GGRC-3052: update UI for daily Workflows

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/object-list-item/object-list-item-updater.js
- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
- src/ggrc/assets/javascripts/models/join_models.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
1. Have at least 10 Control's snapshots on the audit page
2. Invoke New Assessments modal window
3. Click Map objects button
4. Once 10 Control's snapshots are displayed in Unified mapper Select All and Click Map Selected
5. Look at mapped snapshots: only first 5 Control's snapshots were mapped
_Actual Result_: Only five snapshots are mapped to Assessments if select All in Unified Mapper
_Expected Result_: If user clicks "Select All" in Unified mapper to map Control's snapshots to Assessment, all Control's snapshots that exist in audit scope should be mapped to Assessment
> GGRC-2269 Assessments: only five snapshots are mapped to Assessments if select All in Unified Mapper	

- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc_workflows/test_api_calls.py
1. Go to WF info tab with repeat on (for example, repeat every 1 month).
2. Click 3 dots button and select 'Clone Workflow'.
3. Click 'Proceed' button on 'Clone Workflow' pop-up.
Actual result: New workflow has repeat off.
Expected result: New workflow should have repeat 'every 1 month'.
> GGRC-3067 Cloned WF should have the same repeat as the original WF

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/controllers/tests/modals_controller_spec.js
1. Go to the Export page
2. Expand LHN
3. Click 'Create' Workflow button
4. Look at the screen
Actual Result: "Uncaught TypeError: Cannot read property '328' of undefined" error occurred while clicking 'Create' Workflow button in LHN 
Expected Result: no error is shown
TECH NOTE: can be reproduced with low internet connection on opening create modal dialog.
> GGRC-2938: Fix issue with create WF on Export page

- src/ggrc/assets/javascripts/components/assessment/custom-attributes.js
- src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
1. Have archived audit with assessment 
2. Go to assessment tab and expand Info pane
3. Hover over GCA field: edit icon is displayed
4. Click edit icon and update GCA field: 403 error is displayed in console, value is displayed in GCA field
_Actual result:_
If audit is archived a control for edit GCA is not disabled. If update GCA while audit is archived, the app allows to save changes, 403 error is displayed in console. After page refresh value in GCA field is not displayed
_Expected result:_
If audit is archived a control for edit GCA should not displayed
> GGRC-3031 If audit is archived a control for edit GCA is not disabled

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-attribute.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-group.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc/assets/mustache/components/advanced-search/advanced-search-mapping-container.mustache
- src/ggrc/assets/mustache/components/advanced-search/advanced-search-mapping-criteria.mustache
- src/ggrc/assets/mustache/components/advanced-search/advanced-search-mapping-group.mustache
- src/ggrc/assets/mustache/components/object-generator/object-generator.mustache
- src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
- src/ggrc/assets/mustache/components/object-search/object-search.mustache
- src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache
1. Go to My work page > Control tab
2. Open Control Advanced Filter
3. Click 'Add attribute' button
4. Select any search criteria from the dropdown list (e.g. Title)
5. Click 'Add Mapping Filter' button and select an object to which Control is mapped to (e.g. Program)
6. Look at the search criteria from the dropdown list: is not correspond to optional fields for program
*Actual Result:* Optional fields of search criteria do not correspond to selected object in Advanced Search filter
*Expected Result:* Optional fields of search criteria should correspond to selected object in Advanced Search filter
> GGRC-3043 Optional fields of search criteria do not correspond to selected object in Advanced Search filter

- src/ggrc/assets/javascripts/components/tree/tree-item-actions.js
- src/ggrc/assets/mustache/components/tree/tree-item-actions.mustache
Remove 'Map to this object' option from drop down menu on Workflows tree view.
> GGRC-3028: Remove 'Map to this Object' menu item on Workflows tree view

- src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
Only Admin can delete historic and active cycle tasks
WF manager can only delete active cycle tasks
> GGRC-3060 FE: hide 'delete' button in Edit Task modal

- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/directive_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/section.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/javascripts/models/system.js
- src/ggrc/assets/js_specs/models/cacheable_spec.js
- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/javascripts/models/threat.js
1. Have audit with Assessment
2. Expand Assessment's Info pane
3. Invoke Edit Assessment modal window
4. Add Reference url > Click Save
5. Look at the Reference url on Assessment's Info pane
Actual Result: Reference url is not displayed on Info panel if add url via Edit Assessment modal window. REFRESH is needed
Expected Result: Reference url should be displayed on Assessment's Info pane after adding via Edit Assessment modal window
NOTE: Assessment entity is taken as en example. There is necessary to check for other objects
> GGRC-2967 Reference url is not displayed on Info panel if add url via Edit modal window. Refresh is needed

- extras/deploy_settings_local.sh
This fixes issues with `launch_ggrc` after running `deploy_appengine
extras/deploy_settings_local.sh`. Gdrive integration still seems not to
work with `launch_gae_ggrc`, but that's a separate issue.
> QUICK-FIX Add ggrc_gdrive_integration to local deploy settings

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/audits/extended_info.mustache
- src/ggrc/models/assessment_template.py
- test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv
- test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
"Audit Lead" field name could be misleading on the Audit object.
_Expected result:_
Use 'Audit Captain' label on Assessment template form and Audit extended info panel.
> GGRC-2325 Audit Object - Internal Audit Lead field name is confusing

- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
1. Have a program with mapped control 
2. Go to Controls tab and add Reference URL to control 
3. Click 'Global Search' button and find control 
4. Set 'Reference URL' field and look at the search results: there is no wrapping between link and [Assessments] button 
Actual Result: There is no wrapping for reference url in Global Search/Unified Mapper 
Expected Result: Reference url should be cut off with three dots and should be wrapping for reference url in Global Search/Unified Mapper
> GGRC-2899 There is no wrapping for reference url in Global Search/Unified Mapper

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/cycle.py
- test/integration/ggrc/access_control/test_access_control_role.py
- test/integration/ggrc_workflows/test_status_propagation.py
1. Create one time workflow
2. Add at least 3 tasks to Task group in Setup tab, one task should be overdue
4. At the Active Cycles tab verify tasks
5. Click 'undo' button for all tasks: make sure that tasks are moved to Finished state
6. Move one task to In progress
7. Verify one task once again (e.g. Overdue task)
8. Open History tab and look at the tree view: Unverified workflow moves to History tab
Actual Result: Unverified workflow moves to History tab
Expected Result: Unverified workflow should not be moved to the History tab
> GGRC-2908 Unverified workflow moves to History tab

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/auto-save-form/auto-save-form.js
- src/ggrc/assets/mustache/components/auto-save-form/auto-save-form.mustache
- src/ggrc/assets/mustache/components/object-popover/related-assessment-popover.mustache
- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
Scope:
- move the checkbox control right before the text - see the mock
UX of checkbox - https://drive.google.com/file/d/0B7_NYFVmb896WnFvVVg4dmsyd00/view
--from user
Why is this generic attestation a checkbox rather than the drop down as others? For a moment, I was confused as I didn’t expect this new interaction.  https://screenshot.googleplex.com/fLUaVWbgQcT
> GGRC-2966 Assessment UX - checkbox

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/prev-next-buttons/prev-next-buttons.js
- src/ggrc/assets/javascripts/components/prev-next-buttons/tests/prev-next-buttons_spec.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/prev-next-buttons/prev-next-buttons.mustache
- src/ggrc/assets/mustache/components/related-objects/related-issues.mustache
- src/ggrc/assets/stylesheets/modules/_info-pin.scss
- src/ggrc/assets/stylesheets/modules/_object-header.scss
Add ability to navigate between assessments by clicking on "Next" and "Previous" buttons in info pane.
Assessment info pane should be closed when the following actions are performed on the page:
1. Sorting;
2. Pagination;
3. Filtering (simple search / advanced search / filtering by states)
4. On creating new object.
> GGRC-2855: Add Prev-Next buttons on Assessment Info pane

- src/ggrc/assets/javascripts/components/cycle-task-actions/cycle-task-actions.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/mustache/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
1. Create one time workflow.
2. Add at least 3 tasks to Task group in Setup tab, one task should be overdue.
3. Activate workflow.
4. At the Active Cycles tab verify tasks.
5. Click 'undo' button for all tasks and hover over first Tasks's tiers: only overdue task contains 'Verify'/'Decline' buttons.
Expected Result: 'Verify'/'Decline' buttons should be displayed in Tasks first tier after clicking 'undo'
> GGRC-2907: Fix issue with 'Verify'/'Decline' buttons on 'Tasks' tree view

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-state.js
- src/ggrc/assets/mustache/components/advanced-search/advanced-search-filter-state.mustache
There is some confusion between the status of the object (marked active / draft/ deprecated) in GGRC to the actual status of the underlying system of product.
The tool tip should be added for status attribute on Unified mapper and advanced searh of products or system:
Tool tip text is "The state represents the state of this object information within GGRC. It does not indicate the state of the underlying product or system"
> GGRC-3019 Add tooltip for state on Unified Mapper

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
1. Have audit with control's snapshot
2. Generate assessment based on the control's snapshot
3. Expand Assessment's Info pane and click control's snapshot to open Control popup
4. Click Control's link
Actual Result: While clicking Control's link in the Control popup audit page is displayed
Expected Result: While clicking Control's link in the Control popup original control Info page should be displayed
> GGRC-3023 Incorrect control's link in Control popup on Assessment's Info pane

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/related-objects/related-assessment-item.js
- src/ggrc/assets/javascripts/components/related-objects/related-evidences-and-urls.js
- src/ggrc/assets/javascripts/components/related-objects/tests/related-evidences-and-urls_spec.js
- src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
1. Have two assessments on the audit page with filled Reference URLs
2. Expand Assessment Info pane for one of Assessment
3. Click 'Related Assessments' button
4. Look at the Attachments/URLs column: Reference URLs are displayed
Actual Result: If user opens Related Assessments window, Reference URls are displayed
Expected Result: If user opens Related Assessments window, Reference URls should not display. Reference URls should be removed from Related Assessments window. Only evidences and URLs (from grey box) should be displayed in Attachments/URLs column in Related Assessments window
> GGRC-3069: Remove 'Reference URLs' from Related Assessments window

- src/ggrc/assets/javascripts/components/assessment/info-pane/confirm-edit-action.js
1. On the audit page Invoke new assessment modal window
2. Fill the required fields and add Reference URL > Save and Close
3. Look at the assessment's state in tree view: is "In progress"
*Actual Result:* New assessment is created in "In progress" state if add Reference URL while creation
*Expected Result:* If user create/generate new assessment, assessment should be in "Not Started" state
-------
Discussed with Lilia and Andrei K.
Original issue will be fixed in separate ticket on backend side.
In scope of this ticket I should prevent confirmation modal appearing in 'not started' state.
> GGRC-3033 New assessment is created in "In progress" state if add Reference URL while creation

- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
1. Have assessment on the audit page 
2. Expand Info pane and look at the padding between label and title 
Expected Result: Improve padding between label and title: 8 px
> GGRC-2873 Improve padding between label and title 

- src/ggrc/assets/javascripts/components/info-pin-buttons/info-pin-buttons.js
The "Close info pane" tooltip on the assessment info page was stuck in its place when the info pane was closed. 
1. Have audit with created assessment
2. Go to assessments tab and click first tire to expand Info pane
3. Hover over [x] button to show "Close Info pane" tooltip
4. Close Info pane
Actual Result: "Close Info pane" tooltip is sticking to the screen after closing Assessments Info pane
Expected Result: "Close Info pane" tooltip should disappear after closing Assessments Info pane
> GGRC-3036 Remove stuck "Close info pane" tooltip when the close button is pressed.

- src/ggrc/assets/javascripts/components/tabs/tab-panel.js
Sometimes duplicate tab ids where generated which led to making active
two tabs at the same time.
The issue is hard to reproduce due to reliance on the current time stamp which was used as the tab id. On a fast machine, where the code executes faster, this issue should appear more frequently.
1. Go to My work page > Assessments tab
2. Click on first tier of any Assessment in tree view
3. Once Assessment's first tier is expanded click on Related Issues or Related Assessment tab
4. Look at the screen: Related Issues and Related assessments tab are both opening
Actual Result: If user clicks on related assessments or related issues tabs on Assessment's Info pane, mentioned tabs are both opening. Related Issues data is displayed under Related assessments data
Expected …
> GGRC-2822 Fix duplicate tab ids in assessment info pane.

- src/ggrc/assets/javascripts/components/rich_text/rich_text.js
1. Have GCA with rich text type for Regulation
2. Go to My Work page > Regulations tab
3. Navigate to Regulation's Info pane
4. Fill GCA with rich text > Save
5. Update GCA with rich text > Save
6. Look at the screen: error is shown
***Actual Result:*** "Uncaught TypeError: this.attr(...).off is not a function     at Constructor.onRemoved" error message occurs if update CA with rich text on Regulation's Info pane
***Expected Result:*** no errors are shown while updating GCA with rich text type
> GGRC-2937 JS error message occurs if update CA with rich text on Regulation's Info pane

- src/ggrc/assets/stylesheets/components/related-objects/_related-reference-urls.scss
1. Have any program 
2. Add long Reference URL 
3. Look at the URL 
"Actual Result:" Reference URL has too long width on the Info pane 
Expected Result: Make appropriate width for Reference URLs on objects Info pane. TBD with UX person
New of url field is 200px.
> GGRC-2897 Make appropriate width for Reference URLs on objects Info pane

- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/fulltext/test_mysql.py
- test/integration/ggrc/snapshotter/test_indexing.py
BE should support filtering and sorting Assessments by GCA with type 'checkbox' (available values 'Yes' and 'No').
> GGRC-3059 BE: add support for filtering and sorting assessments by GCA with type 'checkbox'

- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
> GGRC-3012: Cut off controls/objectives title on Related Assessment Info and Related Assessments modal

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
**NOTE:** In scope of this ticket I fixed GGRC-2314 because GGRC-2898 is redundant.
GGRC-2314 Steps to reproduce:
1. Invoke New assessment template modal window
2. Look at the "Default Assignees" dropdown: 'Principal Assignee' option should is not selected by default
**Actual Result:** 'Principal Assignee' option is not selected by default for 'Default Assignee' dropdown on Assessment Template
**Expected Result:** 'Principal Assignee' option should be selected by default for 'Default Assignee' dropdown on Assessment Template
> GGRC-2898/ GGRC-2314 'Principal Assignee' option is not selected by default for 'Default Assignee' dropdown on Assessment Template

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment/info-pane-save-status.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/auto-save-form/auto-save-form-status.js
- src/ggrc/assets/javascripts/components/loading/loading-status.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/loading/loading-status.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/components/loading/_loading-status.scss
Scope:
Show gray label "Saving ..." next to Complete button during the time - when user entered smth - until Complete is activated.
From user:
After selecting from the “is control operating effectively” drop down, it takes a few seconds before COMPLETE button activates.
> GGRC-2960 Assessment pane - show "Saving ..." next to COMPLETE button

- src/ggrc/assets/javascripts/controllers/mapper.js
2. Click 'Global Search' button
**Actual Result**: Unified Mapper window is displayed instead of Global Search
**Expected Result**: Global Search window should be displayed if click 'Global Search' button
> GGRC-3095 Unified Mapper window is displayed instead of Global Search

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/lazy-render/lazy-render.js
- src/ggrc/assets/javascripts/components/tree/tree-item-actions.js
- src/ggrc/assets/mustache/components/tree/tree-item-actions.mustache
- src/ggrc/assets/mustache/components/tree/tree-item.mustache
- test/selenium/src/lib/base.py
**Issue:** The main problem is updating the list of items to display ('showedItems' list)
**Target:** Reduce the time of rendering page of treeview
**Results:**
- before:
- after:
**For reviewer:**
- Enable showing all levels of log in the Chrome console (see screenshot 1)
- Go through a few pages of the tree view and look the results
> GGRC-2630 Reduce time of initialization page of tree view after loading data

- src/ggrc/services/common.py
The exception raises when json is formed for deleted object. 
As frontend doesn't use json representation of deleted object it is no need to send it in response.
> GGRC-2872 HTTP500 is returned on deletion of object with CA after the object is deleted

- src/ggrc/automapper/__init__.py
- src/ggrc/migrations/versions/20170710092621_2ada007df3ee_add_automappings_table.py
- src/ggrc/models/all_models.py
- src/ggrc/models/automapping.py
- src/ggrc/models/relationship.py
- src/ggrc/models/snapshot.py
- src/ggrc/snapshotter/helpers.py
- test/integration/ggrc/automapper/test_automappings.py
When deleting a relationship that caused automappings the automapped relationship's automapping_id is set to NULL which means that we lose the information if the relationship was automapped. This PR will fix this by adding a new automappings table that will hold this information even when the parent relationship is deleted.
> GGRC-2465 Make sure we don't lose track of automappings

- src/ggrc/query/assessment_related_objects.py
- src/ggrc/query/views.py
This is a performance improvement of query needed for assessment info pin leading.
~This PR is dependent on https://github.com/google/ggrc-core/pull/6155~
To compare the performance impact with both tihs and the parent PRs merged
https://optimized-dot-ggrc-perf.appspot.com/dashboard#assessment_widget
https://ggrc-perf.appspot.com/dashboard#assessment_widget
The changes in this ticket also remove a lot of data that I assume was not being used anywhere on the frontend, such as related sources and destinations of snapshots and simmilar things.
Besides performance, please also verify for any regressions when dealing with snapshots, comments, and attachments.
> GGRC-2527 Improve assessment related query

- src/ggrc/assets/javascripts/components/related-objects/related-assessment-list.js
Preconditions: have program, control, audit
1. On the audit page generate at least 11 assessments based on control
2. Navigate to Assessment's Info pane one of assessments
3. Open Related Assessments window and using pagination follow to the next page
4. Look at the window
Actual Result: Spinner disappears in Related Assessments window before data was loaded; extra spinners are displayed on Related Assessments window while user navigates on next page.
Expected Result: Spinner should disappear in Related Assessments window when data was loaded; there should be no extra spinners while user navigates on next page.
> GGRC-1984/GGRC-1942: Show spinner in Related Assessment window when data is loading

- src/ggrc/assets/javascripts/components/datepicker/datepicker.js
- src/ggrc/assets/mustache/components/auto-save-form/fields/person-form-field.mustache
- src/ggrc/assets/mustache/components/datepicker/datepicker.mustache
- src/ggrc/assets/stylesheets/components/auto-save-form/fields/_date-form-field.scss
- src/ggrc/assets/stylesheets/components/auto-save-form/fields/_person-form-field.scss
- src/ggrc/assets/stylesheets/modules/_datepicker.scss
1. Have GCA/LCA with date type for assessment
2. Navigate to assessment's Info pane> CA with date type
3. Select date from date picker and save 
4. Try to remove date from CA with date type: there is no possibility to remove date
*Actual Result:* Impossible to remove date from CA field with date type
*Expected Result*: Should be a possibility to remove date from CA field with date type
> GGRC-2500 Impossible to remove date from CA field with date type

- bin/release/get_pr_titles.py
This PR fixes crashes of `get_pr_titles` script on non-ASCII characters in PR titles.
> QUICK-FIX Encode all UTF-8 output explicitly

- src/ggrc_workflows/assets/mustache/workflows/info.mustache
This will help with testing as it is currently impossible to check when
the next cycle will be created without looking into the database.
> QUICK-FIX Show next cycle start date in wf info pane

- src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
- src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache
1. Go to My work page > Assessments tab
2. Type any filter query into Search box (e.g. "Assignees = user@google.com")
3. Click out of the Search box: filter is applied
Actual Result: Filter applies if click out of Search box 
Expected Result: Filter should be applied if click [Filter] button and [Enter]
*Note:* this causes some unfriendly behavior. If user types any Filter query into Search box and then wants to copy some values from the tree view, user clicks out of the Search box and tree view is refreshed. User needs to click reset and type filter query once again.
> GGRC-2180 Filter applies if click out of Search box 

- src/ggrc/assets/mustache/components/prev-next-buttons/prev-next-buttons.mustache
- src/ggrc/assets/stylesheets/modules/_object-header.scss
1. Add tooltips "Open next Assessment", "Open previous Assessment".
2. Reduce border between 'next'/'previous' controls to single line.
3. Update disabled state for 'Prev/Next' buttons.
> GGRC-3098: Update styles for 'Prev/Next' buttons on Assessment Info pane

- src/ggrc/assets/javascripts/components/object-selection/object-selection.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results.mustache
1. Have Control snapshot on the audit page
2. Invoke New Assessments modal window
3. Click Map objects button
4. Once Control snapshot is displayed in Unified mapper Select All and Click Map Selected
5. Look at the mapped snapshot
6. Click Map Objects once again and Select All in Unified mapper: confirm Map selected button in enabled
7. Click Map selected button and look at the mapped snapshots: snapshots are duplicated
Actual Result: Already mapped snapshots to Assessment can be mapped again if click Select all in Unified mapper
Expected Result: Already mapped snapshots to Assessment should not be mapped again if click Select all in Unified mapper
> GGRC-2270: Restrict possibility to map already mapped objects to Assessment

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_snapshots.py
- test/selenium/src/tests/test_unified_mapper.py
Reuse method for objects comparison in tests. Fix issue with converting datetime string to object. Move logic to update assessor value to Entity object and remove redundant code from child.
> QUICK-FIX Refactor asserts comparing objects

- src/ggrc/notifications/__init__.py
The error is caused by qa specific data. Notifications are not sent every day. They are accumulated for a year. There are assessments with corrupted revisions.
However, it would be better to make code more robust in order to process any kind of data without an exception.
> GGRC-3116 _notifications/show_daily_digest: Internal Server Error

- src/ggrc/query/views.py
The optimization for related objects omits some data that right now
causes some regressions and has to be reverted until it is fixed.
> GGRC-3122 Disable assessment related objects optimization

- src/ggrc/assets/javascripts/components/assessment/info-pane-save-status.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/mustache/assessments/header.mustache
Scope:
Show gray label "Saving ..." next to Complete button during the time - when user entered smth - until Complete is activated.
From user:
After selecting from the “is control operating effectively” drop down, it takes a few seconds before COMPLETE button activates.
related to: #6170
> GGRC-2960 Assessment pane - show "Saving ..." next to COMPLETE button (improvement)

- src/ggrc/models/mixins/with_action.py
- test/integration/ggrc/models/mixins/test_with_action.py
Allow empty lists for operations. The change is requested by FE team. It will improve FE code readability.
> GGRC-3101 "Empty actions list" Error

- src/ggrc/assets/javascripts/plugins/utils/dashboards-utils.js
1. Create a new Assessment.
2. Open it in a new tab.
Actual Result: "Uncaught TypeError: Cannot read property 'custom_attribute_id' of undefined" error occurs
Expected Result: no errors are displayed, the info page is shown.
> GGRC-3124 "Uncaught TypeError: Cannot read property 'custom_attribute_id' of undefined"

- src/ggrc/query/autocast.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/querying_with_unicode.csv
1. Create GCA with non-ASCII characters with any type
2. Open existent assessment on the audit page 
3. Fill GCA 
4. Type into Search box GCA title with non-ASCII characters and filter by the value, e.g. "АС\ЫЦУМПА" = siarhei"
Actual Result: ""There was an error" is displayed with 500 error in console.
Expected Result: no error is shown. Filter should work for GCA that contains non-ASCII characters.
> GGRC-2170 HTTP500 returned when you filter by GCA field that contains non-ASCII characters through Filter

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/auto-save-form/auto-save-form-field.js
- src/ggrc/assets/javascripts/components/auto-save-form/auto-save-form.js
- src/ggrc/assets/javascripts/components/auto-save-form/fields/rich-text-form-field.js
- src/ggrc/assets/javascripts/components/auto-save-form/fields/text-form-field.js
- src/ggrc/assets/javascripts/components/form/form-validation-icon.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/plugins/tests/ca_utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
- src/ggrc/assets/mustache/components/auto-save-form/auto-save-form-field.mustache
- src/ggrc/assets/mustache/components/auto-save-form/auto-save-form.mustache
- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
Custom attribute of dropdown type was not correctly displaying
verification icon for certain values.
Some code commits solved the original issue but brought a new one. The non-mandatory dropdown CA was showing the "None" value as invalid and thus required change.
> GGRC-2378 Fix wrong verification state of Dropdown CA

- src/ggrc/assets/mustache/components/tree/tree-filter-input.mustache
- src/ggrc/assets/mustache/components/tree/tree-widget-container.mustache
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
1. Update placeholder in 'Search' field to 'Type here to search or click the advanced search icon'
2. Advanced search icon should not be grey (because it seems as disabled) - color for advanced search icon = black #000000
opacity = 70%
3. Use ‘Advance Search’ title on pop-up.
> GGRC-3140: UX updates for Search component

- src/ggrc/settings/default.py
Reverts google/ggrc-core#6252
We decided to postpone the delivery of 0.10.28 by a week.
> QUICK-FIX Downgrade version to 0.10.28-Raspberry

- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
Space between LCA and from 'Attach' button to LCA list should be equal to 30px.
> GGRC-2024: Fix alignment issues with LCA

- src/ggrc/assets/javascripts/components/assessment/info-pane/confirm-edit-action.js
- src/ggrc/assets/javascripts/components/assessment/map-button-using-assessment-type.js
1. On the audit page create assessment
2. Click Map button twice in the first tier: confirm Unified Mapper window is duplicated
Actual Result: Unified mapper window is duplicated if click twice on Map button
Expected Result: Unified mapper window should not duplicated if click twice on Map button
The ticket was reopened due to Unified mapper is duplicated if click twice on [+] button to map Controls and Related Information on Assessment's Info pane. Also, Unified mapper is duplicated if click twice [Map objects] in Edit Assessments modal window. Now it fixed.
> GGRC-1199 Unified mapper window is duplicated if click twice on Map button 

- src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/stylesheets/components/form/_ggrc-form.scss
- src/ggrc/assets/stylesheets/components/people-group/_people-group.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
- test/selenium/src/lib/constants/locator.py
Split assessment attributes on 3 columns: 
- 200px for content and 40px for padding,
- 720px for text fields content.
> GGRC-2182: Split assessment attributes on 1,2,3 columns

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
1. Have program, control, audit
2. Go to the audit page > Assessments tab
3. Open generate assessments popup
4. Click Select All
5. Look at the 'Generate assessments' button: is disabled while control snapshot is selected
Actual Result: Generate Assessment button is disabled if click select all in generate assessment popup
Expected Result: Generate Assessment button should not be disabled if click select all in generate assessment popup
> GGRC-3145 Generate Assessment button is disabled if click select all in generate assessment popup

- src/ggrc/assets/javascripts/components/assessment/info-pane/confirm-edit-action.js
- src/ggrc/assets/javascripts/components/assessment/map-button-using-assessment-type.js
This fix caused regression with inline edit components
1. Have Assessment on the audit page
2. Expand Assessment Info pane and try to add Verifier
Actual Result: the app freezes and user is not be able to edit any field after adding Creator/Assignee/Verifier on the Assessments Info pane
Expected Result: the app should not freeze and user should be able to edit any field after adding Creator/Assignee/Verifier on the Assessments Info pane
> GGRC-3147 The app freezes if make any inline edit of Creator/Assignee/Verifier on the Assessments Info pane

- src/ggrc/query/views.py
This can now be enable back, because we do not need related objects
information anymore since GGRC-3123 and GGRC-3120 have been merged.
> QUICK-FIX Re-enable assessment related optimization

- src/ggrc/notifications/notification_handlers.py
- test/integration/ggrc/notifications/test_assessment_notifications.py
- test/integration/ggrc/notifications/test_data_handlers.py
1. Create an Assessment.
2. Open its info pane.
3. Add an Evidence URL (to move the Assessment to IN PROGRESS state).
4. Click the map button in Controls section.
5. Map at least two Controls at once.
6. Update the title of the Assessment.
Expected result: the title is updated.
Actual result: the PUT to update the title results in HTTP500
1. Create an Assessment.
2. Map 5 Snapshots to it at once.
Expected result: one "assessment_started" notification is generated.
Actual result: five "assessment_started" notifications are generated.
> GGRC-3134,3135 Create notification only once

- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
To reproduce:
1. Load assessment list with at least two pages.
2. Go to page 2
3. Open first item on the list
Prev button is going to be disabled, after clicking the next button you'll navigate to the second item on the second page instead of the second item on the second page.
> GGRC-3152 Fix prev/next buttons for first items on non first page

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/js_specs/mustache_helpers/date_spec.js
- src/requirements-selenium.txt
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/filter_utils.py
- test/selenium/src/lib/utils/string_utils.py
GGRC app shows datetime attributes of entities in different representation.
Expected: 
GGRC should show datetime attributes of entities in a same (unify) representation:
Format: MM/DD/YYYY hh:mm:ss A Z
e.g. 08/22/2017 03:25:47 PM +03:00
> GGRC-3092 Unify 'datetime' representation on GGRC's UI layer (tree view, info widget, e.t.c.) 

- src/requirements-dev.txt
- src/requirements.txt
The error was caught while trying to create a new CA from the GGRC-2170 ticket.
Werkzeug returns an error when the title of the CA is "АС\ЫЦУМПА"
> GGRC-3102 HTTP500 Returned on POST with some utf-8 symbols.

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/mustache_helpers/get_custom_attr_value_spec.js
1. Have 2 GCAs with checkbox type for assessment
2. Have audit with created assessment
3. Navigate to assessment's Info pane
4. Fill 1 GCA with checkbox type - check checkbox
5. Set visibility in tree view for 2 GCAs with checkbox type
6. Look at the Assessment's first tier
Expected Result: If checkbox is checked it is shown as 'Yes' in tree view. If checkbox is unchecked it is shown as 'No' in tree view
> GGRC-2970: Display CA with checkbox type as 'Yes/No' in tree view

- src/ggrc/assets/javascripts/components/tree/sub-tree-wrapper.js
1. Have Risk/Threat
2. Go to My work page> Risk tab
3. Hover over first tier and Expand subtree
4. Select Filter sub tree > Select "select none" and Click Set Visibility
5. Collapse sublevel
5. Expand Sub level: confirm mappings are shown
Actual Result: "Select none" in Filter sub tree doesn't work for Risks/Threats
Expected Result: "Select none" in Filter sub tree should work for Risks/Threats
If we choose "select none", in sub tree not display any results now.
> GGRC-2042 "Select none" in Filter sub tree doesn't work for Risks/Threats 

- bin/do_deploy
We should not rely on previous deployments for task queues and cron jobs
to be running normally and should always make sure to deploy them with
the latest data
> QUICK-FIX Add cron jobs and task queues to deployment script

- src/ggrc/assets/stylesheets/modules/_object-header.scss
Improve padding between label and title on info pane. Should be 8px.
> GGRC-2873: Improve padding between label and title

- src/ggrc/assets/mustache/components/assessment/custom-attributes.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/stylesheets/components/form/_ggrc-form.scss
Fix for alignment issues in 'Other attributes' tab:
1. CA of type 'Rich text' should occupy one row.
2. Reduce CA title maximum length to 3 lines to avoid issue with hovering over long CAs.
> GGRC-3162: Fix alignment issues in 'Other attributes' tab

- src/ggrc/assets/mustache/base_objects/test_plan.mustache
1. Invoke New Control modal window
2. Fill all the fields required and Test plan field > Save
3. Look at Control's Info page: Test plan is not shown
Actual Result: "Test plan" is not displayed on Control's Info page/pane after adding
Expected Result: "Test plan" should be displayed on Control's Info page/pane after adding
> GGRC-2168 "Test plan" is not displayed on Control's Info page/pane after adding

- src/ggrc/assets/javascripts/components/assessment_generator.js
- src/ggrc/assets/javascripts/components/assessment_templates/assessment_templates.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/components/object-generator/object-generator.mustache
Remove redundant requests on Relationships after open Assessment Generation modal and migrate loading Assessment Templates by Query API
Pre-requirements:
1. Open Network tab in Chrome DevTool
Steps for reproduce:
1. Create Program
2. Map to this Program 1000+ objects of different types
3. Create Audit
4. Open Audit page
5. Go to Assessment tab
6. Open Assessment Generation modal by 3bbs button
Actual result: many GET requests on Relationship in network tab
Expected result: Migrate loading Assessment Templates on Query API
> GGRC-3107 Remove requests on Relationship after open Assessment Generation modal

- src/ggrc/assets/javascripts/components/tree/sub-tree-wrapper.js
- src/ggrc/assets/mustache/components/tree/sub-tree-wrapper.mustache
Precondition:
1. Go to the audit page-> Control's tab
2. Expand sub level in tree view: confirm "Show objects not directly related to this Control" but there is nothing to show
Actual Result: Remove Show objects link in snapshots if there is nothing to open
Expected Result: Show objects link in snapshots should not be shown if there is nothing to open
> GGRC-1217 Remove Show objects link in snapshots if there is nothing to open 

- src/ggrc/converters/snapshot_block.py
- src/ggrc/models/revision.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_snapshot_block.py
- test/integration/ggrc/test_csvs/control_snapshot_data_multiple.csv
- test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
- test/selenium/src/tests/test_snapshots.py
Have program, control with Custom role field (e.g. "Primary Contacts"), audit with control snapshot
On the audit page go to Controls tab and Export controls
Open csv file and look at the custom role field: "Primary Contacts" is not shown
Actual Result: If export control snapshot custom roles are absent in csv file
Expected Result: If export control snapshot custom roles should be displayed in csv file
https://ggrc-qa.appspot.com/audits/4160#control_widget
This PR re-applies changes done in #5938
> GGRC-2750 Re-apply Fix absence of AC roles in exported csv file for snapshots

- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
2. Have at least 3 assessments: control snapshot is mapped to both assessments, 1 assessment has no mapping 
3. Expand Info pane of assessment that has mapped control snapshot
4. Open Related Assessment tab
5. Click Next/Prev
6. Look at the Related Assessments
Actual Result: Related assessments of previous assessment are displayed while click 'Prev/Next'
Expected Result: Related assessments of previous assessment should not be displayed while click 'Prev/Next'
> GGRC-3159: Refresh related assessments after Prev/Next navigation

- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/stylesheets/modules/_assessment.scss
Changes:
1. Place 'Custom roles' at the top of 'Other attributes' tab.
2. Reduce 'Other attributes' width to 720px.
> GGRC-3146: Move custom roles at the top of 'Other attributes' tab

- src/requirements-dev.txt
Versions 0.10 and later of Werkzeug use watchdog (if available on the
system) for more efficient file change detection. Installing watchdog
causes  werkzeug to use inotify reloader which is much more efficient
than the basic stat reloader. Developers should notice a drop in CPU
utilization, especially if using docker for mac.
Before this PR hyperkit was using 20-40% of the CPU when launch_ggrc was running:
After the change CPU usage dropped to 3%:
I believe the change won't be as drastic on Linux machines, but it should still be better.
To verify this PR works look for the reloader text when starting the app:
Before:
```
INFO     2017-08-22 08:49:42,766 werkzeug  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
INFO     2017-08-22 08:49:42,779 werkzeug  * Restarting with stat
``` …
> QUICK-FIX Install watchdog for more efficient change reloading

- src/ggrc/assets/javascripts/apps/dashboard.js
- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/assets/javascripts/components/csv/import.js
1. Have active one time WF
2. Go to Active Cycles tab and Export Cycles
3. Look at Filter by Mapping: is not preselected
4. Click [+] button: is disabled
**Actual Result:** Filter by mapping is not preselected and [+] button is disabled on the Export page if Export Cycles/People/Task Group from Workflow page 
**Expected Result:** Filter by mapping should be preselected (in this case Workflow object and Workflow's title is displayed in the filter field) and [+] button should be enabled on the Export page if Export Cycles/People/Task Group from Workflow page
> GGRC-2226 Filter by mapping is not preselected and [+] button is disabled on the Export page if Export Cycles/People/Task Group from Workflow page 

- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
- src/ggrc/assets/mustache/base_objects/unmap.mustache
Remove Unmap action from 2d level - on objects which are not related directly to current object (gray ones) on Info pin window.
> GGRC 2043: Remove unmap button for not directly related objects 

- src/ggrc/assets/stylesheets/_placeholders.scss
- src/ggrc/assets/stylesheets/modules/_progress.scss
- src/ggrc_workflows/assets/javascripts/controllers/dashboard_page.js
- src/ggrc_workflows/assets/mustache/dashboard/info/workflow_progress.mustache
2. Create at least 5 tasks including 1 overdue task and Activate WF
3. On Active Cycles tab move tasks to the following states: Assigned, In progress, Finished, Declined, Assigned (overdue task)
4. Go to My Work page and look at the created WF stats
**Actual Result:** Workflow stats on My work page is not correspond to tasks states color
**Expected Result:** Tasks states should be correspond to the following requirements:
Assigned - grey color (#bdbdbd);
In Progress - blue color (#3369e8);
Finished - #405f77;
Declined - red (#d50f25);
Verified - green (#009925).
OVERDUE - red
Visual Design: https://drive.google.com/corp/drive/folders/0B65BmaCGVTRwTGc5S296WjVqY3c
> GGRC-2312 Workflow stats on My work page is not correspond to tasks states color

- src/ggrc/assets/javascripts/plugins/ajax_extensions.js
1. Go to My work page
2. My tasks tab
3. Using Search box filter by "TASK DUE DATE" with search query that contains incorrect date (e,g, "TASK DUE DATE" = "2017-06/12")
4. Click Search button: error is displayed
**Actual Result:** "There was an error!" error occurs if filter by "TASK DUE DATE" with query that contains incorrect date
**Expected Result:** 'Invalid date was typed into '<field name>' field, please change and try again!'
> GGRC-3180 FE: make a better error message while date format is wrong

- src/ggrc/assets/javascripts/models/issue.js
1. Have GCA with any type, e.g. date type
2. Have audit with created Issue 
3. Go to the Issues tab > Expand Issue Info pane
4. Edit GCA with date type and save
5. Look at the screen: 'Save' message is displayed but value is not saved
Actual Result: Editing of GCA doesn't work for the Issue object
Expected Result: Editing of GCA should work for the Issue object
> GGRC-3201: Fix editing of GCA for the Issue object

- src/ggrc/assets/javascripts/components/csv/import.js
- src/ggrc/assets/javascripts/components/csv/test/import_spec.js
1. Create program, control, audit
2. Go to Export page
3. Select Snapshots form dropdown "Export Object Type"
4. Select Snapshot object type - control and select mapped to the audit, audit title> Export
5. Make changes in scv file and import
**Actual Result:** Import button is enabled while importing snapshot
**Expected Result:** Import button should be disabled if import snapshot. The system should not allow to import snapshot
> GGRC-1997 Import: If there is nothing to import in the csv file (e.g. snapshots), the import button should be disabled.

- docker-compose.yml
Upgrading to 5.6 seems to work without a problem.
I have also tried upgrading to 5.7, but the migrations fail and there is a need to run mysql_upgrade command for a missing table to be restored (`Table 'performance_schema.session_variables' doesn't exist") [SQL: "SHOW VARIABLES LIKE 'sql_mode'`). Even after this there were issues like the following stack trace:
```
INFO  [alembic.migration] Running upgrade None -> 262bbe790f4c, Import all squashed migrations from 0.9.5-Zucchini-P1.
ERROR [sqlalchemy.pool.QueuePool] Error closing cursor
File "/vagrant/src/packages/sqlalchemy/engine/base.py", line 1277, in _safe_close_cursor
cursor.close()
File "/vagrant-dev/opt/linked_packages/MySQLdb/cursors.py", line 91, in close
while self.nextset():
File …
```
> QUICK-FIX Upgrade mysql to 5.6

- bin/check_pylint_diff
- break logic into functions
- use git clone instead of cp && git clean
- run pylint just once to get both the report and the score
As a side effect, this change makes check_pylint_diff around 3 times faster (roughly 30 seconds vs roughly 8 seconds).
> QUICK-FIX Organize pylint checker neatly

- src/ggrc_basic_permissions/__init__.py
- test/integration/ggrc/services/test_assessments.py
It's not allowed to delete assessment based on the AssigneeType related to assessment.
> GGRC-3229 Assessor/Creator/Verifier shouldn't delete assessment

- src/ggrc/models/mixins/autostatuschangeable.py
- src/ggrc/notifications/notification_handlers.py
- test/integration/ggrc/models/mixins/test_autostatuschangable.py
If I edit the assignee via the 'edit object' popup, the assessment is moved to "In Progress" screenshot-1.png, screenshot-2.png
This does not happen if I open the assessment in a new tab.
I should be given the option on whether I want it to be in progress or not.
Confusing the assignee whether the assessment truly is in process or not.
> GGRC-2759 Changing the assignee field should not force an assessment to "In Progress"

- src/ggrc/models/issue.py
- test/integration/ggrc/models/mixins/test_with_action.py
When FE developer wants to map existing document to assessment, he can add next parameters to assessment PUT request:
`"actions": {
"add_related": [
{
"id": 7,
"type": "Document"
}
]
}`
The same functionality is needed for Issue objects. It is needed for front-end improvement. This is the reason for provided changes.
> GGRC-2854 Add 'actions' pseudo field to Issue to map/unmap objects

- src/ggrc/converters/handlers/snapshot_instance_column_handler.py
- src/ggrc/utils/rules.py
- test/integration/ggrc/converters/test_export_audit.py
- test/integration/ggrc/models/factories.py
- test/unit/ggrc/utils/test_rules.py
Export of Audit should work in the same way as export of Assessment: all mapped objects should be exported. Linked Assessments and Issues should be exported also.
> GGRC-2988 Add mapped objects to Audit export

- src/ggrc_gdrive_integration/settings/development.py
We should not store any private keys in our repo.
From now on keys will have to be specially set up on each dev environment.
> GGRC-3274 Remove invalid client keys

- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/stylesheets/modules/_modal.scss
1 - On the audit page create assessment
2 - Click Map button twice in the first tier: confirm Unified Mapper window is duplicated
Actual Result: Unified mapper window is duplicated if click twice on Map button
Expected Result: Unified mapper window should not duplicated if click twice on Map button
The ticket was reopened due to Unified mapper is duplicated if click twice on [+] button to map Controls and Related Information on Assessment's Info pane. Also, Unified mapper is duplicated if click twice [Map objects] in Edit Assessments modal window.
> GGRC-1199 Unified mapper window is duplicated if click twice on Map button

- src/ggrc/converters/handlers/handlers.py
- test/integration/ggrc/data_platform/test_last_assessment_date.py
1. Export control that has last assessment date
2. Open csv file and change 'last assessment date' column
3. Import csv file with control
Actual Result: User is not informed that Last Assessment Date field is not editable over import
Expected Result: User should be informed that Last Assessment Date field is not editable over import.
Proposal:
1. Inform user in csv file that 'Last Assessment Date' is not editable.
	'Last assessment date' column - NOTE: cannot change 'Last assessment date';
or
2. Warning during analyzing csv file to import
> GGRC-2885 Make proper warning for user that Last Assessment Date field should is not editable over import 

- src/ggrc/assets/stylesheets/components/inline/_inline.scss
Alignment issue for GCA of 'checkbox' type:
leaping effect when user hovers over CA title (should be short enough).
> GGRC-3162: Fix alignment issue for GCA of checkbox type

- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
- test/integration/ggrc_workflows/models/test_workflow.py
- test/integration/ggrc_workflows/test_api_calls.py
- Original Workflow (X August) does not require verification, in other words, Need Verification = False
See attachment: Original Workflow 
- However, when user cloned the workflow, the new workflow automatically created as Need Verification = True
See attachment: Cloned Workflow
- User tried to switch from UI, but button is greyed out, user also tried to use CSV upload to change workflow setup. It resulted errors.
See attachment: CSV update error
- Expected the workflow to be cloned EXACTLY the same
- Expected workflow to allow switching verification requirement (until activation)
- …
> GGRC-3221 RMC Workflow - Cloned workflow forced verification

- src/ggrc/assets/javascripts/components/assessment_templates/assessment_templates.js
Due to move to webpack dropdown element was not imported in the the
Generate Assessment modal.
> GGRC-3287 Fix missing Assessment Template dropdown in Generate Assessment modal

- src/ggrc/query/autocast.py
- test/integration/ggrc/services/test_query/test_basic.py
on hold till ~https://github.com/google/ggrc-core/pull/6359~ will be merged
> GGRC-2836 "There was an error!" error occurs if filter by "TASK DUE DATE" with query that contains incorrect date

- test/integration/ggrc/services/test_query/test_basic.py
This commit makes sure that random order in a sub-list does not affect
the result outcome. Since all elements contain items with unordered list
such as related_sources and related_destinations, we must make sure to
ignore those when making an order comparison.
Example of a test result that failed randomly:
```
u'type': u'Program'},
u'related_destinations': [],
u'related_sources': [{u'context_id': None,
+                         u'href': u'/api/relationships/2699',
+                         u'id': 2699,
+                         u'type': u'Relationship'},
+                        {u'context_id': None,
u'href': u'/api/relationships/2698',
u'id': 2698,
u'type': u'Relationship'},
{u'context_id': None,
u'href': u'/api/relationships/2689',
u'id': 2689,
-                         u'type': …
```
> QUICK-FIX Fix randomly failing integration tests

- bin/create_apisearch_dump
- bin/db_reset
- bin/run_api_search
- src/ggrc/models/mixins/__init__.py
- src/ggrc/settings/testing_api_search_db.py
- test/api_search/__init__.py
- test/api_search/base.py
- test/api_search/helpers.py
- test/api_search/setters.py
- test/api_search/setup_environment.py
- test/api_search/test_acr.py
- test/api_search/test_ca_person.py
- test/api_search/test_modified_by_field.py
- test/api_search/test_person_filters_complete.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/query_helper.py
- test/integration/ggrc/services/test_query/test_snapshots.py
Create a framework for running full integration test suite for read only tests.
EDIT: the old obsolete description
Create integration tests for following parameters
field type: Person
operators: !=,!~, =, ~, is empty
ordering: asc, desc
sub-property: username, email, name
amount: one, two
search property: PERSON, person
search value: VALUE, value
models: all + snapshots
> GGRC-2072 Create testing framework read only filter integration tests

- src/ggrc/assets/javascripts/components/dropdown/dropdown.js
- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/components/tree_pagination/_tree_pagination.scss
- test/selenium/src/lib/constants/__init__.py
- test/selenium/src/lib/constants/counters.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/page/widget/generic_widget.py
This is almost trivial, but would it be an easy fix to view 20 assessments per page versus the preset limit of 10? I don't see any ability to modify the # viewable. 
Q - What is the problem / issue?
---- No problem, just a feature request.
Q - What is the expected result / outcome? (ie What should happen?)
---- I'd like to view more than 10 assessments per page.
Q - What is the impact if it is not fixed / implemented?
---- Impact isn't easily quantified.
With Ksenya we decided add some pagination buttons which always will displayed.
> GGRC-2199 Request to view more than 10 assessments per page 

- src/ggrc/assets/javascripts/components/tree/tests/tree-item-custom-attribute_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item-custom-attribute.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-results-item-attrs.mustache
1. Have GCA with rich text type for Control
2. Go to My work page > Control's tab
3. Set Rich text column to be displayed in tree view
4. Fill GCA field with rich text type on Info pane
Look at the Control's first tier in tree view: data in rich text is not shown
Other case:
1. Have GCA with rich text type for Assessment
2. Go to My work page > Assessments tab
3. Set Rich text column to be displayed in tree view
3. Fill GCA field with rich text type on Info pane
4. Look at the Assessment's first tier in tree view: data in rich text is not shown
Actual Result: Tree view is not automatically refreshed if fill CAs with rich text type
Expected Result: Tree view should be automatically refreshed if fill CAs with rich text type
> GGRC-3137/2232 Tree view is not automatically refreshed if fill CAs with rich text type

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
2. Create audit on the program page
3. Expand Audit Info pane and add auditor
_Actual Result:_ Audit Info pane collapses and tree view refreshes if add auditor to Audit
_Expected Result:_ Audit Info pane should not collapse and tree view should not refresh if add auditor to Audit
> GGRC-3143 Audit Info pane collapses and tree view refreshes if add auditor to Audit

- src/ggrc/assets/javascripts/components/assessment/assessment-people.js
- src/ggrc/assets/javascripts/components/object-list/object-list.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-mapping.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/tests/assessment_model_spec.js
- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
1. On the audit page Invoke New/Edit assessment modal window
2. Without any updates click [x] button to close the window
*Actual Result:* Confirmation message is displayed if there were no changes on asmt new/edit modal
*Expected Result:* Confirmation message should not displayed if there were no changes on asmt new/edit modal
I have found 3 issues broke changes tracking on edit modal:
1) mistake in preparing CustomAttributes.
2) relationships are loading asynchronous, as result - model is changing when backup was already created.
3) some components use instance to store service flags.
Also there were 2 issues on create modal:
1) object-list component sets 'isSelected' flag but does not remove it correctly.
2) default users are initializing …
> GGRC-3275 Confirmation message is displayed if there were no changes on asmt new/edit modal

- src/ggrc/assets/javascripts/components/csv/import.js
Just wanted to let you know that when importing an excel sheet into GGRC, I keep getting this error (screenshot attached to this email). It is preventing me from mapping and creating systems.
1. Have csv file with Section object (attached)
2. Import csv file
**Actual Result:** "Uncaught TypeError: this.attr is not a function" error occurs while importing csv file with section
**Expected Result:** no error are displayed while importing
I reproduced the issue with next steps:
1) Have non csv-file as "some_spreadsheet.ods".
2) Rename file as "some_spreadsheet.csv".
3) Try import this file.
In scope of this ticket: fix frontend logic of import to show error message from backend.
> GGRC-3284 JS error occurs while importing csv file

- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_snapshot_block.py
- test/integration/ggrc_workflows/converters/test_column_definitions.py
Add column 'Last Updated by'. Column should be displayed after 'Last Updated' column.
'Last Update by' column should be added for all objects that have 'Last Updated' column.
Allow user to sort objects by 'Last Updated by'.
Allow user to search / filter by last updated by + advanced search.
Allow user to import / export 'Last Updated by' attribute.
Show emails in 'Last Updated by' column.
> GGRC-3207,3268 Add 'Last Updated By' column to all objects

- src/ggrc/converters/base_block.py
- src/ggrc/converters/handlers/snapshot_instance_column_handler.py
- test/integration/ggrc/converters/test_export_audit.py
Basically ever mapping cell in the audit export that was added now triggers a new db query. 
With 20 mapped objects and a few hundred audits, that makes a few thousand queries too many.
Now the handler for mapped snapshots must be changed to prefetch all snapshot data that will be needed for export in a single query (but no more data than is actually needed) and then the cache should be used to fill out the csv cells instead of running a db query for each cell.
> GGRC-3280 Improve audit export performance

- src/ggrc/assets/mustache/components/object-list-item/document-object-list-item.mustache
- src/ggrc/assets/stylesheets/_common.scss
If the file name exceeds a certain length, I can't see the whole name without opening the file. The link in the bottom tray show the location in Drive. 
screenshot-1.png
I would like to be able to hover my cursor over the text and have a tool tip window show me the whole file name. 
Minimal, nice to have
>  GGRC-3215 Hover-over text for long file names 

- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
- src/ggrc/assets/javascripts/components/object-search/object-search.js
ACCPTANCE CRITERIA
AC1. Set default values for 'Object Type' dropdown on Unified Mapper, depending for which object it is opened:
https://docs.google.com/spreadsheets/d/11CHxbJZHPwD8rc9-4xCDnHbhQ4SE2SKDJcGxckuk2MQ/edit#gid=0
AC2. Set default value for 'Object Type' dropdown = 'Controls' on Global Search pop-up.
> GGRC-3188 Set default 'Object Type' on Unified Mapper

- src/ggrc/assets/stylesheets/modules/_info-pin.scss
1. Go to My work page > Control's tab
2. Navigate to Control's Info pane
3. Look at the [Assessments] button and 3 bb's menu
Actual Result: There is no padding between 3 bb's menu and [Assessments] button on Controls/Objectives Info pane
Expected Result: Improve placement of 3 bb's menu and [Assessments] button on Controls/Objectives Info pane as on screenshot-2.png
> GGRC-2692 Incorrect placement of 3 bb's menu and [Assessments] button on Controls/Objectives Info pane

- test/integration/ggrc/converters/test_acl_import_export.py
- test/integration/ggrc/converters/test_base_block.py
- test/integration/ggrc/converters/test_export_controls.py
- test/integration/ggrc/converters/test_export_csv.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_import_issues.py
- test/integration/ggrc/converters/test_imported_api_requests.py
This PR basically wraps all repeating factory calls into `factories.single_commit` context.
The affected 261 tests took on my machine:
- on dev: 154.223s
- on PR: 123.609s
> QUICK-FIX Reduce the number of commits during test init

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/controllers/gapi_controllers.js
1. Create new program
2. Create new Audit on the program page
3. Navigate to Audit's Info pane and click "Assign folder" link
4. Look at the screen
_Actual Result:_ JS error occurred while clicking "Assign folder" link on Audit Info pane
_Expected Result:_ no error is shown
_Note:_ The issue is reproduced if Audit tab is opened (e.g. On My Work page) and user did not use it for some time. Then user returns to Audit tab, expands Audit Info pane and clicks [Assign folder] button. In this case an error is shown.
> GGRC-2066 Audit: JS error occurred while clicking "Assign folder" link on Audit Info pane

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/mustache/audits/tree-item-attr.mustache
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
- src/ggrc/assets/mustache/directives/tree-item-attr.mustache
- src/ggrc/assets/mustache/objectives/tree-item-attr.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
- src/ggrc/assets/mustache/sections/tree-item-attr.mustache
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/javascripts/models/workflow.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
_Acceptance criteria:_
- Add column 'Last Updated by' to tree view. Column should be displayed after 'Last Updated' column.
- 'Last Updated by' should be hidden in tree view by default. User should be able to add it via 'Set visible fields' pop-up.
- 'Last Update by' column should be added for all objects that have 'Last Updated' column.
- Allow user to sort objects by 'Last Updated by'.
- Allow user to search / filter by 'Last Updated By'
> GGRC-3207/GGRC-3279 Add 'Last Updated By' column to all objects

- src/ggrc/views/__init__.py
- test/integration/ggrc/converters/test_ca_import_export.py
- test/integration/ggrc/fulltext/test_mysql.py
- test/integration/ggrc/fulltext/test_total_reindex.py
- test/integration/ggrc/snapshotter/test_indexing.py
Reindex breaks the index entries for computed attributes. So to fix
those we should reindex computed attributes as well. The easiest way to
do that is to trigger compute attributes background task for all
attributes.
> GGRC-2922 Compute attributes after each full reindex

- test/selenium/bin/run_selenium.py
- test/selenium/pytest.ini
- test/selenium/src/lib/decorator.py
This PR improves procedure of server waiting under docker containers to prevent issues with KOKORO's jobs running.
**Before:**
We had to wait max 60 hops (secs) when server will response with '200' status code, and under local env it could be good enough , but under KOKORO's virtual complicated architecture masters, slaves... we extremely often faced issues like:
```bash
Running Test server
Running Selenium tests
Wating on server: ............................................................[Failed]
mv: cannot stat ‘./test/selenium/logs/results.xml’: No such file or directory
```
**Currently:**
We will wait max 120 hops (secs) and will use 'requests.head(environment.APP_URL).status_code ' library instead 'urllib.urlopen' and 'time_tracker' wrapper to have ability investigate approximately …
> QUICK-FIX Improve procedure of server waiting under docker containers to prevent issues with KOKORO's jobs running

- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/section.js
- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/javascripts/models/threat.js
1. Go to All objects page > Products tab
2. Open set visible fields dialog and set "Last deprecated date"
3. Look at the tree view
Actual Result: "Last deprecated date" column is not displayed in tree view for Product, Clause, Issue, Risk, Threat
Expected Result: "Last deprecated date" column should be displayed in tree view for Product, Clause, Issue, Risk, Threat
> GGRC-2794 "Last deprecated date" column is not displayed in tree view for Product, Clause, Issue, Risk, Threat 

- bower.json
- src/ggrc/assets/javascripts/entrypoints/vendor.js
**Current state of vendor entry:**
**Included only used widgets:**
**Current gzipped size:** 209.2 KB
**Short list of jquery-ui widgets:** 183.23 KB
**Result:** bundle's size reduced on ~12%
> QUICK-FIX Bundle only used widgets from jquery-ui

- src/ggrc/assets/javascripts/models/mappers/mappings-ggrc.js
2. Click 'Add Mapping Filter' button
3. Expand 'Mapped to' dropdown list with the objects
4. Select 'Reference' object
5. Click 'Search' button
*Actual Result:* 'Reference' object is displayed in Unified Mapper/Global Search
*Expected Result:* 'Reference' object should not be displayed in Unified Mapper/Global Search
> GGRC-3296 'Reference' object is displayed in Unified Mapper/Global Search

- src/ggrc/assets/javascripts/components/dropdown/dropdown.js
- src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache
- src/ggrc/assets/stylesheets/components/tree_pagination/_tree_pagination.scss
2. Click Search
3. Click '>' or '>>': is not working
Actual Result: Pagination controls are not function in Global Search/Unified Mapper
Expected Result: Pagination controls should be function in Global Search/Unified Mapper
> GGRC-3370 Pagination controls are not function in Global Search/Unified Mapper 

- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
AC1. Show 'You are about to move assessment from "Completed" to "In Progress".' message only if any attribute except person attributes are modified.
AC2. Increase the width of message and make it same as for 'Please be informed that Assignee and Verifier are the same person.' message.
> GGRC-3171 Show message on attributes modification (Edit Assessment pop-up)

- src/ggrc/assets/mustache/people/tree-item-attr.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- test/selenium/src/tests/test_audit_page.py
1. Go to My work page and open Global Search
2. Select "Programs" object and look at Manager column: is empty
3. Select "Sections" object and look at the Admin column: is empty
4. Select "People" object: Authorizations column is empty
Actual Result: Data in Admin/Manager/Authorization columns is not displayed in Global Search/Unified mapper
Expected Result: People in Admin/Manager columns should be displayed in Global Search/Unified mapper. Authorizations should be displayed in Global Search/Unified mapper
Also, People are not shown in Global Search/Unified Mapper for the following entities:
Clauses - admin column 
Assessment template - admin column 
Workflow - admin column
> GGRC-2381/2633/2224/2399 Data in Admin/Manager/Authorization columns is not displayed in Global Search/Unified mapper

- src/ggrc/assets/javascripts/components/tree/tests/tree-item-custom-attribute_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item-custom-attribute.js
1. Create CA with date type for Control ("date-1")
2. Create program and control
3. On control's Info pane fill CA with date ("date-1") type
4. Set visible field in tree view and look at date
_Actual Result:_ Date is displayed in ISO format (like YYYY-MM-DD) 
_Expected Result:_ Date should be displayed in USA format (like MM/DD/YYYY)
> GGRC-1456 Fix the formatting of the Date type CA in tree view

- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/assets/javascripts/components/csv/test/export_spec.js
- src/ggrc/assets/javascripts/plugins/ajax_extensions.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/import_export/export.mustache
- src/ggrc/assets/mustache/modals/close_buttons.mustache
- src/ggrc/assets/mustache/modals/confirm.mustache
- src/ggrc/assets/stylesheets/modules/_import-export.scss
- src/ggrc/templates/import_export/export_content.haml
- src/ggrc/views/converters.py
- src/ggrc_gdrive_integration/__init__.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_ca_import_export.py
- test/integration/ggrc/converters/test_export_csv.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/services/test_collection_post.py
- test/integration/ggrc/services/test_common.py
- test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/export_page.py
- test/selenium/src/lib/service/webui_service.py
**Includes:** https://github.com/google/ggrc-core/pull/6355
Mock-Ups: https://drive.google.com/corp/drive/folders/0B7_NYFVmb896X3lLQ3pHTktMQUk
Acceptance Criteria:
AC1. Add 'Export Format' dropdown on Export page. The dropdownd should have 2 options: 'Google Sheet' (selected by default) and CSV file.
AC2. Results should be exported in Google Sheet if user selected 'Google Sheet' export format. Google sheet should be created in default folder specified by the user in his Drive.
> GGRC-3231/GGRC-1644 FE: Update /export page. Add export to spreadsheets option

- src/ggrc/migrations/versions/20170913123343_487c94a432b9_update_assessment_template_with_status.py
- src/ggrc/models/assessment_template.py
- src/ggrc/models/audit.py
- test/integration/ggrc/converters/test_import_helpers.py
BE part only.
AC1. Add first-class attribute 'State' to Assessment Template. 
It should be a dropdown with options: Draft, Active, Deprecated.
AC2. Allow user to filter Assessment Template by state.
AC3. Allow user to import / export state for Assessment Template
> GGRC-3203/GGRC-3244 Add first-class attribute 'State' to Assessment Template

- src/ggrc/models/hooks/audit.py
Currently any DELETE request for an Audit fails with HTTP500.
1. Create a new Audit.
2. Open its Info Pane.
3. Click "Delete" button.
Expected result: the Audit is removed.
Actual result: the Audit is reported to be removed, but stays if you refresh the page.
Note: to get this actual result, please run with GAE.
> GGRC-3404 Fix audit removal

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/mustache_helpers/get_custom_attr_value_spec.js
If I go to "My Assessments", the "Due Date" column doesn't display any data. The Due Date shows up in the assessment in "Other Attributes" and I'm still able to filter by it when using Advanced Search.
See screenshot here: [^screenshot-1.png]
Due data values should display in the column and allow sorting.
Slows down ECBP workflow, requiring filtering by date through advanced search rather than being able to sort and see all the assessments at once.
The cause of issue is https://github.com/google/ggrc-core/pull/6188. It breaks displaying of custom attributes in tree-view except checkbox type.
Fix allows …
> GGRC-3386 Due Date not Displayed in Due Date Field in Assessment view

- src/ggrc/assets/stylesheets/components/object-tasks/_object-tasks.scss
Update colors of task state on info pop-up in the following way:
Assigned - grey color (#bdbdbd);
In Progress - blue color (#3369e8);
Finished - #405f77;
Declined - red (#d50f25);
Verified - green (#009925).
> GGRC-2100 Make task status color on (i) pop up consistence with other places in app

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
**Acceptance Criteria:**
**AC1.** Add first-class attribute 'State' to Assessment Template. 
It should be a dropdown with options: Draft, Active, Deprecated.
**AC2.** Allow user to filter Assessment Template by state.
**AC3.** Allow user to import / export state for Assessment Template
**Depends on** https://github.com/google/ggrc-core/pull/6420
> GGRC-3243 FE: Add first-class attribute 'State' to Assessment Template

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/factory.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_snapshots.py
This PR add parametrized test for check Assessment Templates' statuses after Audit cloning w/ them.
```Python
@pytest.fixture(scope="function")
def create_and_clone_audit_w_params_to_update(
self, request, new_program_rest, new_control_rest,
map_new_program_rest_to_new_control_rest, new_audit_rest,
new_assessment_rest, new_assessment_template_rest, new_issue_rest,
selenium
):
"""Create Audit with clonable and non clonable objects via REST API and
clone it with them via UI.
Preconditions:
- Program, Control created via REST API.
- Control mapped to Program via REST API.
- Audit created under Program via REST API.
- Assessment, Assessment Template, Issue created under Audit via REST API.
- Issue mapped to Audit via REST API.
"""
if request.param:
if isinstance(request.param, tuple): …
```
> QUICK-FIX Add parametrized test for check Assessment Templates' statuses after Audit cloning w/ them

- .eslintrc.json
Until https://github.com/google/ggrc-core/pull/6444 is merged and we update uglify-js we'll have to keep writing vars. Disabling `no-var` until then.
Adjustments:
`no-var` - we can't use let yet
`prefer-rest-params` - we can't use rest params yet
`comma-dangle` - adjusted to always-multiline because it is useful for making diffs nicer
> QUICK-FIX Adjust eslint config

- src/ggrc_workflows/migrations/versions/20170925135632_3ebe14ae9547_set_empty_next_cycle_start_date.py
Set empty next cycle start date if workflow hasn't task.
> GGRC-3349 Fix workflow patch1 migration 

- test/integration/ggrc/__init__.py
- test/integration/ggrc/models/mixins/test_autostatuschangable.py
- test/integration/ggrc/notifications/test_reminderable.py
- test/integration/ggrc/snapshotter/__init__.py
Currently this method is copy-pasted into three different places in the integration test suite.
> QUICK-FIX Unify refresh_object method

- src/ggrc_workflows/assets/javascripts/controllers/approval_workflow_controller.js
1. Go to https://ggrc-qa.appspot.com/standards/54 and click on "Submit for review" link on Standards info pane
_Actual Result:_ "Uncaught TypeError: instance.refresh is not a function" error is shown on the Standard page if click "Submit for review" 
_Expected Result:_ no error is shown if click "Submit for review" link
> GGRC-1711 Fix script error when clicking 'Submit on review' on the Standard page

- src/ggrc/assets/javascripts/components/object-list/object-list.js
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/mustache/components/object-list/object-list.mustache
- src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
2. Generate at least 2 assessments
3. Expand Info pane for one assessment and add at least 10 evidences and 10 urls
2. Open related assessment window for the second assessment 
3. Look at the ATTACHMENTS / URLS column: there is no show less/ show all link
Actual Result: Show less/ show all link for evidences and url is not displayed in Related assessments window
Expected Result: Show less/ show all link for evidences and url should be displayed in Related assessments window
> GGRC-2415 Add show less/ show all link for evidences and url in Related assessments window

- src/ggrc/templates/base_objects/_page_header.haml
1. Open Export/Import pages
2. Click on Person icon on the top right corner
3. Look at the dropdown:
_Actual Result:_ There is no "Administration" in dropdown on the Import/Export pages
_Expected Result:_ "Administration" in dropdown is displayed on the Import/Export pages
> GGRC-2275 Add 'Administration' link to user menu on the Import/Export pages

- src/ggrc/converters/handlers/related_person.py
This PR makes sure that the Relationship's fields are populated correctly.
> QUICK-FIX Use ORM mappings for Relationship in Person handler

- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/mustache/people/tree-item-attr.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
 1. Create one time workflow 
2. Go to Peoples tab and look at the tree view 
Actual Result: Workflow Owner except Workflow manager is displayed 
Expected Result: Workflow manager is displayed in Peoples tab on the Workflow page
> GGRC-2018/2420 Workflow Owner except Workflow manager is displayed in Peoples tab on the Workflow page

- .gitignore
- README.md
- docker-compose.override.yml.example
This PR is based on my comments in https://github.com/google/ggrc-core/pull/6433. I believe it's a clean and easy way to allow developers to use GAPI keys on local development machines.
I have also included instructions on how to set up the keys to our README.
> QUICK-FIX Make it easier to add GAPI keys for local development

- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_export_audit.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/test_csvs/assessment_full_no_warnings.csv
- test/integration/ggrc/test_csvs/assessment_update_intermediate.csv
- test/integration/ggrc/test_csvs/assessment_with_warnings_and_errors.csv
This rename is required to display "map:"/"unmap:" columns both Snapshot and Snapshottable original objects for Issues.
> GGRC-3306 Rename "map:{}" to "map:{} versions" for Snapshots

- src/ggrc/assets/stylesheets/_colors.scss
Change color of Top Navigation line to brown for:
- Audit;
- Assessment.
**Mock-Ups:** https://drive.google.com/corp/drive/folders/0B65BmaCGVTRwYUFCVm92MklfbEU
> GGRC-3382 Top Navigation line: update orange color as it's too bright

- src/ggrc/services/__init__.py
- src/ggrc/services/assessment_resource.py
This PR makes it possible to fetch all assesment related information with a single get request to
`/api/assessments/xyz/related_objects`
~Depends on https://github.com/google/ggrc-core/pull/6316~
~Only the last commit here belongs to this PR, but reviewer can decide to merge this with all commits and close the related PR.~
> GGRC-3198 Add a new endpoint for assessment related object optimization

- Dockerfile
- bin/create_apisearch_dump
- bin/db_reset
- provision/docker/my.cnf
Using usernames and passwords in cli shows a warning when resetting the
database and the safer option is to have those in a config file. With
this change we can now omit -u and -p flags on all mysql commands.
> QUICK-FIX Remove username and password from mysql commands

- test/unit/ggrc/models/test_slugs.py
This PR fixes a typo from the tests in https://github.com/google/ggrc-core/pull/6501
> QUICK-FIX Fix slug prefix tests

- src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache
How to reproduce:
1. Go to My Work page > Assessments tab
2. Set view 25 items per page from the top pagination dropdown
3. Set view 50 items per page from the bottom pagination dropdown
4. Look at the pagination top dropdown: shows different settings
> GGRC-2199 Request to view more than 10 assessments per page

- src/ggrc/query/my_objects.py
- test/integration/ggrc/services/test_query/test_owned.py
The check for "Admin" is excessive because there is another query for all ACRoles with "my_work" set.
> QUICK-FIX Remove duplicate ACL check from my_work

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/constants/url.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/element/tree_view.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/factory.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest/template/issue.json
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_objective.py
- test/selenium/src/tests/test_snapshots.py
This PR redesigns test-suite and extends tests related to objects mapping according to new standalone Issue object.
**TODO:**
**Redesign and extend the next tests as a part of future PRs:**
- test_mapping_of_objects_to_snapshots_via_map_btn
- test_mapping_of_objects_to_snapshots_via_tree_view
- test_availability_mapping_of_objects_to_snapshotable_objs
> QUICK-FIX Redesign test-suite and extend tests related to objects mapping according to new standalone Issue object

- bin/jenkins/functions.sh
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/value_aliases.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_audit_page.py
Test to check ability to create object dashboards using global custom attributes.
Steps:
- Create 'Dashboard' GCAs for object.
- Fill CAs with urls
- Check if 'Dashboard' tab exist.
- Navigate to 'Dashboard' tab.
- Check only right filled CA values displayed on the tab.
> QUICK-FIX Test "add dashboard through the 'Dashboard' GCA"

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/js_specs/mustache_helpers/get_default_attr_value_spec.js
AC1. Add 'Archived' checkbox on 'Set visible fields for <object>' popover.
AC2. If user selects 'Archived' checkbox, then display 'Archived' column in tree view.
AC3. 'Archived' column should be hidden by default.
AC4. If Audit / Assessment is archived than, it has 'true' value in 'Archived' column.
AC5. If Audit / Assessment is not archived OR unarchived than, it has 'false' value in 'Archived' column.
Make changes for the objects:
- Audit;
- Assessment.
Make changes on the all pages that have tree view for Audit and Assessment. Currently they are:
- Global search;
- Audit page - Assessments tab
- <snapshottable object> page - Audit tab.
- My Assessments page;
- Assessment page - Audit tab.
- Issue page - Audit tab;
- Program page - Audit tab;
- Person page - Audit …
> GGRC-2318 Display 'Archived' column for Audit and Assessment 

- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
'Need Verification for tasks' need to be disabled if workflow is Active only.
Can be merged only after
#6349
> GGRC-3240 'Need Verification for tasks?' should be enabled for non-activated workflow on front-end 

- src/ggrc/models/reflection.py
- src/ggrc/utils/rules.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/unit/ggrc/utils/test_rules.py
Split map/unmap rules into explicit settings for direct mapping, direct unmapping, snapshot mapping to avoid handling it in consumer code.
> GGRC-3473 Refactor mapping rules

- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
1. Create one time wf
2. In Setup tab add task to task group and map any object to task group
4. Go to Active Cycles tab, expand sublevel with task
5. Expand fourth level to see mappings for task
Actual Result: Mappings for tasks are not shown in Active Cycles tab
Expected Result: Add fourth sublevel to see mappings for tasks. Mappings for tasks should be shown in Active Cycles tab
> GGRC-2031 Mappings for tasks are not shown in Active Cycles tab

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/controllers/tests/summary_widget_controller_spec.js
- src/ggrc/assets/javascripts/modules/widget_descriptor.js
- src/ggrc/assets/javascripts/modules/widget_list.js
Since we have moved how we do performance optimizations, we have to update the frontend
the audit summary page is no longer as fast as it should be because we moved the query optimization to custom endpoint
/api/audits/x/summary
We have to update the frontend to use that endpoint instead of the /query api.
> GGRC-3368 Fetch data for audit summary graph with custom endpoint

- src/ggrc_workflows/migrations/utils/wf_date_updater.py
- src/ggrc_workflows/migrations/versions/20170926125029_3ea1293a93bb_update_monthly_wfs.py
- src/ggrc_workflows/migrations/versions/20170927132542_ab76b910268_set_valid_start_date_and_end_dates_for_.py
- src/ggrc_workflows/migrations/versions/20170927171105_564555de4abb_set_valid_start_date_and_end_dates_for_.py
- src/ggrc_workflows/migrations/versions/20170928103322_4131bd4a8a4d_set_valid_start_date_and_end_dates_for_.py
*ISSUE 1*
After migration tasks dates inside one cycle were mixed-up.
I. Workflow Setup (before migration):
TASK1: 4-5
TASK2: 7-11
II. Migration was launched, for example, on 6 September 2017.
III. Workflow Setup (after migration):
*Expected result:*
TASK1: 4 Sep, 2017 - 5 Sep, 2017
TASK2: 7 Sep,2017 - 11 Sep, 2017
*Actual Result:*
*TASK1: 4 Oct, 2017 - 5 Oct, 2017*
TASK2: 7 Sep,2017 - 11 Sep, 2017
*ISSUE 2*
After migration, manually started cycles were not taken into consideration:
I. Workflow Setup (before migration):
TASK1: 4-5
TASK2: 7-11
II User manually starts a cycle (before migration).
III. Migration was launched, for example, on 6 September 2017.
IV. Workflow Setup (after migration):
*Expected result:*
TASK1: 4 Oct, 2017 - 5 Oct, 2017
TASK2: 7 Oct,2017 - 11 Oct, 2017
*Actual …
> GGRC-3435,3457,3458,3459,3460,3474 FIx task start dates and end dates for WF after migration

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/tests/test_audit_page.py
This PR depends on #6546 and contains 1 parametrized test which comprising 5 tests of checking Audit's statuses under cloning procedure.
```Python
@pytest.mark.smoke_tests
@pytest.mark.cloning
@pytest.mark.parametrize(
"create_and_clone_audit_w_params_to_update",
[("new_audit_rest", {"status": AuditStates.PLANNED}),
("new_audit_rest", {"status": AuditStates.IN_PROGRESS}),
("new_audit_rest", {"status": AuditStates.MANAGER_REVIEW}),
("new_audit_rest", {"status": AuditStates.READY_FOR_EXT_REVIEW}),
("new_audit_rest", {"status": AuditStates.COMPLETED})],
ids=["Audit statuses: 'Planned' - 'Planned'",
"Audit statuses: 'In Progress' - 'Planned'",
"Audit statuses: 'Manager Review' - 'Planned'",
"Audit statuses: 'Ready for External Review' - 'Planned'",
"Audit statuses: 'Completed' - 'Planned'"], …
```
> QUICK-FIX Add tests of checking all possible Audit's statuses under cloning

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/controllers/gapi_controllers.js
- src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
- src/ggrc_gdrive_integration/assets/javascripts/utils/gdrive-picker-utils.js
1. Have audit with no folder assigned
2. Create Assessment and expand Assessment info pane
3. Click 'Attach' button: window to attach evidence file is not shown up
4. Click 'Attach' button once again: window appeared
To Reviewer:
The actual problem here is that the old code was overwriting OAuth promise in pending state and creating a new OAuth promise which led to such a weird behavior of the button and appearing of the second picker modal after the file selection.
> GGRC-3427 Fix GDrive picker not opening on the first click on Attach button

- .eslintrc.json
Some of pull requests ( for example GGRC-1783 ) are blocked by newly introduced ESLint rule "no-invalid-this".
Some places of the code use implicit binding of "this" which are normal use cases.
For example: 
1) CanJS validate API implicitly binds validator's "this" to the validated instance.
__src/ggrc/assets/javascripts/models/assessment.js__
```
this.validate(
'validate_creator',
function () {
if (!this.validate_creator) {
return 'You need to specify at least one creator';
}
}
);
```
2) Some places use lodash's debounce function.
__src/ggrc/assets/javascripts/controllers/dashboard_controller.js__
```
'{window} resize': _.debounce(function (el, ev) {
this.show_hide_titles();
}, 100),
```
and adding new code requires constant search for workarounds which will add unnecessary complexity to …
> QUICK-FIX Turn-off eslint "no-invalid-this" rule

- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache
**HIGH LEVEL REQUIREMENTS**
1. Add 'Attachments' field on:
- 'Audit info' tab on Audit page.
- Audit info pane.
Note: User should not be able to attach docs during Audit creation (new / edit Audit modal pop-up)
2. 'Attachment' field should function in the same way as 'Evidence' field for Assessment:
User should be able to make multiple attachments.
If user has EDIT rights for an object, then he should be able to delete already attached files.
**ACCEPTANCE CRITERIA - ADD FOLDER**
_AC1_. ATTACHMENT field should be displayed on:
- Add / Edit Audit modal pop-up;
- Audit info pane / page.
_AC2_. ASSIGN FOLDER button should be displayed for ATTACHMENT field by default on:
- Add / Edit Audit modal pop-up;
- Audit info pane / page.
_AC3_. On clicking ASSIGN FOLDER button, SELECT FOLDER modal …
> GGRC-2120 Include attachment for audits

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/js_specs/models/assessment_template_spec.js
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/components/flexbox-layout/_flexbox-layout.scss
Add info message for Default Assignee field that should inform that if user selects role optional for an object in Default Assignee dropdown AND such role will be missing for an auditable object, then generated Assessment for such object will be assigned to Internal Audit Lead.
Roles that are optional for snapshottable objects:
▪	Principal Assignee;
▪	Secondary Assignee;
▪	Primary Contact;
▪	Secondary Contact.
▪	Auditors
> GGRC-2203 Add message regarding Default Assignee on Assessment Template

- src/ggrc/migrations/utils/url_util.py
The migration that migrates urls fails on a new cloud sql instance, but
since a fresh instance does not contain any data (and all of our db
instances were already migrated) it is safe to skip migrating the data.
The original migration fails with:
```
sqlalchemy.exc.OperationalError: (OperationalError) (1787, 'When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, the statements CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can be executed in a non-transactional context only, and require that AUTOCOMMIT = 1. These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.') '
CREATE TEMPORARY TABLE temp_url (
id int(11) NOT NULL AUTO_INCREMENT,
object_id int(11) NOT NULL,
url varchar(250) NOT NULL,
modified_by_id …
```
> QUICK-FIX Fix migrations on a fresh cloud sql mysql 5.6 instance

- src/ggrc/converters/handlers/comments.py
- test/integration/ggrc/converters/test_import_comments.py
- test/integration/ggrc/test_csvs/import_comments.csv
- test/unit/ggrc/converters/handlers/test_comment_column_handler.py
Scope:
1. Grammar issues found by @alieh-rymasheuski: https://github.com/google/ggrc-core/pull/6482
2. Dead code removal for warnings
3. Function for splitting comments must be put outside of parse_item and fully covered with unit tests to check and document all edge cases of ;; ;; ;; a;;;b etc.
4. user can add empty comment - comment1;; ;;comment2;;
5. Leading/ trailing spaces are not ignored
> GGRC-3506 Import of comments: address PR comments

- package.json
Build fails on in all environments.
1. Rebuild container or update npm packages.
2. Run karma tests
The version of momentjs library was not locked down and it was automatically updated to the 2.19.0 which brought the issue ( https://github.com/moment/moment/issues/4216 )
Locking down the momentjs version to previous one solves the issue.
> GGRC-3573 Force old version of momentjs which not breaks the build process

- bin/release/tag_current_release.sh
This PR contains two upgrades to our tag creation script that @IlyaTsupryk has complained about during his tag creation:
1. If `/bin/sh` is really `sh` and not a symlink to `bash`, the script won't start.
2. If `master` and `HEAD` have different versions in `settings`, the tag is created with a wrong version.
`git grep -h PATTERN REF -- PATH` has identical output as `grep PATTERN PATH` so it can be safely used in its place.
The Python one-liner is now separated to keep the line lengths lower. 
No js or python code included, no tests available.
> QUICK-FIX Upgrade tag creation script

- src/ggrc/assets/javascripts/components/tree/templates/tree-item-custom-attribute.mustache
- src/ggrc/assets/javascripts/components/tree/tests/tree-item-custom-attribute_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item-custom-attribute.js
Clean up code for displaying custom attribute values in tree view. Fix performance issue (loop over CAV on Mustache-view).
1) Create different types of custom attributes (Text, Rich Text, Dropdown, Date, Checkbox, Map:Person) for different types of objects (at least for Assessment and one non-assessment object).
2) Open objects list tab on Dashboard and make these fields visible/invisible in tree view.
3) Open Info pin on objects list tab and try to update custom attribute.
Expected result: custom attributes should be loaded and refreshed correctly in tree view on 2 and 3 steps.
This PR aims solve 2 issues: make code for displaying custom attributes more reliable and fix performance issue caused by redundant loops over all custom attribute values. The proposed solution comprises the …
> GGRC-3411: Clean up function to display custom attribute values

- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
- src/ggrc/assets/javascripts/components/object-mapper/tests/object-mapper_spec.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/controllers/tests/mapper_spec.js
Object-mapped is initialized with page instance id.
In this case id should be null.
Precondition:
1. Have audit with created Issue
1. On the audit page Invoke New Assessment modal window
2. Click Map objects button
3. Select object type 'Issues' 
4. Click Search 
5. Look at the Search results: Issues that are not mapped to Assessment are shown up as mapped
*Actual Result:* In the new assessment modal Issues are displayed in Unified mapper as already mapped 
*Expected Result:* Issues should not be shown as mapped in Unified mapper in the new assessment modal
Actually the bug is regression caused by splitting unified mapper into 3 components.
In some cases there is`is_new` flag that indicates that id should be null.
> GGRC-3564 In the new assessment modal Issues are displayed in Unified mapper as already mapped 

- src/ggrc/assets/javascripts/plugins/autocomplete.js
- src/ggrc_workflows/assets/assets.yaml
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/javascripts/models/tests/CycleTaskGroupObjectTask_model_spec.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/autocomplete_result.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/extended_info.mustache
AC1. Add 'Task Group' field on 'Add/Edit Cycle Task' pop-up. Task Group field should be a text field with autosuggest. 
Autosuggest should contain:
a) all tasks groups for a particular workflow selected in 'Active Workflow' field - if task is created out of Workflow (My Tasks page, Create a task for an object, All Objects - Tasks).
b) all tasks groups for a particular workflow in which the task is created (Workflow page - Active Cycles).
AC2. 'Task Group' field should be mandatory. Error message 'Cannot be blank'.
AC3. 'Task Group' field should be cleaned up if user deletes Active Cycle (case when task is created out of Workflow page).
AC4. 'Task Group' field should be editable.
AC5. 'Task Group' should be empty by default.
AC6. 'Task Group' should be disabled until user selects an active …
> GGRC-3338 Add 'Task Group' field on 'Add/Edit Cycle Task' pop-up

- src/ggrc/views/cron.py
Fixes this error on ggrc-qa:
```
Failed on sending notification (/base/data/home/apps/s~ggrc-qa/1.404581647653141798/ggrc/views/cron.py:20)
File "/base/data/home/apps/s~ggrc-qa/1.404581647653141798/ggrc/views/cron.py", line 17, in send_error_notification
user_email = common.getAppEngineEmail()
AttributeError: 'module' object has no attribute 'getAppEngineEmail'
```
> GGRC-3583 Fix called function name

- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
Manager names are not getting cut off in tree view
1. Create a program 'program1'
2. On the program Info page in Peoples tab map at least 5 user's and grant them 'Program manager' role
3. Go to the My work page > Programs tab
4. Look at the Manager column in the tree view of the 'program1': Manager names are not cut off
**Actual Result:** Manager names are not getting cut off in tree view
**Expected Result:** Manager names should be cut off in tree view
Text-overflow css property doesn't work with block elements. Use inline tags.
> GGRC-3578 Cut off program managers list in tree view

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-control-related-objects.mustache
- src/ggrc/assets/mustache/custom_attributes/info.mustache
1. Have GCA with any type (e.g. 'Rich text') for controls, objectives, regulations
2. Create a program
3. On the program info page map to program control, objective, regulation with value in GCA field
4. Map objective and regulation to control
5. Create an audit > Go to the audit info page
6. Generate assessment based on the control snapshot
7. Navigate to Assessment Info pane and open Control popup
8. Expand "SHOW RELATED OBJECTIVES' and 'SHOW RELATED REGULATIONS'
9. Hover over GCA field: edit icon is shown
_Actual Result_: If hover over GCA fields in Control popup on the Assessment Info pane, edit icon is shown
_Expected Result_: If hover over GCA fields in Control popup on the Assessment Info pane, edit icon should not be shown
> GGRC-3579 If hover over GCA fields in Control popup on the Assessment Info pane, edit icon is shown

- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- test/selenium/src/tests/test_snapshots.py
Precondition:
created program, control, audit, assessment, issue
1. Go to assessment/issue page
2. Audit tab> open 3 bb's menu
Actual Result: There is no Export/Import controls for Audits in 3 bb's menu on the Assessment/Issue page
Expected Result: Should be Export/Import controls for Audits in 3 bb's menu on the Assessment/Issue page
Note: on the audit page open 3 bb's menu in tree view for any snapshot and look at the dropdown: is empty
> GGRC-1909 There is no Export/Import controls for Audits in 3 bb's menu on the Assessment/Issue/Audit pages

- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
- test/unit/ggrc_workflows/models/test_workflow.py
I. WORKFLOW SETUP:
Task: 29 Feb 2016 - 30 Apr 2016.
II. Workflow with 1 month repeat was activated, for example, on 28 Feb 2016.
III. GENERATED TASKS:
Cycle1: 29 Feb 2016 - 30 Apr 2016.
Actual result: Cycle2: 29 March 2016 - 30 May 2016.
Expected result: Cycle2: 31 March 2016 - 31 May 2016.
!!EXCEPTIONAL CASE:
During leap year only 29 Feb is considered as a last day of month. For example, task 28 Feb 2016 will be generated on 28 March 2016 in next cycle (in repeat every 1 month WF).
During non-leap year 28 Feb is considered as a last day of month. For example, task 28 Feb 2017 will be generated on 31 March 2017 in next cycle (in repeat every 1 month WF).
> GGRC-3478 Monthly Workflow: Consider 28, 29 of Feb and 30 of Apr, June, Sep, Nov as a last days of the month during tasks generations

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
1. Have program, control, regulation, objective mapped to program and control
2. Create and map audit to program
3. Go to Audit page
4. Generate Assessment based on the control ssnapshot
5. Expand assessment info pane and open control popup
Expected Result: Assessment control modal should show regulations first and objectives second
> GGRC-3520 Assessment control modal should show regulations first and objectives second

- src/ggrc/assets/mustache/custom_attributes/info.mustache
1. Add GCA for Program with any type (e.g. date)
2. Log as admin
3. Create a program
4. Log as Global Reader (globreader@gmail.com (engage007)
5. Open program created by admin
6. Hover over GCA field: edit icon is shown screenshot-1.png
Actual Result: Edit icon shows up for Global reader while hovering over GCA field. While editing GCA and saving a value, 'There was a problem saving' error message occurs screenshot-2.png, value is displayed in GCA field. After page refresh a value is not shown in GCA field.
Expected Result: Global Reader should have only 'Read' permissions if he is not creator of the object, program editor, program manager
NOTE: The same behavior is for Global creator with read rights.
> GGRC-3580 Edit icon shows up for Global reader while hovering over GCA field

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-control-related-objects.mustache
- src/ggrc/assets/mustache/custom_attributes/info.mustache
1. Have GCA with any type (e.g. 'Rich text') for controls, objectives, regulations
2. Create a program
3. On the program info page map to program control, objective, regulation with value in GCA field
4. Map objective and regulation to control
5. Create an audit > Go to the audit info page
6. Generate assessment based on the control snapshot
7. Navigate to Assessment Info pane and open Control popup
8. Expand "SHOW RELATED OBJECTIVES' and 'SHOW RELATED REGULATIONS'
9. Hover over GCA field: edit icon is shown
_Actual Result_: If hover over GCA fields in Control popup on the Assessment Info pane, edit icon is shown
_Expected Result_: If hover over GCA fields in Control popup on the Assessment Info pane, edit icon should not be shown
HOT-FIX of #6592
> QUICK-FIX GGRC-3579 If hover over GCA fields in Control popup on the Assessment Info pane, edit icon is shown

- src/ggrc/assets/javascripts/components/csv/csv-template.js
- src/ggrc/assets/javascripts/components/csv/test/csv-template_spec.js
Since merging https://github.com/google/ggrc-core/pull/6361 request data for import-template is not valid.
1. Go to the Import page
2. Select any type of objects, e.g. Issues
3. Click download template
*Actual Result:* Template is not downloaded. POST 400 "Export failed due to server error." is shown in console
*Expected Result:* <Object> template should be dowloaded
Change request data of export in `csv-template` component according new export logic on the BE.
> GGRC-3598 Unable to download <object> template on the Import page

- bin/release/get_pr_titles.py
The ticket list generated by `get_pr_titles` is hard to read.
Run `get_pr_titles` with parameters that list at least one PR starting with "MERGE" word.
1. "MERGE" and "BACKMERGE" (case-insensitive, same as all marks) are added to the list of "special" marks same as "DOCS" and "QUICK-FIX" (even though our guidelines don't have these documented yet, we use them heavily).
2. Ticket-like ("GGRC-some-number") marks are listed separately from all special and malformed marks.
The app is not affected, this is a standalone script.
The standalone scripts don't (and, IMO, shouldn't) have tests.
```
[arymasheuski@arymasheuski ggrc-core]$ ./bin/release/get_pr_titles.py 0.10.31-Raspberry 
From https://github.com/google/ggrc-core
* branch                release/0.10-Raspberry -> FETCH_HEAD
Username: …
```
> QUICK-FIX Cleaner ticket ids list

- src/ggrc/assets/mustache/base_objects/contacts.mustache
1. Create a program and add Primary and Secondary Contacts
2. Look at the Program info page: Primary and Secondary Contacts are not displayed
Actual Result: Primary Contacts and Secondary Contacts are not displayed on the Program Info pane/page
Expected Result: Primary Contacts and Secondary Contacts should be displayed on the Program Info pane/page
NOTE: Primary and Secondary Contacts are not displayed on the Program's Info pane as well
> GGRC-3316 Primary Contacts and Secondary Contacts are not displayed on the Program Info pane/page

- src/ggrc/assets/javascripts/components/tree/sub-tree-models.js
- src/ggrc/assets/javascripts/components/tree/templates/sub-tree-models.mustache
- src/ggrc/assets/javascripts/components/tree/tests/sub-tree-models_spec.js
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
Includes:
1) GGRC-1894 Make object type clickable in "Select child tree object type" window
2) GGRC-1895 Cannot select/deselect "Assessment template" checkbox in Select child tree object type window in Audit tab
3) Unit-tests for `sub-tree-models` component
Note: This tickets was done in scope of https://github.com/google/ggrc-core/pull/6474.
Issue: Clicking on label of object type is not checking/unchecking checkbox in sub tree filter.
GGRC-1894 Steps to reproduce:
1. Go to My objects page and select any object in HNB (e.g. Controls)
2. Hover over the first tier > gear icon> Filter sub tree
3. Click any object type to select checkbox
Actual Result: Object type is not clickable in "Select child tree object type" window
Expected Result: Object type should be clickable in "Select child tree …
> GGRC-1894/GGRC-1895 Make object type clickable in "Select child tree object type" window

- src/ggrc/assets/javascripts/components/csv/export.js
- src/ggrc/assets/javascripts/components/csv/test/export_spec.js
- src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
- src/ggrc/assets/stylesheets/modules/_import-export.scss
Local custom attributes move in new separated group
Open "EXPORT" page.
Select 'Assessments' type of export object.
Each group has separated array for storing.
> GGRC-3209 Export: Group select/deselect CA (questions)

- src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
- src/ggrc/assets/mustache/components/related-objects/related-issues.mustache
- src/ggrc/assets/stylesheets/components/form/_ggrc-form.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/modules/_log-list.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
- src/ggrc/assets/stylesheets/modules/_notifications.scss
- src/ggrc/assets/stylesheets/modules/_object-header.scss
1. Have a program, mapped control with long title, audit
2. On the audit page create assessment and map control snapshot to assessment 
3. There are UI issues on:
Tree view 
Info pane modal/page
Assessment info pane and create/edit modal
Unified mapper
Change Log
> GGRC-3091 Fix UI issues with object's long title

- bin/release/get_pr_titles.py
Since tags are on our master branch but the default base branch that is
pulled is the current release branch, user might not have the tag commit
available locally. This fix makes sure that we can use this script even
if we run it on a clean repo.
> QUICK-FIX Add fetch tag to PR titles script

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- test/selenium/src/tests/test_asmts_workflow.py
1. Have audit with control snapshot and assessment
2. Open edit assessment modal window, fill required fields and map control snapshot > Save
3. Expand Assessment Info pane
4. Look at the control section: control snapshot is not shown
**Actual Result:** After mapping snapshot to Assessment via modal window, snapshot is not displayed on the Assessment Info pane. Refresh is needed
**Expected Result:** After mapping snapshot to Assessment via modal window, snapshot should be displayed on the Assessment Info pane w/o refreshing the page
> GGRC-3154 Fix issue with updating mapped snapshots after Assessment editing

- src/ggrc/query/custom_operators.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/data_for_export_testing.csv
Problem definition:
- Primary/Secondary contacts are missing in People tab
1. Add/Change Primary or Secondary contact for the Program
2. Navigate to People tab
Actual result: Primary/Secondary contact are not shown in the list
Expected result: Primary/Secondary contact are shown in the list
3. Click Map button, and search for Primary/Secondary contact:
Primary/Secondary contact person is shown as mapped
Primary/Secondary contacts are granted an access to the object they are assigned to.
The issue:
- The issue is that persons linked over ACL are not gathered while querying over query API in custom_operators module, "related_people" query operator.
> GGRC-3214/GGRC-1253 Primary/Secondary contacts shown as mapped in the unified mapper but missing in People tab

- src/ggrc/assets/javascripts/components/datepicker/datepicker.js
- src/ggrc/assets/javascripts/components/tests/datepicker_spec.js
- src/ggrc/assets/javascripts/ggrc_base.js
- src/ggrc/assets/javascripts/tests/ggrc_date_spec.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
Save & Close button is disabled on Create New Task modal until Start Date or Due Date are not reselected
1. Navigate on Setup tab of any active Workflow
2. Open Create New Task modal
3. Fill mandatary fields in.
Actual Result: Save & Close button is disabled.
Expected Result: Save and Close button should be active if mandatory fields are filled in New Task modal window
Actual cause of issue - issue in datepicker component that converts one of dates to string and leaves another one as Date object (This bug was introduced quite long ago and fixing it via converting string representation to Date object in every place in datepicker component might be very risky and cause a lot of regressions). Proposed solution - try to get Date representation of start_date and end_date properties in …
> GGRC-755: Save and Close button is disabled if mandatory fields are filled in New Task modal window

- src/ggrc/assets/javascripts/apps/business_objects.js
- src/ggrc/assets/javascripts/components/snapshotter/scope-update.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/tests/inner_navigation_controller_spec.js
- src/ggrc/assets/javascripts/modules/widget_descriptor.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/dashboard/internav_list.mustache
**ISSUE 1**
1. Go to any page, for example 'All Objects'.
2. Change the size of the page.
_Actual result_: names of the tabs are changed from icons with inscription into just icons.
_Expected result_: Name of the tabs should always be displayed in full format (icon + inscription) on all pages except Audit and My Assessments
**ISSUE2.**
1. Go to any page, for example issue page https://ggrc-qa.appspot.com/issues/171.
2. Change the size of the page.
_Actual result_: For a pair of secs all tabs are displayed.
_Expected result_: 
option1: only tabs with actually mapped objects to issue should be displayed right away.
option 2: only  tab should be displayed until all other mappings are loaded.
**ISSUE1**: Do not trigger "adjust" function all instance's types except of 'Audit".
**ISSUE2**: Do …
> GGRC-3510 Do not collapse line with tabs on All Objects page

- src/ggrc/assets/javascripts/components/tabs/tab-panel.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/tabs/tab-panel.mustache
Related assessments are loading each time when user open the corresponding tab on Assessment Info pane
1. Open Assessment tab
2. Move on `Related Assessments` tab
3. Watch on the spinner
4. Move on any other tab
5. Repeat point `2`
6. Watch on the spinner again
Cache current content of `Related Assessments` tab when user move on other tabs
> GGRC-3639 Prevent reloading of related assessments when navigating to other tabs and back

- docs/source/conf.py
- src/docbuilder/descriptors/service.py
- src/docbuilder/templates/package/services.mako
- src/ggrc/__init__.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_gdrive_integration/__init__.py
- src/ggrc_risk_assessments/__init__.py
- src/ggrc_risks/__init__.py
- src/ggrc_workflows/__init__.py
This PR adds json examples to our endpoints. It's was implemented in a rush way before a demo so it's not the best. Ideally instead of having the `MOCK_DATA` dict we should find out the type of each attribute and create json values based on the type instead of the attribute name.
> DOCS List json attributes for all services

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/tests/inner_navigation_controller_spec.js
- src/ggrc/assets/mustache/dashboard/internav_list.mustache
Go to Audit page a and look at the tabs.
Expected:
1. Left part should always be expanded (icons + inscriptions). (as on screenshot - it should never get collapsed) (sample - https://ggrc-qa.appspot.com/audits/4229)
2. Right part should always be collapsed (only icons).
3. For Audit - Audit Summary should be default tab
> GGRC-3635 Improve Audit tab line

- src/ggrc/assets/javascripts/components/tree/templates/tree-item-custom-attribute.mustache
- src/ggrc/assets/javascripts/components/tree/templates/tree-item.mustache
- src/ggrc/assets/javascripts/components/tree/tree-people-list-field.js
- src/ggrc/assets/javascripts/components/tree/tree-people-with-role-list-field.js
- src/ggrc/assets/javascripts/components/view-models/tree-people-base-vm.js
- src/ggrc/assets/mustache/audits/tree-item-attr.mustache
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
- src/ggrc/assets/mustache/directives/tree-item-attr.mustache
- src/ggrc/assets/mustache/objectives/tree-item-attr.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
- src/ggrc/assets/mustache/sections/tree-item-attr.mustache
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tree-item-attr.mustache
- src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
Currently we make additional request on `/api/people` endpoint in order to show people from assignees lists (Creators, Verifiers etc.) in tree view on Assessment tab
1. Open Assessment tab
2. Add `Verifiers` , `Creators' and/or `Assignees` columns to treeview
3. Look into `Network` tab in Chrome DevTool
Assessment instance already have all necessary data for it (in assignees field), because we need to show just an email and  in this case we avoid extra request on `/api/people/` endpoint in order to show assignees lists on Assessment tab.
> GGRC-3576 Speed up render of people assignees lists in tree view

- src/ggrc/fulltext/attributes.py
The point of this PR is to fix error message that appears when invalid date format is used in search.
See screenshots:
Add spaces and "." to message
> GGRC-2862 Make a better error message while date format is wrong

- src/ggrc/assets/javascripts/models/display_prefs.js
- src/ggrc/assets/js_specs/models/display_prefs_spec.js
Acceptance Criteria
AC1. State filter selection should be remembered for combination 'object + user' across all the pages in the app.
For example, user specifies to show only 'Active' Controls on 'All Objects' page.
That means that only 'Active' controls on all pages (My Work, All Objects, 'Contols' tab on any object page)
> GGRC-3206 Remember 'State' filter selection for combination 'user+object' across all the pages

- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/javascripts/models/threat.js
GCA cannot be updated for Risks and Threats.
1. Have GCA with any type for Risks, Threats
2. Go to My work page
3. Threats tab > Expand Threats Info pane
4. Edit GCA with date type and save
5. Look at the screen: 'Save' message is displayed but value is not saved
Actual Result: Editing of GCA doesn't work
Expected Result: Editing of GCA should work for all objects across the app
Actual cause of issue - custom_attribute_values stores the whole objects for Risks and Threats(not Stubs). That causes reseting GCA value on back-end.
Solution - declare custom_attribute_values as 'CMS.Models.CustomAttributeValue.stubs'.
Unit tests are not applicable for this issue.
> GGRC-3249: Fix issue with editing GCA for Risks and Threats

- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
Rich text formatting (bullets) was not saved/displayed on an assessment comment. I tried to enter bullets into a comment and they are not displayed in the Read More/Read Less versions after they are added.
> GGRC-3216 Display bulleted list in comments correctly

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-attribute.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/mustache/components/advanced-search/advanced-search-filter-attribute.mustache
- src/ggrc/assets/mustache/components/object-generator/object-generator.mustache
- src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
- src/ggrc/assets/mustache/components/object-search/object-search.mustache
Advanced Search should work on pressing Enter.
Advanced search modals:
- Object filter on tree view
- Global search
- Map object 
- Generate assessment
Handle pressing enter on every advanced search component. Call the same handler as on 'Search' button click.
> GGRC-3480 Start search on pressing enter in advanced search modals

- src/ggrc_workflows/assets/javascripts/models/tests/approval-workflow-model-helper_spec.js
Cover CMS.ModelHelpers.ApprovalWorkflow with unit tests.
NOTE: should be merged after [PR#6587](https://github.com/google/ggrc-core/pull/6587).
> GGRC-3591: FE - Cover CMS.ModelHelpers.ApprovalWorkflow with unit tests

- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
In state-utils.js 'AssessmentTemplate' is present in two lists of models with different sets of states. It should be removed from second list with no states. It was missed in the next PR: https://github.com/google/ggrc-core/pull/6436/files#diff-750fc82dad94c4cd40fb9be8b5698f7bR40 .
Remove "AssessmentTemplate" from list of objects without states.
> QUICK-FIX Remove "AssessmentTemplate" from list of objects without states

- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/modules/_advanced-info.scss
Different styles for labels on assessment new/edit modal.
1. Invoke new/edit Assessment modal window
2. Look at the Assessment Type, Reference url, notifications style: is old one
*Actual Result:* Old styles of fields are displayed in the New/Edit Assessment modal window
*Expected Result:* Actual style of fields should be displayed in the New/Edit Assessment modal window
*Mockups:* https://drive.google.com/corp/drive/folders/0B65BmaCGVTRwSGFRSVpheHJjcEU
Make labels font bold on assessment modal for next fields: "Assessment Title", "Reference URL".
Out of scope:
1) Add border for non-snapsot mapped objects (approved by Ksenia Koltun).
2) Remove text "No mapped objects" (approved by Ksenia Koltun).
3) Remove outline for "Hide additional fields" button.
4) Fix height of status label on …
> GGRC-3536 Old styles of fields are displayed in New/Edit Assessment modal window

- src/ggrc/assets/javascripts/components/view-models/tests/tree-item-base-vm_spec.js
- src/ggrc/assets/javascripts/components/view-models/tree-item-base-vm.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/directive_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/javascripts/models/section.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/javascripts/models/system.js
- src/ggrc/assets/javascripts/plugins/tests/utils/tree-view-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
- src/ggrc_risk_assessments/assets/javascripts/models/risk_assessment.js
- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/javascripts/models/threat.js
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
Each object should have default settings for 'Filter sub tree' filter due to the table:
https://docs.google.com/spreadsheets/d/11CHxbJZHPwD8rc9-4xCDnHbhQ4SE2SKDJcGxckuk2MQ/edit#gid=0
Specify sub_tree_view_options prop for every required model. Use it to get default filter settings for sub tree view filter.
> GGRC-3202 Set default selections for 'Filter sub tree' on tree view

- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/mustache/people/modal_content.mustache
The 'name' field should be mandatory when adding a new user into gGRC.
1. As admin User go to Administration
2. People tab > Click create a new person
3. Look at "Name" field
**Actual Result:** "Name" field is not required
**Expected Result:** "Name" field is required and marked with red star
Add non blanc validation for name property
> GGRC-1741 Make 'name' field mandatory on new user modal

- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/controllers/tests/mapper_spec.js
Unified Mapper is not shown up by default while adding a new tab after closing unified mapper by pressing ESC for Assessment object. The same behavior if open unified mapper by clicking on Map button.
Issue is reproducible only for snapshots. 
1. Have an audit with created assessment
2. Go to the assessment page
3. Click Add Tab > Controls or Map button
4. Once Unified Mapper appears press ESC on the keyboard and close Controls tab
5. Click Add tab > Objectives  or Map button
6. Look at the screen: Unified mapper is not shown up
**Actual Result:** Unified Mapper is not shown up by default while adding a new tab after click ESC
**Expected Result:** Unified Mapper should be not shown up by default while adding a new tab after click ESC
This is regression issue after #6328 changes. …
> GGRC-3641 Fix issue when unified mapper is not shown up while adding a new tab after pressing ESC

- src/ggrc/migrations/versions/20170908140544_3e7c7f3d9308_add_need_rework_status_for_assessment.py
- src/ggrc/models/assessment.py
- src/ggrc/models/mixins/statusable.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/services/test_assessments.py
- test/unit/ggrc/models/test_states.py
Add 'Rework Needed' state for Assessment.
FE should have ability to move Assessment to Rework Needed state over api 
From 'Rework Needed' state assessment can be moved only to 'In Review' or 'Completed (no verification)' state.
> GGRC-3222 BE:Add `Rework Needed` state for Assessment

- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/extended_info.mustache
1. Wrong formatting of the 'TASK GROUP *' field
2. Task Group link in popup is incorrect on My Tasks page: while clicking the link, user is redirected to My work page. Should be redirected to Workflow page.
> GGRC-3338 Fix Task Group autocomplete issues in Cycle Task modal

- Dockerfile-selenium
- docker-compose-testing.yml
Update bundle chrome - chromedriver to latest stable version for docker environment:
- chrome 62.0.3202.62;
- chromedriver 2.33.506092
Run test suite with at least 5 times runs for each particular test.
We should have last stable version of chrome to run selenium tests.
> QUICK-FIX Update docker selenium environment (chrome 62, chromedriver 2.33)

- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers/handlers.py
If an Issue is mapped to an Assessment, when you try to unmap the Audit from the Issue through the imports, the backend crashes.
1. Create an Audit.
2. Create an Assessment.
3. Raise an Issue in the Assessment.
4. Export the Issue.
5. Rename "map:Audit" to "unmap:Audit" column.
6. Import the CSV.
Actual result: the backend complains of an uncaught exception.
Expected result: a warning is shown that it is impossible to unmap the Audit.
This is a quick fix that checks the flag that blocks this unmapping before trying to unmap. The warning is not shown during dry run, and it should be addressed at some point.
The whole Issue import/export part should be covered with tests in one single PR (GGRC-3565).
> GGRC-2851 Deny unmap:Audit if Issue mapped to an Assessment/Snapshot

- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/bootstrap/tests/modal-form_spec.js
- src/ggrc/assets/javascripts/bootstrap/tests/test-template.mustache
- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/javascripts/ggrc_base.js
- src/ggrc/assets/mustache/components/assessment/attach-button.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/components/templates/gdrive_picker_launcher_upload_error.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/tests/gdrive_picker_launcher_spec.js
- src/ggrc_gdrive_integration/assets/javascripts/models/gdrive_models.js
- src/ggrc_gdrive_integration/assets/javascripts/utils/gdrive-picker-utils.js
All uploaded files should be searchable within Google Drive
This is a proper solution which covers all the edge cases which where not addressed in #6362 and it was reverted. In particular it did not cover the case of picking already uploaded and renamed file to other assessment. It was adding a suffix with the codes of the latest assessment it was attached to.
Uploaded files should be appended with the suffix which contains of the code of the instance the file is attaching to and the codes of the mapped entities (the ones that match the instance type. for example for Assessment of type Control only mapped Controls' codes will be used in the suffix).
Also, the codes are converted to the filename-safe format (lowercased, and all special character are replaced with the dash character ('-')). …
> GGRC-2196 Add suffixes to the uploaded files

- src/ggrc/models/hooks/relationship.py
- test/unit/ggrc/models/hooks/test_relationship.py
Sometimes a Relationship object gets `source_type` and `source_id` set, but `source` unset, and it breaks the optimistic hook that neither checks `if source` nor handles `AttributeError`. 
Precondition:
1. Have an audit with assigned folder and attachment
2. Create Assessment on the audit page
1. Expand Assessment Info pane
2. Attach evidence
3. Click 'Complete' button immediately to make sure both edits are submitted with a single request.
Expected result: the evidence is attached, the state is changed.
Actual result: random; some reports said the evidence is attached, but the state is unchanged.
Look before you leap. Although not very pythonic, it's how we handle broken relationships in our app.
Also there is an utility decorator that hides typical loop over …
> GGRC-3593,3595 Handle unset Relationship.source in relationship hooks

- src/ggrc/assets/javascripts/components/assessment/assessment-people.js
- src/ggrc/assets/javascripts/components/people/editable-people-group-header.js
- src/ggrc/assets/javascripts/components/people/editable-people-group.js
- src/ggrc/assets/javascripts/components/people/people-group-modal.js
- src/ggrc/assets/javascripts/components/people/templates/people-group-modal.mustache
- src/ggrc/assets/javascripts/components/people/tests/editable-people-group_spec.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control-group.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-mapping.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
- src/ggrc/assets/mustache/components/custom-roles/custom-roles.mustache
- src/ggrc/assets/mustache/components/people/editable-people-group-header.mustache
- src/ggrc/assets/mustache/components/people/editable-people-group.mustache
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/components/people-group/_people-group.scss
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/constants/regex.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/element/elements_list.py
- test/selenium/src/lib/element/tables.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
The People list, which contain a lot of people, uses a big area of page.
Open "Control" info page.
Add 10+ persons in one of Custom Roles
**If person list contains more than 4 people**:
1) _Edit mode_: show modal with "Add Person" input and list of added people items.
2) _Read mode_: show only 4 people and "See more" link. See more link should turn on "Edit" mode.
**If person list contains 1 - 4 persons:**
The People list should work as before.
> GGRC-2489 Extend Person control to show many people

- src/ggrc/converters/handlers/related_person.py
- test/integration/ggrc/converters/test_import_assessments.py
1) User imported assessment procedure update along with verifier column (empty), it updated all the assessments with none verifier - empty updates should not be allowed
2) The assessment log showed update of assessment procedure but not verifier update
Verifier is deleted from an Assessment when an empty Verifier field is imported
1. Add a verifier to an Assessment over UI
2. Export the Assessment
3. Delete the Verifier field in the csv file
4. Import the modified csv
5. Check the Verifier was deleted
We should only delete people when the imported value is valid and is not empty
Additionally fixes wrong relationship attr handling for related AssigneeTypes. When modifying with import and removing person from all the lists, relationship_attr remained empty and relationship was not deleted. …
> GGRC-3572 Imports allowing empty fields to be imported and updated. 

- src/ggrc/migrations/utils/update_acr.py
- src/ggrc/migrations/versions/20171027124751_3c095f8ad47_recover_missing_acr_mandatory_roles.py
- src/ggrc_risks/migrations/versions/20171027124743_1be0dd01f559_create_missing_risks_acr_mandatory_roles.py
1. As admin go to the Administration page > Custom Roles tab
2. Click gray triangle for Programs and look at the Custom Roles: 'Secondary Contacts' is missing
Actual Result: 'Secondary contacts' field is missed in Custom Roles for Program
Expected Result: 'Secondary contacts' field should be displayed in Custom Roles for Program and should be predefined
> GGRC-2934 'Secondary contacts' field is missed in Custom Roles for Program

- src/ggrc/login/__init__.py
- src/ggrc/rbac/__init__.py
- src/ggrc/views/__init__.py
- test/integration/ggrc_basic_permissions/test_reader.py
Our reader permission checks were disabled by mistake and thus haven't caught the admin page permission regression introduced with https://github.com/google/ggrc-core/pull/6049 (reader/editor can access admin page).
This PR fixes a few of the issues with the tests and makes sure only admins can access the admin page and some other related URLs.
Login as reader/editor and go to /admin
Since we have `@login_required` it should make sense to have `@admin_required` helper as well. The only quirk of this approach is that the functions need both login_required and admin_required. We can remove login_required, but then if the user is not logged in they won't get redirected to the login page. We could also add login_required inside admin_required.
> QUICK-FIX Fix admin page permission checks

- src/ggrc/assets/javascripts/components/tree/templates/sub-tree-item.mustache
- src/ggrc/assets/javascripts/components/tree/templates/tree-item-actions.mustache
- src/ggrc/assets/javascripts/components/tree/templates/tree-item.mustache
- src/ggrc/assets/javascripts/components/tree/tree-item-actions.js
- src/ggrc/assets/javascripts/components/view-models/tests/tree-item-base-vm_spec.js
- src/ggrc/assets/javascripts/components/view-models/tree-item-base-vm.js
When user click on the row, task list expand
when user hover over to the little "triangle button, a list populated for user to choose to "review task group detail".
- Cycle 1st level - on click on row - expand second level
- Cycle 1st level - menu - remove Filter and Expand on 1st level; add "View info" - to open info panel
- Task Group 2d level - on click on row - expand third level
- Task Group 2d level - menu - remove Filter and Expand on 1st level; add "View info" - to open info panel
- Task 3d level - leave as is - on click on row - open info panel
- Modify tree item actions to display only "view info" for cycles and groups on workflow page.
- Modify tree item base vm to show info-pane when click for cycles and groups on …
> GGRC-3335 RMC - Workflow 2.0 Testing - UX - Task group expansion

- src/ggrc_workflows/assets/javascripts/components/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
"Uncaught TypeError: Cannot read property '0' of undefined" error occurs if click dropdown Cycle Task in tree view or select 'dropdown' task type in Cycle task modal window
Case 1:
1. Go to My work page > Tasks tab
2. Click dropdown Cycle task in tree view
**Actual Result:** "Uncaught TypeError: Cannot read property '0' of undefined" error occurs if click dropdown Cycle Task in tree view
**Expected Result:** no errors should be shown while clicking first tier in tree view in Tasks tab
Case 2:
1. Go to My work page > My tasks tab
2. Invoke Edit Task modal window for any Cycle Task
3. Change task type from rich text or checkbox to dropdown
4. Look at the screen: "Uncaught TypeError: Cannot read property '0' of undefined" error occurs
**Actual Result:** "Uncaught TypeError: Cannot read …
> GGRC-3693/3695 Fix js error when open dropdown tasks in tree view

- src/ggrc/models/mixins/labeled.py
db.Enum accepts either exactly one PEP-435 compliant enumerated type or
one or more string or unicode enumeration labels. This issue broke the
build_docs command.
run `build_docs`
> GGRC-3719 Fix labeled mixing

- Makefile
We used to have a different script for building css and js, so we needed
to run build_css on dashboard.css changes. Now we have a single
build_assets script that does everything and doesn't need to be called
twice.
I have mentioned this issue in https://github.com/google/ggrc-core/pull/6565
> QUICK-FIX Make sure we only build_assets once when deploying

- src/ggrc/automapper/__init__.py
- src/ggrc/converters/base_block.py
- src/ggrc/login/__init__.py
- src/ggrc/login/appengine.py
- src/ggrc/login/common.py
- src/ggrc/login/noop.py
- src/ggrc/models/__init__.py
- src/ggrc/models/cache.py
- src/ggrc/services/common.py
- src/ggrc/utils/log_event.py
- src/ggrc/utils/user_generator.py
- src/ggrc_workflows/__init__.py
- test/integration/ggrc/services/test_user_generator.py
- test/unit/ggrc/services/test_common.py
If  /api/people post request contains
'external': True
user has to be verified via Integration Service and  added to db with Creator role. 
If user already exists in db then found user info is returned.
- Move user generation methods to a separate module. [Currently, all users trying to login are added to db. Users with emails from authorized domains are added with Creator role.]
- Implement 'find or add' method and call it from common.collection_post.
In addition, to avoid cyclic imports:
- Move log_event from services/common.py to a separate module
- Move get_cache method from services/common.py to models/cache.py
The PR depends on #6584. Please, review only 5 last commits.
> GGRC-3522 BE: Handle people creation event

- src/ggrc/assets/mustache/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
While state is changing, 'undo' button is not disabled, so if it clicked it can cause a conflict.
1. Create repeat of workflow
2. Set at least 5 tasks and Activate workflow
3. Go to Active Cycles tab
4. Expand subtree for Task Group
5. Hover over tasks first tier and quickly click start, finish, decline, verify controls to change tasks states
*Actual Result:* Conflict message is displayed while verifying cycle tasks
*Expected Result:* Conflict message should not display while verifying cycle tasks
Disable whole `cycle-task-actions` component while data is loading.
> GGRC-3547 Conflict message is displayed while verifying cycle tasks

- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
The 3bbs button will disable in snapshot with no length.
1. Have assessment with mapped snapshot
2. On the assessment info page click Add tab > e.g. Objectives
3. Once Unified mapper is displayed close it
4. Click 3 bb''s menu: empty dropdown is shown screenshot-1.png
Actual Result: 3 bb's menu button is not disabled in tab with snapshot on the assessment Info page if there is no object in tree view
Expected Result: Disable 3 bb's menu button in tab with snapshot on the assessment Info page if there is no object in tree view
Add disabled class to button if it's a snapshot and tab have no items.
> GGRC-3643 Disable 3 bb's menu button in tab with snapshot on the assessment Info page if there is no object in tree view

- src/ggrc/assets/javascripts/components/tree/get-owner-people-list.js
- src/ggrc/assets/javascripts/components/tree/templates/tree-people-list-field.mustache
- src/ggrc/assets/javascripts/components/tree/tree-people-list-field.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/view-models/tree-people-base-vm.js
- src/ggrc/assets/mustache/directives/tree-item-attr.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
- src/ggrc/assets/mustache/sections/tree-item-attr.mustache
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
- src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
From user: "Text wrapping is a little off in the assignee column because the comma doesn't stay with the first entry"
Solution: 
I had a discussion with Kseniya Koltun and she decide remove commas at all. 
Also we decide add a tooltip with maximum 5 people and phrase with number of hidden from list persons.
Go to assessment or any other tab and have more then 1 person in some people column.
> GGRC-3218 Text wrapping is unconventional for Assignee field on Assessments object

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
Issue tab is shown as icon but should displaying with title on "Audit" page.
1. On the administration page > Custom attributes tab > add GCA with text type as 'Dashboard_data_report' for Audit
2. Have an audit
3. On the Audit info page fill added GCA: insert any link, e.g. https://ggrc-qa.appspot.com > Save
4. Refresh the page
5. Look at the Issues tab screenshot-1.png
Actual Result: 'Issues' tab is displayed as icon
Expected Result: 'Issues' tab should always be expanded
Add condition which increment priorityTabs counter by one.
> GGRC-3674 'Issues' tab is displayed as icon

- src/ggrc/query/builder.py
- src/ggrc/rbac/__init__.py
- src/ggrc/rbac/permissions.py
This is a quick easy performance fix for navigting our tree views for anyone with high enough system role
to check this take a random tree view navigate left and right, and I suggest using `export GGRC_BENCHMARK=last` for log format.
> GGRC-3646 Avoid permissions loading if possible on query api requests

- src/ggrc/assets/javascripts/components/external-data-autocomplete/inline-autocomplete-wrapper.js
**Just a cosmetic change**
The import operation is excess here, because `external-data-autocomplete` has been imported in `src/ggrc/assets/javascripts/entrypoints/dashboard/index.js` file.
There is no way to test - it's just a cosmetic change.
The import left here by mistake during development.
> QUICK-FIX Remove excess import in inline-autocomplete-wrapper.js

- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/models/mixins/__init__.py
- test/integration/ggrc/services/test_collection_post.py
modified_by_id field is updated not for a newly created person but for a creator. updated_at field is updated automatically when object is set or modified: `onupdate=db.text('current_timestamp')`
1. Create a person
2. Check modified_by_id of a newly created person
Result: it is None
Expected result: it is equal to  creator id
3. Check creator modified_by_id
Result: it is equal to a newly created person id
Expected result: 
It is not changed
For some unknown reason 
`obj.modified_by = get_current_user()`
updates current user field instead of obj field if obj is instance of Person. It looks like a bug in SQLAlchemy.
The statement is replaced by `obj.modified_by_id = get_current_user_id()` to change modified_by_id field without invoking SQLAlchemy relationships processing.
> GGRC-3556 BE updates 'updated_at' field when there were no changes

- src/ggrc/assets/javascripts/components/base-objects/pagination.js
- src/ggrc/assets/javascripts/components/base-objects/tests/pagination_spec.js
Pagination controls are not function in Global Search/Unified Mapper
2. Click Search
3. Click '>' or '>>': is not working
**Actual Result:** Pagination controls are not function in Global Search/Unified Mapper
**Expected Result:** Pagination controls should be function in Global Search/Unified Mapper
Looks like it's regression issue after #6559 PR. CanJs select sets pageSize after re rendering.
> GGRC-3694 Pagination controls are not function in Global Search/Unified Mapper

- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
'Show Verify button next to tasks' checkbox should be editable in edit modal for Draft Workflows only.
1. Create monthly workflow, 'Show Verify button next to tasks' set to "true"
2. On the workflow info page add task in the setup tab
4. At the Active Cycles tab verify task
5. On the workflow info page invoke Edit workflow modal window
6. Edit 'need verification' field: success
7. Click save and close button
Actual Result: 'Need verification' field is editable if workflow is Inactive
Expected Result: 'Need verification' field should not be editable if workflow is Active, Inactive, Active Archived, Inactive Archived
Minor changes on Workflow edit modal.
> GGRC-3581: Allow edit Need Verification flag for Draft WF only

- src/ggrc_workflows/migrations/versions/20171030074846_456b7edf6027_remove_contact_id.py
~~On hold, till #6587 is deployed on prod.~~
Need to remove obsolete contact columns from tasks' and cycle tasks' tables.
This is just a migration needed to remove obsolete columns contact_id and secondary_contact_id from tasks and cycle tasks tables. Because these fields are already removed from the models previously and the columns in the database were left for data backup.
1. Go to the database
2. describe task_group_tasks;/ describe cycle_task_group_object_tasks;
3. check these tables don't have 'contact_id' and 'secondary_contact_id' columns
Solution: columns should be removed with a migration.
For downgrade - should recover the columns and all related indexes and constraints. There is no need to recover data from the ICL in this migration since we have a two step process for …
> GGRC-3616 Remove contact_id from tasks and cycle tasks

- src/ggrc/integrations/client.py
- src/ggrc/services/suggest.py
- test/integration/ggrc/services/test_suggest.py
- test/unit/ggrc/integrations/test_client.py
Currently /people/suggest doesn't process prefixes with spaces correctly. If user, for instance, types 'Jhon Sn' in autocomplete component, the user 'Jhon Snow' won't be found. 
It is needed to split prefix on tokens before making request to Integration Service.
> GGRC-3741 BE: Update /people/suggest to process autocomplete requests with spaces

- src/ggrc_risks/__init__.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/notification/__init__.py
- src/ggrc_workflows/services/common.py
For patch operation required to have bulk handling for status change operation and handling status propagation. 
Try to change status over api put on cycle task and group views. It should work the same.
Change contract for status _change signal. 
The arguments should be the list of context objects (instance, new_status, old_status).
Using context instance is required because of code debt. 
This should be changed after removing all flushes.  
Change each status_change handler to use list of contexts. 
Change contract for function update_cycle_task_object_task_parent_state. It should take list of objects.
Change contract for function update_cycle_task_group_parent_state. It should take list of objects.
Remove unused signal status_change from ggrc_risk app part.
> GGRC-3684 Refactor status_change signal for work with list of objects 

- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
User unable to change 'Need Verification' flag while creating Workflow
1. Invoke New workflow modal window
2. Hover over 'Show Verify button next to tasks' checkbox: is disabled
Actual Result: 'Need Verification' checkbox is disabled in New workflow modal window
Expected Result: 'Need Verification' checkbox should not be disabled in New workflow modal window
Small fix on modal view: check whether status exists for current instance.
> GGRC-3755: Enable Need Verification checkbox on create WF modal

- src/ggrc/assets/javascripts/controllers/tests/tree_view_controller_spec.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
1) Go to Admin dashboard/Custom attributes (for ex. Assessments' CAs)
2) Edit then Delete the topmost GCA. System asks if you really want to delete the CA and it's name. Delete it. Message is shown that it's been successfully deleted.
3) CA is still shown on the dashboard
4) Try to delete it again. Pop-up window now offers you to delete a CA with another name. Delete it. Message is shown that it's been successfully deleted. (CA with that "another" name)
5) But the CA it still on the UI, despite some CA is gone from the db. (Checked it, some CA really is being deleted)
6) On the next turn you see that "second" CA name again, and again some CA is deleted from the db.
> GGRC-3099 Remove just deleted custom attributes from the admin dashboard

- src/ggrc/assets/mustache/base_objects/extended_info.mustache
- src/ggrc/assets/mustache/people/autocomplete_result.mustache
- src/ggrc/assets/mustache/people/search_result.mustache
Redundant popover displayed while user hovers over person in autocomplete component and hovers over person in LHN.
1. Invoke New Assessment modal window
2. Type user's name
3. Hover over user's name from autosuggest
Actual Result: Info Popup appears while hovering over user's account
Expected Result: No info popup should show up while hovering over user's account
Solution: Remove info popup for person for all objects across the application:
1. LHN while hovering over People in People/Groups section
2. Autocomplete - Info pane/page/New modal window/Edit modal window
1) Remove show-extended class for person's autocomplete result component (it triggers CMS.Controllers.LHN_Tooltips event handler).
2) Cleanup extended_info view - remove redundant checks on object type cause it shouldn't be …
> GGRC-3692: Remove info popup on hover Person object

- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls.js
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-control-related-objects.mustache
Wrong links to Objectives and Regulations in Control's popup on the Assessment Info pane.
'Not found.' is shown while following Objective or Regulation's link via Control's popup on the Assessment Info pane
1. Have audit with control snapshot with mapped Objective and Regulation to it
2. Go to audit page and generate Assessment based on control snapshot
3. Expand Assessment Info pane and open Control popup
4. Click Objective's or Regulation's link: 'Not found' is displayed
**Actual Result:** 'Not found.' is shown while following Objective's or Regulation's link via Control's popup on the Assessment Info pane
**Expected Result:** If user clicks Objective's or Regulation's link in Control's popup, Info page of original Objective/Regulation should be displayed
Regression issue - #6646 PR. …
> GGRC-3165  Wrong links to Objectives and Regulations in Control's popup on the Assessment Info pane.

- src/ggrc/assets/stylesheets/modules/_modal.scss
Comparison modal is broken for objects with long titles
1. Have program, control with long title, audit
2. On the program page update control (e.g. description)
3. Refresh audit page > Control's tab
4. Open comparison window by clicking "Get the latest version"
5. Look at the comparison window
Reduce .info sections width in Comparison modal to appropriate value (take into account paddings).
> GGRC-3691: Fix layout issue in Comparison modal

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/services/resource.py
- test/integration/ggrc_workflows/test_api_calls.py
It's required to have status propagation to cycle task instances upper in cycle tree. Workflow of that procedure should be the same as propagation for single task instances.  
Update cycle task instances status over bulk update/patch and check if propagation works correctly for each possible cases of combination cycle task statuses and workflow is_verification_needed flags. 
1) send status_change signal on bulk_update action 
2) update cycle task parent state if all works correctly 
3) move cycle to history if it's done 
4) move workflow inactive if all cycles moved to history
> GGRC-3736 Status propagation over task tree

- test/selenium/src/tests/test_snapshots.py
We got unexpected fail of test **'test_bulk_update_audit_objects_to_latest_ver'** due to approach of rendering tree view items after audit bulk update procedure was changed and order can be different.
> QUICK-FIX Add sorting for objects got from tree view after audit bulk update

- src/ggrc/query/custom_operators.py
- test/integration/ggrc/services/test_query/test_in.py
The frontend has to emulate IN operator for Status field and the like.
Compare the output of two requests to QueryAPI:
```json
[{"object_name": "Assessment",
"type": "ids",
"filter": {"expression": {
"op": {"name": "IN"},
"left": "status",
"right": ["Not Started", "In Progress"]
}}}]
```
```json
[{"object_name": "Assessment",
"type": "ids",
"filter": {"expression": {
"op": {"name": "OR"},
"left": {
"op": {"name": "="},
"left": "status",
"right": "Not Started"
},
"right": {
"op": {"name": "="},
"left": "status",
"right": "In Progress"
}
}}}]
```
The responses should be the same.
The new `IN` operator works very similar to `=` operator, but with a list as `right` operand. It is translated to `content IN (some_values)` in SQL.
Tested on ggrc-qa dump from late Aug.
Assessment status in <list> …
> GGRC-3631 Add IN operator for QueryAPI

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-group.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-group.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-wrapper.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-container_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-group_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-container_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-group_spec.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/components/view-models/tests/advanced-search-container-vm_spec.js
- src/ggrc/assets/javascripts/plugins/tests/advanced-search-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/advanced-search-utils.js
Currently we can't import specific utils in small bundles because root namespace `GGRC.Utils` not defined there and we have to import one with all not needed utils or check and create namespace if it not exist, but both option not good since we have Import/export syntax.
Try to import some util without `ggrc_utils.js` file
Migration `advanced-search-utils` on module syntax
> GGRC-3756 Migrate advanced search utils on module syntax

- README.md
- bin/containers
Currently when container is rebulit with `./bin/containers setup dev` docker-compose.override.yaml file is not used and developer needs to make additional steps to load GDrive API keys. This PR amends and completes the solution made in #6479.
1. Have a __docker-compose.override.yml__ file in the project directory ( https://github.com/google/ggrc-core/blob/dev/README.md describes how to create one )
2. Run `./bin/containers setup dev`
3. Run `./bin/containers connect` which is a shortcut to the `docker exec -it ggrccore_cleandev_1 su`
4. Run `echo $GGRC_GAPI_KEY` and see the API key set up normally.
When `docker-compose` command is used with the `--file` param it does not look for the override files automatically. Instead, the user must provide a chain of *.yml files which will be merged …
> QUICK-FIX Proper support for docker-compose override files

- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/tests/object-state-toolbar_spec.js
- src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
When we change state of assessment then `undo` buttons appears. If after this we click `next` or `prev` button and move to other assessment and if its state is not `In Progress` then `undo` button appears only on section with local CA, despite the fact that the assessment was not changed.
1. Have at least 3 assessments in 1. 'In progress', 2. 'In review', 3. 'Not started' states on the audit page
2. Expand Info pane for 'Not started' assessment and complete it
3. Click 'Next'/'Prev' button
4. Look at the Info pane of Assessment 'In review': 'undo' button is displayed but no changes have been made for such assessment
*Actual Result:* Extra 'undo' button is displayed for Assessment
*Expected Result:* Extra 'undo' button should not be displayed for Assessment
Add method …
> GGRC-3749 Extra 'undo' button is displayed for Assessment

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/bulk-update-button/bulk-update-button.js
- src/ggrc/assets/javascripts/components/bulk-update-button/tests/bulk-update-button_spec.js
- src/ggrc/assets/javascripts/components/object-bulk-update/bulk-update-target-state.js
- src/ggrc/assets/javascripts/components/object-bulk-update/object-bulk-update.js
- src/ggrc/assets/javascripts/components/object-bulk-update/tests/bulk-update-target-state_spec.js
- src/ggrc/assets/javascripts/components/object-bulk-update/tests/object-bulk-update_spec.js
- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/models/mappers/mappings.js
- src/ggrc/assets/javascripts/plugins/tests/advanced-search-utils_spec.js
- src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js
- src/ggrc/assets/javascripts/plugins/tests/utils/bulk-update-service_spec.js
- src/ggrc/assets/javascripts/plugins/utils/advanced-search-utils.js
- src/ggrc/assets/javascripts/plugins/utils/bulk-update-service.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
- src/ggrc/assets/mustache/components/bulk-update-button/bulk-update-button.mustache
- src/ggrc/assets/mustache/components/object-bulk-update/bulk-update-target-state.mustache
- src/ggrc/assets/mustache/components/object-bulk-update/object-bulk-update.mustache
- src/ggrc/assets/mustache/modals/mapper/object-bulk-update-modal.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/bulk-update/_bulk-update.scss
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
NOTE: 
Add ability to update CycleTaskGroupObjectTask state in bulk.
1) WHERE?
My Work - Tasks page. 
2) BULK UPDATE in tree view:
'BULK UPDATE' option should be displayed under 3 dots on My Tasks page.
On clicking 'BULK UPDATE', 'Bulk Update' pop-up should be opened. 
3) BULK UPDATE pop-up:
Advanced filters on BULK UPDATE pop-up:
- Task State (Assigned / In Progress / Finished / Declined / Deprecated / Verified); 
- Task Attributes (Summary / Assignee / Start Date / Due Date)
List of tasks related to logged-in user should be displayed on pop-up (same as on My Tasks page); 
- Task Title, Task State, Task Assignees, Task Start Date, Task Due Date columns should be displayed by default for tasks list. 
- Cycle title, Task Last Updated, Task Last Updated By columns should be hidden by …
> GGRC-3463: FE-Bulk Task Update on My Tasks page

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/audits/modal_content.mustache
Save button is disabled in Edit Audit modal window 
1. Go to All objects page > Audit tab
2. Hover over audit first tier > Edit object
3. Look at the Save button: is disabled
4. Edit audit, e.g. edit description: is still disabled
Actual Result: Save button is disabled in Edit Audit modal window
Expected Result: Save button should be enabled in Edit Audit modal window if all the required fields are filled
NOTE: the issue is reproduced not only for all audits (can be reproduced when Audit Captain is not current user and was not loaded in cache before modal opening).
Replace user load via 'using' mustache-helper with 'form_preload' step.
Need to ignore Audit Captain input while serializing modal form - it will reset 'contact' field.
> GGRC-3551: Fix validation issue on Edit Audit modal

- PULL_REQUEST_TEMPLATE.md
Currently the dependencies are not tracked in a common way, leading to
misunderstandings on why a PR is on hold and whether the dependency
has already been merged.
Copy the new version of the template into the description of a PR.
See the example of the dependency list in the end of this description (note that it is illustrative, thus should not be considered real).
We have a de-facto standard of a list of dependencies that is now added to the template.
The dependencies list is organized as a list of checkboxes with PR numbers or (if no PR is open yet) ticket ids.
Once a dependency is merged, its checkbox must be checked.
Once all dependencies are merged, `on hold` label should be removed.
PR numbers are preferred over ticket ids since they are clickable and easier to check: a ticket can …
> DOCS Add a list of dependencies to PR template

- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
Object counts in HNB have incorrect values while Audit Dashboard is opened
1. Log as Admin
2. On the Administration page > Custom attributes tab> Audits >Add global custom attribute with text type and title as "Dashboard_report"
3. Create a program and map control to the program
4. Create and map an audit to the program
5. On the Audit Info page fill GCA "Dashboard_report": e.g. https://ggrc-test.googleplex.com > Save
6. Create an Assessment 
7. Refresh the audit page: confirm Configurable dashboard tab is displayed in HNB
8. Select Configurable dashboard tab and refresh the page
9. Look at the HNB: Assessment tab shows zero, no mappings are displayed in HNB, count in the People tab is incorrect
Actual Result: Incorrect info is displayed in HNB after refreshing the Audit page while Audit …
> GGRC-3803: Fix request for object counts on Audit Dashboard page

- test/selenium/src/tests/conftest.py
This PR modify chrome_options fixture to start chrome maximized but with resolution 1440x900 which is required from business perspective (*minimal from chain below):
MacBook Pro 13.3": 1440x900 (127.68 PPI)
MacBook Pro 15.4": 1440x900 (110.27 PPI)
MacBook Pro 15.4": 1680x1050 (128 PPI)
MacBook Pro 17": 1920x1200 (133.19 PPI)
Before this PR, resolution of docker's virtual Linux environment was set to 1440x900 by docker-compose (ggrc-core/docker-compose-testing.yml):
```
selenium:
build: 
context: .
dockerfile: Dockerfile-selenium
volumes:
- "./test/selenium:/selenium"
- "/dev/shm:/dev/shm"
links:
- dev
environment:
- "TZ=America/Los_Angeles"
- PYTHONDONTWRITEBYTECODE=true
- PYTHONPATH=/selenium/src
- SCREEN_WIDTH=1440
- SCREEN_HEIGHT=900
```
Additionally,  chrome-browser resolution was set …
> QUICK-FIX Modify chrome_options fixture to start chrome maximized (res. 1440x900)

- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control-group.js
- src/ggrc/assets/javascripts/components/related-objects/tests/related-people-access-control-group_spec.js
If audit is archived a control for adding a person into custom role field is not disabled on Assessment info pane.
Custom roles:
- Creator
- Assignee
- Verifier
- Primary contacts
- Secondary contacts
1. Have archived audit with assessment
2. Go to assessment tab and expand Info pane
3. Hover over the title of custom role field: edit icon is displayed 
4. Click edit icon and add a new person: person is added, spinner turning around endlessly and 403 error is displayed in console
**Actual Result:** If audit is archived a control for adding a person into custom role field is displayed
**Expected Result:** If audit is archived a control for adding a person into custom role field should not displayed
Prevent editing when instance archived flag is true.
> GGRC-2734 Disable a control for adding a person into custom role field If audit is archived

- src/ggrc/assets/javascripts/components/bulk-update-button/bulk-update-button.js
- src/ggrc/assets/javascripts/components/bulk-update-button/tests/bulk-update-button_spec.js
Redundant calls after bulk updates
1) Go on My Work page 
2) Open Assessments
3) Open Tasks and apply Bulk Update
Actual Result: 2 calls for CTGOT and Assesments refresh are made
Expected Result: only 1 call for CTGOT refresh should be made
Find closest tree-widget-container component and trigger refresh on it.
> GGRC-3838: Remove redundant calls after Bulk Update

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/components/tests/gdrive_picker_launcher_spec.js
- src/ggrc_gdrive_integration/assets/javascripts/utils/gdrive-picker-utils.js
The issue was that if there where no audit folder assigned to the audit, GDrive API gave an error when we where trying to attach ( copy and rename ) shared files. As stated in the [API Doc](https://developers.google.com/drive/v3/reference/files/copy#parents) if we need to copy file to the GDrive root folder, we need to omit the parents param from the request. Somehow it works for the own file but doesn't work for shared files. For shared files we need provided `root` as the id of the folder. It's not described in the doc, but buried deep in the examples.
__GGRC-3811__
_Precondition:
1. User1 has a file in GDrive folder.
2. Owner of the file shares the link/can comment/can view with User1 to this file. 
3. User1 has read access to the file_
1. Have an Assessment on the …
> GGRC-3811,3841 Fix issues with attaching of shared files and files from the same folder

- src/ggrc/models/assessment_template.py
- src/ggrc/models/mixins/attributevalidator.py
- test/integration/ggrc/models/test_attributevalidator.py
User can create LCA with the same name as reserved names in Assessment. But he shouldn't.
1. Have audit with control snapshot 
2. On the audit page create Assessment template with LCA date type and title 'Due date' screenshot-1.png￼ 
3. Go to Assessment tab and generate assessment based on assessment template and control snapshot
Actual Result: 'Assessment generation has failed.' error occurs while generating assessment based on template that contains LCA 'Due date' Expected Result: no errors should be shown up while generating assessment. Creating of LCAs with title 'Due date' should be restricted.
Added virtual relation between assessment_template and assessment for adding Assessment's reserved names to AssessmentTemplate's reserved names list. So Assessment's …
> GGRC-3706 Fix LCA - reserved names collision issue

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/javascripts/components/tabs/tab-container.js
- src/ggrc/assets/javascripts/events/eventTypes.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
In this pr improved redirection method to error cause place.
It switch to needed tab with error cause now.
1. Have Assessment with mandatory local custom attribute field which is not filled
2. Expand Assessment info pane and open 'Other attributes' tab
3. Click 'Complete' button
> GGRC-3425 Redirect to Assessment tab while clicking 'Complete' button if mandatory custom attribute is not filled

- src/ggrc/assets/javascripts/components/access_control_list/tests/access_control_list_roles_helper_spec.js
- src/ggrc/assets/javascripts/models/business_object_models.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/directive_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/models/section.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/javascripts/models/system.js
- src/ggrc_risks/assets/javascripts/models/risk.js
- src/ggrc_risks/assets/javascripts/models/threat.js
If add a user to custom role filed and click 'discard', user is still shown on Info pane
1. Invoke Edit assessment modal window
2. Add person to custom role field screenshot-1.png
3. Click 'discard' button
4. Look at the custom rile field on Assessment Info pane
_Actual Result_: If add a user to custom role filed and click 'discard', user is still shown on Info pane
_Expected result_: If add a user to custom role filed and click 'discard', user should not be shown on Info pane
Access_control_list should be empty before merge with access_control_list from response.
Added _'before:refresh'_ method to _'accessControlList'_. This method cleans access_control_list before merge
> GGRC-3758 If add a user to custom role filed and click 'discard', user is still shown on Info pane

- src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js
⚠️  I did not have the time today to figure out when the blocker was introduced, but I did checkout 0.10.34 locally and verified that the issue is reproducible there. Hopefully I (or another frontend dev) will do a quick git bisect to determine when the issue was introduced. 
⚠️  I also did not have the time to look at the problems with the editor role (as described in the 3 NOTEs below).
Creator with Auditor role cannot create an Issue from the related issues tab on assessment.
1. Log as Global Reader/Global Creator (globcreator@gmail.com (engage007)
2. Create a program, audit
3. On the audit page create assessment and raise an issue for assesment
Actual Result: A message that 'you don't permissions' occurs
Expected Result: Global Reader/Global Creator should have the …
> GGRC-3857 Add context to raise issue button

- src/ggrc/migrations/versions/20171110133934_1af0b27960a2_update_recipients_field.py
- src/ggrc/models/comment.py
- src/ggrc/notifications/data_handlers.py
- test/integration/ggrc/converters/test_import_commentable.py
- test/integration/ggrc/models/test_control.py
- test/integration/ggrc/notifications/test_comment_notifications.py
Notification should be sent if comment created in any model. It should be sent to Admins, Primary Contacts, Secondary Contacts of the object.
~This PR depends on #6320 . It contains cherry picked comments from it~
FE for this ticket in #6404
> GGRC-3184 Set up notifications for comments created in all models

- src/ggrc/assets/javascripts/components/tree/sub-tree-item.js
- src/ggrc/assets/javascripts/components/tree/sub-tree-wrapper.js
- src/ggrc/assets/javascripts/components/tree/templates/sub-tree-item.mustache
- src/ggrc/assets/javascripts/components/tree/templates/tree-item.mustache
- src/ggrc/assets/javascripts/components/tree/tests/sub-tree-wrapper_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unmap-button/unmap-button.js
- src/ggrc/assets/javascripts/components/view-models/tree-item-base-vm.js
- src/ggrc/assets/javascripts/events/eventTypes.js
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view-animations.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
Tree view is not refreshed if Unmap object on the second level.
**Current solution:** Collapse and highlight open subtrees which contain unmapped item.
> GGRC-2043 Unmap on 2d level: tree view is not refreshed

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/tests/info-pane_spec.js
LCAs are available for edit and there is no 'Edit answers' button if move Assessment to the 'Deprecated' state.
1. Have an assessment in "In progress" state on the Audit page with any type of LCA
2. Navigate to Assessment Info pane and click 'Deprecate' in 3 bb's menu
3. Edit LCA attribute: No confirmation massage is shown up while editing
*Actual Result:* LCAs are available for edit and there is no 'Edit answers' button if move Assessment to the 'Deprecated' state
*Expected Result:* LCAs should not be available for edit before clicking 'Edit answers' button if Assessment is in 'Deprecated' state
Refactor getter of `editMode` attribute. Allows edit only if assessment is not archived and it is in editable status.
> GGRC-3792 LCAs are available for edit and there is no 'Edit answers' button if move Assessment to the 'Deprecated' state

- src/ggrc/assets/mustache/people/tree-item-attr.mustache
Incorrect tooltip is shown for person with no role for Program on People tab.
1. Have program 
2. Go to Peoples tab > map person: confirm mapped person has 'no role' 
3. Hover over first tier in tree vier: 'Mapped' tooltip is shown instead of 'no role'
Actual Result: If hover over user's program role incorrect tooltip is shown up
Expected Result: If hover over user's program role tooltip should be the same as user's program role
Check whether role is 'Mapped' and provide appropriate title value.
> GGRC-3528: Fix tooltip for people role (Program object)

- src/ggrc/fulltext/mysql.py
- src/ggrc/migrations/versions/20171122133459_14f51dd9affb_fix_text_fields_data.py
- src/ggrc/models/assessment_template.py
- src/ggrc/models/clause.py
- src/ggrc/models/comment.py
- src/ggrc/models/context.py
- src/ggrc/models/control.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/directive.py
- src/ggrc/models/document.py
- src/ggrc/models/help.py
- src/ggrc/models/issuetracker_issue.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/notification.py
- src/ggrc/models/object_person.py
- src/ggrc/models/section.py
- src/ggrc_risks/models/risk.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/converters/test_import_commentable.py
- test/integration/ggrc/models/test_assessment.py
Not started assessment moves to In progress state if open Edit assessment modal window and w/o any updates click Save
1. Have an audit with a control snapshot
2. Generate assessment based on a control snapshot screenshot-2.png
3. In the Assessment tab invoke Edit Assessment modal window screenshot-3.png
4. Do not update assessment and click Save and Close button. Look at the state of Assessment screenshot-4.png
Actual Result: Assessment changed a state from Not started to In progress
Expected Result: Assessment should not change a state from Not started to In progress
The issue appeared because of the difference in the data stored in the database and the data being posted in the PR. For example, let's have a text field which is represented as NULLABLE TEXT in the …
> GGRC-3410 Not started (generated) assessment moves to In progress state.

- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
- src/ggrc/assets/stylesheets/modules/_modal.scss
Formatting of People list in Comparison window is broken
1. Have an audit with a control snapshot
2. Go to the original control page and add at list 5 people to custom role field, 'See more' link should be displayed
3. On the audit page in the Controls tab refresh tree view
4. By clicking 'Get the latest version link' open Comparison window and look at the People list 
**Actual Result:** Formatting of People list in Comparison window is broken
**Expected Result:** Formatting of People list in Comparison window should not be broken
Formatting is broken because people loads asynchronously. So preloading people fixes the issue.
> GGRC-3817 Fix formatting of people list in comparison modal

- src/ggrc_workflows/__init__.py
- test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
If you update cycle task state over import from Assigned/InProgress state right to the Verified state when Cycle Task finished day is empty. It shouldn't happen. 
1. Create any WF (Verification flag - TRUE)
2. Add 1 task to Task Group
3. Activate WF > Cycle Task has 'Assigned' state
4. Export Cycle Task of the Cycle
5. Change state of cycle task to 'Verified' and Import the Cycle task
6. Expand Cycle Task Info pane in UI and look at the Actual Finish Date: is empty
Actual Result: 'Actual Finish Date' contains 'none' after bulk update of Cycle task via Import
Expected Result: 'Actual Finish Date' should contain 'Actual finished date' after bulk update of Cycle task via Import
Attach one or more files to this issue
On update Cycle status to verified check if finished …
> GGRC-3900 'Actual Finish Date' contains 'none' after bulk update of Cycle task via Import

- src/ggrc/assets/javascripts/components/assessment_templates/assessment_templates.js
- src/ggrc/assets/javascripts/components/assessment_templates/tests/assessment_templates_spec.js
- src/ggrc/assets/javascripts/components/object-generator/object-generator.js
- src/ggrc/assets/mustache/components/object-generator/object-generator.mustache
Search results are not relevant in Assessment Generation popup 
1. Have an audit with a control and an objective snapshots
2. Create assessment template with 'Objectives' Assessment type
3. Open Generate Assessment popup
4. Look at the screen: object type is updated from 'Controls' to 'Objectives', Search results contain control snapshot
Actual Result: If generate assessment based on Assessment template with 'Objective' object type (or other objects except Control), search results are not updated and show control snapshots by default in generation popup
Expected Result: Search results should be updated in Generation popup
Fire event from assessment-templates component when AT is loaded and search results only after that.
> GGRC-3826: Search results on Generate Assessment modal after AT is loaded

- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/test_api_calls.py
Allow to move task from Declined state to Finished. 
NOTE: found one more issue Key error if You send Assigned state. 
Move Cycle Task to Declined from Finished. Move from Finished to Declined.
Try to update to Assigned state
Add Declined state in list of allowed states for Finished State.
Add Assigned state with empty from state list.
> GGRC-3892 Can not update Declined state to Finished state for Cycle Tasks

- src/ggrc/models/hooks/__init__.py
- src/ggrc/models/hooks/custom_attribute_definition.py
- test/integration/ggrc/models/mixins/test_customattributable.py
- test/integration/ggrc/models/test_revision.py
- test/selenium/src/tests/test_snapshots.py
After the deletion of CADs new revision for object that have value for this CAD is not created. And at the FE in not shown link "Get the latest version" for snapshots after deleting CADs.
1. Go to audit page and confirm that Control is displayed in tree view with values in CAs on the Info pane 
2. Go to Administration > Custom attributes tab and remove all created CAs 
3. Go to audit page, refresh the page and look at the Control's Info pane 
Actual Result: "Get the latest version" link is not shown in Control snapshot Info pane after updating CAs 
Expected Result: "Get the latest version" link should be shown in Control snapshot Info pane after updating CADs
Snapshot has bool attribute "is_latest_revision", which is True if there are no new revisions for …
> GGRC-1773 "Get the latest version" link not shown in control snapshot Info pane after Deleting CADs

- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control.js
Prev/Next buttons on assessment do not update the creator/assignee/verifier list
1. Go to My work page > Assessments tab
2. Navigate to Info pane of any assessment in the tree view
3. Look people in creator/assignee/verifier fields
4. Click Prev or Next button: the same people in creator/assignee/verifier fields are displayed
**Actual Result:** Prev/Next buttons on assessment do not update the creator/assignee/verifier list
**Expected Result:** Prev/Next buttons on assessment should update the creator/assignee/verifier list
Refresh people groups on instance update event.
> GGRC-3810 Prev/Next buttons on assessment do not update the creator/assignee/verifier list

- src/ggrc_gdrive_integration/file_actions.py
- test/unit/ggrc/converters/test_get_gdrive_file.py
If we have \n in column that we want to import then we will have a Bug on it. Column Value will be broken.
try to import data if there are line breaks in column
Pull all data from gDrive to Buffer and use that buffer as file in csv parser.
> GGRC-3946 Fix import with line breaks inside cells

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/stylesheets/components/form/_ggrc-form.scss
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/relationship.py
- test/integration/ggrc/models/test_assessment.py
- Rename checkbox next to 'Object under assessment' to 'Inherit <object type> Assessment Procedure'. 
- Check box should be shown for all the objects that have 'Assessment Procedure' attribute.
- Checkbox should be checked by default.
- Add 'inherit Assessment Procedure" switch next to 'Assessment Type' dropdown;
- Switch should be turned ON by default.
- 'Inherit Assessment Procedure" switch should be displayed for all objects that are selected in 'Assessment Type' dropdown and have 'Assessment Procedure' attribute.
AC1. Snapshot is mapped to Assessment:
- Assessment Procedure text from snapshot should be copied and pasted into Assessment 'Assessment Procedure' field, if snapshot type = type specified in 'Assessment type' attribute in Assessment.
- Snapshot 'Assessment Procedure' text …
> GGRC-2285/2265/3163 Copy Assessment Procedure from snapshot to Assessment on mapping

- src/ggrc_basic_permissions/roles/Creator.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc_basic_permissions/test_reader.py
Global Reader (Program Reader) is able to Unmap users on People tab
1. Create program, map Global Creator to program
2. Map GR to program and grant Program Reader role
3. Log as Program Reader (globreader@gmail.com (engage007) and open program page
4. Go to People tab
5. Click on GC's first tier > 3 bb's menu > Unmap
Expected Result: Global Reader (Program Reader) should not be able to Unmap users on People tab
Create separate list of object permissions and used it for Creator/Reader delete
> GGRC-3352 Disable to unmap people from Program for Global Reader

- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
Remove ability to move CTGOT to other Workflow or TaskGroup.
Open Edit modal for CTGOT on MyTasks page or on Active Cycles tab for Workflow.
Check whether it is existing object and show fields in read-only mode.
NOTE: there is known issue with empty values for Workflow and TaskGroup if user opens Edit modal on My Tasks page via flipped down menu.
> GGRC-3957,GGRC-3958: Make Workflow and TaskGroup readonly on CTGOT Edit modal

- src/ggrc/assets/javascripts/components/tree/tree-header.js
Tree view doesn't sorted by 'Last updated' by default
1. On the My work page open Assessment tab
2. Look at the Last updated column: sorting control is not set by default by DESC
_Actual Result_: Default sorting control is not set in the tree view for Last updated column for Assessment
_Expected Result_: Default sorting control should be set in the tree view for Last updated column for Assessment. Sorting by DESC
'_tree-header_' component sets '_order_' property by default
> GGRC-3844 Default sorting control is not set in the tree view for Last updated column for Assessment

- src/ggrc/assets/mustache/components/custom-attributes/custom-attributes.mustache
"Add required info" link is shown when assessment is not in an editable state.
1. Have audit with a control snapshot
2. Create assessment template with LCA (dropdown type, comment, evidence are required)
3. Generate assessment based on a control snapshot and assessment template
4. Expand Assessment Info pane and select the value that require a comment from LCA
5. Do not enter a comment and click Close: "Add required info" link should be displayed in grey box
6. Archive audit
7. Expand Assessment info pane and click on "Add required info" link: comment box is displayed
8. Type any comment and click Save: "Uncaught TypeError: e.item.attr is not a function" error message is displayed
**Actual Result:** "Add required info" link of LCA with dropdown type is active if …
> GGRC-3916 "Add required info" link of LCA with dropdown type is active if assessment is archived

- src/ggrc/assets/stylesheets/modules/_modal.scss
CustomRole columns should occupy the same width as form items.
CustomRole column occupies less space than form item
1) Open New-Edit  Assessment modal
2) Compare width of "Creators", "Assignees", "Verifiers" at the top of modal with "Code" and "Due Date" at the bottom.
Enlarge width to 250px and make right margin smaller (30px).
> GGRC-3983: Fix CustomRole column width on modals

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc/assets/javascripts/models/cacheable_conflict_resolution.js
Changing a state on assessment should be the same as editing a field in an assessment and there is no need to make a get request before put.
Assessment shown is the one being verified and we should always have the latest etag for it. If someone edited the assessment elsewhere, we would still allow the state change without warning a user that he might be verifying data that is not displayed.
Such assumptions are dangerous and the fact that we might not have the correct etag should be solved elsewhere not on the state button click.
1. Open Assessment info-pane
2. Change status of Assessment
**Actual result:** before PUT request sended extra GET request on assessment
**Expected result:** must be sended only PUT request
was removed extra GET request,
conflict resolution of simple property was …
> GGRC-2545 Remove redundant GET request before assessment state change

- src/ggrc/models/assessment.py
- test/integration/ggrc/converters/test_import_assessments.py
1) Over import and over api not started assessment on status update to Deprecated will be moved in Progress state.
2) Imposible to move assessment from ReworkNeeded state to Deprecated
1) create new assessment 
2) update it's state to deprecated
--------------------
1) create new assessment 
2) update state to rework needed 
3) update state to deprecated
1) remove end_date from tracked fields, end date is the service field and it's not allowed to change by user 
2) add Deprecated state as valid to move from Rework Needed
> GGRC-3955,3952 Correct assessment status update to Deprecated

- src/ggrc/models/assessment.py
- src/ggrc/models/mixins/statusable.py
- test/integration/ggrc/models/mixins/test_autostatuschangable.py
The issue is connected with the fact that Deprecated status is treated as a Done state which in turn is included in FIRST_CLASS_EDIT states (autostatuschangeable.py: 28).
Since object has attribute changes it goes and handles this first_class_edit: set the _need_status_reset flag to True if object state is inside FIRST_CLASS_EDIT states. This is why system changes objects state to "In Progress". 
We should not consider Deprecated state neither START or DONE state.
1. Have an Audit with control snapshot
2. Create assessment template with required LCA with any type, e.g. date
3. Generate assessment based on assessment template
4. Navigate to Assessment Info pane > 3 bb's menu > Depecated
5. Look at the screen: 400 error in console
6. Refresh the page: assessment is moved …
> GGRC-3735 Fix Deprecate Assessment with mandatory LCA

- src/ggrc/services/assessment_resource.py
Currently comments are requested(using Query API) with the following sorting parameters:
{sortBy: 'created_at', sortDirection: 'desc'}
Custom endpoint should return comments with the similar sorting
trigger a custom endpont for /api/assessments/X/related_objects and check comment order
the latest comment should be on top
Added order by creation date and Id to comments. Id is needed because multiple comments can be added via imports which makes their created at time the same, but we should still retain the same order as they were in the csv fle.
> GGRC-4008 Add order to assessment comments

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
JS error occurs while adding 'Audits' tab on the Program page
2. On program Info page click Add tab and click Audits
Actual Result: "Uncaught Error: Syntax error, unrecognized expression: #ajax-modal-programs-1483-!audit_widget" error occurs while adding Audits tab on the program page
Expected Result: no errors should be shown while adding Audits tab on the program page
When we moved to can.route we started use links with exclamation `!` symbol.
The solution is add exclamation to 'blacklist'.
> GGRC-4022 Exclude exclamation symbol when build modalId

- src/ggrc/migrations/versions/20171208083413_45ccf2a009bb_fix_default_peole.py
1. Have an audit with an old assessment template (created before migration Assignees to ACL)
2. Clone audit
There will be a script error + a message in the console:
WARNING  2017-12-07 21:58:54,647 ggrc.services.common Invalid value for default_people.assignees. Expected a people label in string or a list of int people ids, received None.
1. Have an audit with an assessment templates
2. Clone audit with assessment templates
Audit should be cloned successfully
This issue is a regression of https://github.com/google/ggrc-core/pull/6629.
There are wrong default_people groups ("assessors") in Assessment templates now in db. But in code this group is named "assignees". When we try to find mandatory "assignees" group in some old default_people value we get validation error.
Selenium tests …
> GGRC-4020 Fix Audit cloning server error

- src/ggrc/migrations/versions/20171121072747_5240c67306fe_add_folder_fields.py
- src/ggrc/migrations/versions/20171208083413_45ccf2a009bb_fix_default_peole.py
This PR backmerges the release branch and makes all migrations in dev to base on the latest release migration.
Every instance that hosts `dev` branch should have its migrations downgraded to the branchpoint since the migration history is modified.
> BACKMERGE Fix migration chain

- src/ggrc/access_control/list.py
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/modal-connector.js
- src/ggrc/assets/javascripts/components/object-list-item/person-list-item.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control.js
- src/ggrc/assets/javascripts/controllers/mapper/mapper.js
- src/ggrc/assets/javascripts/controllers/tests/mapper_spec.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/mixins.js
- test/integration/ggrc/access_control/test_ac_rbac.py
After this ticket is done, all information needed to display an assessment info panel or edit modal should be fetched with only two queries
get /api/assessments/x
get /api/assessments/x/related_objects
This ticket does not require the other requests to be removed. That would be good but if it is too much work we should have separate tickets for removal of additional requests.
But the acceptance criteria for this ticket is that all info needed is received by those two mentioned requests.
Open Assessment Info pane
Assessment indo pane data is loading by optimized endpoint
> GGRC-3228 Fetch data for Assessment info panel use custom endpoint

- src/ggrc_workflows/assets/javascripts/controllers/approval-workflow-modal.js
- src/ggrc_workflows/assets/javascripts/controllers/tests/approval-workflow-model-helper_spec.js
Provide WF Admin in ACL for Approval Workflow.
1. Open any Control without approval task
2. Run the following code in Web Tools Console 
``` javascript 
GGRC.access_control_roles.push({
default_to_current_user:false,
delete:true,
id:83,
mandatory:true,
modified_by:null,
my_work:false,
name:"Admin",
non_editable:false,
object_type:"Workflow",
read:true,
selfLink:"/api/access_control_roles/83",
tooltip:null,
type:"AccessControlRole",
update:true})
```
3. Create Approval WF and check request on WF creation in Web Tools -> Network tab
> GGRC-3935: provide WF Admin in ACL for Approval WF

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/migrations/versions/20171204095103_6a7dbb10dfa_fix_cycle_and_cycle_task_group_dates.py
- src/ggrc_workflows/services/resource.py
- test/integration/ggrc_workflows/test_status_propagation.py
*ISSUE 1: Task Group state is NOT recalculated when cycle task is deleted*
*ISSUE 2: Cycle and cycle task group are still overdue, if all overdue tasks are completed / verified.*
*ISSUE 1: Task Group state is NOT recalcualated when cycle task is deleted*
1. Cycle task group should have 2 cycle tasks: In Progress and Finished.
2. Remove 'In Progress' cycle task.
Actual result: Cycle task group has 'In Progress' state.
Expected result: Cycle task group has 'Finished' state.
*ISSUE 2: Cycle and cycle task group are still overdue, if all overdue tasks are completed / verified.*
1. Create a WF with a task group.
2. Add 2 tasks into task group. (1 of them should be overdue after activation)
3. Activate WF.
4. Complete / Verify overdue tasks.
Actual result: cycle and cycle task group still have …
> GGRC-2895/3948/3954 Task Group showing as overdue even when all milestones completed

- src/ggrc_workflows/assets/javascripts/models/workflow.js
- src/ggrc_workflows/assets/mustache/workflows/tree-item-attr.mustache
Add default columns for Admin and Workflow Member in tree-view.
1. Open Workflows tab on All Objects page
2. Run the following code in Web Tools Console (add breakpoint in the bootstrap.js)
``` javascript 
GGRC.access_control_roles.push({
default_to_current_user:true,
delete:true,
id:83,
mandatory:true,
modified_by:null,
my_work:false,
name:"Admin",
non_editable:false,
object_type:"Workflow",
read:true,
selfLink:"/api/access_control_roles/83",
tooltip:null,
type:"AccessControlRole",
update:true})
GGRC.access_control_roles.push({
default_to_current_user:false,
delete:true,
id:85,
mandatory:true,
modified_by:null,
my_work:false,
name:"Workflow Member",
non_editable:false,
object_type:"Workflow",
read:true,
selfLink:"/api/access_control_roles/83",
tooltip:null,
type:"AccessControlRole", …
```
> GGRC-3934: Update tree-view columns for WFs

- PULL_REQUEST_TEMPLATE.md
I have uncommented the migration checklist part, because it seems that
developers are forgetting to uncomment that when opening a PR with a
migration. It seems that it is safer to force developers to remove it if
it's not needed instead of relying on devs to uncomment it when it is
needed.
Besides that I have added an additional check that was missing for the
downgrade part.
> QUICK-FIX Update pull request template

- src/ggrc_workflows/assets/javascripts/models/workflow.js
Redundant Task Groups are created on Workflow update.
1. Open existing Workflow
2. Update Workflow
**Actual result:** New Task Group is created.
**Expected result:** Task Group count should be the same.
Check whether it is new Workflow on it's update.
> QUICK-FIX Fix an issue with WF update

- src/ggrc/models/mixins/customattributable.py
- test/integration/ggrc/models/mixins/test_customattributable.py
User cannot delete LCA from Edit Assessment template modal window.
1. On the audit page create Assessment template with LCA (any type)
2. Invoke Edit Assessment template modal window and remove LCA > Click Save and Close
3. Invoke Edit Assessment template modal window again: LCA wasn't removed
1. On the audit page create Assessment template with LCA (any type)
2. Invoke Edit Assessment template modal window and remove LCA > Click Save and Close
3. Invoke Edit Assessment template modal window again: LCA should be removed
Reason of issue is that local CADs will be removed on BE only if we receive non-empty list in `custom_attribute_definition` field from FE. So if user want to remove all CADs from Assessment template, this list will be empty and BE skip deletion code. I …
> GGRC-3945 Fix deletion of LCA from Edit Assessment template window

- src/ggrc/models/reflection.py
- src/ggrc_workflows/migrations/versions/20171218080506_3355d60d65d8_add_workflow_acr_records.py
In scope of moving Workflow roles to ACL needed roles should be added.
alembic upgrade, downgrade + db_reset
Check the code, please. It is pretty simple. [Here is](https://docs.google.com/document/d/1ktIPqtiC84gX9XlKD7O3c5mb-OVnnsnY3T8RqsnL5Y8/edit#) some technical details as well as requirements.
> GGRC-3929 Add Workflow needed ACR records

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/converters/snapshot_block.py
- src/ggrc/views/converters.py
The issue with export is that it consumes a lot of memory. Export creates in memory all the exported block instances and fills it with data, creates all the row converters and column handlers instances and also fills it with the data. Then it converts all this data to 2d array of csv data. And after consuming all the container memory - python process just breaks.
As for now, we have ~13K assessments in our qa db. Querying them all in row_converters_from_ids() immediately consumes ~700M of memory. While we have 1G available on our qa instance.
Then while converting them to rows one by one consumes ~2M per each (with all fields, mappings and CAs) and processing of all this lasts ~1-2 sec. Even if we'd have 30Gig of RAM export would take ~26K sec. Without all CAs checked ~3 Assessments are …
> GGRC-1800 "500 Server Error" occurred while downloading csv file with Assessments

- src/ggrc/assets/javascripts/components/custom-attributes/custom-attributes-actions.js
- src/ggrc/assets/javascripts/components/custom-attributes/custom-attributes-actions.mustache
- src/ggrc/assets/mustache/assessments/modal_content.mustache
Moving assessment between different statuses don't match the desired logic described in the ticket.
1. Moving assessment from NOT STARTED to IN PROGRESS must not create any confirmation dialogs or show any warnings. See details in the attached spreadsheet in BE subticket GGRC-3947
2. Moving assessment from IN REVIEW to IN PROGRESS by clicking the "Edit Answers" should trigger the status change confirmation dialog.
1. Remove status change warning on Assessment edit modal for 'NOT STARTED' state.
2. Add confirmation dialog for "Edit Answers" button on assessment info-pane.
- [] I have applied the correct milestone and labels.
> GGRC-3475 Add new logic of moving Assessment between states

- src/ggrc/assets/javascripts/models/system.js
Conflict message is displayed while Inline editing custom roles, GCAs for Processes, a value is not saved
1. Have any GCA for Process (e.g. date, dropdown)
2. Create a process
3. On the Info page edit GCA > Save
*Actual Result:* Conflict message is displayed while Inline editing GCAs for Processes, the value is not saved
*Expected Result:* Conflict message should not display while Inline editing GCAs for Processes, a value should be saved
The reason of the issues is the lack of `ca_update` mixin in Process model.
System and Process models have common base model.
System model is defined earlier than Process model.
When `ca_update` mixin was applied for System model, it marks as 'was applied' in base model.
When system tries to apply `ca_update` for Process model, it see …
> GGRC-3361 HTTP409 on Inline edit to ACL/CA for Process

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/templates/mapper-results.mustache
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
ACCEPTANCE CRITERIA:
AC1. Remove scroll for search results in modal.
AC2. Dropdown with a list of number of objects to display should contain: 10, 25, 50.
> GGRC-3213 Unified mapper pop up improvements

- src/ggrc/models/mixins/with_action.py
- test/integration/ggrc/models/mixins/test_with_action.py
Sending PUT with
```
actions: { add_related: {
id: null,
type: "Comment",
custom_attribute_definition_id: 70
}}
```
lead to error "Missed action parameters". That's not informative, need to change it to "Field description is missed"
Send PUT with
```
actions: { add_related: {
id: null,
type: "Comment",
custom_attribute_definition_id: 70
}}
```
to api/assessments/<id>. Error "Field 'description' is missed." should be shown
Compare set of required columns and received, put difference into error message.
> GGRC-3176 Fix error msg for invalid asmnt add_related

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-wrapper.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
GCA with rich text type is not displayed in Global Search / Unified mapper
2. Select Controls object type > Search
3. Set visible fields > Rich Text
*Actual Result:* GCA with rich text type is not displayed in Global Search / Unified mapper
*Expected Result:* GCA with rich text type should be displayed in Global Search / Unified mapper
1) Set `includeRichText` property to true for mapper results.
2) See that now this property is always true.
3) Remove `includeRichText` property at all.
> GGRC-3485 Show RichText CA in search results

- src/ggrc/assets/javascripts/apps/custom_attributes_wrap.js
- src/ggrc/assets/javascripts/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc/assets/javascripts/models/mixins.js
Actual values of GCAs are not displayed automatically, if edit GCAs twice via Edit modal
1. Have GCAs for Control (e.g. date, dropdown, text)
2. Create control
3. Open Edit Control modal window and fill GCAs with values > Save
4. Open Edit Control modal window once again and update GCAs > Save
5. Look at the values of GCAs: previous values are displayed
*Actual Result:* Actual values of GCAs are not displayed automatically, if edit GCAs twice via Edit modal. Refresh is needed
*Expected Result:* Actual values of GCAs should be displayed automatically, if edit GCAs twice via Edit modal
We have the issue because `isReadyForRender` change handler does not handle cases when value was changed from `true` to `true`.
I used events to fix it.
> GGRC-3363 Fix custom attributes re-initialization

- src/ggrc/notifications/common.py
- src/ggrc/utils/__init__.py
- test/integration/ggrc/notifications/test_comment_notifications.py
- test/unit/ggrc/notification/test_common.py
When `_notifications/show_pending` is accessed error thrown:
File "/vagrant/src/ggrc/notifications/common.py", line 326, in show_pending_notifications
_, notif_data = get_pending_notifications()
File "/vagrant/src/ggrc/notifications/common.py", line 207, in get_pending_notifications
get_notification_data(notif))
File "/vagrant/src/ggrc/utils/__init__.py", line 111, in merge_dict
merge_dict(destination[key], source[key], path + [str(key)])
File "/vagrant/src/ggrc/utils/__init__.py", line 111, in merge_dict
merge_dict(destination[key], source[key], path + [str(key)])
File "/vagrant/src/ggrc/utils/__init__.py", line 115, in merge_dict
raise Exception('Conflict at %s' % '.'.join(path + [str(key)]))
Exception: Conflict at user@example.com.comment_created.ParentObjInfo(id=16L, …
> GGRC-2975 Fix data conflict on notifications

- src/ggrc/assets/javascripts/components/cycle-task-actions/cycle-task-actions.js
- src/ggrc/assets/javascripts/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc/assets/javascripts/components/tests/cycle-task-actions_spec.js
CTGOT is expand/collapsed on state change.
1. Create any workflow
2. In the setup tab add task to task group
3. Map any entity to task group
4. Activate Workflow
5. In Active Cycles tab expand subtree for cycle and cycle task group
6. Click [Start] button in Task first tier
**Actual Result:** While clicking [Start] button for Task, tree view with mappings is expanded
**Expected Result:** While clicking [Start] button for Task, tree view with mappings should not expand
The same issue should be fixed for moving CTGOT to Verified state (CTGOT tree is collapsed).
Remove functionality for expanding-collapsing CTGOT tree on state change.
> GGRC-3682: Fix expand/collapse issue on CTGOT state change

- src/ggrc/migrations/versions/20170908142613_3c69a1e45812_remove_meeting_and_objectevent_data.py
- src/ggrc_gdrive_integration/migrations/versions/20170908141255_4bb6fa8fb5e1_remove_meeting.py
- src/ggrc_workflows/migrations/versions/20170908142618_14b87f599ede_remove_meeting_and_objectevent_data.py
Meeting model data cleanup (previously part of #6711)
Just a copy of the cleanup of `Request` model with replaced names.
> GGRC-4089 Remove Meeting data

- src/ggrc/assets/javascripts/components/three-dots-menu/templates/three-dots-menu.mustache
- src/ggrc/assets/javascripts/components/three-dots-menu/tests/three-dots-menu_spec.js
- src/ggrc/assets/javascripts/components/three-dots-menu/three-dots-menu.js
- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
*Empty 3dds menu.*
*Open any Object tab when you have Creator role. When the objects is loaded the 3bbs menu is empty.*
*Disable 3bbs button while the object is loaded.*
> GGRC-3764 3bbs shows an empty menu - fix the empty menu on the audit (tab) tree view screen.

- src/ggrc_gdrive_integration/migrations/versions/20171228091247_3f64d03c6c01_remove_object_folders_table.py
This PR is `on hold` until 0.10.37-Raspberry is deployed:
> GGRC-3898 Remove object_folder table from our db

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/javascripts/components/assessment/tests/assessment-local-ca_spec.js
LCA dropdown fields with evidence required show wrong validation statuses before the attachments are loaded.
1. Create Assessment with 2 dropdown fields and values which require evidences.
2. Switch dropdown to "evidence required" values and add 2 evidences to the assessment.
3. Switch network throttling in chrome devtools to "slow 3G" and reopen assessment info pane.
4. Validation of the dropdown fields does not switch to "invalid" during all stages of form data loading.
The solution is not to run form validation until all data are available. This is achieved by adding the  flag which changes when all related to assessment items are loaded.
> GGRC-3158 Fix LCA dropdown field validation

- src/ggrc_workflows/assets/javascripts/models/cycle_models.js
- src/ggrc_workflows/assets/javascripts/models/task_group.js
- src/ggrc_workflows/assets/javascripts/utils/date-util.js
- src/ggrc_workflows/assets/javascripts/utils/tests/date-util_spec.js
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
User should be able to set week days only for TGT and CTGOT
1. Create weekday WF
2. Add task and Activate WF
3. Go to the Active Cycles tab
4. Edit task: set TASK START DATE/TASK DUE DATE day off
**Actual Result:** While editing task for weekday WF user is able to set day off
**Expected Result:** While editing task for weekday WF user should not be able to set day off
The same should be fixed for create CTGOT modal and Create/Edit TGT modal.
check via moment.js whether date is weekday and amend it to closest Friday (moment.js is in use due to possible issue for different locales).
> GGRC-3366,GGRC-3262: Restrict dates to week days for TGT and CTGOT

- src/ggrc/assets/stylesheets/components/action-toolbar/_action-toolbar.scss
Action toolbar buttons have shadow when in hover state.
Open Assessment Info Pane and take a look at any inline edit control ( ex. Assessment Procedure or Assignees )
Remove box-shadow css prop from inline edit button hover state.
> GGRC-3650 Remove shadow for action toolbar buttons

- src/ggrc/migrations/versions/20171124111204_3911f39325b4_fix_wrong_recipients.py
- src/ggrc/models/comment.py
- test/unit/ggrc/models/test_assessement.py
1. Create an Assessment with "recipients" = ",," (no idea how to do it through the UI, I just had such data in ggrc-qa dump)
2. Click "Complete" on this Assessment's info pane.
Expected result: the state is changed.
Actual result: the backend returns HTTP500.
Supposedly, no other edit to the Assessment succeeds.
Such data shouldn't exit in the app in the first place, we mishandle the "recipients" field in some scenario.
...
```python
File "/vagrant/src/packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/vagrant/src/packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/vagrant/src/packages/flask_login.py", line 758, in decorated_view
return func(*args, …
```
> GGRC-3688 Fix assessment PUT fail when "recipients" field contains ",," value

- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/inner-nav-controller.js
- src/ggrc/assets/javascripts/controllers/tests/inner_navigation_controller_spec.js
- src/ggrc/assets/mustache/dashboard/internav_list.mustache
Remove '+Add Tab' control from Person page
1. Login to GGRC.
2. Search People in Global search.
3. Click 'open in a new tab' link for any person.
4. System opens Person page.
**Actual result:** '+Add Tab' control present on person page.
**Expected result:** '+Add Tab' control should be removed from person page. Person page is just used to see the objects that are mapped to concrete person. Any mappings are prohibit.
Remove redundant code from dashboard_controller.js
> GGRC-2501 Remove '+Add Tab' control from Person page

- test/selenium/src/lib/constants/element.py
- test/selenium/src/tests/test_snapshots.py
Un-skip and redesign test Issue mapped to origin control (after mapping issue to asmt w/ mapped snapshoted ctrl).
```Python
@pytest.mark.smoke_tests
@pytest.mark.parametrize(
"dynamic_objects, dynamic_relationships, expected_state",
[("new_assessment_rest", None, element.AssessmentStates.NOT_STARTED),
(["new_assessment_rest", "new_issue_rest"],
"map_new_assessment_rest_to_new_control_rest_snapshot",
element.IssueStates.DRAFT)],
ids=["Mapping snapshot of Control to Assessment",
"Mapping Assessment with mapped snapshot of Control to Issue"],
indirect=["dynamic_objects", "dynamic_relationships"])
def test_asmt_and_issue_mapped_to_origin_control(
self, create_audit_with_control_and_update_control,
dynamic_objects, dynamic_relationships, expected_state, selenium
):
"""
Check Assessment, Issue …
```
> QUICK-FIX [Snapshots] Redesign test Issue mapped to origin control (after mapping issue to asmt w/ mapped snapshoted ctrl)

- src/ggrc/assets/javascripts/components/tree/tests/tree-status-filter_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-status-filter.js
"Uncaught TypeError: this.viewModel.loadTreeStates is not a function" error is displayed if close advanced search in Search box
2. Click Advanced search icon in tree view
3. Once advanced search pop up appears click Apply button
4. Click close [x] advanced search in search box
Actual Result: "Uncaught TypeError: this.viewModel.loadTreeStates is not a function" error is displayed if close advanced search in Search box
Expected Result: no errors should be shown
The component was broken when it was improved to work with query string.
The fix is adjusting work in 'disabled' mode.
> GGRC-4128 Fix status filter in disabled mode

- src/ggrc/fulltext/recordbuilder.py
- test/integration/ggrc/models/test_audit.py
1. Find program with mapped controls and existing Audits (the issue is reproduced on https://ggrc-qa.appspot.com/programs/1344#!info_widget)
2. Invoke New Audit modal window on the program page
3. Fill out the required fields and click Save button
Actual Result: Error message is displayed while creating a new audit. New Audit modal window is not closed. If user clicks X button and refreshes the page, new audit is displayed in tree view. 
1. Find program with mapped controls and existing Audits
2. Invoke New Audit modal window on the program page
3. Fill out the required fields and click Save button
Expected Result: no errors should be shown while creating a new audit. New audit should be shown in tree view.
Reason of issue is that internal ACL roles are indexed. If we …
> GGRC-4113 Fix Audit creation failure

- src/ggrc/assets/javascripts/components/unified-mapper/templates/mapper-results-item-status.mustache
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/audits/tree-item-attr.mustache
- src/ggrc/assets/mustache/base_objects/general-page-header.mustache
- src/ggrc/assets/mustache/base_objects/open_close.mustache
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
- src/ggrc/assets/mustache/cycle_task_group_object_tasks/tree-item-attr.mustache
- src/ggrc/assets/mustache/directives/tree-item-attr.mustache
- src/ggrc/assets/mustache/objectives/tree-item-attr.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
- src/ggrc/assets/mustache/risk_assessments/tree-item-attr.mustache
- src/ggrc/assets/mustache/sections/tree-item-attr.mustache
- src/ggrc/assets/mustache/task_group_tasks/tree-item-attr.mustache
- src/ggrc/assets/mustache/task_groups/tree-item-attr.mustache
- src/ggrc/assets/mustache/workflows/info.mustache
- src/ggrc/assets/mustache/workflows/tree-item-attr.mustache
- src/ggrc/assets/stylesheets/_common.scss
"Completed and Verified" state has a wrong color in tree view and assessment info pane status label.
1. Create an assessment and move it to the verified state. 
2. Look at the status label on the assessment info pane ( near the title ) it has a proper green color.
3. Take a look at the status of the assessment in the tree view it also has a proper green color.
I added a `verified` css class that overrides the color of the completed class and applied it where necessary. Also during the implementation, I found a bug in `addclass` mustache helper which occurred when using this helper with the mustache variable interpolation. For example, when we used it like this: 
```mustache
<div class="state-value {{addclass 'state' instance.status}} {{#if instance.verified}}verified{{/if}}">
```
the …
> GGRC-1509 Fix verified state color in TreeView and Assessment Info Pane

- src/ggrc_workflows/models/hooks/workflow.py
- test/integration/ggrc_workflows/test_workflow_api_calls.py
> GGRC-3921 Propagate Workflow ACL record for newly created related objects

- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/person.py
- test/integration/ggrc/utils/test_user_generator.py
When assessments are imported, error "internal server error" appears. Error log:
Reason of this issue is that we try to create new Person before Assessment setup and validation. In process of creation we validate email of new Person and if it's incorrect, validation error is raised. But as we run this check before Assessment setup exception is not handled.
1. Export assessments
2. Change email in Assignee field to invalid one (user with such email should exist in integration service)
3. Import csv with such email on instance were hr integration was switched on
4. Validation error like "Line 3: Field 'Assignees' validation failed with the following reason: Email address 'some wrong email' is invalid. Valid email must be provided. The line will be ignored." should be shown
Handle …
> GGRC-4161 Fix import failure if csv has invalid email 

- src/ggrc/assets/javascripts/components/add-object-button/add-object-button.mustache
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessments/tree_add_item.mustache
- src/ggrc/assets/mustache/audits/summary.mustache
- src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache
- src/ggrc/rbac/permissions_provider.py
- src/ggrc_basic_permissions/roles/Creator.py
Access Control List does not currently support adding `create` permission which is an issue because the auditor role should give the user permission to create assessments. 
1. Create program as admin user
2. Create and map an audit to program
3. Add Global Creator to Audit as Auditor
4. Log as Global Creator
5. Go to Assessment tab
Actual Result: Create button in missed in Assessment tab
Expected Result: Auditor should be able to create an Assessment
This is a solution that tries to change as little of the existing code as possible (because the changes are going into the release branch directly). That is why I wasn't able to implement a `create` check into the access control list at this time (it would require a migration and riskier changes than the ones we see here).
I will remove this …
> GGRC-4173 Add is_auditor check to assessment creation on the backend

- test/integration/ggrc_workflows/test_workflow_api_calls.py
> GGRC-3922 BE Check that ACL records are removed on Workflow delete operation.

- src/ggrc/assets/javascripts/apps/workflows.js
- src/ggrc/assets/javascripts/components/tree/sub-tree-wrapper.js
- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
Propagate search query for Cycle and CycleTaskGroup related objects.
1. Create any workflow
2. In the setup tab add at least 3 tasks to task group
4. Go to Active cycles tab and filter by 'task assignees'
5. Look at the screen: filter is not applied correctly
**Actual Result:** Filter for task assignee is not applied for the Cycle task sublevel in Active Cycles tab
**Expected Result:** Filter for task assignee should be applied for the Cycle task sublevel in Active Cycles tab
Check whether user tries to expand Cycle or CycleTaskGroup tree item.
> GGRC-3702, GGRC-930: Propagate filter on Active Cycles tab for Cycle and CTG

- src/ggrc/assets/javascripts/models/cycle_models.js
CTGOT should be named as 'Cycle Tasks' in search options.
1. Open "Global Search modal" modal.
2. Open "Object Type" dropdown and try to select "Cycle Tasks".
**Actual result:** 'Object type' dropdown in 'Global Search modal' contains element "Cycle Task Group Object Tasks"
**Expected result:** 'Object type' dropdown in 'Global Search modal' contains element "Cycle Tasks"
add title_plural property into CTGOT object.
> GGRC-2155: Rename CTGOT to 'Cycle Tasks' in Search options

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/entrypoints/commons.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
Workflow Create modal is broken when open it via LHN on some pages.
1. Expand accordion for Workflow in LHN 
2. Click Create button
3. Once New Workflow popup is opened look at the Repeat controls
**Actual Result:** Formatting of add New Workflow modal window is broken if open New workflow modal via LHN
**Expected Result:** Formatting of add New Workflow modal window should not be broken if open New workflow modal via LHN
Reorganize simple-modal component imports.
> GGRC-4144: Fix issue with broken RepeatOn on Workflow modal

- src/ggrc/assets/mustache/task_group_tasks/task_group_subtree.mustache
- src/ggrc/assets/stylesheets/modules/_workflow.scss
Fix styling issues on Setup tab for Workflows.
1. Create Repeat on workflow (weekly)
2. Go to Setup tab and expand Task Group Info pane
3. Create at least 3 tasks: icon for replace tasks are not centered
4. Map any object to the tasks group
5. Hover over mapped object: tooltip is displayed too far from object
6. Look at the Assignee in Assignee column: font is differ from 'Initial setup' and 'Next Cycle' columns
7. Padding between Create task button and line: approx. 30 pxls
> GGRC-3405: Fix styling issue on Setup tab for WFs

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/custom_attributes.js
- src/ggrc/assets/javascripts/models/custom_roles.js
Unify ordering of object types in "Custom attributes" and Custom Roles" tabs on Admin Dashboard
Currently objects are displayed randomly in "Custom attributes" and Custom Roles" tabs on Admin Dashboard. 
Suggestion:
Make object types in alphabetical order or another order due to business requirements.
Actual Result: user have to find objects in different places in the tabs and scroll up and down
*EXPECTED RESULT:*
'Custom Roles' tab should be sorted just like 'Custom Attributes' tab. 
1) Use lodash with the same options for both tabs.
2) Fix category for Assessment model
> GGRC-2276 Unify types ordering on Admin page

- src/ggrc/assets/mustache/dashboard/internav_list.mustache
- src/ggrc/assets/stylesheets/modules/_top-nav.scss
Fix incorrect 'Activate Workflow' button display 
1. Create Repeat off Workflow
2. On the Workflow Info page look at the [Activate Workflow] button
**Actual Result:** Incorrect display of [Activate Workflow] button
**Expected Result:** [Activate Workflow] button should be displayed according to UX mockups. 
Return 'Activate Workflow' button back in the options list and expand it on a row width.
> GGRC-4180: Correct 'Activate Workflow' display

- src/ggrc/assets/javascripts/components/tree/templates/tree-header.mustache
- src/ggrc/assets/javascripts/components/tree/templates/tree-visible-column-checkbox.mustache
- src/ggrc/assets/javascripts/components/tree/tests/tree-header_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-header.js
- src/ggrc/assets/javascripts/components/tree/tree-visible-column-checkbox.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-columns-configuration.js
- src/ggrc/assets/javascripts/components/unified-mapper/templates/mapper-results-columns-configuration.mustache
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
Checkboxes don't refresh after closing of  "Set visible fields"  dropdown.
Issue is related to tree-view columns and mapper columns
1. Create a program-> Controls tab
2. Create Control and open Set visible fields dialog in 3 bb's menu
3. Select/unselect checkbox for any field and click [x] or click out of the dialog
4. Open Set visible fields dialog once again and look at the field
Actual Result: Checkbox is unfilled/filled in Set visible fields dialog if it is not saved
Expected Result: Checkbox is unfilled/filled in Set visible fields dialog if click [Set visibility] button
'_createSelectedColumnsMap_' return array with columns config instead of '_columnsMap_'
Column config contains additional information about column.
Result: Using of '**columns**' instead of '**availableColumns**' in …
> GGRC-1142 Checkbox is unfilled/filled in Set visible fields dialog if it is not saved

- src/ggrc/assets/javascripts/models/workflow.js
Redundant TaskGroup is created on Workflow cloning
Try to clone any existing Workflow.
Check whether 'clone' property is filled for Workflow on saving.
> GGRC-4158, GGRC-4159: Fix an issue with cloning Workflow

- src/ggrc/assets/javascripts/components/modal-connector.js
No information about mapped object on CTGOT after mapping.
1. Create a WF
2. On the WF page in the Setup tab add task to Task Group
3. Activate WF
4. Go to Active Cycles tab
5. Expand tree with the third level with cycle task
6. Hover over arrow for a cycle task and select Edit object
7. Map any object to cycle task via Edit cycle task modal window, e.g. 'Control'
8. Look at the title of the mapped object: is not displayed
**Actual Result:** If map object to cycle task via Edit Cycle Task modal window, a title of the object is not displayed in the Edit Cycle Task modal window
**Expected Result:** If map object to cycle task via Edit Cycle Task modal window, a title of the object should be displayed in the Edit Cycle Task modal window
Add full item object from cache on object mapping (in …
> GGRC-3554: Fix issue with 'Mapped Objects' on CTGOT Edit modal

- src/ggrc/assets/javascripts/components/tree/templates/tree-item-custom-attribute.mustache
- src/ggrc/assets/javascripts/components/tree/tests/tree-item-custom-attribute_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-item-custom-attribute.js
If user adds new GCA with checkbox type and doesn't fill GCA field, 'No' is not displayed in tree view
1. Have newly created GCA with checkbox type for Assessment
2. Have assessment on the audit page
3. On the Assessment tab Set visible field of GCA with checkbox type
4. Look at the tree view: 'No' is not displayed by default
*Actual Result:* If user adds new GCA with checkbox type and doesn't fill GCA field, 'No' is not displayed in tree view
*Expected Result:* If user adds new GCA with checkbox type and doesn't fill GCA field, 'No' should be displayed in tree view
1) Migrate component to es2015.
2) Add default values map.
3) Add new unit-test.
> GGRC-3385 Add default CA display value for Checkbox CA type

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
If assessment have a GCA of the Date type and new assessment created without filling this field an "Invalid date" is shown in the field's column in tree view.
1. Have GCA with date type for Assessment
2. Go to an audit page
3. Create assessment leaving that field empty
4. Enable the field in tree view and see the value of this field for the newly created assessment - it says: "Invalid date" 
Same as above, but now an empty cell is shown instead of the "Invalid date" message.
There was a check for undefined and null values for the field. The solution is to return an empty string for any falsy value passed to the formatDate function.
__Notice__: The formatDate function was not covered by tests. I added test just for the logic that I touched because the rest of the function have some weird …
> GGRC-4190,4101 Fix formatting of date in tree view when empty string is passed

- src/ggrc/assets/javascripts/components/read-more/read-more.js
- src/ggrc/assets/javascripts/components/read-more/read-more.mustache
- src/ggrc/assets/javascripts/components/read-more/tests/read-more_spec.js
- src/ggrc/assets/stylesheets/_typography.scss
- src/ggrc/assets/stylesheets/components/read-more/_read-more.scss
- src/ggrc/assets/stylesheets/layout/_no-js.scss
- src/ggrc/assets/stylesheets/modules/_page-loader.scss
The "Read More" text isn't visible unless you hover over the field. In this case, user didn't even think to check if there were more lines.
I have discussed it with Pavel Nitsiyeuski and we decide display readMore always if text height take more then 5 rows. ReadMore will displayed in the right corner on the next line (after 5th row).
1. Have an assessment.
2. Fill "ASSESSMENT PROCEDURE" field in edit mode and save (you need more than 5 row of text).
3. Look at the "ASSESSMENT PROCEDURE" - "read more" is not displayed. 
Component is waiting when he will rendered and then checking scrollHeight.
If scrollHeight greater than lineHeight multiplied on maxLinesNumber - component will wrap text in readMore. If user change screen width - component will changed overflow check result also.
> GGRC-3763 Make read-more more understandable for user

- src/ggrc/data_platform/attributes.py
- src/ggrc/data_platform/computed_attributes.py
Compute attributes generates log warnings that are not clean. We should fix those warnings
Run compute attributes and check the logs for "column can not be null" warnings
The issue was that this field was missed in GGRC-3410 when we were making all texts mandatory, but the database column was still modified. This PR just applies the same changes from GGRC-3410 to the missing attribute.
see https://github.com/google/ggrc-core/pull/6749
> GGRC-4150 Remove nullable warning from computed attributes

- src/ggrc/models/hooks/assessment.py
- test/integration/ggrc/models/test_assessment_generation.py
- test/selenium/src/lib/entities/entities_factory.py
If auditor is not assigned to audit and is a default assignee in assessment template, after assessment generation assignee is missed for Assessment.
1. Have audit w/o assigned auditor
2. Create assessment template with auditor that is a default Assignee
3. Generate assessment based on Assessment template
4. Look at the Assignee in the Assessment tree view: is not displayed
5. Navigate to Assessment Info pane > Assessment tab: Assignee is not displayed
6. Invoke Edit Assessment modal window: Assignee is not displayed
1. Have audit without assigned auditor
2. Create assessment template with auditor that is a default Assignee/default Verifier
3. Generate assessment based on Assessment template
4. Assessment Assignee/Verifier should be filled with Audit …
> GGRC-3452 Use Audit Captain as default assignee if Auditor is absent

- src/ggrc_basic_permissions/roles/Auditor.py
- test/integration/ggrc_basic_permissions/test_audit_snapshot_rbac.py
- test/integration/ggrc_basic_permissions/test_auditor_filter.py
- test/integration/ggrc_basic_permissions/test_creator_audit.py
- test/integration/ggrc_basic_permissions/test_issue_mapping.py
Because we couldn't remove audit contexts in scope of audit acl the
auditor role needed to be kept around until we remove them completely.
The side affect was that old auditors set before the migration would not
get properly removed after the migration (acl records got removed, but
the user roles didn't) this caused phantom auditor permissions to remain
in the app. This fix solves the problem by removing all permissions from
the old auditor role. After we remove Program and Workflow user roles we
will be abel to remove the roles completely.
1. Make sure you have an audit with the old auditor
2. Run the audit acl migration
3. Go to the audit and remove the auditor
Expected: The auditor does not have audit access anymore
Actual: The auditor still has auditor access
> QUICK-FIX Remove auditor role permissions

- src/ggrc/assets/javascripts/plugins/tests/current-page-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
**Actual Result:** After updating audit to the latest version, new object tabs are not shown up in HNB. User have to select the tab from the list by clicking Add tab
**Expected Result:** After updating audit to the latest version, new object tabs should be shown up in HNB
1. Have a program with mapped control
2. On the program page create an audit
3. Open audit info page
4. Return back to the program page and create and map a new object to the program, e.g. 'Standards' screenshot-1.png
5. Update the audit to the latest version screenshot-2.png
6. Look at the HNB: 'STANDARDS' tab is not shown up
Update widget's counts
> GGRC-3858 After updating audit to the latest version, new object tabs are not shown up in HNB

- src/ggrc/assets/javascripts/components/cycle-task-actions/cycle-task-actions.js
- src/ggrc/assets/javascripts/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc/assets/javascripts/models/cycle_models.js
- src/ggrc/assets/mustache/dashboard/info/wf_owner.mustache
- src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
- src/ggrc/assets/mustache/wf_people/tree_add_item.mustache
- src/ggrc/assets/mustache/workflows/info.mustache
Remove unused 'kind' property from FE.
Click through workflow functionality.
- Remove 'kind' Workflow object property from front-end
- Remove pre-population logic for 'Active Workflow' on 'Create Cycle Task' modal (My Tasks page)
> GGRC-4189: Remove unused 'kind' property

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/javascripts/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/javascripts/events/eventTypes.js
This is a proper fix for the ticket GGRC-3158 which also fixes the regression ( GGRC-4154 ).
This PR fixes several issues:
1. LCA dropdown fields with evidence required show wrong validation statuses before the attachments are loaded.
3. Regression which brought by original PR. When info-pane opened for the first time, click on Complete button closes all tabs on info-pane.
3. DD field validation is not triggered when connected field changed. By connected fields I mean DD fields which both require evidence.
__1st case: Dropdown field validation on initial form load__
1. Create Assessment with 2 dropdown fields and values which require evidences.
2. Switch dropdown to "evidence required" values and add 2 evidences to the assessment.
3. Switch network throttling in chrome devtools to "slow …
> GGRC-3158,4154 Fix LCA dropdown field validation

- src/ggrc/assets/javascripts/components/rich_text/rich_text.mustache
Strike-through button was not working in Quill editor(rich-text fields in assessment info-pane and assessment modal) as it's not supported by the BE. 
1. Open assessment edit modal
2. Fill some rich-text field ( ex. assessment procedure ) with some text
3. Make different words to be bold, italic and strike-though.
4. Save assessment and open its info-pane.
__Actual result__: Strike-through style is gone. Bold and italic words are in place.
Open assessment edit modal and make sure there're no "Strike-through" button in the rich-editor toolbar.
Remove strike-through button from the Quill editor toolbar to be consistent with BE and wysihtml5 editor used on edit modals of other objects.
> GGRC-2868 Remove strike-through button from Quill toolbar

- src/ggrc/assets/mustache/base_objects/task_group_subtree.mustache
- src/ggrc/assets/mustache/base_objects/task_group_subtree_footer.mustache
- src/ggrc/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
- src/ggrc/assets/mustache/task_groups/tree_add_item.mustache
This PR should be verified based on changes in the following PR:
- #7156 
After moving workflow people to ACL Global Editor cannot create Task Group even if he is Workflow Admin.
1. Create WF with Global Reader as Admin
2. Open Setup tab under Global Editor
**Actual Result: ** Create button is not displayed
**Expected Result: ** Create button is available 
The same issue can be reproduced for Add Object to Task Group and Create Task for Task Group buttons availability.
Check whether user can update parent object (Workflow or Task Group).
> GGRC-4209: Fix issues with 'Create' button for TG

- src/ggrc/rbac/permissions_provider.py
- src/ggrc_basic_permissions/roles/Creator.py
- src/ggrc_basic_permissions/roles/Reader.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/migrations/versions/20180115094803_58e0f07e174b_move_user_roles_to_acl.py
- src/ggrc_workflows/models/cycle_task_entry.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/hooks/workflow.py
- src/ggrc_workflows/models/task_group_object.py
- src/ggrc_workflows/models/task_group_task.py
1. Create Workflow, where Global Creator/Reader/Editor is Workflow Admin 
2. Login as Global Creator/Reader/Editor
3. Press on create TaskGroup button
Actual result: Cannot create task group, rbac works fine but POST on task_groups fails with 403 error
The same for:
+ he cannot create Task Group Task
+ he cannot map/unmap object on Task Group
403 for all cases
+ cannot clone Task Group
+ cannot activate WF
> GGRC-4208/4250 Global Editor/Reader/Creator missed permissions for TaskGroup creation

- src/ggrc/migrations/versions/20180122110011_21db8dd549ac_remove_snapshot_relationships_to_own_originals.py
- src/ggrc/models/relationship.py
- test/integration/ggrc/models/test_relationship.py
This PR is `on hold` until this list gets merged:
For some reason we have weird mappings of Snapshots to their original objects in our relationships table. Which is not used and redundant.
-
The solution is to create a validator for the relationship's source and destination to avoid the described situation. And then remove all the erroneous rows from the relationships table.
> GGRC-650 Remove duplicate relationships between snapshots and original objects

- src/ggrc/models/revision.py
- test/unit/ggrc/models/test_revision.py
"Effective" state is displayed for Access Group, but "Active", "Draft" or "Deprecated" are expected.
Follow the https://ggrc-qa.appspot.com/audits/755#access_group_widget/access_group/21762 link and look at the Access Group state
*Actual Result*: "Effective" state is displayed for Access Group
*Expected Result*: For the snapshotable objects states should be: "Draft, Active, Deprecated"
Replace old-style status for models with changed statuses in *'_content'* field to 'Draft', 'Active' or 'Deprecated' according to [this](https://github.com/google/ggrc-core/blob/dev/src/ggrc/migrations/versions/20170124193902_24b94ce0860c_update_object_states.py) migration. Also set 'Draft' status for models, if status doesn't exist in old-to-new mapping or doesn't exist in model at all.
> GGRC-1507 Fix displaying old-style statuses for snapshots

- src/ggrc/assets/mustache/base_objects/general-page-header.mustache
- src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
- test/selenium/src/tests/test_snapshots.py
"Get the latest version" link is shown on Control's snapshot info pane when original control was deleted. 
1. On the audit page make sure that control is shown
2. Go to program page and delete control
3. Go to audit page and navigate to control's info pane
Actual Result: "Get the latest version" link is shown
Expected Result: "Get the latest version" link should not be visible if original control is deleted
Reuse `originalObjectDeleted` flag check for "Get the latest version" link.
> GGRC-1849 Hide "Get latest version" link for deleted object

- src/ggrc/converters/handlers/custom_attribute.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_ca_export_date.py
- test/unit/ggrc/converters/handlers/test_custom_attribute.py
Date in CA with date type is exported with incorrect format
1. Have CA with date type for control
2. Have created control with filled date in CA
3. Export control created in UI with filled date in CA
4. Look at date format in csv file
5. Date should be exported in USA format (like MM/DD/YYYY) 
This issue appeared because there was no special check for date type in _**get_value()**_ method of the CA handler, which returns CA values during export data generation. Hence unformatted value in unicode was returned. In this PR required check is added. If particular CA value has type of date, it is returned in USA date format.
> GGRC-1457 Fix date format for custom attribute in export

- src/ggrc/templates/notifications/email_digest_content.html
When new assessments are created, the email communication states that the assessment was "started". When you navigate to the assessment in GGRC, it is actually in "not started" state. The email communication stating "started" is mis-leading. 
1. Create new assessment(s)
2. Go to http://localhost:8080/_notifications/show_daily_digest and look for the section "New assessments were created".
3. Verify there's no word "started" after the assessment link
I just removed the unnecessary "start_date_statement" from the "New assessments were created" section of the src/ggrc/templates/notifications/email_digest_content.html
Also I removed the deprecated sections related to Requests since we don't have them anymore. (cleanup)
> GGRC-3331 Daily digest notification claims Assessment started while it's not true

- src/ggrc/fulltext/listeners.py
- src/ggrc/fulltext/mixin.py
- src/ggrc/fulltext/sql.py
- src/ggrc/models/assessment.py
- test/integration/ggrc/query_helper.py
- test/integration/ggrc/services/test_query/test_archived.py
AC1. Allow user to filter Audits by Archived state. Example of query: 'archived=false'
AC2. Allow user to filter Assessments by Archived state.
1. Create several Audits and Assessments
2. Filter Archived Audits and Assessments with query like 'archived=false' ('archived=true')
Filtration of Audits by Archived field was already implemented and this PR just add test for it.
To enable filtration of Assessments by Archived field reindex rule was added (when Audit is modified, related Assessments will be reindexed).
> GGRC-2320 Fix filtration of Assessments by Archived field

- src/ggrc-client/js/components/proposal/templates/apply-decline-proposal.mustache
- src/ggrc-client/styles/components/proposal/_proposal.scss
Buttons on 'proposal-comparison' window have wrong order
1. Go to Control / Risk info pane/page.
2. Propose changes.
3. Go to 'Change Proposals' tab.
4. Click 'Review & Apply' button.
_Actual result:_ Buttons are displayed in order: Cancel, Decline, Apply.
_Expected result:_ Button should be displayed in order: Apply, Decline, Cancel.
Change order of buttons on 'proposal-comparison' window
> GGRC-4206 Change the order of buttons on compare po-up

- src/ggrc/settings/default.py
Reverts google/ggrc-core#7213
We decided to postpone version 1.4 for one week.
> Revert "QUICK-FIX Bump version to 1.4.0-Strawberry"

- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js
- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
- src/ggrc/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
Cycle Task edit modal and Cycle Task info pane don't show right information about WF and Task group.
ISSUE 1: 
1. Assign a cycle task to Global Creator (who has no WF role). 
2. Log in as a Global Creator.
3. Find a task on My Tasks page.
4. Open task info pane. 
Actual result: WF is missing. An error is thrown. 
Expected result: WF name is displayed as static text (label). 
ISSUE 2: 
1. Assign a cycle task to Global Creator (who has no WF role). 
2. Log in as a Global Creator. 
3. Find a task on My Tasks page.
4. Open cycle task edit pop-up. 
Actual result: WF and Task group fields are empty. User can't save any changes to a task, because workflow field is mandatory and empty and there is no possibility to fill it out. 
Expected result: WF and task group names are displayed as static …
> GGRC-4042/4289 Update frontend logic for Workflow/TG fields on CycleTask edit modal

- src/ggrc-client/js/components/revision-log/revision-log.js
- src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
"Uncaught TypeError: Cannot read property 'title' of undefined" error occurs while clicking 'Change Log' tab for Product
1. Go to All objects page > Product tab
2. Find Product https://ggrc-qa.appspot.com/products/11
3. Click 'Change Log' tab
_Actual Result_: "Uncaught TypeError: Cannot read property 'title' of undefined" error occurs while clicking 'Change Log' tab for Product
_Expected Result_: no errors are displayed while clicking 'Change Log' tab
**Steps from developer**:
1) Open some product (control, vendor, etc.);
2) Change value of any CA;
3) Go to Administration page;
4) Remove CA from step 2;
5) Return to product (control, vendor, etc.) from step 1;
6) Open 'Change Log' tab;
Do not create diff object if custom attribute definition is undefined.
> GGRC-3456 "Uncaught TypeError: Cannot read property 'title' of undefined" error occurs while clicking 'Change Log' tab for Product	

- src/ggrc/snapshotter/__init__.py
- test/integration/ggrc/snapshotter/__init__.py
- test/integration/ggrc/snapshotter/test_snapshoting.py
Mappings between snapshot objects is not removed if child objects were unmapped and Audit was updated to the latest version.
2. Create a Control and map it to the Program.
3. Create 5 Regulations and map them both to the Program and to the Control.
4. Create an Audit, generate an Assessment over the Control.
5. Unmap 3 Regulations from the Control.
6. Update Audit to the latest version.
7. Open the Control popup on the Assessment info pane, expand Related Regulations list.
Expected result: 2 Regulations (not unmapped in step 5) are shown.
Add method that find difference between snapshot relationships and their children and remove it.
> GGRC-3659 Remove snapshots mapping if it absent for their children

- src/ggrc/utils/referenced_objects.py
- src/ggrc_basic_permissions/migrations/versions/20180125141011_568f400e4a62_set_administrator_userroles_context_to_0.py
- test/integration/ggrc_basic_permissions/test_admin.py
A newly-assigned Global Admin can't open Administarion page nor create objects on My Work page.
1. Assign a user as an Admin.
2. Log in as the user.
3. Open User dropdown.
Expected result: Administration dashboard is present in the list.
Actual result: no Administration dashboard item in the list.
4. Open `/admin` link in browser manually.
Expected result: Administration dashboard is shown.
Actual result: 403 Forbidden is returned.
5. Go to My Work page, check for Create Object button.
Expected result: the button is present.
Actual result: the button is missing.
UserRole for Admin has context with id 0. `referenced_objects.get` checks `if not id` and returns `None` instead of the special Admin context with zero id.
> GGRC-3833 Fix Admin role context

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/services/common.py
Remove deprecated/unused `workflow_cycle_start` signal from workflow code.
> QUICK-FIX Remove deprecated signal from workflow code

- src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
JS unit-test for setSearchCriteria() method randomly fails with an error:
```
Expected spy dispatch to have been called with [ Object(
{ type: 'criteriaChanged', value: 'criteria' }
) ] but it was never called.
```
The test was randomly failing because the method it was testing is wrapped with lodash debounce with timeout of 500ms and the test has a code which waits for 500ms to check the result. 
Due to the nature of JS timers and the current load of event loop the execution order of timeout callbacks is not guaranteed and sometimes code that checks the result of the method execution was called before the method itself. The solutions is simple - increase the time we wait for result in the test.
> GGRC-4351 Fix randomly failing test for setSearchCriteria method

- src/ggrc/models/hooks/assessment.py
- test/unit/ggrc/models/hooks/test_assessment.py
Assessment generation fails for objects tat have had some custom role removed and have an acl entry for that role in their revisions.
> 1. Have custom role field for control
> 2. Have a program with mapped control with added person in the custom role field
> 3. Delete custom role field for control
> 4. Make a snapshot of the control
> 5. Generate assessment using control's snapshot
> 6. Look at the screen
> Actual Result: Backend fails, user is not notified and spinner is turning around endlessly
> Expected Result: Assessment should be generated and displayed in tree view in the Assessment tab
In assessment generation we should we should ignore any ACL entry for a
role that was deleted, because those roles can not be selected for
default assessment roles. For those …
> GGRC-3027 Fix assessment generation with missing roles

- src/ggrc-client/js/components/assessment/attach-button.js
Attach evidence button on the Assessment Info pane is available if Assessment is Archived
1. Go to any audit page with created assessment 
2. Archive audit
3. Navigate to Assessment Info pane and click 'Attach' button
*Actual Result:* Attach evidence button on the Assessment Info pane is available if Assessment is Archived
*Expected Result:* Attach evidence button on the Assessment Info pane should not be available for user if Assessment is Archived
Should use `.attr()` to make the `hasPermissions` getter observing `archived` flag.
> GGRC-4121 Fix permission check for attach-button

- src/ggrc/models/revision.py
- test/unit/ggrc/models/test_revision.py
In old revision there is logged "custom_attributes" and there isn't "custom_attribute_values" elements.
Open old instance revision log (on qa for example resource_type=Workflow&resource_id=818)
populate custom_attribute_values base on custom_attributes (they should be equal)
> GGRC-4296 Populate revision content cavs if cas exist

- src/ggrc-client/styles/modules/_notifications.scss
- src/ggrc/assets/mustache/assessments/modal_content.mustache
Warning message is displayed in wrong color.
1. Create a program 
2. Create and map an audit to the program 
3. Go to the audit Summary page 
4. Create an Assessment 
5. Navigate to Assessment Info pane and click 'Complete' button to complete Assessment 
6. Click Edit Assessment in 3 bb's menu 
7. Make some changes, e.g. add Assessment Procedure
8. Look at the message: You are about to move assessment from "Completed" to "In Progress".
Actual Result: You are about to move assessment from "Completed" to "In Progress". warning message is displayed in red font color. 
Expected Result: Show 'You are about to move assessment from "Completed" to "In Progress".' message with the color as for 'Please be informed that Assignee and Verifier are the same person.'
I've figured out that the 'warning' …
> GGRC-3437 Show message on attributes modification with an appropriate color

- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
- src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
- src/ggrc-client/js/components/workflow/tests/workflow-helpers_spec.js
- src/ggrc-client/js/components/workflow/workflow-activate.js
- src/ggrc-client/js/components/workflow/workflow-helpers.js
- src/ggrc-client/js/models/cycle_models.js
_4295_ - Global Reader as workflow Admin doesn't see Start button for cycle task
_4329_ - Global Creator as workflow Admin doesn't see Start button for cycle task
_4334_ - Active Cycles tab is not preselected after activating Repeatable Workflow
*4295*:
1. Log as Global Reader and create any workflow 
2. Add a task (assignee - Global Reader) to TG and Activate workflow 
3. At the Active Cycles tab try to Start a task: no success 
Actual Result: Global Reader as workflow Admin doesn't see Start button for cycle task 
Expected Result: Global Reader as workflow Admin should see Start button for cycle task Workaround: refresh the page with Active Cycle Tab - button appears.
*4329*:
1. Log as Global Creator and create any workflow 
2. Add a task to TG …
> GGRC-4295/4329/4334 Global Reader as workflow Admin doesn't see Start button for cycle task

- src/ggrc/converters/handlers/handlers.py
- test/integration/ggrc/converters/test_import_delete.py
Delete revision entries do not get created when deleting an object via imports
test changes:
- delete object via import
- check event lon
Expected: Prevent users from deleting the object
Actual: object deleted, but deletion event is missing
Preventing deletion of objects is just a temporary fix and the correct fix should be, to make sure we create all needed revisions. But that is not going to be done fast enough and we need a temp fix fist.
Try to delete an object via imports and confirm it does not delete it.
just disabled the parser for delete column. anything more will be done with the proper solution later on
> GGRC-4372 Disable delete column on csv import

- src/ggrc/models/mixins/__init__.py
- src/ggrc_workflows/migrations/versions/20180124112407_54418614dec4_add_field_last_deprecated_date_to_cycle_.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/converters/test_column_definitions.py
- test/integration/ggrc_workflows/services/test_cycle_task_deprecated.py
Adding new field in `CycleTaskGroupObjectTask` - `last_deprecated_date`, which contains date of last changing status to `Deprecated`.
1. Create new cycle task.
2. If status of cycle task is not `Deprecated` - field `last_deprecated_date` contains `null`.
3. Change cycle task status to `Deprecated`.
4. Field `last_deprecated_date` contains date of changing cycle task status to `Deprecated` now.
1. A migration has been written that adds a new field `last_deprecated_date` (type - date) to the `cycle_task_group_object_tasks` table.
2. `LastDeprecatedDateDefine` mixin has been used for adding `last_deprecated_date` field to `CycleTaskGroupObjectTask` class.
3. A new tests has been writing for testing behavior of `last_deprecated_date` field in cycle task.
> GGRC-3502 Add "Last Deprecated Date" for a Cycle Task 

- src/ggrc/automapper/__init__.py
- src/ggrc/views/__init__.py
- src/ggrc_basic_permissions/__init__.py
Memchache was failing because our permission dict has gotten too big.
This will help reduce the size by a lot, because we were inserting a lot
of duplicates.
Log in as a user with a lot of programs/workflows/assessment assignees.
Before:
After:
Keep in mind that these are just the lists for read, we also have similar lists for update, delete and view_object_page.
This reduces the amount of data we are storing in the permissions dict, but I'm not sure if this change will be good enough.
We could also remove the view_object_page set since it's basically the same as read and that would reduce the amount of data stored by 1/4.
> GGRC-4389 Use a set for resources instead of a list

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
Custom attribute values don't clear after "Edit modal" dismiss
Prerequisites:
Have global custom attributes for regulation: text, rich text, date
1. Create a regulation
2. On regulation Info pane Invoke edit control modal popup
3. Fill out custom attributes with rich text and date 
4. Click 'x' to close Edit modal popup > Click Discard button
5. On the regulation Info page fill out custom attribute with text type via inline edit > Save value
6. Look at the custom attributes with date and rich text: non saved values are displayed
_Actual Result_: Custom attribute value that was not saved in Edit modal popup appears on the object info pane/page
_Expected Result_: Custom attribute value that was not saved in Edit modal popup should not appear on the object info pane/page …
> GGRC-4368 Custom attribute value that was not saved in Edit modal popup appears on the object info pane/page

- src/ggrc/converters/column_handlers.py
- src/ggrc/data_platform/computed_attributes.py
- src/ggrc/migrations/versions/20180112085248_4906ff3f9c7b_add_last_comment_computed_attr.py
- src/ggrc/models/assessment.py
- src/ggrc/models/hooks/__init__.py
- src/ggrc/models/hooks/common.py
- src/ggrc/models/mixins/attributable.py
- src/ggrc/models/mixins/with_last_assessment_date.py
- src/ggrc/models/mixins/with_last_comment.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/data_platform/test_computed_attributes.py
- test/integration/ggrc/fulltext/test_total_reindex.py
- test/integration/ggrc/models/mixins/test_with_last_comment.py
The comment data should be calculated and presented to the frontend in the same way as "last assessment date" in order to allow for performant read operations.
this task should ensure that we store the latest comment (or all comments depending on the task requirments) into custom attributes table on correct events:
comment added,
comment deleted (not sure if we have that yet but backend should support it and set the previous comment as "latest")
object deleted (should just delete all computed attributes for that object)
/possible other events that I might have missed)
The task should also ensure this works correctly with imported comments.
1. Create Assessment.
2. Add comments to it.
3. GET request on /api/assessments should contain fields last_comment_id (with id of last comment), …
> GGRC-2717 Add last_comment CA

- src/ggrc-client/js/plugins/tooltip.js
In some cases tooltip hides right after it's shown. 
1. Create workflow, add task and activate workflow.
2. Goto Dashboard and hover over the grey progress bar of the workflow
Prior to this PR's changes tooltip was hiding right after it's shown.
Add check if element returned from elementFromPoint is a child of the element from which the tooltip is triggered.
> QUICK-FIX Fix edge case when tooltip hides right after appearing

- src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
- src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
If user adds new GCA with checkbox type and doesn't fill GCA field, 'No' is not displayed in tree view
1. Have newly created GCA with checkbox type for Assessment
2. Have assessment on the audit page
3. On the Assessment tab Set visible field of GCA with checkbox type
4. Look at the tree view: 'No' is not displayed by default
*Actual Result:* If user adds new GCA with checkbox type and doesn't fill GCA field, 'No' is not displayed in tree view
*Expected Result:* If user adds new GCA with checkbox type and doesn't fill GCA field, 'No' should be displayed in tree view
Assessment are containing empty CAV objects. Fix is showing default values if CAV is empty.
> GGRC-3385 Show default value if CAV is empty

- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc/assets/mustache/assessment_templates/info.mustache
No possibility to delete 'Default Verifier' / 'Default Assignees' by trash icon on 'Assessment Template' info-pin.
1. Go to Audit page > Assessment template tab
2. Invoke New Assessment template modal window
3. Add Default Assignees and Default Verifiers by using 'Other' option in dropdown
4. Save Assessment template
5. Navigate to Assessment template Info pane and click on Trash Icon
Actual Result: Cannot remove a person from Assessment template Info pane by clicking Trash Icon
Make person-info not editable on assessment_template info-pin:
Set `editable` property to `false` for `person-info` component.
Fix displaying of person-info list.
> GGRC-4118 Make person-info not editable on assessment_template info-pin

- src/ggrc-client/js/models/task_group.js
Redundant TaskGroup refresh when user removes it.
1. Create any WF
2. In setup tab add a task to TG
3. Activate WF
4. Open Dev tools> Net work tab
4. Invoke Edit TG popup and click Delete button
**Actual Result:** 404 error in console while deleting a task group. Task group is deleted.
**Expected Result:** no errors should be displayed while deleting a task group.
Set 'removed' flag in TaskGroup and use it to skip redundant refresh. 
Alternative solution: don't trigger 'destroyed'-events for TaskGroupTask. It has the following drawback - TGT object will stay in models cache and stubs cache.
> GGRC-4327: Fix 404 error on TaskGroup delete

- src/ggrc-client/js/apps/custom_attributes_wrap.js
- src/ggrc-client/js/components/access_control_list/access-control-list-roles-helper.mustache
- src/ggrc-client/styles/components/related-objects/_related-reference-urls.scss
- src/ggrc-client/styles/modules/_modal.scss
- src/ggrc/assets/mustache/base_objects/modal_content_urls.mustache
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
- src/ggrc/assets/mustache/partials/modal-ajax-test-plan.mustache
"Hide all optional fields" button doesn't work as expected.
"Hide all optional fields" ("restore_ui_status" function from "modals_controller.js") uses tabindex to hide fields on modal.
1. On the audit page invoke new Issue modal window
2. Fill the fields required and click hide optional fields button
3. Click save and close
4. Look at the modal window while saving
_Actual Result_: While Issue is saving hidden optional fields appear in modal window
_Expected Result_: While Issue is saving hidden optional fields should not appear in modal window
1. Open Administration tab and add few custom attributes for Control (or other entity);
2. Open any program;
3. Open Control tab (or tab with entity from first step);
4. Click "Map" button;
5. Click "Create and map new object" on mapper;
6. Click …
> GGRC-1866 While Issue is saving hidden optional fields appear in modal window

- src/ggrc/assets/mustache/workflows/clone_modal_content.mustache
Fix wording in Clone WF modal
1. Open any active workflow
2. On the workflow Info page click Clone workflow in 3 bb's menu
**Actual Result:** Also clone the People in this Workflow (Workflow Owners and Members will also be Members of the new Workflow)
**Expected Result:** Also clone the People in this Workflow (Admins and Workflow Members will also be Members of the new Workflow)
> GGRC-4410: Fix wording in Clone WF modal

- src/ggrc/automapper/__init__.py
- test/integration/ggrc/automapper/test_automappings.py
Objects mapped through automappings don't propagate program roles, this means that the creator user will only be able to see objects that were directly mapped to the program.
As admin:
1. Create a program and add a creator user as program readers/editors/managers
2. Create a regulation and map it to the program
3. Create a section and map it to the regulation
Log in as creator and go to the program page:
Expected: Creator should see both Regulation and Section mapped to the program
Actual: Creator sees the regulation but not the section mapped to the program
The solution adds an additional step to the automapper that inserts the necessary acl records for all newly created mappings.
The current solution does not propagate the permissions to 2nd level mapped objects (Documents/Comments) …
> GGRC-4380 Program role propagation for automappings

- Dockerfile
- bin/db_reset
Cloud SQL always includes the use statement in its dumps, and we usually
export just a single database. So instead of having to always manually
remove the use statement we can have this option in the db_reset script
to make its usage a bit easier.
check if db_reset works with clean dump from cloud sql and that it still works if the dump does not contain the "USE" statement
Also check that data from the dump that is being stored is not modified in any way by romeving the use statemnet
Add different checks for multiple use statemnets and a warning for a single use statment that will be removed.
> QUICK-FIX Allow single use statement in db dump files

- src/ggrc-client/js/components/modal_wrappers/assessment_template_form.js
- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/models/audit_models.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/migrations/versions/20180105105947_3198c7918360_add_test_plan_procedure_to_assessment.py
- src/ggrc/models/assessment.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/relationship.py
"Copy Assessment Procedure" checkbox is not checked by default and is not taken in account during the objects mapping operations.
1. "Copy Assessment Procedure" checkbox should be check by default in both Assessment and Assessment Templates Edit Modals on creation.
2. "Copy Assessment Procedure" checkbox should be check by default when Assessment is autogenerated without template.
4. 'Default assessment procedure' is not saved in Add/Edit Assessment template popup;
Will be fixed
4. If "Copy Assessment Procedure" checkbox is unchecked for Assessment and we are mapping  
a Control from Assessment Info Pane, the Assessment Procedure should not be copied( and should be copied if the copy checkbox is checked )
1. Fix checkbox and textarea bindings in mustache.
2. Make "Copy assessment …
> GGRC-2285,4063,4127,4131 Fix copy assessment procedure behaviour

- src/ggrc-client/js/components/tree/sub-tree-item.js
Tree view is not refreshed after object on the 3rd level in tree view removing.
Pre-condition: existing chain of mapped objects Standard->Objective->Control.
1. Open Control info pane on Standards tab (All objects page).
2. Delete Control.
**Actual result:** tree view is not refreshed, Info pane is opened.
**Expected result:** tree view is refreshed, Info pane is closed.
Subscribe on subtree item removing and trigger event for refreshing tree view.
> GGRC-4247: Refresh tree-view after sub-item remove

- src/ggrc/migrations/versions/20180209123055_4303f98eec2c_add_audit_id_fk_to_assessmenttemplate.py
- src/ggrc/models/assessment.py
- src/ggrc/models/assessment_template.py
- src/ggrc/models/audit.py
- test/integration/ggrc/models/test_assessment_template.py
Assessment Template can be mapped to one and only one Audit. It is not guaranteed by the DB schema currently, and it should be fixed by adding audit_id column (same as Assessment has).
The FE needs to have an `audit` field on Assessment Templates to get the relevant Audit easily (needed to improve performance of Issue Tracker functionality).
Send GET request to `/api/assessment_templates`. Templates in response should contain stub with audit info.
Add audit_id to AssessmentTemplate (with FK and backref)
Set audit_id for old Assessment Templates
Add issuetracker info to audit stub
> GGRC-4355 Add audit stub as a field of Assessment Template

- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
GGRC-4450:
BE must return the total numbers of assessments in response.
Format of response:
```
{
total: X,
assessments: [{}, {}, {}]
}
```
GGRC-4451:
* Each Assessment has to contain `viewLink` field
* Audit object has to contain `viewLink` field
Manually trigger the get request for related assessments and inspect the results. they should contain all self links and total counts
I have just added the missing data to related assessments resource.
> GGRC-4450/4451 Fix related assessments

- ._license_header_exceptions
- src/cron.yaml
- src/ggrc/contributions.py
- src/ggrc/integrations/__init__.py
- src/ggrc/integrations/utils.py
- src/ggrc/views/cron.py
- src/ggrc_workflows/__init__.py
- test/integration/ggrc/integrations/__init__.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
The issue is that someone may come and change the status of the BUG in the issue tracker system. While corresponding Assessment did not change it's status. The status of the BUG should be adjusted back to the status of the corresponding Assessment.
1. User create Assessment with Issue Tracker switch ON.
2. Assessment is in 'Not Started' state for example.
3. User goes and moved assessment into 'Fixed' state.
Expected result: BUG status should be equal to Assessment state. BUG status should be reverted to 'Assigned'.
A cron job was created.
> GGRC-3880 Add job to synchronize statuses of Assessment and issue tracker BUG

- src/ggrc/access_control/roleable.py
- src/ggrc/builder/json.py
- test/integration/ggrc/access_control/test_roleable.py
- test/integration/ggrc/models/test_assessment_base.py
- test/integration/ggrc/models/test_assessment_generation.py
The backend is sending a lot of `access_control_list` items to the frontend which is slowing the app for certain object types - most notably audits.
Nothing should actually change from the users perspective, except loading audits with a lot of assessments mapped should be considerably faster.
We only send non internal access control roles to the fronted - so the roles the user can actually edit.
> GGRC-4306 Use only non internal access_control_list on the frontend

- src/ggrc-client/js/components/custom-roles/custom-roles.js
- src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
Adding a verifier (or a person to any other role) triggers too many requests to the backend:
(make sure that the assessment also has some issues mapped to it before):
Current Requests that are sent:
PUT assessment – this one is needed and should stay
GET assessment – not needed as it always returns the same result as the previous PUT request
POST query - for related assessments
POST query - for objects for related assessments
POST query - in some cases even related issues are fetched.
Developer should ensure that only the first PUT request is triggered when modifying ACL entries either on assessments page on on the assessment info pin.
If there are any side effects that make it so other requests are needed the dev must write a detailed explanation in this ticket and those will be …
> GGRC-4441 Remove redundant requests after adding a person to any assessment role

- src/ggrc/utils/log_event.py
- src/ggrc_workflows/__init__.py
- test/integration/ggrc_workflows/test_recurring_cycles_event.py
Recently start_recurring_cycles function of the nightly cron jobs has been refactored so that many commits were performed instead of a single one, and multiple events were logged (each one before a commit). However, only one event has to be logged in this case.
1. Run start_recurring_cycles() function on the qa db dump;
2. Check the number of created events in the db (1 event should be created);
3. Check the number of revisions created (should be non-zero number).
One more argument - event object - has been added to the log_event function.The next situations are possible:
1. Revisions list is empty and event is None. In this case nether event nor revisions won't be created.
2. Revisions list is not empty and event is None. In this case event and appropriate revisions will be created.
3. …
> GGRC-4429 Refactor log event procedure for nightly cron job

- src/ggrc/models/mixins/__init__.py
- test/integration/ggrc/models/mixins/test_verified_date.py
When user verifies an Assessment and then changes his mind and does "Undo" the Assessment does not reset it's verified date and hence the verified flag.
1. Assign yourself a verifier of an Assessment
2. Complete then verify the Assessment
3. Click "Undo" to step back and move it to "In review" state.
4. Refresh the list of assessments and check if the verified flag and verified date are cleared.
The condition for clearing the verified date was wrong. It did not allow to reset the field when assessment moved from a "completed" state to "In Review" state as "In Review" state is considered one of the DONE_STATED.
> GGRC-4084 Verified flag and Verified Date are not cleared when the assessment moves back to in-review state

- bin/eslint_error_lines
Sometime you need to make changes in old file on front-end that was not formatted according to the latest ESLint rules and code style fails on your PR. You need to find and issue, but running
`git diff --name-only dev | grep ".js" | xargs eslint` gives something like this
Which is often hard to process. 
eslint_error_lines is a tool that shows eslint errors only in the lines which you added or modified. Running `./bin/eslint_error_lines` will give you 
Which is much nicer to handle.
> QUICK-FIX Add eslint_error_lines tool

- src/ggrc/query/builder.py
- src/ggrc/query/pagination.py
- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
the PR https://github.com/google/ggrc-core/pull/7348
fixed a regression but broke related assessements optimization.
Fix the counts on related assessments.
Test:
open an assessment,
map a few controls to it,
check related assessments and
click last page of related assessments
Numbers should be "normal" and last page should contain at least one assessment.
It seems that sa.func.count works on polymorphic tables but does not
work properly on eager queries. While query.count() works on eager
queries and not on polymorphic tables.
This fix just ensures we get the correct counts on all pages, but is not
the proper fix for the underlying problem.
> GGRC-4538 Fix related assessments count

- src/ggrc-client/js/mustache_helper.js
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
**(Rebased PR from Vitaliy M). Assignees was set from old PR:**
User should not be able to map CycleTask to Workflow, Task Group Task, Task Group, Cycle Task, Assessment, Assessment Template.
RiskAssesment should be skipped, cause it will be removed in scope of another PR.
1. Open Global Search modal
2. Search for particular object type
3. Click on a row in search results
4. Open 3bb's menu
"Create Task" should be shown for expected object types only.
For now list of mappable to CycleTask objects is stored on front-end side. It is needed to store it on BE and provide it in GGRC.config object.
> GGRC-4505 Deny creation invalid CycleTask relationships on FE side

- src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
- src/ggrc-client/js/models/join_models.js
Fix incorrect text in the change log tab after mapping snapshot to assessment
1. Have audit with any snapshot
3. Map snapshot to assessment
4. Navigate to assessment info pane > Change Log tab
5. Look at the first column: 'Mapping to Snapshot: function () 
{ return ''; }' is displayed
Actual Result: Incorrect text is displayed in the Change Log tab after mapping snapshot to Assessment.
Expected Result: Correct text is displayed in the Change Log tab after mapping snapshot to Assessment.
Change "*display_name*" function to use child snapshot object
Remove unused "*title*" and "*description*" functions
> GGRC-3349 Fix incorrect text for snapshots in change log tab
