- src/ggrc/models/object_document.py
Add comment on documentable mixin to explain building query for relation between documentable object and document.
> QUICK-FIX Add comment on documentable mixin 

- src/ggrc/converters/autocast.py
- src/ggrc/converters/custom_operators.py
- src/ggrc/converters/query_helper.py
- test/integration/ggrc/api_helper.py
- test/integration/ggrc/services/test_query/test_validation.py
- test/integration/ggrc/services/test_search.py
Incorrect query shouldn't lead to 5xx problem 
Query should be validated and server return Bad request with error message. 
- add some validation step 
- add integrations test to incorrect posted query
> GGRC-2135 Validation on posted filter query

- src/ggrc/assets/mustache/base_objects/unmap.mustache
- src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
P2 - allow unmapping of snapshots from assessment (by Prasanna)
> GGRC-1454 Allow unmapping of snapshots from assessment 

- src/ggrc/assets/stylesheets/components/tree/_tree-item-extra-info.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
Precondition:  have control with filled admin, secondary/primary contacts 
Steps to reproduce: 
1. Go to My work page > Controls tab.
2. Set visible fields: state, admin, secondary/primary contacts, last updated .
3. Look at the control first tier in tree view .
Actual Result: Data in tree view is not aligned with columns 
Expected Result: Data in tree view should be aligned with columns
> GGRC-1955 Data in tree view is not aligned 

- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/models/factories.py
- test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
`True` for Task Assignee / Workflow Owner, `False` otherwise.
It should be used to show/hide "Start", "Finish", "Verify", "Decline" buttons.
> GGRC-2144 Add bool allow_change_state field for CTGOT

- src/ggrc_workflows/notification/data_handler.py
As a follow-up to #5737, this PR resolves three SQLAlchemy warnings introduced there, caused when an empty list of IDs is used as an argument to the "IN" condition in an SQL query.
Probably the easiest way to verify the fix is to run the following integration tests:
`integration.ggrc.notifications.test_assignable_notifications`
Without the fix, the following warnings can be observed in the console:
> /vagrant-dev/opt/dev_virtualenv/local/lib/python2.7/site-packages/sqlalchemy/sql/default_comparator.py:33: SAWarning: The IN-predicate on "cycle_task_group_object_tasks.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
>
> …
> GGRC-2368 Fix SQLAlchemy warnings on empty "IN" conditions

- src/ggrc/assets/javascripts/components/tree/tree-header.js
- src/ggrc/assets/mustache/components/tree/tree-header.mustache
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
Data in tree view is not aligned in Workflow Tasks tab on the program page. See screenshot-9.png
> GGRC-1955/2343 Data in tree view is not aligned 

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/mapped-counter/mapped-counter.js
- src/ggrc/assets/javascripts/components/object-tasks/object-tasks.js
- src/ggrc/assets/javascripts/components/tree/tree-item-extra-info.js
- src/ggrc/assets/mustache/components/object-tasks/object-tasks.mustache
- src/ggrc/assets/mustache/components/tree/tree-item-extra-info.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc/assets/stylesheets/components/object-tasks/_object-tasks.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-item-extra-info.scss
**Actual behaviour:**
All data for popover are loading during rendering of tree view row, even if they will not in demand in the future by user
Sometimes when page's instances have lots of mappings and mapped Tasks doing lots of requests that is a very slowing down loading of page (see [screenshot](https://gojira.corp.google.com/secure/attachment/13390/requests.png))
For example this Program on ggrc-qa instance - https://ggrc-qa.appspot.com/programs/872#control_widget
Load data for popover on demand (on hover on [i] icon or tree view row)
> GGRC-2324 Loading data for popover under [i] icon on demand

- src/ggrc/converters/base_block.py
- src/ggrc/converters/snapshot_block.py
- src/ggrc/fulltext/mysql.py
- src/ggrc/models/control.py
- src/ggrc/models/document.py
- src/ggrc/models/object_document.py
- src/ggrc_basic_permissions/converters/handlers.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/models/test_snapshot.py
- test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
Evidences and Urls were not logged correctly in revision.
> GGRC-2355 Attachments in Controls: save evidences for snapshots as JSON

- test/integration/ggrc/converters/test_export_snapshots.py
See https://github.com/google/ggrc-core/pull/5747#discussion_r121671426 for reference
> QUICK-FIX Update the test_export_snapshots to improve readability

- src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js
1. Go to My Work page > Assessments tab
2. Click on Assessments first tier in tree view to expand Info pane
3. Click on Related issues tab and then click "x" button to close info pane 
4. Click on Assessments first tier for the next Assessment and quickly click on Related Issues tab: JS error is displayed
_Actual Result_: "Uncaught TypeError: Cannot read property 'type' of undefined" error occurs while clicking Related issues tab
_Expected Result_: no error is displayed while clicking on Related Issues tab on Assessments Info pane
> GGRC-2443 "Uncaught TypeError: Cannot read property 'type' of undefined" error occurs while clicking Related issues tab

- src/ggrc/services/common.py
- test/integration/ggrc/models/test_assessment.py
Invalidate cache on put
Make memecache population easier
> GGRC-2473 Backend: Completed assessment moves back to In progress state if open Assessment Log

- src/ggrc_gdrive_integration/models/object_folder.py
- test/integration/ggrc/converters/test_imported_api_requests.py
Folders and files were supposed to be added to Control under GGRC-1806.
But currently an issue remains with adding files.
> GGRC-1933 Issue with attached files

- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/tests/attach-button_spec.js
- src/ggrc/assets/javascripts/components/ca-object/ca-object-modal-content.js
- src/ggrc/assets/javascripts/components/comment/comment-add-button.js
- src/ggrc/assets/javascripts/components/comment/comment-add-form.js
- src/ggrc/assets/javascripts/components/quick_form/quick_add.js
- src/ggrc/assets/javascripts/components/quick_form/tests/quick_add_spec.js
- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
- src/ggrc/assets/javascripts/components/unmap-button/unmap-button.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache
- src/ggrc/assets/mustache/components/object-list-item/editable-document-object-list-item.mustache
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/mustache/requests/gdrive_evidence_storage.mustache
The following improvements should be implemented for user friendly behavior:
1. Add Spinner for evidence/url while attaching/adding
2. Add spinner when delete evidence/url
3. Add spinner - when comment required added
4. Show on UI comment when user types/adds comment
5. Evidence - show spinner right after attachment
6. When add URL/Evidence - don't show spinner in comments area
7. Block [save] and [x] button until the evidence is saved - and add spinner near [Save] button
> GGRC-2495 Improvements for Assessment Validation

- src/ggrc/models/revision.py
- test/integration/ggrc/models/test_assessment.py
- test/integration/ggrc/snapshotter/test_indexing.py
- test/unit/ggrc/models/test_revision.py
Fix populated_content acl list based on primary_contact and contact.
> GGRC-2221 GGRC-2220 primary_contact -> contact

- test/integration/ggrc/models/test_assessment.py
Create integration test to check mappings saving for assessments
> GGRC-2418 Add test to unmap document from assessment based on different order and different cases

- src/ggrc/models/control.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/data_for_export_testing.csv
Filter worked incorrectly for these fields, full_text_index was not used for that. And because of that reason sorting worked wrong.
PR fixes that, now filtering and sorting both work for Controls and Control Snapshots.
+ Filter by Frequency added to Workflows
+ it covers GGRC-1468
> GGRC-1465 Fields "Kind/Nature", "Type/Means", "Frequency"

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tree_view_item.py
- test/selenium/src/lib/factory.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_snapshots.py
This PR depend on #5793 and check following items:
- verify that snapshot can be mapped from asmt and issue page
- verify that snapshot can be mapped from asmt and issue tree view at audit page
> QUICK-FIX Test for mapping asmt and issue to snapshot

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/folder-attachments-list/folder-attachments-list.js
- src/ggrc/assets/javascripts/components/mapped-objects/directly-mapped-objects.js
- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/mappers/mappings-ggrc.js
- src/ggrc/assets/mustache/base_templates/attachment.mustache
- src/ggrc/assets/mustache/components/folder-attachments-list/folder-attachments-list.mustache
- src/ggrc/assets/mustache/components/mapped-objects/directly-mapped-objects.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/controls/modal_content.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/folder-attachments-list/folder-attachments-list.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc_gdrive_integration/assets/javascripts/apps/gdrive.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache
User needs ability to attach documents in control objects (similar to assessments).
> GGRC-1189 Allow attachments in Controls

- README.md
This PR is a follow up to #5863 and fixes the two mis-fixes that slipped through the review.
> DOCS Fix two typos in README.md

- src/ggrc/migrations/versions/20170615140615_436dc4cea0f3_update_primary_assignees_to_principal_.py
Primary Assignees -> Principal Assignees
Primary Contact -> Primary Contacts
> GGRC-2261 Create migration for Assessment templates set valid role names

- src/ggrc/assets/javascripts/components/simple-modal/simple-modal.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/components/simple-modal/simple-modal.mustache
Update Simple Modal Behavior to avoid possible memory leaks
> GGRC-2672 Update Simple Modal Behavior to avoid possible memory leaks

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tree_view.py
- test/selenium/src/lib/element/tree_view_item.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/modal/base.py
- test/selenium/src/lib/page/modal/create_new_object.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest/template/objective.json
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_objective.py
Tasks included creation and mapping Control and Objective via RestAPI calls.
3 test cases were created:
- create control via rest, create objective via rest, map them via rest, verify that status code of mapping call is 200(ok), verify that those control and objective are mapped via UI
- create control via rest, create objective via rest, map them via rest twice, verify that status code of mapping call is 200(ok), verify that only one objective mapped to control via UI
- create control via rest, create 2 different objectives via rest, map control to 2 different objectives, verify that status code of mapping call is 200(ok), verify that two objectives mapped to control via UI
> QUICK-FIX Test task to create and map Objective to Control via rest

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
This reverts the change made by e96bf928. From what I can tell,
isInstanceCompleted funciton is only used to show/hide the comments
form.
> GGRC-2723 Auditors cannot add comments if assessment in "Ready for review" state

- src/ggrc/notifications/data_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
1. go to https://ggrc-qa.appspot.com/_notifications/show_daily_digest
Actual Result: Error “Internal Server Error” is displayed.
Expected Result: no error is displayed. Email is sent
> GGRC-2729 Fix conflict exception on daily digest

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
We need https://github.com/google/ggrc-core/pull/5909 in master so that we don't rush the release today.
> HOT-FIX GGRC-2723 Don't hide the comment box based on assessment state

- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
After selecting an evidence with google picker, we have a get request with the same url for some reason
Since all evidences should already be loaded at that point we could check the urls locally and not need the extra request.
We should investigate if this request is really needed and remove it if it's not.
> GGRC-2621 Remove redundant GET request when attaching a new evidences

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/bootstrap/modal-form.js
Scope of the ticket:
1) New Assessment window - if user click on any action that leads away from screen - show warning message
2) Click ESC - should show the warning as well - same as in #1. (pick the cheapest eng solution here)
> GGRC-2666 New Assessment window is too easily closed without saving

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/tests/test_snapshots.py
This PR depend on #5799 and check following items:
- verify that after mapping snapshot of control to asmt relationship between original control and asmt displayed at control page
- verify that after mapping snapshot of control to issue relationship between original control and issue displayed at control page
> QUICK-FIX Test mapping relationship between asmt & issue to original control

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/inline-confirm-action.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/inline-item.js
- src/ggrc/assets/javascripts/components/inline/inline-form-control-item.js
- src/ggrc/assets/javascripts/components/inline/inline-form-control.js
- src/ggrc/assets/javascripts/components/inline/inline.js
- src/ggrc/assets/javascripts/components/inline/readonly-inline-content.js
- src/ggrc/assets/mustache/components/assessment/info-pane/inline-item.mustache
- src/ggrc/assets/mustache/components/inline/checkbox.mustache
- src/ggrc/assets/mustache/components/inline/date.mustache
- src/ggrc/assets/mustache/components/inline/dropdown.mustache
- src/ggrc/assets/mustache/components/inline/inline.mustache
- src/ggrc/assets/mustache/components/inline/input.mustache
- src/ggrc/assets/mustache/components/inline/person.mustache
- src/ggrc/assets/mustache/components/inline/readonly-inline-content.mustache
- src/ggrc/assets/mustache/components/inline/simple-readonly-text.mustache
- src/ggrc/assets/mustache/components/inline/text.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/inline/_inline.scss
- src/ggrc/assets/stylesheets/modules/_inline-edit.scss
- src/ggrc/assets/stylesheets/modules/_rich-text.scss
Added universal wrapper for inline edit
> GGRC-1560 Create universal wrapper for inline edit component

- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/string_utils.py
QUICK-FIX Improve procedure updating scopes CAs' values from UI
> QUICK-FIX Improve procedure updating scopes CAs' values from UI

- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/info_widget.py
Update Assessment Header Layout
> GGRC-1564 Update Assessment Header Layout

- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_snapshots.py
- test for Unmapping snapshots from Assessment Info page
- test for Unmapping snapshots from Issue Info page
> QUICK-FIX Add test to unmap snapshot from assessment & issue info page

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment_templates/assessment_templates.js
- src/ggrc/assets/javascripts/components/assessment_templates/tests/assessment_templates_spec.js
- src/ggrc/assets/javascripts/components/object-generator/object-generator.js
- src/ggrc/assets/javascripts/components/object-generator/tests/object-generator_spec.js
- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
- src/ggrc/assets/javascripts/components/object-mapper/tests/object-mapper_spec.js
- src/ggrc/assets/javascripts/components/object-search/object-search.js
- src/ggrc/assets/javascripts/components/object-search/tests/object-search_spec.js
- src/ggrc/assets/javascripts/components/tests/mapper-model_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-model.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-toolbar.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-toolbar_spec.js
- src/ggrc/assets/javascripts/components/view-models/object-operations-base-vm.js
- src/ggrc/assets/javascripts/components/view-models/tests/object-operations-base-vm_spec.js
- src/ggrc/assets/javascripts/controllers/mapper.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/models/mappers/mappings.js
- src/ggrc/assets/javascripts/models/mappers/tests/mappings_spec.js
- src/ggrc/assets/js_specs/models/assessment_template_spec.js
- src/ggrc/assets/mustache/components/object-generator/object-generator.mustache
- src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
- src/ggrc/assets/mustache/components/object-search/object-search.mustache
- src/ggrc/assets/mustache/components/unified-mapper/mapper-toolbar.mustache
- src/ggrc/assets/mustache/modals/mapper/object-generator-modal.mustache
- src/ggrc/assets/mustache/modals/mapper/object-mapper-modal.mustache
Move specific properties to separate components.
Use mapper-model as base view model.
> GGRC-2694 Decompose Mapper Model

- src/ggrc/converters/column_handlers.py
- test/integration/ggrc/dp_models/test_last_assessment_date.py
Adds logic to export "last assessment date" column.
> GGRC-2824 add export column handler for last assessment date 

- src/ggrc/views/__init__.py
- src/ggrc/views/common.py
This PR removes unused and excessive Directive view and some dead code.
> GGRC-2837 Remove Directive view

- src/ggrc/services/common.py
- src/ggrc/views/common.py
- src/ggrc_basic_permissions/__init__.py
Less relevant part of #5960.
~Depends on #5960~
> QUICK-FIX Cleanup dead code

- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/components/assessment_generator.js
- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/scope-update.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/scope-update_spec.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/mustache/components/info-pin-buttons/info-pin-buttons.mustache
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/modules/_notifications.scss
Description:
1) When a user does whole audit refresh, we need some sort of message saying that the refresh in progress.
2) Update text and color for assessment generation
Done. Also audit refresh was improved: browser tab is not reloaded, only corresponding data (snapshots).
> GGRC-1623 Floating Message: User indication for whole audit refresh and for Assessment Generation

- src/ggrc/assets/javascripts/components/auto-save-form/fields/rich-text-form-field.js
- src/ggrc/assets/javascripts/components/auto-save-form/fields/tests/rich-text-form-field_spec.js
- src/ggrc/assets/javascripts/components/rich_text/rich_text.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
- src/ggrc/assets/mustache/components/auto-save-form/fields/rich-text-form-field.mustache
- src/ggrc/assets/mustache/components/comment/comment-input.mustache
- src/ggrc/assets/mustache/components/rich_text/rich_text.mustache
- src/ggrc/assets/stylesheets/components/auto-save-form/fields/_rich-text-form-field.scss
- src/ggrc/assets/stylesheets/components/form/_ggrc-form.scss
- src/ggrc/assets/stylesheets/modules/_rich-text.scss
Comment edit input control: rich text area - on focus only
> GGRC-1576 Comment edit input control: rich text area - on focus only

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/migrations/versions/20170724180338_545d1c7adca5_update_workflow_patch1_related_tables.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/data_for_export_testing.csv
- test/integration/ggrc/test_csvs/data_for_wf_query_api.csv
- test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
- test/integration/ggrc_workflows/models/test_workflow.py
- test/integration/ggrc_workflows/notifications/test_cycle_start_failed_notifications.py
- test/integration/ggrc_workflows/notifications/test_deleted_objects.py
- test/integration/ggrc_workflows/notifications/test_enable_disable_notifications.py
- test/integration/ggrc_workflows/notifications/test_monthly_wf.py
- test/integration/ggrc_workflows/notifications/test_recurring_cycles.py
- test/integration/ggrc_workflows/test_api_calls.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
- test/integration/ggrc_workflows/test_status_propagation.py
- test/integration/ggrc_workflows/test_workflow_revisions.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_annually_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_cycle_calculator.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_monthly_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_quarterly_workflow.py
- test/integration/ggrc_workflows/workflow_cycle_calculator/test_weekly_workflow.py
* Create workflow-patch1 branch based on dev branch.
* Add new fields to Workflow model.
* Migration: Add new columns to DB workflows table.
* Create validators for repeat_every, unit, repeat_multiplier for recurrent Workflow.
* Open PR against workflow-patch1 branch.
**Cherry-picked commits from Dzmitry Y PR:**
GGRC-2879 [BE] Add integration tests for Workflow model POST/PUT/DELETE operations
> GGRC-2878 Add new fields to Workflow model

- src/ggrc/models/hooks/__init__.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/common.py
- src/ggrc/models/hooks/issue.py
- src/ggrc/models/hooks/relationship.py
- src/ggrc/models/relationship.py
This refactoring is required to proceed with GGRC-2842.
> QUICK-FIX Move Assessment, Issue and Relationship hooks to modules

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/modal/base.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
Removed duplicated locators for initialization of drop down list options
> QUICK-FIX  Dropdown list refactoring

- src/ggrc_workflows/assets/javascripts/models/task_group.js
- src/ggrc_workflows/assets/mustache/task_group_tasks/modal_content.mustache
* Show repeat summary in Create and Edit TGT dialog.
* Validate Start and Due Dates on TGT initialization.
> GGRC-2883: Add ability to see repeat options for Tasks

- bin/release/get_pr_titles.py
- bin/release/tag_current_release.sh
This PR moves two utils that are used in release preparation to git index.
> QUICK-FIX Release utils

- src/ggrc/access_control/role.py
- src/ggrc/migrations/versions/20170711121643_951213087c6_add_field_noneditable_to_acr.py
- src/ggrc_risks/migrations/versions/20170726133704_163457f4ce13_update_non_editable.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/access_control/test_access_control_role.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/test_assessment.py
- test/integration/ggrc/snapshotter/test_indexing.py
Non-editable roles can't be modified or deleted
~This PR depends on https://github.com/google/ggrc-core/pull/5745~
> GGRC-2373 Custom roles should be able to be non-editable

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/inline/inline-form-control.js
- src/ggrc/assets/javascripts/models/assessment.js
Assessment Improvements: Remove redundant GET request on opening of Assessment Info Pane
> GGRC-2926 Assessment Improvements: Remove redundant GET /assessment/{n} request on opening of Assessment Info Pane

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/dashboard.js
- src/ggrc/assets/stylesheets/modules/_info-pin.scss
Assessment Redesign: Update Scrolling Logic for Assessment Info Pan
> GGRC-2866 Assessment Redesign: Update Scrolling Logic for Assessment Info Pane

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/javascripts/plugins/utils/controllers.js
2. Click 'Submit for review' on the Program Info page
3. Assign reviewer, select due date > Click 'Submit' button
Actual Result: "Uncaught TypeError: Cannot read property 'status' of undefined" error occurs while clicking 'Submit' button
Expected Result: no error is shown while clicking 'Submit' button
> GGRC-2932: Fix for failures in 'Submit for Review' modal

- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc_workflows/assets/javascripts/apps/workflows.js
Show workflows and tasks related to current user in appropriate tabs on 'All Objects' view.
> GGRC-2819: Add 'Workflows' and 'Tasks' tab on 'All Objects' view

- src/ggrc/assets/javascripts/components/quick_form/quick_add.js
- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/models/document.js
- src/ggrc/models/revision.py
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
These are the fixes that were made to realease branch and that must be merged back to dev branch as soon as possible, to avoid any further conflicts.
Currently the only conflict was in revision.py which I solved by applying @plamut's changes to the new code.
Please take extra care when reviewing this PR.
> QUICK-FIX Raspberry to dev merge

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/inline/inline-form-control.js
- src/ggrc/assets/javascripts/models/assessment.js
This reverts commit 2ba123aa36a6efa401400fdeb2e4a0eeac73e5a0, reversing
changes made to 015bd75b1114bcb7e60eeafd090044d5af13c1ed.
> GGRC-2953 Revert "Merge pull request #6043 from YuriChupyrkin/29/GGRC-2926"

- src/ggrc/models/assessment.py
- src/ggrc/models/document.py
- src/ggrc/models/hooks/comment.py
- src/ggrc/models/mixins/autostatuschangeable.py
- src/ggrc/models/mixins/with_action.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/services/common.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/mixins/test_with_action.py
- test/integration/ggrc/models/mixins/test_with_last_assessment_date.py
- test/integration/ggrc/query_helper.py
- test/integration/ggrc/services/test_assessments.py
- test/integration/ggrc/services/test_audits.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/tests/test_snapshots.py
> GGRC-2644: Update Assessment PUT request

- .eslintignore
- src/ggrc/assets/javascripts/components/tree/tree-filter-input.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-filter.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-filter_spec.js
- src/ggrc/assets/javascripts/generated/ggrc_filter_query_parser.js
- src/ggrc/assets/js_specs/generated/ggrc_filter_query_parser_spec.js
- src/ggrc/assets/mustache/components/unified-mapper/mapper-filter.mustache
- src/parser/parser.pegjs
GGRC-1535:
1. Create assessment with a title that contains one of the following special symbols: _%\
2. Try to filter assessment by title (e.g. "title_")
Actual Result: Filter is not applied if searchable value contains some special symbols (e.g. _%\)
Expected Result: Filter should be applied if searchable value contains some special symbols (e.g. _%\)
GGRC-2980:
2. Go to the Objectives tab and create Objective with title 'test%objective'
3. In Search box enter query: title ~ test\%
4. Look at the search results: filter is not applied for the created objective
5. Open advanced search and filter by query: 'test\%'
6. Look at the search results: created objective is displayed in Search results
*Actual Result:* Incorrect search by …
> GGRC-1535/2980 Filter is not applied if searchable value contains some special symbols (e.g. _%\) / Incorrect search by special symbols

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
_Changes by users_
1) Change Read more to More Information
2) Expand the control to more lines.
3) When clicking on more link or on the blue control, show the popup.
> GGRC-2958 Assessment UX - read more - expand by def

- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
Whenever user opens Assessment Info Pane fields of type Person show no data though value might be set
> GGRC-3305 Fix issue with rendering of Person Form field on the opening of Assessment

- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/stylesheets/modules/_notifications.scss
UX: https://drive.google.com/file/d/0B7_NYFVmb896NUlKNDZlRWtXVTg/view
Scope: when click Complete - show blue message to the user on top - see UX
> GGRC-2959 Assessment UX - show blue message when click Complete

- test/integration/ggrc_workflows/test_basic_workflow_actions.py
* Cherry-pick commits from PR#8 and check that tests are passed.
* Cover case when OneTime Workflow's CycleTasks are adjusted because of holidays/weekends.
* Should be merged right after PR#8 will be merged.
depends on #6025
> GGRC-2939 Add integration tests for CycleTask new dates calculation logic

- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/modules/_notifications.scss
Original PRs: 
GGRC-2486: https://github.com/google/ggrc-core/pull/6087 - Fix alignment of "Add required info" link
GGRC-2959: https://github.com/google/ggrc-core/pull/6101 - Assessment UX - show blue message when click Complete
GGRC-2954: https://github.com/google/ggrc-core/pull/6100 - Cursor when hovering over lines doesn’t make it clear the rows are clickable
> GGRC-2486/2959/2954 Re-apply reverted fixes to dev

- src/ggrc/assets/javascripts/components/read-more/read-more.js
- src/ggrc/assets/javascripts/components/read-more/tests/read-more_spec.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/description.mustache
- src/ggrc/assets/mustache/base_objects/notes.mustache
- src/ggrc/assets/mustache/base_objects/test_plan.mustache
- src/ggrc/assets/mustache/base_templates/notes.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/auto-save-form/auto-save-form-field-view.mustache
- src/ggrc/assets/mustache/components/read-more/read-more.mustache
- src/ggrc/assets/mustache/components/related-objects/related-issues.mustache
- src/ggrc/assets/mustache/issues/remediation_plan.mustache
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
- src/ggrc/assets/stylesheets/components/read-more/_read-more.scss
- src/ggrc/assets/stylesheets/modules/_inline-edit.scss
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/info.mustache
- src/ggrc_workflows/assets/mustache/cycles/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
> GGRC-2126/GGRC-2958/GGRC-2763 Overflow of text in fields/Assessment UX - read more - expand by def/Assessment: Comment text shows coding

- src/ggrc/assets/javascripts/components/view-models/tree-people-base-vm.js
Display peoples (creators, verifiers, ...) in tree-view as list of full emails.
> GGRC-2747 FE: Display people lists as lists of ASC sorted full emails across all app

- kokoro/ggrc_selenium.cfg
- test/selenium/pytest.ini
cherry pick from https://github.com/google/ggrc-core/pull/6093
> QUICK-FIX Store html report generated by selenium test in Google cloud storage

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/__init__.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/constants/templates.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest/query.py
- test/selenium/src/lib/service/rest/template/count.json
- test/selenium/src/lib/service/rest/template/query.json
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/help_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_objective.py
- test/selenium/src/tests/test_snapshots.py
> QUICK-FIX Re-apply Test exporting of snapshoted Control from Audit's, Issue's, Assessment's Info Pages

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/elements_list.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/lib/element/tables.py
- test/selenium/src/lib/element/tree_view.py
- test/selenium/src/lib/element/tree_view_item.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_asmts_workflow.py
This PR add 3 acceptance test scenarios from smoke test suite:
1. Assessment Log Pane
2. Related Assessments
3. Raising Issues in Related Issues Tab
> QUICK-FIX Add Assessment tabs tests

- src/ggrc/assets/javascripts/components/rich_text/rich_text.js
- src/ggrc/assets/mustache/components/rich_text/rich_text.mustache
- src/ggrc/assets/stylesheets/modules/_rich-text.scss
1. Navigate to Assessment's Info pane
2. Type into comment box any text, e.g. "www.google.com" and insert it as a link: no success
_Actual Result_: Cannot insert link into comment box on Assessment's Info pane
_Expected Result_: User should be able to insert link into comment box on Assessment's Info pane
> GGRC-2870 Cannot insert link into comment box on Assessment's Info pane

- src/ggrc/models/person.py
- src/ggrc/rbac/__init__.py
- src/ggrc/rbac/permissions.py
This is a fix for the ticket GGRC-2930 done in https://github.com/google/ggrc-core/pull/6049
The check for global read right always failed and the performance fix did not work correctly. This is a quick fix for that .
> QUICK-FIX Fix read rbac optimization

- src/ggrc/assets/javascripts/controllers/quick_search_controller.js
1. Go to My work page
2. Open LHN> All objects
3. Look at the search box
**Actual Result:** "Filter my objects..." is shown
**Expected Result:** "Filter all objects" is shown
> GGRC-1980 Suggested search text says "my" objects instead of "all" objects

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
- test/unit/ggrc_workflows/models/test_workflow.py
Daily cycles should be created only in workdays (from MON to FRI) and cycle calculator should count only that days
> GGRC-3030 changes for daily logic

- test/integration/ggrc_workflows/test_basic_workflow_actions.py
New calculation logic takes into account only working week days, not weekend days.
But holidays also allowed.
> QUICK-FIX Add tests for daily wf dates check

- docs/source/guidelines/performance.rst
The contents of this PR are still up for debate and we should be adding more info to these guidelines as the time goes on.
These guideliens are not complete and any comments in the PR should be regarding wrong iformation. missing information can and should be added in later PRs.
> GGRC-1848 Add basic performance guidelines

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
Comment by a User:
I've been taking a screenshot of the Audit Summary tab each day during fieldwork and sharing with my key contacts. I noticed that the blue piece (In Progress) moved for one day from around 2 o'clock on the pie to 9 o'clock (see July 18th email in the attachment). It shifted back this morning. 
https://gojira.corp.google.com/secure/attachment/14292/Example%20of%20Chart%20colors%20shifting.pdf
The colors of the pie chart would stay in the same order. 
Pie charts - when compared day over day - can be a little harder to understand.
> GGRC-2913 Pie chart changes positions when the status changes

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/people/editable-people-group-header.js
- src/ggrc/assets/javascripts/components/people/editable-people-group.js
- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
- src/ggrc/assets/mustache/components/custom-roles/custom-roles.mustache
- src/ggrc/assets/mustache/components/people/editable-people-group-header.mustache
- src/ggrc/assets/mustache/components/people/editable-people-group.mustache
Assessment Improvements: Add Confirmation Edit Modal to People List
**Depends on** #6070
> GGRC-3020 Assessment Improvements: Add Confirmation Edit Modal to People List

- src/ggrc/assets/javascripts/components/comment/comment-add-button.js
- src/ggrc/assets/mustache/components/comment/comment-add-form.mustache
- src/ggrc/assets/stylesheets/components/comment/_comment-add-form.scss
UI changes:
1. "Send Notifications" is replaced with "Notify Assignees and Verifiers".
2. Tooltip added (with question icon).
3. "Add" button is always enabled.
> GGRC-2964: Restyle 'Send notifications' checkbox on Assessment Info pane

- src/ggrc/assets/javascripts/components/csv/import.js
- src/ggrc/assets/mustache/import_export/import.mustache
- src/ggrc/assets/mustache/import_export/import_test_result.mustache
- src/ggrc/assets/stylesheets/components/auto-save-form/_auto-save-form.scss
- src/ggrc/assets/stylesheets/modules/_import-export.scss
The 2nd variant with Import /Cancel buttons at the bottom is provided.
> GGRC-177 Import page - UX improve

- src/ggrc/models/mixins/__init__.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/migrations/versions/20150423173706_2b89912f95f1_add_notification_entries_for_existng_.py
- src/ggrc_workflows/migrations/versions/20150514130212_1431e7094e26_add_new_notification_type.py
- src/ggrc_workflows/migrations/versions/20170804162350_4991c5731711_setup_advance_notice.py
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/workflow.py
- src/ggrc_workflows/notification/__init__.py
- src/ggrc_workflows/notification/data_handler.py
- src/ggrc_workflows/notification/notification_handler.py
- src/ggrc_workflows/notification/pusher.py
- test/integration/ggrc_workflows/notifications/test_monthly_wf.py
- test/integration/ggrc_workflows/notifications/test_one_time_wf.py
- test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py
- test/integration/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py
- test/integration/ggrc_workflows/notifications/test_task_due_notifications.py
- test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
- test/unit/ggrc_workflows/notification/test_data_handler.py
Fix notification strategy for new workflow handling.
> GGRC-2974 Add notifications for Workflow

- src/ggrc/assets/javascripts/plugins/tooltip.js
- src/ggrc/assets/mustache/people/object_list.mustache
This fixes two frontend issues with the authorization modal:
1. Role is not refreshed correctly
2. Script error in authorization modal
> GGRC-3083 Fix admin page role refresh

- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
Review State columns was removed from Assessment Template tree view.
> GGRC-1684 Remove Owner and Review State columns from Assessment Template tree view

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/tests/attach-button_spec.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
- src/ggrc/assets/js_specs/models/object_state_spec.js
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/migrations/versions/20170817140144_51d5958779f1_change_assessment_state.py
- src/ggrc/models/mixins/statusable.py
- src/ggrc/templates/notifications/email_digest_content.html
- test/integration/ggrc/models/mixins/test_autostatuschangable.py
- test/integration/ggrc/models/test_assessment.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc/test_csvs/assessment_update_intermediate.csv
- test/selenium/src/lib/constants/element.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/unit/ggrc/models/test_states.py
Assessment state should be changed from 'Ready for Review' into 'In Review'.
> GGRC-2896 Rename assessment state 'Ready for Review' to 'In Review'

- src/ggrc/notifications/__init__.py
- src/ggrc/notifications/data_handlers.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/templates/notifications/email_digest_content.html
- test/integration/ggrc/notifications/test_assessment_notifications.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc/notifications/test_notification_functions.py
Make notifications for "Assessment changes" list concrete fields that were updated, e.g.:
https://screenshot.googleplex.com/NiEkEd3hdmJ.png
> GGRC-2400 Improve notification for assessment associated person that a concrete field was updated

- src/requirements-selenium.txt
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/constants/test/modal_create_new.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/tests/test_asmts_workflow.py
This PR verify format of assessment log immediately after asmt creation.
In addition requirements for selenium container were updated according to latest stable versions of those libraries.
> QUICK-FIX Add test to check assessment log tab

- src/requirements-dev.txt
The requirements in requirements-dev should not duplicate ones in
requirements.txt.
> QUICK-FIX Remove duplicate requirements

- test/integration/ggrc_workflows/test_basic_workflow_actions.py
There was a minor error in the test
> Quick-Fix Fix test_recalculate_date test

- src/ggrc/assets/stylesheets/components/action-button/_action-button.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/modules/_tree-header.scss
According to Kseniya Koltun buttons should not have any special hover style and should display original button style (w/o hovering).
> GGRC-2262 Unify button hover style

- src/ggrc_workflows/__init__.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
- test/integration/ggrc_workflows/test_status_propagation.py
And "End date is not showed up for active cycle"
Missing cycle end(due) date caused overdue not shown
> GGRC-3106/3104 Cycle and Task group are not become overdue for the past cycle

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/assessment/info-pane/create-url.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/plugins/utils/deferred-transaction-utils.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
Apply Assessment PUT actions to ReferenceUrls
> GGRC-3120 Apply Assessment PUT actions to ReferenceUrls

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache
Apply Assessment PUT actions to Evidences and Urls
> GGRC-3123 Apply Assessment PUT actions to Evidences and Urls

- src/ggrc_workflows/__init__.py
- test/integration/ggrc_workflows/generator.py
- test/integration/ggrc_workflows/models/test_workflow.py
- test/integration/ggrc_workflows/notifications/test_task_due_notifications.py
1. Create a workflow with repeat ON
2. Create a task in the future (so that no cycle is going to be created immediately)
4. Archive the workflow
Expected: Workflow should be Inactive & Archived
Actual: Workflow is Active & Archived
https://ggrc-qa.appspot.com/workflows/1387#info_widget
https://ggrc-ux-demo.appspot.com/workflows/1395#info_widget
> GGRC-3110 Workflow is Active & Archived

- src/ggrc/assets/mustache/components/prev-next-buttons/prev-next-buttons.mustache
- src/ggrc/assets/stylesheets/modules/_object-header.scss
1. Update naming for Previous\Next buttons - should be 'Prev' and 'Next'.
2. Save URL input field on 'enter'.
3. Close URL input field after adding.
> GGRC-3136: UX updates for Assessment info page

- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/auto-save-form/auto-save-form-actions.mustache
1. Place Custom Roles at the top in the 'Other Attributes' list.
2. Remove "Save Changes" Button.
> GGRC-3146 FE UX updates on Assessment Info page (part 2)

- src/ggrc/assets/javascripts/components/ca-object/ca-object-modal-content.js
- src/ggrc/assets/javascripts/components/comment/comment-add-form.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
Apply Assessment PUT actions to Comments
> GGRC-3132 Apply Assessment PUT actions to Comments

- src/ggrc/assets/javascripts/components/inline/inline-form-control.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
Apply Assessment PUT actions to InlineForm
> GGRC-3139 Apply Assessment PUT actions to InlineForm

- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/confirm-edit-action.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/create-url.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/tests/attach-button_spec.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
Assessment Improvements: Add Confirmation Edit Modal to Assessment URLs
> GGRC-3029 Assessment Improvements: Add Confirmation Edit Modal to Assessment URLs

- src/ggrc/assets/javascripts/ggrc_base.js
- src/ggrc/assets/javascripts/models/cacheable.js
Could you please rewrite the Message in the following way: "There was a conflict while saving. Your changes **have not been saved yet**. Please refresh the page and try saving again."
> GGRC-1900 Changes are not saved if update Standard under several users

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/modal/base.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/help_utils.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_objective.py
This PR contains two tests:
1. **Creation asmt with mapped snapshots via modal**
Check if Assessment can be created with mapped snapshot via ModalCreate. Additional check existing of mapped objs titles on ModalCreate.
2.  **Map snapshots to asmt via edit modal**
Check snapshot can be mapped to Assessment via ModalEdit. Additional check existing of mapped objs titles on ModalEdit.
> QUICK-FIX Test task "Test asmt mapping via modal"

- src/ggrc/assets/javascripts/plugins/utils/dashboards-utils.js
Revert "Remove unneeded reify call"
This reverts commit ac28222c4b234049eb79a379aa61054b0e7eec6b.
> QUICK-FIX GGRC-3181 CA dashboards are not working

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
Fix issue when LCA changes were passed incorrectly
> QUICK-FIX Assessment LCA save actions

- bin/release/get_pr_titles.py
Non-critical labels (like `cla` or `please review`) are not shown.
~Depends on #6249~
> QUICK-FIX Show labels in pr list

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-control-related-objects.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/components/object-list-item/detailed-business-object-list-item.mustache
- src/ggrc/assets/stylesheets/components/collapsible-panel/_collapsible-panel.scss
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
- src/ggrc/assets/stylesheets/components/object-list/_object-list.scss
- src/ggrc/assets/stylesheets/components/simple-modal/_simple-modal.scss
- src/ggrc/assets/stylesheets/modules/_assessment.scss
Precondition: 
1. Have program, mapped control with long title, objective, regulation 
2. Objective and regulation are mapped to control 
3. Audit with generated assessment based on control 
Steps to reproduce: 
1. Expand Assessment's Info pane 
2. Open Control's popup:
Actual Result: Incorrect formatting in Control's popup 
1. font size is too big in label. Make it as in mockups. 
2. three dots should be in blue color. 
3. Increase padding: Admin <-> Name 
4. Increase padding: show related objectives, show related regulations.
> GGRC-2875 Improvements for Control's popup

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/custom-attributes/global-custom-attributes.js
- src/ggrc/assets/mustache/custom_attributes/info.mustache
Reuse InlineEditControl component for GCA of non-assessment type on Info page.
> GGRC-3112/GGRC-2664 Reuse inlineEditControl component for global custom attributes

- src/ggrc/assets/javascripts/components/tabs/tab-container.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
1. Have GCA with text/dropdown/date for assessment
2. Open Assessment Info page > Other attributes tab
3. Fill GCAs > Save
4. Switch to another tab, e.g. Related Assessments and return back to Other attributes tab
5. Look at the GCAs: the value is not shown in GCAs
6. Refresh the page: the value is shown in GCAs
Actual Result: New value in GCA is saved but is displayed after refreshing the page
Expected Result: New value in GCA should be saved and displayed after saving
> GGRC-3196 New value in GCA is saved but is displayed after refreshing the page

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/plugins/tests/utils/deferred-transaction-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/deferred-transaction-utils.js
Update Batching Tool to perform single request simultaneously
> GGRC-3187 Update Batching Tool to perform single request simultaneously 

- bin/db_reset
- bin/launch_ggrc_test
The DB is managed in test scripts
> QUICK-FIX Don't drop ggrcdevtest in db_reset

- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/view-models/object-operations-base-vm.js
- test/selenium/src/lib/page/modal/unified_mapper.py
AC1. Search results should be expanded by default on:
- Unified Mapper;
- Global Search
- Assessment generation popup
> GGRC-3186 Search results should be expanded by default on Unified Mapper.

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc/assets/javascripts/components/form/form-validation-icon.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
- src/ggrc/assets/mustache/components/local-custom-attributes/local-custom-attributes.mustache
- src/ggrc/assets/stylesheets/components/local-custom-attributes/_local-custom-attributes.scss
Custom attribute of dropdown type was not correctly displaying
verification icon for certain values.
Some code commits solved the original. This PR fixes mandatory field icon placement and refactors a form validation.
> GGRC-2378 Fix field validation icon on some Local Custom Attributes fields

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
1. Go to assessment info pane
2. Add comment
3. See in Chrome DevTool Network tab 
**Actual result:** redundant request on `/api/people...`
**Expected result:** no requests on `/api/people`
> GGRC-3263 Remove usage of mapping and extra call for people

- src/ggrc/fulltext/attributes.py
- src/ggrc/query/autocast.py
- test/integration/ggrc/services/test_query/test_basic.py
This reverts commit a4764a5b33ad91d5682c34b5d914a6d2c13930a8.
> Revert "GGRC-2862 BE: make a batter error message while date format is wrong"

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/revision-log/revision-log-data.js
- src/ggrc/assets/javascripts/components/revision-log/revision-log.js
- src/ggrc/assets/javascripts/components/revision-log/tests/revision-log-data_spec.js
- src/ggrc/assets/mustache/components/revision-log/revision-log-data.mustache
- src/ggrc/assets/mustache/components/revision-log/revision-log.mustache
- src/ggrc/models/object_document.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_snapshot_block.py
- test/integration/ggrc/models/mixins/test_with_action.py
- test/integration/ggrc/models/test_assessment.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc/services/test_audits.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/all_snapshottable_objects.csv
- test/integration/ggrc/test_csvs/assessment_full_no_warnings.csv
- test/integration/ggrc/test_csvs/assessment_notifications.csv
- test/integration/ggrc/test_csvs/assessment_update_intermediate.csv
- test/integration/ggrc/test_csvs/assessment_with_templates.csv
- test/integration/ggrc/test_csvs/control_snapshot_data_single.csv
- test/integration/ggrc/test_csvs/controls_no_warnings.csv
- test/integration/ggrc/test_csvs/program_audit.csv
GGRC-2752 [object Object] is displayed in Assessment Log after attaching evidence or adding url
> GGRC-2752/3174 [object Object] is displayed in Assessment Log after attaching evidence or adding url

- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/javascripts/components/related-objects/sortable-column.js
- src/ggrc/assets/javascripts/components/related-objects/templates/sortable-column.mustache
- src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/stylesheets/components/grid-data/_grid-data.scss
_Acceptance criteria:_
Add sorting to columns:
- Assessment title;
- Assessment State;
- Assessment finished date;
- Assessment created date.
Default sorting (as it is now):
- finish date desc, 
- create date desc
> GGRC-3208 Sort within the Related Assessments tab

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/form/form-validation-text.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/local-custom-attributes/local-custom-attributes.mustache
- src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
- src/ggrc/assets/stylesheets/components/form/fields/_date-form-field.scss
- src/ggrc/assets/stylesheets/components/form/fields/_dropdown-form-field.scss
- src/ggrc/assets/stylesheets/components/local-custom-attributes/_local-custom-attributes.scss
Complete button is active all the time. 
User clicks it and if some required field is not filled, the page scrolls down to such a field, field's border becomes read and the msg is shown: 
1. This field is required.
2. Add required info by clicking on the link.
temp folder: 
https://drive.google.com/corp/drive/folders/0B7_NYFVmb896YUZzWlFMeFJsSU0
> GGRC-2976,2998,2999 Assessment UX - Enable Complete, on click - highlight the mandatory fields with red

- src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js
- src/ggrc/automapper/__init__.py
- src/ggrc/automapper/rules.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/converters/handlers/snapshot_instance_column_handler.py
~Depends on #6312~
1. Create an Assessment.
2. Map the Assessment to a Snapshot.
3. Click "Raise an Issue" in the Assessment.
4. Click "Save and Close".
Expected result: the Issue is created, the Issue is mapped to the Assessment, Audit and all Snapshots of the Assessment, no POST to `/api/relationships` are performed.
> GGRC-2847 Automapping Issue-Assessment-Snapshot

- src/ggrc/access_control/role.py
- src/ggrc/access_control/roleable.py
- src/ggrc/models/person.py
- test/integration/ggrc/access_control/test_ac_rbac.py
- test/integration/ggrc/converters/test_import_system.py
Minimal failing csv:
```
Object type,,
System,Code*,Admin*
,SYSTEM-242,andrewcho@google.com
,SYSTEM-242,andrewcho@google.com
```
If `SYSTEM-242` has already been exists in db.
> GGRC-3284 "Uncaught TypeError: this.attr is not a function" error occurs while importing csv file

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/revision-log/revision-log.js
- src/ggrc/assets/javascripts/components/revision-log/tests/revision-log_spec.js
- src/ggrc/assets/javascripts/components/tabs/tab-container.js
- src/ggrc/assets/javascripts/components/tabs/tab-panel.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/general-page-header.mustache
- src/ggrc/assets/mustache/base_objects/info.mustache
- src/ggrc/assets/mustache/base_objects/object-review.mustache
- src/ggrc/assets/mustache/components/tabs/tab-container.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/mustache/objectives/info.mustache
- src/ggrc/assets/mustache/people/info.mustache
- src/ggrc/assets/mustache/policies/info.mustache
- src/ggrc/assets/mustache/processes/info.mustache
- src/ggrc/assets/mustache/products/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/systems/info.mustache
- src/ggrc/assets/stylesheets/modules/_tabs.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache
- src/ggrc_risks/assets/mustache/risks/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_objects/info.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_groups/info.mustache
- src/ggrc_workflows/assets/mustache/cycles/info.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
_Acceptance criteria:_
AC1. Add 'Change Log' tab as on Assessment.
AC2. Add logs into 'Change Log'. Use the same UI for logs as on Assessment.
AC3. Add logs for the following objects: https://docs.google.com/spreadsheets/d/1O6q61a-wPl3XTcoHM5QR7_VQYISTy-yj76UVaSz0D4A/edit#gid=406095162
> GGRC-1656 Paginated logs on all objects like assessments

- src/ggrc_workflows/models/task_group_task.py
- test/integration/ggrc_workflows/test_api_calls.py
- test/unit/ggrc_workflows/models/test_task_group_task.py
Send on next cycle TGT start and end dates over api on task group task level.
> GGRC-3378 RMC - Workflow 2.0 Data Validation - Setup date picked up current month

- Dockerfile-selenium
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/settings.py
- test/selenium/src/lib/constants/value_aliases.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/conftest.py
This PR implement improving of screenshot capturing for chromedriver by expanding browser VIEWPORT. If InfoPanel exists expand it too.
In this PR Selenium Dockerfile updated to the last version.
> QUICK-FIX Add chrome fullsize screenshot capturing

- test/selenium/src/lib/factory.py
- test/selenium/src/tests/test_snapshots.py
Add test parameters to verify that snapshots can be unmapped from Assessments/Issues in different states.
> QUICK-FIX Add test of unmapping snapshots from asmts and issues in diff states

- src/ggrc/assets/javascripts/components/sort_by_sort_index/sort_by_sort_index.js
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/modules/_workflow.scss
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree.mustache
- src/ggrc_workflows/assets/mustache/base_objects/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree.mustache
- src/ggrc_workflows/assets/mustache/task_group_tasks/task_group_subtree_footer.mustache
- src/ggrc_workflows/assets/mustache/task_groups/info.mustache
- src/ggrc_workflows/assets/mustache/task_groups/tier2_content.mustache
Add 'Next Cycle' column to Tasks table for Task Group on Setup tab.
> GGRC-3377: Show Next Cycle dates on TG Setup page

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/modal/create_new_object.py
- test/selenium/src/lib/page/modal/edit_object.py
Add waiting of "green success alert" after update object via edit modal
> QUICK-FIX Add waiting condition to edit modal

- src/ggrc_workflows/__init__.py
The reason was that on Sept 1 cron job was not worked because cron.yaml was missed during deployment.
On RMC test instance there are some Workflows that were not started but should (2 in April and 3 in September as far as I remember).
> GGRC-3376 RMC - Workflow 2.0 Testing - Missing monthly cycle activation

- src/ggrc/assets/javascripts/components/csv/import.js
- src/ggrc/assets/mustache/import_export/import.mustache
- src/ggrc/converters/import_helper.py
- src/ggrc/utils/error_handlers.py
- src/ggrc/views/converters.py
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- test/integration/ggrc/__init__.py
Mock-Ups: https://drive.google.com/corp/drive/folders/0B65BmaCGVTRwcHFWRUVaX0JVNDQ
The requirement was to replace the "import from file directly" option with the following:
- import from gdrive
- upload a file from local drive to gdrive then import it
> Ggrc-3252/ggrc-3177 import from google sheets

- src/ggrc/automapper/__init__.py
- src/ggrc/builder/json.py
- src/ggrc/models/hooks/common.py
- src/ggrc/utils/__init__.py
- src/ggrc/utils/benchmarks.py
- src/ggrc/utils/referenced_objects.py
This PR just pulls some commits from https://github.com/google/ggrc-core/pull/6431.
The pulled commits are just prep work and I have pulled them out to make the original PR easier to review with only the commits that are relevant to the Issue epic.
> QUICK-FIX Code cleanup

- src/ggrc/assets/javascripts/components/tree/tree-status-filter.js
**Issue:** a possibility of storing obsolete objects states of tree-view.
**FIx:** check if stored selected states is actual states.
> GGRC-3380 /query calls using deprecated filter from local storage

- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/bootstrap/tests/modal-form_spec.js
- src/ggrc/assets/javascripts/bootstrap/tests/test-template.mustache
- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/javascripts/ggrc_base.js
- src/ggrc/assets/mustache/components/assessment/attach-button.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/mustache/components/ca-object/ca-object-modal-content.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/javascripts/components/templates/gdrive_picker_launcher_upload_error.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/tests/gdrive_picker_launcher_spec.js
This PR will add suffixes to the files picked from GDrive (uploaded or existing) in the format of 
filename_ggrc_[GGRC Assessment ID]_[GGRC Control-ID].file_extension. The "_ggrc_" part of the suffix is needed in the case a user needs to reattach the file to a different assessment or remove and attached the file to the same assessment again.
> GGRC-2196 Add suffixes to the uploaded files

- README.md
- bin/jenkins/functions.sh
- docker-compose-deploy.yml
- docker-compose-testing.yml
- docker-compose.override.yml.example
- docker-compose.yml
This PR will just allow us to set `tmpfs` flag in the override file to speed up development.
db_reset before the PR 2m7.582s
db_reset with tmpfs 0m4.065s
> QUICK-FIX Update docker compose configs

- src/ggrc/models/exceptions.py
- src/ggrc/services/common.py
- test/integration/ggrc/services/test_delete.py
Background task masks any error codes returned by the deletion.
> GGRC-3070 Run deletion synchronously

- src/ggrc_workflows/__init__.py
1. Have tasks on the My work page
2. Go to Tasks tab
3. Hover over task first tier to verify task
4. Once task is verified click undo button
5. Look at the screen: 'Decline' and 'Verify' buttons disappear from task first tier
6. Hover over task first tier for another task > Click start > Click Finish > Click undo > Click Finish > Click Verify > Click undo
7. Look at the screen: a conflict message is displayed screenshot-2.png
**Actual Result:** Verify button disappeared after "undo"
**Expected Result:** Verify button should not disappear after "undo"
Workaround: refresh the page
User verified a task and hit "undo" as soon as the "undo" button showed up.
The verify button then appeared for a split second and then the …
> GGRC-3521 RMC - Workflow 2.0 Testing - Verify button disappeared after "undo"

- bin/move_regulations_to_asmnt
- bin/move_snapshots.py
This script will be run on production only. It will map all regulations and objectives mapped to control (which mapped to assessment) to assessment for one Audit.
> GGRC-3503 Map Regulations and Objectives to Assessments

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/info_widget.py
This PR is crucial one cause it is improving fault tolerance of suite in a part of operating with Info Widget model Page Objects.
> QUICK-FIX Improve fault tolerance of Info Widget's Page Objects initializing procedure

- bin/move_snapshots.py
This is the fix of merged #6531. Original script failed with error:
`sqlalchemy.exc.OperationalError: (OperationalError) (1787, 'When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, the statements CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can be executed in a non-transactional context only, and require that AUTOCOMMIT = 1. These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.') "\n      CREATE TEMPORARY TABLE temp_control_snapshots (\n        snapshot_id int(11),\n        assessment_id int(11)\n      );\n\n      INSERT INTO temp_control_snapshots(snapshot_id, assessment_id)\n      SELECT snap_id, asmnt_id\n      FROM (\n        SELECT r.destination_id AS snap_id, r.source_id as asmnt_id\n …
> GGRC-3549 Fix script to map Snapshots of regulations and objectives to Assessment

- package.json
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
- src/ggrc/assets/javascripts/entrypoints/login.js
- src/ggrc/assets/javascripts/entrypoints/styles.js
- src/ggrc/settings/__init__.py
- src/ggrc/templates/admin/index.haml
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/base_objects/show.haml
- src/ggrc/templates/dashboard/index.haml
- src/ggrc/templates/import_export/export.haml
- src/ggrc/templates/import_export/import.haml
- src/ggrc/templates/layouts/base.haml
- src/ggrc/templates/welcome/index.haml
- webpack.config.js
Different types of pages should contain specific scripts
1. Import
2. Export
3. Object related pages
4. Login
5. Admin
6. My Assessment
**NOTE:** In scope of this PR was setting up just a configuration for use different scripts on different pages. Custom scripts will be configured in future PRs.
> GGRC-3304 Setting up configuration in order to use different scripts on different pages

- src/ggrc/app.py
- src/ggrc/fulltext/__init__.py
- src/ggrc/fulltext/listeners.py
- src/ggrc/fulltext/mixin.py
- src/ggrc/fulltext/sql.py
This is part one of the parent ticket for indexer updates. This is just a cleanup before the actual work and the code is in it's own PR to make the other review easier.
> GGRC-3529 Move indexer init

- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-control-related-objects.mustache
- src/ggrc/assets/mustache/components/assessment/mapped-objects/mapped-controls.mustache
- src/ggrc/assets/mustache/custom_attributes/info.mustache
- src/ggrc/assets/mustache/programs/tree-item-attr.mustache
Conflicts resolved manually 
Original: https://github.com/google/ggrc-core/pull/6600
> Backmerge release/0.10-Raspberry into dev

- src/ggrc/migrations/versions/20171019074757_2ad7783c176_fix_design_operationally_notes_data.py
- src/ggrc/models/assessment.py
1. Have Not started assessment
2. Invoke Edit assessment modal window
3. Click Save and Close
4. Look at the Assessment's state: moves to 'In progress'
Actual Result: Not started assessment moves to In progress state if open Edit assessment modal window and w/o any updates click Save
Expected Result: Not started assessment should not move to In progress state if open Edit assessment modal window and w/o any updates click Save
> GGRC-3410 Not started assessment moves to In progress state if open Edit assessment modal window and w/o any updates click Save

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/modal/edit_object.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
Remove green warning messages (on creation of objects)
> GGRC-3512 Remove green warning messages (on creation and editing of objects)

- src/ggrc/assets/mustache/dashboard/lhn_search.mustache
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/modules/_header-content.scss
- src/ggrc/assets/stylesheets/modules/_side-nav.scss
- src/ggrc_workflows/assets/mustache/workflows/lhn_search.mustache
UX: https://drive.google.com/corp/drive/folders/0B65BmaCGVTRwcTJlQmFzRklFZTg
Scope: LHN
Colors for blue - snapshots and links
Colors for create new buttons
> GGRC-3623 LHN - change purple to dark gray + change the blue color for snapshots

- test/selenium/src/tests/test_snapshots.py
This PR add 'test_availability_mapping_of_objects_via_mapper_and_add_widget':
1) All types of snapshotable objects and Issues to Assessment;
2) All types of snapshotable objects, Issues, Programs, Projects and Task Groups (*for mapper only) to standalone Issue.
> QUICK-FIX Test availability mapping of objects to Assessment and Issue via Unify mapper and Add Widget

- PULL_REQUEST_TEMPLATE.md
🚨 **This is currently just a suggestion, all items of the template including the template itself are still up for debate!**
> QUCK-FIX Add a pull request template

- src/ggrc/assets/assets.yaml
- src/ggrc/assets/javascripts/components/tasks-counter/tasks-counter.js
- src/ggrc/assets/javascripts/components/tasks-counter/tests/tasks-counter_spec.js
- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/mustache/components/tasks-counter/tasks-counter.mustache
- src/ggrc/services/__init__.py
- src/ggrc/services/person_resource.py
- test/integration/ggrc/services/test_person_resource.py
This PR is a duplicate of https://github.com/google/ggrc-core/pull/6620 but built without mulitple assignees.
I am leaving both PRs opened since they have the same fix but different code due to backend changes on dev brach.
> GGRC-3604/3605 Add optimized end point for my tasks counts

- src/ggrc_workflows/migrations/versions/20171005114532_251191c050d0_add_assignee_roles_to_tasks.py
This reverts commit 67a750f2b5a54bc1a8f8686ee01f5cb6408c0f9c.
I will fix the ggrc-dev db manually.
> GGRC-3640 Revert "Add default to current user flag for assignees"

- docs/source/development/advanced_query_api.rst
"join" queries are removed
"limit" + "order_by" parameters are added
filter operators are updated
> DOCS Update QueryAPI proposal with actual docs

- src/ggrc/assets/javascripts/components/csv/export.js
In an export query data, there is the "fields" property that sets with can.List object, but it must be a regular array. It was missed in the next PR: https://github.com/google/ggrc-core/pull/6567/files#diff-0648c83a9188f60d8b70a5c6065a6a65R93
1) Via Tree View 3bbs for any entity click export or navigate to core export page directly;
2) Try to export any entity w/ and w/o filtering using Google Sheet or CSV;
NOTE: the same flow for snapshots works correctly.
**Actual:** 400 error when try to export GGRC entities via Export page (excluding snapshots).
**Expected:** Export should work w/o any UI errors and w/ correct final result on exported file.
Call `serialize()` method for "fields" property to transform can.List into array.
> GGRC-3647 400 err when try to export GGRC entities via Export page (excluding snapshots)

- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_query_api_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/contributions.py
- src/ggrc/services/person_resource.py
- src/ggrc/templates/dashboard/index.haml
- src/ggrc/views/__init__.py
- test/integration/ggrc/services/test_person_resource.py
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/lib/page/export_page.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
- test/selenium/src/lib/service/webui_service.py
This PR should bring performance improvements for displaying task counts on my work page
Note: 
you can test this PR merged and deployed here 
https://331-dot-ggrc-perf.appspot.com/dashboard
And the original 0.10.33 version here for comparison 
https://33-dot-ggrc-perf.appspot.com/dashboard
To check this PR, look at the time needed to get `my_work_count` request, which should be less than 1 second.
To test for bugs, go to my work page (hopefully with different users) and navigate all the tabs.
the counter in the tab must match the total counter in the tree view for all tabs.
This solution uses the same query generated for getting the counts in the query api, but without any boilerplate and with running a single query for all objects instead of running it in a loop for one object at a …
> GGRC-3602/3603/3604/3065 Speed up my work counts and all object counts

- src/ggrc/assets/javascripts/components/view-models/object-operations-base-vm.js
- src/ggrc/assets/javascripts/components/view-models/tests/object-operations-base-vm_spec.js
- src/ggrc_workflows/assets/mustache/task_groups/modal_content.mustache
- test/selenium/src/tests/test_snapshots.py
"Uncaught Error: can.view: No template or empty" error occurs while selecting workflow in task group modal window
1. Go to the My Work page
2. Controls tab
3. Hover over an arrow in the tree view > Map to this object
4. Select 'Task Group' object type
5. Click create and map new object
6. Set cursor into the Workflow field
There is a link to nonexistent template.
The same autocomplete is used without custom template: `/src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache`
> GGRC-3585 "Uncaught Error: can.view: No template or empty" error occurs while selecting workflow in task group modal window

- src/ggrc/assets/javascripts/components/object-mapper/object-mapper.js
In some cases appears a JS error when user try to create and map objects
**NOTE:** I couldn't reproduce the issue locally and on ggrc-qa instance
Steps to reproduce from QA:
1. Create a new program
2. Add tab > Objectives
3. Click 'Create and map new object' in Unified mapper
4. In New objective modal window type a title, insert reference url > Save and Close [^screenshot-1.png]
*Actual Result:* the system freezes, "Uncaught TypeError: Cannot read property 'uniqueId' of undefined" error is shown up in console. After refreshing the page and trying to create new objective with the same tile, the system shows a message that objective with this title is already exists. After searching objective in Unified mapper and mapping it an error occurs once again [^screenshot-2.png] …
> GGRC-3629 Fix JS error on mapping modal

- src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
> QUICK-FIX GGRC-3209 Export: Group select/deselect CA (questions)

- src/ggrc/assets/javascripts/components/issue/issue-unmap-item.mustache
- src/ggrc/assets/javascripts/components/tree/templates/tree-widget-container.mustache
- src/ggrc/assets/javascripts/components/tree_pagination/tests/tree_pagination_spec.js
- src/ggrc/assets/javascripts/components/tree_pagination/tree_pagination.js
- src/ggrc/assets/mustache/assessments/related-assessments-without-reuse.mustache
- src/ggrc/assets/mustache/assessments/related-assessments.mustache
- src/ggrc/assets/mustache/components/related-objects/related-issues.mustache
- src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache
Make the top row just a text - and only bottom one should be configurable.
> GGRC-2199 Request to view more than 10 assessments per page

- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_query_api_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/contributions.py
- src/ggrc/services/person_resource.py
- src/ggrc/templates/dashboard/index.haml
- src/ggrc/views/__init__.py
- test/integration/ggrc/services/test_person_resource.py
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/lib/page/export_page.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/service/webui_service.py
Release -> dev conflict resolution.
Files affected:
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
> QUICK-FIX resolve conflict test (Release to Dev)

- src/ggrc/settings/default.py
> QUICK-FIX Bump version to 0.10.34-Raspberry

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
1. Rename 'Effective Date' into 'Due Date'.
2. Add 'Due Date' field on Assessment Info pane/page - Assessment tab.
3. Due Date should be displayed by default in Assessment tree view.
4. User should be able to select any date (no restrictions).
There are no tests as no changes in logic.
> GGRC-3341 Rename assessment 'Effective Date' to 'Due Date'

- src/ggrc/services/common.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/services/__init__.py
- src/ggrc_workflows/services/resource.py
- test/integration/ggrc/api_helper.py
- test/integration/ggrc/services/test_common.py
- test/integration/ggrc_workflows/test_api_calls.py
This is new feature which adds possibility to send PATCH request to update statuses for bunch of CycleTasks in one request.
- Create 3 CycleTasks in 'Assigned' state.
- Send PATCH request to endpoint: "http://{app_path}/api/cycle_task_group_object_tasks".
Request body:
`[
{
"state": "InProgress",
"id": 1
},
{
"state": "InProgress",
"id": 2
},
{
"state": "InProgress",
"id": 3
}
]`
Response body:
`[
{
"status": "success",
"id": 1
},
{
"status": "success",
"id": 2
},
{
"status": "success",
"id": 3
}
]`
https://docs.google.com/spreadsheets/d/1Q0jUhEt7x7wVOffa1tVseA0CpGR9ZGAnWSxoUdBXtP0/edit#gid=0
> GGRC-3624/3625/3626 Add PATCH operation for bulk update

- src/ggrc/settings/default.py
> QUICK-FIX Bump version to 0.10.35-Raspberry

- docs/source/guidelines/git/how_to_write_a_commit_message.rst
Update our guidelines to reflect our current practices.
> DOCS Update PR title guidelines

- src/ggrc/migrations/versions/20170911141835_fa2f60a53c9_add_label_to_assessment.py
- src/ggrc/models/assessment.py
- src/ggrc/models/mixins/labeled.py
- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/services/test_query/test_basic.py
Add label in Assessment
* migration
* field
* search
* import/export
* tests
> GGRC-3254 Add first-class attributed 'Labels' for Assessment 

- src/ggrc/assets/javascripts/components/external-data-autocomplete/autocomplete-results.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/autocomplete-results.mustache
- src/ggrc/assets/javascripts/components/external-data-autocomplete/external-data-autocomplete.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/external-data-autocomplete.mustache
- src/ggrc/assets/javascripts/components/external-data-autocomplete/external-data-provider.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/inline-autocomplete-wrapper.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/tests/autocomplete-results_spec.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/tests/external-data-provider_spec.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/tests/inline-autocomplete-wrapper_spec.js
- src/ggrc/assets/javascripts/components/quick_form/quick_add.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/audits/modal_content.mustache
- src/ggrc/assets/mustache/components/access_control_list/access_control_list.mustache
- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
- src/ggrc/assets/mustache/components/custom-roles/custom-roles-modal.mustache
- src/ggrc/assets/mustache/components/form/fields/person-form-field.mustache
- src/ggrc/assets/mustache/components/people/editable-people-group.mustache
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
- src/ggrc/assets/stylesheets/_components.scss
- src/ggrc/assets/stylesheets/components/access-control-list/_access-control-list.scss
- src/ggrc/assets/stylesheets/components/external-data-autocomplete/_autocomplete-results.scss
- src/ggrc/assets/stylesheets/components/external-data-autocomplete/_external-data-autocomplete.scss
- src/ggrc/assets/stylesheets/components/form/fields/_person-form-field.scss
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/modal_content.mustache
- src/ggrc_workflows/assets/mustache/task_groups/modal_content.mustache
- src/ggrc_workflows/assets/mustache/wf_objects/approval_modal_content.mustache
This Pull Request contains Frontend part of [GGRC-1329](https://gojira.corp.google.com/browse/GGRC-1329)
- [GGRC-1782 Frontend: Creating autocomplete component](https://gojira.corp.google.com/browse/GGRC-1782)
- [GGRC-3526 Frontend: Integrate Autocomplete component](https://gojira.corp.google.com/browse/GGRC-3526)
- [GGRC-3525 Frontend: Create switcher](https://gojira.corp.google.com/browse/GGRC-3525)
[Requirements](https://docs.google.com/spreadsheets/d/1AbVAeDe4PcneRGPoErhgc_d7qutqw2M4K8PiHEexovo/edit#gid=0)
Execute the following code to run test server (node js):
```
const http = require('http');
const url = require('url');
const server = http.createServer(function(req, res) {
res.setHeader('Access-Control-Allow-Origin', '*');
res.setHeader('Access-Control-Allow-Headers', …
```
> GGRC-1782/GGRC-3526/GGRC-3525 Frontend: Creating autocomplete component

- docs/source/contributing/performance.rst
Added a few more performance guidelines that contributers should take into consideration.
> DOCS Add additional performance guidelines

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-state.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-wrapper.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-container_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-state_spec.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-status-filter_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-status-filter.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/models/display_prefs.js
- src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/advanced-search-utils.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
Request for the `count` is sent with each request in the treeview(if selected at least one status in multiselect dropdown).
1. Open Network tab in Chrome DevTool
2. Move on other tab or other page of treeview within tab
- Don't send query with statuses when all of them selected.
- It should positive affect on parsing query on back-end side and will generate simplier SQL to DB.
- Will avoid additional requests for the counts in some cases(by default all statuses selected for most of objects), GGRC-2712
> GGRC-3680 Simplify of request with statuses for tree view

- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
- src/ggrc/assets/mustache/components/custom-roles/custom-roles-modal.mustache
- src/ggrc/assets/stylesheets/components/people-group/_people-group.scss
Broken styles of people group titles
1. Invoke New Assessment modal window
2. Look at the custom role fields
_Actual Result:_ Formatting of Custom role fields is broken in New/Edit Assessment modal window
_Expected Result_: Formatting of Custom role fields should not be broken in New/Edit Assessment modal window
Added separate class for "deletable people group" titles
> GGRC-3711 Formatting of Custom role fields is broken in New/Edit Assessment modal window

- src/ggrc/assets/javascripts/components/tree/templates/tree-header.mustache
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/components/assessment/info-pane/info-pane.mustache
*MOCK-UPS:*
(Approved) https://drive.google.com/corp/drive/folders/0B1Uh7PxmdYVwWnludzBUN2FPczQ
AC1. Allow user to add label(s) for Assessments:
- 'Labels' dropdown control should be displayed on 'Add / Edit Assessment' pop-up.
- 'Labels' dropdown control should have options: Needs Discussion, Needs Rework, Followup, Auditor pulls evidence.
- 'Labels' should be optional
- 'Labels' should be displayed on 'Assessment info pane / page'.
- 'Labels' column should be displayed by default in tree view.
AC2. Allow user to sort assessments by labels in tree view.
AC3. Allow user to search Assessment(s) by label(s):
- filtering;
- advanced search;
- global search.
AC4. Allow user to import labels attribute for Assessment:
- Add 'Labels' column in import spreadsheet for …
> GGRC-3253 FE: Add first-class attributed 'Labels' for Assessment

- src/ggrc/assets/mustache/base_templates/assignable_extended_info.mustache
- src/ggrc/assets/mustache/directives/autocomplete_result.mustache
Rename Start date to Due date for assessment in LHN
> GGRC-3341 Rename Start date to Due date for assessment in LHN

- src/ggrc/assets/javascripts/components/assessment/info-pane/confirm-edit-action.js
- src/ggrc/assets/javascripts/components/assessment/tests/confirm-edit-action_spec.js
- src/ggrc/assets/javascripts/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
- src/ggrc/assets/js_specs/models/object_state_spec.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/components/object-state-toolbar/object-state-toolbar.mustache
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
**Depends on:** 
Add new state "Rework Needed" for assessment.
AC1. Rename "Reject" button to 'Needs Rework' state for Assessment.
AC2. Assessment should be moved to in 'Rework Needed' state on clicking 'Rework Needed' button.
AC3. From 'Rework Needed' state assessment can be moved only to 'In Review', 'Completed (no verification)', 'Deprecated'.
https://docs.google.com/spreadsheets/d/1RW2mg-kIRW2s1oabI8odPuZK_na_QBT-wFUGBHU2SPI/edit#gid=803691936
AC4. update export/import
AC5. update audit summary chart (same red color)
AC6. update tree view, filter by states in search and adv search
AC7. Backwards compatibility - make sure all existing states keep working - Investigate if any migration needed here on BE.
**Note:** Currently the backend prohibits move an assessment from 'Rework needed' …
> GGRC-3223 FE: Add 'Rework Needed' state for Assessment

- Dockerfile
- docs/source/backend/automapping.rst
- docs/source/conf.py
Automappings docs are meager and outdated.
Run build_docs.
- removed obsolete docs
- updated docs for rules
- added an example
- added a few notes on the implementation
**Note**: to make `build_docs` work, make sure to rebuild the container or install `graphviz` inside.
> GGRC-3716 Update automappings docs

- src/ggrc/services/__init__.py
https://github.com/google/ggrc-core/pull/6611#pullrequestreview-730191:
@zidarsk8:
We should not use relative imports as per our guidelines:
https://google.github.io/styleguide/pyguide.html?showone=Imports#Imports
The other code here is before we started to follow those, and instead of making this line fit, it would be better if we updated the rest of the imports here instead.
> QUICK-FIX Remove relative imports

- src/ggrc/assets/javascripts/components/show-more/show-more.js
- src/ggrc/assets/javascripts/components/show-more/tests/show-more_spec.js
- src/ggrc/assets/mustache/components/custom-attributes/custom-attributes.mustache
- src/ggrc/assets/mustache/components/object-popover/related-assessment-popover.mustache
- src/ggrc/assets/stylesheets/components/custom-attributes/_custom-attributes.scss
- src/ggrc/assets/stylesheets/components/form/_form-validation-icon.scss
On the assessment info page in related assessment tab in more-info popup if title of CA is too long then it overflows.
1. Have GCA for Assessment with a long title
2. Have audit with control snapshot
3. Generate two assessments based on control snapshot
4. Navigate to assessment info pane > Related Assessments tab
5. Open More info popup and look at GCA long title: is not cut off
*Actual Result:* Long title of GCA is not cut off in the More info popup
*Expected Result:* Long title of GCA should be cut off in the More info popup
Remove redundant css-properties and add another to prevent overflowing.
Out of scope:
1) In `show-more` component display difference between visible and invisible items (approved by UX-designer).
2) Fix help-text for CA-labels in popover to …
> GGRC-3560 Long title of GCA is not cut off in the More info popup

- src/ggrc/assets/javascripts/apps/custom_attributes_wrap.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-state.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-wrapper.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-container_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-state_spec.js
- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls.js
- src/ggrc/assets/javascripts/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc/assets/javascripts/components/ca-object/ca-object-value-mapper.js
- src/ggrc/assets/javascripts/components/gca-controls/gca-controls.js
- src/ggrc/assets/javascripts/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc/assets/javascripts/components/object-popover/related-assessment-popover.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-status-filter_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-status-filter.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/display_prefs.js
- src/ggrc/assets/javascripts/plugins/tests/ca_utils_spec.js
- src/ggrc/assets/javascripts/plugins/tests/state-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/advanced-search-utils.js
- src/ggrc/assets/javascripts/plugins/utils/ca-utils.js
- src/ggrc/assets/javascripts/plugins/utils/state-utils.js
Cherry-pick commit from PR https://github.com/google/ggrc-core/pull/6402
Currently we can't import specific utils file in page specific bundles because `GGRC.Utils` namespace not defined.
Utils migrated on ES6 module.
Reduced number of changes in the original PR
> QUICK-FIX Migrate ca-utils on module syntax

- src/ggrc/utils/rules.py
- test/unit/ggrc/utils/test_rules.py
Some of map: and unmap: columns are missing on Issue CSV template:
- Program
- Cycle task
- Issue
- Person
- Project
- Risk Assessment
Export a CSV template for Issue on Import page.
This PR adds missing rules into rule set for Issue.
The default (string-like) rules are interpreted as "this object can be mapped and unmapped directly", so just listing the missing models does its work.
The expected result in the unit test was checked to be the same as the type list in the requirements.
Note: Person mapping works incorrectly right now, we have a ticket for it.
> GGRC-3609 Add missing map and unmap columns for Issue

- PULL_REQUEST_TEMPLATE.md
> QUICK-FIX Fix PR template links

- src/ggrc/assets/stylesheets/modules/_notifications.scss
On flash notification white message text is transparent, because on the parent element (black background) applied opacity: 0.76, and it is applied for text. So when we scroll page through text (which color is black) the notification is hard to read.
1. Have a program with any type of GCA
2. On the Info pane fill GCA and save
3. Look at the error message frame: title/value of GCA is visible through message frame
*Actual Result:* Message frame is semitransparent
*Expected Result:* White text on floating message should not be semitransparent. Black background can be still semitransparent. 
Apply transparency only for the black background of notification.
> GGRC-3661 Message frame is semitransparent

- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
**Includes:**
**GGRC-3747** Needs Rework/Verify buttons are increased if click complete button:
In container for state buttons not enough space for "Needs Rework" button, so word "Rework" moves to the second line.
**GGRC-3750**  'Rework needed' label is shifted while hovering over Assessment's long title:
When we hover across assessment title an edit icon appears, so in container for the state label and the edit-icon is not enough space.
**GGRC-3747** Steps to reproduce:
1. Have assessment on the audit page
2. Navigate to Assessment Info pane and add a verifier
3. Click Complete button and look at the screen
*Actual Result:* Needs Rework/Verify buttons are increased if click complete button
*Expected Result:* Needs Rework/Verify buttons should not increase if click complete button …
> GGRC-3747/GGRC-3750 Needs Rework/Verify buttons are increased if click complete button

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-wrapper.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc/assets/javascripts/components/tree/sub-tree-wrapper.js
- src/ggrc/assets/javascripts/components/tree/tests/sub-tree-wrapper_spec.js
- src/ggrc/assets/javascripts/components/tree/tests/tree-widget-container_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-header.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results-columns-configuration.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/components/view-models/tests/tree-item-base-vm_spec.js
- src/ggrc/assets/javascripts/components/view-models/tree-item-base-vm.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/control.js
- src/ggrc/assets/javascripts/models/issue.js
- src/ggrc/assets/javascripts/models/person.js
- src/ggrc/assets/javascripts/models/simple_models.js
- src/ggrc/assets/javascripts/plugins/tests/current-page-utils_spec.js
- src/ggrc/assets/javascripts/plugins/tests/utils/tree-view-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
AC1. All objects should be sorted by default by Last Updated Date in:
- tree view;
- global search;
- unified mapper;
- generate assessment pop-up;
- advanced search.
AC2. 'Last Updated' column should be displayed by default.
Where:
- object tree view;
- global search;
- unified mapper;
- generate assessment pop-up.
For objects:
- Standards
- Regulations
- Sections
- Objectives
- Controls
- Products
- Systems
- Processes
- Access Groups
- Assessments
- Clauses
- Contracts
- Data Assets
- Facilities
- Issues
- Markets
- Org Groups
- Policies
- Programs
- Projects
- Risks
- Threats
- Vendors
- Audit
- Risk Assessment
- Workflow
- Assessment Template
- Person
OUT OF SCOPE:
Objects:
- Task Group Tasks;
- Task Groups;
- Cycle Task Group Object Tasks.
Pages:
My Tasks page, Tasks tab on an 'All …
> GGRC-3630 Sort by default by Last Updated Date all objects lists

- src/ggrc/assets/javascripts/components/inline/inline.js
- src/ggrc/assets/mustache/assessments/header.mustache
- src/ggrc/assets/mustache/components/inline/inline.mustache
- src/ggrc/assets/stylesheets/components/inline/_inline.scss
Possible to remove assessment title while inline editing
1. Have assessment on the audit page
2. Navigate to Assessment Info pane
3. Click edit icon for title > Remove title > Save
**Actual Result:** Possibility to delete Assessment's title while inline editing 
**Expected Result:** User should not be able to delete Assessment's title as title is a mandatory field
Add 'mandatory' attribute to inline-edit-control component
> GGRC-3518 Possibility to delete Assessment's title while inline editing

- src/ggrc_workflows/services/resource.py
- test/integration/ggrc_workflows/test_api_calls.py
Log all changes for cycle tasks updated over bulk update action. 
Update cycle tasks over bulk update and check if changes are saved in revisions table.
Add log event action on bulk update operation.
> GGRC-3737 Log event on bulk update

- README.md
For semantic understanding.
For proper & clarity of understanding on the documentation.
It don't get involved the code. Just this file. No need of test. 
> DOCS Some minor fixes on

- test/integration/ggrc_workflows/test_api_calls.py
Changes that was done over bulk update action should be searchable. 
Make bulk update over cycle task. Try to search updated instance over query api. 
Indexer should update full text records on each commit procedure. In this pr i add tests to check if it's true or not.
> GGRC-3738 Full text search on bulk update

- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/components/mapped-objects/_mapped-objects.scss
After moving Global Attributes to a separate panel on info-pane, additional scrolling for comments became unnecessary. Also there is redundant `:after` element with transparent gradient.
1. Navigate to Assessment Info page
2. Add long text comment > Click Add button
3. Look at the added comment [^screenshot-1.png]
4. Scroll up/down: scrolling over comment box and Add button
*Actual Result:* Comment styles are broken on the Assessment Info pane
*Expected result:* Comment styles should not be broken on the Assessment Info pane.
*NOTE:* during the implementation of the issue check the expected behavior with UX person
Remove absolute positioning for comments side-bar
Increase margin between comments
> GGRC-3729 Comment styles are broken on the Assessment Info pane

- docs/source/contributing/git/how_to_write_a_commit_message.rst
This commit just adds general guidelines that should help with cleaning
up our commit history and with understanding past code when debugging
and refactoring.
> DOCS Add basic guidelines for commit content

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- test/integration/ggrc/converters/test_import_controls.py
The error occurs: GGRC-3284 "Uncaught TypeError: this.attr is not a function" error occurs while importing csv file.
The issue was that during import handler could not access an attribute of the object which is not bound to a session anymore.
There was a try to fix the issue in #6417, but it was reverted then.
1. Have csv file with Section object (attached to the Jira ticket)
2. Import csv file
Expected Result: no error are displayed while importing
The object was missing in a session because it's row was marked as ignored and then expunged. The issue was that the rows with duplicate column values are marked as ignored, but the rows with the duplicate slugs represent the same object and if we mark one of these rows as ignores, then the …
> GGRC-3284 Object is expunged from a session

- src/ggrc/assets/javascripts/components/people/templates/people-group-modal.mustache
- src/ggrc/assets/stylesheets/components/external-data-autocomplete/_autocomplete-results.scss
- src/ggrc/assets/stylesheets/components/people-group/_people-group.scss
HR API Integration is not applied for Extend Person control
Precondition:
1. HR API 'On'
1. Have an Assessment on the Audit page
2. Navigate to Assessment Info pane
3. Add at least 5 Verifiers 
4. Click 'See more' link and set cursor into Add person field: no @google.com accounts are displayed
*Actual Result:* HR API Integration is not applied for Extend Person control
*Expected Result:* HR API Integration should be applied for Extend Person control
`people-group-modal` component was added to the app w/o `external-data-autocomplete`.
In the PR I add external-data-autocomplete component and modify style to show results correctly.
> GGRC-3790 HR API Integration is not applied for Extend Person control

- src/ggrc_workflows/notification/__init__.py
- src/ggrc_workflows/notification/notification_handler.py
- src/ggrc_workflows/notification/pusher.py
- test/integration/ggrc_workflows/test_api_calls.py
Notifications should be update in correct order after bulk update action. 
Update cycle task over bulk update action. Check notification is correct. 
Change notification handler to use list of objects.
> GGRC-3739 Notification handling for bulk update

- src/ggrc/assets/mustache/assessments/header.mustache
Global Reader can change assessment state to Deprecated state.
Cause: In template of 3 bb's menu for `Deprecate` button no check for allowance to update instance.
1. Have assessment created by user1 (admin)
2. Log as Global reader (globreader@gmail.com (engage007) and open Assessment Info page
3. Click 3 bb's menu  > Select Deprecate
*Actual Result:* Global Reader can change assessment state to Deprecated state
*Expected Result:* Global reader with read permissions should not be able to update assessment. Deprecated control should be hidden.
NOTE: after refreshing the page Assessment is moved to the initial state
Wrap `<object-change-state>` component into `{{#is_allowed}}` mustache helper which check permissions to update an instance.
> GGRC-3734 Global Reader can change assessment state to Deprecated state

- src/ggrc/assets/javascripts/components/external-data-autocomplete/external-data-autocomplete.js
- src/ggrc/assets/javascripts/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
**GGRC-3798:**
When add a person as a verifier, such person is duplicated in Creator/Assignee fields if such person is already creator or assignee
**GGRC-3799:**
Cannot add a person as a Verifier if such a person already exists in Creator/Assignee fields
**GGRC-3798:**
1. Have Assessment where user1 is a Creator and Assignee
2. Navigate to Assessment Info pane
3. Add user1 as Verifier: user1 is shown up in Creator and Assignee fields
*Actual Result:* When add a person as a verifier, such person is duplicated in Creator/Assignee fields if such person is already creator or assignee
*Expected Result:* When add a person as a verifier, such person should not be duplicated in Creator/Assignee fields if such person is already creator or assignee
**GGRC-3799:**
Steps to …
> GGRC-3798/GGRC-3799 - Use cached model if it exists.

- src/ggrc/assets/stylesheets/_mixins.scss
- src/ggrc/assets/stylesheets/components/tree/_sub-tree-wrapper.scss
- src/ggrc/assets/stylesheets/components/tree/_tree-view.scss
- src/ggrc/assets/stylesheets/mixins/_disabled.scss
Relates to: https://github.com/google/ggrc-core/pull/6695
On the "My Task" page cycle-task-actions buttons is not disabled while task state changing. In this PR https://github.com/google/ggrc-core/pull/6695 disabling applied only for items in sub-tree.
1. Create repeat of workflow
2. Set at least 5 tasks and Activate workflow
3. Go to "My Task" page
4. Hover over tasks and quickly click start, finish, decline, verify controls to change tasks states
*Actual Result:* Conflict message is displayed while verifying cycle tasks
*Expected Result:* Conflict message should not display while verifying cycle tasks
Move css-styles for `.item-actions.disabled` from `.sub-tree-item` scope into the global scope.
> GGRC-3547 Conflict message is displayed while verifying cycle tasks

- src/ggrc/assets/javascripts/components/issue/issue-unmap-item.js
- src/ggrc/assets/javascripts/components/issue/tests/issue-unmap-item_spec.js
Unmap button for original object is displayed in 3 bb's menu on the Issue Info page
Precondition:
2. Created Issue with mapped control snapshot
1. Go to the Issue Info page
2. Controls tab
3. Navigate to Control Info pane > 3 bb's menu
4. Look at the screen: 'Unmap from issue' button is dislplayed
5. Click 'Unmap from issue' button.
*Actual Result:* Nothing happens.
*Expected Result:* Floating error message should be shown "Unmapping cannot be performed. Please unmap Issue (ISSUE-1) from Control version (CONTROL-2), then mapping with original object will be automatically reverted."
Show message if there is no relationship between issue and another object
> GGRC-3562 Unmap button for original object is displayed in 3 bb's menu on the Issue Info page

- src/ggrc/migrations/versions/20171005145516_33d043d8ba29_migrate_assignees_to_acl.py
- src/ggrc/models/hooks/relationship.py
- test/integration/ggrc/models/test_assessment.py
If Snapshot is unmapped from Assessment, AC mapped roles can be removed for other Assessments were this Snapshot and same assignees used.
Create 2 Assessments.
Assign same user with Creator permissions to both Assessments and map one snapshot to both of them.
Unmap snapshot from first Assessment.
Check that assigned user has access to snapshot in second Assessment and Audit.
Add parent_id to unique constraint of ACL.
Use parent_id in calculation of ACL instances that should be created.
Correct relationship deletion hook to remove ACLs for proper object only.
Right before merging this pull request, we must downgrade the dev DB to before #6629
> GGRC-3820 Snapshot unmapping in one Assessment can affect other Assessments

- src/ggrc/migrations/versions/20171101081955_413d6c32ccf5_set_acl_roles_for_regulation.py
- src/ggrc/models/hooks/access_control_list.py
- src/ggrc/models/hooks/relationship.py
- src/ggrc/models/relationship.py
- test/integration/ggrc/access_control/test_ac_rbac.py
- test/integration/ggrc/models/test_assessment.py
Allow Assessment Assignee to READ Objectives and Regulations related to Controls (snapshots) mapped to Assessment.
Create snapshots of Control, Objective, Regulation mapped to each other. Create Assessment and map snapshot of Control to this Assessment (don't map snapshots of Objective and Regulation to Assessment). Assigned to Assessment user should have read access to all snapshots.
In Relationship creation hook check if new snapshot mapped and check if this is Snapshot of Control and it has related snapshot of Objective and Regulations. For related snapshots of Objective and Regulations create roles with read access.
> GGRC-3534 Expand Assignee rights for Regulation and Objective snapshots

- src/ggrc/assets/javascripts/components/csv/import.js
- src/ggrc/assets/javascripts/components/csv/templates/csv-import.mustache
- src/ggrc/assets/javascripts/components/csv/test/import_spec.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/converters/import_helper.py
- src/ggrc/utils/error_handlers.py
- src/ggrc/views/converters.py
- src/ggrc_gdrive_integration/__init__.py
- src/ggrc_gdrive_integration/file_actions.py
- src/requirements.txt
- test/integration/ggrc/__init__.py
- test/integration/ggrc_gdrive_integration/test_gdrive_auth.py
It is needed to make possible importing of a csv file either from a local PC or a gDrive.
Go to /import page and import a valid/invalid csv file from both: local drive and gDrive
I have implemented the required file actions with gdrive files including the required app authorization to use gDrive. Authorization is checked once user gets to /import or /export url. In case the app is not authorized by user to work with gdrive, it redirects to the google api auth page.
If user got to /export page from any page offering to export a list of items, the export context is saved and at the end of the auth process user is redirected back to export page with the correct context.
> GGRC-3252/GGRC-3177 Allow to import from Google Sheet

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-group.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-group.js
- src/ggrc/assets/javascripts/components/base-objects/pagination.js
- src/ggrc/assets/javascripts/components/base-objects/tests/pagination_spec.js
- src/ggrc/assets/javascripts/components/issue/issue-unmap-item.js
- src/ggrc/assets/javascripts/components/issue/tests/issue-unmap-item_spec.js
- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/javascripts/components/tree/sub-tree-item.js
- src/ggrc/assets/javascripts/components/tree/tree-item.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/components/tree_pagination/tests/tree_pagination_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/components/view-models/advanced-search-container-vm.js
- src/ggrc/assets/javascripts/components/view-models/tests/advanced-search-container-vm_spec.js
- src/ggrc/assets/javascripts/components/view-models/tests/tree-item-base-vm_spec.js
- src/ggrc/assets/javascripts/components/view-models/tree-item-base-vm.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
Base VMs defined in global `GGRC` namespace.
Migration on module syntax
> QUICK-FIX Migrate base view-models on module syntax

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/assessment_templates/tree_add_item.mustache
- src/ggrc/assets/mustache/audits/dropdown_menu.mustache
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
- src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
"Uncaught TypeError: Cannot read property 'reify' of undefined" error occurs while saving Risk Assessment
2. Add tab > Risk Assessment
3. Invoke New Risk Assessment modal window and fill all required fields> Save
**Actual Result:** "Uncaught TypeError: Cannot read property 'reify' of undefined" error occurs while saving Risk Assessment
**Expected Result:** no error are displayed while saving Risk Assessment
Program object is required for saving RiskAssessment and should be provided for modal.
> GGRC-3793 Impossible to save Risk Assessment

- bin/do_deploy
It is dangerous to just deploy without a confirmation, as it is hard
to abort the deployment if the settings are wrong.
Run `./bin/deploy <any-instance>` and wait until the deployment step.
If the user responds with `no`, `gcloud app deploy` will return a non-zero code and the script will be stopped because of `errexit`.
The migrations are now triggered after the deployment, so it is safe to cancel the deployment process.
> QUICK-FIX Return the prompt before the deployment

- bin/do_deploy
- extras/deploy/settings-template.sh
- src/ggrc/settings/default.py
Add autoincrement support for deployment
Deploy the same app multiple times and check the serving version.
I have key text in the version field "use ggrc version and hash" will generate a version number for the current ggrc app version and the current commit hash. The version will be modified and trimmed to match requirements for gae app version name.
> GGRC-3813 Add support for autoincrement version numbers

- src/ggrc/assets/javascripts/components/people/editable-people-group.js
User cannot add a person to custom role field on the object Info pane using inline edit
1. My work page > Controls tab
2. Navigate to Control Info pane and click on Edit icon of Principal Assignee field
3. Try to add a person: no success
**Actual Result:** GGRC-DEV: User cannot add a person to custom role field on the object Info pane using inline edit
**Expected Result:** User should be able to add a person to custom role field on the object Info pane using inline edit
Add missed imports.
> GGRC-3856 User cannot add a person to custom role field on the object Info pane using inline edit

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/mapped-objects/mapped-controls.js
- src/ggrc/assets/javascripts/components/assessment/mapped-objects/tests/mapped-controls_spec.js
- src/ggrc/assets/javascripts/components/assessment_templates/assessment_templates.js
- src/ggrc/assets/javascripts/components/issue/issue-unmap-item.js
- src/ggrc/assets/javascripts/components/issue/tests/issue-unmap-item_spec.js
- src/ggrc/assets/javascripts/components/mapped-counter/mapped-counter.js
- src/ggrc/assets/javascripts/components/mapped-objects/mapped-objects.js
- src/ggrc/assets/javascripts/components/modal-connector.js
- src/ggrc/assets/javascripts/components/object-tasks/object-tasks.js
- src/ggrc/assets/javascripts/components/related-objects/related-documents.js
- src/ggrc/assets/javascripts/components/related-objects/related-evidences-and-urls.js
- src/ggrc/assets/javascripts/components/related-objects/related-objects.js
- src/ggrc/assets/javascripts/components/tests/modal-connector_spec.js
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/plugins/autocomplete.js
- src/ggrc/assets/javascripts/plugins/tests/current-page-utils_spec.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_query_api_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/query-api-utils.js
- src/ggrc/assets/javascripts/plugins/utils/snapshot-utils.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
Currently we can't import specific utils in small bundles because root namespace GGRC.Utils not defined there and we have to import one with all not needed utils or check and create namespace if it not exist, but both option not good since we have Import/export syntax.
Try to import some util without ggrc_utils.js file
Migrate query-api-utils on module syntax
> GGRC-3756 Migrate query api utils on module syntax

- src/ggrc/assets/javascripts/components/add-issue-button/add-issue-button.js
Reverts google/ggrc-core#6804
This pull requests leads to data corruption if a Global Creator or Global Reader raises an Issue in an Assessment
> GGRC-3862 Revert "GGRC-3857 Add context to raise issue button"

- src/ggrc/assets/javascripts/components/effective-dates/effective-dates.js
- src/ggrc/assets/javascripts/components/form/fields/date-form-field.js
- src/ggrc/assets/javascripts/components/form/fields/dropdown-form-field.js
- src/ggrc/assets/javascripts/components/issue-tracker/modal-issue-tracker-fields.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/index.js
- src/ggrc_workflows/assets/javascripts/components/cycle-task-group-object-task/cycle-task-group-object-task.js
- src/ggrc_workflows/assets/javascripts/components/repeat-on-button.js
On edit modals not displayed 'datepicker' and 'dropdown' components
Open edit modal for any object
Added imports
> QUICK-FIX Add imports for missed components on edit modals

- src/ggrc/assets/mustache/components/advanced-search/advanced-search-filter-attribute.mustache
Lesser then/Greater then work vise versa in Advanced Search filter
2. Click advanced search icon and filter by "Last deprecated date" "Lesser than" "2016"
3. Click apply and look at the search results: controls greater than 2016 are displayed
*Actual Result:* Lesser then/Greater then work vise versa in Advanced Search filter
*Expected Result:* Lesser then/Greater then should work correctly in Advanced Search filter
Swap operator keys.
> GGRC-2792 Lesser then/Greater then work vise versa in Advanced Search filter

- src/ggrc/assets/javascripts/models/mixins.js
Server returns _undefined_ instead of _Audit_ object for _Issue_ page
1. Go to My work page
2. Click 'Create object' > Issue
3. Fill the required fields and save
_Actual Result_: GGRC-DEV: "Uncaught TypeError: Cannot read property 'issue_tracker' of undefined" error occurs while creating an Issue from My Work page
_Expected Result_: no errors should be shown while creating an issue
Check _Audit_ object before use _issue_tracker_ property.
> GGRC-3870 "Uncaught TypeError: Cannot read property 'issue_tracker' of undefined" error occurs while creating an Issue from My Work page

- src/ggrc_gdrive_integration/assets/javascripts/controllers/gapi_controllers.js
Modals chunk isn't loading for gAPI auth
1. Go to Import page
2. Click 'Choose file to import' button screenshot-1.png, screenshot-2.png
Actual Result: GGRC-DEV: Script Error is displayed while clicking 'Choose file to import' button on the Import page
Expected Result: No errors are displayed while clicking 'Choose file to import' button on the Import page
Added dynamic loading of modals chunk
> GGRC-3866 Loading modals chunk for gAPI auth

- src/ggrc/assets/javascripts/components/assessment/assessment-people.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control-group.js
- src/ggrc/assets/javascripts/components/related-objects/tests/related-people-access-control-group_spec.js
- src/ggrc/assets/mustache/components/assessment/assessment-people.mustache
User is able to add Creator/Assignee/Verifier to archived assessment
1. Have an adit with created Assessment
2. Audit and Assessment are archived
3. Navigate to Assessment Info pane and add Creator/Assignee/Verifier > Save
**Actual Result:** User is able to add Creator/Assignee/Verifier to archived assessment
**Expected Result:** User should not be able to add Creator/Assignee/Verifier to archived assessment
Prevent editing when instance archived flag is true.
> GGRC-3877 User is able to add Creator/Assignee/Verifier to archived assessment

- src/ggrc/assets/javascripts/components/tasks-counter/tasks-counter.js
- src/ggrc/assets/javascripts/components/tasks-counter/tests/tasks-counter_spec.js
- src/ggrc/assets/mustache/components/page-header/page-header.mustache
**Refresh** method of **Person** model returns rejected deferred object because model doesn't have **href** and **selfLink** properties
In this case **init** method (modals_controller.js) doesn't call **after_preload** method.
1. As admin user open My work page > Objective tab
2. Open [https://ggrc-test.googleplex.com/objectives/508](https://ggrc-test.googleplex.com/objectives/508) page
3. On the objective Info page click Edit Objective in tree bb's menu
4. Look at the screen: the app freezes w/o any error in console
_Actual Result_: The app freezes while opening New/Edit modal window
_Expected Result_: The app should not freeze while opening New/Edit modal window
Set current user instead of current user id for tasks-counter.
Because tasks-counter adds wrong person object to cache when …
> GGRC-3789 The app freezes while opening New/Edit modal window

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/mustache/assessments/dates_list.mustache
- src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
1. Change 'Stop Date' label into 'Last Deprecated Date' label.
2. Make changes for Assessment.
3. Add 'Last Deprecated Date' on:
Assessment info pane / page - Other Attributes;
'Set visible fields for <object>' pop-up (on widget and unified mapper);
as a column on Assessment tab;
as a column on Global Search;
Export spreadsheet;
4. Date should be autopopulated with current date, when Object status is changed to 'Deprecated'.
5. If deprecated object is moved to another state, then keep date unchanged.
6. User should not be able to update date manually.
Remove 'Stop Date' / 'Last Deprecated Date' from:
'New Assessment' pop-up;
'Edit Assessment' pop-up;
Import spread sheet.
Import page.
7. Allow user to search Assessments by Last Deprecated Date (advanced search).
8. Allow user to filter …
> GGRC-3500 Change Stop Date to Last Deprecated Date for Assessment

- PULL_REQUEST_TEMPLATE.md
Dependencies should be the first thing a reviewer sees to give as much
context as needed before starting the review itself.
Open A PR and check if dependecies section is suggested on the top.
> DOCS Move dependencies to the top of PR template

- src/ggrc_basic_permissions/roles/Reader.py
- test/integration/ggrc/automapper/test_automappings_rbac.py
- test/integration/ggrc/test_csvs/issue_automapping_setup.csv
The previous fix missed the case for Readers.
See #6819, replace Creator with Reader.
"Issue" permission is added to global permissions for Reader
> GGRC-3860 Allow Global Reader to create Issue

- src/ggrc/models/hooks/assessment.py
https://gojira.corp.google.com/browse/GGRC-3865
https://gojira.corp.google.com/browse/GGRC-3864
https://gojira.corp.google.com/browse/GGRC-3854
https://gojira.corp.google.com/browse/GGRC-3855
https://gojira.corp.google.com/browse/GGRC-3831
Please follow ticket in a section above.
Perform sync of external issue upon assessment update by sending whole state to override issue parameters when any of trackable properties gets changed.
Change also fixes some minor issue in external issue update flow.
> GGRC-3865 Fix for syncing issue upon assessment update

- src/ggrc/assets/javascripts/components/custom-roles/templates/custom-roles-modal.mustache
- src/ggrc/assets/mustache/components/gca-controls/gca-controls.mustache
- src/ggrc/assets/mustache/custom_attribute_definitions/tree.mustache
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
- src/ggrc/assets/stylesheets/_widget.scss
- src/ggrc/assets/stylesheets/components/custom-attributes/_custom-attributes.scss
- src/ggrc/assets/stylesheets/components/form/_ggrc-form.scss
- src/ggrc/assets/stylesheets/components/info-pane/_info-pane.scss
- src/ggrc/assets/stylesheets/components/people-group/_people-group.scss
GCAs long title is not cut off
1. As admin go to Administration page and add GCA with any type with long title to Assessment
2. Open audit page and invoke new/edit Assessment modal window
**Actual Result:** GCAs long title is not cut off
**Expected Result:** GCAs long title should be cut off
Update css styles
> GGRC-3873 Cut off GCAs long titles

- src/ggrc/assets/javascripts/components/people/editable-people-group.js
- src/ggrc/assets/javascripts/components/people/tests/editable-people-group_spec.js
- src/ggrc/assets/mustache/components/custom-roles/custom-roles.mustache
- src/ggrc/assets/mustache/components/people/editable-people-group.mustache
User has the possibility to add a person from Person list on snapshot info pane and in the Comparison window on the Audit page.
Case 1:
1. Have a program with mapped control, at least 5 admins are added to Admin field in control, audit mapped to program
2. Have an audit with control snapshot
3. Go to the Program page and edit a control, e.g. description
4. Refresh the Audit page > Controls tab
5. Open Comparison window by clicking 'Get the latest version' link on the Control Info pane
6. Click 'See more' link > add a new person in extend person control: conflict error message is shown
**Actual Result:** User has the possibility to add a person from People list in the Comparison window on the Audit page. A conflict error message is shown while adding a person.
**Expected Result:** Adding a …
> GGRC-3814/GGRC-3815/GGRC-3907 Prevent updating people lists for snapshots

- src/ggrc/migrations/versions/20171115121711_3d505e157ab7_cleanup_unused_tables_columns.py
- src/ggrc_risks/migrations/versions/20171115131005_3e667570f21f_cleanup_unused_tables_and_columns.py
We have a lot of tables and columns that are no longer used. This PR cleans up our data model a little bit.
Removes some of the columns and tables that are no longer needed.
> QUICK-FIX Cleanup unused tables and columns

- src/ggrc/assets/stylesheets/modules/_tree-content.scss
Left and right paddings are different.
1. As admin go to Administration
2. Click Custom Attributes/Custom roles tab in Horiz Nav bar
3. Click ">" sign next to the item list title
4. Look at the padding in the second tier: there is no padding at right, see [^screenshot-1.png]
*Actual Result:* There is no padding in the second tier in Custom Attributes/Custom roles tabs
*Expected Result:* Make padding at right in the second tier in Custom Attributes/Custom roles tabs as it exist at left 
Change padding for this case.
> GGRC-2650 Incorrect padding in Custom Attributes/Custom Roles tabs

- src/ggrc/assets/mustache/issues/modal_content.mustache
1. On the audit page invoke New Issue modal window
2. Fill in mandatory fields and fill Test plan field> Save
3. Look at Test plan field in Issue info pane 
**Actual Result:** "Test plan" and "REMEDIATION PLAN" fields are differ in UI
**Expected Result:** Rename "Test plan" to "REMEDIATION PLAN" in Issue modal window
> GGRC-1692 Rename 'Test Plan' to 'Remediation Plan' in issue modal

- src/ggrc/assets/javascripts/components/people/tests/editable-people-group_spec.js
debugger was committed by mistake and should be removed.
> QUICK-FIX Remove debugger

- src/ggrc/assets/javascripts/controllers/info_widget_controller.js
JS error occurs on info tab of any object that wait for task for approval (buttons `Approve` and `Decline` are active)
Open page of object that wait for task for approval and move on info tab
Modal's chunk is loading for info tab
> GGRC-3950 Load modal's chunk for info tab

- test/selenium/src/lib/constants/messages.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest/template_provider.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/filter_utils.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
Improve encoding (decoding) overall for selenium test automation framework's procedures and add extra logging for server's responses deserialization 
- Refactor string utils (particularly random methods, add string-escape, exclude potential issues related symbols )
- Refactor factory for entities accordingly
- Add try catch and logging for responses
- make PUT and POST requests using string-escape
- correct msg's comparison procedures
- and more...
> QUICK-FIX [TAF] Improve encoding (decoding) procedures and add extra logging for responses' deserialization 

- src/ggrc/converters/base.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/converters/handlers.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc_workflows/converters/test_column_definitions.py
- test/integration/ggrc_workflows/converters/test_import_workflow_people.py
User should be able to import WorkflowMembers, WorkflowManagers for Workflows. In CSV file only Workflow should be present, don't mix with others objects (TaskGroups, TaskGroupTasks).
1. Create/update workflow with Members and Managers via import.
2. Check that created/updated workflow contains valid related people number.
For more details check comments to the ticket.
> GGRC-3212,GGRC-3333,GGRC-3334,GGRC-3369 RMC - Workflow - People error

- test/integration/ggrc/models/test_revision.py
Test check the correct changes of modified_by field after changing
modified_by_id field.
Add tests for covering modified_by fields changes after updating modified_by_id fields.
In my solution [GGRC-1773](https://github.com/google/ggrc-core/pull/6800/) I am modifying modified_by_id field, and this test check that field modified_by contains information about user, whose id is contained into modified_by_id field.
Add test with next scenario:
1) Create control
2) Create CAD for controls
3) Create CAV for this control (or not create - see parameter is_add_cav)
4) Save ids of all revisions for this control in _ids_before_del_ var
5) Create user with Administrator role (admin)
6) Admin delete CAD
7) Save ids of all revisions again for this control in _ids_after_del_ var
8) In deleting CAD …
> QUICK-FIX Add tests to cover modified_by fields changes for GGRC-1773 ticket

- src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js
"Uncaught Error: can.Map: Object does not exist" error message occurs if click on list of objets types while it loading
1. Log as admin user and open Administration page
2. Click on Custom Attributes tab
3. While Objects are loading click on blank tier of object type: JS error occurs
_Actual Result:_ "Uncaught Error: can.Map: Object does not exist" error message occurs if click on list of objets types while it loading
_Expected Result_: no errors should be shown
Check control before call method of this control
> GGRC-3943 "Uncaught Error: can.Map: Object does not exist" error message occurs if click on list of objets types while it loading

- src/ggrc_workflows/assets/javascripts/models/task_group.js
- src/ggrc_workflows/assets/mustache/task_groups/tree_add_item.mustache
User can submit TaskGroup without provided Workflow
1. Create Repeat off workflow
2. In Setup tab click Create button to create a new Task Group
3. Fill the required fields and click Save and close
Actual Result: POST 500 error occurs while creating a new task group
Expected Result: no errors should be shown up while creating a new task group
Add required validation on Workflow: it disables Save button till values for all required fields are provided.
> GGRC-3949 Add required validation on Workflow for TaskGroup

- src/ggrc/assets/javascripts/plugins/utils/modals.js
"Uncaught Error: can.view: No template or empty template:undefined/modals/confirm_button.mustache" while deleting Products, Systems, Processes
1. Go to My work page > Systems tab
2. Delete any Section in tree view
**Actual Result:** "Uncaught Error: can.view: No template or empty template:undefined/modals/confirm_button.mustache" while deleting Products, Systems, Processes
**Expected Result:** no errors should be shown while deleting Products, Systems, Processes
GGRC.mustache_path is undefined when warning.settings object creates. Use path variable to generate views paths.
> GGRC-3956/GGRC-3356 Fix js exception which occurs while deleting Products, Systems, Processes

- src/ggrc/assets/stylesheets/modules/_modal.scss
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/object_detail.mustache
User's email is duplicated in the Authorizations popup.
Should be displayed user name and email.
1. Open program Info page > Peoples tab
2. Expand user Info pane and click edit Authorizations in 3 bb's menu
3. Look at the User's email screenshot-1.png
**Actual Result:** User's email is duplicated in the Authorizations popup
**Expected Result:** User's email should not be duplicated in the Authorizations popup
> GGRC-3532 Show user name and email in authorizations popup

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/controllers/dashboard_widgets_controller.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/entrypoints/admin/bootstrap.js
- src/ggrc/assets/javascripts/entrypoints/admin/routes.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/bootstrap.js
- src/ggrc/assets/javascripts/entrypoints/dashboard/routes.js
- src/ggrc/assets/javascripts/models/mixins.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
- src/ggrc/assets/javascripts/router.js
- src/ggrc/assets/mustache/components/page-header/page-header.mustache
- src/ggrc/assets/mustache/components/tree_pagination/tree_pagination.mustache
- src/ggrc/assets/mustache/dashboard/internav_list.mustache
- src/ggrc/templates/base_objects/_page_header.haml
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/url.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_program_page.py
Currently we use manual hash manipulation for FE navigation.
It's a big technical debt causing lots technical limitations.
--
Manual hash reading and parsing was replaced with can.route
Broken subpath code was removed.
Routes and widget naming were left for back compatibility.
Modified obsolete parts of code which not covered by tests
> GGRC-3912 Improve the app to use can.route for FE navigation

- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/assessment_template.py
- test/integration/ggrc/converters/test_import_assessment_templates.py
Import of a new Assessment Template successfully creates a new object. But modification of Assessment Template over import fails with an error mentioned in the header.
1. Have Assessment template created on the audit page
2. Export Assessment template and make any changes (e.g. change title) and Save
3. Import Assessment Template
Expected Result: "Assessment template" should be imported
Error was caused by the Audit column handler. Some objects have an attribute audit, and others are mapped to an Audit through relationships. AssessmentTemplates are mapped to Audit over relationship. Whilst Audit Column handler was trying to get Audit as an attribute of AssessmentTemplate. It is done in the handler to check that the Audit slug is not being changed during import (imported Audit slug vs the …
> GGRC-2205 Assessment template: "Import failed due to server error"

- src/ggrc/assets/javascripts/components/tree/sub-tree-wrapper.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
- src/ggrc/assets/mustache/people/tree-item-attr.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
GC/GR as Program Reader is able to see unmap button for Person
1. Create program, map control to program
2. Map GC to program and grant Program Reader role
3. Log as Program Reader and open program page
4. Go to Control tab, expand subtree for control
5. Click on Person's tier > 3 bb's menu
**Actual Result:** Program Reader is able to see unmap button for Person
**Expected Result:** Program Reader should not be able to see unmap button for Person
Person should be unmapped from page instance and TreeBaseLoader should be created also for page instance. So should be user tree-view loader.
Also user_roles and object_people should be uploaded to determine user permissions.
> GGRC-3350 Hide Person Unmap link from subtree when user doesn't have permissions

- src/ggrc/assets/javascripts/components/tree/child-models-map.js
- src/ggrc/assets/javascripts/components/tree/tests/child-models-map_spec.js
Few typos were missed in PR https://github.com/google/ggrc-core/pull/6846
> QUICK-FIX Fix typos for child-models-map component

- src/ggrc/assets/javascripts/components/tree/tests/tree-status-filter_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-status-filter.js
In scope of this ticket tree-view status filter should be able to read/write values from/to query string.
Query string param should override current filter set saved on client, but should not be saved.
Open /dashboard#!assessment_widget&state%5B%5D=In+Progress
**In Progress** filter should be applied
Read values from query string when initialize filter.
Write values to query string when user change status.
> GGRC-3913 Add ability to read status filter from query string.

- ._license_header_exceptions
The javascript file had it's header added and tests run before the check
for headers was merged and because we don't force all branches to be up
to date this was a conflict that was missed by automated tests.
see that all tests pass in this PR (possibly look at the logs)
This fix just makes that we will now have a valid header checks.
Note: the proper thing that should be done in order to avoid this clash,
would be to re-run tests on all branches right after the checks for
license headers were merged.
> QUICK-FIX Remove js file from license header exceptions.

- src/ggrc/assets/mustache/assessments/assignable_extended_info.mustache
LHN: 'End Date' is displayed in Assessment Info popup instead of 'Last Deprecated Date'.
1. Have an Assessment with Last Deprecated Date
2. Open LHN and find an Assessment
3. Hover over Assessment's title and look at the info popup
Actual Result: While hovering over Assessment's title in LHN, End date is displayed instead of Last deprecated date
Expected Result: While hovering over Assessment's title in LHN, Last deprecated date should be  displayed
Rename "End date" to "Last Deprecated Date" in LHN assessment popover.
> GGRC-3981 Rename "End date" to "Last Deprecated Date" in LHN assessment popover

- src/ggrc/assets/javascripts/controllers/tree/tree-view-node.js
Custom attributes/Custom roles shows zero if click on grey triangle of object type tier.
1. As admin go to Administration page
2. In Custom Attributes/ Custom roles tab click on grey triangle of any object type tier
3. Look at the count
**Actual Result:** Custom attributes/Custom roles shows zero if click on grey triangle of object type tier
**Expected Result:** Custom attributes/Custom roles should not show zero if click on grey triangle of object type tier
Stop updateCount event propagation in tree-view-node controller.
> GGRC-3940 Prevent updating widgets count on sub-tree opening

- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc/assets/mustache/components/custom-attributes/custom-attributes.mustache
Global reader without edit rights in Audit can edit LCAs on the Assessment Info pane.
1. Have an audit with control snapshot
2. Create Assessment template with any type of LCA
3. Generate Assessment-1 based on control snapshot and Assessment template
4. Log as Global Reader and open Assessment-1 Info page
5. Edit LCA
*Actual Result:* Global reader without edit rights in Audit can edit LCAs on the Assessment Info pane. 403 error is displayed in console. After refreshing a page data added by Global Reader is not displayed.
*Expected result:* Global reader without edit rights in Audit cannot edit LCAs on the Assessment Info pane
Add 'canEdit' property which check editMode and Permission for update current instance.
> GGRC-3908 Global reader without edit rights in Audit can edit LCAs on the Assessment Info pane

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/mustache/audits/summary.mustache
When user click on chart value on Audit Summary page, he should be redirected to Assessments tab with applied corresponding status filter.
Go to Audit summary page.
Click on chart or legend value.
Add click handler to chart.
Add links to legend.
> GGRC-3914 Add ability go to tree-view when click to chart.

- Dockerfile
- Makefile
- package-lock.json
Some of the frontend dependencies are set as "^SomeVersion" which doesn't fixate minor versions of the dependency. We should freeze all the versions of the dependencies (and all the tree of dependencies) up to minor versions as it may cause future bugs with incompatible minor versions.
Freeze npm packages version by adding package-lock.json.
Package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
https://docs.npmjs.com/files/package-lock.json
https://docs.npmjs.com/files/package-locks
**Note:** To generate package-lock.json npm v.5 or higher is required, …
> GGRC-3575 Freeze versions of all frontend dependencies

- src/ggrc/assets/mustache/components/folder-attachments-list/folder-attachments-list.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_folder.mustache
GC Assessment Assignee (Creator, Verifier) with no Auditor and no Program-level role doesn't see the folder assigned to the Audit
2. Create an Audit in the Program.
3. Assign a Folder to the Audit.
4. Create an Assessment in the Audit.
5. Assign a Global Creator as Creator/Assignee/Verifier (doesn't matter) to the Assessment.
6. Log in with the Global Creator.
**Expected result:** The assigned Folder is displayed on the Audit Info page.
**Actual result:** No folder is displayed on the Audit info page.
Show folder details for all users and hide edit controls for users without 'update' permissions.
Implemented for audits and controls.
> GGRC-2104/GGRC-2906 Show folder details for users with read permissions

- ._license_header_exceptions
This adds a missing exeption to license headers, that was merged due to stale tests.
> QUICK-FIX Add package-lock.json as license headers exception

- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/mixins/__init__.py
- test/integration/ggrc/converters/test_import_assessments.py
Need to allow 'Last Updated By' field to be exportable, but not importable.
1. Go to Assessments tab
2. Export all Assessments (including the ones with the 'Last Updated By' missing to check it's exported without errors)
3. modify the 'Last Updated By' column to one or more objects in the csv (do not set as currently logged in user).
4. import it back
5. check the 'Last Updated By' in the imported objects.  'Last Updated By' is set to the currently logged in user during import.
It's quite straightforward.
> GGRC-3268 Allow to export 'Last Updated By, 'Created at', 'Updated at'

- src/ggrc/assets/javascripts/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/javascripts/components/snapshotter/tests/revisions-comparer_spec.js
- src/ggrc/assets/stylesheets/modules/_modal.scss
GCA changes are not highlighted in revisions compare modal.
1. Have audit with snapshot
2. Update original for snapshot object
3. Open revisions compare modal
Comparing didn't work because of changes in markup. Update GCAs comparing logic.
> GGRC-3902 Highlight GCA changes in revisions compare modal

- .eslintrc.json
- src/ggrc/assets/javascripts/entrypoints/commons.js
- src/ggrc/assets/javascripts/ggrc_base.js
- src/ggrc/assets/javascripts/models/cacheable.js
- src/ggrc/assets/javascripts/plugins/persistent_notifier.js
PersistentNotifier object is available in global scope
PersistentNotifier is migrated on module
> QUICK-FIX Remove PersistentNotifier from global scope

- src/ggrc/assets/javascripts/plugins/utils/modals.js
"Uncaught TypeError: Cannot read property 'on' of undefined" error occurs if Deprecate / Delete System, Process, Product while importing
Case 1
1. Create System in UI
2. Export System to csv file
3. Open System csv template and set Deprecated status > Save
4. Import System csv template
**Actual Result:** "Uncaught TypeError: Cannot read property 'on' of undefined" error occurs if Deprecate / Delete System, Process, Product while importing
**Expected result:** no errors should be shown up if Deprecate / Delete System, Process, Product via import.
Case 2
1. Create System/Process/Product
2. Change status to Deprecated
**Actual Result:** "Uncaught TypeError: Cannot read property 'on' of undefined" error occurs
Exception occurs because 'confirm' function doesn't return $target. So 'confirm' …
> GGRC-4001 Fix js error when change status to deprecated for System/Process/Product

- src/ggrc/models/custom_attribute_value.py
- test/integration/ggrc/models/mixins/test_customattributable.py
If add a space in front of the CA value (' Dashboard_some_name') it would be saved to the db as is. It's not validated and trimmed.
1. Log as Admin
2. On the Administration page > Custom attributes tab> Audits >Add global custom attribute with text type and title as "Dashboard_report"
3. Create a program
4. Create and map an audit to the program
5. On the Audit Info page fill GCA "Dashboard_report": add space and insert https://ggrc-qa.appspot.com > Save
6. Refresh the page and look at the tabs in HNB: Configurable dashboard for audit is not displayed
Expected Result: Configurable dashboard should be shown up on the object page if add a space into 'Dashboard_' field. A space should be cut off.
A validator is added to a Text type CA field which trims all the spaces …
> GGRC-3791 Configurable dashboard is not shown up if add a space into 'Dashboard_' field

- test/selenium/src/lib/base.py
- test/selenium/src/lib/service/webui_service.py
> QUICK-FIX [TAF] Improve Assessments' comments container page objects and methods

- src/ggrc_workflows/assets/mustache/workflows/info.mustache
In scope of moving Workflow roles to ACL add components for Workflow people on WF Info page/pane.
Due to absence of back-end support for Workflow ACL we need to test changes in the provided way
1) Open existing WF
2) In Web Tools Console add breakpoint in info_widget_controller.js at the begining of init()
3) Run the following lines into console
```javascript
GGRC.access_control_roles.push({
default_to_current_user:true,
delete:true,
id:85,
mandatory:false,
modified_by:null,
my_work:false,
name:"Workflow Member",
non_editable:false,
object_type:"Workflow",
read:true,
selfLink:"/api/access_control_roles/83",
tooltip:null,
type:"AccessControlRole",
update:true});
GGRC.access_control_roles.push({
default_to_current_user:false, …
```
> GGRC-3933: add component for ACL people on Workflow info page

- src/ggrc/assets/javascripts/components/add-tab-button/add-tab-button.js
- src/ggrc/assets/javascripts/components/add-tab-button/add-tab-button.mustache
- src/ggrc/assets/javascripts/controllers/dashboard_controller.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/dashboard/internav_list.mustache
- src/ggrc/assets/stylesheets/modules/_top-nav.scss
- src/ggrc/templates/layouts/dashboard.haml
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/widget_base.py
Separate interNav into 2 columns and "add scope" is not displaying now if all scopes is already added.
1. Move to audit > look at the interNav panel
2. Move to audit > add all scopes > refresh page
Comments from jira:
1. Right part should always be collapsed (only icons) - display icons in the right part of the screen. Display icons in two rows in the right part. Need to discuss with Kseniya Koltun, Pavel Nitsiyeuski
2. "Add tab" should be hidden if all types of entities are mapped to audit.
> GGRC-3635 Improve Audit tab line

- src/ggrc/models/mixins/with_similarity_score.py
- src/ggrc/query/custom_operators.py
- test/integration/ggrc/models/mixins/test_with_similarity_score.py
AC1. Related Assessment for Assessment should contain:
all assessments that are mapped to snapshot that are currently mapped to a particular Assessment.
AND we should use snapshots that have the same type, that is set in 'Assessment Type' dropdown.
all assessments that are mapped to snapshots of original object that is mapped to object, which snapshot is mapped to Assessment.
AND objects should have the same type.
AC2. Related Assessments for Controls should contain:
Assessments mapped to snapshots of original Control;
Assessments mapped to snapshots of Controls that mapped to a particular original Control.
The same for Objectives.
DIAGRAM
Attached below. See Diagram 2.
Create Assessments and map Snapshots and …
> GGRC-2447 Calculate Related Assessments basing on mapping of objects of the same type

- docs/source/contributing/git/how_to_write_a_commit_message.rst
- Change id types from CORE to GGRC which now reflect our tickets.
- Add the second example for multiple issues listing in the PR title.
> DOCS Modify multiple issues title guidelines

- src/ggrc/__init__.py
- src/ggrc/__main__.py
- src/ggrc/assets.py
This is just some basic lint of our python files. Nothing that should change the app behavior was should be done here.
> QUICK-FIX Lint ggrc init and main files

- src/ggrc/assets/javascripts/plugins/tooltip.js
Tooltip sticks to the position where it is shown and is not removed when the cursor leaves the element for which the tooltip was shown.
Case 1:
1. Go to Audit page > Assessment tab
2. Expand Assessment Info pane
3. Add at least 3 evidences and hover over evidence link
Actual Result: Tooltip adheres to the screen if hover over evidence link on the Assessment info pane
Expected Result: Tooltip should not adhere to the screen if hover over evidence link on the Assessment info pane
Case 2:
2. Click Add tab > Objectives
3. Close Unified Mapper window
4. Move cursor over the Objectives tab until tooltip is shown
5. Close Objectives tab
Actual Result: Tooltip stuck on its place ( sometimes jumps to the left top corner of the screen ) …
> GGRC-3450,3915 Add a watchdog to remove stuck tooltips

- src/ggrc/notifications/common.py
Some version of email preview in GMail shows the text-only part of the email (reported by the user).
1. Get an email from our application.
2. Check its body.
Expected result: it should contain only HTML contents.
Actual result: it contains extra text part with a TODO string.
No idea how to really test this by hand.
The TODO string has never been implemented, and the requirement for it became outdated long time ago.
> GGRC-3046 Remove the placeholder for text-only email part

- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-attribute.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-group.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-operator.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-filter-state.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-container.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-mapping-group.js
- src/ggrc/assets/javascripts/components/advanced-search/advanced-search-wrapper.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-container_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-group_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-filter-state_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-container_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-mapping-group_spec.js
- src/ggrc/assets/javascripts/components/advanced-search/tests/advanced-search-wrapper_spec.js
Add default line as attribute query to Unified mapper/ Global Search / Generation popup
1. Open Unified Mapper for any entity
2. Look at the default line as attribute query
**Actual Result:** Default line as attribute query is not displayed in Unified mapper/ Global Search / Generation popup
**Expected Result:** Default line as attribute query should be displayed in Unified mapper/ Global Search / Generation popup 
Set default 'filterItems' value.
> GGRC-3447 Add default line as attribute query to Unified mapper/ Global Search / Generation popup

- ._license_header_exceptions
- src/ggrc/utils/error_handlers.py
- test/integration/ggrc/test_csvs/not_a_csv.txt
- test/integration/ggrc/utils/test_error_handlers.py
When an uncaught type error occurs in our code, error handler in error_handlers.py tries to get error code, description and get_response() method from the error. But the error is not an instance of werkzeug error. And it fails with AttributeError.
NA
Try to check if error object has the required attributes, if not - return the error itself.
> QUICK-FIX Fix error handling for uncaught type errors.

- src/ggrc/assets/mustache/assessments/header.mustache
Deprecte' button should exist under 3 dots button for Assessment in 'Rework Needed' state.
On clicking 'Deprecate' button, Assessment should be moved to 'Deprecated' State.
1. Find Assessment in 'Rework Needed' state.
2. Click 'Deprecate' button for this Assessment.
> GGRC-3697 Allow to move Assessment from 'Rework Needed' to 'Deprecated' state.

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/models/search.js
The issue happens because of the underscore "\_" symbol means any symbol in SQL, so if we search for "test_" it also matches for "test1", "test2" etc.
Similar case with "%" symbol, it will match any sequence of symbols.
1. Have programs which names begin with "test".
2. Create program "test_"
3. Add audit widget and invoke new audit window
4. Look at the title field in modal window
Actual Result: Audit title number is incorrect and all widgets on the program page are not shown 
Expected Result: Audit number should start with 1 if there is no objects created earlier
Add escaping for symbols by adding backslash before them with regular expression to query in search api.
> GGRC-1879 Add escaping of percent and underscore symbols

- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
This PR is critical one and need to unblock some PR to dev which are failed due to unstable behavior of test:
```
src/tests/test_snapshots.py::TestSnapshots::test_mapping_of_objects_to_snapshots[Via Tree View MAP btn (map snapshoted Control to Assessment)]
```
For now we don't definitely know it is a app's issue or tests' issue and used a lot of approches for redesign methods according to article https://blog.codeship.com/get-selenium-to-wait-for-page-load/ but unfortunately they allow us to get only 70% of stable work, however JS approach got 99.9% stability as a workaround.
> QUICK-FIX [TAF] Change opening tabs' URLs to use JS due to freezing app 

- src/ggrc/assets/javascripts/plugins/utils/modals.js
Cannot confirm deletion/deprecation of Product / System / Process by clicking Enter button
1. Create system
2. On the system Info page open 3 bb's menu > Edit system
3. Click delete button
4. Type 'I confirm' and click [Enter]
**Actual Result:** Cannot confirm deletion/deprecation of Product / System / Process by clicking Enter button 
**Expected Result:** Deletion/deprecation of Product / System / Process should proceed by clicking Enter button
Handle pressing Enter.
> GGRC-3356 Allow confirmation for deleting/deprecating of Product / System / Process by pressing Enter button

- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Cannot Assign a person as Default Assignee if select 'Others' option in Assessment Tempate.
1. Go to the Audit summary page and Invoke new Assessment template modal window
2. Fill out a title
3. Select 'Others' option in Default Assignee dropdown list
4. Select a person and click on it
Actual Result: User cannot Assign an Assignee using 'Others' option in Assessment template
Expected Result: User should be able to Assign an Assignee using 'Others' option in Assessment template. Assignee should be displayed next to 'Default Assignee' field
Issue reproduced on ggrc-test, but not on ggrc-qa!
Nonexistent callback "assessorAdded" was replaced to "assigneeAdded".
> GGRC-4034 Cannot Assign a person as Default Assignee in Assessment Template

- .eslintrc.json
- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/components/assessment/assessment-local-ca.js
- src/ggrc/assets/javascripts/components/assessment/attach-button.js
- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.js
- src/ggrc/assets/javascripts/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc/assets/javascripts/components/audit/attach-folder-button.js
- src/ggrc/assets/javascripts/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control-group.js
- src/ggrc/assets/javascripts/components/related-objects/tests/related-people-access-control-group_spec.js
- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
- src/ggrc/assets/javascripts/entrypoints/commons.js
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/pbc/workflow_controller.js
- src/ggrc/assets/javascripts/permission.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
- src/ggrc/assets/javascripts/plugins/tests/ggrc_utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/snapshot-utils.js
- src/ggrc/assets/javascripts/tests/permission_spec.js
- src/ggrc/assets/js_specs/mustache_helpers/with_is_reviewer_spec.js
- src/ggrc_workflows/assets/javascripts/workflow_mustache_helpers.js
Permission constructor is available in global scope
Permission constructor is migrated on module
> QUICK-FIX Remove Permission constructor from global scope

- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/issue_tracker.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/services/common.py
This is the first part of the ticket GGRC-1799, and is meant as just a small cleanup before the bigger changes.
The main thing here is to remove redundant queries to the database. The improvement in this PR is still quite minor and does not affect the overall performance by much so.
Check that generating assessments still works in exactly the same way (same things are stored in the db) as before.
I have just removed any queries that read duplicate data on the backend, and added some code cleanup.
This PR is prep work for the bigger changes with bulk inserts.
> GGRC-1799 Improve performance of generating assessments

- src/ggrc/assets/mustache/base_objects/mapper-item-description.mustache
- src/ggrc/assets/stylesheets/components/unified-mapper/_unified-mapper.scss
Description is shown with tags in Global Search
1. Go to My work page and invoke new program modal window
2. Fill title 
3. Fill description and press "Enter" several times > Save
4. Open Global Search and find created program
5. Click triangle to see a description
*Actual Result:* Description is shown with tags in Global Search
*Expected Result:* Description should not be shown with tags in Global Search
Use {{{description}}} instead of {{description}} to render unescaped value.
> GGRC-2757 Show description unescaped

- src/ggrc/access_control/list.py
The unique constraint on access control list was modified in a migration
from commit 96a5438a4a2e6ca516f05d2afcb7657eff5aa457, but the ACL model
itself was not update accordingly. This commit reduces the amount of
differences between our models and db schema.
Autogenerate migrations and check the diff from before and after this change. The new autogenerated migration should show fewer changes.
Add a missing constraint part into our model.
> QUICK-FIX Update ACL unique constraint

- src/ggrc_gdrive_integration/migrations/versions/20171226160800_4491d7eaca49_remove_objectfile_data.py
> GGRC-4092 Remove ObjectFile table

- src/ggrc/models/label.py
- src/ggrc/models/mixins/labeled.py
- test/integration/ggrc/models/mixins/test_labeled.py
Label name shouldn't have leading/trailing spaces.
Manually update assessment pull request: add leading/trailing spaces.
Add validator to name field
> QUICK-FIX Add label name validation

- src/ggrc/assets/javascripts/components/sort/sort-by.js
- src/ggrc/assets/javascripts/components/tree/tree-view.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
"CATEGORIES" and "ASSERTIONS" attributes should be sorted by alphabet
- Open Control.
- Look at "CATEGORIES" and "ASSERTIONS" attributes:
1. in tree view
2. info pane/info page
3. New/Edit modal window
Order by name options before build html string in mustache helper
> GGRC-2815 display values in "CATEGORIES" and "ASSERTIONS" columns in tree view and Info pane in alphabetical order

- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/sections/modal_content.mustache
- src/ggrc_workflows/assets/mustache/base_objects/approval_link.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/task_groups/modal_content.mustache
Incorrect declaration of `if_helper`
> QUICK-FIX Fix if_helper declaration

- src/ggrc/models/__init__.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/migrations/versions/20171218080506_3355d60d65d8_add_workflow_acr_records.py
- src/ggrc_workflows/models/hooks/__init__.py
- src/ggrc_workflows/models/hooks/workflow.py
- test/integration/ggrc_workflows/test_workflow_api_calls.py
~This PR is `on hold` until the dependencies are merged:~
> GGRC-3919 Propagate roles on Workflow PUT

- src/ggrc/assets/javascripts/components/tree/tree-item-actions.js
- src/ggrc/assets/javascripts/models/mappers/tests/mappings_spec.js
- src/ggrc_risk_assessments/assets/javascripts/apps/risk_assessments.js
1) When you map "Risk Assessment" to "Program" error occurs.
2) When you try map objects to "Risk Assessment" error occurs.
2. Add widget> Risk assessment
3. Create Risk assessment
4. Click Map button in first tier
Actual Result: "Uncaught TypeError: Cannot read property 'model_singular' of undefined" error occurs while clicking map button on Risk assessment first tier
Add "Risk Assessment" into `forbiddenMapList` in `tree-item-actions` component.
Remove canonical mapping between "Program" and "Risk Assessment".
> GGRC-1314 Remove ability to map "Risk Assessment"

- src/ggrc/assets/javascripts/components/revision-log/revision-log.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Dates with unsupported format appear in change log tab. As result they are displayed as 'Invalid date'. CA dates are displayed in wrong format 'YYYY-MM-DD'.
Add additional ISO format to `formatDate` util and to mustache helper `localize_date`. Add `formatDate` for CA dates.
> GGRC-2108 Add additional allowed format date 'YYYY-MM-DDTHH:mm:ss.SSSSSS'

- src/ggrc/assets/javascripts/models/join_models.js
ObjectOwner has been deprecated in August 2017 and its logic has been mirated into ACL. The FE code related to this model should be removed.
> GGRC-4069 Remove ObjectOwner model

- src/ggrc/services/assessment_resource.py
> Currently '/api/assessment/
> 
> {id}
> /related_objects' contain not needed data.
> Person and Relationship arrays is redundant now
trigger a get request for the related_objects custom endpoint on assessment "api/assessments/x/related_objects" and check that it does not contain person and relationship data.
Assessment custom endpoint had people and relationships data because
assignees were mapped with special relationships. Since we moved all
assessment roles to ACL, this data is no longer needed.
The PR just removes that data and all related functions.
> GGRC-4005 Remove redundant data from related objects

- src/ggrc/assets/javascripts/apps/base_widgets.js
There is no "People tab" on the Issue Info Page
1. Create an Issue on the Audit page
2. Open created Issue In a new tab
3. Click [+] Add tab: there is no People widget
*Actual Result:* There is no "People tab" on the Issue Info Page
*Expected Result:* Should be the possibility to add "People tab" on the Issue Info Page
People tab was hided manually. I removed the code hiding the tab.
> GGRC-3342 Show "People" tab on Issue page

- src/ggrc/assets/javascripts/controllers/modals_controller.js
- src/ggrc/assets/mustache/audits/modal_content.mustache
- src/ggrc_risks/assets/mustache/risks/modal_content.mustache
- src/ggrc_workflows/assets/mustache/cycle_task_entries/modal_content.mustache
- src/ggrc_workflows/assets/mustache/task_groups/modal_content.mustache
- src/ggrc_workflows/assets/mustache/wf_objects/approval_modal_content.mustache
- src/ggrc_workflows/assets/mustache/workflows/modal_content.mustache
To avoid a merge conflict I have based my changes on the PR listed below. Once it's merged I'll rebase so that only the last two commits are added by this PR.
Description fields in some objects had the program_description id set. This was wrong and is now fixed 
I have also noticed that there was some code that used to clear description fields, now this is handled automatically by data binding so the manual code was removed. The if clause that was removed in the second commit never actually executed because calling `$textArea.data('wysihtml5')` always gave a falsy result.
> QUICK-FIX Fix description ids

- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/assets/mustache/audits/info.mustache
Depends on:
- Make changes for Audit.
- Add 'Last Deprecated Date' on :
- Audit info pane / page
- Set visible fields for Audit pop-up (on widget and unified mapper)
- as a column on Audit tab
- as a column on Global Search
- Export spreadsheet
- Date should be autopopulated with current date, when Audit status is changed to 'Deprecated'.
- If deprecated object is moved to another state, then keep date unchanged.
- User should not be able to update date manually.
Do NOT add 'Last Deprecated Date' on:
- 'New Audit pop-up;
- 'Edit Audit' pop-up;
- Import spread sheet.
- Import page.
- Allow user to search Audits by Last Deprecated Date (advanced search).
- Allow user to filter Audits by Last Deprecated Date.
- Allow user to sort Audits by Last Deprecated Date.
> GGRC-3501 FE: Add "Last Deprecated Date" for an Audit.

- src/ggrc/models/hooks/issue_tracker.py
Seems, that Status transitions map for assessment with verifier (in issue_tracker.py) was incorrect. 
('Completed', 'In Progress', True): 'ASSIGNED',
Hardly I can imagine a case when assessment moving from Completed to In Progress and is still Verified in the new state.
1. Have an assessment in 'Completed and Verified' state on the Audit page. IssueTracker is switch 'ON'
2. Modify Assessment to get it to In Progress state
3. Go to Issue Tracker and look at the generic message
Expected result: Message should contain the updated status (...Current status of related GGRC Assessment is In Progress....)
The solution was simply to fix the Status transitions map, change verified value from True to False:
('Completed', 'In Progress', False): 'ASSIGNED',
> GGRC-3992 Message not updated in Issue Tracker if assessment moves from Completed and Verified to In progress state

- src/ggrc/assets/javascripts/models/audit_models.js
Since audit captain is now a access control role validating the contact
field needs to be removed.
Save button on audit edit modal is always disabled
1. Create a new program and audit
2. Try to edit the newly created audit
The save button will be disabled.
Since audit captain is now an access control role validating the contact
field needs to be removed. Because of the contactable mixin the contact field is set to the current user in the create new modal, so the issue only pops up in the edit modal.
I will remove the contactable mixin from audit in a separate pull request as I wanted to keep this one light because the issue is blocking and we want to make it as easy to review as possible.
> GGRC-4120 Remove contact validation on audit

- src/ggrc/assets/javascripts/models/assessment.js
- src/ggrc/assets/javascripts/models/audit_models.js
Error message 'cannot be blank' should be displayed for Component ID and Issue Title
Should have the same behavior as any other mandatory text field fields on 'Add / Edit pop-up'.
1. User opens pop-up.
2. User deletes Component ID.
3. User moves focus out of Component ID field.
_Expected result_: 'cannot be blank' error message should be shown
Make changes for:
_Component ID_ (on 'Add/Edit Assessment'; 'Add/Edit Assessment Template'; 'Add/Edit Audit' pop-ups);
_Issue Title_ (on 'Add/Edit Assessment' pop-up).
Display "cannot be blank" instead of "Enter Component ID" message
> GGRC-3801 Error message 'cannot be blank' should be displayed for Component ID and Issue Title

- src/ggrc/assets/javascripts/models/audit_models.js
No real issue, just removing some code that should no longer be there.
Make sure creating/editing the audit still works.
I thought I'd be able to remove the contactable mixin, but it's still used by TaskGroups :(
> QUICK-FIX Cleanup contactable from audit

- src/ggrc/settings/default.py
> 1. Log as admin user to ggrc-dev instance
> 2. My work page > Assessment tab
> 3. Navigate to assessment info pane and click Attach button
> 4. Click 'Authorize Google API' button
> Actual Result: After clicking "Authorize Google API" nothing happens and GDrive picker is not opened
> Expected Result: GGRC-DEV: After clicking "Authorize Google API" user should be authorized and GDrive picker should be opened
Test if Gdrive integration works (attach any evidences and check import export)
The exports variable that was defined on top was originally overwritten
and so the new gdrive export variables did not get exported correctly.
This change makes sure we set the exports for all variables than need to
be exported in a single place.
> GGRC-4122 Fix settings exports for gdrive integration

- src/ggrc/settings/default.py
Update the app verison
Open the app and check that the version is set to 1.1.0
Update the version setting.
> QUICK-FIX Bump version to 1.1.0-Strawberry

- src/ggrc/assets/javascripts/bootstrap/modal-ajax.js
- src/ggrc/assets/javascripts/bootstrap/modal-form.js
- src/ggrc/assets/javascripts/components/object-bulk-update/object-bulk-update.mustache
- src/ggrc/assets/javascripts/components/object-generator/object-generator.mustache
- src/ggrc/assets/javascripts/components/object-search/object-search.mustache
- src/ggrc/assets/javascripts/components/unified-mapper/mapper-results.js
- src/ggrc/assets/javascripts/components/view-models/object-operations-base-vm.js
- src/ggrc/assets/javascripts/controllers/info_pin_controller.js
- src/ggrc/assets/javascripts/controllers/tests/info_pin_controller_spec.js
- src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_folder_picker.js
- src/ggrc_gdrive_integration/assets/javascripts/components/gdrive_picker_launcher.js
- src/ggrc_gdrive_integration/assets/js_specs/components/gdrive_folder_picker_spec.js
- src/ggrc_gdrive_integration/assets/js_specs/components/gdrive_picker_launcher_spec.js
- src/ggrc_gdrive_integration/assets/mustache/gdrive/gdrive_file.mustache
The info pane isn't closed after pressing the escape key.
**Comment by User:**
*In other words, I want the escape key to act like the "X" in the top right corner.*
*When the escape key is pressed info pane isn't closed.*
*By pressing the escape button the event handler closes the info pane.*
> GGRC-3770 Use Escape key to exit out of pop-up window

- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/info.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/mustache/objectives/info.mustache
- src/ggrc/assets/mustache/people/info.mustache
- src/ggrc/assets/mustache/policies/info.mustache
- src/ggrc/assets/mustache/processes/info.mustache
- src/ggrc/assets/mustache/products/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/systems/info.mustache
- src/ggrc_basic_permissions/assets/mustache/ggrc_basic_permissions/people_roles/info.mustache
- src/ggrc_risk_assessments/assets/mustache/risk_assessments/info.mustache
- src/ggrc_risks/assets/mustache/risks/info.mustache
- src/ggrc_workflows/assets/javascripts/components/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
- src/ggrc_workflows/assets/mustache/workflows/info.mustache
- test/selenium/src/lib/constants/element.py
Currently the first tab on object info pane/ page is named due to the object type. For example, on any Program it is named as 'Program'.
This naming should be changed to 'Attributes'.
The list of objects that should be updated:
1. Standards
2. Regulations
3. Sections 
4. Objectives 
5. Controls 
6. Products 
7. Systems 
8. Processes
9. Access Groups 
10. Audits
11. Clauses 
12. Contracts
13. Data Assets 
14. Facilities 
15. Issues 
16. Markets 
17. Org Groups 
18. Policies
19. Programs 
20. Projects 
21. Risks 
22. Threats 
23. Vendors 
24. Risk Assessments
25. Workflows
26. Cycle Tasks
27. Person
28. Assessment Template
> GGRC-3472 Rename first tab on info pane into 'Attributes'

- src/ggrc/assets/javascripts/plugins/tooltip.js
An edge case was found when tooltip where not removed.
1. Create an assessment with verifier(s).
2. Make sure the verifiers column is visible in the tree view
3. Hover over the verifiers filed column of a newly created assessment and click on it when a tooltip appear
4. Prior to this change, tooltip would stuck in its place
Check if element, for which tooltip is shown, is actually visible and not covered by some other element, ex. modal window. For this we take the coordinates of the element relative to the viewport and getting the element in that position with `document.elementFromPoint `. Then we compare if element in that position is our element or its child. If so, element is at least partially visible and tooltip should stay, otherwise - removing the tooltip.
> GGRC-3450 Remove tooltip when element is covered by modal

- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/converters/handlers/custom_attribute.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/converters/handlers/list_handlers.py
- src/ggrc/converters/pre_commit_checks.py
- src/ggrc/models/exceptions.py
- src/ggrc/models/mixins/validate_on_complete.py
- test/integration/ggrc/converters/test_import_assessments.py
Error "Import failed due to unknown error." is displayed while importing Assessment with filled any type of mandatory LCA
1. Have an assessment with mandatory LCA in UI in Not Started state
2. Export Assessment to csv file
3. Open csv file and set a state 'Completed' (or any other state) > Save
4. Fill values for CAs
5. Import Assessment
"Import failed due to unknown error." is displayed.
Reason of this issue is that Assessment status validation was run before inserting CADs: during import we setup values for base object (Assessment), run validator, insert base object into db and only after it CAs will be set up. Validator method see empty values in mandatory CA and throw the error.
Also such error message is unclear, need to show information about what exact field and row contain wrong …
> GGRC-4039 Check Assessment CADs before import

- src/ggrc/assets/javascripts/components/assessment/info-pane/info-pane.mustache
- src/ggrc/assets/stylesheets/components/action-toolbar/_action-toolbar.scss
- src/ggrc/assets/stylesheets/components/inline/_inline.scss
- src/ggrc/assets/stylesheets/components/people-group/_people-group.scss
Inline edit icon should be displayed when user hovers over all attribute area.
Currently inline edit icon is shown only if user hovers over attribute title.
It is required to shod inline edit icon on hovering over the whole area of attribute.
Update css styles for :hover selector.
> GGRC-3484 Show inline edit icon when hover over whole attribute area

- src/ggrc/assets/javascripts/components/info-pane/info-pane-footer.mustache
- src/ggrc/assets/javascripts/models/audit_models.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/page/widget/info_widget.py
GGRC-1878:
Rename "Created at" to "Created date" at the bottom of the object's info page and across the application
GGRC-3406:
Rename 'Modified by' to 'Last updated by' on the object's Info page
Open info page and take a look into widget footer.
> GGRC-1878/3406 Improve info widget footer wording

- src/ggrc/access_control/roleable.py
- src/ggrc_workflows/__init__.py
- test/integration/ggrc_workflows/test_workflow_api_calls.py
> GGRC-3920 Give Workflow Member role to TaskGroup Assignee

- src/ggrc/assets/javascripts/plugins/tooltip.js
"Uncaught TypeError: Cannot read property 'parentElement' of null" while opening Unified mapper in Edit Assessment popup
1. Create a program, map a control to a program'
2. Create an audit on a program page
3. Go to the audit page and generate assessment based on the control snapshot
4. Invoke Edit Assessment popup and click on Map objects button
5. Close Unified mapper
6. Click Map Objects button once again
Actual Result: "Uncaught TypeError: Cannot read property 'parentElement' of null" while opening Unified mapper in New/ Edit Assessment popup
Expected Result: no errors should be displayed while opening Unified mapper in Edit Assessment popup
The tooltip is trying to get element by coordinates, but in the described case button moves down under the screen when 2nd …
> GGRC-4135,4153 Fix tooltip visibility condition

- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control.js
Task Assignees are not reset after click on 'Save and Add Another' (Create Task modal).
Flow A:
1. Go to My Tasks page / Active Cycles page for one-time WF (repeat turned OFF)
2. Click 'Create' button to create a cycle task.
3. Fill required fields and click 'Save and Add Another' button
Flow B:
1. Go to Workflow - Setup page.
2. Expand task group.
3. Click 'Create Task' button
4. Fill required fields and click 'Save and Add Another' button
**Actual result:** User is populated as Task Assignee.
**Expected result:** Task Assignee should be empty by default.
Refresh people in 'related-people-access-control' on instance update.
> GGRC-3701: Reset TaskAssignees on 'Save and Add Another'

- src/ggrc/query/custom_operators.py
Old audit roles (user_roles auditors) were still popping up on audit
People tab. This commit makes sure only AccessControlList auditors show
up.
We are still showing program user_roles, these will be removed in PR
#7076.
1. Have an audit with an auditor before the Audit ACL migration
2. Migrate the database and see the auditor on the list of people on the audit page
3. Remove the auditor form the audit info pane
Expected: The auditor should be removed from the list of people (unless he has another ACL record for that audit e.g. Assessment Assignee Mapped role)
Actual: The auditor is still shown as an auditor on the people page.
The solution makes sure we don't return audit roles based on user_roles anymore. There is still an issue with the Authorizations column, that will still go through …
> QUICK-FIX Hide old audit user_roles from people tab

- src/ggrc/notifications/data_handlers.py
Daily digest failing if you remove ACR from available list to presented model (for example: Assessment) 
- create Assessment 
- add ACR to assessment 
- add person to that assessment 
- remove person from that assessment 
- remove that ACR
Check if required role_id is in list of available roles, and if it's not just skip that role_id.
> GGRC-4184 Fix daily digest if role undefined

- src/ggrc/assets/javascripts/components/object-tasks/object-tasks.js
Tasks in final state should not have 'Overdue' indicator, and vice versa.
1. Create any WF with need verification - TRUE
2. Add at least 5 overdue tasks to Task Group and and map any object to Task Group, e.g. Control
4. On the Active Cycles tab move cycle tasks to different states: In progress, Finished, Declined, Verified
5. Go All objects page > Controls tab > Find mapped control
6. Hover over 'i' icon and look at the cycle tasks states: Finished state is not shown as overdue
**Actual Result:** Info popup with mapped tasks shows incorrect cycle tasks statuses
**Expected Result:** Info popup with mapped tasks should show exact cycle tasks statuses
request 'is_verification_needed' field for tasks.
> GGRC-4079: Fix issue with overdue tasks indicator

- src/ggrc/assets/stylesheets/modules/_modal.scss
Create/Edit modal -> hide button is not clickable for date fields
Preconditions:
- have a control
Steps:
- open control's from preconditions info pane
- press 3bb's -> Edit
- click "hide" link on the top-right corner of the field with date
Actual: hide link is not clickable
Expected: hile link is clickable, field is hidden from the modal
We have the issue because datepicker covers 'hide' button.
> GGRC-774 Fix 'hide' button position

- src/ggrc/assets/javascripts/components/issue/issue-unmap-item.mustache
'Related audit'/ 'Related snapshots' are displayed in unmapping popup if nothing to show
1. Have audit with mapped snapshot A, snapshot B
2. Create Assessment 1 and map it to snapshot A
3. Create Assessment 2 and map it to snapshot B
4. Raise an Issue for Assessment 1
5. Map raised Issue to Assessment 2
6. Go to the Issue Info page > Assessments tab
7. Click on Assessment
8. On the Assessment Info pane click 'Unmap' in 3 bb's menu
*Actual Result:* 'Related audit'/ 'Related snapshots' are displayed in unmapping popup if nothing to show
*Expected Result:* 'Related audit'/ 'Related snapshots' should be displayed in unmapping popup if Issue is unmapped from Audit, related snapshots
Modify conditions in template to hide all section instead of list.
> GGRC-3655 Fix empty sections displaying

- src/ggrc/assets/javascripts/controllers/summary_widget_controller.js
- src/ggrc/assets/stylesheets/_colors.scss
- src/ggrc/assets/stylesheets/_common.scss
- src/ggrc/assets/stylesheets/_placeholders.scss
Update the colors for states in accordance with mock-up: https://drive.google.com/corp/drive/folders/1bRXUGQbyua9TZYj_RWObMEPUoXrTum8K
Go through different object's states and check colors.
> GGRC-2776 Update the colors for states

- src/ggrc/assets/javascripts/components/aggregate-field-vm.js
- src/ggrc/assets/javascripts/components/inline/inline-aggregate-field.js
- src/ggrc/assets/javascripts/components/inline/inline-aggregate-field.mustache
- src/ggrc/assets/javascripts/components/inline/people-with-role-inline-field.js
- src/ggrc_workflows/migrations/versions/20171218080506_3355d60d65d8_add_workflow_acr_records.py
- src/ggrc_workflows/models/hooks/__init__.py
- src/ggrc_workflows/models/hooks/workflow.py
- test/integration/ggrc/access_control/acl_helper.py
- test/integration/ggrc_workflows/test_workflow_api_calls.py
On-hold until all dependencies will be merged. Depends from:
> GGRC-3923 Remove related ACL records on related object delete operation

- src/ggrc/assets/javascripts/mustache_helper.js
- src/ggrc/rbac/permissions_provider.py
https://github.com/google/ggrc-core/pull/7092 Was merged before I could address the comments raised there. I'm opening a separate PR where I address the comments.
> QUICK-FIX Fix comments from blocker pull request

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/task_group.py
- src/ggrc_workflows/models/workflow.py
- test/unit/ggrc_workflows/models/test_task_group.py
> GGRC-3928 Fix “clone Workflow with people” functionality

- src/ggrc/settings/default.py
> QUICK-FIX Bump version to 1.3.0-Strawberry

- src/ggrc/migrations/versions/20171215130030_1ade34010ee3_add_notification_settings_to_role.py
On migration warning
/vagrant/src/packages/sqlalchemy/connectors/mysqldb.py:68: Warning: Field 'notify_about_proposal' doesn't have a default value
rowcount = cursor.executemany(statement, parameters)
rerun migration 
add default value to field 'notify_about_proposal'
> GGRC-4210 Fix ACR migration warning

- src/ggrc/assets/javascripts/components/effective-dates/effective-dates.js
- src/ggrc/assets/mustache/components/datepicker/datepicker.mustache
- src/ggrc/assets/mustache/wf_objects/approval_modal_content.mustache
- src/ggrc/assets/stylesheets/modules/_datepicker.scss
- src/ggrc/assets/stylesheets/modules/_modal.scss
Hide link for date fields in modal windows doesn't work
1. Click Start new program
2. Click hide link for date fields: doesn't work
**Actual Result:** Hide link for date fields in modal windows doesn't work 
**Expected Result:** Hide link for date fields in modal windows should hide optional date field
Note: hide link should not be present for mandatory date fields
datepicker__wrapper block overlaps hide link because of relative position style.
This style can be removed as inner datepicker__input-wrapper also has relative position.
> GGRC-1267 Hide link for date fields in modal windows doesn't work

- src/ggrc/assets/javascripts/plugins/ggrc_utils.js
Map button is displayed in tree view in People tab on the Issue Info page
1. Create an Issue 
2. Open People tab on the Issue Info page
3. Look at the tree view: Map button is displayed
**Actual Result:** Map button is displayed in tree view in People tab on the Issue Info page
**Expected Result:** Map button should not be displayed in tree view in People tab on the Issue Info page
> GGRC-4163 Hide Map person button for Issue object

- .eslintrc.json
- package-lock.json
- package.json
After migration on up to date version on eslint config we have lost a couple of rules because current version doesn't extend from `xo-config`
Added `eslint:recommended`
**NOTE**: in scope of other ticket we need to analyse which rules we have lost and analyse which rules need for us due to the fact that we started to use ES2015 syntax
**NOTE 2:** the failed check style test is good for this PR, because was removed rule that allow use `var`
> QUICK-FIX Update eslint config 

- provision/docker/mysql/packet_size.cnf
Importing ggrc-test db fails with the following error:
```
ERROR 1118 (42000) at line 674: The size of BLOB/TEXT data inserted in
one transaction is greater than 10% of redo log size. Increase the redo
log size using innodb_log_file_size.
```
1. Try to import the ggrc-test db
The default value is 48MB and is not enough to import our ggrc-test db. Increasing it fixes the issue.
> QUICK-FIX Increase innodb log file size

- src/ggrc/assets/javascripts/plugins/tests/current-page-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
Request on counts contain redundant parts, which were generated for not tree-view tabs(info, summary, ...)
Load the page with opened DevTool and Network tab.
Look into counts request that contain redundant part.
Left queries only with counts for tree view tabs
> QUICK-FIX Remove redundant queries from counts request

- src/ggrc_workflows/migrations/versions/20180115094803_58e0f07e174b_move_user_roles_to_acl.py
> GGRC-3930  Migrate Workflow UserRoles to ACL

- src/ggrc/assets/mustache/base_objects/approval_link.mustache
Uncaught SyntaxError "Unexpected token \ in JSON at position 1" is thrown when a user declines control review.
1. As admin go to Control Info page 
2. Click Submit for review 
3. Add reviewer and a date > Save 
4. Once Approve /Decline buttons appear click Decline button 
Result: no errors should be displayed while declining object review
When a user clicks "Decline" button the application tries to parse data-object-params defined for the control. Since the params object is not valid JSON, users see the error. Solution - remove slashes.
> GGRC-4168 fix decline button at control info page

- src/ggrc/assets/javascripts/components/tree/tree-widget-container.js
- src/ggrc/assets/javascripts/plugins/tests/current-page-utils_spec.js
- src/ggrc/assets/javascripts/plugins/utils/current-page-utils.js
- src/ggrc/assets/javascripts/plugins/utils/tree-view-utils.js
After change the page in tree view is sended extra request for the counts, if in multi-select status filter selected some statuses.
- select some statuses in filter (not all)
- move on other page in tree view
**Actual result:** in network tab of devtool you can see two requests on query api
**Expected result:** should be sended just an one request  
Requests on query api is batched into one
> GGRC-2712 Remove second request to Query API(counts) after load data for tree view

- src/ggrc/assets/javascripts/components/comment/comment-add-button.js
- src/ggrc/assets/javascripts/components/comment/comment-add-form.js
- src/ggrc/assets/javascripts/components/comment/comment-add-form.mustache
- src/ggrc/assets/javascripts/components/comment/comment-data-provider.js
- src/ggrc/assets/javascripts/components/comment/comment-input.js
- src/ggrc/assets/javascripts/components/comment/mapped-comments.js
- src/ggrc/assets/javascripts/components/comment/tests/comment-input_spec.js
Add comment button is available for Global Reader/Global Creator as Program Reader
1. Create a program and map Global Creator as Program Reader to a program
2. Leave a comment to a program
3. Log as Global Creator and open Program Info page
4. Type a comment into comment box and Click add button
**Actual Result:** Add comment button is available for Global Reader/Global Creator as Program Reader
**Expected Result:** Add comment button should not be available for Global Reader/Global Creator as Program Reader
**NOTE:** Make sure to do it for every commentable object.
Check user update object permissions.
> GGRC-4077 Hide comment form if user is not allowed to add comments

- src/packages
This commit just makes a symlink absolute to match the path of
node_modules symlink. In some cases docker fails to build if the folders
referenced by the symlinks do not exists and having both of our links
absolute makes it easier to mock the folder structure so that the
container builds properly.
Note: Deployment with the new symlink was tested by deployment on ggrc-perf and general sanity test of the app.
Make sure containers build and the app runs afterwars. 
Maybe even test a deployment.
> QUICK-FIX Make symlink absolute

- src/ggrc/migrations/versions/20180115102622_12c716cf3817_remove_documentation_description.py
- src/ggrc/models/control.py
Remove an obsolete element form our code.
The actual issue was that documentation description field was visible on control proposals, but this commit should not be the one that fixes the issue. Issue should be fixed with change of attribute names.
This just removes all references to our outdated field.
> GGRC-4191 Drop controls.documentation_description column

- src/ggrc/migrations/versions/20180115130212_2ac95a7b18fa_cleanup_document_model.py
- src/ggrc/models/document.py
- test/integration/ggrc_basic_permissions/test_creator.py
- test/integration/ggrc_basic_permissions/test_reader.py
Document model contains unused fields, and its link and title don't match the business requirements and the actual logic.
Unused fields are dropped both from the code and the DB.
Title and link become non-nullable, and they are filled in with empty or default values when null.
> QUICK-FIX Clean up Document model

- src/ggrc/assets/javascripts/components/access_control_list/access-control-list-roles-helper.js
- src/ggrc/assets/javascripts/components/access_control_list/access-control-list-roles-helper.mustache
- src/ggrc/assets/javascripts/components/custom-roles/custom-roles-modal.js
- src/ggrc/assets/javascripts/components/custom-roles/templates/custom-roles-modal.mustache
- src/ggrc/assets/javascripts/components/related-objects/related-people-access-control-group.js
- src/ggrc/assets/mustache/controls/modal_content.mustache
- src/ggrc/assets/mustache/risks/modal_content.mustache
Global Reader cannot propose changes for ACL roles
1. As admin user create a control 
2. Log as Global Creator and open the control created by Admin
3. Click Propose Changes button
4. Propose a person for custom role: no success
_Actual Result_: Global Reader cannot propose changes for ACL roles
_Expected Result_: Global Reader should be able to propose changes for ACL roles
Allow edit ACL for readers on proposal modal
> GGRC-4217 Global Reader cannot propose changes for ACL roles

- src/ggrc/assets/javascripts/controllers/tree/tree-view.js
Blank type name displayed for GCA after scrolling on 'Custom attributes' tab
1. Log as admin user and open Administration page
2. Click on Custom Attributes tab
3. Expand few(1-3) GCA dropdown
4. Scroll to bottom then scroll to top
**Actual result:** Some object type names displayed as blank. (will be fixed if click on it)
**Expected result:** Some object type names displayed appropriate
Set disable_lazy_loading flag to true to prevent list items redrawing on scroll event.
As TreeView controller is used only for Custom Attributes and Custom roles tabs it can be set as default.
> GGRC-4050 Fix blank GCA titles after scrolling on 'Custom attributes' tab

- src/ggrc_basic_permissions/roles/Creator.py
No real issue.
No steps to test, nothing should change before/after, except that the Creator will now be able to create Categorization objects correctly, but we never create Categorization objects like that.
Create workflow role is givent to the creator with WorkflowRoleContributions https://github.com/Smotko/ggrc-core/blob/b3abb58b24e7559960d71a94ba79c75539e7fe29/src/ggrc_workflows/__init__.py#L959
> QUICK-FIX Remove "Workfow" from creator.py

- src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
Issues tab doesn't contain MAP btn in Tree View when Risk is src object
When we have Risk src object and try to map destination issues (we can do that only 1st time when are opening issues tab and unified mapper is appearing, but after that MAP btn isn't appearing on tree view)
Actual:
we can do that only 1st time when are opening issues tab and unified mapper is appearing, but after that MAP btn isn't appearing on tree view
Expected:
we should can map destination issues useing MAP btn on tree view
Risk module overrides `add_item_view` and use always `base_objects/add_item_view`. The base view didn't rendered map button, but now Issue is first class object and we can show the button.
> GGRC-4057 Show 'Map' button for Issues

- src/ggrc-client/js/components/comment/tests/comment-input_spec.js
- src/ggrc-client/js/components/diff/tests/instace-acl-diff_spec.js
- src/ggrc-client/js/components/diff/tests/instance-fields-diff_spec.js
- src/ggrc-client/js/components/diff/tests/instance-gca-diff_spec.js
- src/ggrc-client/js/components/multi-select-label/multi-select-label_spec.js
- src/ggrc-client/js/components/three-dots-menu/tests/three-dots-menu_spec.js
- src/ggrc-client/js/components/tree/tests/tree-field_spec.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
- src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/spec_helpers.js
Add more unit-tests for multi-select-label component.
Remake spec_helpers.js as module to get rid of eslint errors: 'getComponentVM' is not defined.
> QUICK-FIX Add unit-tests for multi-select-label component

- src/ggrc-client/js/models/task_group.js
- src/ggrc-client/js/models/workflow.js
Check steps below.
1. Login as Global Reader.
2. Create Workflow with default Task Group. Global Reader should be Admin in Workflow.
3. After redirect to setup tab press on Task Group.
**Actual result:** Check that TaskGroupTask 'create'/Map object buttons are hidden. As workaround - refresh page and it will appear.
**Expected result:** Create TGT button and Map object is shown on TG info pane without refresh.
The similar problem when we clone task group as GGRC-4228.
After cloning there is no ability to edit and clone task group. After refresh all is ok.
1. Login as Global Reader.
2. Create Workflow with default Task Group. Global Reader should be Admin in Workflow.
3. After redirect to setup tab refresh the page.
4. Clone TaskGroup.
5. Press on cloned Task Group. …
> GGRC-4228/4248/4251 Global Reader cannot create/clone TaskGroupTask until refresh the page

- src/ggrc/rbac/permissions_provider.py
- src/ggrc_basic_permissions/roles/Creator.py
- test/integration/ggrc/proposal/test_proposal_permissions.py
Global creator and program editor/owner/reader has no right permissions on proposals.
user with read ACL on control has no permission to create proposal.
as global creator try to propose changes as program reader/owner/editor for related to program control 
as global creator with ACL (read/update) role try to create proposal 
Add condition that will add hook on permissions checker. This will grant permissions to the proposals based on it instance property.
> GGRC-4232,4237 Add custom permissions handling

- src/ggrc/cache/cache.py
- src/ggrc/services/common.py
- test/integration/ggrc/services/test_revision_history.py
This is a temporary solution to object history bugs from ticket GGRC-4242. The full fix should be done on dev branch with full memcache support and a different endpoint for fetching object differences.
Note this is an alternative approach for: https://github.com/google/ggrc-core/pull/7188
1. Create a Control
2. Make a proposal
3. Apply/ Decline proposal
4. Go to Version History tab: version is displayed
5. Refresh the page: version shows empty columns with ATTRIBUTE/ CURRENT VALUE/ REVISED VALUE
Actual Result: Version History tab shows empty rows
Expected Result: Version History tab shows: ATTRIBUTE/ CURRENT VALUE/ REVISED VALUE
This is the least impact change for the given issue with performance degradation on all revision related tabs.
> GGRC-4242 Remove revisions memcache

- src/ggrc-client/js/models/person.js
Not able to search by GCA for People
1. Have any GCA for People
2. Go to My Work page and open Global Search
3. Select 'People' object type
4. Click 'Add attribute': attribute contains 'name', 'authorizations', 'email'
*Actual Result:* Not able to search by GCA for People
*Expected Result:* User should be able to search by GCA for People
Allow to edit columns for Person type.
It was approved.
> GGRC-3362 Allow to edit columns for Person type

- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/models/audit_models.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/cycle_models.js
- src/ggrc-client/js/models/person.js
- src/ggrc-client/js/models/workflow.js
- src/ggrc/models/mixins/base.py
- test/integration/ggrc/converters/test_export_assessments.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_snapshot_block.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/integration/ggrc_workflows/converters/test_column_definitions.py
- test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
- test/selenium/src/lib/constants/element.py
Rename 'Last Updated' column to 'Last Updated Date' for all objects
1.Tree View columns
2.Set visible fields for <object> pop up 
3.Global Search columns
4.Export
5.Import template
> GGRC-3259/GGRC-4151/GGRC-4152 Rename 'Last Updated' to 'Last Updated Date'

- src/ggrc/query/autocast.py
- src/ggrc/query/builder.py
- src/ggrc/query/default_handler.py
- src/ggrc/query/my_objects.py
- src/ggrc/query/pagination.py
- src/ggrc/query/utils.py
This is just prep work for custom api endpoints for object history and related assessments. 
Since bothe of those will need pagination, we should ensure that all places will use the same functions for order by and limit.
Check that order by and limit still work. The order by should be tested with more than a single column like clicking on the top of tree view supports.
I have encapsulated and separated limit and order by functions and moved them to their own module.
> QUICK-FIX Cleanup query builder

- src/ggrc/assets/mustache/audits/extended_info.mustache
Audit LHN tooltip issues:
1. /H6 text near the Report Period field
2. NOT SET text below is bigger than Header (the same field)
Check audit tooltip in LHN.
Close h6 tag.
> GGRC-1853 Fix audit tooltip markup (LHN)

- src/ggrc/assets/mustache/help/filters_helper_content.mustache
Update search tooltip text:
- Use parentheses to create more complex searches. For example, (title ~ PCI OR title ~ ISO) AND description ~ “needs to be”
- Filters are case insensitive. For example, title is the same as Title or TITLE
- AND has precedence over OR
- Use quotes every time space (“ “) or any other special character is part of search phrase or filter expression. For example, “modified date” > 03/03/2015 AND "primary contacts" = “example@google.com”
- Valid date formats are MM/DD/YYYY, YYYY-MM-DD
> GGRC-3064/GGRC-4172 Update search tooltip text

- bin/check_migration_history
Each time when a migration is merged the developers have to run `alembic <module_name> branches` for each `<module_name>` in a set of 4.
From the container, run:
```bash
check_migration_history
```
For OK chains, it'll report OK.
For broken chains, it'll return the list of heads.
If any chain is broken, the error code will be non-zero.
Just a script with a `for` with a call to check migration heads inside.
It takes 20 seconds on my machine to finish, that's why I didn't add it to `run_integration` as it can slow down somebody's workflow. If you have an idea how to use it for our CI cleanly, please try to. :)
> QUICK-FIX Add a simple migration chain checker

- src/ggrc/settings/default.py
Bump current version on dev branch.
Open the app and check the version number
> QUICK-FIX Bump version to 1.4.0-Strawberry

- src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.js
- src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.mustache
- src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
- src/ggrc-client/js/components/gdrive/tests/gdrive_picker_launcher_spec.js
- src/ggrc-client/js/components/unmap-button/tests/unmap-button_spec.js
- src/ggrc-client/js/components/unmap-button/unmap-button.js
- src/ggrc-client/styles/components/folder-attachments-list/folder-attachments-list.scss
Add spinners while adding/deleting evidence for Control
1. Have program with mapped control
2. Go to Controls tab > Control's info pane
3. Add folder 
4. Attach evidence: spinner is not shown while attaching
5. Delete evidence: spinner is not shown while deleting
*Actual Result:* There is no spinner while adding/deleting evidence for Control
*Expected Result:* Spinner should be displayed while adding/deleting evidence for Control
https://drive.google.com/corp/drive/folders/0B7_NYFVmb896YmVESEZVblBCX2c
Add spinner component switching based on 3 conditions - loading, unmapping, attaching.
> GGRC-2791 Add spinner to folder-attachments component

- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js/models/workflow.js
Object Review - Submit for review window doesn't not respond
2. Expand Controls Info pane and click [Submit for Review] link
3. Assign reviewer and set a due date
4. Click Submit for review
**Actual Result:** While clicking Submit for review button, submit for review popup is not closed and Apply/ Declined controls are not displayed in Control Info pane
**Expected Result:** While clicking Submit for review button, submit for review popup should be closed and Apply/ Declined controls should be shown up in Control Info pane
It's a regression issue after 9efbf3f commit when was set default task_group_title value. When task_group_title is set TaskGroup with default data is created after creating Workflow. But ApprovalWorkflow requires TaskGroup with …
> GGRC-4302 Fix issue with creating object review

- src/ggrc-client/js/components/proposal/templates/review-proposal.mustache
- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
- src/ggrc/assets/mustache/modals/modal_compare_header.mustache
'proposal-comparer' doesn't display instructions (description) for columns
1. Go to Control / Risk info pane / page.
2. Open 'Change Proposals' tab.
3. Click 'Review & Apply' button.
_Actual result:_ There are no instructions,
_Expected result_: There should be instructions:
1) Left column - 'Current version: <date and time, when the version was created>
2) Right column - 'Proposal: <person who created> <date and time, when the proposal was created>
Add instructions (description) to 'proposal-comparer'
> GGRC-4219 Add instructions for columns on compare pop-up

- src/ggrc-client/js/components/related-objects/revisions/related-revisions.js
Version History tab is not refreshed after Restore and Editing an object
1. Create a control
2. Propose changes and apply them
3. Go to Version History tab
4. Restore current version: new revision version is not shown up
_Actual Result_: Version History tab is not refreshed after Restore and Editing an object
_Expected Result_: Version History tab should be refreshed after Restore and Editing an object
Handle 'modelAfterSave' event and call 'loadRevisions' method
> GGRC-4244 Version History tab is not refreshed after Restore and Editing Control

- src/ggrc/models/assessment.py
Remove dead code from our codebase
Check if similar assessments still work
Simple removal of code that is not referenced anywhere.
> QUICK-FIX Remove obsolete similarity_options

- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/js/controllers/tests/info_pin_controller_spec.js
- src/ggrc-client/styles/modules/_info-pin.scss
Can not change the height and can not close Control's Info pane if change the screen resolution or the screen size
1. Navigate to Control’s Info pane at the program page
2. Click + to Maximize height
3. Change the screen size
**Actual Result:** Can not change the height and close Control's Info pane if change the screen resolution or the screen size
**Expected Result:** scrolling should give the possibility to up and down Info pane so the tree view is shown and the possibility to change Info pane size and close it 
**Note:** check the behavior for all objects
Set height in percentages instead of px.
> GGRC-937  Fix issue when impossible to close info pane after window resizing

- src/ggrc-client/js/components/related-objects/proposals/related-proposals-item.js
- src/ggrc-client/js/models/proposal.js
Time is displayed differently in Change Proposals tab:
1. Create a control
2. Make a proposal and decline it
3. Go to Change proposal tab and hover over Decline label
4. Compare proposed time and decline time in tooltip and in the tab
_Actual Result_: Time is displayed differently in Change Proposals tab
_Expected Result_: Correct time should be shown in Change Proposals tab
"GGRC.Utils.formatDate" method doesn't set current time zone if receive date as string.
Solution: pass date to "GGRC.Utils.formatDate" method as "Date" object
> GGRC-4246 Time is displayed differently in Change Proposals tab

- src/ggrc_workflows/models/cycle_task_group_object_task.py
This PR is `on hold` until @iSokrat  approve desired JSON fields:
**After @iSokrat approve provided protocol it can be reviewed and merged separately without FE part, cause it is not breaking anything on FE. It just adds 3 fields to CycleTask JSON response.**
This is needed by FE to show parent's static info for CycleTask assignee, who doesn't have access to parent Workflow and CycleTaskGroup.
**Added fields are next:**
Check cases from tickets GGRC-4032, GGRC-4289.
Added workflow, workflow_title, cycle_task_group_title attributes to CycleTask response JSON. It is needed to show this information as static text on MyTasks/All Objects pages for CycleTasks. CycleTasks Assignee can be without permissions for CycleTaskGroup or Workflow objects so they cannot be queried properly by FE. …
> GGRC-4032 Add attributes needed by frontend to show static info on CycleTask

- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
- src/ggrc-client/js/components/workflow/workflow-activate.js
- src/ggrc-client/js/models/task_group.js
- src/ggrc/assets/mustache/dashboard/internav_list.mustache
- src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
- src/ggrc/assets/mustache/task_groups/tree_add_item.mustache
- src/ggrc/assets/mustache/workflows/info.mustache
When Task Group is created then extra requests will be created.
1. Create any WF 
2. Open Dev tools>Network 
3. At the setup tab create a Task group and look at the queries in Network tab 
**Actual Result**: Creating of TG triggers 9 requests 
**Expected Result**: Improve performance while creating a task group (remove extra requests)
I've removed extra requests as possible.
The issue was partially appeared when CanJS rerendered componentes inside several helpers. Thus
each component inside rendering area will call apoppriate methods for initializing itself (init, inserted and so on) which can make several non-pure actions (in our case - make requests to the server).
I think we need to refactor internav_list template in the future for using component way. It'll give …
> GGRC-4270 Creating of TG triggers 2 extra requests

- src/ggrc-client/js/mustache_helper.js
Object review: Tasks assignee doesn't see Approve/Decline buttons
1. Log as admin user and Submit Task for review. Assign Global Reader as reviewer
2. Log as Global Reader
3. Open info panel of object for which you submitted the task
*Actual result:* Approve/Decline buttons are not shown, instead you can see text REVIEW IN PROGRESS BY ...
*Expected result:* Approve/Decline buttons should be available for assignee
There was used incorrect ACL role.
> GGRC-4330 Use correct Assignee-role

- bin/do_deploy
This pull request might fix current current failing deployment to ggrc-dev. 
This change can be tested by deploying manually from machine or using one of kokoro-qa deployment job. The verification would be, there shouldn't be any interactive prompts (like Do you want to continue...) for gcloud app deploy command.
Currently when it tries to deploy to using gcloud deploy command it keeps hanging with the prompt "Do you want to continue (Y/n)?". This pull request disables all such prompts while deploying.
I have tested this pull request by deploying in the sandbox environment more than 10 times and it is passing consistently.
I also tried upgrading the cloud sdk version to 186.0.0 but it also doesn't solve this issue. The deployment failed in the same way even with the latest sdk version.
> GGRC-4299 Disable all interactive prompts when running gcloud deploy command

- src/ggrc-client/js/components/assessment/assessment-local-ca.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
- src/ggrc-client/js/components/ca-object/tests/ca-object-modal-content_spec.js
Comment is not saved in LCA field while saving it for the first try and cannot complete assessment 
1. Have an audit with a control snapshot
2. Create assessment template with LCAs:
- text - mandatory
- Dropdown: comment required - mandatory
3. Autogenerate assessment based on the assessment template and a control snapshot
4. Expand assessment Info pane
5. Fill out LCA with text type and quickly select an option that required a comment from LCA with dropdown type 
6. Click Complete button
*Actual Result:* Comment is not saved in LCA field while saving it for the first try and cannot complete assessment 
*Expected Result:* User should be able to complete assessment while LCA has a green mark
https://ggrc-test.googleplex.com/assessments/17733
The issue was caused by only …
> GGRC-4268 Fix LCA change-flow on assessment info-pane

- src/ggrc_workflows/models/cycle_task_entry.py
- test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
By mistake SQLAlchemy considered CycleTaskEntry (comment) model as parent in relationship between CycleTask and CycleTaskEntry.
Preconditions:
- have any active wf
1. Go to Active Cycles tab
2. Expand Cycle task Info pane
3. Add a comment
4. Click Delete CycleTask button in 3 bb's menu
**Actual Result:** JS error is displayed while deleting Cycle task with comment. Cycle task is not deleted
**Expected Result:** no errors should be displayed while deleting a cycle task with a comment
[By SQLAlchemy documentation](http://docs.sqlalchemy.org/en/latest/orm/cascades.html#cascades) backref for parent relationship should define cascade option.
> GGRC-4335 Cascade delete comment on CycleTask delete operation

- src/ggrc-client/js/components/form/fields/rich-text-form-field.js
- src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc-client/js/components/people/people-list-info.js
- src/ggrc-client/js/components/people/people-list-info.mustache
- src/ggrc-client/js/controllers/tree/list_view_controller.js
- src/ggrc-client/js/controllers/tree/tree-loader.js
- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/js/entrypoints/admin/index.js
- src/ggrc-client/js/entrypoints/dashboard/index.js
- src/ggrc-client/js/plugins/openclose.js
- src/ggrc/assets/mustache/custom_attributes/info.mustache
Conflict message is shown because Person instance doesn't have Etag.
1. As admin go to the administration > People tab
2. Select any user and click grey triangle to expand Info pane 
3. Edit GCA: Conflict message is shown
_Actual Result_: Inline editing doesn't work for Peoples via administration. Conflict message is shown and a value is not saved
_Expected Result_: Inline editing should work for Peoples via administration
Refresh instance when info-pane is opening
> GGRC-3347 Inline editing doesn't work for Peoples via administration

- src/ggrc-client/js/components/object-list-item/comment-list-item.mustache
- src/ggrc-client/styles/_colors.scss
- src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
Proposal link has wrong text
1. Go to Control / Risk info pane/page.
2. Create a proposal.
_Actual result_: Comment with link 'Proposal' is added to an object.
_Expected result_: Link should be renamed to 'Change Proposal'.
Change text of link
> GGRC-4254 Change comment link to 'Change Proposal'

- src/ggrc-client/js/generated/ggrc_filter_query_parser.js
- src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
- src/ggrc-client/js_specs/generated/ggrc_filter_query_parser_spec.js
- src/ggrc/assets/mustache/help/filters_helper_content.mustache
- src/parser/generate_parser.js
- src/parser/parser.pegjs
- src/parser/parser_template.js
Keys and order_by props inside filters are ignored by BE. So they should be removed from search query parser.
Check advanced search
> GGRC-4134 Remove keys, order_by from search query parser result

- src/ggrc-client/js/components/issue/issue-unmap-dropdown-item.mustache
'Unmap' button is displayed as 'Unmap from Issue' in 3 bb's menu if trying to unmap Assessment from Issue
1. Have an audit with snapshot A
2. Create Assessment 1 and map snapshot A to assessment 1
3. Raise an Issue via Assessment Info pane
4. Open Issue page in a separate tab
7. In the Assessments tab click Assessment and open 3 bb's menu: 'Unmap from Issue' is shown
Actual Result: 'Unmap' button is displayed as 'Unmap from Issue' if trying to unmap Assessment from Issue
Expected Result: Wording 'Unmap' should be displayed in 3 bb's menu if unmap Assessment from Issue.
Change wording.
> GGRC-3653 Fix "unmap issue" wording

- src/ggrc/utils/revisions.py
Temporary comment create and update revision steps in `refresh_revision` job.
N/A
N/A
> GGRC-4374 Comment out update and create revisions steps

- src/requirements-dev.txt
Every new container (including CI) fails to build.
1. Clone the project anew.
2. Run `./bin/containers setup`
Pylint expects isort version higher than 4.2.5 and the tried to install
4.3.0 which is broken at the moment. This fix is just to ensure pylint
works as expected.
> GGRC-4377 Add pylint dependency explicitly

- src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc-client/styles/components/inline/_inline.scss
- src/ggrc/assets/mustache/custom_attributes/info.mustache
An asterisk symbol doesn't show for mandatory custom attributes on info-pin/info-pane
1. As Admin user go to Administration page
2. Add custom attribute field with any type to Control which is required
3. Create a Control and look at the custom attribute field on Control info pane/page
_Actual Result_: If custom attribute is required, there is no asterisk on object Info pane/page
_Expected Result_: If custom attribute is required, there should be an asterisk on object Info pane/page
1) Display the asterisk for mandatory custom attributes;
2) Fix the highlighting of invalid values in inline component
> GGRC-4198 Add asterisk for mandatory custom attributes on object Info pane

- src/ggrc/models/hooks/issue_tracker.py
Just the message is wrong
1. Go to Audit with Buganizer switch turned ON.
2. Click Create assessment button.
3. Fill in all the required fields.
4. Make sure that Buganizer is turned ON for Assessment.
5. Enter non-existing Hotlist ID/ Component ID
7. Click 'Save' button for assessment.
Expected Result: 'Unable to create a bug' warning message should be displayed
N/A
> GGRC-3990 Improve generic message if issuetracker issue is not created

- src/ggrc/query/builder.py
- src/ggrc/query/pagination.py
- src/ggrc/services/__init__.py
- src/ggrc/services/common.py
- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
~On hold until frontend part is finished, so we can see if this part needs any modifications. Even though this could be merged before frontend is finished, we will still wait to avoid too many PRs for small changes that might take place.~
This PR should be safe to merge before the frontend part is finished. but FE is good to verify that everything works.
Add optimized endpoint for related assessments
This speeds up fetching data for related assessment from 6s +  to around 0.1s on a smaller test sample.
More benchmarks will be added.
- Check that related assessments still work without frontend changes. pay attention to pagination and sorting of current assessments.
- Check sorting and pagination on normal tree views (due to changes in query api code)
- Check different api calls (listed …
> GGRC-3636 Related assessment resource

- src/ggrc/fulltext/attributes.py
- test/integration/ggrc/fulltext/test_mysql.py
Reindex reserve allot of memory. Some that memory allocated to index non searchable acls.
This is required to be fixed. 
Rerun reindex with ggrc-qa dump 
FE may use query api to filter some data base on internal roles. This is require some investigation.
If this is the true, then this fix require to add extra column in ACR. This setting called `indexed`. It should be true by default and set it to false only if it's really needed. 
Add datamigration that will setup false to each populated mapped role. 
Stop index internal roles
> GGRC-4394 Not index internal ACLs

- Makefile
- src/requirements-dev.txt
Update some outdated python libraries to remove some warnings
> GGRC-4377 Update pyhon libraries

- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
- src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
- src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.mustache
- src/ggrc-client/js/models/assessment.js
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/audits/modal_content.mustache
Remove 'buganizer' word from application.
1. Rename 'Buganizer' column into 'Ticket Tracker':
in assessment tree view.
2. Rename 'Buganizer' section into 'Ticket Tracker' on:
Audit info pane / page;
Audit edit / add pop-up;
Assessment info pane / page (Other attributes tab);
Assessment edit / add pop-up;
Assessment Template info pane / page;
Assessment Template edit / add pop-up;
3. Rename 'Buganizer Link' into 'Ticket' on:
Assessment info pane / page (Assessment / Other Attributes tabs).
4. Rename 'Show/Hide Buganizer info' to 'Show/Hide Ticket Tracker Info'
Change wording
> GGRC-4300 Rename 'Buganizer' into 'Ticket Tracker'

- src/ggrc/models/hooks/issue_tracker.py
Bad message on unavailability to create or update an issuetracker ticket.
1. Go to Audit with Buganizer switch turned ON.
2. Click Create assessment button.
3. Fill in all the required fields.
4. Make sure that Buganizer is turned ON for Assessment.
5. Enter non-existing Hotlist ID/ Component ID
7. Click 'Save' button for assessment.
Expected Result: 'Unable to create a ticket.' warning message should be displayed
N/A
> GGRC-3990 Improve generic message if buganizer issue is not created

- src/ggrc/app.py
- src/ggrc/maintenance_views/maintenance.py
- src/ggrc/migrate.py
Check with launch_gae_ggrc that maintenance page and the app still work
This just cleans up some minor things in our code, no functional changes should be present in this PR.
> QUICK-FIX Cleanup minor code issues

- src/ggrc/notifications/common.py
- src/ggrc_workflows/__init__.py
During CONTRIBUTED_CRON_JOBS execution memory limit on the instances is exceeded. This causes instance shut down.
memory_profiler could be run locally on start_recurring_cycles on any db dump with significant amount of data (e.g. qa).
In according to memory_profiler the biggest amount of memory is consumed during db commit:
The memory is freed after commit execution:
The temporary hot fix split single db commit into multiple ones - one commit per workflow cycle. This helps to free memory after each commit being executed:
Perfomance note: on the local qa dump execution time after hot fix applying has been increased from 186.1 s to 210.63 s.
> GGRC-4406 Hotfix to reduce start_recurring_cycles cron job memory consumption

- src/ggrc-client/js/controllers/summary_widget_controller.js
- src/ggrc-client/js/controllers/tests/summary_widget_controller_spec.js
- src/ggrc-client/styles/modules/_audit-summary.scss
- src/ggrc/assets/mustache/audits/summary.mustache
- src/ggrc/services/resources/audit.py
- test/integration/ggrc/services/test_summary.py
This PR is BE part of GGRC-3979. ~It will be `on hold` until dependencies are merged~ This PR contain commits from GGRC-3979:
Modify response for GET request '/api/audits/<audit_id>/summary' into next kind of structure:
{
statuses: [
{
name: "Not Started",
assessments: X,
documents: Y
},
{name: "In Progress", ...},
{name: "In Review", ...},
{name: "Completed and Verified", ...},
{name: "Completed (no verification)", ...},
{name: "Deprecated", ...},
{name: "Rework Needed", ...}
],
total: {
assessments: N,
documents: L
}
}
X - number of assessments with this status;
Y - number of documents attached to assessments with this status;
N, L - total count of assessments, documents accordingly in this audit.
Send GET request to '/api/audits/<audit_id>/summary' and check if result has format as …
> GGRC-3979,4003 Add evidence to summary

- src/ggrc/models/categorization.py
- src/ggrc/models/control.py
- src/ggrc/models/hooks/proposal.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/proposal.py
- src/ggrc/models/revision.py
- src/ggrc/models/utils.py
- src/ggrc/utils/referenced_objects.py
- src/ggrc/utils/revisions_diff/applier.py
- src/ggrc/utils/revisions_diff/builder.py
- src/ggrc/views/cron.py
- test/integration/ggrc/proposal/test_proposal_api.py
Need to cleanup some code.
Fix pylint and flake8 warnings for related to proposal epic files.
> GGRC-4203 Fix codestyle issues from proposal PR 

- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/styles/modules/_tree-content.scss
- src/ggrc/assets/mustache/people/tree-item-attr.mustache
- src/ggrc/assets/mustache/people_roles/info.mustache
Person Authorization is not displayed in People tab if a person was added via Custom role field
2. Add Primary and secondary contacts person to the program
3. Go to the People tab and look at the authorization column
**Actual Result:** Person Authorization is not displayed in People tab if a person was added via Custom role field
**Expected Result:** Person Authorization should be displayed in People tab if a person was added via Custom role field
Issue was fixed in #7076 PR. So only design for person authorization is updated in this PR.
> GGRC-3871 Display person Authorization in People tab if a person was added via Custom role field

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc/assets/mustache/base_objects/form_restore.mustache
Fields hide before rerender.
Also, "displayState.ui_array" has wrong values.
2. On program Info page click Add tab and click Audits
3. Close Audit Creation modal window
4. Go to Audit tab then click 'Create' button
_Actual behavior_: 'Show all optional fields' is displayed but all fields are expanded
_Expected behavior_: 'Hide all optional fields' is displayed
1) Do not override "displayState.ui_array" array. Assign copy of this array to "options.ui_array".
2) Call "restore_ui_status_from_storage" function when "fetch_all" is completed.
> GGRC-4049 Invalid behavior of 'Show/Hide all optional fields' button on create object modal

- src/ggrc/migrations/versions/20180112085248_4906ff3f9c7b_add_last_comment_computed_attr.py
This PR fix warnings in migration from #7203
> QUICK-FIX Resolve migration warnings

- src/ggrc-client/js/components/comment/comment-add-form.js
- src/ggrc-client/js/components/last-comment/last-comment.js
- src/ggrc-client/js/components/last-comment/last-comment.mustache
- src/ggrc-client/js/components/last-comment/last-comment_spec.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/events/eventTypes.js
- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
Add column with last comment for assessment tree-view.
UX: https://drive.google.com/file/d/0B7_NYFVmb896YUh5LWdiS2dWLUk/view
Add a new property `last_comment` for the Assessment model.
Add new component `last-comment` which displays description of comment without html tags.
When you hover over text of `last-comment`, it loads the comment object and then displays tooltip with created date and author email.
When a new comment is created, it dispatches the `commentCreated` event on an assessment instance, which is handled in `last-comment` component.
> GGRC-2786 Add "Last Comment" column for assessments tree-view

- src/ggrc-client/js/components/object-list-item/business-object-list-item.js
No icon is shown in Assessments info pane for Access Group snapshot
1. Have audit with mapped Access Group's snapshot
3. Map Access Group's snapshot to Assessment
4. Expand Assessment's Info pane and look at the Related Information
_Actual Result:_ No icon is shown in Assessments info pane for Access Group snapshot
_Expected Result:_ Icon should be shown in Assessments info pane for Access Group snapshot
Use 'table_singular' to build icon css class
> GGRC-2271 No icon is shown in Assessments info pane for Access Group snapshot

- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
- src/ggrc-client/js/models/cycle_models.js
1. Make changes for a Task.
2. Add 'Last Deprecated Date' on :
Task info pane;
Global Search;
'Set visible fields for <object>' pop-up (on widget and unified mapper)
as a column on Workflow Task tab.
as a column on Global Search.
Export spreadsheet.
4. Date should be autopopulated with current date, when Task status is changed to 'Deprecated'.
5. If deprecated object is moved to another state, then keep date unchanged.
6. User should not be able to update date manually.
Do NOT add 'Last Deprecated Date' on:
'New Task pop-up;
'Edit Task' pop-up;
Import spreadsheet.
Import page.
7. Allow user to search Tasks by Last Deprecated Date (advanced search).
8. Allow user to filter Tasks by Last Deprecated Date.
9. Allow …
> GGRC-3502/GGRC-4243 FE: Add "Last Deprecated Date" to Cycle Tasks

- src/ggrc-client/js/mustache_helper.js
Lots of `indent` eslint errors in the `mustache_helpers.js` file
Apply `eslint --fix` for `mustache_helpers.js` file only with `indent` rule in eslint config
> QUICK-FIX Fix eslint indent rule in mustache_helper.js

- docs/source/contributing/git/reviewing_pull_requests.rst
The paragraph containing the guidelines for reviewing PRs with migrations should be updated.
Check the https://github.com/google/ggrc-core/blob/dev/docs/source/contributing/git/reviewing_pull_requests.rst 
NA
> DOCS Update the review pull request guide

- src/ggrc_basic_permissions/roles/Creator.py
- src/ggrc_basic_permissions/roles/Reader.py
Global Readers & Creators with program level (Managers, Editors) and audit level roles (Audit Leads) were not able to add objects into audit scope.
1. Log as Global Creator
2. Create a program
3. Create and map audit to the program
4. Open Audit page
5. Map object to the audit, e.g. control
Actual Result: "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server." warning message is shown up. POST 403 is displayed in console
Expected Result: Global Creator as Program manager and Audit Captain should map object to audit
NOTE: it is necessary to check the behavior for Global Reader/Editor es well.
Add a update check for audit when creating snapshots. I am now writing new tests for this. I'll add them to the …
> GGRC-4424 Fix adding objects into audit scope for global readers & creators

- test/integration/ggrc/proposal/test_proposal_permissions.py
add test on query api for proposals
nothing to test, just review test 
add test and no more else
> GGRC-4385 Add test for proposals over query api

- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/styles/dashboard.scss
- src/ggrc-client/styles/layout/_content.scss
- src/ggrc-client/styles/layout/_footer.scss
- src/ggrc-client/styles/layout/_header.scss
- src/ggrc-client/styles/modules/_distraction-free-view.scss
- src/ggrc-client/styles/modules/_header-content.scss
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/layouts/dashboard.haml
This PR replaces closed #7148 and #7187 PRs.
There're couple layout issues: Page content is overlapped by footer + the page has 2 scrolls.
Case 1:
1. Login as Admin user
2. Go to administration page and add GCAs to Regulation (at least 10 GCAs)
3. Create Regulation and open it.
4. Scroll down to see "Created date" and "Last update by"
**Actual Result:** "Created date" and "Last update by" are not shown in the bottom of the page if object contains GCAs 
**Expected Result:** "Created date" and "Last update by" should be shown in the bottom of the page if object contains GCAs
Case 2:
1. Log as "user-1"
2. Create Standard
3. Click Submit for review, add reviewer ("user-2") and select a date
4. Log as "user-2"
5. Click Approve button
6. Look at the "Modified by "user" in the bottom of the Info …
> GGRC-4169/GGRC-1632 Fix page layout

- src/ggrc-client/js/mustache_helper.js
- src/ggrc/assets/mustache/people/tree-item-attr.mustache
- src/ggrc/assets/mustache/people_roles/info.mustache
"Uncaught TypeError: Cannot read property 'filter' of undefined" error message occurs while searching People in Global Search.
1. As Admin user go to My work page 
3. Choose Objects type 'People' and click on Search button
**Actual Result:** "Uncaught TypeError: Cannot read property 'filter' of undefined" error message occurs while searching People in Global Search. The app freezes until user refreshes the page.
**Expected Result:** no errors should be displayed while Searching People in Global Search
Check if access_control_list prop is defined for page instance.
Also update helper to have ability to set object instance to get user roles for. If object instance is not set global role should be shown.
> GGRC-4449 Js exception occurs while searching People in Global Search

- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
- src/ggrc-client/js/models/workflow.js
'Need verification' checkbox is switching on while new workflow is saving.
1. Open new Workflow popup
2. Fill out the fields required and click save button
3. Look at the "NEED VERIFICATION FOR TASKS?" checkbox: is checked
*Actual Result*: 'Need verification' checkbox is switching on while new workflow is saving
*Expected Result*: 'Need verification' checkbox should not switch on while new workflow is saving
*WORKAROUND*: until workflow is not activated user can uncheck NEED VERIFICATION checkbox via Edit workflow modal window.
From @ahetmanski - seems that it is back-end issue: is_verification_needed is not set by front-end while create new workflow. 
Solution: FE will set is_verification_needed explicitly to false when a user didn't set checkbox NEED VERIFICATION FOR TASKS.
> GGRC-4348 'Need verification' checkbox is switching on while new workflow is saving

- src/ggrc/models/hooks/issue_tracker.py
Wording 'Test plan' is displayed instead of 'Assessment procedure' in Issue Tracker.
Buganizer integration should be turned on.
Precondition:
1. Control snapshot with Assessment procedure is mapped to Assessment, 'Copy Assessment procedure' is checked;
2. Buganizer is switched on for Assessment with valid Component ID and Hotlist ID.
1. Navigate to Assessment Info pane and click 'Buganizer' link;
2. Look at the BUG.
Wording 'Assessment procedure' should be displayed instead of 'Test plan'.
Wording for assessment procedure is hardcoded in the issue_tracker.py. It's been changed to a required one.
> GGRC-4068 Change wording in issue tracker

- src/ggrc_risk_assessments/migrations/versions/20180207134809_4b3a070f5f00_add_state_field_for_risk_assessment_.py
- src/ggrc_risk_assessments/models/risk_assessment.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/mixins/test_stateful.py
Add `status` field for `RiskAssessment` object with next valid statuses: `Draft`, `Active`, `Deprecated`
1. Create new `Program`
2. Add new tab `Risk Assessment`
3. Create new `Risk Assessment` object
State field is available for this object
1. A migration has been written that adds a new field `status` (type - `string`) to the `risk_assessments` table.
2. `Stateful` mixin has been used for adding `status` field to `RiskAssessment` class.
> GGRC-2009 Add 'State' field for Risk Assessment object

- .eslintrc.json
- src/ggrc-client/js/components/diff/diff-base-vm.js
- src/ggrc-client/js/components/diff/instance-list-fields-diff.js
- src/ggrc-client/js/components/diff/instance-mapping-fields-diff.js
- src/ggrc-client/js/components/sort/sort-by.js
- src/ggrc-client/js/components/sort/tests/sort-by_spec.js
- src/ggrc-client/js/models/control.js
- src/ggrc-client/js/models/mixins.js
- src/ggrc-client/js/plugins/utils/models-utils.js
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/controls/tree-item-attr.mustache
ASSERTIONS/CATEGORIES values are not cleaned from Control Info pane after clicking 'Discard' button in Edit Control popup
1. Create a control w/o filling out ASSERTIONS/CATEGORIES fields
2. Invoke Edit Control popup
3. Set any values for ASSERTIONS/CATEGORIES fields
4. Click Discard button and look at the ASSERTIONS/CATEGORIES fields on the Control Info pane
_Actual Result_: ASSERTIONS/CATEGORIES values are not cleaned from Control Info pane after clicking 'Discard' button in Edit Control popup
_Expected Result_: ASSERTIONS/CATEGORIES values should not be changed on Control Info pane after clicking 'Discard' button in Edit Control popup
1) Clear _categories_ and _assertions_ before refresh.
2) Update '_sort-by_' component to avoid use '_using_' helper, because it works incorrect with …
> GGRC-4193 ASSERTIONS/CATEGORIES values are not cleaned from Control Info pane after clicking 'Discard' button in Edit Control popup

- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/base_templates/mapped_objects.mustache
- src/ggrc/assets/mustache/cycle_task_group_object_tasks/modal_content.mustache
Remove 'Map object to this Assessment' tooltip (Add / Edit Assessment)
Tooltip was removed from Add/Edit Assessment pop-up and also from Add/Edit CTGOT pop-up.
> GGRC-4160 Remove tooltip from 'Map Objects' buttons

- src/ggrc/migrations/versions/20180208105738_19a260ec358e_create_import_exports_table.py
- src/ggrc/models/import_export.py
Create table needed for storing all import export data and model for it
Run db_reset
ImportExport model is needed only to access to import_exports table. It hasn't be indexed as it will be accessed only from /api/people/person_id/import and /api/people/person_id/import endpoints.
> GGRC-4273 Create tables needed for storing all import export data

- src/ggrc_workflows/migrations/versions/20180115094803_58e0f07e174b_move_user_roles_to_acl.py
Migration for moving WF roles to ACL use a lot of memory 
run migration on the huge pull of data and see that memory usage is less 
1) split migration to small chunks
2) free memory if it's data inserted
3) split procedure to 2 steps (parent role insert, insert roles based on context). Garbage Collector will free memory after function will be done.
> GGRC-4479 Change WF migration to use less memory

- src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
- src/ggrc/assets/mustache/base_objects/mapper-item-description.mustache
Notes are shown with tags in Global Search.
1. Go to My work page and invoke new program modal window
2. Fill title 
3. Fill Notes and press "Enter" several times > Save
4. Open Global Search and find created program
5. Click triangle to see a description
**Actual Result:** Notes is shown with tags in Global Search
**Expected Result:** Notes should not be shown with tags in Global Search
Do not escape notes value.
> GGRC-4138 Do not show tags for notes in Global Search

- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
Actual:
Assessment Template creation modal contains a singular form attr's name "Default Verifier"
Expected:
Assessment Template creation modal should contains a plural form attr's name "Default Verifiers".
> GGRC-4115 Update label for 'Default Verifier' in Assessment Template

- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
Rename selfLink to view link
Trigger the endpoint for related assessmentsa and check that it contains `viewLink` with the correct data.
Rename selfLink to view link
> GGRC-4451 Rename selfLink to viewLink

- src/ggrc-client/js/components/csv/export.js
- src/ggrc-client/js/components/csv/import.js
- src/ggrc-client/js/controllers/gapi_controllers.js
- src/ggrc-client/js/controllers/modals/gapi-modal.js
- src/ggrc-client/js/plugins/ggrc-gapi-client.js
- src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
- src/ggrc/gdrive/__init__.py
- src/ggrc/gdrive/file_actions.py
- src/ggrc/templates/gdrive/auth_gdrive.haml
- src/ggrc/views/converters.py
- test/integration/ggrc_gdrive_integration/test_gdrive_auth.py
User can't import/export if auth token is invalid.
The description is in the JIRA issue.
If BE can't use token it returns Unauthorized (HTTP 401) and FE handles this case by asking the user to authorize again.
> GGRC-4417 Fix of the import error (Refresh token problem)

- src/ggrc-client/js/models/risk_assessment.js
- src/ggrc/assets/mustache/risk_assessments/modal_content.mustache
FE: Add 'State' field for Risk Assessment object
Add "State" field on:
- Edit Risk Assessment modal window;
- New Risk Assessment modal window.
Allow a user to sort Risk Assessments by state.
Add "State" column on Risk Assessment widget.
"State" column should be displayed by default on Risk Assessment widget.
"State" checkbox on "Set visible fields for Risk Assessment" pop-up on widget.
"State" column should be hidden on RA widget if "State" checkbox is unchecked on "Set visible fields for Risk Assessment" pop-up.
"State" column should be displayed on RA widget if "State" checkbox is checked on "Set visible fields for Risk Assessment" pop-up.
> GGRC-4440 Add 'state' field to RiskAssessment model

- src/ggrc-client/js/components/add-object-button/add-object-button.mustache
- src/ggrc/assets/mustache/base_objects/generate_assessments_button.mustache
On the summary page is wrong checks for permissions to display buttons.
1. Create a program as Admin
2. Assign Global Creator as Program Reader
3. Create and map audit to the program 
4. Log as Program Reader and open Audit Summary page
*Actual Result:* Create assessment /Create template/Autogenerate buttons are available for Program Reader
*Expected Result:* Create assessment /Create template/Autogenerate buttons should not be available for Program Reader
Use the same checks as in tree-view on 'Assessments' tab for 'Create' button:
1) 'add-object-button': replace `{{#is_allowed 'create' instance}}` with `{{#is_allowed 'update' instance}}`.
**Note:** There was redundant if-branch with the same check but instead of `instance` there was `parent_instance` which is not …
> GGRC-4434 Create assessment /Create template/Autogenerate buttons are available for Program Reader

- src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
- src/ggrc-client/js/components/workflow/workflow-activate.js
- src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache
There is code inside workflow-activate component with big methods.
There are no changes in the app work.
Component was turned into little parts which are convenient to test and read.
> GGRC-4392/4393 Refactor workflow-activate component

- package-lock.json
- package.json
- src/ggrc-client/js/components/comment/comment-input.mustache
- src/ggrc-client/js/components/form/fields/rich-text-form-field.mustache
- src/ggrc-client/js/components/proposal/templates/apply-decline-proposal.mustache
- src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
- src/ggrc-client/js/components/rich_text/rich_text.js
- src/ggrc-client/js/components/rich_text/rich_text.mustache
- src/ggrc-client/js/components/rich_text/tests/rich_text_spec.js
- src/ggrc-client/styles/modules/_rich-text.scss
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/assessments/modal_content_additional_fields.mustache
- src/ggrc/assets/mustache/workflows/modal_content.mustache
Audit Module - GGRC connection fail when pasting text into comments box in assessment
*REQUIREMENTS:*
1. Only 2000 symbols should be allowed to type into comment field.
2. Show counter of symbols for comment field, it should change while user types ("n/2000").
3. Show red warning instead of counter, if person pastes more then 2000 symbols into comment field ("Maximum characters exceeded 2000/2000").
4. Changes should affect comment fields on all objects, that currently have them.
1) Refactor rich-text component
2) Update quill to latest version
3) Add counter to rich-text component
4) Create unit-tests
> GGRC-4344 Improve rich-text component

- test/integration/ggrc/models/mixins/test_related_assessments.py
- test/integration/ggrc/models/model_factory.py
These are tests writter for related assessment optimization work. They are meant to cover all possible cases of two different assessments being related, so that the refactor work will be safe.
Read and try to understand the tests, you can break some asseessment relatad cases and see if the tests catch them
This is a comprehensive test for all possible ways two diffeerent assessments can be related. The tests try to balance out how complicated they are and how much copy pasted code there is.
A developer should read and try to understand the tests fully and if there is a cleaner way of doing this (without copy pasting same tests many times over) any suggestinos would be helpful.
> QUICK-FIX Extend related assessment tests

- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_asmts_workflow.py
* Add a test to filter assessments based on the template with LCA
* "generate_ca_value" function was modified because "modified_by" is not set for LCA
> QUICK-FIX Test filtering of assessments based on assessment template with LCA

- src/ggrc/services/common.py
- test/integration/ggrc_basic_permissions/test_creator.py
"Failed to fetch revision history data." error message is displayed if Global Creator opens Change Log tab.
Reason of this issue is that permissions for relationship from revision content is calculated in same way as for base relationship for GC. Calculation of permissions for relationship uses source and destination fields, but they are absent in revision content.
1. Log as Verifier (global creator)
2. Open Assessment Info pane
3. Click 'Change log' tab
Expected Result: no errors should be shown while opening Change Log tab
Put in cache instances of revision resource.
Use these cached objects to calculate rights for relationship from revision content.
> GGRC-4136 Fix changelog access for GC user

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/styles/_modules.scss
- src/ggrc-client/styles/_responsive.scss
- src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
- src/ggrc-client/styles/modules/_global-custom-attributes.scss
- src/ggrc-client/styles/modules/_modal.scss
- src/ggrc/assets/mustache/custom_attributes/modal_content.mustache
Create/Edit modal -> hide button breaks layout some times
1) Open Create/Edit modal with GCAs.
2) See GCA in 2 columns.
3) Hide GCA from first column.
`:nth-child(even)` is not skipping hidden elements.
In the PR I used flex to build 2 columns layout.
> GGRC-775 Fix GCA modal layout

- src/ggrc/query/pagination.py
- test/integration/ggrc/services/test_query/test_basic.py
Object tab shows Incorrect count and increased while tab is loading
1. Open My work page
2. Click Systems tab
Object tab shows correct count
Change way of query count calculation
> GGRC-4416 My Work/All Objects/program page tabs show Incorrect count

- src/ggrc-client/js/apps/risk_assessments.js
- src/ggrc-client/js/components/tree/tree-item-actions.js
Filter subtree dialog is empty for Risk Assessment
1. Navigate to the program page
2. Create and map new Risk assessment to the program
3. Hover over first tier of Risk assessment and select Filter subtree
Actual Result: Filter subtree dialog is empty for Risk Assessment
Expected Result: "_Filter subtree_" link should be hidden
Show "_Filter subtree_" link only for items which contain "_available_" models
> GGRC-3726 Filter subtree dialog is empty for Risk Assessment

- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/styles/dashboard.scss
- src/ggrc-client/styles/layout/_content.scss
- src/ggrc-client/styles/layout/_footer.scss
- src/ggrc-client/styles/layout/_header.scss
- src/ggrc-client/styles/modules/_distraction-free-view.scss
- src/ggrc-client/styles/modules/_header-content.scss
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/layouts/dashboard.haml
Reverting the changes made by https://github.com/google/ggrc-core/pull/7301 because they broke the dashboard view.
Dashboard view is way too small
1. Enable dashboards by running `export DASHBOARD_INTEGRATION=True` in docker
2. Start the app with `launch_ggrc`
3. Create a custom attribute on programs/audits that starts with `Dashboard_`
4. Create a program, set the custom attribute to something that starts wit `https://`
5. Go to the dahboard tab
> GGRC-4524 Revert "Merge pull request #7301 from tor4/GGRC-4169"

- src/ggrc/assets/mustache/audits/dropdown_menu.mustache
- src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache
- src/ggrc/assets/mustache/sections/dropdown_menu.mustache
- src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache
Cannot unmap Issue from Snapshot if Snapshot is Archived.
Precondition:
1. Have an Issue mapped to Assessment and Control Snapshot
2. Have Archived Audit
3. Assessment and Snapshot are Archived
1. Go to Issue page
2. Click Control versions tab. 
3. Click Control snapshot to open Snapshot info pane
4. Open 3 bb's menu: Unmap link is not displayed
Actual Result: Cannot unmap Issue from Snapshot if Snapshot is Archived
Expected Result: Allow user to unmap Issue from Snapshot if Snapshot is Archived
Requirements: https://docs.google.com/spreadsheets/d/1lzlBOmi0aDFKLkVPTK1I0cMg9hNvPChsz_y7MX0I_ik/edit#gid=1905740661
1) Remove redundant checks.
2) Add `{{#if_helpers '\
^if' instance.snapshot.archived '\
or #if_instance_of' page_instance 'Issue'}}` check.
> GGRC-3596 Allow unmap snapshots from archived issues

- src/ggrc-client/js/components/related-objects/revisions/related-revisions.js
- src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js
- src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions_spec.js
Added unit tests for "related-revisions" and "related-revisions-item" components
> QUICK-FIX Add unit tests for "related-revisions" and "related-revisions-item" components

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mixins.js
- src/ggrc-client/js/models/tests/cacheable_model_spec.js
The issue was that on a slow internet connection, when assessment info-pane is opened and the Complete button is clicked before the GET request for the instance is returned, a PUT request for the status change is sent with the empty access_control_list. The issue was introduced in [this commit](https://github.com/google/ggrc-core/pull/6794/commits/9d483cac325cb27428bbef366f1ef854e2700615) as a solution to fix the issue GGRC-3758.
1. Generate or create Assessment
2. On assessment info-pane, move it to "In Progress" state (by changing CA for example)
3. Close info-pane
4. Switch to 'Slow 3G' mode in dev-tools in the Network tab
5. Open this Assessment and quickly click the "Complete" button (before the Assessment GET request is completed)
6. Assessment PUT request will go with the empty …
> GGRC-4382,3997,4433,3758 Fix restoring a previous state of an instance.

- pylintrc
Simalirites for imports are sometimes impossible to resolve and do not bring much in code clarity so they can be ignored when checking for duplicate code with pylint
Add 5 identical import lines to two files and run pylint on those two files
Add ignore flag to pylintrc
> QUICK-FIX Ignore imports on plint similarities check

- src/ggrc/data_platform/computed_attributes.py
- src/ggrc/utils/revisions.py
Reindex job triggers computed attributes and those fail on appengine due to memory issues
Verify that the memory consumption is lower on this PR when runining 
`$.post("/admin/compute_attributes")`
I have just removed most of the redundant data that was pulled from the db and not actually needed for the computation of new values.
> GGRC-4500,4309 Improve memory usage on computed attributes

- src/ggrc/snapshotter/indexer.py
- src/ggrc/utils/__init__.py
- src/ggrc/views/__init__.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/fulltext/test_total_reindex.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/integration/ggrc/snapshotter/test_indexing.py
Global reindex job fails with out of memory error.
ggrc-perf has current dev and last commit on this PR deployed with two version `dev` and `reindex-fix` you can manually run reindex commands and look at the results
Split reindex into separate jobs since we seem to retain memory on each step.
This solution is not a proper one, but just a temporary fix to get prod working.
The reindex code must be refactored asap and at that time this PR should be reverted.
> QUICK-FIX Reduce memory consumption for reindex jobs

- src/ggrc/settings/default.py
Update the app version, since 1.5.0 has already branched out to our release branch
Open the app and confirm that the version number is 1.6.0
> QUICK-FIX Bump version to 1.6.0-Strawberry

- src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/general-page-header.mustache
- src/ggrc/assets/mustache/workflows/info.mustache
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/info_widget.py
Remove 'Title' label from object Info page
1. Open Control Info page
2. Look at the title: label 'Title' is displayed
**Actual Result:** 'Title' label is displayed on the Control Info page
**Expected Result:** Remove 'Title' label from object Info page
**NOTE:** implement this for all objects across the app.
Show title label on info-pin and hide otherwise.
> GGRC-3451 Remove 'Title' label from object Info page

- src/ggrc-client/js/controllers/modals/modals_controller.js
Clicking outside modal window "Discard changes" popup is displayed after clicking Save button
2. Add Controls tab and Invoke new Control modal window
3. Fill in fields required and click [Save and Close] button
4. Click outside modal window
_Actual Result_: Clicking outside modal window "Discard changes" popup is displayed after clicking Save button
_Expected Result_: Clicking outside modal window "Discard changes" popup should not displayed after clicking Save
_Note_: Moreover, user has the possibility to edit fields in modal window after click Save button.
Disable  "modal-backdrop" and "modal close icon" while instance is saving
> GGRC-1958 Clicking outside modal window "Discard changes" popup is displayed after clicking Save button

- src/ggrc/models/relationship.py
- src/ggrc_workflows/migrations/versions/20180220145425_4489d0ec0076_remove_invalid_relationships.py
- test/integration/ggrc_workflows/helpers/api_helper.py
- test/integration/ggrc_workflows/helpers/common_api.py
- test/integration/ggrc_workflows/helpers/relationship_api.py
- test/integration/ggrc_workflows/models/factories.py
- test/integration/ggrc_workflows/test_relationships.py
**THIS PR SHOULD BE REVIEWED AND CAN BE APPROVED BUT NOT MERGED BEFORE DEPENDENCY.**
It is needed to avoid new invalid relationships creation after this migration will be merged.
User can create invalid relationship between CycleTask and "Workflow", "TaskGroupTask", "TaskGroup", "CycleTaskGroupObjectTask", "Assessment", "AssesmentTemplate".
2. Search Workflow/TaskGroup/TaskGroupTask (they are not Relatable) and choose one.
3. Click 3-dots menu/Create Task.
4. Fill mandatory fields, press Save&Close.
**Actual Result:** CycleTask is created and mapped to chosen object from step 2
**Expected Result:** No possibility to perform such mapping.
**As well user can create CycleTask and map to CycleTask, Assessment, …
> GGRC-4504 Fix invalid relationship between CycleTask and other objects

- src/ggrc/integrations/issues.py
- src/ggrc/integrations/utils.py
- src/ggrc/models/hooks/issue_tracker.py
The issue tracker statuses map should be a public constant if it's being
used in multiple places.
The reason for moving it out of the hooks file is because it causes
hooks to be imported before all models are imported and that breaks
causes problems when trying to consolidate hooks from different objects.
One example is moving workflow hooks into ggrc module.
Try using all_models.Workflow inside the any hook in ggrc module.
> GGRC-4567 Move Issue tracker statuses map

- src/ggrc-client/js/components/access_control_list/access-control-list-roles-helper.js
- src/ggrc-client/js/components/access_control_list/tests/access_control_list_roles_helper_spec.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/diff/instance-acl-diff.js
- src/ggrc-client/js/components/related-objects/related-people-access-control.js
- src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
- src/ggrc-client/js/components/revision-log/revision-log.js
- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js
- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/models/audit_models.js
- src/ggrc-client/js/models/cycle_models.js
- src/ggrc-client/js/models/document.js
- src/ggrc-client/js/models/simple_models.js
- src/ggrc-client/js/models/task_group.js
- src/ggrc-client/js/models/tests/assessment_model_spec.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/ggrc_utils.js
- src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
- src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
- src/ggrc-client/js/plugins/utils/acl-utils.js
- src/ggrc-client/js/plugins/utils/snapshot-utils.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
- src/ggrc-client/js_specs/spec_setup.js
Currently work with ACL on FE side is doing really not optimized (this is due to the fact that from BE side we are getting list of which is uncomfortable to work).
Most popular work with ACL on FE side:
find all roles for specific object type
find specific role by object type and role name
And sometimes:
find role by id
find role by role name
In scope of this improvement I'd suggest to create a set of util methods for work with GGRC.access_control_roles, wich will create a map in order to quickly find nesessary role or set of roles.
Format of the map:
{
ObjectType1 : {
roleNameA: {},
roleNameB: {},
roleNameC: {},
},
ObjectType2 : {
roleNameX: {},
roleNameY: {},
roleNameZ: {},
}
....
}
https://github.com/google/ggrc-core/pull/7064#discussion_r162974815
In order to speed up work with ACL I …
> GGRC-4297 Improve work with ACL on FE side

- src/ggrc/assets/mustache/cycles/info.mustache
There is redundant loading GCA for Cycles.
> QUICK-FIX Remove redundant GCA component for Cycle

- src/ggrc-client/js/models/workflow.js
Workflow - 404 error in console is displayed while deleting a workflow
1. Open any active workflow and try to delete it
2. Open dev tools > Network tab
Actual Result: 404 error in console is displayed while deleting a workflow. Workflow id deleted
*Expected Result: * no errors should be displayed while deleting a workflow
When we try to delete WF we trigger for cycles and task groups (TGs) "destroy" event. This event is processed by workflow-activate component which tries to update TGs which were deleted with help DELETE request for workflow. Thus we can remove old logic about dispatching the "destroy" event for related objects for TGs and cycles because they will be removed on the server.
> GGRC-4400 Workflow - 404 error in console is displayed while deleting a workflow

- src/ggrc_workflows/models/hooks/workflow.py
During running migration in the maintenance mode hooks are triggered. This causes "RuntimeError: working outside of application context" as well as long execution of this hooks.
Use ggrc-qa db from 2/15 and deploy 1.3 version,  then deploy 1.4 and run migrations manually in the maintenance window.
To test this locally:
1. Run `deploy_appengine extras/deploy_settings_local.sh && launch_gae_ggrc`
2. Go to localhost:8080/maintenance/index run migrations.
In this PR hooks with session as target are deleted manually. This is needed to be done through event object `remove()` and `listen()` methods. To do this `ctypes` lib is needed to be used. However this lib is not supported by gae (see TODO list).
**Update:**
`handle_acl_changes` hook is fixed so that it doesn't use app context.
> GGRC-4499 Fix hooks handling during migration execution

- src/ggrc/fulltext/mysql.py
- src/ggrc/models/relationship_helper.py
- src/ggrc/query/custom_operators.py
- src/ggrc/query/my_objects.py
- src/ggrc/rbac/__init__.py
- src/ggrc/rbac/permissions_provider.py
- src/ggrc/services/resources/person.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_basic_permissions/models.py
Some of the subqueries are no longer used/needed and are now just
slowing down the response times.
Removed subqueries:
- people mapped through ObjectPerson table
- people mapped through relationships
- people mapped through UserRoles
- people contact_id/secondary_contact_id queries
- context_in expression in permission checks
- get_ids_related_to user roles
Query API & Search API queries were not updated once we deprecated some tables (e.g. ObjectPeople) and moved roles to ACL. Removing these queries is important for performance and also for the correct behavior of our app (the fact that we were still querying contact_ids probably introduced subtle bugs that were missed).
Check the results of /query & /search API calls.
The PR just removes some code.
Noticeable improvements:
The LHN for …
> GGRC-4581 Remove deprecated subqueries from my_objects query api call

- src/ggrc/models/assessment.py
- src/ggrc/models/mixins/assignable.py
Clean up obsolete code
- Check to see if notifications still work and 
- do basic sanity check on assessments (comment assignee types should still be displayed correctly)
Remove the obsolete function that triggered a redundant sql query.
> GGRC-4586 Update assignable mixin

- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/styles/modules/_object-header.scss
Assessment Info pane is jumping while clicking Complete button.
Assessment Info pane is jumping while scrolling when window height is small enough (look Common steps).
Steps to reproduce (from ticket):
1. Go to any audit with a control snapshot
2. Create assessment template with any mandatory LCA (1 LCA)
3. Generate Assessment based on the control snapshot and Assessment template
2. Navigate to assessment Info pane and click Complete button
Actual Result: Assessment Info pane is jumping while clicking Complete button
Expected Result: Assessment Info pane should not jump while clicking Complete button
Common steps:
1) Go to assessment info-pane with no content (where is no LCA);
2) Reduce height of window and stop before a scroll appears on info-pane:
3) Scroll up on …
> GGRC-4166 Use "position: sticky" for info-pane header

- src/ggrc/views/cron.py
The job was created in scope of GGRC-3880
But there is a wrong handler set for hourly cron job endpoint, which calls now half_hour_cron_endpoint() with proposals notification.
Same as GGRC-3880
1. User create Assessment with Issue Tracker switch ON.
2. Assessment is in 'Not Started' state for example.
3. User goes and moved assessment into 'Fixed' state.
Expected result: BUG status should be equal to Assessment state. BUG status should be reverted to 'Assigned'.
Set the correct endpoint handler.
> GGRC-3880 Fix hourly cron job to synchronize statuses of Assessment and issue tracker

- src/ggrc/settings/default.py
Bump version to 1.5.1-Strawberry
Deploy and check version
> QUICK-FIX Bump version to 1.5.1-Strawberry

- src/ggrc/views/cron.py
Cherry-picked version of #7356
> GGRC-3880,GGRC-4605 Fix hourly cron job endpoint

- src/ggrc_workflows/models/hooks/workflow.py
During running migration in the maintenance mode hooks are triggered. This causes "RuntimeError: working outside of application context" as well as long execution of this hooks.
Use ggrc-qa db from 2/15 and deploy 1.3 version,  then deploy 1.4 and run migrations manually in the maintenance window.
To test this locally:
1. Run `deploy_appengine extras/deploy_settings_local.sh && launch_gae_ggrc`
2. Go to localhost:8080/maintenance/index run migrations.
In this PR hooks with session as target are deleted manually. This is needed to be done through event object `remove()` and `listen()` methods. To do this `ctypes` lib is needed to be used. However this lib is not supported by gae (see TODO list).
**Update:**
`handle_acl_changes` hook is fixed so that it doesn't use app context.
> GGRC-4499 Fix events listening during migration applying

- test/integration/ggrc_workflows/helpers/rbac_helper.py
- test/integration/ggrc_workflows/helpers/setup_helper.py
- test/integration/ggrc_workflows/helpers/workflow_api.py
- test/integration/ggrc_workflows/helpers/workflow_test_case.py
- test/integration/ggrc_workflows/models/test_cycle.py
- test/integration/ggrc_workflows/models/test_cycle_task_entry.py
- test/integration/ggrc_workflows/models/test_cycle_task_group.py
- test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
- test/integration/ggrc_workflows/models/test_task_group.py
- test/integration/ggrc_workflows/models/test_task_group_object.py
- test/integration/ggrc_workflows/models/test_task_group_task.py
- test/integration/ggrc_workflows/models/test_workflow.py
This PR covers some permission cases for Workflow related objects. Actually this is technical debt ticket for GGRC-4208 and GGRC-4250 tickets.
Check integration tests results.
Cover use cases provided in GGRC-4208, GGRC-4250 with integration tests.
**Cases that should be covered by tests:**
1. Login as Global Reader/Creator/Editor.
2. Create Workflow with current user as Admin.
Next steps should be performed without errors:
3. Create TaskGroup;
3.1 Create TaskGroupTask;
3.2 Map/Unmap object to/from TaskGroup;
3.3 Clone TaskGroup;
3.4 Activate Workflow.
> GGRC-4253 Cover Workflow related objects permissions cases with tests

- src/ggrc_workflows/notification/notification_handler.py
Fixed minor errors in spelling and grammar.
> Fixed spelling and grammar

- src/ggrc/models/hooks/issue_tracker.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
There are multiple issues solved here:
1. Auditors get added to IssueTracker Issues CC list (they shouldn't as they have only internal role on the Assessment).
2. The current user is set as the Reporter for IssueTracker Issues (a user requested to set an Audit Captain there instead).
3. Creators get added to IssueTracker Issues CC list (a user requested to not add them).
2. Create an Audit with IssueTracker integration on.
3. Set User1 and User2 as Audit Captains, User3 and User4 as Auditors.
4. As User5, create and Assessment with IssueTracker integration on, setting User6 and User7 as Creators, User8 and User9 as Assignees, User10 and User11 as Verifiers.
Expected result: the external Issue will have User1 as Reporter, User8 as Assignee, User9 in CC list.
The logic …
> GGRC-4574,4575 Set correct people for IssueTracker

- src/requirements.txt
In launch_ggrc mode many developers faced SSL Handshake exception. To fix it we need to update httplib2 library.
Go to import/export and check that it work correctly.
Library update.
http2lib contains certs.txt file that contains root certificates, thats used during ssl handshake.
Old ones can't validate https://www.googleapis.com
New version of lib contains new certs.txt that validates  https://www.googleapis.com properly.
> QUICK-FIX Update httplib2 to fix SSL handshake error.

- src/ggrc-client/js/components/people/editable-people-group.js
- src/ggrc-client/js/components/people/editable-people-group.mustache
- src/ggrc-client/js/components/people/people-group-modal.js
- src/ggrc-client/js/components/people/templates/people-group-modal.mustache
- src/ggrc-client/js/components/people/tests/editable-people-group_spec.js
- src/ggrc-client/js/components/simple-modal/simple-modal.js
- src/ggrc-client/styles/components/people-group/_people-group.scss
People are hidden if click edit control/See more link
1. Navigate to Assessment Info page
2. Add more than 4 person as a verifier
3. Click Edit icon / See more link
**Actual Result:** People are hidden if click edit control/See more link. There is no control for adding a person.
**Expected Result:** People should not be hidden if click edit control/See more link:
a control to add a new person should be displayed
It's a regression issue after fc2fd3d commit (#7346). 
This PR reverts changes of this commit and fixes empty space under title on info-page in other way.
> GGRC-4597 Fix issue when people popup is invisible for custom-roles component

- src/ggrc/models/hooks/__init__.py
- src/ggrc/models/hooks/access_control_list.py
- src/ggrc/models/hooks/acl/__init__.py
- src/ggrc/models/hooks/acl/audit_roles.py
- src/ggrc/models/hooks/acl/program_roles.py
- src/ggrc/models/hooks/acl/relationship_deletion.py
- src/ggrc/models/hooks/relationship.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/hooks/__init__.py
- src/ggrc_workflows/models/hooks/workflow.py
Dependencies:
So far every object has it's own hook on session after_flush, and all of those always loop through all objects in a session and filter out their own. This is in itself is not efficient and with multiple flushes that we already have it should be avoided.
Besides the first part this is needed so that we can make a joined and efficient acl propagatin across the app.
To check this PR, just do basic rbac sanity checks on role propagation for workflows programs audits and assessments.
All individual after_flush hooks were removed and calls to the same function are done from a single hook. The refactor of how that hook handles other parts will be in a separate PRs as each individual hook is refactored.
> GGRC-4594 Join hooks for ACL propagation

- src/ggrc-client/js/components/rich_text/rich_text.js
- src/ggrc-client/js/components/rich_text/tests/rich_text_spec.js
User is able to insert more symbols than allowed.
1. Insert 2000 into the comment box on the Assessment INfo panel
2. Press Enter
Actual Result: Maximum characters exceeded more than 2000
Expected Result: Maximum characters exceeded 2000/2000
Special keys (f.e. Enter) does not trigger "keypress" event.
The solution is listen quill "text-change" event and undo last action.
> GGRC-4344 Fix restriction of max length

- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc-client/js/components/import-export/templates/quick-tips.mustache
- src/ggrc-client/js/components/import-export/test/import_spec.js
- src/ggrc-client/styles/_mixins.scss
- src/ggrc-client/styles/mixins/_icon.scss
- src/ggrc-client/styles/modules/_import-export.scss
- src/ggrc-client/styles/modules/_notifications.scss
> GGRC-4468 [IMPORT] Redesign of Errors/Warnings section

- src/ggrc/notifications/data_handlers.py
- test/unit/ggrc/notification/test_data_handlers.py
Revisions that collect changes about changing internal ACL for assessment will produce an exception on daily digest email generation. 
Open daily digest link on DB from ggrc_test
1) don't present internal ac in email 
2) if role_id that saved in revision and don't associated to object_type it should be skipped
> GGRC-4556,4557 GGRC-TEST-_notifications/show_daily_digest shows Server Error

- src/ggrc/automapper/rules.py
- test/integration/ggrc/automapper/test_automappings.py
Automappings that are triggered by Objective - Objective and Control - Control mappings confuse the users and should not happen.
1. Create a Program P1.
2. Create a Section S1.
3. Create two Objectives O1 and O2.
4. Create two Controls C1 and C2.
5. Map P1 to S1.
6. Map S1 to O1.
7. Map O1 to C1.
8. Map O2 to O1.
9. Map C2 to C1.
Expected result: O2 is mapped only to O1, C2 is mapped only to C1.
Actual result: O2 and C2 are mapped to whole hierarchy (P1, S1, O1, C1).
The corresponding rules are dropped. The tests now assert that the automappings don't happen.
> GGRC-4637 Disable horizontal automappings

- bin/release/get_pr_titles.py
When Github REST API responds with a non-200 code, `get_pr_titles` script doesn't log the error message properly.
Run `get_pr_titles` and provide an invalid password or user name.
Expected result: the error is printed properly.
Actual result: `AttributeError` is raised.
Just a correct field name.
> QUICK-FIX Fix field name for non-200 responses

- docker-compose.override.yml.example
These variables were enabled in 1fa41deee71f08a but the basic
documentation was not added. This commit just adds the data that was
included in the PR #7298, but was left out from codebase.
Try the issue tracker variables in the yml file (both having them on and off). Be sure to stop and start the docker container after the yml changes.
> QUICK-FIX Add optional env vars to override yaml file

- src/ggrc/settings/default.py
Issue description
Bump version to 1.7.0
Open the app and check teh version in the bottom right corner
Increased the version number in our default settings
> QUICK-FIX Bump version to 1.7.0-Strawberry

- src/ggrc_basic_permissions/roles/Creator.py
- test/integration/ggrc_basic_permissions/test_creator.py
If Global Creator as Primary assignee opens Proposal for Control popup, Assertions values are not shown up
1. Create a control as admin and set Global Creator as Primary/Secondary Assignee
2. Log as Global Creator and open Control Info page
3. Click Propose Changes button
4. Look at the Assertions values in the Proposal for Control popup
Actual Result: If Global Creator as Primary assignee opens Proposal for Control popup, Assertions values are not shown up
Expected Result: If Global Creator as Primary/Secondary assignee opens Proposal for Control popup, Assertions values should be displayed
Grant permissions to read Control Assertions to global creator
> GGRC-4236 If Global Creator as Primary assignee opens Proposal for Control popup, Assertions values are not shown up

- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/styles/dashboard.scss
- src/ggrc-client/styles/layout/_content.scss
- src/ggrc-client/styles/layout/_footer.scss
- src/ggrc-client/styles/layout/_header.scss
- src/ggrc-client/styles/modules/_dashboard-widget.scss
- src/ggrc-client/styles/modules/_distraction-free-view.scss
- src/ggrc-client/styles/modules/_header-content.scss
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/layouts/dashboard.haml
This PR contains changes from #7301. #7301 was reverted in #7354 because of issue in dashboard widget.
There're couple layout issues: Page content is overlapped by footer + the page has 2 scrolls.
Case 1
1. Login as Admin user
2. Go to administration page and add GCAs to Regulation (at least 10 GCAs)
3. Create Regulation and open it.
4. Scroll down to see "Created date" and "Last update by"
**Actual Result:** "Created date" and "Last update by" are not shown in the bottom of the page if object contains GCAs
**Expected Result:** "Created date" and "Last update by" should be shown in the bottom of the page if object contains GCAs
Case 2
1. Enable dashboards by running export DASHBOARD_INTEGRATION=True in docker
2. Start the app with launch_ggrc
3. Create a custom attribute on …
> GGRC-4169 Fix page layout

- src/ggrc-client/js/components/assessment/assessment-local-ca.js
If move assessment to Deprecated state, unfilled mandatory custom attribute is displayed with green mark
1. Have Audit with control snapshot and Assessment template with any required local custom attribute;
2. Generated Assessment;
1. Expand assessment Info pane
2. Click 3 bb's button and press Deprecate
3. Look at the mandatory CA on the grey box screenshot-1.png: shows with green mark, but value doesn't exist in it;
4. Click Restore in 3 bb's menu: green mark is still shown
_Actual Result:_ If move assessment to Deprecated state, unfilled mandatory custom attribute is displayed with green mark
_Expected Result:_ If move assessment to Deprecated state, unfilled mandatory custom attribute should be displayed with red mark
Trigger form validation after init of LCA
> GGRC-4522 Incorrect behavior of Local CA form

- src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
When you try inline edit issue tracker fields then the confirmation modal for changing state appears, but editing of this fields does not change the assessment state.
1. Have an audit with switch on issue tracker
2. Create assessment 
3. Navigate to Assessment Info panel and move assessment into Completed (no verification) state
4. Open Other attributes tab and edit issue tracker inline-fields
Add `isConfiramtionNeeded = false` for issue tracker fields.
> GGRC-4602 Remove confirmation for inline editing of issue tracker fields

- src/ggrc/assets/mustache/audits/tree_add_item.mustache
Map button is displayed at Audit tab on Risk/Threat Info page
1. Create a Risk/Threat 
2. Add tab > Audit
3. Click Map button in tree view
_Actual Result_: Map button is displayed at Audit tab on Risk/Threat Info page. While clicking on Map button Unified mapper is displayed. Default object type is Data Assets
_Expected Result_: Map button should not be displayed at Audit tab on Risk/Threat Info page
Extend a condition of the button displaying.
> GGRC-4409 Map button is displayed at Audit tab on Risk/Threat Info page

- src/ggrc/assets/mustache/base_objects/approval_link.mustache
While clicking 'here' link control Info page is not opened.
2. Expand Controls Info pane and click [Submit for Review] link
3. Assign reviewer and set a due date > Save
4. Click 'here' link
_Actual Result:_ While clicking 'here' link control Info page is not opened. My work page is opened instead.
_Expected Result:_ While clicking 'here' link Workflow task tab on the control Info page should be displayed
Redirect to object info-pane and then open "Workflow tasks" tab
> GGRC-4331 Object review: 'here' link doesn't open object page

- src/ggrc/migrate.py
- src/requirements-dev.txt
- src/requirements.txt
The containers should be rebuilt as the requirements change here.
Alembic dependency is outdated in our project.
Run db_reset, db_migrate, etc, and check if they work correctly.
The requirement is updated. The monkey-patch to enable multiple migration chains is updated as well.
> GGRC-1458 Update alembic to 0.9.8

- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/issue_tracker.py
- src/requirements-selenium.txt
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/service/rest/template_provider.py
This PR is smaller cleanup work done for refactoring ACL propagation hooks, and only partly touches these two tickets GGRC-4133, GGRC-2174.
Check that assessment generation and issue tracker still work.
Remove the custom cache and use the one that is populated at the begining of every post request.
> QUICK-FIX Cleanup assessment hook

- src/ggrc-client/js/plugins/utils/state-utils.js
Multi select dropdown filter is applied not properly when 'Rework Needed' and some of 'Completed' states is selected.
1. Open Audit Info page
2. Create Assessment and move it to 'Rework Needed' state
3. In Assessment tab set 'Rework Needed' and 'Completed and verified' states in the Multi select dropdown filter
4. Look at the search results
Both of 'Completed' states pass through filter - verified and not verified.
When parsing of 'Completed' states is happened info about 'verified' state add to the end of string. So all 'completed' states should be at the end of array to join properly.
> GGRC-4498 Fix assessment state filter parsing issue

- src/ggrc/migrations/versions/20180117095052_40d92baab48c_drop_gdrive_integration_service_table.py
- src/ggrc/settings/default.py
Obsolete and mostly empty `ggrc_gdrive_integration` module with migrations that cancel out in the end.
Check that the DB dumps are the same (except automatic timestamps):
- `db_reset` with `ggrc_gdrive_integration` set and unset (the alembic table for the "with" case is OK)
- `db_reset latest-qa-dump-possible.sql` with `ggrc_gdrive_integration` set and unset
The alembic table is dropped to keep the DBs cleaner.
The meetings table has been dropped for all existing instances having latest release in the deprecated migration chain. However, we have to duplicate the `DROP TABLE meetings` part since the table gets created in the initial `ggrc` chain migration.
> QUICK-FIX Disable gdrive_integration migrations

- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc-client/js/components/import-export/test/import_spec.js
- src/ggrc-client/styles/modules/_import-export.scss
> GGRC-4469 [IMPORT] Handle a possible errors and show correct messages

- src/ggrc-client/js/apps/workflows.js
1. Workflow tab should be shown on person page.
2. If person is mentioned as 'Admin' or 'Workflow Member' for a particular WF, then this WF should be shown in 'Workflow' tab on person page.
1. Open Person page.
2. Open Workflow tab.
Expected result: If person is mentioned as 'Admin' or 'Workflow Member' for a particular WF, then this WF should be shown in 'Workflow' tab.
Add Workflow Tab config for person page.
> GGRC-4448 Add Workflow tab for Person

- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
- src/ggrc-client/js/components/object-generator/object-generator.mustache
- src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
- src/ggrc-client/js/components/revision-history/templates/restore-revision.mustache
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/plugins/can_control.js
- src/ggrc-client/styles/_common.scss
- src/ggrc-client/styles/components/proposal/_proposal.scss
- src/ggrc-client/styles/components/revision-history/_revision-history.scss
- src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
- src/ggrc/assets/mustache/components/object-mapper/object-mapper.mustache
- src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
Spinner displays to the right of buttons on ADD/EDIT modals
1) Open Programs;
2) Click 3 bb's;
3) Click "Edit Program";
4) Click "Save & Close";
_Actual result_: Spinner displays to the right of buttons.
_Expected result_: Spinner displays to the left of buttons.
Move spinner to the left of buttons on ADD/EDIT modals;
Add spinner to "Create Proposal" modal;
Remove redundant "pending-ajax" class.
> GGRC-4543 Spinner should display to the left of buttons on ADD/EDIT modals

- package-lock.json
- package.json
Moment.js before 2.19.3 have a security vulnerability (CVE-2017-18214) and needs to be upgraded.
N/A
N/A
> QUICK-FIX Update moment to 2.19.3

- src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
- src/ggrc-client/styles/components/grid-data/_grid-data.scss
- src/ggrc-client/styles/modules/_tabs.scss
On the Related Assessments tab "More info" popup is corrupted.
2. Open Assessment in tree view that has related Assessments
3. Open Related Assessments tab
4. Click 'i' icon to open More info popup 
Actual Result: Incorrect formatting of More info popup
Expected Result: Improve formatting of More info popup
Unnecessary overflow styles was removed.
> GGRC-4622 Fix related assessments more info popup

- src/ggrc-client/js/components/object-list-item/person-list-item.js
- src/ggrc-client/js/controllers/info_widget_controller.js
- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc-client/styles/modules/_modal.scss
- src/ggrc/assets/mustache/assessment_templates/info.mustache
- src/ggrc/assets/mustache/assessments/info.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/info.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/mustache/objectives/info.mustache
- src/ggrc/assets/mustache/people/info.mustache
- src/ggrc/assets/mustache/policies/info.mustache
- src/ggrc/assets/mustache/processes/info.mustache
- src/ggrc/assets/mustache/products/info.mustache
- src/ggrc/assets/mustache/programs/info.mustache
- src/ggrc/assets/mustache/systems/info.mustache
- src/ggrc/assets/mustache/workflows/info.mustache
FE sends unneeded get request
1. Open https://ggrc-qa.appspot.com/objectBrowser#!audit_widget
2. Find audits which contains 'big program'
3. Open Info pane
4. See Network tab in Chrome DevTool
1) Remove unneeded type definition of `define` property.
2) Do not display info-pane-footer on `info-pin` and on `revisions-comparer` modal
> GGRC-4565 Remove redundant requests after open Audit info panel

- src/ggrc-client/js/controllers/summary_widget_controller.js
- src/ggrc-client/js/plugins/utils/state-utils.js
New order of Assessment's statuses:
_Not Started
In Progress
In Review
Rework Needed
Completed (no verification)
Completed and Verified
Deprecated_
1) Open Audit Summary page
Update order of Assessment's statuses
> GGRC-4304 Reorder statuses on Audit Summary Page

- src/ggrc/converters/base_block.py
- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/models/assessment.py
- src/ggrc/models/reflection.py
- test/integration/ggrc/converters/test_export_ticket_tracker.py
- test/integration/ggrc/converters/test_import_helpers.py
User who has read rights for an Assessment should be able to export issuetracker issue ids, if an issuetracker issue is linked to an assessment.
- Verify that 'Ticket Tracker' checkbox is on 'Export' page
- Export Assessment linked to issuetracker issued
- Add 'Ticket Tracker' column into exported assessment spreadsheet.
- Add 'Ticket Tracker' checkbox on 'Export' page. (in ATTRIBUTES)
> GGRC-4570 Export Attribute does not contain ticket tracking number

- src/ggrc-client/js/components/diff/instance-gca-diff.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-access.js
- src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
- src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-access_spec.js
- src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-object_spec.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
Proposed values after Review&Apply operation are placed into incorrect inputs.
1. As admin user go to All objects tab > Controls tab
2. Click on any Control in TreeView
3. Make a proposal for any Global CA
4. Apply Proposal
5. Open Attributes tab and look at the proposed changes
Actual Result:
Proposed values after applying are placed into GCA inputs, which are not related to them.
Expected Result: Applied proposal should be displayed w/o refreshing the page, no extra values should be shown.
We should prepare CAVs on FE before merging them with BE CAVs .
> GGRC-4610 User has to refresh the page to see applied proposals for GCA for an old Control

- src/ggrc-client/js/components/object-tasks/object-tasks.mustache
- src/ggrc-client/styles/components/object-tasks/_object-tasks.scss
Info popup with mapped tasks doesn't show Deprecated state of cycle task.
1. Create Repeat off workflow
2. Add a task to task group
3. Map a control to a task group and Activate Workflow
4. At the Active Cycles tab move a task to Deprecated state
5. Go to All objects page and find a control
6. Hover over 'i' icon in control's first tier: Deprecated state is not shown up
Actual Result: Info popup with mapped tasks doesn't show Deprecated state of cycle task
Expected Result: Info popup with mapped tasks should show Deprecated state of cycle task
Was added "Deprecated" state.
> GGRC-4275 Show Deprecated status for object-tasks component

- src/ggrc/services/resources/related_assessments.py
Global creator as program manager/Audit captain/auditor doesn't see Related Assessments
1. Log as Admin user 
2. Create a program with mapped control and audit to the program
3. Assign Global Creator as Auditor to Audit
4. Open audit page and generate 2 assessments based on the control snapshot
5. Log as Auditor (Global Creator) and open Audit page
6. Expand Assessment Info panel and click on Related Assessments tab
Actual Result: Global creator as auditor doesn't see Related Assessments:
Related assessments tab is empty;
GET 403 is displayed in Network tab
Expected Result: Global creator as program manager/Audit captain/auditor should see Related Assessments
There were multiple issues with the code:
1. Permission query check was called with wrong parameters
2. …
> GGRC-4546 Fix related assessments query for creators

- src/ggrc/models/hooks/issue_tracker.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
In CC field in issue tracker only Creators and Verifiers are filtered, while only Assignees except the first one are needed to be included.
1. Create Audit, Assessment with ticket tracker turned on;
2. Fill Audit Captain and Auditor, Assessment Assignee (more than one), Assessment Verifier, Assessment Creator, Assessment Primary and Secondary Contacts with some values;
3. Create GCA for Assessments and fill it in;
4. Open ticket link.
Expected result: only Assignees except the first one have to be included in CC.
Currently only Creators and Verifiers where filtered from CC list. Now all roles except Assignee are filtered.
> GGRC-4658 Fix incorrect cc list in issue tracker

- src/ggrc/settings/default.py
This PR is `on hold` until the dependencies are merged to release and backmerged to dev:
Bump version to 1.6.1-Strawberry
Open the app and check the version in the bottom right corner
Increased the version number in our default settings
> QUICK-FIX Bump version to 1.6.1-Strawberry

- src/ggrc/models/hooks/issue_tracker.py
- src/ggrc/services/resources/related_assessments.py
- src/ggrc_basic_permissions/__init__.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
This is a duplicate PR from  https://github.com/google/ggrc-core/pull/7491
Nothing is changed here, the PR branch is made by:
```bash
git fetch upstream dev
git checkout -b merge-release-to-dev upstream/dev
git fetch upstream release/0.10-Raspberry
git merge FETCH_HEAD
git push HEAD
```
There were no conflicts in this merge and nothing was resolved. I believe that on the original PR, github is showing invalid conflict, even though the commit that caused the conflict was already merged into dev.
> BACKMERGE 1.6.1-Strawberry into dev 

- src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
- src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
- src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
- src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
- src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/tracker/actions.js
- src/ggrc-client/js/tracker/analytics.js
- src/ggrc-client/js/tracker/index.js
- src/ggrc-client/js_specs/spec_setup.js
Added trackers for Google Analytics
> GGRC-4678 Add analytic trackers for bulk update and change status of tasks

- test/integration/ggrc/access_control/test_roleable.py
- test/integration/ggrc/data_platform/test_last_assessment_date.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/snapshotter/test_indexing.py
Having models imported in the factories module has lead to wrongly used models instead of factories.
We should prevent deves from directyl importing models from factories and if models are needed they should be exiplicitly imported from `models` or `all_models`
Run tests and see if they work.
in ipython import factories and check there is a chance to access an actual object instead of a factory.
Fixed the tests with wrong usage of factory elements, and changed all model imports to package or module.
PS: the ACL changes rely on this PR so it needs to be merged before ACL propagation is done for 1.7 release.
> QUICK-FIX Update integration test factories

- src/ggrc-client/js/components/questions-link/questions-link.js
- src/ggrc-client/js/components/questions-link/questions-link.mustache
- src/ggrc-client/js/models/business_object_models.js
- src/ggrc-client/js/models/system.js
- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc/assets/mustache/base_objects/info-pane-utility.mustache
- src/ggrc/assets/mustache/base_objects/tree-item-attr.mustache
- src/ggrc/templates/layouts/base.haml
- src/ggrc_risks/templates/layouts/base.haml
This PR has the dependencies:
MOCK-UPS:
https://drive.google.com/corp/drive/folders/13U0ZjY5KUPQOpR0tC5GEuf8QzDHacX8G
UX DETAILS:
1. 'Questionnaire' link should be displayed for Product, System, Process objects on:
info pane / page;
tree view.
2. if questionnaire exists and user clicks a link, then re-direct him to GGRCQ on Questionnaire Run page with 'Questionnaire' tab selected.
EXAMPLE OF LINK IN GGRCQ:
/questionnaires/<object_type>/code/<object slug>/answers
for example: /questionnaires/product/code/product-1234/answers or  /questionnaires/system/code/system-1234/answers
generic: ggrcq-url/questionnaires/<object_type>/<field_name>/<field_value>/answers
Add following setting `GGRC_Q_INTEGRATION_URL=<http://example.com>` into 'docker-compose.override.yml' file to see Questionnaire link …
> GGRC-4255 Add link to questionnaire on Product / System / Process info pane/page

- bin/release/get_pr_titles.py
Basic HTTP auth doesn't work with your usual password if you have 2FA enabled, and [using access token instead of the password](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/#using-a-token-on-the-command-line) is confusing and a bit redundant (the token implies the username).
1. [Generate a new access token](https://github.com/settings/tokens) (no scopes required as it's needed just to authenticate you)
2. Run `./bin/release/get_pr_titles.py 1.5.1-Strawberry`, pass the token in.
There's a new parameter `--auth {basic, token}` to choose either Basic HTTP auth or [Token-based auth](https://developer.github.com/v3/#oauth2-token-sent-in-a-header).
Since every developer has 2FA enabled by now (required by the repo owner), token-based auth is the default …
> QUICK-FIX Add access tokens authentication to PR getter script

- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Update the format of questionnaire links.
**EXAMPLE OF LINK IN GGRCQ:**
/questionnaires/<object_type>=<object_slug>/answers
for example: '/questionnaires/product=product-13/answers' or  'questionnaires/system=system-13/answers'
Add following setting GGRC_Q_INTEGRATION_URL=http://example.com into 'docker-compose.override.yml' file to see Questionnaire link for Product, System and Process.
> GGRC-4255 Change format of questionnaire link

- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Redundant postfix '/answers' in the questionnaire links.
Add following setting GGRC_Q_INTEGRATION_URL=http://example.com into 'docker-compose.override.yml' file to see Questionnaire link for Product, System and Process.
> GGRC-4255 Remove "/answers" from qlink

- src/ggrc-client/js/plugins/tooltip.js
Tooltip hides after appearing.
1. Open My work page
2. Hever over tabs in HNB
Actual Result: Tooltip disappears while hovering over tabs in HNB
Expected Result: Tooltip should not disappear while hovering over tabs in HNB
I've fixed calculation to select appropriate node.
> GGRC-4496 Calculate correct coordinates for selector

- bin/review_branch
Simple helper to make the review.
> QUICK-FIX Add review branch bash script to automate review procedure

- src/ggrc-client/styles/components/tree/_tree-view.scss
Pagination controllers' rendering on tree view doesn't work properly.
1. Pre-requirements:
Program, Control, MapControlToProgram, Audit, Assessment, MapSnapshotedControltoAssessment, Issue, MapIssueToAssessment
2. Got to Assessment info page and try to navigate through exist tabs' tree views.
_Expected_:
The upper and lower pagination controllers' on tree view should be parallel.
_Actual_:
The upper and lower pagination controllers' on tree view are placed no parallel.
Update `padding` of `tree-footer`
> GGRC-4067 Pagination controllers' rendering on tree view doesn't work properly

- test/integration/ggrc_workflows/helpers/person_setup.py
- test/integration/ggrc_workflows/helpers/setup_helper.py
- test/integration/ggrc_workflows/models/test_cycle.py
- test/integration/ggrc_workflows/models/test_cycle_task_entry.py
- test/integration/ggrc_workflows/models/test_cycle_task_group.py
- test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
- test/integration/ggrc_workflows/models/test_task_group.py
- test/integration/ggrc_workflows/models/test_task_group_object.py
- test/integration/ggrc_workflows/models/test_task_group_task.py
- test/integration/ggrc_workflows/models/test_workflow.py
Cover case from steps with test.
1. Create a WF.
2. Log in as a Global Editor.
3. Go to a WF (Global Editor should NOT have any WF role in this workflow: WF manager, WF member, Task Assignee).
4. Go to 'Setup' tab and select a task group.
**Actual result:** 'Create Task' button is missing.
**Expected result:** 'Create Task' button should be available. Global Editor should be able to add new tasks into task group.
This ticket was fixed in scope of other ticket, so added a tests here for above case.
> GGRC-4026 Create tests for Global Editor with no role in Workflow POST Task

- src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
- src/ggrc-client/styles/components/related-objects/_related-assessments.scss
'No related assessments were found' is shown in the Related Assessments tab while related assessments are loading 
Prerequisites:
- Have at least two related assessments on the audit page
1. Open audit page > Assessments tab
2. Expand Assessment Info panel and click on Related Assessments tab
*Actual Result:* 'No related assessments were found' is shown while related assessments are loading
- if related assessments are present in Related Assessments tab, no wording "No related assessments were found" should be displayed;
- show spinner while related assessments are loading.
Use spinner provided by object-list component.
> GGRC-4559 Fix related-assessments spinner

- src/ggrc/assets/mustache/base_objects/approval_link.mustache
Global Creator as Program manager doesn't see Submit for review link
1. Log as Admin user and create a program;
2. Add a user that did not logged to GGRC before as Program manager. User should not have any created objects before. It is needed to create a new user in Admin dashboard.
3. Log in with such a user from step #2 and open program Info page
_Actual Result_: Global Creator as Program manager doesn't see Submit for review link
_Expected Result:_ Global Creator as Program manager should be able to assign a person for submitting for review.
**NOTE**:
1. It is necessary to check the behavior for Global Reader/Editor 
2. while taking action on the ticket it is necessary to check if Global Creator is able to Apply /Decline review.
Check permissions for instance instead of 'Workflow'
> GGRC-4411 Global Creator as Program manager/object admin doesn't see Submit for review link

- src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
- src/ggrc-client/styles/components/ca-object/_ca-object-modal.scss
- src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Save/ Attach buttons are hidden in 'Required evidence' popup if user attaches evidences (more than19)
Prerequisites:
- Have an Audit with a control snapshot;
- Created Assessment template with LCA dropdown (evidence is required);
- Generated Assessment based on AT and control snapshot
1. Expand Assessment INfo panel
2. Set evidence option in LCA dropdown
3. Attach at least 19 evidences and look at Save/ Attach buttons
*Actual Result:* Save/ Attach buttons are hidden in 'Required evidence' popup if user attaches evidences (more than19)
*Expected Result:* Add scroll if 'Required evidence' popup contains a big number of evidences
The modal is goes out of screen.
In the PR I've added a scroll bar to the modal content.
> GGRC-4542 Fix ca-object-modal layout

- src/ggrc/access_control/role.py
- src/ggrc/utils/revisions_diff/applier.py
- src/ggrc/utils/revisions_diff/builder.py
- test/integration/ggrc/proposal/api/test_acl.py
User should not have ability to change internal ACLs.  
One part
1) create proposal via raw api with changing internal ACL roles 
2) after creation its content shouldn't contain information about changing internal ACL 
Second part 
1) create ACR
2) create proposal with changing ACL related to that ACR
3) change that ACR and make it internal (via raw sql)
4) apply that proposal 
5) after apply that kind of proposals ACl shouldn't changed. 
1) remove ability save proposal changes related internal acl 
2) remove ability to apply proposal changes related internal acl
> GGRC-4437 Disallow to apply internal program roles

- src/ggrc/templates/notifications/proposal_digest.html
no margin on proposal email block 
get the proposal email and check it 
add extra row before proposal email content
> GGRC-4218 change presentation proposal emails

- src/ggrc/settings/default.py
Bump version from 1.7.0 -> 1.8.0
> QUICK-FIX Bump Version

- src/ggrc/access_control/role.py
- src/ggrc/models/revision.py
- src/ggrc/utils/revisions_diff/builder.py
- src/ggrc/utils/revisions_diff/meta_info.py
- test/integration/ggrc/services/test_revision_history.py
It's required to send on FE some meta info about mandatory fields on any layer. 
Raw api calls testing only. 
Add meta information in revision that will collect all info about mandatory fields.
> GGRC-4633 BE: Implement presentation list of mandatory fields on diff building.

- src/ggrc/migrations/versions/20180326094741_9e44253512f2_add_effective_date_and_last_deprecated_.py
- src/ggrc/models/objective.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_import_last_deprecated_date.py
Objectives lacks `Effective Date` and `Last Deprecated Date` which are used to track applicability of business objects.
Export a `Objective`. It should contain `Effective Date` and `Last Deprecated Date` fields.
`Effective Date` should be importable
`Last Deprecated Date` should not be importable
`Last Deprecated Date` should be set to current date once objective is moved to Deprecated state
Objective now mixes `WithLastDeprecatedDate` and `WithEffectiveDate`.
> GGRC-4787 Add "Effective Date" and "Last Deprecated Date" fields for Objective object

- src/ggrc/__init__.py
- src/ggrc/__main__.py
- src/ggrc/app.py
- src/ggrc/settings/default.py
- src/ggrc/settings/development.py
We have a lot of slow requests in our app. We need to make them more visible so that (hopefully) they will get improved faster.
NA
This adds a simple log that highlights slow reqests with in yellow (if
it takes more than 1s) and red (if it takes more than 10s).
> QUICK-FIX Highlight slow request in local development

- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/test/import_spec.js
- src/ggrc/gdrive/file_actions.py
Different messages for user when import not supported files from GDrive and Computer.
Try to import file in not supported format.
Messages have been unified.
> GGRC-3354 Make proper message to inform user that csv file cannot be imported

- src/ggrc-client/js/components/info-pane/info-pane-footer.mustache
- src/ggrc-client/styles/_widget.scss
- test/selenium/src/lib/page/widget/info_widget.py
Last user which modified Standard is not shown in the bottom of the Info panel
1. Log as "user-1"
2. Create Standard
3. Click Submit for review, add reviewer ("user-2") and select a date
4. Log as "user-2"
5. Click Approve button
6. Look at the "Modified by "user" in the bottom of the Info panel
**Actual Result:** Last user which modified Standard is not shown in the bottom of the Info panel
**Expected Result:** Last user which modified Standard should be shown in the bottom of the Info panel
It happens because person-info component doesn't fetch person data after person changing.
Replace person-info with people-list-item component which already support it.
> GGRC-1632 Fix issue when last user which modified object is not shown in the footer

- src/ggrc/cache/utils.py
- src/ggrc/converters/base_block.py
- src/ggrc/services/common.py
- src/ggrc_basic_permissions/__init__.py
`services.common` is over 1600 LOC
Check that the app still runs and memcache is functional.
All memcache-specific code (esp. shared with imports logic) is moved to a separate module.
> QUICK-FIX Move memcache utils out of REST logic

- src/ggrc/fulltext/mysql.py
Refreshing my work page, produces a sqlalchemy warning. We should avoid those when possible. 
```
/vagrant/src/packages/sqlalchemy/sql/default_comparator.py:35: SAWarning: The IN-predicate on "fulltext_record_properties.type" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
return o[0](self, self.expr, op, *(other + o[1:]), **kwargs)
```
use ggrc_qa_db-backup-2018-02-23.sql dump.
1. run launch_ggrc
2. open dashboard (my work page)
3. check server output.
Note: refreshing the page will not show a warning. to show the warning again, we must shut down the server and run launch_ggrc again.
Replace the empty `in` statement with a `false` statment, and avoid triggering …
> QUICK-FIX Cleanup permissions query

- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/related-objects/related-issues.mustache
Information in the Related Assessments/Change Log of previous assessment are displayed while click 'Prev/Next'
2. Have at least 3 assessments: control snapshot is mapped to both assessments, 1 assessment has no mapping 
3. Expand Info pane of assessment that has mapped control snapshot
4. Open Change log tab
5. Click Next/Prev
6. Look at the information of the Change log tab
_Actual Result:_ Information in the Related Assessments/Other Attributes/Change Log of previous assessment are displayed while click 'Prev/Next'
_Expected Result:_ Information in the Related Assessments/Other Attributes/Change Log of previous assessment should not display while clicking 'Prev/Next'
Reload Related assessments and revisions after change of the page instance
> GGRC-3251 Information in the Related AssessmentsChange Log doesn't update while click 'Prev/Next'

- src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js
- src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-access_spec.js
- src/ggrc-client/js/plugins/utils/custom-attribute/tests/custom-attribute-object_spec.js
Server returns default values for `custom_attribute_values`.
This values are used on client side to set value if it is empty.
> GGRC-4698 Use default value from custom attribute definition

- Dockerfile-selenium
- README.md
- bin/jenkins/functions.sh
- bin/jenkins/run_checkstyle
- bin/jenkins/run_code_style
- bin/jenkins/run_integration
- bin/jenkins/run_unittests
- docker-compose-testing.yml
- test/selenium/pytest.ini
Google Chrome 63+ restricts dev name to be HTTPS-only. See e.g. https://textslashplain.com/2017/12/05/strict-transport-security-for-dev/
Please note that not only .dev is restricted but also http://dev. Accessing http://dev from Chrome leads to ERR_SSL_PROTOCOL_ERROR error
To access dev container from Selenium tests we can: use different container name / use a network alias / use some Chrome flag.
I think using the same "cleandev" name used for dev and deploy is the best solution as it simplifies things.
Using Chrome flag will decrease security if tests are run from untrusted network if site uses some external resources.
> QUICK-FIX Change dev container name to cleandev, Update Chrome version

- src/ggrc-client/styles/components/related-objects/_related-assessments.scss
Wording "No Related Assessments were found" is not centered
1. Open Related Assessments window 
2. Look at the wording "No Related Assessments were found": is not centered
_Actual Result_: Wording "No Related Assessments were found" is not centered
_Expected Result_: wording "No Related Assessments were found" should be centered
Apply `text-align: center` to "empty Related Assessments" message
> GGRC-2004 Assessment: wording "No Related Assessments were found" is not centered

- test/selenium/src/tests/test_asmts_workflow.py
Constructor of HelpRestService initializes RestClient. Constructor of RestClient uses APP_URL.
APP_URL will be set in Pytest function fixture so it can't be used when code is parsed.
> QUICK-FIX Initialize ObjectsInfoService at test level in Selenium tests

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/__init__.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/export_page.py
- test/selenium/src/lib/page/login.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/url.py
- test/selenium/src/lib/utils/conftest_utils.py
- test/selenium/src/tests/conftest.py
- test/selenium/src/tests/test_admin_dashboard_page.py
- test/selenium/src/tests/test_login_page.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_people_groups_page.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_risk_threats_page.py
- test/selenium/src/tests/test_snapshots.py
We plan to use two dev endpoints for Selenium tests' parallelization.
I plan to set endpoint in Pytest function fixture.
So we should not set `URL` class attribute as it won't be changed when APP_URL changes.
I removed `URL` attribute where it was unused.
In the rest of places `URL` can't generally be moved to a constructor because a constructor expects that a page is already navigated to and initializes page elements.
base.Page class was used only in one place (LoginPage in test_login_page.py) so I decided to remove it as having one page class is simpler.
> QUICK-FIX Do not set page url when code is parsed as APP_URL will be set in Pytest function fixture

- src/cron.yaml
Cron job for syncing triggers too many requests and is being throttled. 
deploy cron.yaml and check the app-enigne to see that the hourly cron is not present
Remove the cron configuration for issue tracker sync job.
Note: This has already been deployed to prod and pilot and verified there that the cron job is no longer present.
> GGRC-4804 Remove hourly cron job for issue tracker sync

- bin/check_migration_history
Exception:
```sh
ggrc: OK migration chain.
ggrc_basic_permissions: OK migration chain.
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/vagrant/src/ggrc/migrate.py", line 226, in <module>
main(sys.argv)
File "/vagrant/src/ggrc/migrate.py", line 220, in main
cfg = make_extension_config(extension_module_name)
File "/vagrant/src/ggrc/migrate.py", line 92, in make_extension_config
module = get_extension_module(extension_module_name)
File "ggrc/extensions.py", line 34, in get_extension_module
__import__(module_name)
ImportError: No module named ggrc_gdrive_integration
ggrc_gdrive_integration: OK migration chain. …
```
> QUICK-FIX Remove obsolete migration chain from a script

- src/ggrc/models/proposal.py
- src/ggrc/models/utils.py
- src/ggrc_workflows/models/task_group_object.py
- test/integration/ggrc_workflows/models/test_cycle.py
`TaskGroupObject object has no attribute` error message is displayed while clicking `Submit` button in `Submit for review` popup for Risk object.
1. Create `Risk`;
2. Click `Submit for review` button on Risk info pane/page;
3. Assign `reviewer` and `Due date`.
Risk object has been successfully submitted for review.
* `object` property has been replaced by `JsonPolymorphicRelationship` in `TaskGroupObject`;
* `JsonPolymorphicRelationship` has been updated with logic for loading instance from db, if this instance doesn't exist in object as attribute;
* A new integration tests has been writing for testing cycle creation with mapped object.
> GGRC-4223/1639 Fix TaskGroupObject attribute error

- src/ggrc/models/hooks/acl/__init__.py
- src/ggrc_workflows/models/hooks/workflow.py
Cleanup Workflow propagation code for future refactors
make sure wf propagation works
This just makes sure we have all data needed to do wf acl propagation in flask.g, so we can do the propagation at any later point in the request.
> QUICK-FIX Cleanup workflow ACL propagation 

- src/ggrc-client/js/components/object-mapper/object-mapper.js
- src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
- src/ggrc-client/js/components/tree/sub-tree-wrapper.js
- src/ggrc-client/js/components/tree/tests/sub-tree-wrapper_spec.js
- src/ggrc-client/js/events/eventTypes.js
- src/ggrc-client/js/models/cycle_models.js
Tree view is not refreshed on 'Active Cycles' tab after adding new Cycle Task to current Workflow.
1. Create Repeat off workflow
2. Create a task for task group and activate wf
3. At the Active Cycles tab click Create button to create a Cycle task
4. In new cycle task modal fill out the required fields and click Save and Close button
Actual Result: Tree view is not refreshed after adding a cycle task
Expected Result: Tree view should be refreshed after adding a cycle task.
Handle Cycle Task creation for Active Cycles tab.
> GGRC-4388 Refresh Active Cycles after add new

- src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
Auditor doesn't see Import assessment button in 3 bb's menu
1. Create an audit and add auditor to audit
2. Log as auditor and go to audit page
3. Click 3 bb's menu in tree view in Assessments tab
_Actual Result_: Auditor doesn't see Import assessment button in 3 bb's menu
_Expected Result_: Auditor should see Import assessment button in 3 bb's menu
Display "_Import Assessments_" if "_is_auditor_" helper returns "**true**"
> GGRC-4283 Auditor doesn't see Import assessment button in 3 bb's menu

- src/requirements-selenium.txt
- test/selenium/conftest.py
- test/selenium/pytest.ini
- test/selenium/run_selenium.py
- test/selenium/src/lib/constants/settings.py
- test/selenium/src/lib/environment/__init__.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/url.py
- test/selenium/src/tests/test_audit_page.py
A fixture that sets an url should be function fixture as we'd like
to use different base urls depending on the test.
base_url fixture can't be changed to be function fixture because
pytest-base-url uses it from autouse session _verify_url fixture.
Also change APP_URL to lowercase as it's not constant anymore.
Contains changes from #7560
> QUICK-FIX Use pytest-env instead of pytest-base-url to set the base url

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/show-related-assessments-button/show-related-assessments-button.js
- src/ggrc-client/js/controllers/inner-nav-controller.js
- src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
- src/ggrc-client/js/plugins/utils/models-utils.js
- src/ggrc-client/js/plugins/utils/snapshot-utils.js
- src/ggrc-client/js/pub-sub.js
Last assessment date  doesn't update after updating of Assessment's status.
1. Map Control to Regulation (or other entity);
2. Map Assessment (generated by Control from point 1) to Regulation (or other entity);
3. Open Regulation page;
4. Open Controls tab;
5. Open Assessments tab;
6. Open Assessment and set 'Complete' status;
7. Open Controls tab again.
_Actual result_: Control's tree-view wasn't refreshed. Last assessment date column is empty;
_Expected result_:  Last assessment date column is **NOT** empty;
Set `refresh` flag to `true` value for all opened tree-views except of **assessment tree-view**
> GGRC-4771 Last assessment date column doesn't display data for certain controls

- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
- src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
Search should be applied by default on 'Bulk Update' pop-up
1. Go to 'May Tasks' page.
2. Click 3 dots menu.
3. Click 'Bulk Update'.
Actual result: 'Bulk Update' pop-up is opened. No tasks are displayed, as far as search isn't applied.
Expected result: 'Bulk Update' pop-up is opened. Search is applied
Run search in 'inserted' event handler.
> GGRC-4239 Search should be applied by default on 'Bulk Update' pop-up

- src/ggrc/models/hooks/issue_tracker.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
As assignees change, the buganizer sync needs to be updated
Change assessment assignee with enabled issue tracker integration. Issue assignee should be updated.
Assignee update functionality has been added to `sync_issue_tracker_statuses()`
> GGRC-4654 Change assignee in issue tracker in case it has been updated

- src/ggrc-client/js/components/proposal/review-proposal.js
- src/ggrc-client/js/components/revision-log/revision-log.js
- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
- src/ggrc/cache/cache.py
- src/ggrc/cache/memcache.py
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/hooks/custom_attribute_definition.py
- src/ggrc/models/mixins/customattributable.py
- src/ggrc/models/revision.py
- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_imported_api_requests.py
- test/integration/ggrc/models/test_revision.py
- test/integration/ggrc/proposal/api/test_cads.py
- test/integration/ggrc/services/__init__.py
- test/integration/ggrc/snapshotter/test_indexing.py
- test/selenium/src/tests/test_snapshots.py
- test/unit/ggrc/models/test_revision.py
On revert to state where CADs are not set up values are not presented in diff builder and not reverted. 
1) create control 
2) create cads for control 
3) propose change on editing newly added cads 
4) review proposal 
expected: 
on proposals newly added cads should be presented 
actual:
changes are not presented 
1) create control
2) edit control any way 
3) create cads for control 
4) review revision on version history tab
expected: 
newly added cads are presented 
actual:
they are not presented
populate CADs and CAVs in revisions to actual state of object.
> GGRC-4215,4216,4199 Custom attribute is missed in revision section

- ._license_header_exceptions
- bin/jenkins/functions.sh
- bin/jenkins/run_selenium
- common-services.yml
- docker-compose-testing.yml
* Remove CHROME_DRIVER_VERSION unused build arg of cleandev image
* Remove unused "vagrant_bind" volume mapping
* Use networks and depends_on instead of links as links are deprecated in docker-compose v2
* Another PR will add two additional services to docker-compose-testing.yml (cleandev_destructive, db_destructive). So services were moved to common-services.yml to DRY
* Make service a required argument in functions.sh#setup for simplicity
* Move building assets from functions.sh#setup as:
1. They are not needed for codestyle and unit tests
2. Assets will be built for cleandev and cleandev_destructive in parallel in another PR. cleandev_destructive container will be created only for selenium_tests
> QUICK-FIX Make it easier to add a new dev container to docker-compose-testing.yml

- src/ggrc/models/hooks/acl/__init__.py
> When a migration is ran, an exception is raised:
> 
> {code}
> RuntimeError: working outside of application context
> {code}
> 
> It's this line of code:
> {code}
> flask.g.new_wf_acls = workflow.get_new_wf_acls(session)
> {code}
> 
> This code shouldn't run during migrations. 
> 
Run migrations from `/maintenance/index`, and check the logs.
Please note that after a failed migration we must turn off maintenance mode manually (from the same page) in order to re-run migrations.
Prevent after commit hook to run outside the needed request context.
> GGRC-4829 Fix migration hooks

- src/ggrc/converters/import_helper.py
- src/ggrc/gdrive/file_actions.py
- src/ggrc/login/__init__.py
- src/ggrc/migrations/versions/20180322133839_9b75e604c326_add_in_progress_status_to_import_export_.py
- src/ggrc/models/all_models.py
- src/ggrc/models/import_export.py
- src/ggrc/services/resources/person.py
- src/ggrc/views/converters.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/model_factory.py
- test/integration/ggrc/services/resources/test_converters.py
Execute import/export as a background task
1. Run integration tests.
2. Manually run HTTP requests described in [TDD](https://docs.google.com/document/d/1EWyVTtYppNDS_jRc7rTwH3aH5VMrGvKKtzBZka2vE4c).
[TDD](https://docs.google.com/document/d/1EWyVTtYppNDS_jRc7rTwH3aH5VMrGvKKtzBZka2vE4c)
> GGRC-4365/2665/4274/4125/4132 Import/Export

- src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
Assessment template is written in one word as "AssessmentTemplate" in 3 bb's menu
1. On the audit page create assessment template
2. In assessment template tab click 3 bb's menu in tree view
3. Look at the controls 
Actual Result: Assessment template is written in one word as "AssessmentTemplate"
Expected Result: Assessment template is written in two word as "Assessment Template"
Use `title_plural` instead of `model_plural`.
> GGRC-1865 Fix import/export buttons wording

- src/ggrc/settings/default.py
Bump version from 1.8.0-Strawberry to 1.9.0-Strawberry.
> QUICK-FIX Bump version to 1.9.0-Strawberry

- src/ggrc-client/js/components/modal_wrappers/assessment-modal.js
- src/ggrc-client/js/components/modal_wrappers/tests/assessment-modal_spec.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
Issues that are mapped to Assessment directly should not to be displayed in Edit Assessment popup (also for Audit, it was discussed with Liliya)
1. Open Assessment window with mapped or raised issues
2.Open Edit Assessment popup.
If type of mapped object is Audit or Issue not to display it into Edit Assessment popup template
> GGRC-4614 Prohibit display mapped issues and audit

- src/ggrc-client/js/models/join_models.js
"Uncaught TypeError: Cannot read property 'content' of null" error occurs if Global Creator opens Change Log tab for Assessment. Spinner is rounding endlessly, no info is shown
1. Create a program and a control in scope of the program
2. Create an audit in scope of the program
3. Open audit page, create an Assessment and assign Global Creator user as Assignee Verifier
4. Map Snapshot to this Assessment
5. Log as Verifier and open Audit page
6. Expand Assessment Info panel and click Change Log tab
_Actual Result:_ "Uncaught TypeError: Cannot read property 'content' of null" error occurs if Global Creator opens Change Log tab for Assessment. Spinner is rounding endlessly, no info is shown
_Expected Result:_ no errors should be shown up if open Change Log tab as Global Creator
**Reason**: …
> GGRC-4690 "Uncaught TypeError: Cannot read property 'content' of null" error occurs if Global Creator opens Change Log tab for Assessment

- src/ggrc-client/js/components/confirm-action/confirm-action.js
- src/ggrc-client/js/components/import-export/download-template/download-template.mustache
- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc-client/js/components/import-export/test/import_spec.js
- src/ggrc-client/styles/components/confirm-action/_confirm-action.scss
> QUICK-FIX [IMPORT] Small UI fixes after BA review

- src/ggrc/assets/mustache/assessment_templates/info.mustache
'Default Verifier' wording is displayed on Assessment Template info panel
2. Create assessment template
3. Expand ATemplate Info panel
Actual Result: 'Default Verifier' wording is displayed on Assessment Template info panel
Expected Result: *'Default Verifiers'* wording is displayed on Assessment Template info panel
Change label.
> GGRC-4545 Fix default verifiers label for Assessment Template

- src/ggrc-client/js/components/object-mapper/object-mapper.js
The application sends 2 Assessment's GET requests instead of 1 request.
1. Open any assessment;
2. Open _Control mapper_;
3. Map any Control;
4. Look at the number of **GET** requests;
_Actual result_: The application sends 2 GET requests;
_Expected result_: The application sends 1 GET request;
Remove unneeded instance's `refresh`
> GGRC-3237 Assessment - Map Control or other object: remove unneeded queriesGGRC-3237

- src/ggrc/notifications/job_emails.py
- src/ggrc/settings/default.py
- src/ggrc/templates/notifications/import_export.html
- src/ggrc/views/converters.py
**Please, review only the 2 last commits**
Send emails about import/export job results.
1. Run import/export requests manually according to [TDD](https://docs.google.com/document/d/1EWyVTtYppNDS_jRc7rTwH3aH5VMrGvKKtzBZka2vE4c).
Emails templates are created according to https://docs.google.com/spreadsheets/d/1LOlpayMjQaj8-EiBUNR52Mb-EAk4xgxCaY64sqW4erg
> GGRC-4126/4130 Import/Export Emails

- src/ggrc/converters/base_block.py
- test/integration/ggrc/converters/test_import_csv.py
- test/integration/ggrc/test_csvs/import_with_code_column.csv
- test/integration/ggrc/test_csvs/import_without_code_column.csv
`Import failed due to server error` error occurs while importing csv file with no `Code` column
1. Export csv file for some `Slugged` objects (`Controls` for example)
2. Remove `Code*` column
3. Try to import this file
4. Error message `Missing mandatory column Code, when adding object.` should be displayed.
Some additional checks have been added before csv file parsing (in `BlockConverter` validation step). 
If somebody tries to import object which is subclass of `Slugged` mixin  and there is no `Code` column in csv file, error message will be displayed.
Also integration test for this case has been added.
> GGRC-2057 "Import failed due to server error" error occurs while importing csv file with no Code column

- src/ggrc-client/js/components/import-export/import.js
If import is successfully finished and user stays on import page, then show a floating message.
Message: Import was completed successfully.
> GGRC-4853 [IMPORT] Show floating message if import is finished and user stays on the page

- src/ggrc-client/styles/modules/_import-export.scss
If import file with any error, then a red triangle should be shown and name of file should also be red.
If triangle is yellow, then title of file should be still black.
> GGRC-4852 [IMPORT] Make name of file red, if some errors occur

- bin/jenkins/functions.sh
- docker-compose-testing.yml
- test/selenium/conftest.py
- test/selenium/pytest.ini
- test/selenium/run_selenium.py
- test/selenium/src/lib/constants/regex.py
- test/selenium/src/lib/constants/test_runner.py
- test/selenium/src/lib/custom_pytest_scheduling.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_snapshots.py
- test/selenium/src/tests/test_unified_mapper.py
Please see #7568 for run time comparison.
Build time: 26 min
Tests run time: 1000, 1020 seconds
> QUICK-FIX Parallel Selenium tests without headless

- src/ggrc/converters/import_helper.py
- src/ggrc/models/import_export.py
- src/ggrc/views/converters.py
- test/integration/ggrc/services/resources/test_converters.py
If csv-file contains blocks with invalid object type, the errors have to be shown in pre-analysis phase of import (when csv-file is submitted)
Try to import csv-file with invalid object type.
info structure is returned for every block. It contains error messages with line number. Status of import is set to "Analysis Failed" if errors are found, otherwise, it is "Not Started".
> BE - [IMPORT] Show error about invalid object type on pre-analysis

- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/styles/components/folder-attachments-list/folder-attachments-list.scss
- src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
- src/ggrc-client/styles/components/related-objects/_related-urls.scss
- src/ggrc-client/styles/modules/_assessment.scss
- src/ggrc/assets/mustache/assessments/modal_content.mustache
- src/ggrc/assets/mustache/audits/info.mustache
- src/ggrc/assets/mustache/base_objects/reference-urls.mustache
- src/ggrc/assets/mustache/controls/info.mustache
- src/ggrc/assets/mustache/workflows/info.mustache
Cut long attachment/folder title and urls with the length equal to two columns. 
Check objects with attachments and urls.
Set max-width for required blocks.
> GGRC-4059 Align attachments and urls width

- src/ggrc-client/js/components/import-export/import-export-utils.js
- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc-client/js/components/import-export/test/import-export-utils_spec.js
- src/ggrc-client/js/components/import-export/test/import_spec.js
- src/ggrc-client/styles/modules/_import-export.scss
Steps to reproduce
1. Create a program, map control, objective
2. Go to the Import page and download Audit template
3. Fill required fields, map program, control, objective to audit > Save
4. Import audit
5. Look at the screen: "1 records ignored" is shown
Actual Result: If there is an error while importing, BE sends an error but FE doesn't show an error
Expected Result: If there is an error while importing FE should show an error that was sent by BE
Case 2
1. Create Program, map control
2. Create Audit, Assessment and Issue
3. Export Issue -> unmap Audit -> import Issue
4. Look at BE response
Actual Result: There is a warning while importing Issue but FE doesn't show a warning.
*Briefly explain the solution or add a link to the …
> GGRC-3959/4834 [IMPORT] Show import's errors

- src/ggrc-client/js/components/revision-log/revision-log-data.mustache
Value of Rich text custom attribute is displayed in tags.
1. Open any Standard Info page
2. Fill out rich text global CA > Save
3. Open Change Log tab and look at the new value
**Actual Result:** Value of Rich text custom attribute is displayed in tags
**Expected Result:** Value of Rich text custom attribute should not be displayed in tags
Display unescaped values in change log.
> GGRC-4608 Show formatted text in revision/change log

- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.mustache
Deprecate' option is missing for **Admin** and **Editor** roles
1. Create a WF, create at least one task group task in a task group. Activate WF.
2. Log in as a Global Editor.
3. Go to a WF (Global Editor should NOT have any WF role in this workflow: WF manager, WF member, Task Assignee).
4. Go to 'Active Cycles' tab and open info pane for a cycle task.
5. Click 3 dots button.
_Actual result_: 'Deprecate' option is missing
_Expected result_: 'Deprecate' option should be available. Global Editor should be able to deprecate / restore cycle task.
`allow_change_state` is true when user is WF Admin or CT Assignee and cycle is current.
By requirements every user with edit rights (WF Admin, CT Assignee, CT Secondary Assignee, Global Admin, Global Editor) can deprecate/restore cycle task. 
So …
> GGRC-4027, 4028 Global Editor/Admin should be able to deprecate / restore cycle task

- bin/jenkins/run_integration
- bin/jenkins/run_selenium
- bin/jenkins/run_unittests
I run `./bin/jenkins/run_selenium` locally.
If this task is already currently running, it takes a lot of CPU.
Building containers also takes CPU.
So stopping containers before building them reduces CPU usage.
If containers are already stopped, stopping takes 0 seconds so this change doesn't affect CI time.
> QUICK-FIX Teardown containers before building them

- test/selenium/pytest.ini
Test run time (with headless): 985, 900, 990, 910 seconds
Test run time (in Kokoro):
Without parallelization | With parallelization (n=4), with headless | With parallelization (n=4), without headless
---------------|----------|-----
36 - 45 minutes (based on 11 runs) | about 18 minutes | about 18 minutes |
Locally tests take more time on my machine both with and without parallelization.
Parallelization of tests is very easy to achieve with Pytest-xdist. Only "-n" parameter should be added.
But currently there was one test that couldn't be run in parallel with other tests. We think that we may have more such tests in future so we decided to send all such tests to a different dev container than other tests.
> QUICK-FIX Parallel Selenium tests with headless

- src/ggrc-client/js/models/mixins.js
- src/ggrc-client/js/models/simple_models.js
"Uncaught TypeError: Cannot read property 'issue_tracker' of undefined" error occurs if open LHN
Enable issue tracker.
1. Open My work page
2. Open LHN and expand accordion with Assessments 
*Actual Result:* "Uncaught TypeError: Cannot read property 'issue_tracker' of undefined" error occurs
*Expected Result:* no errors should be shown while opening LHN
`get_instance` builds model without `type` property.
We use the property in `mixins.js:ensureParentAudit()` to send query api request.
> GGRC-4791 "Uncaught TypeError: Cannot read property 'issue_tracker' of undefined" error occurs if open LHN

- src/ggrc/settings/default.py
Bump version from 1.9.0-Strawberry to 1.10.0-Strawberry.
> QUICK-FIX Bump version to 1.10.0-Strawberry

- test/selenium/src/lib/base.py
Currently if there is a large number of checkboxes, `select_by_titles` method takes several seconds to execute.
As a result, if there are 150 GCAs (unrealistic case), `test_destructive_asmts_gcas_filtering` takes 150 seconds with not optimized implementation. With optimized implementation, it takes about 43 seconds regardless of number of GCAs.
Overall, "select_by_titles" method is used at least in the following tests:
* test_destructive_asmts_gcas_filtering
* test_destructive_asmts_lcas_filtering
* test_destructive_search_unified_mapper_and_check_mapping
> QUICK-FIX Optimize selection of checkboxes to check

- src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js
- src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.mustache
- src/ggrc-client/styles/modules/_assessment.scss
Values in PRIMARY CONTACT and SECONDARY CONTACT fields are not updated on Control's popup with related Objectives and Regulations 
1. Have audit with Control's snapshot that contain values in PRIMARY CONTACTS and SECONDARY CONTACTS fields
2. Generate assessment based on the Control's snapshot
3. On the Assessment's Info pane expand Control's popup with related Objectives and Regulations
4. Look at the PRIMARY CONTACTS and SECONDARY CONTACTS fields: there are no values
_Actual Result_: Values in PRIMARY CONTACT and SECONDARY CONTACT fields are not updated on Control's popup with related Objectives and Regulations 
_Expected Result_: Values in PRIMARY CONTACT and SECONDARY CONTACT fields should be displayed on Control's popup with related Objectives and Regulations or should be updated …
> GGRC-2414 Add PRIMARY CONTACT and SECONDARY CONTACT fields on Related Controls Modal

- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
There were a lot of eslint issues not fixable automatically.
Fix issues manually.
> QUICK-FIX Fix rest eslint issues in mustache_helper.js

- src/ggrc/assets/mustache/audits/dropdown_menu.mustache
Audit captain can see 'Clone Audit' button although he has no rights to modify program. As result, if he tries to clone it, he will get an permission error.
1. Log as Global Creator user and create a program
2. Create an audit
3. Remove Global Creator as a program manager and assign another user
4. As Global Creator (Audit Captain) try to clone Audit
**Actual result:** 
User as an Audit captain is not able to clone Audit if such a user is removed as program manager. GET 403 error is shown
Audit Captain role shouldn't give you rights to clone an Audit.
Only user who has both minimum READ rights for Audit and EDIT rights for Program should be able to clone an Audit.
That means, that we should hide 'Clone' option for a person who is Global Creator or …
> GGRC-4714 Hide "Clone Audit" button if it is not allowed to update program

- src/requirements-selenium.txt
- test/selenium/pytest.ini
Currently our Selenium tests intermittently fail to start in CI presumably because some of our plugins don't work with each other well.
The stack trace printed is the same as in these issues:
* https://github.com/pytest-dev/pytest-xdist/issues/204
* https://github.com/pytest-dev/pytest-xdist/issues/117
* https://bitbucket.org/pytest-dev/pytest-timeout/issues/8/internalerror-valueerror-signal-only-works
Also I removed unused pytest-flask and pytest-pep8 plugins.
> QUICK-FIX Fix intermittent issue with test startup

- test/selenium/src/tests/test_snapshots.py
This will increase build / test run time as this test is relatively slow.
> QUICK-FIX Mark an intermittently failing test as destructive

- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc-client/styles/modules/_object-content.scss
Default Assignees/Default Verifiers are displaying differently in Assessment template info panel/page
1. Open any Audit page
2. Create Assessment template with Default Assignees and Default Verifiers
3. Expand Assessment Info panel and look at the Default Assignees/Default Verifiers 
4. Open Assessment template Info page and look at the Default Assignees/Default Verifiers 
**Actual Result:** Default Assignees/Default Verifiers are displaying differently in Assessment template info panel/page
**Expected Result:** Unify format of Default Assignees/Default Verifiers in Assessment template info panel/page.
Update css.
> GGRC-4668 Unify format of Default Assignees/Default Verifiers in Assessment template

- src/ggrc/views/converters.py
Out of memory exception has to be processed gracefully. Import/Export job shouldn't stuck 'In Progress' state.
Run import of huge amount of objects.
If deferred task failed to for some reason, the task is retry by app engine automatically. So, request's header
> GGRC-4835 [IMPORT] Handling big imports that cause memory exceptions

- src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
- src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
- src/ggrc-client/js/components/issue-tracker/temporary-issue-tracker-notification.js
When user change or remove hotlist id - changes are save in GGRC, but hotlist isn't removed in buganizer issue.
1. In 'docker-compose.override.yml' set:
ISSUE_TRACKER_ENABLED=true
ISSUE_TRACKER_MOCK=true
2. rebuild container, launch ggrc
3. Create /generate an Assessment with buganizer switch ON. 
4. Remove / update Hotlist ID for Assessment and save changes.
Actual result: Changes are save in GGRC, but hotlist isn't removed in buganizer issue.
Expected result. On saving, a floating message should be shown "To change or remove hotlist, you have to remove it for Assessment and then make necessary changes in Buganizer. Sorry for inconvenience"
I've added listener which show the notification if "hotlist_id" is change.
> GGRC-3977 Show message when user change/remove hotlist id

- src/ggrc/notifications/job_emails.py
- src/ggrc/templates/notifications/import_export.html
- src/ggrc/templates/notifications/style.html
View of email notification does not follow the design
Open email notification after Import/Export
New design
> GGRC-4873 Improve email layout for Export/Import

- src/ggrc/services/common.py
- test/integration/ggrc/services/test_common.py
- test/integration/ggrc/utils/test_user_generator.py
I really want this code to be moved into specific Person resource, but a PR straight to the release branch can't have refactorings.
If a client POSTs multiple People with `external=True`, all objects except the first one are ignored.
POST multiple People with `external=True` flag.
Special code that processes just the first Person object is replaced with code that processes a list of Person objects.
> GGRC-4775 Create external users in bulk

- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc/bootstrap.py
- src/ggrc/models/hooks/acl/__init__.py
- src/ggrc_workflows/models/hooks/workflow.py
- test/integration/ggrc_workflows/test_acl_concurrency.py
The object review bug was fixed on the frontend and caused a performance regression. This PR should move the fix to the backend and allow concurrent requests when creating object review 
>  1. Open /controls/6585  or any other control on should work as well 
>  2. On the Control Info page click Submit for review
>  3. Assign a reviewer and set a due date
>  4. Click Submit button
>  *Actual Result:* (OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') error occurs while submitting for review 
>  *Expected Result:* no errors should be displayed while submitting for review
Add commits and retries when a deadlock occurs.
> GGRC-4832 Fix concurrency issues

- src/cron.yaml
The job is fixed in scope of #7571 and should be enabled again.
Deploy cron.yaml and check the cron jobs list on app engine.
Revert #7556
> GGRC-4886 Enable issue tracker sync job

- src/ggrc-client/js/components/assessment/templates/assessment-people.mustache
- src/ggrc-client/js/components/custom-roles/custom-roles.js
- src/ggrc-client/js/components/custom-roles/templates/custom-roles.mustache
- src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
- src/ggrc-client/js/components/related-objects/related-people-access-control.js
- src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
- src/ggrc-client/js/events/eventTypes.js
The changing of custom-roles as Assignees, Creators and Verifiers is one separate PUT request which is not synchronized with changing of assessment state, this problem is cause for conflicts and that assessment goes in wrong status after completing it.
1. Have audit with assessment
2. Navigate to assessment's info pane and fill all the mandatory fields if any 
3. Add a verifier to the People list and click [Complete] button once a person is added to People list (do not wait when the app saves person in People list)
4. Look at the assessment's status and open Dev tools (Network)
Actual Result: Assessment is not moved to Ready for Review state with verifier
Expected Result: Assessment should be moved to Ready for …
> GGRC-2454/4502 Synchronize Creators, Assignees, Verifiers with "Complete" button

- src/ggrc/views/converters.py
After running import in dry mode db changes are not rolled back
Import object that doesn't exist in db.
Rollback changes made durig dry-run import mode.
> GGRC-4881 Error message that object already exists is displayed after importing

- src/ggrc-client/js/components/feedback-link/feedback-link.js
- src/ggrc-client/js/components/feedback-link/templates/feedback-link.mustache
- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/components/page-header/page-header.mustache
- src/ggrc/templates/base_objects/_page_header.haml
ACCEPTANCE CRITERIA:
AC1. Make it possible to turn on this feature during deployment. If feature turned of, then do not display 'Feedback' button.
AC2. Make it possible to turn on this feature for both prod instances (not only rmc).
AC3. Show this link in the header (except header for My Assessments page).
AC4. On clicking 'Feedback' button, buganizer page in a new tab should be opened.
Open any page, where can be placed header. The link should be placed near with the Global Search.
The mockup is placed into the ticket.
For showing the link, the separate component was created. The link will be included by BE with help an env variable `CREATE_ISSUE_URL `.
> GGRC-4770 RMC - New UI Feature

- src/ggrc-client/js/components/gca-controls/gca-controls.js
- src/ggrc-client/js/components/proposal/review-proposal.js
- src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js
- src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js
- src/ggrc-client/js/components/revision-history/mandatory-fields-modal.js
- src/ggrc-client/js/components/revision-history/restore-revision.js
- src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
- src/ggrc-client/js/components/revision-history/templates/restore-revision.mustache
- src/ggrc-client/js/components/revision-history/tests/mandatory-fields-modal_spec.js
- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/js/plugins/tests/object-history-utils_spec.js
- src/ggrc-client/js/plugins/utils/object-history-utils.js
- src/ggrc-client/styles/components/revision-history/_revision-history.scss
Implement pop-up with mandatory fields for Restore Version feature
1. User creates a control.
2. User changes title.
3. Admin adds mandatory GCA for all controls in admin dashboard.
4. User restore initial version of the control.
**Actual result:** Version is restored if user clicks 'Restore Version' button on comparer pop-up.
**Expected result:** Pop-up with all mandatory fields that were added to object, after restored version had been created, should be shown. User first need to fill out required field / make sure that they are properly filled out, and then restore version.
> GGRC-4176/GGRC-4617 Implement pop-up with mandatory fields for Restore Version feature

- src/ggrc-client/js/components/import-export/export.js
- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc/assets/assets.yaml
- src/ggrc/assets/mustache/modals/open_sheet.mustache
1. Go to Export page
2. Select any object type to export
3. Click 'Start export' button
4. Click 'Write to Sheet' button
Actual Result: Chrome browser blocks displaying of Google Sheet while clicking 'Write to Sheet' button on Export page
Expected Result: Chrome browser should not block displaying of Google Sheet while clicking 'Write to Sheet' button on Export page
link on gSheet has moved into modal dialog
> GGRC-4882 Additional permissions are required for displaying Google Sheet after export

- src/ggrc-client/js/components/multi-select-label/multi-select-label.js
- src/ggrc-client/js/components/multi-select-label/multi-select-label_spec.js
Created labels don't have `type` property
Add `type: Label` property when create new label
> GGRC-4099 FE: Update labels attribute format

- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc-client/styles/modules/_import-export.scss
- src/ggrc/views/converters.py
'Wrong status' error is appears after click on `Cancel` button
**GGRC-4885**
1. Open import page
2. Choose a file to import with a valid format (csv) from GDrive/computer
3. After pre-analysis check 'I confirm' checkbox
4. Click on 'Proceed' button
5. Click on 'Cancel' button when analysis is in progress
Actual Result:
'Wrong status' error message is displayed in UI;
PUT 400 is displayed in Network tab (console)
Spinner is turning around endlessly for Analyzing file
Expected Result: Analysis should be canceled. Initial Import page should be displayed.
**GGRC-4891**: Previous background job is displayed on the Import page if click trash icon in Import history
1. Open Import page
2. Download two separate csv templates for any objects: e.g. Projects …
> GGRC-4885/4891 'Wrong status' error message is displayed if user canceled analysis of imported file

- test/selenium/src/lib/constants/__init__.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/url.py
Currently ACL role ids are hardcoded.
I have used "api/access_control_roles" to remove this hardcoding.
Unrelated, I also refactored RestClient class to use requests.Session. This simplified code a bit. Session uses Keep-Alive.
> QUICK-FIX Remove hardcoded acl role ids

- src/ggrc-client/js/apps/base_widgets.js
Remove Assessment widget on the Program page
1. Have program, audit, assessment
2. On the program page add Assessment widget: assessments are not shown
Actual Result: The possibility to add Assessment widget on the Program page
Expected Result: There should be no possibility to add Assessment tab on the Program page.
Change config file.
> GGRC-2163 Remove Assessments tab from Program page

- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
TICKET TRACKER control is not aligned to the left
2. Turn on buganizer for audit
3. Create Assessment
4. Navigate to Assessment Info panel > Other Attributes tab
5. Look at TICKET TRACKER control
_Actual Result_: TICKET TRACKER control is not aligned to the left
_Expected Result:_ TICKET TRACKER control should be aligned to the left
Display TICKET TRACKER in separated row.
Added `ggrc-form-item__row` class
> GGRC-4884 Ticket Tracker control is not aligned to the left on Assessment Info panel

- bin/jenkins/functions.sh
- test/selenium/conftest.py
- test/selenium/pytest.ini
- test/selenium/run_selenium.py
- test/selenium/src/lib/file_ops.py
- test/selenium/src/lib/utils/conftest_utils.py
- test/selenium/src/tests/test_audit_page.py
Currently dev server logs in Selenium tests cannot be observed.
Add dev server logs as links to HTML report.
I use only one instance of dev server locally. So DEV_LOG, DEV_URL, DEV_DESTRUCTIVE_LOG, DEV_DESTRUCTIVE_URL are configured via env variables as I override them at IDE level.
> QUICK-FIX Add dev server logs to Selenium HTML report

- src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js
- src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
- src/ggrc-client/js/components/tests/cycle-task-actions_spec.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/styles/components/tree/_sub-tree-wrapper.scss
- src/ggrc-client/styles/components/tree/_tree-view.scss
- src/ggrc-client/styles/modules/_spinner.scss
Display spinner for cycle tasks in TreeView, while a request to the server is in progress.
1. Create any WF; 
2. In the Setup tab add tasks to Task Group ;
3. Activate WF;
4. In the Active Cycles tab expand TreeView with Cycle Tasks;
5. Click on "Start", "Undo" or "Finish" button;
Modify `cycle-task-actions.mustache` template to include `spinner` component when an action button is disabled.
> GGRC-4874/GGRC-4875 Add spinner for Cycle Tasks actions in TreeView

- src/ggrc-client/js/components/feedback-link/feedback-link.js
- src/ggrc-client/js/components/page-header/page-header.mustache
- src/ggrc-client/styles/layout/_header.scss
- src/ggrc/templates/base_objects/_page_header.haml
Make it possible to configure the name of button on the moment of deployment.
- Add setting `CREATE_ISSUE_BUTTON_NAME=<some_name>` into docker-compose.override.yml
- Rerun container: `./bin/containers run`
- Look on the feedback button.
Display `CREATE_ISSUE_BUTTON_NAME` if it is exist, else display 'Feedback'.
Fix styles for feedback link in colored headers.
> GGRC-4898 Get 'Feedback' button name from environment variable

- src/ggrc-client/js/apps/risk_assessments.js
- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/bootstrap/wysihtml5.js
- src/ggrc-client/js/components/quick_form/quick_add.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/components/tasks-counter/tasks-counter.js
- src/ggrc-client/js/components/workflow/workflow_deactivate.js
- src/ggrc-client/js/controllers/approval_workflow_controller.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js/controllers/workflow_page.js
- src/ggrc-client/js/ggrc_base.js
- src/ggrc-client/js/models/category.js
- src/ggrc-client/js/models/directive_models.js
- src/ggrc-client/js/models/local_list_cache.js
- src/ggrc-client/js/models/notification_config.js
- src/ggrc-client/js/models/risk_assessment.js
- src/ggrc-client/js/models/workflow.js
- src/ggrc-client/js/models/workflow_join_models.js
- src/ggrc-client/js/plugins/datepicker.js
- src/ggrc-client/js/plugins/wysiwyg.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
- src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
- src/ggrc-client/js_specs/mustache_helpers/debugger_spec.js
- src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
- src/ggrc-client/js_specs/mustache_helpers/get_permalink_for_object_spec.js
A lot of eslint warnings.
Fixed `quotes` rule in all codebase
~ -1k eslint errors
> QUICK-FIX Fix eslint quotes rule

- src/ggrc-client/js/components/import-export/import.js
Very general message for failed jobs
1. Download Assessment csv template
2. Add at least 300 Assessments to csv file > Save
3. Import csv file
4. Look at the screen: 'Import failed due to server error' is displayed
Actual Result: 'Import failed due to server error' is displayed for user in UI if user tries to import huge # of objects and import proceeds more than 10 min
Expected Result: Make a proper warning message for a user that csv file cannot be imported due to exceeding a limit of items in csv file
"The volume of import is too big. Please split your import in smaller portion of 200 or less rows and import one after another. Sorry for inconvenience."
Message changed
> GGRC-4915 Update message for failed import job

- src/ggrc-client/js/mustache_helper.js
- src/ggrc/assets/mustache/audits/dropdown_menu.mustache
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/import_export/export.haml
- src/ggrc/templates/layouts/dashboard.haml
Global Creator as Program manager is not able to archive an audit.
1. Log as admin user and create a program
2. Assign Global Creator user as Program manager of the program
3. Create an audit
4. Log as Global Creator and open audit summary page
5. Go to Audit Info tab > 3 bb's menu
Actual Result: If global creator as program manager opens audit Info tab, opens 3 bb's menu, Archive audit button is not displayed
Expected Result: Global Creator as Program manager should be able to archive an audit
Add `#has_role` helper  which checks if current user has specified role in scope of specified instance.
See commits.
> GGRC-4681 Show "Archive Audit" button for Program Manager

- src/ggrc-client/js/components/assessment/assessment-local-ca.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js
- src/ggrc-client/js/components/assessment_attributes.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
- src/ggrc-client/js/plugins/tests/ca_utils_spec.js
- src/ggrc-client/js/plugins/utils/ca-utils.js
- src/ggrc-client/styles/components/related-objects/_related-urls.scss
- src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/mixins/customattributable.py
- test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py
**Note:** Contains [GGRC-4041](https://github.com/google/ggrc-core/pull/7075)
Currently user can create an assessment template with a local custom attribute of type dropdown with a list of options. For each option he can mark that it is required to attach file or/and add comment, if option is selected.
Now user would like to mark 'evidence urls' as required for such options.
User generates an assessment.
User adds an evidence url
User select an option in local custom attribute (type = dropdown), that requires url.
System shouldn't ask to attach urls, answer is valid.
User select an option in another local custom attribute (type = dropdown), that requires url.
System should ask to attach url.
See ticket GGRC-3495 for acceptance criteria and details.
See commits.
> GGRC-3495/4041 Update assessment logic to accept attachments and/ or urls as evidence

- src/ggrc/converters/base_row.py
- src/ggrc/services/common.py
- src/ggrc/utils/__init__.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
Import fails when assessment with issue tracker integration turned on is imported.
Changes can not be tested properly in gae mode. 
Issue tracker hooks caused error because no object with initial state of assessment was sent. Now an object with initial assessment is sent from import functionality.
> GGRC-4916 Fix issue tracker hooks on assessment import

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/lib/element/tables.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
This PR adds tests for related assessments.
Left side of diagrams 1.2, 1.3, 2 from https://github.com/google/ggrc-core/pull/6841 is implemented. Test cases were discussed with Vadim.
Some stuff from https://github.com/google/ggrc-core/pull/6841 was reworked in order to simplify things.
> QUICK-FIX Tests for related assessments

- src/ggrc/migrations/versions/20180419102258_fcd5e64ff664_add_relationship_to_proposals.py
- src/ggrc/models/hooks/proposal.py
- src/ggrc/models/proposal.py
- test/integration/ggrc/proposal/test_proposal_relationship.py
Any object that will have ACL propagation on it, must be connected to the parent with relationships table. So we have to ensure that every proposal is connected to its parent object via relationinships.
Check that existing Proposals has relationships with parent instances.
Create new Proposal for proposalable object, check that relationship between this object and Proposal is created (Though the api or db).
Create a relationship between parent object and proposal in model_posted hook.
> GGRC-4810 Add relationship to Proposals

- test/integration/ggrc/__init__.py
In integration tests if where is no api calls yet tests are breaking
nosetests integration.ggrc.proposal.test_proposal_permissions
invalidate reindex_set only in cases when it's exists in the scope of the db.session
> QUICK-FIX Invalidate reindex_set on test only if it exists

- src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
Assessment template's dropdown options contain titles of fields for Audit
2. Go to Assessment template tab and click Create button
3. Click on Dropdown options for filter screenshot-1.png
4. Look at the dropdown options
Actual Result: Dropdown options contain titles of fields for Audit
Expected Result: Dropdown options should contain titles of fields for Assessment template
Fixed type for modal
> GGRC-4636 Fix dropdown for Assessment template popup

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
This PR has a simple implementation of a fixture that dynamically calls another fixture and can be used in `parametrize` together with `indirect`.
I discussed additional tests with Vadim.
> QUICK-FIX Add tests to check related asmts on Control and Objective pages

- src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
- src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
Redirection to another tab after user has defined assessment template on dashboard page (any page except Audit page).
1. Open My work page > Audit tab
2. Click on any audit in tree view
3. Click Define Assessment template in 3 dots menu
4. Create Assessment template 
Actual Result: User is redirected to Info tab after Assessment template creation
- Audit tab should be displayed after AT creation;
- Audit Info panel should be displayed after AT creation.
Add `isAuditPage` computable property for `assessment-template-clone` component.
Set `updateHash` property to modal only If `isAuditPage` equals to true.
> GGRC-4767 Check if it is audit page before redirect after Assessment Template creation

- src/ggrc/converters/errors.py
- src/ggrc/converters/handlers/multi_object.py
- src/ggrc_workflows/converters/handlers.py
- test/integration/ggrc_workflows/converters/test_task_group_import.py
User is able to map Assessment to task group via import but shouldn't.
1. Create a new workflow
2. Create a task group via import and map `Assessment: ASSESSMENT-XXX` to the Objects column.
3. Add a task to the workflow and start the cycle
**Actual Result:** User is able to map Assessment to task group via import and map Assessment to Cycle task
**Expected Result:** User should not be able to map Assessment to task group via import and map Assessment to Cycle task
Added validation to ObjectsColumnHandler related to TaskGroup.
> GGRC-4831 User is able to map Assessment to task group via import

- src/ggrc-client/js/components/add-tab-button/add-tab-button.js
- src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
- src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js
- src/ggrc-client/js/components/tree/tree-item-actions.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/permission.js
- src/ggrc-client/js/tests/permission_spec.js
- src/ggrc/assets/mustache/assessments/modal_content.mustache
"Uncaught TypeError: Cannot read property 'id' of undefined" error occurs if click map Control on Assessment Info panel
1. Open any audit page 
2. Create a control and Assign Global Creator as Primary Contact to Assessment
3. Log as Global Creator and Open Assessment Info page
4. Click Map Control button 
*Actual Result:* "Uncaught TypeError: Cannot read property 'id' of undefined" error occurs if click map Control on Assessment Info panel
*Expected Result:* no errors should be shown if click map Control on Assessment Info panel as Primary contact
Don't render map buttons if there is no audit or there is no permission to audit.
> GGRC-4766 Disallow to map Assessment if Audit is inaccessible

- docker-compose.yml
The minor version on cloud sql is currently .36 and our version on dev
environment must match it.
Normally this should not affect anything, but it seems that different
indexes are used in our queries depending on the minor version. Those
indexes can have a drastic impact on our performance.
use ggrc-qa-db dump from 2018-04-27 and update a cycle task on "big-wf-2" and see that it takes longer than 1 minute.
This means that the incorrect index is used, which is the same as on cloudsql
Set the minor mysql version to match cloudsql
> QUICK-FIX Add minor version to mysql server

- src/ggrc-client/js/mustache_helper.js
"Uncaught TypeError: Cannot read property 'type' of null" is displayed if auditor (Global creator/reader/editor) opens audit page.
The Issue happens when user has no access to the parent program, as result in the audit object the field program is null.
1. As admin user create a program, audit
2. Assign Global Creator user as Auditor in the Audit
3. Log in as Auditor (Global Creator)
4. Open Audit page
Actual Result: If Auditor (Global creator/reader/editor) opens audit page "Uncaught TypeError: Cannot read property 'type' of null" is displayed, Audit Info page is not displayed.
Expected Result: If Auditor (Global creator/reader/editor) opens audit page no errors should be displayed, audit info tab should be opened.
Check instance before getting acr in `has_role` …
> GGRC-4981 Check instance before getting acr in has_role helper.

- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/models/cacheable.js
There were a lot of redundant requests, when someone tried to open "Delete" modal for workflow.
1. Create activated WF.
2. Go to WF info page.
3. Open dev tools on Network tab.
4. Expand 3-dots menu on WF info page.
5. Click "Delete" item from the list **without** click on the "Delete" button on the appeared popup.
**Actual result**:
There are 6+ requests, which is redundant for this modal.
**Expected result**:
There are no redundant requests.
`orphaned_objects` mappings was removed, because there is no sense to use it. Bindings, which perform appropriate mappings, should have `Join` instances. Currently, there are no `Join` models, which can present appropriate instances for mappings.
There are situation, when one redundant request will be sent from modal constructor …
> GGRC-4558 Reduce extra request when "delete" modal for Workflow is shown.

- src/ggrc/data_platform/computed_attributes.py
- src/ggrc/snapshotter/indexer.py
- src/ggrc/utils/__init__.py
- src/ggrc/utils/helpers.py
- src/ggrc/utils/structures.py
- src/ggrc/views/__init__.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/fulltext/test_total_reindex.py
- test/integration/ggrc/services/resources/test_related_assessments.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/integration/ggrc/snapshotter/test_indexing.py
Reindex operation for all models, snapshots, CA consumed more than 1 GB of RAM. In https://github.com/google/ggrc-core/pull/7364 it was divided into 3 api endpoints but it was temporary solution. This PR return back single reindex.
Run reindex and check memory consumption.
Change `SQLALCHEMY_RECORD_QUERIES` to False in log options. This options is a boolean flag that is used by Flask-SQLAlchemy to cache all executed queries (http://flask-sqlalchemy.pocoo.org/2.3/api/ for last version, but for 1.0 this option work in same way).
Also to optimize memory usage for CA reindex it's run by chunks (with size 500).
Old reindex on ggrc-perf:
Reindex after reindex split:
Full reindex with this fix:
> GGRC-4580 Fix memory consumption by reindex operation

- src/ggrc-client/js/plugins/datepicker.js
- src/ggrc/assets/mustache/wf_objects/approval_modal_content.mustache
User has the possibility to set Due date in weekend for object review
1. Create a control as admin user
2. Click Submit for review link, assign a current user as reviewer
3. Set Due date in weekend and click Submit
1. User has the possibility to set Due date in weekend for object review;
2. FE doesn't send the date that user selected and shifted Due date before start date
**Expected Result:** 
1. Prohibit select Due date in weekend;
2. FE should send the date that user selected.
Add `beforeShowDay: $.datepicker.noWeekends` property in _config_ of the datepicker.
> GGRC-4452 User has the possibility to set Due date in weekend for object review

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
- src/ggrc-client/styles/mixins/_disabled.scss
- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc-client/styles/modules/_modal.scss
User has the possibility to edit fields in modal window after click Save button
1. Invoke new Control modal window
2. Fill in fields required and click [Save and Close] button
3. Update any field while saving (e.g. date)
_Actual Result_: User has the possibility to edit fields in modal window after click Save button.
_Expected Result_: User should not have the possibility to edit fields in modal window after click Save button.
Apply `ui-disabled` class to **modal's content** while the form is being processed
> GGRC-4587 Prohibit to update any field in modal window popup while saving

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/import_helper.py
- src/ggrc/converters/snapshot_block.py
- src/ggrc/views/converters.py
Improve memory usage in export.
1. On the Export page select Assessments object type
2. Select all Custom attributes
3. Click Export
Actual Result: "500 Server Error" occurred while downloading csv file with Assessments 
Expected Result: No error is shown. CSV file for Assessments is uploaded
While importing all assessments with all CA on ggrc-test it fails with memory error. 
On next picture you can see memory stats on ggrc-test. It fails almost after export starts:
On the next picture you can see memory statistic on running export on ggrc-perf with changes in this PR (But at this running export process wasn't in deferred task, so this running without newest changes from dev):
In this case export finished …
> GGRC-4880 Improve memory usage in export

- test/selenium/pytest.ini
Since test parallelization was implemented a lot of intermittent failures started to appear.
Most of time, these failures are due to deadlocks that lead to 500 errors. The following is shown in dev server logs:
```
Deadlock found when trying to get lock; try restarting transaction') 'INSERT INTO fulltext_record_properties
```
or
```
Deadlock found when trying to get lock; try restarting transaction') 'INSERT INTO access_control_list
```
or
```
Deadlock found when trying to get lock; try restarting transaction') 'INSERT IGNORE INTO relationships
```
These errors currently sometimes lead to inability to merge critical PRs and necessity to apply force-run (sometimes several times).
Deadlocks happen on prod but it looks not a priority issue.
I plan to change parallelization so there will be …
> QUICK-FIX Rerun Selenium tests twice

- src/ggrc/settings/default.py
Bump version from 1.10.0-Strawberry to 1.11.0-Strawberry.
> Bump version to 1.11.0-Strawberry

- src/ggrc-client/js/tests/ggrc_errors_spec.js
Fix skipped unit tests.
We had long time 6 skipped unit tests. They were fixed.
> QUICK-FIX Fix skipped tests

- src/ggrc-client/js/controllers/modals/modals_controller.js
Custom role tab is switched to Custom attributes tab after adding a new custom role
1. Log as admin and open Admin Dashboard
2. Go to Custom role tab and add a new custom role to any object
_Actual Result_: Custom role tab is switched to Custom attributes tab after adding a new custom role
_Expected Result_: Custom role tab should not switch to Custom attributes tab after adding a new custom role
Remove unneeded logic from 'update_hash_fragment' function
> GGRC-4341 Custom role tab is switched to Custom Attributes tab after adding a new custom role on admin dashboard

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
The changing of GCAs is separate PUT request which is not synchronized with changing of assessment state, this problem is cause for conflicts and that assessment goes in wrong status after completing it.
1. Open Assessment Info panel > Other Attributes tab 
2. Edit any GCA and save 
3. Click Complete button while saving process 
Actual Result: Assessment is moving from 'In Review' to 'In Progress'.
Expected Result: Assessments should not be moved themselves from 'In Review' to 'In Progress' while clicking Complete button.
Use 'deferredSave' to save Assessment GCAs
> GGRC-4844 Use 'deferredSave' to save Assessment GCAs

- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Add tests to check related asmts on Control page

- src/ggrc/access_control/roleable.py
- src/ggrc/models/audit.py
- test/integration/ggrc/access_control/test_roleable.py
The `full_access_control_list` should never be used in our python code. Splitting acl to internal and non-internal entries was just step towards removing all access to internal acl entries. This PR is the final step.
Check that audit archiving still works and that basic rbac checks work on it. (~~Only program managers should be able to archive and unarchive an audit~~. Only Global Admin/Program Manager can archive Audit. Only Global Admin can unarchive Audit.)
Removal of all code related to full access control list and fix the permission checks to avoid using the internal roles.
> GGRC-4975 Remove full_access_control_list references

- src/ggrc-client/js/components/related-objects/related-people-access-control.js
Exception out of memory while adding a person as Program Reader to program with 470 program readers
1. Open https://ggrc-qa.appspot.com/programs/2009#!info_widget
2. Add one more Program Reader
*Actual Result:* 
* BE processed adding a person during 56 sec. 
* FE shows exception out of memory. 
* Spinner rounds endlessly and Info pane freezes.
*Expected Result:* No exceptions should be shown while adding a user as Program reader to the program with huge # of program readers ( more than 400)
The `related-people-access-control` subscribed on `'{viewModel.instance.access_control_list} change'` event which being triggered many times after saving updated instance (canjs triggers event for each delta).
The fix is:
- Remove `access_control_list` handler. …
> GGRC-5033 - Fix incorrect event handling

- src/ggrc_basic_permissions/__init__.py
The changes in this PR with hardcoded string have been removed and replaced with proper model class name in https://github.com/google/ggrc-core/pull/7779.
This PR only contains the minimum amount of changes to fix the user blocking bug.
Memcache limit is reached when a person has permissions for too many objects
log in as vadim on latest ggrc-qa db and give him access to a bunch of big programs and such.
Note: this changes our permissions storage, so we must also test for any rbac regressions.
Remove relationships from the permissions dict.
The relationships were added to permissions automatically when we started storing acl entries for them. They were never meant to be used, but the entrie are there just for easier acl propagation, so it is safe to remove them.
Results: 
on …
> GGRC-4951 Fix memcache issue

- src/ggrc/models/import_export.py
- src/ggrc/views/converters.py
- test/integration/ggrc/services/resources/test_converters.py
Fixing this [PR-7676](https://github.com/google/ggrc-core/pull/7676)
After start new import job need to remove all previous not finished jobs on BE side, because currently it is doing from the FE side
1. Load import file.
Result: import job entry is created.
2. Load another import file.
Expected result: the previous import job is deleted by BE.
If there is an active import in "Analysis" or "In Progress" state, raise BadRequest error (401)
If there is an inactive import in "Not Started" or "Blocked" state, delete it.
Leave other imports ("Finished", "Stopped", "Analysis Failed") as they are.
> GGRC-4893 Delete previous not finished import job after start new one

- src/ggrc-client/js/components/assessment/assessment-local-ca.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
- src/ggrc-client/js/components/comment/comment-add-form.js
- src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
- src/ggrc-client/js/components/gdrive/tests/gdrive_picker_launcher_spec.js
- src/ggrc-client/js/components/object-mapper/object-mapper.js
- src/ggrc-client/js/components/tree/sub-tree-wrapper.js
- src/ggrc-client/js/components/tree/tree-item-base-vm.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/save_queue.js
- src/ggrc-client/js/tracker/actions.js
No possibility to track performance of some user scenarios
Added trackers for user scenarios
> GGRC-4970 Cover user scenarios with Google analytics

- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/models/save_queue.js
- src/ggrc-client/js/tracker/actions.js
Typos in the names of actions
Fixed typos
> QUICK-FIX Fix names of user actions in Google Analytics

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/test_my_work_page.py
> QUICK-FIX Update test to check default value in LHN

- src/ggrc-client/js/tracker/analytics.js
Currently we do not have possibility to know which branch(hash) was deployed in scope of metrics in Google Analytics   
Hash added as custom dimension to Google Analytics
> QUICK-FIX Add version's hash as custom dimension in Google Analytics

- src/ggrc/converters/snapshot_block.py
- src/ggrc/utils/__init__.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/data_platform/test_last_assessment_date.py
- test/unit/ggrc/converters/test_snapshot_block.py
Date is displayed in ISO format in export csv file/Google sheet for snapshots
Precondition:
Have an audit with control snapshot
1. Open Audit page > Controls tab
2. Export control snapshot and open it in Google sheet
3. Look at the 'Last Updated Date', 'Created Date', 'Last Assessment Date', 'Revision Date'
Display date in export csv file/Google sheet for snapshots in US format "mm/dd/yyyy".
Change the date format to US when exporting a snapshot.
> GGRC-5054 Change format data for snapshots in export csv file/Google sheet

- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/local_storage.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
The application doesn't support **background deletion** anymore.
Need to clean up unused code
Remove unneeded logic from `makeDestroy` function.
However, `makeDestroy` should be saved to avoid `createUpdateDestroyHandler` function call (`model.js` (can.js lib))
> GGRC-3535 Cleanup unused code managing background deletion

- src/ggrc/migrations/versions/20180517092933_70fdda308cb7_remove_mappings_between_documents_and_.py
We used to have Request model, which could have Comments with Attachments inside.
Since we migrated Requests to Assessments, the Attachments inside Comments became invisible (we don't have such feature for Assessments), but the data still remains in the database.
Now we're making Attachments a commentable first-class object, and 'old' Comments mapped to Documents should be removed.
We can't check it throughout UI, just in DB.
Add migration to delete all relationships between Documents and Comments
> GGRC-4075 Add migration to remove mapping Document-Comment

- .eslintignore
- .eslintrc.json
- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/bootstrap/wysihtml5.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/components/workflow/workflow_deactivate.js
- src/ggrc-client/js/controllers/approval_workflow_controller.js
- src/ggrc-client/js/controllers/dashboard_controller.js
- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js/controllers/workflow_page.js
- src/ggrc-client/js/ggrc_base.js
- src/ggrc-client/js/models/category.js
- src/ggrc-client/js/models/directive_models.js
- src/ggrc-client/js/models/local_list_cache.js
- src/ggrc-client/js/models/notification_config.js
- src/ggrc-client/js/models/recently_viewed_object.js
- src/ggrc-client/js/models/workflow.js
- src/ggrc-client/js/models/workflow_join_models.js
- src/ggrc-client/js/plugins/popover_template.js
- src/ggrc-client/js/plugins/wysiwyg.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
- src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
A lot of eslint warnings.
Fixed a few eslint rules for all codebase and excluded vendor folder.
~ -2k eslint warnings
> QUICK-FIX Fix eslint rules

- src/ggrc-client/js/models/mixins.js
```
Cannot read property 'issue_tracker' of undefined TypeError: Cannot read property 'issue_tracker' of undefined 
issue_trackerat u.initIssueTrackerForAssessment  (webpack:///js/models/mixins.js:333:21)
initIssueTrackerForAssessmentat Object.<anonymous>  (webpack:///js/models/mixins.js:287:17)
```
Use `attr` instead of pure properties of instance
> GGRC-5077 PROD errors - investigate&fix issues in issue tracker mixins

- src/ggrc/access_control/roleable.py
- src/ggrc/converters/handlers/evidence.py
- src/ggrc/models/evidence.py
- src/ggrc/models/mixins/base.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/test_csvs/assessment_with_evidence_url.csv
Evidence admin role is not set during the import.
1) Import assessment with evidence (URL)
2) Check that user is specified in "ADMIN" section at evidence info pane.
Add add_admin_role method to evidence model, call that method during the import
> GGRC-5069 Evidence created via import has empty mandatory admin field

- src/ggrc-client/js/components/related-objects/related-assessments.js
- src/ggrc-client/js/components/revision-log/revision-log.js
- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/models/person.js
- src/ggrc-client/js/tracker/actions.js
Added extra scenarios for Google Analytics
> GGRC-5087 Add extra scenarios for Google Analytics

- ._license_header_exceptions
- .eslintrc.json
- getReleaseNotesDate.js
- loaders/md-to-html.js
- loaders/parse-inner-links.js
- package-lock.json
- package.json
- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/components/page-header/page-header.mustache
- src/ggrc-client/js/components/release-notes-list/release-notes-list.js
- src/ggrc-client/js/components/release-notes-list/release-notes-list.mustache
- src/ggrc-client/js/components/release-notes-list/release-notes-list_spec.js
- src/ggrc-client/js/components/release-notes-list/release-notes.md
- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.mustache
- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
- src/ggrc-client/js/components/release-notes-modal/release-notes-modal.js
- src/ggrc-client/js/components/release-notes-modal/release-notes-modal.mustache
- src/ggrc-client/js/models/display_prefs.js
- src/ggrc-client/styles/_components.scss
- src/ggrc-client/styles/components/release-notes/_release-notes.scss
- src/ggrc-client/styles/modules/_menu.scss
- src/ggrc/settings/default.py
- src/ggrc/settings/testing.py
- src/ggrc/views/__init__.py
- webpack.config.js
TEXT:
https://docs.google.com/document/d/1Tm1nRVDIgUArjezZSnCvcwCm3gLcXdB6wRJKUaF6VUA/edit#
MOCK-UPS:
https://drive.google.com/corp/drive/folders/1p12yXPNpgokB71mCcf-nfiEDmDrJuBZ8
PROBLEM:
Users of GGRC are not aware about new features that are launched.
To solve this problem, we would like to show a list of updates in the latest release. This list should be shown right away when user comes to GGRC after release, but only once for each user. Also user should be able to find it in our app at any time.
SCOPE:
Show 'What's New?' pop-up once for a user, when he comes to GGRC after new version is released.
Show 'What's New?' pop-up, when user clicks on 'What's new' option in the header.
Have an possibility to update 'What's New?' text easily for each releases.
Add components …
> GGRC-4519/4924 What's New

- src/ggrc-client/js/components/rich_text/rich_text.js
- src/ggrc-client/js/components/rich_text/tests/rich_text_spec.js
Error is shown If copy paste empty html into rich text.
1) Have assessment with 'input' LCA
2) Type spaces into input field
3) Copy spaces into clipboard from input
4) Paste it into RichText as example into comment box
Actual result: JS error 'Uncaught TypeError: Cannot read property 'insert' of undefined' is shown. Rich text is broken.
Expected result: No error is shown. Rich text is available for editing.
If delta.ops.length is zero, return empty delta.
> GGRC-5060 Do no match url if no delta in rich-text

- src/ggrc-client/js/components/questions-link/questions-link.js
Hide 'Questionnaire' link on object info pane and in tree view if following objects are deprecated:
- products;
- systems;
- processes.
1) Have products, systems or processes.
2) See questionnaire link on info-pane and in tree-view
3) Change state of object to 'Deprecated'
Expected result: questionnaire link is not shown
See commits.
> GGRC-4736 Hide 'Questionnaire' link, if object is deprecated

- src/ggrc/models/hooks/issue_tracker.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
After assessment put last comment is sent to issue tracker. This is wrong.
PR is reverted.
> QUICK-FIX Revert PR 7595

- test/unit/ggrc/models/test_slugs.py
- test/unit/ggrc/utils/test_rules.py
- test/unit/ggrc_workflows/models/test_workflow.py
This is meant just to get a more readable test output when running unit
tests in a verbose mode.
Running unit tests in verbose mode makes them hard to read
run
cd test
nosetests -v unit
check the output
Add a more friendly docstrings to unit tests.
> QUICK-FIX Add unittest docstrings

- src/ggrc/models/reflection.py
- test/integration/ggrc/views/__init__.py
- test/integration/ggrc/views/test_get_attributes.py
* Allow user create custom role objects with Non-ASCII symbols.
* Fix backend.
Login as admin user and open Administration page. Add custom role field with a title using Non-ASCII symbols. Relogin or go to main page.
Change some strings from str to unicode.
> GGRC-4615 If user creates a custom role field with Non-ASCII symbols, it crashes the app and user gets an error

- src/ggrc/models/mixins/__init__.py
**Note: This is a partial PR for the specified ticket.**
Deprecating an object shows a sql warning.
launch a server with launch_ggrc
deprecate an objective or a section.
look at results
Extra: compare integration tests output
use the correct data type for last_deprecated_date
> GGRC-5132 Fix data type for last deprecated date

- src/ggrc/services/common.py
- src/ggrc/utils/__init__.py
- test/unit/ggrc/utils/test_util_functions.py
Duplication of straigtforward code.
Check that PUT and POST still work.
Move the validation logic into a decorator.
> QUICK-FIX Abstract Content-Type validator

- src/ggrc-client/js/components/sortable-column/sortable-column.js
- src/ggrc-client/js/components/sortable-column/tests/sortable-column_spec.js
- src/ggrc-client/js/components/tree/templates/tree-header.mustache
- src/ggrc-client/js/models/business_object_models.js
- src/ggrc-client/js/models/system.js
- src/ggrc-client/styles/components/tree/_tree-view.scss
As Questionnaire column contains only link and not sortable, sorting should be disabled.
Add 'disable_sorting' flag to columns configuration and prevent sorting when flag is true.
> GGRC-4709 Disable sorting for Questionnaire column for Product/System/Process in tree view

- src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache
JS error when attaching a file for dropdown LCA option
1. Create audit
2. Create assessment template with dropdown LCA that has some value with EVIDENCE FILE REQUIRED = yes
3. Generate assessment from this assessment template
4. Open generated assessment
5. Choose the value that requires evidence file
6. Attach file in the appeared popup
Use correct collection for evidence files.
> GGRC-5151 Use correct collection for evidence files

- src/ggrc/rbac/permissions_provider.py
Create ASMT takes about 9 sec in some cases. 
1) Create Program and Audit. 
2) Add many persons (about 100) as Auditors to that Audit. 
3) Login as one of the Auditors
4) Create Asmt login as one of that Auditors. 
Access_control_list isn't loaded eagerly for the audit that is why for each ACL instance SQLalchemy creates and run extra queries. 
I swap calls based on acl instances iteration to one exists sql call. 
Same problem exists for WF instances with checking permissions for Admin. I fix that issue here too.
> GGRC-5076 Check create permissions takes too much time

- src/ggrc/models/comment.py
- src/ggrc/models/mixins/with_evidence.py
- src/ggrc/models/object_document.py
Now relationships with comments, documents and evidences are provided in unperformant way (statistic below).
Before comments were obtained with query like:
```
SELECT comments.description AS comments_description, comments.id AS comments_id 
FROM comments, relationships 
WHERE %s = CASE WHEN (relationships.source_type = %s AND relationships.destination_type = %s) THEN relationships.source_id WHEN (relationships.source_type = %s AND relationships.destination_type = %s) THEN relationships.destination_id END AND comments.id = CASE WHEN (relationships.destination_type = %s) THEN relationships.destination_id WHEN (relationships.source_type = %s) THEN relationships.source_id END
```
It works about 0.18s in average on my machine
After relationship change SQL is the following:
```
SELECT …
```
> GGRC-5166 Change relationship for comments/documents/evidences

- bin/deploy
Help text for deploy script is incorrect.
Mistake in deploy help text is fixed.
> QUICK-FIX Fix deploy help message

- src/ggrc/models/hooks/issue_tracker.py
- test/integration/ggrc/integrations/test_issuetracker_issue.py
Issue is not updated if assessment's title has been updated.
Update assessment title. Issue title in issue tracker should be updated.
Issue title update included into issue update functionality.
> GGRC-4769 Update issue with assessment title

- src/ggrc-client/js/components/page-header/page-header.mustache
- src/ggrc-client/js/components/tooltip-content/templates/tooltip-content.mustache
- src/ggrc-client/js/components/tooltip-content/tests/tooltip-content_spec.js
- src/ggrc-client/js/components/tooltip-content/tooltip-content.js
- src/ggrc-client/js/entrypoints/dashboard/index.js
- src/ggrc-client/styles/_components.scss
- src/ggrc-client/styles/_mixins.scss
- src/ggrc-client/styles/components/feedback-link/_feedback-link.scss
- src/ggrc-client/styles/mixins/_text-overflow.scss
Add a limitation on name length of configurable button: 20 characters.
If the button name is more than 20 character, then truncate it and show tooltip with a full name on hover.
Apply changes for "Feedback" button.
1. Open any page, which contains header.
2. To show "Feedback" button, you should override `GGRC.config.CREATE_ISSUE_URL` and `GGRC.config.CREATE_ISSUE_BUTTON_NAME` fields. For example, you can open `feedback-link.js` and set fake data for these fields before `viewModel` initializing.
**Expected result**: If there is no free space for the text, then the full text should be showed using a tooltip.
Separate component was created, which contains logic for the overflow detection.
> GGRC-4927 Name length limitation of configurable button

- src/ggrc/converters/handlers/assessment_template.py
- src/ggrc/converters/handlers/custom_attribute.py
On generation Asmt from template import goes to long. The biggest part is the part responsible for  generation local CAVs. The reason is to get newly created CAD from DB during creation procedure. 
Try create Asmt via import with related Asm Temaplate with big amount of CAD.  
Don't get CADs on import from DB on Asmt creation and asked it once to the cache.
If new cads created during import procedure put newly created cads to cache.
> GGRC-5146 Some imports speedups (stop load CADS for Asm in its creation via import)

- src/ggrc-client/styles/components/release-notes/_release-notes.scss
In scope of the ticket it is necessary to apply the proper font size according to the mockup  provided by UX team.
1) Open "What's new" modal from header menu.
2) Look at the fonts.
> GGRC-5200 Change font styles for "What's new"

- src/ggrc/settings/default.py
Bump version from 1.11.0-Strawberry to 1.12.0-Strawberry.
> Bump version to 1.12.0-Strawberry

- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Add tests to check related issue functionality

- src/ggrc-client/js/application.js
- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/styles/_z_index.scss
- src/ggrc-client/styles/modules/_modal.scss
- src/ggrc-client/styles/modules/_tree-content.scss
- src/ggrc/assets/mustache/base_objects/tree_add_item.mustache
> QUICK-FIX Clean up unused global event handlers

- src/ggrc/migrations/utils/acr_propagation.py
- src/ggrc/migrations/utils/acr_propagation_constants_evidence_comments.py
- src/ggrc/migrations/versions/20180513125525_e6127a4956b1_add_evidence_comment_rbac_rule.py
- src/ggrc_basic_permissions/migrations/versions/20180513130906_f514d6d7a8cd_add_evidence_comment_rbac_rule.py
- test/integration/ggrc/access_control/acl_propagation/base.py
- test/integration/ggrc/access_control/acl_propagation/test_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
- test/integration/ggrc/access_control/acl_propagation/test_auditors.py
- test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
- test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
- test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
- test/integration/ggrc/access_control/rbac_factories/__init__.py
- test/integration/ggrc/access_control/rbac_factories/evidence.py
Evidence comments have no ACL propagation.
1) As assessment creator add evidence (URL) 
2) Write comment to created evidence
3) As admin add Another user (user2) with creator role to the given assessment
4) Go to attached evidence
Expected result: User2 can see comments.
Actual result: User2 can't see comments.
Update missing ACL propagation rules.
Add tests.
> GGRC-5064 evidence comment ACL propagation

- src/ggrc/query/my_objects.py
- test/integration/ggrc/services/resources/test_person.py
As a GGRC user I would like to see only objects that are directly mapped (related) to me on My Work page.
**AC1.**  Object(s) should be displayed on My Work page, if one of the following conditions is met:
1.  logged-in user presents in any Custom Role in object and this custom role is granted with READ or higher rights. See more details [here](https://docs.google.com/spreadsheets/d/1IkrTqdIh45N3v_bwYHkkZauJ8YPZvm-WkfegihIwo8A/edit#gid=1514189107)
2. logged-in user presents in Global Custom Attribute of Person type
**AC2.** Objects of all states should be displayed on My Work page. See more details [here](https://docs.google.com/spreadsheets/d/1IkrTqdIh45N3v_bwYHkkZauJ8YPZvm-WkfegihIwo8A/edit#gid=1527600527)
Create several tasks with different states for one user and see all of them show …
> GGRC-3687 Make task show on MyWork page despite its status

- src/ggrc/fulltext/mysql.py
- src/ggrc/models/hooks/acl/__init__.py
It's required to make logger better and log commit hooks separately 
Test that commit action not broken (just update some object via api)
Move index and acl propagation block in the scope of benchmark with statement.
> GGRC-5152 Benchmark indexing and ACL propagation separately - add logs

- src/ggrc_workflows/notification/data_handler.py
- test/unit/ggrc_workflows/notification/test_data_handler.py
**Actual Result:** Workflow info page is displayed if user clicks on cycle task in email
**Expected Result:** My Tasks tab should be displayed if user clicks on cycle task in email
1. Create repeat off workflow
2. Add a task to TG with due date tomorrow
3. Activate WF
4.1 Once got an email with daily digest click on cycle task title
4.2 Or open `ggrc-dev/_notifications/show_daily_digest`, then click on cycle_task title.
**Actual Result:** Workflow info page is displayed if user clicks on cycle task in email
**Expected Result:** My Tasks tab should be displayed if user clicks on cycle task in email
Changed old link to MyTasks page link for CycleTask notification.
> GGRC-4995 Notifications CycleTask link should point to MyTasks page

- src/ggrc/models/document.py
- src/ggrc/models/evidence.py
Slugged mixin extends Base mixing which already includes Identifiable.
This change just should not affect code execution. And the slugged mixin
is moved to the end because base mixin must be the last mixin of all
that contain eager_query.
Check that document object still works
remove redundant mixin.
> QUICK-FIX Remove redundant Identifiable mixing from document

- docs/source/contributing/performance.rst
Add basic documentation help for comparing and analyzing performance of our application.
> QUICK-FIX Add documentation for performance checks

- src/ggrc/services/resources/person.py
- test/integration/ggrc/services/resources/test_person.py
The count of cycle tasks is equal to sum of tasks that assigned to the user (both primary and secondary). 
1. Have a user with no tasks assigned
2. Create a workflow
3. Create several tasks in a task group for the workflow, put the user as a primary and secondary assignee
4. Activate the workflow
Expected result: the count of cycle tasks assigned to the user should be equal to sum of unique tasks assigned to the user
When selecting tasks by assignee return only unique task ids.
> GGRC-4976 The count of cycle tasks is equal to sum of tasks that assigned to the user (both primary and secondary).

- src/ggrc-client/js/components/tree/templates/tree-item.mustache
- src/ggrc-client/js/plugins/utils/state-utils.js
- src/ggrc/assets/assets.yaml
- src/ggrc/assets/mustache/documents/tree-item-attr.mustache
1. There is no status filter
2. Document title should be a link
3. Document type is displayed incorrectly (should be Reference URL instead of REFERENCE_URL.)
1. Add reference url and attach file to Control
2. Open document tab
> GGRC-5198 Fix documents tree view
