src/docbuilder/descriptors/service.py, src/ggrc/models/hooks/acl/program_roles.py, src/ggrc/models/snapshot.py
The only place where snapshotted_objects are currently used is in program roles propagation (handle_snapshots). I think it's not a problem if the call there lazy loads the snapshots, especially since @zidarsk8 is working to remove that code right now.
We are sending snapshotted_objects dict to the frontend even though it's not actually used there. On an audit with 3000 snapshots the dict takes a while to populate on the BE and parse on the FE.
Inspect any GET or query requests for audits. After this change is merged it should not include a list of snapshotted_obejcts anywhere.
Snapshotted objects are lazy loaded instead of eagerly loaded so that we load the data only when we access the snapshotted_objects property on the backend. The only place that I can find that does that is the …
=> GGRC-4584 Remove snapshotted_objects API property

src/ggrc/access_control/roleable.py, src/ggrc/builder/json.py, src/ggrc/models/audit.py, src/ggrc/models/hooks/acl/audit_roles.py, src/ggrc/models/hooks/acl/program_roles.py, src/ggrc/models/hooks/acl/relationship_deletion.py, src/ggrc/models/hooks/relationship.py, src/ggrc/models/proposal.py, test/integration/ggrc/access_control/test_roleable.py, test/integration/ggrc/proposal/test_proposal_acl.py
Loading the full access control list with all propagated roles is causing performance and memory issues on the backend.
n/a
We only need the full access control list for a limited amount of role propagation operations, but currently we load the full list for all objects even on GET request. 
Therefore it makes sense to lazy load the full list only when needed by role propagation. 
Note: Hopefully moving the role propagation code into sql statements will soon remove the need of loading full access control list. At which point the `full_access_control_list` property can be removed.
Loading an audit with 1000 assessments, 2000 regulations and 1000 controls (12119 access control list items, 11 of which were not propagated).
Before:
After:
=> GGRC-4582 Use the full access_control_list only where absolutely needed

src/ggrc/utils/referenced_objects.py, test/unit/ggrc/utils/test_referenced_objects.py
500 error appears when assessment id=116672 Change Log tab is opened.
Use any db dump which contains an assessment id=11667 (assessment was created on Feburary 22, 2017).
1. Log in as admin user and open assessment;
2. Once Assessment Info pane is opened, click Change Log tab .
No errors should be shown while opening change log tab.
Some of the revisions point to ObjectDocument model, which has been removed. They have to be stored in the db for history purposes. To support this case some checks if table exists were added to `referenced_objects` module.
=> GGRC-4488 Fix revisions history for ObjectDocument

src/ggrc/models/mixins/base.py, test/integration/ggrc/converters/test_import_assessments.py
it costed me ~300 queries locally to generate two Assessments in Audit 8 from our qa db.
I've investigated the issue, and found a lot of similar queries to access_control_list table.
Part of them were conducted to get the created_at/updated_at values from the already created ACL records, which are already in the session. But the created_at/updated_at default values are set by the database thus the session didn't have them.
1. Have audit with at least 2 controls snapshots
2. Create Assessment template
3. Generate assessments based on 2 controls snapshots and assessment template
4. Look at the time of assessments generation in Dev tools > Network
I changed the ChangeTracked mixin to set the default values in python, so SQLalchemy does not have to go for them to the db.
It allowed to reduce …
=> GGRC-2174 Improve performance for assessment generation

src/ggrc/utils/revisions_diff/applier.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/proposal/api/test_cads.py
FE is moved to the new API, so this old-style functionality have to be removed.
Click through the version history tabs (after object creation / update / restoration).
Old-style functionality has been removed as well as appropriate tests.
=> GGRC-4492 Revert CAVs proposal generation for old style api

src/ggrc/models/hooks/comment.py
The comment ACL entry should be done before by our post signals before
any sqlalchemy events are triggered. This way we can ensure that all
triggers will contain the needed data.
Since the new hook is triggered on a collection of objects the acl
setter is also updated to use the full ORM objects and to avoid nested
loops through all roles. This also ensures we set the correct ORM object
for ac_role instead of just its id.
Check that comments still work on all objects that have them, and that the current user is always set as the comment author.
Make sure that the label for current user role on assessments still works as well (assignees should have assignees marked in the comment next to their email).
Change hook to use collection_posted. I have checked that no flushes are called before …
=> GGRC-4585 Update comment acl hook

Dockerfile-selenium, src/ggrc-client/js/entrypoints/dashboard/bootstrap.js, src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js, src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.mustache, src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-log.js, src/ggrc/templates/layouts/dashboard.haml
Need to enable Issue tracker for all assessments in scope of Audit.
Script for run into browser console that loads all related assessments and enable issue tracker where it not enabled.
**Steps:**
1. Open Audit page
2. Open Chrome DevTool
3. Run `GGRC.enableIssueTracker()` in the console
=> GGRC-4579 Script for bulk enable of issue tracker

src/ggrc/models/hooks/assessment.py, test/integration/ggrc/models/hooks/test_assessment.py
**NOTE:** We need to decide if this is going in as a hotfix or in 1.6.0
Generating assessment templates failed when revision content does not include the test_plan key.
1. Create an object and make sure it's revision doesn't have a test_plan (you might have to do it manually).
2. Create a Program -> Audit -> Assessment Template (make sure `Copy Assessment Procedure from mapped object` is checked)
3. Generate an assessment using the template from 2. and an object from 1.
Make sure we retrieve the test plan with `get`, avoiding the possibility of a key error.
=> GGRC-4653 Fix copy_snapshot_plan when no test_plan in revision content

src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/models/cycle_task_group.py
Because access_control_list entries were being lazy loaded sending a PUT
request to a single cycle task produced a big amount of
access_control_list queries. Locally this change reduces PUT response
times from 8s to 4s on a workflow with 1000 tasks.
Before:
After:
The number of queries went down from 2000 to 150.
Create a workflow with a big amount of tasks (at least 1000). Observe the response times of PUT requests on cycle tasks.
We make sure access_control_list items of cycle_task_group_tasks are not lazy loaded in the cycle indexer. 
**Note**: I don't believe this will fix the main issue that the users are experiencing (10-20 minute wait times for saving tasks). I think the main issue is due to how we do indexing where every cycle task PUT triggers the reindexing of the cycle which …
=> GGRC-4281 Reduce the number of queries on cycle task PUT

src/ggrc/models/custom_attribute_definition.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/proposal/api/test_cads.py
Checkbox is shown as proposed value if user is not proposed to change it
1. Create a control as Admin user
2. Log As global Reader and propose to change GCAs values: e.g. date, rich text, checkbox
3. As Admin Apply changes
4. As Global Reader propose to change desccription
5. As Admin open Change Proposals tab and look at the checkbox: is shown as checked
Actual Result: Checkbox is shown as proposed value if user is not proposed to change it
Expected Result: If checkbox was not changed, it shouldn't shown up in change proposals tab and in comparison window
It doesn't matter in what format FE send value to checkbox cav, it should be converted to format valid for saving for that data and only after that it should be compared with value in latest revision.
=> GGRC-4227 Checkbox is shown as proposed value if user is not proposed to change it

src/ggrc-client/js/components/import-export/download-template/download-template.js, src/ggrc-client/js/components/import-export/download-template/download-template.mustache, src/ggrc-client/styles/modules/_import-export.scss
Selected items must be reseted after close of download templated modal
1. Open Import page
2. Invoke Download Templates modal
3. Select a few items in dropdown
4. Close modal and open again
Actual result: items still selected
Expected result: dropdown must be clean
Items is reseted after close the modal
=> GGRC-4460 Reset selected items after close download templates popup

src/ggrc/snapshotter/__init__.py, src/ggrc/snapshotter/helpers.py, test/integration/ggrc/snapshotter/test_snapshoting.py
The relationships created between original objects and audits were done
as a hack to ensure the unified mapper showed already created snapshots
as mapped. This issue was later fixed on the front-end but the legacy
code was never removed. Now the code just presents a performance
degradation and brings no actual value to our app.
Second thing to consider is that the relationships are generated ONLY on
audit creation from the objects mapped to the programs. Any additional
snapshots that are created and mapped to the audit at later time, do not
have these relationships. And since half of the snapshots have them and
half don't without showing any bugs in our app, we can safely say that
removing this code should not cause any regressions. Any bugs that would
be caused by this must already exist …
=> GGRC-4655 Remove redundant relationship creation

src/ggrc-client/js/controllers/summary_widget_controller.js, src/ggrc-client/styles/_colors.scss
Set #704C70 color for Deprecated/Inactive states.
=> GGRC-4381 Change color for Deprecated state

src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js, src/ggrc-client/js/components/workflow/workflow-activate.js, src/ggrc/assets/mustache/dashboard/object_nav_actions.mustache, src/ggrc/assets/mustache/workflows/info.mustache, src/ggrc_workflows/models/workflow.py
When loading a workflow with a lot of task groups and task group tasks, a lot of requests are made to the BE to figure out if we can display the "manually start a cycle" button and "activate workflow" buttons. These requests need to be removed.
Have a Workflow with 100 task groups and 1000 tasks and see the network tab.
Instead of calculating whether we can start a cycle on the FE we do this on the BE.
Before:
After:
=> GGRC-4501 Improve workflow page loading

src/ggrc/models/relationship_helper.py, test/integration/ggrc/services/test_query/test_relevant.py
The propagated roles are only used to determine if a user has access to
a given object or not. They are not user visible roles and should not be
used in any user visible filter. The check for parent_id ensures that
only base roles are used by the query.
Any person with a propagated role to the assessment will see that assessment on their "my assessments" page.
> Steps to reproduce,
>  * Be one of the following roles:
>  ** Audit captain
>  ** Auditor
>  ** Program Editor
>  ** Program Reader
>  ** Program Admin
>  * inside the audit, create an assessment, but make sure you have no role on that assessment
>  * Go to my assessments page
> 
> Expected: You should not be able to find that asssesssment there
> 
> Actual: Person is able to see an assessment there even when they have no actual …
=> GGRC-4659 Ignore all propagated roles on relevant filters

docker-compose-testing.yml, docker-compose.yml
For safety reasons it's better to not expose local environment to external ports without proper security level.
Local environment works as expected.
It's impossible to access local environment from external machine.
Docker binding changed to localhost only.
=> GGRC-4670 Don't expose dev environment to external ports

src/ggrc-client/js/components/import-export/import.js, src/ggrc-client/js/components/import-export/templates/import-error.mustache, src/ggrc-client/js/components/import-export/test/import_spec.js
Import with clean cookie case: "Uncaught TypeError: Cannot read property 'message' of undefined" error message is displayed while importing a csv file
1. Import task group task csv template
2. Fill out the required fields and save
3. Open dev tools and clean up cookies
4. Import csv file
Actual Result: "Uncaught TypeError: Cannot read property 'message' of undefined" error message is displayed while importing a csv file
Expected Result: no errors should be shown while importing
If we remove cookies, user becomes unauthorized for backend, and it tries to redirect user to external login page, but it falls (CORS) because original request was made by JS, not user.
The solution is showing correct error message.
=> GGRC-4518 Add general error handler to import

src/ggrc-client/js/components/revision-log/revision-log.js, src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
Revision compare on change log marks `list like` fields as dirty even if nothing was changed in them (for example `assertions`, `categories`, `ACR`s)
1) Make changes where you add allot of acr users (for example 5) also make changes that will change allot of mapping list fields ( on control they are Assertions and  Categories) 
2) change any filed in the object (for example description) 
You should see only this change in `change log` and don't see changes in list like fields.  
Order and compare list like fields base on it's order.
=> GGRC-4293 People are shown up as a change if no changes were made.

src/ggrc/models/relationship_helper.py, test/integration/ggrc/services/test_query/test_relevant.py
The propagated roles are only used to determine if a user has access to
a given object or not. They are not user visible roles and should not be
used in any user visible filter. The check for parent_id ensures that
only base roles are used by the query.
Any person with a propagated role to the assessment will see that assessment on their "my assessments" page.
> Steps to reproduce,
>  * Be one of the following roles:
>  ** Audit captain
>  ** Auditor
>  ** Program Editor
>  ** Program Reader
>  ** Program Admin
>  * inside the audit, create an assessment, but make sure you have no role on that assessment
>  * Go to my assessments page
> 
> Expected: You should not be able to find that asssesssment there
> 
> Actual: Person is able to see an assessment there even when they have no actual …
=> GGRC-4659 Ignore all propagated roles on relevant filters 

src/ggrc/snapshotter/__init__.py, src/ggrc/snapshotter/helpers.py, test/integration/ggrc/snapshotter/test_snapshoting.py
The relationships created between original objects and audits were done
as a hack to ensure the unified mapper showed already created snapshots
as mapped. This issue was later fixed on the front-end but the legacy
code was never removed. Now the code just presents a performance
degradation and brings no actual value to our app.
Second thing to consider is that the relationships are generated ONLY on
audit creation from the objects mapped to the programs. Any additional
snapshots that are created and mapped to the audit at later time, do not
have these relationships. And since half of the snapshots have them and
half don't without showing any bugs in our app, we can safely say that
removing this code should not cause any regressions. Any bugs that would
be caused by this must already exist …
=> GGRC-4655 Remove redundant relationship creation 

src/ggrc_basic_permissions/__init__.py
Fetching all ACL records from the database so that we can perform permission checks on the BE and FE is very slow. We will be removing this query here: https://github.com/google/ggrc-core/pull/7398, but this won't make it into 1.6.1 and perhaps also not into 1.7.0 (depending how busy I am with other things). So until we remove this query altogether we can at least make it slightly faster.
Make sure permissions still work correctly.
Instead of returning all the acl rows we group them together by
object_id and object_type. This puts additional load on the mysql server
but drastically reduces the amount of data transfared and the amount of
data python needs to crunch through.
This reduces the amount of rows for my user on ggrc-qa from ~70k to ~20k and reduces the time by a few seconds. …
=> GGRC-4686 Reduce the amount of rows retrieved by the acl query

src/ggrc/models/hooks/acl/audit_roles.py, test/integration/ggrc/services/test_query/test_basic.py
Currently the only autoassigned role we have is when creating an audit captain. Those get assigned program editor roles in our current app.
The implementation for this is badly mixed up with internal roles propagation and this is now blocking the performance 3.5 epic.
Instead of refactoring the code, Akhil Parekh approved that we can remove this link. This should also make role assignments more explicit and easier for users to understand.
To test this:
- Add a new audit captain without any program role
- make sure they do not get program editor role.
Test updates and code removal to match the new spec.
=> GGRC-4680 Remove Audit captain automatic role assignment to program editors

src/ggrc/data_platform/computed_attributes.py, test/integration/ggrc/data_platform/test_last_assessment_date.py
> When generate assessment error message appears and page is reloading.
> New assessment appears in a corresponding tab, but log contains the following error.
> 
> ERROR    2018-03-16 13:54:15,354 ggrc.models.background_task Task failed
> Traceback (most recent call last):
>   File "/vagrant/src/ggrc/models/background_task.py", line 151, in decorated_view
>     result = func(task)
>   File "/vagrant/src/ggrc/views/__init__.py", line 95, in compute_attributes
>     computed_attributes.compute_attributes(revision_ids)
>   File "/vagrant/src/ggrc/data_platform/computed_attributes.py", line 674, in compute_attributes
>     attribute_groups = group_revisions(attributes, revisions)
>   File "/vagrant/src/ggrc/data_platform/computed_attributes.py", line 201, in group_revisions
>     key = …
=> GGRC-4705 Fix computed attributes

src/ggrc/models/program.py, test/integration/ggrc/models/test_program.py
When the UI PUTs a Program that has Audits with empty `audits` field, all Audits in it get removed.
1. Create a Program, open it in Tab#1.
2. Open the same Program in Tab#2.
3. Create an Audit, open it in Tab#3.
4. In Tab#1, update any ACL field on the Program.
5. Refresh Tab#3.
Expected result: the Audit is there.
Actual result: the Audit is removed, 404 is returned.
`audits` field is read-only now. It will be removed altogether in a later release.
=> GGRC-4713 Fix accidental Audit deletion on Program PUT

src/ggrc/models/hooks/issue_tracker.py
Redundant list() conversion is removed.
=> GGRC-4751 Improve cc list generation function

src/ggrc/converters/snapshot_block.py, test/integration/ggrc/converters/test_export_snapshots.py
Snapshot export fails when exporting acl entry of a deleted role.
Steps to reproduce
- Create a new user role on control.
- Create a control with that user.
- Make a snapshot of that control on some audit.
- Confirm that the user is shown under that role on the snapshot.
- Delete that role.
- Export snapshots
Expected: Snapshot export should work, but that role is not displayed.
Actual: Server error appears.
Note: The expected result is actually not fully correct, but we are trying to fix snapshot exports here and not reorganize how we store revisions, In order for that role to still be visible on snapshots after it's deleted, is a whole different epic in itself.
Add checks if the ACR still exists.
=> GGRC-4740 Fix snapshot export with deleted ACR

src/ggrc/models/revision.py, test/unit/ggrc/models/test_revision.py
Our revisions should not store internal ACL entries and our code should not use them directly.
Due to older bugs that are already fixed, some older revisions can still contain internal acl entries. We must ensure that those are properly filtered out from the content before the rest of the code might accidentally use them.
no actual steps, but just check the revision content of some object with internal acl entries.
Revisions should not contain any information on propagated roles. As
such, we should filter out all instances that could be contained in
older revisions, in order for our code to work correctly.
=> GGRC-4739 Fix handling internal roles in revisions

src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/revision.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/services/test_custom_attributes.py
Add default_value to CADs api 
raw api calls to BE and check info about default_value for CADs
1) send default_value to FE
2) log it in revisions
3) populate it for older revisions
=> GGRC-4697 Add default value for each custom attribute definition

src/ggrc/models/exceptions.py
The translate message just strips out parts of the message so that it
can be displayed on the front-end, but the exception itself is not shown
anywhere. This change makes it a lot easier for developers to track down
errors cause the request to fail.
Additionally, without this our logs would not log any errors, just
warnings when an API request fails due to duplicate key.
The translate message just strips out parts of the message so that it
can be displayed on the front-end, but the exception itself is not shown
anywhere. This change makes it a lot easier for developers to track down
errors cause the request to fail.
Additionally, without this our logs would not log any errors, just
warnings when an API request fails due to duplicate key.
- use ggrc-qa database from …
=> QUICK-FIX Add extra logging on API exceptions

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc/assets/mustache/assessments/header.mustache
Currently it's possible to move an archived assessment to:
1. Deprecated state
2. Not Started state if the assessment was deprecated before making it archived (I found this issue during the testing of the case with deprecated state. The details about this issue were shared with @AlexNo and I've got confirmation from Alex to add the fix for this case into this pull request)
Case with Deprecated state:
1. Have an audit with created Assessment
2. Audit and Assessment are archived
3. Navigate to Assessment Info pane and move it to Deprecated state
Actual Result: User is able to move assessment to Deprecated state if Assessment is archived
Expected Result: User should not be able to move assessment to Deprecated state if Assessment is archived
Case with Not Started state:
1. Have an audit with …
=> GGRC-3875 Deny possibility to move archived assessment to Deprecated or Not Started state

src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js, src/ggrc-client/js/components/tests/cycle-task-actions_spec.js, src/ggrc-client/js/components/tree/sub-tree-item.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js, src/ggrc-client/js/components/workflow/tests/workflow-helpers_spec.js, src/ggrc-client/js/components/workflow/workflow-helpers.js, src/ggrc-client/js/models/cycle_models.js
There are a lot of requests, which are occurred after Cycle Task editing. 
1. Open any Cycle Task from workflow page / My work page.
2. Click edit button from info pane / subtree item menu.
3. Open Dev Tools on the Network page.
4. Click Save & Close button. 
Expected result: Should be removed all necessary requests.
We have several places, where we can edit Cycle Task though edit modal.
In this case we should use following request:
- PUT request for save changes.
- GET for getting an updated count of Cycle Tasks. It can be changed, if we try to unassign current user from the editing task (Task Assignee or Secondary TA).
- GET for getting an updated permissions. The reason is the same as from the previous point.
In this case we should use following request:
Additionally to previous …
=> GGRC-4660 Remove redundant requests on editing a cycle task

src/ggrc-client/js/plugins/ggrc-gapi-client.js, src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
"Uncaught TypeError: Cannot read property 'getToken' of undefined" error occurs if open control/Assessment in a separate tab
1. Login as admin user
2. Open https://ggrc-dev.appspot.com/regulations/4517#!info_widget
3. Go to Controls tab and open control "test control1" in a separate tab
*Actual Result:* "Uncaught TypeError: Cannot read property 'getToken' of undefined" error occurs while control is opened in a separate tab
*Expected Result:* no errors should be shown
FE tries to use gapi client library before it become loaded.
The solution is wait for deferred object representing gapi library and execute code after library is loaded.
=> GGRC-4786 Fix gapi client loading racing issue

src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
We seem to have concurrency issues when creating an approval workflow because we try to create both task_group_task and task_group_object at the same time.
>  1. Open [https://ggrc-test.googleplex.com/controls/6585#!info_widget] link
>  2. On the Control Info page click Submit for review
>  3. Assign a reviewer and set a due date
>  4. Click Submit button
>  *Actual Result:* (OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction') error occurs while submitting for review 
>  *Expected Result:* no errors should be displayed while submitting for review
We make sure we only send the task_group_object request after the request to create task_group_task has finished.
=> GGRC-4640 Don't use concurrency when creating an approval workflow

src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache, src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js, src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.mustache, src/ggrc/assets/mustache/assessments/header.mustache
When user add evidences assessment is moved into 'In Progress' state, so if user add some evidences and then clicks 'Complete' button before evidences saving response, assessment will be moved back 'In Progress' state.
1. Open an Assessment which is 'In progress'
2. Perform one of the following steps:
- attach evidence and click on Complete button while changes are saving;
- add evidence URL and click on Complete button while changes are saving;
3. Look at the state of the Assessment
**Actual Result:** If user clicks complete button before changes were saved, assessment is moving to In review state and then back to In progress.
**Expected Result:** Complete button should be disabled before attachment and evidence url are not saved.
Define `isPending` flag which …
=> GGRC-4715 Disable "Complete" button if evidences is updating

src/ggrc-client/js/plugins/utils/snapshot-utils.js, src/ggrc/assets/mustache/base_objects/general-page-header.mustache, src/ggrc/assets/mustache/snapshots/dropdown_menu.mustache, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/element/widget_info.py
Unmap button is missing on the snapshot's info pane under Global Creator as Program Reader and auditor in audit
1. Have program, control, audit
2. Map GC to program and grant PR role 
3. Assign Global Creator as auditor to audit
4. Log as auditor (globcreator@gmail.com (engage007) and open audit page
5. Create Assessment and map control snapshot to assessment
6. Go to the Assessment info page > controls tab
7. Navigate to control's info pane > 3 bb's menu: 'unmap' button is not displayed
Actual Result: Unmap button is missing on the snapshot's info pane under Global Creator as Program Reader and auditor in audit
Expected Result: Unmap button should be displayed on the snapshot's info pane under Global Creator as Program Reader and auditor in audit
1) Check …
=> GGRC-3358 Fix snapshot 3bb menu

src/ggrc/models/relationship.py, test/integration/ggrc/api_helper.py, test/integration/ggrc/models/test_issue.py, test/integration/ggrc/services/test_response_codes.py
When a client POSTs a Relationship between a deleted object and anything, the backend responds with HTTP500 instead of HTTP400.
1. Create a Control.
2. Create another Control.
3. Delete one of the Controls.
4. POST a Relationship between the two Controls manually.
Expected result: HTTP400 is returned.
Actual result: the BE crashes with HTTP500.
`None` is now handled in Relationship validator.
=> GGRC-4758 Handle deleted object mapping

src/ggrc_basic_permissions/roles/Creator.py, src/ggrc_basic_permissions/roles/Editor.py, src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc_basic_permissions/test_acr.py
ACR should be readable over api. Current functionality is required for GGRCQ integration for create Product/Process/System.
1) Log in as Global Creator user.
2) Run following request:
GET https://your_server/api/access_control_roles?object_type=product
makes ACR readable for any user role
=> GGRC-4801 Access Control Roles GET doesn't return object type roles if user if Global Creator

src/ggrc-client/js/components/assessment/attach-button.mustache
There is wrong message on assessment page if you cancel gDrive authorization.
1) Create a program.
2) Create an audit and while creating assign audit folder with the access of a current user to the folder.
3) Go to the audit page.
4) Create assessment.
5) Clean cookies.
6) Navigate to assessment's info pane and look at the evidence field
Actual Result: "More Info error" is shown while audit folder is assigned
Expected Result: If audit folder is assigned and a user has an access to the folder no error is shown. Evidences should be attached and displayed on Assessment's Info pane properly.
- Authorization pop-up should be automatically opened, if user opens assessment info pane/page, when cookies are cleaned up.
- If authorization pop-up is closed, then display message …
=> GGRC-1956 Add authorize link for attach-button

src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/controllers/tests/modals_controller_spec.js
If close modal during loading, script error appears.
When all resources are loaded for modal, it is painting but the element is already destroyed in this case, so error occurs.
1. Open any program page;
2. Add tab > Objective;
3. Click Map button > Create and map a new object;
4. While modal window is loading click 'x' button (or press ESC button on keyboard).
Actual Result: "Uncaught TypeError: Cannot read property 'find' of null" error occurs if close Add New object popup while a window is loading.
Expected Result: no errors should be shown.
**NOTE:** If you are having problems with reproducing this issue (modal with spinner disappear very quickly), wrap `userFetch` deferred (line 107) in setTimeout.
Do not call `after_preload` function it there is no modal element.
=> GGRC-4514 Check existence of modal after loading

src/ggrc-client/js/apps/workflows.js, src/ggrc-client/js/controllers/modals/approval-workflow-modal.js, src/ggrc-client/js/controllers/tests/approval-workflow-model-helper_spec.js, src/ggrc/assets/mustache/base_objects/approval_link.mustache
After we removed related_sources/related_destinations (https://github.com/google/ggrc-core/pull/7382) approval workflow buttons no longer appeared correctly. We were relying on related_destinations to fetch all tasks in the `approval_tasks` mapping. 
1. As admin user open My work page > Controls tab
2. Open any control in tree view 
3. Click 'Submit for review' link, assign a person, set a date and click Save button
4. Look at the Object review: Decline/Apply buttons are not displayed
Actual Result:
Apply/ Decline buttons are not displayed after assign a person for review;
'Here' link is not displayed screenshot-2.png
Expected Result: Apply/ Decline buttons should be displayed after assign a person for review. Admin user should be able to see Decline/Apply buttons …
=> GGRC-4798 Fix approval workflow buttons

src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc_workflows/__init__.py
**Before this PR changes:**
1. On CycleTask PUT some data was changed. 
2. Then `db.session.commit` was [invoked](https://github.com/google/ggrc-core/blob/dev/src/ggrc/services/common.py#L591). 
3. Cause CycleTask was changed then [hook on update](https://github.com/google/ggrc-core/blob/dev/src/ggrc/fulltext/listeners.py#L19) was invoked. 
4. Then reindexing procedure was started [here](https://github.com/google/ggrc-core/blob/dev/src/ggrc/fulltext/mysql.py#L226). 
5. Then on CycleTask `model_put_after_commit` CycleTaskGroup dates are changed [here](https://github.com/google/ggrc-core/blob/dev/src/ggrc_workflows/__init__.py#L565).
6. It leads to that CycleTaskGroup marked as dirty in session. On next [commit](https://github.com/google/ggrc-core/blob/dev/src/ggrc_workflows/__init__.py#L566 …
=> GGRC-4703 Remove redundant indexing on CycleTask PUT

src/ggrc-client/styles/components/form/_ggrc-form.scss
Long title of GCA is not cut off in Assessment modal window
2. Open Custom Attributes tab and add GCA with 'text' type with long title to Assessment
3. Open any Audit page
4. Invoke New Assessment modal window
**Actual Result:** Long title of GCA is not cut off in Assessment modal window
**Expected Result:** Long title of GCA should be cut off in Assessment modal window
Fix css styles
=> GGRC-4596 Cut off long GCA titles in modals

src/ggrc-client/js/components/multi-select-label/multi-select-label.js, src/ggrc-client/js/components/multi-select-label/multi-select-label_spec.js, src/ggrc-client/js/models/assessment.js, src/ggrc-client/js/plugins/tests/label-utils_spec.js, src/ggrc-client/js/plugins/utils/label-utils.js
do we have requirements about sorting of labels?
Default sorting of labels right now - by id (created date)
Because currently we have a bit strange behaviour after adding the label from suggestions list.
Open Assessment info pane that have a couple of labels
Remove 1st and 2nd labels and add them again (labels showing in end of the list)
Close and open info pane one more time
Labels are sorted by default
the simplest way will be sort labels by `created_at` field immediately after adding. It won't confuse the users, when sorting was changed after they added some labels(new labels in end of the list) and opened Assessment again(labels sorted by created_at field).
Open any Assessment
1. Sort labels ascendingly by alphabet.
2. Apply sorting right away on saving.
=> GGRC-4094 Sorting of labels for Assessment

src/requirements-selenium.txt, test/selenium/conftest.py, test/selenium/pytest.ini, test/selenium/src/lib/page/export_page.py, test/selenium/src/lib/utils/selenium_utils.py
Running Chrome in headless uses leads to a bit smaller CPU and memory usage.
I didn't yet check how much benefit this provides in our case but I think it would be better to merge it as it's easy to turn it off via specifying `--headless=False` in pytest.ini`.
Selenium tests' run time comparison with other jobs (from HTML reports):
This PR: 2240, 2135, 2140, 2220, 2540, 2580 seconds
Other PRs with passed tests: 2185, 2300, 2710, 2225, 2555, 2600, 2400, 2750, 2200, 2320, 2160 seconds
=> QUICK-FIX Use headless chrome in Selenium tests

src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.mustache, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js
Need 'is empty' as an advanced search option.
=> GGRC-4626 Add 'Is empty' option to advanced search

test/integration/ggrc_basic_permissions/test_cads.py
Just cover permissions for cads collection api by integration tests.
=> GGRC-4814 add permission tests to CADs

src/ggrc-client/js/models/section.js, src/ggrc/assets/mustache/base_objects/info.mustache, src/ggrc/assets/mustache/sections/modal_content.mustache
'If statement' should be removed from info.mustache in scope of GGRC-4823
Add "Effective Date" and "Last deprecated Date" fields for Section object
A1. 'Stop Date' field isn't needed for Section object any more. Instead of 'Stop Date' we ned to add 'Last Deprecated Date' field.
AC2. Add new attribute 'Effective Date' for Section object.
AC3. Allow user to import 'Effective Date' for Section object.
AC4. Allow user to import / export 'Effective Date' / 'Last Deprecated Date' for Section object.
AC5. Allow user to sort sections by 'Effective Date'.
AC6. Allow user to sort sections by 'Last Deprecated Date'.
AC7. Allow a user to filter Sections by 'Effective Date'.
AC8. Allow a user to filter Sections by 'Last Deprecated Date'.
AC9. System should auto populate …
=> GGRC-4422 Add Effective and Last Deprecated dates to Section

src/ggrc/models/comment.py, test/integration/ggrc/models/mixins/test_commentable.py
Commentable objects like Assessment have extra comments in `comments` property. This issue leads to creation of huge amount of data in `fulltext_record_properties`. Commentable objects (that even don't have any comments) have concatenated comments from other objects there. It takes significant amount of memory and extra time for reindexation.
0. On a clean DB (the issue depends on object ids)
1. Create two Assessments.
2. Write one comment for each Assessment.
3. In Python REPL, run `from ggrc import app ; from ggrc.models import all_models ; print all_models.Assessment.query.first().comments`
Check source and destination types for relationships with comments.
=> GGRC-3488 Correct comments relationship in Commentable mixin

test/selenium/src/lib/custom_pytest_scheduling.py, test/selenium/src/tests/test_snapshots.py
"_send_tests" is executed from pytest-xdist's "schedule" method.
It contains the following code:
```python
initial_batch = max(len(self.pending) // 4, 2 * len(self.nodes))
nodes = cycle(self.nodes)
for i in range(initial_batch):
self._send_tests(next(nodes), 1)
```
This causes tests too many tests to be scheduled to destructive node.
=> QUICK-FIX Prevent unequal load on pytest-xdist's nodes

src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc-client/styles/modules/_modal.scss
If user added a new person to custom role field, it is not colored in Comparison window 
1. Open any program page
2. Create a new control and audit
3. Update control: add a person to 'Primary contacts' 
4. Open audit page > Controls tab
5. Expand Info pane and click 'Get the latest version' link
*Actual Result:* 
- new added person is not colored that it was added
*Expected Result:* If user added a new person to custom role field, it should be colored in the comparison window
Check whether there are empty groups, if yes - highlight them.
=> GGRC-4845 Highlight empty person groups in revision comparer

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc-client/js/plugins/tests/utils/deferred-transaction-utils_spec.js, src/ggrc-client/js/plugins/utils/deferred-transaction-utils.js
LCA changes and state change of assessment send in different requests, it is generates conflict errors.
1. On the audit page create assessment 
2. Navigate to assessment's info pane and fill any CA
3. While changes are saving click Complete button
Steps for GGRC-4513:
1. Open any audit page with a control snapshot
2. Create Assessment template with mandatory custom attribute of text type.
3. Generate assessment based on control snapshot and assessment template
4. Expand Assessment Info pane and add a verifier
5. Select comment option from dropdown CA and leave a comment > Save
6. Type a text into text CA click on 'Complete' button
7. Click Edit Answers button, confirm changes and remove values from custom …
=> GGRC-1920/4513 Synchronize assessment "Complete" button with LCA changes

src/ggrc-client/js/components/dropdown/dropdown.js, src/ggrc-client/js/components/dropdown/dropdown.mustache, src/ggrc/assets/mustache/controls/modal_content.mustache
Propose button is enabled if click Hide all optional fields.
1. Open any Control Info page
2. Click on Propose Changes
3. Click on Hide optional fields button
4. Look at the Propose button: is enabled but no changes were made
**Actual Result:** Propose button is enabled if click Hide all optional fields
**Expected Result:** Propose button should be disabled if click Hide all optional fields and if no proposal were made by user
If `tabindex` is set on can component, canjs adds additional property to the instance (in case with control dropdown `"-1":"14"`) after element hiding and setting `tabindex="-1"`
=> GGRC-4779 Set tabindex on select tag instead of custom component

src/ggrc/integrations/integrations_errors.py, src/ggrc/integrations/issues.py, src/ggrc/integrations/utils.py, src/ggrc/models/hooks/issue_tracker.py, test/integration/ggrc/integrations/test_issuetracker_issue.py, test/unit/ggrc/integrations/test_utils.py
Cron job to sync Assessments status to IssueTracker failed to complete because of rate limit on API side.
Run Cron job to sync Assessments status to IssueTracker and check it completes successfully.
Handle HTTP 429 error in Cron job properly and re-try multiple times with some back off period. There is also a need to not disable Issue Tracker integration for an Assessment if issue update fails because rate limit.
=> GGRC-4782,4783 Amend IssueTracker cron job to handle rate limit

src/ggrc/converters/base_block.py, src/ggrc/converters/snapshot_block.py, test/integration/ggrc/data_platform/test_last_assessment_date.py
Last assessment date is not shown when exporting control/objective snapshot to csv file. 
1. Have control/objective snapshot with last assessment date on the audit page 
2. Export control/objective snapshot form the audit page 
3. Open csv file and look at the last assessment date column: Last assessment should be shown
Since the last assessment date presents in attributes of a snapshot, we could access it when forming a content during csv export.
=> GGRC-3367 Last assessment date is not shown in csv file after exporting Control/Objective snapshots

src/ggrc/models/hooks/issue_tracker.py, test/integration/ggrc/integrations/test_issuetracker_issue.py
Issue tracker status should have a valid value. Now it is always changed to `ASSIGNED`.
Change assessment assignee and status.
Issue status should be changed in according to the rules:
Not Started --> Assigned
In Progress --> Assigned
In Review --> Fixed
Rework Needed --> Assigned
Completed --> Fixed (Verified)
Completed (no verification) --> Fixed (Verified)
Deprecated --> Won't Fix (Obselete)
The line that updates assessment status to `ASSIGNED` on assessment update and assignee change removed.
=> GGRC-4863 Fix issue status update

src/ggrc/migrations/versions/20180327141151_7c9d15c78b0f_add_is_external_default_value.py
The is_external field has a default value on ORM layer but when creating
new relationships with raw sql, we get a warning because the default
value is not set on the mysql server layer.
on empty db create a new audit.
check for warning:
```
/vagrant/src/packages/sqlalchemy/engine/default.py:436: Warning: Field 'is_external' doesn't have a default value
cursor.execute(statement, parameters)
```
Set the missing default value on the mysql server side as well.
=> QUICK-FIX Add server default value for is_external flag

src/ggrc/integrations/utils.py, test/unit/ggrc/integrations/test_utils.py
Issue status sync cron job failed with `Got an unexpected issue from Issue Tracker` error.
Run `hourly_issue_tracker_sync_endpoint` job. No errors should appear in logs.
The type of ids in db didn't match with type of ids received from issue tracker. In this PR ids are casted to unified type.
=> GGRC-4654 Fix issue status cron job

test/selenium/src/tests/test_snapshots.py
Currently Selenium test "test_destructive_mapping_control_to_existing_audit" fails in dev branch in build system but doesn't fail when running ./bin/jenkins/run_selenium locally.
Skip the test so merges of dev PRs won't be blocked until the reason will be investigated.
=> QUICK-FIX Skip Selenium test that fails in dev branch

src/ggrc-client/js/components/related-objects/related-people-access-control-group.js, src/ggrc-client/js/components/related-objects/related-people-access-control.js, src/ggrc-client/js/components/related-objects/tests/related-people-access-control-group_spec.js, src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js
Not all "ACL" methods are covered by unit tests.
=> GGRC-1928 Increase test coverage for the accessControlList frontend component

src/ggrc/fulltext/listeners.py, src/ggrc/fulltext/mysql.py, test/integration/ggrc/__init__.py, test/integration/ggrc/fulltext/test_total_reindex.py
In some cases when in the same moment someone try to update object, one of updated object was not reindexed. 
1) create assessment 
2) open it in 2 different tabs and almost in the same time try to add comment and depreacate it in 2 different tabs 
3) try to filter that object by status, if should be searchable by the fact saved status of the object
Create Thread safety object to collect instances that required to be reindexed.
=> GGRC-4708,4498,4303,4497,4800 Use thread-safe reindex_set

src/ggrc-client/js/bootstrap/modal-ajax.js, src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/controllers/tests/modals_controller_spec.js, src/ggrc/assets/mustache/assessments/modal_content.mustache
This issue is actual for any modal in edit mode. In case of having modal in edit mode and changing a field's value it's possible to see that the value for the same field at the original page is changed too.
1. Create an instance (control, assessment, etc.)
2. Invoke edit modal (control, assessment, etc.) window
3. While typing a field's value (for example: description) look at the same field at the page: the same value is shown
Modals controller contains `instance` field. Looks like initially it was designed to create and handle own instance. Actually modals controller uses `instance` from `options` directly and methods like `set_value`, `set_value_from_element`, etc. change it instead of using own `instance` of the controller. This is the reason why during typing a new value for any …
=> GGRC-4258 Use own instance in modals controller

src/ggrc/converters/base_row.py, src/ggrc/migrations/utils/acr_propagation.py, src/ggrc/migrations/versions/20180305202849_3db5f2027c92_update_acr_table.py, src/ggrc/services/common.py
Issue 1:
The create from select is not supported with our current cloud sql
settings. So the change manually creates the temp tables and then
inserts the data.
Issue 2:
There was an invalid conflict resolution done in https://github.com/google/ggrc-core/pull/7714. The end result was that imports were duplicated.
Run migrations upgrade and downgrade. possibly deploy to one of our test instances.
check result of pylint and flake8 and check that there are no multiple uses of dump_attrs
- Remove the `create table ... select` from our migrations
- Remove duplicate imports
=> QUICK-FIX Fix migrations for cloud sql and remove redundant imports from invalid backmerge

src/ggrc-client/js/controllers/dashboard_page.js, src/ggrc/assets/mustache/dashboard/info/workflow_progress.mustache
On dashboard page: My workflows are loading if there is no active workflow.
1. Log as user that doesn't have any active workflow
2. Open My work page and look at the My workflows section
Actual Result: My workflows are loading if there is no active workflow
Expected Result: My workflows should not be loading if there is no active workflow
Move `self.scope.attr('loading', false);` in right place.
Replace `{{#loading}}` on `{{#if loading}}` because of first option not handle `{{else}}` block.
=> GGRC-4768 Show correct message if there is no workflows in progress

src/ggrc_workflows/__init__.py, src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/models/cycle_task_group.py, test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py, test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py, test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py
Update Cycle Task may take really long period of work.
Create quiet big Cycle. I test it on 10 Task Group and 1000 task in each task group and about 10 Comments per task. 
Remove reindex procedure for Cycle and Task Group on update Cycle Task.
=> GGRC-4960 Disabling the filtering for active cycle [task editing performance]

src/ggrc-client/js/plugins/ajax_extensions.js
In some cases response on HTTP errors is returning not in valid JSON format, that leads to JS errors and not clear warnings for the user.
Added try/catch block in global error handler
=> QUICK-FIX  Add try/catch block for parsing of JSON in global error handler

src/ggrc/converters/base.py, src/ggrc/converters/import_helper.py, src/ggrc/models/cache.py, src/ggrc/services/common.py, test/integration/ggrc/__init__.py, test/integration/ggrc/converters/test_export_snapshots.py, test/integration/ggrc/models/mixins/test_with_last_comment.py, test/integration/ggrc/services/resources/test_converters.py
Control snapshot is not mapped to audit if original control is created via import.
1. Open Import page
2. Download Program and Control in one csv template
3. Fill out required fields for Program and Control, map Control to Program (add control's slug into 'map:control' column in Program)
4. Import csv template
5. Open Program page in UI and create an audit
6. Open Audit page and look at the control snapshot: is not mapped
7. Update audit to the latest version: control snapshot is still not mapped
**Actual Result**: If user create a control via import, mapping between audit and control snapshot of the control is not created.
**Expected Result**: Control snapshot should be mapped to audit if original control is created via import.
See Steps to reproduce.
Import is run as …
=> GGRC-4955 Create revisions on import

src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache, src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc/assets/mustache/assessments/header.mustache
'Complete' button should be disabled for assessment while updating:
1) Evidence file/url
2) LCA
3) GCA
4) Comments
5) Custom roles
1) Generate assessment from assessment template with LCA
2) Change items from list above
Expected result: 'Complete' button should be disabled during saving.
Disable "Complete" button on "isInfoPaneSaving", which contains checks on saving for all items.
=> GGRC-5024 Disable "Complete" button on "isInfoPaneSaving"

src/ggrc-client/js/components/revision-log/revision-log.mustache, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/revision-log/_revision-log.scss
Comment message is shown with tags instead of html elements
1. Open any Control Info page
2. Add a comment to comment box and click Add
3. Open Change Log tab and look at the created comment
Actual Result: if user adds a comment to comment box, comment is displayed in tags in Change log tab
Expected Result: Comment should not be shown in tags in Change Log tab
Parse string to HTML before rendering the comment (unescape)
=> GGRC-4781 Parse string to HTML before rendering the comment

src/ggrc/converters/handlers/default_people.py, test/integration/ggrc/converters/test_export_assessment_templates.py
* `Audit Captain` as Default Assignee/Default Verifier should be displayed in Assessment Template csv file.
* Implement this functionality.
Export `Assessment Template` objects, open file and look.
* Change `get_value` method in default person column handler.
* Add test for check this functionality.
=> GGRC-3375 'Audit Lead' is displayed in Assessment Template csv file instead of 'Audit Captain'

src/ggrc/cache/memcache.py, test/unit/appengine/test_memcache_decorator.py
One of the imports failed because of invalid memcache. 
Rarely memcache could expire and in the result we will receive invalid cache (None value). 
Store value in the variable in order to return it after check for None value.
=> GGRC-4929 Import: Assessment gets created w/o control mapping

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/object-mapper/object-mapper.js, src/ggrc-client/js/components/related-objects/related-objects.js, src/ggrc-client/js/components/workflow/task-list/task-list.js, src/ggrc-client/js/components/workflow/task-list/tests/task-list_spec.js, src/ggrc/assets/mustache/base_objects/task_group_subtree_footer.mustache
FE sends redundant request to the server, when objects are mapped to some Task Group.
1. Open any workflow
2. Open any task group
3. Try to map objects to task group.
**Actual result**: there are a lot of extra requests. It seems, count of redundant requests depends on count of mapped objects.
**Expected result**: there are no extra requests.
There are several ways, which help to remove extra requests.
1. When pagination for the Task Group Task was added, `related-objects` component, which is used inside `task-list`, catches `refreshInstance` event onto `baseInstance` and refreshes items for the list. Thus, when the user tries to map objects to TG, then `object-mapper` component will dispatch `refreshInstance` event -> after mapping `task-list` will refresh the inner list. To resolve this …
=> GGRC-5013 Reduce extra requests, when objects are mapped to Task group

src/ggrc/gdrive/__init__.py
Some requests to GDrive fail with "Deadline exceeded".
1. Create a new Attachment for Assessment from a GDrive file.
Expected result: the GDrive file is copied, a GGRC object is created.
Actual result: the GDrive call to copy the file times out.
It pretty hard to reproduce on test env because we need to simulate poor network (delay about 5s)
I've reproduce it at local env using a standard utility from Mac dev tools.
Note: this issue wasn't reproduced on any test instance, though it occurs quite often on prod (can be seen in the logs). It is possible that prod has a different setup impacting GDrive calls.
Increase httplib2 timeout to 45s.
Since the default time limit for AppEngine calls is 60 seconds, it's dangerous to set this timeout to greater values. 45 seconds is just a magic number …
=> GGRC-4996 Increase httplib2 timeout to 45s 

src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.js, src/ggrc-client/js/components/cycle-task-actions/cycle-task-actions.mustache
Start/Finish/Verify/Decline buttons are not shown fo Global Admin and Editor on some views.
If global admin or global editor goes to 'Workflow Tasks' tab on object page or 'Tasks' tab on all objects page, he won't be able to start/finish/decline/verify tasks unless he has Task Assignee / Task Secondary Assignee / Workflow Admin role.
However due to workflow rbac such users should be able to start/finish/decline/verify tasks and they see these buttons for such tasks on 'Active Cycles' tab on workflow page.
Every person who should be able to Start/Finish Cycle Tasks has Edit permissions, and no other people have Edit permissions. Therefore "Has Edit Permission" <=> "Is Able to Start/Finish", therefore there is no need for the special flag and we can replace "allow_change_state" with …
=> GGRC-4850 Show task buttons for global admin and global editor

src/ggrc/models/custom_attribute_definition.py
Currently function get_custom_attributes_for is run for all object types. It leads to memcache quering and definition_type calculation each time when this function is invoked. But there are no sense to do it for objects that can't have custom attributes (not inherited from CustomAttributable mixin).
This PR is part of GGRC-4919
Tested locally generation of 247 Assessments in Audit with:
196 Standarts
1015 Objectives
4744 Controls
86 Products
140 Systems
5 Audit Captains
10 Auditors
22 Program role people
Without template:
Without fix: 195.535 seconds
With fix: 93.766 seconds
With template (3 CADs):
Without fix: 209.394 seconds
With fix: 88.486 seconds
Run generation of Assessments before and after fix. Check if performance improvement exists.
Check if model is CustomAttributable, if not - …
=> GGRC-5028 Process CAD getter only for CustomAttributable objects

src/ggrc/access_control/list.py, src/ggrc/access_control/roleable.py, src/ggrc/access_control/utils.py, src/ggrc/migrations/versions/20180430005840_e5f737f2a428_add_parent_id_nn_to_acl_table.py, src/ggrc/models/hooks/acl/propagation.py, src/ggrc_workflows/models/hooks/workflow.py
I have added the https://github.com/google/ggrc-core/pull/7773 PR as a dependency because it has a conflict with this one. The conflict is already resolved here and this PR contains all changes.
Updating a single cycle task status takes more than 2 minutes, on bigger workflows (2k tasks and multiple cycles)
The biggest bottleneck in this is the query that pulls out all cycle tasks for a given cycle, which are then used for reindexing. The fix to not pull all tasks for the reindex job is done here: https://github.com/google/ggrc-core/issues?q=assignee%3Azidarsk8+is%3Aopen
But even so the query for multiple objects must never run that slow.
Example query that takes a few minutes (cut down version of the origina for readability):
```sql …
```
=> GGRC-4926 Add access control list table optimizations

src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js, src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
Save & Close button is disabled in Edit Task Group popup when you reassign the task to a user who is an author of Control, attached to the Task Group.
Model cache is not updated from external-data-autocomplete.
1. Create a Control by User#2.
2. Login as User#1 and create a Workflow.
3. Open Task Group in Setup tab.
4. Attach the Control (from step 1) to the Task Group.
5. Open Edit Task Group.
6. Try to reassign it to User#2.
**Actual Result:** Save & Close button is disabled.
**Expected Result:** Save & Close button should be enabled.
Added model.reify() to external-data-autocomplete on createOrGet item.
=> GGRC-5017 Save & Close button is disabled in Edit Task Group popup after reassign task group assignee

src/ggrc_workflows/migrations/versions/20180328152231_5206dc9f95f0_remove_invalid_cycletask_relationships.py
Somebody created invalid relationship on ggrc-dev instance between CycleTask and Assessment. It happened before GGRC-4576 was merged. Currently it is impossible.
- Take latest ggrc-dev instance db dump and deploy it on local machine.
- Run next query to check for invalid relationships. There is should be non-empty output.
```SELECT id FROM relationships WHERE (source_type = "CycleTaskGroupObjectTask" AND destination_type = "Assessment") OR (source_type = "Assessment" AND destination_type = "CycleTaskGroupObjectTask");```
- Apply changes from this PR and run db_migrate.
- Check for invalid relationships and revisions. All of them should disappear.
```SELECT id FROM relationships WHERE (source_type = "CycleTaskGroupObjectTask" AND …
```
=> GGRC-4688 Remove invalid CycleTask-Assessment relationships/revisions

src/ggrc/services/resources/related_assessments.py
**Note: This is a partial PR for the specified ticket.**
Fetching a list of 0 related assessments shows an sqlalchemy warning.
freshly start the dev server (launch_ggrc)
on a clean db create a new assessment and open it.
wait for related assessment query to be called as well
look at the server output:
you will see:
```
/vagrant/src/packages/sqlalchemy/sql/default_comparator.py:35: SAWarning: The IN-predicate on "relationships.destination_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
return o[0](self, self.expr, op, *(other + o[1:]), **kwargs)
/vagrant/src/packages/sqlalchemy/sql/default_comparator.py:35: SAWarning: The IN-predicate on …
```
=> GGRC-5134 Remove sqlalchemy warnings on related assessments

src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc_basic_permissions/test_reader.py
Global reader can't read Evidence revision.
3. Attach evidence to assessment
4. Log as Global Reader user
5. Open Assessment Info page > Evidence tab
6. Expand Evidence Info panel and click Change Log tab
**Actual Result**: If Global Reader user, who doesn't have any role in audit opens Change Log tab in Evidence, "Uncaught TypeError: Cannot read property 'access_control_list' of null" error occurs, no info is shown in Change Log
**Expected Result**: no errors should be shown if global creator user w/o any role in program opens change log tab on Evidence
Add Evidence object to Global reader's configuration.
=> GGRC-5127 Global reader can't read Evidence revision.

src/ggrc/models/mixins/__init__.py
The end_date variable is a date not a datetime. Setting it to now
instead of today triggered an sql warning that the data was being
truncated.
Deprecating an assessment shows a warning
/vagrant/src/packages/sqlalchemy/engine/default.py:436: Warning: Data truncated for column 'end_date' at row 1
start server with launch_ggrc
deprecate an assessment
look at server logs
Extra: compare integration tests output
Set the correct value format to end_date.
=> GGRC-5133 Remove data truncated warning

src/ggrc/services/attribute_query.py, test/integration/ggrc/services/test_custom_attributes.py
Add ability to filter CADs mandatory field by int value.
Get request to https://{your_server}/api/custom_attribute_definitions?definition_type=product&mandatory=1
should return filtered CAD list
add ability to filter boolean filed by int values.
=> GGRC-4813 Custom Attribute Definitions: Filtering by mandatory doesn't work

src/ggrc/notifications/__init__.py, test/integration/ggrc/models/mixins/test_customattributable.py
There is internal error when assessment is put into progress state after global CAD is deleted.
1. Have an assessment in 'In Review' state;
2. Add global CAD;
3. Fill in this cad in the assessment;
4. Delete cad;
5. Click 'Edit Answers' button.
No errors should appear; assessment should be moved in 'In Progress' state.
An error appeared in notification handler. There is KeyError in method which checks if cad has been updated. To fix it, check if object exists in dict was added.
=> GGRC-4997 Fix 500 error when moving assessment to In Progress after GCAD delete

src/ggrc/models/hooks/acl/__init__.py, src/ggrc_workflows/models/hooks/workflow.py
Adding a comment on cycle tasks takes too long on a big workflow
2000+ tasks in a workflow (with a few cycles started)
50+ people assigned as wf members or admins.
- Fully test rbac on cycle tasks and cycle task comments. 
- Check performance impact on different cases for different users.
Note: pay attention if you have WF roles or cycle task role or none or both.
Originally to avoid handling all special cases, any new object that was
added to a workflow scope, triggered the entire workflow propagation.
This is good enough for cycle generation and other such operations
because we avoid duplicating work, or specifying all possible special
cases for child propagation, when multiple objects are created in a
single transaction.
Cycle tasks on the other hand need to be faster and they are easy …
=> GGRC-5168 Add special acl handler for cycle task comments

src/ggrc/models/mixins/notifiable.py, src/ggrc_workflows/migrations/versions/20180521064346_fd8706aad739_clean_up_notifications_table.py
Deleting an active workflow show a "object_id can not be null" warning, and sets the id to invalid 0.
launch the server with launch_ggrc
create and activate a workflow
delete a workflow
Check server logs.
Check that notification entries do not exist for that workflow and those deleted cycle tasks.
Check errors output on run_pytest 
Set the correct relationship cascade property to ensure notifications for deleted objects are deleted as well.
Remove all notification entries for past deleted objects.
=> GGRC-5130 Remove sql warning on active workflow deletion

docs/source/frontend/overview.rst, src/ggrc_basic_permissions/__init__.py, src/ggrc_basic_permissions/contributed_roles.py, src/ggrc_basic_permissions/models.py, src/ggrc_workflows/__init__.py, test/integration/ggrc/models/factories.py, test/integration/ggrc_basic_permissions/models/factories.py
Legacy role propagation code from before the ACL migration should be removed and we must make sure it does not affect anything else in the app now.
Do some basic rbac checks for audits programs and workflows. 
Part 1: 
The dead function lookup_role_implications was the only place left where
role implications were used. Since this function is no longer called
anywhere we have deleted the entire chain of dead code left over from
the previous rbac model.
Note: the only place with RoleImplications left is now in
src/ggrc/assets/mustache/events/object_list.mustache
But since that lists revisions of past events and has the filter to
ignore revisions of Controls and RoleImplications I have opted to leave
this code in.
Part 2:
Removal of all context implications. We will remove object contexts …
=> GGRC-5123 Remove legacy role propagation code

src/ggrc/converters/handlers/default_people.py, src/ggrc/converters/pre_commit_checks.py, test/integration/ggrc/converters/test_import_assessment_templates.py, test/integration/ggrc/utils/test_user_generator.py
Error shows 'Default Verifiers' field as mandatory while importing Assessment template. But 'Default Verifiers' field is not mandatory in UI and there is a possibility to create Atemplate w/o Default Verifiers.
1. Open any audit page 
2. Create assessment template w/o Default verifiers 
3. Export Assessment template 
4. Import Assessment template w/o any changes 
Expected result: No error should be shown while importing Assessment template if Default Verifiers column is empty in csv/google sheet
Since we can check is the field is mandatory or not when setting up the value (verifier is not mandatory while assignee is), the additional check is added in order not to raise any error when verifier is empty.
=> GGRC-4665 Make Default Verifiers non-mandatory in import

src/ggrc/data_platform/attributes.py, src/ggrc/data_platform/computed_attributes.py
Assessment deletion triggers a unicode sql warning.
launch server with launch_ggrc
Delete an assessment 
check logs for warnings
Extra: compare integration tests output
Since the object type and id are set automatically by ORM mapper when
deleting an assessment we can't force it to be unicode and then
sqlalchemy shows a warning that we're comparing ascii to unicode.
The original reason for using unicode was to be as close to data
platform design as possible, but the key difference here is that our
models are actual python classes that can't be unicode. This makes it
safe to change the filed from unicode to normal string.
=> GGRC-5131 Remove unicode warnings from attributes deletion

src/ggrc/templates/assessments_view/index.haml, src/ggrc/templates/import_export/export.haml, src/ggrc/templates/layouts/dashboard.haml, src/ggrc/views/__init__.py
Previously GGRC.roles were added to templates of the application with no usages (https://github.com/Smotko/ggrc-core/commit/bcd44381b48e1aa2090d05ba8c0435db2ebaa726). At the same time the application loads them on initial loading. The goal of this story is to remove unused GGRC.roles from the front-end and get_roles_json from the back-end.
Application:
- open the application in a browser
- check that we don't have errors in the console after initial loading
Administration:
- open the administration in a browser
- check that we don't have errors in the console after initial loading
- click at Roles tab
- check that roles are rendered
GGRC.roles and get_roles_json are not in usage anywhere so we can remove them and reduce time of initial loading.
=> GGRC-5170 Revert "Preload roles"

src/ggrc/models/hooks/acl/propagation.py, test/integration/ggrc/models/hooks/acl/test_propagation.py
re-calculating ACL propagation fails for workflows.
This is a regression from https://github.com/google/ggrc-core/commit/af4173508e467469a9106309a3f93720966d28c9
have a few workflows and run propagate_acl command
Extra run propagate_all on various db dumps from our instances.
I have added the missing variable to wf acl propagation command.
=> GGRC-5204 Fix full acl propagation for workflows

src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc/access_control/acl_propagation/test_assignees.py, test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py, test/integration/ggrc/access_control/acl_propagation/test_auditors.py, test/integration/ggrc/access_control/acl_propagation/test_program_editors.py, test/integration/ggrc/access_control/acl_propagation/test_program_managers.py, test/integration/ggrc/access_control/rbac_factories/evidence.py
Global Reader as assessment Assignee cannot attach evidence file/url
1. Log as user-1
2. Create program, control, audit
3. On the audit page create assessment and add user-2 (Global Reader) as Assignee
4. Log as user-2 (Global Reader) and open Assessment info page
5. Try to attach evidence file/url
Actual Result:
'You do not have permissions...' message is shown;
Evidence file/url is not attached.
Actual Result: Global Reader user as Assessment Assignee should have permissions to add evidence file/url to Assessment.
NOTE: Global reader should not have any program roles.
Because we can't propagate 'create' permissions we need to  allow Global reader to create Evidence/Document.
Global Reader can create Evidence, but can't map it w/o Assignee role.
=> GGRC-5193 Global Reader as assessment Assignee cannot attach evidence file/url

src/ggrc/migrations/versions/20180528102128_f77f9a8aff84_remove_obsolete_attribute_from_sections.py, src/ggrc/models/section.py
The section attribute 'na' is not used anywhere in our code. Import and
export does not have a column for it and no frontend code uses it at
all. That is why this should be a safe deletion of obsolete code.
The section attribute 'na' is not used anywhere in our code. Import and
export does not have a column for it and no frontend code uses it at
all. That is why this should be a safe deletion of obsolete code.
Check that there are no changes visible in the UI on the section model.
remove `na` attribute and its references.
=> GGRC-4167 Remove obsolete section attribute

src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-filter-input.js, src/ggrc-client/js/components/tree/tree-status-filter.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js, src/ggrc-client/js/plugins/tests/ggrc_query_api_spec.js, src/ggrc-client/js/plugins/tests/state-utils_spec.js, src/ggrc-client/js/plugins/utils/advanced-search-utils.js, src/ggrc-client/js/plugins/utils/query-api-utils.js, src/ggrc-client/js/plugins/utils/state-utils.js, src/ggrc-client/js/plugins/utils/tree-view-utils.js
1) Use "in" operator for Status multi-select filter
2) Build status filter in object format on tree-view
Try to apply status filter - it should use `IN` operator.
Modify components to build filters as objects instead of building long strings and applying query parser.
=> GGRC-5135, GGRC-5099 - Build and use query API filters as objects, not strings.

src/ggrc/converters/base_row.py, src/ggrc/models/mixins/__init__.py
The audits failed to be created via import. 
Steps to test:
1. Create a program in UI
2. Download Audit csv template
3. Fill out required fields > Save and then import Audit csv template
The reason for failing import is that some data could be corrupted (slug is an empty string). In order to prevent it I've created a validator for slug. Also when importing objects we can check whether the key value is falsy.
=> GGRC-4934 Cannot create an Audit via Import

src/ggrc/access_control/utils.py, src/ggrc/models/hooks/acl/propagation.py, src/ggrc_workflows/models/hooks/workflow.py, test/integration/ggrc/models/hooks/acl/test_propagation.py
Having a single big delete statement that takes a long time is hard to
track in the logs if something went wrong and it has a higher risk of
triggering lock_wait_timeout error.
- Check that normal acl propagation (adding a role and mapping objects) still works
- check that propagate_acl command works
The deletion of acl roles is split into same chunks as creation of acl roles for easier tracking and spotting of slower parts of deletion.
I have left the default chunk size because some parts are really slow and it took "too long" for a the slowest chunks to be handled.
=> GGRC-5229 Split acr propagation deletion into chunks

src/ggrc-client/js/entrypoints/commons.js, src/ggrc-client/js/entrypoints/user.js, src/ggrc-client/js/plugins/tests/current-page-utils_spec.js, src/ggrc-client/js/plugins/utils/current-page-utils.js
GGRC-5051 Cleanup redundant people request when add a comment to CAV
When adding a comment in Assessment, a new request for a Person is fired although you are an author of Assessment.
1. Create new Assessment Template with Dropdown custom attribute.
2. Mark any field in Dropdown as "Comment Required". Create.
3. Create new Audit.
4. Select Assessment Template created in p.2.
5. Autogenerate Assessment.
6. Open Assessment.
7. Select appropriate option in dd and leave a comment.
**Actual Result**: A redundant people request is fired for your user.
**Expected Result**: User model should already be in Person cache as user is creator of Assessment.
Add GGRC.current_user to Person model cache on bootstrap stage
=> GGRC-5051 Cleanup redundant people request

src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
Gdrive picker triggers unneeded `modal:success` event that handled by `add-issue-button` component and causes extra query api call.
Attach evidence file to assessment.
Remove triggering of the event.
=> GGRC-3236 Don't trigger modal:success in gdrive picker

src/ggrc/services/common.py, src/ggrc/views/__init__.py
We experience performance issues because of lazy loading of revisions ids. 
The solution is to send event id to the background task and query revisions ids with one qouery by event id.
When creating an assessment see in the sqlalchemy logs the queries to the database. Now we should only query revision ids once per background task.
=> GGRC-5075 Revision ids are loaded lazily in send_event_job

src/ggrc-client/js/models/document.js, src/ggrc/assets/mustache/documents/tree-item-attr.mustache, src/ggrc/assets/mustache/evidence/tree-item-attr.mustache
Last Updated By column is not populated for Evidence objects in tree view / global search
1. Open tree view with evidence objects / Global Search
**Actual result:** Last Updated By column is not populated
**Expected result:** Last Updated By column should be populated
Use correct component for displaying person field.
=> GGRC-5245 Fix issue with populating Last Updated By column for Document/Evidence

src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache, src/ggrc-client/js/components/state-colors-map/state-colors-map.js
"Completed and Verified" state has wrong color.
Have program, control, audit, at least 2 assessments generated based on the same control snapshot.
1. Move 1 assessment to "Completed and Verified" state
2. Open Assessment Info pane for the second Assessment
3. Open Related Assessment tab and look at the Completed and Verified state
Actual Result: "Completed and Verified" state isn't displayed in green color
Expected Result: "Completed and Verified" state should be displayed in green color:
I've added 'verified' to classes in case if it has "verified date" to set correct color.
=> GGRC-4197 Fix state color indication

src/ggrc-client/js/models/category.js, src/ggrc-client/js/models/local_storage.js, src/ggrc-client/js/models/notification_config.js, src/ggrc-client/js_specs/models/local_storage_spec.js
Previously require comments were used to import dependencies. After switching on webpack they are not actual and should be removed.
No testing required.
Remove outdated comments.
=> QUICK-FIX Remove outdated require comments

docs/source/frontend/modals.rst, src/ggrc-client/js/components/modal-connector.js, src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/models/save_queue.js, src/ggrc-client/js/plugins/persistent_notifier.js, src/ggrc-client/js/plugins/tests/utils/models-utils_spec.js, src/ggrc-client/js/plugins/utils/models-utils.js, src/ggrc-client/js_specs/models/cacheable_spec.js
There are extra requests, when someone tries to unmap objects from CT via Edit modal.
1. Open Workflow page -> Active Cycles.
2. Open any Cycle task with some mapped object.
3. Open Edit modal for this Cycle task.
4. Unmap mapped object.
5. Click "Save".
**Actual result**: There are a lot of requests. 
Need to make an investigation, which requests are really needed.
When some object are unmapped from Cycle task via Edit modal, a lot of requests are occurred.
Was removed extra requests:
1. Double refresh after unmap operation.
=> GGRC-5068 Reduce extra requests when objects are unmapped from Cycle Task via Edit modal

src/ggrc/automapper/rules.py, test/integration/ggrc/automapper/test_automappings.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc/converters/test_import_automappings.py, test/integration/ggrc/test_csvs/automappings.csv
We need to disable all automapping rules that map Objectives and Controls to Sections, Clauses, Directives (Regulations, Policies, Contracts, Standars), Programs (basically, any objects on a higher level in the hierarchy).
Check that Objective and Control is not automapped to higher hierarchy objects.
Remove Section/Objective automapping rules.
=> GGRC-5157 Disable all automapping rules for Objective and Controls

src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
Using State dropdown in Global search / Unified mapper breaks search
1. Click Global Search
2. Check / uncheck something in State dropdown (e.g. just uncheck and check a checkbox)
3. Click Search
Actual result: no results are found
Expected result: results should be found
1) Correctly build filters in can.Map/can.List format.
2) Convert filters to JS objects to avoid sending service fields to server.
=> GGRC-5346 Convert advanced search items to JS objects

src/ggrc-client/js/components/create-document-button/create-document-button.js, src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
GC can't attach gdrive file to control if he doesn't have access to its document
**Case 1** - "User can't attach file to control if he doesn't have access to the document"
1. Login as <user1>
2. Create a control, attach a gdrive file (gdrive file is shared with <user2>)
3. Login as <user2>
4. Create a control, click attach -> Attach new -> choose this gdrive file.
5. Click Proceed in the warning
**Actual result:** A document is not mapped because incorrect request is sent
**Expected result:** A document should be mapped. <user2> should be made an admin of it
**Case 2** - "User isn't made admin of the document when attaching its file if he has access to the document"
1. Login as <user1>
2. Create a control, attach a gdrive file (gdrive file is shared with <user2>), make <user2> an admin of …
=> GGRC-5262 Use correct fields when make user as admin

src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js
On opening of tree-item, instance of it is refreshed. But if tree-view list was changed before refresh, there is no actual instance for tree-item.
**Case 1:**
1) Have more than 10 assessments
2) Open tree-view with this assessments with 10 items per page
3) Open last assessment
4) Minify info-pane
5) Type nonexistent assessment title into search filter
6) Click 'Next' button on assessment info-pane
**Case 2:**
1) Have more than 11 assessments with following filter by state applied: (Not Started, In Progress, Rework Needed)
2) Open tree-view with this assessments with 10 items per page
3) Open last assessment
4) Complete assessment
5) Click 'Next' button on assessment info-pane
**Actual result:** Error is shown: Cannot read property 'refresh' of undefined
**Expected result:** No error is …
=> GGRC-5080 Check existence of instance before refresh it on info-pane

bin/containers_functions.sh, bin/jenkins/run_checkstyle, bin/jenkins/run_code_style, bin/jenkins/run_integration_acl, bin/jenkins/run_integration_ggrc, bin/jenkins/run_integration_non_ggrc, bin/jenkins/run_selenium, bin/jenkins/run_unittests, bin/selenium_containers, docker-compose-selenium.yml, docker-compose-testing.yml
PR https://github.com/google/ggrc-core/pull/7891 previously has removed ports from docker-compose-testing.yml so several cleandev containers could be started.
Ports were used by Selenium tests. This PR adds another docker-compose file to be used by Selenium tests.
=> QUICK-FIX Split selenium docker compose file

src/ggrc/converters/handlers/snapshot_instance_column_handler.py, test/integration/ggrc/converters/test_import_audit.py
Import of existing Audit fails if imported data contains information about mapped snapshots.
UI error: 'The volume of import is too big. Please split your import in smaller portion of 200 or less rows and import one after another. Sorry for inconvenience.'
Reason of this issue is in wrong implementation of mapped snapshots collection.
1. Go to Export page and export any existent audit
2. Click Write to sheet after export
3. With or without any updates Import Audit
Expected Result: Audit should be imported. No errors should be shown.
Refactor procedure `audit_object_pool_query` to handle cases when mapped snapshots should be found for Audit and Assessment.
=> GGRC-5065 Fix import of Audit

src/ggrc/query/custom_operators.py, test/integration/ggrc/services/test_query/test_in.py
Impossible to filter by `"Stask State" in [anything]"`. (note: this isn't the actual text of the query, you have to build the tree equivalent to `self._make_query_dict("CycleTaskGroupObjectTask", expression=["Task State", "IN", [...]])`).
Check that state dropdown filter for cycle tasks works.
Instead of doing a special operator, use the common wrapper `build_op_shortcut`.
=> GGRC-5362 Support aliases for IN operator

src/ggrc/services/common.py, test/integration/ggrc/api_helper.py, test/integration/ggrc/services/test_head.py
Need to add possibility to send HEAD request in cases when need to get ETag only.
In that case we will avoid loading of unneeded data and improve performance.
Send HEAD request to "/api/<model>/<id>". Check correctness of response (valid ETag, empty body). Check that only required queries are loaded during HEAD request processing.
Add new handler for HEAD requests.
=> GGRC-5291 Add HEAD request handler

src/ggrc/migrations/utils/__init__.py, src/ggrc/migrations/versions/20180604100018_3a41fc031f53_update_send_by_default_evidence_field.py, src/ggrc/migrations/versions/20180604140037_b1dbfad3bbad_create_missing_admins.py, src/ggrc/migrations/versions/20180605090010_ad7e10f2a917_create_missing_evidence_admins.py, src/ggrc/models/evidence.py
Evidence and Document objects exist w/o Admin user role
1. Log as admin user to ggrc-test https://ggrc-test.googleplex.com/objectBrowser#!evidence_widget
2. Open Evidence tab
3. Type into search box: "admin is empty"
4. Look at the Search results
Actual Result: Filter query returns evidences w/o Admin user
Expected Result: Admin user should exist for Evidence object
Implement migration to set admin using 'created' revision. If not exists, migration_user_id.
=> GGRC-5149 Evidence and Document objects exist w/o Admin user role

src/ggrc/migrations/versions/20180604140037_b1dbfad3bbad_create_missing_admins.py, src/ggrc/migrations/versions/20180605090010_ad7e10f2a917_create_missing_evidence_admins.py
GGRC-DEV shows Server Error
Migration was not completed because of enforce_gtid_consistency=ON setup at CloudSQL
Check that migrations run successfully at test instance
Add SET AUTOCOMMIT = 1 in the migration scripts
=> GGRC-5395 GGRC-DEV shows Server Error

src/ggrc/migrations/versions/20180508145225_9bc9e8064e04_change_relationship_assessment_template_audit_not_null.py, src/ggrc/models/assessment_template.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/test_audit.py, test/integration/ggrc_basic_permissions/test_audit_archiving.py
User is able to delete an audit if Assessment template exists in scope of it
1. Create a program, audit
2. Open audit page
3. Create Assessment template
4. Go to Assessment template Info page > Audit tab
5. Click Delete button in 3 bb's menu
Do not allow user to delete an Audit unless all the Assessment Templates in scope of this Audit are deleted (same behavior as for Assessments)
Update assessment_templates db table
1) `audit_id` int(11) NOT NULL
2) CONSTRAINT fk_assessment_template_audits
=> GGRC-4817 User is able to delete an audit if Assessment template exists in scope of it

src/ggrc/migrations/versions/20180620152957_2da3b90cf88e_delete_invalid_issue_tracked_issues.py, src/ggrc/models/issuetracker_issue.py, test/integration/ggrc/integrations/test_issuetracker_issue.py
The deletion of an audit of failing.
Steps to reproduce (on sql dump):
1. Create a new program and audit.
2. Open its Info Pane.
3. Click "Delete" button in 3 bb's menu
Actual result: Audit is not removed, exception appears in UI
Expected result: Audit should be removed
Steps to reproduce (on clear database):
1. Create new program and 2 audits
2. Delete the first audit (successfully)
3. Delete the second audit
Actual result: Audit is not removed, exception appears in UI
Expected result: Audit should be removed
Make relationships use cascade during deletion
=> GGRC-5382 Cannot delete an audit

src/ggrc/automapper/__init__.py
Note: Only the last two commits belongs to this PR.
We must remove context checks form our code and this in this PR we remove them from automappings code
Note: Relationships created by automappings still contain context_ids and those will be removed when we remove contexts from the relationship model.
Check rbac on automappings.
Remove contexts from permission checks in automappings code.
I have not found any specification on how rbac on automappings should work, but I have verified that there should be no differences between current dev branch and this PR.
Checks were done by checking differences between mapping to a program by a Reader, Creator and Admin, where creator/reader did not see/have access to all objects in the …
=> GGRC-5402 Remove contexts from automapper

src/ggrc/models/comment.py, test/integration/ggrc/models/mixins/test_commentable.py, test/integration/ggrc/models/mixins/test_with_action.py
Title and option of LCA dropdown are missed after Assessment Info panel got refreshed
Precondition:
Have an audit and created Assessment with LCA dropdown, comment is required
1. Open Assessment Info panel
2. Select option with required comment for LCA, type a comment and save it
3. Confirm that Person's email, assessment role, LCA title, dropdown option and comment are displayed under comment box
4. Close and open Assessment Info panel: only Person's email, assessment role and comment are shown
Expected Result: Title and option of LCA dropdown should not be missed after Assessment Info panel got refreshed
When creating a json for a Comment fill the property that is used for retrieving title information on the UI
=> GGRC-5048 Title and option of LCA dropdown are missed after Assessment Info panel got refreshed

src/ggrc-client/js/components/simple-modal/simple-modal.js, src/ggrc-client/js/components/simple-modal/simple-modal.mustache, src/ggrc-client/js/components/unified-mapper/mapper-results.js
Date picker is cut off in New Control popup.
1. Log as Admin user and go to Administration page
2. Add mandatory custom attribute with date type.
3. Invoke new control popup from mapper as you can see on screenshot (click Map -> within the mapper, click Create and map new object).
Note 1: "Create and map new object" link should be clicked before the moment, when the data for mapper's tree view will be loaded.
Note 2: This ticket is reproducible, when mapper's items have "Assessments" button.
4. Click on ca with date type
**Actual Result**: Date picker is cut off in New Control popup
**Expected Result**: Date picker should not be cut off in New Control popup
The issue was due to the method `show` from `modal-ajax.js` added `overflow: …
=> GGRC-5055 Date picker is cut off in New Control popup

docs/source/contributing/python.rst
The old links for google style guides are deprecated so we should update our links
=> QUICK-FIX Update google style guide links

src/ggrc/fulltext/mysql.py
We should avoid logging the benchmark if there is nothing to be indexed.
The actual use for the statement before the return statement would be to
check that this function is not called too many times. But we have other
fail-safes for too many commits.
This commit just prevents the spamming of logs on total acl propagation
recalculation.
Run propagate_acl on ggrc_qa_db an look at the logs
Move the benchmark statement so it's only displayed when there is something to reindex.
It does not make much sense to log performance of a single return statement.
=> QUICK-FIX Move indexer benchmark statement

src/ggrc/migrations/utils/__init__.py
If there are multiple "created" revisions for a Document (Evidence) with no Admin, the migration to restore Admins violates unique constraint on the ACL table.
1. Remove the Admin record from three Document objects.
2. For the first Document object, remove all revisions for it.
3. For the second Document object, manually INSERT a new Revision with fields same as its "created" revision (only `resource_id`, `resource_type`, `action`, `event_id`, `modified_by_id` matter).
4. For the third Document object, manually INSERT a new Revision with fields same as its "created" revision but with a different `modified_by_id` value.
5. Run the migration to populate Admins on Documents.
Actual result: manipulations from steps 3 and 4 break the migration.
Expected result: the first Document gets the …
=> GGRC-5434 Fix deployment blocker with duplicate revisions

src/ggrc-client/js/bootstrap/sticky-popover.js, src/ggrc-client/js/controllers/dashboard_widgets_controller.js, src/ggrc-client/js/controllers/lhn_controllers.js, src/ggrc-client/js/models/directive_models.js, src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
Basically we have 96 eslint comma style errors. 
No QA testing required. From eslint perspective it's possible to check that `',' should be placed last comma-style` errors are not actual anymore.
Place commas last.
=> QUICK-FIX Fix eslint comma style issues

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/unit/ggrc/models/hooks/test_issue_tracker.py
The logs show that Ticket Tracker was "ON" in the assessment, after the 500 error, the ticket tracker was turned off.
Do not turn off the Ticket Tracker manually.
=> GGRC-4818 IssueTracker turns off when IssueTracker sync errors

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc-client/js/components/object-list/object-list.mustache
Issue connected to render the`comments` list.
Items render again after each adding of new comment
Create and open an assessment in Chrome
Open performance monitor in Chrome dev tools
Add a lot of comments (for example 100)
_Actual result:_ JS heap size and number of DOM Nodes values are high.
1. Use {{#each key}} helper instead of {{#key}}
https://v2.canjs.com/docs/can.mustache.helpers.section.html
2. Improve performance of `afterCreate` method (info-pane.js) (Removed unneeded `Array.replace`)
Previous version of implementation `afterCreate` updated 1 item from collection and then invokes `replace`. This `replace` triggers redraw of all items.
**Data set**: 600 comments
**Actions**: adding of 3 new comments
| Param description  | Before fix | After fix |
| ------------- | ------------- | …
=> GGRC-5178 Fix memory leak for comments form

src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-container_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-group_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-container_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-group_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-wrapper_spec.js
=> QUICK-FIX Update tests for advanced-search-filter components

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
JS error is displayed while attaching evidence file to Assessment via dropdown LCA.
This is regression from [5178](https://github.com/google/ggrc-core/pull/8054) , caused by replacing `{{#items}}` on `{{#each items}}`.
1. Create a program, audit, map control snapshot to this audit
2. Create asmt template with dropdown LCA that has evidence file=required
3. Generate asmt from template and control snapshot
4. Open this asmt
5. Choose a value from dropdown LCA that required evidence file
6. Click Attach and upload file from PC or GDrive
***Actual Result:*** Uncaught TypeError: Cannot read property 'appendChild' of null error is displayed. Info panel freezes. After refreshing the page evidence file is shown as attached.
***Expected Result:*** no errors while attaching …
=> GGRC-5495 Use 'attr' instead of 'replace' when updating evidence

src/ggrc_basic_permissions/__init__.py
Currently permissions data stored in memcache can consume too mach memory. It lead to error like:
`Values may not be more than 1000000 bytes in length`.
Login under user who has > 900k acl entries. No errors should be thrown.
Compress permission data before saving it.
This solution allows to decrease permission object size in 2 times. For ggrc.creator@gmail.com on last ggrc-qa db permission object in memcache takes 622 Kb in uncompressed state. If it's compressed it takes 310 Kb.
=> GGRC-5513 Store compressed permission dict in memcache

src/app.yaml.dist
Comment creation on ggrc-perf takes too much time. The reason is deployment settings. 
We have manual scaling, this scaling leads to constant numbers on instances, but each instance may process more then 1 requests in separate thread cause threads are enable. Each running thread locks process CPU cause of GIL.  
try to create comments via ggrc-perf 
Deny thread via GAE settings.
=> GGRC-5525 Make instance thread safe

src/ggrc-client/js/components/import-export/export.js, src/ggrc-client/js/components/import-export/test/export_spec.js
Snapshots are missed in csv file/Google sheet if export it w/o Filter by mappings
2. Select OBJECT TYPE 'Snapshots'
3. Select 'SELECT SNAPSHOT OBJECT TYPE' e.g. Control
4. Export snapshots to Google Sheet
5. Open Google Sheet
Expected Result: All snapshots in the system should be exported for the selected object type if user doesn't indicate mappings
The reason of this bug is that child_type was always added to the filter with AND operator. So additional check for presence of filters should resolve it.
=> GGRC-5524 Fix export of snapshots without filter by mappings

src/ggrc-client/js/components/ca-object/ca-object-modal-content.mustache, src/ggrc/assets/mustache/gdrive/gdrive_file.mustache
Page is reloaded when adding evidence url or evidence file for dropdown LCA.
The issue appeared after this [PR](https://github.com/google/ggrc-core/pull/7997), but actually refresh of page happens because of this button is inside of `<form>` and its `type` attribute is not defined, so by default it is `submit`. Submit event of form calls reload of page.
1. Create a program, audit, map control snapshot to this audit
2. Create asmt template with dropdown LCA that has evidence url = required or  evidence file = required
3. Generate asmt from template
4. Open this asmt
5. Choose a value from dropdown LCA
8. Click Add evidence url/ attach file button
Actual: Page is reloaded, with following URL `.../audits/4570?#!assessment` (`?` sign is added after instance id)
Expected: Add url text field / …
=> GGRC-5494 Add 'type' attribute for buttons on LCA popup

src/ggrc/snapshotter/__init__.py, test/integration/ggrc/converters/test_import_audit.py
Import of CSV with more than 1 audit fails
import file attached to GGRC-5499
Fixed SnapshotGenerator to update query execution in scope of session.
Removed commit from SnapshotGenerator because of RowConverter.process_row has commit statement.
=> GGRC-5499 Import of CSV with more than 1 audit fails

src/ggrc/converters/snapshot_block.py, src/ggrc/migrations/versions/20180706140827_0e40a37a05f4_add_foreignkey_snapshot.py, src/ggrc/models/audit.py, src/ggrc/models/snapshot.py, test/integration/ggrc/converters/test_export_snapshots.py, test/integration/ggrc/converters/test_snapshot_block.py
'Archived' column added to export of snapshots
Create Audit with mapped controls, and make an export of snapshots. CSV file should contain 'Archived' column with archived status of related audit.
- Add 'archived' to export code base
- Add foreign key relationship to Snapshot-Audit to eagerly load archived status with constant number of queries.
- Fix broken tests(not expecting 'Archived' column)
- Add test of exporting snapshots with archived status
*Change Snapshot.parent_id to foreign key to Audit.id*
*Migration will delete snapshots with wrong foreign key parent_id or parent_type not equal to 'Audit'*
=> GGRC-2365 Export snapshots archived column

src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.js, src/ggrc-client/js/components/dropdown/multiselect-dropdown-wrapper.mustache, src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown-wrapper_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/mustache_helper.js, src/ggrc-client/styles/_common.scss, src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss, src/ggrc-client/styles/modules/_modal.scss, src/ggrc/assets/mustache/controls/modal_content.mustache
GGRC-5142 Improve UX for Assertions and Categories elements in Create/Edit modal of Control object.
Unify multi-selects and replace Assertions and Categories multi-selects to multi-select dropdown.
1. Open a control.
2. Click on Edit Control.
3. Check that multi-selects for Assertions and Categories replaced to multi-select dropdown and work properly.
Create `multiselect-dropdown-wrapper` component, which fetches options before passing them to `multiselect-dropdown`.
Replace `category_select` helper with `multiselect-dropdown-wrapper` component in Control's modal_content.
Remove `category_select` helper.
=> GGRC-5142 Improve UX for Assertions and Categories

src/ggrc/migrations/versions/20180710160131_0e385718442a_remove_star_from_slugs.py, src/ggrc/models/mixins/__init__.py, test/integration/ggrc/converters/test_import_csv.py, test/unit/ggrc/models/test_slugs.py
Prevent "*" sign in object codes(slugs) 
Because exported Snapshots have slugs like "\*CONTROL-1234" (with "\*" to denote snapshot), "\*" entered by the user manually may confuse the users.
Create for example Control with Code field 'CONTROL*-1' and error should occur. Creation of objects with slug without '*' should finish successfully.
Add validator to field 'slug' in Slugged mixin.
For existing slugs add migration that will replace '\*'  to '-' and in case of conflict add "-{int}" to end of slug.
*Migration will replace in existing slugs(codes) '\*'  to '-' and in case of conflict add "-{int}" to end of slug*
=> GGRC-1789 Prevent "*" sign form object codes (slugs)

src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss, test/selenium/src/lib/entities/entity.py
Custom attributes on the Assessment page should be displayed in the same text case (not uppercase) as in the assessment templates.
1. Create assessment template with custom attributes
2. Generate assessment with this template
3. Open modal window with assessment info
4. Check that the attributes are not displayed in uppercase
Labels for attribute names have a css class with text-transform: uppercase. So removing this property allows to display these attributes in the initial case.
=> GGRC-5438 Remove uppercase style for asmt custom attributes

src/ggrc/access_control/roleable.py, src/ggrc/migrations/versions/20180627150313_26488ecb342a_fix_acr_ids_in_acl.py, src/ggrc/services/common.py, test/integration/ggrc/access_control/test_role_validation.py, test/integration/ggrc/integrations/test_assessment_integration.py
This PR doesn't fix ACL for Workflow items. It should be done in scope of GGRC-5492.
For some of access control list entries there are wrong access control roles (object_type are different). It lead to warnings on reindex.
Check migration: it should fix only broken items, user rights should be the same as before migration run.
Run reindex, check if there are no warnings for non-workflow models.
Fix broken acl entries in migration: delete rows if there is a duplicate with proper acr, update in another case.
Check correctness of access_control_list in object on POST and PUT.
=> GGRC-5433 Fix ACL with wrong ACR

src/ggrc-client/js/components/inline/inline-form-control.js
The app shows incorrect message if there was a conflict.
- Have an assessment
- Go to the other attributes tab and use inline edit to create a conflict with the notes field
Expected: Conflict error message should be shown
Actual: Cannot save error message is shown
Use `notifierXHR` that shows correct message based on xhr status
=> GGRC-5621 Use common error messages in Assessment inline edit

src/ggrc/services/resources/person.py, test/integration/ggrc/services/resources/test_person.py
PUT to /api/people/<id>/profile with full ISO string returns HTTP500
Run tests. 
Send PUT request to /api/people/<id>/profile with last_seen_whats_new:"2018-07-18T14:37:40.894Z"
SQL Alchemy can't compare offset-naive and offset-aware datetimes. I've brought dates to the same offset-naive type
=> [WIP] GGRC-5628 Can't PUT ISO time to person_profile

._license_header_exceptions, provision/docker/my.cnf, provision/docker/mysql/default_utf8.cnf, provision/docker/mysql/gtid_mode.cnf, provision/docker/mysql/log.cnf, provision/docker/mysql/packet_size.cnf
Enable GTID mode on docker db container, like on Cloud SQL instance in Google Cloud.
Some migrations with "CREATE TEMPORARY TABLE" or "CREATE TABLE ... SELECT" queries can pass local and kokoro tests, but fail in Google Cloud.
Add gtid_mode.cnf file with necessary settings to enable GTID mode. 
Add license header to all MySQL config files
=> GGRC-5648 Enable GTID mode on local dev db

src/ggrc-client/js/bootstrap/modal-ajax.js, src/ggrc-client/js/components/autocomplete/tests/autocomplete_spec.js, src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js, src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js, src/ggrc-client/js/components/tasks-counter/tests/tasks-counter_spec.js, src/ggrc-client/js/components/tests/datepicker_spec.js, src/ggrc-client/js/components/tests/mapped_tree_view_spec.js, src/ggrc-client/js/components/tests/reminder_spec.js, src/ggrc-client/js/controllers/contributions.js, src/ggrc-client/js/controllers/tests/modals_controller_spec.js, src/ggrc-client/js/controllers/tests/tree_view_controller_spec.js, src/ggrc-client/js/controllers/tests/tree_view_node_controller_spec.js, src/ggrc-client/js/controllers/tree/tree-view-node.js, src/ggrc-client/js/entrypoints/dashboard/bootstrap.js, src/ggrc-client/js/models/business-models/tests/cycle-task-group-object-task_spec.js, src/ggrc-client/js/models/tests/save_queue_spec.js, src/ggrc-client/js/plugins/component_registry.js, src/ggrc-client/js/plugins/tests/component_registry_spec.js, src/ggrc-client/js_specs/models/assessment_template_spec.js, src/ggrc-client/js_specs/models/display_prefs_spec.js, src/ggrc-client/js_specs/models/mappers_spec.js, src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js, src/ggrc-client/js_specs/mustache_helpers/get_default_attr_value_spec.js, src/ggrc-client/js_specs/mustache_helpers/get_item_spec.js, src/ggrc-client/js_specs/mustache_helpers/if_string_spec.js, src/ggrc-client/js_specs/mustache_helpers/model_info_spec.js
Multiple spaces are found before comments and variable assignment.
Run "eslint --format compact src/ | grep 'no-multi-spaces'" command. The list of errors should be empty.
Remove multiple whitespaces according to the [no-multi-spaces](https://eslint.org/docs/rules/no-multi-spaces) rule.
=> GGRC-5579 Fix eslint no-multi-spaces rule

src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, test/integration/ggrc/integrations/test_issue_integration.py, test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
"Issue GGRC has been deleted" occurred if turn off Issue Tracker
1. Create Issue GGRC with Issue Tracker turned on:
2. Open Edit Issue popup and turn off Issue Tracker
3. Click 'Ticket' link on Issue Info panel to open Issue Tracker
4. Look at the message: "GGRC object has been deleted. GGRC changes will no longer be tracked within this bug." is displayed
Actual Result: If user turns off Issue Tracker for Issue, Issue has been deleted is shown in Issue Tracker
Expected Result: "Changes to this GGRC object will no longer be tracked within this bug." should be displayed if turn off Issue Tracker
Fix incorrect message on turning off integration.
=> GGRC-5636 "Issue GGRC has been deleted" occurred if turn off Issue Tracker

src/ggrc/models/custom_attribute_definition.py, test/integration/ggrc/models/test_revision.py, test/integration/ggrc/services/test_custom_attributes.py
System don't have proper default value for custom attribute definitions of `Dropdown` and `Date` types
Create global custom definition of `Date` type and in the response check if the backend receive `default_value: ""`
Add into enum list new default values for custom attribute definitions of `Dropdown` and `Date` types
=> GGRC-5618 New default values for CAD

src/ggrc-client/js/components/assessment/assessment-generator-button.js, src/ggrc-client/js/components/mapped-counter/mapped-counter.js, src/ggrc-client/js/components/object-mapper/object-mapper.js, src/ggrc-client/js/components/related-objects/related-documents.js, src/ggrc-client/js/components/revision-log/revision-log.js, src/ggrc-client/js/components/tree/tree-item-extra-info.js, src/ggrc-client/js/controllers/contributions.js, src/ggrc-client/js/controllers/filterable_controller.js, src/ggrc-client/js/controllers/gapi_controllers.js, src/ggrc-client/js/controllers/lhn_controllers.js, src/ggrc-client/js/controllers/modals/approval-workflow-modal.js, src/ggrc-client/js/controllers/modals/gapi-modal.js, src/ggrc-client/js/controllers/modals/quick_form_controller.js, src/ggrc-client/js/controllers/tree/tree-view-node.js, src/ggrc-client/js/controllers/tree/tree-view.js, src/ggrc-client/js/models/mappers/base-list-loader.js, src/ggrc-client/js/models/mappers/cross-list-loader.js, src/ggrc-client/js/models/mappers/multi-list-loader.js, src/ggrc-client/js/modules/widget_descriptor.js, src/ggrc-client/js/pbc/workflow_controller.js, src/ggrc-client/js/plugins/autocomplete.js, src/ggrc-client/js/plugins/utils/current-page-utils.js, src/ggrc-client/js/plugins/utils/tree-view-utils.js
ES6 allow us to use the spread operator instead of .apply()
Run "eslint --format compact src/ | grep 'prefer-spread'" command. The list of errors should be empty.
All cases of using .apply with the same `this` argument are replaced with the spread operator ([prefer-spread](https://eslint.org/docs/rules/prefer-spread) rule)
=> GGRC-5584 Fix eslint prefer-spread issues

src/ggrc_workflows/__init__.py, src/ggrc_workflows/migrations/versions/20180720081024_96b11a5760ee_for_all_deprecated_cycles_need_to_set_.py, test/integration/ggrc_workflows/test_api_calls.py
Cycle is not moved to History If all cycle tasks have Deprecated state. 
**Actual Result:** Cycle is not moved to History If all cycle tasks have Deprecated state 
**Expected Result:** Cycle should be moved to History If all cycle tasks have Deprecated state
1. Create any workflow (e.g. Repeat off) 
2. In Setup tab create at least 3 tasks for task group 
3. Activate Workflow 
4. Go to Active Cycles tab 
5. Move all cycles tasks to Deprecated state 
6. Reload the page
7. Cycle should be moved to History If all cycle tasks have Deprecated state
Cycle will be current if his new status is not `Deprecated`, `Finished` or `Verified`
We assume that status `Finished` or `Verified` of the cycle make him `done` but `Deprecated` just change cycle status
Note: Expected behavior is cycle move to the …
=> GGRC-4222 Move Cycle to history when deprecated

src/ggrc/settings/default.py
=> Bump version up to 1.18.0-Strawberry

src/ggrc-client/js/components/view-object-buttons/view-object-buttons.mustache, src/ggrc-client/js/mustache_helper.js, src/ggrc-client/js_specs/spec_setup.js, src/ggrc/assets/mustache/assessments/assignable_extended_info.mustache, src/ggrc/assets/mustache/assessments/header.mustache, src/ggrc/assets/mustache/audits/dropdown_menu.mustache, src/ggrc/assets/mustache/base_objects/dropdown_menu.mustache, src/ggrc/assets/mustache/cycles/info.mustache, src/ggrc/assets/mustache/workflows/info.mustache
**GGRC-5098** Users with global role (not only admin) should see "Open <Object>" in the 3bb menu on info panel of object.
**GGRC-5685** "Open" button is missed for global Creator, Reader, Editor.
**GGRC-5715** Incorrect Assessment link in LHN
**GGRC-5098** 
1. Login as global creator / reader / editor
2. Open any tree view 
3. Open info panel of some object
Actual result: User doesn't see "Open object" in 3bb menu
Expected result: User should see "Open object" (e.g. "Open Program") in 3bb menu
**GGRC-5685**
1. Login as global creator / reader / editor
3. Search by any object, e.g. Control
4. Look at the Search results
Actual result: "Open" button is missed for Creator, Reader, Editor
Expected Result: "Open" button should be presented
**GGRC-5715**
1. Login as global …
=> GGRC-5098/GGRC-5685/GGRC-5715 Remove view_object_page permission check

src/ggrc/views/__init__.py
Document is not mapped in case when attaching a gdrive file and this document already exist in the system.
Actual result: The user is made an admin of the document but the document is not attached
Expected result: The document should be attached
1. Login as <user1>
2. Create a file in Gdrive, share it <user2>
3. Create a control, attach this gdrive file
4. Login as <user2> (not an admin)
5. Create a control, click attach -> Attach new -> choose this gdrive file.
6. Click Proceed in the warning
7. The document should be attached
When the user post the request to making him the admin of the attached document the system doesn't invalidate the permission cache and as the result the client receive cached permissions which are not contain the new one for document. 
**Note:** I use explicit call …
=> GGRC-5632 Add permission cache invalidation in doc

src/ggrc/migrations/utils/strip_text_field.py, src/ggrc/migrations/versions/20180731140314_d617da1998ef_trim_spaces_from_slugs.py, src/ggrc/models/mixins/__init__.py, src/ggrc_risks/migrations/versions/20180802075311_610cf459b347_trim_spaces_from_slugs.py, src/ggrc_workflows/migrations/versions/20180802073238_c17f5f1f273e_trim_spaces_from_slugs.py, test/integration/ggrc/models/test_audit.py, test/unit/ggrc/migrations/__init__.py, test/unit/ggrc/migrations/utils/__init__.py, test/unit/ggrc/migrations/utils/test_strip_text_field.py
User can create objects with 'Code' field with leading or trailing spaces.
* Try to create any object with invalid 'Code' field contains any number of leading and / or trailing whitespaces.
* Check that this object is created without leading and / or trailing whitespaces.
SLUG validation has been extended. Now it trim invalid SLUGs contains leading and trailing whitespace.
=> GGRC-4256 Trim leading and trailing spaces in 'Code' field from all objects

src/ggrc-client/js/plugins/utils/ca-utils.js
Use default_value in Assessment LCA.
If FE will send null (empty date LCA), conflict resolution does not work correctly.
Clear Date or DD LCA and see that empty value has been sent.
1) Initialize CAV with default value (case when we create new Assessment)
2) Use default value when clear CAV
=> GGRC-5622 Use default_value in Assessment LCA

src/ggrc/models/mixins/__init__.py
Warning about trimming spaces in slugs appears in console, even when create object with slug without leading or trailing spaces.
* Try to create any object with valid 'Code' field not contains leading and trailing whitespaces.
Expected result: warning about trimming spaces in console is not appeared.
Added an expression before logging, which verifies that the slug was trimmed.
=> QUICK-FIX Logging valid SLUGs as SLUGs with leading or trailing spaces 

test/integration/ggrc/services/test_query/test_updated_at.py
Since updated_at query API requests functionality works as designed and there are no tests to confirm it, we should cover it with tests.
Just run tests 
Tests for Query_API request for updated_at field were added. I've tested IN and NOT IN operators.
=> GGRC-5554 Test Query API for updated_at field

src/ggrc/models/hooks/issue_tracker/common_handlers.py, test/integration/ggrc/integrations/test_issue_integration.py
If create Issue with reference Url, a message with empty comment is added to Issue Tracker
1. Create GGRC Issue with Reference url and Issue Tracker turned ON:
2. Click on the Ticket link to open Issue in Issue Tracker
3. Look at the message
Actual Result: If create Issue with reference Url, a message with empty comment is added to Issue Tracker
Expected Result: If create Issue with reference Url, a message with empty comment should not be added to Issue Tracker
All mapping operations was handling in `handle_comment_creation_event`. I have added check in event handler that mapped object is comment. Also I have added integration test for it.
=> GGRC-5703 If create Issue with reference Url, a message with empty comment is added to Issue Tracker

src/ggrc/services/resources/person.py, test/integration/ggrc/services/resources/test_person.py
POST request to people/profile endpoint fail with internal server error (status code - 500):
AttributeError: 'NoneType' object has no attribute '_inflector'
Send POST request to /api/people/id/profile (example: /api/people/150/profile), response should be 405 Method Not Allowed
Update PersonseResource class with method that raise "405 Method Not Allowed" response when server handle POST request
=> GGRC-5496 Fix POST request to people/profile endpoint

src/ggrc/cache/utils.py, src/ggrc/migrations/versions/20180627104424_385ee48cd6b9_add_acr_for_background_tasks.py, src/ggrc/models/background_task.py, src/ggrc_basic_permissions/roles/Creator.py, src/ggrc_basic_permissions/roles/Editor.py, src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc/models/hooks/acl/test_bg_task_roles.py, test/integration/ggrc_workflows/test_workflow_api_calls.py
The bug here is that when the FE polls at /api/background_tasks?id__in=42 (where 42 is the id) the BE replaces the info about the Background Task with null because the check for read permissions returns no access for the current user Global Creator. The check is done in an invalid way because the permission for Background Tasks is specified with a condition (which uses a complete instance of a Background Task object), but is checked with just object type + global context (where the Global Creator doesn't have any permissions for Background Tasks). See the block starting here: https://github.com/google/ggrc-core/blob/5bc2897499e5be5858798a23362e5f089e02e6dd/src/ggrc/services/common.py#L1400
1. Login as global creator  (reproduced for reader and editor as well)
2. Open audit with many …
=> GGRC-5711 Add Background task ACL

src/ggrc/migrations/versions/20180815130731_b992a3d51db6_rename_sections_to_requirements.py
JS error occurs while opening Change Log tab on Program Info page.
Section model was renamed to Requirement, but on server side it still named
as Section in `revisions.destination_type`.
1. Download ggrcdev_backup-2018-06-13
2. Run `db_reset ggrcdev_backup-2018-06-13.sql` and launch application
3. Open https://127.0.0.1:8080/programs/2009#!info link
4. Click Change Log tab on Program Info page
**Expected Result:** no error is shown in browser conslole
Created migration that renames sections to requirements in definition_type field of revisions.
=> GGRC-5852/GGRC-5767 JS error occurs while opening Change Log tab on Program Info page.

src/ggrc/views/converters.py, test/integration/ggrc/services/resources/test_converters.py
If you import file with special symbols in filename and then download it from import history you can see unexpected behavior.
1. Download csv template for any object;
2. Fill out required fields and Save csv file;
3. Rename csv file with special symbols, e.g. "!@@#$$#$%"
4. Import csv template
5. Download imported csv template from Import History
Actual Result:
csv file is downloaded like csv, html or return network error
GET 'failed' is not displayed in dev tools (Network) 
Expected Result: Imported csv file that contains special symbols in title should be dowloaded from Import History 
Not all OS support special symbols "/#?" in file names. So I made filename validation that restrict user to import file with special symbols.
=> GGRC-4920 Downloading of csv file failed if csv file contains special symbols in title

src/ggrc/migrations/versions/20180816123728_888972f313a7_rename_sections_to_requirements.py
this is a fix for the previous PR: https://github.com/google/ggrc-core/pull/8288
When we rename sections, we added an [migration](https://github.com/google/ggrc-core/pull/8071/files#diff-a22b65a5b08711b783c08afac2e4aa96) that misses `destination_type` field in revisions
table. Some values of `destination_type` field of revisions table in DB still named as 'Section' instead 'Requirement'. That is the cause bug on FE which we fixed in
[8288](https://github.com/google/ggrc-core/pull/8288), but some values of `source_type` in revisions table still named as 'Section'. This can cause similar problems.
To make shure that revision table don't contains 'Section' instead 'Requirement'
execute this query:
```sql
select count(*) from revisions where destination_type = "Section" or source_type = …
```
=> GGRC-5767 Rename 'Section' to 'Requirement' in source_type of revisions

src/ggrc_workflows/models/cycle_task_group_object_task.py, src/ggrc_workflows/notification/data_handler.py, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
The related objects is already defined for cycle tasks with the
Relatable mixin. To have all objects consistent it is better to use that
instead of overriding it in a special way.
Check if related objects still work fine on cycle task notifications. and if they are correctly displayed on cycle task page.
Remove the overriding property and replace its usages with the same named function from Relatable mixin.
=> QUICK-FIX Remove redundant related_objects property

src/ggrc/models/background_task.py, src/ggrc/utils/__init__.py, src/ggrc/views/__init__.py, test/integration/ggrc/models/hooks/acl/test_bg_task_roles.py, test/integration/ggrc/services/test_delete.py
Time required for adding comments to assessment was increased in 1.19-Strawberry comparing with 1.18-Strawberry (from 5s to 7s).
1. Log in to GGRC-PERF https://ggrc-perf.appspot.com/audits/4567#!assessment
2. Open Assessment Info panel (title = 'Check timing') https://ggrc-perf.appspot.com/assessments/24643
3. Type comment to comment box and click Add button: saving time is 7.1 sec / 6.8 sec / 7.27 sec / 6.5 sec
*4. Select 'no' option from dropdown lca, type comment and click Save button: saving time is *7.12 sec / 7.15 sec / 7.17 sec
Actual Result: Performance for saving comment decreases and equals 7.1 sec / 6.8 sec / 7.27 sec / 6.5 sec
Expected Result: comment saving time should be ~ 5 sec
Load time: https://docs.google.com/spreadsheets/d/1gNrun5Gm-IOF5xXDB3YbRfRS_ru_ppctF2KiwDShDT0/edi …
=> GGRC-5881 Fix performance for comment adding

docs/source/contributing/git/how_to_write_a_commit_message.rst
This is a minor update to our git commit message documentation meant for backmerges where merge commit conflicts can occur. 
To check this PR, just make sure the new addition makes sense and that there aren't any grammatical mistakes.
=> QUICK-FIX Update git commit message documentation

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Switch Assessment Info-pane to "Deferred Transaction" mechanism without delays for comments on assessments, comments on LCA and adding evidence URL.
Impact:
UI acceleration for 1s for comments and evidences
Add comment or evidence url to an assessment and see that there is no 1s lag between "create" and "map" requests.
Use 'execute' method instead of 'push'
=> GGRC-5890 Use "execute" instead of "push" when map objects

src/ggrc-client/js/components/inline/inline.js
Conflict resolution for notes field
Go to the other attributes tab and use inline edit to create a conflict with the notes field
Expected: Conflict error message should be shown
Actual: Cannot save error message is shown
Just trim string value, do not set null.
=> GGRC-5621 Fix inline edit string trimming

src/ggrc-client/js/components/import-export/download-template/download-template.js, src/ggrc-client/js/components/import-export/download-template/download-template_spec.js, src/ggrc-client/js/components/import-export/import-export-utils.js, src/ggrc/views/converters.py, test/integration/ggrc/__init__.py, test/integration/ggrc/converters/test_assessment_csv_template.py, test/integration/ggrc/converters/test_audit_csv_template.py
Remove evidence file from audit/assessment import template
Download template, check that 'Evidence File' is absent
Added endpoint for downloading of templates.
=> GGRC-5177 Remove evidence file from audit/assessment import template

src/ggrc-client/js/apps/workflows.js, src/ggrc-client/js/models/mappers/tests/mappings_spec.js
Currently, Unified Mapper contains Workflow object type. But user cannot map entity to workflow directly. 
1. Log to GGRC and open All objects/My Work page
2. Open any tab, e.g. Regulations
3. Hover over gear icon for any Regulation in treeView and click Map to this object
4. Click on Object type list
**Actual Result:** Workflow object is displayed in Object type list in Unified Mapper
**Expected Result:** Workflow object should not be displayed in Object type list in Unified Mapper
Remove Workflow from mappings config.
=> GGRC-5937 Remove Workflow from Unified Mapper options

src/ggrc/migrations/versions/20160119143508_262bbe790f4c_import_squashed_migrations.py, src/ggrc/migrations/versions/ggrcdev.sql
There should not be any objects without revisions on an empty database.
The entry deleted here was due to a bug on how the old migration worked
on an empty db, when it created an invalid entry.
Second change is updating the title of the migration to display the
correct version from which the squash was created.
Check that the migrations still work.
- reset the database
- create a new object
- mark it for new revision manually,
- run the create missing revisions command
I have just removed an invalid entry from the initial dump. Since db reset makes an empty database there can not be any object that would have a missing revision (for prepopulated objects we do not store revisions)
=> QUICK-FIX Update initial migration

src/ggrc-client/js_specs/models/display_prefs_spec.js, src/ggrc-client/js_specs/models/local_storage_spec.js, src/ggrc-client/js_specs/models/mappers_spec.js
PR fixes 'There should be no space after '{' (object-curly-spacing)' eslint error.
=> GGRC-5591 Fix eslint object-curly-spacing rule

src/ggrc-client/js_specs/models/display_prefs_spec.js, src/ggrc-client/js_specs/models/local_storage_spec.js, src/ggrc-client/js_specs/models/mappers_spec.js
PR fixes 'There should be no space before '}' (object-curly-spacing)' eslint error.
=> GGRC-5592 Fix eslint object-curly-spacing rule

src/ggrc-client/js/controllers/lhn_controllers.js, src/ggrc-client/js_specs/models/cacheable_spec.js, src/ggrc-client/js_specs/models/mappers_spec.js
PR fixes 'Unexpected space(s) after '{' (block-spacing)' eslint error.
=> GGRC-5589 Fix eslint block-spacing rule

src/ggrc/converters/errors.py, src/ggrc_workflows/converters/handlers.py, test/integration/ggrc_workflows/converters/test_task_group_import.py
It is possible to import TaskGroup with existing slug and map it to different workflow.
Slightly different with ones described in the ticket as better reproduce the root cause of the issue.
1. Create Workflow1.
2. Create TaskGroup1 with slug 'TG-1' mapped to Workflow1.
3. Create TaskGroupTask1 mapped to TaskGroup1.
3. Create Workflow2 with slug 'WF-1'.
4. Import TaskGroup with slug 'TG-1' and Workflow with slug 'WF-2'
**Actual result:** TaskGroup1 is mapped to Workflow2 and contains TaskGroupTask1 mapped.
**Expected result:** error 'TaskGroup 'TG-1' already exists at the system and mapped to another workflow. Please use different code for this TaskGroup.' should appear during import. TaskGroup1 shouldn't be mapped to Workflow2.
Handler for workflow column in task groups has been fixed to …
=> GGRC-5551 It is possible to map TaskGroup to another wf via import

src/ggrc/builder/json.py, src/ggrc/contributions.py, src/ggrc/notifications/common.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/views/__init__.py, src/ggrc_workflows/notification/notification_handler.py, src/ggrc_workflows/notification/pusher.py, test/integration/ggrc/__init__.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py, test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py, test/integration/ggrc_workflows/notifications/test_wf_notifs_generator.py, test/integration/ggrc_workflows/test_api_calls.py
During cycle tasks status update lots of queries are sent to db. This locks notifications table, slow done cycle tasks update and cause 500 error if many tasks' statuses are updated sequentially.
Change state of multiple cycle tasks (check scenarios for various state). Call `$.post("/admin/generate_wf_tasks_notifications");` to process cycle tasks notifications.
Check the result both in db and with `/_notifications/show_daily_digest` call.
Notifications processing  on cycle tasks status change has been moved out of hooks to separate cron job. Now only notifications on task status `Declined` is generated in hook. Besides, json handler for `Date` field has been fixed to get rid of several redundant queries on cycle task status put.
=> GGRC-5345,GGRC-4864,GGRC-5240 Generate cycle tasks status change notifications in cron job

src/ggrc/migrations/versions/20180906085124_b2cdde0ea7b5_add_info_about_object_and_operation_to_.py, src/ggrc/models/all_models.py, src/ggrc/models/background_operation.py, src/ggrc/models/background_operation_type.py, src/ggrc/models/background_task.py, src/ggrc/views/__init__.py, test/integration/ggrc/__init__.py, test/integration/ggrc/integrations/test_bulk_issue_generate.py
FE need to have information about status of bulk issuetracker create operation that was run. Existing /api/background_tasks/<id> endpoint can't be used as bg task id will be lost if user update page, or if he try to open this page from other tab/window. But by our requirements, if user start bulk tickets creation, he shouldn't be able to run it again until previous one will not be finished.
Send GET request to '/background_task_status/<object_type>/<object_id>'
See tech dock in GGRC-4603 ticket.
=> GGRC-5958 Implement background task status endpoint

src/ggrc-client/js/components/issue-tracker/generate-issues-in-bulk-button.js, src/ggrc-client/js/components/issue-tracker/templates/generate-issues-in-bulk-button.mustache, src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache, src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js, src/ggrc-client/js/controllers/info_pin_controller.js, src/ggrc-client/styles/components/info-pane/_info-pane.scss, src/ggrc/assets/mustache/audits/info.mustache
As a user with 'Edit' rights for an Audit, I would like to generate in bulk tickets for each assessment in scope of this audit, that is not linked to a ticket yet.
Create new `generate-issues-in-bulk-button` component to initiate generating issues on BE.
=> GGRC-4858 FE: Allow to generate issues in bulk

src/ggrc/integrations/issuetracker_bulk_sync.py, src/ggrc/settings/default.py, src/ggrc/templates/notifications/bulk_sync_exception.html, src/ggrc/templates/notifications/bulk_sync_failed.html, src/ggrc/templates/notifications/bulk_sync_succeded.html, src/ggrc/templates/notifications/style.html, test/integration/ggrc/integrations/test_bulk_issue_generate.py
Send mail notifications on succeeded and failed issuetracker bulk tickets generation (only for Assessments in scope of Audit - /generate_children_issues).
See mockups in Jira ticket GGRC-4603
Create tickets for Assessments in Audit, check receiving mail (should be tested on instance with working email notifications).
See tech doc in Jira ticket GGRC-4603.
=> GGRC-5959 Send notifications on bulk issuetracker tickets generation

src/ggrc/migrations/versions/20180917130840_eabcf439ab5d_create_issuetracker_issues_for_all_.py
For Assessments and Audits older 2017-08 related IssueTrackerIssue object can be missing. It can be a problem for bulk tickets creation as bulk functionality suppose that every Issuetracked object has related IssuetrackerIssue.
Check existence of Assessments/Audits without IssuetrackerIssues before migration, run migration and check that missed objects were created, revisions for these objects should be created after "create revisions" run.
Find missing objects by 
```
SELECT a.*
FROM assessments a
LEFT JOIN issuetracker_issues ii ON ii.object_id = a.id AND ii.object_type = 'Assessment'
WHERE ii.id IS NULL;
```
query and create them. Create revisions for them also.
=> GGRC-6038 Create missing IssuetrackerIssues for Assessments and Audits

src/ggrc-client/js/components/import-export/export-panel.js, src/ggrc-client/js/components/import-export/panel.js, src/ggrc-client/js/components/import-export/test/export-panel_spec.js, src/ggrc-client/js/components/import-export/test/panel_spec.js, src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
Export button is not disabled if there is more then 1000 columns in sheet.
3. In the assessments tab click on Export Assessments in 3 dot's menu
4. Look at the Export button: is not disabled while "Exports are currently limited to maximum of 1000 columns per file." message is shown
**Actual Result:** Export button is not disabled if there is more then 1000 columns in sheet
**Expected Result:** Export button should be disabled if there is more then 1000 columns in sheet
Case is reproducible only when panel initially has invalid configuration (when user is redirected from Assessments page). It happens because canJs is not recalculate `exportAllowed` prop in `csv-export` component after selecting all options in `export-panel` component.
As a …
=> GGRC-5934 Disable export button if selected more than 1000 attributes

src/ggrc/models/revision.py, test/unit/ggrc/models/test_revision.py
Version history 'Review & Restore' js errors.
Open  'Version history -> 'Review & Restore' for objects created before 1.24
Added revision population for os_state
=> GGRC-6071 Fix object review revisions

src/ggrc/migrations/versions/20180917154533_5c83e0840a71_migrate_old_review_to_new.py
This PR is `on hold` until the PO confirmation.
We need to migrate objects became non reviewable
We need to process objects mapped to CycleTaskGroupObjectTasks related to object review only. 
Run migrations and check that proper CycleTaskGroupObjectTasks are unmapped. 
Foe instance ggrc-test dump /products/1 is mapped to 4 CycleTaskGroupObjectTasks one of them object review related.
Added processing of list of objects thats became non reviewable.
Added filter to SQL query CycleTaskGroupObjectTasks.title starts with 'Object review for'
=> GGRC-6073 Fix object review migration

src/ggrc/models/relationship.py
Fix for "send_daily_digest_notifications" task for destinations/sources that don't exists
Run "send_daily_digest_notifications" task for objects without "source" or "destination"
Populate "sources" and "destinations" with exception check. If exception appears, object won't be add
=> GGRC-6086 Fix "send_daily_digest_notifications" task without "destination"

src/ggrc-client/js/components/object-review/templates/request-review-modal.mustache, src/ggrc-client/styles/components/object-review/_request-review-modal.scss
Scroll is not appear If we add a lot of reviewers on the Request Review popup. The bottom of the modal window with the Request button can be hidden.
1. Open any object (e.g. Control)
2. Click Request Review button
3. Add at least 10 people (it depends on the size of the browser window)
Actual Result: Scroll is not appear in Request Review popup
Expected Result: Scroll should appear in Request Review popup
Add `max-height` to the modal content (reviewers list + comment). Header with the 'An email notification will be sent to each reviewer' subheader and Request button are static and should always be shown. So `max-height` of the content equals 100% minus header and footer height.
=> GGRC-6066 Add scroll to the Request Review modal

src/ggrc/login/__init__.py, src/ggrc/login/appengine.py, src/ggrc/login/noop.py, src/ggrc/rbac/permissions.py, src/ggrc/services/common.py, src/ggrc/utils/errors.py, src/ggrc/utils/user_generator.py, src/ggrc_basic_permissions/__init__.py, src/ggrc_workflows/__init__.py, test/integration/ggrc/utils/test_user_generator.py, test/integration/ggrc_basic_permissions/test_external_login.py, test/unit/ggrc/login/test_appengine.py, test/unit/ggrc/test_login.py
We need to be able to provide GGRCQ service account rights to any GGRC user on call from GGRCQ as a trusted source.
The behavior:
1. New x-external-user header should be added. 
2. 
- If the user doesn't exist in GGRC, create new user with Global Creator role.
- If exists use the existing user
3. Create the object requested by the external system. Permissions should be checked by service account
4. Put in modified by field the user that was specified in x-external-user header.
5. Corresponding revisions needs to be created
**Note**: Please keep backward compatibility. Request can be done without X-external-user header, in that case X-external-user will equals to X-ggrc-user.
Use the postman collection for testing that you can find in JIRA.
Set ALLOWED_QUERYAPI_APP_IDS and …
=> GGRC-5985 Allow external users work on behalf their account

src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py, src/ggrc/integrations/synchronization_jobs/sync_utils.py, test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Fix for reduce synchronization a lot of Issue Tracker records without changes
Run Issue Tracker synchronization job for assessment with and without changes. Only records with changes should be send.
Run tests (unit and integration)
Update implementation for Assessment CCs synchronization, check current CCs state and previous
=> GGRC-6115 Update CCs for Issue Tracker synchronization

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/integration/ggrc/integrations/test_assessment_integration.py
Auditors are displayed in CC list in Issue Tracker
Create Audit with audit captains and auditors, only audit captains should be in "reporter" and "ccs"
Update audit hook with validation for audit captains
=> GGRC-6134 Auditor is displayed in CC list in Issue Tracker

src/ggrc-client/js/models/business-models/cycle.js, src/ggrc-client/js/models/business-models/directive.js, src/ggrc-client/js/models/business-models/policy.js, src/ggrc-client/js_specs/models/object_state_spec.js
State column is missed in treeView for Policy object
1. Create a Policy
2. Open My work page > Policies tab
3. Open 'Set visible fields for Policy' popup
Actual Result: State column is missed in treeView for Policy object
Expected Result: State should not be missed in treeView for Policy object
All policy attributes from attr_list are presented in Directive except 'Kind/Type', so we should extend `Directive` list, not `Cacheable`.
=> GGRC-6084 Show State column in treeView for Policy object

src/ggrc/migrations/versions/20180831103643_cb58d1d52368_create_missed_revisions_for_ct_unmapped_objects.py, src/ggrc_workflows/notification/data_handler.py, test/integration/ggrc_workflows/notifications/test_data_handler.py
Some objects that was previously mapped to CycleTasks and then unmapped don't have revisions for some reason on ggrc-test. This cause `nightly_cron_job` failure. Among them Programs and Audits. 
To fix the problem:
1. Appropriate revisions should be generated.
2. To avoid cron job failure in the future check if revisions exist is added. If there is no such revision, warning is logged; notification is sent without the information about unmapped object.
=> GGRC-5709 CycleTasks unmapped objects' missed revisions crash nightly_cron_job

src/ggrc/models/assessment.py, src/ggrc/models/assessment_template.py, src/ggrc/models/audit.py, src/ggrc/models/mixins/issue_tracker.py, src/ggrc/models/requirement.py, test/integration/ggrc/fulltext/test_total_reindex.py, test/integration/ggrc/models/test_assessment_template.py, test/integration/ggrc/models/test_query_api_queries.py
`Audits`, `Assessments`, `Issues` and `Requirements` has non-constant number of queries when doing a query API with different number of queried objects.
The reason of this for `Audits`, `Assessments`, `Issues` is loading of `issuetracker_issue` for every object. 
The reason of the issue for `Requirements` is loading of `notes` for every object
Some reference numbers (before the change):
1. Audit
10 objects: 26 db queries
20 objects: 36 db queries
2. Assessment
10 objects: 41 db queries
50 objects: 121 db queries
3. Issue
10 objects:  27 db queries
21 objects: 38 db queries
4. Requirements
10 objects: 27 db queries
50 objects: 67 db queries
Check the number of queries fired when opening assessment/audit/issues/requirements tab before and after the change. 
Change the number of loading …
=> GGRC-5771 Query API performance of IssueTracked objects

src/ggrc-client/js/controllers/dashboard_widgets_controller.js, src/ggrc-client/styles/_widget.scss, src/ggrc-client/styles/components/tree/_tree-view.scss, src/ggrc-client/styles/layout/_content.scss, src/ggrc-client/styles/modules/_tree-header.scss
When any element of tree view is expanded it's width becomes wider than the header and as a result the expanded element is not been overlapped by header when scrolling down.
Precondition:
Have multiple elements of any type (e. g. Control)
1. Go to 'All Objects' -> open Controls tab
2. Hover over gear icon of any element in the table
3. Select 'Expand Subtree'
4. Scroll down
Expected behavior: Expanded element is covered by the header. 
Remove default margins from top container and change w/ appropriate margins only in places where needed.
=> GGRC-5486 Make 'tree-header' overlap expanded table element

src/ggrc/gdrive/errors.py, src/ggrc/gdrive/file_actions.py, test/unit/ggrc/models/test_file_actions.py
Need to change logged message if user which is authorized in google drive hasn't permissions for  file what he tries to add in Control.
Related tickets:
**GGRC-5147** 500 error when attaching a file to the folder the user doesn't have edit access to
**GGRC-5843** 'There was an error' (POST 500) is displayed if user attaches a file to the folder in which he has 'view only' permissions
Steps:
1. Login as `<user1>`
2. Create a `control-1`. Assign a new folder and attach a file.
3. Assign `<user-2>` as Secondary Contact in the control created by `<user1>`.
3. Login as `<user2>` that has access to Document object but doesn't have access to the file that was attached by <user-1>.
4. Create a `control-2`. Assign a new folder to `control-2`.
5. Try to map a document added by `<user1>`.
Actual …
=> GGRC-5227 500 error when map a document of file you don't have read access to

src/ggrc-client/js/components/related-objects/related-urls.js, src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
'Add' reference url button should be displayed on create new object modal under Global creator.
1. Log as Global creator user and invoke any new object popup, e.g. Standard.
2. Look at the Reference URL: Add button is missed.
Actual Result: 'Add' reference url button is not displayed in new object popup under Global creator.
Expected Result: 'Add' reference url button should be displayed.
Use `isNew()` to check if user creates new object.
=> GGRC-5512 'Add' reference url button is not displayed in new object popup under Global creator

src/ggrc/bootstrap.py, src/ggrc/login/appengine.py, src/ggrc/login/noop.py, src/ggrc/services/common.py, src/ggrc/utils/user_generator.py, test/integration/ggrc/utils/test_user_generator.py, test/integration/ggrc_basic_permissions/test_external_login.py
The creation of new user and adding a creator role to the user should not contain flush, commit and log_event.
One bug that caused by this design is the following:
When you send the request to create an object (e.g. Market) using X-ggrc-user and X-external-user the following revisions are created:
```
mysql&gt; select id, resource_id, resource_type, event_id, action,modified_by_id from revisions;
+----+-------------+---------------+----------+----------+----------------+
| id | resource_id | resource_type | event_id | action | modified_by_id |
+----+-------------+---------------+----------+----------+----------------+
| 1 | 2 | PersonProfile | 2 | created | 2 |
| 2 | 2 | Person | 2 | created | 2 |
| 3 | 3 | Context | 2 | created | 2 |
| 4 | 3 | PersonProfile | 3 | created | 3 |
| 5 | 4 | …
```
=> GGRC-6120 Remove flush and commit from user creation

src/ggrc/converters/handlers/handlers.py, src/ggrc/models/mixins/with_mappimg_via_import_handable.py, src/ggrc/models/review.py, src/ggrc/services/signals.py, test/integration/ggrc/converters/test_import_reviewable.py, test/integration/ggrc/models/factories.py
If unmap / map snapshottable object via import, objects are not reverted to "unreviewed" state
If add a comment via import, Control is reverted to Unreviewed state
If add reference url via import, Control is reverted to Unreviewed state
If Import control w/o changes, Control is reverted to Unreviewed state
If change ACL role via import, Control is reverted to Unreviewed state
Map "snapshottable" objects with "reviewed" state via import, state should be reverted to "unreviewed"
Update signal handlers with check on "snapshottable" state
=> GGRC-6088, GGRC-6087, GGRC-6080, GGRC-6076, GGRC-6079 Revert to "Unreviewed" state via import "snapshottable" objects

src/ggrc-client/js/controllers/lhn_controllers.js
When results is very big (>34 000) then because of 'replace' method exception occurs (Maximum call stack size exceeded).
"Uncaught RangeError: Maximum call stack size exceeded" occurred if expand Assessments in LHN 
Have more than 34 000 assessments (use dump from ggrc-test).
2. Open LHN
3. Expand Assessments
Actual Result: "Uncaught RangeError: Maximum call stack size exceeded" occurred. The list of Assessments in not shown up.
Expected Result: no errors should be shown. The list of Assessments should be displayed.
Use `attr` instead of `replace`.
`replace` calls `splice` with too much arguments, when `attr` manually resets items.
=> GGRC-6155 JS error occurs if expand Assessments in LHN

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, test/integration/ggrc/converters/test_export_ticket_tracker.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
It should be possible to link existing Assessments to existing Issue Tracker tickets, relink existing Assessments and create new ticket for linked Assessment.
- Apply changes from [#8311](https://github.com/google/ggrc-core/pull/8311) to turn on FE functionality
- Apply changes from  https://github.com/google/ggrc-core/pull/8395) Implement BE functionality for creating linked Assessment, to turn on linking for new Assessments
- These changes with applied [#8311](https://github.com/google/ggrc-core/pull/8311) and [#8372](https://github.com/google/ggrc-core/pull/8372) have been deployed to maximb-ggrc-5899  ggrc-test instance to have opportunity to click through the app.
- ### check test cases from …
=> GGRC-5899  Implement BE functionality for linking Assessments to Issue Tracker

src/ggrc/fulltext/mixin.py, src/ggrc/views/__init__.py
Fulltext records db inserting now is implemented using sqlalchemy core construction (db.session.execute(_table_.insert(), data_dict). Such inserting is quite unperformant, it’s faster to use raw SQL.
Tests were done locally on ggrc_test dump (2018-09-27)
Without fix:
100 Assessments: 1.6s average 
All assessments (33591): 497.00s
Total reindex time: 978.14s
Archiving big Audit (4519): 72.29s
With fix:
100 Assessments: 1.2s average
All assessments: 370.66s
Total reindex time: 736.11s
Archiving big Audit (4519): 44.95s
Run reindex with and without fix and compare results, run POST/PUT on huge Assessment and check time.
Expected result: time with fix decreased.
Replace SQLAlchemy insert/delete to row SQL.
Replace commit with plain_commit.
To get object ids load id only instead of whole …
=> GGRC-5848, GGRC-5851 Rewrite index records insert to row SQL

src/ggrc-client/js/bootstrap/sticky-popover.js, src/ggrc-client/js_specs/models/mappers_spec.js, src/ggrc-client/js_specs/mustache_helpers/debugger_spec.js, src/ggrc-client/js_specs/mustache_helpers/get_permalink_for_object_spec.js
PR fixes "Block must not be padded by blank lines (padded-blocks)" eslint error.
=> GGRC-5601 Fix eslint 'padded-blocks' rule

src/ggrc/notifications/common.py, src/ggrc/views/__init__.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py, test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py, test/integration/ggrc_workflows/notifications/test_wf_notifs_generator.py, test/integration/ggrc_workflows/test_api_calls.py
There was an issue in CycleTasks notifications generation job for show_daily_digest case (notifications retrieving logic was incorrect).
To test changes locally:
1) Reset db;
2) Create and activate wf with CycleTasks;
3) Change state of CycleTasks and generate notifications with $.post("/admin/generate_wf_tasks_notifications"). Check the result in the db and via '_notifications/show_daily_digest' endpoint.
=> GGRC-6183 Fix cycle tasks notifications generation job

test/integration/ggrc/converters/test_import_assessments.py
one test randomly fails with error:
```
====================================================================== A 
FAIL: Test changing state of Assessment with unfilled mandatory CA A 
---------------------------------------------------------------------- A 
Traceback (most recent call last): A 
File "/vagrant/test/integration/ggrc/converters/test_import_assessments.py", line 305, in test_error_ca_import_states A 
self._check_csv_response(response, expected_errors) A 
File "/vagrant/test/integration/ggrc/__init__.py", line 253, in _check_csv_response A 
expected_str, response_str)) A 
AssertionError: Expected response does not match received response: A 
EXPECTED: A 
{ A 
"Assessment": { A 
"block_errors": [], A 
"block_warnings": [], A 
"row_errors": [ A 
"Line 3: Field 'State' validation …
```
=> QUICK-FIX Skip randomly failing import test

src/ggrc/access_control/roleable.py, src/ggrc/models/assessment.py, src/ggrc/models/control.py, src/ggrc/models/evidence.py, src/ggrc/models/mixins/attributable.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/models/mixins/with_evidence.py, src/ggrc/models/object_document.py, src/ggrc/models/product.py, src/ggrc/models/review.py, test/integration/ggrc/fulltext/test_total_reindex.py, test/integration/ggrc/models/mixins/test_with_similarity_score.py
Now we often load whole object fields on reindex when we need just several columns, for some models we don't eagerly load necessary data so it's queried on each access.
Run reindex with and without changes from this PR.
Expected result: Reindex works faster on this PR changes.
Tested it on ggrc_perf_db-benchmark-data-v1.26.0-2018-10-08 backup.
Reindex without fix: 743.55s
Reindex with fix: 579.07s
Add necessary objects loading to `indexed_query()`. Load only required fields in base mixins.
Remove indexed mixin from Review model as it's useless here.
=> GGRC-5850 Optimize reindex objects loading

src/ggrc/models/review.py, test/integration/ggrc/review/test_status_auto_update.py
Reviewable does not get review status updated from reviewed to unreviewed on changes to custom attributes, if custom attribute value already existed.
1. Reproduce:
- Add instance of any reviewable
- Create global custom attribute for this reviewable
- Add value to the global custom attribute of the instance
- Set review status of the instance to reviewed
- Update the global custom attribute value (review status should go to unreviewed, but does not)
2. Run integration tests
Custom attribute values are related instances to custom attributable, thus their changes are not visible immediately. The solution is to go over custom attribute values and check attribute_value attribute history. Much like in [autostatuschangable.py](https://github.com/google/ggrc-core/blob/dev/src/ggrc/models/mixins/a …
=> GGRC-6082 Fix bug when review status is not updated for customattributable

src/ggrc-client/js/controllers/inner-nav-controller.js
At current moment 'count' attribute in 'update_widget' initializes based on value from template. The template was changed and this value will never be populated any more. Need to refactor this control and appropriate template.
1. Open 'Dashboard' page
2. Inspect 'Navigation' section in the top
Expected behavior: Objects's counts are displayed in the following format: ```"ObjectName" (ObjectCount)```.
Logic that populates attributes values from template was changed to get data from appropriate element passed to method as parameter.
=> GGRC-6021 Fix obsolete logic for 'has_count' init in 'inner_nav_controller' module

src/ggrc/models/comment.py, test/integration/ggrc/models/mixins/test_with_action.py
Field `custom_attribute_revision` was null in response after saving comment
- Create Audit (Title)
- Create Control (Title and Assertions fields)
- Map Control to Audit from gear menu of Audit (Object type=Control, after Governance in GUI)
- Open Audit in new tab via gear menu. Create Assessment Template for Audit: "Create Template->Create new assessment template", Default Assessment Type : Control, Title, Custom Attributes type Dropdown (add values), "Add field", set checkboxes "Comment required"
- Open Assessment tab. From "three dots" menu Generate Assessment for Audit from template with Control
- Open Assessment, select value and add comment
- Look to the field `custom_attribute_revision` in the response of request to /api/comments
In property `custom_attribute_revision` self.revision …
=> GGRC-6198 Fix returning custom_attribute_revision after saving comment

src/ggrc-client/js/components/object-review/object-review.js, src/ggrc-client/js/components/object-review/request-review-modal.js, src/ggrc-client/js/components/object-review/templates/object-review.mustache, src/ggrc-client/js/components/object-review/templates/request-review-modal.mustache, src/ggrc-client/js/components/object-review/tests/object-review_spec.js, src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js, src/ggrc-client/styles/components/object-review/_request-review-modal.scss
As a user I want to be allowed to request a review for an already reviewed object. Such request will revert it into unreviewed state.
Business need: the review of the objects may eventually expire. E.g. review made a year ago may not be actual now as a lot might be changed since the time of the review. To handle this cases users should be able to 'Request review' even if the object was already reviewed.
1. Open any object with review functionality.
2. Review this object - Request Review button should be visible, Mark Reviewed button - hidden.
3. Click on the Request Review button - popup with the note about Unreviewed status (at the bottom) is opened.
4. Click on the Request button - object status should be changed to Unreviewed.
5. On the Change Log tab should be the record about status …
=> GGRC-6202 Allow to request a review for an already reviewed object

src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.mustache, src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache, src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.js
Js error appear when switching from unarchived assessment to archived assessment on 'My Assessments' page.
*Precondition:*
- Have archived audit
- Have Assessment in scope of the audit (archived)
- Have non archived audit
- Have Assessment in scope of the audit (non archived)
1. Open My Assessments page
2. Open assessment Info panel which is not archived
3. Click on Next button
*Actual Result:* 'Uncaught TypeError: Cannot read property 'nodeName' of null' error message is displayed if click Next button on Assessment info panel. The app is freezing.
*Expected Result:* No errors should be displayed, next assessment info panel should be displayed.
Errors appears because of nested mustache conditions.
Use property `isEditDenied` from info-pane viewModel to display …
=> GGRC-6296 Fix conditions for <assessment-controls-toolbar>

src/ggrc-client/js/controllers/summary_widget_controller.js, src/ggrc-client/js/controllers/tests/summary_widget_controller_spec.js
Assessment count doesn't match in audit summary
1. Create Program -> Audit
2. Create 2 Assessments
3. Move both Assessments to 'In Review' state
4. Set 'verified_date' for 2-d assessment to any valid date (it can be done through import functionality or directly in db)
Actual behavior: Statistics page contains only info for Assessments w/ 'verified' flag set to 'true'
Expected behavior: Statistics page should contains info for all Assessments
In current implementation counts of assessment w/ 'verified' flag equals 'true' are skipped from the calculations (only assessments with verified=0 are present in table and on pie chart). Calculation was changed to summarize assessments in all states.
=> GGRC-6219 Fix assessment count on Audit Summary page

test/integration/ggrc/models/factories.py, test/integration/ggrc/models/test_query_api_queries.py, test/integration/ggrc/services/test_query/test_comment.py, test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py, test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py, test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py, test/integration/ggrc_workflows/converters/test_export_cycle_task_groups.py, test/integration/ggrc_workflows/converters/test_export_cycle_tasks.py, test/integration/ggrc_workflows/models/factories.py, test/integration/ggrc_workflows/models/test_cycle_task_entry.py, test/integration/ggrc_workflows/models/test_cycle_task_group_object_task.py, test/integration/ggrc_workflows/notifications/test_data_handler.py, test/integration/ggrc_workflows/notifications/test_workflow_comment_notifications.py, test/integration/ggrc_workflows/test_api_calls.py, test/integration/ggrc_workflows/test_relationships.py
Migrated comments are shown in wrong order
- Migrate CycleTaskEntry to comments.
- run reindex
Query API is works properly. We forgot to run reindex. 
Is scope of this ticket test was developed. Improved CycleTaskFactory to not create unnecessary workflows.
=> GGRC-6319 Add comment Query API test. WF Factory improvements.

src/ggrc-client/js/components/assessment/info-pane/create-url.js, src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc-client/js/components/ca-object/ca-object-modal-content.js, src/ggrc-client/js/components/comment/comment-add-button.js, src/ggrc-client/js/components/comment/comment-add-form.js, src/ggrc-client/js/components/comment/comment-add-form.mustache, src/ggrc-client/js/components/comment/comment-data-provider.js, src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js, src/ggrc-client/js/components/create-document-button/create-document-button.js, src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js, src/ggrc-client/js/components/object-list-item/comment-list-item.js, src/ggrc-client/js/components/object-list-item/comment-list-item.mustache, src/ggrc-client/js/components/object-list-item/document-object-list-item.js, src/ggrc-client/js/components/object-list-item/document-object-list-item.mustache, src/ggrc-client/js/components/related-objects/related-documents.js, src/ggrc-client/js/mustache/audits/info.mustache
Currently requests to create some object types (like: comment, evidence, document ) contain redundant 'created_at' field in their bodies. It's not required to send this data as this field will be auto-populated on server side.
Case#1
1. Open info-pane for any object that has comments section
2. Open dev-tools and add new comment
3. Inspect sent request body
Expected behavior: request body doesn't contain 'created_at' field. Spinner is displayed in 'date' area until request is not resolved.
Case#2
1. Open 'Audit Info' page
2. Add new 'EVIDENCE URL'
Expected result: request body doesn't contain 'created_at' field. Spinner is displayed in 'date' area until request is not resolved.
Remove 'created_at' field from attributes list send in …
=> GGRC-5538 Remove 'date' from create requests

src/ggrc/models/hooks/access_control_role.py, src/ggrc/models/hooks/acl/propagation.py
Adding a new ACR fails and breaks all edits on the objects that the ACR was added on.
Add a new custom role on controls and then try to create or edit a control,
before the fix both steps should have an error, after the both steps should work.
Note that testing after the first step has failed, we must re-run propagate_acl to ensure the correct state of the database.
Since the hook for adding missing acl roles is used when creating a new
ACR and when running propagated_acl it was made to support a filter only
for propagate_acl command. This was a performance optimization that
caused problems in the past. Now since the limit has be modified to
support the filter we should not be using the hook without the filter
for handled acl entries.
This commit resolves a problem with adding a new ACR …
=> GGRC-6332 Remove redundant acl role adding optimization

src/ggrc/notifications/common.py, src/ggrc_workflows/notification/data_handler.py, test/integration/ggrc_workflows/notifications/test_middle_level_one_time_wf.py
If cycle task was deprecated user is still receiving reminder emails for it.
1. Create CT
2. Deprecate it
3. Check emails
Expected:
Deprecated tasks do not generate a reminder email.
Actual:
Deprecated tasks generate a reminder email.
Remove notifications for existing tasks in migration. Remove notifications if user change status to deprecated. Don't create new notifications if cycle task already deprecated.
=> GGRC-5853 Disable emails for cycle tasks that are deprecated

src/ggrc-client/js/components/assessment/info-pane/info-pane.js
Verify button is available for Assignee/Creator when he is not Verifier.
1. Create program, control, audit
2. Open audit page
3. Create assessment with Creator user as Creator or Assignee
4. Log as Creator user and open the audit page
5. Open Assessment Info panel and add a Verifier
6. Add a comment to comment box
7. Click Complete button
Actual Result: Assessment is moving to In review state. Verify and Needs Rework buttons are displayed
Expected Result: Assessment should be moved to In review state. Verify and Needs Rework buttons should not be  displayed
NOTE: After refreshing the page Verify and Needs Rework buttons disappear. But Creator is able to verify/complete assessment
Define 'verifiers' with copies of persons.
Values of 'verifiers' can be changed if return …
=> GGRC-6286 Define 'verifiers' with copies of persons

src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js, src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js
There are errors that fall when passing tests in the browser console, as well as requests are made, which should not be in the tests
1. Run unit tests.
2. Open console or network tab on Browser.
**Actual result:** have errors in console tab and requests in network tab.
**Expected result:** don't have errors in console tab and requests in network tab.
Added `spyon` on methods and used `async` for tested functions.
=> GGRC-3746 Fix unit test errors

src/ggrc/integrations/issuetracker_bulk_sync.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/integration/ggrc/integrations/test_bulk_issue_generate.py
When user press 'Generate' button on Audit page we generate new tickets for each Assessment in Audit. If any Assessment here doesn't have related IssueTrackerIssue, such object will be created automatically. But revision for this created IssueTrackerIssue is missed (with event).
Expected result: We should always have 'create' revision (and event) for IssueTrackerIssue object.
- Create new Audit with disabled IssueTracker
- Create one or more Assessments corresponding to this Audit
- Enable IssueTracker in Audit
- Press Generate Button
- Check corresponding revisions in DB
Added action param to log_issues and create_revisions methods
Added creation of revisions for newly created issuetracker issues
=> GGRC-6318 Fix revision for IssueTrackerIssue 'create' action is absent for bulk tickets generation

src/ggrc-client/js/components/import-export/export.js, src/ggrc-client/js/components/import-export/import.js, src/ggrc-client/js/plugins/utils/import-export-utils.js
Refreshing of status of import/export increases in two times each time, so eventually it can take a lot of time before user gets actual status of import/export.
Start import/export with big amount of data. See on timeouts between request.
Use constant timeouts for tracking import-exports.
2000 ms after first request, 5000 ms after next request.
=> GGRC-5085 Use constant timeouts for tracking import-exports

src/ggrc/models/custom_attribute_value.py, src/ggrc/models/mixins/customattributable.py, test/integration/ggrc/models/mixins/test_customattributable.py, test/integration/ggrc/notifications/test_assessment_notifications.py
*Sometimes CustomAttributeValue table had entries with mapping to not existing Person object.*
1. Create CAD to Assessment model with "Map:Person" type from administration.
2. Send request to create/edit object from Assessment with wrong person ID.
3. You should get 400 as response.
- Added validator to check existance of mapped object in CustomAttributeValue.
- Added tests that adds not existing Person as CAV to object.
=> GGRC-5993 Entries with non-existing Person id in CustomAttributeValue

src/ggrc/models/review.py, src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py
Revision content for Review is not populated properly.
1. Create a new Control object
2. On Control Info page push Mark Reviewed 
3. Open Change Log tab in inspector mode
4. Look into the revision content (`review` section) 
In the constructor of Revision I replaced `review` value with proper review stub.
=> GGRC-6100 Fix incorrect review stub in revision content

src/ggrc-client/js/components/revision-log/revision-log.js
"Uncaught TypeError: Cannot read property 'AssigneeType' of undefined" error occurred. Data in not shown in change log tab
1. Log in GGRC as admin user  
2. Open All objects tab > Contracts tab 
3. Open Contract Info panel in TreeView for Contract created in 2015 
4. Click on Change Log tab 
Added extra checking to frontend script to avoid error.
=> GGRC-6069 Add extra check to fix property read of undefined in Change log

src/ggrc/integrations/issuetracker_bulk_sync.py, test/unit/ggrc/integrations/test_bulk_issue_generate.py
If there were no exceptions during bulk generate and we have empty error list we try to update DB and 
`db.session.execute(stmt, update_values)` where stmt has expr.bindparams and update_values is empty list crashes with 
>A value is required for bind parameter 'object_id_'
>
instance `maximb-with-import ` has been deployed to ggrc-test. 
Steps to test changes:
1. create issue with integration = off. component_id = 64445, hotlist_id=700706
2. enable integration via import.
3. Look through email notification. Ticket creation should be successful. (There were some errors in generating tickets for your GGRC import 'filename' were previously).
We shouldn't update failed items in DB if we don't have errors.
=> GGRC-6424 Bulk crashes with exception if there were no errors during bulk generation

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/handlers.py, test/unit/ggrc/converters/handlers/test_mapping_column_handler.py
**Issue description**
Whan user import a data in GGRC with unmap: Regulation/unmap: Standard he see the message: "Line 3: You do not have the necessary permissions to unmap scoping objects to directives in this application. Please contact your administrator if you have any questions. Column 'map:Regulation' will be ignored." The message is wrong becaouse we sould will have 'unmap'
Column 'unmap:Regulation' / 'unmap:Standard' is shown
**Solution description**
1. I fixed message.
2. I added logic for check mapping. We will see the massage only when we will update database after import
**Sanity checklist**
**PR Review checklist**
=> GGRC-6112 Fix unmap warning in import

src/ggrc/models/hooks/custom_attribute_definition.py, src/ggrc/views/__init__.py, test/integration/ggrc/services/test_query/test_cad_reindex.py
*Creation/Editing of CAD doesn't bring to reindexing of all the entities connected with CAD.*
1. Create CAD (checkbox) for any object type, e.g. assessment 
2. Search by CAD, "CAD = no": no result 
3. Update assessment, but do not update CAD 
4. Search by CAD, "CAD = no": success
*Changed hook after creating or deleting CustomAttributeDefinition. Revisions and reindex are created using chunks*
=> GGRC-3374 fix CAD reindexing after Creation/Deleting 

src/ggrc/migrations/versions/20181120162305_e2ab6a7b6524_cleanup_object_people_out_of_proposal_.py, src/ggrc/models/proposal.py, test/unit/ggrc/models/test_proposals.py
There are some controls in the db which have related object_people object. This leads to filling proposals content with object_people data, which is not used anymore in proposals functionality.
Find controls with object_people in the db. Generate a proposal. Update page. No front-end errors should appear.
Prevent putting obejct_people into proposals content. Clean up proposals content in the db.
=> GGRC-6064 Prevent creating proposal content with object_people field

src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/integration/ggrc/integrations/test_issue_integration.py
It should be possible for user to change at the initial ticket status to 'Won't fix(obsolete)' in case Issue Tracker ticket was unlinked from Assessment and Issue.
- Create a new assessment or open any old assessment without linked ticket
- Turn Ticket tracker integration on, leave Ticket ID empty, add Hotlist ID, Component ID, P, S, Ticket Title
- Click 'Save and close': a ticket generated for the assessment (ticket 1). Save link to it.
- Click 'Edit assessment'
- Leave 'Ticket ID' empty again
- Click 'Save and close': a new ticket generated for the assessment (ticket 2)
- Open saved link to ticket 1.
Actual result: comment to ticket about unlinking added. Ticket has status 'Assigned'.
Expected result: comment to ticket about unlinking added. Ticket has status 'Won't Fix: Obsolete'.
I've …
=> GGRC-6259 Set status 'Won't fix(obsolete)' in case ticket was unlinked from Assessment or Issue

src/ggrc-client/js/models/business-models/assessment-template.js, src/ggrc-client/js/models/business-models/tests/assessment_template_spec.js
LCA is not saving in New Assessment template popup.
1. Create a program, control in scope of the program, audit
2. Open Audit page
3. Create Assessment template with any type of LCA (text, date)
4. Open Edit Assessment Template popup and look at the LCA: is missed
Actual Result: LCA is not saving in New Assessment template popup
Expected Result: LCA should be saved in New Assessment template popup
Additional case:
1. Create a program, control in scope of the program, audit
2. Open Audit page
3. Create Assessment template with any type of LCA (text, date)
4. Open new Assessment template modal
Actual Result: LCA appears again
Expected Result: LCAs which were added previously should not appear on new Assessment template modal
Creation of …
=> GGRC-6462 Add CAD field to AssessmentTemplate model

src/ggrc/utils/memcache.py, src/ggrc_basic_permissions/__init__.py, test/integration/ggrc_basic_permissions/test_permissions_loading.py, test/unit/appengine/test_memcache_blob_operations.py
Application (with enabled memcache) will crash if user will have too a lot of ACL entries (got error on 443k of ACL and 470k of ACP). Problem is that we try to save permissions dict in memcache, but it has limitation for maximal value size - 1 Mb.
1. Setup environment with huge count of ACLs (size of compressed permissions dict should be bigger than 1 Mb).
2. Launch application with enabled memcache
Actual behavior: App is crashed.
Expected behavior: App is working.
Use blob get and set operations to store objects bigger 1 Mb
=> GGRC-5870 Fix crash of app in case of huge ACL count for user

src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/snapshotter/indexer.py, test/integration/ggrc/models/test_revision.py
Audit creation in Program with > 1000 Snapshots takes 2 min
1. Open Program with several thousand mapped objects 
2. Open dev tools> Network tab and create an audit
Actual Result: Audit creation took 2 min
Expected Result: Time for audit creation should be smaller
Load only global CADs for snapshotted objects, remove loading of local CADs as snapshotted objects don't have them.
Local test on Program 2009 (3500 Snapshots)
Without fix: 45.1370s
With fix: 31.5531s
=> GGRC-5139 Fix audit creation performance

src/ggrc-client/js/components/person/person-data.js, src/ggrc-client/js/components/quick_form/quick_update.js, src/ggrc-client/js/controllers/mapper/mapper.js, src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/controllers/tests/mapper_spec.js, src/ggrc-client/js/controllers/tests/modals_controller_spec.js, src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/models/business-models/contract.js, src/ggrc-client/js/models/business-models/person.js, src/ggrc-client/js/models/business-models/policy.js, src/ggrc-client/js/models/business-models/regulation.js, src/ggrc-client/js/models/business-models/standard.js, src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/mustache_helper.js, src/ggrc-client/js/plugins/ajax_extensions.js, src/ggrc-client/js/plugins/ggrc_utils.js, src/ggrc-client/js/plugins/utils/display-prefs-utils.js, src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
Currently we have two approaches for caching objects: custom `cache`, and `can.Model.store` provided by canJs.
We should use only one. Previously was investigated that `can.Model.store` has some inconvenient feature, it clears all models which has no bindings to DOM, and this breaks functionality with revisions in our app.
So it was decided to replace using of `store` on custom `cache`.
1) Replace using of store on custom cache.
2) Clean up using of can.getObject method
3) Use own cache for directive models
Models: Policy, Regulation, Standard, Contract - had common cache for storing objects by some historical reasons, currently there is no need for it.
4) Remove obsolete `provisional_cache` and related logic
=> GGRC-6154 Replace using of store on custom cache

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_csv.py
Currently Ticket Tracker columns are displayed after mapping fields and user have to find it. For usability reasons suggest to shift Ticket Tracker columns before all mapping fields.
Confirmed with BA.
1. Download Issue/Assessment template to Google sheet
2. Open it
3. Ticket Tracker columns are displayed before all mapping fields
I've just changed order.
=> GGRC-6395 Move Ticket Tracker columns before all mapping fields

src/ggrc-client/js/models/mappers/search-list-loader.js, src/ggrc-client/js/mustache_helper.js
This PR is `on hold` until dependencies are merged:
CanJS 3 does not support can.getObject.
1) Check `<relevant-filter>` on export page
2) Check autocomplete for 'Program' when creating audit from LHN 
Replace can.getObject.
=> GGRC-6381 Remove using of can.getObject

src/ggrc-client/js/components/assessment/assessment-local-ca.js, src/ggrc-client/js/components/diff/instance-gca-diff.js, src/ggrc-client/js/components/inline/inline.js, src/ggrc-client/js/components/related-objects/proposals/related-proposals-item.js, src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js, src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions-item_spec.js, src/ggrc-client/js/plugins/ggrc_utils.js, src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-help-utils.js, src/ggrc-client/js/plugins/utils/user-utils.js
Incorrect validation for mandatory CA with rich text type.
`Case 1 (create/edit popup):`
1. Log in to GGRC as admin user
2. Open Admin page and create mandatory 'rich text' GCA for any object, e.g. Access Group
3. Invoke new Access Group popup (or edit already existing)
4. Type only spaces in rich text CA and click out of field: 'cannot be blank' disappears 
5. Fill out required fields and save Access Group
`Case 2 (edit inline attr):`
1. Open Access Group with GCA
2. Try to edit mandatory rich text CA on Info panel (via 'pencil' icon)
**Actual Result:** Mandatory CA with rich text type is valid if user types space and Access Group can be saved
**Expected Result:** 'rich text' CA with spaces in value is invalid, cannot be saved, red border appears.
`Case 3 (local CA):`
1. Open assessment …
=> GGRC-5932 Fix validation for mandatory CA with rich text type

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/handlers.py, src/ggrc_workflows/models/task_group.py, test/integration/ggrc/converters/test_import_risk_assessment.py, test/integration/ggrc_workflows/converters/test_import_cycle.py, test/integration/ggrc_workflows/converters/test_import_task_group.py, test/unit/ggrc/converters/handlers/test_user_column_handler.py
If user tries to import a task group csv template with at least two task group assignees, "Import failed due to server error" error message occurs.
1. Create any wf in UI
2. Go to Import page and download task group csv template
3. Fill out required fields and set at least two task group assignees > Save changes
4. Import task group csv template
Actual Result:
"Import failed due to server error" error message occurs;
POST 400 is displayed in Network tab;
task group is not imported
Expected Result: If user tries to import a task group csv template with at least two task group assignees:
show informative message that only one task group assignee can be imported;
a message that a task group assignee will be alphabetically first registered user;
no error message should be …
=> GGRC-4541 Fix import a task group with at least two task group assignees.

src/ggrc/migrations/utils/__init__.py, src/ggrc/migrations/versions/20181206063405_5bb7c74d2089_add_modified_by_id_column_to_objects.py, src/ggrc/utils/revisions.py
After migration users see different users in a change log of objects.
Current logic for new or modified object - `revisions.modified_by_id` is set to `object.modified_by_id` (if value in object is not specified, user who runs migrations is used)
Current logic for deleted object - `revisions.modified_by_id` is set to `last_object_revision.modified_by_id`(if value in object is not specified, user who runs migrations is used)
The goal is to create object revisions on behalf of system user instead of different user. System user is default migrator.
1. Set default migrator in config
2. Create and run test migration which creates, changes and removes objects
3. Login as non-migrator user. run `create_missing_revisions` step after migration.
4. Ensure that in Revisions table `modified_by_id` is …
=> GGRC-6132 Do migration on behalf of system user

src/ggrc/models/background_task.py, src/ggrc/notifications/import_export.py, src/ggrc/views/converters.py, test/integration/ggrc/services/resources/test_converters.py
GGRC-PERF: Import failed for 500/1000 Assessments
Open audits/4567
Using Assessment import template [attached] import 500 or 1000 assessments
Actual Result: Import failed
Expected Result: Import should not fail
Import shown as failed because it was stopped by cron job (but actually it continue work). To prevent it, collecting of ImportExport jobs was corrected.
=> GGRC-6521 Correct collecting of ImportExport jobs

src/ggrc/query/custom_operators.py, test/integration/ggrc/models/test_revision.py
Currently `query API` does not support sorting by `created_at` for revisions. Which is necessary to arrange pagination for `change log`.
1. Perform query API request for revisions with `order_by` argument set to `created_at`.
2. See that revisions in result are sorted by `created_at`.
Solution consists of adding `created_at` and `updated_at` to `GETATTR_WHITELIST` in `query/custom_operators.py` so now `_joins_and_order` function from `query/pagination.py` will not perform joins and ordering agains `fulltext_record_properties` table in case `created_at` or `updated_at` are provided as ordering keys.
There may be a better solution like creating mixin analogues to `Filterable` one and providing each model with something like `_sortable_attr` dict containing fields against which sorting could …
=> GGRC-6498 Add ordering by created_at in query API

src/ggrc-client/js/mustache/audits/modal_content.mustache, src/ggrc-client/styles/modules/_modal.scss, src/ggrc/migrations/versions/20181211120905_44f601715634_add_manual_snapshots_column_in_audit.py, src/ggrc/models/audit.py, src/ggrc/models/relationship.py, src/ggrc/snapshotter/listeners.py, test/integration/ggrc/models/test_audit.py
While creating a new audit with a checkbox, if no snapshot needs to be auto mapped to audit and user
will manually map the snapshots. Create a checkbox in audit to map snapshot manually (by default it
should be off).
1. Create Program
2. Map some object to Program
3. Crete Audit. "Manually map snapshots" checkbox should be on
4. Check that Program objects are not mapped to Audit
Add manual_snapshots column in audit
=> GGRC-6339 Add manual_snapshots column in audit

src/ggrc/converters/base_row.py, src/ggrc/models/cache.py, test/integration/ggrc/converters/test_import_controls.py
Import doesn't create revision for the object if only ACL changed
2. Create control with filled Control Operator and Control Owner
3. Export control to Google Sheet
4. Change Control Operator and Control Owner (add one more person or remove them)
5. Import control and ensure that updates for control are correct in UI
6. Create audit for the program and open audit page
7. Open Controls tab and open controls info panel
8. Look at the Control Operator and Control Owner
Actual Result: Import doesn't create revision for the control. There is a difference between people in original Control and control's snapshot
Expected Result: Import should create a valid revision
Create revision for the object each time when import was run (no matter if something was changed or not).
=> GGRC-6486 Create object revision in import

src/ggrc/models/mixins/base.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/test_revision.py
For reviewable objects we have possibility filter 'change log' to show only changes after last review of object. So we need possibility to filter revisions in query API to get this revisions.
1. Create some object;
2. Perform several edits of this object;
3. Run query API request:
```
{
"object_name": "Revision",
"filters": {
"expression": {
"op": {"name": "AND"},
"left": {
"op": {"name": "AND"},
"left": {
"op": {"name": "="},
"left": "resource_type",
"right": <object_type>
},
"right": {
"op": {"name": "="},
"left": "resource_id",
"right": <object_id>
}
},
"right": {
"op": {"name": ">"},
"left": "created_at",
"right": <datetime>
}
}
}
},
```
Solution is to provide `ChangeTracked` mixin with `_filterable_attrs` list containing `created_at` and `updated_at` fields.
=> GGRC-6503 Filter revisions by created_at

README.md
Commands in `Reprovisioning a Docker container` section are outdated. 
Run:
`docker-compose up -d --force-recreate`
`docker exec -it $(docker container ls -f name=ggrccore_cleandev_1 -q -a) su vagrant`
Update `Reprovisioning a Docker container` with the correct command.
=> QUICK-FIX Update reprovisioning section in README

src/ggrc/snapshotter/__init__.py, src/ggrc/snapshotter/indexer.py, test/integration/ggrc/fulltext/test_bg_indexing.py, test/selenium/src/lib/service/rest_service.py
Reindexing of Snapshots takes significant part of time of Audit creation:
40s - Snapshots reindex, 1 min - total Audit creation time.
This PR move snapshots reindex into background.
Note: It will not affect import reindex.
Create Audit in big Program (for example program 1657 in ggrc-perf). Check timings of Audit creation with/without this PR.
Move snapshots reindex into background.
=> GGRC-6520 Move Audit Snapshots reindex into background

src/ggrc/gcalendar/calendar_event_sync.py, test/integration/ggrc/gcalendar/test_calendar_event_sync.py
If the event was not synced before deletion, than we receive a warning from CalendarAPI since we do not have `external_event_id` set at the moment. 
* Run integration tests
* Mock the calls to the API and test the case above is fixed: if event was not synced, the delete will not be called. 
Add check whether the event was synced before deletion.
=> QUICK-FIX Do not delete event from Calendar API which was not synced before

src/ggrc-client/js/components/issue/issue-unmap-item.js, src/ggrc-client/js/components/simple-modal/simple-modal.js
Modal backdrop is still displayed after issue unmapped from assessment.
1. Create an assessment
2. Map issue to the assessment
3. Unmap the issue
Assessment issue page has modal backdrop. (Can be removed by clicking on the page)
Assessment issue page has no modal backdrop.
The `issue-unmap-item` component which shows simple-modal with backdrop is deleted due to the fact that the tree-view is refreshed after issue unmapping. So closing of the modal does not work as `simple-modal` component does not exist.
Added `removed` event handler which hides a simple-modal before removing from the dom to fix this issue.
=> GGRC-6333 Modal backdrop is still displayed after issue unmapped from assessment

src/ggrc-client/js/application.js
`migrateMute` flag was added initially more than 5 years ago (https://github.com/google/ggrc-core/commit/6525b2be8fdfe7008069d98ea91ab61d4a2f0f9d#diff-5ba616f9408d08341bee0f64463bbf12R30) and was used for dependency `jquery-migrate` only. `jquery-migrate` is not a project dependency anymore and this flag can be removed.
Check that `migrateMute` is not defined as a property for `$` object.
Remove `migrateMute` flag.
=> QUICK-FIX Remove migrateMute flag

src/ggrc_workflows/models/cycle_task_group_object_task.py, test/integration/ggrc/gcalendar/test_calendar_events_model.py
The models that has relationship to CalendarEvent will fail to load.
1. Create repeat off WF
2. Create a task
3. Activate WF
4. Generate a CalendarEvent
5. Open CT's info panel on Active Cycles tab and look at the Network tab (devTools)
Actual Result: GET 500 while expanding CT's Info panel
Expected Result: no errors should be displayed
Define `_custom_publish` for CycleTaskGroupObjectTask that filter out relationships to `CalendarEvent`.
=> GGRC-6576 Fix loading of relationships to CalendarEvents

src/ggrc_basic_permissions/roles/Creator.py, src/ggrc_basic_permissions/roles/Editor.py, src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc_basic_permissions/test_person_profile_permissions.py
Persons don't have an access to their profiles since the relationship between them was fixed. 
Steps to reproduced:
2. Look at the screen: 'What's new' popup is not displayed
Actual Result: 'What's new' popup is not displayed while log in
Expected Result: 'What's new' popup should be displayed while log in
Add global permission for PersonProfile.
For the moment we don't have a permission mechanism for the profiles.
As a temporary fix we allow global roles to read and update people profiles since profiles don't have sensitive data.
=> GGRC-6575 Add global permission for PersonProfile.

src/ggrc/converters/base_block.py, src/ggrc/migrations/versions/20190102062852_8b0a23af6c55_create_missing_revisions.py, src/ggrc/models/snapshot.py, src/ggrc/notifications/data_handlers.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/utils/errors.py, src/ggrc_workflows/notification/data_handler.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/models/test_audit.py, test/integration/ggrc/notifications/test_assignable_notifications.py, test/integration/ggrc_workflows/notifications/test_data_handler.py
1. Objects are created without revisions after failed import
2. Editing Assessment and nightly_cron_job crashes because there are some objects (for example Assessments) without revisions
3. There are failing cases for daily digest
For Assessment without revisions:
1. Create assessment via import with snapshot mapped
2. On the audit page open assessments tab
3. Create Assessment with a due date filled
4. Click 3 bbs to open edit assessment popup > Clean due date
5. Pick the same due date and save changes
6. Add Evidence url or comment to comment box and save it
Expected Result: no errors should be displayed, Comments/evidence urls should not disappear
Check url /nightly_cron_endpoint for objects without revisions
Check url /_notifications/send_daily_digest for CycleTask without revisions …
=> GGRC-5976/GGRC-5922/GGRC-5923/GGRC-6330 Fix failing cases for object without revision

src/ggrc/automapper/__init__.py, test/integration/ggrc/automapper/test_automappings_rbac.py, test/integration/ggrc/test_csvs/issue_automapping_setup.csv
If we raise an Issue as Global Creator for Assessment that was generated based on Control, no mapping between Issue and Control Snapshot is being created.
1. Log as Global Creator;
2. Create a Program;
3. Map Control to the Program;
4. Map Audit to the Program;
5. Go to the Audit page;
6. Autogenerate an Assessment based on Control Snapshot;
7. Raise an Issue for generated Assessment;
8. Open Issue Info page in a separate tab;
9. Look at the tab pannel;
10. See "Controls" and "Controls Versions" tabs.
Previously `generate_automappings` method skipped permission check in case of "Audit"-"Issue" mapping. Proposed solution introduces class-level variable `_AUTOMAP_WITHOUT_PERMISSION`, which now holds both "Audit"-"Issue" and "Snapshot"-"Issue" rules, so no permission check should be …
=> GGRC-4595 Fix missed automapping between Issue and Snapshot

src/ggrc/query/custom_operators.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/services/test_query/test_not_empty.py
If requesting not empty revisions right after object change, 500 status code is returned.
1. Open some Control;
2. Open Edit modal and click save without any changes;
3. Run query API request;
```
{
"object_name": "Revision",
"filters": {
"expression": {
"op": {"name": "not_empty_revisions"},
"resource_type": "Control",
"resource_id": <object_id>
}
}
}
```
4. Expected result: query returns not empty revisions without errors.
Solution consists of replacing comparison of two revision contents. Instead a comparison of diffs of each revision with current instance is performed.
=> GGRC-6597 500 status when requesting not empty Revisions

src/ggrc-client/js/plugins/utils/snapshot-utils.js, src/ggrc-client/js/plugins/utils/widgets-utils.js
Mappings for Issue are not displayed properly in HNB.
1. Open an audit page and create an Issue in audit scope
2. Map any object to issue e.g. control
3. Open Issue page in a separate tab and look at the HNB
original control is not displayed as mapped to issue;
Control Version tab is displayed w/o any control snapshot in treeView
original control should be displayed as mapped to issue;
Control Version tab should not be displayed as control snapshot is not mapped to issue in this case;
Control Version tab with control snapshot should be displayed if control snapshot was mapped to issue via 'raise issue' functionality
**NOTE:** if create an issue separately and map control to it, extra Control Versions tab is also displayed in HNB for issue.
**Note:** …
=> GGRC-6552 Display properly mappings in HNB for Issue

src/ggrc/query/custom_operators.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/services/test_query/test_not_empty.py
Currently `not_empty_revisions` query API operator ignores revisions containing changes in some fields, e.g. `review_status`, but it should not.
1. Open control;
2. Click button "Mark Reviewed";
3. Run next query API request;
```
{
"object_name": "Revision",
"filters": {
"expression": {
"op": {"name": "not_empty_revisions"},
"resource_type": "Control",
"resource_id": <object_id>
}
}
}
```
4. See revision with changed review_status in result.
The bug was caused by usage of `utils.revisions_diff.builder.prepare` function to calculate diff between revisions. This did not work out because this function was created for using it with proposals functionality (at least I think so) and it skips certain revision fields, specifically the ones which are properties on models and aren't marked as …
=> GGRC-6617 Make not_empty_revisions not to ignore certain fields

src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/plugins/utils/snapshot-utils.js
Audit page opens with JS error in specific case.
Scenario 1:
1. Open /audits/4698#!summary on qa env.
Actual: JS error.
Scenario 2:
1. Go to any audit.
2. Open any snapshot widget, e.g. Control.
3. Set some filter status, e.g. Draft.
Actual: JS error.
Scenario 1:
Protect FE `snapshotCounts` method from unexpected objects.
BE part of the issue will be handled in scope of GGRC-6661.
Scenario 2:
Remove unneeded refresh of widget counts in the case when filtering was applied.
This was originally introduced to keep counts in widget tab in actual state when filter changes. This is not actual anymore.
=> GGRC-6657 Error on Audit page

src/ggrc/snapshotter/__init__.py, src/ggrc/snapshotter/listeners.py, test/integration/ggrc/models/test_audit.py
In GGRC-6339 we implemented audits with manual snapshot mapping, but Related Objectives/Regulations on Control popup in Asmt info panel won't working.
Also if we press "Update objects to latest version" on Audit, no new snapshots should be mapped to audit
1. Create a program, control, objective, regulation in scope of the program
2. Map control to objective, regulation
3. Create an audit with Manually map snapshots checked
4. Open audit page and map control to audit
5. Generate asmt based on control
6. Open Asmt info panel > Control popup: Check Related Objectives/Regulations
7. Repeat step 4 for objective, regulation and check again Related Objectives/Regulations.
Actual Result: Control popup doesn't show Related Objectives/Regulations if snapshots mapped manually …
=> GGRC-6601 Fix Audit with manual mapping 

src/ggrc/migrations/utils/__init__.py, src/ggrc/migrations/versions/20181121120334_b494ed20d04d_rename_roles_for_control.py
One migration script uses `Control` from `all_models`. As result, after changing schema of `ggrc.models.control.Control` (for example, after adding new column to the class) the migration raises exception "there is no such column in database" during `db_reset` script execution
To reproduce the issue:
1. Add new column into the `Control` model in `ggrc.models.control`
2. Run `db_reset`
Result - exception is raised
After the fix `db_reset` works without errors
To fix the issue the migration script was change to remove `all_models` usage.
=> QUICK-FIX Remove usage of all_models in migration

src/requirements-selenium.txt
Updated third-party library causes selenium tests fail
Specify exact version of third-party library
=> QUICK-FIX Add fixed more-itertools version

src/ggrc/gcalendar/calendar_api_service.py, test/unit/ggrc/gcalendar/test_calendar_api_service.py
Calendar invites show user as "Busy" and are causing an auto-reject for other calendar events.
1. Turn on calendar events for a user
2. Create cycle task for a user with due date in the future
3. Trigger `send_calendar_events`
4. See that event in the calendar events show 'free' status
gGRC calendar events should be defaulted to "Free"
https://developers.google.com/calendar/v3/reference/events
set `transparency` option to `transparent`. 
> `"transparent" - The event does not block time on the calendar. This is equivalent to setting Show me as to Available in the Calendar UI.`
=> GGRC-6716 Update gGRC calendar events to "Free" rather than "Busy"

src/cron.yaml, src/ggrc/contributions.py, src/ggrc/gcalendar/calendar_event_builder.py, src/ggrc/notifications/common.py, src/ggrc/views/converters.py, src/ggrc/views/cron.py, test/integration/ggrc/gcalendar/test_calendar_event_builder.py, test/integration/ggrc/notifications/test_assignable_notifications.py
In case `send_daily_digest` has failed with an error, despite having try-catch clause, all the following jobs may fail to execute. For example, we might to have the error like this for next jobs: 
```
This Session's transaction has been rolled back due to a previous exception during flush.
To begin a new transaction with this Session, first issue Session.rollback(). 
Original exception was: (IntegrityError) (1062, "Duplicate entry '1384' for key 'PRIMARY'") 
```
Also the `send_calendar_events` job will fail in case the generation (not sync) of any event has failed. We need to handle this gracefully
* Run the nightly cron jobs
1. Split nightly cron jobs on logical units: email notifications, calendar notifications, all other. It will allow to execute the jobs in parallel and will help to …
=> GGRC-6594 nightly cron job split

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Issue Tracker is OFF for asmt, if generate it based on AT with Issue Tracker ON
1. Open any audit with Issue tracker ON: Hotlist ID: 700706, component ID: 64445
2. Map any control to audit
3. Create AT with Issue Tracker ON
4. Generate Assessment based on AT
5. Open Assessment and look at Issue Tracker
Actual Result: Issue Tracker is OFF. There is no link to ticket in Issue Tracker
Expected Result: Issue Tracker is ON. Link to ticket in Issue Tracker should be displayed.
Add validation that Issue Tracker -> ON for Assessment Template
=> GGRC-6682 Issue Tracker is OFF for asmt, if generate it based on AT with Issue Tracker ON

src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, test/integration/ggrc/integrations/test_issue_integration.py
We should sync issue title to Issue Tracker when we change it on GGRC side.
1. Create GGRC Issue with Issue Tracker turned ON
2. Open Edit Issue modal and update 'Issue Title' field > Save
Expected Result: 'Issue Title' field should be updated. Changes should be saved.The following behavior should be for "Issue Title" filed:
I've just added title sync to our hook.
=> GGRC-5792 Incorrect behavior of 'Issue Title' field for Issue object

src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js, src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache, src/ggrc-client/js/models/business-models/issue.js, src/ggrc-client/js/templates/issues/modal_content.stache, src/ggrc/converters/base.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/issue_tracker.py, test/integration/ggrc/converters/test_import_issuetracked_objects.py
**PROBLEM:**
User can trigger new ticket autogeneration for issues in completed statuses. There is a restriction on Ticket Tracker API side, it allows to create tickets only in 'New' or 'Assigned' statuses. It means that, if Issue is in 'Completed and Verified' status, the ticket linked to such issue will have 'Assigned' status, until cron job will change it to Fixed (Verified). This can cause confusions for users, who already completed an issue and then receive a notification from Ticket Tracker system, that it is required to complete the same issue.
**SOLUTION:**
Do not allow to autogenerate tickets for issue that are in 'Fixed', 'Fixed and Verified' and 'Deprecated' states.
**ACCEPTANCE CRITERIA:**
**Via UI:** 
1. In case user chosen for issues statuses 'Fixed', 'Fixed and Verified' …
=> GGRC-5617/GGRC-6548 Do not allow to autogenerate Tickets at Ticket Tracker for Issues in some statuses via import

src/ggrc/migrations/utils/print_tree.py, src/ggrc/migrations/versions/20190211130153_57b14cb4a7b4_update_snapshot_delete_permissions.py, src/ggrc/services/common.py, test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py, test/integration/ggrc/access_control/acl_propagation/test_auditors.py, test/integration/ggrc/access_control/rbac_factories/snapshot.py
After implementing a new feature ('Delete snapshots from audit' GGRC-5638), there is an issue with permissions. Only Global Admin has rights to delete snapshots from audit. Global roles (editor, reader, creator) as program manager/editor or audit captain has no rights to delete snapshots.
1. Log as global editor (creator, reader) user
2. Create a program, control, audit
3. Open audit page and delete control snapshot
Actual Result: 'You do not have permissions..' message is shown up. Delete 403.
Expected Result: 
The following users should be able to delete snapshots:
Global Editor;
Global Editor with all program, audit roles permissions;
Global Reader, as Program Manager, Program Editor, Audit Captain.
Global Creator as Program Manager, Program Editor, Audit Captain.
- …
=> GGRC-6702 Global Editor/Reader/Creator cannot delete snapshots

src/ggrc/access_control/roleable.py, src/ggrc/models/mixins/autostatuschangeable.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/integration/ggrc/models/mixins/test_autostatuschangable.py
Currently when modifying ACLs on assessment with **IN REVIEW** or **COMPLETED** status, status is not switched to **IN PROGRESS** but should.
Case 1: Steps to reproduce:
1. Open any assessment without Verifier;
2. Complete assessment (assessment is in **COMPLETED** state);
3. Add or delete verifier/creator/assignee;
4. Assessment status is changed to **IN PROGRESS**.
Case 2: Steps to reproduce:
1. Open any assessment with Verifier;
2. Complete assessment (assessment is **IN REVIEW** state);
3. Add or delete verifier/creator/assignee;
4. Assessment status is changed to **IN PROGRESS**.
Case 3: Steps to reproduce:
1. Open any assessment with Verifier (your account)
2. Complete assessment and verify it (assessment is in **COMPLETED** state)
3. Add or delete verifier/creator/assignee;
4. …
=> GGRC-6607 Assessment status switch on ACL changes

src/ggrc/converters/handlers/handlers.py, src/ggrc/models/all_models.py, src/ggrc/models/relationship.py, test/integration/ggrc/__init__.py, test/integration/ggrc/converters/test_base_block.py, test/integration/ggrc/converters/test_import_mapping.py, test/integration/ggrc/models/hooks/acl/test_propagation.py, test/integration/ggrc/models/test_relationship.py, test/integration/ggrc/services/test_query/test_basic.py, test/integration/ggrc/snapshotter/test_snapshoting.py, test/unit/ggrc/converters/handlers/test_mapping_column_handler.py
The goal is to make relationship read-only for regular GGRC users between Control and Scope objects, Standards and Regulations.
Login as regular user, ensure that it cannot create/delete relationship between  Control and Scope objects, Standards and Regulations
Login as external user, ensure that it can create/delete relationship between Control and Scope objects, Standards and Regulations
Add validation during relationship creation
=> GGRC-6640 Disable map control to Standard, Regulation and Scope objects

src/ggrc/access_control/role.py, src/ggrc/migrations/versions/20190219103003_a8a4442a2b91_remove_asterisks_from_cads_and_roles.py, src/ggrc/models/custom_attribute_definition.py, test/unit/ggrc/models/test_access_control_roles.py, test/unit/ggrc/models/test_custom_attribute_definition.py
Backend part of GGRC-4954
The character "*" should not be allowed in any custom name for roles or attributes.
Issue is that "" is used for imports and setting a name like "use search A" will break imports because * will get stripped from the attribute name.
Also the * is used for internal roles and removing it from user defined roles will prevent any name clashes.
Ticket also needs a migration to remove any possible already existing * from current names.
Currently validation implemented by FE but user still can create custom role via API
Create Custom Role or Custom Attribute with name that includes "*" symbol using API.
Update validation rules in modes.
Migration searching for names with "*" symbol and remove the symbol. If new name already exists, add number to the end.
=> GGRC-5246 prevent "*" character to be used in custom role names and custom attribute names 

src/ggrc_workflows/__init__.py, test/integration/ggrc_workflows/test_status_propagation.py
Cycle is moving from In progress to Assigned if create new Cycle Task for one time workflow.
1. Open Active Cycle and expand the tree with Cycle Tasks.
2. Start Cycle Task to move Cycle into In Progress state.
3. Create new Cycle Task
4. Check that newly added Cycle Task is in Assigned state, however Cycle and Cycle Tasks Group still in In Progress state.
Function `_update_parent_state`, which is invoked during calculating statuses of Cycle and Cycle Task group, didn't handle Assigged state of newly added child.
=> GGRC-5015 Cycle is moving from In progress to Assigned if create new CT for one time workflow

src/ggrc_workflows/models/cycle_task_group_object_task.py, test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
Import comments for cycle tasks
1. Allow Global Admin to import comments for cycle tasks. (in the same way as for assessments)
To test locally:
1. Make import files with correct filed 'Comments' field.
2. Checked that by opening 'Cycle Tasks' info in web-browser.
1.  Added new value to 'Importable list' property of 'Cycle Tasks'.
2.  Created new test for this functionality.
=> GGRC-4883 Added comments to importable fields Added new test

src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/custom_attribute_value.py, test/integration/ggrc/models/mixins/test_customattributable.py
We can't edit an assessment with inline edit if any mandatory CAs are missing.
Create an assessment without a mantatory person custom attribute by either
- create an assessment and add a person local CA
- generate an assessment with mandatory person local ca
Try to edit the title with inline edit
Since we're removing person global custom attributes, we are ignoring those in this PR.
The PR itself fixes the issue for local custom attributes. Since those are only on assessments and mandatory global custom attributes on assessments mean different that on other objects, we can ignore the mandatory checks.
on other objects:
- mandatory means we can not edit an object until mandatory fields are filled in.
on assessments:
- mandatory means we can edit the object without that value but we can not …
=> GGRC-6686 Remove mandatory checks for person LCA

src/ggrc_workflows/models/task_group_object.py, test/integration/ggrc/models/test_control.py
Error: "External application can delete only external relationships" is returned on Control PUT if Control is mapped to TaskGroup
1. Create Control
2. Create Workflow
3. Map Control to TaskGroup from this Workflow
4. Send PUT on Control
Actual result: Control is not updated. Error "External application can delete only external relationships" is returned.
Expected result: Control is updated successfully. TaskGroup/TaskGroupObjects are not affected.
Disable updating of TaskGroupObjects through the api
=> GGRC-6829 Disable updating of TaskGroupObjects through the api

src/ggrc-client/js/templates/snapshots/dropdown_menu.stache
The following users should be able to delete snapshots on audit page:
- Global Editor Audit Captain.
- Global Reader Audit Captain.
- Global Creator Audit Captain.
Others shouldn't see Delete snapshots option under 3 dots.
1. Log as global editor (creator, reader) user
2. Create a program, control, audit
3. Open audit page and delete control snapshot
Actual Result: 'You do not have permissions..' message is shown up. Delete 403.
Add delete permission check in template for `<delete-button>`.
Remove unneeded check for map permission.
=> GGRC-6811/GGRC-6702 Hide Snapshot "Delete" button for users that don't have delete right

src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/components/tree/tree-widget-container.js
GGRC-5927: js error on revisions update and change tab while updating snapshot to the latest version
1. Have a program with market and audit
2. Open audit page, the market snapshot should exist in audit scope
3. Update market on its own page (edit description)
4. Refresh audit page and open market snapshot info panel
5. Click on Get the latest version link > Click Save button in Comparison window
6. Quickly click on Audit summary tab: JS error occurred screenshot-1.png 
Actual Result **before** fix: JS error occurs if switch to Audit summary tab while updating snapshot to the latest version
Expected Result: JS error should not occur if switch to Audit summary tab while updating snapshot to the latest version
Actual Result **after** fix is equal to Expected Result: *Control was refreshed …
=> GGRC-5927: Js error on revisions update and change tab

src/ggrc/migrations/versions/20181112075115_e6f8ba2075a4_remove_task_group_objects_related_to_clause.py
1. Log in into GGRC
2. Go to Export page
3. Select export object type = task group.
4. Click 'Export Objects' button.
Actual result: No task groups are exported. 400 error is thrown.
1. Repeat steps from issue description. Expected result: Export should be completed successfully.
2. Open workflow with broken task group. i.e. workflow with id=94 (on test instance). It should open setup page correctly (on dev it throws error).
This problem emerged due to some Task Group Objects which are connected with Task Groups with foreign key 'task_group_id' were still connected to outdated "Clause" model. 
The problem is that if there is any object related to Task Group being exported (Control, System, etc.) this object is also included in the CSV file (in 'Object' row). 
The server error occurred …
=> GGRC-2995 Impossible to export all Task Groups

src/ggrc/services/common.py, test/integration/ggrc/services/test_collection_post.py, test/integration/ggrc_workflows/test_workflow_api_calls.py
Open GGRC app
On My Work page click on Start New Audit button
Click on [Add] Evidence URL
Fill in any evidence url and save it
Actual Result: Error is displayed in UI, POST 400 in Network tab. Evidence URL is not displayed after saving an audit
Expected Result: No errors should be displayed after saving Evidence URL in New Audit popup
Context functionality is obsolete (ACL is used to propagate permissions now). So the validation for 'context' key in POST dict was removed.
Additionally, an extra fix was made - raise validation error if title is None in all models (this issue didn't allow to pass tests for the issue with context)
=> GGRC-6485 Allow create evidence before audit

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Issue tracker is not enabled for generated assessment if is generated without assessment template, and issue tracker is ON for corresponding audit
1. Open any audit with Issue tracker ON: Hotlist ID: 700706, component ID: 64445
2. Map any control to audit
3. Generate Assessment based on control snapshot
4. Open Assessment and look at Issue Tracker
Expected Result: Issue Tracker is ON. Link to ticket in Issue Tracker should be displayed.
Enable issue tracker is it's enabled for audit, and enable flag is not specified neither in API dict directly nor in template dict
=> GGRC-6751 Properly handle issue tracker status for assessment creation without assessment template

src/ggrc-client/js/components/revision-history/mandatory-fields-modal.js, src/ggrc-client/js/components/revision-history/restore-revision.js, src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.stache, src/ggrc-client/js/components/revision-history/templates/restore-revision.stache, src/ggrc-client/styles/components/revision-history/_revision-history.scss
Global custom attribute validation popup is not shown. The problem is caused by the addition of `removed` event to `simple-modal` component.
1. Log in ggrc-dev as admin
2. Create a risk
3. Make any changes, e.g. update a title
4. Go to Administration page > Add any GCA for risk and make it mandatory, (e.g. date)
5. Open risk from step 2
6. Click on Version History tab
7. Click on Review & Restore
8. Click Restore Version button on Restore Version modal: GCA Validation popup should be displayed
**Actual Result:** GCA Validation popup is not shown, revision is not restored.
**Expected Result:** Validation popup should be shown.
Disable "Restore Version" modal closing after clicking "Restore Version" button. 
Pass element to `saveInstance` event handler.
=> GGRC-6611 GCA validation popup is not shown

src/ggrc-client/js/components/assessment/info-pane/confirm-edit-action.js, src/ggrc-client/js/components/assessment/tests/confirm-edit-action_spec.js
Editing some properties for deprecated Assessment via inline edit functionality moves it to 'In Progress' state while the same actions performed in 'Edit' modal doesn't.
- Open any Assessment
- Move Assessment to 'Deprecated' state
- Edit Assessment title via inline edit
Actual result: Confirm moving Assessment to 'In Progress' state popup appears
Expected result: No confirmation popup should appear, title is changed without affect on Deprecated status.
Add 'Deprecated' state to states list for which confirmation popup is not displayed while inline editing.
=> GGRC-6714 Remove confirmation popup for Assessments in 'Deprecate' state while inline edit

src/ggrc/login/common.py, src/ggrc/utils/user_generator.py, test/integration/ggrc_basic_permissions/test_external_login.py, test/selenium/src/tests/test_workflow_page.py, test/unit/ggrc/login/test_appengine.py
GGRC uses external API to get user's first name and last name.
during external app request GGRC calls that api 10+ times. It leads to excess of quota.  
Run test and check that no requests for external API
Because of this fix goes to release directly implementation should be as simple as possible.
I've updated user search logic to use data from header not from external API for external app calls.
=> GGRC-6832 Disable HR api for external app requests

src/ggrc/migrations/versions/20190311140106_0d7a3a0aa3da_update_propagation_tree_for_control_.py
The propagation tree is not valid for Control Owners / Operators in Control
To test locally:
1. Make two files via utility print_tree --as_dict 
2. Compare result via 'deepdiff' library 
*  migration
*  propagate_acl
*  reindex
1.  Created new migration with update_acr_propagation_tree()method
2.  Applied new migration
=> GGRC-6497 Fixing propagation tree for Control Operators and Control Owners

src/ggrc/models/relationship.py, test/integration/ggrc/models/test_relationship.py
Before 2.0 external app can remove only self created relationships (marked by flag is_external=True)
In 2.0 some relationship creation/removing will be transferred to external app. Thats why we don't need this validation anymore.
Example:
Before 2.0 control was mapped to directive 
Control <-> Directive 
in 2.0 we transfer this mapping to external app.
After 2.0 user can remove this mapping in the external app
Sync service needs to remove this relationship in GGRC.
But this relationship with is_external=False. And validator don't allow to do that.
Remove validation from relationship model
=> GGRC-6953 Remove validation is_external

src/ggrc-client/js/models/mappers/mappings-ggrc.js
No redirect to new frontend if map Control to Key Report.
2. Open Key Reports tab on My Dashboard tab
3. Open Unified mapper to map Control to Key Report
4. Click on Search button
5. Check checkbox for any control and click on Map Selected
Actual Result: POST 400 is displayed in Network tab, 'you do not have permissions ..' message is displayed in UI
- Controls should not be displayed in Search Results if click on Search Button
- 'Open in new frontend' button should be displayed
- 'Please click the button below to map controls for this key report in new frontend.' should be displayed
Add external mapping to Control for Key Report.
=> GGRC-6924 Add external mapping to Control for Key Report

src/ggrc-client/js/components/object-generator/object-generator.js, src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js
Generation should be possible only from snapshotable objects, not from mappings.
Issue is displayed in Object type list in Assessment generation popup
1. Open any audit page in ggrc app
2. Audit Summary tab > Click on Autogenerate button
3. Expand Object type list
Actual Result: Issue object is displayed
Expected Result: Issue object should not be displayed as Assessment can be generated based on snapshots in scope of the audit. Issue is not snapshotable object.
Use list of snapshotable objects from global config instead of list of available mappings in `object-generator` component.
=> GGRC-6695 Redefine availableTypes for object-generator

src/ggrc/services/common.py, src/ggrc_basic_permissions/roles/Editor.py, test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py, test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py, test/integration/ggrc/access_control/acl_propagation/test_auditors.py, test/integration/ggrc/access_control/acl_propagation/test_program_editors.py, test/integration/ggrc/access_control/acl_propagation/test_program_managers.py, test/integration/ggrc/access_control/acl_propagation/test_program_readers.py, test/integration/ggrc/models/test_assessment_file_url_and_status_put.py, test/integration/ggrc/services/test_query/test_basic.py
If Global Editor user is not present in audit/assessment ACL, he cannot remove evidence file/url for assessment, but he should be able to.
1. Log in as Global Editor;
2. Open any audit (Global Editor should not be present in ACL of that audit);
3. Open any assessment or create a new one (Global Editor should not be present in ACL of that assessment);
4. Add file/url evidence to assessment and try to delete file/url.
Expected Result: Global Editor should be able to remove file/url evidence from assessment.
Solution consists of adding Evidence in delete section of Global Editor permissions specified in `ggrc_basic_permissions.roles.Editor` module.
=> GGRC 6929 Allow GE to remove evidence on assessment if GE not in ACL.

src/ggrc_basic_permissions/roles/Creator.py, test/integration/ggrc/models/mixins/test_labeled.py
GlobalCreator could not see labels in new tab 
1. As Admin open audit Info page and assigned Global Creator as auditor
2. Log as Global Creator and open audit page
3. Create Assessment and add label to assessment (when you start typing to add label you can see all created labels that match your characters)
4. Open created Assessment in a new tab and look at the label
Expected Result: Global creator as auditor should see his labels on Assessment Info page
GlobalCreator has been granted to see all labels
=> GGRC-4516 Global Creator Can See All Labels

src/ggrc-client/js/components/assessment/attach-button.js, src/ggrc-client/js/components/assessment/attach-button.stache, src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/info-pane.stache, src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js, src/ggrc-client/js/components/assessment/tests/attach-button_spec.js, src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache, src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js, src/ggrc/models/evidence.py, test/integration/ggrc/converters/test_export_assessments.py, test/integration/ggrc/models/mixins/test_autostatuschangable_evidence.py, test/integration/ggrc/models/mixins/test_with_auto_deprecation.py, test/integration/ggrc/models/mixins/test_with_evidence.py, test/integration/ggrc/models/test_evidence.py
"Etag" and "last-modified" are not changed after creation of a new mapping/relationship
1. Have audit with snapshot and Assessment
2. Navigate to assessment's Info pane
3. Open dev tools > Network
4. Attach evidence
5. Look at the Network tab in dev tools.
Actual Result: "Etag" and "last-modified" are not changed after creation of a new mapping/relationship
Expected Result: "Etag" and "last-modified" should be changed after creation of a new mapping/relationship.
When we attaching Evidence File, Assessment object remain the same, just new relationship creats.
We have to update Assessment object (send PUT) after adding Evidence File that would map and update parent object (and eTag).
=> GGRC-2774 "Etag" and "last-modified" are not changed after creation of a new mapping/relationship

test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/utils/string_utils.py
'*' symbol is forbidden for ACR name cause we use it for our roles propagation. 
Some tests are fails and rerun because of this symbol in role name. It causes additional time for selenium tests.
i.e. TestEventLogTabDestructive::()::test_chronological_sequence_1st_page::setup:
> E         ContentDecodingError: Server request body:
E         [{"access_control_role": {"name": "Objective_99688ef8-55d6_j5;Vt-g\*eoO\*i", "modal_title": "Add Custom Role to type Control", "read": true, "object_type": "Objective", "update": true, "context": {"id": null}, "delete": true}}]
E         Server response text:
E         code: 400, message: Attribute name contains unsupported symbol '*'
- Сheck if selenium tests are ok.
- Check if there are reruns because of this errors.
I've changed allowed symbols arg …
=> QUICK-FIX remove '*' symbol from generated ACR name for selenium tests.

src/ggrc-client/js/components/revision-log/revision-page.js, src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc-client/js/plugins/tests/ca-utils_spec.js, src/ggrc-client/js/plugins/utils/ca-utils.js, src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js, src/ggrc-client/js/plugins/utils/object-history-utils.js, src/ggrc/converters/snapshot_block.py, src/ggrc/models/revision.py, src/ggrc/notifications/__init__.py, src/ggrc/notifications/proposal_helpers.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/models/test_revision.py, test/integration/ggrc/proposal/api/test_cads.py, test/unit/ggrc/converters/test_snapshot_block.py
Now for Proposals we send custom_attribute_values array, which includes objects, which contain `attribute_object_id` property. We should remove this property, because the information about `id` should be included into `attribute_object` object.
**Case "Revision comparing"**:
1) Have Audit with snapshot of control
2) Modify original control (add some person as custom attribute)
3) On audit page open info-pane of this snapshot
4) Click "Get the latest version"
Expected: all works as expected.
**Case "Change Log":**
1) Open any object e.g. Control
2) Modify object (add some person as custom attribute)
3) Open "Change Log" tab
Expected: adding of a person should be displayed.
**Case "Create Proposal":**
1) Open any object with proposals (e.g Risk)
2) Click "Propose change"
3) Add some person …
=> GGRC-4642/GGRC-4643/GGRC-4647 Remove using of attribute_object_id

src/ggrc/query/builder.py, src/ggrc/rbac/permissions.py, src/ggrc/rbac/permissions_provider.py, test/integration/ggrc_basic_permissions/test_creator.py
Global Creator user does not see info in Change Log tab of objects it is assigned to.
1. As admin user create a program, audit;
2. Assign creator user as program manager;
3. Log as creator user;
4. Open program page > Change Log tab;
**Expected Result: Global Creator user should see info in Change Log tab**.
5. Open Audit page > Change Log tab;
**Expected Result: Global Creator user should see info in Change Log tab**.
The bug was introduced when change log was modified to use query API instead of request with query parameters. 
The solution includes adding special check for `Revision` type in query API method responsible for permission resolution. There query condition is build which resolves to `True` only for revisions of objects current user has right permission on.
This approach was …
=> GGRC-6808 Allow GC to see change log of objects it is assigned to

src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js, src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js, src/ggrc-client/js/models/cacheable.js
`can-model` from _CanJS 3_ returns Promise instead of Deferred object.
It happens because _CanJS 2_ wraps a callback in Can.Deferred.
But _CanJS 3_ doesn't do it.
"Create/Update" method of "Cacheable" model should return Deferred object instead of Promise object
=> GGRC-6989 "Create/Update" model's methods should return Deferred instead of Promise

src/ggrc/models/hooks/issue_tracker/issue_integration.py, test/integration/ggrc/integrations/test_issue_integration.py
Our user creation had bugs.
look through ticket details. 
i've added find_user method from our library.
- As this bug was reproduced for new users you can't use my instance for testing cause these users were added to DB.
=> GGRC-6837 Manual linking with issue doesn't work with users at ticket tracker CC list that do not exist at the system

src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/issue_tracker.py, src/ggrc/integrations/constants.py, src/ggrc/models/hooks/assessment.py, src/ggrc/models/hooks/issue_tracker/__init__.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/integration_utils.py, src/ggrc/models/hooks/issue_tracker/issue_integration.py, src/ggrc/models/issuetracker_issue.py, src/ggrc/models/mixins/issue_tracker.py, test/integration/ggrc/converters/test_import_issuetracked_objects.py
Predefined values for issue tracker are incorrectly calculated for Issue tracked objects.
For assessment, values have to be fetched in the following order:
1. Values in Assessment template, if assessment template specified and issue tracker values are available
2.  Values from Audit if issue tracker values are available for audit
3. Default values
For assessment template, values have to be fetched in the following order:
1.  Values from Audit if issue tracker values are available for audit
2. Default values
For Issue issue tracker values have to be fetched from default values.
Moreover, values have to be fetched in that order even if import file doesn't contain corresponding columns!
1. Prepare import spreadsheet and import it.
2. Ensure that issue tracker values of imported objects are …
=> GGRC-6756 Properly calculate predefined values for issue tracker dict during import

src/ggrc/migrations/versions/20190322_724fcf70a349_mark_obosolete_clause_and_section_.py
Changelog breaks when dailing with relationships from obosolete objects
3. Open link https://ggrc-perf.appspot.com/standards/2409#!info (changing example with control to a standard because controls don't have this bug anymore
4. Open Change log tab and open all 50 entries
Actual result: 'Failed to fetch data for person' error occurs
Expected Result: no errors should be while opening Change Log tab
This migration ensures that queries for existing objects and
relationships don't fetch any revisions for objects that have been
renamed or deleted
=> GGRC-6651 Mark obsolete revision entries

src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js_specs/models/cacheable_spec.js
Mapping to Proposal shows 'Deleted' in Change Log tab for Control and Risk
1. Create a risk
2. Propose changes
3. Open Change log tab on the Info panel
4. Look at the Mapping to Proposal: shows DELETED
Actual Result: Mapping to Proposal shows 'Deleted' in Change Log tab for Control and Risk
Expected Result: Mapping to Proposal should not show 'Deleted' in Change Log tab for Control and Risk
The issue was in the Cacheable.display_name method. It supposed the object is deleted if both title and name are undefined. But actually, we do have valid not deleted objects without these both fields. For example Proposal.
So we had to change the way of determinating if the object is deleted. Every not deleted object has created_at property, which is now used for this task.
Also, I had to return …
=> GGRC-5835 Deleted label in change log

test/integration/ggrc/__init__.py
Refactor Basic CSV Import
1. Set 'delete' parameter of 'tempfile.NamedTemporaryFile' function in 'import_data' to 'False'. This 'import_data' method is defined in 'test/integration/ggrc/__init__.py'
2. Change the arguments of 'data_block.extend' method in 'test_map_core_objects', present in 'TestBasicCsvImport' class of 'test/integration/ggrc/converters/test_import_csv.py', as specified below.
data_block.extend = [
OrderedDict([
("object_type", "standard"),
("Code*", "STANDARD-1"),
("title", "Standard-1"),
("admin", "user@example.com"),
]),
OrderedDict([
("object_type", "standard"),
("Code*", "STANDARD-2"),
("title", "Standard-2"),
("admin", "user@example.com"),
("map:regulation", "REGULATION-1"),
("map:policy", "POLICY-1"),
("map:contract", "CONTRACT-1"),
("map:requirement", …
=> GGRC-6388 Refactor basic csv import

src/ggrc/notifications/proposal_helpers.py
We have failing half hour cron job on ggrc-uat instances.
1. Go to ggrc-uat;
2. Execute half hour cron job;
Expected result: no errors in job logs.
Half hour jobs where failing on ggrc-uat because of the way email body is generated from proposal's content `mapping_fields` field. Before integration with GGRCQ `Control` had nullable relationships `kind`,  `mean` and `verify_frequency`. And there was proposal created with this fields left empty which led to proposal's content `mapping_fields` fields to have `None` values when method responsible for building object representation expects dicts.
The solution is to pass `{"id": None, "type": None}` as default value for method build object representation.
=> GGRC-7050 Failing half hour cron job on UAT

src/ggrc/migrations/versions/20190403_2e4325bb21ed_remove_kind_column_from_workflows_table.py, src/ggrc_workflows/models/workflow.py
Remove unused 'kind' field from Workflow FE/BE
1. Set up the dev container using command 'sudo ./bin/containers setup dev'
2. Connect to dev container using command 'sudo ./bin/containers connect'
3. Connect to mysql server using command 'mysql -hdb ggrcdev'
4. View the schema of 'workflows' table using comand 'desc workflows'
5. 'kind' column will not appear in the schema.
Created a new migration file, which drops the 'kind' column from 'workflows' table.
=> GGRC-3895 Remove kind column from workflows BE

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/test_csvs/assessment_template_no_warnings.csv, test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
Default Test plan instead of Default Assessment Procedure is displayed in export/import page for the Assessment template object type.
Test Case 1.
1. Open Export page > Select Assessment template object type
2. Look at the Attributes
Actual Result: Default Test plan instead of Default Assessment Procedure is displayed
Expected Result: "Default Assessment Procedure" attribute should be shown for Assessment template on the Export page
Test case 2.
1. Import Assessment template csv
2. Look at the columns: "Default Test Plan" column is shown
Actual Result: Default Test plan instead of Default Assessment Procedure is displayed
Expected Result: Default Assessment Procedure should be displayed
Updated the aliases in the models files from Default Test Plan to Default …
=> GGRC-4667 Updated Default Test Plan attribute to Default Assessment Procedure

src/ggrc-client/js/components/assessment/info-pane/info-pane.js, src/ggrc-client/js/components/assessment/info-pane/info-pane.stache, src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js, src/ggrc-client/js/components/related-objects/related-assessments.js, src/ggrc-client/js/components/related-objects/tests/related-assessments_spec.js
Cannot reuse evidence file/url for related assessments
1. Log in ggrc-app and open any audit page with mapped control snapshot
2. Generate two assessments based on the control snapshot
3. Add evidence file and url to one assessment 
4. Open second assessment info panel > Related assessment tab
5. Reuse evidence file and url screenshot-1.png
6. Click on Assessment tab: evidence file and url are not shown up (even after page reload)
**Actual Result:** Cannot reuse evidence file/url for related assessments
**Expected Result:** User should have a possibility to reuse evidence file/url for related assessments
Issue was introduced in #9199 PR. In this PR mapping of evidence and Assessment was updated. Previously was used `parent_obj` in Evidence object. Now mapping happens through assessment …
=> GGRC-7056 Fix evidence reusing of file/url for related assessments

src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js, src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
**CanJS 3** doesn't support **can.Object.same** function.
It can be replaced with **lodash.isEqual**
=> GGRC-7097 Use lodash.isEqual instead of can.Object.same

src/ggrc/services/resources/assessment.py, test/integration/ggrc/services/resources/test_assessment.py
Made original_object_deleted field of snapshots to be returned when requesting related_objects of assessment.
Add original_object_deleted field for snapshots from related objects
Query API response for snapshots contains field `original_object_deleted`. In case of getting snapshots through assessment related objects: api/assessments/#id/related_objects the response for snapshot does not contain this field. Based on this flag FE will be able to identify that link to GGRCQ should be hidden.
Added required data to output returned by related_objects method of AssessmentResource.
=> GGRC-6747 Add original_object_deleted field for snapshots from related objects

src/ggrc-client/js/components/revision-log/revision-log.stache, src/ggrc-client/styles/components/tree_pagination/_tree_pagination.scss
ChangeLog paging: multiple "Next page" click is possible 
1. Open any objective, e.g.: /objectives/148#!info from test DB. 
2. Go to Change Log 
3. In paging, click "Next page" many times fastly. 
Actual result: Many requests sent to BE for each page.
Expected results: Paging becomes disabled while one page is loading.
Disabling is done via CSS pointer-events property applied to the overall tree-pagination component.
We already have isLoading property in revision-log, so it's just passed down to tree-pagination.
=> GGRC-6738 Disable changelog pagination while loading

src/ggrc/migrations/versions/20190412_cfe397ab518c_remove_lock_task_order_for_task_group_.py, src/ggrc_workflows/models/task_group.py
BE Remove lock_task_order property for Task Group Task
Search for lock_task_order property in the code and delete if any.
Run the build_assets command.
Once the assets are build successfully run the launch_ggrc command in the container.
Removed the lock_task_order property from BE code.
Updated the table task_groups by deleting the lock_task_order column.
Update the file "src/ggrc/migrations/versions/20190412_cfe397ab518c_remove_lock_task_order_for_task_group_.py" with the below query:
Query : op.drop_column('task_groups', 'lock_task_order')
Note: If the file is not editable change the permissions by logging out of the docker container.
Run the below command in order to execute the sql changes:
python migrate.py revision -m "remove_lock_task_order_for_task_group_task"
Run the below query …
=> GGRC-4994 Remove lock_task_order property for Task Group Task from BE

src/ggrc/models/audit.py, src/ggrc/models/program.py, src/ggrc/utils/errors.py, src/ggrc/views/__init__.py, test/integration/ggrc/models/test_audit.py, test/integration/ggrc/models/test_program.py, test/integration/ggrc/services/test_delete.py
This pr includes commits from [9251](https://github.com/google/ggrc-core/pull/9251) cause most of the changes were done there but we need to have them in release branch.
Need to update error message shown while deleting audit with mapped assessment or assessment template.
1. Open audit page
2. Create/map assessment
3. Delete audit
**Before changes**: "This request will break a mandatory relationship from assessments to audits." message is shown
**After changes**: "The following Audit cannot be deleted due to existing assessment(s) or assessment template(s) mappings. Please delete assessment(s) or assessment template(s) mapped to this Audit to continue." message should be displayed
Add dot to the end of Audit cannot be deleted message.
Add additional check to audit handler to check for …
=> GGRC-6508 Update cannot delete audit message 

src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py, test/selenium/src/tests/test_workflow_page.py
Send daily notifications is failing because of key error in cad/cavs population
Run send_daily_notifications or show_daily_digest and see that the job succeeded. 
During population of the content of revision there might be `Custom Attribute Values` for which `Custom attribute definition` was deleted. In this case during generation of email and notifications the code will trigger an error when trying to access CAD name by CAV. The solution is to filter out such CAVs along with CADs.
=> GGRC-7144 Send daily digest is failing

._license_header_exceptions, docs/source/support/aliases.rst, docs/source/support/index.rst
Try steps, described in `aliases.rst` and verify that new aliases work both on Mac OS and Ubuntu
Add document with several useful aliases.
Related info about bash config differences between Linux and Mac OS:
In Linux things work this way:
`.bashrc` is executed every time you launch a new terminal tab or window.
`.bash_profile` is executed only when you login into the computer (that's what is called login shell).
Sources: [stackoverflow](https://stackoverflow.com/q/415403) and [bash man page](https://www.gnu.org/software/bash/manual/bashref.html#Bash-Startup-Files)
That's why in Linux the best solution is to put aliases in `.bashrc`.
But in Mac OS it works a bit another way:
By default Terminal app always launches bash as login shell. Such login shell executes `.bash_profile`, but not …
=> DOCS: Add aliases doc

src/ggrc-client/styles/components/multi-select-label/_multi-select-label.scss
Cannot select label in Edit Assessment popup
1. Open Edit Assessment popup
2. Expand Label dropdown list 
Actual Result: Last item in suggestions is overlapped by assignee screenshot-1.png
Expected Result: Last item in suggestions should not be overlapped by an assignee
3. The select label above Assessment Procedure field
Actual Result: Labels cannot be selected since they are displayed above Assessment Procedure rich text (e.g. "Assessment label", "Audit created by auditor1")
Expected Result: Labels can be selected.
Set autocomplete result box z-index to push it upper than other content.
=> GGRC-6967 Fix label in edit Assessment modal

src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache, src/ggrc-client/js/plugins/utils/snapshot-utils.js, src/ggrc-client/styles/components/action-button/_action-button.scss
Link to original Control is displayed on assessment's control popup despite the fact that original object does not exist any more.
- Create an Assessment & map Control to it
- Remove original Control
- Open Assessment Info pane & open modal for deleted Control
Expected behavior: 
- Button to original Control is disabled
- Link to Control in new frontend is not displayed
Add condition to template based on 'original_object_deleted' flag received from backend to enable/disable button & show/hide link to original Control.
=> GGRC-6748/GGRC-6824 Hide link to original Control for snapshot on assessment

src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
In scope of the migration to CanJS 3 few tests with `can.List` were failed
Expected result: unit tests were successfully passed 
The reason of this issue with `can.List` is empty array passed into it. To fix it filled array should be passed.
=> QUICK-FIX Pass filled array into can.List

src/ggrc/migrations/versions/20190306113217_adf7bdb8996e_rename_reviewer_to_reviewers.py, src/ggrc/models/review.py, test/integration/ggrc/access_control/acl_propagation/test_review_reviewer.py, test/integration/ggrc/converters/test_export_import_reviewable.py, test/integration/ggrc/notifications/test_review_notiffications.py, test/integration/ggrc/review/__init__.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/page/widget/page_mixins.py
"Reviewer' field is displayed on "Request Review" pop-up which should be re-named as 'Reviewers' in all places on UI for all objects that have review.
Go to My Work page
Click "Controls" tab.
Click on a control raw.
Click "Request Review" button.
- "Reviewer' field is displayed on "Request Review" pop-up.
Update the file "/vagrant/src/ggrc/migrations/versions/20190306113217_adf7bdb8996e_rename_reviewer_to_reviewers.py" with the below sql query:
Query : UPDATE access_control_roles SET name = 'REVIEWERS' WHERE parent_id is NULL and name = "REVIEWER";
Note: If the file is not editable change the permissions by logging out of the docker container.
Run the below command in order to execute the sql changes:
python src/ggrc/migrate.py revision -m "Rename reviewer to reviewers" 
Run the below …
=> GGRC-6213 Reviewers should be in plural on UI 

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_export_assessment_templates.py, test/integration/ggrc/converters/test_import_assessment_templates.py
Valid values for Default Assignees / Default Verifiers should be specified in assessment template import / export files
1. Download assessment template import template
Actual result: Valid values for Default Assignees / Default Verifiers are not specified
Expected result: They should be specified
1. Modify src/ggrc/models/assessment_template.py to add valid values for Default Assignees and Default Verifiers
2. Modify below test assessment files
/vagrant/test/integration/ggrc/converters/test_export_assessment_templates.py
/vagrant/test/integration/ggrc/converters/test_export_assessment_templates.py
=> GGRC-5365 Add valid values for Default Assignees/Verifiers in Assessment Template

src/ggrc/builder/json.py, src/ggrc/models/mixins/with_readonly_access.py, src/ggrc/services/common.py, src/ggrc/services/resources/relationship.py, test/integration/ggrc/models/mixins/test_with_readonly_access.py
For now all objects on GGRC side are marked as read-only and we can’t change them through the api. To fix it we need to allow processing requests from external users.
Expected behaviour of GGRC for API requests made by external user:
1. It is not expected that sync service sends any requests to endpoints which start from the following paths: “/api/relationships”, /api/add_folder, /api/remove_folder. No changes will be made to these endpoints, so GGRC will behave for external user the same as for normal user
2. It is not expected that sync service sends DELETE requests to api/systems/<id> endpoint. Behaviour of GGRC will be the same as for normal user.
3. Sync service can send POST/PUT requests to /api/systems and /api/systems/<id> endpoints. GGRC have to allow such requests no matter …
=> GGRC-7067 Allow edit readonly objects for external user

src/ggrc/migrations/versions/20190404_014ddab36256_resolve_duplicates_in_access_control_.py
Table `access_control_people` sometimes contains duplicated records for `person_id`/`ac_list_id` pair. The goal is to remove duplicates from DB and create `UNIQUE CONSTRAINT` for this table
Migrate DB with and without duplicated records, ensure app works as expected
1. Remove duplicates if any
2. Add constraint
=> GGRC-6717 Remove duplicates from ACP and add unique constraint

src/ggrc-client/js/components/custom-autocomplete/tests/autocomplete-input_spec.js
`jasmine.clock().uninstall()` is used in `autocomplete-input_spec.js` like a workaround for jasmine clock issue. In combination with no usage in one test about 150 tests are failed in migration for CanJS 3.
Install/uninstall clock separately in tests.
=> QUICK-FIX Use jasmine clock separately

src/ggrc/migrations/utils/custom_attributes.py, src/ggrc/migrations/versions/20190423_fd7f3834a37e_custom_attribute_added_to_control_for_.py
New Custom attribute for Control is needed.
1. 
GCA Title = Operating Procedure
Type = Rich text
Inline help = EMPTY
Placeholder = EMPTY
Is Mandatory = false
2.
GCA Title = Control Narrative
Type = Rich text
Inline help = EMPTY
Placeholder = EMPTY
Is Mandatory = false
Rum migration ad check that all  controls had new global custom attributes.
Since we can't edit controls anymore attributes were added by migration.
=> GGRC-7108, GGRC-7186 Add Custom attributes to control.

src/ggrc/services/__init__.py, test/integration/ggrc/generator.py, test/integration/ggrc/models/mixins/test_customattributable_preconditions_failed.py, test/integration/ggrc/models/test_control.py
Custom attribute values on read only objects or archived objects can be edited manually via api requests.
spoof an api request to /api/custom_attribuet_values/id for a control or any read only object.
Since we never use cav api and all edits should only be done on objects themselves, we removed the entire service. This ensures proper checks on the parent objects will be done if we try to edit a custom attribute value.
=> GGRC-7058 Remove custom attribute value api

src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Three dots are not displayed for rich text fields if content is very long and doesn't have white spaces
1. Open 'Create Control' or other object modal
2. Fill 'Description' field w/ very long text w/o white spaces (300+ symbols)
3. Fill out all mandatory fields and click 'Save'
4. Open 'Global Search' modal & perform search by 'Control' or the respective object type
5. Add 'Description' to be displayed
Actual behavior: 3 dots are not displayed at the end of 'Description' field content.
Expected behavior: If text is not fully displayed then 3 dots should be displayed at the end of visible content.
Modify css properties in src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss file
=> GGRC-6525 Fix display of three dots for rich text fields

src/ggrc/converters/base.py, src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/boolean.py, test/integration/ggrc/models/mixins/test_with_readonly_access.py
The goal is to allow global admin unset flag `readonly` for Systems
1. Ensure that global creator who is admin assigned as admin for read-only system cannot unset flag `readonly` via import
2. Ensure that global admin can unset flag `readonly` via import
=> GGRC-7031 Allow global admin unset flag readonly for SOX Systems via import

src/ggrc/converters/handlers/acl.py, src/ggrc/converters/handlers/comments.py, test/integration/ggrc/converters/test_import_comments.py, test/integration/ggrc/test_csvs/import_comments_without_assignee_roles.csv
User role in Assessment is not displayed in UI after importing a comment.
1. Log in to ggrc app.
2. Click on Import link
3. Import an Assessment, containing few comments. The assessment must contain all required mappings.
4. After successful import of Assessment, open the Assessment info page and verify if associated comments are imported successfully.
* Defined the function 'insert_object' in 'src/ggrc/converters/handlers/acl.py'.
* The function determines if the current user is assigned to any role. If current user is assigned a role and comments are associated with the imported parent object, the role is set to those comments.
=> GGRC-4290,GGRC-6822 Display user role for imported comments

src/ggrc/access_control/role.py, src/ggrc/models/custom_attribute_definition.py, src/ggrc/utils/validators.py, test/selenium/src/lib/entities/entities_factory.py, test/unit/ggrc/models/test_access_control_roles.py, test/unit/ggrc/models/test_custom_attribute_definition.py
It is possible to create GCA with title like "map:person". Then when we will try to import such GCA object will not be cteated
1. Log in to GGRC as admin user
2. Open Admin page > Custom attributes tab
3. Select an object, e.g. Technology Environment
4. Create GCA with title "map:person"
Actual Result: There is no validation during creating GCA with title "map:person" (as an example)
Expected Result: The system should validate title of gca while creating it.
Add title validation for GCA. We should not allow users create GCA with title starts with "map:" or "unmap:".
=> GGRC-5635 GGRC-7024 No validation during creating GCA with title "map:person" or "*"

src/ggrc/automapper/__init__.py
A lot of log entries about automapping with zero count 
For example send_calendar_events should not flood logs.
Log only events with non zero automappings
=> QUICK-FIX Do not log zero automapping events

src/ggrc/fulltext/mysql.py, src/ggrc/migrations/versions/20190417_2168ca30ae3b_add_index_on_fulltext_record_properties.py, src/ggrc/services/common.py
Search for "Mapped to" under "Filter by Mapping" on export page works slow.
1. Go to export page;
2. In "Filter by Mapping" section select object type and start typing;
3. Check timings in dev tools.
Search in filter by mapping is performed with search API. In addition user is able to see the preview of search results by hovering it. All this is achieved with two HTTP queries: first one performs actual search and second one queries objects by ids search query returns.
Both queries works slow, sometimes search query may take up to 3 sec to return search results (e.g. in case of Assessments).
The following changes are introduced here to improve performance (however the performance improvement is not that significant):
1. A composite index is added on `type` and `property` fields on …
=> GGRC-5534 Reduce latency in filter by mapping search on export page

src/ggrc-client/js/components/last-comment/last-comment.js, src/ggrc-client/js/components/last-comment/last-comment.stache, src/ggrc-client/js/components/last-comment/last-comment_spec.js
It fixes issue when creating new assessment and there is no last_comment field.
"Uncaught TypeError: Cannot read property 'replace' of null" if select Last comment column in tree view for asmt
1. Open audit page
2. Create assessment 
3. Set Last comment column in tree view
Actual Result: "Uncaught TypeError: Cannot read property 'replace' of null" error is displayed, spinner rounds endlessly in tree view
Expected Result: no errors should be displayed, asmt should be displayed in tree view
Rewrite helper `getText` as getter for prop `commentText` using define plugin. Return empty string if there is no `last_comment` field in assessment.
=> GGRC-7252 Add commentText getter for last-comment

test/selenium/src/tests/test_workflow_page.py
*Daily digest is not opened at CI nodes.*
*Run tests at CI and check that daily digests tests are not xfailed.*
*Remove xfail handling from tests for this issue.*
=> GGRC-6527 Remove xfail handling for selenium tests

src/ggrc-client/js/components/revision-log/revision-page.js
Change log can not be opened when there is no "modified_by" data in automapping revision.
***Preconditions:***
* there is an object with the automapping revision where "modified_by" field is empty (e.g. automapping of issue: raised issue on assessment is automapped to audit)
* automappings were performed before 2.3 release
***Steps:***
Open the "Change log" tab of the object
*Actual result:* Change log is loading, JS error occurs;
*Expected result:* Change log is displayed without errors;
- Use `modified_by` field from revision (not from automapping);
- Replace user name with `"unknown" user` if `modified_by` is empty;
=> GGRC-7255 JS error while opening the change log tab

src/ggrc-client/js/models/business-models/cycle.js, src/ggrc-client/js/models/business-models/tests/cycle_spec.js
Active Cycles/History tabs are not refreshed if Cycle is deprecated or restored
1. Create Repeat off workflow. Need verification TRUE
2. Add 1 task to Task group
4. Open Active Cycles tab and Deprecate Cycle task
5. Click on Active Cycles tab and Look at the History tab: both tabs show 'zero'  
**Actual Result**: Active Cycles/History tabs are not refreshed if Cycle is deprecated or restored  
**Expected result**: Active Cycles/History tabs should be refreshed if Cycle is deprecated or restored
Subscribe to cycle 'status' attribute changes and dispatch event after the Cycle status has changed to or from 'Deprecated' value. In tree-widget-container component listen this event and call the function to refresh tabs.
=> GGRC-5815: Active Cycles/History tabs are not refreshed if Cycle is deprecated or restored

src/ggrc/models/system.py, test/integration/ggrc/models/test_system.py
Sync service send POST/PUT requests (for SOX Systems) where access_control_list is set in format like:
```
{<role name>:[
{"name": <user name>, "email": <user email>}
]}
```
This format differs from GGRC format, so we need to modify ACL setter for GGRC Systems.
Try to create/update System using new ACL format.
Change Roleable to RoleableSynchronizable (this mixin already contain required logic)
=> GGRC-7223 Add possibility to setup ACL in sync service format on GGRC side

src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.stache, src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js, src/ggrc-client/js/components/advanced-search/tests/advanced-search-wrapper_spec.js, src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js, src/ggrc-client/js/plugins/utils/advanced-search-utils.js
Search for Cycle Tasks doesn't properly work:
Default selected Status is Deprecated (should be selected all statuses)
Open global search
Select Cycle Tasks object type
The root cause is the fact, that when we update modelName somehow, stateModel setter is called before modelName is actually updated. Thus in this line we have old modelName, so we get states for old modelName. To fix it, I remove setter, put its code into a separate function, called in search-wrapper and advanced-search-filter-container, which are wrappers for the advanced-search-filter-state
=> QUICK-FIX Canjs 3 migration fix global search

src/ggrc/models/mixins/with_readonly_access.py, test/integration/ggrc/models/mixins/test_with_readonly_access.py
We need to load readonly Systems from GGRC by sync service. Loading will be implemented using /query endpoint. To allow filtration by 'readonly' in /query it should be in fulltext.
Send query request for System model with expression `readonly="yes"/"no"`
Add readonly to _fulltext_attrs.
=> GGRC-7222 Add readonly attribute to fulltext

src/ggrc/services/__init__.py, src/ggrc/services/resources/external_internal.py, test/integration/ggrc/models/test_system.py
GGRC disable PUT request if it doesn't contain If-Match and If-Unmodified-Since headers, but if request comes from sync service it doesn't have such headers (and they are useless there), so headers validation should be skipped.
Send PUT requests to System endpoint without If-Match/If-Unmodified-Since headers (but with "X-external-user" header)
Inherit base Resource class with overriding header validation method.
=> GGRC-7224 Process PUT requests without headers validation for external systems

src/ggrc/migrations/versions/20190511_b194e332fa65_change_risk_type_to_optional.py, src/ggrc/models/risk.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/services/test_revision_history.py
Column "risk_type" for "Risk" model should be changed from mandatory to optional
Check scheme before and after migration - "risk_type" should be optional after migration
Create risk object without risk type
Check create/update Risk on UI - "risk_type" should be optional
Update back-end implementation for "risk_type" column
Update initial scheme with "risk_type"
Add migration for make "risk_type" optional
=> GGRC-7290 Change "risk type" field from mandatory to optional

src/ggrc/access_control/role.py, src/ggrc/integrations/issuetracker_bulk_sync.py, src/ggrc/migrations/versions/20190301113245_bba307188ef6_add_is_empty_column.py, src/ggrc/models/revision.py, src/ggrc/query/custom_operators.py, src/ggrc/utils/empty_revisions.py, src/ggrc/utils/revisions_diff/builder.py, src/ggrc/views/__init__.py, test/integration/ggrc/models/test_revision.py
Now there is a performance issue in change log even with pagination implemented.
The main reason why is that object revision are not just only paginated, but also only "not empty" revisions are queried. A revision is considered "not empty" if it contains any actual changes in object state. This is implemented with `not_empty_revisions` query API operator. Problem is, this operator still needs to go through all the revisions to find "not empty" ones so pagination does not bring any performance improvement.
1. Open change log on object having a lots of changes;
2. See timings.
Expected result: Timings should be less than 2 sec.
The proposed solution is to evaluate revisions at creation time to decide whether revision is empty or not. To do this the following changes where made:
1. New …
=> GGRC-6809/GGRC-6610 Pagination performance

src/ggrc-client/js/models/business-models/cycle.js, src/ggrc/models/audit.py, src/ggrc/models/mixins/__init__.py, src/ggrc_workflows/__init__.py, test/integration/ggrc/access_control/rbac_factories/audit.py, test/integration/ggrc/access_control/rbac_factories/base.py, test/integration/ggrc/access_control/rbac_factories/task_group.py, test/integration/ggrc/access_control/rbac_factories/workflow.py, test/integration/ggrc/models/mixins/test_titled.py, test/integration/ggrc_workflows/generator.py, test/integration/ggrc_workflows/helpers/workflow_api.py, test/integration/ggrc_workflows/test_workflow_api_calls.py, test/selenium/src/lib/rest_services/workflow_rest_service.py, test/unit/ggrc_workflows/models/test_task_group.py
500 HTTP error if API POST request for workflow (and other objects) creation doesn't contain 'title' field.
Root cause: title validator for4 all `Titled` models doesn't raise error if title is None. At the same time, column `title` in DB is not nullable. As result, unexpected `IntegrityError` is raised by SQLAlchemy which leads to 500 HTTP error.
Make API call to create workflow where title field is not added or value equal to null
Expected result: 400 error with message "'title' must be specified"
Improve title validator
=> GGRC-6923 Validate title is specified in API calls

src/ggrc-client/js/components/proposal/create-proposal.js, src/ggrc-client/js/components/related-objects/proposals/related-proposals.js, src/ggrc-client/js/components/related-objects/related-objects.js, src/ggrc-client/js/events/eventTypes.js
Proposal is not displayed in Change Proposals tab w/o page reload
3. Make a proposal
4. Open Change Proposals tab and look at the Proposal
**Actual Result:** Proposal is not displayed in Change Proposals tab
**Expected Result:** Proposal should be displayed in Change Proposals tab after saving
After POST request for proposal creation background indexing job is being started, in case this job isn't yet finished when query for updated proposals is being sent newly created proposal won't be included in response.
Solution: Add POST response object right to the proposals list instead of refreshing on FE.
=> GGRC-6483 Add new proposal to the Proposals list

src/ggrc/models/revision.py
List of recipients can be empty for objects that were moved to GGRCQ (Control, Risk and etc.)
In that case validation on string should be added for correct implementation
Generate request for objects that were moved to GGRCQ (control for example) without recipients
Recipients population were updated with additional string validation
=> GGRC-7305 Remove "recipients" sorting from "content"

src/ggrc/converters/import_helper.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/models/reflection.py, src/ggrc/views/converters.py, test/integration/ggrc/converters/test_assessment_csv_template.py
To limit number of fields included in generated CSV file for Assessments extra filtering by template ids is implemented.
New user interface feature was implemented for downloading template CSV import file. Now user can select assessment templates which should be used for gathering custom attributes to include in CSV file thus limiting number of processed assessment templates thus speeding up CSV file generation. Previously if many assessment templates existed it took too long to process all of their custom attributes to generate template CSV import file.
1. Log in to GGRC-TEST
2. Open Import page
3. Click on 'Download Import Template' > Select 'Assessment' object type from the list
4. Select Assessment templates to use for custom attributes gathering <- new UI feature [GGRC-5880]
4. Click …
=> GGRC-7116 BE: Latency while downloading Assessment CSV import template 

src/ggrc-client/js/components/reusable-objects/reusable-objects-item.js, src/ggrc-client/js/components/reusable-objects/tests/reusable-objects-item_spec.js
If select url/file to reuse, checkbox becomes unchecked after clicking 'show more' link
1. Log in ggrc-app and open any audit page with mapped control snapshot
2. Generate two assessments based on the control snapshot
3. Add evidence file and url to one assessment 
4. Open second assessment info panel > Related assessment tab
5. Check checkboxes to reuse evidence file and url
6. Click on 'show more' link: checkboxes got unchecked
7. Check one checkbox: the second becomes selected
**Actual Result:** If select url/file to reuse, checkbox becomes unchecked after clicking 'show more' link
**Expected Result:** If select url/file to reuse, checkbox should not be unchecked after clicking 'show more' link
`show-more` component rewrites content on every click on `show more/show …
=> GGRC-7057 Fix issue when checkbox becomes unchecked after clicking 'show more' link for reusable objects

src/ggrc-client/js/plugins/tests/utils/deferred-transaction-utils_spec.js
The strange code in deferred transaction tests.
And sometimes the last test fails on my PC.
[Related comment in CanJS 3 migration PR](https://github.com/google/ggrc-core/pull/9198#issuecomment-489145126)
Run `run_karma` inside container
Move call of the `done` callback after all expectations and increase the timeout in the last test.
=> QUICK-FIX Improve deferred transaction tests

src/ggrc-client/js/components/datepicker/datepicker.js, src/ggrc-client/js/components/tests/datepicker_spec.js
This PR is `on hold` until:
1. Open New/Edit modal for Risk
2. Set Effective Date manually or type text
3. Click out of field
_Actual Result_: "Uncaught TypeError: Cannot read property '**datepicker**' of undefined" error is displayed
_Expected Result_: no errors should be displayed, prohibit to set a date manually, user should be able to set a date from date picker
Use `viewModel` argument as array (depends on canJs 3 migration)
=> GGRC-7275 Uncaught TypeError: Cannot read property 'datepicker' of undefined

src/ggrc-client/js/templates/assessment_templates/info.stache
Cannot change "Default Assignees" or "Default Verifiers" if selected "other" option
1. Open any assessment template
2. Open edit modal
3. Choose "other" option in "Default Assignees" dropdown and add 1+ person
4. Save assessment template
5. Open edit modal again
6. Try to change value of "Default Assignees" dropdown.
_Expected result:_ value of "Default Assignees" is changed.
_Actual result:_ the application throws javascript exception
Use `{{#}}` statement instead of `{{#each}}` to avoid triggering of "person-data.personId" setter before triggering of "**isArray**" helper.
Because _{{#each}}_ helper adds event handlers which work async and can be called before "**isArray**" helper
=> GGRC-7299 Cannot change "Default Assignees" or "Default Verifiers" if selected "other" option

src/ggrc/migrations/versions/20190509_f68d49c6e2c4_delete_deprecated_risk_objects_table.py
After removing of risk objects, the risk_objects table became obsolete and should be removed
Run the following query after doing the db_reset:
select * from risk_objects;
Below is the expected output for the above query:
ERROR 1146 (42S02): Table 'ggrcdev.risk_objects' doesn't exist
Update the file "src/ggrc/migrations/versions/20190509_f68d49c6e2c4_delete_deprecated_risk_objects_table.py" with the below sql query:
Query : conn = op.get_bind()
conn.execute("DROP TABLE risk_objects;")
Note: If the file is not editable change the permissions by logging out of the docker container.
Run the below command to execute the changes:
db_reset
Run the below query to verify that the changes were made successfully:
select * from risk_objects;
=> GGRC-5172 Delete deprecated risk_objects table

src/ggrc/converters/__init__.py
Risk type should be only exportable from GGRC side, not importable
Try to import Risk from UI - it's should not be possible
Try to export Risk from UI - it's should be possible
Run integration/unit tests
Update constants from import/export tamplates
=> GGRC-7309 Remove "Risk" type from import template

src/ggrc/models/mixins/autostatuschangeable.py, src/ggrc/models/mixins/rest_handable.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/services/common.py, src/ggrc/services/resources/relationship.py, test/integration/ggrc/notifications/test_assignable_notifications.py, test/integration/ggrc/services/test_common.py
There is not such user case where source/destination objects can be   changed for relationship object. However, it's possible make PUT request to /api/relationships/<id> which   potentially can modify source/destination.  
The goal of this ticket is to ensure that FE doesn't use PUT requests to /api/relationships/<id>, and   disallow PUT (modifying) requests to this endpoint.
Run in the container command run_integration to verify the added test 'test_put_relationship_405' is working properly
raise MethodNotAllowed error in def put() method for the urls that are matches **/api/relationships/[0-9]+$** expression
=> GGRC-7059 Removes ability to modify relationships via PUT method

src/ggrc-client/js/models/service-models/external-comment.js, src/ggrc-client/js/models/service-models/index.js
*Show ExternalComment on Change log.*
=> QUICK-FIX Fix Change Log for Risks&Controls

src/ggrc/integrations/issuetracker_bulk_sync.py, src/ggrc/templates/notifications/bulk_child_sync_succeded.html
"Open" button is missed in notification if tickets generation completed successfully. Button should open audit's assessments list.
1. Open Audit with Issue Tracker turned off;
2. Create an Assessment;
3. Turn on Issue Tracker for audit;
4. Click on Generate button;
5. Open email box and look at the Notification.
Expected Result: "Open" button should be displayed in notification body and should lead to audit's assessments list.
* Add `<a>` tag with link to audit assessment list and appropriate styles to `bulk_child_sync_succeded` notification template.
* Include audit's url in data used to render `bulk_child_sync_succeded` template.
=> GGRC-6040 Add missed "Open" button in successful ticket generation notifications

src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.stache
**ON HOLD until #9356 is merged**
Related information popup shows Control instead of Access group
Login to GGRC application:
Open any audit page
Map control and access group to audit
Create assessment with Control type
Open Assessment info panel> Other attributes tab
Click Map icon for Related Information and map Access group snapshot to assessment
Click on Access group snapshot to open popup
Actual Result: Related information popup shows Control instead of Access group
Expected Result: Related information popup should show mapped object type
Look at the DESCRIPTION
- Updated the mustache files to show information regarding the mapped object
- Added padding top for the description field
=> GGRC-6801 Related information popup should shows mapped object type

src/ggrc-client/js/components/object-selection/object-selection-item.js, src/ggrc-client/js/components/object-selection/object-selection-item.stache, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache
Unified mapper shows base program as mapped to itself.
1. Login to GGRC app
2. Create four programs titled : 'Program 1', 'Program 2', 'Program 3', and 'Program 4'
3. Click on 'Programs' tab.
4. Click on map button for any of the above programs and search for Object type: 'programs'.
5. In the list of displayed programs, the base program must be unchecked and disabled.
* Defined a new attribute 'isBlocked' in 'src/ggrc-client/js/components/object-selection/object-selection-item.js' and set it to a default value of 'false'.
* This attribute value changes to 'true', when 'isMegaMapping' is true in 'src/ggrc-client/js/components/unified-mapper/mapper-results.js' file.
=> GGRC-7210 Unmap base program from unified mapper

src/ggrc/converters/base_row.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/utils/log_event.py, test/integration/ggrc/converters/test_import_assessments.py, test/unit/ggrc/services/test_common.py
Currently creation of any object leads to execution of big amount of same insert revision queries.
Most of those queries originate from log_event() function call.
Add SQLALCHEMY_ECHO = True in app_engine configuration to see SQL queries in app log
Create Audit
Import Assessment for previously created Adit
Before changes:
- 10+ queries like INSERT INTO revisions (resource_id, ...
After changes:
- 1 query INSERT INTO revisions (resource_id, ...
Refactor log_event() function to insert all revisions related to event in one DB query.
=> GGRC-5112 Revisions insert into db should be done in bulk

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/integration/ggrc/integrations/test_assessment_integration.py
Reverts google/ggrc-core#9430
We have bug now. We can create audit with issue tracker off. than create assessments. 
If wi will turn on issue tracker on audit and change values for integration and then generate tickets it would create tickets with default values instead of audit ones.
=> Revert "GGRC-6812 Cannot turn ON issue tracker for completed assessment"

src/ggrc/services/common.py, src/ggrc/services/constants.py, test/unit/ggrc/services/test_common.py
In some cases validation on relationships were skipped, it's mostly relevant for requests from external service
Run unit/integration tests
Try to make requests with account_balance type and existed relationship -> validation should be worked correct
Add module with dictionary for mapping object_type to types in relationships model
Update get_relationships method with correct validation mapping
=> GGRC-7332 Check and improve relationships validation

src/ggrc/models/evidence.py, test/integration/ggrc/models/mixins/test_with_evidence.py
Evidence file copied few times during every `flush()`.
1. Log in ggrc app and open any audit
2. Attach folder to audit
3. Create assessment and attach evidence file to this assessment from GDrive
4. Open Gdrive and open the folder
Actual Result: Evidence attached to assessment object duplicates in audit folder
Expected Result: Evidence attached to assessment object should not be duplicated in audit folder
Evidence.`_parent_obj` can only be set using API and should be handled only once in `ggrc.models.evidence.Evidence#exec_gdrive_file_copy_flow` during before_flush hook, but it was handled few times because of bug.
Also I removed function `_build_relationship()` since it is unused after #9199
=> GGRC-7271 Evidence attached to assessment object duplicates in audit folder

src/ggrc/models/hooks/relationship.py, src/ggrc/models/relationship.py, test/integration/ggrc/models/test_relationship.py
Currently ext_app can create relationship without is_external flag.
To keep date consistent we need to add such validation.
Create and run tests for that case
Added new hook for validation  to is_external flag in 2 ways:
External user create regular relationships;
Local user create external relationship;
=> GGRC-6954 Validation for ext app relationships creation

src/ggrc/migrations/versions/20190524_b881918e8cdc_set_cav_attribute_object_id_to_null.py
Mappable CAV holds mapped object ID in `attribute_object_id` field. In #9223 all CADs with type `Map:Person` where changed to type `Text` but values in `attribute_object_id` on CAV still remains the same. This causes problems during object serialization in query API.
JSON builder has the following code:
```py
if getattr(obj, '{0}_id'.format(attr_name)):
result = LazyStubRepresentation(
getattr(obj, '{0}_type'.format(attr_name)),
getattr(obj, '{0}_id'.format(attr_name)))
```
So since `attribute_object_id` still holds person ID, for `obj` of `CustomAttributeValue` type and `attr_name = "attribute_object"` code above returns `LazyStubRepresentation` with `type` set to `None`. The reason for it is in the code bellow:
```py
@property
def attribute_object_type(self):
"""Fetch the mapped object …
```
=> QUICK-FIX Set attribute_object_id for global CAVs to NULL

src/ggrc/app.py, src/ggrc/services/common.py, src/ggrc/utils/__init__.py, src/ggrc/utils/error_handlers.py, test/integration/ggrc/maintenance/__init__.py, test/integration/ggrc/maintenance/test_maintenance.py, test/integration/ggrc/models/factories.py
When GGRC is under maintenance, user sees incorrect error messages:
1. If reloading web page - 500 error whithout any content
2. If page was load before maintenance mode, then when FE makes REST API request to GGRC, a message "internal server error" is flashed
1. Turn on maintenance mode
2. Ensure "GGRC is under maintenance" message with error code 503 is shown when FE is making API requests,
3. Ensure that after reloading web page browser is redirected to mainenance page which returns 503 error
1. Change order of before_request/`after_request` hooks is fixed - fix 500 error with empty content
2. Return JSON string with error message for API requests - fix error message for REST API requests
=> GGRC-7312 Show maintenance mode message correctly

src/ggrc-client/js/components/rich-text/people-mention/people-mention.js, src/ggrc-client/js/components/rich-text/people-mention/people-mention.stache, src/ggrc-client/js/components/rich-text/people-mention/people-mention_spec.js
When user is trying to edit already selected ldap value and selects proposed value from autocomplete, then only first part of email (excluding _@domain_) are being changed with the new one.
1. Navigate to a comment block
2. Type email_1 and insert the mentioning
3. Change "1" symbol to "2" by moving cursor and replacing the symbol
4. Click on the "email_2@gmail.com" item in the suggestion list
5. Check the email
Actual Result: "email_2@gmail.com@gmail.com" is displayed
Expected Result: "email_2@gmail.com" is displayed
Do not skip _@domain_ part of the email on replacing previously typed value.
=> GGRC-7124 Behavior is incorrect if user tries to edit the mentioning

src/ggrc/utils/helpers.py, src/ggrc/views/__init__.py
App exceeds the memory limit while deleting GCAs on Administration page and "Server error" is displayed
1. Log as Admin to to App with imported test DB dump
2. Go to Administration > Custom attributes
3. Expand Assessments
4. Remove GCA from Assessments
5. Connect to container in another terminal and launch **top** to monitor memory consumption while deleting GCA 
Actual Result: Memory consumption increases until application crashes
Expected Result: GCA should be deleted and memory consumption in background task should be low
Memory is consumed by **Revision** objects bound to **Event** object and **sqlalchemy_cache**.
This PR addresses second issue by removing sqlalchemy_cache while executing background task. First issue is …
=> GGRC-4055 "Server error" is displayed while deleting GCAs on Administration page

src/ggrc/gdrive/__init__.py, src/ggrc/settings/default.py
When uploading files to assessments, I get asked to auth for what seems like every assessment I complete. This can happen many times in the same day or even in the same session.
Try to attach evidence to assessment with few scenarios. 
1) during day with more than hour interval
2) deploy with reduced cookie lifetime, and check updating expired refresh token
3) Also check imports are working.
Also i think we should notify users that they would be asked to give permissions to our app and should not worry about it.
During authorization on google drive we get access token and refresh token. Access token get 1 hour life limit, but we can use refresh token to get new access token.
Refresh tokens are send only in case of consent prompt at google, that is why I changed it. Also I changed cookie …
=> GGRC-6358 Assessment File Upload - Frequent Auth Requested

src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js, src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache, src/ggrc-client/js/components/assessment/info-pane/templates/ticket-id-checker.stache, src/ggrc-client/js/components/assessment/info-pane/ticket-id-checker.js, src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js, src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache, src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/models/business-models/issue.js, src/ggrc-client/js/plugins/tests/validation-extensions/validate-issue-tracker-issue-id_spec.js, src/ggrc-client/js/plugins/validation-extensions.js, src/ggrc-client/js/templates/assessments/modal_content.stache, src/ggrc-client/js/templates/issues/modal_content.stache, src/ggrc-client/styles/components/simple-modal/_simple-modal.scss, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/issue_tracker.py, test/integration/ggrc/converters/test_import_issuetracked_objects.py
User can trigger new ticket autogeneration for assessments and issues in completed statuses. There is a restriction on Ticket Tracker API side, it allows to create tickets only in 'New' or 'Assigned' statuses. It means that, if Assessment is in 'Completed and Verified' status, the ticket linked to such assessment will have 'Assigned' status, until cron job will change it to Fixed (Verified). This can cause confusions for users, who already completed an assessment and then receive a notification from Ticket Tracker system, that it is required to complete the same assessment.
**SOLUTION:**
Do not allow to autogenerate tickets for assessments that are in 'In Review', 'Completed (no verification)', 'Completed and Verified' and 'Deprecated' statuses.
**ACCEPTANCE CRITERIA:**
**Via UI:** 
For …
=> GGRC-5942/GGRC-5617/GGRC-6633 Do not allow to autogenerate Tickets at Ticket Tracker for Issues and Assessments in some statuses

src/ggrc/migrations/versions/20190502100338_6d7a0c2baba1_add_workflow_parent_id.py, src/ggrc_workflows/__init__.py, src/ggrc_workflows/models/task_group.py, src/ggrc_workflows/models/workflow.py, test/integration/ggrc_workflows/models/test_task_group.py, test/integration/ggrc_workflows/test_api_calls.py, test/unit/ggrc_workflows/models/test_workflow.py
When copied, Task Groups and Workflows were not named properly. After merging those changes, the general convention will be 
`name = old_name + (copy N)`
This PR resolves both  GGRC-4200 and GGRC-4202
1. Create any 'workflow1'
2. In the "workflow info" tab click Clone Workflow in 3 bb's menu
3. Confirm that naming convention is `name = old_name + (copy N)`
1. Create any 'workflow1'
2. In the "setup" tab click Clone Task Group in 3 bb's menu
3. Confirm that naming convention is `name = old_name + (copy N)`
Added a ForeignKey field `parent_id` to both Task Group and Workflow models. This field stores a reference to the parent model, from which it was originally copied. 
While naming the new copy, we iterate through all objects from the same parent, picking the first available copy naming, …
=> GGRC-4200/GGRC-4202 Fix titles of copied Workflows & Task Groups

src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js, src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js, src/ggrc-client/js/components/snapshotter/tests/snapshot-scope-update_spec.js, src/ggrc-client/js_specs/models/mappers_spec.js
4 Deferred exceptions appear in the console as warnings just if you run `run_karma`. Such warnings are completely useless, so should be removed:
1st
```
WARN: 'jQuery.Deferred exception: Cannot read property 'toLowerCase' of undefined', 'TypeError: Cannot read property 'toLowerCase' of undefined
at Map.getResultNotification (webpack-internal:///./js/components/bulk-update-button/bulk-update-button.js:65:44)
at Map.eval (webpack-internal:///./js/components/bulk-update-button/bulk-update-button.js:53:28)
at mightThrow (webpack-internal:///../../../vagrant-dev/node_modules/jquery/dist/jquery.js?369c:3557:29)
at process (webpack-internal:///../../../vagrant-dev/node_modules/jquery/dist/jquery.js?369c:3625:12)', undefined
```
2nd
```
WARN: 'jQuery.Deferred exception: Cannot read property …
```
=> QUICK-FIX Fix deferred exceptions in tests

src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/partials/restore-button.stache, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/partials/three-dots-menu-in-history.stache, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/partials/three-dots-menu.stache, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js
Disable Edit functionality for Cycle Tasks in History tab.
1. Create Repeat off workflow
2. In the setup tab on workflow page create a task for task group
4. In Active Cycles tab End Cycle
5. Open History tab and expand tree view with Cycle Task
Actual Result: User is able to edit Cycle task in History tab:
Can add Task Assignee/ Task Secondary Assignee;
Map Objects;
Open Edit Cycle Task modal window;
Deprecate, delete
Expected Result: Edit functionality should be disabled:
cannot edit (no option in 3 bb's menu), add comment, map, add Task Assignee/ Task Secondary Assignee, deprecate, delete.
`is_in_history` flag was used to determine that cycle task is in history.
=> GGRC-6121 Disable Edit functionality for Cycle Tasks in History tab

src/ggrc/converters/handlers/document.py, src/ggrc/converters/handlers/evidence.py, src/ggrc/converters/handlers/snapshot_instance_column_handler.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/models/mixins/test_autostatuschangable_evidence.py, test/integration/ggrc/notifications/test_assessment_notifications.py, test/integration/ggrc/notifications/test_assignable_notifications.py, test/integration/ggrc/test_csvs/assessment_notifications.csv
User doesn't get notification if update assessment which is "Completed", "Ready for review" states via import
1. Export created assessment in UI (assessment is "Completed", "Ready for review")
2. Update assessment:
editing Assessment mappings through imports
editing Assessment evidence through imports
editing Assessment CA values through imports
3. Import assessment 
Actual Result: User doesn't get notification if update assessment which is "Completed", "Ready for review" states via import
Expected Result: User gets notification if update assessment which is "Completed", "Ready for review" states via import
Send model_posted signal when assessment mapping created. Send model_put signal after secondary_objects insert.
=> GGRC-1715 Send notification if assessment attributes were changed in import

test/integration/ggrc/services/test_query/test_snapshots.py
We have a test with wrong params thats need to be fixed.
Tests should pass same as before.
Fix parameters list.
=> QUICK-FIX Fix wrong test params

src/ggrc/models/risk.py, test/integration/ggrc/converters/test_import_helpers.py
Review state is displayed instead of 'Review status' on Export page
2. Look at the ATTRIBUTES
Actual Result: 'Review state' is displayed
Expected Result: 'Review status' should be displayed
Modify below file to rename Review State to Review Status
src/ggrc/models/risk.py
=> GGRC-7352 Rename Review State attribute for Risks on export page

src/ggrc/converters/base_block.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/converters/test_import_comprehensive.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc_workflows/converters/test_import_task_group.py
Improve a message on the import page
Steps to Reproduce:
1. Log in ggrc app
2. Create program1 and program2
3. Export program1 to google sheet
4. Add 'map:program' column and map program2
5 Import program1
Actual Result: You are not able to map/unmap Program to program via import. The column
{column name} will be skipped.
Expected Result: You are not able to map/unmap Program to Program via import. The column {column name} will be skipped. (programs should be with Capital letter)
Modify below file to improve the message on the import page
src/ggrc/converters/base_block.py
=> GGRC-7250 Improve a message on the import page

src/ggrc-client/js/controllers/modals/modals_controller.js
Mandatory fields in popup are not highlighted in red when we create an object by clicking on 'Save & Add Another' button
1. Open New Assessment popup with mandatory GCA
2. Fill out required fields and click 'Save & Add Another' button
3. In New Assessment popup fill in a title and click out of title field
**Actual Result**: No red color for mandatory CA
**Expected result**: Border for mandatory CA should be displayed
In change event handler for popup the result of checking for isDirty returns false for instance created by clicking on 'Save & Add Another' button because they do not have backup.
Add call backup for instance created by clicking on 'Save & Add Another' button.
=> GGRC-7301 Border is not red for mandatory CA

src/ggrc-client/js/components/mega-relation-selection-item/tests/mega-relation-selection-item_spec.js, src/ggrc-client/js/components/object-mapper/tests/create-and-map_spec.js, src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js, src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js, src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js, src/ggrc-client/js/components/tree/tests/child-models-map_spec.js, src/ggrc-client/js/components/tree/tests/sub-tree-item_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-items-header_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc-client/js/controllers/tests/mapper_spec.js, src/ggrc-client/js/models/mixins/tests/mega-object_spec.js, src/ggrc-client/js/plugins/tests/utils/mega-object-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/object-versions-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js, src/ggrc-client/js/plugins/utils/mega-object-utils.js
Add missing tests for Mega Program FE.
=> GGRC-6794 Add tests for Mega Program FE

src/ggrc/migrations/versions/20190530_0dbe123e4118_remove_mirrored_external_revisions.py, src/ggrc/models/relationship.py, src/ggrc/services/common.py, test/integration/ggrc/__init__.py, test/integration/ggrc/models/test_relationship.py
GGRC allows creating relationships with swapped source/destination.
1. Make 2 POST request to map 2 objects with source/destination fields swapped.
2. Ensure that only one relationship record is created in DB
Do not create relationship is another relationship with swapped source/destination exists.
=> GGRC-7318 Reuse relationship if another relationship with swapped src/dst exist

src/ggrc-client/js/templates/people_roles/option_column.stache
Currently, each option has a tooltip with "map" text. At first sight, this text is ambiguous.
Would be better to have some other text for these tooltips with description of the option selected by the user (or just remove it if it's unneeded here). 
Open Administration page -> People tab.
Select any user.
From 3 dots menu click Edit Authorizations.
Hover your mouse over any option.
Actual result: tooltip with "map" text is showed.
Expected result: no tooltip is shown.
Modify below file to fix tooltip
src/ggrc-client/js/templates/people_roles/option_column.stache
=> GGRC-6571 Fix tooltip for User Role Assignments

src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py
After previous PR https://github.com/google/ggrc-core/pull/9258 objects return extra CADs.
1. Open audit with mapped objective snapshot
2. Open Admin page and add any few GCAs for Objective
3. Refresh audit page and open objective snapshot: new GCAs are displayed (incorrect)
4. Remove GCAs for Objective on Admin page
5. Refresh audit page and open objective snapshot: the least removed GCA is displayed (incorrect)
We should return only CADs that is saved in revision and do not fetch CADs from custom_attributes_description DB table.
=> GGRC-7022 Snapshotable object has last deleted GCA after deleting all GCAs and before getting the latest version

src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js, src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
Conflict resolution message is wrong
1. Open the same assessment in two tabs
2. Open edit modals for them
3. Edit title field in the first tab and save
4. In the second tab enter another value for title field and save
**Actual Result**: 'There was an error!' appears
**Expected result**: 'Please refresh the page and try saving again' should appear
Remove unnecessary notifierXHR call and arguments
=> GGRC-7265 'There was an error' for conflict resolution message

src/ggrc-client/js/components/tree/sub-tree-models.js, src/ggrc-client/js/components/tree/templates/sub-tree-models.stache, src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
"Program_child" and "Program_parent" naming in Filter sub tree 
1. Open programs list. 
2. Open "Filter sub tree" for some program. 
Expected result: "Child Programs" and "Parent Programs" among other options.
Actual result: "Program_child" and "Program_parent"
Use `widgetName` instead of `name` in `displayModelsList` getter in `sub-tree-models`, cause it's almost the same for mega and simple objects. Now, this getter also removes spaces in `widgetName`. Cause mega object's widgetName is space-delimited and simple objects don't contain spaces. So in order to avoid having 2 spaces in mega objects `displayName` we need to remove all spaces in `widgetName`
=> GGRC-7310 Snakecase in mega objects names in filter sub tree 

src/ggrc/models/hooks/__init__.py, src/ggrc/models/hooks/with_action.py, test/integration/ggrc/models/mixins/test_with_action.py
No email notification for mentioning person in assessment
3. Add a comment to assessment with mentioning person
Actual Result: Email notification that user is mentioned in assessment is not sent
Expected Result: Email notification that user is mentioned in assessment should be sent to a user that was mentioned in comment
FE was updated to not send POST relatiships request after creating a comment, but add action section to PUT object request. Action handler on BE should be updated.
=> GGRC-7375 No email notification for mentioning person in assessment

src/ggrc-client/js/components/object-mapper/create-and-map.js, src/ggrc-client/js/plugins/utils/modals.js
Spinner rounds endlessly (instead of 'Activate Workflow' button) if press esc on keyboard
1. Create any workflow
2. Add task to Task group
3. Click on 'Activate Workflow' button
4. Click on ESC on keyboard
**Actual Result**: Spinner rounds endlessly (instead of 'Activate Workflow' button)
**Expected result**: 'Activate Workflow' button should be displayed and enabled
Add esc handler for popup
=> GGRC-7228 Spinner rounds endlessly (instead of 'Activate Workflow' button) if press esc on keyboard 

src/ggrc/services/resources/relationship.py, test/integration/ggrc/services/resources/test_relationship.py
Make validation of "source" and "destination" be independent from the
order in which those fields are set.
It is impossible to map a control onto a program.
(locally, empty DB, Version 1.11.0-Strawberry (dd9207d)) :
2. Create several audits in the program
3. Open one of the audits created and try to map control to the audit.
**Expected result:** a control snapshot is created
**Actual result:** control snapshot is failing to create with the following error:
```
WARNING  2018-05-15 14:03:41,813 common.py:1106] Collection POST commit failed
File "/vagrant/src/ggrc/services/common.py", line 1096, in collection_post
self.collection_post_loop(body, res, no_result)
File "/vagrant/src/ggrc/services/common.py", line 973, in …
```
=> GGRC-5088 Fix validation in Relationship model.

src/ggrc-client/js/components/people/people-list-info.stache, src/ggrc-client/js/components/tree/templates/tree-header.stache, src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache, src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache, src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache, src/ggrc-client/js/models/business-models/person.js, src/ggrc-client/js/templates/people/filters.stache, src/ggrc-client/js/templates/people/info.stache
Authorization field for person on 'People' tab contains list of all roles in scope of current object. On the other hand 'Authorization' section on Person Info pane contains 'Global Role' for specified person. Different content for the same field may lead to confusion.
Part 1. System Authorizations
1. The 'AUTHORIZATIONS' column on the People tab of the Administration page should be re-named to 'SYSTEM AUTHORIZATIONS' 
2. The 'AUTHORIZATIONS' attribute of the Person Info page should be re-named to ' SYSTEM AUTHORIZATIONS'
3. The 'AUTHORIZATIONS' attribute of the Person for Global Search should be re-named to ' SYSTEM AUTHORIZATIONS' (includes: 'Set visible fields for Person' menu, Attribute dropdown, AUTHORIZATIONS column)
4. Check places the field is also displayed and re-name it there as …
=> GGRC-6650 Fix title for 'Authorization' attribute on 'Person' tab

src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc-client/js/components/sort-component/sort-component.js, src/ggrc-client/js/templates/programs/info.stache, src/ggrc-client/styles/modules/_modal.scss
Some fields in comparison window are not been marked as changed. The issue caused by the reason that comparable modals are not been fully rendered prior the actual comparison.
1. Create a Control
2. Map a Control to an Audit
3. Add/change value of assertions for Control
4. Open Audit page > Controls tab > Info panel > click on 'Get the latest version' link
Actual Result: Changes for assertions are not marked (currently green color)
Expected Result: Changes for assertions should be marked (currently green color)
Set timeout to let template fully render. General refactoring.
=> GGRC-6994 Changes for some fields are not marked in comparison window

src/ggrc/converters/base_block.py, src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/converters/import_helper.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/models/reflection.py
Currently export of a single assessment with small number of CADs and assignees takes an unreasonable amount of time - about 10 s. It should be faster.
1. Create assessment with:
* 1 creator;
* 2 assignees;
* 2 verifiers;
* 1 mapped control snapshot;
* 2 gca.
2. Export created assessment like this (no LCA and 2 GCA selected):
Solution includes following changes:
1. Cache of snapshots mapped to object being passed to the row converter is created. It allows to rewrite snapshot column handler to use this cache of snapshots to simplify query needed to get an object for which snapshot was created. It leads to performance improvement since SELECT by ID is faster than query in `snapshoted_instances_query` method that was in use before this change.
2. Custom attribute definitions cache on …
=> GGRC-5793 Improve performance for single assessment export

src/ggrc-client/js/templates/programs/info.stache, src/ggrc/models/mixins/__init__.py, src/ggrc/models/program.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/api/test_folder_field.py, test/integration/ggrc/models/mixins/test_autostatuschangable.py, test/integration/ggrc/models/test_audit.py, test/integration/ggrc/models/test_program.py, test/integration/ggrc/services/test_revision_history.py
Make 'slug' and 'folder' fields not updatable to remove them from diff builder.
Fix recipients handling in diff builder - do not show diff if recipients reordered but not changed.
This PR is `on hold` until the FE PR merged:
Revisions functionality is currently available for Risks.
We need to replicate the flow for Programs.
Two places of the app should be updated:
1. The 'Review & Apply' button should be added to the Change Proposals tab of the Program
2. The 'Review: Compare to Current' modal window
This PR provides minor BE fixes for Programs 'Version History'
1. Open Program with id=131 (qa dump)
2. Open 'Version History' tab
Before changes:
- Code(slug) and folder can be restored from version history
- Some revisions have reordered 'Recipients' that are shown as diff
After changes:
- …
=> GGRC-6977/GGRC-7216/GGRC-7217 Add revisions for program

src/ggrc/fulltext/attributes.py, test/integration/ggrc/models/test_risk.py
Current implementation of DatetimeFullTextAttr do not supports empty attributes. It leads to error during reindex of shapshot.
1. Have the audit with mapped Risk snapshot
2. Make updates of the Risk  via API call or on Q side.
3. Go to Risk tab on the audit page
4. Update Risk snapshot to latest version
Actual Result: PUT 500 is displayed in console, no message that snapshot was successfully updated
Expected Result: no errors should be displayed, snapshot should be updated
Updated implementation of DatetimeFullTextAttr to support empty attributes.
=> GGRC-7429 Fix 500 when updating Risk snapshot to latest version.

src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field.js, src/ggrc-client/js/components/assessment-templates/add-template-field/add-template-field_spec.js
The character "*" should not be allowed in any local custom attribute title
1. Try to create a local custom attribute with "*" in the title
**Actual Result**: Attributes with invalid titles are created
**Expected result**: User should not be able to do that
Add isInvalidTitle validator for checking "*" in custom attribute title.
=> GGRC-7025 FE: prevent "*" character to be used in local custom attribute names

src/ggrc/models/exceptions.py, test/integration/ggrc/models/test_program.py
*Create Program via rest with following body:*
*[{"program": {"status": "Draft", "kind": "Directive", "send_by_default": true, "managers": ["user@example.com"], "description": "", "recipients": "Admin,Primary Contacts,Secondary Contacts", "title": "Program_1ea9d2a8-c93b_06E~(}Hh(fgwb", "notes": "", "custom_attributes": {}, "custom_attribute_definitions": [], "context": null, "review": {"status": "Unreviewed", "reviewers": null, "last_reviewed_by": null}, "access_control_list": [{"person": {"type": "Person", "id": 2}, "ac_role_id": 1333}], "slug": "e72669b9-0587"}}]
Actual result: empty response text
Expected result: response text with error message*
*Run command: nosetests -s test/integration/ggrc/models/test_program.py:TestProgram.test_create_program_with_wrong_recipients
or send a POST …
=> GGRC-7206 Adds error content in blank 400 program response

src/ggrc/models/control.py, test/integration/ggrc/models/test_control.py
Error during updating of control by sync service.
Run sync from External App to GGRC.
Run test.
Control model has wrong deserialization logic for created_by attribute. It leads to error during revision comparison. I've fixed this method to use person stub instead of raw model.
=> HOT FIX Updated Control.log_json method to contain person stub instead of model.

src/ggrc/access_control/utils.py, src/ggrc/cache/utils.py, src/ggrc/models/hooks/acl/__init__.py, src/ggrc/models/hooks/acl/propagation.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/models/hooks/acl/test_propagation.py, test/integration/ggrc_basic_permissions/test_permissions_loading.py
Permissions recalculated in cache on every PUT or POST request. As the result cache is used in a very ineffective way. This may be one of the reason why app works slowly for users with lots of ACLs. 
Test next cases on deployed version on test masha-to-test-acls (or locally):
1. Add new ACL;
2. Delete ACL;
3. Delete object;
4. Add/remove URL;
5. Map/unmap object;
6. Add Comment.
Verify that benchmarks look correct.
Call /admin/propagate_all job. Check that no errors appear.
Check that import didn't become slower.
Permissions in cache should be recalculated only for cases when propagation is needed (add ACL, delete object, add relationship). If ACL is added, permissions could be recalculated only for this specific user.
This solution does not speed up permissions query since it's difficult …
=> GGRC-7009/GGRC-6867 Improve permissions caching

src/ggrc/contributions.py, src/ggrc/notifications/common.py, src/ggrc/notifications/data_handlers.py, src/ggrc_workflows/notification/data_handler.py, test/unit/ggrc/notification/test_init.py
show_daily_digest take a huge amount of time to generate notifications
1. Open _notifications/show_daily_digest page for instance with huge amount of notifications (~30 000) and a lot of CADs (200 000).
Add ca_cache parameter to send daily notification functions,
=> GGRC-5052 _notifications/show_daily_digest page is loading all the time

src/ggrc/gcalendar/calendar_event_sync.py, src/ggrc/utils/__init__.py, src/ggrc/views/__init__.py
Server and Background task logs the wrong number of objects and have a log process of updating because of that
1. Open admin page
2. Type to add new GCA
3. Take a look at server console logs
Expected result: Server and Background task must correctly send the number of objects and finally update and log to the console on time
Actual result: Background task processing for the long time and do not stop logging the objects, even all objects where updated
There were changed the logic of counting the objects which have to be updated while background task
=> GGRC-7159 FIxes long processing while updating CAD

src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache, src/ggrc-client/js/components/tree/tests/tree-visible-column-checkbox_spec.js, src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js
Warnings, shown when you open any object list on dashboard:
`can-stache/src/expression.js: Unable to find helper "title".`
Open any object list, e.g. `/dashboard#!requirement`
Click on the hamburger menu (3 lines) on the top left
Warnings show because in some cases `title`, used in `tree-visible-column-checkbox` is function, and in other it's a string. And when it's string stache tries to resolve `title` as a helper, but there's no such helper, so it reports warning.
Solution is to create a function in `tree-visible-column-checkbox` which will generate a title based on the item and incapsulate logic of determination if title is a string or a function.
Also I simplified logic of selection and reduce code duplication.
=> QUICK-FIX Improve tree visible column checkbox

src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/components/workflow/cycle-end-cycle.js, src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js, src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js, src/ggrc-client/js/components/workflow/workflow-activate.js, src/ggrc-client/js/components/workflow/workflow-start-cycle.js, src/ggrc-client/js/controllers/info_widget_controller.js, src/ggrc-client/js/controllers/tree/list_view_controller.js, src/ggrc-client/styles/_widget.scss, src/ggrc-client/styles/modules/_modal.scss
Need to unify the count on tabs across the app. 
Current behavior:
- Filtering on advanced search - causes tab count change
- Filtering through basic search - doesn't cause the tab count change
Expected behavior:
- On all tabs with counts in case any filtering applied - the tabs counts should show the number of filtered items.
Case#1:
- Open any object tab
- Apply filter (simple & advanced) or filter by status
Expected behavior: Counts have been changed accordingly
Case#2:
- Open any object tab
- Create any object using LHN
Expected behavior: Counts have been changed accordingly
Case#3:
- Open any object tab
- Apply some filter (by status, simple or advanced)
- Create or Delete some object
Expected behavior: Counts have been changed accordingly
Initiating counts update on filtering and …
=> GGRC-6528 Tab count should display total amount of records across the app

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/snapshot_instance_column_handler.py, test/integration/ggrc/converters/test_import_issues.py
User can map snapshot to Issue via import
1. Have an audit with mapped snapshot
2. Create an Issue on the audit page
3. Export Issue 
4. Open csv file and map snapshot to Issue> Save changes
5. Import csv file with Issue
6. Expand subtree for Issue and look at the mapped objects: snapshot is shown
7. See warning message "You cannot map snapshots to Issue directly."
Disabled possibility to map snapshot to issue via import.
=> GGRC-3622 Disabled to map snapshot to issue via import

src/ggrc/migrations/versions/20190514_437d91566937_make_user_mandatory_for_person.py, src/ggrc/migrations/versions/20190604_1f6da86c4564_update_empty_name_from_email.py, src/ggrc/models/person.py, src/ggrc/services/common.py, test/integration/ggrc/converters/test_import_audit.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/fulltext/test_mysql.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/test_csvs/people_order.csv, test/integration/ggrc/utils/test_user_generator.py, test/integration/ggrc_workflows/helpers/person_setup.py
Make name field mandatory for User model
For users with empty name, name should be populated from email (parsed by @ and get ldap)
Create user without name from API
Create user without name from import
Create user without name from UI
Add migration to populate users without name with ldap
Add migration to make name column mandatory
Add back-end logic for get ldap from email for user without name
=> GGRC-3837 Make name field mandatory for User model

src/ggrc/integrations/constants.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/integration_utils.py, test/integration/ggrc/integrations/test_assessment_integration.py
1. Log in ggrc app and open Audit with Issue Tracker OFF
2. Create 2 assessments and move to 'In Progress' and 'Rework Needed' statuses
3. Switch ON Issue Tracker for the Audit:
4. Open Edit modal of any assessment which in 'In Progress' and 'Rework Needed' statuses and Switch ON Issue Tracker > Save
Actual Result: 'Unable to create a ticket' is displayed screenshot-1.png 
5. Open Audit Info tab and click on Generate button
Actual Result: Error while generating Assessments is shown. Issue Tracker doesn't allow to create a ticket in 'Accepted' state.
Expected Result: Allow to autogenerate tickets for assessments that are in 'In Progress' and 'Rework Needed' statuses and status of the ticket should be 'Assigned' in Issue Tracker
1. …
=> GGRC-7483 Cannot autogenerate tickets for assessments that are in 'In Progress' and 'Rework Needed' statuses

src/ggrc-client/js/components/tree/tree-field-wrapper.js
Unsaved person is shown on Task Group tree view.
1. Open Edit Modal for Task Group
2. Remove predefined task group assignee and choose any other 
3. Click Close button
4. Click Discard button
The issue is that after restoring source data, `'{viewModel} source'` event isn't called as the object is the same, only with changed data.
1. Updated `tree-field-wrapper` with trigger on _id_ change
=> GGRC-7458 Fix bug when unsaved person is shown on tree view

src/ggrc/converters/base_block.py, test/integration/ggrc/converters/test_export_assessments.py
There is case when particular assessment is being exported and it does not have all LCAs that FE passed to BE. And since only CADs of objects being exported are cached, a `KeyError` occures.
1. Log in ggrc app;
2. Export any assessment but select LCAs which exported assessment does not have;
**Expected result: there should not be any errors during assessment export.**
Check if field is present in `self.object_headers` during `generate_csv_header` method before trying to get this field form `self.object_headers`.
=> GGRC-7496 Fix assessment export errors cased by caching and LCAs

test/integration/ggrc/converters/test_import_csv.py
There aren't tests for checking to import objects without code
Added new integration test that checks to import objects without code
=> GGRC-4895 Add test for importing objects without code

src/ggrc/query/custom_operators.py, test/integration/ggrc/models/test_issue.py, test/integration/ggrc/query_helper.py
'Related audit' section is shown up in unmapping popup if Issue is manually mapped to Audit
1. Have an audit with snapshot A
2. Create Assessment 1 and map snapshot A to assessment 1
3. On Audit page on Issues tab create an Issue and map it to the Audit.
4. Map the Issue to Assessment 1.
5. Open Issue page in a separate tab
7. On the Issue page in the Assessments tab click 'Unmap from Issue' from 3 bb's menu
8. See that 'Related audit' section was not shown up in unmapping popup.
'Related audit' section is not shown up in unmapping popup if Issue is manually mapped to Audit
=> GGRC-3652 Fix to unmap issue from assessment

src/ggrc/services/resources/access_controle_role.py, test/integration/ggrc/access_control/test_access_control_role.py
User can to create custom role with configuration: (read: no and edit: yes or delete: yes).
1 Log in as Global Admin.
2 Try to add a custom role with configuration (read - no and edit - yes or delete - yes).
3 Custom role is NOT created.
Added checking of options during creating new custom role. If options are wrong we will raise ValueError and return 400 response code.
=> GGRC-7083 Fix creating custom role with wrong options

test/selenium/src/lib/element/info_widget_three_bbs.py, test/selenium/src/lib/page/modal/person_modal.py, test/selenium/src/lib/page/widget/widget_base.py, test/selenium/src/lib/service/admin_webui_service.py, test/selenium/src/tests/test_admin_dashboard_page.py
*Add test to check that edit authorization works on WebUI.*
=> GGRC-7466 Add test for editing person authorization

src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js
Incorrect behaviour of saved searches paging 
Note: The issue is reproducible if only one Saved Search item is presented on the last page of the Saved Searches list.
1. Log in GGRC app and open Global Search pop-up
2. Create the list of saved searches with only one Saved Search item for example on the third page (you need to have 21 saved search items)
3. Go to the last Saved Searches page
4. Go back on on the previous page
_Actual result_: The first page with Saved Search items is displayed.
_Expected result_: The second page with Saved Search items is displayed
Move **decrease current page logic** to `removeSearch` handler
=> GGRC-7537 Switching between pages for Saved Search items works incorrect

src/ggrc/migrations/versions/20190617_17fbb17f7cec_map_one_person_to_one_userrole.py, src/ggrc_basic_permissions/models.py
A User is having multiple user roles defined. This is not correct as per design.
1. Log into ggrcdev database from backend.
2. Run the below command and ensure that the count of **user_count** and **user_roles_count** is same.
> select count(distinct person_id) as user_count, count(id) as user_roles_count from user_roles;
3. Also run the below command and check if 'person_id' column in 'user_roles' table got unique constraint.
> desc user_roles;
Created a migration file, which retains the highest user role for user having multiple roles, and deletes the other roles from database.
=> GGRC-1863 Remove duplicate user roles for a user

test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_snapshots.py
Check that audit created with checked manually mapping snapshots option doesn't have snapshots.
=> GGRC-7548 Check that audit created with selected manually mapping snapshots option doesn't have snapshots

src/ggrc-client/js/components/diff/templates/instance-diff-items.stache, src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.stache, src/ggrc-client/js/components/revision-log/revision-log-data.stache, src/ggrc-client/js/components/revision-log/revision-page.stache, src/ggrc-client/js/helpers.js, src/ggrc-client/js/templates/base_objects/extended_info.stache
Description text in Change Log tab and in Proposals tab could be too large so we need a way to Show/Hide it
- Create Program
- Add large description
- Navigate to Change Log tab
- There you should now see `Read more` link/button
- Add Proposal
- Navigate to Proposals tab
- There you should now see `Read more` link/button
- Open burger menu and hover over the newly created program
- You should see Description and `Read more` link/button
I have simply added `read-more` component to corresponding templates
=> GGRC-7322 add read more read less to change proposal and changelog tabs

src/ggrc/migrations/utils/external_cads.py, src/ggrc/migrations/versions/20190713_c4f1d9267f88_move_cad_to_external_cad.py
Migrate CADs to external CADs
Run migration and check that CADs for risk/control will be migrated successfully
Add migration for CADs
=> GGRC-7403 Migrate CADs to external CADs

src/ggrc/migrations/utils/external_cads.py, src/ggrc/migrations/utils/external_cavs.py, src/ggrc/migrations/versions/20190713_8937c6e26f00_move_cav_to_external_cav.py, src/ggrc/migrations/versions/20190713_c4f1d9267f88_move_cad_to_external_cad.py
Migrate CAVs to external CAVs
Depends on:
Run migration and check that CAVs from risk/control will be moved to external CAVs
=> GGRC-7403 Migrate CAVs to external CAVs

src/ggrc/migrations/utils/acr_propagation_constants_program_proposals.py, src/ggrc/migrations/versions/20190725_f00343450894_creator_reads_program_proposals.py, test/integration/ggrc/proposal/test_custom_creator_role.py
Global Creator with custom role (Program Readers/Editors) for a Program doesn't see proposals created by other users
1. Log as Admin user and open Admin page
2. Add Custom role for PROGRAM with readonly rights, e.g. Program Reader'
3. Create a program
4. Add Global Creator user to 'Program Reader' field
5. Log as Global Creator and open Program's page
I added the migration which adds permission to Program Readers/Editors to R-read Proposals
=> GGRC-6592 Reader role cant see proposals by others

src/ggrc/converters/base_row.py, test/integration/ggrc_workflows/converters/test_import_task_group.py
If a Task Group is being imported with not existing user as an "Assignee" and in the next block this user is being imported, "Import failed due to unknown error" error is shown for Person block but it should import correctly.
1. Have any active wf in UI;
2. Import Task group and People into one Google sheet - (Task group should be displayed first in sheet);
3. Open Google sheet and fill out the required fields for Task group and New Person;
4. Set newly created person as Task group Assignee;
5. Save changes and Import it.
Expected result: For Task Group should be shown an error (due to unknown assignee) and there should not be any errors for Person.
Creating Task Group with unknown user as an assignee caused e-mail of this user be recorded into `converter.new_objects` dictionary as …
=> GGRC-6263 Fix "Import failed due to unknown error." while importing a person and task group in one template

src/ggrc/notifications/data_handlers.py, test/integration/ggrc/notifications/test_assessment_notifications.py
Layout of ATTRIBUTE / NEW VALUE / OLD VALUE is broken in _notifications/show_daily_digest.
- Evidence data shows the dictionary instead of link 
- header columns and content data is not similar as in design example [GGRC-6766](https://github.com/google/ggrc-core/pull/9664)  was shown
1. Login GGRC app as admin user
2. Update any assessment (add one more assignee)
3. Follow _notifications/show_daily_digest page
4. Find the assessment and look at the layout of ATTRIBUTE / NEW VALUE / OLD VALUE
- I added an additional if-statement for the EVIDENCE FILE and EVIDENCE URL fields
- returns link data from the EVIDENCE FILE and EVIDENCE URL fields
=> GGRC-7536 Fixes evidence content in daily digest

src/ggrc/models/mixins/__init__.py, test/integration/ggrc/converters/test_export_snapshots.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/converters/test_snapshot_block.py, test/integration/ggrc/models/test_export_models.py, test/integration/ggrc/test_csvs/issue_for_import.csv, test/integration/ggrc_workflows/converters/test_column_definitions.py
User can not add folder via import.
1. Export any object to Google Sheet, e.g. Control 
2. Add Folder to Control 
3. Import Control 
4. Open Control in UI and look at the folder: folder is displayed
folder display_name was changed and help_text was added for folder
=> GGRC-6022 Fix to add folder via import

provision/docker/mysql/remote_server.cnf
Local and remote DBs have different settings.
1 Open DB local settings 
2 Open DB remote settings
3 See that settings are different
Add a file with new settings that do local DB settings similar remote.
=> GGRC-5287 Add new DB local settings

src/ggrc/gdrive/errors.py
Create common message for GDrive warning when user do not have access either to the file or to the folder
Common message: "You do not have access either to the file or to the folder, please, request edit access from its owner"
Discussed and approved within BA team
Related tickets:
**GGRC-5843** 'There was an error' (POST 500) is displayed if user attaches a file to the folder in which he has 'view only' permissions
**GGRC-5227** Fixed error message when map a document
Case 1:
1. Login as user1
2. Create an object and assign a folder to it.
Set a folder as sharable via link with view-only access.
3. Login as user2
4. Open this object
5. Attach file to folder via Google Drive
Case 2:
1. Login as user1
2. Create a control-1. Assign a new folder and attach a file.
3. Assign user-2 as …
=> GGRC-5147 common gdrive message file and folder

src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js, src/ggrc-client/js/components/tree/templates/tree-widget-container.stache, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/plugins/utils/advanced-search-utils.js
Tree-view has wrong permalink on "_object-version_" tab
- 1. Open Issue with mapped original objects and object versions (for example mapped Objectives and Objective Versions).
- 2. Open Objective Versions tab.
- 3. Apply any saved search.
- 4. Click 3bbs to copy permalink
- 5. Open new browser tab and paste copied link.
_Expected result_: Link should redirect to **Objective versions** tab.
_Actual result_: Link redirects to **Objectives** tab.
- 1. Open Issue with mapped original objects and object versions (for example mapped Objectives and Objective Versions).
- 2. Open Objective Versions tab.
- 3. Open Advanced search modal.
- 4. Copy permalink to buffer.
- 5. Open new browser tab and paste copied link.
_Expected result_: Link should redirect to **Objective versions** tab.
_Actual …
=> QUICK-FIX. Fix saved-search permalink for object versions

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/tests/test_controls.py
Check that new browser tab is displayed after clicking Review Details button for objects disabled in GGRC
=> GGRC-7614 Check review details button for controls

src/ggrc/access_control/roleable.py, src/ggrc/models/assessment.py, src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/hooks/assessment.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/mixins/attributevalidator.py, src/ggrc/services/common.py, src/ggrc/utils/referenced_objects.py, test/integration/external_app/test_export_risk.py
During investigation of GGRC-5974 turned out that when generating 3000 assessments for 4 audits (750 assessments per 1 audit) with LCA and mapped objective some queries executed up to 60 000 times. 
1. Perform assessment autogeneration with snapshot and template having CADs;
2. Look at issued queries.
Solution contains following changes:
- LCA and ACP are now inserted in batches during assessment generation.
- Objects are now undeferred upon loading from request data.
- `_get_global_cad_names` is fixed so now it caches CADs that have already been queried.
=> GGRC-7427 Reduce number of queries during assessment generation with LCA

src/ggrc/converters/base_block.py, src/ggrc/converters/column_handlers.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/handlers.py, src/ggrc/converters/import_helper.py, src/ggrc/models/reflection.py, src/ggrc/models/review.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc/converters/test_import_reviewable.py
The solution should follow criteria below:
AC1. Disallow a user to change Review state via import.
Remove 'Review State' column from template of objects that have review feature*
Add warning message on import: 
“Line #: Field 'Review State' is non-editable via import. The the ‘Review State' column will be ignored."
AC2. Disallow a user to change Reviewers via import.
Remove 'Reviewers' column from template of objects that have review feature*
Add warning message on import:
“Line #: Field 'Reviewers’ is non-editable via import. The the ‘Reviewers' column will be ignored."
AC3. Allow user to export the ‘Review State’ column.
’Review State’ column should present in exported spreadsheet for all the objects that have 'Review' feature*
AC4. Allow user to export the …
=> GGRC-6177 reviewable fields visible in empty template

src/ggrc/migrations/versions/20190806_307953997c8b_modify_default_recipients_in_document.py, src/ggrc/migrations/versions/ggrcdev.sql, src/ggrc/models/document.py, test/integration/ggrc/converters/test_import_csv.py
1. Create object (e.g. objective) with reference url via import
2. Open the document created via import
3. Click Changelog tab
Actual result: "Recipients" is set to "Assignees, Creators, Verifiers"
Expected result: "Recipients" should be set to "Admin" like for control created via UI
It looks the same happens for other types of objects (e.g. Recipients in controls)
Modify recipients column in Document module with default value - Admin
Add tests with recipients validation on Import
Update default scheme configuration
=> GGRC-5265 Recipients field is set to invalid value for imported Documents

src/ggrc/models/mixins/attributevalidator.py
Linter warns about wrong default type, because later we assign `dict()` as value to this `defaultdict(set)`. Potentially it can lead to bug .
I don't see need for `defaultdict` at all.
=> QUICK-FIX Fix linting issue about wrong datatype

src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/converters/block_mixins/__init__.py, src/ggrc/converters/block_mixins/people_cache.py, src/ggrc/converters/handlers/default_people.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/utils/test_user_generator.py, test/unit/ggrc/converters/handlers/test_user_column_handler.py
The original code that handles people during import / export performs SQL queries or HR API calls for each column in each row which leaves us with `O(m*n)` complexity. The performance could be improved if we cache people in a block and use this cached people during the process.
1. Import several assessments with ACL fields filled with several people emails;
2. Compare the DB requests for people before and after.
Solution includes following changes:
- `people_cache` property is added which returns cache of people or creates one if it does not exist. Implementation of cache builder differ on  `ImportBlockConverter` and `ExportBlockConverter`.
- `PersonColumnHandlerMixin` is added which contains basic functionality for parsing emails from string value and extracting people IDs from some …
=> GGRC-3724 Cache people on import / export

src/ggrc/models/mixins/attributevalidator.py, src/ggrc/services/resources/external.py, test/integration/external_app/test_ext_cad.py
Unify response for external CAD with representation by model
Add Admin panel for control/risk CAD
Open Network in browser
Response should be with "external_" prefix
For other CADs response should be without "external_"
Remove custom representation for external models
=> GGRC-7675 Unify external CAD endpoint for Admin Panel

src/ggrc/models/mixins/__init__.py, test/integration/ggrc/converters/test_export_snapshots.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/converters/test_snapshot_block.py, test/integration/ggrc/models/test_export_models.py, test/integration/ggrc/test_csvs/issue_for_import.csv, test/integration/ggrc_workflows/converters/test_column_definitions.py
Incorrect name of a column for import 'folder' attr
1 Create object and attach folder to object
2 Export the object to Google Sheet
2 Open document
3 See that  folder is located  on 'GDrive  Folder ID' column
Change name of column and add help text
=> GGRC-6022 Fix name of 'folder' attr

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_csv.py
* "Delete" column does not have a tip in csv template
1. Log into GGRC app.
2. Goto Export page.
3. Select the Object Type and export the csv file.
4. Open the excel and check for the delete column , here you can see the tip message " Allowed value: Yes " above the delete column.
The function 'get_object_attr_definitions' in 'src/ggrc/models/reflection.py' is modified such that it will show the tip message for delete attribute.
=> GGRC-3663 Add tip message 'allowed value :Yes' for delete attribute

src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/snapshot_instance_column_handler.py, test/integration/ggrc/converters/test_import_assessments.py
Assessments status wasn't changed from IN REVIEW to IN PROGRESS if Verifiers were changed when it was updated via import with new  some data in map:any_field.
Example: map:objective versions
1. Create assessment
2. Add Objective to Assessment
3. Set assessment to the IN REVIEW state
4. Export Assessment
5. Set '--' into Verifiers field
6. Check if Objective slug existing in map:objective versions field
7. import assessment
8. Check assessment status and verifiers field
the cause of the problem was in sqlalchemy db.session.flush method:
1) src/ggrc/converters/handlers/snapshot_instance_column_handler.py here you can see that previously this method used to flush only data that were updated, but 
2) if empty data were received this method flushed everything in the session, and it leads to …
=> GGRC-6529 Fixes assessment status when verifiers and map fields changed

src/ggrc/models/assessment.py, test/integration/ggrc/converters/test_export_csv.py
Assessment Type Column doesn't have tip message in csv template.
3.Select the Object Type (which have Assessment Type as field) and export the csv file.
Open the excel and check for the Assessment Type column , here you can see the tip message
"Options are:
AccessGroup
AccountBalance
Contract
Control
DataAsset
Facility
Market
Objective
OrgGroup
Policy
Process
Product
Regulation
Requirement
Standard
System
Vendor
Risk
TechnologyEnvironment
Threat
Metric
ProductGroup
KeyReport" above the Assessment Type column.
A variable **ASSESSMENT_TYPE_OPTIONS**  is added to the class Assessment in ggrc/models/assessments.py and updated \_aliases variable as per requirement.
=> GGRC-3939 Add Tip message for Assessment Type

src/ggrc/models/external_custom_attribute_definition.py, test/integration/external_app/test_ext_cad.py
Request with empty id for create/update CAD from external service raise 500 error
Send request for create/update CAD from external service without id.
Response should be: 400 Bad Request - id for the CAD is not specified.
Add validates method for external CAD model
=> GGRC-7695 Send correct response on request with empty CAD id

src/ggrc/query/builder.py
Assessment  'Change log' tab opens very long if current user has a lot of related objects (on QA about 2 minutes)
1. As admin user create a program, regulation, audit 
2. Open audit page and create assessment 
3. Assign Global Creator user as Auditor in Audit 
4. Log in as Global Creator user and open audit page 
5. Open Assessment Info panel and click on Change Log tab
6. See that tab opens fast
Before, we got all user allowed resources and next, we filtered all records by request ids. Now we get revisions by request ids and next we filter records by a list of allowed resources for current user.
=> GGRC-7434 Fix revision query performance

test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_controls.py
Check that buttons 'Mark Reviewed' and 'Request Review' are not displayed at Control Info page
=> GGRC-7625 Check that buttons 'Mark Reviewed' and 'Request Review' are not displayed at Control Info page

src/ggrc/gdrive/file_actions.py, test/unit/ggrc/gdrive/__init__.py, test/unit/ggrc/gdrive/test_gdrive_utils.py
If user attaches a file twice, file appears in the folder with the same title
1. Log in ggrc app and open any audit
2. Attach folder to audit
3. Create assessment and attach evidence file to this assessment from GDrive
4. Attach the same file once again
4. Open Gdrive and open the folder
Actual Result: If user attaches a file twice, file appears in the folder with the same title
Expected Result: Evidence attached to assessment twice should not have the same title in audit folder. File should be named differently (such as (1) or (2) after the file name.
Check if file already exists in folder and rename original file
=> GGRC-7480 If user attaches a file twice, file appears in the folder with the same title

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/lib/page/widget/version_history.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_controls.py
Confirm user cannot restore Control's version
=> GGRC-7582 Confirm user cannot restore Control's version

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py
*Import of Assessment failed if the import file contains LCA of assessment template that was deleted
1. Open any audit with a snapshot 
2. Create assessment template with any LCA 
3. Generate assessment based on the Assessment template 
4. Export assessment 
5. Delete assessment template in the audit 
6. Import Assessment with any updates (e.g. change slug, title) 
Actual Result: Import of assessment failed
Expected Result: Import of assessment should not fail*
*Steps to reproduce:
1. Open any audit with a snapshot 
2. Create assessment template with any LCA 
3. Generate assessment based on the Assessment template 
4. Export assessment 
5. Delete assessment template in the audit 
6. Import Assessment with any updates (e.g. change slug, title) 
Import of assessment …
=> GGRC-7694 Import of Assessment failed if the import file contains LCA of assessment template that was deleted

src/ggrc/migrations/versions/20190902_7542f6d44eaa_fix_null_resource_slugs_in_revisions.py, src/ggrc/utils/objects_cache.py
Export fails when trying to export assessments some object is linked to from trie view. The following error appears: `"Your Export job failed due to a server error. Please restart the export again. Sorry for the inconveniences."`
But when exporting assessments linked to object from export page, everything works fine.
Changes could be reproduced on PROD instances only due to corrupted data. To reproduce changes locally some manual changing of data in DB is needed:
1. Login in GGRC;
2. Create program, audit;
3. Map control to audit;
4. Create assessment and map control to it;
5. Look in the DB for snapshot of control from step 4;
6. Find revision specified in snapshot and set `resource_slug` to `NULL`;
7. Click on mapped snapshot on UI and select "View original Control" option;
8. Go to …
=> GGRC-7669 Fix error when exporting assessments linked to object from trie view

src/ggrc/models/assessment.py, test/integration/ggrc/converters/test_export_csv.py
Archived column doesn't have tip message in csv template.
3.Select the Object Type ( Assessment) and export the csv file.
Open the excel and check for the Archived column , here you can see the tip message
yes
no"
Updated the description for Archived attribute in  \_aliases in ggrc/models/assessments.py
=> GGRC-3664 Add tip message for Archived

src/ggrc-client/js/components/related-objects/templates/related-assessments.stache
Does not appear popup of conformation moving Assessment to "In Progress".
1. Create 2 Assessments and map one Control 
2. Open the first Assessment and add several evidence 
3. Open the second Assessment and Complete it 
4. Open Related Assessments tab for second Assessment 
5. Select Evidence for reusing and click Reuse button  
**Actual result**: Evidence are reused. Assessment remains in Completed status  
**Expected result**: Confirmation popup appears. If user confirms Assessment status is changed to In Progress and evidence attaches.
Add appearing popup of conformation moving Assessment to "In Progress" after click on "Reuse".
=> GGRC-7202 Confirmation popup is not displayed if Assessment moves to IN progress

src/ggrc-client/js/components/deferred-mapper.js, src/ggrc-client/js/components/object-mapper/object-mapper.js, src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/workflow/cycle-task-objects/cycle-task-objects.js, src/ggrc-client/js/events/eventTypes.js, src/ggrc-client/js/plugins/utils/mapper-utils.js
Cycle Task modal contains deleted objects.
1. Open Create Cycle Task modal -> click Map Objects.
2. Select any object and click Map.
3. Click Map Objects again -> find mapped object from p.2 -> expand its 3dots menu & click create task.
4. On newly CT's Create modal click Map objects button.
5. Find mapped object from p.2 -> expand 3 dots menu and click Delete button.
6. After deletion, go to first Create Modal .
7. Verify that Cycle Task doesn't contain deleted objects and can be saved without errors.
The issue was in that object deletion wasn't triggered any updates for parent component.
1. Added event that's called on objects deletion to update list of objects.
=> GGRC-7457 Fix bug when Cycle Task modal contains deleted object

src/ggrc/models/audit.py, test/integration/ggrc/converters/test_export_csv.py
Archived column doesn't have tip message for Audit  in csv template.
3.Select the Object Type ( Audit) and export the csv file.
Open the excel and check for the Archived column , here you can see the tip message
yes
no"
Updated the description for Archived attribute in \_aliases in ggrc/models/audits.py
=> GGRC-3664 add tip for Archived in Audit 

test/integration/ggrc/models/mixins/test_with_last_comment.py
Rework test_with_last_comment.py
Execute test/integration/ggrc/models/mixins/test_with_last_comment.py and make sure the tests pass without allowing usage of custom slugs
1) Removed custom slug from import_data in test_import_last_comment and query assessment by title instead of slug
2) Removed custom slug from import_data in test_ca_create_on_import and query assessment by title instead of slug
=> GGRC-7637 Rework test_with_last_comment.py

src/ggrc/models/custom_attribute_value.py, test/unit/ggrc/models/test_custom_attribute_value.py
Sync for control/risk with dropdown GCA crashed if value was added
Update control/risk on GGRCQ side with integer value for GCA
Update validator with casting integer to string
=> GGRC-7780 GCAs are not synced in some Control objects

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_csv.py
Unify hints for Drop down custom attributes
2. Add a custom attribute (Drop down type) for any object.
3. Goto Export page.
4. Select the Object Type and export the csv file.
6. check for the added custom attribute column , here you can see the tip message
option_1
option_2"
**option_1 and option_2 will be   extracted from Dropdown multi_choice_options
Updated the code function get_custom_attr_definitions in /src/ggrc/models/reflection.py as per requirement.
=> GGRC-7033 Add tip for Dropdown custom attributes

src/ggrc/integrations/external_app/__init__.py, src/ggrc/integrations/external_app/constants.py, src/ggrc/views/__init__.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/views/test_get_attributes.py
Attributes are duplicated and not actual in Global/Advanced Search for Controls & Risks
Check Global Search for Risk/Control - should be only external attributes without duplication
Add filters for attribute_json and all_attributes_json
=> GGRC-7782 Attributes are duplicated and not actual in Global Search

src/ggrc/integrations/constants.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/integration_utils.py, src/ggrc/models/hooks/relationship.py, src/ggrc/utils/helpers.py, test/integration/ggrc/integrations/test_assessment_integration.py
"Assessment Procedure" from mapped snapshot is not copied to Issue Tracker. If "Assessment Procedure" on assessment is changed, a corresponding comment should be left at Issue tracker (overall should by synced like "Remediation plan" for issues).
1. Open any audit page with a control snapshot with filled "Assessment Procedure";
2. Turn on Issue Tracker for audit with valid Component ID and Hotlist ID;
3. While creating assessment map a control snapshot via "New Assessment" popup;
4. Navigate to "Assessment Info" pane and click ticket link;
Expected Result: If assessment has an "Assessment procedure'"it should be displayed in Issue Tracker. If it is changed - a corresponding comment should be left at Issue tracker (overall should be synced like "Remediation plan" for issues).
Solution …
=> GGRC-4506 Copy assessment procedure to Issue Tracker upon snapshot mapping

src/ggrc/models/assessment.py, test/integration/ggrc/converters/test_export_csv.py
Assessment Type Column doesn't have tip correct message in csv template.
3.Select the Object Type (which have Assessment Type as field) and export the csv file.
Open the excel and check for the Assessment Type column , here you can see the tip message
Access Groups
Account Balances
Data Assets
Facilities
Key Reports
Markets
Org Groups
Processes
Product Groups
Products
Systems
Technology Environments
Vendors
Contracts
Controls
Objectives
Policies
Regulations
Requirements
Risks
Standards
Threats"
Updated variable *ASSESSMENT_TYPE_OPTIONS* is added to the class Assessment in ggrc/models/assessments.py
=> GGRC-3939 Update the Assessment type options

src/ggrc-client/js/plugins/utils/snapshot-utils.js, src/ggrc/models/snapshot.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/models/mixins/test_customattributable.py, test/integration/ggrc/models/test_snapshot.py, test/unit/ggrc/models/test_revision.py
'Get the latest version ' link will appear for snapshots if you add a comment to the original object.
1 Have a program with mapped standard, audit
2 Add a comment to standard
3 Open Standard snapshot info panel on audit page and see that there is not 'Get the latest version ' link.
Added new snapshot flag 'is_identical_revision' that is responsibility for comparing 2 last revision
=> GGRC-7021 Update checkout conditions for latest revision

src/ggrc/login/__init__.py, src/ggrc/models/person.py, src/ggrc_workflows/__init__.py, test/integration/ggrc/api_helper.py, test/integration/ggrc_workflows/test_basic_workflow_actions.py, test/selenium/src/lib/service/rest/session_pool.py, test/selenium/src/lib/utils/date_utils.py
2 WF cycles created during WF activation if client date < server date
Pre-condition: client time < server time (like example from 17 to 24 in LA in browser, from 00 to 8 in London)
1. Create repeat on WF that repeats every weekday
2. Create task w/start date today
3. Click activate button
4. Go to Active cycles tab
Currently FE application convert datetime objects to UTC time and send it to BE.
In this fact BE doesn't know about local user time(date).
Was added method that collect user's time zone to calculate user's time(date) for cycles generating.
=> GGRC-6491 2 WF cycles created during WF activation if client date < server date

src/ggrc/converters/base.py, src/ggrc/integrations/issuetracker_bulk_sync.py, test/integration/ggrc/converters/test_import_issuetracked_objects.py
There aren't any notifications regarding Issue Tracker Issues when they are created / updated via import. Upon import two different types of emails should be sent - one when tickets are created during import and one when they are updated.
**Version alexl-6532  is deployed to ggrc-test, changes could be checked there.**
1. Create Audit with Issue Tracker turned ON;
2. Create some Assessments (with Issue Tracker turned ON) via import for Audit from previous step;
3. Check that corresponding tickets are created in Issue Tracker.
Email `Ticket generation status` is sent after background job finishes.
1. Create Audit with Issue Tracker turned ON;
2. Create some Assessments (with Issue Tracker turned ON)  in Audit from step 1.
2. Update created Assessments via import;
3. …
=> GGRC-6532 Notification emails aren't sent after Issue Tracker Issue create / update via import

src/ggrc/converters/handlers/assessment_template.py, test/integration/ggrc/converters/test_import_assessments.py
Precondition:
Create an Audit
Create an assessment template with LCA-s in this Audit (Template 1)
Create an assessment template without LCA-s (Template 2)
1. Generate an Audit Assessment via template with LCA-s
2. Create the second Assessment via template without LCA-s
3. Export Assessments to google sheet 
4. Insert Template 1 code for two Assessments (in google sheet)
5. Import Assessments
Actual result:  'Import failed due to unknown error' displays while importing assessments with a template with LCA-s.
Expected: A warning should be displayed with the following text:
=> GGRC-7937 Skip custom attribute creation for not new assessment

src/ggrc-client/js/components/inline/base-inline-control-title.js, src/ggrc-client/js/components/inline/base-inline-control-title.stache, src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js, src/ggrc-client/js/plugins/utils/custom-attribute/custom-attribute-object.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js, src/ggrc-client/js/templates/custom_attributes/info.stache, src/ggrc/migrations/versions/20190914_75ad21f0622b_add_external_name_for_cad.py, src/ggrc/models/external_custom_attribute_definition.py, test/integration/external_app/test_ext_cad.py
Use case that should be fixed:
Preconditions:
Administrator logs into GGRCQ app.
Administrator goes to administration dashboard.
Administrator creates a new global custom attributes for risks or controls OR updates the name of any existing custom attribute for risks or controls.
Steps:
User logs into GGRC.
User opens any control or risk info pane.
User mouses over any global custom attributes created/updated in step 3 in precondition.
User clicks on pencil icon.
Control detailed page with already opened "Create Proposal" pop-up is opened in a new tab in GGRCQ application.
Add external_name column for CAD
Add response with external_name
Update redirection link to GGRCQ
=> GGRC-7733 Update "proposal" redirect to GGRCQ

src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py
Front-end expected that CADs will not change the order when we create new one CAD. So, new CADs should be always at the end of the list.
1. Log in ggrc app as admin user and open any audit
2. Map Facility object with GCA rich text to audit (snapshot Facility is created)
3. Go to Admin page and add any GCA (date) to Facility
4. Open Original Facility and fill GCA date
5. Open Facility snapshot on the audit page in treeView and open Comparison window by clicking 'Get the latest version' link
Actual Result: GCA rich text marked to be updated
Expected Result: No changes should be triggered for GCA rich text
Front end expected CADs sorted by creation. In a DB we have CADs sorted by title. We should update response format to the expected one.
=> GGRC-7486 Comparison window contains updates for GCA which should not be changed

src/ggrc/integrations/synchronization_jobs/one_time_back_sync.py, test/integration/ggrc/integrations/test_onetime_back_sync.py
For some issues empty `hotlist_ids` is returned from Issue Tracker. This case isn't handled correctly during back-sync due to absence of check if list is not empty before accessing its elements. This leads to list-out-of-range errors during back-sync job.
1. Deploy this branch to GAE with dump from ggrc-test / ggrc-uat in DB;
2. Login in GGRC and execute `$.post("/admin/onetime_back_sync")` in devtools console;
3. Check logs after job finishes and make sure there wasn't any errors _(note that 200 status code will be returned even in case of an error, so job logs should be checked)_
Solutions consist of additional check for `hotlist_ids` obtained from Issue Tracker. If `hotlist_ids` is an empty list, `None` will be used as value for `IssuetrackerIssue.hotlist_id`.
=> QUICK-FIX Fix index out of range errors during onetime back-sync job

src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss, src/ggrc-client/styles/components/form/fields/_date-form-field.scss, src/ggrc-client/styles/modules/_datepicker.scss
**Should be merged in "asmt-bulk"**
Fix font-size for person input in LCA section on Bulk Complete modal and fix fa-times position and height of date input globally.
1. Check person input font-size in LCA section on Bulk Complete modal. It should be 13px.
2. Check all places where date input is used. fa-times should be in the center of date input.
=> BC: QUICK-FIX Fix font-size for person input and fa-times position and height of date input

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_assessments.py
Local Custom Attributes columns are displayed after Ticket Tracker fields.
1. Open ggrc-app
3. Create objective to audit
4. Create assessment with GCA and LCA columns
5. Export assessment table
6. Check columns order
Added LCA columns(OBJECT_CUSTOM_ATTR_PREFIX) to ordered attributes after GCA columns
=> GGRC-6513 Shift Local Custom Attributes columns after Global Custom Attributes

src/ggrc-client/js/templates/access_control_roles/subtree.stache
On the Administration tab in the list of Custom Roles for the Assessment object add (?) icon for Assignee near his Edit permissions.
On hovering the (?) icon help text should be shown: 
"For assessments with enabled SOX 302 flow assignees:
- can provide/edit answers for local custom attributes;
- cannot edit assessment and its local custom attributes upon assessment completion."
1. Open Custom Roles tab.
2. Verify that only in the list of Custom Roles for the Assessment (?) icon for Assignee near his Edit permissions is shown with help text. 
Added icon with help text if `object_type` and `name` of an instance equal to "Assessment" and "Assignees".
=> RP: GGRC-7958 Add '?' icon for Edit Assignees permissons on Assessments Custom Roles

src/ggrc/notifications/data_handlers.py
Issue description
The error appears when we try to open notification page if we restore QA / UAT DB dump
1 Install QA DB dump
2 Login to the system as Superuser
3 Open notification pending page on the link: localhost:8080/_notifications/show_daily_digest
Type of empty arg returned of '_get_updated_fields'  function was changed
=> GGRC-7988 / GGRC-7984 Fix to show daily digest

src/ggrc-client/js/components/add-tab-button/add-tab-button.js, src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache, src/ggrc-client/js/components/related-objects/related-issues.stache, src/ggrc-client/js/components/related-objects/related-people-access-control-group.js, src/ggrc-client/js/components/tree/tree-actions.js, src/ggrc-client/js/components/tree/tree-item-actions.js, src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js, src/ggrc-client/js/helpers.js, src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/templates/assessments/header.stache, src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
When checkbox "Enable SOX 302 assessment workflow" in the assessment template is switched on, 
all assessments created based on this template shall provide restricted permissions to the assessment assignees. 
1) if assessment is in "Not Started", "In Progress", "Rework needed" or "In Review" statuses:
- assignee cannot edit any built-in, global custom attribute on the assessment
- assignee cannot add/remove labels
- assignee cannot map/unmap any snapshot to assessment
- assignee cannot deprecate assessment
- assignee cannot raise/unmap issue to assessment
- assignee cannot turn on/off linking to issue tracker
+ assignee can add/edit answers to Local Custom Attributes
+ assignee can add/update/delete/reuse evidence url, files
+ assignee can add …
=> RP: GGRC-7959/GGRC-7960 Restrict assignee permissions on Assessment pages/tabs

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/unit/ggrc/integrations/test_assessment_integration.py
Currently it takes about 20 minutes for hourly issue tracker sync job to run on ggrc-uat instance. It makes testing of all the cases of object synchronisation to take an unreasonably long amount of time.
This PR contains fixes that should lead to performance improvement of sync job.
1. Deploy this PR to GCP and import the last ggrc-uat dump;
2. Start hourly issue tracker sync job by performing `GET /hourly_issue_tracker_sync_endpoint` request;
3. Look in the browser's dev tools at time it took for request to finish and compare it with the results obtained on currently deployed ggrc-uat instance.
The bottleneck for issue tracker sync job is a syncronisation of Assessments. The problem is that each Assessment should be synced by `PUT` request to issue tracker, which can take up to 1.5 sec. …
=> GGRC-8017, GGRC-7607 Hourly Issue Tracker sync job performance, Users are not populated in CC list after run cron job

src/ggrc/converters/base_row.py, src/ggrc/converters/errors.py, src/ggrc/converters/pre_commit_checks.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/converters/test_import_audit.py
Error is shown on import of Assessment with status changed and filled LCA
1. Create assessment template with Dropdown LCA "TEST CAD" with values:
- yes 'comment required'
- no
2. Generate assessment with "TEST CAD"
3. Export assessment
4. Change "TEST CAD" value to 'yes' and Status to 'Complete'
5. Import changed filed
- Added asmt validation in `secondary_check_assessment` with the logic same as in `_validate_assessment_done_state`
- Added bool checker in `commit_object` method when exception in `send_before_commit_signals` raise and DB rolled back
- Removed usage `self.offset` attribute in `ImportRowConverter` with the `self.block_converter.offset`
=> GGRC-7909 Fix complete assessmnet while import

src/ggrc/converters/handlers/template.py, src/ggrc/models/assessment_template.py, src/ggrc/models/custom_attribute_definition.py, test/integration/ggrc/models/mixins/test_with_sox_302.py
_After review this PR should be targeted into `GGRC-7771-sox-skip-verify` branch._
This PR is on hold until following dependencies are merged:
This PR contains SOX 302 functionality for Custom Attributes (support for negative options is added). After all builds pass should be targeted into common branch.
**_Import / export of Assessment Template with Custom Attributes with specified negative options_**
Scenario I (Assessment Template create via import)
1. Download CSV import template for Assessment Template objects;
2. Fill all needed fields along with Custom Attributes. Custom Attributes should be of _"Dropdown"_ / _"Text"_ / _"Rich Text"_ type with marked negative options (see hint in CSV for more details);
3. Import CSV and check that Assessment Template was created with Custom …
=> GGRC-7894 / GGRC-7895 [SV] Negative options for CADs

src/ggrc/converters/handlers/assessment_template.py, src/ggrc/migrations/versions/20191011_0f827fe39ad5_add_sox302_flag_for_asmt.py, src/ggrc/models/assessment.py, src/ggrc/models/hooks/assessment.py, src/ggrc/models/mixins/with_sox_302.py, test/integration/ggrc/models/mixins/test_with_sox_302.py
_After review this PR should be targeted into `GGRC-7771-sox-skip-verify` branch._
This PR contains SOX 302 functionality for Assessment. After all builds pass should be targeted into common branch `GGRC-7771-sox-skip-verify`.
This PR contains following changes:
* New migration which adds `sox_302_enabled` flag on `assessments` table:
```sql
ALTER TABLE assessment_templates ADD sox_302_enabled TINYINT(1) NOT NULL DEFAULT 0 ;
```
* New mixin `WithSOX302FlowReadOnly` is created which is a subclass of `WithSOX302Flow` mixin. New mixin provides the same functionality but makes …
=> GGRC-7897 [SV] Add sox_302_enabled field for Assessment

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/assessment/info-pane/create-url.js, src/ggrc-client/js/components/item-edit-control/item-edit-control.js, src/ggrc-client/js/components/item-edit-control/item-edit-control.stache, src/ggrc-client/js/components/object-list-item/editable-document-object-list-item.stache, src/ggrc-client/js/components/related-objects/templates/related-urls.stache, src/ggrc-client/js/models/business-models/evidence.js, src/ggrc-client/js/templates/audits/info.stache, src/ggrc-client/js/templates/audits/modal_content.stache, src/ggrc-client/js/templates/evidence/info.stache, src/ggrc-client/js/templates/evidence/modal_content.stache, src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss, src/ggrc-client/styles/components/info-pane/_info-pane.scss, src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss, src/ggrc-client/styles/components/object-list/_object-list.scss, src/ggrc/migrations/versions/20190924_394f80f98f02_add_notes_column_to_evidence.py, src/ggrc/models/evidence.py, test/integration/ggrc/models/test_evidence.py, test/selenium/src/lib/element/page_elements.py
What   is the problem / issue?   
Although we can use the Response/Comment field to add comments, I believe it   would be easier to have a dedicated field for small comments (ex: "See   section x.y" or "Go to page x")       
What is the impact if it is not fixed / implemented? 
(Quantify the impact,   eg, # of hours)   Minor confusion could occur when adding multiple links/files.
Solution to be implemented:
AC1: Add on Evidence file and evidence url INFO PAGE / INFO PANE/ EDIT EVIDENCE POPUP additional field named 'Notes'. Field type 'Text'
AC2: Add on Assessments/Audits INFO PANE / INFO PAGE / EDIT POPUPs near added Evidence URL/file an 'Edit' icon.
AC3: On 'Edit' icon click a popover with text field, Approve and Cancel buttons should appear.
AC4: After adding a text to popover and …
=> GGRC-6361 Add optional description field for evidence URL/File

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py
During import Assessment template, mandatory GCAs are not validated on GGRC-QA instance
**Expected**: Error for each empty mandatory field should be shown on import page
**Note**: bug reproduced on multiselect GCA
1. Create audit
2. Create GCA mandatory multiselect
3. Open Import page
4. Download Assessment template
5. Add any Title, Audit code, Creator and Assignee
6. Leave multiselect GCA mandatory field:
- empty 
- put any value not represented in GCA choices
- put any valid value but with diff cases
7. Import assessment
1. Fixed `get_multiselect_values` method for parsing value
2. Added tests
=> GGRC-7781/GGRC-7765 Fix import multiselect cad

test/integration/ggrc_basic_permissions/test_audit_archiving.py
There is a test `test_audit_context_editing` in `test_audit_archiving.py` which randomly fails.
The solution is to encode title generated via `factories.random_str()` in `UTF-8`.
Also there was an error in `.format` call during error message construction for assertion. The problem is that object name for Assessment Template is defined on test class as simply `"template"`. And by this name the value from `response.json` was accessed. But for Assessment Template, there will not be any `"template"` in response but `"assessment_template"`.
=> QUICK-FIX Fix randomly failing tests in test_audit_archiving.py

src/ggrc-client/js/bootstrap/modal-ajax.js, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache, src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.js, src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.stache, src/ggrc-client/js/components/tree/templates/tree-item-attr.stache, src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/models/business-models/assessment-template.js, src/ggrc-client/js/plugins/utils/modals.js, src/ggrc-client/js/templates/assessment_templates/info.stache, src/ggrc-client/js/templates/modals/assessment_template_footer.stache, src/ggrc-client/js/templates/modals/assessment_template_warning.stache, src/ggrc-client/js/templates/modals/assessment_template_warning_buttons.stache, src/ggrc-client/styles/modules/_modal.scss
**Should be merged into _GGRC-7771-sox-skip-verify_ branch**
On click 'Save and Close' at Create/Edit modal of Assessment template few warnings are possible:
1. when at least one LCA has no negative answer:
show a warning 'Warning! Pay attention that the following attributes do not have the negative answers selected.' with the list of LCA that do no have negative answers marked.
With buttons:
_Continue editing_
_Confirm_
2. when for at least one LCA all answers marked as negative:
show a warning 'Warning! Pay attention that the following attributes do not have the positive answers selected.' with the list of LCA that have all answers marked as negative.
With buttons
_Continue editing_
_Confirm_
3. when at least one LCA do not have …
=> GGRC-7879 / 7880 [SV] Implement the functionality to validate “Negative responses” for each LCA item

src/ggrc-client/styles/modules/_top-nav.scss
Projects object icon is not marked as snapshot on Audit page
1. Create a Program
2. Map any Project object to the Program
3. Create Audit
4. Open Created Audit
4. Review icon for Project
**Actual**l: Icon for Project object is not marked as all other snapshot objects
**Expected**: Project object is marked as all other snapshot objects
=> GGRC-8009 Projects object icon is not marked as snapshot on Audit page

src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js, src/ggrc-client/js/plugins/tests/validation-extensions/validate-on-excluded-symbols_spec.js, src/ggrc-client/js/plugins/validation-extensions.js, src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
User should be able to type * for Title of GCA. Then when field validation is triggered, the field should be highlighted in red and the following message should be shown under the field:"Cannot contain *"
1. Click Create new Custom Attributes.
2. Type any value with '*' symbol to Title field. Click outside the field(unfocused). 
3. Verify that error message "Cannot contain *" is shown. 
Instead of preventing typing the symbols, use `instance.errors` to add error message when input value contains excluded symbols.
1. Replaced cleanUpInput with validateInput method.
2.  Added event to trigger errors changes.
3. Updated unit tests.
=> GGRC-7432 Add error message for GCA title instead of preventing typing symbols

src/ggrc/models/directive.py, test/integration/ggrc/converters/test_export_csv.py
Add Hint of the Kind/Type attribute for the Policy object
2. Add a custom attribute (Drop down type) for any Policy object.
3. Goto Export page and extract data for Policy object.
4. Select the Object Type and export the csv file.
6. check for the added custom attribute column , here you can see the tip message
“Allowed values are:
Company Policy
Org Group Policy
Data Asset Policy
Product Policy
Contract-Related Policy
Company Controls Policy ”
Added the variable with the POLICY_OPTIONS in the directive.py file.
=> GGRC-7972 Hint of the Kind/Type attribute for the Policy object

src/ggrc-client/js/components/gca-controls/gca-controls.stache, src/ggrc-client/js/templates/custom_attributes/info.stache
Add tooltip to the GCA attributes with long title.
1. Login in GGRC app. 
2. Open Administration page. 
3. Add GCA attribute with long title e.g to the Objective.  
4. Open any Objective object and review created GCA. 
**Actual**: A part of the GCA's title is cut and there is no possibility to view all the title. 
**Expected**: Full GCA's title is be visible in toolltip.  
Add tooltip when we hover over the title.
=> GGRC-7779 Add tooltip to the GCA attributes with long title

src/ggrc/snapshotter/indexer.py, src/ggrc/snapshotter/rules.py, test/integration/ggrc/snapshotter/test_indexing.py
User cannot create an assessment with the snapshots from audit. In the Unified Mapper snapshots do not display while mapping a snapshot.
_Preconditions:_
1. Take latest dump from ggrc-uat.
2. Have Program with mapped object, e.g. Control.
1. Open a program;
2. Click Add tab and select Audit (do not check 'Manually map snapshots' checkbox);
3. Check that Control snapshot is automapped to the Audit;
4. Create an Assessment with mapped Control snapshot.
**Expected result:** Snapshot should be mapped to an assessment while creating it.
**Before changes**: Impossible to map a Snapshot to the Assessment while creating it as a Snapshot isn't displayed in Search results in the Unified mapper.
`_get_custom_attribute_dict` produced result containing duplicates of custom …
=> GGRC-8073 Impossible to create Assessment with snapshots automapped to Audit

src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache, src/ggrc/models/custom_attribute_definition.py, src/ggrc/views/__init__.py, test/integration/ggrc/proposal/api/test_cads.py, test/integration/ggrc/services/test_custom_attributes.py, test/integration/ggrc/services/test_query/test_cad_reindex.py, test/selenium/src/lib/page/widget/widget_base.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_admin_dashboard_page.py, test/unit/ggrc/models/test_custom_attribute_definition.py
We need to make not-editable the following fields of Custom 
- Attribute title 
- Attribute 
- Possible values (for Dropdowns and Multiselect) 
The following fields of Custom Attributes should be editable:
- Inline Help 
- Placeholder 
- Mandatory 
 
1. Open Admin dashboard.
2. Create a Custom Attribute for Program, click "save".
Expected result: no Edit button is displayed for the Custom Attribute.
Actual result: Edit button is displayed for the Custom Attribute, it is possible to change its title and type.
Change access for fields to non-editable in `CustomAttributeDefinition` model. Also, change it dynamically for `multi_choice_options` depending on `attribute_type`. Fix template according these improvements.
=> GGRC-4048 Forbid to edit GCA after creation

src/ggrc-client/js/components/workflow/task-group-objects/task-group-objects.js, src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache, src/ggrc-client/js/components/workflow/task-group-objects/tests/task-group-objects_spec.js
On Task Group info "unmap" operation wasn't performed for several objects . Actually, this causes due to the backend cannot perform "unmap" operation so quickly. The list of mapped objects contains objects, which are in progress with "unmap" operation.
1. Open TG's info panel.
2. Map any 7-10 objects to TG.
3. Quickly click "trash" icon for all mapped objects -> then quickly close info panel and open it again (Need to have throttling for network, slow 3G).
4. Verify that items with pending request are shown with spinner and 'trash' button is disabled. 
1. Stored pending request with items in `pendingUnmappings` list. Show items that not resolved yet with spinner. On resolve remove an item from the list.
=> GGRC-6409 Add spinner for 'unmap' operation on Task Group info

test/selenium/src/lib/base.py, test/selenium/src/lib/constants/counters.py, test/selenium/src/lib/constants/str_formats.py, test/selenium/src/lib/ui/comments_ui_facade.py, test/selenium/src/lib/utils/string_utils.py, test/selenium/src/tests/test_mentioning_person.py
Add test checking mentioning person in comments box on assessment info page works if the first character is '+' or '@'.
=> GGRC-7908 Add test checking mentioning person works if the first character is '+' or '@'

src/ggrc-client/js/helpers.js, src/ggrc-client/js/templates/cycle_task_group_object_tasks/tree_add_item.stache
Rename "Create" button to "Create Task" and hide it for non active workflow on Active Cycles tab.
1. Open Active Cycles tab for any active Workflow.
**Expected result:** Button name should be "Create Task".
2. Open Active Cycles tab for any non active Workflow.
**Expected result:** Button "Create Task" shouldn't be displayed.
3. Check My Tasks page and Workflow Tasks tab for different objects type for which we can create a task.
**Expected result:** Button name should be "Create".
Rename "Create" button and add condition by which we show this button.
=> GGRC-8032/GGRC-8031 "Create Task" button shouldn't be displayed on Active cycles tab on not active Workflows

src/ggrc/builder/json.py
Existing logger.warning logged more data that needed.
The issue arises exceptionally and cannot be reproduced locally.
Excess logger.warning has been removed. A place with issue was placed in a try-except block. In except block, logger.warning was added to check for problematic data.
=> QUICK-FIX GGRC-7925 Logger.warning changed to logger.info

src/ggrc/migrations/versions/20190904_007ee00ff963_add_missing_acp_revisions.py
Records in access_control_people table which do not have corresponding records in table revisions.
1 Download UAT dump
2 Reset dump
3 Run migration from this PR
4 Run sql query 
5 `SELECT * FROM access_control_people WHERE id NOT IN (SELECT resource_id FROM revisions WHERE resource_type = "AccessControlPerson") ORDER BY id DESC`
6 See that count of query result less than 1
Add migration that creates missing revisions
=> GGRC-7079 Add missing ACP revisions

src/ggrc/maintenance_views/maintenance.py, src/ggrc/templates/maintenance/trigger.html, test/integration/ggrc/maintenance/__init__.py, test/integration/ggrc/maintenance/test_maintenance.py
Being logged in as an admin, there is a functionality implemented to trigger reindexing using /maintenance/index admin page. Additionally, last executed task status is shown with following states:
- "Not started" if reindex wasn't started
- "In progress" if reindex is ongoing
- "Finished" if reindex is finished
1.	Login in GGRC app as Admin 
2.	Open page <domain_name>/maintenance/index 
3.	There is a new button that triggers reindexing and label with last reindexing task result
There is a new endpoint provided "maintenance/reindex" to trigger reindex within maintenance module.
=> GGRC-2686 Add reindex button and it's status info on admin page

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_csv.py
This PR is `on hold` until we'll discuss this test.
Hint for the User-defined Global Custom Attributes of People type
Written the test case and verified the data is coming properly or not.
GUI console doesn't have the CA of People type to test in GUI.
Changed the  method in 'src/ggrc/models/reflection.py' and 'src/ggrc/models/custom_attribute_definition.py' to full fill the requirement,
=> GGRC-7976 Add Hint for the Global CA of People type

src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js, src/ggrc-client/js/components/tree/tree-status-filter.js
States resets to default after tab switching
1. Log in GGRC as admin user
2. Open All objects / My Work page
3. Set dropdown filter for Standards: Active
4. Set dropdown filter for Regulations: Draft
5. Set dropdown filter for Requirements: Deprecated
6. Click on Regulations tab: Filter switched to Active/Draft/Deprecated (incorrect)
7. Click on Standards tab twice: Filter switched to Active/Draft/Deprecated (incorrect)
_Actual Result_: Filter settings are incorrect while switching objects tabs
_Expected Result_: Filter settings should be saved while switching objects tabs.
Ignore empty "state" query param
=> GGRC-7604 Incorrect behavior of dropdown filter

src/ggrc-client/js/components/related-objects/revisions/related-revisions.js, src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions.stache, src/ggrc-client/js/components/related-objects/revisions/tests/related-revisions_spec.js
After creating a comment for Program, Version History tab issues HTTP request for revisions and gets 2 revisions (one for "create" action, and one for mapping to comment). And at this point Version History has empty line.
2. Add a comment to a Program.
3. Go to Version History tab.
4. Verify that tab doesn't get revision for created action above(doesn't show empty line).
After discussion with BE decided to getting revisions by _query_ request instead of _get revisions_ request.  It allows to set option `not_empty_revisions_for` and avoids showing empty lines on the tab.
=> GGRC-7456 Version with no attributes is created in Version History tab

test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/selenium_utils.py, test/selenium/src/tests/test_disabled_objects.py
Add test checking that user cannot update GCAs for Risk
=> GGRC-8093 Check that GCA field cannot be edited for Risk

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_asmts_workflow.py, test/selenium/src/tests/test_rbac.py
Testcases for Controls from RBAC section should be updated. Controls objects cannot be created or edited in GGRC so object type should be changed to Objective.
Methods checking controls elements should be removed.
=> GGRC-8175 Change Controls to Objectives in RBAC cases

src/ggrc/notifications/common.py, test/unit/ggrc/notification/test_common.py
We do not see some notification in daily digest email
We need to use DB with notifications count more than 5000 (ex.: qa dump).
1. Create any Workflow
2. Create task with any user assigned
4. Run _notifications/show_daily_digest
5. Find notifications that should be sent for Assignee
Actual: Notification that task was assigned is not presented in the daily digest
Expected: Notification about assigned task is presented
In for loop for generate_daily_notifications() iterator we are loosing old notifications when merging two dicts. Function for deep merging should be used.
=> GGRC-8118 Notifications for Task Assignee doesn't send

src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/custom_attribute_value.py, src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc/fulltext/test_mysql.py, test/integration/ggrc/models/mixins/test_customattributable.py, test/selenium/src/tests/test_asmts_workflow.py, test/unit/ggrc/converters/handlers/test_custom_attribute.py
The following text should be added for Checkbox in Custom attributes for all objects: "Allowed values are:
yes no"
Backend values for checkboxes should fits "yes, no" values in import settings
All entered values should be:
3.1. case insensitive
3.2. space insensitive
System should allow user to enter the following values and recognize them as described below:
4.1. True = yes
4.2. False = no
2. Add a custom attribute (checkbox type) for any object.
3. Goto Export page.
4. Select the Object Type and export the csv file.
6. check for the added custom attribute column , here you can see the tip message
yes
no"
7. Goto import page.
8. import data from new file.
9. Validate the custom attribute column updated correctly …
=> GGRC-7963 Text for Hint in the Checkbox for attributes

test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_disabled_objects.py
Check that user cannot update role for risk
=> GGRC-8120 Check that user cannot update role for risk

src/ggrc/models/review.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/utils/__init__.py, test/integration/ggrc/models/test_program.py
*User has a possibility to restore Object review state.*
*Steps to reproduce:
1. Create a program as Admin user
2. Click Request Review button on the Program Info panel
3. Assign a reviewer and Save
4. Click Mark Reviewed button to Review Program
5. Open Version History tab
6. Click Review & Restore button
7. Click Restore Version
Open Attributes tab and look the Review state: is reviewed.*
Empty PUT for object might rewrite some fields while keeping the value semantically the same (e.g. order of recipients is changed but not the recipients itself).
Now such attributes will be checked without taking the order of values into the account.
=> GGRC-5796: User has a possibility to restore Object review state

src/ggrc/migrations/versions/20191119_283ed454353a_add_sox_302_notifications_types.py
_After review this branch should be merged into base branch called "GGRC-7812-sox-notifications"._
We want to add new notifications types for sox_302 notifications
1. Run migration
2. See that new notifications types are added to notification_types table
Add new migration file
=> [SOX5 Notifications] GGRC-8121 Add new notifications types for sox_302 notifications

src/ggrc/templates/notifications/email_digest_content.html
Font sizes in notifications was different because of wrong html tag in jinja-template
3. Make any changes in Assessment e.g change Description
4. Run Daily digest (_notifications/show_daily_digest)
5. Review the font in the notification - font size for 'New assessments were created' and 'Assessment ... has been updated' should be equal
Change tag in jinja-template
=> GGRC-7766 Unify font style in notifications

src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache, src/ggrc-client/styles/_common.scss
While file is attaching Evidence url for LCA, close popup.  Spinner is spinning all the time, file was not added (file disappears after refreshing page). 
The best solution to avoid this case will be to disable Close button until the file is attached. The following message should be shown while the file is attaching: "Wait until the file is attached."
1. Login as Global Creator user .
2. Open any Audit.
3. Create Assessment template with Dropdown LCA and Evidence file required .
4. Generate Assessment using created template .
5. Open Assessment.
6. Choose answer in LCA that required Evidence file .
7. In appeared popup click Upload button .
8. While file is attaching, verify that Close button is disabled and message is shown. 
1. Disabled Close button  and shown message when …
=> GGRC-8104 Fix bug when Evidence file is not added to Assessment if popup was closed while file is attaching

src/ggrc/app.py, src/ggrc/sox/__init__.py, src/ggrc/sox/notifications/__init__.py, src/ggrc/sox/notifications/hooks.py, src/ggrc/sox/notifications/notification_types.py, src/ggrc/sox/notifications/utils.py, test/integration/ggrc/sox/__init__.py, test/integration/ggrc/sox/test_hooks.py
We want to create special notifications after creating asmt
1 Create assessment template with 'special_flag'=True
2 Create assessment with asmt_template from 1 step and set 'due_date'
3 See that we create special notifications
Create POST hook that creates notifications after creating assessment.
=> GGRC-8124 add creating notif hook

src/ggrc_basic_permissions/__init__.py, src/ggrc_basic_permissions/models.py, test/integration/ggrc_basic_permissions/test_permissions_loading.py
Error appears on previously unavailable due to permissions object after applying `Admin` role for `Global Creator` user and refreshing the object's page.
1. Login as Global Creator user;
2. Open any Audit that Global creator has no access to;
3. Change Role for user from Global Creator to Admin;
4. Refresh Audit page.
**Expected result: Audit page should be opened without any errors.**
Perform permission recalculation for a user on its `UserRole` create and delete actions.
=> GGRC-7931 Error appears on objects after applying Admin role for Global Creator user

src/ggrc-client/js/components/three-dots-menu/tests/three-dots-menu_spec.js, src/ggrc-client/js/components/three-dots-menu/three-dots-menu.js
Object Snapshot 3bb's dropdown menu is empty for Global Creator.
**Note!** The issue is reproducible for all object snapshots only for Global Creator role.
1. Open GGRC as an Admin
2. Create an Audit with any object snapshots, e.g. Objective (example)
3. Create an Assessment of the Objective type (example) with mapped Objectives
4. Assign Global Creator as an Assignee in the Asmnt
5. Log in as a Global Creator and open the Audit
6. Click on Objective snapshots and open any of them
7. Click on 3bb's dropdown menu
**Actual result:** 3bb's dropdown menu is empty for Global Creator on Objective snapshots
**Expected result:** 3bb's dropdown menu should be disabled for Global Creator as they don't have permission to view the original object
Update check to disable 3bb's dropdown menu. Check …
=> GGRC-8090 Object Snapshot 3bb's dropdown menu is empty for Global Creator

src/ggrc/settings/default.py
=> BUMP UP 2.24.0-Pumpkin version

src/ggrc/converters/handlers/snapshot_instance_column_handler.py, src/ggrc/utils/errors.py, src/ggrc/utils/objects_cache.py, test/integration/ggrc/converters/test_export_snapshots.py
Fix error export audit snapshot revision slug empty
and
Add missing test for current case and for the ticket GGRC-7669 https://github.com/google/ggrc-core/pull/9976
1. Login in GGRC;
2. Create program, audit;
3. Map control to audit;
4. Look in the DB for snapshot of control from step 3;
5. Find revision specified in snapshot and set `resource_slug` to `NULL`;
6. Click on mapped snapshot on UI and select "View original Control" option;
7. Go to "Audit" tab;
8. Select "Export Audits" from three dots menu;
9. Go on "Export" page and see that export has failed due to unknown server error.
- Added if-statement for `audit_snapshot_slugs_cache` if revision_slug is empty
- Added test for audit snapshot revison slug = None
- Added test for assessment snapshot revison slug = None (for ticket …
=> GGRC-7747 Fix error export audit snapshot revision slug empty

src/ggrc-client/js/components/inner-nav/inner-nav-vm.js, src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js, src/ggrc-client/js/plugins/tests/utils/mega-object-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js, src/ggrc-client/js/plugins/utils/mega-object-utils.js
Objects are not in alph order in Add tab menu.
> To initialize the list of objects "hiddenWidgets" in the "Add tab" menu, a request is made to the server. In our case, all objects are sent in one request[1], but another request[2] is sent, for a different purpose, in which there is a "Document" object. When working with a remote server, the first request is sent earlier than the second, but the response to the second comes earlier than the response to the first. Since when a new object is added to "hiddenWidgets", "push" is used, the objects that came after "Documen" will be in the list after it. But in such a scenario, the objects should be in the order [Documents, Access Group, ..., Workflow Tasks, ...], that is, first “Document”, and then in the same order as in the server response. …
=> GGRC-7646 Objects are not in alph order in Add tab menu

src/ggrc/models/assessment.py, src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_import_assessment_templates.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/models/test_with_sox_302.py
This PR merge requirements:
Add support for Assessment Template Search API
=> GGRC-8113: [MLV] Add support for Assessment Template Search API

src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js, src/ggrc-client/js/components/object-state-toolbar/tests/object-state-toolbar_spec.js
Undo button doesn't work for deprecated Assessments with empty mandatory LCA.
1. Create or open Assessment with mandatory LCA.
2. Set LCA empty.
3. Click Deprecate button in three-dots menu.
4. Click Undo button.
5. Verify that Assessment status is changed to previous one. 
Undo button doesn't change state if LCA has validation error. 
1. Updated to skip validation check if `isUndo` is set to `true`. 
2. Added unit tests for the `changeState` method
=> GGRC-8202 Undo link doesn't work for deprecated Assessments with empty mandatory LCA

src/ggrc/views/converters.py, test/integration/ggrc/services/resources/test_converters.py
Downloading of imported csv file from Import History failed if title contains non ascii characters
1. Download csv template for any object;
2. Fill out required fields and Save csv file;
3. Rename csv file with 'non ascii characters'
4. Import csv template
5. Download imported csv template from Import History
Change title of imported files to utf 
This change allows user to import file with any name, except few special chars
If file couldn't be imported, email is generated.
Files are visible only in "Import", so names can be of any characters, and cause no problems
=> GGRC-4913 Downloading of imported csv file from Import History failed if title contains non ascii characters

src/ggrc/converters/base_block.py, test/integration/ggrc/converters/test_export_assessments.py
If a user tries to export object and selects fields on UI that the object doesn't have, values in resulting file will be shifted (will be written in wrong columns).
1. Create two Assessments with different sets of LCAs;
2. Go to _"Export"_ page;
3. Select "Assessment";
4. Filter Assessment in _"FILTER QUERY"_ by title;
5. Select some LCAs that filtered Assessment doesn't have;
6. Click _"Start Export"_ button;
7. Open exported Assessment in Sheets;
Expected result: values in Issue Tracker and Mappings columns should be correct (not shifted);
The issue is related with the fact that `self.fields` and `self.object_headers` are of different length in `ExportBlockConverter`.
`self.fields` contains all fields that are passed in HTTP response from UI. Thus, if some fields that are not present on …
=> GGRC-7799 Mapped objects don't display in "map:.." columns in Export

src/ggrc-client/js/components/assessment/info-pane/confirm-edit-action.js, src/ggrc-client/js/components/assessment/tests/confirm-edit-action_spec.js, src/ggrc-client/js/components/create-document-button/create-document-button.js, src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js, src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js, src/ggrc-client/js/components/workflow/workflow-start-cycle.js, src/ggrc-client/js/plugins/utils/workflow-utils.js
1. Confirm edit button.
1.1 Launch GGRC.
1.2 Open assessment.
1.3 Make it completed.
1.4 Click "Edit Answers" button and confirm moving.
1.5 Expected: It works.
2. Create document button.
2.1 Launch GGRC.
2.2 Create or open existing data assets object.
2.3 Click "Attach button".
2.4 Click "attach new" on opened modal.
2.5 Select some files and upload.
2.6 Expect: It works.
3. Workflow utils.
3.1 Launch GGRC.
3.2 Create new workflow.
3.3 Setup task group and activate cycle.
3.4 Expected: It works.
Replace Deferred with Promise.
=> GGRC-8263 Replace Deferred with Promise part 0

src/ggrc/models/issuetracker_issue.py, test/integration/ggrc/integrations/test_assessment_integration.py
Hourly cron job doesn't update due_date of ticket in Issue Tracker
1. Create assessment with issue tracker ON and set a due date
2. Open Issue Tracker and look at the due date in the ticket: is displayed [^screenshot-5.png]
3. Remove due date on assessment
4. Run a cron job
5. Open Issue Tracker and look at the due date has been changed 
Fix 'update_from_dict' mothod of IssuetrackerIssue
=> GGRC-6181 Fix updating issue_tracker_issue due_date

src/ggrc_basic_permissions/__init__.py, src/ggrc_workflows/__init__.py, test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py, test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py, test/integration/ggrc_workflows/test_workflow_api_calls.py
User is not able to clone Workflow that user has no access to. There was a bug which allow to do that without proper permissions
Also, fixed bug with reading ACL permissions. 
If stubs list is an empty dict, a mistakes occurs and `load_access_control_list` returns an empty ACL permissions list. 
1. Login as Global Creator
2. Create any Workflow
3. Open dev tools and open created Workflow
4. Clone the just created Workflow
5. Copy Post request with title "workflow" as fetch
6. Paste request in console and change Workflow ID that Global Creator has no access to
Added check for a read permission before cloning.
=> GGRC-8152 Prevent cloning w/o read permissions

src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.js, src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field_spec.js
Fronted should not allow adding an empty attribute option of the Dropdown LCA.
1. Click Create Template button -> Create new assessment template
2. Select Dropdown LCA and input `1,2,3, , 5` (the 4th value is blank)
3. Click Add Field button
4. Verify that empty checkbox isn't created
1. Added check to exclude empty values
=> GGRC-8226 Fix issue when Empty Dropdown attribute option is allowed to add in LCA of the Assessment Template

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/tests/test_disabled_objects.py
Check that comments can not be added to Risk
=> GGRC-8284 Confirm user cannot add comment to Risk

package-lock.json, package.json, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache, src/ggrc-client/js/components/import-export/download-template/download-template.stache, src/ggrc-client/js/components/import-export/templates/export-group.stache, src/ggrc-client/js/components/import-export/templates/relevant-filter.stache, src/ggrc-client/js/components/required-info-modal/required-info-modal.stache, src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache, src/ggrc-client/js/plugins/console-interceptor.js
During the implementation of "Bulk Complete" epic, we needed to render the list of items. For now, "stache" mechanism allows us to use only deprecated syntax of #each helper (as was in CanJs v2) which is quite unclear in some situations. 
Need to investigate possibility to use new version of #each helper (#each(expression)) which'll allow us to iterate through the list items and explicitly give the name for each item (for now, we need to use . expression in order to get the current item of the list).
Doc with the new syntax: https://v3.canjs.com/doc/can-stache.helpers.each.html
1. Launch GGRC.
2. Open any tab or any object.
3. It works correctly.
Updated can-stache to the latest version. Now we can use `{{helper (expression, hash_expression)}}` or `{{helper expression, …
=> GGRC-8230 Investigate possibility to use {{#each(expression)}} construction in stache files 

src/ggrc/models/hooks/acl/propagation.py, test/integration/ggrc_basic_permissions/test_permissions_loading.py
After generating _Assessments_ from _Assessment Template_ and _Snapshots_ they does not appear at _"My Assessments"_ tab for _Assignee_ right away and even after page reload, but they should.
1. Login as User 1 (Admin) in one tab
2. Login as User 2 (Global Creator) in other tab
3. User 1 creates Program and maps 3+ Snapshots to it
4. User 1 creates Audit for Program and Assessment Template (User 2 is a default assignee) for Audit
5. User 1 generates Assessments based on Assessment Template and Snapshots
6. User 1 checks that all assessments were generated
7. User 2 accesses _"My Assessments"_ tab
Results before: Assessments does not shown at the _"My assessments"_ tab right away though they appear in a couple of minutes.
Expected result: All Assessments should appear right away.
When User …
=> GGRC-8199 Assessments appear at "My assessments" not right away

src/ggrc-client/js/components/assessment/assessment-local-ca.js, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/assessment/tests/assessment-local-ca_spec.js, src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js, src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js, src/ggrc-client/js/components/ca-object/ca-object-modal-content.js, src/ggrc-client/js/components/custom-attributes/custom-attributes.js, src/ggrc-client/js/components/custom-attributes/custom-attributes.stache, src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js, src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-picker-launcher.stache, src/ggrc-client/js/components/required-info-modal/required-info-modal.js, src/ggrc-client/js/modules/widget-descriptor.js, src/ggrc-client/js/plugins/ajax-extensions.js, src/ggrc-client/js/plugins/utils/ca-utils.js, src/ggrc-client/js/plugins/utils/errors-utils.js, src/ggrc-client/js/plugins/utils/notifiers-utils.js, src/ggrc-client/js/plugins/utils/query-api-utils.js
After first part of "Bulk complete" epic, there were found several places where code can be improved/cleaned up. 
1. Unused templates.
1.1 Open any object with info tab.
1.2 Open any object with custom dashboard or add a custom dashboard to object:
Open admin dashboard. Open custom attributes. 
Create new custom attribute with this parameters:
Attribute title: `Dashboard_ ` any text 
Attribute type: text
Create new object with created custom attribute. 
Add some link to created custom attribute. 
Link should start from `https://`
Open created object.
1.3 Open any audit. (Only there we can find summary widget)
1.4 Expected: Widgets works correctly.
2. `getLCAPopupTitle` util
2.1  Launch GGRC.
2.2 Create audit.
2.3 Create assessment template with `dropdown` as custom attribute.
2.4 Make …
=> GGRC-8229 Clean up / refactor FE-related code

src/ggrc/models/hooks/relationship.py, test/integration/external_app/test_ext_relationships.py, test/integration/ggrc/models/test_relationship.py
*Some relationships have related one (just mirrored) and when we delete one of two there is mapping between objects stay.*
*Now you can't create mirrored mappings, so you need program tests.*
*Add a hook for relationship deletion to delete mirrored too.*
=> GGRCIE-7746: GGRC and GGRCQ UI Out of Sync

test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_disabled_objects.py
Add test to check that user cannot update predefined field for risk
=> GGRC-8106 Add test to check that user cannot update predefined field for risk

src/ggrc/converters/column_handlers.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/boolean.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_import_reviewable.py, test/integration/ggrc/models/mixins/test_with_sox_302.py
For now, it is possible to create sox-302 assessment, export it to sheets, change value in sox_302_enabled column and import it without any warning or errors about the changes in read-only column.
1. Create an AssessmentTemplate with sox_302_enabled.
2. Create an Assessment with new Template. 
3. Export Assessments to google sheets, open - in column sox_302_workflow must be "yes". 
4. Change it to "no" and try to import. Warning should be displayed, and you can proceed. The column would be ignored.
5. In case of creating an Assessment via import, you can't make it "sox_302_enabled" without template. With the existing template, value from the template will be used instead of value in Assessment sox_302_workflow column. If there is a contradiction, warning would be displayed.
In order to …
=> GGRC-8204 Add warning import Asmt SOX 302 column change

src/ggrc/models/hooks/assessment.py, test/integration/ggrc/models/test_assessment_generation.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/service/rest_service.py
Audit Captain is set as Verifier on an Assessment being generated from an Assessment Template and a Snapshot if no Auditors present, but it should not.
1. Create an Audit and map some snapshots to it;
2. Leave _"Auditors"_ field empty for created Audit;
2. Create an Assessment Template with default verifiers to be taken from _"Auditors"_;
3. Click _"Autogenerate"_ button on _"Audit Summary"_ tab;
4. Select Template and Snapshot and generate Assessment;
5. Open generated Assessment;
**Expected result: Assessment's _Verifiers_ field should be empty.**
Previously the `_generate_role_people_map` method explicitly extended list of _Auditors_ with _Audit Captains_ it had if _Auditors_ where empty. This was made to populate _Assignees_ of generated Assessment with _Audit Captains_ if no …
=> GGRC-8033 Audit Captain is set as Verifier on autogenerated Assessment if no Auditors present

src/ggrc-client/js/bootstrap/modal-ajax.js, src/ggrc-client/js/components/object-mapper/create-and-map.stache, src/ggrc-client/js/components/related-objects/related-people-access-control.js, src/ggrc-client/js/components/related-objects/tests/related-people-access-control_spec.js, src/ggrc-client/js/plugins/utils/user-utils.js
When we reassign role from Role A (for example, WF Admin) to Role B (for example, WF Member) then, if we did not refresh the page, we still have ability to make actions like for Role A (Admin). 
1. Create some of this objects: assessment, wf, standard, regulation, requirement, objective, product, systems, metrics, technology env, product groups, proccesses, audit, access group, contract, data asset, document, evidence, facilities, key report, markets, org groups, policies, programs, projects, tasks, threats, vendors. 
2. Delete yourself from role 
**Actual Result**: You have ability to make actions like for role that was deleted. 
**Expected result**: Page should reload with new permisions. 
Refresh the permissions after delete yourself on all objects with inline edit (assessment, wf, …
=> GGRC-4249 User with changed role act as user with ex-role

src/ggrc-client/js/components/related-objects/revisions/related-revisions.js, src/ggrc-client/js/components/revision-log/revision-log.js, src/ggrc/query/custom_operators.py, test/integration/ggrc/services/test_query/test_not_empty.py, test/unit/ggrc/query/test_validate_decorator.py
*Change Log shows 'Modified' and 'Created' for mappings*
*Send empty put or similar post for any object. Open change log tab.
There is no wrong revisions*
BE:
Change not_empty_revisions filter operator to get also relationship revisions for object
Add ignore relationship flag and modify validate decorator to handle optional args too
FE:
Change format of filter for revisions.
=> GGRC-6133/GGRC-8077 Change Log shows 'Modified' and 'Created' for mappings

src/ggrc/services/common.py, src/ggrc/services/resources/relationship.py, test/integration/ggrc/services/resources/test_relationship.py
New record in change log shouldn't appear if relationship was updated via POST request
1. Create Product in GGRC
2. Go to GGRCQ, find the Product from step#1 & created Questionnaire for it
3. Add 'Dependency' answer using Product from step#1
4. Send POST request to create relationships between objects from the previous steps
5. Open any mapped object's 'Change Log' tab.
- added **is_new** attribute to **ModelView** class **default = False**
- enable **is_new = True** if request method is POST
- disable **Is_new = False** if relationship was already created and it is external relationship
- replaced **needs_update** arg with **needs_update ModelView** attribute
=> GGRC-7749 [Reopen] New revision record after update rels via post

src/ggrc/migrations/versions/20191210_a35b27563863_update_state_for_invalid_workflows.py, src/ggrc_workflows/__init__.py, test/integration/ggrc_workflows/test_workflow_api_calls.py
Fix changes logic for wf status changes via api calls, adds migration which cleans db from wf with wrong 'Active" status by making a revision and changing the status without removing such objects.
1. in dev: using dump db, check count of active workflows in My dashboard and LHN.
expected - different number
2. Log in as globcreator@gmail com
3. in branch GGRC-7229 do the same, expected - numbers are equal
in order to forbid incorrect status changes via api calls, new checks were added. To fix currently existing wf with incorrect statuses (f.e. Active wf with no task groups and no tasks) new migration was added, that cleans db of such workflows without removing objects.
=> GGRC-7229 Count of Active workflow are not the same on My dashboard and LHN

src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/controllers/info-widget-controller.js
`my_work_count` GET request is duplicated when add comment on objects via info pane
1. Login in tha GGRC app
2. Open My Dashboard
3. Open any object e.g Access Group
4. Open Network Tab in Crome dev tools
5. Add any comment
6. Verify number of `my_work_count` requests
Request `my_work_count` is sent after every instance created request. When add comments, `my_work_count` is sent after create Comment and Relationship objects that's why duplicated. 
Removed calling of `refreshCounts` method for Comment object type as this type isn't displayed in the menu.
=> GGRC-8297 Fix issue when "my_work_count" GET request is duplicated when add comment on objects via info pane

src/ggrc/views/__init__.py, test/integration/ggrc/views/test_get_attributes.py
After deprecating scope objects and moving external CADs back to all other CADs, performance degradation of the whole application is being experienced. 
1. Apply DB dump from QA environment;
2. Log in in the application;
3. Open _"All objects"_ page;
Expected result: All object page should be opened no more than 5 seconds.
At the time we had external CADs stored separately, we had to make 2 DB queries to get custom attributes - one for internal ones and one for external ones.  
After moving external CADs back to the same table as all other CADs, the second query is no longer needed so all the methods and functions were adjusted accordingly. Except for the `get_attributes_json()` function which was mistakenly made to query all CADs instead of all external CADs (which no longer exist). It …
=> GGRC-8445 Performance degradation of the whole application

src/ggrc/services/resources/audit.py, test/integration/ggrc/services/resources/test_audit.py
Snapshot icons are displayed for Global Creator with no rights in Audit
Precondition:
As Admin create an Audit
Attach several snapshots of objectives, e.g. Controls, Regulations, Vendors
Create an Assessment with mapped Control snapshot
Assign Global Creator as Assignee
Steps to Reproduce:
Login as Global Creator to GGRC
Open a previously created Audit
Check snapshots icons display
Actual result: Controls, Regulations, Vendors snapshot icons are displayed on the panel for Global Creator. The snapshots are not visible to Global Creator except the mapped Control to the Assessment where GC user is assigned
Expected: Only a Control snapshot icon should be visible to a Global Creator, other snapshot icons shouldn't be displayed
Count only Snapshots that user able to read
=> GGRC-8213 Snapshot icons are displayed for Global Creator with no rights in Audit

src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
We have tests included into "describe('viewModel() method')" for object-mapper component. If we remove it / move to other place then all other tests will be failed. It means that all other tests are depending on moved "describe" suite. Because of that, there is some troubles to update existing tests. Need to reorganize tests for object-mapper just to all suites will be independent of each other.
1. Open object-mapper_spec.test in IDE.
2. Comment a "describe('viewModel() method')" section.
3. Run tests.
4. All tests must be passed success.
Setting a value to viewModel variable was moved to beforeEach method. Since this variable declared in global scope and if we delete "describe('viewModel() method')" section this variable in next describe sections will be undefined.
=> GGRC-6293 Reorganize tests for object-mapper component

src/ggrc-client/js/components/delete-button/delete-button.js, src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js, src/ggrc-client/js/controllers/modals/archive-modal-controller.js, src/ggrc-client/js/controllers/modals/delete-modal-controller.js, src/ggrc-client/js/controllers/modals/modals-controller.js, src/ggrc-client/js/controllers/tests/archive-modal-controller_spec.js, src/ggrc-client/js/controllers/tests/modals-controller_spec.js, src/ggrc-client/js/plugins/tests/utils/modal_spec.js, src/ggrc-client/js/plugins/utils/modals.js
1. archive-modal-controller
1.1 Create or open existing audit.
1.2 Click archive from tree-dotted menu.
1.3 Confirm archiving.
1.4 Expected: Archive button has been disabled.
2. delete-modal-controller
2.1 Open or create audit.
2.2 Click delete form tree-dotted menu.
2.3  Confirm delete. 
2.4 Expected: Delete button has been disabled.
3. delete-button
3.1 Open or create audit.
3.2 Map to audit snapshotable object.
3.3 Open info-pane of mapped object.
3.4 Open tree-dotted menu and click delete.
3.5 Confirm delete.
3.6 Expected: Delete button has been disabled.
4. ggrc-gdrive-picker-launcher. …
=> GGRC-8251 Replace Deferred with Promise part 7

test/selenium/src/lib/page/modal/unified_mapper.py, test/selenium/src/tests/test_unified_mapper.py
Check that user cannot map Risk to Scope Objects/ Directives via Unified Mapper (create a new scope/directive object)
=> GGRC-8222 Check that newly created disabled obj cannot be mapped via um

src/ggrc/migrations/versions/20200122_14891a489a2d_remove_hanging_proposals.py, src/ggrc/models/proposal.py, src/ggrc/services/signals.py, test/integration/ggrc/proposal/api/base.py, test/integration/ggrc/proposal/test_proposal_relationship.py
Proposals are not deleted when a parent object is deleted.
2. Add a proposal
3. Delete a program
4. A proposal has been deleted
Add _delete_proposals method to Program class in src/ggrc/models/program.py
Add _delete_proposals func call to _handle_delete hook in src/ggrc/models/program.py
=> GGRC-7676 Delete proposals from db when parent object is deleted

src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js, src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js
Filter should display Verified Assessments when user clicks Show Results in Bulk Update floating message
Precondition:
3. Current user should be set as Verifier
4. Move Assessment to In Review state
Step to reproduce:
1. Open My Assessments
2. Set filter to display Assessments in In Review state only
3. Click Bulk Verify button
4. Verify Assessment from precondition using Bulk Verify tool
5. Wait while Assessment update be completed and click "Show Results" link in appeared floating message
6. Verify that assessments are shown by state Completed&Verified
Updated `reloadLink` to set Completed&Verified state
=> GGRC-8341 Filter should display Verified Assessments when user clicks Show Results in Bulk Update floating message

src/ggrc-client/js/models/business-models/access-group.js, src/ggrc-client/js/models/business-models/account-balance.js, src/ggrc-client/js/models/business-models/data-asset.js, src/ggrc-client/js/models/business-models/facility.js, src/ggrc-client/js/models/business-models/key-report.js, src/ggrc-client/js/models/business-models/market.js, src/ggrc-client/js/models/business-models/metric.js, src/ggrc-client/js/models/business-models/org-group.js, src/ggrc-client/js/models/business-models/process.js, src/ggrc-client/js/models/business-models/product-group.js, src/ggrc-client/js/models/business-models/product.js, src/ggrc-client/js/models/business-models/project.js, src/ggrc-client/js/models/business-models/system.js, src/ggrc-client/js/models/business-models/technology-environment.js, src/ggrc-client/js/models/business-models/vendor.js
=> QUICK-FIX Add migrationDate for Scope objects

src/ggrc/converters/base_row.py, src/ggrc/models/hooks/assessment.py, src/ggrc/models/hooks/audit.py, src/ggrc/models/hooks/issue.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/mixins/autostatuschangeable.py, src/ggrc/models/mixins/rest_handable.py, src/ggrc/models/mixins/with_sox_302.py, src/ggrc/models/proposal.py, src/ggrc/models/review.py, src/ggrc/notifications/notification_handlers.py, src/ggrc/services/common.py, src/ggrc/services/signals.py, src/ggrc_workflows/__init__.py, src/ggrc_workflows/notification/__init__.py, test/integration/ggrc/models/mixins/test_with_sox_302.py
The New Value in the Change log indicates that the status of the Assessment is 'In Review,' when in actuality it should state 'Completed (no verification)' as the result of all assessments being completed with affirmative answers in skip verify Assessment. The New Value in the Change log 
1. Create skip verify Assessment.
2. Assignee any Verifier to this Assessment.
3. Give affirmative answers and move Assessment in state 'Completed (no verification)'.
**Expected result:** The New Value in the Change log should be 'Completed (no verification)'.
Function for Execute skip verify Assessments status change flow was moved from handle_put_before_commit hook to handle_put hook.
=> GGRC-8329 Change log of Assessment represents the wrong status

src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/plugins/tests/object-history-utils_spec.js, src/ggrc-client/js/plugins/utils/object-history-utils.js
Dropdown/Multiselect CAs are not marked with changes in comparison window for Proposal.
1. Log as admin user and add dropdown, multiselect CAs for Program
2. Create a program with filled dropdown, multiselect CAs
3. Make a Proposal for Program: remove values in dropdown, multiselect CAs
4. Open Change Proposal tab and look at the current value/proposed value: changes are correct screenshot-1.png
5. Click Review&Apply button to open Comparison window
6. Look at the values in dropdown, multiselect CAs
_Actual Result:_ new values are not displayed and are not marked (red and green colors).
_Expected Result_: New values should be displayed and marked (red and green colors).
It's regression issue after #9223 PR.
Unneeded condition is removed to fix it.
=> GGRC-7437 Dropdown/Multiselect CAs are not marked with changes in comparison window for Proposal

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/notifications/bulk_notifications.py, src/ggrc/templates/notifications/bulk_complete.html, src/ggrc/views/bulk_operations.py, test/integration/ggrc/notifications/test_bulk_notification.py
If user opens bulk verify in one browser tab, selects multiple assessments to verify, then - without verificaton! - switches to another tab and deletes one of the selected assessments, then try to bulk verify - bulk verifies fails and pop-up appears.
3. Set current user as Verifier > move Assessment to In Review state
4. Open My Assessments
5. Click Bulk Verify button
6. Select created in the previous step Assessment
7. Open Created in the 2nd step Assessment in the new tab and Delete it
8. Open tab with Bulk Verify from the previous steps
9. Run Bulk Verify with selected Assessment (that was deleted before)
The problem arises when during import csvbuilder tries to interpret empty string as empty unicode string. By adding decode("utf-8") this problem …
=> GGRC-8339 Message that Bulk Status change for Assessment was failed doesn't send

src/ggrc/models/hooks/relationship.py, src/ggrc/models/relationship.py, src/ggrc/services/common.py, test/integration/external_app/test_ext_relationships.py, test/integration/ggrc/models/test_revision.py
1) Remove hook for revisions deletion
2) Correct delete method in dispatch request to delete related relationships
3) Change relatonship model to allow ext_app delete related internal relationships
4) Modify tests
=> GGRCIE-7746: GGRC and GGRCQ UI Out of Sync fixed version.

src/ggrc/migrations/versions/20200127_d0f2f2dcde8d_update_propagation_tree_for_assessment.py, src/ggrc/query/builder.py, test/integration/ggrc_basic_permissions/test_creator.py
User logged as Global Creator can read the comments from all objects (via console) - even if he doesn't have access to objects.
For local testing:
1. Log in by Global Creator user
2. Use query from GGRC-8265
**Expected Result:** User can see only comments from objects that he has access to.
The function _get_comments_type_query has been added to the query construction, which builds a filter based on the comments available to the user.
The propagation tree for Primary and Secondary contacts in Assessment was also updated, because access of these roles to the Evidence comments was a bug.
After changes in this PR access is granted in the correct way.
=> GGRC-8265 Creator has access to view all comments from every object

src/ggrc-client/js/components/object-selection/object-selection.js, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc-client/js/plugins/autocomplete.js, src/ggrc-client/js/plugins/tests/current-page-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js, src/ggrc-client/js/plugins/utils/current-page-utils.js, src/ggrc-client/js/plugins/utils/widgets-utils.js
1. Widgets-utils
1.1 Create audit and assessment.
1.2 Map to assessment some issues and evidences.
1.3 Expected: Counts of related objects displays correctly in tabs.
2. Mapper-results & current-page-utils & object-selection
2.1 Create audit and map to it some controls.
2.2 Create assessment for this audit,
2.3 Map controls to this audit, click select all.
2.4 Expected: It works.
2.5 Open audit, go to assessments tab and click expand tree.
2.6 Expected: It works.
Updated logic which connected to batchRequests util.
=> GGRC-8249 Replace Deferred with Promise part 5

src/ggrc-client/js/templates/custom_attribute_definitions/subtree.stache, src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache, src/ggrc-client/styles/_widget.scss
Edit header displays together with values (as 'NO') for Mandatory column that was removed for Assessments on Custom Attributes tab.
Edit header is not aligned with the column Edit on Custom Attributes tab.
Case 1: 
1. Open Custom Attributes tab.
2. Expand Assessment.
3. Verify table values.
Case 2: 
1. Open Custom Attributes tab.
2. Expand any object, e.g. Contract.
3. Verify that Edit header is align to right.
1. Hide `td` with Mandatory checkbox values in case of Assessment objects
2. Add `text-align` style for Edit header
=> GGRC-8567/GGRC-8568 Hide Mandatory checkbox values for Assessment on Custom Attributes tab

src/ggrc/models/control.py, src/ggrc/models/mixins/with_external_created_by.py, src/ggrc/models/risk.py, test/integration/ggrc/converters/test_export_snapshots.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/converters/test_snapshot_block.py
Following Q-side Control attributes should be displayed on UI on Control- and Export pages.
1. _"Created By"_;
2. _"Due Date"_;
3. _"Last Owner Reviewed Date"_;
4. _"Last Owner Reviewed By"_;
5. _"Last Compliance Reviewed Date"_;
6. _"Last Compliance Reviewed By"_.
1. Login in GGRC application;
2. Go on Export page and select "Control" in "Object type" dropdown;
3. See that all described attributes are present there.
The specified attributes already exist on Control model in GGRC Back-End, but they weren't added to `Control._aliases` and `Control._fulltext_attrs`. This is needed for these attributes to be shown on Export page and to allow the search of Controls by these attributes for further export.
Field names on `Control` model:
- `created_by` ("Created By");
- `due_date` ("Due Date"); …
=> GGRC-8231 Add external Control attributes to Export page

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/models/mappers/mappings-ggrc.js, src/ggrc-client/js/models/mappers/tests/unmappings_spec.js
Evidence can exist in deprecated state without mapping to assessment, and can be unmapped via trash icon. But we can't unmap it via Unmap button from tree dots menu on info pin.
1. Create an assessment.
2. Add an evidence.
3. Open evidence tab.
4. Open evidence in info pane.
Expected: "Unmap" is shown in 3bbs.
Added unmap rule to Assessment for Evidence. Added refreshing info pane page after evidence or snapshotable object was unmapped from assessment.
=> GGRC-5326 Unmap button is not shown for evidence on assessment

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user cannot update Scope obj status
=> GGRC-8512 Confirm user cannot update Scope obj status

src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache, src/ggrc-client/js/components/tree-view-filter/tests/tree-view-filter_spec.js, src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js, src/ggrc-client/js/components/tree/templates/tree-filter-input.stache, src/ggrc-client/js/components/tree/tree-filter-input.js, src/ggrc-client/styles/_colors.scss, src/ggrc-client/styles/components/action-button/_action-button.scss, src/ggrc-client/styles/components/tree/_tree-view.scss
On clicking 'Open Assessment list' at email with successful tickets generation,  a filtered out list of assessments, for which ticket tracker integration was turned on successfully via import, should be displayed in GGRC app 'All objects' page.
At 'All objects' page a clip with the name 'Email Import' appears at input field.
At 'All objects' page a floating message should be added with clarification what user sees on a screen: _The filter query refers to the report you've received on your email._
Open the APP by link:
_http://localhost:8080/objectBrowser#!assessment&saved_search={**your_existing_saved_search_id**}&labels=Import+Email_
Add "Email Import" clip to `tree-filter-input` component.
Show that clip when a "saved search" opened by URL and route has `labels=Import+Email` queryParam
=> GGRC-7750 Put 'Open Assessments / Issues list' link into email "Ticket generation completed successfully"

test/selenium/src/tests/test_disabled_objects.py
Confirm change log tab for Scope objects is valid
=> GGRC-8562 Confirm change log tab for Scope objects is valid

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/issuetracker_issue.py, test/integration/ggrc/integrations/test_asmt_sync_job.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/integration/ggrc/integrations/test_bulk_issue_generate.py
This pr also fix GGRC-6181
This PR is `on hold` GGRC-8543 will be fixed:
Issue tracker doesn't sync empty Due Date in Assessment
1. Open any adit page with issue tracker turned ON
2. Create Assessment with empty Due date and issue tracker turned ON
3. On Assessment Info panel click Ticket link
4. Once Issue Tracker is displayed look at Due Date in Ticket: is empty (correct)
5. Add empty due date in Assessment
Actual Result: If due date is empty in assessment, it should sync with issue tracker
*Change all 'if' statements to accept None value of 'due_date' attr*
=> GGRC-6207/GGRC-6181: Issue tracker doesn't sync empty Due Date in Assessment

src/ggrc-client/js/components/object-list-item/comment-list-item.stache
When the user responds with a negative answer to a question within the assessment, the question pertaining to this negative answer within the responses/comments section becomes cut off on the screen. As a result, the entire question is not visible in the responses/comments section. Solution: The user recommends text wrapping as the solution so that the question does not become cut off.
1. Create Audit.
2. Create Assessment template with LCA dropdown which has long title.
3. Create Assessment with AT which was added at second step.
4. Fill dropdown.
5. Look and hover over the comment title.
**Actual Result**: The title is cropped.
**Expected result**:  The title is displayed cropped with three dots. After hovering, a tooltip with a full title is displayed.
If LCA title length is longer …
=> GGRC-8331 LCA and answer is cut when added a Required comment

src/ggrc/integrations/constants.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/integration_utils.py, src/ggrc/models/hooks/relationship.py, src/ggrc/utils/helpers.py, test/integration/ggrc/integrations/test_assessment_integration.py
This PR is `on hold` GGRC-8543 will be fixed:
'Assessment procedure' is missed in Issue Tracker
This is fix of #9794 reopen
1. Open any audit page with a control snapshot with filled "Assessment Procedure";
2. Turn on Issue Tracker for audit with valid Component ID and Hotlist ID;
3. While creating assessment map a control snapshot via "New Assessment" popup;
4. Navigate to "Assessment Info" pane and click ticket link;
Expected Result: If assessment has an "Assessment procedure'"it should be displayed in Issue Tracker. If it is changed - a corresponding comment should be left at Issue tracker (overall should be synced like "Remediation plan" for issues).
Solution includes following changes:
- New handler `handle_snapshot_link` which is being called upon relationship creation between …
=> GGRC-4506: Assessment procedure from mapped snapshot is not copied to Issue Tracker

src/ggrc-client/js/components/datepicker/datepicker-component.js, src/ggrc-client/js/components/datepicker/datepicker-component.stache, src/ggrc-client/js/components/tests/datepicker-component_spec.js, src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js, src/ggrc-client/js/models/business-models/task-group-task.js, src/ggrc-client/js/plugins/tests/date-utils_spec.js, src/ggrc-client/js/plugins/utils/date-utils.js
Date and date.time. Calendar widget has two variants of picked date.
1. Try to create any object with start/end date:
2. **First option**: open calendar and choose date - today > save&close. Look at request payload in devtools - there are only date(for current user timezone) was send to BE.
**Second option**: do not open calendar(by default date = today) > save&close. Look at request payload in devtools - there are date.time(UTC) was send to BE.
**Actual Result**: FE send date to BE in with time.  
**Expected result**: FE send date to BE without time.  
Add formatting of date for new date instances.
Refactor datepicker component. Fix datepicker bugs.
=> GGRC-7800 [FE] Date and date.time. Calendar widget has two variants of picked date.

src/ggrc-client/js/models/business-models/regulation.js, src/ggrc-client/js/models/business-models/standard.js, src/ggrc-client/js/templates/base_objects/object-review-state.stache, src/ggrc-client/js/templates/directives/info.stache, src/ggrc-client/js_specs/models/object-state_spec.js
Remove everything related to Object Review' block: Info pane/page, Advanced/Global search.
Old snapshots (created before migration) should have Object Review information.
New or updated snapshots (created or updated after migration) should not have Object Review information.
2. Verify that Object Review Information is hidden.
3. Open Advanced/Global search for the object.
4. Verify that Review Status is hidden.
5. Open any snapshot for the object. 
6. Verify that Object Review status is shown. 
Removed `Reviewable` mixin, `Review Status` attribute from the models. 
Added `objects-review-state` template to show Object Review only on snapshot.
=> [S&R: Phase 2] GGRC-8488 Remove Object Review Information

src/ggrc-client/js/components/simple-modal/simple-modal.js
Disable possibility closing modal by pressing escape when modal disabled.
1. Create AT with dropdown that will have "EVIDENCE FILE REQUIRED" option.
2. Create Assessment with this AT.
3. Select option with "EVIDENCE FILE REQUIRED".
4. Upload file.
5. Press ESC when modal load file.
**Actual Result**: Modal will be closed.
**Expected result**: Modal will not be closed.
Add handler of escape event which will cancel the closing.
=> GGRC-8216 Add possibility to prevent close simple modal after clicking ESC button

src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py, test/unit/ggrc/models/test_revision.py
Created By attribute is not displayed in Change Log for Risks 
1.	Create Risk object on GGRCQ side
2.	Open created Risk on GGRC side
3.	Open Change Log tab
Expected: Created By attribute is displayed in Change log
Add populate_created_by method to Revision class.
=> GGRC-8594 Add populate_created_by method to Revision class

src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache, src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js, src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-filter-input.js, src/ggrc-client/js/components/tree/tree-status-filter.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/controllers/summary-widget-controller.js, src/ggrc-client/js/templates/audits/summary.stache
Assessments are filtered incorrect if open Assessments by state from Audit Summary tab
1. Open Audit Summary page and click on Assessments in any state e.g Deprecated.
2. Click any state on Audit summary, e.g. In Progress.
3. Review filtered assessments. 
4. Open Audit Summary page again and click on Assessments in another state.
5. Verify filtered assessments. 
1. Request to get assessments is sent before update filter values that's why incorrect values are shown => Updated buildSearchQuery to call onFilter event  after searchQueryChanged event. 
2. Removed `total !== counts` condition from `_widgetShown` so as this perform double requests to get assessment. And this condition is already covered by `_triggerListeners`.
3. Added `allStatesUrl` attribute to correctly trigger …
=> GGRC-8334 Fix issue when Assessments are filtered incorrect if open Assessments by state from Audit Summary tab

src/ggrc/integrations/constants.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/issue_integration.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/integration/ggrc/integrations/test_issue_integration.py
*Assessment is not created when hotlist ID is invalid or not existing and message shown is not clear enough.*
1. Go to Audit with Buganizer switch turned ON.
2. Click Create assessment button.
3. Fill out all the required fields.
4. Make sure that Buganizer is turned ON for Assessment.
5. Enter invalid / non-existing Hotlist ID.
6. Click 'Save' button for assessment.
Assessment should be created
Buganizer issue should not be created
"The ticket tracker issue cannot be created. Check if the Hotlist ID and Component ID are correct and try again or contact our support service" should be shown.
1)Remove warning messages for issue and assesment and add common message for ticket
2)Change assessment and issue integration to use common ticket message
3)Implement tests for issue and assessment
=> GGRC-3829: Issue Tracker Issue is not created if enter invalid / non-existing Hotlist ID:

src/ggrc/models/mixins/customattributable.py, src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/models/mixins/test_customattributable.py, test/integration/ggrc/models/test_revision.py
LCA changes are not displayed in the Assessment template change log.
2. Create Assessment template with LCA
3. Open Assessment template and add any LCA e.g Text
4. Open revision in DB for edited Assessment template
**Expected result:** In revision content should be information about LCA.
Solution for this issue consists of two parts: BE and FE (#10569)
From BE part of solution was added to function `log_json` in file `src/ggrc/models/mixins/customattributable.py` checking of custom attribute definitions. What provides the addition of information about LCA to assessment template revision.
Also was changed `prepare_content_full_diff` from `src/ggrc/utils/revisions_diff/builder.py`, because changes in custom attribute definitions were ignored in step of building revision.
=> GGRC-8021 LCA changes are not displayed in the Assessment template change log

src/ggrc-client/js/components/related-objects/related-objects.js, src/ggrc-client/js/components/related-objects/tests/related-objects_spec.js
While opening another page with proposals on program, related proposals after loading doesn't update immediately and old values is displaying throughout ~500 ms after the spinner disappeared.
1. Create a Program on GGRC
2. Make 6 proposals for the Program
3. Click on Change proposals tab
4. Click on the 2nd page of the proposals
Actual result: the first 5 proposals display for 1-2 sec as blinking on the second page where only the 6th proposal is placed
Expected result: the second page should open a list of proposals without blinking of the list of proposals from the first page
Hiding a spinner moved to point after rendering loaded proposals.
=> GGRC-8117 List of proposals blinks when the second page is opened on Change Proposals tab for a Program

src/ggrc-client/js/components/tree/tests/tree-item-actions_spec.js, src/ggrc-client/js/components/tree/tree-item-actions.js
Edit functionality is not disabled for Cycle Tasks in History tab.
1. Create a workflow.
2. In the setup tab on workflow page create a task for task group.
3. Activate Workflow.
4. In Active Cycles tab End Cycle.
5. Open History tab and expand tree view with Cycle Task.
6. Hover over Cycle task's triangle.
7. Verify Edit and map objects on the history tab is not allowed for the user
Extend `denyEditAndMap` with condition for `is_in_history`.
=> GGRC-8629 Edit functionality is not disabled for Cycle Tasks in History tab

src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js, src/ggrc-client/js/plugins/utils/advanced-search-utils.js
Saved search link for tasks is generated incorrect from Workflow Task Tab. 
1. Open any object e.g Standard
2. Add Workflow Task tab to the object
3. Click create button
4. Set all mandatory fields and click Save & Close button
5. Click on the filter icon
6. Enter any Saved Search title and click Save Search button
7. Copy Saved Search link
8. Paste and open in a new browser tab
9. Verify that Workflow Task info tab is opened
Added condition for `cycle_task_group_object_task` widget id in `buildSearchPermalink` function
=> GGRC-8273 Saved search link for tasks is generated incorrect

test/selenium/src/lib/base.py, test/selenium/src/lib/page/modal/bulk_update.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_asmts_bulk_update.py
Extends test test_bulk_verify_modal_filter with checks of opening assessment detail page and checks of expanded sections.
=> GGRC-8574 Add test checking assessment detail page on bulk verify modal GGRC-8582 Add test checking opening of assessment in bulk verify modal

src/ggrc_workflows/models/workflow.py, test/integration/ggrc/generator.py, test/integration/ggrc_workflows/models/factories.py, test/integration/ggrc_workflows/models/test_workflow.py
Archived workflow can be unarchived via an API call. This is invalid behavior. Unarchiving should be prohibited
1. Create workflow
2. Archive workflow via UI
3. Send API GET request for Workflow from the previous step in Postman e.g **qa instance** /api/workflows/2141
4. Copy body of the request
5. Paste copied body in request body in Postman
6. Change "recurrences" value in body to "true" 
7. Change API method to PUT
8. Add the following headers
Content-Type:application/json
x-requested-by:GGRC
If-Unmodified-Since:{{last-modified}}
If-Match:{{etag}}
x-usertimezoneoffset:180
Accept-Encoding:gzip, deflate, br
9. Add the following script to the Pre-request Script tab:
pm.sendRequest(" **qa instance** /api/workflows/2141", function (err, response){
pm.globals.set("etag", …
=> GGRC-8285 remove the possibility of changing state from archived to unarchived for workflows via api put

src/ggrc/integrations/issuetracker_bulk_sync.py, test/integration/ggrc/integrations/test_bulk_issue_generate.py
This PR is `on hold` GGRC-8543 will be fixed:
*Currently we don't make revisions if sync failed via bulk mechanism and we disabled Issue Tracker integration for object in this case. *
*You can create mock to raise exception to fall bulk sync and check db for revisions.*
*In case we have errors and disable IssueTracker we also add log_issues method to create revisions for this event.*
=> GGRC-6410: Create revisions for objects failed to sync via bulk mechanism:

src/ggrc/models/evidence.py, test/integration/ggrc/converters/test_import_helpers.py
Changes for the Note field are not pulled in Evidence Change log.
1. Open any Evidence
2. Open three dots menu and click Edit Evidence
3. Add any note for the Evidence URL
4. Open Change Log tab
**Expected:** Changes for the Note field are displayed in the Change log.
Field Note was added to `_aliases` for Evidence model.
=> GGRC-8071 Add changes for the Note field to the Evidence's Change Log

src/ggrc/notifications/data_handlers.py, src/ggrc/templates/notifications/email_digest_content.html, test/integration/ggrc/notifications/test_assessment_notifications.py
Notification "New assessments were created" doesn't contain date and time for assessments in /_notifications/show_daily_digest
1. Create new Assessment on the audit page
2. Go to https://ggrc-qa.appspot.com/_notifications/show_daily_digest or https://ggrc-qa.appspot.com/_notifications/show_pending
3. Look at the "New assessments were created" notification
Actual Result: Notification "New assessments were created" doesn't contain date and time for assessments in /_notifications/show_daily_digest
Expected Result: Notification "New assessments were created" should contain date and time for assessments in /_notifications/show_daily_digest
Added new attribute obj_created_at in for notif data in the data_handlers file.
Updated the email template to display the object_created _at time in the …
=> GGRC-2753 New assessments created do not contain date and time for assessments in Notifications

src/ggrc-client/js/components/revision-log/revision-page.js, src/ggrc-client/js/components/revision-log/revision-page.stache, src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js, src/ggrc-client/js/components/role-avatar/role-avatar.js, src/ggrc-client/js/plugins/utils/acl-utils.js, src/ggrc-client/styles/_modules.scss, src/ggrc-client/styles/modules/_label-list.scss, src/ggrc-client/styles/modules/_role-avatars.scss
Recently, we've had a logic, when a person associated with Assessment added a comment/file/url/mapping, there was a corresponding icon in Change Log tab, e.g.:
Assignee - "A";
Verifier - "V".
Currently, such logic is broken and 'N' icon is displayed for all the changes with Assessment screenshot-1.png.
1. Open any assessment.
2. Assign yourself as Assessment assignee or verifier.
3. Leave a comment or add evidence url > Open Change Log tab.
**Actual Result**: 'N' icon is displayed.
**Expected Result**: 'A' (assignee) or 'V' (verifier) icon is displayed.
Implement the display of different avatars according to the role. All changes were made based on PR #9629 when icons for roles were deleted.
=> GGRC-7389 Incorrect icons for people in Change Log tab in Assessment	

src/ggrc/converters/base.py, src/ggrc/converters/base_block.py, src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/issue_tracker.py, src/ggrc/integrations/issuetracker_bulk_sync.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/integration_utils.py, src/ggrc/models/hooks/issue_tracker/issue_integration.py, src/ggrc/views/__init__.py, test/integration/ggrc/integrations/test_bulk_issue_generate.py
This PR is `on hold` GGRC-8543 will be fixed:
When turning OFF the integration on Assessment / Issue via import, there is not any comment in BUG that integration was turned OFF, but it should.
1. Create an Issue/Assessment in GGRC with Issue Tracker turned ON 
2. Export Issue to Google Sheet
3. Turn OFF Issue Tracker and Import Issue 
4. Click on Ticket Tracker link on Issue Info page/panel to open Issue Tracker
5. Look at the BUG
Actual Result: There is no message that "Changes to this GGRC object will no longer be tracked within this bug."  for issue and "Changes to this GGRC Assessment will no longer be tracked within this bug." for assessment*
Expected Result: messages should be displayed.
*Get needed issuetracker issue ids before changing and implement IssueTrackerDisableUpdater for …
=> GGRC-6396: Add a comment to BUG if Integration was turned OFF

src/ggrc-client/js/components/access-control-list/access-control-list-roles-helper.js, src/ggrc-client/js/components/access-control-list/access-control-list-roles-helper.stache, src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache, src/ggrc-client/js/components/custom-roles/custom-roles-modal.js, src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache, src/ggrc-client/js/components/effective-dates/effective-dates.stache, src/ggrc-client/js/components/gca-controls/gca-controls.stache, src/ggrc-client/js/components/modal-container/modal-container.js, src/ggrc-client/js/components/related-objects/related-people-access-control-group.js, src/ggrc-client/js/templates/assessment_templates/modal-content.stache, src/ggrc-client/js/templates/audits/modal-content.stache, src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache, src/ggrc-client/js/templates/contracts/modal-content.stache, src/ggrc-client/js/templates/issues/modal-content.stache, src/ggrc-client/js/templates/objectives/modal-content.stache, src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache, src/ggrc-client/js/templates/people/modal-content.stache, src/ggrc-client/js/templates/policies/modal-content.stache, src/ggrc-client/js/templates/programs/modal-content.stache, src/ggrc-client/js/templates/regulations/modal-content.stache, src/ggrc-client/js/templates/requirements/modal-content.stache, src/ggrc-client/js/templates/standards/modal-content.stache, src/ggrc-client/js/templates/task_group_tasks/modal-content.stache, src/ggrc-client/js/templates/task_groups/modal-content.stache, src/ggrc-client/js/templates/threats/modal-content.stache
Hide button should be shown for custom roles. 
Hide function works incorrect: when click Hide on an attribute, expected that only the attribute should be hidden, but actual all attribute are hidden
Case 1:
1. Open e.g Create  modal for any Object.
2. Fill all mandatory fields.
3. Click Hide icon on any GCA.
4. Click Save & Close button.
5. Open Create new issue modal again.
Expected: All GCA are displayed except one that was hidden in the step 3.
Case 2:
1. Open any Audit.
2. Click Create Template button on Audit Summary tab.
3. Click Create new assessment template link.
4. Set all mandatory fields.
5. Click Hide icon on the "Default Verifiers" field.
6. Click Save & Close button.
7. Click Create template button on Audit Summary tab one more time.
8. Click Create new assessment template …
=> GGRC-8518 Hide function for the attributes works incorrect

test/selenium/src/lib/constants/messages.py, test/selenium/src/lib/service/webui_facade.py
Refactor format_err_msg_equal method to extend error message of general assert lists comparison to have possibility to investigate root causes of tests failures.
=> GGRC-8644 Refactor format_err_msg_equal method

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_export_assessment_templates.py
Looks like Principal Assignees and Secondary Assignees are not applicable for Standard, Regulation, Requirement, Objective, Threat, Contract, Policy, Scope objects types.
Run application go to Import -> Download template -> Assessment Temaplate.
Look at description for "Default Assignees*" and "Default Verifiers" column
Delete aliases for that roles from constant.
=> GGRC-8674 Change list of default assignees, verifiers

src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.stache, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-state_spec.js
Filtered states are not saved in Advanced search if click Apply button after selecting states
1. Open All Objects page
2. Select any object e.g Standards
3. Open Advanced Search
4. Set State filter to display only Standard in e.g Draft state and click Apply button
5. Verify that State Filter is applied. 
Save filter states values on `selectedChanged` event instead of `dropdownClose`. Initialise `filterStates` on `inserted` event to avoid rerender of `multiselect-dropdown` component.
=> GGRC-8597 Filtered states are not saved in Advanced search if click Apply button after selecting states

src/ggrc/models/reflection.py, test/integration/ggrc/models/mixins/test_with_sox_302.py
Hints for the Text and Rich text Custom attributes columns should be changed or removed, it can confuse the user.
1. Create SOX302 Assessment template with Text and Rich text LCA (And mark Not Empty as a negative response)
2. Create Assessment using Created in the previous step template
3. Export created Assessment
4. Open exported file
**Expected result:** No hints should be included in the field. The same as for NOT SOX 302 assessments.
Hints for the Text and Rich text Custom attributes was removed on step creating csv file.
=> GGRC-8232 Hints for the Text and Rich text Custom attributes columns should be changed

src/ggrc-client/js/components/form/field-views/text-form-field-view.stache, src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.stache, src/ggrc-client/js/models/business-models/risk.js, src/ggrc-client/js/templates/assessments/modal-content.stache, src/ggrc-client/styles/components/saved-search-list/_saved-search-list.scss, src/ggrc-client/styles/modules/_audit-summary.scss, src/ggrc-client/styles/modules/_modal.scss
1. Input field in create-saved-search is not highlighted (Updated by BA: remove highlight from advanced search)
3. Incorrect layout of trash icon on Global Search
4. Select Assessment Template field should be below "Map Object" button on New assessment modal
5. Read more for dropdown LCA is not displayed
6. Pop up on Assessments diagram is blinking on hover
7. Incorrect date in UI message in Risk Change Log tab
1. Login GGRC app and open Advanced search
2. Save filter for any object type
3. Expected: `Type to save search` input doesn't highlighted
4. Hover over saved filter and look at the trash icon
5. Trash icon align on center
9. Open any Audit page
10. Open Assessments tab
11. Click Create button
12. Review Edit modal
13. Expected: Select Assessment Template field is displayed below …
=> GGRC-7533/GGRC-7531/GGRC-7595/GGRC-8004/GGRC-8212/GGRC-7943 Styles improving

src/ggrc/models/review.py, test/integration/ggrc/models/test_program.py
Reseted "reviewed" status to "unreviewed" for Program when acl was changed
1. Create Program with standard list of recipients.
2. Set Program review status to "Reviewed".
3. Update list of recipients.
4. Program status will not revert to "Unreviewed".
Add if statement in  function _update_status_on_attr to file src/ggrc/models/review.py.
Cover changes by some test.
=> GGRC-7254 Reseted "reviewed" status to "unreviewed" for Program when acl were changed 

src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
Request Payload query is duplicated when Status filter is applied to objects in Advanced Search
1. Open GGRC
2. Open All Objects dashboard
3. Click on any object's tab, e.g. Regulation
4. Open Network tab in dev console
5. In State dropdown select any state, e.g. Active
6. Apply it
7. Expand 'query' in Network tab in dev console
8. Check Request Payload section
9. Expected: Request Payload query should not be duplicated.
Added extra condition for updateCurrentFilter() method for preventing extra trigger the search if it isn't search on audit page by assessment states.
=> GGRC-8701 Request Payload query is duplicated when Status filter is applied to objects in Advanced Search	

src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
Mapping to Assessment is duplicated in Advanced Search.
1. Open any Audit.
2. Create Assessment and open it in a new tab.
3. Open Audits tab.
4. Open Advanced search.
5. Add any Saved Search title and click Save Search button.
6. Copy Saved search link.
7. Open in a new tab.
8. Open Advanced Search and close it.
9. Open Advanced Search again.
**Actual Result**: Mapping to Assessment is duplicated in Advanced Search.
**Expected result**: Mapping to Assessment shouldn't duplicate in Advanced Search.
Move filtering of duplicates to another condition.
=> GGRC-8274 Mapping to Assessment is duplicated in Advanced Search

src/ggrc-client/js/models/business-models/audit.js, src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js, src/ggrc-client/js/plugins/tests/utils/validation-utils_spec.js, src/ggrc-client/js/plugins/utils/validation-utils.js, src/ggrc-client/js/plugins/validation-extensions.js, src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal-content.stache
Fields that will be affected:
1. Audit Firm (add/edit audit pop-up);
2. Program (add/edit audit pop-up);
3. Active Workflow (add/edit cycle-task pop-up);
4. Task Group (add/edit cycle-task pop-up).
User clicks 'Start New Audit' button on dashboard.
On 'Create' Audit pop-up, start typing existing name of program in 'Program' field and select it from autosuggest.
Move focus into 'Program' field and change the name of selected program to non-existing.
Move focus out of the field.
Actual result: invalid name of program is still displayed. When Audit is saved, it will be saved with program selected on step 2.
This behaviour is reproduced on cycle-task pop-up with workflow and task group fields.
1. Launch GGRC.
2. Click on "Start new Audit".
3. Add Program and Audit Firm
4. Edit this values. …
=> GGRC-5527 Invalid value in fields with autosuggest should be reset to last saved state on moving focus out

src/ggrc/models/exceptions.py, test/integration/ggrc/models/test_program.py
Correct upper case in error message when a Program with already existing title
1. Create a program with already existing title 
2. Check the error message 
Letter has been corrected  from lowercase to upper case in error message when a Program already exist
=> GGRC-8239 Correct letter in error message when a Program already exist

src/ggrc-client/js/components/import-export/csv-import.js, src/ggrc-client/js/components/import-export/templates/csv-import.stache
Add Cancel button according to the mockup in the ticket [UX/UI] Cancel import.
User should be able to remove the results of previous import on the import page.
1. Open import page.
2. Choose file.
**Actual Result**: The cancel button did not appear after analysis.
**Expected result**: The cancel button appeared after analysis.
Add "Cancel" button for "Not Started", "Failed" and "Analysis failed" statuses.
=> GGRC-8605 FE: Cancel import button

src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache, src/ggrc-client/js/templates/audits/modal-content.stache, src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache, src/ggrc-client/js/templates/programs/modal-content.stache, src/ggrc-client/styles/modules/_modal.scss
1. 'Hide' option is missed on some optional fields (people fields).
2. 'Hide' option is located far from the field.
1. Open modals of objects that are listed  in "Solution description".
2. Look at the "hide" buttons and "Show/Hide all optional fields".
**Actual Result**:  Not displayed on all required fields.
**Expected Result**: Displayed on all required fields
Add 'Hide' option to people fields at objects 'Edit' and 'New' screens for:
Programs'
=> GGRC-6937 Align 'Hide' on 'Edit' and 'New' screens of all objects by right border of the field

src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js
Newly created GCA's are appeared only after page refresh.
1. Open Administration page
2. Open Custom Attributes Tab
3. Click e.g on Programs
4. Click + icon and any Attribute title and select any attribute type e.g Text
5. Click Save & Close button
6. Open LHN =>
7. Click Create button
**Actual Result**: Newly created attribute is not displayed in the Create new program modal.
**Expected result**: Newly created attribute is displayed in the Create new program modal.
Add new GCA to global variable after creating.
=> GGRC-8664 Newly created GCA's are appeared only after page refresh

src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.js, src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field_spec.js
System cuts the text after 255 symbols in LCA titles.
1. Start creating Assessment Template
2. Create LCA - insert the text in the title of LCA with more than 255 symbols
3. Submit adding LCA
4. Expect: Error 'A custom attribute title cannot contain more than 255 symbols' displays.
Added validation for LCA's title length.
=> GGRC-8333 Assessment template Field Attribute Character Limit

src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js
Attachment folder is not updated on UI in all objects when it's changed via Edit mode.
1. Open GGRC-uat.
2. Create any object, e.g. Regulation.
3. Click 'Assign folder' .
4. Select a folder in gdrive.
5. Click on Edit object button via 3bb's menu.
6. Click on Edit icon near the Attachment.
7. Select a new folder in gdrive.
8. Save changes.
9.Validate an updated folder on the Info page of the object.
To save a folder, `add_folder` request should be sent after instance save. 
Added `'{viewModel.instance} modelAfterSave'` event to save folder. 
Added `'{viewModel.instance} folder'` event  to refresh folder value on Info page.
=> GGRC-8724 Attachment folder is not updated on UI in all objects when it's changed via Edit mode

src/ggrc/views/bulk_operations/utils.py, test/integration/ggrc/bulk_operations/test_matrix.py
There is an empty response for cavs/search if assessments value in empty if assessment has no any LCA
1. Create audit
2. Create asmt template
3. Gen assessment
4. Run query:
_fetch("http://localhost:8080/api/bulk_operations/cavs/search", {"credentials":"include","headers":{"accept":"*/*","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","cache-control":"max-age=0","content-type":"application/json","if-match":"undefined","if-unmodified-since":"undefined","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","x-requested-by":"GGRC","x-requested-with":"XMLHttpRequest","x-usertimezoneoffset":"180"},"referrer":"http://localhost:8080/assessments_view","referrerPolicy":"no-referrer-when-downgrade","body":"[{\"object_name\":\"Assessment\",\"type\":\"ids\",\"fields\":[],\"fil …
=> [Matrix view] QUICK-FIX Match assessments with cads if cad is null

src/ggrc/models/system.py, test/integration/ggrc/models/test_query_api_queries.py
GCAttr for System are not synced from Q to C or GCAttr values are not displayed on C 
Run sync from Q to C with GCA for System type and validate changes
Add CustomAttributable mixin
=> GGRCIE-8713 / GGRCIE-8978 - fix sync system with GCA

src/ggrc-client/js/components/redirects/external-control/external-control.js, src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Incorrect redirection link for all Scope Objects in ACTIVE state. User should be redirected to the Background Info page on Q side when Edit icon of any field is clicked of any ACTIVE Scope object on GGRC. Url should be the following `https://${urlToQ}/questionnaires/key_report=keyreport-57/initialize
`
1. Open any Scope object in Active status
2. Click on Edit icon for any fields
3. Verify that redirection url contains `/initialize` 
4. Verify that any Scope object in other status does not contain `/initialize`  in redirection url for fields. 
Added `getQuestionsAttrUrl` method to build url based on status
=> GGRC-8815 Incorrect redirection link for all Scope Objects in ACTIVE state only

src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache, src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
Add tooltip for assessment title link
1. Open Bulk Complete mode
2. Put cursor on assessment title. Tooltip 'Open in a new tab' should be shown
Add tooltip for assessment title link on `<assessments-bulk-complete-table-row>`
=> [Matrix view] QUICK-FIX Add tooltip for assessment title link

src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
Border bottom does not stretch across the table if column fit to the screen width.
1. Open Bulk Complete mode for asmt with (1-2 columns).
Check border bottom.
Border bottom should be the entire width of the table.
Border bottom should not be transparent when scrolling with an open absolute element (dropdown, calendar).
2. Open Bulk Complete mode for asmt with many columns. Check border bottom.
Use box-shadow instead of border-bottom.
=> [Matrix view] QUICK-FIX Fix border bottom for Bulk Complete table
