google/ggrc-core

- src/ggrc-client/js/components/input-filter/input-filter.js
- src/ggrc-client/js/components/input-filter/templates/input-filter.mustache
- src/ggrc-client/js/components/input-filter/tests/input-filter_spec.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc/assets/mustache/access_control_roles/modal_content.mustache
- src/ggrc/assets/mustache/custom_attribute_definitions/modal_content.mustache
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/utils/string_utils.py
The character "*" should not be allowed in any custom name for roles or attributes
Try to create a custom role or a custom attribute with * in the name
Expected: user should not be able to do that
Actual: roles with invalid names are created
Create new component that prevents entry of the specified characters in the input field. Use this component to prevent usage of "*" in the names of custom role and attribute.
> GGRC-4954 prevent "*" character to be used in custom role names and custom attribute names

- setup.cfg
The config is closest to what we have de-facto now, except for
4-spaces indent.
No formally defined code style in the code base.
On the host machine (or in the container) run:
```bash
pip install yapf
yapf -i src/path/to/a/file.py
```
The file should be formatted in place.
**Note**: our pylint config currently requires two-spaces indents, so it's listed in `yapf` config for now. We are probably going to replace it with four-space indents later.
The config is done by trial-and-error based on readme from https://github.com/google/yapf
`yapf` hasn't been added to the requirements-dev list on purpose: it can (and should, probably) be ran on the host machine and maybe using the developer's preferred IDE.
> QUICK-FIX Add yapf config

- src/ggrc_basic_permissions/__init__.py
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/cycle_task_entry.py
- src/ggrc_workflows/models/task_group.py
- src/ggrc_workflows/models/task_group_object.py
- test/integration/ggrc/fulltext/test_total_reindex.py
Query filtered by any changed object from stub, it takes too much time. 
Try to update any roleable object
Filter stubs and load only roleable models from acl.
> GGRC-5233 Loading acl permissions takes too much time

- src/ggrc_workflows/migrations/versions/20180518133737_a1a399a5cfed_fill_objects_without_revisions.py
**After merge, next steps should be added to deployment doc:**
- Run migration
- Create missed revisions through `$.post("/admin/create_missing_revisions")`
1) Some objects in Workflow scope are without revisions due to some old defects, that should be already fixed, but revisions are not created yet.
2) Comments that are not mapped to any object were created somehow (maybe through import). Notifications were created for such comments, but they cannot be sent, cause mapping is needed for sending it.
**Solution was checked on ggrc_qa, ggrc_test DB dumps from 2018 May 22.**
- db_reset `latest_db_dump` (check for qa and test dumps)
- `select count(*) from objects_without_revisions;` (check that number of objects without revisions != 0). Check change_log tab for any workflow without revision …
> GGRC-5113/4959 Create missed revisions. Delete invalid objects.

- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX restructure test asmts wf to avoid inheriting test methods

- src/ggrc/migrations/versions/20180516132642_5d0fa1d7d55d_add_people_profiles_table.py
- src/ggrc/models/all_models.py
- src/ggrc/models/person.py
- src/ggrc/models/person_profile.py
- src/ggrc/services/resources/person.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/services/__init__.py
- test/integration/ggrc/services/resources/test_person.py
- test/integration/ggrc/services/test_common.py
- test/integration/ggrc/utils/test_user_generator.py
Each "What's New" list has own date. Basing on this date we can check whether the user has seen a certain list. Therefore we need to store this data on the server (to avoid storing it on client which may lead to inconveniences for the users).
Person profile is accessible for GET and PUT via a resource enclosed in the person object, like /api/people/1/profile.
For now, have only "last seen what's new" column in the user preferences table 
A PersonProfile module was created. It has  0 or 1 to  1 relationship to people table. All existing users achieve their profiles during migration process, and profile is created for all new users. If user doesn't have profile, it would be created during GET or PUT profile request.
> GGRC-5018 Store "last seen What's New" date on the backend

- test/integration/ggrc/services/resources/test_person.py
This PR deletes outdated dockstrings and redundant code from code merged via [GGRC-5018](https://github.com/google/ggrc-core/pull/7848) PR
I've just deleted outdated and redundant code
> QUICK-FIX clean person_profile code

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
Unit tests were written  for `assessment-info-pane` component.
> QUICK-FIX Cover assessment-info-pane component with unit tests

- src/ggrc/assets/mustache/controls/info.mustache
We are not going to make a copy of gDrive file, when it is attached to control any more. That's why tooltip need to be updated.
1. Go to any control info pane / page.
2. Assign a folder to a control.
3. Hove over 'Attach' button on control info pane / page.
**Expected result:** No copy will be created. Original files will be added to the destination <object type> folder.
> GGRC-5225 Update tooltip for Attach button for Control

- src/ggrc/assets/mustache/cycle_task_groups/info.mustache
'Edit Cycle Tasks' group is displayed in 3 bb's menu in the Active Cycle tasks tab.
- Open any active workflow
- Go to Active Cycles tab
- Expand Cycle Task Group Info panel
- Click on 3 bb's menu
Actual Result: If user opens Cycle task group info panel, 3 bb's menu is displayed and contains:
- Edit Cycle task group control;
- Get permalink;
- Unmap;
- Delete
Expected Result: If user opens Cycle task group info panel, 3 bb's menu should not be  displayed.
NOTE: if user clicks 'Edit Cycle task group control' in 3 bb's menu, JS error is displayed.
An existing layout for Cycle Task Group's info panel was fixed.
> GGRC-5183 'Edit Cycle Tasks' group is displayed in 3 bb's menu in the Active Cycle tasks tab

- src/ggrc-client/js/components/tree/templates/tree-actions.mustache
- src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
- src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
- src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
- src/ggrc-client/js/components/tree/tree-actions.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/utils/acl-utils.js
- src/ggrc-client/styles/components/tree/_tree-view.scss
- src/ggrc-client/styles/layout/_content.scss
- src/ggrc-client/styles/modules/_import-export.scss
- src/ggrc-client/styles/modules/_tree-header.scss
There're import/export menu items in tree view for Documents and Evidence.
1. Open My Work / All Objects / Assessment object
2. Choose Evidence/Documents tab
**Actual result:** Export Evidence / Import Evidence is present in 3bbs
**Expected result:** Hide 3bbs on Evidence tab as Evidence objects can't be exported / imported.
Move tree actions logic to the separate component and do not display actions for Documents and Evidence.
> GGRC-5145 Hide Export/Import Evidence/Document in tree view

- bin/containers_functions.sh
- bin/jenkins/run_integration_acl
- bin/jenkins/run_integration_ggrc
- bin/jenkins/run_integration_non_ggrc
- bin/run_integration_acl
- bin/run_integration_ggrc
- bin/run_integration_non_ggrc
- docker-compose-testing.yml
- kokoro/ggrc_integration_acl.cfg
- kokoro/ggrc_integration_acl.sh
- kokoro/ggrc_integration_ggrc.cfg
- kokoro/ggrc_integration_ggrc.sh
- kokoro/ggrc_integration_non_ggrc.cfg
- kokoro/ggrc_integration_non_ggrc.sh
- test/appengine/base.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/converters/test_export_snapshots.py
- test/integration/ggrc/converters/test_imported_api_requests.py
Integration tests take too long to run.
Check that the sum of test counts for individual runners is the same as for integration tests and that all still work.
Try running some tests with imports such as:
```bash
nosetests integration.ggrc.converters.test_imported_api_requests -x
```
before and after.
For this split we first had to pull work from https://github.com/google/ggrc-core/pull/7784 because our test runner is currently broken o dev branch (we are unable to run individual tests that contain imports and are outside the ggrc module)
After applying that patch and fixing the issues pointed out in that PR, we could split the integration tests into 3 separate parts.
These parts were chose by ease of splitting and distribution of time taken for each part.
> QUICK-FIX Split integration tests

- src/ggrc/models/import_export.py
- test/integration/ggrc/services/resources/test_converters.py
CanJs is trying to convert high amount of errors and warnings to observable object on import endpoint.
Open import page and check that the query response doesn't contain `results` field.
Remove `results` field from each item retrieved using the `/api/people/${currentUserId}/imports GET` endpoint.
> GGRC-5160 "Uncaught RangeError: Maximum call stack size exceeded" error occurs while opening Import page

- src/ggrc-client/styles/modules/_menu.scss
There is no space between Feedback button and My Tasks. 
Mouse hover My Tasks button.
Add margin-right to `.feedback`.
> QUICK-FIX Add margin to Feedback button

- src/ggrc/converters/handlers/acl.py
- src/ggrc/converters/handlers/handlers.py
- test/integration/ggrc/access_control/test_access_control_role.py
Logged WF admin user can't delete Task Secondary Assignee using "--" key in imported Google sheet. 
1. Log as Admin user and create any WF (Need verification - TRUE)
2. In the Setup tab create a task for task group with filled Task Secondary Assignee
3. Activate WF
4. Export Cycle Task to Google Sheet or csv file
5. Remove Task Secondary Assignee from Cycle Task in Google Sheet or csv using "--"
6. Import Cycle Task
7. In Active Cycles tab open Cycle Task Info panel and look at the Task Secondary Assignee
Expected Result: Task Secondary Assignee's were deleted. 
I've added to multi users fields handler checks  to set "set_empty" flag for non-mandatory fields and to clear them in AC "set_obj_attr" method
> GGRC-5129 WF admin is not able to remove secondary assignee via import 

- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
According to [GGRC-4197](https://github.com/google/ggrc-core/pull/7527) BE should add verified flag to related assessment json. 
Integration test is written to check this flag.
I've just added missing flag to related assessment json.
> GGRC-4789 Send "verified" flag to related assessment json

- src/ggrc/utils/log_event.py
Import failing with the following error: 
Bad Request: Import failed due to server error: working outside of request context.
1. Enable INTEGRATION_SERVICE_URL and set up EXTERNAL_APP_USER. 
2. Create import of standards with admin equal to EXTERNAL_APP_USER (should not be presented in the db)
3. See in the logs the warning about trying to access request context
Handle the exception gracefully since the import run as deferred task and does not have flask request.
> GGRC-5025,GGRC-5242 "BadRequest: 400 Bad Request: Import failed due to server error" occurred while importing 3 Standards

- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/models/document.js
- src/ggrc-client/styles/components/tree/_tree-view.scss
'Map' button is NOT displayed on 'Document' tab on Control page
1. Open a Control page.
2. Go to 'Documents' tab
**Actual result:** No 'Map' button is displayed.
**Expected result:** 'Map' button should be displayed.
Configure map button view for Document.
> GGRC-5226 Display Map button on Documents tab

- src/ggrc/migrations/utils/acr_propagation_document_epic.py
- src/ggrc/migrations/versions/20180531073542_2efe5292b7ac_document_epic_acl_rules_update.py
- src/ggrc_basic_permissions/migrations/versions/20180531073905_f67c32c1ec20_document_epic_acl_rules_update.py
- src/ggrc_basic_permissions/roles/Editor.py
- src/ggrc_risk_assessments/__init__.py
- src/ggrc_risks/migrations/versions/20180531081012_3a7d002f930e_document_epic_acl_rules_update.py
- test/integration/ggrc/access_control/acl_propagation/test_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py
- test/integration/ggrc/access_control/acl_propagation/test_auditors.py
- test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_admin.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_primary_contacts.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_principal_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_contacts.py
- test/integration/ggrc/access_control/acl_propagation/test_program_editors.py
- test/integration/ggrc/access_control/acl_propagation/test_program_managers.py
- test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
- test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
- test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
- test/integration/ggrc/access_control/rbac_factories/__init__.py
- test/integration/ggrc/access_control/rbac_factories/document.py
Global Creator can't see Comments/Documents on objects were he's Primary/Secondary Contacts
Only Global Admin should be able to delete any Document and Evidence object.
Use case 1
1) Assign Global Creator as Primary/Secondary Contacts for any documentable object
2) Login as that user and try to add Document
3) Add comment to that document
Use case 2
Try to delete Document using user with any role except Global Admin
- Update ACR propagation rules tree.  
- Update Document Admin Role
- Update Global roles config.
> GGRC-5189,GGRC-5217,GGRC-5260 document ACL update

- src/ggrc-client/js/models/section.js
The comment in section model is outdated and for some reason was not removed before. Basically it was added for another model (https://github.com/google/ggrc-core/commit/af113e812f3551630aef469f68e76ea5d4035a79#diff-47be79e258ee386b3195939369ecfa04R12).
No testing required.
This comment was added for another model and has no connection with section model. For some reason it was not removed together with SectionBase model. So it's time to remove it.
> QUICK-FIX Remove outdated comment from section model

- src/ggrc/migrations/utils/acr_propagation_document_epic.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_principal_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_one_rank_secondary_assignees.py
> QUICK-FIX Fix code style issues.

- src/ggrc-client/js/apps/business_objects.js
- src/ggrc-client/js/models/issue.js
Map button is not shown on Issues tab on Document page.
1. Create document object
2. Add Issues tab
**Actual result:** Map button is not shown on Issues tab
**Expected result:** Map button should be shown to allows map more issues to the document
Set up default `add_item_view` for `Issue` model.
> GGRC-5236 Display Map button on Issues tab on Document page

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/comment/comment-data-provider.js
- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.mustache
- src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
- src/ggrc-client/js/components/tree/tests/tree-header_spec.js
- src/ggrc-client/js/components/tree/tree-header.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/components/unified-mapper/mapper-results.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc-client/js/plugins/tests/ggrc_query_api_spec.js
- src/ggrc-client/js/plugins/utils/query-api-utils.js
Add default sorting for tasks in Bulk Update pop-up
1. Go to Tasks.
2. Open three dots menu, click Bulk Update.
**Expected result:** 'order_by' is sent in request body to sort by: Due Date, Task Assignee, Title.
Add order_by array to initial CycleTaskGroupObjectTask request.
Change sorting format in Paging model from {sortBy: 'key', sortDirection: 'direction'} to {sort: [{key: 'key', direction: 'direction'}]}.
> GGRC-4240 Set default sorting in Bulk Update

- src/ggrc-client/js/controllers/inner-nav-controller.js
- src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
- src/ggrc/query/custom_operators.py
- test/integration/ggrc/services/test_query/test_relevant.py
Evidence tab on Audit page show all evidences mapped to assessments.
- Create audit, assessments. 
- Map evidence to audit, assessment
- Check evidence tab contains number equals sum of evidence mapped to assessments.
Add related_evidence operator to query API
> GGRC-5047 Evidence tab on Audit page show all evidences mapped to assessments

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/custom-attributes/custom-attributes.mustache
- src/ggrc-client/js/components/gca-controls/gca-controls.mustache
- src/ggrc-client/js/components/object-popover/related-assessment-popover.mustache
- src/ggrc-client/styles/components/custom-attributes/_custom-attributes.scss
`extraClass` helper is registered locally in `assessment-info-pane` component but not used in it. Instead, `extraClass` helper is found in other component's templates, where it shouldn't work.
Remove `extraClass` helper from `info-pane.js` and from all templates that are not related to info-pane.
Add `custrom-attribute-{{type}}` css class instead.
> QUICK-FIX Remove unused helper extraClass

- src/ggrc-client/js/models/cycle_models.js
- src/ggrc-client/js/tracker/actions.js
Covered adding a comment for CycleTask scenario with Google Analytics Timing API
> QUICK-FIX Cover adding a comment for CycleTask by Google Analytics

- bin/jenkins/run_integration
Now that ggrc_integration tests are no longer required for merging of PRs, we can disable them to speed things up.
The test scrip remains because kokoro is still set up to run it. We will do additional cleanup after kokoro is updated.
Check that integration tests on this PR do not take more than 1 minute
Remove the part that runs integration test.
> QUICK-FIX Disable deprecated integration test runner

- src/ggrc/fulltext/mixin.py
- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/fulltext/sql.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc/models/model_factory.py
On index procedure created many unused and non required instances. 
Try to run reindex for current object (via update or create)
Run reindex for all object via reindex all. 
Stop create Record instances on record generation procedure. Instead of creation useless instances create records via bulk creation over sending list of dicts.
> GGRC-5207 Create fewer objects during record creation

- src/ggrc-client/styles/components/release-notes/_release-notes.scss
Font of modal header and font of version block not correspond to requirements.
1) Open "What's new" modal from header menu.
2) Look at the fonts.
> GGRC-5200 Fix font color for "What's new"

- src/ggrc/models/document.py
- src/ggrc/models/evidence.py
1. Create evidence object with type URL
2. Open this object
3. Choose Changelog tab
**Actual result:** There is a line with name Attachment and value of url. This looks misleading
**Expected result:** Link would be better name for this line
> GGRC-5154 Rename Attachment to Link in evidence change log

- src/ggrc/assets/mustache/assessment_templates/attribute_field.mustache
- src/ggrc/assets/mustache/assessment_templates/modal_content.mustache
'Evidence URL Required' column is not displayed between 'Evidence file required' and 'Comment required' columns in Add/Edit Assessment template popup
1) Open Assessment template widget on Audit page
2) Click on 'Create' button and open 'New Assessment template' modal
3) Look on the header of 'Custom Attributes' table
> GGRC-5053 Change order of required items in dropdown LCA

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/page/modal/create_new_person.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/widget_base.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/lib/service/admin_webui_service.py
- test/selenium/src/lib/url.py
- test/selenium/src/tests/test_admin_dashboard_page.py
> QUICK-FIX Add test create new person w no role from administration

- src/ggrc/fulltext/attributes.py
- src/ggrc/query/custom_operators.py
- src/ggrc_workflows/models/workflow.py
- test/integration/ggrc_workflows/models/test_workflow.py
* Allow user to filter Workflows by `repeat`.
* Implement backend part for sort Workflows by `repeat`.
For example, write this sentence `repeat = "every 2 months"` in filter query for Workflows.
* Remove `__sort__` attribute from fulltext search.
* Add attribute with custom ordering.
* Add tests for check this functionality.
> GGRC-3079 Show repeat on tree view and allow user to filter workflows by repeat

- src/ggrc/converters/handlers/snapshot_instance_column_handler.py
Snapshot column handler loads all related snapshots to audit on import each asmt. 
try to import asmt with mapping snapshot to it and related audit has about 2000 mapped snapshots.
Load only required snapshots during import specific row.
> GGRC-5314 Load only required items on SnapshotColumnHandler

- src/ggrc-client/js/apps/risk_assessments.js
- src/ggrc-client/js/apps/risks.js
- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/models/mappers/mapper-helpers.js
- src/ggrc-client/js/models/mappers/mappings-ggrc.js
- src/ggrc-client/js/models/mappers/mappings.js
GGRC FE has global utils, which can be switched to "import/export" syntax. It'll help us to reduce count of global data.
Global `GGRC.MapperHelpers` object was switched to "import/export" syntax.
`all_local_results` method was introduced by these changes: https://github.com/google/ggrc-core/commit/e482d016116565cbeb0c28bcd427b29ce995619a#diff-34e0a99f32a01d381b83348a38d25cb3
> QUICK-FIX Use "import/export" syntax for GGRC.MapperHelpers utils

- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/entrypoints/dashboard/index.js
FEEDBACK button is broken on Export/Import pages.
1. Open Import/Export page
*To show "Feedback" button, you should override GGRC.config.CREATE_ISSUE_URL and GGRC.config.CREATE_ISSUE_BUTTON_NAME fields. For example, you can open feedback-link.js and set fake data for these fields before viewModel initializing.*
2. Look at the Feedback button next to Global Search
Actual Result: FEEDBACK button is broken on Export/Import pages.
Expected Result: Improve Feedback button on Export/Import pages
`tooltip-content` component wasn't initialized. It was included into `page-header` component.
> GGRC-5241 FEEDBACK button is broken on Export/Import pages

- src/ggrc/converters/errors.py
Both for non-existed in GGRC objects and objects that can't be imported show the following message: `Unknown object type '<object type>'`. Need to change this message to `Object type '<object type from imported spreadsheet>' doesn't exist or can't be imported.`
1. Create any workflow.
2. Add a task to task group and activate workflow.
3. Export cycle task group to google sheet and update it.
4. Import cycle task group.
5. See warning message.
Change message.
> GGRC-4353 Make a proper wording of the error that user is not able to update/delete cycle task group

- src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.mustache
- src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
As Questionnaire column contains only link and not sortable, sorting should be disabled. 
Sorting is disabled on dashboard and all objects pages but is not disabled in Global Search.
> GGRC-4709 Disable sorting for Questionnairy global search

- kokoro/deploy_ggrc_perf.cfg
- kokoro/deploy_ggrc_perf.sh
- kokoro/deploy_ggrc_test.cfg
- kokoro/deploy_ggrc_test.sh
Currently deployment to test and perf instances are manual. This will help to automate the process.
The configs in this pull requests are similar to other deployment configs (eg : deploy_ggrc_qa.cfg, deploy_ggrc_qa.sh). This can be tested once we have proper settings file in GCS bucket and required configs are checked in into google3.
Note : If merged, the changes in this PR will not affect any other process.
Once this PR is merged and required settings file are added into GCS bucket, deployment to test and perf instance can be done from within kokoro UI. This will eliminate lot of manual work.
> QUICK-FIX Add kokoro deployment configs

- src/ggrc/templates/layouts/base.haml
`GGRC.Settings` is unused within the app. We should remove it.
`GGRC.Settings` was removed.
It was created (here)[https://github.com/google/ggrc-core/pull/3109/files#diff-2c397c3a3c34b68fd31028f1b78601aa].
> QUICK-FIX Remove unused GGRC.Settings scope

- src/ggrc/converters/handlers/assessment_template.py
- src/ggrc/models/hooks/assessment.py
Creation cads for newly create asmt from related asmt template takes too long cause in has commit in each column handling. 
Create new asmt via import with related asm tmpl that has al least 5 cads. And try to setup values for that cads.  
1) reuse cad generation for newly created asm from api call handler hook.
2) stop make commit in each asmt template column handler, flush should be enough
> GGRC-5324 Speed up import Asmt with related Template 

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/converters/handlers/handlers.py
- src/ggrc/converters/import_helper.py
- test/unit/ggrc/converters/test_import_helpers.py
Part of #7978 with no breaking changes.
Check that import/export tests still pass.
#7978 up until the first breaking commit.
> GGRC-5374 Cleanup of block processing logic in import

- src/ggrc/fulltext/mysql.py
- src/ggrc/rbac/permissions.py
- src/ggrc/services/common.py
- src/ggrc/services/search.py
Since we don't use permission_model anywhere on the frontend anymore we
can remove the support for it and the dead code on the backend.
Check RBAC on LHN, try to find any place that might use this code that I could have missed.
Remove permission_model argument from all functions and the dead code when that is not set.
> GGRC-5373 Remove permission_model argument

- test/integration/ggrc_workflows/test_acl_propagation.py
integration tests with invalid assertions show errors
Run:
```bash
nosetests integration.ggrc_workflows.test_acl_propagation:TestWorkflowAclPropagation.test_async_role_propagation
```
and check the console output
The test for concurrency was meant to check that acl propagation does
not cause any problems, but we forgot about the actual etags that do not
match on different concurrent requests. So it is valid that some of the
requests might fail, but we still check that the end result of the
requests is correct.
The error hidden in this test started to appear after we added a strict
unique constraint on acl table - meaning no columns in the constraint
can be nullable. The error is triggered in the main commit loop before
the propagation even starts.
We must still fix concurrency issues …
> GGRC-5372 Remove invalid assertion from tests

- src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
- src/ggrc-client/js/ggrc_base.js
For `GGRC.default_widgets` variable isn't assigned any *useful* data within the app - it's always an empty array. There are no reasons to hold it in the app.
`GGRC.default_widgets` was removed.
This variable was introduced by this commit - https://github.com/google/ggrc-core/commit/5e7ea60e651c3c47fb514903841fafbc1ceebbf9.
> QUICK-FIX Remove redundant GGRC.default_widgets variable

- src/ggrc-client/js/models/assessment.js
- src/ggrc-client/js/models/audit_models.js
- src/ggrc-client/js/models/business_object_models.js
- src/ggrc-client/js/models/control.js
- src/ggrc-client/js/models/directive_models.js
- src/ggrc-client/js/models/document.js
- src/ggrc-client/js/models/evidence.js
- src/ggrc-client/js/models/issue.js
- src/ggrc-client/js/models/risk.js
- src/ggrc-client/js/models/section.js
- src/ggrc-client/js/models/simple_models.js
- src/ggrc-client/js/models/system.js
- src/ggrc-client/js/models/task_group.js
- src/ggrc-client/js/models/threat.js
- src/ggrc-client/js/models/workflow.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
- src/ggrc-client/js_specs/mustache_helpers/get_default_attr_value_spec.js
**Need to be implemented:**
- Need to add all searchable attributes into attributes field in 'Advanced Search' and 'Global Search' for all typed of object (the main use case is  'Description' attribute for control object type) 
- Need to show all 'rich text' attributes as column in tree view (same as 'Last Comment' for Assessment) 
 
**Searchable attributes:**
- Description; 
- Notes; 
- Assessment Procedure; 
- Remediation Plan; 
- Task Summary; 
- GCA of type 'Rich Text' / 'Text'; 
Note: Remove sorting in tree view for rich text attributes, as far as sorting won't work correctly because of tags.
1. Add corresponding fields to models.
2. Extend get_default_attr_value helper with rich text attributes.
3. Disable sorting in tree view for rich text attributes.
> GGRC-3388 Include searchable attributes in advanced/global/filtering search and in tree view

- docs/source/backend/access_control.rst
- docs/source/backend/adding_new_object.rst
- docs/source/backend/advanced_query_api.rst
- docs/source/backend/object_manipulation.rst
- docs/source/backend/overview.rst
- src/docbuilder/descriptors/service.py
Context usage is now deprecated and is being removed, we should also make sure our docs don't reference contexts anywhere. This will also make it easier to grep for context and see if we missed any places in the codebase.
Check the docs.
Removal of all context references from the backend code.
> GGRC-5318 Remove context references from our documentation

- bin/run_integration_acl
- bin/run_integration_ggrc
- bin/run_integration_non_ggrc
- src/ggrc/settings/testing.py
We should allow developers to run acl and other integration tests in parallel locally to speed up development time.
Run commands:
run_integration_non_ggrc
run_integration_ggrc
run_integration_acl
in parallel and check test results.
We just added a unique named database for every test runner.
Note:
Running all tests at the same time, took just slightly over half hour to run all tests:
```
Ran 2000 tests in 1865.939s  # acl
Ran 1634 tests in 1995.156s  # ggrc 
Ran 652 tests in 1251.514s  # non ggrc
```
> QUICK-FIX Split databases for test runners

- src/ggrc/assets/mustache/access_control_roles/modal_content.mustache
Only Global Admin should be able to delete any Document and Evidence object.
On Administration Dashboard need to hide / disable 'Delete' checkbox
Disable checkbox for Evidence and Document types.
> GGRC-5231 Disallow all global roles except Global Admin to delete Document and Evidence objects

- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/category.js
- src/ggrc-client/js/models/mixins.js
Proposal value is shown as [Deleted] in Change Proposals tab after making a proposal in Categories for Control
1. Create a control with a category (specify it at time of object creation)
2. Propose a change
**Actual result:** "Proposed Value" is set to "ControlCategory ID: 49" (DELETED)
**Expected Result:** "Proposed Value" is set to category name
1. Have a control with categories
2. Propose a categories change
**Actual result:** Current value column is empty for Assertions and Categories
**Expected result:** Current value column should contain current Assertions and Categories values.
There couple issues fixed in this PR.
1. Issue with incorrect displaying Control name ("ControlCategory ID: 49" (DELETED)). 
Instance should be restored after creating proposal. During restoring CanJs …
> GGRC-4777 Display correctly categories for control in proposal

- src/ggrc-client/js/models/workflow.js
Show repeat on tree view and allow user to filter workflows by repeat.
_ACCEPTANCE CRITERIA_
AC1. Show 'Repeat' column on Workflow tab for 'All Objects' page.
AC2. Show 'Repeat' column on Workflow tab for '&lt;object&gt;' page.
AC3. Allow user to filter Workflows by repeat.
Exact filtering should be performed by inscriptions on UI: repeat = 'every 2 months';
AC4. Allow user to sort Workflows by repeat. Sorting should be preformed by groups:
Ascending order:
- off; 
- weekdays; 
- weeks; 
- months. 
Descending order:
- months; 
- weeks; 
- weekdays; 
- off. 
Add corresponding field to workflow model.
> GGRC-3037 Show repeat on tree view and allow user to filter workflows by repeat

- src/ggrc/converters/handlers/document.py
- src/ggrc/converters/handlers/evidence.py
- test/integration/ggrc/converters/test_import_assessments.py
- test/integration/ggrc/converters/test_import_controls.py
Duplicate evidence.url / document.reference_url is created via import.
1. Create an object
2. Add an evidence / document to it
3. Import this object with the same evidence / document
Actual result: Object continues to be mapped to the old evidence / document (that's correct). But a new unmapped evidence / document is created as well.
Expected result: Duplicate evidence / document object shouldn't be created
Updated document/evidence handlers to check if imported link already exists.
Note: Decrease import performance a little because for each object with document/evidence we need to check if such objects already exists.
obj.evidences_url/obj.documents_reference_url -> leads to extra SQL call (0.0019 sec / 0.000034 sec at qa dump with 6k evidence)
> GGRC-5351 Duplicate evidence / document is created when import

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- test/integration/ggrc/converters/test_base_block.py
Import/export functionality has to be splitted.
Check that import/export doesn't cause any errors.
BaseConverter, RowConverter and BlockConverter was splitted to separate classes for import and export.
> GGRC-5266 Split import/export functionality

- src/ggrc/fulltext/sql.py
- test/integration/ggrc/models/model_factory.py
Remove one function that is only used for tests
Do basic checks that indexing still works
Remove obsolete function and write explicit commands in the test factories
> QUICK-FIX Remove dead code

- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
- src/ggrc-client/js/models/audit_models.js
- src/ggrc-client/js/models/control.js
- src/ggrc-client/js/models/join_models.js
- src/ggrc-client/js/models/mappers/mappings-ggrc.js
Remove AuditObject from the frontend
> GGRC-837 Remove AuditObject model

- src/ggrc/data_platform/computed_attributes.py
- src/ggrc/fulltext/mysql.py
- src/ggrc/fulltext/sql.py
- src/ggrc/migrations/versions/20180619143546_2bec1dfcaec0_remove_contetx_from_fulltext_table.py
- src/ggrc/query/builder.py
- src/ggrc/rbac/__init__.py
- src/ggrc/services/common.py
- src/ggrc/snapshotter/indexer.py
We should not be relying on contexts for permissions in the fulltext search
check rbac on any search/query api request:
- lhn
- lhn filters
- autocomplete
- special autocomplete in section creation
- search filters on admin tabs (people and other tabs there)
- counts on my work and all objects
- tree views.
I have removed the context from the full text table and made sure that the permission query on it does not use the context column anymore.
> GGRC-5385 Remove contexts from fulltext

- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/models/business_object_models.js
- src/ggrc/assets/mustache/dashboard/lhn.mustache
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/page/lhn.py
Move 'OrgGroup' object into 'Scope' (previously 'Assets/Business') list.
- in LHN;
- 'Object type' dropdown on unified mapper, global search, generate assessment pop-ups;
OrgGroup page - header should be green as for all other scoping objects (previously 'Assets/Business')
See commits.
**Note:** on moment when PR created 'Assets/Business' is not renamed into 'Scope'  [GGRC-5116](https://github.com/google/ggrc-core/pull/7914) , still it doesn't block this PR.
> GGRC-5249 Move OrgGroup into scope objects

- src/ggrc/app.py
- src/ggrc/automapper/__init__.py
- src/ggrc/automapper/rules.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/handlers/boolean.py
- src/ggrc/converters/handlers/document.py
- src/ggrc/converters/handlers/evidence.py
- src/ggrc/fulltext/attributes.py
- src/ggrc/gdrive/__init__.py
- src/ggrc/gdrive/file_actions.py
- src/ggrc/migrations/utils/__init__.py
- src/ggrc/migrations/versions/20161117114904_142272c4a0b6_migrate_audits_for_snapshots.py
- src/ggrc/migrations/versions/20161220161315_275cd0dcaea_migrate_assessments_issues_data.py
- src/ggrc/models/cache.py
- src/ggrc/snapshotter/__init__.py
- src/ggrc/snapshotter/helpers.py
- src/ggrc/utils/revisions.py
- src/ggrc/views/__init__.py
We use too many pylint exceptions and they are often used in too broad scope. 
Here we just remove the redundant exceptions meant for logger variable which is now allowed in our pylintrc file.
Check that the code changes don't actually affect any functionality
Remove invalid name warnings on some places and fix some invalid names.
> QUICK-FIX Pylint cleanup

- docs/source/contributing/git/reviewing_pull_requests.rst
`needs work` description doesn't state that PR author should remove it after introducing required changes.
Check the https://github.com/google/ggrc-core/blob/dev/docs/source/contributing/git/reviewing_pull_requests.rst
> DOCS Update "needs work" label description

- src/ggrc-client/js/components/tree/templates/tree-widget-container.mustache
- src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js
- src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js
- src/ggrc-client/js/components/tree/tree-status-filter.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/models/display_prefs.js
- src/ggrc-client/js/modules/widget_descriptor.js
- src/ggrc-client/js/plugins/utils/current-page-utils.js
- src/ggrc-client/js/plugins/utils/object-versions-utils.js
- src/ggrc-client/js/plugins/utils/state-utils.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
Treeview freezes after apply specific filter for Assessments
Steps:
1. Open All Objects page on default (Regulation) tab
2. Go to Assessment tab
3. Apply status filter with In Progress, Not Started and Rework Needed statuses
Actual result:
JS Error: Maximum call stack size exceeded
Request to Query API with multiple parameters (~2000)
App freezes
Expected result: No error
The issue caused by specific logic: if we select all statuses - route should be clear.
Since we have status filter for each tab, there is a conflict when on first tab all states are selected (3 states of 3), but on second tab filters are selected partially (3 of 5). In this case first tab will clear filters, but second tab will try to recover them :)
There is fault in tree-view that does not provide current widgetId …
> GGRC-5312 Handle status route events only for current widget

- src/ggrc-client/js/components/add-tab-button/add-tab-button.js
Remove Evidence from Add tab list for Assessment
1. Create assessment without evidence
2. Click "Add tab"
**Actual result:** Evidence is listed in list of tabs to add
**Expected result:** Evidence should not be listed as a user can't use it to add an evidence
Update config for `add-tab-button` component.
> GGRC-5108 Hide Evidence option for Add Tab button for Assessment

- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/components/page-header/page-header.mustache
- src/ggrc/templates/assessments_view/index.haml
Links missing from My Assessments page.
1. Open 'My Assessments' page
**Actual result:** Header links are missing.
**Expected result:** Header should be identical throughout the UI.
Use the same header component as on another pages.
> GGRC-4073 Add links on My Assessments page header

- src/ggrc/converters/base_block.py
- src/ggrc_basic_permissions/converters/handlers.py
We must remove all code referring to legacy roles, since dead code might still be accessed and cause invalid bugs.
This ticket handles removal of legacy roles from import/export code.
Check that there is no code for accessing old roles in any import/export module anymore.
Verify that import/export of the removed roles (that are now in ACL) still work.
Just deletion of obsolete code.
Note: I have verified the export code, but I can not get imports working due to gdrive even on dev branch. I have checke my settings and they have not changed since the last time this worked. Gdrive auth goes through and the picker works, but then the backend fails to receive selected files and it might be a network issue.
> GGRC-5404 Role import cleanup

- src/ggrc/converters/base_block.py
- src/ggrc/migrations/versions/20180624164209_7a8eaf2c9b75_remove_context_from_events.py
- src/ggrc/models/event.py
- src/ggrc/services/common.py
- src/ggrc/utils/log_event.py
- src/ggrc_basic_permissions/converters/handlers.py
- test/integration/ggrc/models/model_factory.py
- test/integration/ggrc_workflows/notifications/test_data_handler.py
We must remove contexts from our API events table. This is part of the effort to remove all contexts from our app.
Check events log and its contents on admin page.
This PR also removed context checks in the rest API, so please check for possible rbac regressions when fetching various objects.
I believe possible regressions are only users not being able to see things, and not that they would see too much. so chekc audit program comments and workflow comments and such things.
Remove context checks from API requests, that prevented any object without context to be returned. and remove contexts from events table.
> GGRC-5405 Remove event context

- src/ggrc/migrations/utils/__init__.py
- src/ggrc/migrations/versions/20180529141537_8ffc6d30dba2_remove_unmapped_documents.py
- test/selenium/src/tests/test_admin_dashboard_page.py
In the current implementation when the user clicks 'delete' icon near a URL in inline edit, we don't remove the URL object, but instead just unmap it. These orphan objects don't have any business value as they've been deleted by the users, so they can be safely removed.
Run migration and check that:
- documents w/o mapping and updated_at < 2018-06-12 (1.12 release) are removed.
- for removed documents new 'deleted' revision is created with last revision's content (if exists).
Implemented migration script.
> GGRC-4319 Remove orphan (with no mapped objects) Documents.

- src/ggrc-client/js/components/comment/mapped-comments.mustache
- src/ggrc-client/js/components/object-list/object-list.js
- src/ggrc-client/js/components/object-list/object-list.mustache
- src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals.mustache
- src/ggrc-client/js/components/related-objects/related-issues.mustache
- src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions.mustache
- src/ggrc-client/js/components/related-objects/templates/related-assessments.mustache
- src/ggrc-client/js/components/unified-mapper/templates/mapper-results.mustache
- src/ggrc-client/js/components/workflow/task-list/templates/task-list.mustache
- src/ggrc-client/styles/components/grid-data/_grid-data.scss
- src/ggrc-client/styles/components/object-history/_object-history.scss
- src/ggrc-client/styles/components/object-list/_object-list.scss
Improve spinner for pagination on TG.
1. Open Workflow with task group;
2. Expand TG;
3. Using pagination control follow to the next page;
4. Look at the spinner.
Expected result: Improved spinner for pagination on TG.
Provided solution was discussed with UX team.
> GGRC-5036 Improve spinner for pagination on TG

- src/ggrc/snapshotter/indexer.py
- test/integration/ggrc/models/test_snapshot.py
Search for snapshots by reference url doesn't work
2. Create a control (or some snapshottable object) with a reference url. Map it to program
3. Create audit under program
4. Open this audit. Open Controls snapshot tab
5. Filter by valid Reference url
Expected result: Snapshot should be found
Updated snapshot indexer to properly index reference url
> GGRC-5271 Search for snapshots by reference url doesn't work

- src/ggrc/migrations/versions/20180613132524_e1256da10630_remove_acl_w_o_corresponding_documents.py
When migrating documents to evidence ACL wasn't cleaned up.
We need to remove all Document ACL without corresponding documents
It impossible to check through UI
Reviewer need to write sql query.
Implemented migration.
> GGRC-5313 Remove Document ACL w/o corresponding documents.

- docs/source/backend/adding_new_object.rst
- src/ggrc-client/js/apps/business_objects.js
- src/ggrc-client/js/apps/risk_assessments.js
- src/ggrc-client/js/apps/risks.js
- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc-client/js/components/assessment/assessment-object-type-dropdown.js
- src/ggrc-client/js/components/assessment/tests/assessment-object-type-dropdown_spec.js
- src/ggrc-client/js/components/import-export/relevant-filter.js
- src/ggrc-client/js/components/mapped-counter/mapped-counter.js
- src/ggrc-client/js/components/modal-connector.js
- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js
- src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js
- src/ggrc-client/js/components/object-mapper/object-mapper.js
- src/ggrc-client/js/components/object-search/object-search.js
- src/ggrc-client/js/components/object-search/tests/object-search_spec.js
- src/ggrc-client/js/components/view-models/object-operations-base-vm.js
- src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mappers/mappings-ggrc.js
- src/ggrc-client/js/models/mappers/mappings.js
- src/ggrc-client/js/models/mappers/tests/mappings_spec.js
- src/ggrc-client/js/plugins/autocomplete.js
- src/ggrc-client/js/plugins/ggrc_utils.js
- src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
- src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
- src/ggrc-client/js/plugins/utils/current-page-utils.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
GGRC FE has global utils, which can be switched to "import/export" syntax. It'll help us to reduce count of global data.
Global `GGRC.Mappings` was switched to "import/export" syntax.
> GGRC-5407 Use import/export for GGRC.Mappings

- src/ggrc-client/js/models/metric.js
- src/ggrc-client/styles/components/tree/_tree-view.scss
Add searchable attributes from [GGRC-3388](https://github.com/google/ggrc-core/pull/7905) to Metrics object.
**Searchable attributes:**
- Description;
- Notes;
- Assessment Procedure;
- GCA of type 'Rich Text' / 'Text';
Note: Remove sorting in tree view for rich text attributes, as far as sorting won't work correctly because of tags.
Add corresponding fields to Metric model.
> GGRC-5421 Include searchable attributes for Metric object

- src/ggrc/views/converters.py
Hard to analyze failing import/export tests.
1. Add a "raise" statement in any part of import functionality covered by an integration test.
2. Run the integration test.
Expected result: the exception is printed with stack trace.
Actual result: "import failed due to server error" stub is returned.
Re-raise the exception on the top level of import and export logic if `TESTING` flag is set.
> QUICK-FIX Don't mask exceptions in import/export tests

- docs/source/backend/adding_new_object.rst
- docs/source/frontend/modals.rst
- src/ggrc-client/js/apps/risks.js
- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/ggrc_base.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/ggrc_utils.js
GGRC FE has global utils, which can be switched to "import/export" syntax. It'll help us to reduce count of global data.
Global `GGRC.register_hook` method and `GGRC.hooks` object was switched to "import/export" syntax.
> QUICK-FIX Use "import/export" syntax for GGRC.register_hook/GGRC.hooks

- src/ggrc-client/js/models/cycle_models.js
Add searchable attributes from [GGRC-3388](https://github.com/google/ggrc-core/pull/7905) to Cycle Task object.
Searchable attributes:
**Task Description**
Note: Remove sorting in tree view for rich text attributes, as far as sorting won't work correctly because of tags.
Add corresponding fields to `CycleTaskGroupObjectTask` model.
> GGRC-5256 Make Task Description searchable

- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/components/workflow/end_cycle.js
- src/ggrc-client/js/controllers/tree/tree-view.js
500 error when end workflow cycle.
Steps:
1. Login as admin
2. Create a workflow with one task
3. Activate this workflow
4. Click End Cycle button
Actual result: A call to /api/cycle_task_group_object_tasks takes 4 minutes. After that it returns 500 error.
Expected result: No 500 error.
After investigation of the failed request was decided to remove it, because it loads data, which are unnecessary.
Unneeded request was removed.
Unused code was removed:
Just for help  - changes from these commits were removed: https://github.com/google/ggrc-core/commit/38162e2e2af12e8d4422ed3bf0113ee9370b0f4a, https://github.com/google/ggrc-core/commit/f812e04a2946b8190b543c7998b5cd3defdfa51c
> GGRC-5342 500 error when end workflow cycle

- test/selenium/src/tests/test_snapshots.py
Mark test_destructive_search_unified_mapper_and_check_mapping
with skip tag  with due to failing in dev branch needs investigation.
> QUICK-FIX Add skip tag to test which needs research.

- docs/source/contributing/git/reviewing_pull_requests.rst
This pull request contains description for the new `complex` label.
Not testing required.
Add new `complex` label to `Using GitHub labels` section in `reviewing_pull_requests.rst`.
> DOCS Add complex label to docs

- src/ggrc-client/js/mustache_helper.js
- src/ggrc/assets/mustache/audits/dropdown_menu.mustache
- src/ggrc/assets/mustache/dashboard/info/info.mustache
- src/ggrc/assets/mustache/dashboard/widgets.mustache
`system_role` helper usage for audit dropdown can be replaced on `current_user_is_admin`.
In other places it can be removes as only users with global role have access to the system.
> QUICK-FIX Remove  system_role mustache helper

- src/ggrc/bootstrap.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/fulltext/listeners.py
- src/ggrc/fulltext/mysql.py
- test/integration/ggrc/__init__.py
ACL propagation takes place after each row is processed, and it adds up 1 second for each row's processing time.
Run import with huge amount of assessments. 
Do not start pre and post commit hooks on each row and run it only once after commit.
> GGRC-5490 Speedup import/export after splitting it into row by row import

- src/ggrc-client/js/components/unified-mapper/mapper-results-item-attrs.js
- src/ggrc-client/js/components/unified-mapper/mapper-results-item-details.js
- src/ggrc-client/js/components/unified-mapper/mapper-results-item-status.js
- src/ggrc-client/js/components/unified-mapper/mapper-results-item.js
- src/ggrc-client/js/components/unified-mapper/mapper-results-items-header.js
- src/ggrc-client/js/components/unified-mapper/mapper-results.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-attrs_spec.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-details_spec.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results-items-header_spec.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
`GGRC.Components` provides additional wrapper which potentially can be removed and `can.Component` used instead of it. In the scope of this ticket `IIFE` should be removed and `export` should be used instead of it.
> GGRC-5473 Use can.Component instead GGRC.Components for mapper-results components

- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/modules/widget_list.js
500 error while filtering cycle tasks by state.
**GGRC-5471**
Precondition:
- have a task on My tasks tab
1. Open My tasks tab
2. Filter by any state via dropdown filter
*Actual Result:* 500 error is displayed and 'There was an error' in UI
*Expected Result:* no errors should be shown, filter should be applied.
**GGRC-5424**
1. Log as Global Admin user.
2. Open All Objects page
3. Look at the 'Workflow' tab: is missed
**Actual Result:** 'Workflow' tab is missed on All objects page
**Expected Result:** User with read/edit rights should be able to see 'Workflow' tab on All objects page
The issues were occurred due to these [changes](https://github.com/google/ggrc-core/pull/7989).
> GGRC-5471/5424 500 error while filtering cycle tasks by state

- src/ggrc-client/styles/components/action-button/_action-button.scss
- src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
GGRC-5464
Decrease css rule strength for buttons on related-assessment page.
> GGRC-5464 Decrease RA button rule strength

- src/ggrc/models/hooks/acl/__init__.py
- test/integration/ggrc/models/hooks/acl/test_propagation.py
Propagation for Program Editors or Readers didn't propagate to Asmt instance. Same story for Audit. 
1. Log as admin user
2. Create a program, control, audit
3. Assign Global Creator user as Program Editor
4. Create Assessment using template attached (verifier/assignee/creator should not contain creator user)
5. Log as Global Creator user (globcreator@gmail.com(engage007)
6. Open Audit page and open Assessment tab
Actual Result: Global Creator as Program editor doesn't see assessment created via import
Expected Result: Global Creator as Program editor should see assessment created via import
Add only non empty ids for propagation into flask g.
> GGRC-5510 1.14.2 regression: for imported Assessments no Audit ACL gets propagated

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/object-list/object-list.mustache
- src/ggrc-client/js/components/people/templates/people-group-modal.mustache
- src/ggrc-client/styles/components/people-group/_people-group.scss
'Uncaught TypeError: Cannot read property 'appendChild' of null' is displayed while adding evidence url
1. Open any audit page with control snapshot
2. Create Assessment template with dropdown lca, with option evidence url = required
3. Generate asmt based on control snapshot and assessment template
4. Open Assessment info panel
5. Add evidence url to dropdown lca and close the popup
6. Add evidence url on info panel: error is shown up
*Actual Result:* If user added evidence url via dropdown lca and then added evidence url via add button on info panel, the error is displayed
*Expected Result:* no errors should be shown up when user adds evidence url
1) Revert [PR](https://github.com/google/ggrc-core/pull/8086) created by @Klim711, because it does not fix root cause.
2) …
> GGRC-5523 Fix object-list component

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/tests/test_snapshots.py
> QUICK-FIX Add waiting until mapper spinner not present.

- src/ggrc-client/js/components/add-object-button/add-object-button.js
- src/ggrc-client/js/components/add-tab-button/add-tab-button.js
- src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
- src/ggrc-client/js/components/assessment/attach-button.js
- src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
- src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
- src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js
- src/ggrc-client/js/components/info-pin-buttons/info-pin-buttons.js
- src/ggrc-client/js/components/prev-next-buttons/prev-next-buttons.js
- src/ggrc-client/js/components/prev-next-buttons/tests/prev-next-buttons_spec.js
- src/ggrc-client/js/components/view-object-buttons/view-object-buttons.js
GGRC.Components provides additional wrapper which potentially can be removed and can.Component used instead of it. In the scope of this ticket IIFE should be removed and export should be used instead of it.
> GGRC-5480 Replace GGRC.Component on can.Component for buttons components

- src/ggrc/settings/default.py
Bump version from 1.15.0-Strawberry to 1.15.1-Strawberry.
> Bump version to 1.15.1-Strawberry

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/datepicker/datepicker.js
- src/ggrc-client/js/components/form/fields/checkbox-form-field.js
- src/ggrc-client/js/components/form/fields/checkbox-form-field.mustache
- src/ggrc-client/js/components/form/fields/date-form-field.js
- src/ggrc-client/js/components/form/fields/date-form-field.mustache
- src/ggrc-client/js/components/form/fields/dropdown-form-field.js
- src/ggrc-client/js/components/form/fields/dropdown-form-field.mustache
- src/ggrc-client/js/components/form/fields/person-form-field.js
- src/ggrc-client/js/components/form/fields/person-form-field.mustache
- src/ggrc-client/js/components/form/fields/rich-text-form-field.js
- src/ggrc-client/js/components/form/fields/rich-text-form-field.mustache
- src/ggrc-client/js/components/form/fields/templates/text-form-field.mustache
- src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/dropdown-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/person-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/text-form-field_spec.js
- src/ggrc-client/js/components/form/fields/text-form-field.js
- src/ggrc-client/js/components/rich_text/rich_text.js
- src/ggrc-client/js/plugins/utils/deferred-transaction-utils.js
LCAs are not reinited after saving on newly opened info-pane
1. Have an Assessment with any LCA
2. Navigate to assessments Info panel and fill CA value 
3. Close Info pane while changes are saving
4. Open Info panel once again and look at the CA value
_Actual Result_: CA value displayed with latency on Assessment info pane if close Info pane while data saving and open it once again
_Expected Result_: TBD
Reinit LCA after 'instance updated' event
> GGRC-4799 LCA value is displayed with latency on Assessment info panel

- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Remove xfail tag from test url dropdown.

- src/ggrc/notifications/data_handlers.py
- src/ggrc/notifications/job_emails.py
- src/ggrc/views/converters.py
- test/unit/ggrc/notification/test_job_emails.py
AC1. Update an email for successful export in accordance with mock-ups.
AC2. Show a warning, if user comes from an export successful email to `GGRC` and the file with exported results is already removed.
1. User goes to `Export` page and run an export.
2. System successfully completed an export.
3. System send an email about successfully completed export to a user.
4. User downloads / writes to sheets / removes the export generated file.
5. User goes to an email from step (3) and clicks `Open` button.
Change url in notification.
> GGRC-5092 Export link doesn't take me to my download

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/workflow.py
- src/ggrc_workflows/views/__init__.py
The backlog workflows were removed in scope of pr #7773 for reducing
loading for permissions. The check at the time proved that no backlog
workflows exist in any prod or dev environment so permission checks for
those were removed. Having an endpoint that creates such a workflow is
now considered a regression so it has to be removed.
Do basic sanity checks for workflows and check that no references to backlog workflows remain in our app.
Removal of obsolete code and nothing else.
> QUICK-FIX Remove obsolete backlog workflow endpoint

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/components/object-mapper/object-mapper.js
- src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc/assets/mustache/base_objects/autocomplete_result.mustache
- src/ggrc/assets/mustache/modals/save_cancel_delete_buttons.mustache
- src/ggrc/assets/mustache/wf_objects/autocomplete_result.mustache
`Mapper` prop is always set false. And can be removed.
> QUICK-FIX Remove unused mapper prop from modals controller

- src/ggrc-client/js/models/business-models/audit.js
JS error appears when choosing an audit firm second time in Create/Edit audit modal.
The problem is a broken Audit Firm validation.
2. Click to create an audit.
3. Click on Audit firm.
4. Choose some value if they are there (or create and audit firm if not).
5. Choose this or any other value.
Actual result: JS error appears.
Expected result: An option should be chosen.
Remove broken Audit Firm validation. 
New validation logic will be implemented in GGRC-5527.
> GGRC-5302 JS error when choosing an audit firm second time in Create/Edit audit modal

- src/ggrc/migrations/versions/20180706140827_0e40a37a05f4_add_foreignkey_snapshot.py
For usage of temporary tables we should SET AUTOCOMMIT = 1 in migrations.
Add SET AUTOCOMMIT = 1 in migration
> QUICK-FIX Fix migration

- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/mustache/issues/modal_content.mustache
Correct text for issue tracker notes:
_If turned on, a bug will be generated for this issue. Any subsequent updates to admins, primary contacts, secondary contacts and state fields should be made through tracking system and synced with GGRC._
> QUICK-FIX Update issue tracker notes for issue

- src/ggrc-client/js/plugins/ggrc_utils.js
- src/ggrc-client/js/plugins/utils/snapshot-utils.js
Previously we had logic which prevented caching of snapshots. After this [commit](https://github.com/google/ggrc-core/commit/a521e51ef5a0603a34f09f183cb6526624b7feb7) snapshot object became Snapshot model and saved in cache. When we getting refreshed values it incorrectly merges with values in cache. As result we have wrong data.
1. Open any program page with mapped control and audit
2. In separate browser tab update original object of control snapshot
2. On Audit page open widget with control snapshots
5. On Audit Info widget click "Update objects to latest version"
6. In separate browser tab update original object of control snapshot
7. On Audit page open widget with control snapshots
8. Click on snapshot of edited control
9. Click "Get the latest version"
**Actual …
> GGRC-4857 Fix caching of snapshots

- src/ggrc/assets/mustache/controls/modal_content.mustache
> QUICK-FIX Fix typo for Assertions

- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/integrations/test_issue_integration.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Ticket is incorrectly updated, if user deletes an issue object
* Create a GGRC Issue with ticket tracker integration turned on.
* Delete the GGRC Issue object.
Actual result:
* Ticket status is changed to 'Won't Fixed';
* Ticket is updated with a comment: "Changes to this GGRC object will no longer be tracked within this bug."
* Ticket status should NOT be changed.
* Ticket should be updated with a comment: "GGRC object has been deleted. GGRC changes will no longer be tracked within this bug."
Remove setting obsolete status on issue deletion.
> GGRC-5566 Ticket is incorrectly updated, if user deletes an issue object

- src/ggrc/automapper/__init__.py
- src/ggrc/data_platform/computed_attributes.py
- src/ggrc/migrations/utils/acr_propagation.py
- src/ggrc/migrations/utils/update_acr.py
- src/ggrc/models/context.py
- src/ggrc/models/hooks/custom_attribute_definition.py
- src/ggrc/models/hooks/proposal.py
- src/ggrc/models/hooks/relationship.py
- src/ggrc/models/import_export.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/mixins/clonable.py
- src/ggrc/models/person_profile.py
- src/ggrc/models/snapshot.py
- src/ggrc/notifications/common.py
- src/ggrc/notifications/notification_handlers.py
- src/ggrc/services/common.py
- src/ggrc/utils/proposal.py
- src/ggrc/views/converters.py
- src/ggrc_basic_permissions/__init__.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/services/resource.py
- test/integration/ggrc/converters/test_import_assessments.py
Time on the backend side should be processed in UTC.
> GGRC-5543 Time on the backend side should be processed in utc

- setup.cfg
`flake8` doesn't allow lines exactly 80 characters long, and `yapf` does.
Yapf `app.py` and then check `flake8` on it.
Expected result: all is fine.
Actual result: there is a 80-char long line.
Yapf config is adjusted.
> QUICK-FIX Fix the mismatch between flake8 and yapf configs

- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Issue Reporter cannot create a Bug if he doesn't exist in custom roles
Create Issue with ticket tracker integration turned on and Issue reporter doesn't exist in custom roles.
Actual Result: Bug is not created. The system says that Issue reported is Global Auditor
Expected Result: If issue reporter is not an auditor in GGRC, he should be able to create Issue in Issue tracker
Append 'modified_by_id' person in checking emails list.
> GGRC-5573 Issue Reporter cannot create a Bug if he doesn't exist in ACL roles

- src/ggrc-client/js/models/business-models/assessment.js
In some cases references are put into description field. Users would like to be able to have the description as a visible field in assessments to sort by. 
1. Create Audit 
2. Create two Assessments w/ different values in 'Description' field
3. Open 'Assessments' tab
4. Open 'Set visible fields for Assessment' modal and select 'Description'
Description field is added and Assessments could be sorted by it's value.
> GGRC-5392 Make Description field for Assessment View sortable

- src/ggrc-client/js/components/assessment/mapped-objects/mapped-control-related-objects.mustache
- src/ggrc-client/styles/modules/_assessment.scss
When a control assessment is created and clicked on from within the assessment, it shows the related regulations and objectives. Once you click on "show related regulations" it shows all mapped regulations (incl. active, draft, and deprecated). It would help the user to understand what status the regulation is in. This fix brings in the status of the regulation into this view.
1. Create Control
2. Create and Map Regulations and Objectives in all states ('Draft', 'Deprecated', 'Active') to Control
3. Create Audit and Map crearted Regulations and Objectives
4. Create Assessment with Control for Audit
5. Open Control from within the Assessment info
6. Expand 'Related Regulations/Objectives Section'
State for each object is displayed next to date of latest revision and is colored …
> GGRC-5436 Add Regulation and Objective status to related section on InfoPane

- src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
- test/integration/ggrc/integrations/test_issue_sync_job.py
Remove a previous person from 'Admin' / 'Primary Contacts' field for GGRC Issue if Issue was reassigned in Issue Tracker
1. Create Issue in Issue tracker with filled Primary/Secondary Contact and Issue tracker turn on
2. Click ticket link to open Issue Tracker
3. Remove Assignee/Verifier in Issue Tracker and add new ones
4. Look at Issue in GGRC: previous Primary/Secondary Contact is not removed, however new people were added as Primary/Secondary Contact
Actual Result: Previous person is not removed from 'Admin' / 'Primary Contacts' field for GGRC Issue if Issue was reassigned in Issue Tracker
Expected Result: Remove a previous person from 'Admin' / 'Primary Contacts' field for GGRC Issue if Issue was reassigned in Issue Tracker
> GGRC-5575 Remove a previous person from 'Admin' / 'Primary Contacts' field for GGRC Issue if Issue was reassigned in Issue Tracker

- src/ggrc/models/hooks/issue_tracker/common_handlers.py
- src/ggrc/models/hooks/issue_tracker/handlers_mapping.py
- src/ggrc/models/hooks/issue_tracker/issue_integration.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/integrations/test_issue_integration.py
Add comment to issue in issue tracker when comment has been added in GGRC
Add comment to issue with enabled integration in GGRC. Check that comment has been added to ticket in issue tracker.
implement event handlers for collection posted signal on relationship of comment and issue.
> GGRC-5296 Add comment to issue in issue tracker when comment has been added in GGRC

- test/selenium/src/lib/entities/entity.py
> QUICK-FIX Remove uppercase style for gca

- src/ggrc/settings/default.py
Bump version from 1.16.0-Strawberry to 1.17.0-Strawberry.
> Bump up version to 1.17.0-Strawberry

- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/models/business-models/vendor.js
- src/ggrc/assets/mustache/dashboard/lhn.mustache
Move 'Vendors' object into 'Scope' (previously 'Assets/Business') list.
- in LHN; 
- 'Object type' dropdown on unified mapper, global search, generate assessment pop-ups; 
Vendors page - header should be green as for all other scoping objects (previously 'Assets/Business')
See commits.
> GGRC-5556 Move Vendors into scope objects 

- src/ggrc-client/js/models/business-models/document.js
- src/ggrc-client/js/models/business-models/evidence.js
Search for Last Updated Date doesn't work for Evidence and Documents
2. Choose Documents object type.
3. Search for "Last Updated Date"
Actual result: No such field (just "Last Updated" is present)
Expected result: Results should be found as search for "Last Updated Date" works for other objects.
Rename "Last Updated" to "Last Updated Date"
> GGRC-5253 Rename Last Updated to Last Updated Date for Evidence and Documents in search modal

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/test_asmts_workflow.py
Should be merged after https://github.com/google/ggrc-core/pull/8169
This PR has a simple implementation of a fixture that dynamically calls another fixture and can be used in parametrize together with indirect.
The test checks that assessment autogenerated from template is has correct representation on UI.
> QUICK-FIX Add test to check assessment generated from template with date lca

- src/ggrc-client/js/plugins/tests/state-utils_spec.js
- src/ggrc-client/js/plugins/utils/state-utils.js
Incorrect default filter on My Tasks tab
1. Log as Admin user and Click on My Tasks tab
2. Once Tasks tab is displayed look at the dropdown filter screenshot-1.png
**Actual Result:** All Cycle Tasks states are selected in the dropdown filter
**Expected Result:** The following Cycle Tasks states should be selected by default in the dropdown filter:
- Assigned;
- In Progress.
Configure default states for CycleTaskGroupObjectTask model.
> GGRC-5470 Set up default filter on My Tasks tab

- src/ggrc-client/js/apps/risk_assessments.js
Risk Assessment object is missed in Add tab menu
1. Create a Program 
2. Open Add tab menu
Actual Result: Risk Assessment object is missed in Add tab menu
Expected Result: Risk Assessment object should be displayed in Add tab menu
Use model name as widget descriptor name
> GGRC-5542 Risk Assessment object is missed in Add tab menu

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
"Uncaught TypeError: Cannot read property 'find' of null" occurs if click propose changes button and then click 'esc'.
1. Open any control page
2. Click Propose changes button
3. While Edit control modal window is loading press 'esc' on keyboard
*Actual Result:* "Uncaught TypeError: Cannot read property 'find' of null" occurs if click propose changes button and then click 'esc' 
*Expected Result:* no errors should be displayed if click propose changes button and then click 'esc' 
Notes:
I haven't reproduced this issue through provided steps.
But after some investigation, I've understood this issue is appeared, when we do the following steps:
1. Open Edit modal for any object.
2. Click Hide optional fields.
3. Save and Close.
4. Open Edit modal for previous object …
> GGRC-5126 "Uncaught TypeError: Cannot read property 'find' of null" occurs if click propose changes button and then click 'esc'

- src/ggrc-client/js/components/custom-roles/templates/custom-roles.mustache
- src/ggrc-client/js/components/people/editable-people-group.js
- src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
Number of DOM Nodes and JS Heap size too high after opening people modal.
1. Open Program.
2. Add 5+ persons for some Role.
3. Open People modal of this Role.
4. Close.
5. Repeat 6 times steps 3-4
**See more**
1. Add/remove person to/from some group which contain 5+ people
2. Click save.
Expected result: "See more" and "edit icons" are not shown while **loading**.
Actual result: "See more" is shown while **loading**
Update order of changing properties values.
Remove unneeded dependencies between components.
P.S. The solution **partially** fixes issue with memory leak.
It reduces that memory leak.
**BEFORE**
**AFTER**
> GGRC-5388 PEOPLE modal. Reduce size of memory usage

- src/ggrc-client/js/components/assessment/assessment-generator-button.js
Message that assessments are generated is shown before the background task is completed.
Generate assessment and check Network for `background_tasks` requests.
Format should be `background_tasks/id`
1. Login as global creator/editor
2. Open audit with many snapshots 
3. Generate assessments
**Actual result:** The first call to /api/background_tasks returns no background_tasks. This causes "Show results" to be shown. But assessments aren't shown if user opens assessments tree view. They will be generated only in some time when the invisible background task will complete.
**Expected result:** "Show results" should be shown only after assessments are generated
**Note:** Behaviour is fine for my global admin google account as /api/background_tasks returns the task.
Change findAll to findOne …
> GGRC-5339/GGRC-5546 findOne instead findAll in BackgroundTask

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
- src/ggrc-client/js/components/autocomplete/autocomplete.js
- src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
- src/ggrc-client/js/components/tree/tree-item-map.js
- src/ggrc-client/js/components/workflow/workflow_clone.js
- src/ggrc-client/js/controllers/gapi_controllers.js
- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/js/controllers/info_widget_controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js/models/mappers/attr-filtered-list-loader.js
- src/ggrc-client/js/plugins/autocomplete.js
- src/ggrc-client/js/plugins/tooltip.js
- src/ggrc-client/js/plugins/utils/modals.js
We should use `let` or `const` instead of `var`.
Run "eslint --format compact src/ | grep 'no-var'" command. The list of errors should be empty.
All variable declarations with `var` were replaced by `let` according to the [no-var](https://eslint.org/docs/rules/no-var#require-let-or-const-instead-of-var-no-var) rule.
> GGRC-5582 Fix eslint no-var rule

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_objects_review.py
Test for Submit for review on Control scenario
> QUICK-FIX add tests for control obj functionality

- src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
- src/ggrc-client/js/models/conflict-resolution/conflict-resolvers.js
- src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolvers_spec.js
1. Create a control.
2. Open edit modal for the control in 2 separate tabs.
3. In 1st tab modify assertions and click save.
4. In 2nd tab modify categories and click save.
5. Check that both changes were saved.
> GGRC-3744  Add conflict resolution for assertions/categories

- src/ggrc/assets/mustache/issues/info.mustache
- src/ggrc/assets/mustache/issues/modal_content.mustache
Update text to:
"If turned on, a bug will be generated for this issue. Any subsequent updates to admins, primary contacts, secondary contacts and state fields should be made through tracking system and will be synced automatically to GGRC"
Make changes on:
* issue info pane;
* issue create / update pop-up.
> GGRC-5630 Update information text for Issue tracker switch for issue object

- src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js
- src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
- src/ggrc-client/js/entrypoints/admin/bootstrap.js
- src/ggrc-client/js/entrypoints/dashboard/bootstrap.js
- src/ggrc-client/js/entrypoints/export/bootstrap.js
- src/ggrc-client/js/entrypoints/import/bootstrap.js
- src/ggrc-client/js/plugins/ggrc-gapi-client.js
1) Some tested methods were firing requests internally.
2) ggrc-gapi-client.js was making JSONP automatically when it's instance was imported.
Check Network tab when debugging Karma.
1) Mock methods which required a request for work.
2) Move `loadGapiClient()` to bootstrap.js of each entrypoint. This will be still ran before all components. However bootstrap.js is not loaded in tests, thus `loadGapiClient` won't be made in tests.
> GGRC-5348 Remove network requests from tests

- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
- src/ggrc-client/js/entrypoints/user.js
- src/ggrc-client/js/models/local-storage/display-prefs.js
- src/ggrc-client/js/plugins/tests/current-page-utils_spec.js
- src/ggrc-client/js/plugins/tests/date-util_spec.js
- src/ggrc-client/js/plugins/tests/user-utils_spec.js
- src/ggrc-client/js/plugins/utils/current-page-utils.js
- src/ggrc-client/js/plugins/utils/date-util.js
- src/ggrc-client/js/plugins/utils/user-utils.js
Store user profile (currently only "last_seen_whats_new") on BE and fetch it.
GGRC-5255.
1. Login to app.
2. Check network - "profile" request should be made.
Get user profile with last_seen_whats_new date to handle release-notes component's behavior.
> GGRC-5255 Store "Last seen whats new" date

- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/controllers/approval_workflow_controller.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/plugins/popover_template.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
- src/ggrc-client/js_specs/mustache_helpers/debugger_spec.js
- src/ggrc-client/js_specs/mustache_helpers/file_type_spec.js
- src/ggrc-client/js_specs/mustache_helpers/get_permalink_for_object_spec.js
Variables should be declared separately 
Run "eslint --format compact src/ | grep 'one-var'" command. The list of errors should be empty.
Variables are declared separately (one variable declaration for each variable) according to the [one-var](https://eslint.org/docs/rules/one-var#enforce-variables-to-be-declared-either-together-or-separately-in-functions-one-var) rule.
> GGRC-5583 Fix eslint one-var issues

- package-lock.json
- package.json
Known high severity security vulnerability detected in {{parsejson <=0.0.3}}defined in package-lock.json.
**parsejson** is a dependency of old karma version. Latest karma does not need **parsejson**
> GGRC-5643 Security vulnerability: parsejson <=0.0.3defined in package-lock.json.

- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
- src/ggrc-client/js/components/assessment/assessment-generator-button.js
- src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
- src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/components/tree/tree-item-map.js
- src/ggrc-client/js/controllers/approval_workflow_controller.js
- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/js/plugins/utils/modals.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
Space should present immediately after the initial `//` or `/*` of a comment.
Run `eslint --format compact src/ | grep 'spaced-comment'` command. There should be no 'spaced-comment' issues.
Add space after the initial `//` or `/*` of a comment.
> GGRC-5580 Fix eslint spaced-comment issues

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
Assessment - Comment popup is not shown up if select dropdown option with required item
1. Create a program, audit, map control snapshot to this audit
2. Create asmt template with dropdown LCA:
- option 1 with no action required
- option 2 with comment = required
3. Generate asmt from template and control snapshot
4. Open this asmt
5. Choose a value from dropdown LCA that required a comment, type a comment and save it
6. Choose a value from dropdown LCA that no action required
7. Choose a value from dropdown LCA that required a comment: "Add required info" link is shown up, popup is not displayed
**Actual Result:** Comment popup is not shown up if select dropdown option with required a comment 
**Expected Result:** Comment popup should be shown up if select dropdown option with required a …
> GGRC-5497 Show popup for LCA if option for dropdown with required item is selected

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.16.0
See list of updates. 
Convert doc from ticket into markdown paste it into `release-notes.md`.
Update date of what's new for 8/01/2018.
Remove redundant empty lines in `release-notes.md`.
> GGRC-5344 Updates for "What's new" v1.16.0

- setup.cfg
Yapf config mismatches with our accepted style.
Yapf a file and check for the empty string before module docstring.
A toggle in yapf config changed.
> QUICK-FIX Allow blank line before module docstring

- test/integration/ggrc/converters/test_import_assessment_with_map.py
Test to verify assessment import with mapped regulation
> QUICK-FIX Test for import assessment with mapped regulation

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/components/inline/people-with-role-inline-field.js
- src/ggrc-client/js/controllers/contributions.js
- src/ggrc-client/js/controllers/mapper/mapper.js
- src/ggrc-client/js/models/business-models/person.js
- src/ggrc-client/js/plugins/ggrc_utils.js
There is unnecessary escaping non-special characters in regular expression and strings
Run "eslint --format compact src/ | grep 'no-useless-escaper'" command. The list of errors should be empty.
Remove `\` character to avoid unnecessary escaping in some places according to the [no-useless-escape](https://eslint.org/docs/rules/no-useless-escape#disallow-unnecessary-escape-usage-no-useless-escape) rule
> GGRC-5585 Fix eslint no-useless-escape issues

- src/ggrc/converters/handlers/default_people.py
- src/ggrc/converters/pre_commit_checks.py
- test/integration/ggrc/converters/test_export_assessment_templates.py
- test/integration/ggrc/utils/test_user_generator.py
"Default Verifiers" currently can't be set to "--" using import.
Old PR: #7757
When assessment template with Default Verifiers = "--" is exported, export file should contain "--". Also a user should be able to set value to "--" by importing the file with "--".
1. Allow deletion of non-mandatory people during pre-commit-checks
2. Add default value for people object when getting the empty value
> GGRC-4665 Error shows 'Default Verifiers' field as mandatory while importing Assessment template

- src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
- src/ggrc-client/styles/components/info-pane/_info-pane.scss
Component ID/Issue title fields are not marked as mandatory on Issue Info panel.
1. Create GGRC Issue with Issue Tracker turned on Hotlist ID: 700706 Component ID: 64445 
2. Look at the Component ID/Issue fields on Issue Info panel: are not marked as mandatory 
**Actual Result:** Component ID/Issue title fields are not marked as mandatory on Issue Info panel 
**Expected Result:** Component ID/Issue title fields should be marked as mandatory on Issue Info panel
> GGRC-5652 Display asterisk near mandatory issue tracker fields on info-pane

- src/ggrc/models/hooks/acl/__init__.py
Add information on why propagation in some cases skips a few objects
N/A
Add a comment with the proper explanation for skipping some code.
> QUICK-FIX Add clarification comment to ACL propagation

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.17.0
run script build_assets
Convert doc from ticket into markdown paste it into `release-notes.md`.
Update date of what's new for `8/08/2018`.
> GGRC-5644 Update "What's new" for v1.17.0

- test/integration/ggrc/integrations/test_issue_integration.py
Add integration test which checks that 'enabled' flag hasn't been changed after receiving an error from Issue Tracker.
This test has been written by analogy with test in #7952
> QUICK-FIX Add test that issue tracker does not change state in case receiving an error.

- src/ggrc/assets/mustache/requirements/modal_content.mustache
New Requirement popup: CODE - 'Section-XXX' is displayed
1. Invoke New Requirement popup
2. Look at the Code field
Actual Result: 'Section-XXX' is displayed
Expected Result: 'Requirement-XXX' is displayed
Change placeholder.
> GGRC-5777 New Requirement popup: CODE - 'Section-XXX' is displayed

- Dockerfile-selenium
- src/requirements-selenium.txt
- test/selenium/conftest.py
- test/selenium/pytest.ini
- test/selenium/src/lib/constants/settings.py
- test/selenium/src/lib/constants/test_runner.py
- test/selenium/src/lib/environment/__init__.py
- test/selenium/src/lib/meta.py
- test/selenium/src/lib/mixin.py
- test/selenium/src/lib/utils/selenium_utils.py
> QUICK-FIX Update selenium tests' dependencies

- src/ggrc/fulltext/listeners.py
- src/ggrc/utils/helpers.py
- test/integration/ggrc/fulltext/test_reindex.py
Unable to activate big workflow. PUT on "/api/workflows/1757 lead to 500 error.
Error in log:
2018-07-16 15:40:29.058 CEST
Exceeded soft private memory limit of 1024 MB with 1252 MB after servicing 33 requests total. Consider setting a larger instance class in app.yaml.
1. Create any big workflow (I reproduced this issue on workflow with 6000 tasks)
2. Click Activate Workflow button
Actual Result: Unable to activate workflow. 500 error is displayed in console.
Expected Result: User should be able to activate workflow. No errors should be shown.
Reindex model data by chunks. Don't cache sqlalchemy queries for reindex procedure.
Results before change:
With change:
See first PUT request
> GGRC-5488 Fix big workflow activation

- src/ggrc-client/js/apps/base_widgets.js
- src/ggrc-client/js/models/business-models/issue.js
- src/ggrc-client/js/modules/widget_descriptor.js
- src/ggrc-client/js/plugins/utils/object-versions-utils.js
- test/selenium/src/lib/url.py
Incorrect hash fragment for object versions.
1. Open Issue with mapped control snapshot.
2. Open 'Controls Versions' tab.
3. Look at the hash fragment in the browser address bar.
Actual state: issues/610#!Control_versions
Expected state: issues/610#!control_version
Apply lower case and change versions to version.
> GGRC-5347 Fix hash fragment for object versions

- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/integrations/test_issue_integration.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
Remediation Plan and Description updated in Issue Tracker if Save Issue with Issue Tracker turned off
1. Create GGRC Issue with Issue tracker turned on:
2. Click Ticket link on GGRC Issue to open Issue Tracker
3. Invoke Edit Issue popup, update Description/Remediation plan, turn off Issue tracker and save
4. Refresh Issue Tracker page and look at the Description/Remediation plan: it is updated
Actual Result: Remediation Plan and Description updated in Issue Tracker if Save Issue with Issue Tracker turned off
Expected Result: Remediation Plan and Description should not be updated in Issue Tracker if Save Issue with Issue Tracker turned off
Update logic in IssueTracker params builder and fix unit and integration tests.
> GGRC-5631 Remediation Plan and Description updated in Issue tracker if Save Issue with Issue Tracker turned off

- src/ggrc/views/converters.py
- test/integration/ggrc/services/resources/test_converters.py
if you download file from import history with non-ascii symbols server will return HTTP500.
1. Import a CSV with Chinese characters in its filename.
2. In Import history tab, click "Download" button.
In the response headers we can not specify filename, cause headers work bad with non-ascii symbols in headers
> GGRC-5795 Allow re-download imported files with non-ascii in title

- test/selenium/conftest.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/object_states.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_elements.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_rbac.py
- test/selenium/src/tests/test_snapshots.py
> QUICK-FIX Add ACL tests for adding evidence url to asmt

- src/ggrc/maintenance_views/maintenance.py
In specific cases the deployment may fail because of incorrect response format from migrations. 
> Traceback (most recent call last):
File "./bin/trigger_migrations.py", line 61, in <module>
trigger(sys.argv[1], sys.argv[2], sys.argv[3])
File "./bin/trigger_migrations.py", line 27, in trigger
response_body = json.loads(response.text)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Try to deploy with email listed in BOOTSTRAP_ADMIN_USERS and with no current user.
Dump to …
> QUICK-FIX Dump to JSON migration trigger response

- src/ggrc-client/js/components/import-export/connection-lost-notifier.js
- src/ggrc-client/js/components/import-export/export.js
- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/plugins/ajax_extensions.js
- src/ggrc-client/js/plugins/utils/errors-utils.js
"Uncaught SyntaxError: Unexpected token u in JSON at position 0" error is displayed if INTERNET_DISCONNECTED while user import/export csv template
**Preconditions:**
have downloading csv template for any object, e.g. Issue
All required fields are filled out
1. On the Import page click 'Choose file to Import' button
2. Select a file from computer or from GDrive
3. Check 'I confirm' and click Proceed button
4. Turn off Internet connection
5. Look at the import page
- "Uncaught SyntaxError: Unexpected token u in JSON at position 0" error is displayed
Spinner is turning around endlessly;
- User have to refresh the import page to see that the file was imported after internet connection had been restored
- no error should be …
> GGRC-4932  Handle connection lose for import/export

- karma.conf.js
- package-lock.json
- package.json
- src/ggrc-client/js_specs/specs.js
Update jasmine to latest version
`run_karma`
- Remove unused jasmine-fixture package.
- Update jasmine npm package.
- Disable random test execution order (I will create a separate ticket to fix tests and remove this flag after we merge current PR)
> GGRC-5699 Update jasmine to v3

- src/docbuilder/descriptors/service.py
Service related_assessments breaks usual logic for services metadata
because of no model.
Run build_docs in dev container.
Just a patch for a special kind of service. I didn't find out the need for the `name` property at all, it doesn't appear to be used, but removing it breaks doc building job.
> QUICK-FIX Fix docbuilder for model-less services

- src/ggrc/models/all_models.py
- src/ggrc/models/notification.py
- src/ggrc/notifications/common.py
- src/ggrc_workflows/migrations/versions/20180803121149_6bc56d6072a2_move_notifications_to_history.py
- test/integration/ggrc_workflows/notifications/test_notifications_history.py
Notifications that won't be sent in future should be moved into history table to make main table smaller to decrease time of appropriate queries.
> GGRC-5444 Move non-actual notifications into history table

- src/ggrc/migrations/versions/20180802131253_ba1e6a203f07_update_falsy_values_of_checkbox_cav.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/revision.py
- test/integration/ggrc/models/mixins/test_customattributable.py
- test/integration/ggrc/models/test_revision.py
- test/unit/ggrc/converters/handlers/test_custom_attribute.py
"Failed to fetch revision history data" is displayed while opening Change Log tab on Assessment Info panel
The reason is that in some cases Checkbox Custom Attribute can be populated with empty value, instead of 0 or 1. It leads to errors when fetching the revisions with corrupted data.
1. Create an assessment via import with CA Checkbox not filled with any value (or drop the column).
2. Open the assessment and change any other CA than Checkbox
3. Try to open Change Log and receive the error 
1. Add validation for CAV
2. Add migration to fix current values. 
3. Populate old migrations CA Checkbox falsy values with a default value (zero).
> GGRC-5014 Add checkbox CA validation

- loaders/parse-inner-links.js
- src/ggrc-client/js/components/release-notes-list/release-notes.md
- Add new section highlighted with read;
- Add (<version no>, <date of release in format mm/dd/yyyy>) for each feature.
- Change order of features in accordance with a doc.
run script build_assets
Convert doc from ticket into markdown paste it into release-notes.md.
Update date of what's new for 8/15/2018.
Clarification to commit `Do not use regular expressions to match header`:
New doc with updates contains headers and links with brackets.
`match` method converts passed string into `RegExp`, but brackets is unescaped. As result `match` returns falsy value.
Solution for this is to use `indexOf`(which do not convert string to `RegExp`) instead of `match`. As alternative we can …
> GGRC-5861 Update "What's new" for v1.18.0

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_elements.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Add ACL tests for changing assessment state

- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/element/widget_info.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_elements.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_rbac.py
> QUICK-FIX View evidence urls as another user

- src/ggrc/migrations/versions/20180627104424_385ee48cd6b9_add_acr_for_background_tasks.py
Migration chain has two heads right now
Run `db_reset`
Update migration chain
> QUICK-FIX Update migration version

- src/ggrc/migrations/versions/20180730135813_8aec8b112701_new_index_into_revisions.py
- src/ggrc/models/revision.py
- src/ggrc/snapshotter/helpers.py
Optimize snapshotter.helpers.get_revisions step on audit create if program has about 4k snapshotable objects from ~ 10 sec locally to 1 sec. 
try to create audit on big program.
Move revision filtering from python to sql side.
> GGRC-5367 Optimize query for revisions for new snapshots

- src/ggrc-client/js/components/import-export/export.js
- src/ggrc-client/js/components/import-export/test/export_spec.js
- src/ggrc-client/js/entrypoints/export/bootstrap.js
- src/ggrc/notifications/job_emails.py
- test/unit/ggrc/notification/test_job_emails.py
FE Subtask of GGRC-5092.
Show warning modal when user clicks email link
leading to export page with job_id of old export
that was already resolved
1. User makes export (e.g. 'Test export', with id == 50) and receives and email notification with link [Open].
2. User goes to export page (via link or other way), finds 'Test export' and interacts with it (click Download or Write...).
3. ('Test export' disappears from page).
4. User goes back to e-mail and clicks  [Open] again (link will contain '/export#!job_id=50').
5. User is redirected to export page.
**Expected result:** User should see Warning modal, please see attached image from mock-ups in GGRC-5641.
Show modal if `job_id` from hash is not found in response of `exports GET`.
> GGRC-5641 Add warning modal for resolved export

- src/ggrc-client/js/apps/workflows.js
There is extra TG's data, which is sent to the server via QueryAPI.
1. Open any activated workflow, which has some count of cycles.
2. Go to Active Cycles tab.
3. Open Dev Tools -> Network tab.
4. Expand sub tree for any cycle.
Actual result: There is extra TG's data, which is sent to the server via QueryAPI.
Expected result: There is no extra TG's data, which is sent to the server via QueryAPI.
During the work with this PR, an extra option from the workflow config was removed in order to avoid extra data within QueryAPI request. 
Furthermore, obsolete pieces of code were detected. Thus, such code was cleaned up and refactored.
> GGRC-5316 Remove extra TG's data from QueryAPI request, when Cycle's sub tree was opened

- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mixins/mixin.js
During the work with GGRC-5316 (#8203), several pieces of obsolete code were found. Due to this reason, refactoring for WF related objects was performed.
Refactoring was performed.
> GGRC-5859 Refactor workflow config

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.19.0
Convert doc from ticket into markdown paste it into release-notes.md.
Update date of what's new for `8/21/2018`.
> GGRC-5862 Update "What's new" for v1.19.0

- src/ggrc/contributions.py
- src/ggrc/models/import_export.py
- src/ggrc/views/converters.py
In some exceptional situations Im-/Export job can freeze in "In Progress" status. 
Create long running import job and interrupt it with Ctrl-C. Launch app and make sure there is Import with "In Progress" status.  Change job _start_at_ time to yesterday in DB. Refresh page with imports and job should change status to Failed. Log in console should report detection of overtimed task.
Same should be reproduced for Exports.
This happens because of uncaught failure of background task and not updating record in database. BG task should update job status in DB after completion, but it normal flow was interrupted.
BG task can live in App Engine no more than 24 hours, and we can consider Im-/Export tasks started more than 24 hours before as Failed.
> GGRC-5778 If import job died corresponding record in db must be updated

- src/ggrc-client/js/models/business-models/audit.js
POST 400 is displayed in console while cloning an audit
2. Create and map an audit to the program
3. In the Audit tab click on created Audit in tree view
4. Click Clone Audit in 3 bb's menu > Clone
**Actual Result:** 'The value '4366-1275' is already used for another code. code values must be unique.' error occurs. Audit is not cloned
**Expected Result:** No errors occur while audit cloning. Audit should be cloned
BE doesn't expect custom_attributes_values collection in request and return POST 400 error.
A quick fix is to send empty custom_attribute_values on clone as it was some time ago.
> GGRC-4635 Fix error while cloning an audit

- src/ggrc-client/js/components/release-notes-list/release-notes.md
- src/ggrc/contributions.py
- src/ggrc/migrations/versions/20180730135813_8aec8b112701_new_index_into_revisions.py
- src/ggrc/migrations/versions/20180815130731_b992a3d51db6_rename_sections_to_requirements.py
- src/ggrc/migrations/versions/20180816123728_888972f313a7_rename_sections_to_requirements.py
- src/ggrc/models/import_export.py
- src/ggrc/views/converters.py
The backmerge for current release should be custom with adding a commit that fixes broken migration chain in the dev branch
> BACKMERGE release into dev

- src/ggrc-client/js/components/import-export/export-group.js
- src/ggrc-client/js/components/import-export/export-panel.js
- src/ggrc-client/js/components/import-export/export.js
- src/ggrc-client/js/components/import-export/panel.js
- src/ggrc-client/js/components/import-export/templates/csv-export.mustache
- src/ggrc-client/js/components/import-export/templates/export-panel.mustache
- src/ggrc-client/js/components/import-export/test/export_spec.js
- src/ggrc-client/js/components/import-export/test/panel_spec.js
- src/ggrc-client/styles/modules/_import-export.scss
- src/ggrc/assets/mustache/import_export/export/attribute_selector.mustache
Display validation message "Exports are currently limited to maximum of 1000 columns per file." when selected more than 1000 attributes per object.
2. Select more than 1000 attributes
**Expected result:** Validation message is displayed.
> GGRC-5479 Export: display message on UI when there is more then 1000 attributes selected.

- test/selenium/src/lib/service/rest_service.py
> QUICK-FIX Remove workaround for a fixed bug

- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_elements.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/page/widget/page_tab.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Test for adding a primary contact to assessment

- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Incorrect link to questionnaire
Have defined following env variable `GGRC_Q_INTEGRATION_URL=http://example.com/` in `docker-compose.override.yml` file.
1. Log in
2. Open info pane of Technology Environment object (or Org Group) in Active/Draft state
3. Hover over 'Questionnaire' link on Info panel and look at the link in the bottom of the screen screenshot-1.png
Actual Result: /questionnaires/<technology-environment>=<object_slug> is shown
Expected Result: the link should be: /questionnaires/<technology_environment>=<object_slug>
Replace ` ` on `_` instead of `-` in model name.
> GGRC-5879 Transform model name into snake case for qlink

- src/ggrc/automapper/__init__.py
- src/ggrc/fulltext/listeners.py
- src/ggrc/models/__init__.py
- src/ggrc/models/cache.py
- src/ggrc/models/hooks/acl/__init__.py
- src/ggrc/models/mixins/autostatuschangeable.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/notification/__init__.py
CycleTasks hooks have not enough benchmarks. They should be added to make logs more informative.
Benchmarks are added to CycleTasks orm and request signals. Pre commit hooks and post commit hooks already have benchmarks.
> GGRC-5911 Add benchmarks to CycleTask put hooks

- src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
- src/ggrc-client/js/controllers/approval_workflow_controller.js
- src/ggrc-client/js/controllers/workflow_page.js
- src/ggrc-client/js/router.js
There is unnecessary semicolons. While not technically an error, extra semicolons can cause confusion when reading code.
Run "eslint --format compact src/ | grep 'no-extra-semi'" command. The list of errors should be empty.
Remove unnecessary semicolons.
> GGRC-5586 Fix eslint unnecessary semicolon (no-extra-semi) issues

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update for 'What's new' date for v1.19.0
Update date to 08/23/2018 for 'What's new' v1.19.0
> GGRC-5917 Update "What's new" date for v1.19.0

- src/ggrc/converters/handlers/custom_attribute.py
- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/mixins/customattributable.py
- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
- test/integration/ggrc/services/test_query/test_snapshots.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/utils/filter_utils.py
- test/selenium/src/tests/test_asmts_workflow.py
CAV objects don't contain `attribute_object` field in response from `related_assessments` endpoint.
Override `log_json_base` function in `CustomAttributeValue` model.
> GGRC-4710 People in GCA with person type are not shown up in More Info popup in Related Assessments tab

- src/ggrc-client/js/bootstrap/modal-ajax.js
Content is duplicated in simple-modal. Duplicated part is not visible. If simple modal contains a lot of people ( > 400 ), the DOM nodes will be inserted twice into DOM (will be created copies of people components and so forth) - it leads to increasing of memory usage.
1. Open info pane for any object (for example, for Assessment).
2. Assign at least 6 people to Verifiers.
3. Click See more.
Actual result: Content of simple modal is duplicated (inside simple-modal and out of it).
Expected result: There is no duplication for simple modal content.
On showing a simple-modal`$cloneEl` is created, it contains clone of the original element and handles DOM events. Before detaching the original element the content of the of cloned element is changed by the original element. This breaks reference …
> GGRC-5629 Remove cloned element for simple-modal

- src/ggrc-client/js/apps/workflows.js
- src/ggrc_workflows/models/cycle.py
- src/ggrc_workflows/models/cycle_task_entry.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/task_group.py
- src/ggrc_workflows/models/task_group_object.py
- src/ggrc_workflows/models/task_group_task.py
- src/ggrc_workflows/models/workflow.py
- src/ggrc_workflows/notification/data_handler.py
- test/integration/ggrc/models/test_relationship.py
- test/integration/ggrc_workflows/test_recurring_cycles_event.py
- test/integration/ggrc_workflows/test_relationships.py
- test/unit/ggrc_workflows/notification/test_data_handler.py
We must add relationships objects to workflow objects so that we can use the global acl propagation on them
The objects are also highly denormalized for other reasons and contain too many foreign keys. This PR focuses only on foreign keys needed for ACL propagation and no other.
the relationships need to be created for
workflow > task group
workflow > cycle
task group > task group task
task group > task group object
cycle > cycle task group
cycle task group > cycle task
cycle task > cycle task entry
propagation from cycle task to the original object will be done in a separate ticket since it implies change to the current functionality.
Additionaly changes that this PR brings
After adding relationships for ACL propagation, cycle task …
> GGRC-5808,GGRC-5839 Add relationships to workflow objects

- src/ggrc/migrations/versions/20180814195035_ace8f9834418_add_workflow_relationships.py
Please coordinate and merge this PR together with https://github.com/google/ggrc-core/pull/8265
This migrations add all relationships to existing workflows that are
needed to unify ACL propagation across all objects in our app.
Manually check that upgrade and downgrade migrations work.
check that all relationships that are now newly added in https://github.com/google/ggrc-core/pull/8265 are created for old workflows. Check for missing relationships/typos etc.
Add relationship objects for all existing workflows
relationships added are for
workflow > task group > task group task, task group object
workflows > cycle > cycle task group > cycle task > cycle task entry
> GGRC-5868 Add migration for new workflow relationships

- src/ggrc/models/assessment_template.py
- test/integration/ggrc/models/test_clonable.py
- test/selenium/src/tests/test_audit_page.py
Assessment Templates don't change ('Draft') status after finishing procedure of Audit cloning with Assessment Template.
1. Create Audit based on Program
2. Create Assessment Template under Audit
3. Change Assessment Template status to (Active, Draft, Deprecated)
4. Clone Audit with Assessment Template
5. Check the status of cloned Assessment Template
**Expected Result:** Assessment Templates should has the same status after cloning (Active-Active, Draft-Draft, Deprecated-Deprecated)
* Status field was included in data for Assessment Template clone logic.
> GGRC-3423 Assessment Templates don't change ('Draft') status after finishing procedure of Audit cloning with Assessment Template

- src/ggrc/migrations/versions/20180827001531_fe3ce1807a4e_remove_last_traces_of_migration_modules.py
We still have some leftover tables from the era of migration modules. These need to be cleaned up.
1. Do db_reset before 1.19.0 so that you have the old migration tables in the db
2. Migrate to 1.19.0 after the migration change (see that the migration tables are still there)
3. Migrate to the revision of this PR.
Make sure those tables are not there anymore.
> QUICK-FIX Add a migration that removes last traces of migration modules

- src/ggrc-client/js/controllers/dashboard_controller.js
App freezes if select categories/assertions in Edit control popup.
- Create a control in scope of the program
- Open control page 
- Open Edit control popup
- Select all Categories
**Actual Result:** If select categories/assertions in Edit control popup, app freezes
**Expected Result:** App should not freeze if select categories/assertions in Edit control popup
Listen for changes of `instance.title` not for `change` of instance.
Clicking on `Select All` produces about 300 changes of instance, as result it reseted page title 300 times, because of this app was freezing.
> GGRC-5925 Reset page title only when instance.title is modified

- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_rbac.py
> QUICK-FIX Add tests for asmt permissions

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.20.0
Convert doc from ticket into markdown paste it into release-notes.md.
Update date of what's new for 8/28/2018.
> GGRC-5940 Updates "What's new" for v1.20.0

- src/ggrc/migrations/versions/20180712081827_b46bdb31d869_clear_cc_list_column_in_issuetracker_issue.py
Auditors that are displayed in CC list in Issue Tracker are not removed after updating people on the Assessment level. Currently, it is needed to remove auditors from CC list in Issue Tracker manually.
Deploy on `GGRC-test` and run background task `/_background_tasks/create_missing_revisions`.
Write migration for clear `cc_list` column in `issuetracker_issue` table.
> GGRC-4657 Migration - Manually clearing the cc_list column in the issue tracker table

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.21.0
Need to update only data and version in what's new pop-up:
version = 1.21.0-Strawberry
date = Sep 4, 2018
run script build_assets
Update date of what's new for 9/04/2018.
> GGRC-5965 Update "What's new" for v1.21.0

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
Related people sections were not updated in Audit -> New Assessment
after pressing [Save & Add Another].
From GGRC-5431:
2. Invoke new Assessment popup, fill out required fields and click Save and Add another button
3. Look at the Creators/Assignees fields once New Assessment popup is opened
Actual Result: After clicking Save and Add another button in New Assessment popup, Creators/Assignees are not prepopulated in New Assessment popup
Expected Result: Assignee/Creator should be prepopulated in New Assessment popup after clicking Save &Add another button
Call `this.reset_form(...` (with `newInstance` as argument) to mutate instance, and after it run `$.when(this.options.attr('instance', newInstance))` which will trigger `inserted` event with updated instance.
Add …
> GGRC-5431 Dispatch "Updated" after ACL change

- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_elements.py
- test/selenium/src/lib/utils/ui_utils.py
Currently some of our tests fail when selecting a user in person autocomplete dropdown.
This happens because sometimes they select the user before the users are filtered which (for some unknown reason) leads to the wrong user being selected.
This PR attempts to fix this by waiting for filtering to happen.
> QUICK-FIX Fix intermittent failure when selecting a user in person autocomplete

- src/ggrc-client/js/plugins/ajax_extensions.js
- src/ggrc-client/js/plugins/utils/errors-utils.js
- src/ggrc-client/js/tracker/index.js
- src/ggrc-client/js/tracker/local.js
Add google analytics tracking for 4xx, 5xx status codes.
Extend tracker API to handle errors. Add error-util to get info about error from jqxhr.
> GGRC-5341/5340 Track AJAX errors in google analytics

- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Add a test to check related asmts on snapshot page

- test/selenium/conftest.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest/session_pool.py
> QUICK-FIX Cache Requests' sessions in Selenium tests

- src/ggrc/converters/base_block.py
Import of a single assessment fails OOM on ggrc-test.
Import an assessment on ggrc-test.
Expected result: the import passes.
Actual result: the import fails OOM.
Instead of loading all existing CADs for Assessments, load only ones that are either selected on export page or the ones that are present in imported CSV.
Previous measurements by @pod2metra showed that CAD metadata takes huge amount of memory in imports and exports, and I believe there was a PR by him once with the change I re-did in this PR. Also ggrc-test is well-known to have an ever increasing count of Assessments and LCADs for them. That's the reason why I blame CAD loading for increased memory footprint.
In this PR I provide no measurements of my own (because, sadly, I don't have enough time to perform the measurements …
> GGRC-5954 Load only referenced CADs

- src/ggrc/assets/mustache/cycle_task_entries/tree.mustache
- src/ggrc/services/common.py
- src/ggrc/utils/__init__.py
- src/ggrc_basic_permissions/roles/Creator.py
- src/ggrc_basic_permissions/roles/Reader.py
- test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py
- test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py
- test/integration/ggrc/access_control/acl_propagation/test_wf_member.py
This PR temporary fixes task assignees comment creation for
Creators and Readers.
In this PR creators can still not read and create comments due to
faulty permission checks on collection get request and faulty permission
check in the mustache file for "Add Comment" button.
The commit "Fix editing of cycle task entries" is for the ticket GGRC-4276 and is needed to make tests pass. That could be pulled into a separate PR as a dependency of this one. but since it's a small commit I left it here for now.
Do basic rbac checks for readers and creators on cycle task comments
Add a special checker for cycle task comments.
This will be remove with the rbac 1.5 refactor, but until that is done this is better than having all users as global editors.
> GGRC-4285,GGRC-4276 Allow Global Reader as task assignee or wf admin to create comments

- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
PR fixes 'Missing semicolon (semi)' eslint error.
> GGRC-5587 Fix eslint semi rule

- src/ggrc/assets/mustache/requirements/modal_content.mustache
ACCEPTANCE CRITERIA:
AC1 'Requirement' object should have 'Description' attributes instead of 'Text of Requirement'. Need to rename attribute and keep existing values.
Open modal of Requirement;
Find "Text of Requirement" field which is renamed into "Description".
Update label for description field.
Unify help text for 'Requirement'.
> GGRC-5828 Rename 'Text of requirement' into 'Description'

- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
PR fixes 'Unexpected space(s) before '}' (block-spacing)' eslint error.
> GGRC-5590 Fix esling block-spacing rule

- docs/source/contributing/git/reviewing_pull_requests.rst
This pull request contains description for `important` label.
No testing required.
Add `important` label to `Using GitHub labels` section in `reviewing_pull_requests.rst`.
> DOCS Add important label to docs

- src/ggrc-client/js/components/link_to_clipboard.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/controllers/modals/approval-workflow-modal.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
- src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
PR fixes 'Unnecessarily quoted property ’…’ found (quote-props)' eslint error.
> GGRC-5588 Fix eslint quote-props rule

- src/ggrc-client/styles/modules/_top-nav.scss
Please check GGRC-5772.
.section css rules was not replaced by .requirement
1. Create an audit
2. Map a requirement to it
Actual result: Icon of requirement snapshots is black
Expected result: Icon of requirement should be blue as it's related to snapshots
Change .section css rule to .requirement
> GGRC-5772 Change .section css rule to .requirement

- src/ggrc/assets/mustache/product_groups/modal_content.mustache
- src/ggrc/assets/mustache/technology_environments/modal_content.mustache
Effective date field is broken in Technology Environment and Product Group popup.
1. Open Technology Environment/Product Group popup.
2. Try to select State -> should succeed.
3. Try to select Effective Date -> should succeed.
4. Click [Hide all optional fields] -> there should be no Effective Date displayed.
Wrap `effective-dates` component in `<div class="span4 hidable"></div>`.
> GGRC-5837/5995 Fix effective date in Technology Environment

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.22.0
Convert doc from ticket into markdown paste it into release-notes.md.
Update date of what's new for `9/11/2018`.
> GGRC-6003 Update "What's new" for v1.22.0

- src/ggrc/converters/errors.py
- src/ggrc/gdrive/__init__.py
- src/ggrc/gdrive/errors.py
- src/ggrc/gdrive/file_actions.py
- src/ggrc/services/common.py
- src/ggrc/utils/errors.py
- src/ggrc/views/converters.py
- test/integration/ggrc/utils/test_error_handlers.py
We would like to propose some generic message for un-expected server erros, in order not to show sql statements for a user.
For example: 'Server error occurred. Please contact your system administrator to receive more details."
Manually raise an Exception and see the error message
log errors, but do not show errors on the UI
> GGRC-3470 Show default message when receiving an error not in test mode

- src/ggrc/migrations/versions/20180809145523_189b3c9b694a_remove_sections_table.py
- src/ggrc/migrations/versions/20180810054048_0a61f4e5c57e_remove_outdated_tables.py
We renamed Section object in [PR #8071 ](https://github.com/google/ggrc-core/pull/8071) and deployed it in 1.17.0. Sections table left for downgrade and as backup option. 
You can just run tests and click through app. It's not used anywhere.
I've just dropped this table
> QUICK-FIX Remove outdated tables from DB

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/models/mappers/base-list-loader.js
- src/ggrc-client/js/models/mappers/cross-list-loader.js
- src/ggrc-client/js/models/mappers/direct-list-loader.js
- src/ggrc-client/js/models/mappers/indirect-list-loader.js
- src/ggrc-client/js/models/mappers/mapping-result.js
- src/ggrc-client/js/models/mappers/multi-list-loader.js
- src/ggrc-client/js/models/mappers/proxy-list-loader.js
- src/ggrc-client/js/models/mappers/reifying-list-loader.js
- src/ggrc-client/js/models/mappers/search-list-loader.js
- src/ggrc-client/js/models/mappers/type-filtered-list-loader.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
PR fixes "Expected { after 'if'. (curly)" eslint error.
> GGRC-5593 Fix eslint curly rule

- src/ggrc/builder/json.py
- src/ggrc/migrations/versions/20180412072421_2c659b2fdac1_add_reviews_table.py
- src/ggrc/migrations/versions/20180426074024_02d030db8c53_add_acr_to_review_models.py
- src/ggrc/models/all_models.py
- src/ggrc/models/control.py
- src/ggrc/models/hooks/proposal.py
- src/ggrc/models/mixins/__init__.py
- src/ggrc/models/mixins/rest_handable.py
- src/ggrc/models/mixins/with_proposal_handable.py
- src/ggrc/models/review.py
- src/ggrc/models/utils.py
- src/ggrc/services/__init__.py
- src/ggrc/services/signals.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/test_control.py
- test/integration/ggrc/review/__init__.py
- test/integration/ggrc/review/test_api.py
- test/integration/ggrc/review/test_status_auto_update.py
When attributes of reviewable object are changed we need to set Review status to UNREVIEWED
When mapping/unmapping of reviewable object are changed we need to set Review status to UNREVIEWED
Make Control Reviewable, remove skip marker from integration tests
Added rest handlers mixins. Implemented logic in Review model and Reviewable mixin
> GGRC-5844,GGRC-4901,GGRC-5845,GGRC-4900 Object review models + auto status update

- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
We have build_issue_tracker_url() method in integration_utils module and template in assessment integration module that duplicates this functionality. 
- Basic regression testing.
- maximb-qf-redundant-code instance was deployed to ggrc-test to have ability to click through the app
- Common test case:
1. Create GGRC Assessment with Issue tracker turned on
2. Open assessment and click Ticket button. 
3. Look through comment in issue tracker. Find assessment URL. It should be link to assessment with the same id as you created. 
I've just replaced usage of duplicated code to our util.
> QUICK-FIX Remove redundant code from assessment integration

- src/ggrc-client/js/tracker/index.js
If any AJAX error appear (5XX/4XX code errors) then during error handling another JS error appear: "Uncaught TypeError: Cannot read property 'trackError' of undefined". As result  AJAX errors handled and displayed incorrectly.
It happens when only `build_assets` script was run without `watch_assets`.
run `build_assets`, `launch_ggrc`/`launch_gae_ggrc`
Reproduce some AJAX Error (e.g. create two Controls with the same name).
For `build_assets` there is next setting `NODE_ENV=production` so when tracker initialized there is no strategy for it.
Always use `localStrategy` for tracking if no analytics id.
> GGRC-6006 Always use localStrategy for tracking if no analytics id

- src/ggrc/notifications/job_emails.py
1. Update message of success e-mail template to "Go to export page to download the results. If the file generated for this export request has been downloaded, you can ignore the email".
2. Add red icon to Error e-mail template. Please see attached image.
Deploy on the server, start an export of some entity and see email notification.
Change message in `import_export.html`.
Add ❗Exclamation Mark instead of icon on mockup.
> GGRC-5653 BE: Update e-mail templates

- src/ggrc/migrations/versions/20180913120818_3bbaeab12163_add_not_applicable_category.py
Add 'Not applicable' option to 'Assertions' for Control object.
1. Log in to GGRC
2. Invoke new Control popup
3. Expand 'Assertions' dropdown list
**Expected Result:** 'Not applicable' option should be displayed for 'Assertions' field.
Add migration which adds new 'Not applicable' value in 'categories' table.
> GGRC-5948 Add 'Not applicable' option to 'Assertions' for Control object.

- test/integration/ggrc_workflows/test_status_propagation.py
After [#8215](https://github.com/google/ggrc-core/pull/8215) is merged one test based on python threads (which relies on the fact that CycleTask PUT which moves task to In Progress finishes faster than CycleTask PUT which moves task to Finish) fails randomly on dev. This happens because part of hooks have been removed. Since this scenario can not be reproduced at UI and this test fails randomly, it is better to remove it.
> QUICK-FIX Remove randomly failing test

- .eslintrc.json
- package-lock.json
- package.json
- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/js/components/assessment-template-clone-button/assessment-template-clone-button.js
- src/ggrc-client/js/components/assessment/assessment-generator-button.js
- src/ggrc-client/js/components/assessment/map-button-using-assessment-type.js
- src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js
- src/ggrc-client/js/components/tree/tree-item-map.js
- src/ggrc-client/js/components/workflow/taskgroup_clone.js
- src/ggrc-client/js/components/workflow/workflow_clone.js
- src/ggrc-client/js/controllers/gapi_controllers.js
- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/js/controllers/info_widget_controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/plugins/autocomplete.js
- src/ggrc-client/js/plugins/ggrc-gapi-client.js
- src/ggrc-client/js/plugins/utils/modals.js
For files with dynamic imports eslint shows only error regarding dynamic import and does not show other errors and warnings.
Change deprecated "experimentalObjectRestSpread" rule for Eslint to the new way, described in docs.
Check, that eslint works fine.
Was used `babel-eslint` instead of `esprima` parser.
Was used `"ecmaVersion": 2018` instead of `experimentalObjectRestSpread` rule.
> GGRC-5425/GGRC-5667 Change deprecated "experimentalObjectRestSpread" rule for Eslint to the new way, described in docs

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tree/tree-view-node.js
- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mixins/refetch-hash.js
- test/selenium/src/lib/page/modal/create_new_person.py
In some cases the app generates direct urls for specific item in tree view.
For example /assessment/assessment/12345
It was implemented for old tree view that uses search API.
Current tree view does not support those links and we need to remove code that generates those broken links.
Case 1
1) Generate create an assessment on Audit info page
2) See that after redirect there is no the route in url.
Case 2
1) Create custom role or Custom attribute on admin page.
2) See that there is no the route in url.
> GGRC-5363 Remove unsupported direct hash fragments

- src/ggrc/models/hooks/issue_tracker/issue_integration.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/integrations/test_issue_integration.py
It should be possible to create issue linked to existing IssueTracker ticket
- Apply changes from [#8311](https://github.com/google/ggrc-core/pull/8311) to turn on FE functionality
- These changes with applied #8311 PR are deployed to maximb-ggrc-5969 ggrc-test instance to have opportunity to click through the app
- ### Create linked issue:
0. Prepare test data:
Go to Issue Tracker and choose any ticket. 
Click create issue in same component. 
Enter title, description, assignee and ccs. 
Click create button. 
Copy Issue ID. 
1. Create GGRC Issue with Issue tracker turned on
Enter issue ID from previous step. 
2. Open issue and click Ticket button. 
3. Look through comment in issue tracker. Find issue URL. It should be link to issue with the same id …
> GGRC-5969 Implement BE functionality for creating linked Issue

- src/ggrc/views/converters.py
PR is created in order to resolve some issues pointed by @zidarsk8 in PR #8261 
Manually raise an Exception and see the error message
Refactor the code
> QUCIK-FIX Refactor errors in converters

- src/ggrc/migrations/versions/20180907105308_a55fc79683d2_migrate_mappings.py
For proper integration GGRC with external systems we need to make all existing relationships for `scoping object <-> regulation` and `scoping object <-> standards` 
After migration the field `is_external` in relationships table will be set to `1` for `scoping object <-> regulation` and `scoping object <-> standards`
Make mappings `scoping object <-> regulation` and `scoping object <-> standards` as created by GGRCQ system
> GGRC-5659 Migrate relationships as created by ext system

- src/ggrc-client/js/components/add-object-button/add-object-button.js
- src/ggrc-client/js/components/add-object-button/add-object-button.mustache
- src/ggrc/assets/mustache/audits/summary.mustache
"Uncaught Error: Cannot save assessment, audit context not set." error is displayed while creating assessment	
1. Open any audit page > Audit Summary tab
2. Click on add an "assessment manually" link
3. Fill out required fields in New Assessment popup and click Save
_Actual Result:_ "Uncaught Error: Cannot save assessment, audit context not set." error is displayed while creating assessment.
_Expected Result:_ no errors should be displayed
Remove `noparams` attribute from `add-object-button` component
> GGRC-6063 "Uncaught Error: Cannot save assessment, audit context not set." error is displayed while creating assessment	

- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/controllers/contributions.js
- src/ggrc-client/js/permission.js
PR fixes "Expected '===' and instead saw '==' (eqeqeq)" eslint error.
> GGRC-5596 Fix eslint 'eqeqeq' rule

- src/ggrc/migrations/versions/20180914085354_b75a3fba7d6e_remove_category_scope_id.py
- src/ggrc/models/category.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/test_control.py
- test/integration/ggrc/services/test_query/test_snapshots.py
Remove obsolete field from categories table and from the code
Check that there is not more references to scope_id field and that both assertions and category work on control, via ui and import/export
remove all references and uses of scope_id
> GGRC-6030 Remove obsolete scope_id filed from categories

- src/ggrc/models/hooks/issue_tracker/issue_integration.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- src/ggrc/models/mixins/issue_tracker.py
- test/integration/ggrc/integrations/test_issue_integration.py
- test/integration/ggrc/models/factories.py
It should be possible to link existing issues to existing Issue Tracker tickets, relink existing issues and create new ticket for linked issue.
- Apply changes from [#8311](https://github.com/google/ggrc-core/pull/8311) to turn on FE functionality
- Apply changes from  [#8372](https://github.com/google/ggrc-core/pull/8372) Implement BE functionality for creating linked Issue to turn on linking for new Issues
- These changes with applied [#8311](https://github.com/google/ggrc-core/pull/8311) and [#8372](https://github.com/google/ggrc-core/pull/8372) have been deployed to maximb-ggrc-5900 ggrc-test instance to have opportunity to click through the app.
- ### check test cases from  [#8372](https://github.com/google/ggrc-core/pull/8372) …
> GGRC-5900 Implement BE functionality for linking Issues to Issue Tracker

- src/ggrc/models/evidence.py
- test/integration/ggrc/fulltext/test_total_reindex.py
Currently reindex of 6k evidence takes about 5 min at local env. (25 queries for reindex 10 evidence)
Compare reindex speed at DB with 6k+ evidence
Updated indexed query to load related assessments and audits
Local env (db tempfs disabled)
**Before (dev)**
ggrc.views Evidence: 6160 / 6160
ggrc.performance **112.15s** (**67.99s** CPU and 0.00s for 1  db queries) 'POST /_background_tasks/reindex'
**After**
ggrc.views Evidence: 6160 / 6160
ggrc.performance **73.67s** (**23.24s** CPU and 0.00s for 1  db queries) 'POST /_background_tasks/reindex'
> GGRC-5521 improve evidence reindex speed

- src/ggrc-client/js/components/assessment/mapped-objects/templates/mapped-controls.mustache
- src/ggrc-client/styles/components/action-toolbar/_action-toolbar.scss
- src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
- src/ggrc-client/styles/components/read-more/_read-more.scss
Full text of mapped business object's description is always shown. In case when description contains a lot of text significant part of info pane modal will be occupied by content of the field.
1. Create Control w/ long description (more then 5 rows of text)
2. Create Audit map Control to this Audit
3. Create Assessment and map Control
4. Expand Assessment Info pane and examine mapped Control description
Expected behavior: Should have 'Read More' link. On click full text should be shown.
Adding 'read-more' component for description field of mapped business object.
> GGRC-5503 Add 'read-more' for control description on assessment info tab

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.24.0
Update date of what's new for `9/26/2018`.
> GGRC-6004 Update "What's new" for v1.24.0

- bin/run_integration_acl
- bin/run_integration_ggrc
- bin/run_integration_non_ggrc
- test/integration/ggrc/__init__.py
- test/integration/ggrc/access_control/rbac_factories/base.py
- test/integration/ggrc/api_helper.py
- test/integration/ggrc/converters/test_imported_api_requests.py
**_Note: this PR is marked as important because it fixes issues need for ACL epic._**
Tests had invalid api calls with test client, which left old data in flask.g caches that we use.
This PR just ensures all tests run cleanly and that order running the tests and api calls do not affect each other.
Run a test with multiple api calls, and in the beginning of the second one check flask.g. Variables such as referenced objects and others, should not be present at the beginning of a new request.
Wrap most api calls into app context. This focuses on the API helper, so some tests that use the test client might still have this issue. Those will probably be done at a later point.
> QUICK-FIX Fix test api calls

- src/ggrc-client/js/models/mappers/mapping-result.js
- src/ggrc-client/js/models/mappers/reifying-list-loader.js
PR fixes 'Expected { after 'else' (curly)' eslint error.
> GGRC-5594 Fix eslint 'curly' rule

- src/ggrc-client/js_specs/models/display_prefs_spec.js
PR fixes "Missing space before opening brace (space-before-blocks)" eslint error.
> GGRC-5602 Fix eslint 'space-before-blocks' rule

- src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
- src/ggrc/integrations/synchronization_jobs/sync_utils.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
If add a new Audit Captain to Audit, he should be populated in CC list in Issue Tracker
1. Have an Audit with Issue Tracker 'turned ON' and <user1> as Audit Captain
2. Create an Assessment with Issue Tracker 'turned ON'
3. Open Issue Tracker by clicking Ticket link on Assessment Info panel in Attributes tab
4. Add one more Audit Captain <user2> to Audit
5. Look at the CC list in Issue Tracker after Assessment is synchronized with Issue Tracker
If add a new Audit Captain to Audit, he should be populated in CC list in Issue Tracker
Update Issue Tracker records for Audit with Audit Captains
Group CCs from Assessment and Audit Issue Trackers on PUT signal and periodic tasks
> GGRC-5950 Add a new Audit Captain in CC list in Issue Tracker

- src/ggrc/access_control/utils.py
- src/ggrc/models/hooks/acl/propagation.py
Propagate all fails with out of memory exception on prod. This PR is not a sure thing, but made just in hopes it might solve the problem.
Run propagate all on a bigger db and compare memory consumption
reduce chunk sizes on propagation
This solution is just a simple fix we hope might work. The best option would be to revert changes in the propagation code to allow insert from select statements.
> GGRC-6095 Reduce ACL propagation chunk sizes

- src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
- src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-autocomplete_spec.js
After this [PR](https://github.com/google/ggrc-core/pull/8380), `create` method of `Model` returns `Promise`. It does not have `always` as `can.Deferred` but has `finally`.
Add next settings to `docker-compose.override.yml`:
` - INTEGRATION_SERVICE_URL=mock`
`- AUTHORIZED_DOMAIN=example.com`
1) Have audit
2) Open info pane of audit
3) Assign new 'Auditor'
Actual result: JS error is shown
Expected result: Person assigned successfully
Replays `always` on `finally` in `onItemPicked` function.
> GGRC-6097 Fix external-data-autocomplete model creation

- src/ggrc-client/js/components/object-review/object-review.js
- src/ggrc-client/js/components/object-review/templates/object-review.mustache
- src/ggrc-client/js/components/object-review/tests/object-review_spec.js
- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
- src/ggrc-client/styles/components/object-review/_object-review.scss
Show only review status for snapshots and revisions. Highlight the row in comparer modal window if statuses are different.
**Snapshot:**
1. Review state should be displayed on snapshot of reviewable object.
**Comparer modal for snapshots:**
2. Review state should be displayed on comparer modal for snapshot (get the latest version for a snapshot).
3. After getting the latest version for a snapshot, review state of snapshot should be equal to review state of original object. 
**Comparer modal for restoring version:**
4. Review state should be displayed on comparer modal for restoring version.
5. Review state shouldn't be restored. After restoring version, review state should be updated in accordance with the 'Revert to Unreviewed' rules.
Use `isSnapshot` util to check and hide information …
> GGRC-5203 Show only review status for snapshots and revisions

- src/ggrc-client/js/apps/workflows.js
- src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js
- src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-criteria_spec.js
- src/ggrc-client/js/components/advanced-search/tests/advanced-search-mapping-filter_spec.js
- src/ggrc-client/js/components/import-export/relevant-filter.js
- src/ggrc-client/js/components/import-export/templates/export-panel.mustache
- src/ggrc-client/js/components/import-export/templates/relevant-filter.mustache
- src/ggrc-client/js/models/mappers/mappings-ggrc.js
- src/ggrc-client/js/models/mappers/mappings.js
- src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
'Uncaught TypeError: Cannot read property 'model_singular' of undefined' error occurred if click Add mapping filter in Global Search for Task Group Task object.
1. Open global search
2. Select Task Group Task object type
3. Click 'Add Mapping Filter'
**Actual Result:** 'Uncaught TypeError: Cannot read property 'model_singular' of undefined' error occurred if click Add mapping filter in Global Search for Task Group Task object
**Expected Result:** no errors should be displayed if click Add mapping filter in Global Search
**NOTE:** also issue is reproduced for Workflow, People, Assessment template objects.
This issue is regression of #8335, #8310, #8307.
Exception occurs because there're no canonical mappings for mentioned above objects.
Currently _canonical mappings config is used to …
> GGRC-5991 Fix js exception if click Add mapping filter in Global Search for Task Group Task object

- src/ggrc-client/js/components/object-mapper/object-mapper.js
Script Error while mapping a newly created object to Cycle Task.
1 Open Task tab on My Work page
2 Click Create button in treeView
3 In Create Cycle Task popup Click Map Object button
4 Select any object type, e.g Control and click 'Create and map new object' link
5 Fill required fields in New control popup and Save
Actual Result: Script error while mapping a newly created object to Cycle Task.
Expected Result: no errors should be displayed. Object should be mapped to Cycle Task.
We should process this situation, when we have deferred "map" operation for the object. These situations are only for Assessments and Cycle Tasks. However, only via CT's create modal we can do next: Open Create CT modal -> Click Map Objects -> Via Object Mapper click Create New object. For Assessments, we can map …
> GGRC-6057 Script Error while mapping a newly created object to Cycle Task

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.25.0
Update date of what's new for `10/03/2018`.
> GGRC-6092 Update "What's new" for v1.25.0

- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/custom-attributes/custom-attributes.mustache
Assessment - cannot change LCA date after deprecated state
Create assessment with the following LCAs:
1) text
2) rich texg
3) date (mandatory)
4) checkbox
5) dropdown (mandatory)
6) person
Open infopane
Deprecate the assessment via 3bb menu
Restore the assessment via 3bb menu
Click on date field
Datepicker should appear.
Somehow canjs loses view bindings when we re-render edit component. ViewModel changes does not appear on view.
The working solution do not use flag from parent scope.
> GGRC-6000 Assessment - cannot change LCA date after deprecated state

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for v1.25.0
Update date of what's new for 10/04/2018.
> GGRC-6138 Update "What's new" date for v1.25.0

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/components/import-export/export-group.js
- src/ggrc-client/js/components/import-export/export-panel.js
- src/ggrc-client/js/components/import-export/test/export-group_spec.js
- src/ggrc-client/js/controllers/info_pin_controller.js
- src/ggrc-client/js/controllers/mapper/mapper.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tree/tree-view-node.js
- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/js/controllers/workflow_page.js
- src/ggrc-client/js/plugins/utils/current-page-utils.js
- src/ggrc-client/js/plugins/utils/workflow-utils.js
- src/ggrc-client/js/router.js
Replace window.location redirects with can.route
Add `getUrlParams` method to router to extract can.route params from url string.
Add `redirect` method to router to change `can.route.attr` with provided data.
Replace location.href, location.assign, location.hash with `redirect` method.
> GGRC-5352 Replace window.location redirects with can.route

- src/ggrc-client/js/generated/ggrc_filter_query_parser.js
- src/ggrc-client/js_specs/generated/ggrc_filter_query_parser_spec.js
- src/ggrc/assets/mustache/help/filters_helper_content.mustache
- src/parser/parser.pegjs
Make filter possible using 'IN' operator
Open Export page
Select 'Objective' object type
Type FILTER QUERY: code IN (OBJECTIVE-123, OBJECTIVE-323, OBJECTIVE-423)
Click Start Export button
Open in Google Sheet: is empty
Actual Result: Export template is blank using IN operator for filter query
Expected Result: Object should be exported using IN operator in FILTER QUERY
Add "IN" operator to query parser
> GGRC-6056 Make filter possible using 'IN' operator

- src/ggrc/contributions.py
- src/ggrc/integrations/synchronization_jobs/__init__.py
- src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
- src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
- src/ggrc/integrations/synchronization_jobs/sync_utils.py
- src/ggrc/migrations/versions/20180821131903_1ec05f3e6107_add_due_date_to_issuetracker_issue.py
- src/ggrc/migrations/versions/20181001071651_abb4e8958464_update_issuetracker_issues_due_date.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/issuetracker_issue.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_issue_sync_job.py
- test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Bug due date should equal GGRC assessment due date.
Related PR: https://github.com/google/ggrc-core/pull/8319
Deploy the changes, create an assessment and check due_date in IssueTracker.
> GGRC-5830 Due date field from GGRC should transfer to Issue tracker by

- src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
Pagination component on the bottom has 1 pixel distance from top.
Check pagination component style.
> QUICK-FIX Fix pagination style

- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/integration_utils.py
- test/integration/ggrc/integrations/test_assessment_integration.py
It should be possible to create assessment linked to existing IssueTracker ticket
- Apply changes from [#8311](https://github.com/google/ggrc-core/pull/8311) to turn on FE functionality
- These changes with applied #8311 PR are deployed to maximb-ggrc-5979 ggrc-test instance to have opportunity to click through the app
- ### Create linked issue:
0. Prepare test data:
Go to Issue Tracker and choose any ticket. 
Click create issue in same component. 
Enter title, description, assignee and ccs. 
Click create button. 
Copy Issue ID. 
1. Create GGRC Assessment with Issue tracker turned on
Enter issue ID from previous step. 
2. Open issue and click Ticket button. 
3. Look through comment in issue …
> GGRC-5979 Implement BE functionality for creating linked Assessment

- src/ggrc-client/js/mustache-templates.js
Build failed on some configurations when parsing the RegExp
Build and deployment is fine.
Replace invalid RegExp with string methods.
> QUICK-FIX Replace invalid RegExp with string methods

- src/ggrc-client/js/components/people/templates/people-group-modal.mustache
- src/ggrc-client/js/components/simple-modal/simple-modal.js
People list and edit icon disappears if click ESC in 'See more' popup
1. Create any object, e.g. Product Group
2. Add to COMPLIANCE CONTACTS/Primary/Secondary contacts 5 people (See more link should be displayed) 
3. Click on see more link to open popup with people
4. Click on ESC on keyboard
Actual Result: People list and edit icon disappears if click ESC in 'See more' popup 
Expected Result: People list and edit icon should not disappear if click ESC in 'See more' popup
Add 'keydown' event for 'editable-people-group' component. In this event, the cancel() method is called when the ESP key is pressed and a 'See more' popup is open.
> GGRC-5994 People list and edit icon disappears if click ESC in 'See more' popup

- .eslintrc.json
- src/ggrc-client/js/mustache-templates.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
PR fixes "‘…’ is not defined (no-undef)" eslint error
> GGRC-5599 Fix 'no-undef' eslint error

- src/ggrc/utils/user_generator.py
- test/integration/ggrc_basic_permissions/test_external_login.py
We need to add validation on email format for request headers. 
If validation (at least the email is parsed and contains '@') fails then we should return 400 status code.
- Run integration tests
- Perform request on behalf of invalid X-external-user header
Add validation when parsing email that at least the email is parsed and contains '@'
> QUICK-FIX Add validation on email format in the header

- src/ggrc-client/js/apps/business_objects.js
- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/bootstrap/sticky-popover.js
- src/ggrc-client/js/components/form/fields/tests/checkbox-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/date-form-field_spec.js
- src/ggrc-client/js/components/form/fields/tests/rich-text-form-field_spec.js
- src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
- src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
- src/ggrc-client/js/components/link_to_clipboard.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/models/local-storage/display-prefs.js
- src/ggrc-client/js/models/tests/pending-joins_spec.js
- src/ggrc-client/js/modules/widget_list.js
- src/ggrc-client/js/plugins/persistent_notifier.js
- src/ggrc-client/js/plugins/popover.js
- src/ggrc-client/js/plugins/popover_template.js
- src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/local_storage_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
- src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
PR fixes "Line '...' exceeds the maximum line length of 80. (max-len)" eslint error.
> GGRC-5604 Fix eslint 'max-len' rule

- src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.mustache
- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.mustache
- src/ggrc-client/js/components/object-generator/object-generator.mustache
- src/ggrc-client/js/components/object-mapper/object-mapper.mustache
- src/ggrc-client/js/components/proposal/templates/create-proposal.mustache
- src/ggrc-client/js/components/revision-history/templates/mandatory-fields-modal.mustache
- src/ggrc-client/js/components/revision-history/templates/restore-revision.mustache
- src/ggrc-client/js/mustache/gdrive/confirm_buttons.mustache
- src/ggrc-client/js/mustache/modals/confirm_button.mustache
- src/ggrc-client/js/mustache/modals/confirm_cancel_buttons.mustache
- src/ggrc-client/js/mustache/modals/discard_buttons.mustache
- src/ggrc-client/js/mustache/modals/open_sheet.mustache
- src/ggrc-client/js/mustache/modals/prompt_buttons.mustache
- src/ggrc-client/js/mustache/modals/save_cancel_buttons.mustache
- src/ggrc-client/js/mustache/modals/save_cancel_delete_buttons.mustache
- src/ggrc-client/js/mustache/people_roles/base_modal.mustache
- src/ggrc-client/js/mustache/quick_form/confirm_buttons.mustache
- src/ggrc-client/js/mustache/selectors/base_modal.mustache
- src/ggrc-client/js/mustache/workflows/confirm_start_buttons.mustache
Some templates contains unused class value and should be removed.
Remove 'preventdoubleclick' from class attribute.
> GGRC-6093 Remove unused 'preventdoubleclick' class

- src/ggrc-client/js/components/import-export/download-template/download-template.js
- src/ggrc-client/js/components/import-export/download-template/download-template.mustache
- src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
- src/ggrc-client/styles/modules/_import-export.scss
- src/ggrc/views/converters.py
You can find mockups in parent ticket.
AC1. Add 'Download Sheet' button on 'Download Template' pop-up.
AC2. On clicking 'Download Sheet' button:
- 'Download Template' pop-up should be disabled. 
- Spinner should be shown near "Download Sheet" button.
AC3. Once import templated is generated:
- 'Download Template' pop-up should be closed
- "File Generated" pop-up should be shown.
AC4. Import template in gDrive file should be generated and saved in user's (who triggered event) main folder.
AC5. On clicking "Open" button:
- "File Generated" pop-up should be closed.
- gDrive file should be opened in a new tab.
AC6. On clicking "Close" button, "File Generated" pop-up should be closed.
1) Open import change
2) Click 'Download Import Template'
Add `export_to` field in request body for downloading …
> GGRC-6124/6126 Add ability to download template with gdrive

- src/ggrc/integrations/constants.py
- src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
- src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
- src/ggrc/integrations/synchronization_jobs/sync_utils.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_issue_sync_job.py
- test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
Update implementation for parse "Due Date" and remove "custom_fields" if necessary
Run integration tests.
Try to synchronize assessment with issuer tracker in case when "custom_fields" is empty from issue tracker server
Add logic for parse "Due Date" fields in list of dictionaries
> GGRC-6179 Update Due Date synchronization with Issue Tracker

- src/ggrc-client/js/apps/business_objects.js
- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/models/service-models/notification-config.js
- src/ggrc-client/js/models/service-models/search.js
- src/ggrc-client/js/models/tests/pending-joins_spec.js
- src/ggrc-client/js/permission.js
- src/ggrc-client/js/plugins/popover.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
- src/ggrc-client/js_specs/models/display_prefs_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
- src/ggrc-client/js_specs/models/recently_viewed_object_spec.js
PR fixes "Identifier ‘…’ is not in camel case (camelcase)" eslint error.
> GGRC-5605 Fix eslint 'camelcase' rule

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for v1.27
Update date of what's new for 10/16/2018.
> GGRC-6197 Update "Whats new" date for v1.27

- .eslintrc.json
- src/ggrc-client/js/apps/business_objects.js
- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/components/object-selection/object-selection.js
- src/ggrc-client/js/components/proposal/apply-decline-proposal.js
- src/ggrc-client/js/components/related-objects/related-documents.js
- src/ggrc-client/js/components/related-objects/related-people-access-control-group.js
- src/ggrc-client/js/components/unmap-button/tests/unmap-button_spec.js
- src/ggrc-client/js/controllers/dashboard_controller.js
- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
- src/ggrc-client/js/models/mappers/mappings.js
- src/ggrc-client/js/models/service-models/snapshot.js
- src/ggrc-client/js/modules/widget_descriptor.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/autocomplete.js
- src/ggrc-client/js/plugins/utils/ca-utils.js
- src/ggrc-client/js/plugins/utils/errors-utils.js
- src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js
- src/ggrc-client/js/plugins/utils/modals.js
- src/ggrc-client/js/plugins/utils/models-utils.js
- src/ggrc-client/js/tracker/local.js
- src/parser/generate_parser.js
PR fixes 'Unexpected console statement (no-console)' eslint error
Disable eslint checks for lines where console is used.
> GGRC-5581 Fix eslint 'no-console' rule

- src/ggrc-client/styles/_typography.scss
Edit/Delete buttons overlapping when user not authorized in gdrive.
Please check screenshot in the ticket.
1. Log in GGRC app as <user1> and open any audit page
2. Assign <user2> as auditor and add folder to audit to which <user2> has no access
3. Log in as <user2> and open audit page
4. Look at the edit/delete controls next to warning
Expected Result: Divide edit/delete controls
Override [class^="icon-"], [class*=" icon-"] styles, by applying `width: auto`
> GGRC-6156 Fix icon-link style

- src/ggrc-client/js/plugins/utils/modals.js
**GGRC-5840**
If press `Enter` key in 'I confirm' input then reload is happen (`<input>` is inside of `<form>`, `Enter` key triggers `submit` event which reloads page).
**GGRC-6114**
There is possibility to delete object without typing 'I confirm' only by pressing `Enter` key (`confirmButton` does not have `disable` attribute but has class with the same name).
**Preconditions:**
To enable integration with questionnaires need to set next variable to `docker-compose.override.yml`:
`- GGRC_Q_INTEGRATION_URL=http://example.com/`
after this run `docker-compose up -d` and connect to docker-container.
**GGRC-5840**
1. Login to ggrc-test and create Metric in Draft state
2. Open Edit Metric popup
3. Click Delete button
4. Type 'i confirm' once popup appears and click Enter on …
> GGRC-5840/6114 Fix triggering of confirmButton click

- test/selenium/src/lib/utils/date_utils.py
*Test selects the closest working day in future.*
*Run tests during weekend*
*Test logic updated according to application logic by selecting the closest working day in the past.*
> QUICK-FIX UPATE test logic for closest working day

- test/integration/ggrc/fulltext/test_total_reindex.py
TestTotalReindex is failing for cycle workflow objects because the additional queries are counted.
Run integration test
Disable random-failing test
> QUICK-FIX Disable random failing reindex test

- src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js
This cleanup was missed in this changes https://github.com/google/ggrc-core/pull/8384/commits/69aeec617c4ee0efa4d84124615996d284e46196
> QUICK-FIX Remove duplicated definition of 'filterStates'

- src/ggrc-client/js/bootstrap/modal-ajax.js
- test/selenium/src/lib/page/modal/set_value_for_asmt_ca.py
1. Go to Audit info.
2. "Create Task" from menu.
3. [Map Objects] button.
4. Click [Assessments] button on any control.
5. (Related Assessments opened) Press ESC key.
Expected: Related Assessments modal closed, user see previous modal (Mapper).
Actual: Several modals closed.
Check Issue description
Simple-modal is opened using `.modal()` method, which differs from `.modal_form()`, is result simple-modal container doesn't have `modal` class. When `modal-ajax` handles ESC (in `preventdoubleescape`) it relies on closest element with `modal` class 😏 . 
On the top of it, when simple-modal was opened, closed and opened again, it won't have focus, thus I've moved `$el.focus()` out of condition to make it all the time on opening.
> GGRC-6027 Fix simple-modal closing by ESC

- src/ggrc/fulltext/mixin.py
- src/ggrc/utils/__init__.py
On reindex model it's possible that sql alchemy inserter will get much more than 1000 rows to insert (if reindexing object has a lot of related data that should be indexed). To provide more stability (selecting and inserting big chunk of data can be very slow) and decrease memory consumption insert should be done by chunks.
Run reindex. Check if memory consumption is stable. Check if reindex time is not too bigger than before.
Select and insert reindex data by 1000 chunks.
> GGRC-5208 Insert index data by chunks

- src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
- src/ggrc-client/js/components/form/fields/numberbox-form-field.js
- src/ggrc-client/js/components/form/fields/templates/numberbox-form-field.mustache
- src/ggrc-client/js/components/issue-tracker/info-issue-tracker-fields.js
- src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js
- src/ggrc-client/js/components/issue-tracker/templates/info-issue-tracker-fields.mustache
- src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.mustache
- src/ggrc-client/js/components/numberbox/numberbox.js
- src/ggrc-client/js/components/numberbox/tests/numberbox_spec.js
- src/ggrc-client/js/mustache/assessment_templates/info.mustache
- src/ggrc-client/js/mustache/assessment_templates/modal_content.mustache
- src/ggrc-client/js/mustache/assessments/modal_content.mustache
- src/ggrc-client/js/mustache/audits/info.mustache
- src/ggrc-client/js/mustache/audits/modal_content.mustache
- src/ggrc-client/js/mustache/issues/info.mustache
- src/ggrc-client/js/mustache/issues/modal_content.mustache
- src/ggrc-client/styles/components/form/_ggrc-form.scss
- src/ggrc-client/styles/components/info-pane/_info-pane.scss
Do not merge the ticket - it should be merged together/after BE part.
Dependencies:
FE part of Issue tracker p2 epic
The PR also contains changes required by the following sub-tickets:
GGRC-5903
GGRC-5904
GGRC-5905
GGRC-5906
GGRC-5907
GGRC-5908
GGRC-6018
GGRC-6023
Add the following settings to docker-compose.overrride.yml
- ISSUE_TRACKER_ENABLED=true
- ISSUE_TRACKER_MOCK=true
Restart docker container.
Run the app in gae mode.
1) Add ticket id field to Assessment and Issue.
2) Fix numberbox form field.
3) Improve styling.
4) Improve wording.
> GGRC-5902/GGRC-5909 FE - Issue tracker p2

- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/common_handlers.py
- test/integration/ggrc/converters/test_export_ticket_tracker.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_issuetracked_objects_import.py
- test/integration/ggrc/test_csvs/issue_for_import.csv
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
We should detach issue tracker update from our hooks to send them to async job
This code can be deployed with logging to issue tracker to look that UI works as usual and they doesn't work for imports. 
Run integration tests, they cover usual cases of ui usage.
Our app doesn't have request inside defered import request. This trick is already used in our code.
> GGRC-6043 detach imports from issuetracker hooks

- src/ggrc/login/appengine.py
- src/ggrc/login/common.py
- src/ggrc/login/noop.py
- src/ggrc/services/common.py
- src/ggrc/utils/user_generator.py
- test/integration/ggrc/utils/test_user_generator.py
This PR is fixing the following issues in #8523
1. New user can't login
2. User post is returning invalid response
_*Precondition:*_
_*- Have a user account that hasn't logged in GGRC app before*_
1. Click on 'Login' button
- the app allow user to log in;
- user get Creator rights in the system
1. Open Admin page
2. Grant any user with 'No role' role
3. Log in GGRC app with the user that has 'No role' role
- the app allow user to log in;
- user get Creator rights in the system
1. Open any Assessment
2. Add a user as a verifier (that have never been selected before in ACL)
3. Click save
*Expected Result:* User should be displayed, count should be increased by 1, no errors should be shown while …
> GGRC-6225 Fix post of external users

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.28.0
Update date of what's new for `10/24/2018`.
> GGRC-6239 Update "What's new" for v1.28.0

- test/integration/ggrc/review/test_api.py
Test test_reviewable_revisions falls in case of run all tests but OK if run single mode. It happens in ACL feature branch. It seems that problem in date mocking.
Run all integration tests.
Changed ordering of test results from date to id.
> QUICK-FIX change results ordering to avoid falling in case of mocked date.

- test/selenium/conftest.py
- test/selenium/src/lib/constants/object_states.py
- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/app_entity_factory.py
- test/selenium/src/lib/page/modal/delete_object.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/page/widget/page_elements.py
- test/selenium/src/lib/page/widget/page_tab.py
- test/selenium/src/lib/page/widget/task_group_info_panel.py
- test/selenium/src/lib/page/widget/workflow_page.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/rest/base_rest_service.py
- test/selenium/src/lib/rest/workflow_rest_service.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add tests for delete task group and activate workflow

- src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
Issue type is displayed with 'none' on Assessment info-pane.
1. Open audit with Issue Tracker turned ON.
2. Create assessment with Issue Tracker turned ON.
3. Open Assessment Info panel> Other attributes tab.
**Actual Result:** Issue type is displayed with 'none'.
**Expected Result:** Issue type should not be displayed with 'none'.
Pass Issue Type to `inline-edit-control` component and remove unnecessary `span`.
> GGRC-6210 Issue type is displayed with 'none'

- test/integration/ggrc/integrations/test_issue_integration.py
This test depends on outer scope - if we run tests not in default order it's sometimes possible this test fails cause somewhere user@example.com name changes to "Example User". 
just run integration tests. 
I've created user for this test.
> QUICK-FIX Fix dependent test

- src/ggrc-client/js/components/assessment/info-pane/info-pane.mustache
- src/ggrc-client/js/mustache/assessments/modal_content_additional_fields.mustache
Assessment has a field, where we can edit only plain text.
All other objects use Rich Text for editing.
Case#1:
1. Open Assessment Info-Pane
2. Inspect 'Notes' section
Case#2: 
1. Open Assessment page
2. Open 'Other Attributes' tab
3. Inspect 'Notes' section
Expected behavior: Notes use 'Rich Text' element for editing
Replace 'input' with 'rich-text' in appropriate mustache templates, replace value of 'type' attribute for 'Notes' element in info-pane.mustache from 'input' to 'text'.
> GGRC-5432 Change 'Notes' input field for assessment to 'rich-text'

- src/ggrc-client/js/apps/business_objects.js
- src/ggrc-client/js/components/assessment/assessment-local-ca.js
- src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc-client/js/controllers/mapper/mapper.js
- src/ggrc-client/js/models/refresh_queue.js
- src/ggrc-client/js/plugins/canjs_extensions.js
- src/ggrc-client/js/plugins/tests/ca-utils_spec.js
- src/ggrc-client/js/plugins/utils/ca-utils.js
PR fixes the following eslint errors:
- Identifier name ‘…’ is too short (< 2) (id-length)
- Identifier name ‘…’ is too long (> 25) (id-length)
> GGRC-5606/GGRC-5607 Fix eslint 'id-length' rule

- src/ggrc/models/review.py
- test/integration/ggrc/converters/test_import_reviewable.py
- test/integration/ggrc/review/__init__.py
- test/integration/ggrc/review/test_status_auto_update.py
Updating a folder field on any folderable model resets review status to "Unreviewed". The desired result is that review status will preserve through updates on folder field.
1. Create control
2. Mark Reviewed
3. Assign Folder
Expected result: control state -> Reviewed
Review model checks changed fields and if there is a field not listed in ATTRS_TO_IGNORE set, then review status automatically switches to "Unreviewed". Extending that set to include "folder" field resolves the issue.
> GGRC-6081 Fix review status change on folder update

- src/ggrc-client/js/components/comment/comment-add-form.js
- src/ggrc-client/js/models/mixins/scope-object-notifications.js
- src/ggrc/migrations/utils/acr_propagation_constants_scoping_objects_new_roles.py
- src/ggrc/migrations/versions/20181023110228_348465c9e5ed_update_acr_add_2_roles_for_scoping_objects.py
- src/ggrc/migrations/versions/20181023123921_e2ff62fe34eb_add_2_new_roles_to_comment_.py
- src/ggrc/models/comment.py
- test/integration/ggrc/converters/test_import_commentable.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/notifications/test_comment_notifications.py
Add new attributes for scope objects:
* Line of Defense One Contacts
* Vice President
These roles should NOT be mandatory and should work in the same way as technical leads, system owners, etc.
(BE part) Migration: add new roles for all existing scope objects. Roles that will be added to existing objects in the migrations, should not be populated. 
(FE + BE) If a comment is added with checked 'Notify Contacts' checkbox, an email should be sent for all people that are listed on hover mark.
- import;
- export;
- search;
- email sending
- revisions
- Add a migration with role propagation
- Add a migration to update Recipients field for scoping objects
- Update revisions roles mapping
> GGRC-6163/GGRC-6244 Add 2 new roles for scoping objects

- test/selenium/conftest.py
- test/selenium/run_selenium.py
- test/selenium/src/lib/constants/object_states.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/constants/test_runner.py
- test/selenium/src/lib/custom_pytest_scheduling.py
- test/selenium/src/lib/element/tab_containers.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/proposal_digest.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/page/widget/related_proposals.py
- test/selenium/src/lib/service/proposal_email_service.py
- test/selenium/src/lib/service/proposal_ui_facade.py
- test/selenium/src/lib/service/proposal_ui_service.py
- test/selenium/src/lib/service/rest/template/access_control_role.json
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/users.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/test_proposals.py
- test/selenium/src/tests/test_rbac.py
- test/selenium/src/tests/test_snapshots.py
> QUICK-FIX Add tests for checking Change proposals

- test/selenium/src/lib/page/widget/object_modal.py
Need to wait for status dropdown displaying on the modal.
> QUICK-FIX Fix filling obj creation modal

- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/app_entity_factory.py
- test/selenium/src/lib/entities/cycle_entity_creation.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/table_with_headers.py
- test/selenium/src/lib/page/widget/task_group_info_panel.py
- test/selenium/src/lib/page/widget/tree_widget.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/page/widget/workflow_tree_rows.py
- test/selenium/src/lib/page/widget/workflow_tree_widgets.py
- test/selenium/src/lib/rest/rest_convert.py
- test/selenium/src/lib/rest/workflow_rest_service.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Test to map obj to cycle task

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.29.0
Update date of what's new for `10/30/2018`.
> GGRC-6275 Update "What's new" for v1.29.0

- src/requirements-selenium.txt
- test/selenium/src/lib/entities/app_entity_factory.py
- test/selenium/src/lib/entities/cycle_entity_creation.py
- test/selenium/src/lib/utils/date_utils.py
- test/selenium/src/tests/test_workflow_page.py
Fix generation of cycle task due date.
> QUICK-FIX Fix generation of cycle task due date

- src/ggrc-client/js/mustache/audits/info.mustache
- src/ggrc-client/styles/_typography.scss
"ATTACHMENT" label missed on Audit Info page.
1. Create an audit
2. Open an audit info pane / page
Actual result: "Attachment" label is not shown on audit info pane / page above Assign Folder button
Expected result: "Attachment" label should be shown on audit pane / page above Assign Folder button
Add header element w/ appropriate text above Assign Folder button. Remove redundant style from 'h6' locator.
> GGRC-5303 Add label for 'Attachment' on Audit's info pane

- src/ggrc/integrations/constants.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/integration_utils.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
It's possible that bulk mechanism would be called with enabled integration and doesn't have mandatory values, i.e. it was turned on via import. Default values should be used.
I've implemented test for changed method. App behavior shouldn't change.
I've added default values for builder method if some fields are missed
> GGRC-6270 Update create json methods for assessments issue tracker integration

- test/selenium/src/lib/base.py
- test/selenium/src/lib/page/modal/apply_decline_proposal.py
- test/selenium/src/lib/page/widget/related_proposals.py
- test/selenium/src/lib/service/proposal_rest_service.py
- test/selenium/src/lib/service/proposal_ui_facade.py
- test/selenium/src/lib/service/proposal_ui_service.py
- test/selenium/src/lib/service/rest/query.py
- test/selenium/src/lib/utils/date_utils.py
- test/selenium/src/tests/test_proposals.py
> QUICK-FIX Add tests to check an applied proposal

- src/ggrc/integrations/issuetracker_bulk_sync.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
Our bulk mechanism collects issuetracker_issues records for all sent objects. It should try to sync only those one that have integration enabled True. 
This methods aren't called in our app right now but they would affect imports for issue tracker fields.
App behavior shouldn't change. I've wrote tests for this query.
I've added check if integration is enabled in this queries.
> GGRC-6266 Fix queries in bulk update mechanism

- src/ggrc-client/js/components/modal-connector.js
- src/ggrc-client/js/components/object-mapper/object-mapper.js
- src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/components/tests/modal-connector_spec.js
- src/ggrc-client/js/components/workflow/cycle-task-modal/cycle-task-modal.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/models/pending-joins.js
- src/ggrc-client/js/mustache/assessments/modal_content.mustache
- src/ggrc-client/js/mustache/cycle_task_group_object_tasks/modal_content.mustache
- src/ggrc-client/js/plugins/utils/mapper-utils.js
TreeView is not refreshed on object page while adding a cycle task.
1. Open any Control page
2. Add tab > Workflow task
3. Create a cycle task
*Actual Result:* Cycle task is not displayed in tree view after creating. User has to refresh the page
*Expected Result:* TreeView should be refreshed and cycle task should be displayed after creating
I described needed details in comments.
> GGRC-5549 TreeView is not refreshed on object page while adding a cycle task

- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/related_proposals.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/service/proposal_rest_service.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/test_workflow_page.py
Failure 1:
I changed locator for related proposals in https://github.com/google/ggrc-core/pull/8614. It didn't work for a case when there are no related proposals. PR https://github.com/google/ggrc-core/pull/8619 added such tests. Both PRs were merged at the same time so this error wasn't found at PR merge time.
Failure 2:
`test_map_obj_to_cycle_task` often fails when clicking "Map Objects" link. Reason is positions of elements change while panel is being rendered. Chromedriver finds element on screen but its position changes between `find_element` and `click`, and so exception "Element ... is not clickable at point ..." happens. I added a wait for an element that appears at the start of panel rendering process and a wait for an element that disappears relatively late in panel rendering …
> QUICK-FIX Fix failures in Selenium tests

- src/ggrc/migrations/utils/acr_propagation.py
- src/ggrc/migrations/versions/20181023132410_70e734fea4a4_evidence_readonly_for_auditor.py
- test/integration/ggrc/access_control/acl_propagation/test_auditors.py
- test/integration/ggrc/models/hooks/acl/test_evidence_role_propagation.py
*Currently auditor can edit evidence of audit. Auditor shouldn't edit evidence.*
- Create audit with evidence
- Assign auditor
- Login as auditor
- Evidence mustn't be editable by auditor
*Created migration with change of Audit Evidence ACR for Auditor to readonly permission.*
> GGRC-5325 Set readonly permissions to audit evidence for auditor

- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
It's possible that bulk mechanism would be called with enabled integration and doesn't have mandatory values, i.e. it was turned on via import. Default values should be used. 
I've implemented test for changed method. App behavior shouldn't change.
I've added default values for builder method if some fields are missed
> GGRC-6268 Update create json methods for issues issue tracker integration

- src/ggrc-client/styles/components/bulk-update/_bulk-update.scss
- src/ggrc-client/styles/components/form/fields/_dropdown-form-field.scss
Warning in dev tools:
> [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
Case 1:
1. Add Global Custom attribute with dropdown type to the object (e. g. Program).
2. Open Create New Program modal
Expected result: There is no warning about '#' character in dev tools.
Case 2:
1. Open Tasks tab on the dashboard
2. Click on the Bulk Update button
Expected result: Modal window is opened and there is no warning about '#' character in dev tools.
Use `%23` instead of unescaped `#` character for "fill" property in data URI (in style for background).
> GGRC-5306 Fix warning about deprecated '#' character in a data URI body

- Dockerfile-selenium
- src/requirements-selenium.txt
> QUICK-FIX Update Selenium container

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for 1.30
Update date of what's new for 11/07/2018.
> GGRC-6304 Update "Whats new" date for v1.30.0

- test/selenium/src/lib/page/widget/related_proposals.py
> QUICK-FIX Add waiting until proposals loading is over

- test/selenium/conftest.py
- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/app_entity_factory.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/rest/base_rest_service.py
- test/selenium/src/lib/rest_facades/person_rest_facade.py
- test/selenium/src/lib/rest_services/person_rest_service.py
- test/selenium/src/lib/ui/internal_ui_operations.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/lib/users.py
- test/selenium/src/lib/utils/app_utils.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Run tests that change workflow under creator and reader

- src/ggrc/views/__init__.py
*Fixed import styles in src/ggrc/views/__init__.py*
> QUICK-FIX Fixed import styles

- src/ggrc/models/background_task.py
- src/ggrc/views/__init__.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
As we should create background tasks from import, we should update endpoints for generating and issue update so it could work from deffered import. 
Currently the only need to create these background task is import of issue tracked fields. As they would be created from deferred task we wouldn't do api call for it. We have some issues about absent request and user here.
Rework background task creation for issue create/generate.
Regression testing is required. App behavior shouldn't change.
- I've changed create_task method to make it possible to run task if request doesn't have headers.
- I've added methods to call appropriate functions from import and wrote tests for it.
> GGRC-6282, GGRC-6267 Make it possible to call bulk inside import.

- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/app_entity_factory.py
- test/selenium/src/lib/entities/ui_dict_convert.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/related_proposals.py
- test/selenium/src/lib/rest/base_rest_service.py
- test/selenium/src/lib/rest/rest_convert.py
- test/selenium/src/lib/rest_facades/object_rest_facade.py
- test/selenium/src/lib/rest_services/control_rest_service.py
- test/selenium/src/lib/rest_services/person_rest_service.py
- test/selenium/src/lib/rest_services/workflow_rest_service.py
- test/selenium/src/lib/ui/internal_ui_operations.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/lib/utils/date_utils.py
- test/selenium/src/lib/utils/test_utils.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Check created_at, updated_at dates and modified_by for workflow

- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/app_entity_factory.py
- test/selenium/src/lib/entities/ui_dict_convert.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/related_proposals.py
- test/selenium/src/lib/rest/base_rest_service.py
- test/selenium/src/lib/rest/rest_convert.py
- test/selenium/src/lib/rest_facades/object_rest_facade.py
- test/selenium/src/lib/rest_services/control_rest_service.py
- test/selenium/src/lib/rest_services/person_rest_service.py
- test/selenium/src/lib/rest_services/workflow_rest_service.py
- test/selenium/src/lib/ui/internal_ui_operations.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/lib/utils/date_utils.py
- test/selenium/src/lib/utils/test_utils.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add test to read workflow as member

- src/ggrc/integrations/issuetracker_bulk_sync.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
Issue Tracker issues is not created when click 'Generate' button at Audit page.
1. Have any audit with Issue Tracker turned ON
2. Create Assessment with Issue Tracker turned OFF
3. Open Audit Info tab and click on [Generate] button
Actual Result: Ticket is not generated for assessment, floating message that "Tickets were generated successfully" is displayed, user gets an email that tickets generation for audit "xxx" was completed successfully.
Expected Result: Ticket should be generated for assessment.
Bulk synchronization mechanism for assessments requires issuetracker_issue object for each assessment, but new assessments are generated w/o issuetracker_issue.
Add generation of missing issuetracker_issue for assessment.
> GGRC-6242 Ticket is not generated using [Generate] button

- test/integration/ggrc/integrations/test_bulk_issue_generate.py
This test was implemented when we had broken business logic. It was fixed in the scope of https://github.com/google/ggrc-core/pull/8631.
Test should pass.
I've set correct assertions according to our business logic
> QUICK-FIX Fix existing test for related assessment issue tracker sync.

- src/ggrc/fulltext/recordbuilder.py
- src/ggrc/models/custom_attribute_value.py
- src/ggrc/models/hooks/access_control_role.py
- src/ggrc/utils/__init__.py
- Reindex and propagate_acl fail on ggrc_dev_db
- propagate all does not create all missing ACL entries for existing objects
Run reindex and propagate_acl on dev db
- make sure that there is no acr that does not have any acl entries on existing objects
Ignore invalid people custom attribute values when reindexing
fix generator for missing acl entries
> GGRC-6317 Fix ACL propagation

- test/selenium/src/lib/entities/cycle_entity_population.py
- test/selenium/src/lib/page/widget/tree_widget.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/page/widget/workflow_tree_rows.py
- test/selenium/src/lib/rest_services/workflow_rest_service.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Test start cycle task

- src/ggrc-client/js/components/related-objects/related-documents.js
Adding a reference url to Issues on an archived audit is broken.
Log in to GGRC and open any audit page
1. Create an Issue
2. Open Audit Info tab and click on 'Archive Audit' in 3 dot's menu
3. Add Reference URL to the created Issue
**Actual Result:** If user adds Reference URL to Issue in Archived Audit:
- the warning message is shown up;
- spinner rounds endlessly;
- reference url is not displayed after Info panel got refreshed
**Expected Result:** User should be able to add Reference URL to Issue in Archived Audit
Send context only for Evidence objects.
> GGRC-5910 Allow to add reference url to Issue on an archived audit.

- src/requirements-dev.txt
- src/requirements-selenium.txt
Known moderate severity security vulnerability detected in requests package <= 2.19.1
Updated package for `dev` and `selenium` dependencies
> GGRC-6278 Update request package for dev and selenium

- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/cycle_entity_population.py
- test/selenium/src/lib/entities/ui_dict_convert.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add assignee to cycle task

- test/selenium/src/lib/entities/app_entity.py
- test/selenium/src/lib/entities/cycle_entity_population.py
- test/selenium/src/lib/entities/ui_dict_convert.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/workflow_tabs.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/tests/test_workflow_page.py
This test consistently passes in CI after https://github.com/google/ggrc-core/pull/8641 was merged.
> QUICK-FIX Remove not needed xfail

- src/ggrc/settings/selenium.py
*During some launches application behaves unexpectedly and there are not enough information what happening with application to find root cause of the issue.*
*Increase logger verbosity for testing environments.*
> QUICK-FIX Update logging settings for test env

- PULL_REQUEST_TEMPLATE.md
Add new point about essential labels update after merging a PR with a migration
> QUICK-FIX Add new point to the PR template

- src/ggrc/data_platform/computed_attributes.py
*Improve performance for assessment generation*
1. Have audit with at least 2 controls snapshots 
2. Create Assessment template 
3. Generate assessments based on 2 controls snapshots and assessment template 
4. Look at the time of assessments generation in Dev tools > Network
Use database union for queries instead of union sets in BE.
For 2 Control: 
Without fix: 4.213s
With fix: 3.784s
> GGRC-2174 Improve performance for assessment generation

- src/ggrc-client/js/components/add-tab-button/add-tab-button.js
- src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
- src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js
- src/ggrc-client/styles/modules/_top-nav.scss
When I click on "Add Tab", the order of the icons appears to be random. Tab names are easier to find if  they are in alphabetical order.
1. Create any object, e.g. System
2. Click Add Tab button
3. Look at the objects in dropdown menu
Actual Result: Objects are not sorted in alphabetical order in dropdown menu if click Add Tab button on the object page
Expected Result: Objects should be sorted in alphabetical order in dropdown menu
Sort widget list by `internav_display` property. `column-count: 2;` in styles allows us to display object names in vertical order.
> GGRC-5390 Display objects in alphabetical order in dropdown menu

- src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js
Several questionable requests run each time after CT was created.
1. Open any object, for example Control.
2. Click Add tab and choose Workflow Tasks.
3. Open Dev Tools -> Network
4. Click "Create" button, fill out needed fields -> Click Save & Close button.
**Actual:** GETs for cycle_task_groups, cycles, workflows.
Add comment on why we have `refresh_all_force` in CT `created` handler. We need this due to reason that related cycle task group, cycle and workflow are dependant on newly created cycle task (that might change everybody's status).
> GGRC-6122 Comment refresh_all on CT created event

- src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
- src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.mustache
- src/ggrc-client/js/components/dropdown/autocomplete-dropdown.js
- src/ggrc-client/js/components/dropdown/autocomplete-dropdown.mustache
- src/ggrc-client/js/components/dropdown/tests/autocomplete-dropdown_spec.js
- src/ggrc-client/styles/_components.scss
- src/ggrc-client/styles/components/autocomplete-dropdown/_autocomplete-dropdown.scss
- src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/page/modal/unified_mapper.py
Dropdown element in advanced search contains a lot options and it's hard to find the right one.
1. Open 'All Objects' page
2. Expand advanced search modal
3. Click 'Add Attributes' then expand attributes dropdown list
Actual behavior: Dropdown list contains a lot options that are not sorted alphabetically
Expected behavior: Dropdown list contains search box in the top. On typing any value options list are shorten by text match.
Add new component with search box in the top and scrollable options list.
> GGRC-6221 Add 'autocomplete-dropdown' component

- src/ggrc/gdrive/errors.py
- src/ggrc/services/common.py
- test/integration/ggrc/generator.py
- test/integration/ggrc/models/test_metric.py
- test/integration/ggrc_workflows/test_api_calls.py
Error message is not displayed when map a document of file you don't have read access to
1. Login as user1
2. Create a control-1. Assign a new folder and attach a file. 
3. Assign user-2 as Secondary Contact in the control created by user1
4. Login as user2 that has access to Document object but doesn't have access to the file that was attached by user-1. 
5. Create a control-2. Assign a new folder to control-2 5. Try to map a document added by user1 
Added new except for HTTPException and changed error message
> GGRC-5227 Fixed error message when map a document

- src/ggrc/converters/column_handlers.py
- src/ggrc/converters/handlers/issue_tracker.py
- src/ggrc/models/mixins/issue_tracker.py
- test/integration/ggrc/converters/test_export_ticket_tracker.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
It should be possible to turn on/off assessments and issues synchronization during import
Try to import and export issuetracked objects and check if Integration enabled flag is set and stored correctly. 
Column Handler for handling integration state. If integration field is empty enabled=false is set.
> GGRC-6249 IssueTracker integration on/off via import functionallity.

- src/ggrc/converters/base.py
- src/ggrc/converters/base_row.py
- src/ggrc/integrations/constants.py
- src/ggrc/integrations/issuetracker_bulk_sync.py
- src/ggrc/integrations/synchronization_jobs/sync_utils.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/integration_utils.py
- src/ggrc/models/hooks/issue_tracker/issue_integration.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- src/ggrc/views/__init__.py
- src/ggrc/views/converters.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
- test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
- test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
- We should forward all issuetracked objects that were imported to our IssueTracker bulk update mechanism. 
- It should be possible to sync comments updates after issuetracked models are imported to Ticket Tracker system. Comments could be imported in bulk using `;;` separator.
Common test case:
As now it's not possible to turn integration on/off via import:
1. Create issuetracked instanses with enabled Issue Tracker integration. 
2. Import these instanses with some changes. Check if appropriate tickets were updated in Issue Tracker. 
3. Check email notification. It should be sent to your gmail. 
4. To check error notification set invalid component id. 
- Create issuetracked objects(Issue or Assessment) with enabled Issue Tracker  integration.
- Import comments for this objects.
- Check …
> GGRC-6248, GGRC-4720 Sync imported objects and comments into Ticket Tracker

- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Existing logic:
1) link manually GGRC Assessment and Ticket from Issue tracker
2) the Issue Tracker CC list is changed in the following way:
Ticket CC list is removed
To Ticket CC list are populated GGRC Assessment Assignee (that are not used for Issue Assignee) and GGRC Audit captain (that are not used for Issue Reporter) 
New logic:
1) link manually GGRC Assessment and Ticket from Issue tracker
2) the Issue Tracker CC list is changed in the following way:
Ticket CC list is KEPT UNCHANGED
To Ticket CC list are added GGRC Assessment Assignee (that are not used for Issue Assignee) and GGRC Audit captain (that are not used for Issue Reporter) 
Create new ticket in Issue Tracker. Add people to cc list.
Link from GGRC to this ticket. Check if cc from ggrc were added to Issue Tracker ticket. …
> GGRC-6172 Make union of existing Ticket CC list and GGRC people after user manually linked Assessment and Ticket

- README.md
- bin/containers
- bin/containers_functions.sh
- bin/deploy
New version of docker compose(1.23) adds slug(random) to container name. 
Run scripts working with containers(./bin/containers). Check mysql log viewing command from readme.md
Changed constant names of container to bash subcall with search by name(ignoring random slug)
> GGRC-6368 Fix scripts to search containers by name without slug

- src/ggrc/migrations/utils/acr_propagation.py
- src/ggrc/migrations/versions/20181018162940_d9c56989ac07_remove_acr_backgroung_tasks.py
- src/ggrc/models/background_task.py
- src/ggrc/models/reflection.py
- src/ggrc/services/common.py
- src/ggrc/settings/__init__.py
- src/ggrc/settings/default.py
- src/ggrc/views/__init__.py
- src/ggrc_basic_permissions/roles/Creator.py
- src/ggrc_basic_permissions/roles/Editor.py
- src/ggrc_basic_permissions/roles/Reader.py
- test/integration/ggrc/builder/test_json.py
- test/integration/ggrc/models/test_background_task.py
Improve existing implementations of background tasks. Creation of BG task should take no more than 0.1 sec of request time
`create_task` is wrapped in benchmark. Test performance of function call. 
It is possible to trigger creation of task with POST request to `/admin/create_missing_revisions`. 
Also it is important to test creation of BG task with request from FE. E.g Audit-Autogenerate assessments. 
Next changes was implementod to reduce background task creation time
- Remove ACL(Roleable mixin) from BackgroundTask model.
- Remove sensitive information from REST API response. Return only 'id' and 'status'
- Grant Global Creator read permission on BackgroundTasks after removing ACL.
- Remove `db.session.commit()` from `create_task` function.
- Change header X-Task-ID to X-Task-Name
- …
> GGRC-6139 Update existing solution of BG tasks

- src/ggrc-client/js/components/comment/comment-add-form.js
- src/ggrc-client/js/components/mapping-controls/mapping-type-selector.js
- src/ggrc-client/js/models/business-models/access-group.js
- src/ggrc-client/js/models/business-models/data-asset.js
- src/ggrc-client/js/models/business-models/facility.js
- src/ggrc-client/js/models/business-models/market.js
- src/ggrc-client/js/models/business-models/metric.js
- src/ggrc-client/js/models/business-models/org-group.js
- src/ggrc-client/js/models/business-models/process.js
- src/ggrc-client/js/models/business-models/product-group.js
- src/ggrc-client/js/models/business-models/product.js
- src/ggrc-client/js/models/business-models/project.js
- src/ggrc-client/js/models/business-models/system.js
- src/ggrc-client/js/models/business-models/technology-environment.js
- src/ggrc-client/js/models/business-models/vendor.js
- src/ggrc-client/js/models/mappers/mappings.js
- src/ggrc-client/js/models/mappers/tests/mappings_spec.js
- src/ggrc-client/js/plugins/utils/models-utils.js
Previously 'business' category of models was renamed into 'scope' but only on UI.
In codebase it is still 'business', it is quite confusing, and leads to conflicts in naming.
- Create any scoping object (e. g. Process)
- Open 'All Objects' page
- Select 'Processes'
- Open 'Map Object' modal
- Expand 'Object Type' dropdown
Expected behavior: Scope & Governance groups are displayed and contains appropriate entities.
Change value of 'category' attribute for appropriate entities from 'business' to 'scope'.
Change value in comparison methods that identifies whether entity is 'Scope' object or not.
> GGRC-6157 Rename 'business' category to 'scope'

- src/ggrc-client/js/components/add-tab-button/add-tab-button.mustache
- src/ggrc-client/js/mustache/dashboard/info/get_started.mustache
- src/ggrc-client/styles/_common.scss
- src/ggrc-client/styles/modules/_top-nav.scss
As a user I want to have an alphabetically ordered list at 'Create object' menu because an actual solution is not readable. The actual solution - alphabetical order shown in rows, for better understanding should be used an alphabetical order in columns.
1. Open the main page
2. Click on the Create Object btn
3. Dropdown menu is opened
Actual Result: Objects is shown in alphabetical order in rows
Expected Result: Objects should be sorted in alphabetical order in columns
Use `column-count: 2;` for dropdown-menu in `.hidden-widgets-list` class. Remove some outdated styles. Add `fa-fw` to the icons, so that they have the same width and thereby align the text (object names)
> GGRC-6334 Make vertical alphabetical order at the objects list at 'Create Object'

- src/ggrc-client/js/apps/business_objects.js
Can not open "My Tasks" tab.
Log in to GGRC.
Click "My Tasks" tab at the top of the page.
Actual Result: "My Tasks" tab is not opened.
Expected Result: "My Tasks" tab should be opened.
This is a regression after this commit https://github.com/google/ggrc-core/commit/ccee359b8f9633d05a15c6f09ff2de00bb0f2df1.
> GGRC-6392 Can not open "My Tasks" tab

- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.mustache
- src/ggrc-client/js/components/import-export/test/import_spec.js
Incorrect wording to confirm import on import page
1. Open import page
2. Choose file to import 
**Actual result**: current wording  "_I confirm, that data being imported is complete and accurate_".
**Expected result**: necessary wording "_I confirm that the import file containing X objects is complete and accurate to the best of my knowledge. I understand that regardless of GGRC's integrity check of the import file, the quality of this import data and adherence to the approved taxonomy and mapping model is my responsibility. Note: bulk import files when not appropriately validated for quality, can have a material effect on the data quality of the overall system_".  Аlso the words "_taxonomy_" should be a link.
Changed the wording to the expected in mustache file and wrapped in a span …
> GGRC-5831 Import steps are out of order

- src/ggrc-client/js/controllers/modals/modals_controller.js
When user is fetching data for the object he has no access to error notification is not displayed. In average circumstances user is trying to open object page using direct url and see the 'Forbidden' page. But in case user had lost access to the object and did not refresh the page and is trying to updated the object then he will not be notified. 
- Login as user-1
- Create Product & assign it to user-2
- Login as user-2 & open created Product
- Remove user-2 from assignee
- Click 3bb menu & select 'Edit Product' 
Actual result: no error notification is displayed
Expected result: common error notification
Add handler for failed request with base notification based on response from server.
> GGRC-6031 Add notification on error when opening 'Edit' modal

- src/ggrc/migrations/versions/20181118111903_05b0a3e7b4ed_update_program_reader_propagation_acr.py
- src/ggrc_basic_permissions/roles/Editor.py
- test/integration/ggrc/access_control/acl_propagation/test_program_readers.py
Program Reader can modify Review object on mapped controls.
This fixes the regression introduced in the original ACR setup for Reviews
https://github.com/google/ggrc-core/blob/fb1a120ae5/src/ggrc/migrations/versions/20180827134847_c465979824fc_add_review_acl.py#L51
- Log in as Administrator
- Create program with Global Creator as Program Reader
- Create control and map it to program
- Mark control reviewed and undo
- Login as Global Creator
- Open control
Actual results:
Review buttons are displayed.
Review buttons are not displayed.
Set correct permissions for program reader.
> GGRC-6323 Fix Program Reader propagated permissions

- test/integration/ggrc_basic_permissions/test_csvs/audit_rbac.csv
- test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_create.csv
- test/integration/ggrc_basic_permissions/test_csvs/audit_rbac_snapshot_update.csv
Currently we don't clear default user `user@example.com` before tests. Some tests import csvs that change this user name from `Example User` to `user@example.com`. It can cause tests fail if they rely on this user name. 
If we don't reset default user, we shouldn't change this user in tests. Never.
App behavior shouldn't change.
In csv's that corrupt default user I've changed user name and email. This data haven't checked it asserts so tests that use this csv still pass successfully.
> QUICK-FIX Fix tests that corrupt default data.

- src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
- src/ggrc-client/js/controllers/tree/tree-view-node.js
- src/ggrc-client/js/models/business-models/assessment.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mappers/mappings.js
- src/ggrc-client/js/models/mixins/mixin.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/utils/models-utils.js
- src/ggrc-client/js_specs/spec_helpers.js
**Problem statement**
CanJS 3 does not support can.isFunction.
**Approach**
Replace can.isFunction to _.isFunction
Open files with can.isFunction
Changed can.isFunction on _.isFunction.
> GGRC-6378 Replace can.isFunction to _.isFunction

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for 1.32.0
Update date of what's new for `11/28/2018`.
> GGRC-6404 Update "Whats new" date for v1.32.0

- src/ggrc/integrations/issuetracker_bulk_sync.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
Bulk mechanism sync logic should be changed:
- we should turn integration off if we had an error during bulk create operations. It's needed cause we can have inconsistent data after i.e. import. We can have unlinked instance with integration turned on. 
It would confuse users: they will see turned on integration but data wouldn't be synced.
- we shouldn't turn it off during bulk update cause it can be synced later with cron job
1. Enable integration via import for assessment or issue and set invalid component_id.
2. Check if integration set off after import.
1. Import assessment or issue with enabled integration and set invalid component_id.
2. Check if integration set  on after import.
- Please, read commit messages.
- maximb-with-import instance was deployed on test.
I've added disable …
> GGRC-6285 Update bulk mechanism sync logic.

- .codeclimate.yml
- .gitignore
- Makefile
- docs/source/backend/adding_new_object.rst
- docs/source/frontend/overview.rst
- src/app.yaml.dist
- src/ggrc-client/js/mustache/base_objects/general-page-header.mustache
Since bootstrap-sass and ggrc/assets/mustache are moved to ggrc-client we need to get rid of all code and mentions of ggrc/assets folder and it's content.
1. Build container
2. Launch the app
Expected behavior: App is working correct
Removed all mentions of 'ggrc/assets'.
> GGRC-6165 Remove all code related to 'ggrc/assets'

- src/ggrc-client/js/models/business-models/requirement.js
- src/ggrc-client/js/mustache/requirements/modal_content.mustache
**Problem Statement**
FE sends unneeded `directive` field when we create Requirement object.
BE ignores the field.
**Approach**
Remove `directive` field from the request payload.
1. Create Requirement object.
**Actual result:** extra field `directive` sends for POST requests.
**Expected result:** extra field `directive` don't sends for POST requests.
Change `directive` field as private in instance `Requirement` model
> GGRC-5856 Remove extra 'directive' option from Requirement create request 

- src/ggrc-client/js/models/business-models/issue.js
- src/ggrc-client/js/models/business-models/product.js
- src/ggrc-client/js/models/business-models/threat.js
Cannot search Product, Issue and Threat  by Effective date
1. Open Global Search 
2. Select Products object type and try to filter by 'Effective date'
3. Set visible fields for Product: 'Effective Date' is missed
**Actual Result:** Cannot search Product by Effective date. 'Effective date' is missed in attributes and Set visible fields popup
**Expected Result:** User should be able to search Product by Effective date. 'Effective date' should be shown in attributes and Set visible fields popup
Note: Issue and Threat should also be verified.
Add Effective Date to the `attr_list` of Product, Issue and Threat models
> GGRC-6403 Fix search by Effective Date

- src/ggrc-client/js/mustache_helper.js
mustache helper `is_allowed_all` not used.
Removed mustache helper `is_allowed_all`
> QUICK-FIX Remove is_allowed_all mustache helper

- src/ggrc/models/mixins/filterable.py
- src/ggrc/models/revision.py
- src/ggrc/query/custom_operators.py
- test/integration/ggrc/services/test_query/test_basic.py
- Added option to filter by column value in Query API.
- Use Query API to filter objects by attribute value. Use "=" operator, as left operand write attribute name and as right operand desired value.
- Currently only "Revision" have filterable attributes ("resource_id", "resource_type", "source_type", "source_id", "destination_type", "destination_id").
Created mixin for models that help specify filterable attributes. Query API's compare operations will check if model inherited Filterable mixin and specified attribute listed as filterable attribute.
> GGRC-6127 Add filtering by attribute value in Query API

- src/ggrc/migrations/versions/20181019121928_5afb1bf2e93a_update_issue_type_to_not_null.py
- src/ggrc/models/issuetracker_issue.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
- test/integration/ggrc/models/test_assessment_template.py
Cron job fails if Issue Type contains null
1) run cron job /hourly_issue_tracker_sync_endpoint
2) check logs for 
{"error": "com.google.apps.framework.request.BadRequestException: java.lang.IllegalStateException: unspecified type"}
Updated issuetracker_issues.issue_type with Null values to "PROCESS"
> GGRC-6211 Add migration to set issue_type="PROCESS"

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for 1.33.0
Update date of what's new for `12/04/2018`.
> GGRC-6428 Update "Whats new" date for v1.33.0

- src/ggrc/models/audit.py
- src/ggrc/models/evidence.py
- src/ggrc/models/hooks/audit.py
- test/integration/ggrc/services/test_query/test_archived.py
* Evidence is not archived along with audit. 
1) Create audit, add assessment with evidence with link xxxx
2) Archive audit
3) Go to global search and search evidence with name xxxx and archived = True
Add simple_property (related_evidences) on Audit model that is used on AUTO_REINDEX_RULES n Evidence model.
> GGRC-5520. Evidence is not reindexed if audit archived/unarchived

- src/ggrc-client/js/controllers/contributions.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/canjs_extensions.js
- src/ggrc-client/js/plugins/utils/models-utils.js
No need to have custom 'reduce' (which is not covered by tests), since we also use Lodash library.
1) Replace all usages of 'can.reduce' on '_.reduce'
2) Remove custom implementation of 'can.reduce'
> GGRC-6206 Remove custom 'can.reduce' method

- src/ggrc-client/js/apps/risk_assessments.js
- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/js/models/mixins/mixin.js
- src/ggrc-client/js/models/service-models/role.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/utils/local-storage-utils.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
- src/ggrc-client/js_specs/models/mappers_spec.js
**Problem statement**
CanJS 3 does not support can.inArray.
**Approach**
Replace can.inArray to includes or indexOf
Open files with can.inArray
Changed  can.inArray on includes or indexOf methods.
> GGRC-6380 Replace can.inArray to includes or indexOf

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for 1.34.0
Update date of what's new for `12/11/2018`.
> GGRC-6442 Update "Whats new" date for v1.34.0

- src/ggrc-client/js/controllers/contributions.js
- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/controllers/info_widget_controller.js
- src/ggrc-client/js/controllers/inner-nav-controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/inner_navigation_controller_spec.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
- src/ggrc-client/js/controllers/tree/list_view_controller.js
- src/ggrc-client/js/controllers/tree/tree-view-node.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mappers/base-list-loader.js
- src/ggrc-client/js/models/mappers/list-binding.js
- src/ggrc-client/js/models/service-models/search.js
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js/plugins/autocomplete.js
- src/ggrc-client/js/plugins/utils/models-utils.js
**Problem statement**
can.Observe is a reference to can.Map and can.Observe.List is reference to can.List. CanJs 3 does not support can.Observe.
**Approach**
Replace can.Observe to can.Map and can.Observe.List to can.List.
Replaced can.Observe to can.Map and can.Observe.List to can.List.
> GGRC-6377 Replace can.Observe to can.Map and can.Observe.List to can.List

- test/selenium/src/lib/page/modal/apply_decline_proposal.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/proposal_rest_service.py
- test/selenium/src/lib/service/proposal_ui_facade.py
- test/selenium/src/lib/service/proposal_ui_service.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_proposals.py
> QUICK-FIX Add test to check proposal comparison window

- src/ggrc/models/background_task.py
In case of new user log in to app, a new Person created in request and BackgroundTask created to index this Person. When user email contain AUTHORIZED_DOMAIN, this user get a Creator role and logs in.
Creation of BackgroundTask uses get_current_user() function with returns currently logged in user.
In case of Creator role this function returns a new user, in other cases function return AnonymousUser. 
AnonymousUser raises exception and request returns 500 code, Person created but without indexing.
Log into app with email containing AUTHORIZED_DOMAIN and not containing. In first case user should log in successfully, in second case user should see warning about not having permission to access app
. No 500 code should be returned.
Write function that use get_current_user() to return current …
> GGRC-6426 Fix issue with anonymous user

- src/ggrc-client/js/components/related-objects/related-documents.js
If create object with reference url, it is not appearing in tree view.
1. Open any Program page
3. Look at the Controls tab: newly created control is not displayed in tree view
**Actual Result:** If create object with reference url, it is not appears in tree view
**Expected Result:** If create object with reference url, it should appear in tree view.
`.create-control modal:success` event (handler creates Relationship between new object and page object) is not dispatched from `modal-ajax` because `.create-control` $trigger is repainted after permissions refreshing.
Permissions refreshing was added because `mapper-utils.mapObjects` contained `isAllowedToMap` check (which checks 'update' permissions for mapping objects). As there is no permissions check in `mapObjects` …
> GGRC-6477 Fix issue when object is not appearing in tree view If create it with reference url

- README.md
- bin/containers_functions.sh
New version of docker compose(1.23) adds slug(random) to container name.
Changed constant names of container to bash subcall with search by name(ignoring random slug)
> QUICK-FIX Fix bash scripts using docker

- src/ggrc/utils/html_cleaner.py
- src/requirements.txt
Newer `bleach` versions have various performance improvements and bug fixes.
The ticket GGRC-6276 proposed update from `bleach 1.2` to bleach `2.x` cause latter contains various performance improvements. However, according to `bleach` change log, there are some bugs in `bleach 2.x` so this PR contains bleach update to `3.0.2` version, which is the last stable version for now.
`html5lib` was dropped from requirements cause it became part of `bleach` starting from `3.0` version.
`webencodings` added to requirements cause later versions of `html5lib` (which is part of bleach now) depend on it.
Also this PR propose usage of `bleach.sanitizer.Cleaner` instead of plain `clean` function.
> GGRC-6276 Bleach update to 3.x

- src/ggrc/models/revision.py
- test/unit/ggrc/models/test_revision.py
 "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined" occurred if click Review and Apply/Restore Version in Control/Risk.
1. Log in GGRC as admin and open All objects page 
2. In Controls tab click on any Control in tree view (old one 2015)
Example Control content:
<pre>
<code>{"company_control": null, "principal_assessor_id": null, "updated_at": null, "contact_id": null, "fraud_related": null, "id": null, "display_name": "222", "title": "222", "kind_id": null, "documentation_description": null, "parent_id": null, "version": null, "directive_id": null, "secondary_contact_id": null, "context_id": null, "start_date": null, "status": "Draft", "description": "", "end_date": null, "os_state": null, "secondary_assessor_id": null, "means_id": null, "modified_by_id": 5, …
> GGRC-6071 "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined" occurred if click Review and Apply/ Restore Version in Control/Risk 

- src/ggrc/settings/default.py
> QUICK-FIX Bump up version

- src/ggrc_workflows/models/workflow.py
'Need verification' column contains incorrect text in csv template.
Download csv template / workflow. 'Need verification' column should contain correct text.
> GGRC-3748 Fix 'need verification' column in workflow csv template

- src/ggrc/services/resources/related_assessments.py
- test/integration/ggrc/services/resources/test_related_assessments.py
Global creator as auditor did not see related assessments if they did not have any role on the assessment 
follow steps in the ticket
This just fixes the query to join by the propagated acls instead of the primary ones.
> GGRC-6356 Fix related assessments

- src/cron.yaml
- src/ggrc/contributions.py
- src/ggrc/migrations/versions/20181126135701_8737b9b51407_add_import_export_bg_operation_types.py
- src/ggrc/models/import_export.py
- src/ggrc/notifications/import_export.py
- src/ggrc/notifications/job_emails.py
- src/ggrc/utils/__init__.py
- src/ggrc/views/converters.py
- src/ggrc/views/cron.py
- src/queue.yaml
- test/integration/ggrc/services/resources/test_converters.py
- test/unit/ggrc/notification/test_job_emails.py
Currently, if user starts import and background job failed for some reason, user is not notified immediately, but has to wait during 24 hours instead (it might be less). On UI "Import in progress" is still displayed and user cannot start a new import.
Run import/export job
Crash it somehow
Check that `import_health_cron_endpoint` cron job move import_export and bg task into proper status (from In Progress to Failed)
Check that import/export job marked as failed on UI.
Add cron job `import_health_cron_endpoint` which check status of all running import/export jobs, move crashed ones into Failed state and send notifications about it.
> GGRC-5913 Notify user frequently, If background import job failed

- test/selenium/src/lib/entities/ui_dict_convert.py
- test/selenium/src/lib/page/modal/repeat_workflow_modal.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add test to check repeat on workflow creation

- src/ggrc/converters/handlers/issue_tracker.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
In case user didn't add via import values for Ticket tracker configuration fields (Component ID, Hotlist ID, Priority, Severity) for assessments then:
- in case exists, use values from audit
- in case they are not added for audit - use following default values: 
1. import assessment with empty issue tracker fields. 
2. Check if this values were populated from audit.
I've just updated appropriate column handlers.
> GGRC-6391 For Assessments with empty Issue Tracker configuration fields use values from Audit

- src/ggrc/converters/handlers/handlers.py
- test/integration/ggrc/converters/test_import_audit.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc/notifications/test_comment_notifications.py
Program-audit relationship is not allowed to change so when a user tries to do that via import, we should show a warning telling him that the field can not be updated
1. Export existing Audit 
2. Change program to some other 
3. Import this file 
User sees a warning that the column will be ignored and nothing get's modified
> GGRC-1398 Show warning when user changes program column when updating Audit via imports

- src/ggrc/utils/rules.py
- test/unit/ggrc/utils/test_rules.py
Now `Audit` is missing in `CycleTaskGroupObjectTask` mapping rules and so not visible on export page.
1. Go to export page;
2. Select `Cycle Tasks` objects;
3. See that mapping to `Audit` is now present in mapping section.
Update dictionary of mapping rules in `ggrc/utils/rules.py`.
> QUICK-FIX Add missed mapping rule for CycleTask

- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_issue_integration.py
Comment text has been lost within the message text (no newlines, quotes etc.)
Verify that comment text looks good both for issues generated in bulk and standard way. Please, use deployed version to check manually.
Comments are distinguished with blank lines and quotes now.
> GGRC-6222 Make comment text more recognizable in issue tracker

- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add xfail for holiday repeat on workflow due date

- .eslintrc.json
- src/ggrc-client/js/components/release-notes-modal/release-notes-modal.js
- webpack.config.js
Actually we have to update what's new date manually each release.
After this changes date will be updated automatically after every deploy.
What's new modal will appear automatically only if date in `release-notes.md` was changed.
`build_assets`
`launch_gae_ggrc`
1) Login into app
2) Open 'Whats new' modal through dropdown-menu in page header.
Date in modal header should be date of assets build.
Add global constant `BUILD_DATE` with `DefinePlugin` which configured at compile time.
Display it in `release-notes-modal` instead of `RELEASE_NOTES_DATE`.
> GGRC-6196 Display build date in release-notes modal

- src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.mustache
- src/ggrc-client/js/components/assessment/info-pane/templates/ticket-id-checker.mustache
- src/ggrc-client/js/components/assessment/info-pane/tests/ticket-id-checker_spec.js
- src/ggrc-client/js/components/assessment/info-pane/ticket-id-checker.js
- src/ggrc-client/js/components/issue-tracker/info-issue-tracker-fields.js
- src/ggrc-client/js/components/issue-tracker/issue-tracker-switcher.js
- src/ggrc-client/js/models/business-models/assessment.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/mixins/assessment-issue-tracker.js
- src/ggrc-client/js/models/mixins/issue-tracker.js
- src/ggrc-client/styles/components/info-pane/_info-pane.scss
a) The following solution should be implemented only for the case when there were no linked ticket to assessment before and ticket tracker integration is switched OFF
b) when user changes to 'ON' ticket tracker integration a popup should appear (see design)
c) few use cases are possible:
- user adds a ticket ID and clicks 'Link with existing Ticket' - linking should happen
- user clicks 'Generate new Ticket' - new ticket should be generated for an assessment
- user left empty Ticket ID field and clicked 'Link with existing Ticket' - an error should be shown 'Please fill in the Ticket ID'
- user adds a ticket ID and clicks 'Generate new Ticket' - a new Ticket should be generated.
1. Create assessment with turned OFF ticket tracker integration
2. Go to Info pane: Other attributes tab
3. Via …
> GGRC-6260 [Ticket Tracker] Allow users to manually link ticket to assessment via inline edit after turning on integration

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" date for 1.35.0
Update date of what's new for `12/20/2018`.
> QUICK-FIX Update "Whats new" date for v1.35.0

- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add xfail to selenium tests for GGRC-6491 issue

- test/selenium/src/tests/test_asmts_workflow.py
> QUICK-FIX Add wait after related asmt creation

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.35.0
Update date of what's new for `12/20/2018`.
> GGRC-6495 Update "Whats new" for v1.35.0

- src/ggrc-client/js/common-handlers.js
- src/ggrc-client/js/components/page-header/notifications-menu-item.js
- src/ggrc-client/js/components/page-header/notifications-menu-item.mustache
- src/ggrc-client/js/components/page-header/page-header.js
- src/ggrc-client/js/components/page-header/page-header.mustache
- src/ggrc-client/js/components/page-header/tests/notification-menu-item_spec.js
- src/ggrc-client/js/models/service-models/notification-config.js
Remove notification logic from `common-handlers.js`.
Test daily email digest notifications.
Move logic to separate component. Refactor component.
> GGRC-6464 Move daily email digest notifications logic to component

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.36.0
When open app, 'whats new' should not appear as long as no new text was added. Just minor spelling fixes.
> GGRC-6517 Update "Whats new" for v1.36.0

- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Update path to datetime method

- src/ggrc-client/js/components/object-list-item/document-object-list-item.mustache
- src/ggrc-client/js/components/tree/templates/tree-item-attr.mustache
- src/ggrc-client/js/mustache_helper.js
- src/ggrc-client/js_specs/mustache_helpers/normalizeLink_spec.js
Incorrect behavior of Reference url.
1. Open any control https://ggrc-test.googleplex.com/controls/7024
2. Add Reference url as 'www.google.com'
3. Click on 'www.google.com' link
**Actual Result:** www.google.com page is not opened
**Expected Result:** www.google.com page should be opened
Normalize reference links: add `http` protocol if required.
The following url's should be normalized:
- www.any_domain.com
- any_domain.com
- any text
The following url's should not be updated:
- starts from `http://` or `https://` or another protocol
- relative (starts from `/`)
> GGRC-5978 Normalize reference link's

- src/ggrc/settings/default.py
`on hold` until #8877 is merged
> Bump version to 1.38.0-Strawberry

- test/selenium/src/lib/element/widget_bar.py
- test/selenium/src/lib/factory.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget_bar.py
- test/selenium/src/lib/service/admin_webui_service.py
- test/selenium/src/tests/test_admin_dashboard_page.py
*Add test that verify that People tab count correctly updated by adding new person.*
> QUICK-FIX Add People tab count test

- docs/source/contributing/git/reviewing_pull_requests.rst
As we decided downgrades aren't mandatory, we should fix a bit our guidelines.
> QUICK-FIX Fix PR review guidelines

- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc/snapshotter/test_indexing.py
Currently user is able to filter Cycle Tasks by 'Needs verification' using 'false/true'. 
For usability reasons recommend filtering using 'yes/no' as it is displayed on UI
1. Open My tasks tab
2. Set 'Needs verification' column
3. Filter by 'Needs verification' ~ yes
4. Filter by 'Needs verification' ~ no
Add true_value/false_value parameters to BooleanFullTextAttr declaration
> GGRC-6518 Make needs verification searchable by yes and no values

- src/ggrc-client/js/components/comment/comment-data-provider.js
- src/ggrc-client/js/components/mapped-counter/mapped-counter.js
- src/ggrc-client/js/components/mapped-counter/tests/mapped-counter_spec.js
- src/ggrc-client/js/components/tree/templates/sub-tree-item.mustache
- src/ggrc-client/js/components/tree/templates/tree-item-extra-info.mustache
- src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js
- src/ggrc-client/js/components/tree/tree-item-extra-info.js
- src/ggrc-client/js/events/eventTypes.js
Number of comments is not displayed in info popup for Cycle task 
Log in to GGRC and open My task tab
Create a Cycle task and assign it to current user
Click Cycle task in treeView
Add a comment
Hover over 'i' icon on Cycle task first tier: comment shows 'zero' screenshot-1.png
Actual Result: Number of comments is not displayed in info popup for Cycle task
Expected Result: Number of comments should be displayed in info popup for Cycle task
Added new `REFRESH_MAPPED_COUNTER ` event handled by `mapped-counter`.
> GGRC-5887 Number of comments is not displayed in info popup for Cycle task

- src/ggrc_workflows/notification/pusher.py
In some cases this function can produce query that run slowly because of excessive filter.
Activate workflow with tasks. `get_notification_query()` called with objs without ids and produce query like 
`SELECT … FROM ...
WHERE ... 
(notifications.object_id, notifications.object_type) IN ((NULL, 'CycleTaskGroupObjectTask'), ... (NULL, 'CycleTaskGroupObjectTask'))`
`list` with object id and type changed to `set` that collapse duplicates.
Query run time reduce from 3.5 sec to 0.5 sec for workflow with 300 tasks on local env.
> QUICK-FIX Improve query filter statement

- src/ggrc-client/js/components/people/people-list-info.js
- src/ggrc-client/js/components/people/people-list-info.mustache
- src/ggrc-client/js/components/people/tests/people-list-info_spec.js
- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.js
- src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item_spec.js
- src/ggrc-client/js/models/service-models/index.js
- src/ggrc-client/js/models/service-models/person-profile.js
- src/ggrc-client/js/plugins/utils/user-utils.js
- src/ggrc-client/js_specs/spec_helpers.js
- src/ggrc-client/styles/_components.scss
- src/ggrc-client/styles/components/people-list-info/_people-list-info.scss
- src/ggrc/gcalendar/calendar_event_sync.py
- src/ggrc/migrations/versions/20181214114431_e9be5898856c_add_event_notification_checkbox.py
- src/ggrc/models/calendar_event.py
- src/ggrc/models/person.py
- src/ggrc/models/person_profile.py
- src/ggrc/services/__init__.py
- src/ggrc/services/resources/person.py
- src/ggrc/views/__init__.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc/gcalendar/test_send_calendar_events.py
- test/integration/ggrc/models/test_query_api_queries.py
After merge run on dev env `UPDATE people_profiles SET send_calendar_events = false` in order to disable notifications for all people. 
Use send_calendar_events flag to switch on/off sending events to Google Calendar.
See the sending of calendar events based on on/off flag.
Add new checkbox attribute for person profile. 
If your PR includes a migration include the additional checklist items
> GGRC-6465/GGRC-6417 Add events mute setting to administration of people

- src/ggrc/converters/handlers/issue_tracker.py
- src/ggrc/models/mixins/issue_tracker.py
- test/integration/ggrc/converters/test_export_ticket_tracker.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
Column for Issue Tracker integration should be named "Ticket Tracker Integration". It should contain hint and it should be possible to turn it on/off with "On" and "Off" commands. 
1. Download Issue/Assessment template to Google sheet
2. Open it
3. "Ticket Tracker Integration" column should be displayed with ON/OFF option and a hint text: "Turn on integration with Ticket tracker, On / Off options are possible"
I've just changed name.
> GGRC-6393 "Integration Enabled" - rename to "Ticket Tracker Integration"

- src/ggrc/views/converters.py
- test/integration/ggrc/converters/test_export_import_core_obj_template.py
'Last Deprecated Date' is not removed from Assessment import spreadsheet
Create import template for Assessment. Check that 'Last Deprecated Date' column is missing
Add attribute `end_date` in `IGNORE_FIELD_IN_TEMPLATE`
> GGRC-3982 'Last Deprecated Date' is not removed from Assessment import spreadsheet

- src/ggrc/integrations/issuetracker_bulk_sync.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
Currently, all the notifications are grouped in one block - "Tickets generation status"
When the updates are made send  emails to all authors about the update status (success, failed).
Requirements, row 4
1. Create assessment with integration turned ON.
2. Import this assessment and change i.e. Priority via import. 
3. Check success letter were sent with "Ticket update status" title. 
Same steps as in case 1 but  with Issue. 
1. Create assessment with integration turned ON.
2. Import this assessment and change component_id to invalid(i.e. 11111111111111111) via import. 
3. Check fail letter were sent with "Ticket update status" title. 
Same steps as in case 3 but  with Issue. 
I've moved email title inside bulk class and override it for update. 
Now we have some issues (GGRC-6532) with …
> GGRC-6399 Change title for "Ticket update status" notification - Issue/Assessment

- test/selenium/run_selenium.py
- test/selenium/src/lib/page/widget/admin_widget.py
- test/selenium/src/lib/page/widget/tree_widget.py
- test/selenium/src/lib/utils/date_utils.py
- test/selenium/src/lib/utils/string_utils.py
- test/selenium/src/tests/test_admin_dashboard_page.py
> QUICK-FIX Add test to verify events data

- src/ggrc-client/js/components/tree/tree-widget-container.js
GGRC-6537 Prev/Next buttons are disabled on Assessment info panel
2. Create at least two assessments
3. Open Assessment info panel of any assessment 
4. Look at the Prev/Next buttons: are disabled
Actual Result: Prev/Next buttons are disabled on Assessment info panel
Expected Result: Prev/Next buttons should be clickable on Assessment info panel
Was added a hack which processes the cases when Prev/Next buttons are used + Task Group's info pane is opened.
> GGRC-6537 Prev/Next buttons are disabled on Assessment info panel

- src/ggrc-client/js/components/import-export/relevant-filter.js
- src/ggrc-client/js/components/import-export/test/relevant-filter_spec.js
Unable to map export of Cycle Tasks by Workflow.
1. Open Export page.
2. Click "+" near "Filter by mapping" header.
Actual result: There is no "Workflow" option into "Mapped to" dropdown.
Expected result: "Workflow" option should be presented into "Mapped to" dropdown.
This PR is a fix of the regression introduced by this commit ccee359b8f.
Additionally to 'Workflow' option, 'TaskGroup' was returned back to dropdown since it was placed there as well.
> GGRC-6489 Unable to map export of Cycle Tasks by Workflow

- src/ggrc-client/js/controllers/modals/modals_controller.js
Workflow: Cannot create a task group in Setup tab.
Root cause: legacy logic was removed from `set_value` method in `modals_controller`, but there was a place that was using it in specific case.
1. Create repeat off workflow
2. Open Setup tab and click on Create button in tree view to create a task group
3. Fill Summary and press on Save & Close button
Revert `modals_controller`'s  `set_value` method cleanup for now.
> GGRC-6538 Revert 'set_value' cleanup

- src/ggrc/gcalendar/calendar_event_builder.py
- src/ggrc/gcalendar/calendar_event_sync.py
- src/ggrc/gcalendar/utils.py
- src/ggrc/migrations/versions/20181129064509_b52499891945_add_calendar_events_model.py
- src/ggrc/models/calendar_event.py
- src/ggrc/models/person.py
- src/ggrc/models/person_profile.py
- test/integration/ggrc/gcalendar/test_calendar_event_builder.py
- test/integration/ggrc/gcalendar/test_calendar_event_sync.py
- test/integration/ggrc/models/test_query_api_queries.py
1. In case the job is failed to sync one CalendarEvent, then the job will fail and roll back all changes. We need to continue sync for other events in this case.
2. Some additional queries are used that should be eliminated.
3. The relationship between person and people_profiles doesn't use FK. 
* Run tests and test business scenarios mentioned in the docs.
* Test the job execution on ~40k cycle tasks (2 times: on fresh database, then re-do the job).
Note: For local testing the one should remove (or comment) calls to Calendar API inside CalendarApiService
* Add try-catch block on sync
* Prefetch ACL and ACR for cycle tasks. 
* Prefetch events
* Fix relationship declaration between person and people_profiles. 
* Change type of due_date field to DATE. The migration is also fixed. Dev …
> GGRC-6533 Fix calendar events query count

- src/ggrc/settings/default.py
Bump up version to from 1.38.0-Strawberry to 1.39.0-Strawberry
> QUICK-FIX Bump up version to 1.39.0-Strawberry

- src/ggrc/gcalendar/calendar_event_builder.py
- test/integration/ggrc/gcalendar/test_calendar_event_builder.py
Change Calendar Event description text
Check that new events is created with updated description
Change Calendar Event description text
> QUICK-FIX Fix calendar event description

- test/selenium/run_selenium.py
> QUICK-FIX Add time tracker for login operation during dev server preparation

- src/ggrc/integrations/client.py
- src/ggrc/integrations/constants.py
- src/ggrc/integrations/issuetracker_bulk_sync.py
- src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
- src/ggrc/integrations/synchronization_jobs/issue_sync_job.py
- src/ggrc/integrations/synchronization_jobs/sync_utils.py
- src/ggrc/migrations/versions/20181107130824_dd2a3a987de5_add_reporter_column_in_issuetrackerissue.py
- src/ggrc/models/hooks/assessment.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/integration_utils.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- src/ggrc/models/issuetracker_issue.py
- test/integration/ggrc/converters/test_export_ticket_tracker.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
- test/integration/ggrc/integrations/test_assessment_integration.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
- test/integration/ggrc/integrations/test_issue_integration.py
- test/integration/ggrc/integrations/test_issue_sync_job.py
- test/integration/ggrc/models/test_clonable.py
- test/unit/ggrc/integrations/synchronization_jobs/test_assessment_sync_job.py
- test/unit/ggrc/integrations/test_client.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
Implement only part of the solution, update assessment_integration.py module, add one class for Assessment integration and include all necessary logic inside this class (builders and handler). It isn't a complete solution, but it's a help to improve current implementation for Assessment and Audit integration, all necessary logic will be included into one class and used in places where it's necessary
Related ticket, include BA requirements:
GGRC-6166
Re-check all actions, connected with Assessment integration with Issue Tracker
Run integration/unit tests
> GGRC-6182, GGRC-6314, GGRC-6136, GGRC-6151, GGRC-6166, GGRC-6181, GGRC-6246 Holistic solution for Assessment - IssueTracker sync (Phase one)

- src/ggrc-client/js/components/people/deletable-people-group.mustache
- src/ggrc-client/js/components/people/editable-people-group.mustache
- src/ggrc-client/js/components/people/templates/people-group-modal.mustache
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/models/cacheable.js
**Problem statement**
method `can.Observe.prototype.attr` is overwritten
Modification and extension of prototype is anti-pattern.
**Possible approach**
Avoid prototype modification.
**Method can.Observe.prototype.attr**
Removed can.Observe.prototype.attr override. Serialize can.Map before passing to `attr()` function where required.
> GGRC-6372 Remove can.Observe.prototype.attr modification

- src/ggrc-client/js/components/import-export/current-exports/current-exports.js
- src/ggrc-client/js/components/import-export/current-exports/current-exports.mustache
- src/ggrc-client/js/components/import-export/export.js
- src/ggrc-client/js/components/import-export/templates/csv-export.mustache
- src/ggrc-client/styles/modules/_import-export.scss
- src/ggrc/cloud_api/task_queue.py
- src/ggrc/converters/base.py
- src/ggrc/models/background_task.py
- src/ggrc/models/import_export.py
- src/ggrc/views/converters.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/services/resources/test_converters.py
- test/integration/ggrc/utils/helpers.py
In GGRC, there is not an option to 'kill' an export once it has been initiated. If you exit the page, it will continue to pull the export.
- Run long export
- Send request on /api/people/{}/exports/{}/stop
Actual result:
Export run until all the data will be exported
Export stopped
Check if status of ImportExport object was changed to stopped and if it was, raise exception that will stop export process.
> GGRC-5854/GGRC-6506 Add a possibility to stop the export

- .eslintrc.json
- src/ggrc-client/js/components/assessment/mapped-objects/mapped-controls.js
- src/ggrc-client/js/components/create-document-button/create-document-button.js
- src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js
- src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
- src/ggrc-client/js/components/gdrive/tests/gdrive_picker_launcher_spec.js
- src/ggrc-client/js/components/issue/issue-unmap-item.js
- src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js
- src/ggrc-client/js/components/related-objects/related-assessments.js
- src/ggrc-client/js/components/revision-log/revision-log.js
- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
- src/ggrc-client/js/components/unified-mapper/mapper-results.js
- src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js
- src/ggrc-client/js/models/custom-attributes/custom-attributable.js
- src/ggrc-client/js/models/custom-roles/roleable.js
- src/ggrc-client/js/plugins/utils/current-page-utils.js
- src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
CanJS 3 does not support can.when.
General regressions, make sure async operations work fine.
run_karma to make sure tests stay valid.
Replace can.when with $.when. 
Add can.when restriction to Eslint.
> GGRC-6531 Replace can.when with $.when

- src/ggrc/migrations/versions/20181222084339_26d983e69d78_set_missed_issue_tracker_values.py
ISSUE PRIORITY / ISSUE SEVERITY / ISSUE TYPE should be displayed by default in Edit Audit popup
1. Open /audits/32#!info link on our test instance.
2. In 3 bb's menu select Edit Audit
3. Turn ON Issue Tracker and look at the ISSUE PRIORITY / ISSUE SEVERITY / ISSUE TYPE
Expected Result: ISSUE PRIORITY / ISSUE SEVERITY / ISSUE TYPE should be displayed by default in Edit Audit popup
Issue Type was fixed in @olegnatsevsky PR. I've migrated the rest of missed values.
> GGRC-6050 ISSUE PRIORITY / ISSUE SEVERITY / ISSUE TYPE are not displayed by default in Edit Audit popup for old audits if turn ON Issue Tracker

- src/ggrc-client/js/components/dropdown/boolean-dropdown-wrapper.js
- src/ggrc-client/js/components/tree/templates/tree-item-attr.mustache
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/models/business-models/control.js
- src/ggrc-client/js/mustache/controls/info.mustache
- src/ggrc-client/js/mustache/controls/modal_content.mustache
- src/ggrc/migrations/versions/20190103151322_077caaf74f6b_change_format_of_fraud_related_key_.py
FRAUD RELATED/ SIGNIFICANCE values are not displayed on Control Info panel.
1. Open any Control info page
2. Open Edit Control popup
3. Set a value in FRAUD RELATED/ SIGNIFICANCE fields > Save
4. Look at the Control Info panel
**Actual Result:** FRAUD RELATED/ SIGNIFICANCE values are not displayed on Control Info panel
**Expected Result:** FRAUD RELATED/ SIGNIFICANCE values should be displayed on Control Info panel
Data contract was changed on BE side. BE returns true/false/null instead of 1/0/empty string.
Use these values in dropdown. As dropdown sets string values to instance conversion before saving is required.
> GGRC-5500/GGRC-6277 Display fraud related/significance fields on Control info pane.

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v1.38.0
Target branch for this PR and only one reviewer were discussed and confirmed.
> GGRC-6603 Update "Whats new" for v1.38.0

- src/ggrc/gcalendar/calendar_event_builder.py
- test/integration/ggrc/gcalendar/test_calendar_event_builder.py
Calendar event generation is failing if cycle task has non-ascii character in the title
1. Create any wf
2. Add a task with non-ascii symbol in title
3. Activate wf
Actual Result: Send calendar events fails
Expected Result: Send calendar events should not fail
Convert all titles to `unicode` before joining them.
> GGRC-6595 Process unicode characters in cycle task titles

- src/ggrc/utils/revisions_diff/builder.py
- test/integration/ggrc/services/test_revision_history.py
500 error when viewing a change log for object where CAV attribute_object_id is str in revision content
Create CAV for Assessment where attribute_object_id is string digit
Open change log
Added conversion person_id value to int
> GGRC-5279 Fix 500 errors in change Log

- src/ggrc-client/js/components/people/people-list-info.js
- src/ggrc-client/js/components/person-modal/person-modal.js
- src/ggrc-client/js/components/person-modal/tests/person-modal_spec.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/models/business-models/person.js
- src/ggrc-client/js/mustache/people/modal_content.mustache
- src/ggrc-client/js/plugins/utils/user-utils.js
- src/ggrc-client/styles/components/form/_ggrc-form.scss
Need to add events mute setting to administration of people on Edit/Create modal.
For Create modal, option should be set to "checked" state by default (confirmed with BA).
Edit modal:
1. Login as Admin.
2. Open Administration page -> People tab.
3. Click any row with person.
4. Open Edit modal via 3 dots menu.
Expected result: "Turn on calendar events" option should be presented.
Edit modal from autocomplete:
1. Login as Admin.
2. Find any autocomplete for person.
3. Click "+ Create" button.
Edit modal from LHN:
1. Login as Admin.
2. Open Left hand navigation -> People/Groups -> People.
3. Click "+ Create" button.
Expected result: "Turn on calendar events" option should be presented.
Create modal:
1. Login as Admin.
2. Open Administration page.
3. Click "Create" button. …
> GGRC-6535 Add events mute setting to administration of people on Edit/Create modal

- src/ggrc/converters/handlers/issue_tracker.py
- src/ggrc/models/mixins/issue_tracker.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
User wants to add to Assessment Template and Audit import/export files Issue Tracker configuration fields. 
1) User downloads an Import template that has the following columns about integration with Ticket Tracker:
- Ticket Tracker switch (on, off) (Turns on integration with Ticket tracker, On / Off options are possible)
- Hotlist ID
- Component ID
- Priority
- Severity
in case Hotlist ID, Component ID, Priority, Severity user left empty use Audit's values.
2) User fills in the Import template with new Assessment Templates or makes updates at existing Assessment Templates.
3) User imports the file. Appropriate fields are updated. 
4) User makes export of Assessment Template with the following columns about integration with Ticket …
> GGRC-5952/GGRC-5953 Import Issue Tracker settings for ASSESSMENT TEMPLATE/AUDIT objects

- src/ggrc/models/audit.py
- src/ggrc/models/mixins/rest_handable.py
- src/ggrc/services/common.py
- test/integration/ggrc/models/test_audit.py
- test/integration/ggrc/services/test_delete.py
If Assessment exists in scope of audit and user tries to delete an audit, there is no a proper message to explain that audit cannot be deleted.
1. Open any audit page;
2. Create an Assessment;
3. Delete an Audit.
Solution includes creating new `rest_handable.WithDeleteHandable` mixin and adding it to `Audit` model which implements `handle_delete` method to check whether Audit has assessments or not. If any assessments are present, an exception with new proper message will be raised.
> GGRC-5506 Proper message while deleting Audit with Assessments

- src/ggrc-client/js/components/gca-controls/gca-controls.js
- src/ggrc-client/js/components/gca-controls/gca-controls.mustache
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/mustache/assessments/modal_content_additional_fields.mustache
- src/ggrc-client/js/mustache/custom_attributes/modal_content.mustache
- src/ggrc-client/js/plugins/canjs_extensions.js
- src/ggrc-client/js/plugins/tests/canjs_extensions_spec.js
Apply one validation flow for fields and GCA fields
1. Have an object with global custom attributes. For example control.
2. Click 'Create' on LHN. For example on control.
_Actual result:_
mandatory global custom attributes are validated immediately  
regular fields (like assertions) are not validated immediately
_Expected result:_ all required fields are validated simultaneously.
Regular fields are validated when `_suppress_errors` prop is set. Use this prop for GCA.
> GGRC-5929 Fix validation flow for GCA

- src/ggrc/migrations/versions/20190108123221_4b53c40122a2_comment_read_write_for_task_assignees.py
Task assignees and secondary task assignees didn't have access to comments
to run migrations/utils/print_tree.py and check propagation tree of CycleTaskGroupObjectTask task assignees
New migration file has been created where propagation tree of CycleTaskGroupObjectTask was extended with comments
> GGRC-6321 Task Assignees can read/write comments

- src/ggrc-client/js/components/diff/instance-list-fields-diff.js
Fix typo in `modifiedDisplayNames` variable.
> QUICK-FIX Fix typo in modifiedDisplayNames

- src/ggrc/migrations/versions/20181120162305_e2ab6a7b6524_cleanup_object_people_out_of_proposal_.py
- src/ggrc/migrations/versions/20190115194014_b295575c706c_cleanup_task_group_objects_out_of_.py
JSON code passed in raw SQL query without escaping and can be potentially changed by sql server.
Create proposal with quotes in some field and change filtering on line 29 to let this proposal be migrated. After migrating proposal content should be correct JSON, with escaped quotes inside field \\"
Changed the way of forming sql query to sa.text and escaping JSON content.
> GGRC-6623 Fix case with quotes in content of proposal

- src/ggrc/migrations/versions/20190103151322_077caaf74f6b_change_format_of_fraud_related_key_.py
> QUICK-FIX Fix migration of proposal content

- src/ggrc-client/js/components/gca-controls/gca-controls.js
- src/ggrc-client/js/components/gca-controls/gca-controls.mustache
- src/ggrc-client/js/mustache/assessments/modal_content_additional_fields.mustache
- src/ggrc-client/js/mustache/custom_attributes/modal_content.mustache
Mandatory custom attribute is not unmarked as failed after been filled out
- Open Create Object modal w/ mandatory GCA
- Make some filled to be marked as invalid
- Fill this field w/ correct value
Actual behavior: Field is marked as empty
Expected behavior: Field should be marked as valid
Use 'if_helper' function to validate whether mandatory field is empty or not.
> GGRC-6624 Remove 'field-failure' class from gca after filling it

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
In case of changing the status of an assessment the UI part is changing immediately. At the same time in case of getting a server error like 4xx, 5xx, etc (except 409) after that the status will be not returned back and no message will be visible for a user. The goal of this story is to return status back and show an error for the user.
- Open any assessment.
- Disable network or ideally is to use a soft for intercepting requests/response and change status codes to 4xx, 5xx.
- Try to change the status of the assessment. For example by clicking on 'Complete' button
_Actual result_:
Status is not returned to the previous after getting an error.
No error message.
_Expected result_:
The status of the assessment was returned to the previous before changing the status.
The error message should …
> GGRC-5120 Error handling on Assessment Info pane on status change 

- src/ggrc/notifications/data_handlers.py
- src/ggrc/notifications/fast_digest.py
- test/integration/ggrc/notifications/test_review_notiffications.py
- test/unit/ggrc/notification/test_data_handlers.py
Currently emails with subject **"Proposal Digest"** are being sent when proposals to controls or risks are made. New subject should be in form **"GGRC Change requests review digest for [date in format MM/DD/YYYY] [time in format hh:mm:ss] [time zone name]"**
1. Go to any control / risk;
2. Click 'Propose Changes' button.
3. Modify something on 'Proposal for control / risk' pop-up and click 'Propose' button. Email is sent to admins and primary contacts for control / risk;
4. Email subject is in form **"GGRC Change requests review digest for [date in format MM/DD/YYYY] [time in format hh:mm:ss] [time zone name]"**
Solution includes:
1. Replacing `DIGEST_TITLE` variable in `ggrc/notifications/fast_digest.py` with new variable `DIGEST_TITLE_TMPL` which contains subject template.
2. …
> GGRC-6010 Proper subject for digest emails

- src/ggrc-client/js/components/delete-button/delete-button.js
- src/ggrc-client/js/components/delete-button/delete-button_spec.js
- src/ggrc-client/js/components/tree/tree-widget-container.js
- src/ggrc-client/js/entrypoints/dashboard/index.js
- src/ggrc-client/js/models/service-models/snapshot.js
- src/ggrc-client/js/mustache/modals/snapshot-related-objects.mustache
- src/ggrc-client/js/mustache/snapshots/dropdown_menu.mustache
- src/ggrc-client/styles/_modules.scss
- src/ggrc-client/styles/modules/_snapshot-related-objects.scss
- src/ggrc/models/snapshot.py
- src/ggrc/services/__init__.py
- src/ggrc/services/common.py
- src/ggrc/services/resources/snapshot.py
- test/integration/ggrc/services/resources/test_snapshot.py
We need to un-map snapshots (i.e. the objects versioned from the program into the audit) from audit.
**User flow:**
Open any audit at new tab
Click any snapshots tab
Choose any snapshot and click on it - snapshots info pane appears
Under '3 dots' click an option 'Delete'
Add logic to make possible to delete snapshots.
Add component `<delete-button>` which performs deleting of snapshot.
> GGRC-5638/GGRC-6435/GGRC-6436 Unmap snapshots from audit

- test/selenium/src/lib/base.py
- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/widget/info_panel.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/tests/test_my_work_page.py
> QUICK-FIX Improve stability of my work tests

- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/ui/workflow_ui_facade.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Add test task group creation

- src/ggrc/cache/memcache.py
- src/ggrc/cache/utils.py
- src/ggrc/converters/base.py
- src/ggrc/rbac/permissions.py
- src/ggrc/services/common.py
- src/ggrc/utils/memcache.py
- src/ggrc_basic_permissions/__init__.py
- test/integration/ggrc_basic_permissions/test_permissions_loading.py
- test/unit/appengine/test_memcache_blob_operations.py
To cache permissions in `memcache`, `permissions:list` was placed in default namespace, and `permissions:<user-id>` was placed in "permissions" namespace. However the function `clear_permission_cache():` was removing all permissions keys atomically using default permission. As result, user specific permissions were not removed properly, which leaded to some random error (such as intermittent 403 Forbidden and other errors).
1. Log in GGRC as Global Creator user
2. On MY dashboard click Start new program
3. Fill title and click Save and Close (before fix - 403 error was displayed until page reload)
5. Create a control in the program (before fix - control created by "create and map new object" was not displayed until page reload)
- No errors in the end of step 3
- No errors …
> GGRC-6606 Use default namespace for all permission keys to allow atomic deletion

- src/ggrc-client/js/components/delete-button/delete-button.js
When clicking on delete button on snapshot info pane then broken modal is shown.
1) Open audit
2) Map snapshot
3) Open info-pane of this snapshot 
4) Click 'Delete' button
Expected result: Delete confirmation modal is shown
After dynamic import use `module.default` to initialize controller for delete confirmation modal.
Alternative: add default static import of `modals_controller.js`.
> GGRC-6689 Create instance of controller for delete confirm modal

- src/ggrc-client/js/models/mappers/base-list-loader.js
- src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
- src/ggrc-client/js/models/mappers/direct-list-loader.js
- src/ggrc-client/js/models/mappers/index.js
- src/ggrc-client/js/models/mappers/list-binding.js
- src/ggrc-client/js/models/mappers/list-loader.js
- src/ggrc-client/js/models/mappers/mapping-result.js
- src/ggrc-client/js/models/mappers/multi-list-loader.js
- src/ggrc-client/js/models/mappers/proxy-list-loader.js
- src/ggrc-client/js/models/mappers/reifying-list-loader.js
- src/ggrc-client/js/models/mappers/search-list-loader.js
- src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
CanJS 3 does not support syntax like 
`can.Construct('GGRC.ListLoaders.BaseListLoader')`
Explicitly add list loaders to GGRC namespace through assignment.
> GGRC-6384 Explicitly create GGRC.ListLoaders

- src/ggrc-client/js/components/import-export/relevant-filter.js
- src/ggrc-client/js/components/import-export/test/relevant-filter_spec.js
- src/ggrc/fulltext/attributes.py
- src/ggrc/fulltext/mixin.py
- src/ggrc/fulltext/mysql.py
- src/ggrc/models/all_models.py
- src/ggrc/models/person.py
- src/ggrc/query/autocast.py
- src/ggrc/services/common.py
- test/integration/ggrc/api_helper.py
- test/integration/ggrc/services/test_search.py
- test/integration/ggrc_workflows/services/test_search.py
"Cycle", "Cycle Task Group", "Cycle Task" are missed in the "Mapped to" list on Export page
1. Open Export page.
2. Expand "Mapped to" list.
Actual result: Cycle, Cycle Task Group, Cycle Task are missed in the list.
Expected result: Cycle, Cycle Task Group, Cycle Task should be presented in the list. Search must work for all types by the following type fields: `title`, `name`, `email`, `notes`, `description`, `slug` (if corresponding fields exist)
Cycle, Cycle Task Group, Cycle Task were added to the "Mapped to" list.
> GGRC-6551 "Cycle", "Cycle Task Group", "Cycle Task" are missed in the "Mapped to" list on Export page

- src/ggrc-client/js/mustache/dashboard/lhn_search.mustache
JS error if click create button for Assessment in LHN.
1. Log in
2. Open LHN and expand Assessments
3. Click on create button
Actual Result: Create button is displayed for Assessment in LHN. JS error is displayed while clicking on it.
Expected Result: Create button should not be displayed for Assessment in LHN
This is regression after this [commit](https://github.com/google/ggrc-core/pull/8923/commits/3aa8c8db3a79532809bc8cd246f03916ec4c534c). There was missed `actions` attribute. `actions` is path to template which should be rendered in `<ul class="sub-actions"></ul>` (see this [logic](https://github.com/dnovikau/ggrc-core/blob/3aa8c8db3a79532809bc8cd246f03916ec4c534c/src/ggrc-client/js/controllers/lhn_controllers.js#L727)). For assessment it is defined with empty template in [lhn …
> GGRC-6683 Hide create button for assessments in LHN

- src/ggrc-client/js/components/events/event-item.js
- src/ggrc-client/js/components/events/event-item.stache
- src/ggrc-client/js/entrypoints/admin/index.js
- src/ggrc-client/js/templates/events/object_list.stache
- src/ggrc/access_control/people.py
- src/ggrc/migrations/versions/20181228140530_f0efc214e735_modify_access_control_people_keys.py
- src/ggrc/services/common.py
- test/integration/ggrc/converters/test_imported_api_requests.py
- test/integration/ggrc/models/test_event.py
- test/integration/ggrc/utils/test_referenced_objects.py
There is primary key in access_control_people table contains ('id','person_id', 'ac_list_id') fields. As the result we can't retrieve acp entry only by id, and `Events` page in `Administration` tab fails to open sometimes.
There is one more issue. Some events which were created by create_missing_revisions job have too much revisions. In this case 'response is too big' error happens.
Primary key modified to include only ('id') field. Unque constraint which contains ('person_id','ac_list_id') fields is added.
To fix the second part, events are returned with only first 100 of revisions. Revisions json is made smaller too.
> GGRC-6363/GGRC-6602 Fix server error on the events page

- .eslintrc.json
Actually we don't have one indent approach for functions.
1) Need to define with team members which config of this rules is preferable.
2) Apply this rules.
3) Fix existent eslint errors for this rules
> GGRC-6152 Add eslint indent rules 'FunctionDeclaration', 'FunctionExpression'

- src/ggrc-client/js/components/proposal/create-proposal.js
- src/ggrc/migrations/script.py.mako
- src/ggrc/migrations/utils/__init__.py
- src/ggrc/migrations/utils/fix_acl.py
- src/ggrc/migrations/versions/20181220123106_c3224a449d11_fix_admin_permissions_for_control_.py
- test/integration/ggrc/proposal/test_custom_creator_role.py
- test/selenium/src/lib/service/proposal_ui_facade.py
- test/selenium/src/tests/test_proposals.py
A user with Global Creator role cannot see Control Proposals which were created by him.
Steps 1-4 have to be run BEFORE the fix is applied!
1. Create user, make him Global Creator
2. Login as Admin, create custom role for Control with read permission only
3. As Admin, create a new Control -  add Global Creator user (created in step 1) to a list created in step 2
4. Login as user created in step 1, create proposal in control created in step 3
5. Apply change provided by current PR, run reindex (`jQuery.post('/admin/reindex')`)
6. Ensure that user now can see proposal created by him in step 4
7. Ensure that user can see all new proposal created by him
To fix the issue, the following changes are made:
1. Create corresponding record in `access_control_list` table for ProposalEditor and …
> GGRC-5091 Allow specifying ACL in Proposal creation request for Control

- src/ggrc/converters/base_row.py
- test/integration/ggrc/notifications/test_assessment_notifications.py
Email change notification in not sent when change assessment custom attribute using import
1. Create assessment through UI
2. Change it stats to Verified/Completed
3. Export it
4. Change value of any custom attribute and import it
Expected result: a notification about Assessment change is created
Actual result: the notification is not created
Signal to create notification has been added
> GGRC-1598 Email Assessment Change Notification is not Sent

- src/requirements-selenium.txt
Due to the issue https://github.com/pytest-dev/pytest/issues/4770 we need to have fixed more-itertools version <6.0.0.
> QUICK-FIX Add fixed more-itertools version

- test/selenium/src/lib/element/page_elements.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/modal/request_review.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_objects_review.py
Confirm user with Global Creator role assigned as REVIEWER is displayed on Program Info panel
> QUICK-FIX Confirm reviewer is displayed on Program Info panel

- src/ggrc/migrations/versions/20181228140530_f0efc214e735_modify_access_control_people_keys.py
- src/ggrc/migrations/versions/20190211084938_0472c1760a69_fix_acp_keys.py
Unique constraint was added incorrectly to acp table in [this commit](https://github.com/google/ggrc-core/pull/8881/commits/865ead6a0fbd8ebac5e5d4cc6cad9985c6d52b54).
> QUICK-FIX Fix acp keys migration

- src/ggrc/models/mixins/with_action.py
- test/integration/ggrc/models/test_assessment_file_url_and_status_put.py
Only Global Admin should be able to delete any Document and Evidence object
1. Add a user with Creator Role
3. Create URL or Document Evidence for newly created assessment
4. Add previously created user as Assignee to the assessment
5. Login with previously created user
6. Open assessment
7. Press 'Bucket' button near the evidence
Before changes:
- Evidence deleted
After changes:
- Forbidden Error
Evidence can be removed with PUT requests to assessment endpoint using remove_related action
Added permission checking to WithAction mixin for Evidence and Document objects
Added corresponding test
> GGRC-5311 Only Global Admin should be able to delete any Document and Evidence object

- src/ggrc-client/js/components/assessment/info-pane/create-url.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
- src/ggrc-client/js/components/related-objects/related-urls.js
- src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
- src/ggrc-client/js/plugins/tests/utils/url-utils_spec.js
- src/ggrc-client/js/plugins/utils/url-utils.js
At current moment input values for evidence & reference URLs are not validated anyhow. JavaScript could be injected to the page and used by intruder to still some sensitive data.
- Create object with reference or evidence url
- Add url like "javascript:alert(1)"
- Open object as another user
- Click this link
Actual result: JS is executed
Expected result: TBD. JS is not executed
Add validation method for reference and evidence url on input prior saving.
> GGRC-5155 Fix XSS in evidence/reference URLs

- src/requirements.txt
Kokoro build is failing because of 
```
setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
```
1. See that kokoro builds are passed.
2. Reduild local container
Update setuptools from 3.3 to 15.0
> QUICK-FIX Update setuptools from 3.3 to 15.0

- src/ggrc/models/control.py
- src/ggrc/models/mixins/synchronizable.py
- src/ggrc/utils/user_generator.py
- test/integration/ggrc/generator.py
- test/integration/ggrc/models/test_control.py
- test/integration/ggrc/snapshotter/__init__.py
Sync service grab ACL data from GGRCQ in format 
{role name: [{"name": user name, "email": user email}]}.
Example:
{
"Admin":
[
{"name": "Vasya, "email": "vasya@example.com"},
{"name": "Petia, "email": "petia@example.com"}
],
"Verifier":[...]
}
It's quite difficult and unperformant to convert such format of ACL to GGRC style, thus GGRC should be able to setup ACL using new style json.
If user is absent on GGRC side it should be created and get Global Creator role.
If received role is absent on GGRC side, BadRequest should be raised.
Try to create new control/update existing one with access_control_list in format specified above.
Created new mixin RoleableSynchronizable which inherit Roleable and use it in Control. Overrode `access_control_list` setter in this mixin.
> GGRC-6697 Update access_control_list setter for Synchronizable models

- src/ggrc/migrations/versions/20190212100125_59b41fe6c145_delete_deprecated_workflow_people_table.py
Delete deprecated Workflow_People table
To check if Workflow_People table still exist
Workflow_People table has been deleted
> GGRC-4205 Delete Deprecated Workflow People Table

- src/ggrc-client/js/components/tree/sub-tree-wrapper.js
- src/ggrc-client/js/components/tree/templates/sub-tree-wrapper.stache
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
- src/ggrc-client/styles/components/tree/_sub-tree-wrapper.scss
Currently there is no limit for number of Cycle Tasks to be loaded. In case there are huge number of Task for some Group there are some latency while opening Active Cycles tab on Workflow info page.
1. Create any WF in UI
2. Add 1000 tasks for the Group and activate WF
3. Open Active Cycles tab and expand tree view with CT
Actual result: Loading of all Tasks take some time
Expected result: Avoid latency on expanding Task Group
Add limitation for Tasks count to request body. Add pagination buttons to subtree for Tasks.
Add
> GGRC-5037 Add pagination button for cycle tasks on tree view

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/gdrive/gdrive_picker_launcher.js
- src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc-client/js/components/inline/inline-form-control.js
- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
- src/ggrc-client/js/components/snapshotter/scope-update.js
- src/ggrc-client/js/controllers/modals/delete_modal_controller.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js
- src/ggrc-client/js/models/conflict-resolution/tests/conflict-resolution_spec.js
- src/ggrc-client/js/plugins/tests/utils/notifiers-utils_spec.js
- src/ggrc-client/js/plugins/utils/errors-utils.js
- src/ggrc-client/js/plugins/utils/notifiers-utils.js
There is no message if Assessment update failed.
1. Remove revisions of some assessment from DB.
2. Try to add Comment or Evidence URL to this assessment.
3. Repeat several times.
**Actual results:** No error shown.
**Expected results:** Error message: "The object you are trying to update/map is broken. Please contact administrator for help."
Add `notifier` to `fail` handler in `addRelatedItem` method in `info-pane` to show error message.
Fix `conflict-resolution`: provide error handling on object update failure (this fixes 3rd step from **Steps to test the changes**).
Improve `notifierXHR` to parse XHR response text.
> GGRC-6530 Show error on Assessment update failure

- src/cron.yaml
- src/ggrc/contributions.py
- src/ggrc/notifications/common.py
- src/ggrc/views/cron.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
Revert splitting of nightly cron jobs since we want to receive notifications right after cycle task generation. Therefore we should execute nightly tasks one by one. 
The proper solution for the ticket GGRC-6594 will be discussed and prepared using ordinal git flow. 
* Run `nightly_cron_job` endpoint locally.
* Try to deploy cron.yaml file on any env. 
Revert changes of #8952 that are connected to jobs split. 
19ee9d2d7a9180128a7121bdc312d567301f1964
6a41d42dd18cbc9aabd3239ef582161d63c9d5aa
and move it to "Reopened" state.
> QUICK-FIX Revert GGRC-6594 splitting of nightly cron jobs

- src/ggrc/models/custom_attribute_definition.py
- test/integration/ggrc/services/test_custom_attributes.py
Reindex is failing for control and its snapshots in case we have CADs that are differ only by whitespaces. 
1. Create some cad with some title, e.g. 'abc'
2. Try to create another cad with the title with leading or trailing whitespaces. 
Expected result: creation of cad will fail.
1. Create some cad with some title, e.g. ' abc '
Expected result: CAD is created with a stripped title 'abc'
* Add strip on title validation
* Unify logic on title validation
> GGRC-6658 Strip custom attribute definition title on validation

- src/ggrc-client/js/components/import-export/import.js
- src/ggrc-client/js/components/import-export/templates/csv-import.stache
- src/ggrc-client/js/entrypoints/import/index.js
- src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
- src/ggrc-client/styles/modules/_import-export.scss
Add text and link to import page.
1. Open import page
2. Make sure that text and link were added to the page
3. Check that external link is correct
`getUrl` function was extended to get url with path only. Based on that is possible to get import url.
> GGRC-6672 Add text and link to import page

- src/ggrc-client/js/components/questionnaire-link/questionnaire-link.js
- src/ggrc-client/js/components/questionnaire-link/questionnaire-link.stache
- src/ggrc-client/js/components/tabs/tab-container.js
- src/ggrc-client/js/components/tabs/tab-container.stache
- src/ggrc-client/js/components/tabs/tab-link/tab-link.js
- src/ggrc-client/js/components/tabs/tab-panel.js
- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
- src/ggrc-client/js/templates/controls/info.stache
- src/ggrc-client/styles/_components.scss
- src/ggrc-client/styles/components/questionnaire-link/_questionnaire-link.scss
- src/ggrc-client/styles/components/tabs/_tab-container.scss
- src/ggrc-client/styles/modules/_info-pin.scss
- src/ggrc-client/styles/modules/_tabs.scss
1. Open control's info pane.
Expected result: links should be shown for tabs: "Change Proposals", "Version History", "Change Log".
Introduce `tab-link` component which will be setting `panels` like `tab-panel` component does:
Pros: one way how `panels` are set
Cons: `tab-link` will be added to content area (info.stache) and this is not the right place for component with such name
> GGRC-6664 Add external links functionality to tab-container component

- docs/source/backend/object_manipulation.rst
Delete mentions of Workflow_people and Workflow_person from the documentation
Review the following document: docs/source/backend/object_manipulation.rst
All mentions of Workflow people have been deleted
> QUICK-FIX: Update object manipulations

- src/ggrc-client/js/components/questionnaire-create-link/questionnaire-create-link.js
- src/ggrc-client/js/components/questionnaire-create-link/questionnaire-create-link.stache
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/templates/base_objects/search_actions.stache
- src/ggrc-client/styles/modules/_side-nav.scss
Create link on LHN should redirect to external `create` modal for Control.
1. Open LHN for Control
2. Click on '+ Create' link.
Use new `questionnaire-create-link` component.
> GGRC-6752 Update “Create” link on LHN for Control

- src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
- src/ggrc-client/js/models/business-models/control.js
- src/ggrc-client/js/templates/controls/info.stache
- src/ggrc-client/js_specs/models/object_state_spec.js
- src/ggrc-client/styles/_common.scss
Apply new styles to review states for Control in tree-view and on info-pane.
1. Update review state for any Control
`
update controls
set review_status="<review_status>", review_status_display_name="<review_status_display_name>"
where id = "control_id";
`
2. Refresh page
Possible review states:
**_review_status_**          : **_review_status_display_name_**
review_needed                 : Review Needed
re_review_needed             : Re-review Needed
reviewed_by_owner          : Reviewed by Owner
reviewed_by_compliance : Reviewed by Owner & Compliance
Set specific css classes to review blocks.
> GGRC-6668/GGRC-6666 Apply new styles to review states for Control

- src/ggrc/migrations/versions/20190213102427_3f80820cbf08_change_cycletaskgroupobjecttask.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- test/integration/ggrc_workflows/converters/test_cycle_status_update_over_import.py
- test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
- test/integration/ggrc_workflows/test_basic_workflow_actions.py
Error message is displayed on the import page to inform a user that Actual Finish Date is greater than Actual Verified Date. Empty field for Actual Finish Date leaves the date already stored in the DB intact (DateTime with time portion set), and filled field for Actual Verified Date sets it to a value (DateTime without time portion set); the resulting operation tries to set such an Actual Verified Date that violates our validation rules.
1. Create monthly wf, repeat one month (Verification flag - TRUE)
2. Add task to task group and activate workflow
3. Verify a cycle task
4. Export a cycle task
5. In cycle task csv template remove 'Actual Finish Date' (clean a value in cell) and save
6. Choose cycle task csv template to import and look at the import page after analyzing
Add migration to …
> GGRC-3849 Error message is displayed on the import page to inform a user that Actual Finish Date is empty

- src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
- src/ggrc-client/js/components/inline/base-inline-control-title.js
- src/ggrc-client/js/components/inline/base-inline-control-title.stache
- src/ggrc-client/js/templates/custom_attributes/info.stache
Add redirection for GCA.
Open info pane for some control which has gcas.
Names of GCA should be in lowercase and splitted by "_". Example:
"Long NamE" -> "long_name".
If text has several count of whitespaces then these whitespaces should be joined into '_'. Example:
```
"LoNg    Name" -> "long_name".
```
> GGRC-6767 Add redirection for GCA

- src/ggrc/converters/base_block.py
- src/ggrc/converters/errors.py
- src/ggrc/models/custom_attribute_definition.py
- src/ggrc/models/exceptions.py
- src/ggrc/utils/errors.py
- test/integration/ggrc/converters/test_import_assessment_templates.py
Incomplete error message is displayed while importing 'Assessment template' with a title of LCA as a field for Assessment
1. Go to Import page and download csv for 'Assessment template' object
2. Fill out required fields, add LCA with a title as a field for Assessment, e.g. 'ASSESSMENT PROCEDURE' > Save
3. Import csv 'Assessment template'
<b>Actual Result:</b>
"Line X: the attribute name already exists at this object type. Please choose another attribute name and restart the import." is displayed as error message.
<b>Expected Result:</b>
Assessment template should not be imported with a title of LCA as Assessment has (GCA, custom roles, GCAs);
make a proper error to inform a user that importing LCA with a title of field for Assessment is prohibited: "Line X: the …
> GGRC-4811 Fix error message for AssessmentTemplate import

- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
- test/integration/ggrc/integrations/test_bulk_issue_generate.py
- test/integration/ggrc/integrations/test_issue_sync_job.py
Download Issue/Assessment template to Google sheet
2. Open it
3. Fill out required fields
4. Set 
Priority = P2
Severity = S2
Type = BUG
Component ID = 64445
Hotlist ID = 700706
5. Import Issue
6. Open Issue in UI: TICKET TYPE = 'BUG'
7. Click on Ticket Tracker link to Open Issue Tracker and look at the Issue Type
Actual Result: User is able to create Issue with Issue Type = 'Bug' via Import
Reproduce steps from Issue description. 
Expected Result: User should not be able to create Issue/Assessment with Issue Type = 'Bug' via Import. Only 'PROCESS' type is possible. Should be a warning message that 'BUG' is incorrect Issue Type. The default value will be used - PROCESS
I've just removed Bug from allowed types.
> GGRC-6400 User is able to create Issue with Issue Type = 'Bug' via Import

- src/ggrc-client/js/components/people/people-list-info.js
- src/ggrc-client/js/components/people/people-list-info.stache
- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
- src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
- src/ggrc-client/js/templates/assessments/header.stache
- src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
- src/ggrc-client/js/templates/cycles/info.stache
- src/ggrc-client/js/templates/people/dropdown_menu.stache
- src/ggrc-client/js/templates/workflows/info.stache
- src/ggrc-client/styles/_common.scss
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/info_widget_three_bbs.py
- test/selenium/src/lib/element/three_bbs.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/service/webui_facade.py
We have duplicated templates for <three-dots-menu> to manage empty list.
Test three-dots-menu buttons on info-pane for different objects including people on admin-page and cycles, tasks, group tasks on workflow page.
Replace duplicated templates (search by class `btn-3bbps`) on `<three-dots-menu>` component. Delete common conditions which check whether the button should be displayed.
> GGRC-6117 Unify three-dots button by using common component

- src/ggrc/converters/handlers/issue_tracker.py
- src/ggrc/integrations/constants.py
- src/ggrc/models/hooks/issue_tracker/assessment_integration.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
1. Login ggrc app and open import page
2. Download Audit template
3. Fill out required fields and import it
4. Open Edit Audit modal popup
5. Turn ON Issue Tracker and look at the default values
Actual Result: Default value for Issue Tracker (Hotlist ID) is not the same as for UI if audit is created via import
Reproduce steps from issue description. 
Expected result: it should be the same as for UI (you can find it in a ticket).
I've splitted issue hotlist id cause it's specific.
> GGRC-6690 Improve default value for Issue Tracker if audit is created via import

- README.md
Control object will be made readonly (except possibility to create mappings for some objects). The alternative branch will contain CRUD functionality for controls and README.md will contain note regarding that.
It's possible to verify text in this pull request and see how it looks like here: https://github.com/romamatusevich/ggrc-core/tree/GGRC-6763#quick-start
Note regarding control object is added to README.md.
> GGRC-6763 Add note for controls to README.md

- src/ggrc/builder/json.py
- src/ggrc/models/mixins/__init__.py
- test/integration/ggrc/api/test_folder_field.py
- test/integration/ggrc/models/mixins/test_protected_attributes.py
We need to prevent altering of protected field for external user. Currently there is only "folder" field that should be protected.
1. Create object with "folder" field. Ex: Risk
2. Login as external user
3. Update "folder" field for created object
4. "folder" field should not be modified
Created mixin that identifies protected fields. API checks if model has protected fields and remove them from request body.
> GGRC-6830 Protect folder attribute

- src/ggrc/migrations/versions/20190226124913_7d10655e87f9_remove_title_unique_contraint_from_.py
- src/ggrc/models/control.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/models/test_control.py
Backend should not validate uniqueness of title column of Control.
1. Create first control with custom title
2. Create second control with the same title
3. Second control should be created properly
Created migration that drop constraint from control title column.
> GGRC-6813 Remove unique title constraint from Control

- src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
- src/ggrc-client/js/templates/controls/info.stache
- src/ggrc-client/styles/_common.scss
Review Status is not displayed in Global Search for Control.
1. Open Global search
2. Search by Control
3. Add Review Status column
**Actual result:** Review status is not displayed
**Expected result:** Review status is displayed.
Use correct prop to display.
> GGRC-6840 Display external review status in global search

- src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js
- src/ggrc-client/js/plugins/utils/ggrcq-utils.js
> QUICK-FIX Update external urls

- README.md
Year in **Copyright Notice** section in README.md is still 2018.
> QUICK-FIX Update year in copyright notice

- src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py
- src/ggrc/integrations/synchronization_jobs/sync_utils.py
All info messages currently are printed into error level of logging. 
It leads to a lot of error reports on the dev env. 
I propose to move these error messages into the appropriate levels: Info/warning.
Impact: messy logs, actual error could be missed.
1. Deploy. 
2. Run Issue Tracker Cron job.
3. Check logs.
There were a trouble with info level logging during holistic solution implementation and error level has been put to these logs. 
I've checked now it's ok and I've changed logging levels.
> GGRC-6720 Print info messages during hourly issue tracker sync

- src/ggrc-client/js/components/gdrive/gdrive_folder_picker.js
- src/ggrc/__init__.pyi
- src/ggrc/views/__init__.py
- src/ggrc/views/folder.py
- test/integration/ggrc/__init__.py
- test/integration/ggrc/views/test_folder.py
We have restricted updates for controls for regular users it brakes add/remove folder functionality.
We need to create 2 endpoints
1) POST `/api/add_folder`
`{ "object_type": "Control", "object_id":1, "folder": "some_id" }`
if folder in request is already set to this value, HTTP code 200 is returned
2) POST `/api/remove_folder`
`{ "object_type": "Control", "object_id":1, "folder": "some_id" }`
those endpoints should save/remove folder information to object.folder to db.
If folder in request is not equal to folder value of the object, HTTP code 400 is returned
Responses:
1) In case of success - HTTP code 200, no content in response
2) In case of failure - HTTP code other than 200, content is error message in HTML format
Other requirements:
only logged in regular GGRC users who have …
> GGRC-6831 Add endpoints to add/remove folder

- provision/docker/vagrant.bashrc
1. `bin/containers setup dev`
2. run `refresh` inside container
Add `refresh` alias to run set of commands needed to completely refresh FE packages:
```
rm -rf node_modules/*
git checkout package-lock.json
npm i --unsafe-perm
```
> QUICK-FIX: 'refresh' alias for packages on FE

- src/ggrc-client/js/components/inline/base-inline-control-title.js
- src/ggrc-client/js/templates/custom_attributes/info.stache
Title of GCAs for Assessment are missed on Other Attributes tab.
1. Open existing Assessment in ggrc.
2. Other attributes tab > Look at the GCAs titles: are missed.
3. Add a new GCA for assessment and look at the the GCA title of assessment: is missed.
Actual Result: Title of GCAs for Assessment are missed on Other Attributes tab.
Expected Result: Title of GCAs for Assessment should not be missed on Other Attributes tab.
Use `leakScope: false` for `<base-inline-control-title>` component.
> GGRC-6852 Title of GCAs for Assessment are missed on Other Attributes tab

- src/ggrc/migrations/versions/20190306053803_22624692e663_add_control_assertions.py
Add control assertions for demo. 
check all appropriate control assertions are in appropriate places
Assertions are kept in our categories table
> GGRC-6872 Add values to Control Assertions attribute

- src/ggrc/models/mixins/after_flush_handleable.py
This mixin is just pulled from another PRs (https://github.com/google/ggrc-core/pull/9075) because it will be used in different places before that big pr will be merged
Just check if the code looks okay, and that it is not used anywhere and that it does not affect anything.
This mixin should be used to verify attributes on an object that are
dependent on each other. Those can't be verified with @validate because
the order in which they are set is not defined and that might break
validation.
> QUICK-FIX Add after flush handleable mixin

- src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
- src/ggrc-client/js/components/tree/templates/tree-header.stache
- src/ggrc-client/js/controllers/inner-nav-controller.js
- src/ggrc-client/js/models/business-models/project.js
- src/ggrc-client/js/router.js
- src/ggrc-client/js/templates/partials/modal-ajax-test-plan.stache
- src/ggrc-client/js/templates/projects/modal_content.stache
- src/ggrc/views/__init__.py
Rename Project to Account Balance
Please check the cases described in spreadsheet.
`title_singular` was added to `project` model and `internav_display` was updated to handle cases connected with renaming.
> GGRC-6876 Rename Project to Account Balance

- src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js
- src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache
- src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.stache
- src/ggrc-client/js/components/advanced-search/advanced-search-filter-group.js
- src/ggrc-client/js/components/advanced-search/advanced-search-filter-group.stache
- src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.stache
- src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
- src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
- src/ggrc-client/js/components/dropdown/autocomplete-dropdown.js
- src/ggrc-client/js/components/dropdown/autocomplete-dropdown.stache
- src/ggrc-client/js/components/people/editable-people-group-header.js
- src/ggrc-client/js/components/people/editable-people-group-header.stache
- src/ggrc-client/js/components/related-objects/related-people-access-control.js
- src/ggrc-client/js/components/tree/templates/tree-header.stache
- src/ggrc-client/js/components/tree/templates/tree-visible-column-checkbox.stache
- src/ggrc-client/js/components/tree/tree-header.js
- src/ggrc-client/js/components/tree/tree-visible-column-checkbox.js
- src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js
- src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
- src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache
- src/ggrc-client/js/helpers.js
- src/ggrc-client/js/models/business-models/control.js
- src/ggrc-client/js/plugins/ggrc_utils.js
- src/ggrc-client/js/plugins/utils/tree-view-utils.js
- src/ggrc-client/js/templates/base_objects/modal-content-reference-urls.stache
- src/ggrc-client/js/templates/base_objects/reference-urls.stache
Need to check spreadsheet which attributes should be changed.
Need to check spreadsheet which attributes should be changed.
Created util which returns needed attribute name.
> GGRC-6851 Make changes in Object fields

- package-lock.json
- package.json
- src/ggrc-client/js/components/assessment/mapped-control-related-objects/mapped-control-related-objects.stache
- src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
- src/ggrc-client/js/components/form/field-views/rich-text-form-field-view.stache
- src/ggrc-client/js/components/inline/readonly-inline-content.stache
- src/ggrc-client/js/components/object-list-item/comment-list-item.stache
- src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.stache
- src/ggrc-client/js/components/read-more/read-more.js
- src/ggrc-client/js/components/related-objects/related-issues.stache
- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
- src/ggrc-client/js/templates/assessments/modal_content.stache
- src/ggrc-client/js/templates/audits/info.stache
- src/ggrc-client/js/templates/base_objects/description.stache
- src/ggrc-client/js/templates/base_objects/mapper-item-description.stache
- src/ggrc-client/js/templates/base_objects/notes.stache
- src/ggrc-client/js/templates/base_objects/test_plan.stache
- src/ggrc-client/js/templates/controls/info.stache
- src/ggrc-client/js/templates/cycle_task_groups/info.stache
- src/ggrc-client/js/templates/cycles/info.stache
- src/ggrc-client/js/templates/issues/remediation_plan.stache
- src/ggrc-client/js/templates/risk_assessments/info.stache
- src/ggrc-client/js/templates/risks/info.stache
- src/ggrc-client/js/templates/workflows/info.stache
Application should be able to read and properly display markdown format for rich text fields (only Controls in scope of this ticket)
1. Pass some markdown format syntax into rich text field of Control, e.g. (some link)[http://link.com]
2. Perform all check from migration checklist
3. Check that tests of `HTML2MarkdownParser` satisfy requirements stated in the ticket.
Add `showdown` package which parses markdown into html.
1. Implement `HTML2MarkdownParser` that is able to parse html to markdown.
2. Implement migration that move from html to markdown the following objects:
* Comments for control (external_comments)
* Custom attribute values for Controls
* Rich text attributes for Control: title, description, test_plan, notes
> GGRC-6818/GGRC-6819/GGRC-6820 Update rich texts syntax

- src/ggrc-client/js/components/assessment/assessment-people.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
- src/ggrc-client/js/components/assessment/request-review/request-review-roles.js
- src/ggrc-client/js/components/assessment/request-review/request-review-roles.stache
- src/ggrc-client/js/components/assessment/request-review/request-review.js
- src/ggrc-client/js/components/assessment/request-review/request-review.stache
- src/ggrc-client/js/components/assessment/templates/assessment-people.stache
- src/ggrc-client/js/components/autocomplete/autocomplete.stache
- src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
- src/ggrc-client/js/components/people/editable-people-group.js
- src/ggrc-client/js/components/related-objects/related-people-access-control.js
- src/ggrc-client/js/components/simple-modal/simple-modal.js
- src/ggrc-client/js/controllers/inner-nav-controller.js
- src/ggrc-client/js/plugins/utils/local-storage-utils.js
- src/ggrc-client/js/router.js
- src/ggrc-client/js/templates/assessments/header.stache
- src/ggrc-client/js/templates/assessments/modal_content.stache
- src/ggrc-client/styles/_common.scss
- src/ggrc-client/styles/components/info-pane/_info-pane.scss
- src/ggrc-client/styles/components/object-review/_object-review.scss
- src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
- src/ggrc/views/__init__.py
Assessment verification should be performed multiple times by different people.
- Open Assessment info-page
- Click 'Edit Verifiers'
- Fill all groups with appropriate people then click 'Proceed'
- Add multilevel review component
> GGRC-6851 Make multilevel review verification

- src/ggrc/templates/notifications/fast_digest.html
Incorrect message for Object review digest.
1. Create a control and mark as Review
2. Move control to Unreviewed state (change title)
3. Open email and look at the notification from Object review digest
Corrected the text message in "fast_digest.html" file
> GGRC-6700 Correct object review digest message

- src/ggrc-client/js/components/assessment-templates/template-field/template-field.js
- src/ggrc-client/js/components/custom-autocomplete/autocomplete-wrapper.js
- src/ggrc-client/js/components/dropdown/dropdown.js
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/models/cacheable.js
- src/ggrc-client/js/models/custom-attributes/custom-attributable.js
- src/ggrc-client/js/models/custom-roles/roleable.js
- src/ggrc-client/js/models/mappers/custom-filtered-list-loader.js
- src/ggrc-client/js/models/mappers/direct-list-loader.js
- src/ggrc-client/js/models/mappers/multi-list-loader.js
- src/ggrc-client/js/models/mappers/proxy-list-loader.js
- src/ggrc-client/js/models/mappers/search-list-loader.js
- src/ggrc-client/js/models/mappers/stub-filtered-list-loader.js
- src/ggrc-client/js/models/refresh_queue.js
- src/ggrc-client/js/models/service-models/search.js
- src/ggrc-client/js/plugins/autocomplete.js
- src/ggrc-client/js/plugins/lodash_helpers.js
- src/ggrc-client/js_specs/models/cacheable_spec.js
**can.map** utility is potentially unsupported by CanJs 3.
Use **_.map** instead of **can.map**.
Also, I added **_.filter**, because **can.map** filters items by **null** and **undefined**.
> GGRC-6614 To use _.map instead of can.map

- src/ggrc-client/js/components/assessment/assessment-people.js
- src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.js
- src/ggrc-client/js/components/assessment/controls-toolbar/controls-toolbar.stache
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
- src/ggrc-client/js/components/assessment/templates/assessment-people.stache
- src/ggrc-client/js/components/custom-roles/custom-roles.js
- src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
- src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.stache
- src/ggrc-client/js/components/people/editable-people-group-header.js
- src/ggrc-client/js/components/people/editable-people-group.js
- src/ggrc-client/js/plugins/ggrc_utils.js
- src/ggrc-client/js/templates/assessments/header.stache
verifiers -> current verifiers.
Show verifiers of the current level of review.
> GGRC-6919 Show Verifiers of current level of review

- src/ggrc/models/person.py
- test/integration/ggrc/services/test_authorizations.py
Fix Global Search of People by Authorizations
1. Log in to GGRC app
3. Select 'People' object type
4. Select filter query Authorizations and click Search button
Expected result: Filter should be applied for People by Authorizations
"Authorizations" has been added to FellTextAtrr
> GGRC-6366 Fix Global Search by Authorizations

- src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
- src/ggrc-client/js/components/people/editable-people-group-header.js
Counts are incorrect for roles.
1. Open an assessment
2. Check that values for roles are correct
Return people length for all roles except verifiers.
> QUICK-FIX Fix counts for roles on Assessment's info pane

- src/ggrc-client/js/components/people/people-group-modal.js
- src/ggrc-client/js/components/people/templates/people-group-modal.stache
People group titles are not correct on simple modals.
Open any object
Fill any group w/ 5+ people
Click 'See more' button
Actual behavior: Title for selected group is not correct
Use helper to change title value.
> QUICK-FIX Fix people group titles on simple modals

- README.md
Set 2019 date in copyright section of README
> DOCS: Update copyright date in readme

- src/ggrc/migrations/alembic.ini
- src/ggrc/migrations/script.py.mako
Currently we have some issues with alembic:
1. Our `alembic revision --autogenerate` command raises python exception. 
2. Our alembic versions look too bulky.
3. As we don't support downgrade we can put NotImplemented exception to our downgrade.
Check alembic commands and verify result is ok.
i.e. 
- `alembic revision --autogenerate -m "message"`, 
- `alembic revision -m "message"`,
- `alembic revision`
I've just fixed this issues.
> QUICK-FIX Update alembic scripts.

- src/ggrc-client/js/components/assessment/templates/assessment-people.stache
- src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.stache
Add warning message when 4 and 5 levels of review are empty
1. Create and open an assessment
2. Add verifiers for three levels
3. Verify three levels
Expected result: verify button is no shown and the message is displayed
Add message and apply behavior based on flag `isVerifyBtnDisabled`
> QUICK-FIX Add warning message when 4 and 5 levels of review are empty

- src/ggrc-client/js/components/assessment/request-review/request-review.stache
- src/ggrc-client/js/components/simple-modal/simple-modal.js
Fix saving of roles
1. Open an assessment
2. Add 5+ people for a role
3. Open inline-edit popup
4. Add/remove people
5. Save
Actual result: people are not saved
Expected result: people are saved
Rename `save` to `saveUpdatedReviewGroups`
> QUICK-FIX Fix saving of roles

- src/ggrc/query/custom_operators.py
- test/integration/ggrc/services/test_query/test_basic.py
- test/integration/ggrc/test_csvs/risk_special_chars_in_description.csv
'_', '\\' and '%' are special characters in LIKE operator strings and should be escaped in order to get proper search results.
1. Open Global Search.
2. Use Object type, which contains Description attribute (for example, Risk).
3. Use filter: Description contains 5_.
Actual result: BE returns results, which don't contain "5_" string.
Expected result: BE returns results which contain "5_" string.
Escape '_', '\\' and '%' chars.
> GGRC-6874 Incorrect search results when description includes special chars

- src/ggrc/migrations/versions/20181218084229_f1130618060e_add_control_default_assertion_if_none.py
- src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
Migration of Control Comments to ExternalComments changed creators of comments to system user.
1. Open ggrc app and create a control 
2. Add a comment 
3. Run migration ggrc->ggrcq and ggrcq->ggrc sync
4. Open the control in ggrc app and look at the name of the comment creator
 Actual Result: 'ggrc-system@google.com(Inactive user)' is displayed
 Expected Result: real user 'name'@google.com should be displayed (e.g. vvechar@google.com)
Insert modified_by_id into external_comments from comments table.
> GGRCIE-4747 Set proper creator in migration for Control Comments

- src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
- test/integration/ggrc/models/test_control.py
After migration Comments to ExternalComments Admin is not assigned automatically to Control Comment.
1. Create new comment on Control
2. Check if current user assigned as Admin on this Control
Actual result: he's not assigned
Expected result: he's assigned
Add Admin role to ACR, update related rows in ACL. Create new Admin acp entry on ExternalComment POST.
> GGRC-6926 Add Admin role for ExternalComments

- src/ggrc-client/js/templates/modals/snapshot-related-objects.stache
Improve the message while deleting snapshot.
1. Open audit page with mapped snapshot
2. Click on Delete button in 3 bb menu on snapshot
3. Look at the confirmation popup
Corrected the text message in "snapshot-related-objects.stache" file.
> GGRC-6705 Improve deleting snapshot message

- src/ggrc/converters/column_handlers.py
- src/ggrc/models/reflection.py
- Removes Remove redundant 'due_on' field from BE code.
- Run the build_assets command.
- Once the assets are build successfully run the launch_ggrc command in the container.
- Removed the due_on field from the column_handlers.py and reflection.py files in BE code.
> GGRC-6512 Remove redundant 'due_on' field

- README.md
We have an incomplete section on running integration tests since we added external users
run 
```
nosetests /vagrant/test/integration/ggrc/models/mixins/test_customattributable.py
```
and see some tests fail. then follow the instructions and all tests should pass.
> DOCS Update readme for running integration tests

- bin/do_deploy
> QUICK-FIX Add --no-promote for custom versions in do_deploy script

- src/ggrc/converters/handlers/issue_tracker.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
the ticket is reopened due to following case:
1. Open Audit with Issue Tracker off
2. Download Assessment import template
3. Fill out required fields, set Ticket Tracker ON
4. Import Assessment
5. Look at the issue tracker for assessment in tree view on UI: is ON
Actual Result: Issue Tracker is ON for asmt while Issue Tracker is OFF for audit
Expected Result: Issue Tracker is OFF for asmt while Issue Tracker is OFF for audit
Reproduce issue and check expected Result. 
I've added appropriate functionality to imports.
> GGRC-6391 For Assessments with empty Ticket Tracker configuration fields use values from Audit

- test/selenium/src/lib/element/page_elements.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/service/rest/template/risk.json
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_proposals.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Change controls to risks in order to test proposals

- test/selenium/src/lib/constants/roles.py
- test/selenium/src/tests/test_admin_dashboard_page.py
> QUICK-FIX Fix tests for events on admin page

- README.md
We were missing any info for developer on what to do when we add a new JS package.
add a new custom js package or switch between commits that add one and remove one and try the instructions if they work.
add notes on how to properly install missing JS packages.
> DOCS Add JS package update docs

- src/ggrc-client/js/models/mappers/mappings-ggrc.js
Cannot map Requirements, Policy, Contracts to Control in ggrc
1. Log in ggrc app and open all objects page
2. Open Requirements tab
3. Map Control to any Requirement via Unified mapper
No controls in Search result in Unified mapper
'Open new frontend' button is displayed
**Expected Result:** Controls should be displayed in Search results. User should be able to map controls to Requirements, Policy, Contracts is ggrc app
Update mappings config.
> GGRC-6938 Allow map Control to Requirement, Contract, Policy

- src/ggrc/converters/base_row.py
- src/ggrc/converters/handlers/comments.py
- src/ggrc/models/hooks/relationship.py
- src/ggrc/notifications/common.py
- src/ggrc/notifications/people_mentions.py
- src/ggrc/settings/default.py
- src/ggrc/templates/notifications/bulk_child_sync_exception.html
- src/ggrc/templates/notifications/bulk_child_sync_failed.html
- src/ggrc/templates/notifications/bulk_child_sync_succeded.html
- src/ggrc/templates/notifications/bulk_sync_exception.html
- src/ggrc/templates/notifications/bulk_sync_failed.html
- src/ggrc/templates/notifications/bulk_sync_succeded.html
- src/ggrc/templates/notifications/email_mentioned.html
- src/ggrc/templates/notifications/import_export.html
- src/ggrc/templates/notifications/style.html
- test/integration/ggrc/models/mixins/test_with_action.py
- test/integration/ggrc/notifications/test_assignable_notifications.py
- test/integration/ggrc/notifications/test_people_mentions.py
- test/unit/ggrc/notification/test_people_mentions.py
This PR has following dependency:
As a user I want mention person at comments so that he received a notification about it.
Add feature: possibility to mention person in the comment with autocomplete.
1. Test comment import with mention
2. Test comment creation with mention
1. Send notifications with a hook on relationship to comment creation
2. Send notifications after the row commit when doing import
> GGRC-6712 Send notifications on person mentions in the comments

- src/ggrc/migrations/versions/20190221143740_3b6acfd18e5c_create_external_comments_table.py
After migration Control Comments have same creation datetime (equal to migration datetime).
Check if time of Comments creation before migration is the same with time after migration.
Copy creation time of Control Comments to ExternalComments
> QUICK-FIX Copy creation time of Control Comments to ExternalComments

- src/ggrc/migrations/versions/20190218090347_da49d3baf2ec_add_ggrcq_attributes_for_control.py
- src/ggrc/models/control.py
- test/integration/ggrc/models/test_control.py
- test/integration/ggrc/models/test_snapshot.py
Initial request was modified to fit external app naming.
Run updated test and check that fields are populated during post/put request for control
Rename DB table attributes, update control model
> QUICK-FIX Rename control external attributes

- src/ggrc/templates/notifications/email_digest_content.html
Email about new comment in cycle task has invalid link.
Login to GGRC application
1. Create a workflow with task
2. Activate workflow
3. Add assignee or secondary assignee to the cycle task
4. Add comment to the cycle task
5. Open Daily digest
Actual: Link to the cycle task is invalid 
Expected: According to Hanna title of the cycle task should be a regular text (not a link) as there is no info page for a cycle task
Updated title of the cycle task to be a regular text (not a link) as there is no info page for a cycle task.
> GGRC-6335 Updated title of the cycle task to be a regular text (not a link) in email

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Look at the 'Evidences for Assessments and Audits' section in 'What's new' popup.
1. Log in to GGRC
2. Look at the 'Evidences for Assessments and Audits' section in 'What's new' popup
Actual Result: Extra spaces are shown
Expected Result: Extra spaces should not be shown
Remove the extra white spaces in the Whats new pop information page.
> GGRC-5816 Remove the extra spaces from the release-notes.md

- src/ggrc-client/js/components/object-mapper/create-and-map.js
- src/ggrc-client/js/components/object-mapper/object-mapper.stache
- src/ggrc-client/js/components/object-mapper/tests/create-and-map_spec.js
JS error while opening Unified Mapper from Assessment modal window.
This PR fixes regression(f66e4441c0dcf99cc1456c782cbbe626df76ab94).
1. Log in ggrc app
2. Open any audit page > Assessment tab
3. Invoke New Assessment modal window
4. Click on Map Objects button
Actual Result:
• Uncaught (in promise) TypeError: Cannot read property 'constructor' of null' error occurs 
• Unified mapper is not displayed
Expected Result: no errors, Unified mapper should be displayed 
Use `sourceType` instead of `model_singular`.
> GGRC-6932 JS error while opening Unified Mapper from Assessment modal window

- src/ggrc/notifications/job_emails.py
- src/ggrc/views/converters.py
Not correct email notification text for failed exports cases
Make Export Fail. Check the email body text is correct
Change email template for EXPORT_FAILED case
> GGRC-4945 Improve email body if export did not finish due to errors

- src/ggrc/models/custom_attribute_value.py
- src/ggrc/utils/url_parser.py
- test/integration/ggrc/models/test_control.py
- test/unit/ggrc/utils/test_url_parser.py
Parser for html links (CAVs) can't work with unicode symbols
Run unittests 
Change type of strings to unicode
> QUICK-FIX fix unicode in parser

- src/ggrc/converters/base.py
- src/ggrc/converters/base_block.py
- src/ggrc/converters/base_row.py
- src/ggrc/utils/benchmarks.py
Currently we have quite little information about export procedure progress. In case of performance issues with export there is no useful information in logs that may help to find the reason.
Run export of some objects and check logs. They should contain information about how much time we spend on processing rows and columns during export.
Add benchmarks to export procedure. Add measuring of slowest column handing.
Tested on perf db on custom instances with 10 workers with memcache enabled.
Export with benchmarks:
4805 Controls
165.1 s
190.9 s
183.3 s
100 Assessments (Audit 4042)
119.5 s
119.8 s
Without benchmarks:
4805 Controls
166.9 s
181.2 s
179.3 s
100 Assessments (Audit 4042)
113.5 s
119.3 s
> GGRC-6911 Add benchmarks for export functionality

- src/ggrc-client/js/models/business-models/issue.js
- src/ggrc/converters/handlers/issue_tracker.py
- src/ggrc/integrations/constants.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
- test/unit/ggrc/models/hooks/issue_tracker_integration/test_params_builder.py
This PR is `on hold` until the dependencies would be resolved:
The default component_id populated for new issue point to evidence gathering instead of audit findings. Please modify the default component_id for new issues to appropriate value.
1. deploy instance and create new issue via UI/import without component id. 
2. look if default value for component id is correct.
I've added this logic to backend and frontend.
> GGRC-6871 Modify the default component_id for issues

- src/ggrc-client/js/components/page-header/page-header.stache
Fix incorrect tooltip of GGRC logo
1. Log in GGRC app 
2. Open My Work page 
3. Hover over GGRC logo
Actual Result: 'GRC' tooltip is displayed
Expected Result: 'GGRC' tooltip should be displayed
Tooltip was renamed
> GGRC-6484 Fix incorrect tooltip of GGRC logo

- src/ggrc-client/js/components/assessment/assessment-generator-button.js
Assessment is generated with option's type instead of selected object's type
1. Create program with mapped control and section
2. Create an audit in scope of the program
3. Open the audit summary page
4. Click Autogenerate button
5. Select 'Sections' object type, check Control in Search results and click Generate Assessment' button
_Actual Result_: Assessment was generated with Section type. Control snapshot is displayed in Related information.
_Expected Result_: Assessment should be generated with control type.
Use "snapshot.child_type" instead of "options.type" to generate Assessments
> GGRC-5633 Assessment was generated w/o control type

- src/ggrc/models/mixins/issue_tracker.py
- test/integration/ggrc/converters/test_export_csv.py
- test/integration/ggrc/converters/test_export_ticket_tracker.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/converters/test_import_issuetracked_objects.py
- test/integration/ggrc/test_csvs/issuetracker_no_warnings.csv
1. Download Issue/Assessment template to Google sheet
2. Open it
Actual Result: "Issue Title" is displayed
Expected Result: "Ticket Title" should be displayed
Make steps from Issue description. Check if Column is named Ticket Title. 
I've just renamed alias and fixed existing tests.
> GGRC-6394 Rename "Issue Title" to "Ticket Title"

- src/ggrc-client/js/components/tree_pagination/tree_pagination.stache
- src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
- src/ggrc-client/styles/components/tree_pagination/_tree_pagination.scss
1. Open mapper, search for some objects.
2. Change height of the browser window.
Fix pagination border.
> QUICK-FIX Fix pagination styling

- src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
Incorrect type for document/evidence in Global search/unified mapper
1. Log in ggrc-app
3. Select document object type
4. Search and set Type column in the search results
**Actual Result:** Incorrect type for document/evidence screenshot-1.png
**Expected Result:** Display correct type for document/evidence.
As `kindTitle` is function, it cannot be used in `firstnonempty` helper.
> GGRC-6866 Display type correctly for Document/Evidence in global search

- src/ggrc/services/suggest.py
- test/integration/ggrc/services/test_suggest.py
Persons suggest does not have a limit for query results.
Launch app locally and set `INTEGRATION_SERVICE_URL` equal to "mock".
Try mention people in the comments (like @abc) and see in the network tab responses from the suggest api. 
Limit db select results by parameter passed in the request.
> GGRC-6760 Add limit for mock of persons suggest

- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/tests/test_create_object.py
> QUICK-FIX Added test for no modal after clicking create control

- src/ggrc/notifications/job_emails.py
Email sent to user after Import job failed due to a server error required an improvement.
The body of an email sent to user has been changed.
> GGRC-6519 Improve the message due to error

- test/selenium/src/lib/utils/random_utils.py
Generated string could form escape sequence for object names in selenium tests. 
Remove backslash from characters set
> QUICK-FIX Fix chars set for random strings generation

- src/cron.yaml
GAE has single config for all services. We need to update it with job for sync_service
This not an executable code just configuration.
run and check that ggrc sync job in the cron job list
gcloud app deploy cron.yaml
Regular cron configuration
> QUICK-FIX Update cron.yaml with ggrc sync job for sync service

- src/ggrc/models/audit.py
- src/ggrc/utils/errors.py
- test/integration/ggrc/models/test_audit.py
Error message on deleting Audit with assessment is not correct
1. Create : Program > Audit > Assessment
2. Try to delete Audit
1. Changed error message.
2. Fix test case for this case.
> GGRC-6508 Error message on delete Audit case

- src/ggrc-client/js/controllers/dashboard_widgets_controller.js
- src/ggrc-client/js/controllers/infinite-scroll-controller.js
- src/ggrc-client/js/controllers/lhn_controllers.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/controllers/tests/modals_controller_spec.js
- src/ggrc-client/js/controllers/tree/list_view_controller.js
- src/ggrc-client/js/controllers/tree/tree-loader.js
- src/ggrc-client/js/entrypoints/vendor.js
- src/ggrc-client/js/models/mappers/proxy-list-loader.js
- src/ggrc-client/js/models/refresh_queue.js
The APP uses can.proxy to call method with current context.
CanJS 3 doesn't support that method.
To use arrow functions instead of '**can.proxy**'
> GGRC-6848 Use arrow function instead of usage of "proxy" method

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.0.0
> GGRC-6997 Add 'What's new' for release 2.0.0

- src/ggrc/access_control/role.py
- src/ggrc/utils/validators.py
- test/integration/ggrc/access_control/test_access_control_role.py
Error raising during ACL propagation. It was triggered by ACR event listener, which prevent modification of ACR for internal users.
1. Load dump from dev environment which marked as "*corrupted_proposals*"
2. Launch GGRC
3. Login as admin
4. Request POST to "/admin/propagate_acl" endpoint
Propagate ACL creates missing ACLs for all ACR objects. Since all related ACLs is represented as relationship in ACR, creation of new ACL triggers ACR listeners, however it shouldn't.
Now we check if ACR modified in "before_update" ACR listener.
> GGRC-6868 Fix propagate acl error in dev

- src/ggrc-client/js/helpers.js
- src/ggrc-client/js/templates/access_control_roles/tree.stache
- src/ggrc-client/js/templates/assessment_templates/modal_content.stache
- src/ggrc-client/js/templates/assessments/modal_content.stache
- src/ggrc-client/js/templates/audits/search_result.stache
- src/ggrc-client/js/templates/base_objects/autocomplete_result.stache
- src/ggrc-client/js/templates/base_objects/search_result.stache
- src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
- src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
- src/ggrc-client/js/templates/cycle_task_groups/autocomplete_result.stache
- src/ggrc-client/js/templates/directives/autocomplete_result.stache
- src/ggrc-client/js/templates/events/object_list.stache
- src/ggrc-client/js/templates/objectives/autocomplete_result.stache
- src/ggrc-client/js/templates/org_groups/autocomplete_result.stache
- src/ggrc-client/js/templates/people/autocomplete_result.stache
- src/ggrc-client/js/templates/people/object_list.stache
- src/ggrc-client/js/templates/programs/search_result.stache
- src/ggrc-client/js/templates/roles/object_list.stache
- src/ggrc-client/js/templates/task_group_tasks/task_group_subtree.stache
- src/ggrc-client/js/templates/vendors/autocomplete_result.stache
- src/ggrc-client/js/templates/workflows/search_result.stache
**Can JS 3** doesn't support "_data_" helper.
Add custom **stache helper** and use it instead of legacy "data" helper
> GGRC-6991 Remove legacy "data" stache helper

- src/ggrc-client/js/templates/modals/save_cancel_delete_buttons.stache
Save button is active on create modal when mandatory attrs are not filled.
1. Log as admin user to GGRC
2. Click Create object -> Control
3. Fill required fields and click Save & Add Another
4. Look at the result: 
**Actual result:** New control modal is shown, mandatory attrs are not filled, Save buttons are active. 
**Expected result:** Save buttons should not be active on create modal when mandatory attrs are not filled.
CanJs not always handle correctly adding disable class or attribute to element on instance updating.
Re-rendering all buttons fixes the issue.
> GGRC-6649 Disable Save button on create modal when mandatory attrs are not filled

- src/ggrc/services/common.py
- test/integration/ggrc_workflows/test_workflow_api_calls.py
This is additional PR for issue GGRC-6538. Request payload on task group post was incorrect (id should be a number instead of object). Response status code should be equal 400 in such case.
> QUICK-FIX Handle incorrect data payload on object creation

- src/ggrc/cache/utils.py
- src/ggrc/converters/base.py
- src/ggrc/models/exceptions.py
- src/ggrc/utils/errors.py
- src/ggrc/views/converters.py
- test/integration/ggrc/services/resources/test_converters.py
When you try to kill export using kill button it haven't stoped and will send email notification when it would be finished.
Start long export. Kill it. Look in Task queue that export job have stopped.
I've added check to export handler to check if export was stopped and interrupt process.
Also I've refactored our base.py and converters.py files. Please look through commit messages.
(1500 programs exported on perf instance. time in seconds.):
dev branch: 84.3, 63.8, 55.4, 64.5, 66.8
branch with changes: 83.4, 69.9, 65.5, 68.1, 62.3
average: 
- before 66.96
- after 69.84
- 4.3% degradation
average w/o corner values:
- before 65.05
- after 67.83
- 4.27% degradation 
We've tested best solution we've found and it causes performance degradation approx. 4.5%. We've measured it for 995 …
> GGRC-5854 Make a possibility to stop the export

- src/ggrc-client/js/components/workflow/task-group-objects/templates/task-group-objects.stache
Unified mapper shows that control is not mapped to task group
1. Create any workflow
2. Setup tab > Task Group > Map Control
3. Open Info panel, look at the mapped control
**Actual Result:** Checkbox is unchecked, whereas control is mapped to task group
**Expected Result:** If control is mapped to task group, checkbox should be checked for such control in Unified mapper
Set `task group id` for unified mapper. If it is not set unified mapper uses page object id. In this case it's Workflow id.
> GGRC-6843 Fix issue with highlighting mapped objects in unified mapper for Task Group

- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/element.py
- test/selenium/src/lib/constants/objects.py
- test/selenium/src/lib/constants/roles.py
- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/rest/template/review.json
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/url.py
- test/selenium/src/lib/utils/date_utils.py
- test/selenium/src/tests/test_objects_review.py
Confirm user with READ rights for an object assigned as REVIEWER can review an object.
> QUICK-FIX Confirm reviewer with read rights can review an object

- test/selenium/conftest.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_unified_mapper.py
*Test to check that new control modal not created from unified mapper by user with creator role.*
> QUICK-FIX Test for no modal on create object from unified mapper.

- src/ggrc/gcalendar/calendar_event_sync.py
- src/ggrc/models/calendar_event.py
- test/integration/ggrc/gcalendar/test_calendar_event_sync.py
New calendar transperant events are not visible to the user
For new events:
1. Create a cycle task in active workflow
2. Run the sync job `_notifications/send_calendar_events`
3. See the event in calendar.google.com
For previous events:
1. Before applying the change create several cycle tasks and see that events are not visible in  calendar.google.com
2. Apply changes
3. Run the sync job `_notifications/send_calendar_events`
4.  See the events in calendar.google.com
Update end date for all-day events - move it to one day forward
> GGRC-7001 New calendar events are not visible 

- src/ggrc-client/js/controllers/lhn_controllers.js
jQuery v3+ doesn't support .size() method
> GGRC-7039 Use jQuery 'length' property instead of 'size()'

- test/selenium/src/tests/test_audit_page.py
*Autogenerated title replace already existing title, that might cause test failure.*
*Assert audit w/o title property and then compare actual title with expected and matching default title template.*
> QUICK-FIX Xfail test due to autogenerated title

- src/ggrc-client/js/components/form/fields/rich-text-form-field.js
- src/ggrc-client/js/components/form/fields/text-form-field.js
- src/ggrc-client/js/entrypoints/admin/bootstrap.js
CanJS 3 doesn't support can.trim function
To use `_.trim` instead of `can.trim`
> GGRC-6990 Use lodash.trim instead of can.trim

- src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Dividing lines are missed in Global Search results.
1. Login to GGRC app
2. Open Global Search (Controls are default object) and click Search button
3. Look at the Search results: dividing lines between rows are missed
Actual Result: Dividing lines are missed in Global Search
Expected Result: Dividing lines should not be missed in Global Search
- Added new styles class.
- Added border to the newly created styles class.
> GGRC-5624 Added Dividing lines for Global Search results

- src/ggrc-client/js/controllers/tree/tree-view.js
- src/ggrc-client/styles/modules/_filters.scss
**Legacy tree-view** loader contains redundant pieces of the source code
> GGRC-7038 Remove redundant piece of the source code fro legacy tree-view

- src/ggrc-client/js/models/business-models/task-group-task.js
Task-group-task Model has unneeded condition in validation rule
> GGRC-7036 Remove unneeded condition from task-group-task validation rule

- src/ggrc/migrations/versions/20190328_42ac8162b810_set_default_values_in_notifications_.py
Update notification table to set defaults for not null columns
1. Run the new migration file 'aed073309899'.
2. Login into mysql server.
3. Reset database using 'db_reset'
4. View the schema of 'notifications' table.
5. View the default values of 'force_notifications' and 'repeating' columns.
1. Created a new migration file 'aed073309899'
2. Edited the new migration file with required MySQL statements, written under 'upgrade' function.
> GGRC-5460 Set default values in notifications table

- src/ggrc/templates/notifications/style.html
Margin:20px doesn't work in google mail
Margin 20px doesn't work in google mail
1. Import csv template
2. Open mail and look at the notification
Actual Result: Padding is not displayed in email notification after importing/exporting
Expected Result: Add padding in email notification after importing/exporting
Replace margin:20px by padding:20px
> GGRC-4933 Add padding in email notification after importing/exporting

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/object-state-toolbar/object-state-toolbar.js
- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/events/eventTypes.js
- src/ggrc-client/js/models/business-models/assessment.js
- src/ggrc-client/js/models/business-models/tests/assessment_spec.js
After mapping snapshots through Edit modal assessment is not moved to 'In Progress' state.
- Create assessment on the audit page
- Complete Assessment (Completed, In Review, Completed and Verified)
- Open Edit assessment popup and Map a snapshot to it
- Click Save and Close
- Look at the Assessment's state on the Info panel: is still Completed
Actual Result: Assessment is moving to 'In progress' only after refresh
Expected Result: Assessment should be moved to 'In progress'
> GGRC-6526 Refresh assessment after creation of relationship

- src/ggrc-client/js/templates/people_roles/option_column.stache
Use canData helper instead of legacy 'data' helper
> QUICK-FIX Use canData helper instead of legacy 'data' helper

- src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js
- src/ggrc-client/js/components/mapped-counter/mapped-counter.js
- src/ggrc-client/js/components/mapped-counter/mapped-counter.stache
- src/ggrc-client/js/components/object-loader/object-loader.js
- src/ggrc-client/js/components/people/people-list-info.stache
- src/ggrc-client/js/components/tree/templates/tree-item-attr.stache
- src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache
- src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
- src/ggrc-client/js/entrypoints/commons.js
- src/ggrc-client/js/helpers.js
- src/ggrc-client/js/templates/assessment_templates/modal_content.stache
- src/ggrc-client/js/templates/audits/dropdown_menu.stache
- src/ggrc-client/js/templates/audits/extended_info.stache
- src/ggrc-client/js/templates/audits/info.stache
- src/ggrc-client/js/templates/audits/modal_content.stache
- src/ggrc-client/js/templates/base_objects/extended_info.stache
- src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
- src/ggrc-client/js/templates/cycle_task_groups/extended_info.stache
- src/ggrc-client/js/templates/cycles/info.stache
- src/ggrc-client/js/templates/processes/info.stache
- src/ggrc-client/js/templates/products/info.stache
- src/ggrc-client/js/templates/risk_assessments/modal_content.stache
- src/ggrc-client/js/templates/systems/info.stache
- src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
- src/ggrc-client/js/templates/task_groups/modal_content.stache
- src/ggrc-client/js/templates/task_groups/tier2_content.stache
'can.view' methods are deprecated in CanJs v3 and should be replaced with another supported functionality.
Case#1:
- Open Dashboard page & expand LHN menu
- Expand 'Issues' section & hover over any item
Expected behavior: 'Extended Info' modal contains info about mapped items
Case#2:
- Open Dashboard page
- Click 'Create a Task' button
- Fill out all mandatory fields & click 'Save' button
Expected behavior: New Task is successfully created.
Replace usage of 'with_mapping_count' helper w/ appropriate component ('mapped-counter')
Replace usage of 'using' helper w/ newly created <object-loader> component that explicitly fetches data on demand.
> GGRC-6961 Remove usage of 'can.view.hook'

- src/ggrc/access_control/roleable.py
- src/ggrc/models/mixins/customattributable.py
- src/ggrc/models/mixins/issue_tracker.py
- src/ggrc/models/mixins/notifiable.py
- src/ggrc/models/relationship.py
Deleting an assessment triggers queries for all objects that look like
```sql
SELECT 
objectives.id AS objectives_id, 
objectives.recipients AS objectives_recipients, 
objectives.send_by_default AS objectives_send_by_default, 
objectives.updated_at AS objectives_updated_at, 
objectives.modified_by_id AS objectives_modified_by_id, 
objectives.created_at AS objectives_created_at, 
objectives.context_id AS objectives_context_id
FROM objectives
WHERE 1 = objectives.id AND 'Assessment' = 'Objective' AND 0 = 0
```
and due to conditions like 'Assessment' = 'Objective' for all objects it never returns anything.
1. Create program, audit, assessment;
2. Delete an assessment;
3. Look at queries issued during request.
Expected result: there should not be any queries like the one described above.
This …
> GGRC-5125 Redundant DB queries on assessment deletion

- src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache
- src/ggrc-client/js/templates/audits/modal_content.stache
Make Audit Captain field visible when clicked on 'Hide optional fields'.
1. On the program page click Add tab > Audit
2. Click on Create button
3. Click 'Hide optional fields' button and look at the 'Audit captains' field
The div element corresponding to 'Audit Captain' field is removed from class 'hidable'.
Additionally, change has been done in 'custom-roles-modal.stache' file where the class 'hidable' is added to required div element.
> GGRC-6421 Make audit captain role visible

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.1.0
> GGRC-7073 Add 'What's new' for release 2.1.0 

- src/ggrc-client/styles/components/tree/_tree-view.scss
If add more than 5 people, tooltip is appeared and then quickly disappeared in tree view.
1. Open any assessment info pane
2. Add ~ 6 assignees to assessment
3. Close info panel and hover over assignees in tree view: tooltip quickly disappears
**Actual Result:** If add more than 5 people, tooltip is appeared and then quickly disappeared in tree view
**Expected Result:** If add more than 5 people, tooltip is appeared while hovering over people in tree view
If the tree-view element contains more than 6 people, most of the people block is invisible. Tooltip checks block's center visibility (and it's invisible) and disappears.
Solution: don't display not visible people in the `tree-people-with-role-list-field` on tree-view.
> GGRC-6619 Tooltip appears and then quickly disappears in tree view

- src/ggrc/views/__init__.py
object count is different on all objects and lhn
that's because all objects tabs count actual objects, while lhn gets unique ids only from fulltext index and that can have records from objects that don't longer exist.
use ggrc qa database (or dev) and compare the numebers
then run reindex and compare the numbers again.
Since we modified reindex to just update records that we have in our
database, we lost the chance to clean up any records that should not
exist. These records are a result of different bugs where a deletion of
an object fails after deletion but before the fulltext update. So here
we just make sure that after running reindex no dead objects will remain
in the fulltext index.
> GGRC-2756 Add cleanup of dead records to reindex

- test/integration/ggrc_workflows/converters/test_export_cycle_task_group_object_tasks.py
Implement advanced search for comments for CycleTaskGroupObjectTasks.
This ticket is part of out of scope items from the ticket GGRC-4458
Before there was a possibility to search by "task comments". Now there are no such functionality 
1. Add comment to a CycleTask
2. Search for "task comments"
After removing cycle_task_entries we should search by "task comment" keyword.
Integration test used CycleTaskEntryFactory and updated to use CommentFactory.
> GGRC-7017 Add filtering by CycleTask comments

- test/selenium/src/lib/constants/ux.py
- test/selenium/src/lib/decorator.py
- test/selenium/src/lib/page/modal/apply_decline_proposal.py
- test/selenium/src/lib/page/widget/workflow_tree_rows.py
- test/selenium/src/lib/rest_facades/control_rest_facade.py
- test/selenium/src/lib/rest_facades/person_rest_facade.py
- test/selenium/src/lib/rest_facades/workflow_rest_facade.py
- test/selenium/src/lib/service/proposal_rest_service.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/utils/test_utils.py
> QUICK-FIX Add waiters for object creation

- kokoro/deploy_ggrc_dp.cfg
- kokoro/deploy_ggrc_dp.sh
Need to automate deployment to dp instance via kokoro.
The configs in this pull requests are similar to other deployment configs (eg : deploy_ggrc_prod.cfg, deploy_ggrc_prod.sh). This can be tested once we have proper settings file in GCS bucket and required configs are checked in into google3.
Note : This is an isolated change. If merged, the changes in this PR will not affect any other process.
Once this PR is merged and required settings file are added into GCS bucket, deployment to dp instance can be done from within kokoro UI. This will eliminate lot of manual work.
> QUICK-FIX Add kokoro deployment configs for dp instance

- test/selenium/conftest.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/tests/test_create_object.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_snapshots.py
*Added test to check that Control cannot be created from LHN.*
> QUIK-FIX Test Control cannot be created from Lhn.

- src/ggrc-client/js/bootstrap/modal-ajax.js
- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/components/form/fields/person-form-field.stache
- src/ggrc-client/js/components/info-pin-buttons/info-pin-buttons.stache
- src/ggrc-client/js/components/object-mapper/object-mapper.stache
- src/ggrc-client/js/components/page-header/page-header.stache
- src/ggrc-client/js/components/three-dots-menu/templates/three-dots-menu.stache
- src/ggrc-client/js/components/tree/templates/tree-header.stache
- src/ggrc-client/js/components/unarchive_link.js
- src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache
- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
- src/ggrc-client/js/templates/assessments/header.stache
- src/ggrc-client/js/templates/dashboard/info/get_started.stache
- src/ggrc-client/js/templates/dashboard/lhn.stache
- src/ggrc-client/js/templates/dashboard/lhn_risks.stache
- src/ggrc-client/js/templates/help/filters_helper_content.stache
- src/ggrc-client/js/templates/snapshots/dropdown_menu.stache
- src/ggrc/templates/assessments_view/index.haml
- src/ggrc/templates/layouts/dashboard.haml
- src/ggrc/templates/welcome/index.haml
- test/selenium/src/lib/constants/locator.py
**can-stache-bindings** package throws exception for **<a>** tags with **href="#"** attribute
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
> GGRC-7037 Use href="javascript:void(0)" instead of href="#"

- extras/deploy_settings_selenium.override.sh
- test/selenium/src/lib/app_entity/control_entity.py
- test/selenium/src/lib/app_entity_factory/control_entity_factory.py
- test/selenium/src/lib/base.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/dynamic_fixtures.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/rest_services/control_rest_service.py
- test/selenium/src/lib/service/rest/client.py
- test/selenium/src/lib/service/rest/session_pool.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_rbac.py
- test/selenium/src/tests/test_snapshots.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Fix assessments workflow tests

- src/ggrc/access_control/list.py
- src/ggrc/access_control/role.py
- src/ggrc/access_control/roleable.py
- src/ggrc/utils/__init__.py
- src/ggrc/utils/referenced_objects.py
- test/integration/ggrc/converters/test_imported_api_requests.py
Creation of assessment inside audit 4567 on perf instance takes to much time.
1. Deploy this PR on perf;
2. Open audit 4567 on perf;
3. Create an assessment;
4. Look at timings and logs.
The solution is in reducing number of DB queries performed while working with ACL:
1. During object creation step for each person to be added in ACL one DB query was initiated which does not perform well in case of hundreds of people. One DB query per ACL querying all people in it is introduced here instead.
2. Since some fields on `Person` model are lazily loaded, the number of DB queries when caching was equal to number of people in ACL. Here new property `people` is implemented, which queries all people of ACL undefering fields from `Person_complete` group.
> GGRC-5322 Reduce latency while creating assessment inside large audit

- src/ggrc-client/js/components/assessment/mapped-controls/mapped-controls.stache
Type of the mapped instance isn't shown because of the typo in variable name
2. Map control and access group to audit
3. Create assessment with Control type
4. Open Assessment info panel > Other attributes tab
5. Click Map icon for Related Information and map Access group snapshot to assessment
6. Click on Access group snapshot to open popup
Actual Result before the fix: type of the mapped instance isn't shown in the title on the left to the version because of the typo in variable name
Expected Result: type of the mapped instance is shown on the left to the version
Fix typo in mustache variable name, so now it's resolved correctly and displays Type of the mapped instance
> QUICK-FIX Fix typo in stache variable name

- src/ggrc-client/js/components/assessment/custom-attributes.stache
- src/ggrc-client/js/templates/custom_attributes/info.stache
Make inline help text of a GCA visible on info panel
1. Log in GGRC as admin user
2. Open Administration page > Custom attributes tab> Select any object (Policy) and add any CA with Inline help, e.g. Rich text
3. Create Policy and look at the Info panel
A new div element with class name 'ggrc-form-item__small-text' is added to 'ggrc-core/src/ggrc-client/js/templates/custom_attributes/info.stache' file.
> GGRC-6562 Make inline help text of a GCA visible on info panel

- src/ggrc-client/js/controllers/modals/modals_controller.js
- src/ggrc-client/js/helpers.js
- src/ggrc-client/js/models/business-models/audit.js
- src/ggrc-client/js/templates/audits/modal_content.stache
Audit:
GGRC-6289: Double 'search' request for counts when saving audit
GGRC-7048: Custom title is replaced by default one 
GGRC-6289:
1. Go to any Program page. 
2. Select the Audit tab. 
3. While creating new Audit, click [Save & Add Another]. 
4. Check Network for 'search' requests.
Actual Result before the fix: 2 same requests go to the backend
Expected Result (= actual result after the fix): do not load backend uselessly
GGRC-7048:
1. Open any program info page
2. Expand dev tools > Performance > Make Slow 3G
3. Add tab > Audit > Click on 'Create'
4. Start typing a title or insert some value from clipboard
Actual Result: if a default value is not displayed in the title field and user types some title (or insert from clipboard), the default system title replaces user's title
Expected …
> GGRC-7048/GGRC-6289 Default Audit title replaces custom and launches double search request

- README.md
Add `refresh` command to README
> QUICK-FIX Add refresh command to README

- src/ggrc-client/js/templates/modals/confirm.stache
Align text of the confirm message of object mapper to left.
1. Log in ggrc app > My dashboard > Controls tab
2. Open Unified mapper for any control and select Regulation/Standard object type
3. Create New Regulation/Standard and look at the message
4. The confirm text message should be left aligned.
Removed the class, 'centered', for the 'div' element present in 'src/ggrc-client/js/templates/modals/confirm.stache' file
> GGRC-6862 Align object mapper confirm text message to left

- src/ggrc-client/js/components/read-more/read-more.js
- src/ggrc-client/js/components/tree/tests/tree-item-attr_spec.js
- src/ggrc-client/js/components/tree/tests/tree-item-custom-attribute_spec.js
- src/ggrc-client/js/components/tree/tree-item-attr.js
- src/ggrc-client/js/components/tree/tree-item-custom-attribute.js
- src/ggrc-client/js/plugins/tests/utils/markdown-utils_spec.js
- src/ggrc-client/js/plugins/utils/markdown-utils.js
Link in Rich text field is shown as markdown in tree view
1. Create control in Q side
2. Add to rich text field (Notes, Description, Assessment procedure) link screenshot-1.png
3. Open Control on C side on My Work page
4. Set visible fields in tree view (Notes, Description, Assessment procedure)
**Actual Result:** Link in Rich text field is shown as markdown in tree view
Add util to convert markdown into html.
Use this util in tree-view components for displaying text fields.
Use this util in `read-more` component.
> GGRC-6986 Convert markdown into html in tree-view

- src/ggrc/models/comment.py
- src/ggrc/notifications/people_mentions.py
- test/integration/ggrc/notifications/test_people_mentions.py
- test/unit/ggrc/notification/test_people_mentions.py
During the review few improvements are suggested:
* add a help text to the column 'comment' (below the text _DELIMITER=";;" double semi-colon separated values_ ):
                _To mention person at the comment use the following format <a href="mailto:some_user@example.com">+some_user@example.com</a> ._
* change notification date format to (the same as used for Proposal digest):
_11/28/2018 06:44:22 PDT_
1. Run tests
2. Create comments with mentions and check email 
3. Export import template
Update templates
> GGRC-7106 Add mention person help text at import template and change date format at notification

- test/selenium/conftest.py
- test/selenium/run_selenium.py
- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/page_elements.py
- test/selenium/src/lib/page/lhn.py
- test/selenium/src/lib/page/widget/info_panel.py
- test/selenium/src/tests/test_audit_page.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_program_page.py
- test/selenium/src/tests/test_rbac.py
- test/selenium/src/tests/test_risk_threats_page.py
- test/selenium/src/tests/test_snapshots.py
- test/selenium/src/tests/test_unified_mapper.py
> QUICK-FIX Fix dashboard tests

- src/ggrc/converters/handlers/handlers.py
- test/integration/ggrc/converters/test_export_csv.py
- test/integration/ggrc_workflows/converters/test_import_task_group.py
When import Task Group Task with empty "Start Date"/"End date", here a incorrect error message "Import failed due unknown error.
Excepted error message - "Start Date"/"End Date" is required. Line will be ignored"
1. Import Task Group Task with empty dates fields
1. Added proper ERROR_MESSAGE for empty value statement.
2. Added new test.
> GGRC-5857 Wrong error message at import tgt with empty dates fields.

- src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache
- src/ggrc-client/js/components/quick_form/quick_update.js
- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
- src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
- src/ggrc-client/js/templates/account_balances/modal_content.stache
- src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
- src/ggrc-client/js/templates/task_group_tasks/modal_content.stache
Position of the 'Note' for activated workflow is not correct.
- Open active Workflow
- Open 'Setup' tab & open 'Task Group' modal
Expected behavior: 'Note' should be centered
Add missed closing tag in 'tag-group.stache' template
> QUICK-FIX Fix note positioning for activated workflow

- src/ggrc-client/js/bootstrap/modal-form.js
- src/ggrc-client/js/components/action-toolbar-control/action-toolbar-control.js
- src/ggrc-client/js/components/clipboard-link/clipboard-link.js
- src/ggrc-client/js/components/clipboard-link/permalink.js
- src/ggrc-client/js/components/clipboard-link/shortlink.js
- src/ggrc-client/js/components/comment/comment-add-button.js
- src/ggrc-client/js/components/delete-button/delete-button.js
- src/ggrc-client/js/components/form/form-validation-text.js
- src/ggrc-client/js/components/state-colors-map/state-colors-map.js
- src/ggrc-client/js/components/tasks-counter/tasks-counter.js
- src/ggrc-client/js/components/textarea-array/textarea-array.js
- src/ggrc-client/js/components/tree/tree-people-with-role-list-field.js
- src/ggrc-client/js/components/workflow/repeat-on-button-wrapper.js
- src/ggrc-client/js/controllers/tree/tree-loader.js
- src/ggrc-client/js/entrypoints/admin/bootstrap.js
- Open 'Create Task' modal
- Change type of CT's description (dropdown or checkbox)
Expected behavior: Text area should stay clean.
Replace new string syntax with strings concatenation.
> QUICK-FIX Fix indentions in stache templates

- src/ggrc-client/styles/components/object-tasks/_object-tasks.scss
'Open Tasks' button height is not valid on 'tree-item-extra-info' modal for empty tasks list:
- Create 'Control'
- Go to 'My Work' page and open 'Controls' tab
- Hover over 'i' icon for 'Control' from step#2
Expected behavior: 'Open Tasks' button height should be 18px, text should not be wrapped.
Set 'width' attribute for tag title in case there is no tasks.
> QUICK-FIX Fix 'object tasks' button height

- src/ggrc-client/js/components/sort/sort.js
`can.List.sort` gets unneeded argument
1. Open any control
2. Take a look at _Assertions/Categories_
Expected result: Assertions/Categories_ should be sorted
Remove unneeded argument
> QUICK-FIX Remove unneeded argument from 'sort' function

- src/ggrc-client/js/components/assessment/attach-button.js
- src/ggrc-client/js/components/assessment/info-pane/create-url.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
- src/ggrc-client/js/components/assessment/tests/attach-button_spec.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.js
- src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
- src/ggrc-client/js/components/related-objects/related-documents.js
- src/ggrc-client/js/controllers/modals/delete_modal_controller.js
**can-component (canJS3)**  cleans up all event bindings after `removed` event.
`viewModel.dispatch` doesn't work properly, when a component removed from **DOM**.
Try to add **comments\urls\files** on assessment info-pane
Use **pubSub** to dispatch events
> GGRC-7075 Use pubSub for dispatching events connected to Assessment related objects

- src/ggrc-client/js/components/snapshotter/revisions-comparer.js
**can.List.reverse** function returns **reversed** can.List (**canJS 2**)
But **can.List.reverse** from **canJS 3** is **void** function (doesn't return any value).
> GGRC-7086 Use lodash.reverse instead of can.List.reverse

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/lazy-render/lazy-render.js
- src/ggrc-client/js/components/lazy-render/test/lazy-render_spec.js
- src/ggrc-client/js/components/proposal/apply-decline-proposal.js
- src/ggrc-client/js/components/proposal/create-proposal.js
- src/ggrc-client/js/components/related-objects/related-assessments.js
- src/ggrc-client/js/components/tabs/tab-panel.js
- src/ggrc-client/js/components/tabs/tab-panel.stache
- src/ggrc-client/js/events/eventTypes.js
Need to refactor logic connected to tab refresh,
Because it has implicit implementation and doesn't work properly for CanJS 3
1.  Open any Risk
2.  Open **Proposals** tab
3.  Create new **Proposal**
_Expected result_: Proposals list should be refreshed
1.  Open any Assessment
2. Open **Related Assessments** tab
3. Open Edit modal
4. Change **Assessment type**
5. Save assessment
_Expected result_: Related assessments list should be refreshed
> GGRC-7091 Use REFRESH_RELATED instead of REFRESH_TAB_CONTENT

- src/ggrc-client/js/models/service-models/snapshot.js
Error while deleting a snapshot
1. Open any audit with snapshots
2. Go to any snapshots tab
3. Open Info panel > Click on Delete in 3 bb's menu
Actual Result: "Uncaught TypeError: this.is_deleted is not a function" error is displayed. Snapshot is not removed
Expected Result: no errors should be shown while deleting a snapshot
`display_name` of snapshots returns `display_name` of cacheable with binded `revision.content` which is not instance of cacheable. So solution is not call `display_name` of cacheable and return just `title` of `revision.content`.
> GGRC-7121 Fix display_name for snapshots

- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py
- src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py
- test/integration/ggrc/integrations/test_issue_integration.py
1. Open Issue Tracker and create a ticket with Component ID: 64445
2. Log in ggrc app
3. Invoke new Issue popup
4. Fill in required fields, insert ticket ID (from Issue Tracker), remove default Hotlist ID, set Component ID: 64445 > Save
Actual Result: "Unable to update a ticket in issue tracker." message is shown in UI. Issue is not linked to the ticket in Issue Tracker
Overal Hotlist ID solution for ISSUES should be:
In case Holist ID wasn't added to Issue and user tries to link it with existing ticket at Ticket Tracker - no changes at Ticket Tracker ticket side needed (Ticket Tracker ticket Hotlist ID remains unchanged);
In case Holtist ID was added to Issue and user tries to link it with existing Ticket Tracker ticket - changes at Ticket Tracker ticket needed …
> GGRC-6807 Unable to link Issue manually to the ticket in Issue Tracker in case Hotlist ID is empty

- src/ggrc-client/js/templates/dashboard/lhn.stache
Objects inside the groups at LHN to are not ordered in alphabetical order.
1. Log in to GGRC
2. Click 3 line menu icon on top left corner
3. Click on "DIRECTIVES" and check if the objects are alphabetically ordered
4. Click on "SCOPE" and check if the objects are alphabetically ordered
Make changes in lhn.stache file to order the objects alphabetically.
> GGRC-6941 Change the order of objects inside the groups at LHN to alphabetical

- src/ggrc-client/js/templates/assessments/header.stache
- src/ggrc-client/js/templates/base_objects/confirm_archive.stache
- src/ggrc-client/js/templates/base_objects/confirm_delete.stache
- src/ggrc-client/js/templates/workflows/confirm_start.stache
Left Align Text in all confirmation windows.
1. Log into ggrc app.
2. Create any object and try deleting it. 
3. Similarly create an Audit or workflow object and try archiving it. 
4. After creating a workflow object, create one or more tasks under the workflows taskgroup  and activate the workflow.
5. The confirmation windows, appearing after performing any of the above activities or similar activities, have the text message left aligned.
Removed the class, 'centered', for the 'div' elements present in below files:
'src/ggrc-client/js/templates/base_objects/confirm_archive.stache',
'src/ggrc-client/js/templates/base_objects/confirm_delete.stache',
'src/ggrc-client/js/templates/workflows/confirm_start.stache'.
The text message, appearing in one confirmation window, is displayed completely …
> GGRC-7098,GGRC-7136 Align text in all confirmation windows to left

- src/ggrc-client/js/models/business-models/assessment.js
- src/ggrc-client/js/models/cacheable.js
Render of ACL on info-pane sometimes happens between **cleanupACL** and **model** methods.
That issue is actual only for **canJS 3**
```
.then($.proxy(that, 'cleanupAcl'))
.then($.proxy(that, 'cleanupCollections'))
.then($.proxy(that.constructor, 'model'))
```
Remove unneeded chain of "then" function to avoid async execution of source code
> GGRC-7085 Remove chain of "then" function

- Dockerfile-selenium
> QUICK_FIX Bump chrome driver version

- test/selenium/run_selenium.py
- test/selenium/src/tests/test_rbac.py
> QUICK-FIX Add waiting for create permission

- test/selenium/src/lib/base.py
- test/selenium/src/lib/page/widget/task_group_info_panel.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/tests/test_workflow_page.py
1. Raised exceptions not handled correctly
2. Not stable enough waiting during 
1. Handle raised exceptions correctly by using str method and by except statement
2. Add additional waiter for task group info panel page object
> QUICK-FIX Address stability issues in selenium tests

- src/ggrc/converters/base_row.py
- src/ggrc/converters/errors.py
Improper error message while importing Control.
1. Log in GGRC
2. Export any Control to Google Sheet/csv file
3. Import Control back
Actual result: 2 Error Messages: 'Trying to import external model entry.'  and 'New instance creation is denied. The line will be ignored.'
Expected result: 1 Error Message: 'Import for Control object is not available in GGRC system anymore. Go to new frontend to perform import there. The line will be ignored.'
Replace error message while importing controls.
> GGRC-6909 Make proper message while importing controls

- src/ggrc/templates/notifications/email_digest_content.html
- src/ggrc_workflows/notification/data_handler.py
Daily digest included links to cycle tasks, but each link were not filtered and pointed to all tasks.
1. Create 2 workflows with at least one task group and task in each.
2. Open daily digest and follow the links for tasks.
3. Check that opened page includes only certain task.
Template page had link for 'My tasks' page without any filter for tasks. Now it includes filter by task title.
> GGRC-6553 Cycle link in in daily digest point to workflow

- src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache
- src/ggrc-client/js/components/related-objects/templates/related-assessments.stache
> QUICK-FIX Close "div" tags

- test/selenium/src/lib/utils/selenium_utils.py
*After moving to new chromedriver version this issue appers after executing js code to verify that page is ready.*
*Extend handling this error for whole open_url method.*
> QUICK-FIX Extend handling of UnexpectedAlert error for whole open_url method

- src/ggrc-client/js/components/tree/tests/tree-actions_spec.js
- src/ggrc-client/js/components/tree/tree-actions.js
Import control option in 3bbs button are displaying but shouldn't
1. Open My work/All objects page
2. Controls tab> click on 3 dots menu in tree view
Actual Result: 'Import controls' is displayed
Expected Result: 'Import controls' should not be displayed
Added check by "isChangeableExternally" type into "showImport" getter.
> GGRC-6844 Fix import control displaying in 3bbs menu

- ._license_header_exceptions
- docs/source/support/index.rst
- docs/source/support/local_dbs.rst
Add doc with steps describing steps to create custom db and work with it.
> DOCS: Add docs for local db management

- src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache
An unused additional class name for the dropdown component in the people list component
1. Logical test: search through the codebase for `js-toggle-field`
2. UI test:
a. Go to any audit page
b. Go to the summary page
c. Click **Create template** to define Assessment template
d. Click **Create new assessment template** link to create it from scratch
e. Make sure that *Default Assignees* and *Default Verifiers* dropdowns look the same as they look before changes
Remove additional class as it isn't used anywhere. We can remove the entire prop, as default dropdown class name is `input-block-level`
> QUICK-FIX Remove unused additional classname from dropdown

- src/ggrc/templates/notifications/bulk_child_sync_exception.html
- src/ggrc/templates/notifications/bulk_child_sync_failed.html
- src/ggrc/templates/notifications/bulk_child_sync_succeded.html
- src/ggrc/templates/notifications/bulk_sync_exception.html
- src/ggrc/templates/notifications/bulk_sync_failed.html
- src/ggrc/templates/notifications/bulk_sync_succeded.html
- src/ggrc/templates/notifications/email_digest_content.html
- src/ggrc/templates/notifications/import_export.html
It's possible to use html tags inside object title, these tags will be rendered inside mail body. For example create control with title `<a href="https://www.google.com/">my control</a>`. Rendered mail body will contain only "my control" with redirection to google.com.
1. Create Risk
2. Add a comment to the Risk
3. Check daily email digest (http://localhost:8080/_notifications/show_daily_digest) 
Enable Jinja2 autoescape for digest emails.
> GGRC-6059 There is possibility to create html code injection into mail body 

- src/ggrc/models/program.py
- src/ggrc/utils/errors.py
- src/ggrc/views/__init__.py
- test/integration/ggrc/models/test_program.py
Deleting a program with mapped audits shows a server error.
Create a program with one audit
try to delete the program
I added the same handler for deletion that we already have on audits, because those can't be deleted if they have assessments in them. I made sure the code works in the same way for consistency.
> GGRC-4399 Handle program deletion

- Dockerfile-selenium
- test/selenium/run_selenium.py
- test/selenium/src/lib/base.py
- test/selenium/src/lib/page/widget/task_group_info_panel.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/utils/selenium_utils.py
- test/selenium/src/tests/test_rbac.py
- test/selenium/src/tests/test_workflow_page.py
> QUICK-FIX Apply fixes for selenium tests from dev to release

- src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache
- src/ggrc-client/js/templates/cycles/info.stache
Invalid 'Permalink' value for Workflow, Cycle & Cycle Tasks.
1. Open 'All Objects' page
2. Select Workflows tab
3. Open any Workflow info pane
4. Expand 3bb menu & hover 'Get Permalink' option
Actual behavior: Permalink value equals to current url
Expected behavior: Permalink value should be equal to Info page url of selected Workflow object
Note: The same behavior is also relevant for Cycle & Cycle Task objects.
Although Cycle & Cycle Task objects doesn't have direct links the described scenario is still not valid.
All Objects page:
Open 'All Objects' page -> Select 'Tasks' tab -> Expand CT info pane -> Click 'Get Permalink'
Workflow page:
Open Workflow Info page -> Select 'Active Tasks' tab -> Expand CT info pane -> Click 'Get Permalink'
Open Workflow Info page -> Select 'Active Tasks' …
> GGRC-6337 Remove 'Permalink' value for Workflow, Cycle & Cycle Tasks

- src/ggrc/models/hooks/proposal.py
- src/ggrc/notifications/people_mentions.py
- test/integration/ggrc/notifications/test_people_mentions.py
No email notification for mentioning person in comment for proposal
1 Log in ggrc app and open any Risk
2 Make a proposal with mentioning person in the comment (+/@user@google.com)
3 Save proposal
4 Open email
Actual Result: There is no email notification that user mentioned 'you' in proposal for Risk
Expected result: Email notification should be received.
1 Log in ggrc app and open any Risk
2 Make a proposal
3 Open Change Proposals tab> Click on Review and Apply
4 Mention a person in comment and apply proposal
5 Open email
Actual Result: There is no email notification that user mentioned 'you' in proposal for Risk
Expected result: Email notification should be received.
Send notifications when comment created in hooks on proposals
> GGRC-7134 No email notification for mentioning person in comment for proposal

- src/ggrc-client/js/components/info-pane/info-pane-footer.stache
- test/selenium/src/tests/test_asmts_workflow.py
- test/selenium/src/tests/test_rbac.py
"**Last update by**" field is not changed after edit.
`instance.modifiedBy` saves `_cid` property and doesn't trigger `person` setter of `person-data` component
1. Open any assessment with "Last update by" not equal current user.
2. Edit title via inline edit
Actual result: "Last update by" field was NOT updated
Expected result: "Last update by" field was updated
Set `personId` property of `person-data` component to trigger `person` setter
> GGRC-7148 Fix "Last update by" on Assessment footer

- src/ggrc/gcalendar/calendar_api_service.py
- src/ggrc/gcalendar/calendar_event_sync.py
- test/integration/ggrc/gcalendar/test_calendar_event_sync.py
- test/unit/ggrc/gcalendar/test_calendar_api_service.py
Deleted in calendar events that were not deleted from database continue to trigger errors (Not found)
1. Import latest QA dump (OR create event, sync it, then delete it with sync, restore it in the database)
2. Run send_calendar_events
3. See that all events that should be deleted are deleted. 
Update try-catches in the calendar sync logic
> GGRC-7088 Investigate failures of sync calendar events

- src/ggrc/models/hooks/relationship.py
Comment is not created in launch_ggrc mode
1. Run launch_ggrc version
2. Create some scope object (Contract for example)
3. Try to add comment to it
Expected result: comment is created
Use post commit hook on Relationship
> GGRC-6964 Comment is not created in launch_ggrc mode

- test/selenium/src/lib/entities/entities_factory.py
- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/proposal_rest_service.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/rest_service.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/tests/test_objects_review.py
Confirm "Mark reviewed" button is hidden and "Request review" button is visible after review approval.
> QUICK-FIX Confirm review buttons state after review approval

- src/ggrc/converters/snapshot_block.py
- src/ggrc/migrations/versions/20181018162940_d9c56989ac07_remove_acr_backgroung_tasks.py
- src/ggrc/migrations/versions/20190204110757_25a1b9502690_modify_import_export_table.py
- src/ggrc/models/import_export.py
- src/ggrc/models/types.py
- src/ggrc/views/converters.py
- test/integration/ggrc/converters/test_snapshot_block.py
- test/unit/ggrc/converters/test_snapshot_block.py
This PR is duplicate of closed [https://github.com/google/ggrc-core/pull/8855](https://github.com/google/ggrc-core/pull/8855)
Export request did not finish due to errors while exporting all controls snapshots.
Possible reason - unused objects not released while exporting large amount of data which leads to process being killed when running out of memory.
2. Select OBJECT TYPE 'Snapshots'
3. Select 'SELECT SNAPSHOT OBJECT TYPE' e.g. Control
4. Click Export button
Before changes: Export failed due to server error. occurred, export was not finished
After Changes: Export success (~190000 Snapshots)
Downloading exported **csv** file will fail because of GAE limit of 32Mb response size. This issue should be addressed in another ticket.
Solution is partially based on …
> GGRC-5646 Snapshot export fails

- README.md
- bin/containers
Removed trailing whitespaces in both files. Added connect_db argument to bin/containers. Fixed README.md to not remove git tracked files.
> QUICK-FIX for README.md and bin/containers

- src/ggrc/cache/utils.py
There are errors in logs like "CACHE: Unable to add status for newly created entries ['DeleteOp:collection:audits:4567', 'DeleteOp:collection:snapshots:114989', 'DeleteOp:collection:snapshots:116910']" during import.
1. Import CSV file
2. Check console
Improve logging if unable to save entries to memcache.
.bulk_add returns a list of keys whose values were NOT set because they already exist in memcache. On success, this list should be empty. On network/RPC/server errors, a list of all input keys is returned; in this case the keys may or may not have been updated.
> GGRC-7183 Improve logging of update_memcache_before_commit

- src/ggrc/templates/notifications/style.html
Space between rows in the email digest is being displayed.
1. Create any object (Key Report)
2. Assign any person to custom role (Assignee)
3. Add a comment, (Notify Contacts) should be ON
4. Open email and look at the notification
Added line-height: 0.5 attribute to the list_item_sublist() class in the style.html page to fix the line height between the email notifications.
> GGRC-6758 Delete space between rows in email notification

- src/ggrc/models/background_task.py
- src/ggrc/views/__init__.py
- src/ggrc/views/converters.py
- src/queue.yaml
- test/integration/ggrc/services/resources/test_converters.py
In case of long commit to db, taskqueue can trigger request to application before BackgroundTask object is commited to db. In this case request fill be failed and because of no retry config it will never be retried again. Background object will be in Pending  state and will not be failed by health check.
Add retry logic import/export requests
> GGRC-7105 Fix import/export tasks running forever

- src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
- src/ggrc-client/js/components/workflow/task-list/templates/task-list.stache
- src/ggrc-client/js/templates/audits/tree_add_item.stache
- src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
- src/ggrc-client/js/templates/cycle_task_group_object_tasks/tree_add_item.stache
- src/ggrc-client/js/templates/dashboard/info/get_started.stache
- src/ggrc-client/js/templates/risk_assessments/tree_add_item.stache
- src/ggrc-client/js/templates/task_group_tasks/task_group_subtree.stache
JS error is thrown in dev console while clicking on Create button for Audit in scope of program. This prevents 'Create/Edit' model from been open thus it's impossible to create new Audit from Program scope.
- Create Program with '"' (double quotes) in title
- Open Program -> open Audit tab, expand browser Console and click on Create button
Actual Result: "Uncaught (in promise) SyntaxError: Unexpected token p in JSON at position 77" error is displayed. New Audit modal window is not displayed.
Expected Result: no errors should occur. New Audit modal window should be displayed.
Remove ```title``` field from ```data-object-params``` attribute that is been passed to ```modal_controller``` on opening 'Create/Edit' modal window.
> GGRC-6922 JS error on create Audit in scope of Program

- src/ggrc-client/js/templates/access_groups/modal_content.stache
- src/ggrc-client/js/templates/assessments/modal_content.stache
- src/ggrc-client/js/templates/contracts/modal_content.stache
- src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
- src/ggrc-client/js/templates/data_assets/modal_content.stache
- src/ggrc-client/js/templates/facilities/modal_content.stache
- src/ggrc-client/js/templates/issues/modal_content.stache
- src/ggrc-client/js/templates/key_reports/modal_content.stache
- src/ggrc-client/js/templates/markets/modal_content.stache
- src/ggrc-client/js/templates/modals/confirm_cancel_buttons.stache
- src/ggrc-client/js/templates/modals/discard_buttons.stache
- src/ggrc-client/js/templates/modals/modal_header.stache
- src/ggrc-client/js/templates/modals/save_cancel_buttons.stache
- src/ggrc-client/js/templates/objectives/modal_content.stache
- src/ggrc-client/js/templates/org_groups/modal_content.stache
- src/ggrc-client/js/templates/policies/modal_content.stache
- src/ggrc-client/js/templates/processes/modal_content.stache
- src/ggrc-client/js/templates/products/modal_content.stache
- src/ggrc-client/js/templates/programs/modal_content.stache
- src/ggrc-client/js/templates/projects/modal_content.stache
- src/ggrc-client/js/templates/regulations/modal_content.stache
- src/ggrc-client/js/templates/requirements/modal_content.stache
- src/ggrc-client/js/templates/risks/modal_content.stache
- src/ggrc-client/js/templates/standards/modal_content.stache
- src/ggrc-client/js/templates/systems/modal_content.stache
- src/ggrc-client/js/templates/threats/modal_content.stache
- src/ggrc-client/js/templates/vendors/modal_content.stache
- src/ggrc-client/js/templates/workflows/confirm_start_buttons.stache
Old commented out code in templates
1. Verify, that only commented out code was removed
2. Verify, that level of indentation is fine
Remove commented out code. Remove one level of indentation, if required.
> QUICK-FIX Remove commented out code in templates

- test/selenium/src/tests/test_proposals.py
> QUICK-FIX Move Proposal tests to separate node

- src/ggrc-client/js_specs/models/mappers_spec.js
In scope of https://github.com/google/ggrc-core/pull/9002 models creation was made explicit without using namespace. Creation of `MockModel` inside `mappers_spec` was not updated.
Create `MockModel` explicitly without namespace.
> QUICK-FIX Create mock model explicitly

- src/ggrc-client/js/components/tests/datepicker_spec.js
In scope of the migration to CanJS 3 some tests were failed in case viewModel was created without helper `getComponentVM`.
Create viewModel using helper `getComponentVM`
> QUICK-FIX Create view model using helper

- src/ggrc-client/js/components/assessment/assessment-custom-roles.js
- src/ggrc-client/js/components/assessment/assessment-people.js
- src/ggrc-client/js/components/assessment/info-pane/info-pane.stache
- src/ggrc-client/js/components/assessment/templates/assessment-custom-roles.stache
- src/ggrc-client/js/components/assessment/templates/assessment-people.stache
- src/ggrc-client/js/components/assessment/tests/assessment-custom-roles_spec.js
- src/ggrc-client/js/components/custom-roles/custom-roles-vm.js
- src/ggrc-client/js/components/custom-roles/custom-roles.js
- src/ggrc-client/js/components/custom-roles/templates/custom-roles.stache
- src/ggrc-client/js/components/custom-roles/tests/custom-roles_spec.js
- src/ggrc-client/js/components/related-objects/related-people-access-control.js
- src/ggrc-client/js/templates/assessments/modal_content.stache
Confirmation popup is not displayed if Assessment moves to IN progress.
Case 1: Steps to reproduce:
1. Open any asmt without Verifier
2. Complete asmt (assessment is in 'Completed' state)
3. Add verifier or add creator or add assignee 
Actual Result: actual status is not changed
Expected Result: assessment status is changed to 'IN PROGRESS'. Confirmation popup should be displayed.
Case 2: Steps to reproduce:
1. Open any asmt with Verifier
2. Complete asmt (assessment is 'IN REVIEW' state)
3. Add verifier or add creator or add assignee 
Actual Result: actual status is not changed
Expected Result: assessment status is changed to 'IN PROGRESS'. Confirmation popup should be displayed.
Case 3: Steps to reproduce:
1. Open any asmt with Verifier (your account)
2. Complete asmt and click 'Verify' …
> GGRC-6803 Show confirmation popup when custom role is changed

- src/ggrc/gcalendar/calendar_api_service.py
Due to lack of exponential backoff we have to increase google calendar api quotas. 
1. Have a large pool of cycle tasks that are not synced
2. Set default quota for requests per second
3. Run sync of calendar event
Add exponential backoff on 403 code 
https://developers.google.com/drive/api/v3/handle-errors#implementing_exponential_backoff
https://developers.google.com/calendar/v3/errors
> GGRC-6723 Use retries for calendar api

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.2.0
> GGRC-7193 Add 'What's new' for release 2.2.0

- src/ggrc/utils/html_cleaner.py
- test/unit/ggrc/utils/test_html_cleaner.py
String values like ""&*a;" transformed to "&*;;"
1.	Create any type of object with &*!;
2.	Verify field
Expected: &*!;
Actual: &*;;
We are detecting values by pattern that would transform into incorrect values and replace back them.
> GGRC-7051 Combination of chars &*!; converted into &*;; 

- src/ggrc-client/js_specs/models/mappers_spec.js
Actually strings are used to mock instances. At the same time in scope of the migration to CanJS 3 expectation is object.
Pass objects to `MappingResult`
> QUICK-FIX Pass objects for mappings

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Update release date for v2.2.0
> QUICK-FIX Update release date for v2.2.0

- src/ggrc/notifications/common.py
- src/ggrc/notifications/fast_digest.py
As a user I want to have a prefix of what environment sends me a notification.
E.g. daily digest will have the following view:
for test: [test] GGRC daily digest for Dec 03
for UAT: [UAT] GGRC daily digest for Dec 03
for perf: [Perf] GGRC daily digest for Dec 03
for prod (NO LABEL NEEDED): GGRC daily digest for Dec 03
The label should be added to:
all sent email notifications
calendar events 
The prefix should be set via config file. In case empty - no prefix is needed.
send emails (probably on a deployed instance)
I just added the prefix that was already used on calendar events. and added it to all places I could find that send out emails.
> GGRC-6441 Add custom prefix to email subject

- src/ggrc-client/js/components/tree/tree-item-actions.js
The app has unused pieces of the source code
> GGRC-7215 Remove unneeded piece of the source code

- src/ggrc-client/js/components/assessment/info-pane/info-pane.js
- src/ggrc-client/js/components/assessment/info-pane/tests/info-pane_spec.js
- src/ggrc-client/js/components/feedback-link/feedback-link.js
CanJS v3 doesn't support `capitalize` function.
Use `_.capitalize `function
> GGRC-7214 Use '_.capitalize' instead of 'can.capitalize'

- src/ggrc-client/js/components/tree/sub-tree-models.js
- src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
- src/ggrc-client/js/components/tree/tests/sub-tree-models_spec.js
- src/ggrc-client/styles/components/tree/_tree-view.scss
> GGRC-5528 Sub-tree filter's layout and order

- test/selenium/src/lib/entities/entity.py
- test/selenium/src/lib/page/widget/page_mixins.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/tests/test_objects_review.py
Confirm floating message 'Review is complete' with 'Undo' button appear after review approval.
> QUICK-FIX Confirm floating message with 'Undo' button appear after review approval

- test/selenium/src/lib/decorator.py
- test/selenium/src/lib/rest/api_client.py
- test/selenium/src/lib/rest_facades/control_rest_facade.py
- test/selenium/src/lib/service/rest_facade.py
- test/selenium/src/lib/service/webui_facade.py
> QUICK-FIX Remove work by external user decorator

- test/selenium/src/lib/page/dashboard.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/tests/test_create_object.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_unified_mapper.py
Added test that user cannot map control to scope objects/directivesia add tab menu.
> QUICK-FIX Test user cannot map control to scope objects/directives

- src/ggrc-client/js/components/add-tab-button/add-tab-button.js
- src/ggrc-client/js/components/add-tab-button/add-tab-button.stache
- src/ggrc-client/js/components/inner-nav/inner-nav-vm.js
- src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js
- src/ggrc-client/js/components/tree/tree-item-actions.js
- src/ggrc-client/js/helpers.js
- src/ggrc-client/js/models/business-models/audit.js
- src/ggrc-client/js/models/mappers/mappings-ggrc.js
- src/ggrc-client/js/models/mappers/mappings.js
- src/ggrc-client/js/models/mappers/tests/available-mappings_spec.js
- src/ggrc-client/js/models/mappers/tests/mappings_spec.js
- src/ggrc-client/js/templates/base_objects/dropdown_menu.stache
`is_allowed_to_map_task` helper contains list of models. It used to check possibility to create Cycle Task for object. 
It should be removed and used common mappings config.
**Case 1**
1. Log in ggrc app > My Work page
2. Documents tab > Open any Document info page
3. Add tab > Workflow Tasks
4. Create > Fill required fields > Save
**Actual Result:** Sever error is displayed (POST 500)
**Expected Result:** Document should not be mapped to Workflow Tasks. No 'Workflow Tasks' object should be displayed in Add tab menu for Document
**Case 2**
1. Open any object page, e.g. Regulation
2. Click on Add tab and select Workflow 
**Actual Result:** 'Workflow' object should not be displayed in Add tab menu if this object is not mapped to workflow task
**Expected Result:** 'Workflow' tab (and …
> GGRC-6963/GGRC-7020/GGRC-5938/GGRC-7035 Replace is_allowed_to_map_task helper with common mappings approach

- src/ggrc-client/js/components/object-review/object-review.js
mark reviewed button is broken if there are no reviews present.
Create a new object
click mark reviewed button
since we update the role from reviewer to reviewers we forgot to do the same change on the frontend.
> GGRC-7207 Fix reviewer role getter

- src/ggrc-client/styles/modules/_modal.scss
Labels positioning on CT Create is not valid
Actual:
Expected:
- Open Create CT modal
- Investigate 'Dates' section
Replace locator that was applied to all labels more specific.
> QUICK-FIX Fix labels positioning

- src/ggrc/migrations/versions/20190423_fd7f3834a37e_custom_attribute_added_to_control_for_.py
There is a migration with wrong 'down_revision' in release branch, it isn't executed on deployed instance.
Run migrations and check that "Custom Attribute added to Control for Control Narrative" migration executed
Fix migration chain
> QUICK-FIX Fix migration chain in release branch

- src/ggrc-client/js/components/object-generator/object-generator.stache
No snapshots found in generation popup. Can't switch object type in generation popup.
1. Create Audit
2. Map snapshot of Access Group to Audit
3. Go to Audit Summary and click on Autogenerate button
3. Select No template > Object type: Access Group 
4. Click on Search button
**Actual Result:** "No Controls were found" is displayed in Search Results. Snapshots of Access Group is not displayed
**Expected Result:** Snapshots of Access Group should be displayed in Search Results
Use two-way binding for selected type.
> GGRC-7123 No snapshots found in generation popup

- src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.stache
- src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache
- src/ggrc-client/js/components/people/people-list-info.stache
- src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
- src/ggrc-client/js/components/workflow/task-group/templates/task-group.stache
- src/ggrc-client/js/templates/audits/modal_content.stache
- src/ggrc-client/js/templates/custom_attribute_definitions/modal_content.stache
- src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache
- src/ggrc-client/js/templates/help/filters_helper_content.stache
- src/ggrc-client/js/templates/people/info.stache
- src/ggrc-client/js/templates/policies/modal_content.stache
- src/ggrc-client/js/templates/processes/info.stache
- src/ggrc-client/js/templates/systems/info.stache
- src/ggrc-client/js/templates/task_groups/clone_modal_content.stache
- src/ggrc-client/js/templates/vendors/modal_content.stache
- src/ggrc-client/js/templates/workflows/clone_modal_content.stache
- src/ggrc-client/js/templates/workflows/extended_info.stache
- src/ggrc-client/js/templates/workflows/info.stache
> QUICK-FIX Fix closing tags warnings

- docs/source/backend/object_manipulation.rst
- src/ggrc/migrations/versions/20190417_f911d14458c5_remove_unused_coloumn_sort_index.py
- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/cycle_task_group.py
- src/ggrc_workflows/models/cycle_task_group_object_task.py
- src/ggrc_workflows/models/task_group.py
- src/ggrc_workflows/models/task_group_task.py
Remove sort_index from BE
No particular steps to test the change as the sort_index was removed from the BE code and cannot be spotted out anywhere from FE
Removed the sort_index column from BE code and from the following tables:
1. cycle_task_group_object_tasks
2. cycle_task_groups
3. task_group_tasks
4. task_groups
> GGRC-4862 Remove sort_index from BE code

- src/ggrc-client/js/templates/custom_attributes/info.stache
Increase the width of the Control Narrative attribute. 
Change the width of Rich text custom attributes to a screen-wide (like is done for type Text).
Open some info-pane/page with rich-text global custom attribute
**Actual result:** The width of rich text GCA is third part of the page
**Expected result:** The width of rich text is screen-wide.
> GGRC-7153 [MAIN] Change the width of Rich Text custom attribute

- src/ggrc-client/js/templates/custom_attributes/info.stache
Increase the width of the Control Narrative attribute. 
Change the width of Rich text custom attributes to a screen-wide (like is done for type Text).
Open some info-pane/page with rich-text global custom attribute
**Actual result:** The width of rich text GCA is third part of the page
**Expected result:** The width of rich text is screen-wide.
> GGRC-7153 Change the width of Rich Text custom attribute

- src/ggrc_basic_permissions/__init__.py
When user has lots of acls we have an error "Exceeded soft memory limit of 2048 MB with 2514 MB after servicing 728 requests total".
Log into app with the user who has lots of acls (about 2 000 000). No errors should appear.
The biggest amount of memory is taken by SQLAlchemy objects. ACL records retrieving could be done with raw SQL. This reduced the amount of consumed memory for the user with 330 000 acls from 477 MB to 102 MB locally.
> GGRC-7238 Reduce memory consumption on permissions load

- src/ggrc_workflows/__init__.py
- src/ggrc_workflows/models/task_group_task.py
nightly_cron_endpoint fails due to old cycle tasks
Edit a cycle task generated via Object Review
Actual result: 500 error
Expected result: 200 response
Run http://localhost:8080/admin/start_unstarted_cycles job
Actual result: 500 error
Expected result: 200 response
1. Update code to fit the refactoring in #8985 
2. Introduce fields for models that are exist in the db
> GGRC-6823 nightly_cron_endpoint fails due to old cycle tasks

- src/ggrc/converters/handlers/related_person.py
Not used file without any code
Check that the file was really not used anywhere
Removed the dead file.
> QUICK-FIX Remove dead python file

- src/ggrc/notifications/__init__.py
- src/ggrc/utils/revisions_diff/builder.py
Opening Change Log of Mega Program with id 457 using test DB dump results in 500 internal server error. 
Open Change Log of Mega Program with id 457
Before changes: 
Internal server error in Chrome DevTools
After changes:
Change Log displayed as expected
Some Program revisions do not contain 'attribute_object' cav. Replaced getting value from revision dict with safe alternative - get method call in revision diff builder and notifications _get_value function.
> QUICK-FIX Build revision diff when there is no 'attribute_object' in Program revision results in error

- test/selenium/src/lib/constants/locator.py
- test/selenium/src/lib/element/tree_view.py
- test/selenium/src/lib/page/modal/unified_mapper.py
- test/selenium/src/lib/page/widget/controls_tab.py
- test/selenium/src/lib/page/widget/controls_tree_rows.py
- test/selenium/src/lib/page/widget/generic_widget.py
- test/selenium/src/lib/page/widget/object_modal.py
- test/selenium/src/lib/page/widget/tree_widget.py
- test/selenium/src/lib/service/webui_facade.py
- test/selenium/src/lib/service/webui_service.py
- test/selenium/src/lib/ui/ui_facade.py
- test/selenium/src/lib/url.py
- test/selenium/src/tests/test_create_object.py
- test/selenium/src/tests/test_my_work_page.py
- test/selenium/src/tests/test_unified_mapper.py
Added test that control cannot be mapped to objects/directives via UnifiedMapper
> QUICK-FIX Test that control cannot be mapped to objects/directives via UM

- test/selenium/src/lib/element/page_elements.py
- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/tests/test_controls.py
Added test that user cannot add a person to custom Role.
> QUICK-FIX Added test that user cannot add a person to custom Role

- test/selenium/src/lib/page/widget/info_widget.py
- test/selenium/src/tests/test_objects_review.py
Confirm review history is updated in change log after review approval.
> QUICK-FIX Confirm review history is updated in change log after review approval

- src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.3.0
> GGRC-7257 Update "What's new" for v2.3.0

- src/ggrc/gcalendar/calendar_event_builder.py
- src/ggrc/gcalendar/calendar_event_sync.py
- src/ggrc/models/calendar_event.py
- test/integration/ggrc/gcalendar/test_calendar_event_builder.py
- test/integration/ggrc/gcalendar/test_calendar_event_sync.py
- test/integration/ggrc/gcalendar/test_calendar_events_model.py
- test/integration/ggrc/gcalendar/test_send_calendar_events.py
- test/integration/ggrc/gcalendar/test_should_create_event_for_task.py
- test/integration/ggrc/gcalendar/test_should_delete_event_for_task.py
This PR is `on hold` until dependencies would be resolved:
If cycle task is verified or becomes overdue, event got deleted from calendar
1. Create any WF
2. Add a 2 tasks with due date in future and activate workflow
3. Run a cron job and open google calendar: event is created
4. Verify 1 cycle task: event is removed from calendar - WORKS AS INTENDED
5. Make second cycle task overdue: event is removed from calendar - TO FIX
Actual Result: If cycle task is verified or becomes overdue, event got deleted from calendar
Expected Result: If cycle task becomes overdue, event SHOULD NOT be deleted from calendar
Introduce new method for checking whether the calendar event should be deleted.
> GGRC-6589 Do not delete events for overdue tasks

- test/integration/ggrc_basic_permissions/test_external_login.py
The integration test might fail because of rewrite of the setting variable
Run `nosetests integration/ggrc_basic_permissions/test_external_login.py`
Use mock instead of settings redefinition
> QUICK-FIX Mock setting on EXTERNAL USER in the test

- src/ggrc/migrations/versions/20190429_9d89d2061961_add_review_status_for_risk.py
- src/ggrc/models/risk.py
- test/integration/ggrc/converters/test_import_helpers.py
- test/integration/ggrc/models/factories.py
- test/integration/ggrc/models/test_risk.py
- test/integration/ggrc/review/test_status_auto_update.py
- test/integration/ggrc_basic_permissions/test_external_login.py
Update review implementation for Risk model
Run unit/integration tests
Check database schema after change "review" status for Risk 
Add review/review display columns for Risk
Update review implementation for Risk model
> GGRC-7236 Update review implementation for Risk model
