src/ggrc/migrations/utils/html_markdown_parser.py, src/ggrc/migrations/versions/20190416_62d98cc2f69a_migrate_risks_to_markdown.py, test/unit/ggrc/utils/test_html_markdown_parser.py
Migrate risks to markdown
Run migration and check the data before and after the change
Apply HTML2Markdown parser to risk data
=> GGRC-7092 Migrate risks to markdown

src/ggrc/gcalendar/calendar_event_builder.py, src/ggrc/gcalendar/calendar_event_sync.py, test/integration/ggrc/gcalendar/test_calendar_event_builder.py
send_calendar_events may fail due to memory limit
Run send_calendar_events on different db instances. 
Use chunks on generation and syncing events
=> GGRC-7114, GGRC-6618 Use chunks in sync of events

src/ggrc-client/js/templates/help/filters_helper_content.stache
Improve Filter Help for Advanced Search
1. Login to ggrc app.
2. Create one or more programs or any other objects.
3. Go to Objects tab.
4. Click on filter help question mark. 
5. Check if new changes are added to it.
Added the html content to file 'src/ggrc-client/js/templates/help/filters_helper_content.stache'.
=> GGRC-6764 Improve filter help for advanced search

src/ggrc-client/js/templates/cycles/info.stache
Extra "open workflow" item from 3 dots menu being displayed for Cycles.
1. Login to GGRC
2. Create a Workflow
3. Create a Task for the Workflow
4. Create a Task Group for the Task
5. Click on Activate Workflow
6. Navigate to the Active Cycles tab and click on the View Info
Extra "open workflow" being displayed on the Cycles Info tab.
Removed the 3 dots menu from the Cycles info page
=> GGRC-5886 Remove 3 dots menu for Cycles

test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_objects_review.py
Confirm reviewer can undo object review approval by clicking on 'Undo' button on floating message.
=> QUICK-FIX Confirm reviewer can undo obj review approval.

test/selenium/src/lib/utils/date_utils.py
=> QUICK-FIX Remove shifting due date to the day before US holidays

src/ggrc_basic_permissions/converters/handlers.py, test/integration/ggrc_basic_permissions/test_csvs/import_with_noaccess_role.csv, test/integration/ggrc_basic_permissions/test_csvs/import_with_user_role.csv, test/integration/ggrc_basic_permissions/test_user_role_column_handler.py
Unable to import People with "No Access"  role.
1. Login into GGRC app.
2. Import a person with 'No Access' Role
3. A user record must be created in 'people' table, for the imported person.
4. No user role must be created for the imported person.
1. Added 'No Access' to list of 'allowable_roles' defined in 'UserRoleColumnHandler', present in file 'src/ggrc_basic_permissions/converters/handlers.py'.
2. Also test case, ' TestUserRoleColumnHandler' in 'test/integration/ggrc_basic_permissions/test_user_role_column_handler.py' is modified such that it verifies creation of record with 'No Access' role.
=> GGRC-5040 Import person with 'No Access' role

src/ggrc/gcalendar/utils.py, src/ggrc/notifications/people_mentions.py, test/integration/ggrc/notifications/test_people_mentions.py
System redirects user to log in page if click 'open' in the email for cycle task
1. Log in ggrc app > My dashboard
2. Make mentioning person in comment for any cycle task
3. Go to email > click on Open button
Actual Result: System redirects user to log in page
Expected Result: System redirects user to My Task with the filtered task.
Use a separate case for link generation (that is done with filtering) for CycleTaskGroupObjectTask since this object does not contain a separate view.
=> GGRC-7132 System redirects user to log in page if click 'open' in the email for cycle task

src/ggrc-client/js/templates/assessment_templates/info.stache
DEFAULT PROCEDURE DESCRIPTION field is displayed instead of Default assessment procedure field in the Assessment template Info page
1. Log in ggrc app and open any audit page
2. Create Assessment template 
3. Open Info panel
'Default assessment procedure' field should be displayed instead of DEFAULT PROCEDURE DESCRIPTION
Renamed the field DEFAULT PROCEDURE DESCRIPTION to Default assessment procedure in the assessment_template info mustache file to display the correct field name.
=> GGRC-7145 Rename 'Default Procedure Description' to 'Default assessment procedure'

src/ggrc-client/js/components/import-export/current-exports/current-exports.stache, src/ggrc-client/js/components/import-export/export.js, src/ggrc-client/styles/modules/_import-export.scss
Currently export page doesn't have instruction to download export results
1. Open export page
2. Export any object, e.g. Standard
3. Look at the export results
_Actual Result_: Instruction to download export results is not displayed
_Expected Result_: Add wording to export results: 
**Please click button below to download csv or open spreadsheet with exported data. Be aware that export results will be removed once you download them.**
1. Add instruction into **current-export** template.
2. Set `isInProgress` property to `true` if current job has **In Progress** status
=> GGRC-4948 Add Instruction to download export results

src/ggrc/utils/validators.py
It is possible to create GCA with title like "map:person". Then when we will try to import such GCA object will not be cteated
- Log in to GGRC as admin user
- Open Admin page > Custom attributes tab
- Select an object, e.g. Technology Environment
- Create GCA with title "map:person"
Actual Result: There is no validation during creating GCA with title "map:person" (as an example)
Expected Result: The system should validate title of gca while creating it.
This is additional fix for PR https://github.com/google/ggrc-core/pull/9237
=> GGRC-5635 No validation during creating GCA with title "map:person"

src/ggrc_workflows/__init__.py, src/ggrc_workflows/models/workflow.py, test/integration/ggrc_workflows/models/test_workflow.py
Activate Workflow button is enabled if create  Workflow with empty Task Group
1. Create Repeat off workflow with empty FIRST TASK GROUP'S TITLE field
2. Open the workflow
3. Look at the 'Activate Workflow' button
Actual Result: Activate Workflow button is enabled if create Workflow with empty Task Group
Expected Result: Activate Workflow button should not be enabled if create Workflow with empty Task Group
Add check for empty task_groups
=> GGRC-5955 Activate Workflow button is enabled if create  Workflow with empty Task Group

src/ggrc-client/js/templates/base_objects/search_result.stache
Color inside of Assessments and Issues in LHN is not in sync with the colors of Programs, Audits.
1. Expand LHN
2. Open accordion for Assessment and Issues
Actual Result: Color of items inside is blue
Expected Result: Color of items (Assessment and Issues) inside should be as for program, audit
Modify the below css file to make the color in sync with that of program, audit
src/ggrc-client/styles/modules/_side-nav.scss
=> GGRC-3678 Improve color inside of Assessments and Issues in LHN

src/ggrc-client/js/components/revision-log/revision-page.stache
Changelog's spinner is shown above Global search modal
1. Open some object
2. Click Changelog
3. While changelog is being loaded, click Global Search
Actual result: Spinner is shown above Global search modal
Expected result: Spinner should not be visible - it should be below the modal
Use `spinner-component` component instead of `attach-spinner` helper.
=> GGRC-5285 Fix changelog's spinner

src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc-client/js/templates/controls/info.stache, src/ggrc-client/styles/components/info-pane/_info-pane.scss
Changes for some fields are excluded from comparison logic and changing of field value is not marked as expected (e.g. description, test_plan).
1. Create Audit
2. Create & Map Control to Audit
3. Update description for Control
4. Open Audit page > Controls tab > Info panel > click on 'Get the latest version' link
Actual Result: Changes for description, title, assertions are not marked
Adding skipped nodes from Control template for comparison.
=> GGRC-6994 Compare values of all fields for control snapshot

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/integration/ggrc/integrations/test_assessment_integration.py
Tickets aren't created for assessments if they were created with disabled integration.
1. Log in ggrc app and open any audit page
2. Turn ON issue tracker: Component ID: 64445, Hotlist iD: 700706
3. Create assessment with Issue Tracker OFF
4. Open Assessment Info panel and add evidence (status become In Progress)
5. Open Other Attributes tab on assessment info panel > Turn ON Issue Tracker> Generate a new ticket
Check that ticket was created
1. Log in ggrc app and open any audit page
2. Turn ON issue tracker: Component ID: 64445, Hotlist iD: 700706
3. Create assessment with Issue Tracker OFF
4. Open Assessment Info panel and add verifier.
5. Log in as verifier
6. Open Assessment Info panel and click Complete, then Needs Rework 
7. Open Other Attributes tab on assessment info panel > Turn …
=> GGRC-6812 Cannot turn ON issue tracker for completed assessment

src/ggrc-client/js/components/assessment/info-pane/info-pane.js
1. Open any assessment.
2. Disable network or ideally is to use a soft for intercepting requests/response and change status codes to 4xx, 5xx.
3. Try to change the status of the assessment. For example by clicking on 'Complete' button.
_Actual result_: 'There was an error' is displayed in UI at the left bottom corner.
_Expected result_: The status of the assessment was returned to the previous before changing the status. Make a user friendly message like on the screenshot 
Use `errors-utils` to get proper error message
=> GGRC-6701 Make proper message on Assessment status change if internet connection is lost/server error

src/cron.yaml
We need to run sox sync once per day.
Deploy cron.yaml and check that service was run at 4:00.
New config data was added to cron.yaml.
=> GGRC-7304 Run sox sync job once per day

src/ggrc-client/js/components/related-objects/related-objects.js
Proposals list doesn't display new Proposals 
1. Open any risk.
2. Open Proposal tab.
3. Create new Proposal.
_Expected result_: Proposals list will be updated after creating of new Proposal.
_Actual result_: Javascript exception
Get `relatedObjects` from `viewModel`
=> QUICK-FIX Fix Javascript exception on Proposal tab

src/ggrc/models/revision.py
Extend review / review display status for Snaphots with Risk type
Open Snapshots for early created Risks and check review status - status should be showed
Extend populate snapshot display method with Risk type
=> GGRC-7306 Update review/review display for Snapshots

src/ggrc/migrations/versions/20190404_a9c71728dd5f_create_tables_for_saved_searches.py, src/ggrc/models/mixins/base.py, src/ggrc/models/person.py, src/ggrc/models/saved_search.py, src/ggrc/query/views.py, src/ggrc/utils/__init__.py, src/ggrc/utils/contributed_objects.py, src/ggrc/views/__init__.py, src/ggrc/views/saved_searches.py, test/integration/ggrc/views/saved_searches/__init__.py, test/integration/ggrc/views/saved_searches/initializers.py, test/integration/ggrc/views/saved_searches/test_saved_search_delete.py, test/integration/ggrc/views/saved_searches/test_saved_search_get.py, test/integration/ggrc/views/saved_searches/test_saved_search_post.py, test/integration/ggrc/views/test_folder.py
Created new model: SavedSearch and corresponding migration.
Linked with Person as one (Person) to many (SavedSearches).
Created required routes and corresponding methods. Covered new stuff with tests.
New functionality: we need to support saving of search filters of multiple object types.
There are lot's of steps.
Implemented per requirements.
=> GGRC-7027 Saved searches

src/ggrc/gdrive/file_actions.py, src/ggrc/models/evidence.py, test/integration/ggrc/models/test_evidence.py
We need to change current behavior while attaching evidence to assessment: Keep the filename as it is originally (no need to change filename) and move the logic of listing mapped objects to 'Description' of Evidence.
1. Create new Assessment
2. Attach Evidence file to this Assessment
Before changes:
- Postfix like `_ggrc_assessment-<assment_id>` was added to filename.
After changes:
- Filename unchanged, evidence description contains `Mapped to: assessment-<assessment_id>`
Put mapping information to description of uploaded evidence file instead of storing it in file name.
=> GGRC-6299 Attach Evidence renaming of file

src/ggrc/converters/handlers/template.py, test/integration/ggrc/converters/test_import_assessment_templates.py, test/integration/ggrc/test_csvs/assessment_template_with_warnings_and_errors.csv
"Import failed due to unknown error." is displayed if CAD type is missing
1. Go to Import page and download csv for 'Assessment template' object
2. Fill out required fields, add LCA with a title but do not indicate a type if it
3. Import csv 'Assessment template'
Actual Result: "Import failed due to server error." is displayed 
Expected Result: Make a proper warning to inform a user that type of LCA should be indicated in import template
We need to validate that CAD field contains title and type and add warning in another case
=> GGRC-7043 "Import failed due to unknown error." is displayed if CAD type is missing

src/ggrc-client/js/models/business-models/risk.js, src/ggrc-client/js/templates/risks/info.stache, src/ggrc/models/control.py, src/ggrc/models/risk.py, src/ggrc/utils/__init__.py, test/integration/ggrc/models/test_snapshot.py
Update reviewers representation with emails
Check risk details with approved review status - users with emails should be showen
Update control/risk stubs with emails
Update risk details with email
=> QUICK-FIX Update reviewers representation with emails

src/ggrc-client/js/components/assessment-templates/people-list/people-list.js, src/ggrc-client/js/components/assessment-templates/people-list/people-list.stache, src/ggrc-client/js/components/assessment-templates/people-list/people-list_spec.js, src/ggrc-client/js/plugins/tests/validation-extensions/validate-default-people_spec.js, src/ggrc-client/js/plugins/validation-extensions.js, src/ggrc-client/js/templates/assessment_templates/modal_content.stache
1. "**Default Verifiers**" field cannot be saved with empty value
2. "**Default Verifiers**" field doesn't have "**hide**" link
3. "**Default Assignees**" field doesn't have **mandatory star**
1. Log in ggrc app and open audit page
2. Go to Assessment template tab > Create > Create a new Assessment template
3. Look at the Default Assignees field: mandatory star is missed
_Actual Result_: Mandatory star is missed for 'Default Assignees'
_Expected Result_: Mandatory star should not be missed for 'Default Assignees'
4. Type a title and do not Select 'Default Verifiers' 
_Actual Result_: Save button is disabled
_Expected Result_: Save button should not be disabled as 'Default Verifiers' is not obligatory
1. Update validation rule for `default_people` attribute.
2. Add **star** icon to …
=> GGRC-7294 'Default Assignees' field doesn't have a mandatory star

src/ggrc-client/js/components/snapshotter/revisions-comparer.js
Need to highlight fields of revision comparer for Risk's snapshots in a proper way.
=> QUICK-FIX Fix revision comparer for Risks

src/ggrc/models/revision.py, test/integration/ggrc/models/test_revision.py
Snapshotable object has last deleted GCA after deleting all GCAs and before getting the latest version 
1.	Create Program, GCAs for risk, Risk mapped to program, Audit, 
2.	Delete GCAs on administration page
3.	Open Risk Snapshot 
Revision object gets CADs from custom_attribute_definitions table. But after removing we do not have them in it.
We should get CADs from rivision content.
=> GGRC-7022 Snapshotable object has last deleted GCA after deleting all GCAs and before getting the latest version

src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.5.0
=> GGRC-7313 Add "What's New" for 2.5.0

src/ggrc-client/js/components/add-tab-button/add-tab-button.stache, src/ggrc-client/js/components/collapsible-panel/collapsible-panel-header.stache, src/ggrc-client/js/components/datepicker/datepicker.js, src/ggrc-client/js/components/multi-select-label/templates/label-autocomplete-results.stache, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.stache, src/ggrc-client/js/components/related-objects/related-issues.stache, src/ggrc-client/js/components/related-objects/revisions/related-revisions-item.js, src/ggrc-client/js/entrypoints/vendor.js, src/ggrc-client/js/plugins/console-interceptor.js, src/ggrc-client/js/plugins/ggrc-gapi-client.js, src/ggrc-client/js/templates/assessments/modal_content.stache, src/ggrc-client/js/templates/workflows/info.stache, src/ggrc-client/styles/components/collapsible-panel/_collapsible-panel.scss, test/selenium/src/lib/constants/locator.py
A number of warning appears in the console just when you travel through the app
1. Click through the app
2. Run tests `run_karma`
Fix some code (close html tags, fix the structure, close strings in some places)
=> QUICK-FIX Fix simple CanJS 3 warnings

src/ggrc/models/risk.py, test/integration/ggrc/models/test_snapshot.py
Update Risk log_json with stubs for users
Run unit/integration tests
=> QUICK-FIX Update Risk log_json with stubs for users

src/ggrc-client/js/plugins/console-interceptor.js
JS error when you try to `console.log` something other than a string (eg number, object, boolean)
```
console-interceptor.js:22 Uncaught TypeError: e.includes is not a function
at console-interceptor.js:22
at $t (lodash.js:582)
at Function.fi.filter (lodash.js:9174)
at s (console-interceptor.js:20)
at console.log (console-interceptor.js:38)
at <anonymous>:1:9
```
1. Open console in GGRC
2. Type `console.log(1)` and hit `Enter`
Stringify everything before passing to the isHidden function to make sure that only string can be there.
=> QUICK-FIX Fix JS error when logging not string

test/selenium/src/lib/app_entity/regulation_entity.py, test/selenium/src/lib/app_entity_factory/regulation_entity_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/modal/unified_mapper.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/url.py, test/selenium/src/tests/test_controls.py, test/selenium/src/tests/test_unified_mapper.py
Test that user cannot map control to scope objects via unified mapper(create new one).
=> QUICK-FIX Added test that user cannot map control via um new obj

src/ggrc-client/js/components/tree/templates/sub-tree-models.stache
`on:el:click couldn't find method named @innerClick` warning appears when open sub-tree-models and click anywhere inside it.
1. Go to any object with mapped objects. Eg `/programs/2035#!audit` on dev instance
2. Open filter sub tree for the audit.
3. Click anywhere inside the new component.
4. Check browser console
Expected Result: no warnings appear in the console.
Actual Result: `on:el:click couldn't find method named @innerClick` warning appears 
Remove click handler as there's no definition of innerClick across all the codebase.
=> QUICK-FIX Fix invalid click handler warnings

test/selenium/conftest.py, test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_controls.py
*Added test that user cannot update custom attribute for control*
=> QUICK-FIX Test user cannot update custom attribute for control

src/ggrc-client/js/components/workflow/cycle-task-modal/tests/cycle-task-modal_spec.js, src/ggrc-client/js/components/workflow/cycle-task-objects/tests/cycle-task-objects_spec.js, src/ggrc-client/js/plugins/tests/utils/workflow-utils_spec.js
=> GGRC-6930 Update & write unit tests for updated/new logic related to CT components

src/ggrc/app.py, src/ggrc/utils/issue_tracker_mock/__init__.py, src/ggrc/utils/issue_tracker_mock/remote_stub.py
Issue_tracker emulation works only in launch_ggrc version but doesn't work in gae mode. So it's impossible to test features of gae version like import/export together with issuetracker locally.
What is the expected result / outcome?
Developers will save time for developing and testing their code (as they will not need to deploy remote instance)
1. Enable Issue Tracker and Issue Tracker mock
2. Launch application using launch_gae_ggrc
3. Enable IssueTracker synchronization in Audit and press 'Generate' button to generate tickets for Assessments
4. Run $.get("/hourly_issue_tracker_sync_endpoint"); in Browser DevTools Console
Expected result: 
'Synchronized issues count: <some_number>, failed count: 0' in log after step 3
'Sync is done, <some_number> issue(s) were processed' in log after …
=> GGRC-4956 Enable to use issue_tracker mock locally in gae version

src/ggrc-client/js/templates/audits/summary.stache
Filter is not applied for assessment's state from Audit summary page
1. Open Audit Summary
2. Click on a state, for instance 'In Progress' 
_Actual result_: all assessments are shown
_Expected result_: assessments with status 'In Progress' should be shown in tree view in Assessments tab
Fix filter link.
=> GGRC-7266 Filter is not applied for assessment's state from Audit summary page

src/ggrc-client/js/components/import-export/csv-import.js, src/ggrc-client/js/components/import-export/current-exports/current-exports.stache, src/ggrc-client/js/components/import-export/templates/csv-import.stache, src/ggrc-client/js/templates/modals/confirm_cancel_buttons.stache, src/ggrc-client/js/templates/modals/proceed-stop-import-buttons.stache, src/ggrc-client/styles/modules/_import-export.scss, src/ggrc/converters/base.py, src/ggrc/converters/base_block.py, src/ggrc/models/exceptions.py, src/ggrc/notifications/job_emails.py, src/ggrc/utils/errors.py, src/ggrc/views/converters.py, test/integration/ggrc/services/resources/test_converters.py
We need to have a possibility to stop import.
Import big file. 'Cancel' button. Import should be stopped. Jobs' statuses should be updated.
Functionality can be tested on deployed instance. You can use mine on ggrc-test or deploy yours.
Add stop job call in stop import handler.
=> GGRC-6311 Add possibility to stop import

src/ggrc-client/js/components/revision-log/revision-page.js
Changing Person local custom attribute for Assessment is not displayed in change log.
1. Create Assessment Template with Person attribute
2. Create Assessment for AT
3. Set Person LCA for new Assessment
4. Open change log
**Actual result:** revision is empty
**Expected result:** revision with Person attribute is displayed.
It's regression issue after merging #9223 PR.
Revert changes from dcc253 commit for change-log.
=> QUICK-FIX Display Person CA in change log

test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/tests/test_controls.py
*Added test to check that user cannot update predefined field.*
=> QUICK-FIX Test user cannot update predefined field

src/ggrc/models/risk.py
We have some mapping between Risk and object people table. 
This mapping is not used anymore but it leads to warnings in the logs.
Update risk acl entry and check that all works as expected.
Remove Personable mixin from Risk model.
=> QUICK-FIX Remove redundant Personable mixin from Risk model.

src/ggrc-client/js/templates/dashboard/lhn.stache
Check LHN.
Remove unused css classes.
=> QUICK-FIX Remove unused classes

src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache, src/ggrc-client/js/components/advanced-search/tests/advanced-search-filter-attribute_spec.js, src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js, src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache, src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone_spec.js, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache, src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js, src/ggrc-client/js/components/object-generator/object-generator.stache, src/ggrc-client/js/components/object-mapper/object-mapper.stache, src/ggrc-client/js/components/object-search/object-search.stache, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc-client/js/components/view-models/object-operations-base-vm.js
Error while filtering by date with filter options
Case 1:
2. Set filter 'Effective date' 'is empty' for Controls
3. Click Search
**Actual Result:** POST 400, 'Invalid operator near 'is':'error is displayed, no search results
**Expected Result:** Filter should be applied w/o errors
Case 2:
2. Set filter 'Last Updated Date' Greater than' and set date for Controls
3. Click Search
**Actual Result:** POST 400, Unknown operator ">" error is displayed, no search results
**Expected Result:** Filter should be applied w/o errors
Fix issues after migration to CanJs3.
Refactor `submitCbs` in mapper.
=> GGRC-7273 Fix filtering by date with filter options in Global Search

src/ggrc-client/js/controllers/tests/tree_view_node_controller_spec.js
Unit tests make real xhr requests.
1. Run `run_karma`
2. Open your browser `http://localhost:9876/` -> click debug
3. Open Dev Tools -> Network tab.
Expected result: There are no xhr requests.
Create stub for `$.ajax` method.
=> GGRC-6014 Tests make xhr

src/ggrc/models/snapshot.py, test/integration/ggrc/snapshotter/test_snapshoting.py
Disable links to control for snapshot in case original control was deprecated at GGRCQ
Added test.
Tested in UI with needed dump
Added additional condition that check original object status
=> GGRC-6824 Disable links to control for snapshot

src/ggrc/models/mixins/mega.py, src/ggrc/query/custom_operators.py, test/integration/ggrc/models/test_program.py, test/integration/ggrc/services/test_query/test_program.py
If FE send query api request with parent(child) operator and id of program that missing(e.g recently deleted), BE crashes with error.
Send request to query api with wrong id. Test is implemented.
Skip collection of parents for programs from query content if program is missing.
=> QUICK-FIX Fix issue with Query operators and id of missing Program

src/ggrc/migrations/versions/20190521_87fa3c8cb442_add_rights_to_delete_evidence.py, test/integration/ggrc/access_control/acl_propagation/test_asmt_roles.py
1. Log in ggrc app and open any assessment
2. Add evidence url/file
3. Assign global creator user as secondary/primary assignee
4. Log in global creator and open assessment
5. Remove evidence url/file from Assessment
Actual Result: 'Unable to remove URL.' message is shown. Url/file is not removed
Repeat steps from issue description.
Expected Result: Global Creator user as secondary/primary contact should be able to remove evidence url/file from Assessment as has RUD rights for this
I've added these rights to our propagation tree.
=> GGRC-7227 "Unable to remove url" message is shown, if global creator user as secondary/primary contact removes evidence url/file on assessment

src/ggrc-client/js/controllers/infinite-scroll-controller.js, src/ggrc-client/js/entrypoints/export/index.js, src/ggrc-client/js/plugins/autocomplete.js, src/ggrc-client/js/plugins/console-interceptor.js, src/ggrc-client/js/templates/base_objects/autocomplete_result.stache, src/ggrc-client/js/templates/cycle_task_groups/autocomplete_result.stache, src/ggrc-client/js/templates/directives/autocomplete_result.stache, src/ggrc-client/js/templates/objectives/autocomplete_result.stache, src/ggrc-client/js/templates/org_groups/autocomplete_result.stache, src/ggrc-client/js/templates/people/autocomplete_result.stache, src/ggrc-client/js/templates/vendors/autocomplete_result.stache
1. Autocomplete's spinner isn't disappear when search is completed.
2. Freezes after hover on autocomplete's items
1. Open export page
2. Click **FILTER BY MAPPING**
3. Type any text into autocomplete input
4. Scroll down to see spinner.
5. While spinner is not hidden, change input text and press "enter" key.
_Expected result_: Search result should be updated regarding to input's text.
_Actual result_: Search result should be updated regarding to input's text. The browser console shows javascript error. Spinner isn't hidden
6. Hover mouse pointer on autocomplete item
7. Hover mouse pointer on another item
8. Repeat point number **7** few times. 
_Expected result_: Popup with **item description** will be opened.
_Actual result_: Popup with **item description** will be opened. The browser …
=> GGRC-5534 The search in "Filter by Mapping" when exporting doesn't work consistently

src/ggrc/migrations/utils/external_comments.py
Ids of comments from GGRCQ can correlate with ids of external comments from GGRC.
In that case we should make current actions:
1. prepare migration for update ids of external comments from GGRC side with max ids
2. update relationships with new ids
3.  recalculate revisions for comments
Run migration for move comments to external comments for Risk/Control
Update util module for migrate comment to external comment
=> GGRC-7327 Update util for ExternalComment preparation

src/ggrc-client/js/components/rich-text/rich-text.js, src/ggrc-client/js/components/rich-text/tests/rich-text_spec.js
Incorrect link for mentioning person after manual update
Preconditions:
have 2 users with
**email_1@gmail.com**
**email_2@gmail.com**
1. Navigate to a comment block
2. Type email_1 and insert the mentioning
3. Change "1" symbol to "2" by moving cursor and replacing the symbol
4. Do not click on the "email_2" item in the mentioning list and save the comment
_Actual Result:_ "**email_2@gmail.com**" email is displayed
notification is sent to **email_1@gmail.com**
mailto link has value "**email_1@gmail.com**" 
_Expected Result:_ "**email_2@gmail.com**" email is displayed
notification is sent to **email_2@gmail.com**
mailto link has value "**email_2@gmail.com**" 
Check changes of rich text. Add ```href="mailto:{email}"``` link, if text is matched **email** template.
=> GGRC-7126 Incorrect link for mentioning person

src/ggrc/models/risk.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/models/test_risk.py
Query Api returns empty result for searches by Risk.review status.
Login to ggrc-uat
1. Open global search
2. Select Risk and search by review status = "Review needed"
Fixed typo in attribute aliases (_aliases.display name)
=> QUICK-FIX Risk query api review status attribute.

src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/models/business-models/program.js, src/ggrc-client/js/templates/programs/info.stache, src/ggrc/models/program.py, src/ggrc/models/proposal.py, test/integration/ggrc/proposal/__init__.py, test/integration/ggrc/proposal/api/__init__.py, test/integration/ggrc/proposal/api/base.py, test/integration/ggrc/proposal/api/test_acl.py, test/integration/ggrc/proposal/api/test_cads.py, test/integration/ggrc/proposal/api/test_property.py, test/integration/ggrc/proposal/test_custom_creator_role.py, test/integration/ggrc/proposal/test_proposal_comments.py, test/integration/ggrc/proposal/test_proposal_email.py, test/integration/ggrc/proposal/test_proposal_permissions.py, test/integration/ggrc/proposal/test_proposal_relationship.py
User should be able to Propose changes to a Program
2. Open program
User should be able to add Proposal
Add proposable mixin to Program
=> GGRC-4211/GGRC-7189/GGRC-7190 Add proposals for program

src/ggrc-client/styles/dashboard.scss
Redundant commented out code
make sure, that `_bootstrap-setup.scss` was removed in the specified commit.
Remove the commented out import.
It's completely redundant as the file, which was imported before the line became commented, was removed in [this commit](https://github.com/google/ggrc-core/commit/d2203bc245f2887a45a63589f3b2f83977345868)
So it's completely safe to remove this commented out code.
=> QUICK-FIX Remove redundant commented out scss import

src/ggrc/migrations/versions/20190530_b142aacd3e9f_remove_unique_title_constraint_from_.py
External app has no unique constraint for risk title. Thus we need to remove it temporary from GGRC 
Run migration and check db schema.
Unique constraint for risk title was removed via migration.
=> QUICK FIX Remove unique title constraint from risk object

src/ggrc-client/js/helpers.js, src/ggrc-client/js/templates/people_roles/option_column.stache, src/ggrc-client/js/templates/roles/object_list.stache
Case 1:
1. Go to Administration page
2. Open Roles tab
**Expected result:** roles list is displayed correctly
Case 2:
1. Go to Administration page
2. Open People tab
3. Select any person
4. Click Edit Authorization in 3bb's menu
**Expected result:** roles an scopes are displayed correctly
=> QUICK-FIX Remove redundant helpers

test/selenium/src/tests/test_controls.py
Confirm user cannot edit or delete Control from info page.
=> QUICK-FIX Confirm user cannot edit or delete Control from info page

src/ggrc-client/js/components/form/field-views/multiselect-form-field-view.js, src/ggrc-client/js/components/form/fields/multiselect-form-field.js
```can-component.prototype.template```: is deprecated and should be released with ```can-component.prototype.view```
- Connect to **dev** container
- Run unit tests: ```run_karma```
Expected behavior: No warnings w/ text: '_can-component.prototype.template: is deprecated ..._'
Actual behavior: There are warnings w/ text: '_can-component.prototype.template: is deprecated ..._'
Replace ```template``` property to ```view```.
=> QUICK-FIX Replace deprecated 'template' property

src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/tests/cycle-task-group-object-task_spec.js, src/ggrc-client/js/plugins/utils/workflow-utils.js
Active Cycles/History tabs are not refreshed if Cycle is deprecated or restored
1. Create Workflow & add 1 task to Task Group
2. Activate Workflow then open Active Cycles tab and Deprecate Cycle task
3. Click on Active Cycles tab and Look at the History tab: both tabs show 'zero'
Actual Result: Active Cycles/History tabs are not refreshed if Cycle is deprecated or restored
Expected result: Active Cycles/History tabs should be refreshed if Cycle is deprecated or restored
Refresh cycle counts for current Workflow on operation to update Cycle state.
=> GGRC-5815 Refresh cycles count on restore & deprecate

src/ggrc/cache/utils.py, test/integration/ggrc/__init__.py, test/integration/ggrc/api_helper.py, test/integration/ggrc/converters/test_import_csv.py, test/integration/ggrc_basic_permissions/test_permissions_loading.py
In current implementation of import we recalculate permissions of user after processing of each row in import file. For users with ACL count bigger 300k it works quite slowly (>10s for each row).
Run import under big user (acl count > 500kk). In this import create some new objects with mappings or update existing ones (some new mappings should be created during import).
Check execution time before and after PR applying.
Recalculate user permissions only once for an import block.
=> GGRC-6910 Clean user permission cache only in the end of import

src/ggrc-client/js/components/form/fields/multiselect-form-field.js
Invalid value is selected in <ms-form-field> component.
Split ```string``` to array of items & check if ```_value``` contains selected item.
=> QUICK-FIX Fix <ms-form-field> invalid selection

src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.6.0
Set date of last change as 'updated date' of whats new (first line in release-notes.md).
=> GGRC-7366 Add Whats New for 2.6.0

src/ggrc-client/styles/_colors.scss, src/ggrc-client/styles/modules/_side-nav.scss
Colors are not unified in LHN for Directives/Controls/Objectives, Scope, Risks/Threats, People/Groups.
1. Open LHN
2. Expand accordion for Controls/Objectives
3. Look at the color of Controls: differ from Objectives
4. Expand accordion for Scope
5. Click on grey triangle for Sections
6. Hover over items: are shown in blue
Actual Result: Colors are not unified in LHN for Directives/Controls/Objectives, Scope, Risks/Threats, People/Groups.
Expected Result: Colors should be unified in LHN for Directives/Controls/Objectives, Scope, Risks/Threats, People/Groups . See style guide for all types:
Modify the below files to improve color.
src/ggrc-client/styles/modules/_side-nav.scss
src/ggrc-client/styles/_colors.scss
=> GGRC-5491 Improve color inside of Controls/Objectives and Scope in LHN

src/ggrc-client/js/bootstrap/modal-form.js, src/ggrc-client/js/components/import-export/csv-import.js, src/ggrc-client/js/components/issue-tracker/generate-issues-in-bulk-button.js, src/ggrc-client/js/components/issue-tracker/tests/generate-issues-in-bulk-button_spec.js, src/ggrc-client/js/components/issue/tests/issue-unmap-item_spec.js, src/ggrc-client/js/components/object-review/object-review.js, src/ggrc-client/js/components/object-review/tests/object-review_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/plugins/tests/utils/notifiers-utils_spec.js, src/ggrc-client/js/plugins/utils/notifiers-utils.js, src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
'Ticket' link is not displayed in tree view once tickets generation completed successfully.
1. Open Audit with Issue Tracker 'Turned OFF'
2. Create an Assessment
3. Set Ticket Tracker column in Tree View in Assessments tab
4. Turn on Issue Tracker for audit in Edit Audit popup: see Hotlist ID and Component ID in the ticket
5. Click on Generate button
6. Open Assessments tab and look at the tree view: 'Ticket' link is not displayed
Actual Result: 'Ticket' link is displayed in tree view after refreshing the page once tickets generation completed successfully
Expected Result: 'Ticket' link should be displayed in tree view once tickets generation completed successfully
Use `pubSub` to refresh Assessments tab once it's opened.
=> GGRC-6041 'Ticket' link is not displayed in tree view once tickets generation completed successfully

src/ggrc-client/js/components/inner-nav/audit-inner-nav.stache
Incorrect stache syntax in the template
Go to any audit page.
Fix the syntax
=> QUICK-FIX Fix incorrect syntax in stache prop passing

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/comment/comment-data-provider.js, src/ggrc-client/js/components/comment/comments-paging.js, src/ggrc-client/js/components/comment/comments-paging.stache, src/ggrc-client/js/components/comment/comments-section.js, src/ggrc-client/js/components/comment/comments-section.stache, src/ggrc-client/js/components/comment/mapped-comments.js, src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/cycle-task-group-object-task.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache, src/ggrc-client/js/plugins/utils/comments-utils.js, src/ggrc-client/js/plugins/utils/query-api-utils.js, src/ggrc-client/styles/components/comment/_comment-list.scss, src/ggrc/services/resources/assessment.py, test/integration/ggrc/services/resources/test_assessment.py
Control (or any other model) with 2000 comments opens about 40 seconds.
1. Open any object
2. Add more then 10 comments
**Expected result:** paging appear
Add `comments-paging` component.
=> GGRC-5462 Add paging for comments

src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.stache
Markdown is not handled properly in `assessment-mapped-controls`.
Open assessment with mapped control, where description contains a link - it should be displayed as a link.
Always handle markdown for assessment mapped snapshots.
=> GGRC-7199 Always handleMarkdown of snapshots in assessments

src/ggrc/models/snapshot.py, test/integration/ggrc/automapper/test_automappings.py
Original object is not automapped to parent program via audit
1. Create program1 and program2
2. Map program1 as a child to program2 
3. Create audit for program1(child)
4. Open audit and map any object to make a snapshot (e.g. Product)
5. Open program1(child): Product is mapped 
6. Open program2(parent): Product is not mapped 
Actual Result: Object is not automapped to parent program if map it via audit
Expected Result: Object should be automapped to parent program if map it via audit
Issue happened because of creation of relationship using raw sql query without initialising Relationship model. That is why automapping hooks not catched new relationships.
Relationship creation logic changed to ORM models.
Also I noticed that `before flush` hook was triggered 4 times …
=> GGRC-7251 Original object is not automapped to parent program via audit

src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js
=> QUICK-FIX Fix code styles

src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
Commented out code. The code was found during working on another PR. Decided to create separate PR for it. 
Remove it
=> QUICK-FIX Remove commented out code in cacheable spec

test/selenium/conftest.py, test/selenium/src/lib/base.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/entities/mixin.py, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_objects_review.py
Confirm reviewer with Read rights for an object can request object review and assign people for review an object
=> QUICK-FIX Confirm reviewer with Read rights for an object can request object review

src/ggrc-client/js/components/object-list-item/document-object-list-item.js, src/ggrc-client/js/components/object-list-item/document-object-list-item.stache, src/ggrc-client/js/components/object-list-item/tests/document-object-list-item_spec.js, src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
**As a Auditor** I want to **know if an Evidence, that is used in an Assessment, or an Evidence, that could be re-used from a Related Assessment, are Active or Deprecated
**So that** deprecated Evidences won't be used for Assessment unintentionally
- Create Audit & map Control to it
- Create Assessment
- Create & Map Evidence Url to Assessment
- Deprecate Evidence Url
- Open Assessment Info Pane
Expected behavior: Evidence Url is marked as Deprecated (colored appropriately & have label "Deprecated" in title)
Add special class and text to link element based on state of Evidence instance.
=> GGRC-4922 Mark inactive evidences as 'deprecated'

src/ggrc-client/js/components/tree/templates/sub-tree-models.stache, src/ggrc-client/styles/components/tree/_tree-view.scss
sub-tree-models popup has fixed height thus items can go out of the border.
Open sub-tree-models popup for Issue.
Change layout to `column-width`
=> GGRC-5528 Fix layout of sub-tree-models

src/ggrc-client/js/templates/programs/modal_content.stache
Fields 'Reference URL', 'Attachements' & 'Code' are not proposable and should not be displayed on 'Propose Changes' modal window. 
- Create Program & open Program Info page
- Open 'Propose Changes' modal
Expected behavior: 'Reference URL', 'Attachements' & 'Code' are hidden
Actual behavior: 'Reference URL', 'Attachements' & 'Code' are visible
Add **{{^if isProposal}}** verification to program **modal_content** template.
=> QUICK-FIX Hide non-proposable fields from proposal modal

src/ggrc-client/js/templates/cycle_task_group_object_tasks/modal_content.stache, src/ggrc-client/styles/modules/_modal.scss
Incorrect layout of Due date for Cycle Task
1. Log in ggrc app and open My work page
2. Open My Tasks tab and click on Create button
3. Clean Due Date
Added line breaks between the Start Date and Due sate fields in the Create New Cycle task page
=> GGRC-7137 Layout of Due date for Cycle Task Modified

src/ggrc-client/js/components/last-comment/last-comment.js, src/ggrc-client/js/components/last-comment/last-comment.stache, src/ggrc-client/js/components/last-comment/last-comment_spec.js, src/ggrc-client/js/components/tree/templates/tree-item-attr.stache, src/ggrc-client/js/components/tree/tree-item-attr.js, src/ggrc-client/js/plugins/ggrc_utils.js, src/ggrc-client/js/plugins/tests/ggrc_utils_spec.js
Display text as a link for Description, Notes, Assessment Procedure in tree view
1. Log into GGRC app
2. Try creating any object for example an objective.
3. Add some text, containing URL links, for attributes Description, Notes, Assessment Procedure while creating the object.
4. Open the created object tab and view the view.
5. The values displayed for attributes Description, Notes, Assessment Procedure should contain hyperlinks
The function 'getDefaultValue' in 'src/ggrc-client/js/components/tree/tree-item-attr.js'  is modified such that it retains the html tags, present in attribute values.
=> GGRC-7157 Display url text as hyperlinks

src/ggrc-client/js/models/business-models/workflow.js
POST 400 while creating Repeat On workflow.
1. Open New workflow popup
2. Set Repeat ON workflow, weekly, repeat every two weeks > Save
"repeat_every' should be integer or 'null" error is displayed in UI
POST 400 in console
**Expected Result:** no errors should be displayed. Repeat ON workflow should be created
Set type for `repeat_every` prop.
=> GGRC-7416 Fix exception while creating Repeat On workflow

src/ggrc-client/js/components/assessment/custom-attributes.stache
No mandatory asterisk for required assessment GCA
1. Log in as admin to ggrc app
2. Go to Admin page and add any mandatory GCA for Assessment
3. Open audit and create Assessment
4. On Assessment info panel click on Other Attributes tab and look at the mandatory CA
Actual Result: Mandatory star is missed
Expected Result: Mandatory star should be displayed next to mandatory field
Pass down mandatory property of GCA to the `base-inline-control` in `assessment-custom-attributes` and inside it use it to show (or don't show) mandatory asterisk
=> GGRC-7279 Show mandatory asterisk for required assessment GCA

src/ggrc-client/js/templates/access_groups/modal_content.stache, src/ggrc-client/js/templates/account_balances/modal_content.stache, src/ggrc-client/js/templates/contracts/modal_content.stache, src/ggrc-client/js/templates/data_assets/modal_content.stache, src/ggrc-client/js/templates/facilities/modal_content.stache, src/ggrc-client/js/templates/issues/modal_content.stache, src/ggrc-client/js/templates/key_reports/modal_content.stache, src/ggrc-client/js/templates/markets/modal_content.stache, src/ggrc-client/js/templates/metrics/modal_content.stache, src/ggrc-client/js/templates/objectives/modal_content.stache, src/ggrc-client/js/templates/org_groups/modal_content.stache, src/ggrc-client/js/templates/policies/modal_content.stache, src/ggrc-client/js/templates/processes/modal_content.stache, src/ggrc-client/js/templates/product_groups/modal_content.stache, src/ggrc-client/js/templates/products/modal_content.stache, src/ggrc-client/js/templates/programs/modal_content.stache, src/ggrc-client/js/templates/projects/modal_content.stache, src/ggrc-client/js/templates/regulations/modal_content.stache, src/ggrc-client/js/templates/requirements/modal_content.stache, src/ggrc-client/js/templates/standards/modal_content.stache, src/ggrc-client/js/templates/systems/modal_content.stache, src/ggrc-client/js/templates/technology_environments/modal_content.stache, src/ggrc-client/js/templates/threats/modal_content.stache, src/ggrc-client/js/templates/vendors/modal_content.stache
Mandatory roles are hidden if click ''Hide all optional fields''
1. Open modal for creation of Program or Issue or Contract
2. Title, and role fields are marked as mandatory
3. Click on 'Hide all optional fields'
Actual result: Role field is hidden
Expected result: Mandatory role field is visible
Modify following fields to fix hidden mandatory roles when "Hide all optional fields" clicked
src/ggrc-client/js/templates/contracts/modal_content.stache
src/ggrc-client/js/templates/issues/modal_content.stache
src/ggrc-client/js/templates/programs/modal_content.stache
=> GGRC-7263 Fix hidden mandatory roles when "Hide all optional fields" clicked

test/selenium/conftest.py, test/selenium/src/lib/utils/assert_utils.py
*Added soft_assert with example.
```
class TestDemoSoftAssert(object):
def test_demo_soft_assert(self, soft_assert):
expected_value_1 = 1
actual_value_1 = 2
soft_assert.expect(
expected_value_1 == actual_value_1,
msg='Value 1 error. Expected: {}, Actual: {}'.format(
expected_value_1, actual_value_1))
expected_value_2 = 1
actual_value_2 = 2
soft_assert.expect(
expected_value_2 == actual_value_2,
msg='Value 2 error. Expected: {}, Actual: {}'.format(
expected_value_2, actual_value_2))
soft_assert.expect(
True is True,
msg='This is OK. So we do not see the error in the list.')
soft_assert.assert_expectations()
```
=> QUICK-FIX Added soft_assert to libs

src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js, src/ggrc-client/js/components/view-models/object-operations-base-vm.js, src/ggrc-client/js/models/service-models/user-role.js
Fixes for comments in #9629 PR.
=> QUICK-FIX Clean up mappings

src/ggrc-client/js/components/page-header/page-header.js
**LNH** controller can be inited multiple times.
1. Turn on **NETWORK** and **CPU** throttling;
2.  Add breakpoint in `init` method of **LHN** controller;
3. Try to open **LNH** by multiple clicking on icon (click 3-5 times);
_Expected result_: Chrome Debugger inserted into `init` method of **LHN** controller 1 time.
_Actual result_: Chrome Debugger inserted into `init` method of **LHN** controller few times.
Set immediately `lhnInitialized` to `true` after click by **LHN** icon.
=> QUICK-FIX Prevent multiple init of LHN controller

src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
1. Run karma tests
2. Open tests in browser
3. Check Console
Expected result: No exceptions.
Mock `loadFirstComments` functions.
=> QUICK-FIX Fix exceptions in unit tests

src/ggrc/integrations/constants.py, src/ggrc/integrations/synchronization_jobs/assessment_sync_job.py, test/integration/ggrc/integrations/test_assessment_integration.py
**Current Behavior**:
Assessment Status | Related Ticket Status
-- | --
Not Started | Assigned
In Progress | Assigned
Rework Needed | Assigned
**Expected Behavior**:
Assessment Status | Related Ticket Status
-- | --
Not Started | Assigned
In Progress | Accepted
Rework Needed | Accepted
1. Create Audit with Assessment and IssueTracker turned on
2. Change Assessment status from 'Not Started' to 'In Progress' and check status of corresponding ticket in IssueTracker
Updated mappings
=> GGRC-5896 Update mappings on assessment and ticket statuses

src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/models/conflict-resolution/conflict-resolution.js, src/ggrc-client/js/plugins/ajax_extensions.js, src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js, src/ggrc/services/common.py, test/integration/ggrc/services/test_common.py
on conflict the PUT request could return the new data + new etag and we would not need to do another GET after the conflicting PUT
1. Open for edit existing object in two tabs
2. Edit and Save object in tab 1
3. Try to Edit and Save object in tab 2
Expected result: We should receive error 409  + new Etag + new data
Add Etag and Last-Modified fields to headers and actual object state to response body
=> GGRC-5570 Conflict resolution performance improvement

src/ggrc/migrations/versions/20190610_b6e89c388581_update_modified_by_id_to_not_null.py, src/ggrc/utils/revisions.py, src/ggrc/utils/user_generator.py, test/integration/ggrc_workflows/notifications/test_data_handler.py, test/integration/ggrc_workflows/notifications/test_monthly_wf.py, test/integration/ggrc_workflows/test_recurring_cycles_event.py, test/integration/ggrc_workflows/test_workflow_cron_job.py
Event created during migration does not contain owner
1. Login as admin
2. Go to /admin#!events_list
3. Find events created by migration 
Actual Result:
First line |by| is empty
First line |by <some_user@example.com>|
1. Modify src/ggrc/utils/revisions.py file to include "modified_by_id"
2. Create below migration file to update existing null values and make modified_by_id column not null 
src/ggrc/migrations/versions/20190425175432_a87a3d6f6c47_update_modified_by_id_to_not_null.py
3. Modify below files to fix test failures
src/ggrc/utils/log_event.py
test/integration/ggrc_workflows/notifications/test_data_handler.py
=> GGRC-6443 Fix owner for event created during migration

src/ggrc/access_control/list.py, src/ggrc/converters/base_row.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/acl.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/models/test_assessment.py, test/integration/ggrc/notifications/test_assessment_notifications.py, test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py
When we import assessment and update creator/verifier/assignee values we should set IN PROGRESS state, as it implemented for UI.
1. Export Assessment in Completed state
2. Add or change or remove verifier/creator/assignee
3. Import Assessment
Actual Result: actual status is not changed in UI
Expected Result: assessment status should be changed to 'IN PROGRESS'.
Previously ImportRowConverter#process_row flushed session before creating secondary_objects and sending before commit signals. We should flush the object only if it is new.
=> GGRC-6804 GGRC-6529 Change assessment status after adding a verifier/creator/assignee via import

src/ggrc/converters/base_block.py, src/ggrc/converters/handlers/snapshot_instance_column_handler.py, src/ggrc/utils/helpers.py, src/ggrc/utils/objects_cache.py, src/ggrc/utils/rules.py, test/integration/ggrc/converters/test_export_csv.py
Export of Assessments takes too a lot of time.
Run export of Assessments/Issues on latest dev and on this PR. Compare timings.
Keep slugs of Snapshots mapped to exporting objects in cache.
=> GGRC-6834 Improve export performance for Assessment and Issue

src/ggrc/login/__init__.py, src/ggrc/login/common.py, src/ggrc/models/person.py, src/ggrc/settings/default.py, src/ggrc/settings/testing.py, src/ggrc/utils/user_generator.py, src/ggrc_basic_permissions/__init__.py, test/integration/external_app/__init__.py, test/integration/external_app/external_api_helper.py, test/integration/external_app/test_ext_app_login.py, test/integration/external_app/test_ext_system.py, test/unit/ggrc/login/test_appengine.py, test/unit/ggrc/test_login.py, test/unit/ggrc/utils/test_user_generator.py
No Questionnaire created for new (ext system app) because of sync from ggrc to external app is broken.
Sync is sensitive to modified_by e.g if object was created/modified by external app, sync is disabled.
Deploy and run sync. Check tests.
We need to distinguish request from external app and sync service. To do that we will use another configuration variable (SYNC_SERVICE_USER).
Refactored login functionality to support multiple service accounts.
=> GGGR-7321 No Questionnaire created for new ext System app

src/ggrc/converters/column_handlers.py, src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_export_assessment_templates.py, test/integration/ggrc/converters/test_import_assessment_templates.py
Assessment procedure is not displayed in export template and after import in UI
1. Log in ggrc app and open audit page
2. Create assessment template with any Assessment procedure
3. Export assessment template to google sheet/csv
4. Look at the 'Default Assessment Procedure' column: value is missed
5. Download 'Assessment template' import template
6. Fill out required fields, add any 'Default Assessment Procedure' and import it
We use incorrect field name during import/export. Field name updated to procedure_description
=> GGRC-7142 Assessment procedure is not displayed in export template and after import in UI

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/entities/mixin.py, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_objects_review.py
Confirm user with Edit rights can revert object review to unreviewed by editing this object.
=> QUICK-FIX Confirm user with Edit rights can revert object review to unreviewed

src/ggrc-client/js/bootstrap/modal-ajax.js, src/ggrc-client/js/components/unified-mapper/mapper-results-item.js, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc-client/js/controllers/modals/modals_controller.js
Mapper doesn't refresh list of mapped items when some item was deleted via [Delete] button.
1. Open Mapper.
2. Search for some objects.
3. Expand first row, click 3 dots menu, click [Delete]. Confirm deletion.
4. When deletion is completed, click the same menu in the same row again, click  [Delete] again.
Expected results: Refresh list of search results in mapper after deletion of an item.
Actual result: Confirmation modal asks if you want to delete the object that goes as next in the list.
When item is destroyed, `<mapper-results-item>` dispatches `itemDataDestroyed` event which is handled by parent component `<mapper-results>` (it refreshes current list of items + removes destroyed item from `selected` collection to prevent mapping of deleted object).
=> GGRC-7213 Mapper: double delete of the same item in search deletes next item

src/ggrc/templates/notifications/email_digest_content.html, src/ggrc_workflows/models/cycle.py, src/ggrc_workflows/notification/data_handler.py, test/unit/ggrc_workflows/notification/test_data_handler.py
Workflow links in daily digest are broken
Previous PR for this ticket #9278 
Generate daily digest using http://localhost:8080/_notifications/send_daily_digest . Check workflow and cycle links
Cycle link use filter to show exact cycle on workflow page
=> GGRC-6553 Cycle link in daily digest point to workflow

test/integration/ggrc/snapshotter/test_snapshoting.py
Snapshot has flag "is_latest_revision" == False but, it matches latest revision
1 Log in.
2 Create a snapshot.
3 Update original object.
4 Update snapshot to the latest version.
5 See that snapshot has is_latest_revision flag == True.
Added new integration test that checks the behavior of is_latest_revision flag
=> GGRC-6067 Add test for checking is_latest_revision

src/ggrc/notifications/fast_digest.py, src/ggrc/notifications/review_helpers.py, src/ggrc/templates/notifications/fast_digest.html, test/integration/ggrc/notifications/test_review_notiffications.py
Notification email does not appear in email digest when object review status changes from 'Reviewed' to 'Unreviewed'. 
Create Program
Assign user as reviewer
Click "Mark reviewed" button
Edit program (e.g. change Description)
open _notifications/show_fast_digest
Add EmailReviewContext for all Reviewers in reviewable object
=> GGRC-7349 Notification email that obj is reverted to 'Unreviewed' does not appear in email digest

src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.7.0
Set date of last change as 'updated date' of whats new (first line in release-notes.md).
=> GGRC-7446 Add Whats New for 2.7.0

src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/plugins/autocomplete.js
Unused variables
1. Run unittests
2. Click through the app
3. Try to find any way how those variables can be used
Remove variables as well as argument
=> QUICK-FIX Remove unused variables

src/ggrc-client/js/components/quick-update/ggrc-quick-update.js, src/ggrc-client/js/components/workflow/cycle-task-group-object-task/templates/cycle-task-group-object-task.stache, src/ggrc-client/js/helpers.js
1. Create cycle task with checkbox/dropdown type
2. Check that all works as expected
Removed deprecated code.
=> QUICK-FIX Clean up ggrc-quick-update component

src/ggrc-client/js/components/external-data-autocomplete/external-data-autocomplete.js
JS error in `external-data-autocomplete` when search is empty.
1. Create WF.
2. Open create Task Group modal.
3. Empty Assignee input.
Protect `searchCriteria` from undefined value.
=> GGRC-7435 Protect searchCriteria from empty value

src/ggrc-client/styles/components/mapped-controls/_mapped-controls.scss
The padding between description and horizontal line is 12 px instead of d 20 px
2. Map control and access group to audit
3. Create assessment with Control type
4. Open Assessment info panel> Other attributes tab
5. Click Map icon for Related Information and map Access group snapshot to assessment
6. Click on Access group snapshot to open popup
7. Look at the DESCRIPTION
Actual Result: Layout of the description is incorrect
2. Map control and access group to audit
3. Create assessment with Control type
4. Open Assessment info panel> Other attributes tab
5. Click Map icon for Related Information and map Access group snapshot to assessment
6. Click on Access group snapshot to open popup
7. Look at the DESCRIPTION
Modified the …
=> GGRC-6801 Modified padding between description and horizontal line

src/ggrc/notifications/people_mentions.py, src/ggrc/templates/notifications/bulk_child_sync_failed.html, src/ggrc/templates/notifications/bulk_sync_failed.html, src/ggrc/templates/notifications/email_digest_content.html, src/ggrc/templates/notifications/fast_digest.html
It's possible to use html tags inside object title, these tags will be rendered inside mail body. For example create control with title `<a href="https://www.google.com/">my control</a>`. Rendered mail body will contain only "my control" with redirection to google.com.
1. Create Cycle Task with title containing html tag
2. Mention a person in a comment
3. Send daily digest email
This is additional fix for PR https://github.com/google/ggrc-core/pull/9154.
Titles inside links should be also escaped
=> GGRC-6059 There is possibility to create html code injection into mail body

test/selenium/conftest.py, test/selenium/src/lib/page/widget/tree_widget.py, test/selenium/src/tests/test_controls.py, test/selenium/src/tests/test_unified_mapper.py
Confirm user cannot edit Control from tree view.
=> GGRC-7449 Confirm user cannot edit Control from tree view

src/ggrc/query/pagination.py, test/integration/ggrc/models/test_control.py, test/integration/ggrc/models/test_query_api_queries.py, test/unit/ggrc/query/test_pagination.py
If we create 2 assessments in 1 second (using api), they have the same time string and looks like can't be sorted correctly.
Create asmts quickly after each other using API
Program
-> Control
-> Audit-1 -> Asmt-1 mapped to Control
-> Audit-2 -> Asmt-2 mapped to Control
Check Related Assessments on Control's page
Add additional sorting by id. If we will have sorting by equal values, then we will see sorting in order of object creation (asc or desc).
=> GGRC-6524 Related asmts are displayed in random order

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/gca-controls/gca-controls.js, src/ggrc-client/js/components/revision-history/restore-revision.js, src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/models/business-models/tests/assessment_spec.js, src/ggrc-client/js/models/cacheable.js
Assessment: Error if click Complete button after adding/deleting person in acl.
Precondition:
1. Mandatory Custom Attribute was created for Assessments (Global CA) - all existing assessments got new mandatory CA with no value.
2. When user press [Complete], there is a validation on BE that checks all mandatory CA are filled.
3. Since Assessment wasn't edited and mandatory CA from step 1 is empty, validation fails, error message is sent to FE.
Steps:
1. Log in ggrc app and open any assessment in "In progress" state
2. Add a verifier and click on Complete button: PUT 400 with an error in UI is shown up
3. Remove any assignee/verifier and click on Complete button: PUT 400 with an error in UI is shown up
**Actual Result:** Error if click Complete button after adding/deleting person in acl …
=> GGRC-7141 Validate GCAs before assessment completing

src/ggrc/models/custom_attribute_definition.py, src/ggrc/models/custom_attribute_value.py
Import of 1000 assessments crashed after 24 hours.
Import Assessment with LCA and measure queries count(expected 25, about 18k before fix)
Validation that forbids creation of global custom attribute with type Map:Person triggers queries to custom_attributes_definition table after every flush and slows down import.
=> GGRC-7476, GGRC-7477 Remove Map:Person validation on CA

src/ggrc-client/js/components/release-notes-list/release-notes.md
=> QUICK-FIX Update release date

src/ggrc/converters/column_handlers.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_export_risk.py, test/integration/ggrc/models/factories.py
Export failed due to server error. Please try again or contact our support team." is displayed while exporting Risks
1. Log in ggrc app
2. Export any Risk
3. Open Export page and look at the export results
Actual Result:
"Export failed due to server error. Please try again or contact our support team." error is displayed in UI;
Risks are not exported
Expected Result: Risks should be exported
Created ExportOnlyPersonColumnHandler thats used to export "created_by" columns.
=> GGRC-7478 Fix risk export.

src/ggrc-client/js/templates/assessments/header.stache
Incorrect message to remind Assignees
1. Open any assessment
2. Click on 'Send reminder to assignees in 3 dots menu
3. Look at the Reminder to assignees popup
4. Click on ESC on keyboard
**Actual Result**: Incorrect message is displayed ('Tomorrow all Assignees will receive a notification to look at this Assessment if they didn&#39;t move it to &#39;Finished&#39; in between.')
**Expected result**: Improve message to remind Assignees ('A reminder to complete the Assessment for Assignees will be sent in the next daily email digest.')
Change message to remind assignees
=> GGRC-7180 Incorrect message to remind Assignees

src/ggrc-client/styles/_responsive.scss, src/ggrc-client/styles/modules/_modal.scss
Hacky IE7-only css properties
Read https://stackoverflow.com/a/1667548
Click through the app
Remove hacky properties
=> QUICK-FIX Remove hacky css ie7-only properties

src/ggrc-client/js/components/external-data-autocomplete/external-data-provider.js, src/ggrc-client/js/components/external-data-autocomplete/tests/external-data-provider_spec.js, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
`ggrcGet` expects 2 arguments (**url** and **data**),
1. Log in ggrc and open any audit
2. Add an auditor: type person email
_Actual Result_: "Uncaught TypeError: e.url.split is not a function" error is displayed;
dropdown list with users email is not displayd
_Expected Result_: User should be able to assign a person to role
Pass **2 arguments** (**url** and **data**) instead of object with **url** and **data** properties.
=> GGRC-7498 Fix "Uncaught TypeError: e.url.split is not a function" error which occurs while adding a person to any role	

src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.js, src/ggrc-client/js/components/object-list-item/business-object-list-item.js, src/ggrc-client/js/components/object-list-item/detailed-business-object-list-item.js, src/ggrc-client/js/components/tree/sub-tree-item.js, src/ggrc-client/js/components/tree/sub-tree-wrapper.js, src/ggrc-client/js/components/tree/tests/sub-tree-item_spec.js, src/ggrc-client/js/components/tree/tests/tree-actions_spec.js, src/ggrc-client/js/components/tree/tree-actions.js, src/ggrc-client/js/components/unified-mapper/mapper-results-item.js, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc-client/js/models/business-models/task-group-task.js, src/ggrc-client/js/models/business-models/task-group.js, src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/plugins/tests/snapshot-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/mega-object-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/tree-view-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js, src/ggrc-client/js/plugins/utils/current-page-utils.js, src/ggrc-client/js/plugins/utils/mega-object-utils.js, src/ggrc-client/js/plugins/utils/snapshot-utils.js, src/ggrc-client/js/plugins/utils/tree-view-utils.js, src/ggrc-client/js/templates/audits/dropdown_menu.stache
Refactor buildCountParams in _buildSubTreeCountMap() method in tree-view-utils.js
Testing of sub-tree is required.
Counts query transformation was improved. Add tests.
Remove unused prop and functions.
=> GGRC-7208 Refactor _buildSubTreeCountMap in tree-view-utils

src/ggrc/migrations/versions/20190625_e1988524ed3e_set_default_value_in_workflows_table.py, src/ggrc_workflows/models/workflow.py, test/integration/ggrc/access_control/rbac_factories/base.py, test/integration/ggrc_workflows/converters/test_cycle_task_import_update.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py, test/integration/ggrc_workflows/notifications/test_wf_notifs_generator.py, test/integration/ggrc_workflows/test_api_calls.py, test/integration/ggrc_workflows/test_basic_workflow_actions.py, test/integration/ggrc_workflows/test_status_propagation.py, test/integration/ggrc_workflows/test_workflow_api_calls.py
'Need verification' should have false default value in DB
1. Connect to container hosting ggrc app.
2. Log into MySQL db with a similar command shown below.
> mysql -hdb ggrcdev
3. Look into schema of 'workflows' table and ensure that default value of 'is_verification_needed' column is set to '0' i.e False.
> desc workflows;
Written a migration file '20190625_e1988524ed3e_set_default_value_in_workflows_table.py' to set the default value of 'is_verification_needed' column to '0'.
=> GGRC-4419 Set default value in Workflows Table

test/selenium/conftest.py, test/selenium/src/lib/page/fast_emails_digest.py, test/selenium/src/lib/service/emails_digest_service.py, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/tests/test_objects_review.py, test/selenium/src/tests/test_snapshots.py
Confirm that user assigned as reviewer for object gets an email notification that object review is reverted to 'Unreviewed' state
=> GGRC-7447 Confirm that user gets an email notification when obj review is reverted to 'Unreviewed'

src/ggrc-client/js/plugins/tests/utils/object-versions-utils_spec.js, src/ggrc-client/js/plugins/utils/object-versions-utils.js
=> QUICK-FIX Clean up object-version utils

src/ggrc-client/js/templates/assessment_templates/modal_content.stache, src/ggrc-client/js/templates/assessments/modal_content.stache, src/ggrc-client/styles/modules/_modal.scss
…ssment
Add 'i' icon near 'Copy Assessment Procedure from mapped object' on 'New Assessment', 'Edit Assessment, 'New Assessment Template' , 'Edit Assessment Template'
Login to GGRC application:
1. Create an Assesment.
2. Click on Edit Object.
Added 'i' icon near 'Copy Assessment Procedure from mapped object' on 'New Assessment', 'Edit Assessment, 'New Assessment Template' , 'Edit Assessment Template'
=> GGRC-3481 Improve the message for 'Copy Assessment Procedure' checkbox for Assessment

test/integration/external_app/test_export_risk.py, test/integration/ggrc/converters/test_export_assessments.py, test/integration/ggrc/query_helper.py
Fix code style failures in release branch introduced by #9748 and #9745 
Export query in tests `test_risk_all_attrs_export` and `test_export_with_missing_lca` is now being constructed with `WithQueryApi` mixin's methods to prevent pylint duplication code errors.
=> QUICK-FIX Fix code style in release branch

src/ggrc/services/common.py, src/ggrc/views/common.py, test/integration/ggrc/services/test_head.py
*Requests to non valid url lead to server error*
*1) launch the ggrc app
2) Ensure that you logged in
3) Send HEAD requests to Non Valid url.
Ex.: 
/api/controls 
/controls/id - id should not be present in the DB
Preveous results: 500 NotImplementedError
Expected results: 405 MethodNotAllowed*
*There are was changed NotImplementedError to MethodNotAllowed*
=> GGRC-5384 Fixes server error while head request to non valid url

src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache, src/ggrc-client/js/components/object-generator/object-generator.js, src/ggrc-client/js/components/object-generator/object-generator.stache, src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js, src/ggrc-client/js/components/object-mapper/object-mapper.js, src/ggrc-client/js/components/object-mapper/object-mapper.stache, src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js, src/ggrc-client/js/components/object-search/object-search.js, src/ggrc-client/js/components/object-search/object-search.stache, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results_spec.js, src/ggrc-client/js/components/view-models/object-operations-base-vm.js, src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Search results should be reset if user changes object type in search modals. _No results_ test should be displayed.
It should be applied to global search, object mapper, object generator modals.
1. go to Audit with few assessment templates of different object types 
2. click 'Autogenerate'
3. See opened popup 'Select [object] to generate assessments'
4. Choose one assessment template (e.g. of object type 'Regulation')
5. Choose another assessment template (of another object type, e.g. 'Org group')
_**Actual result:**_ Search results section is not updated to a new object type
**_Expected result:_** Refresh of a search section happens to show the objects of a needed type.
Use `resultsRequested` flag to display required message.
=> GGRC-7220 Reset search results on changing object type

test/selenium/src/lib/element/info_widget_three_bbs.py, test/selenium/src/lib/factory.py, test/selenium/src/lib/page/dashboard.py, test/selenium/src/lib/page/modal/global_search.py, test/selenium/src/lib/page/modal/object_mapper.py, test/selenium/src/lib/page/modal/search_modal_elements.py, test/selenium/src/tests/test_controls.py
Confirm user cannot edit or delete Control from Global Search
=> GGRC-7448 Confirm user cannot edit or delete Control from Global Search

src/ggrc-client/js/components/release-notes-list/release-notes.md
Updates for 'What's new' v2.8.0
Set date of last change as 'updated date' of whats new (first line in release-notes.md).
=> GGRC-7503 Update Whats New for 2.8.0

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/converters/test_import_comprehensive.py, test/unit/ggrc/converters/handlers/test_custom_attribute.py
Import of assessment with empty GCA of multiselect type some time leads to import error.
1. Open https://ggrc-uat.googleplex.com/audits/1#!assessment audit
2. Export assessments from the audit and import it back w/o changes
Actual Result: " Import failed due to unknown error." is displayed
Expected Result: No errors should be displayed while importing
Updated CustomAttributeColumnHandler to return None instead empty string.
=> GGRC-7481 Fix import assessment with empty GCA of multiselect type.

src/ggrc/services/resources/related_assessments.py, test/integration/ggrc/services/resources/test_related_assessments.py
1. Log as Admin user 
2. Create a program with mapped control and audit to the program
3. Assign Global Creator as Auditor to Audit
4. Open audit page and generate 2 assessments based on the control snapshot
5. Log as Auditor (Global Creator) and open Audit page
6. Open Control tab, expand Control Info panel and click on Assessment button
Actual Result: Global creator as auditor doesn't see Related Assessments:
Related assessments tab is empty;
GET 403 is displayed in Network tab
Expected Result: Global creator should be able to see Related Assessments
Add Objective and Control to read permissions of Creator in `ggrc_basic_permissions/roles/Creator.py`
=> GGRC-4742 Related Assessment window on Controls/Objectives doesn't show related Assessments if user has no read rights for original object 

docs/source/backend/object_manipulation.rst
Remove references to Request model in the front end and the docs
Open the file 'docs/source/backend/object_manipulation.rst' and check if any documentation about 'Request' object exists.
Removed the documentation corresponding to 'Reference' Object.
I've investigated the entire code base for the presence of 'Request' object and have not found any occurrences in code.
=> GGRC-767 Remove FE references to Request model

src/ggrc/migrations/versions/20190520_e75eb65a5a43_remove_invalid_entries_qa_inst.py
GGRC-qa db has air for object_type = ‘CR’ and other invalid types
Created migration for clean up db.
=> GGRC-5106 Remove invalid entries from QA instance db.

src/ggrc/settings/default.py
=> QUICK-FIX Bump up version to 2.9.0-Pumpkin

src/ggrc/migrations/versions/20190711_02e4af0bba5b_notify_after_proposed_program_change.py, test/integration/ggrc/proposal/test_proposal_email.py
No notifications recieved by the Program Manager, Program Editor or Primary Contact. In SPAM folder there are none either.
User is a Program Manager/Program Editor/Primary Contact (in a Program)
1. Click "Propose Changes" button
2. Edit several attribute fields, e.g. Title/Description or any LCA field
3. Click "Propose" button
4. Check email of Program Manager/Program Editor/Primary Contact
1. Program Manager/Program Editor/Primary Contact had notify_about_proposal SETTed 0
2. Only ACR with notify_about_proposal == 1 was able to receive email
3. Created the migrations were this param was setted to 1 for the Program Manager/Program Editor/Primary Contact
=> GGRC-7522 Program manager/Editor/Primary Contacts don't receive the updates notifications

src/ggrc/settings/default.py
=> QUICK-FIX Bump up version to 2.10.0-Pumpkin

src/ggrc/access_control/utils.py, src/ggrc/automapper/__init__.py, src/ggrc/models/relationship.py, src/ggrc/utils/__init__.py
Program with 8-10k mapped objects is quite possible on prod. It would be great if mapping of such a big program to another program completes in ~1 minute.
1. Create a program with 8-10K of mapped objects;
2. Create program without mapped objects;
3. Map the program from 1st step to program created in 2nd step.
**Expected result: mapping should complete in ~1 min.**
This PR contains two main improvements:
1. Relationship and automapper is modified in a way that only relationships to such objects would be cached that are present in automapping rules.
2. New ACLs are now **both** selected and inserted in chunks.
Timing results obtained on ggrc-perf v 2.7.0 instance.
|N|Before changes (sec) | After changes (sec)|
|---|---|---|
|1|78|75|
|2|110|90|
|3|106|71|
|4|78|56|
|Avg|93|73|
=> GGRC-7242 Improve performance for mapping big program

package.json
npm SPDX license warning when `npm i`
`npm i`
=> QUICK-FIX Update package.json license to SPDX

src/ggrc-client/js/components/tree/tree-widget-container.js
Infinite loading on Active Cycles tab is displayed after workflow activating.
1. Create Workflow
2. Add task to Task Group
**Actual result:** Active Cycles tab is opened. Loading is infinite.
**Expected result:** Active Cycles tab is opened. Active cycles list is displayed.
Do not refresh counts for Workflow from `tree-widget-container` component as it does not properly handle additional filters for `Active Cycles` and `History` tabs. All cases for refreshing counts on Workflow page are handled inside related components.
=> GGRC-7502  Fix infinite loading on Active Cycles tab after workflow activating

src/ggrc/models/relationship.py, src/ggrc/settings/testing.py, src/ggrc/utils/user_generator.py, test/integration/external_app/external_api_helper.py, test/integration/external_app/test_ext_relationships.py, test/selenium/src/lib/service/rest/session_pool.py
Manually created scope mappings on GGRC are removed with dependency created answer deprecate
1. Map two GGRC assets in GGRC
2. Create questionnaire with dependency question for one of existing assets
3. Add another asset as Dependency answer
4. Deprecate answer on GGRCQ side
5. Go to GGRC
Expected:
Relationship exists in GGRC
No records about auto mapping/unmapping in changelog
Actual:
Relationship deleted.
Record about delete in change log
I've updated relationship delete validator to distinguish request sync_service or external_app based on request header (service account).
Requests from external_app are validated for is_external flag. 
Validation for requests from sync_service is skipped.
=> GGRC-7015 Manually created scope mappings on GGRC are removed with dependency created answer deprecate

src/ggrc/migrations/versions/20190715_22c80af7da75_add_people_profiles_admin_to_acr.py, src/ggrc/models/person.py, src/ggrc/models/person_profile.py, src/ggrc_basic_permissions/roles/Creator.py, src/ggrc_basic_permissions/roles/Editor.py, src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc/access_control/test_access_control_list.py, test/integration/ggrc/models/hooks/acl/test_propagation.py, test/integration/ggrc/models/test_assessment.py, test/integration/ggrc/services/__init__.py, test/integration/ggrc/snapshotter/test_snapshoting.py, test/integration/ggrc/utils/test_user_generator.py, test/integration/ggrc/views/saved_searches/test_saved_search_delete.py, test/integration/ggrc/views/saved_searches/test_saved_search_get.py, test/integration/ggrc/views/saved_searches/test_saved_search_post.py, test/integration/ggrc_basic_permissions/test_person_profile_permissions.py, test/integration/ggrc_workflows/test_workflow_api_calls.py, test/selenium/src/tests/test_admin_dashboard_page.py
Currently all users can read person profiles through the api. So any user can get profile information of any other user. It's possible by sending GET request to <instance name>/api/people_profiles.
Send GET request to <instance name>/api/people_profiles. 
Add AccessControll rules for people_profiles api.
=> GGRC-6605 Create ACR for PersonProfile

test/selenium/src/tests/test_asmts_workflow.py
Need to run checks about 10 times to prove development fix 
=> GGRC-7535 Remove GGRC-6524 check from selenium tests

src/ggrc-client/styles/components/advanced-search/_advanced-search.scss, src/ggrc-client/styles/components/saved-search-list/_saved-search-list.scss, src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
*simple modal* component isn't scrollable
2. Open All object page
3. Select any object, e.g Controls
4. Open Advanced Search pop-up
5. Add at least 10 filter attributes by clicking "Add Attribute" button
6. Review
Add `overflow: auto` style for `simple-modal__overlay` class.
Update styles of advances-search
=> GGRC-7530 A part of the pop-up is hiding if set more than nine filter attributes

src/ggrc/converters/base.py, src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/comments.py, test/integration/ggrc/notifications/test_assignable_notifications.py
*If comment is added while importing, it is not shown up in show_daily_digest. 
Actual result: the comments do not appear in daily digest.
Expected result: the comments are shown up in daily digest.*
*1.	Import Assessment with added comments and turned on Notification
2.	Open /_notifications/show_daily_digest*
*Create Notification object for the comments while importing in the src/ggrc/converters/handlers/comments.py filte*
=> GGRC-7018 Adds comment notifications while import process

src/ggrc-client/js/components/release-notes-list/release-notes.md
=> GGRC-7546 Update Whats new for 2.9.0

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/__init__.py, test/integration/ggrc/converters/test_import_mapping.py, test/integration/ggrc/converters/test_import_metrics.py
Incorrect message while importing scope object with mapped control
1. Log in ggrc app and open import page
2. Download import template with any scope object
3. Fill in required filed and add to map:control column any control's slug
4. Import scope object and look at the message after analysis
Actual Result: The system says that there is no permissions to map directives to scope in this application
Expected Result: "You do not have the necessary permissions to map scoping objects to controls in this application. Please contact your administrator if you have any questions. Column 'map:Control' will be ignored."
Modify following files to implement the solution.
src/ggrc/converters/errors.py
src/ggrc/converters/handlers/handlers.py
=> GGRC-6992/GGRC-7351/GGRC-7508 Fix incorrect message while importing scope object with mapped control/risk

src/ggrc/settings/default.py
Bump up version to 2.11.0-Pumpkin
=> QUICK-FIX Bump up version to 2.11.0-Pumpkin

test/integration/ggrc/models/test_log_json.py
We have not tests that check work of log_json method.
1 Open GGRC repository
2 See that we do not have tests for checking result of calling log_json method
Add tests that check work of log_json method.
=> GGRC-7439 log_json tests

src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js, src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js, src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js, src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js, src/ggrc-client/js_specs/spec_helpers.js
Fix warnings and errors in unit tests.
Run Karma
Open http://localhost:9876/debug.html
Check console in dev tool.
Fix `'can-component.prototype.template: is deprecated and will be removed in a future release. Use can-component.prototype.view'` warning - replace `template` on `view`.
Update tests to prevent errors in console.
=> QUICK-FIX Fix warnings/errors in unit tests

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/lib/service/proposal_rest_service.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/tests/test_proposals.py
=> GGRC-7557 Add tests checking program proposals creation

src/ggrc-client/js/models/business-models/person.js
E-mail and name should be saved during person creation in admin panel without spaces around name and e-mail should be in lower case.
1. Open Administration page People tab
2. Click Create button
3. Enter user name with spaces before and after
4. Enter email with uppercase letters
5. Click Save
Actual result: user name is saved with spaces and email with uppercase letters
Expected result: user name is saved without spaces and email is lowercased.
As it is impossible to fix issue on Back-end as it is done for the case of saving Programs with tittle rounding with spaces. Fix was added to modals controller in place near similar fix.
=> GGRC-7414 Add checks for name and email when create a user

src/ggrc-client/js/components/release-notes-list/release-notes.md
=> GGRC-7579 Update Whats New for 2.10.0

src/ggrc/migrations/utils/custom_attributes.py, src/ggrc/migrations/versions/20190729_e732f578fa85_add_payments_rma_review_cad_for_control.py
New GCA "Payments RMA Review" of "Date" type should be created for Control. Without it an internal QA process could not be implemented. And since it is not possible to create GCA for Control on UI anymore, it should be done with a migration.
1. Log in GGRC app;
2. Go to "Administration" page and look for "Payments RMA Review" CAD in "Controls" dropdown on "Custom Attributes" tab;
3. Open existing Control and check that "Payments RMA Review" CAD is present there.
Solution includes a migration which creates described CAD with help of `ggrc.migrations.utils.custom_attributes.create_custom_attribute` utility.
=> GGRC-7584 Create "Payments RMA Review" GCA for Control

src/ggrc/migrations/versions/20190726_91d3ba424a6b_clean_objects_without_revisions_table.py
Create missing revisions job failed during prod deployment.
Add broken data to the objects_without_revisions table and run the migration.
Add migration to clean broken data.
=> GGRC-7544 Add migration to clean broken missing revisions entry.

src/ggrc/models/exceptions.py, src/ggrc/utils/errors.py, src/ggrc/views/converters.py, test/integration/ggrc/services/resources/test_converters.py
PUT 400 while canceling Import
Login in to app.
Run import any file.
Press stop import:
if import job was already finished, there new handler will send to UI response:
"Import has already finished. Please refresh this page".
Added new test.
Added new handler for "Finished" state for import
=> GGRC-7441 Add handler for 'Finished' state of import/export job

src/ggrc-client/js/apps/workflows.js, src/ggrc-client/js/components/inner-nav/inner-nav-vm.js, src/ggrc-client/js/components/inner-nav/tests/inner-nav-vm_spec.js, src/ggrc-client/js/components/snapshotter/snapshot-scope-update.js, src/ggrc-client/js/components/snapshotter/tests/snapshot-scope-update_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/controllers/dashboard_controller.js, src/ggrc-client/js/controllers/dashboard_widgets_controller.js
`tree-widget-container` contains two method which should be improved: `display` and `reloadTree`.
Move tree items refetch logic to `tree-widget-container`.
Use common mechanism for refreshing tree view after updating snapshots (snapshot-scope-update component).
=> GGRC-6917 Refactor tree-widget-container

src/ggrc/views/__init__.py, test/integration/ggrc/proposal/api/test_cads.py, test/unit/ggrc/models/test_custom_attribute_definition.py
GCA title is not updated in revisions comparison window.
1. Create GCA of any type Program 
2. Create Program and fill GCA from step 1
3. Open admin page & edit title of GCA from step 1 
4. Create proposal for Program a GCA value 
5. Open 'Revisions Comparison' window 
When we modify CAD we also modify the revision in related objects.
=> GGRC-7387 Update GCA title in revision comparison window

src/ggrc-client/js/components/tree/tree-status-filter.js
Filter status isn't applied after reload page
1. Open any tree-view with status filter.
2. Set  **Active** state.
3. Tree-view displays only Active items.
4. Reload page (refresh page).
_Expected result_: State dropdown has **Active** state. Tree-view displays only **Active** items.
_Actual result_: State dropdown has **Active** state. Tree-view displays **ALL** items.
Filter should be set before loading of tree-view items.
`init` event is called before `inserted`.
=> QUICK-FIX Status filter

src/ggrc/notifications/notification_handlers.py
When several PUT requests are sent for one assessment at the same time, race condition or deadlocks might occur. In this case BE returns response with 500 status code. Bellow are examples of errors.
```
File "/base/data/home/apps/s~google.com:ggrc-test/1-21-0-strawberry-7ee93353806c.412196609848199916/ggrc/services/common.py", line 440, in dispatch_request
return self.put(*args, **kwargs)
File "/base/data/home/apps/s~google.com:ggrc-test/1-21-0-strawberry-7ee93353806c.412196609848199916/ggrc/utils/__init__.py", line 348, in inner
return function(*args, **kwargs)
File "/base/data/home/apps/s~google.com:ggrc-test/1-21-0-strawberry-7ee93353806c.412196609848199916/ggrc/services/common.py", line 609, in put
modified_objects = get_modified_objects(db.session) …
```
=> GGRC-5963 Prevent DB deadlocks and race conditions when sending notifications on assessment update

src/ggrc/services/common.py, test/integration/ggrc/access_control/acl_propagation/test_audit_captains.py, test/integration/ggrc/access_control/acl_propagation/test_auditors.py, test/integration/ggrc/access_control/rbac_factories/snapshot.py
Incorrect entries for object snapshots are shown in Audit / Assessment Change Log for GC user. Global Creator user sees **"Mapping to Snapshot: undefined"**. The same row as for admin user should be shown (no **undefined** should be present).
1. Login as admin;
2. Create audit with global creator as Audit Captain or Auditor;
3. Map an object snapshot to it;
4. Login as global creator;
5. Open Change Log tab;
6. Look at record describing created mapping between object Snapshot and Audit / Assessment.
Expected result: Global Creator should see the correct row - same as admin (no **undefined** should be present).
Solution includes additional check for read permissions on snapshots a revision is attached to when checking read access to the revision.
All logic regarding revision read access …
=> GGRC-5329 Incorrect entries for snapshots are shown in audit / asmt Change Log for GC

src/ggrc/login/__init__.py
After db_reset procedure with the new dump.sql file on the existing database, user will find that he was logged in via user from the new database, but with the same ID
One scenario to reproduce locally:
1. Have a db with some user, e.g. test@example.com. 
2. Log in in the app with this user email
3. Stop the app
4. Import some dump that doesn't contain user test@example.com. 
5. Run the app
1. Check g-appengine user is the same as flask user
2. If not then user_loader method returns None
=> GGRC-6367 Fixes auth user after db_reset with another user

._license_header_exceptions, docs/source/contributing/git/branch_management.rst, docs/source/contributing/git/creating_pull_requests.rst, docs/source/contributing/git/how_to_write_a_commit_message.rst, docs/source/contributing/git/index.rst, docs/source/frontend/modals.rst, docs/source/frontend/overview.rst, docs/source/support/deployment_and_update.rst
=> GGRC-7519 Update git guideline

src/ggrc/migrations/versions/20190716_a6b61113e372_remove_proposal_data_related_to_control.py, src/ggrc/models/control.py
Need code improvement and Proposalable mixin should be removed from control model and clean-up/deprecate proposal data in db.
Check DB for the Control objects related to Proposal model
- I removed Proposalable mixin from the Control model
- Added migration which removes all the proposals related to controls
=> GGRC-7081 Removes proposal mixim from the control model

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/handlers.py, test/integration/ggrc/converters/test_import_metrics.py
Warning is not displayed if deprecate/delete object from Scope via import
The preliminary text for the warning is the following:
Line X: In case there are any compliance/on-boarding Questionnaires related to <object type> <object title> in <GGRCQ link> they will be deprecated too. Please click 'Proceed' to confirm <deprecation/deletion>
1. Create Metric object on UI in Draft state
2. Export the created Metric to Google Sheet
3. Change state from Draft to Deprecated
4. Choose file to Import and confirm import
Added if statement for Metric instances with status from the import-file equals "Deprecated"
=> GGRC-5841 Adds metric import warning msg status deprecated

test/integration/ggrc_workflows/notifications/test_cycle_start_failed_notifications.py, test/integration/ggrc_workflows/notifications/test_monthly_wf.py, test/integration/ggrc_workflows/notifications/test_one_time_wf.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_decline_accept_tasks.py, test/integration/ggrc_workflows/notifications/test_one_time_wf_end_date_change.py, test/integration/ggrc_workflows/notifications/test_task_due_notifications.py, test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py, test/integration/ggrc_workflows/notifications/test_workflow_comment_notifications.py
Secondary task assignee notifications not covered with integration tests.
Run the tests.
Check cases when secondary assignee receives task notifications in `ggrc_workflow/notifications`.
=> GGRC-4349 Cover secondary task assignee notifications with tests

src/ggrc/converters/handlers/custom_attribute.py
The system doesn't show error on the analysis stage if import Assessment in completed state with unfilled LCA
2. Create Assessment Template with required local CA (any type)
3. Download Assessment csv template
4. Fill out the following fields: Template, Audit, Creator, Assignee, mandatory GCAs if any, state of Assessment 'In Review' > Save
5. Import Assessment csv template
Expected Result: The system should show an error message that mandatory field is empty on the analysis stage
Added additional step to collect CustomAttribute for analyses process.
=> GGRC-6261 The system doesn't show error on the analysis stage

src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, test/integration/ggrc/integrations/test_issue_integration.py
Issue assignee in Issue Tracker is not taken in alphabetical order
1. Create an issue with Primary Contacts  (three at least), issue tracker should be ON:
hotlist id: 700706
component ID: 64445
2. Open Ticket and look at the Assignee in Issue Tracker
Created integration test
Changed order key for sorting function
=> GGRC-7232 Issue assignee in Issue Tracker is not taken in alphabetical order

src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Simple-modal height is broken after updating Chrome to the latest version
Open Related Assessments popup in Control
Remove unneeded `height` style from `mapped-controls-info` and `related-assessments` classes.
Add `flex: 1` style for `related-assessments` class
=> GGRC-7645 Control popup is broken for the user with Chrome v.76

src/ggrc/converters/errors.py, src/ggrc/converters/import_helper.py, test/integration/ggrc/converters/test_import_snapshot.py, test/unit/ggrc/converters/test_import_helpers.py
Add proper warning message while importing snapshot object
*Import for Snapshot object is not available in GGRC.*
1. Create a program, control, audit
2. Go to Export page
3. Select Snapshots from dropdown "Export Object Type"
4. Select Snapshot object type - control and select mapped to the audit, audit title> Export
5. Make changes in the csv file and import
Actual Result: non-informative warning message is shown while importing snapshot. The system should not allow importing snapshot
Expected Result: Make a proper warning if import snapshot
*Added an extra check to handle a snapshot import issue in import_helper.py file and also added unit test case for them.*
=> GGRC-1996 Make a proper warning if import snapshot

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_export_assessment_templates.py
Reopen. 
Need to remove Other Contacts option from hint: _For all Assessment Types except of Control and Risk options for the both Default Assignee and Default Verifiers columns_ 
which were added via previous fix in [GGRC-5365](https://github.com/google/ggrc-core/pull/9799)
This task is a blocker for [GGRC-7268](https://gojira.corp.google.com/browse/GGRC-7268)
1. Download assessment template import template
2. Check the hint for Default Assignees*/Default Verifiers
Removed "Other Contacts" field from the _DEFAULT_PEOPLE_LABELS_ACTUAL
=> GGRC-5365 remove other contacts from hint

test/integration/external_app/external_api_helper.py, test/integration/external_app/test_ext_cad.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/models/test_control.py, test/integration/ggrc/services/test_custom_attributes.py
Test cases:
Create eCAD
Get eCAD
Update eCAD
Delete eCAD
=> GGRC-7580 Integration tests for external CAD

src/ggrc-client/js/controllers/dashboard_controller.js, src/ggrc-client/js/models/business-models/access-group.js, src/ggrc-client/js/models/mixins/mixin.js, src/ggrc-client/js/models/mixins/tests/access-control-list_spec.js, src/ggrc-client/js/models/mixins/tests/assessment-issue-tracker_spec.js, src/ggrc-client/js/models/mixins/tests/auto-status-changeable_spec.js, src/ggrc-client/js/models/mixins/tests/is-overdue_spec.js, src/ggrc-client/js/models/mixins/tests/issue-tracker_spec.js, src/ggrc-client/js/models/mixins/tests/mega-object_spec.js, src/ggrc-client/js/models/mixins/tests/related-assessments-loader_spec.js, src/ggrc-client/js/models/tests/save_queue_spec.js
Fix function and mixin names and remove redundant comments
=> QUICK-FIX Fix function and mixin names and remove redundant comments

src/ggrc/converters/handlers/issue_tracker.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/converters/test_import_issuetracked_objects.py
If import empty Issue Tracker fields, warnings are displayed on Import page  
1. Download Issue / Assessment to Google Sheet
2. Fill out required fields and leave Integration Enabled, Hotlist ID, Component ID, Priority, Severity, Issue title, Issue Type EMPTY
3. Import Google sheet
1. Added if-statement for the blank IssueTracker Fields to `parse_item` method
2. if field is blank then do force-return
=> GGRC-6411 warnings import empty issue tracker fields

src/ggrc/migrations/versions/20190806_307953997c8b_modify_default_recipients_in_document.py
Remove duplication in migration chain
=> QUICK-FIX Update migration chain

src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, src/ggrc/services/common.py, src/ggrc/views/__init__.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/integration/ggrc/integrations/test_issue_integration.py
Issue tracker API was changed. To be able to link an assessment and an issue to the existing ticket we weed to modify UI + change params extraction logic.   
Custom version was deployed.
Run integration tests.
UI changed.
component_id and hotlist_id are extracted form the integration service response.
=> GGRC-7541 Changes for issue tracker  integration.

src/ggrc/access_control/role.py, test/unit/ggrc/models/test_access_control_roles.py
If add custom role field with title "title", two columns of title are shown in tree view
1. Go to administration> Custom roles tab
2. Add Custom role for Controls with title "title" and save - try different cases "TitTle" or "TITLE" or "tiTLE"
Actual Result: The role is created (having the name clash between an attribute and a role, we have weird things going with our tree view and imports/exports)
Expected Result: The role should be not created.
Modify incoming name to lowercase for validation step (only).
=> GGRC-2360 Improve role name validation for words in different cases

src/ggrc/integrations/issuetracker_bulk_sync.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/views/__init__.py, test/integration/ggrc/integrations/test_assessment_integration.py
When we disable Audit IssueTracker then we should send comments to all related Assessments BUGs that tracking for them is also disabled
1. Create an Audit with with Issue Tracker turned ON:
Component ID = 64445
Hotlist ID = 700706
2. Create an Assessment with Issue Tracker turned ON:
Component ID = 64445
Hotlist ID = 700706
3. Open BUG in Issue Tracker
4. Turn OFF Issue Tracker for Audit
5. Look at the BUG once again
Actual Result: There is no message that "Changes to thisGGRC  object will no longer be tracked within this bug."
Expected Result: "Changes to this GGRC object will no longer be tracked within this bug." message should be displayed
Create background task that will send comments to all issues related to child assessments
=> GGRC-6401 No comment in BUG if Integration was turned OFF on Audit

src/ggrc-client/js/controllers/tree/tree-view.js, src/ggrc-client/js/models/custom-attributes/external-custom-attribute-definition.js
Need to use external_custom_attribute_definition instead of custom_attribute_definition endpoint for external objects (Control, Risk).
Open Admin page.
Check that Custom Attributes tab is working correctly and gcas for some particular type is showing as expected (RISK and CONTROL are using external endpoint).
=> GGRC-7674 Change CADs requests from UI for external CADs

test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/page/widget/admin_widget.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/page/widget/widget_base.py, test/selenium/src/lib/service/admin_webui_service.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_admin_dashboard_page.py
Add test to check that custom attributes can be edited and changes are saved after it.
=> GGRC-7619 Check that custom attributes can be edited

src/ggrc/models/hooks/issue_tracker/assessment_integration.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/unit/ggrc/models/hooks/issue_tracker_integration/test_assessment_integration.py
maximb-with-import-1 instance was deployed
1. link assessment to existing ticket. 
2. create another ticket
3. try to relink assessment to new ticket. check if it's ok.
=> GGRC-7541 Update issue tracker generic fields validation

src/ggrc-client/js/components/add-issue-button/add-issue-button.js, src/ggrc-client/js/components/add-issue-button/add-issue-button.stache
Client side sends unneeded request to refresh related issues after update assessment via edit modal
1. Open any assessment 
2. Click "Edit Assessment" button 
3. Change some field (for example: title) 
4. Click "Save" 
**Actual Result**: Client side sends request to refresh related issues
**Expected result**: Client side doesn't send request to refresh related issues
Listen to events (modal:added, modal:success) on the button, not globally.
=> GGRC-7094 Client side sends unneeded request to refresh related issues after update assessment via edit modal

src/ggrc/integrations/synchronization_jobs/issue_sync_job.py, test/integration/ggrc/integrations/test_issue_sync_job.py
Bug in status 'Assigned' should be synced to Issue status 'Active'
1. Open instance with enabled ISSUE_TRACKER_ENABLED flag (ex. ggrc-test or ggrc-uat)
2. Create issue and map bug ticket
3. Change bug ticket status from NEW to Assigned (Assign to yourself)
1. Changed ISSUE_STATUS_MAPPING["assigned"] value from Draft to Active
2. Fixed issue sync cron job test
=> GGRC-7571 Bug assigned status sync to issue status active

src/ggrc/settings/default.py
=> QUICK-FIX Bump up version to 2.14.0-Pumpkin

src/ggrc/utils/revisions_diff/builder.py, test/unit/ggrc/utils/test_revisions_diff.py
Update checkbox CAD validation
Run unit tests
=> QUICK-FIX Update checkbox CAD validation

src/ggrc/settings/default.py
Bump up version to 2.15.0-Pumpkin
=> QUICK-FIX Bump up version to 2.15.0-Pumpkin

src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/acl.py, src/ggrc/converters/pre_commit_checks.py, test/integration/ggrc/converters/test_import_assessments.py
There are duplicated warming message, when we import Assessment with change status and remove verifies.
1. Create assessment with verifier
2. Click 'Complete' button (assessment status is changed to In Review)
3. Export assessment
4. Remove Verifier - > set  '--' value in a file
5. Import assessment
Added special flag to Import Row Converter, which check status change. And when status will be set to 'In Progress' flag set to active statement. And this flag checked, when checked verifies.
=> GGRC-7470 Remove duplicated warning message

src/ggrc-client/js/components/modal-autocomplete/utils.js
Email is incorrectly displayed in the Assignee field at Task group modal without HR integration.
1. Log in GGRC app without HR integration.
2. Open any Workflow page
3. Open Setup Tab
4. Click Create button
5. Set Title and any user with Gmail account as Assignee 
e.g Title - "Test" task and Assignee - "7659005@gmail.com" (need to click on email in the appeared dropdown)
6. Remove from the Assignee field "@gmail.com"
7. Select again the same assignee in the appeared dropdown
**Actual result:** Email is not displayed in the Assignee field, user name is displayed instead
**Expected result:** Email should be displayed in the Assignee field
=> GGRC-7545  Fix autocomplete email for task group

test/selenium/conftest.py, test/selenium/src/lib/element/tab_element.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/lib/page/widget/related_proposals.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/ui/ui_facade.py, test/selenium/src/tests/test_controls.py, test/selenium/src/tests/test_create_object.py, test/selenium/src/tests/test_my_work_page.py, test/selenium/src/tests/test_unified_mapper.py
Confirm user can not make Proposal for Control
=> GGRC-7556 Confirm can not make Proposal for Control

test/selenium/conftest.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/element/info_widget_three_bbs.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/service/rest/template/standard.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_asmts_workflow.py, test/selenium/src/tests/test_controls.py
Check that user cannot unmap Control from Directive
=> GGRC-7623 Check that Control cannot be unmapped from Directive

test/integration/ggrc_workflows/converters/test_import_task_group.py
Rework test_import_task_group.py
we have some troubles with below tests in this file test_import_task_group.py. 
Test_start_end_dates_error
Test_task_group_task_weekend
Modify below file to fix test case failures
test/integration/ggrc_workflows/converters/test_import_task_group.py
=> GGRC-7575 Rework test_import_task_group.py

test/integration/ggrc_workflows/converters/test_import_workflow_people.py
Rework test_import_workflow_people.py
We face next issues with this file:
1. We create workflow using import with custom slug. We should rework test setUp
2. We should provide import_workflow (and task group if needed) method appropriate slug that was created on a setUp stage for update via import. 
3. We should update our tests according to this functionality. 
Modify below file to fix test case failures
test/integration/ggrc_workflows/converters/test_import_workflow_people.py
=> GGRC-7566 Rework test_import_workflow_people.py

src/ggrc-client/js/components/revision-log/revision-page.js
Assertions field is blank on Control in Change Log.
1. Open Control info page.
2. Click Change Log tab.
3. Verify that Assertions field is not blank and corresponds to value on Control Attributes tab. 
The issue is invalid data format to view Assertions data.
1. Updated data format from list of objects to list of strings.
=> GGRC-7599 Fix bug when Assertions field is blank on Control change log

src/ggrc/utils/date_parsers.py, test/integration/ggrc/services/test_query/test_basic.py
Filter for dates is not applied in 'mm-dd-yyyy', 'mm-yyyy' formats.
1. Log in ggrc app
2. Create any object, e.g. Obejective
3. Open My Work page > Objectives tab
4. Set 'LAST UPDATED DATE' column in tree view and sort by 'LAST UPDATED DATE' = mm-dd-yyyy or 'LAST UPDATED DATE' = mm-yyyy
Was updated regular expression for US date standard. Was updated tests for incorrect date format.
=> GGRC-7162 Update filter for dates to work with 'mm-dd-yyyy', 'mm-yyyy' formats

test/integration/external_app/test_ext_control.py, test/integration/external_app/test_ext_risk.py, test/integration/ggrc/__init__.py, test/integration/ggrc/models/test_assessment_file_url_and_status_put.py, test/integration/ggrc/models/test_control.py, test/integration/ggrc/models/test_risk.py, test/integration/ggrc/utils/helpers.py
*Currently integration tests for Risks and Controls uses api.login_as_external() to simulate requests from external application. This mechanism is not reflects real life requests. We have created ExternalApiClient to simulate requests properly. We need to refactor old tests to use new api client.*
*Start test_control.py and test_risk.py modules in test/integration/ggrc/models/ and test_ext_risk.py and test_ext_control.py modules in /test/integration/external_app/*
*Rewrite tests for risks and controls and move external app tests to external_app package*
=> GGRC-7524 Update integration tests for risks to use ext_api_client

src/ggrc-client/js/controllers/modals/modals_controller.js
Chrome popup is displayed while saving any Object.
1. Log in ggrc app.
2. Open New program popup, fill out required fields and click Save&Close button.
3. Verify that popup is not shown.
The save instance isn't resolved for Program and Issue models using jQuery `done`. Audit and Workflow models has own implementation of save instance that allows resolving.
1. Changed `done `to `then`.
=> GGRC-7644 Fix bug when Chrome popup is displayed while saving any Object

test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
After review target branch should be changed to #9818.
setUp method allows import of custom code. 
Run the test cases in the file 'test/integration/ggrc_workflows/converters/test_workflow_export_csv.py'. All the test cases should pass.
* Removed the existing 'export_csv' method
* Usage of 'import_file' method is removed
=> GGRC-7563 Refactor test_workflow_export_csv.py

src/ggrc/settings/default.py
Bump up version to 2.16.0-Pumpkin
=>  QUICK-FIX Bump up version to 2.16.0-Pumpkin

test/selenium/src/lib/base.py, test/selenium/src/lib/page/export_page.py, test/selenium/src/lib/page/login_page.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_audit_page.py
Add test to check that Login page is displayed in Dashboard widget if GCA filled with appropriate url.
=> GGRC-7613 Check login page is displayed on dashboard gca

src/ggrc/templates/notifications/email_digest_content.html, src/ggrc/templates/notifications/style.html
Email layout is broken due to previuos changes and do not match with the attached design
Previous PR [GGRC-6766](https://github.com/google/ggrc-core/pull/9664)
1. Log in ggrc app and open any audit page
2. Create assessment (fill description and any custom attribute)
3. Export assessment to google sheet
4. Update description and custom attribute
5. Import assessment
6. Once daily digest is received, look at the email message
1. Added styles for the assessment_updated th and td tags
=> GGRC-6766 Broken email layout assessment updates table

src/ggrc/models/assessment.py, test/integration/ggrc/converters/test_export_csv.py
Conclusion:Design and Conclusion:Operation columns of Assessment doesn't have tip message in csv template.
3.Select the Object Type (Assessment) and export the csv file.
Open the excel and check for the Role column , here you can see the tip message
Effective
Ineffective
Needs improvement 
Not Applicable"
Updated design and operationally attributes in _aliases in ggrc/models/assessment.py
=> GGRC-3665 Add tip for Conclusion:Design and Operation

src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache, src/ggrc-client/js/components/object-generator/object-generator.stache, src/ggrc-client/js/components/object-mapper/object-mapper.stache, src/ggrc-client/js/components/object-search/object-search.js, src/ggrc-client/js/components/object-search/object-search.stache, src/ggrc-client/js/helpers.js
No Reset for search Results for saved search.
1. Login GGRC app and open Global Search 
2. Select any object type, set filter query, search results and save the first filter
3. Select one more object type, set filter query, search results and save the second filter
4. Click on the first filter and look at the Search Results count 
**Actual Result:** Count of the previous search result is shown
**Expected Result:** Do not show Search Results count for saved filter until user clicks on Search button
Unify counter for all search modals.
=> GGRC-7534  Fix search results counter

src/ggrc/models/person.py, test/integration/ggrc/converters/test_export_csv.py
Role column for the People object doesn't have in csv template
3.Select the Object Type ( people) and export the csv file.
Open the excel and check for the Role column , here you can see the tip message
No access
Creator
Reader
Editor
Administrator"
Added a varibale *ROLE_OPTIONS*  and updated the description for user_role  attribute in \_aliases in ggrc/models/person.py
=> GGRC-3672 Add tip message for Role

src/ggrc-client/js/templates/issues/info.stache
Due Date is not marked with a start on Issue panel/info.
1.  Open any Issue panel/info.
2. Verify that Due Date label is marked with a start. 
Start icon was missed for Due Date field. 
1. Added start icon.
=> GGRC-7381 Fix bug when Due Date is not marked with a start on Issue panel

test/selenium/conftest.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/modal/snapshoted_controls_info.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/rest/template/regulation.json, test/selenium/src/lib/service/rest/template/requirement.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_snapshots.py
Check that related Requirement / Regulations are shown at Control snapshot modal opened from Assessment Info panel
=> GGRC-7606 Check objects related to control snapshot are shown

src/ggrc/models/product.py, test/integration/ggrc/converters/test_export_csv.py
Kind/Type column doesn't have tip in csv template
3.Select the Object Type ( Products) and export the csv file.
Open the excel and check for the Role column , here you can see the tip message
Appliance
Saas
Desktop Software
"
Added a variable *TYPE_OPTIONS* and updated the updated the description for kind attribute in \_aliases in ggrc/models/product.py
=> GGRC-3673 add tip for Kind/Type

src/ggrc/settings/default.py
BUMP UP 2.17.0-Pumpkin version
=> BUMP UP 2.17.0-Pumpkin version

src/ggrc/migrations/utils/external_cads.py, src/ggrc/migrations/utils/external_cavs.py
QUICK-FIX add revisions during CAD/CAV migration
=> QUICK-FIX add revisions during CAD/CAV migration

src/ggrc/settings/default.py
BUMP UP 2.18.0-Pumpkin version
=> BUMP UP 2.18.0-Pumpkin version

test/integration/ggrc/converters/test_import_commentable.py
Refactor test_import_commentable.py
* The test cases in 'test/integration/ggrc/converters/test_import_commentable.py' should not allow custom slugs and pass without any errors.
* The test cases are modified such that the required objects are created with empty code.
=> GGRC-7650 Refactor test_import_commentable.py

test/selenium/conftest.py, test/selenium/src/lib/page/dashboard.py, test/selenium/src/lib/page/widget/controls_tab.py, test/selenium/src/lib/page/widget_bar.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_controls.py, test/selenium/src/tests/test_my_work_page.py, test/selenium/src/tests/test_snapshots.py
Check that user can export Control
=> GGRC-7513 Confirm user can export Control

src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js, src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.stache, src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.stache, src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-button/assessments-bulk-complete-button.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-button/assessments-bulk-complete-button.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache, src/ggrc-client/js/components/object-selection/object-selection.js, src/ggrc-client/js/components/tree/templates/tree-actions.stache, src/ggrc-client/js/components/tree/templates/tree-widget-container.stache, src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/js/controllers/mapper/assessments-bulk-complete-modal.stache, src/ggrc-client/js/controllers/mapper/mapper.js, src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js, src/ggrc-client/js/plugins/utils/advanced-search-utils.js, src/ggrc-client/js/plugins/utils/state-utils.js, src/ggrc-client/js/templates/assessments/tree_add_item.stache, src/ggrc-client/styles/_placeholders.scss, src/ggrc-client/styles/_typography.scss, src/ggrc-client/styles/components/advanced-search/_advanced-search.scss, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss, src/ggrc-client/styles/modules/_modal.scss
Precondition: you should have 1 <= assessments which should pass next rules:
- you must have "update" rights on these assessments (just create assessments and you'll immediately get "update" rights on the created assessment).
- assessments should not be Archived, 
- possible assessments statuses are 'In Progress' / 'Rework Needed' / 'Not Started'.
Open My Assessments or Audit -> Assessments tab and click Bulk Complete button (on Audit page, it's a menu item of 3 dots menu).
What was done and should be tested.
1) By clicking on "Bulk complete" buttons, modal "Bulk complete" should be shown. 
2) Modal should have 3 sections as shown on the screenshot:
3) "Select assessments" should be expanded by default after opening of the modal and default filter should be appllied - on Audit page, …
=> GGRC-7705/GGRC-7706/GGRC-7707 Create framework for Bulk complete modal

src/ggrc_workflows/models/workflow.py, test/integration/ggrc/converters/test_export_csv.py
Workflow's columns doesn't have tip message in csv template.
1. Force real-time email updates.
2. Need Verification.
3.Select the Object Type and export the csv file.
4.Open the excel.
5.check for the  Force real-time email updates column , here you can see the tip message
Yes
No"
6.check for the  Need Verfication column , here you can see the tip message
TRUE
FALSE"
updated \_aliases in file src/ggrc_workflows/models/workflow.py as per requirement.
=> GGRC-3677 Add tip message for Workflow's attributes

test/integration/ggrc/converters/test_export_csv.py
QUICK-FIX rename import tips test names
=> QUICK-FIX rename import tips test names

src/ggrc/models/assessment.py
Conclusion:Design and Conclusion:Operation columns of Assessment doesn't have tip message ordered  in csv template.
3.Select the Object Type (Assessment) and export the csv file.
Open the excel and check for the Role column , here you can see the tip message
Effective
Ineffective
Needs improvement
Not Applicable"
Updated the *VALID_CONCLUSIONS* in ggrc/models/assessment.py
=> GGRC-3665 fixed Conclusion tip order

src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
Simple-modal height is broken after updating Chrome to v77.
1. Log in ggrc app.
2. Expand Assessment info pane.
3. Set any LCA set as mandatory field with Comment required e.g "new dropdown" LCA.
4. Verify that modal is shown without any issue. 
For simple-modal style set `flex-basis` to `auto` instead of default value `0%`.
=> GGRC-7793 LCA popup is broken for the user with Chrome v.77

test/integration/ggrc/object_owner/test_comment.py
Rework test_comment.py
Execute test/integration/ggrc/object_owner/test_comment.py and make sure the tests pass without allowing usage of custom slugs
1) import_file usage and csv file usage has been removed, import_data is used instead
2) Previously 12 Assessments are used in csv file. Modified test case has reduced number of assessments getting imported.. Avoided import of assessments that have redundant combination of attributes.
3) Created _get_assessment_import_data method to return data_block containing those 6 assessments
4) Implemented functionality to import/create program, audit and persons during setUp
=> GGRC-7634 Rework test_comment.py

test/integration/ggrc/utils/test_user_generator.py
Rework test_user_generator.py
we have some troubles with tests in this file. 
Test_verifier_import
Test_person_import
Modify the below file to fix failing tests
test/integration/ggrc/utils/test_user_generator.py
=> GGRC-7600 Rework test_user_generator.py

test/integration/ggrc/integrations/test_assessment_integration.py
Rework test_assessment_integration.py
Execute test/integration/ggrc/integrations/test_assessment_integration.py and make sure the tests pass without allowing usage of custom slugs
Remove custom slug from import_data in test_basic_import
=> GGRC-7647 Rework test_assessment_integration.py

test/integration/ggrc/utils/test_user_generator.py
We've missed freezegun in one test and it can lead to unpredictable and unexpected integration tests failure if this test would run more than one second. 
run integration tests. 
I've added time freeze. Later we would refactor tests and remove asserts for person profile out of all these tests and create separate tests for profile.
=> QUICK-FIX Add freezegun to person profile asserts.

src/ggrc/migrations/versions/20190815_ac75e70c9081_delete_unrelated_comments.py, src/ggrc/models/hooks/comment.py, test/integration/ggrc/converters/test_export_assessments.py, test/integration/ggrc/models/mixins/test_commentable.py
Comments are not deleted when a parent object is deleted
Previous closed PR [GGRC-5307](https://github.com/google/ggrc-core/pull/8102)
1. Create an object (e.g. program)
2. Add a comment
3. Delete an object
1. Add a delete-hook on Relatable and Commentable objects to delete related comments
2. Add a migration to delete comments without any relationship and create a revision for them
=> GGRC-5307 Delete comments from deleted objects

test/integration/ggrc/converters/test_import_special_objects.py
Refactor test_import_special_objects.py
Run the below command to check whether the test case is passing:
Refactored the test case using OrderedDict to create new people, programs and audits in order to avoid the csv import data.
=> GGRC-7649 Refactor test_import_special_objects.py

src/ggrc/models/relationship.py, test/integration/ggrc/models/test_relationship.py
GGRC user can not delete Standard / Regulation if it is mapped to scope object, the message "You do not have the necessary permissions to map and unmap scoping objects to directives in this application. Please contact your administrator if you have any questions." is displayed. 
GGRC user should be able to delete Standard / Regulation if they are mapped to scope object and vise versa. Upon deletion of an object, mapping should be deleted as well.
**NOTE**: In addition to expected behavior above, GGRC user have to be able to delete Scope / Standard / Regulation objects which are mapped to Control.
1. Log in to GGRC and find any scope object (e.g. Product) with mapped Standard / Regulation;
2. Open scope object page in GGRC app and delete Standard / Regulation;
Expected result: Standard / …
=> GGRC-6107 Don't validate source and destination types when deleting orphan relationship

src/ggrc-client/js/components/person-modal/person-modal.js
Name input is disabled after update of selected email
1. Go to Administration page
2. Click on People tab
3. Click Create button
4. Input any valid email and select it from the autosuggestion list
5. Hover over the Name field and check that it is disabled for editing
6. Edit email manually till @google.com part
7. Hover over the Name field
_Actual_: the Name field is disabled. It becomes editable only when at least one symbol is being edited in @google.com part.
_Expected_: If an email (from suggested list) is edited, then the Name field should be enabled. This is applicable only for @google.com emails.
Set `isNameReadOnly` to **false** when email was changed
=> GGRC-7681 'Name' is disabled when 'Email' ldap was edited at Administration

src/ggrc/models/saved_search.py, test/integration/ggrc/views/saved_searches/test_saved_search_post.py
Search filters should be saved for Workflows, Tasks Groups and Task Group Tasks
1. Log in in the GGRC app
3. Select Workflows or Tasks object type
4. Input any title in the Save search field e.g "test 12345"
5. Click Save Search button
1. Created _EXTENSION_SUPPORTED_OBJECT_TYPES for the models which are not presented in CONTRIBUTED_OBJECTS list
2. Added _get_supported_object_types func for generation SUPPORTED_OBJECT_TYPES 
3. Added tests for non contributed object types
=> GGRC-7636 Save search for workflows and tasks

src/ggrc/settings/default.py
=> BUMP UP 2.19.0-Pumpkin

test/integration/ggrc/notifications/test_comment_notifications.py
Refactor test_comment_notifications.py file.
* The test cases in 'test/integration/ggrc/notifications/test_comment_notifications.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7819 Refactor test_comment_notifications.py

src/ggrc-client/js/components/custom-attributes/custom-attributes.stache, src/ggrc-client/js/components/form/form-validation-icon.js, src/ggrc-client/js/components/object-popover/related-assessment-popover.stache
Mandatory GCA is marked with asterisk in Assessments info popup, when there value is None.
1. Log into GGRC as Admin.
2. Go to 'Administration' page and create one or more mandatory CA for assessments.
3. Create an Audit.
4. Open the audit with a snapshot and generate two Assessments.
5. On Assessment info panel click on Related Assessments tab
6.  Click on 'i' icon and look at the mandatory CA
7. If mandatory GCA is not filled, asterisk should be displayed
* In related assessments info popup, the mandatory custom attributes, having None values, are marked with asterisk mark and those having values are marked as valid.
* Function 'iconCls' in 'src/ggrc-client/js/components/form/form-validation-icon.js' is modified.
=> GGRC-7281 Mark mandatory GCA with asterisk 

src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js, src/ggrc-client/js/components/saved-search/create-saved-search/tests/create-saved-search_spec.js, src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js, src/ggrc-client/js/components/saved-search/saved-search-list/tests/saved-search-list_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js
Added unit tests for Saved searches
=> GGRC-7373  Add unit tests for Saved Searches

src/ggrc/notifications/notification_handlers.py
"Import failed due to unknown error." is displayed while importing asmt
2. Use spreadsheet from the ticket and import Asmt
In some notification object from db.session we do not have access to notification_type related object, but we have notification_type_id value. We can get any of them and we do not need to have additional query to db.
=> GGRC-7609 "Import failed due to unknown error." is displayed while importing asmt

src/ggrc-client/js/components/autocomplete/autocomplete-component.js, src/ggrc-client/js/components/autocomplete/autocomplete-component.stache, src/ggrc-client/js/components/import-export/download-template/download-template.js, src/ggrc-client/js/components/import-export/download-template/download-template.stache, src/ggrc-client/js/components/import-export/download-template/download-template_spec.js, src/ggrc-client/js/templates/base_objects/autocomplete_result.stache, src/ggrc-client/styles/components/autocomplete/_autocomplete.scss, src/ggrc-client/styles/modules/_import-export.scss, src/ggrc/converters/base.py, src/ggrc/converters/base_block.py, src/ggrc/converters/import_helper.py, src/ggrc/models/mixins/customattributable.py, src/ggrc/models/reflection.py, src/ggrc/utils/objects_cache.py, src/ggrc/views/converters.py, test/integration/ggrc/converters/test_assessment_csv_template.py, test/integration/ggrc/converters/test_export_assessments.py, test/integration/ggrc/converters/test_import_assessments.py
Downloading Assessment template csv. file took more then 30 sec.
- Open Import page
- Click on 'Download Import Template' > Select 'Assessment' object type from the list
- Click on 'Download CSV'
Actual behavior: Import Assessment csv template downloaded during ~ 27 sec
Expected behavior: Improve performance for downloading csv import template with choosing at Import page (step 2) an import template with only LCA that refer to a concrete Assessment template.
Add additional input field with autocomplete to select specific assessment template. Send list of required templates to the server.
=> GGRC-5880/GGRC-7116/Latency while downloading Assessment csv import template

test/integration/ggrc/converters/test_import_delete.py, test/integration/ggrc/test_csvs/ca_deletion.csv, test/integration/ggrc/test_csvs/ca_setup_for_deletion.csv
Refactor test_import_delete.py file.
* The test cases in 'test/integration/ggrc/converters/test_import_delete.py' should not allow custom slugs and pass with out any errors.
* Removed the file 'test/integration/ggrc/test_csvs/test/integration/ggrc/test_csvs/ca_setup_for_deletion.csv'.
* Removed the file 'test/integration/ggrc/test_csvs/ca_deletion.csv'
=> GGRC-7640 Refactor test_import_delete.py

src/ggrc-client/js/components/release-notes-list/release-notes.md
=> Update Whats New for 2.17.0

src/ggrc-client/styles/layout/_content.scss, src/ggrc-client/styles/modules/_dashboard-widget.scss
Scroll doesn't work properly on Info page.
Case 1:
1. Open any Info page, e.g. Program.
2. Try to scroll Info page.
3. Verify that there is no double scroll. 
Case 2:
1. Open Administration.
2. Verify that there is no double scroll. 
Because of setting `height:100%` for content block, double scroll was shown on the page that didn't allow to scroll page properly. 
1. Removed style for content block.
=> GGRC-7768 Fix bug when scroll doesn't work properly on Info page

src/ggrc/notifications/notification_handlers.py, test/integration/ggrc/notifications/test_assessment_notification_errors.py
Update Assessment via import could lead to 500 internal service error.
Update assessment via import using provided template.
Problem was in exception during sending of notifications. We decided handle those exceptions, log them and not break import procedure.
=> GGRC-7745 Import updates to Assessments

src/ggrc-client/js/components/release-notes-list/release-notes.md
=> Update Whats New for 2.17.0 in release

src/ggrc/models/person.py, test/integration/ggrc/services/test_authorizations.py
Search/ Advanced search is not applied for users authorization
1. Open Global Search > Object type: People
2. Add attribute > Authorizations
3. Filter by any role, e.g. 'Superuser'
4. Look at the search results: 'no people were found' while 'superuser' role exists
5. Open any program page > Peoples tab
6. Type search query into search box, e.g. 'authorizations ~ role' and Search: no results
Actual Result: Search/ Advanced search is not applied for users authorization
Expected Result: Search/ Advanced search should be applied for users authorization
Update alias to match QueryAPI request from FE
=> GGRC-3527 Search/ Advanced search is not applied for users authorization

test/integration/ggrc/converters/test_import_assessment_templates.py
We have some troubles with tests in this file:
- test_valid_import
- test_modify_over_import
- test_modify_persons_over_import
Connect to the container-
Run the command to execute the nose tests: nosetests -sv integration.ggrc.converters.test_import_assessment_templates
Refactored the test cases using the OrderedDict methods instead of importing data from the csv file.
=> GGRC-7668 Refactor test_import_assessment_templates.py

src/ggrc/integrations/client.py, src/ggrc/integrations/constants.py, src/ggrc/integrations/integrations_errors.py, src/ggrc/models/hooks/issue_tracker/assessment_integration.py, src/ggrc/models/hooks/issue_tracker/issue_integration.py, test/integration/ggrc/integrations/test_assessment_integration.py, test/integration/ggrc/integrations/test_issue_integration.py
No message if user creates Assessment w/o enough rights to Hotlist in Issue Tracker
Custom version alext-to-test-5704 deployed to test environment
1. Have an audit with Issue Tracker turned ON 
Hotlist ID: 833568
2. Create assessment w/o enough rights to Hotlist
Actual Result: No message if user creates Assessment w/o enough rights to Hotlist in Issue Tracker
Expected Result: if user creates Assessment w/o enough rights to Hotlist in Issue Tracker, show the message: "Ticket in issue tracker wasn't added to Hotlist. Please make sure that you have enough rights for the Hotlist and try again."
Issue Tracker return error message in format 
403 {"error": "com.google.apps.framework.request.ForbiddenException: apphosting-bla-bla-bla@environment.google.com …
=> GGRC-5704 No message if user creates Assessment w/o enough rights to Hotlist in Issue Tracker

test/integration/ggrc/converters/test_import_update.py, test/integration/ggrc/test_csvs/policy_basic_import_update.csv
The test cases in 'test/integration/ggrc/converters/test_import_update.py' should not allow custom slugs and pass with out any errors.
* The test case is modified such that the required policy object is created without using 'import_file' function.
* Removed the file 'test/integration/ggrc/test_csvs/policy_basic_import_update.csv'.
=> GGRC-7638 Refactor test_import_update.py

src/ggrc-client/js/templates/assessments/assignable_extended_info.stache, src/ggrc-client/js/templates/audits/extended_info.stache, src/ggrc-client/js/templates/base_objects/extended_info.stache, src/ggrc-client/js/templates/cycle_task_groups/extended_info.stache, src/ggrc-client/js/templates/workflows/extended_info.stache
Memory usage and number of DOM Nodes constantly grow when open popup to view items from LHN.
1. Open LHN. 
2. Click on Programs to expand the list.
3. Hover any Program to trigger a popup window.
4. Hover another Program.
5. Repeat steps 3 and 4 to see results.
6. Verify Memory and number of DOM Nodes were reduced after growing.
Number of DOM nodes wasn't being reduced because they were kept in memory as Detached elements. The reason of existing detached elements is instance wrapper that doesn't clean references.  
1. Removed instance wrapper for `extended_info`.
=> GGRC-6427 Fix memory leak on LHN

src/ggrc/models/revision.py, test/unit/ggrc/models/test_revision.py
Missing type field in populated revision content
1. Load ggrc instance dump file
2. Query for 1st or any early created revision object
3. Check content field from sqlalchemy revision-instance
1. Added populate_type method for adding {"type": self.resource_type} for the populated content which have no "type" field in theit content
2. Added test_populate_type test
=> GGRC-7921 BC: Fix type in populate revision content

src/ggrc/notifications/common.py, src/ggrc_workflows/notification/data_handler.py, test/integration/ggrc_workflows/notifications/test_data_handler.py
Related object name is shown incorrectly for notifications.
1. Create Repeat Off workflow 
2. Set a task to task group, map control to task group and Activate Workflow 
3. Run _notifications/show_daily_digest 
4. Look at the future notification
5. Title of mapped object to Cycle task should not be shown as 'Untitled object' in daily digest notification 
Fixed get_cycle_task_related_objects for correctly showing names of related objects
=> GGRC-7272 Fix showing ralation objects name for notification.

src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.js, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache, src/ggrc-client/js/plugins/utils/errors-utils.js, src/ggrc-client/js/plugins/utils/it-enable/issue-tracker-enable.js, src/ggrc-client/js/plugins/utils/request-utils.js, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss, src/ggrc-client/styles/components/dropdown-wrap-text/_dropdown-wrap-text.scss
P. 1
1. Open Bulk Complete modal.
2. Select at least 1 assessment in the list of assessments -> "Select" button should be enabled.
3. Click "Select" button.
Expected:
- Warning modal shouldn't be shown.
- Select button should be disabled during the loading of LCAs.
- After loading of LCAs, LCAs section should be expanded.
- List of generated LCAs should be shown.
- "Select" section should be collapsed.
- "Select" button in "Select" section should be disabled.
P. 2 
After steps from P.1, try to open "Select" section and select/unselect some assessments in the list.
Expected:
- "Select" button in "Select" section should be enabled if the list of selected assessments is changed. If the list is returned to initial state, "Select" button should be disabled again.
P.3
If at least one attribute …
=> GGRC-7703/GGRC-7828 BC: Add "Select assessments" sections for Bulk complete

src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js, src/ggrc-client/js/components/tree/templates/tree-widget-container.stache
Mapped to label is empty
1. Open any Assessment.
2. Open advanced search
Pass *parent_instance* attr from _tree-widget-container_ to _tree-view-filter_ component
=> QUICK-FIX Pass parentInstance to tree-view-filter component

src/ggrc-client/js/components/unified-mapper/mapper-results-item.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results-item.stache, src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
**Should be merged to "asmt-bulk".**
Add "Open" button for each `<mapper-results-item>` on Bulk Complete modal.
Open Bulk Complete modal. In 'Select assessments to complete in bulk' section for each mapper-results-item "Open" button should be displayed. It should redirect to appropriate Assessment's info page.
Change condition to show "Open" button in `mapper-results-item`.
=> BC: GGRC-7864 Add "Open" button for each <mapper-results>'s item

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_issue_csv_template.py
Import Template for Issue should contains help text for snapshot columns that are read-only
1. Open Import objects page
2. Download import templates for Issue
3. Check help test for "map: object versions" fields
Send list of read only types for Issue object to ggrc.models.reflection.AttributeInfo#_generate_mapping_definition method
=> GGRC-7150 Add help text for 'map: object versions' columns at import/export template for Issue

test/integration/ggrc/converters/test_export_snapshots.py
Refactor test_export_snapshots.py
The test cases in 'test/integration/ggrc/converters/test_export_snapshots.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7825 Refactor test_export_snapshots.py

src/ggrc/bulk_operations/__init__.py, src/ggrc/bulk_operations/csvbuilder.py, test/unit/ggrc/bulk_operations/__init__.py, test/unit/ggrc/bulk_operations/csv_builder.py
We should create 3 csv builders to perform imports:
builder for LCA update
builder for bulk complete
I've added it according to our doc
=> GGRC-7723 Create builder methods for LCA and complete

src/ggrc/integrations/synchronization_jobs/one_time_back_sync.py, test/integration/ggrc/integrations/test_onetime_back_sync.py
Attributes of issuetracker_issues can be equal to empty string or contains invalid string literals
Extended previos test.
Add additional logical check for attributes values
=> QUICK-FIX GGRC-7574 Fixed logic; Extended test

src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.js, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache, src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache, src/ggrc-client/js/components/custom-attributes/custom-attributes.stache, src/ggrc-client/js/components/form/fields/dropdown-form-field.js, src/ggrc-client/js/components/form/form-validation-icon.js, src/ggrc-client/js/components/object-popover/related-assessment-popover.js, src/ggrc-client/js/components/object-popover/related-assessment-popover.stache, src/ggrc-client/js/components/required-info-modal/required-info-modal.js, src/ggrc-client/js/components/required-info-modal/required-info-modal.stache, src/ggrc-client/js/components/url-edit-control/url-edit-control.js, src/ggrc-client/js/components/url-edit-control/url-edit-control.stache, src/ggrc-client/styles/_common.scss, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/ca-object/_ca-object-modal.scss, src/ggrc-client/styles/components/related-objects/_related-urls.scss, src/ggrc-client/styles/components/required-info-modal/_required-info-modal.scss
**Should be merged into "asmt-bulk" branch**
What was done:
1. Added validation for LCA fields.
2. Added validation for attachments which can be presented for LCA with `Dropdown` type.
3. Logic from PR #10084 was reworked (returned old implementation) - it's needed in order to be able to reuse component `form-validation-icon` which was changed in that PR.
=> GGRC-7829/GGRC-7711/GGRC-7712 BC: Implement validation for the fields

src/ggrc/converters/base.py, src/ggrc/converters/handlers/evidence.py, src/ggrc/converters/handlers/file_handler.py, src/ggrc/views/__init__.py, test/integration/ggrc/converters/test_import_assessments.py
Create ability to add evidence documents to assessments via import
1. Create audit
3. Export assessment
4. Set Evidence File field with gdrive shareable file link
5. import assessment
1. Added import_bulk mode to ImportConverter
2. Created generate_evidence background task
3. Added execution of generate_evidence background task to EvidenceFileHandler
=> GGRC-7730 BC: Implement documents import

src/ggrc/views/bulk_operations.py, test/integration/ggrc/views/test_bulk_operations.py
**related_assessments** list needs to contain all the cads
1. Open ggrc-app
3. Create objective to audit
4. Create assessment template with CAD
5. Create the assessment with 'Autogenerate' button
6. Make a post request to /api/bulk_operations/cavs/search endpoint with [{'ids': [<asmnt_id>]}] data
Removed else statement in `_get_bulk_cad_assessment_data` func. Now an assessment with LCA will be added to `related_assessments` list
=> QUICK-FIX BC: related_assessments contains all cads

src/ggrc/views/bulk_operations.py
Fix endpoint according our doc
Perform `POST` request to `/api/bulk_operations/complete` to make sure that such endpoint exists.
Endpoint `/bulk_operations/complete` was renamed into `/api/bulk_operations/complete` one.
=> QUICK-FIX Fix endpoint according doc

src/ggrc/settings/default.py
Bump up version to 2.20.0-Pumpkin
=> QUICK-FIX Bump up version to 2.20.0-Pumpkin

src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-lca-popover/assessments-lca-popover.js, src/ggrc-client/js/components/assessment/assessments-lca-popover/assessments-lca-popover.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.js, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/assessments-local-custom-attributes.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-answers-content.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-answers-header.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-objects-content.stache, src/ggrc-client/js/components/assessment/assessments-local-custom-attributes/templates/popover-related-objects-header.stache, src/ggrc-client/js/components/inline/readonly-inline-content.js, src/ggrc-client/js/components/popover-component/popover-component.js, src/ggrc-client/styles/_common.scss, src/ggrc-client/styles/components/assessments-local-custom-attributes/_assessments-local-custom-attributes.scss, src/ggrc-client/styles/components/popover-component/popover-component.scss
**Should be merged to "asmt-bulk".**
Integrate popovers into LCA section on Bulk Complete modal.
When ? is hovered you should see popover with list of snapshots of mapped objects related to Assessments which contains this LCA.
When ! is hovered you should see popover with list of Assessments where this LCA is filled.
Load data when ?/! is hovered and cache it to avoid making request again.
=> BC: GGRC-7714 Integrate popovers into LCA section

src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache, src/ggrc-client/js/components/view-models/object-operations-base-vm.js
**Should be merged in "asmt-bulk"**
In the scope of this PR:
1. Default filter was applied:
State any of ['In Progress', 'Rework Needed', 'Not Started'"] AND
Assignees contains [email of the logged user]
2. Disable "Select" button when there are no selected assessments in the search list.
=> GGRC-7982 BC: Add predefined "Assignees" filter

src/ggrc-client/js/controllers/modals/modals_controller.js
Unexpected error message is appeared when edit person on Audits.
1. Open any Audit with mapped Person.
2. Click on the People icon.
3. Hover over gear icon and select Edit Object.
4. Verify that modal is opened without error message.
For person model `formPreload` function is implemented to return promise. `formPreload` is called in `reset_form` that should be resolved before drawing modal. Using `done()` method doesn't allow to wait until promise resolved that's why modal is appeared before promise resolved=>error message displays. 
1. Replaced `done` method to `then`.
=> GGRC-7803 Unexpected error message is appeared when edit person on Audits

src/ggrc-client/js/helpers.js
For GGRC scope objects on FE remove Delete option. Also, suggested removing the "Delete" Scoping Object (Product, Market, etc.) option from GGRC so that such instances can be avoided. Deprecate will still be available.
1. Open any Scope object info.
2. Verify that Delete option is not shown on any place with Scope object. 
1. Extended `is_allowed` helper to check for scope objects.
=> GGRC-7989 Remove Delete options from all Scope object

src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/templates/assessments/header.stache, src/ggrc-client/styles/_colors.scss, src/ggrc-client/styles/_common.scss
Assessment’s instance has to have “SOX302” label based on `sox302Enabled` field from instance. 
1. Set `sox302Enabled` to `true`.
2. Verify that “SOX302” label is shown on Assessment info/pane. 
1. Added the field to assessment model.
2. Added label to stache template. 
3. Fixed issue with place of _archived_ label.
=> RP: GGRC-7881 Add SOX302 label to Assessment header

test/integration/ggrc/models/test_clonable.py
Refactor test_clonable.py
The test cases in 'test/integration/ggrc/models/test_clonable.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7820 Refactor test_clonable.py

src/ggrc/views/bulk_operations.py
FE team needs BG task id to check BG status
=> QUICK-FIX [BC] Return BG task in response

test/integration/ggrc/services/test_query/test_order.py
Refactor test_order.py
The test cases in 'test/integration/ggrc/services/test_query/test_order.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7786 Refactor test_order.py

src/ggrc/bulk_operations/csvbuilder.py
As some assmts can have no CA's we've added 'assessments_ids' field to our request
=> QUICK-FIX Add assessments that have no custom attributes values

src/ggrc-client/js/components/tree-view-filter/templates/tree-view-filter.stache, src/ggrc-client/js/components/tree/tests/tree-status-filter_spec.js, src/ggrc-client/js/components/tree/tree-filter-input.js, src/ggrc-client/js/components/tree/tree-status-filter.js
JS throws the error when url has **query** param
Open link http://localhost:8080/dashboard#!task&query=%22task+slug%22%3DCYCLETASK-1639
Update `filter` to `submitFilter` event name, because that name conflicts with `filter` attr of viewModel
=> GGRC-8011 "Uncaught TypeError: Cannot read property 'slice' of undefined" error appears on UI from all task links in daily digest email

test/selenium/src/lib/service/proposal_ui_facade.py, test/selenium/src/lib/service/rest/template/access_control_role.json, test/selenium/src/tests/test_proposals.py
=> GGRC-8012 Unskip all proposals tests

src/ggrc/converters/__init__.py, src/ggrc/views/__init__.py, src/ggrc/views/converters.py
- Style check failed
- Selenium tests failed due too import comment ticket GGRC-7726
1. Open import page
2. Press **Download import template**
3. Press **Choose Templates**
4. Check for the comments in the dropdown list
- Added # pylint: disable=unused-argument for the unused kwargs
- Added method too generate only visible list of import templates
=> QUICK-FIX BC: Styles and import comments

src/ggrc-client/js/plugins/utils/background-task-utils.js
=> BC: QUICK-FIX Fix status extraction

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/rest/template/technology_environment.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_mega_program.py
Add test that confirms that technology environment is mapped to programs when you map it to audit which was created in scope of child program.
=> GGRC-7923 Add test checking that Audit's objects (f.e. technology environment) are automatically mapped to Parent and Child programs

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/tree/tests/tree-actions_spec.js, src/ggrc-client/js/components/unmap-button/tests/unmap-dropdown-item_spec.js
Add unit tests to cover new functions around Restrict assignee permissions.
1. Added unit tests for isRestricted, isSemiRestrictedOnStatus attributes, isReadOnlyAttribute method.
2. Extended unit tests for addItem and isAllowedToUnmap attributes.
=> RP: GGRC-7961 Add unit tests for Restrict assignee permission functionalities

src/ggrc/views/bulk_operations.py
=> QUICK-FIX Fix issues with exception after complete button press

src/ggrc-client/js/components/issue-tracker/modal-issue-tracker-fields.js, src/ggrc-client/js/components/issue-tracker/templates/modal-issue-tracker-fields.stache, src/ggrc-client/js/components/issue-tracker/tests/modal-issue-tracker-fields_spec.js, src/ggrc-client/js/components/numberbox/numberbox-component.js, src/ggrc-client/js/components/numberbox/templates/numberbox-component.stache, src/ggrc-client/js/plugins/utils/issue-tracker-utils.js, src/ggrc-client/styles/components/issue-tracker/_modal-issue-tracker.scss, src/ggrc/integrations/constants.py, src/ggrc/integrations/utils.py, src/ggrc/views/__init__.py, src/ggrc/views/issue_tracker.py, test/integration/ggrc/views/test_validate_issue.py
This PR is `on hold` until the the following tickets are implemented:
Provide functionality to check if Issue Tracker ticket's ID is correct.
`alexl-9692` version is deployed to `ggrc-test` and could be used for testing.
1. Perform `GET /api/validate_issue/<issue_id>` request with `issue_id`: 
- one that does not exist in Issue Tracker;
- one that is already linked to GGRC object;
- one that exists and is not linked;
- one that exists and is linked to current resource.
2. Check response message. It should contain following values:
- **if ticket does not exist**: *Ticket tracker ID does not exist or you do not have access to it.*
- **if ticket is already linked**: *This ticket was already linked to another GGRC issue, assessment or review object. Linking the same ticket to multiple objects …
=> GGRC-5897/GGRC-7296 Implement endpoint to check correctness of Issue Tracker ticket's ID

src/ggrc/views/bulk_operations.py
=> QUICK-FIX queued task doesn't return response

test/integration/ggrc/converters/test_import_assessments.py
`OrderedDict` is used directly though only `collection` is imported.
=> QUICK-FIX Fix usage of OrderedDict to prevent Flake8 errors

src/ggrc-client/js/components/add-tab-button/add-tab-button.js, src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/related-objects/related-people-access-control-group.js, src/ggrc-client/js/components/tree/tests/tree-actions_spec.js, src/ggrc-client/js/components/tree/tree-actions.js, src/ggrc-client/js/components/tree/tree-item-actions.js, src/ggrc-client/js/components/unmap-button/tests/unmap-dropdown-item_spec.js, src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js, src/ggrc-client/js/helpers.js, src/ggrc-client/js/models/business-models/assessment.js
BE assessment fields names were changed. Require updates for FE.  
1. Renamed assessment properties due to BE fields names.
=> RP: QUICK-FIX Rename assessment attributes for sox302

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/views/bulk_operations.py
=> QUICK-FIX fix values for import types

src/ggrc-client/js/components/assessment-template-attributes/add-template-field/add-template-field.stache, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache, src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache, src/ggrc-client/js/models/business-models/assessment-template.js, src/ggrc-client/js/plugins/utils/ca-utils.js, src/ggrc-client/js/templates/assessment_templates/modal_content.stache, src/ggrc-client/js/templates/assessments/modal_content.stache, src/ggrc-client/styles/components/add-template-field/_add-template-field.scss, src/ggrc-client/styles/components/assessment-template-attributes/_assessment-template-attributes.scss, src/ggrc-client/styles/components/template-field/_template-field.scss, src/ggrc-client/styles/modules/_modal.scss
**Should be merged into _GGRC-7771-sox-skip-verify_ branch**
1. Open Assessment template modal.
2. Create few LCAs with all types.
3. Check *Enable SOX 302 assessment workflow* checkbox.
- *Is Negative Response* column should be appeared in LCA table.
- *Is Negative Response* should be allowed for LCAs with following types: Text, Rich Text, Dropdown.
- *Text* and *Rich Text* LCAs should have two options: *Not Empty* and *Empty*
=> GGRC-7874 / 7878 / 7877 / 7874 [SV] Add Sox 302 Enabled checkbox on Assessment Template modal

src/ggrc-client/js/models/business-models/assessment-template.js, src/ggrc-client/js/templates/assessment_templates/modal_content.stache, src/ggrc-client/styles/modules/_modal.scss
1.1) Change text under '?' icon for 'Enable SOX 302 assessment workflow" checkbox to:
"SOX 302 assessment workflow enables:
Assignees can only read assessment upon its completion."
1.2) Change help text which is shown when the checkbox is checked: 
"By checking this checkbox:
Assignees will have read only permissions upon assessment completion."
1. Open Assessment template modal. 
2. Verify that checkbox is shown.
2. On click the checkbox help text is presented. 
Commits with adding 'Enable SOX 302 assessment workflow' checkbox were got from other PR. 
Updated help text for the checkbox.
=> RP: GGRC-7957 Change text under '?' icon and help text for 'Enable SOX 302 assessment workflow' checkbox

src/ggrc/settings/default.py
=> BUMP UP 2.21.0-Pumpkin

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/notifications/bulk_notifications.py, src/ggrc/settings/default.py, src/ggrc/templates/notifications/bulk_complete.html, src/ggrc/views/bulk_operations.py, test/integration/ggrc/notifications/test_bulk_notification.py
=> GGRC-7729 Add notifications for bulk task

test/integration/ggrc/converters/test_import_automappings.py
we have some troubles with tests in this files.
We should collect all test cases from these tests
We should totally split and re-implement all of these tests and cover all collected test cases.
Re constructed the test case
=> GGRC-7639 Rework test_import_automappings.py

src/ggrc/views/bulk_operations.py, test/integration/ggrc/bulk_operations/test_bulk_complete.py, test/integration/ggrc/converters/test_import_assessments.py
=> QUICK-FIX BC Fix review issues, codestyle and tests

test/integration/ggrc/bulk_operations/test_bulk_complete.py, test/integration/ggrc/bulk_operations/test_csvbuilder.py
Test csvbuilder extra data empty
Added test for empty extra attributes data (Null or {})
=> BC: QUICK-FIX Test csvbuilder extra data empty

src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.stache
**Should be merged to "asmt-bulk"**
=> QUICK-FIX BC: Exclude "State" option from advanced search for "Bulk complete" modal

src/ggrc/bulk_operations/csvbuilder.py, test/integration/ggrc/bulk_operations/test_csvbuilder.py
=> QUICK-FIX Tests randomly failed, checkboxes not set up

src/ggrc-client/js/components/assessment/controls-toolbar/assessment-controls-toolbar.stache
Edit Answers button should be check not only for` _is_sox_restricted` but also for assessment status. 
=> RP: QUICK-FIX Fix check for Edit Answers button

test/integration/ggrc/converters/test_export_audit.py
Fix wrong sort of slugs in test
=> QUICK-FIX Test wrong string sorted

test/integration/ggrc/bulk_operations/test_bulk_complete.py
Test complete asmt with all variety of LCA attribute type
=> BC: QUICK-FIX Test bulk all attribute types

src/ggrc/converters/handlers/evidence.py, src/ggrc/converters/handlers/file_handler.py, test/integration/ggrc/converters/test_import_assessments.py
Refactor EvidencFileHandler 
Add test for evidence file update in bulk mode
=> BC: QUICK-FIX Change evidence file handler

src/ggrc-client/js/components/release-notes-list/release-notes.md
=> GGRC-8038 Update Whats New for 2.20.0

src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/templates/assessments/header.stache, src/ggrc-client/styles/_colors.scss, src/ggrc-client/styles/_common.scss
Must be merged to **GGRC-7771-sox-skip-verify** branch
=> GGRC-7881 / 7883 [SV] Add attribute “SOX 302” to Assessment Template’s attributes on Global Search modal

src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes.js, src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache, src/ggrc-client/js/components/modal-wrappers/assessment-modal.js, src/ggrc-client/js/templates/assessments/modal_content.stache
Must be merged to **GGRC-7771-sox-skip-verify** branch
1. Open Any Audit.
2. Open Assessments tab.
3. Click **Create** button.
4. Select **Assessment Template** in **SELECT ASSESSMENT TEMPLATE
** dropdown where sox_302_enabled is true
_Expected result_: **Is Negative Response** checkboxes should be displayed in LCA table.
=> QUICK-FIX [SV] Add "Is Negative Response" checkbox on Assessment Create modal

src/ggrc-client/js/components/autocomplete/autocomplete-component.js, src/ggrc-client/js/components/import-export/download-template/download-template.js, src/ggrc-client/js/components/import-export/download-template/download-template.stache, src/ggrc-client/js/components/import-export/download-template/download-template_spec.js
After template has erased from input, assessment template id sent to BE.
1. Go to import page.
2. Select Assessment import type.
3. Add some assessment template - pick value from suggested list.
4. Erase text from input (direct remove of text with keyboard).
5. Click Download.
6. Assessment template id hasn't sent to BE.
Added replacing the erased template by empty template as it was erased.
=> GGRC-7981 Import assessment with assessment template: erase template issue

src/ggrc/settings/default.py
=> BUMP UP 2.22.0-Pumpkin

src/ggrc-client/js/components/assessment-template-attributes/assessment-template-attributes.js, src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache, src/ggrc-client/js/components/modal-wrappers/assessment-modal.js, src/ggrc-client/js/components/tree/templates/tree-item-attr.stache, src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/templates/assessments/modal_content.stache
=> QUICK-FIX Add SOX 302 to Global search

loaders/parse-inner-links.js, src/ggrc-client/js/components/release-notes-list/release-notes.md
Documents should not contain a links to any confidential data about project.
1. Open release-notes.md.
Expected: No links to a google docs.
2. Open What's new popup.
Expected: Links works.
Changed parser logic to find h2 tags from incoming html and replace it with anchor links.
=> GGRC-7907 Whats new: Remove link to a doc from release-notes.md

src/ggrc/builder/json.py, test/integration/ggrc/models/test_assessment.py
Сannot view the IN PROGRESS assessments as part of the PC 2019 Q3 audit. The first attempt produced this error . After was granted Audit Captain access, receivied a new error message 
The issue arises exceptionally and cannot be reproduced locally.
Added check when get_model returns None in the build_type_query function from json.py. And this result is skipped in function build_stub_union_query in same place.
=> GGRC-7925 Add check in case when get_model return None

src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_csv.py
Hint for the Predefined Global Attributes of People type
3.Select the Object Type and export the csv file.
Open the excel and check for the Attributes which have the multi options in column , here you can see the tip message
"Multiple values are allowed.
Delimiter is 'line break'.
Allowed values are emails"
Done the changes in 'src/ggrc/models/reflection.py'  as per the requirement.
=> GGRC-7975 Hint for the Predefined Global Attributes of People type

src/ggrc/models/comment.py, test/integration/ggrc/converters/test_export_csv.py
Update the text for Comments attributes hints
1.Login to GGRC.
2. Got to Exports page.
3. Select any object like Program, Projects etc which has comments column.
4. Click on Export
5. Check the comments section hints in the downloaded excel.
Updated the text in the comment.py file to the following:
“Multiple values are allowed.
Delimiter is "double semi-colon separated values" (";;")".
To mention person at the comment use the following format <a href="mailto:some_user@example.com">+some_user@example.com</a>.”
=> GGRC-7974 Hint for the Comments attributes

src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field_spec.js, src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/tests/assessment-template-save-button_spec.js
=> GGRC-7884 [SV] Add unit tests for GGRC-7771

loaders/parse-inner-links.js, src/ggrc-client/js/components/release-notes-list/release-notes.md
Several commits were cherry-picked from #10158.
=> GGRC-8064 Update Whats New for 2.21.0

src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js, src/ggrc-client/js/components/tree/tree-actions.js, test/selenium/src/tests/test_asmts_bulk_update.py
Need to hide "Bulk complete" buttons due to business-related reasons.
=> QUICK-FIX Hide "Bulk Complete" buttons

src/ggrc-client/js/components/related-objects/templates/related-urls.stache
There is a warning around related-urls template in browser console. 
1. Open All objects page. 
2. Open Audits tab.
3. Verify that no warning in console related to `removeItem`. 
3. Open any Audit.
4. Verify that 'trash' Evidence button works. 
1. Updated syntax for `removeItem` from deprecated way.
=> QUICK-FIX Fix warnings for related-urls template

src/ggrc/converters/pre_commit_checks.py, src/ggrc_workflows/models/task_group_task.py, test/integration/ggrc_workflows/converters/test_column_definitions.py, test/integration/ggrc_workflows/converters/test_import_task_group.py, test/integration/ggrc_workflows/converters/test_import_workflow_objects.py, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Hints for Dates and rename Task Group Task Attributes
3.Select the Object Type ( Task Group Tasks) and export the csv file.
Open the excel and check for the columns in Date format , here you can see the tip message for Task Start Date and Task Due Date
“Allowed value is date in one of formats listed below:
YYYY-MM-DD
MM/DD/YYYY
Only working days are accepted”
other than these will have below tip
“Allowed value is date in one of formats listed below:
YYYY-MM-DD
MM/DD/YYYY”
Updated the description for attributes in _aliases in src/ggrc_workflows/models/task_group_task.py
=> GGRC-7973 Hints for Dates and rename Task Group Task Attributes

src/ggrc-client/js/components/workflow/task-group/task-group.js, src/ggrc-client/js/components/workflow/tests/workflow-activate_spec.js, src/ggrc-client/js/components/workflow/tests/workflow-start-cycle_spec.js, src/ggrc-client/js/components/workflow/workflow-activate.js, src/ggrc-client/js/components/workflow/workflow-start-cycle.js, src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/models/business-models/cycle-task-group-object-task.js, src/ggrc-client/js/models/business-models/task-group.js, src/ggrc-client/js/models/business-models/tests/cycle-task-group-object-task_spec.js, src/ggrc-client/js/models/cacheable.js, src/ggrc-client/js/plugins/utils/workflow-utils.js
refresh_all and refresh_all_force methods are defined for base model Cacheable however they are mostly used for Workflow-related objects.
1. Launch GGRC.
2. Create workflow.
3. Open setting tab.
4. Create new tasks or edit existing ones.
5. Activate workflow.
6. It is supposed to work.
Replace methods on refreshAll function from refresh_queue where it needs.
Delete refresh_all and refresh_all_force methods from Cacheable model.
=> GGRC-7598 Convert refresh_all and refresh_all_force methods to utils

src/ggrc/models/assessment.py, src/ggrc/models/assessment_template.py, src/ggrc/models/audit.py, src/ggrc/models/issue.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/mixins/issue_tracker.py, src/ggrc/models/reflection.py, src/ggrc_workflows/models/workflow.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Unified the Hint that format for attributes in import template
3.Select the Object Type and export the csv file.
Open the excel and check for the Attributes which have the multi options in column , here you can see the tip message
Option_1
Option_2
Option_3"
Modified the below files '_aliases' to give the hint as per requirement and tested.
src/ggrc/models/assessment.py
src/ggrc/models/assessment_template.py
src/ggrc/models/audit.py
src/ggrc/models/issue.py
src/ggrc/models/mixins/__init__.py
src/ggrc/models/mixins/issue_tracker.py
src/ggrc_workflows/models/workflow.py
=> GGRC-7962 Unified the Hint that format for attributes

src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.js, src/ggrc-client/js/components/advanced-search/advanced-search-container/advanced-search-container.stache, src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-attribute.stache, src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-container.stache, src/ggrc-client/js/components/advanced-search/advanced-search-filter-operator.js, src/ggrc-client/js/components/advanced-search/advanced-search-filter-operator.stache, src/ggrc-client/js/components/advanced-search/advanced-search-wrapper.js, src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-button/assessments-bulk-complete-button.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete/assessments-bulk-complete.js, src/ggrc-client/js/components/assessment/assessments-bulk-verify-button/assessments-bulk-verify-button.js, src/ggrc-client/js/components/assessment/assessments-bulk-verify-button/assessments-bulk-verify-button.stache, src/ggrc-client/js/components/assessment/assessments-bulk-verify/assessments-bulk-verify.js, src/ggrc-client/js/components/assessment/assessments-bulk-verify/assessments-bulk-verify.stache, src/ggrc-client/js/components/assessment/view-models/assessments-bulk-updatable-vm.js, src/ggrc-client/js/components/assessment/view-models/bulk-updatable-button-vm.js, src/ggrc-client/js/components/tree/templates/tree-actions.stache, src/ggrc-client/js/controllers/mapper/assessments-bulk-verify-modal.stache, src/ggrc-client/js/controllers/mapper/mapper.js, src/ggrc-client/js/plugins/tests/advanced-search-utils_spec.js, src/ggrc-client/js/plugins/utils/advanced-search-utils.js, src/ggrc-client/js/plugins/utils/state-utils.js, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
**Should be merged to "bulk-verify"**
Add 'Bulk verify' option under 3 dots menu to 'Mapped Assessments' tab at 'Audit' when user for at least one Assessment is - set as Verifier - has Update permissionand Assessment meets the rules:
- Assessment not Archived
- Asmt status in 'In Review'
Add 'Bulk verify' at 'My Assessments' when user for at least one Assessment is 
- set as Verifier 
- has Update permissionand Assessment meets the rules:
- Assessment not Archived,
- Asmt status in 'In Review'
On click 'Bulk verify' a 'Bulk verify' popup should appear.
'Bulk verify' popup should contain the following sections:
1) 'Filter' - filter assessments block 
2) 'Select assessments to verify in bulk' - selecting assessments from the list block
3) 'Verify' button
1) Filter
Filter Assessments block …
=> GGRC-7734/GGRC-7736/GGRC-7737/GGRC-7738/GGRC-7739 BV: Create framework for Bulk verify modal

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/templates/access_control_roles/subtree.stache, src/ggrc-client/styles/_widget.scss
**Should be merged in GGRC-7772**
=> RP: QUICK-FIX Use short form for get attribute value

src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
The client side sends unneeded fields of `issue_tracker` object 
1. Create Audit with **SWITCHED OFF** issue tracker.
2. Create Assessment with **SWITCHED OFF** issue tracker.
3. Open the Assessment and change any attribute.
4. Take a look at request body.
__Actual result__: `assessment.issue_tracker` object has all fields (component_id, hotlist_id, etc.)
__Expected result__: `assessment.issue_tracker` object has only one field (`enabled: false`)
Remove unneeded condition
=> QUICK-FIX Remove unneeded condition from clean up before save

src/ggrc/models/mixins/autostatuschangeable.py, test/integration/ggrc/models/mixins/test_autostatuschangable_evidence.py
Fix Assessment goes from 'In Review/Completed/Completed and Verified/Deprecated' to 'In Progress' state once Note and Description fields are updated in Evidence File/Evidence URL
1. Add any Evidence URL/Evidence file to the Assessment
2. Click on Edit icon at the Evidence URL/Evidence file and add any comment
3. Complete an Assessment
4. Go to All Objects dashboard and click Evidence
5. Open that attached evidence file or url and edit Note field (or Description field)
6. Go back to Assessment and check its status
- Added StatusAffectedChanges for validation and tracking object changed fields
=> GGRC-8067 Fix assessmnet change state evidence note changed

src/ggrc-client/js/components/revision-log/revision-log.js, src/ggrc-client/js/components/revision-log/revision-page.js, src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js, src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
We have two people queries that runs in different time on change log tab .
1. Open any object with additional users.
2. Open Change Log tab.
3. Inspect networks in devtools. Query of users must be one.
loadACLPeople method moved from revision-page to revision-log.
It helps us to getting all users by one query.
=> GGRC-7315 Latency while opening change log tab

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_export_csv.py
The following text should be added for Hint of the ‘Ticket Tracker Integration’ attribute for the Assessment Template object:
“Allowed values are:
On
Off”
1. Log into GGRC app.
2. Navigate to Export page.
3.Select the Object Type ( Assessment Template) and export the csv file.
Open the excel and check for the Ticket Tracker Integration column , here you can see the tip message
“Allowed values are:
On
Off”
Added the values for the Ticket Tracker Integration attribute in the assessment_template.py file
=> GGRC-7967 Hint for 'Ticket Tracker Integration' attribute for Assessment Template Object

test/integration/ggrc/snapshotter/test_indexing.py
Refactor 'test_indexing.py' file
* The test cases in 'test/integration/ggrc/snapshotter/test_indexing.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7817 Refactor test_indexing.py

src/ggrc-client/js_specs/models/cacheable_conflict_resolution_spec.js
In scope of the migration to CanJS 3 test `sets timeout id to XHR-response` in `js_specs/models/cacheable_conflict_resolution_spec.js` was failed. The reason is spy on setTimeout.
1. Run `run_karma`
2. Verify that all tests passed
The tests were incorrect at all because check conditions were added to failFilter of Deferred Object object instead of doneFilter and were never run. As about test with `setTimeout`, the `warningId` option is already covered in `modals_controller_spec.js` and from `cacheable_conflict_resolution_spec.js`  it's impossible to set `warningId` by `setTimeout.` 
Also added new test to cover case with failed conflict resolution.
=> GGRC-7205 Fix tests for cacheable conflict resolution

src/ggrc-client/js/models/mixins/assessment-issue-tracker.js, src/ggrc-client/js/models/mixins/issue-tracker.js, src/ggrc-client/js/plugins/utils/issue-tracker-utils.js
1. Open GGRC
2. Create an Audit with mapped object (any object, e.g. Objective)
3. Create Asmnt Template of appropriate object type (e.g. Objective type)
4. Autogenerate an Assessment via the created Asmnt Template
**Actual result:** Asmnt is not autogenerated, a spinner is in an endless progress, in dev console there's a JS error
**Expected:** Assessment should be autogenerated via Assessment template without any errors 
Check issue tracker before clean UP
=> GGRC-8130 Assessment is not autogenerated via template due to JS error

src/ggrc-client/js/components/advanced-search/advanced-search-filter-state.stache, src/ggrc-client/js/components/dropdown/multiselect-dropdown.js, src/ggrc-client/js/components/dropdown/templates/multiselect-dropdown.stache, src/ggrc-client/js/components/dropdown/tests/multiselect-dropdown_spec.js, src/ggrc-client/js/components/form/fields/multiselect-form-field.js, src/ggrc-client/js/components/form/fields/multiselect-form-field.stache, src/ggrc-client/js/components/import-export/download-template/download-template.stache, src/ggrc-client/styles/components/multiselect-dropdown/_multiselect-dropdown.scss
Implement option search by typing the name of needed option using keyboard.
Main areas for testing: global search, import and custom attributes.
1. Open multiselect-dropdown
2. Type the first letters of an existing option
**Expected result**: Detected option will be automatically highlighted
3. Type the first letters of a nonexistent option
**Expected result**: Previous highlighted option will remain highlighted
4. Press arrow down on the keyboard
**Expected result**: Next option will be highlighted
5. Press arrow up on the keyboard
**Expected result**: Previous option will be highlighted
6. Press enter on the keyboard
**Expected result**: Current  highlighted option will be checked/unchecked
7. Press escape on the keyboard
**Expected result**:  Multiselect dropdown will be closed …
=> GGRC-6616 Improve search of options placed in multiselect-dropdown

test/integration/ggrc_basic_permissions/test_audit_archiving.py
Refactor test_audit_archiving.py
The test cases in 'test/integration/ggrc_basic_permissions/test_audit_archiving.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7815 Refactor test_audit_archiving.py

src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js, src/ggrc-client/js/controllers/modals/archive_modal_controller.js, src/ggrc-client/js/controllers/modals/modals_controller.js, src/ggrc-client/js/controllers/tests/archive_modal_controller_spec.js, src/ggrc-client/js/controllers/tests/modals_controller_spec.js, src/ggrc-client/js/plugins/tests/ggrc-gapi-client_spec.js
Some tests were written in synchronous style for Deferred. In jQuery 3 Deferred is asynchronous. In case of nested deferred there is no possibility to test them. The only way is to rewrite those methods.
https://github.com/google/ggrc-core/commit/a43b9b25db7fc81bf9ad5f662de113e4e2fb53e8
1. Modals controller.
1.1 Launch GGRC.
1.2 Create new programm, or open any other modal.
1.3 Expected: Current user had prefetched before after_preload modal method called.
1.4 Add some fields.
1.5 Click "save & add another" button.
1.6 Expected: Modal fields will reset.
2. GGRC gdrive picker launcher
2.1 Launch GGRC.
2.2 Create new audit and assessment.
2.3 Assign folder for audit.
2.4 Attach some files to folder and upload.
2.5 Expected: It works.
3. Archive modal controller
3.1 Launch GGRC.
3.2 Create …
=> GGRC-7285 Refactor untestable methods

src/ggrc/services/common.py, src/ggrc/services/resources/relationship.py, test/integration/external_app/test_ext_relationships.py, test/integration/ggrc/models/test_relationship.py, test/integration/ggrc_workflows/test_relationships.py
*1. Map two GGRC assets in GGRC
2. Create questionnaire with dependency question for one of existing assets
3. Add another asset as Dependency answer
4. Deprecate answer on GGRCQ side
5. Go to GGRC
Relationship deleted.*
*1. Map two GGRC assets in GGRC
2. Create questionnaire with dependency question for one of existing assets
3. Add another asset as Dependency answer
4. Deprecate answer on GGRCQ side
5. Go to GGRC
Relationship exists in GGRC*
*1: Move get_model_instance relationship part to overriden relationship resource
2: Check if we already have relationship posted
3: If we do, don't change it*
=> GGRC-7015: Manually created scope mappings on GGRC are removed with dependency created answer deprecate:

src/ggrc-client/js/components/assessment/assessments-bulk-verify/assessments-bulk-verify.js
**Should be merged to "bulk-verify" branch**
=> QUICK-FIX BV: Use id for BT tracking

test/integration/ggrc/models/mixins/test_with_readonly_access.py
Rework the test case file test_with_readonly_access.py
Remove slugs from tests where we create models with import
Run the integration test for the TestWithReadOnlyAccessAPI, run the below command:
nosetests -sv integration.ggrc.models.mixins.test_with_readonly_access
Removed slugs from tests where we create models with import
=> GGRC-7821 Refactor Test with readonly access

src/app.yaml.dist
If version for `MySQLdb` is specified as `"latest"` it might install version which will not be working with out BE code.
This PR changes the version of `MySQLdb` in `app.yaml.dist` from `"latest"` to `"1.2.5"`.
=> GGRC-8149 Freeze MySQLdb at 1.2.5

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py
*Import assessment with LCA show incorrect warning logs with many outputs with same error description.*
*You can't see it on UI*
*We check if cell in file have value before adding warning so it will be added only for objects with real errors in file*
=> GGRC-7763: Investigate incorrect import log for Assesments with LCA

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/factory.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/object_page.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/tests/test_disabled_objects.py
Add test to check that user cannot unmap Risk from Scope Objects/Directives
=> GGRC-7624 Check that user cannot unmap Risk from Scope Objects/Directives

src/ggrc/models/comment.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/mixins/base.py, src/ggrc_workflows/models/task_group_task.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc_workflows/converters/test_workflow_export_csv.py
Add Hint to the attributes that cannot be edited
2. Goto Export page.
3. Select the Object Type and export the csv file.
4. Open the excel.
5. check for the non-editable attribute columns , here you can see the tip message
'Automatically provided values'
Modified the _aliases object where ever required in files.
=> GGRC-7966 Add Hint to the attributes that cannot be edited

src/ggrc/settings/default.py
=> BUMP UP 2.23.0-Pumpkin

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/assessment/info-pane/info-pane-issue-tracker-fields.js, src/ggrc-client/js/components/assessment/info-pane/templates/info-pane-issue-tracker-fields.stache, src/ggrc-client/js/components/assessment/info-pane/ticket-id-checker.js, src/ggrc-client/js/components/general-page-header/general-page-header.js, src/ggrc-client/js/components/info-pane/info-pane.js, src/ggrc-client/js/components/inline/inline-form-control.js, src/ggrc-client/js/components/issue-tracker/issue-tracker-switcher.js, src/ggrc-client/js/controllers/info-pin-controller.js, src/ggrc-client/js/templates/base_objects/info-pane-utility.stache, src/ggrc-client/js/templates/issues/info.stache, src/ggrc-client/js/templates/programs/info.stache, src/ggrc-client/styles/components/form/_ggrc-form.scss, src/ggrc-client/styles/components/inline-edit-control/_inline-edit-control.scss, test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py
Add possibility to use inline edit on Issue and Program info-panes
Inline editing should be added for the following fields:
1. ISSUE:
- Description
- REMEDIATION PLAN
- Notes
- EFFECTIVE DATE
- DUE DATE
- Ticket tracker
2. Program:
- Description
- Notes
Create new CanJs components:
1. **info-pane** - to wrap content (in _info.stache_) and check permissions (to avoid copy-past of usage `is_allowed` helper)
2. **issue-info-page-header** - to make **Title** editable and remove redundant functions (located in _general-page-header.stache_) from issue header
=> GGRC-3178 Add inline edit for some attributes across objects: issue, program

test/integration/ggrc_basic_permissions/test_audit_rbac.py
Refactor test_audit_rbac.py file
All the test cases refactored in 'test_audit_rbac.py' file must pass.
* Read access to a program, audit, assessment and an issue is verified for global roles: Administrator, Creator, Reader, and Editor. Access is also verified for program roles: Program Manager, Program Editor and Program Reader.
* Read access to a program, audit, assessment and an issue is verified for global roles: Administrator, Creator, Reader, and Editor. Access is also verified for program roles: Program Manager, Program Editor and Program Reader.
=> GGRC-7612 Refactor test_audit_rbac.py

src/ggrc/models/hooks/assessment.py, src/ggrc/models/mixins/__init__.py, test/integration/ggrc/converters/test_import_assessments.py, test/integration/ggrc/models/mixins/test_autostatuschangable.py
Assessment with set verifier is changed state to Completed if state was changed via Import
2. Create Assessment and set verifier
3. Export created Assessment in sheet
4. Open created GDrive file
5. Change Assessment state to Completed in the table
6. Import Assessment
7. Open Assessment
Actual: Assessment state was changed to Completed
Expected: Assessment state was changed to In Review
We are verifying Assessment Status and for some conditions updating it to right value
=> GGRC-8096 Assessment with set verifier is changed state to Completed if state was changed via Import

src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.js, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field.stache, src/ggrc-client/js/components/assessment-template-attributes/template-field/template-field_spec.js, src/ggrc-client/js/components/assessment-template-attributes/templates/assessment-template-attributes.stache, src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/assessment-template-save-button.js, src/ggrc-client/js/components/assessment-templates/assessment-template-save-button/tests/assessment-template-save-button_spec.js, src/ggrc-client/js/components/modal-wrappers/wrapper-assessment-template.js, src/ggrc-client/js/components/tree/templates/tree-item-attr.stache, src/ggrc-client/js/entrypoints/vendor.js, src/ggrc-client/js/helpers.js, src/ggrc-client/js/models/business-models/assessment-template.js, src/ggrc-client/js/plugins/utils/verification-flow-utils.js, src/ggrc-client/js/templates/assessment_templates/info.stache, src/ggrc-client/js/templates/assessment_templates/modal-content.stache, src/ggrc-client/styles/modules/_modal.scss
1. Open Assessment Template tree-view
2. Check **ASSESSMENT WORKFLOW** column
1. Open Assessment Template info-pane
2. Check updated layout
1. Open Assessment Template CREATE \ EDIT modal
2. Check updated layout
3. Check **ASSESSMENT WORKFLOW** dropdown
=> GGRC-8136 / 8137 [MLV] Update Assessment Template CREATE\UPDATE modal. Add new dropdowns and update styles

src/ggrc-client/js/components/assessment/assessment-evidence-objects/tests/assessment-evidence-objects_spec.js, src/ggrc-client/js/components/assessment/assessment-mapped-comments/assessment-mapped-comments.js, src/ggrc-client/js/components/assessment/assessment-mapped-comments/tests/assessment-mapped-comments_spec.js, src/ggrc-client/js/components/assessment/assessment-mapped-objects/tests/assessment-mapped-objects_spec.js, src/ggrc-client/js/components/assessment/assessment-tree-actions/tests/assessment-tree-actions_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-verify/tests/assessments-bulk-verify_spec.js, src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js, src/ggrc-client/js/components/assessment/view-models/tests/bulk-updatable-button-vm_spec.js, src/ggrc-client/js/components/tree/tests/tree-actions_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item-details_spec.js, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-item_spec.js, src/ggrc-client/js/plugins/tests/utils/background-task-utils_spec.js, src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
**Should be merged after merging Bulk Verify epic into dev.**
Add unit tests for Bulk Verify functionality.
Rewrite `initMappedComments()` method in`assessment-mapped-comments.js` to async/await.
=> BV: GGRC-8028 Prepare unit tests for Bulk Verify functionality

src/ggrc-client/js/components/release-notes-list/release-notes.md
Update What's New content for 2.22.0.
=> GGRC-8064 Update What's new for 2.22.0

test/integration/ggrc/converters/test_export_full_filled_model.py
Test exporting of model where all fields are filled
Run the tests.
The problem is fully described in RCA in GGRC-7478. Actually I check if column has default handler and it doesn't exist then fill this column, create a model object and export it.
=> GGRC-7514 Implement test to validate all fields for exportable models

test/selenium/src/lib/factory.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/conftest_utils.py, test/selenium/src/tests/test_my_work_page.py
Confirm that user cannot create Risk from LHN
=> GGRC-8068 Confirm user cannot create Risk from LHN

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/modal-wrappers/assessment-modal.js, src/ggrc-client/js/models/business-models/assessment.js, src/ggrc-client/js/plugins/utils/verification-flow-utils.js, src/ggrc-client/js/templates/assessments/header.stache
When there are multiple verification level in the assessment, the overall assessment statuses could be shown as:
- Not Started
- In Progress
- In Review 1 of N (when the first level verifiers should review the assessment)
- In Review 2 of N (when the second level verifiers should review the assessment)
...
- In Review N of N (when the last level verifiers should review the assessment)
- Rework Needed
- Completed (with verification)
=> GGRC-8139 [MVL] Update "In Review" Assessment state label

src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/test_export_csv.py
GGRC-7969 Add hint for 'Severity' column for AssesmentTemplate object and integration test to verify it
The following text should be added for Hint of the ‘Severity’ attribute for the Assessment Template object:
“Allowed values are:
S0
S1
S2
S3
S4”
The following text should be added for Hint of the ‘Severity’ attribute for the Assessment Template object:
“Allowed values are:
S0
S1
S2
S3
S4”
Change alias for Severity attribute with allowed values
=> GGRC-7969 Add hint for 'Severity' for AssesmentTemplate object

src/ggrc/converters/handlers/boolean.py, src/ggrc_workflows/models/workflow.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Hint of the ‘Need Verification’ attribute for the Workflow object
2. Goto Export page.
3. Select the Object Type ( Workflow) and export the csv file.
6. check for the added 'Need Verification' column , here you can see the tip message
yes
no"
7. Goto import page.
8. import data from new file.
9. Validate the custom attribute column updated correctly as per data
changed multiple file to make the values allowed and values default with the given requirement.
=> GGRC-7970 Hint of the 'Need Verification' attribute for Workflow

src/ggrc-client/js/components/related-objects/related-documents.js
Sometimes no URL is displayed in the 'Evidence URL' filed when add it on Audit info. 
1. Open Audit.
2. Add Evidence URL and save it.
3. Verify that added evidence is shown in the 'Evidence URL' filed.
After create evidence, request to get all evidences is sent to update list of evidences on UI . Sometimes because of background tasks on Server, the response data is empty and no URL is displayed. To avoid this flex state, use current state data instead of sending the request.
=> GGRC-8059 Fix issue when Evidence URL is not displayed straight away in Audit after saving the URL

src/ggrc-client/js/templates/base_objects/info-pane-utility.stache, src/ggrc-client/js/templates/issues/info.stache, src/ggrc-client/js/templates/programs/info.stache, src/ggrc-client/styles/components/info-pane/_info-pane.scss
Spinner layout is broken
1. Open **Standards** info-pin
=> QUICK-FIX Fix spinner layout

src/ggrc-client/js/components/diff/diff-base-vm.js, src/ggrc-client/js/components/diff/templates/instance-diff-items.stache, src/ggrc-client/js/components/read-more/read-more.js, src/ggrc-client/js/components/read-more/tests/read-more_spec.js, src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.stache
Read more/Read Less appears only after page refreshment.
1. Open a Program in ggrc
2. Click Propose Changes button
3. Insert a big-sized text (2000 signs) in Description field
4. Click Propose button
5. Wait for proposal tab will be loaded (blue icon should be shown)
6. Click Change Proposals tab
7. Verify that Read More / Read Less links appear in Change Proposal tab
_Actual result_: No Read More / Read Less links appear in Change Proposal tab. The links appear only after page is refreshed.
_Expected result_: Read More / Read Less links should appear in Change Proposal tab immediately.
Use **IntersectionObserver** to update **read-more** content (trigger `updateOverflowing`)
=> GGRC-7322 Add Read More / Read Less to Change Proposal tab/Change log tab

src/ggrc-client/styles/components/form/fields/_date-form-field.scss
Border is not in red if date is mandatory field.
1. As admin user ligin ggrc app
2. Open Administration page > Custom attributes> Add 'Date' CA to any object, make it mandatory
3. Open Create object popup and look at the Date CA
4.  Border should be marked in red if date is mandatory field
Removed the readonly border color in 'src/ggrc-client/styles/components/form/fields/_date-form-field.scss'.
=> GGRC-6693: Fix for Border is not in red if date is mandatory field

test/selenium/src/tests/test_asmts_workflow.py
Fix test destructive asmts gcas filtering
=> GGRC-8203 Fix test_destructive_asmts_gcas_filtering

src/ggrc/models/evidence.py, test/integration/ggrc/services/test_query/test_evidence.py
Fix searching for Evidence with Notes attribute filled with the text
1. Add any Evidence URL/Evidence file to the Assessment 
2. Click on Edit icon at the Evidence URL/Evidence file and add any comment 
3. Click on Global Search 
4. Select Assessment as Object type 
5. Click Add Mapping Filter button 
6. Select Evidence as an Object type 
7. Select 'Note' as attribute that "Contains" or "Equals" the comment (NOTES) that was added 
to Evidence URL/Evidence file previously  
8. Click Search button 
1. Added notes field to _fulltext_attrs list;
2. Added test for Evidence search with notes field.
=> GGRC-8065 Fix searching for Evidence with Notes attribute filled with the text

src/ggrc-client/js/templates/audits/modal-content.stache, src/ggrc-client/styles/_common.scss, src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
UI is broken for Attachment and Evidence URL LCA in Edit pop-up.
1. Open GGRC My Dashboard
2. Click Create Audit
3. Check the UI for all fields and buttons of the Audit creation popup
4. Verify that UI looks properly for Attachment and Evidence URL LCA.
1. Updated span size for Evidence Url and Attachment  elements on Audit modal.
2. Set `width: 60%` only for info-pane elements
3. Fixed layout for _Report Period_ on Audit modal.
=> GGRC-8046 Fix bug when UI is broken for Attachment and Evidence URL on 'Edit' pop-up

src/ggrc/models/custom_attribute_definition.py, test/integration/ggrc/models/mixins/test_with_sox_302.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_asmts_workflow.py, test/selenium/src/tests/test_rbac.py
For Checkbox, Date and Map:Person LocalCADs we have multi_choice_options is None
1. Create Assessment template with new functionality enabled and Checkbox, Date or Map:Person Local Custom Attribute
2. Create Assessment based on the Template and add any Assignee
3. Try to Complete Assessment
Actual result: Server Error 500
We do not have any negative options if multi_choice_mandatory mask is None.
=> GGRC-8209 Server Error 500 is appeared when complete Assessment

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/item-edit-control/item-edit-control.js, src/ggrc-client/js/components/related-objects/templates/related-urls.stache
Date on Evidences should be changed if Note was added.
1. Open any Assessment/Audit with added Evidence few days ago.
2. Add any note for existed Evidence URL/File.
3. Review the date. It should be changed to the current date.
Use `updated_at` attribute instead of `created_at`.
=> GGRC-8074 Date on Evidences should be changed if Note was added

test/selenium/conftest.py, test/selenium/src/lib/base.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_mega_program.py
=> QUICK-FIX Add test parent program icon in Unfied Mapper

src/ggrc/utils/json_comparator.py, test/unit/ggrc/models/test_json_comparator.py
FE send context and selfLink attributes for Label model, but we do not have them in json models on BE. 
1. Create Assessment with sox302 enabled and some local custom attributes
2. Add Label to the Assessment
3. Try to update any local custom attribute
Actual result: Error 403 in console
Expected result: Assessment should be updated
Skip verification for attributes in models that we do not have in "second" model. But add validation for objects id's.
=> GGRC-8215 Assignee is not able to save values to LCA

test/selenium/src/lib/base.py, test/selenium/src/lib/page/modal/request_review.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/ui/mentioning_ui_facade.py, test/selenium/src/tests/test_asmts_workflow.py, test/selenium/src/tests/test_mentioning_person.py
Add test checking mentioning on Propose changes and Request review modals for Program works when typing '+' or '@' symbols to comment box
=> GGRC-7930 Add test checking mentioning on Propose changes for Program GGRC-7945 Add test for mentioning on "Request review" popup

test/integration/ggrc/snapshotter/test_snapshoting.py
Refactor test_snapshoting.py file
* The test cases in 'test/integration/ggrc/snapshotter/test_snapshoting.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7816 Refactor test_snapshoting.py

test/integration/ggrc/notifications/__init__.py, test/integration/ggrc/notifications/test_assignable_notifications.py, test/integration/ggrc/notifications/test_comment_notifications.py, test/integration/ggrc/notifications/test_reminderable.py, test/integration/ggrc_workflows/notifications/test_task_due_notifications.py, test/integration/ggrc_workflows/notifications/test_task_overdue_notifications.py
Refactor the _fix_notification_init() helper function in tests.
* All test cases corresponding to notifications should pass without fail after refactoring.
* Removed the duplicated copies of '_fix_notification_init()' function and written a single copy in 'test/integration/ggrc/notifications/__init__.py' file.
=> GGRC-2691 Refactor _fix_notification_init function

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py
Cannot import Assessment with empty mandatory LCA
1. Login in GGRC app
2. Open any Audit
3. Create Assessment template with mandatory LCA
4. Generate Assessment based on the created in the previous step template
5. Export generated Assessment
6. Fill in all mandatory fields except mandatory LCA and Assessment template ID in the Template column
7. Import assessment file
Assessments in the states 'Not Started', 'In Progress', 'Deprecated' can be imported with empty mandatory LCA. Therefore, a function was added to check the state of the imported assessment. Result of this function used in checking the import possibility with empty mandatory LCA.
=> GGRC-7904 Unable to create Assessment with mandatory LCA via import

src/ggrc/query/custom_operators.py, test/integration/ggrc/models/factories.py, test/integration/ggrc/services/test_query/test_cascade_unmappable.py
Changed an implementation of a query in a cascade_unmappable operator and covered logic with tests.
*-*
Changed logic of a query for a cascade_unmappable operator. Earlier, it was implemented using 'set' logic. According to the ticket requirements now it is implemented using 'join' logic. 
Also, added tests to cover logic.
=> GGRC-5320 Refactor cascade_unmappable query API operator

src/ggrc/notifications/fast_digest.py
Prefix in the subject line of fast digest emails is being duplicated (e.g. `[UAT] [UAT] GGRC Change requests review digest for ...`) but it should not.
1. Create a Program;
2. Request review from some user;
3. Execute `$.get("/half_hour_cron_endpoint")` in dev tools console.
4. Look at logs (if running locally) or check an email;
Expected result: email with subject where prefix **is not duplicated** should be sent.
All notifications are sent via `send_email()` function from `notifications.common` module. In this method email subject line is being appended with a prefix. But fast digest emails constructing email subject line with `build_subject()` function were subject is also appended with the prefix.
`build_subject()` function is rewritten in a way that it does not add a prefix anymore. …
=> GGRC-8228 Prefix is duplicated in the subject of fast digest emails

test/integration/ggrc_basic_permissions/test_audit_snapshot_rbac.py
Refactor test_audit_snapshot_rbac.py file
* The test cases in 'test/integration/ggrc_basic_permissions/test_audit_snapshot_rbac.py' should not allow custom slugs and pass with out any errors.
=> GGRC-7578 Refactor test_audit_snapshot_rbac.py

src/ggrc-client/js/components/proposal/apply-decline-proposal.js, src/ggrc-client/js/components/proposal/tests/apply-decline-proposal_spec.js
After apllied proposed changes with non-unique title a spinner of saving the changes is in a constant progress. 404 error displays from the Back-end side in console. No UI error displays that user cannot apply changes.
1. Launch GGRC.
2. Open any program and click Propose Changes button.
3. Propose title of another existing program as a change to this program's title.
4. Click Change proposals tab .
5. Click Apply button.
6. Expected: Modal closes, ui error displays.
Updated prepareDataAndSave() method logic, added error notification.
=> GGRC-8119 Error is missing on UI when user applies proposal with an existing already title to the Program

src/ggrc/notifications/common.py, test/unit/ggrc/notification/test_common.py
Fix bug send_email raise exception in launch_ggrc mode
1. Launching the application: execute in shell >> launch_ggrc
2. Create comment with mentioned person
Doesn't rise AssertionError: No Api proxy found for service "mail"
=> GGRC-7176 Fix bug send_email raise exception in launch_ggrc mode

src/ggrc/converters/errors.py, src/ggrc/converters/handlers/assessment_template.py, src/ggrc/converters/import_helper.py, src/ggrc/converters/pre_commit_checks.py, src/ggrc/models/assessment_template.py, src/ggrc/models/reflection.py, test/integration/ggrc/converters/test_export_full_filled_model.py, test/integration/ggrc/converters/test_import_assessment_templates.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/models/test_with_sox_302.py
=> GGRC-8110 [MLV] Add support for Import/Export for Assessment Templates

src/ggrc/builder/json.py, src/ggrc/models/assessment.py, src/ggrc/models/review_level.py, src/ggrc/services/common.py, test/integration/ggrc/models/test_assessment_review_levels.py
=> GGRC-8111: [BE] Implement multiple review levels workflow support

src/ggrc-client/js/components/info-pane/info-pane.js, src/ggrc-client/js/components/proposal/review-proposal.js, src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/templates/programs/info.stache
Broken revisions-comparer's layout
1. Open any Program.
2. Create a **proposal** with update **description** attribute.
3. Click **Review and Apply** button
Highlight `readonly-inline-content` on revisions-comparer modal
=> GGRC-3178 Fix revisions-comparer modal

test/integration/ggrc/converters/test_import_helpers.py
QUICK-FIX update code style in import helper
=> QUICK-FIX update code style in import helper

src/ggrc/notifications/fast_digest.py, test/integration/ggrc/converters/test_import_helpers.py
BACKMERGE 2.22.0-Pumpkin to dev
=> BACKMERGE 2.22.0-Pumpkin to dev

src/ggrc/converters/handlers/issue_tracker.py, src/ggrc/models/assessment.py, src/ggrc/models/assessment_template.py, src/ggrc/models/audit.py, src/ggrc/models/hooks/issue_tracker/issue_tracker_params_container.py, src/ggrc/models/issue.py, test/integration/ggrc/converters/test_export_csv.py
The following text should be added for Hint of the ‘Priority’ attribute for the Assessment Template, Assessment, Issue and Audit objects:
“Allowed values are:
P0
P1
P2
P3
P4”
1. Log into GGRC app.
2. Navigate to Export page.
3. Select the Object Type (Assessment Template, Assessment, Issue, Audit) and export the csv file. Open the excel and check for the Ticket Tracker Integration column, here you can see the tip message
“Allowed values are:
P0
P1
P2
P3
P4”
Added values for the Priority attribute in the assessment_template.py file
=> GGRC-7968 Hint of the ‘Priority’ attribute for the Assessment Template object

src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" document for 2.23 release.
=> GGRC-8238 What's new for 2.23.0

src/ggrc/gdrive/errors.py, src/ggrc/gdrive/file_actions.py, test/unit/ggrc/models/test_file_actions.py
When the user has no read permission to the file in gdrive, gdrive API returns error with code=404. The same error is returned in case file not found in gdrive. Please, see https://developers.google.com/drive/api/v3/handle-errors#resolve_a_404_error_file_not_found_fileid. 
Such error is not handled on GGRC side and obfuscated error 'File not found' is displayed to the user.
1. Create Global Reader;
2. Create Audit and 2 related assessments (asmt1 and asmt2);
3. Assign Global Reader as 'Auditor' in Audit;
4. Assign Global Reader as 'Assessment Verifier' in asmt 1;
5. Map new Evidence file to asmt1;
6. Log in as Global Reader;
7. Open asmt2 -> 'Related assessments' tab;
8. Check checkbox on Evidence and reuse it.
Expected result: 404 'You have no access to the file and/or the folder or the …
=> GGRC-7862 Fix error message when gdrive API returns 404

src/ggrc-client/js/plugins/utils/object-history-utils.js
Due to updates to latest babel, spread operator for CanList should be used with `Array.from`
1. Open any Program
2. Propose Changes with role (set a user for PROGRAM READERS)
3. Refresh the page.
4. Verify that there is no error with spread operator
1. Added `Array.from` for the list.
=> GGRC-8242 Fix bug with 'Invalid attempt to spread non-iterable instance' error in console

src/ggrc/migrations/versions/20190520_e75eb65a5a43_remove_invalid_entries_qa_inst.py
GGRC-8156
Error during class models changes related to 20190520_e75eb65a5a43_remove_invalid_entries_qa_inst.py migration
1. Modify db class models
2. Run `./bin/containers setup dev`
Use pure SQL query to collect invalid records function
=> GGRC-8205 Replace migration for remove ACR records with Raw SQL

src/ggrc/access_control/list.py, src/ggrc/converters/base_row.py, src/ggrc/converters/handlers/acl.py, src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/models/assessment.py, src/ggrc/models/mixins/with_custom_restrictions.py, test/integration/ggrc/models/mixins/test_with_custom_restrictions.py
We do not validate all attributes for permissions during import objects.
1. Create SOX 302 Assessment
2. Generate Assessment
3. Assign Global creator user as assignee
4. Login as Assignee and export created Assessment
5. Open exported file and change any built in attribute e.g Verifier
6. Import file
7. Open Assessment and review
Actual: Verifier was set in Assessment
Expected: Assignee is not able to change built in attributes
Add Custom Restrictions validations to ACL and CADs handlers, because they are handling separately as other attributes.
=> GGRC-8237 [SOX 302] Assignee is able to change built in attributes and state via import

src/ggrc-client/js/models/business-models/program.js
Global Creator and Global Reader are not able to add/remove more than one Program Manager.
1. Log in as Global Creator/Global Reader
2. Create Program
3. Edit program
4. Add any Program Manager
5. Review
**Actual:** User is not able to add/remove any Program Managers (Input field and trash icon are not displayed)
**Expected:** User is able to add/remove any Program Managers
Fix readOnly property check.
=> GGRC-8211 All users except Global Admin are able to add/remove only one Program Manager

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py
The PR is reverted due to new requirements requiring further refactoring - import/export column handlers for various types should be divided for LCA and GCA ones since they require different value
validation.
=> REVERT PR #10291 GGRC-7904 Unable to create Assessment with mandatory LCA via import

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.stache, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/ca-object/ca-object-modal-content.js, src/ggrc-client/js/components/ca-object/ca-object-modal-content.stache
Text that describe incorrect action is appeared when user deletes Evidence File and it should be change to avoid confusing the user. 
1. Open Assessment template with Dropdown LCA and Evidence file required
2. Choose answer in LCA that required Evidence file 
3. Add Evidence file
4. Wait until the Evidence file is attached and then click remove Evidence file icon (trash icon) 
5. Review text that is displayed below Attach button
6. Verify that  "Wait until the file is removed." message is displayed
1. Added `isRemovingEvidences` and shown message according to it.
=> GGRC-8240 Change text that is appeared when Evidence file is deleted 

src/ggrc/utils/revisions_diff/builder.py, test/integration/ggrc/models/test_revision.py, test/unit/ggrc/models/test_revision.py
The second page in Change Log is empty on Assessment 
1. Open https://ggrc-test.googleplex.com/assessments/289#!info link
2. Open Change Log > Open second page (click '>')
Added json load for prepare_content_full_diff function in builder.py from revisions_diff. This provides the same data type when creating diff.
=> GGRC-7411 Add json load to revision diff builder

src/ggrc/services/common.py, src/ggrc/services/resources/relationship.py, test/integration/ggrc/services/resources/test_relationship.py
New record in change log shouldn't appear if relationship was updated via POST request
1. Create Objective
2. Create Program
3. Send POST request to create relationship between Porgram and Objective
4. Send POST request to create relationship between Porgram and Objective (2nd time)
5. Check the Program/Objective change log
1. moved instance generating for post collection to RelationshipResource
2. added if statement to check if relationship already exist -> return 200 without log object
=> GGRC-7749 New revision record after update rels via post

src/ggrc/models/hooks/issue_tracker/issue_tracker_params_builder.py, test/integration/ggrc/integrations/test_issue_integration.py
Verifier is not selected in the alphabetical order from the Admins in the Issue.
1: Log in GGRC app
2: Open Audit page
3: Invoke New Issue popup
4: Fill title, 3 Admins (differ from Issue Reporter)
5: Set Hotlist and Component ID: Hotlist ID: 700706 Component ID: 64445
6: Click Ticket link on Issue Info panel to open Issue Tracker 
7: Check the Verifier (selected from Admins)
Actual Result: Verifier is selected in the alphabetical order from the Admins in the Issue
We change sorting of admins from name sort to email sort
=> GGRC-8020: Verifier is not selected in the alphabetical order from the Admins in the Issue

src/ggrc_basic_permissions/roles/Creator.py, src/ggrc_basic_permissions/roles/Reader.py, test/integration/ggrc/access_control/acl_propagation/test_cycle_task_assignees.py, test/integration/ggrc/access_control/acl_propagation/test_task_assignees.py, test/integration/ggrc/access_control/acl_propagation/test_wf_member.py, test/integration/ggrc_workflows/test_workflow_api_calls.py
*Global creator and reader can create cycle tasks as wf_members*
*Try to create cycle task as creator or reader wf_member. You will get 403.*
*Add cycle_task_group_object_task to creator and reader create permissions in only condition they are wf_admins*
=> GGRC-4029: Disallow Global Reader/Creator as workflow member to create cycle tasks in one-time wf

test/selenium/run_selenium.py, test/selenium/src/lib/base.py, test/selenium/src/lib/constants/__init__.py, test/selenium/src/lib/constants/timeouts.py, test/selenium/src/lib/decorator.py, test/selenium/src/lib/page/daily_emails.py, test/selenium/src/lib/page/modal/apply_decline_proposal.py, test/selenium/src/lib/service/proposal_rest_service.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/utils/file_utils.py, test/selenium/src/lib/utils/selenium_utils.py, test/selenium/src/lib/utils/test_utils.py, test/selenium/src/tests/test_mentioning_person.py
Add test checking that mention list doesn't appear when typing '+' or '@' with string which is not exist in list of users.
=> GGRC-7922 Add test checking that mention list doesn't appear when there is no search result

src/ggrc/converters/snapshot_block.py, test/unit/ggrc/converters/test_snapshot_block.py
We have broken CAD synced from Q with type Dropdown and value of boolean type. Issue appears when we trying to convert boolean value expecting that it is string type.
- Apply DB backup from UAT
- Open GGRC
- Go to Export page
- Select 'Snapshots' as Object Type
- Select 'Controls' as Snapshot Object Type
- Don't set any Filter parameters 
- Click Export button
Apply additional check that CAD value is string type
=> GGRC-7831 Unable to export all Control snapshots if filtering is not set

test/selenium/src/lib/base.py, test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_disabled_objects.py
Check that comments can not be added to control
=> GGRC-7626 Check that comments can not be added to control

test/integration/ggrc/services/test_query/test_basic.py
QUICK-FIX update code style for advance query api
=> QUICK-FIX update code style for advance query api

test/integration/ggrc/services/test_query/test_basic.py
QUICK-FIX update code style for query assessment
=> QUICK-FIX update code style for query assessment

test/integration/ggrc/services/test_query/test_basic.py
QUICK-FIX update code style sorting query
=> QUICK-FIX update code style sorting query

src/ggrc/settings/default.py
This PR is un hold until following dependencies are merged:
BUMP UP 2.25.0-Pumpkin
=> BUMP UP 2.25.0-Pumpkin

src/ggrc-client/js/components/unified-mapper/mapper-results-columns-configuration.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results-columns-configuration.stache, src/ggrc-client/js/components/unified-mapper/tests/mapper-results-columns-configuration_spec.js, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
UI of Search Results section is broken. It's possible to set more than 7 fields.
1. Click Global Search button
2. Click Search button
3. Click on Hamburger menu in Search Results section
4. Tick any 7 boxes with filters till they become disabled
5. Click Set fields button
6. Click on Hamburger menu again
7. Verify that all boxes are disabled for ticking
8. Uncheck one box and click box with long name
9. Click Set fields button
10. Verify that layout is not broken. 
1. Set `max-width: 80%` to avoid broken layout in case of long names of attributes.
2.  The event of checking size for visible fields of Hamburger menu didn't work because the handler is in `tree-header-selector` element.  Moved Hamburger menu link into the element.
=> GGRC-7938 Disable ability to set more than 7 visible fields in Search/Unified Mapper popup

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/tests/test_disabled_objects.py
Check that buttons 'Mark Reviewed' and 'Request Review' are not displayed at Risk Info page
=> GGRC-8291 Check that buttons 'Mark Reviewed' and 'Request Review' are not displayed at Risk Info page

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_disabled_objects.py
Confirm that user cannot restore Risk version
=> GGRC-8225 Confirm user cannot restore Risk version

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/tests/test_disabled_objects.py
Check that user can export Risk
=> GGRC-8223 Confirm user can export Risk

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/element/info_widget_three_bbs.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/tests/test_disabled_objects.py
Check that user cannot edit or del Risk from global search
=> GGRC-8142 Check user cannot edit or del Risk from global search

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_disabled_objects.py
Confirm that user cannot edit Risk from tree view
=> GGRC-8132 Confirm user cannot edit Risk from tree view

src/ggrc-client/js/components/release-notes-list/release-notes.md
Update "What's new" document for 2.24 release.
=> GGRC-8298 What's new for 2.24.0

test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/element/tab_containers.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/widget/change_log.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/change_log_ui_facade.py, test/selenium/src/lib/service/change_log_ui_service.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/date_utils.py, test/selenium/src/tests/test_asmts_workflow.py, test/selenium/src/tests/test_disabled_objects.py, test/selenium/src/tests/test_objects_review.py
Confirm that Control's Change log tab is valid
=> GGRC-7593 Confirm Control's Change log tab is valid

src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache
When the user has no read permission to the file in gdrive, gdrive API returns error with code=404. The same error is returned in case file not found in gdrive. https://developers.google.com/drive/api/v3/handle-errors#resolve_a_404_error_file_not_found_fileid.
1. Attach a folder to Audit.
2. Remove folder on Gdrive.
3. Verify error message. 
Use unified message on folder error.
=> GGRC-8258 Fix issue when Wrong message is displayed on Audit for user that no access to the folder in GDrive

src/ggrc-client/js/components/assessment/attach-button.js, src/ggrc-client/js/components/assessment/tests/attach-button_spec.js, src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js, src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js, src/ggrc-client/js/plugins/tests/user-utils_spec.js, src/ggrc-client/js/plugins/utils/gdrive-picker-utils.js, src/ggrc-client/js/plugins/utils/user-utils.js
1. uploadFiles util & attach button
1.1. Open or create audit.
1.2. Assign folder.
1.3. Create assessment related to this audit.
1.4. Open created assessment and click attach button.
1.5. Chose some files and upload.
1.6. Expected: It works.
Replace Deferred with Promise.
=> GGRC-8245 Replace Deferred with Promise part 1

test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/messages.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/constants/regex.py, test/selenium/src/lib/constants/str_formats.py, test/selenium/src/lib/constants/value_aliases.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/modal/unified_mapper.py, test/selenium/src/lib/page/widget/change_log.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/ui/mega_program_ui_facade.py, test/selenium/src/lib/utils/assert_utils.py, test/selenium/src/lib/utils/string_utils.py, test/selenium/src/tests/test_mega_program.py
Add test for mapping one program to another as child and verifying that Child Programs tab appears with mapped programs and tab number is updated.
=> GGRC-7789 Add test checking mapping a Child Program

src/ggrc_workflows/__init__.py, test/integration/ggrc_workflows/test_recurring_cycles_event.py
'Start_recurring_cycle' cron job failed on PROD instance
1. Login to the instance with cron enabled
2. Create workflow with next_cycle_start_date
3. Wait till NIGHTLY CRON JOBS will be execute
1. Added usage of default migrator user if job was executed in CRON
=> GGRC-8027 Fix commit event missing modified by

test/selenium/src/lib/page/modal/global_search.py, test/selenium/src/lib/page/modal/search_modal_elements.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_global_search.py
Test checks that created by Creator search is not available for Admin.
=> GGRC-8335 Add test that admin can not see filter of creator

src/ggrc-client/js/plugins/persistent-notifier.js
Chrome popup is displayed while saving objects with attached Evidence URL and Reference URL
1. Open modal to create any object that contains Reference Url or Evidence
2. Add Reference Url or Evidence on modal
3. Click Save button.
4. Verify that Chrome popup isn't displayed
When modal has Reference Url or Evidence added, it needs to create new object=> create relationship between Reference and the object. Only in this case `goToUrl` is postponed and added to `onEmptyCallbacksList`.  After all promises resolved, `goToUrl` is called from `onEmptyCallbacksList`.  `whenQueueEmpties` removes listener for Chrome popup. When `whenQueueEmpties` is called after `goToUrl`, popup is displayed.
=> GGRC-8266 Fix issues when Chrome popup is displayed while saving objects with attached Evidence URL and Reference URL

test/selenium/src/lib/element/page_elements.py, test/selenium/src/tests/test_asmts_workflow.py
Fix test fill asmt gcas in popup
=> GGRC-8188 Fix test fill asmt gcas in popup

src/ggrc-client/js/components/snapshotter/revisions-comparer.js
Attachment/Folder/Reference URL are marked to be restored
1. Log in ggrc app and create a program
2. Add Attachment/Folder/Reference URL to a program
3. Go to Version History and open 'Restore Version: Compare to Current popup'
4. Look at the Attachment/Folder/Reference URL.
5. Attachment/Folder/Reference URL should not be marked as to be restored
Modified the src/ggrc-client/js/components/snapshotter/revisions-comparer.js file as per the requirement.
=> GGRC-7455: Attachment/Folder/Reference URL are marked to be restored

src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
Should be merge in ggrcq_ggrc_scope_sync
QUICK-FIX add revisions for compliance contact migration
=> QUICK-FIX add revisions for compliance contact migration

src/ggrc/models/relationship.py, src/ggrc/services/common.py, test/integration/external_app/test_ext_relationships.py
=> Fix sync issue by old mechanism

test/selenium/src/lib/constants/element.py, test/selenium/src/lib/page/modal/unified_mapper.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_unified_mapper.py
Confirm that user cannot create Risk from unified mapper.
=> GGRC-8100 Confirm user cannot create Risk from unified mapper

test/selenium/src/lib/base.py, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/constants/messages.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_mega_program.py
Add test for check that mapping the program to itself functionality is disabled in Unified Mapper.
=> GGRC-8217 Add test checking program is not able to map to itself in Unfied Mapper

test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/tests/test_disabled_objects.py
Confirm that Risk's Change log tab is valid
=> GGRC-8260 Confirm Risk Change log tab is valid

src/ggrc-client/js/components/page-header/notifications-menu-item.stache, src/ggrc-client/js/components/page-header/page-header.stache, src/ggrc-client/js/components/release-notes-menu-item/release-notes-menu-item.stache, src/ggrc-client/styles/modules/_header-content.scss, src/ggrc-client/styles/modules/_menu.scss, test/selenium/src/lib/constants/locator.py
Styles for menu are too complicated.  
Clean up css styles for top dropdown menu.
=> GGRC-8180 Clean up css styles for user menu

src/ggrc/converters/base_row.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/acl.py, src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/converters/handlers/handlers.py, src/ggrc/converters/handlers/snapshot_instance_column_handler.py, test/integration/ggrc/models/mixins/test_with_custom_restrictions.py
We had some issues in validating permissions during updating an object. Also validation for some attributes types should didn't work correct (date, checkbox, Map:Person)
1. Login as Admin
2. Open any Audit
3. Create SOX 302 Assessment template with LCA of different types
4. Generate Assessment
5. Set Global Creator as Assignee fill in all LCA and move Assessment to in Complete State
6. Log in as Global Creator user
7. Export Assessment
8. Open Exported file and change State to "In Progress", and fill in all LCA
9. Import file
Actual: Assessment state was changed to In Progress, Warnings during import file analysis
Expected: Assessment state should not be changed (Assignee has no permissions to perform this action)
Validate CAVs before updating the object and improve comparison for some …
=> GGRC-8267 Assignee is able to change state of Assessment to In Progress state via Import

test/integration/ggrc/converters/test_import_comments.py, test/integration/ggrc/test_csvs/import_comments_without_assignee_roles.csv
Refactor 'test_import_comments.py' file
* The test cases in 'test/integration/ggrc/converters/test_import_comments.py' should not allow custom slugs and pass with out any errors.
* The test cases are modified such that the required objects are created without using custom slugs.
* In addition, the following csv file is deleted.
> test/integration/ggrc/test_csvs/import_comments_without_assignee_roles.csv
=> GGRC-8317 Refactor test_import_comments.py

src/ggrc-client/styles/_z_index.scss, src/ggrc-client/styles/components/tree/_tree-item-extra-info.scss
After click on view info, dropdown menu doesn't hide until mouse will leave this menu.
1. Open any audit page in ggrc app.
2. Map any snapshot to the audit.
3. In tree view hover over gear icon of snapshot and click View Info.
4. Expected: Menu will be hidden.
Change z-index of dropdown menu.
=> GGRC-6696 View info tooltip adheres to info panel

src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/plugins/tests/utils/widgets-utils_spec.js, src/ggrc-client/js/plugins/utils/widgets-utils.js
JS error while adding evidence URL on My assessments page
1. Log in ggrc app and open My assessments page
2. Open any asmt in treeView and add evidence url
Actual Result: JS error is displayed in console (dev tools)
Expected Result: no errors should be displayed while adding evidence url
https://github.com/YuriChupyrkin/ggrc-core/blob/ba4a7586f8d4f0d8e1b6e54caff998b08b2eb5df/src/ggrc-client/js/plugins/utils/widgets-utils.js#L202
That line of code expects **Assessment** name, but widget has **assessment** value.
Also, I decide to NOT call `refreshCounts` function on **My Assessments page**
=> GGRC-7596 JS error while adding evidence URL on My assessments page

src/ggrc-client/js/controllers/tree/tree-view.js, src/ggrc-client/js/templates/access_control_roles/tree.stache, src/ggrc-client/js/templates/custom_attribute_definitions/tree.stache
Error if trying to remove GCA's.
1. Login as Global Admin in GGRC app
2. Open Administration page > Custom Attributes tab
3. Open any object e.g Assessment
4. Create new GCA
5. Remove GCA
6. Expected: GCA has been removed without error.
Added extra field in tree-view controller. Added extra condition for rendering a content in tree.stache files.
=> GGRC-8277 GCA's are deleting with error

src/ggrc-client/js/components/advanced-search/advanced-search-mapping-criteria.js, src/ggrc-client/js/components/assessment/assessment-people.js, src/ggrc-client/js/components/collapsible-panel/collapsible-panel.js, src/ggrc-client/js/components/comment/comments-paging.js, src/ggrc-client/js/components/comment/mapped-comments.js, src/ggrc-client/js/components/form/fields/multiselect-form-field.js, src/ggrc-client/js/components/inline/base-inline-control-title.js, src/ggrc-client/js/components/inner-nav/audit-inner-nav.js, src/ggrc-client/js/components/inner-nav/inner-nav-collapse.js, src/ggrc-client/js/components/inner-nav/inner-nav-item.js, src/ggrc-client/js/components/mega-relation-selection-item/mega-relation-selection-item.js, src/ggrc-client/js/components/modal-wrappers/assessment-notifications.js, src/ggrc-client/js/components/object-mapper/create-and-map.js, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-results/people-autocomplete-results.js, src/ggrc-client/js/components/questionnaire-mapping-link/questionnaire-mapping-link.js, src/ggrc-client/js/components/redirects/external-attribute/external-attribute.js, src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js, src/ggrc-client/js/components/rich-text/people-mention/people-mention.js, src/ggrc-client/js/components/saved-search/create-saved-search/create-saved-search.js, src/ggrc-client/js/components/saved-search/saved-search-list/saved-search-list.js, src/ggrc-client/js/components/snapshotter/snapshot-scope-update.js, src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js, src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
To migrate CanJS 2 to version 3, "leakScope" was explicitly set for every component.
Now we can remove default values.
Impact: cleaner code.
Removed `leakScope: false` line from the components
=> GGRC-8305 Remove default 'leakScope: false' from components

src/ggrc/settings/default.py
=> BUMP UP 2.26.0-Pumpkin

src/ggrc-client/js/templates/workflows/info.stache
Edit Workflow and Delete aren't shown at Workflows tab on All Objects page
1. Open All Objects page
2. Choose Workflows tab
3. Click on any workflow -> Workflow info page opens
4. Click 3bbs
Actual result: Edit Workflow and Delete options aren't shown
Expected result: They should be shown if the user has appropriate rights
Changed the condition for rendering a three-dots-menu items.
=> GGRC-5292 Edit Workflow and Delete aren't shown at Workflows tab on All Objects page

src/ggrc/notifications/data_handlers.py, test/integration/ggrc/notifications/test_assessment_notifications.py
If we are returning attribute value to it's original value, then we are seeing empty section in daily digest.
1. Open any Assessment 
2. Edit Assessment
3. Fill in any empty Attribute e.g Description
4. Save changes
5. Edit Assessment again and remove added Description
6. Save changes
7. Run _notifications/show_daily_digest
8. Review
Actual: Changed description value is not displayed
Expected: Section shouldn't be displayed if value was changed on the previous.
We are validating that we have any updated fields for assessment_updated notification. Do not add notification to daily digest if no updated data exists.
=> GGRC-8244 Changed on empty attributes values are not displayed in daily digest

src/ggrc-client/styles/modules/_object-header.scss
Title height jumps when hover over title of changeable externally objects. 
1. Open Control info page.
2. Hover over title.
3. Verify that title doesn't jump.
Height of title wrapper increases when Edit icon is displayed that's why title text jumps. Set `min-height: 28px;` for the wrapper as height of Edit icon.
=> GGRC-8306 Fix issue with hover over title of external objects changes element height

src/ggrc-client/js/components/object-review/tests/request-review-modal_spec.js, src/ggrc-client/js/plugins/utils/object-review-utils.js, test/selenium/src/lib/service/webui_facade.py
409 error presents for a request when user restores a program from Reviewed to Unreviewed and  update Description. 
From BE: The issue is reproducing because of different objects etags in the headers. To refresh etags we can request on FE side program/review objects before make PUT request on it
1.	Open a program or any other reviewable object. 
2.	Open dev console.
3.	Mark the program as Reviewed.
4.	Update a description.
5. Verify that there isn't 409 error for requests.
ReviewableInstance(ex. Program) instance should be refreshed to get Etag after updates of a review.
=> GGRC-8122 Fix bug when 409 error displays when user restores a program from Reviewed to Unreviewed with updated Description

src/ggrc-client/js/controllers/modals/modals-controller.js, src/ggrc-client/js/models/mappers/mappings.js, src/ggrc-client/js/permission.js
There is unused import in mapping.js file
`import '../../plugins/utils/models-utils';`
If remove it, dependencies errors appears.
It should be removed and cyclic dependencies resolved.
1. Run in container `build_assets` and `watch_assets`.
2. Login into GGRC.
Expected: It works.
Models must be initialize before importing the components.
=> GGRC-7371 Resolve cyclic dependencies on FE

src/ggrc/services/common.py
QUICK-FIX remove printf from common.py
=> QUICK-FIX remove printf from common.py

test/selenium/src/tests/test_disabled_objects.py
Confirm that user cannot update or delete Risk from info page.
=> GGRC-8112 Confirm user cannot update or delete Risk from info page

test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user cannot update disabled object (Controls, Risks) status.
=> GGRC-8294 Confirm user cannot update disabled object status

test/selenium/src/tests/test_unified_mapper.py
Check that user cannot map Risk to scope objects/directives via add tab
=> GGRC-8349 Check that user cannot map Risk to scope objects/directives via add tab

test/selenium/src/lib/page/modal/unified_mapper.py, test/selenium/src/tests/test_unified_mapper.py
Confirm that user cannot map Risk to Scope Objects/ Directives via Unified Mapper
=> GGRC-8351 Confirm user cannot map Risk to Scope Objects/ Directives via Unified Mapper

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_mega_program.py
Add test checking that that after unmapping regulation from child program and unmapping child program from parent program regulation remains mapped to parent program.
=> GGRC-8219 Add test checking manual unmapping program from mega program.

src/ggrc/converters/handlers/custom_attribute.py, test/integration/ggrc/converters/test_import_assessments.py
Checkbox value from csv file always updates value in CAV object because of saving format.
1. Open GGRC
2. Create an Assessment Checkbox LCA
3. Tick a Checkbox LCA
4. Complete it
5. Go to Export page 
6. Export a completed Assessment
7. Import it again without any changes
8. Check the Assessment's state
Actual result: Assessment is in 'In Progress' state although no changes were made
Expected: Assessment should stay in 'Completed' state if no changes were made
Validate that we updating CAV attribute value before updating it.
=> GGRC-8325 Assessment goes from 'Completed' to 'In Progress' state if it was imported w/o changes

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/page_mixins.py, test/selenium/src/tests/test_disabled_objects.py
Check that new browser tab is displayed after clicking Review Details button for Risks.
=> GGRC-8346 Check review details button for Risks

src/ggrc-client/js/templates/custom_attributes/modal-content.stache
Hide link is available and if user clicks it optional field will be hidden and he will not bee able to unhide this field (Only after clearing browser cache, cookies it will appear).
1. Open LHN menu > Workflows
2. Click Create
3. Verify that 'hide' option isn't shown
`allowHide` is set to `false` by default in case `Workflow` instance type.
=> GGRC-8308 Remove "hide" link for optional fields on Workflow Create and Edit modals

test/selenium/src/lib/constants/files.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/export_page.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_mega_program.py
Export a parent program as csv. file and check that map/unmap:program; map/unmap: parent program; map/unmap: child program columns are not displayed.
=> GGRC-8218 Add test checking disabled mapping/unmaping Program columns in csv

src/ggrc-client/js/components/object-list-item/comment-list-item.js, src/ggrc-client/js/components/object-list-item/comment-list-item.stache
- backend migration of external application
GGRCQ will implement rich text for comments in Controls and Risks. Currently, Control's and Risk's comments are not able to display markdown properly.
1. Open any Control or Risk with comments.
2. Verify that comments are displayed with applied markdown style.
Added `inheritedHandleMarkdown` property for Control's and Risk's comment component that allows to get `handleMarkdown` directly from base object not from comment.
=> GGRC-7807 Make Control's and Risk's comment be available to display markdown

src/ggrc-client/js/components/simple-popover/simple-popover.stache, src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
Arrow is missing on the 'Items per page' button at the pagination on Chrome v. 79
1. Open Unified mapper, Change log, Version history or Tree View. 
2. Verify style for pagination button. 
`-webkit-appearance: menulist`  style for `<button>` element has been removed in Chrome v. 79 (https://chromestatus.com/feature/5070237827334144)
Replaced this with icons.
=> GGRC-8323 Fix issue when arrow is missing on the 'Items per page' button at the pagination

src/ggrc-client/js/components/related-objects/related-objects.js, src/ggrc-client/js/components/related-objects/tests/related-objects_spec.js, src/ggrc-client/js/plugins/tests/query-api-utils_spec.js, src/ggrc-client/js/plugins/utils/query-api-utils.js
1. Related objects.
1.1 Launch GGRC.
1.2 Create audit.
1.3 Create two assessments for this audit.
1.4 Open created assessment.
1.5 Open related assessments tab.
1.6 Open related issues tab.
1.7 Create issue with Raise issues button.
1.8 Reload page.
1.9 Open related assessments and related issues tabs.
1.10 Expected: It works correctly.
Added batchRequestsWithPromise util for future migration the logic connected to batchRequests util from Deferred to Promise.
=> GGRC-8246 Replace Deferred with Promise part 2

.babelrc, package-lock.json, package.json
We are using "webpack": "^4.20.2", which uses internally UglifyJsPlugin to minimise the source code for production. Actually, UglifyJsPlugin was deprecated and Terser should be used (according to the official Webpack's doc https://webpack.js.org/configuration/optimization/).
Impact:
1) UglifyJsPlugin works with ES5 standart of js. Cos of this, we need to use Babel to parse some features to the old syntax. If we update Webpack's version, there'll no need to do such transformation. This leads to performance improvement.
2) The latest version of Webpack uses Terser internally and able to minimise ES6+ syntax.
1. Run the app via `build_assets` and `watch_assets` script. 
2. Verify that the app works properly.
Updated webpack version. Removed babel plugins that are not required because of …
=> GGRC-8288 Update Webpack to the latest version

test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/ui/mega_program_ui_facade.py, test/selenium/src/tests/test_mega_program.py
Add test for mapping one program to another as parent and verifying that automapping of related objects was successful.
=> GGRC-8105 Add test checking mapping a Parent Program

test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/tests/test_disabled_objects.py
Confirm that user cannot make and view proposals for Risk
=> GGRC-8224 Confirm user cannot make and view proposals for Risk

src/ggrc-client/js/components/inline/base-inline-control-title.stache, src/ggrc-client/js/templates/base_objects/description.stache, src/ggrc-client/js/templates/base_objects/extended-info.stache, src/ggrc-client/js/templates/base_objects/notes.stache
Notes field should be always visible for scoping objects. Soon the same will be applied to directives, thus showing it for all.
=> QUICK-FIX Make notes visible for all objects

src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
When open a tab with Saved Search permalink and click Remove Filtered, `saved_search` param is still kept in url.
1. Create Advanced Search.
2. Click Get permalink and open new tab with the link.
3. Remove Filtered.
4. Verify that  `saved_search` param was removed from url.
5. Verify that Go back/Go forward browser button works properly. 
1. On remove Filter and Apply new filter call `cleanUpUrl ` to clean url hash
2. Added condition with `loading` attribute to prevent double calls '{viewModel.router} saved_search' when user browser navigation.
=> GGRC-8278 Clean url parameter 'saved_search' on remove Advanced Search filter

src/ggrc/models/hooks/relationship.py, test/integration/external_app/test_ext_relationships.py, test/integration/ggrc/models/test_relationship.py
=> GGRCIE-7746 for 2.24.0

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js, src/ggrc-client/js/components/assessment/mapped-controls/assessment-mapped-controls.js, src/ggrc-client/js/components/assessment/mapped-controls/tests/assessment-mapped-controls_spec.js, src/ggrc-client/js/components/issue/issue-unmap-item/issue-unmap-item.js, src/ggrc-client/js/components/issue/issue-unmap-item/tests/issue-unmap-item_spec.js
1. assessment-info-pane
1.1 Create audit.
1.2 Map controls to this audit.
1.3 Create assessment with type 'controls'.
1.4 Map controls to created assessment.
1.5 Expected: List with snapshots should refreshed after mapping.
2. assessment-mapped-controls
2.1 Preconditions:
have a program with mapped control
regulation and requirement are created on the program page and mapped to the control
2.2 Create an audit with selected 'manually map snapshots' checkbox
2.3 Open audit page and map the Control to audit from precondition
2.4 Map …
=> GGRC-8247 Replace Deferred with Promise part 3

src/ggrc/models/hooks/relationship.py, src/ggrc/models/relationship.py, src/ggrc/services/common.py, test/integration/external_app/test_ext_relationships.py, test/integration/ggrc/models/test_relationship.py, test/integration/ggrc/models/test_revision.py
=> GGRCIE-7746 for 2.24.1 new version

src/ggrc-client/js/components/general-page-header/templates/general-page-header.stache, src/ggrc-client/js/components/inline/base-inline-control-title.stache, src/ggrc-client/js/components/people/editable-people-group-header.stache, src/ggrc-client/js/components/redirects/external-attribute/templates/external-attribute.stache, src/ggrc-client/js/components/redirects/external-control/external-control.js, src/ggrc-client/js/templates/base_objects/extended-info.stache
Description is not displayed in extended-info of LHN for Scoping objects.
=> QUICK-FIX Fix description in extended-info

src/ggrc-client/js/components/release-notes-list/release-notes.md
Update What's new for 2.25 release.
=> GGRC-8350 Update What's new for 2.25 release

src/ggrc-client/js/components/redirects/external-attribute/external-attribute.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Descriptions can be edited in external objects
Add `!isSnapshot` check
=> QUICK-FIX Fix edit of snapshots

src/ggrc-client/js/components/mapped-counter/mapped-counter.js, src/ggrc-client/js/components/mapped-counter/tests/mapped-counter_spec.js, src/ggrc-client/js/components/related-comments/related-comments.js, src/ggrc-client/js/components/related-comments/tests/related-comments_spec.js, src/ggrc-client/js/components/revision-log/revision-log.js, src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js, src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache, src/ggrc-client/js/components/tree/tests/tree-item-extra-info_spec.js, src/ggrc-client/js/components/tree/tree-item-extra-info.js
1. Related comments.
1.1 Launch GGRC.
1.2 Create audit.
1.3 Create two assessments for this audit.
1.4 Open created assessment.
1.5 Add some comments for opened assessment.
1.6 Open second created assessment.
1.7 Open related assessments tab.
1.8 Click on show more info icon.
1.9 Chose comments tab.
1.10 Expected: It works correctly.
2. Revision-log
2.1 Open assessment from previous test.
2.2 Add some changes to this assessment.
2.3 Open change log tab.
2.4 Expected: It works correctly.
3. Mapped-counter.
3.1 Create program.
3.2 Map to …
=> GGRC-8248 Replace Deferred with Promise part 4

test/selenium/src/lib/page/modal/global_search.py, test/selenium/src/lib/page/modal/search_modal_elements.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_global_search.py
Added test test_saving_of_global_search
=> GGRC-8337 Add test of saving a global search

test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/service/change_log_ui_service.py, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_mega_program.py, test/selenium/src/tests/test_my_work_page.py, test/selenium/src/tests/test_unified_mapper.py
=> GGRC-8433 Add test checking creating a Project/Key Report from My Dashboard is disabled

test/integration/ggrc/services/test_audits.py
Rework test_audits.py
The test cases in 'test/integration/ggrc/services/test_audits.py' should not allow custom slugs and pass with out any errors.
=> GGRC-8314: Rework test_audits.py

src/ggrc_workflows/models/cycle_task_group_object_task.py, src/ggrc_workflows/services/resource.py, test/integration/ggrc_workflows/test_api_calls.py
Application should show corresponding errors in cases when user has no permissions to update object or tries to set not allowed state via PATCH method.
1. Login in GGRC app
2. Open tasks
3. Open Network tab in Crome Dev Tools
4. Click Bulk Update in three dots menu
5. Update state of any task
Add two statuses ('forbidden' and 'status not allowed') when user has no permissions to update object or tries to set not allowed state via PATCH method.
=> GGRC-8301 Show corresponding errors with PATCH request

src/ggrc-client/js/components/add-issue-button/add-issue-button.js, src/ggrc-client/js/components/add-issue-button/add-issue-button.stache, src/ggrc-client/js/components/add-tab-button/add-tab-button.js, src/ggrc-client/js/components/add-tab-button/tests/add-tab-button_spec.js, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js, src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js, src/ggrc-client/js/components/view-models/object-operations-base-vm.js, src/ggrc-client/js/components/view-models/tests/object-operations-base-vm_spec.js, src/ggrc-client/js/models/business-models/issue.js, src/ggrc-client/js/templates/issues/tree-add-item.stache, test/selenium/conftest.py, test/selenium/src/tests/test_snapshots.py
We need to remove ability to map Issue from Unified Mapper on Assessments, due to this mapping occurs errors (Snapshots of objects are mapped instead of issue object).
I.
1. Open any Assessment
2. Click Edit Assessment in tree dots menu
3. Click Map object button
4. Select Issue object
5. Click Search button
**Expected**: Issue should be removed from objects list on Edit Assessment modal
II.
1. Open any Assessment
2. Open Issue tab
**Expected**: "Map" issue button should be changed with "Create" issue button, and Issue creation pop up should be fired.
Exclude Issue from availableTypes for Assessment.
=> GGRC-8187 Remove ability map Issue to Assessment via Unified mapper

test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_my_work_page.py
=> GGRC-8434 Add test checking creating a Project/Key Report from LHN is disabled

src/ggrc-client/js/components/proposal/review-proposal.js, src/ggrc-client/js/components/snapshotter/revisions-comparer.js, src/ggrc-client/js/components/snapshotter/tests/revisions-comparer_spec.js, src/ggrc-client/js/plugins/tests/utils/revision-utils_spec.js, src/ggrc-client/js/plugins/utils/revision-utils.js
After new GCA's has been added to program, it doesn't display on the Review: Compare to Current pop-up on existing programs.
2. Open admin dashboard.
3. Add new GCA to program.
4. Open created program and propose some changes.
5. Review proposed value and click "Review & Apply" button.
5.1 Actual: New GCA didn't display on the Review: Compare to Current pop-up.
5.2 Expected: New GCA will be displayed on the Review: Compare to Current pop-up.
Added content replacing for GCA's fields from program instance. It give us only actual GCA's and resolve all cases when new or deleted GCA's was missed.
=> GGRC-7798 GCA's are not displayed on the Compare to Current pop-up on Programs 

src/ggrc-client/js/components/assessment/assessment-evidence-objects/assessment-evidence-objects.js, src/ggrc-client/js/components/assessment/assessment-evidence-objects/assessment-evidence-objects.stache, src/ggrc-client/js/components/assessment/assessment-evidence-objects/tests/assessment-evidence-objects_spec.js, src/ggrc-client/js/components/related-objects/templates/related-urls.stache, src/ggrc-client/styles/components/assessment-evidence-objects/assessment-evidence-objects.scss
Add optional description for Evidence URL/File to the Bulk Verify popup.
3. Add Evidence File and Evidence URL
4. Add optional description for Evidence file and Evidence URL
5. Add verifier and move Assessment to In Review state
6. Open My Assessments
7. Click Bulk Verify button
8. Find Created Assessment and click on it
9. Open Evidence and Custom Attributes section
**Expected**: Optional descriptions are displayed on Evidences
Use `item-edit-control` component instead of `document-object-list-item`.
=> GGRC-8255 Optional descriptions for Evidences should pull to the Bulk Verify pop up

src/ggrc-client/js/components/related-objects/related-people-access-control.js
=> QUICK-FIX. Define 'singleUserRoles' value as function

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/dashboard.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/change_log_ui_service.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/lib/service/rest/template/key_report.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_disabled_objects.py, test/selenium/src/tests/test_unified_mapper.py
Confirm user cannot map Risk to Scope Objects/ Directives via Unified Mapper
=> GGRC-8362 Confirm user cannot map Standard/Regulation to Scope Objects via Unified Mapper

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/dashboard.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/change_log_ui_service.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/lib/service/rest/template/key_report.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_disabled_objects.py, test/selenium/src/tests/test_unified_mapper.py
GGRC-8427 Check that user cannot map Scope to Standard/Regulation objects via 'add tab' menu
=> GGRC-8427 Check that user cannot map Scope to Standard/Regulation objects via 'add tab' menu

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/objects.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/dashboard.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/change_log_ui_service.py, test/selenium/src/lib/service/rest/client.py, test/selenium/src/lib/service/rest/template/key_report.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/service/webui_service.py, test/selenium/src/tests/test_disabled_objects.py, test/selenium/src/tests/test_unified_mapper.py
Check that user cannot unmap Scope object from Standard/Regulation.
=> GGRC-8439 Check that user cannot unmap Scope object from Standard/Regulation

src/ggrc/utils/__init__.py, src/ggrc/views/__init__.py, test/integration/ggrc/converters/test_export_controls.py, test/integration/ggrc/fulltext/test_total_reindex.py, test/integration/ggrc/services/test_authorizations.py, test/integration/ggrc/services/test_query/test_snapshots_.py, test/integration/ggrc/snapshotter/test_indexing.py
`/admin/full_reindex` and `/admin/reindex_snapshots` endpoints should be deprecated now in favor of `/admin/reindex` since they don't work properly.
1. Run GGRC app and login as Superuser;
2. Try to perform `POST` /admin/full_reindex` and look in devtools for response;
3. Try to perform `POST` /admin/reindex_snapshots` and look in devtools for response.
Expected result: `405` status code should be returned with appropriate error response telling that this endpoints are deprecated in favor of `/admin/reindex`.
This solutions includes:
- New decorator deprecatted_endpoint which could be used to mark an endpoint as a deprecated one. New endpoint could be provided as a parameter here.`
- Endpoints starting background tasks for full reindex and snapshots reindex are decorated with …
=> GGRC-8069 Deprecate full reindex and reindex snapshot endpoints

src/ggrc/migrations/versions/20191009_9a38b1d92f3e_extend_tables_for_scope_objects.py, src/ggrc/models/control.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/mixins/synchronizable.py, src/ggrc/models/mixins/with_external_created_by.py, src/ggrc/models/risk.py, test/integration/ggrc/converters/test_export_snapshots.py, test/integration/ggrc/converters/test_import_helpers.py, test/integration/ggrc/converters/test_snapshot_block.py, test/integration/ggrc/models/factories.py
Scoping Objects must be extended with "created_by_id" attribute
Extend Synchronizable mixin with field "created_by_id". 
Extend existing migration for Scoping Objects
=> QUICK-FIX Add "created_by_id" attribute for Scoping Objects.

src/ggrc-client/js/components/modal-wrappers/assessment-modal.js, src/ggrc-client/js/components/modal-wrappers/tests/assessment-modal_spec.js, src/ggrc-client/js/templates/assessments/modal-content.stache
We need to remove "You are about to move assessment from "In Review" to "In Progress"." message from Edit Assessment pop up, when Label, Global Custom Roles, Primary Contacts and Secondary Contacts, Ticket Priority, Ticket Severity, Ticket Title fields and turn ON/OFF issue tracker integration changed, because changing these fields doesn't change Assessment state.
1. Open any Assessment
2. Move Assessment to Complete state
3. Open Edit Assessment pop up
4. Edit some fields from description (Labels, Global Custom Roles, etc)
5. Review
**Expected**: Message shouldn't appear
Listens instance change event and sets showMessage attribute to true if some of tracked properties has changed.
=> GGRC-8241 Remove message on Edit Assessment popup, that Assessment state will be changed when edit label field

src/ggrc-client/js/components/import-export/current-exports/current-exports.stache, src/ggrc-client/styles/modules/_import-export.scss, src/ggrc/converters/snapshot_block.py, src/ggrc/models/import_export.py, src/ggrc/notifications/job_emails.py, src/ggrc/views/converters.py, test/integration/ggrc/converters/test_export_with_sql_error.py, test/integration/ggrc/models/test_log_json.py
Export request did not finish due to errors while exporting all controls snapshots.
2. Select OBJECT TYPE 'Snapshots'
3. Select 'SELECT SNAPSHOT OBJECT TYPE' e.g. Control
4. Click Export button
**Actual Result:** Export failed due to server error. occurred, export was not finished.
**Expected Result:** Export success.
Database query to select snapshots was splitted to chunks. Added handling sqlalchemy error, when cannot commit changes in DB. Also added flag, that check is export or not on step creating json.
=> GGRC-5646/GGRC-8286 Export request did not finish due to errors while exporting all controls snapshots

src/ggrc-client/js/components/evidence-item/templates/evidence-item.stache
Large comments make Assessment page very long, and it's inconvenient to work with other LCA.
1. Add any Evidence URL/Evidence file to the Assessment.
2. Click on Edit icon at the Evidence URL/Evidence file.
3. Add any comment with more than 2000 symbols and save it.
4. Expected: Comment collapses.
Added read-more component for collapsing long comments.
=> GGRC-8086 Add Read more link & Read less link that will collapse and expand huge comments of Evidence URL/Evidence File

src/ggrc-client/js/models/cacheable.js
Standard, Policy, Regulation, Contract extend Directive model. Mixins(AccessControlList,Reviewable) are not applied to them (applied only to the first loaded model). 
1. Verify that Mixins (AccessControlList,Reviewable) are applied to all models(Standard, Policy, Regulation, Contract)
When create first inherited model, Mixins are added to `_mixins` property of Parent model and applied, next models cannot add Mixins to `_mixins` because it already contains them.  
`_mixins` property was not clean because of wrong spelling.
=> GGRC-8474 Mixins are not applied to inherited models

test/integration/ggrc/smoke_tests/__init__.py, test/integration/ggrc/smoke_tests/test_bulk_notification.py
Test cases "Bulk verify success message and email notification" and "Bulk Verify failure message and email notification" are not covered by automation tests. To improvement, these test cases should be covered by integration tests.
After changes, all test in test/integration/ggrc/smoke_tests/test_bulk_notification.py should work correct.
In order to cover parts of Smoke test cases through integration tests, the smoke_tests folder was created and the file test_bulk_notification.py was moved to this folder.
=> GGRC-8026 Notifications for bulk update completion

src/ggrc-client/styles/components/mapped-objects/_mapped-objects.scss
=> QUICK-FIX Fix evidence item styles   

src/ggrc-client/js/components/tree/tests/tree-actions_spec.js, src/ggrc-client/js/components/tree/tree-actions.js
Create Task and Create Cycle Task button appears for Global Reader and Global Creator w/o a admin permissions on workflow.
1. Create a WF with repeat off, create at least one task group task in a task group. Activate WF.
2. Log in as a Global Reader.
3. Go to a WF (Global Reader should NOT have any WF role in this workflow: WF manager, WF member, Task Assignee).
4. Go to 'Active Cycles' tab
5. Expected: Create Task button is unavailable.
6. Click on tree-dots-menu
7. Expected: Create Cycle Task button is unavailable.
8. Expected: This behavior will reproduced for Global Creator with WF member role.
*Briefly explain the solution or add a link to the technical design document (this will help the reviewer confirm the code does what you intend). Feel free to also mention alternative …
=> GGRC-4029/GGRC-4456 Disallow Global Reader(or Creator as workflow member) to create cycle tasks in one-time wf	

test/integration/ggrc/notifications/test_people_mentions.py
Add tests for mentioning person in the Assessment, Proposals, Comment LCA.
Exist tests for mentioning person notifications should work correctly.
Added integration tests for mentioning person notifications in file test_people_mentions.py
=> GGRC-8097 Add integration tests for mentioning person notifications

src/ggrc/services/common.py, test/integration/ggrc/models/test_relationship.py
When trying to POST relationship we fetch only first value from mirrored ones and then catch Integrity Error trying to update another relationship. 
Have 2 mirrored relationships and trying to POST on oldest relationship.
Fetch 2 mirrored relationships and check another one.
=> GGRC-8447 Update proper relationship on POST

src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
During the migration of Primary / Secondary Contacts to Compliance Contacts for scope objects wrong records were added to `objects_without_revisions` table.
1. Load DB dump;
2. Run the migration;
3. Execute `create_missing_revisions` background job;
4. Make sure there is no `"Compliance Contacts"` ACPs without Revisions
Fix the existing migration to insert correct data in `object_without_revisions` table.
=> QUICK-FIX Fix missing revisions for Compliance Contacts

src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py, src/ggrc/models/access_group.py, src/ggrc/models/account_balance.py, src/ggrc/models/assessment.py, src/ggrc/models/control.py, src/ggrc/models/data_asset.py, src/ggrc/models/directive.py, src/ggrc/models/facility.py, src/ggrc/models/hooks/relationship.py, src/ggrc/models/issue.py, src/ggrc/models/key_report.py, src/ggrc/models/market.py, src/ggrc/models/metric.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/mixins/with_workflow_state.py, src/ggrc/models/objective.py, src/ggrc/models/org_group.py, src/ggrc/models/product.py, src/ggrc/models/product_group.py, src/ggrc/models/program.py, src/ggrc/models/project.py, src/ggrc/models/requirement.py, src/ggrc/models/risk.py, src/ggrc/models/system.py, src/ggrc/models/technology_environment.py, src/ggrc/models/threat.py, src/ggrc/models/vendor.py, src/ggrc_workflows/__init__.py, src/ggrc_workflows/models/workflow.py, test/unit/ggrc_workflows/models/test_workflow.py
The goal for the ticket is to improve performance of query API and resource requests by implementing the following tasks:
Create column workflow_state in WorkflowState based models, use column value instead of calculating value based on related cycle tasks states each time when model json is returned
Update workflow_state column for related objects when cycle task state is changed
As result, workflow_state attribute value will be fetched directly from DB instead of loading all related cycle tasks and calculating workflow_state attribute for each object request
1. Create Workflow
2. Map object (for example Control) to TaskGroup
3. Create Task inside TaskGroup
4. Activate Workflow
5. Change CycleTaskGroupObjectTask state and observe values in 'workflow_state' field of mapped Control.
Create …
=> GGRC-7155 Add column 'workflow_state' to WorkflowState based models

src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py, src/ggrc/migrations/versions/20200127_d0f2f2dcde8d_update_propagation_tree_for_assessment.py
Fix broken migration chain and move op.get_bind() into callable.
1. Run the migrations and make sure they pass successfully.
2. Make sure `alembic show heads` shows only one head.
* Fix the migration chain.
* Move `op.get_bind()` call in migration "add workflow_state" into a callable. If not placed there, alembic commands like `alembic show heads` and other does not work.
=> QUICK-FIX Fix broken migration chain and move op.get_bind() into callable

src/ggrc/migrations/versions/20191122_2d0f232de783_primary_secondary_to_compliance.py
Migration of Primary and Secondary contacts to Compliance ones fails with `sqlalchemy.exc.InvalidRequestError: Statement is not an insert() expression construct` exception.
1. Run the migration while some data a present in the DB.
2. Make sure all migration pass successfully.
`inserted_primary_key` _sqlalchemy_ property is replaced with already existing util `last_insert_id()`.
It appears that `inserted_primary_key` is not working correctly when a plain SQL is executed via connection. On the other hand, `last_insert_id()` util uses plain SQL to get last inserted ID, so it works just fine.
=> QUICK-FIX Replace "inserted_primary_key" with plain SQL

src/ggrc-client/js/components/diff/templates/instance-diff-items.stache, src/ggrc-client/js/components/proposal/templates/review-proposal.stache, src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals-item.stache, src/ggrc-client/js/components/related-objects/proposals/templates/related-proposals.stache, src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions-item.stache, src/ggrc-client/js/components/related-objects/revisions/templates/related-revisions.stache, src/ggrc-client/js/components/workflow/task-list/templates/task-list.stache, src/ggrc-client/js/templates/task_group_tasks/task-group-subtree.stache, src/ggrc-client/styles/_common.scss, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/related-objects/_related-objects-list.scss, src/ggrc-client/styles/modules/_workflow.scss, test/selenium/src/lib/page/widget/related_proposals.py, test/selenium/src/lib/page/widget/task_group_info_panel.py
We have the similar layouts for the Proposal and Task Group Task types. But, each from the grids has separate css classes, which have names bound to the model within they are used (task-item, or proposal-item). Should be created an unified way for css classes and grid layout.
1. Launch GGRC
2. Open workflow
3. Open Setup tab
4. Open task group
5. Expected: It works.
Reused common styles from proposal and restore version for task-group-tasks
=> GGRC-4877 Unify styles for the grids with Proposals and Task Group Tasks

src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py
There is an ORM dependency in "workflow state" migration which should be removed since it might affect future migrations.
1. Run the migration and make sure it pass successfully.
2. Make sure `workflow_state` column in present in all the meant tables.
Remove ORM dependency from workflow state migration
=> QUICK-FIX Remove ORM dependency from workflow state migration

src/ggrc/views/external_mappings.py, test/integration/ggrc/models/test_ext_mapper.py
External mapping endpoints should be adapted with possibility processing requests with several ids
And send data by filter
Run unit tests
Check external mapping endpoints for processing several ids
Update endpoints configuration
=> [WIP] GGRC-8515 Replace custom values processing without custom attribute id

src/ggrc/notifications/common.py, test/unit/ggrc/notification/test_common.py
while importing file with non-unicode title, email with non-unicode characters cannot be send.
solution: decode string as utf-8 in subject field for email, add test for it.
1. export any object
2. rename it to non-ascii chars (f.e. russian)
3. try to import this file
4. import should be successfull and notification about it would be send by email
Add unicode decoding in prefix_subject method.
=> GGRC-4913 [Reopen] Fix unicode title issue

src/ggrc/migrations/versions/20191210_aee8f6a09419_add_workflow_state_column.py
There is an ORM dependency in "workflow state" migration which should be removed since it might affect future migrations.
1. Run the migration and make sure it pass successfully.
2. Make sure workflow_state column in present in all the meant tables.
Remove usage of `all_models` and `wf_models` from the migraiton.
=> QUICK-FIX Remove dependency on ORM models

src/ggrc/views/external_mappings.py
QUICK-FIX extend external mapping with json loads
=> QUICK-FIX extend external mapping with json loads

test/selenium/src/lib/base.py, test/selenium/src/lib/page/dashboard.py, test/selenium/src/lib/page/modal/search_modal.py, test/selenium/src/lib/page/modal/search_modal_elements.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/lib/utils/selenium_utils.py, test/selenium/src/tests/test_search.py
Check saved advanced searches are sorted by descending, saved search can be removed, permalink appears near the search and works.
=> GGRC-8338 Add test of saving an advanced search

src/ggrc/query/custom_operators.py, test/integration/ggrc/services/test_query/test_not_empty.py
When user creates comment from Q side, C side receives 3 actions: _create comment_, _map comment to object_, _map object to comment_. In that case 2 mapping actions are shown on "Change Log" tab for objects, which were synced with Q side (Control, Risk, Comment).
Only one mapping action for _\<comment - object\>_ should be showed on "Change Log" on C side.
Since currently the creation of the duplicated Revisions for Relationships is already resolved by #10462 PR, the only way to test the changes would be to setup proper DB dump (see the ticket description).
1. Login in GGRC application;
2. Go on page;
3. Open "Change Log" tab.
**Expected result: only one mapping action for _\<comment - object\>_ should be showed in change log (i.e. there should not be any "modified" Revisions of …
=> GGRC-7318 Remove duplicate mapping actions for Comment from Change Log

src/ggrc-client/styles/components/info-pane/_info-pane.scss, src/ggrc-client/styles/components/simple-popover/_simple-popover.scss
UI issue with pagination button when number is long.
UI issue with Verified icon on Assessment info pane. 
Case 1:
1. Open active Workflow. Go to Active cycles tab
2. Scroll down the page and expand tasks
3. Click on number of result
4. Select 100
5. Verify that UI is not broken
Case 2:
1. Open Assessment in Completed&Verified status. 
2. Verify that UI is not broken around `verified-icon`.
1. Fixed style for pagination button
2. Fixed style for `verified-icon` on Assessment info pane
=> GGRC-8548 Number of results <100> has a broken UI on pagination

src/ggrc-client/js/components/tree-view-filter/tree-view-filter.js
`navigator.clipboard` is only supported for pages served over HTTPS and for localhost. Selenium tests are run via HTTP. 
1. Open Advanced Search popup
2. Preset attributes for search and save that search
3. Click Save button to save the search
4. Click Apply button
6. Click Get Permalink via 3'bbs menu
7. Verify that permalink works
Added condition for  `navigator.clipboard`, used workaround in case of undefined.
=> GGRC-8365 "Uncaught TypeError: Cannot read property 'writeText' of undefined" error appears when Get Permalink is clicked on Saved Advanced Search

test/selenium/src/lib/page/modal/bulk_update.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_asmts_bulk_update.py
=> GGRC-8521 Add test checking canceling of bulk verify

src/ggrc/query/my_objects.py, test/integration/ggrc/services/resources/test_person.py, test/integration/ggrc/services/test_query/test_owned.py
Currently, an audit only shows up as a listed audit if user is listed as an Audit Captain or Auditor. If user has an assessment in the audit, they need to have this audit in their My Work panel.
In dev: create 2 audits with different users as audit captains. In both audits create an assessments with the user1 as an creator/assignee/verifier. Log in as user 1. In My work panel in Audits should be 1 element.
Switch to current branch - In My work panel should be 2 elements. 
Change counts for audits and "owned" function, which determines what user can see in My Work panel.
=> GGRC-8415 Ability to add an audit to "My Work" without being an audit captain

src/ggrc-client/js/models/business-models/control.js, src/ggrc-client/js/templates/controls/info.stache, src/ggrc-client/js/templates/risks/info.stache
There are new Attributes in the Control object in internal project. We need to add these attributes to the GGRC Control object as well to be able to synchronize the objects.
1. Add "Created By" attribute
2. Add "Due Date" attribute
3. Add "Last Owner Review Date" attribute
4. Add "Last Owner Reviewed By" attribute
5. Add "Last Compliance Reviewed Date" attribute
6. Add "Last Compliance Reviewed By" attribute
1. Open Control info page.
2. Verify that new attributes are shown in correct order. 
[FE] Added attributes to Control model, updated Control info page.
=> GGRC-7052 Add Attributes to the Control object

test/selenium/src/lib/base.py, test/selenium/src/lib/page/widget/widget_base.py, test/selenium/src/lib/service/admin_webui_service.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_admin_dashboard_page.py
=> GGRC-8542 Add test creating CA for Assessments

test/selenium/src/tests/test_unified_mapper.py
Confirm user cannot create and map Scope to Standard/Regulation via unified mapper
=> GGRC-8431 Confirm user cannot create and map Scope to Standard/Regulation via Unified Mapper

src/ggrc_workflows/__init__.py
Fix 'workflow_state' field calculation for GGRC-7155.
1. Create Workflow
2. Map object (for example Control) to TaskGroup
3. Create Task inside TaskGroup
4. Activate Workflow
5. Change CycleTaskGroupObjectTask state and observe values in 'workflow_state' field of mapped Control and Workflow (in Chrome DevTools).
Add 'workflow_state' column calculation to hooks used in workflow lifecycle.
=> QUICK-FIX Fix 'workflow_state' field calculation

src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/assessment/info-pane/tests/assessment-info-pane_spec.js
Use case # 1
1. Open Assessment info-page.
2. Open reuse tab and reuse some URL or FILES.
Use case # 2
1. Open Assessment info-page.
2. Add 2 URLs.
3. Go to EVIDENCE tab and DELETE 1 URL
=> QUICK FIX 'loadFiles' and 'loadUrls' functions return Evidence instead of canMap

test/selenium/src/tests/test_unified_mapper.py
=> GGRC-8435 Add tests checking a creating scope objs from unified mapper is disabled

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user cannot update Scope object predefined field
=> GGRC-8541 Confirm user cannot update Scope object predefined field

test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user cannot add person to custom role for Scope object
=> GGRC-8561 Confirm user cannot add person to custom role for Scope object

test/selenium/src/lib/element/info_widget_three_bbs.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user cannot edit or delete Scope object from global search
=> GGRC-8510 Confirm user cannot edit or delete Scope object from global search

test/selenium/src/tests/test_disabled_objects.py
=> GGRC-8508 Add test user cannot edit or delete scope objects from info panel

src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Problem statement:
The mapping link is changed on extrnal side (renamed status from 'In progress' to 'Pending review')
New format of link (General format):
`{MAPPING_PAGE_URL}?mappingStatus=pending_review,not_in_scope,reviewed`
We need to change the link in all the places where the old format (`?mappingStatus=in_progress,`) is used.
Check map/unmap links for external objects.
`getMappingUrl` and `getUnmappingUrl` were updated.
=> GGRC-7074 Change the mapping link that points to external service

src/ggrc/converters/column_handlers.py, src/ggrc/models/assessment_template.py, test/integration/ggrc/converters/constants.py, test/integration/ggrc/converters/test_export_csv.py, test/integration/ggrc_workflows/converters/test_import_workflow_objects.py
Add Hint of the ‘Archived’ attribute for the Assessment Template object
2. Goto Export page.
3. Select the Object Type ( AssesmentTemplate) and export the csv file.
6. check for the added 'Archived' column , here you can see the tip message
yes
no"
Added the values for the Archived attribute in the assessment_template.py file
=> GGRC-7971 Add tip for Archived option in Assessment Template

test/selenium/src/tests/test_disabled_objects.py
=> GGRC-8509 Add checking user cannot edit scope object from tree view

test/selenium/src/lib/base.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/page/widget/change_log.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_change_log_tab.py
Add test checking change log with several pages. We add 10 changes to have change log on two pages.
=> GGRC-8452 Add test checking change log with several pages

src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache, src/ggrc-client/js/components/tree/tree-item-extra-info.js, src/ggrc-client/js/models/business-models/regulation.js, src/ggrc-client/js/models/business-models/standard.js
Disable Standard and Regulation.
2. Verify that the mixin is applied. 
Added ChangeableExternally mixin to Standard and Regulation models.
Updated and renamed isDirective condition so as It uses Directive type.
=> [S&R: Phase 2] GGRC-8484 Disable Standard and Regulation

test/selenium/src/lib/page/modal/search_modal.py, test/selenium/src/lib/page/modal/search_modal_elements.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_search.py
-  [x] #10483 
Test checks that a permalink of created and applied search exists in three dots menu and works correctly.
=> GGRC-8336 Add test of permalink for advanced search

test/selenium/src/lib/service/webui_facade.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user cannot add comment to Scope object
=> GGRC-8571 Confirm user cannot add comment to Scope object

test/selenium/src/lib/service/webui_service.py, test/selenium/src/lib/utils/string_utils.py, test/selenium/src/tests/test_disabled_objects.py
Confirm user can export Scope object
=> GGRC-8573 Confirm user can export Scope object

src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js, src/ggrc/views/external_mappings.py
BACKMERGE 2.25.0-Pumpkin to dev
=> BACKMERGE 2.25.0-Pumpkin to dev

test/integration/ggrc/automapper/test_automappings_rbac.py
Needs rework tests from `test_automappings_rbac.py` without custom slugs.
Run tests from `test_automappings_rbac.py` and all tests should pass.
Import from `issue_automapping_setup.csv` has been replaced by creation _Program_, _Audit_ and _Assessment_ using Factory.
=> GGRC-8318 Rework test_automappings_rbac.py

test/selenium/src/tests/test_disabled_objects.py, test/selenium/src/tests/test_unified_mapper.py
Update `test_cannot_unmap_disabled_obj`, `test_cannot_map_disabled_obj_via_unified_mapper`, `test_cannot_map_created_disabled_obj_via_um`.
Each test case should check mapping/unmapping of Risk/Control/Scope and Standard/Regulation/Scope objects.
=> GGRC-8527 Update mapping tests for disabled objects

src/ggrc-client/js/components/import-export/templates/csv-import.stache
**Should be merged to "GGRC-7200".**
Disable import for 5 objects
1. Open import page. Message should be:
"Please notice! Import for Controls, Risks, Scope objects, Requirements, Objectives, Policies, Contracts and Threats is not available in GGRC system anymore. [Go to new frontend](url) to perform import there."
Update message in 'csv-import.stache'.
=> [5Obj] GGRC-8503 Disable import for 5 objects

test/selenium/src/tests/test_rbac.py
Confirm that Assessment Delete button is not displayed for Auditor
=> GGRC-8600 Confirm that Assessment Delete button is not displayed for Auditor

src/ggrc-client/js/apps/business-objects.js, src/ggrc-client/js/components/redirects/proposable-control/proposable-control.js, src/ggrc-client/js/components/redirects/role-attr-names-provider/role-attr-names-provider.js, src/ggrc-client/js/models/business-models/contract.js, src/ggrc-client/js/models/business-models/objective.js, src/ggrc-client/js/models/business-models/policy.js, src/ggrc-client/js/models/business-models/requirement.js, src/ggrc-client/js/models/business-models/threat.js, src/ggrc-client/js/templates/contracts/info.stache, src/ggrc-client/js/templates/objectives/info.stache, src/ggrc-client/js/templates/policies/info.stache, src/ggrc-client/js/templates/requirements/info.stache, src/ggrc-client/js/templates/threats/info.stache
**Should be merged to "GGRC-7200".**
Disable editing of attributes and add redirection links to Q.
1. Open InfoPane for each model.
2. Verify that pencil icon is shown for each attribute.
3. Verify that 'Change Proposals' tab has been added.
4. All attributes except Evidences and Attachments should be redirected to Q. 
_Note_: To test links you could change line 64 in ggrcq-utils.js getUrl() function to `let url = GGRC.GGRC_Q_INTEGRATION_URL || 'example.com';`)
Add Proposable mixin to 5 models.
Update constant roleToLinkMap in role-attr-names-provider.js.
Create separate info.stache for 5 models. 
Add Change Proposal tab link on Info page.
=> [5Obj] GGRC-8498 Disable editing of attributes and add redirection links

src/ggrc-client/js/models/business-models/contract.js, src/ggrc-client/js/models/business-models/objective.js, src/ggrc-client/js/models/business-models/policy.js, src/ggrc-client/js/models/business-models/requirement.js, src/ggrc-client/js/models/business-models/threat.js, src/ggrc-client/js/templates/contracts/info.stache, src/ggrc-client/js/templates/objectives/info.stache, src/ggrc-client/js/templates/policies/info.stache, src/ggrc-client/js/templates/requirements/info.stache, src/ggrc-client/js/templates/threats/info.stache
**Should be merged to "GGRC-7200".**
Add “Created by” attribute to 5 models.
1. Open InfoPane for each model.
2. Check 'Created by' attribute in 'Hide Advanced' block.
Update `tree_view_options.attr_list` for business-models.
Update info.stache files for 5 models.
=> [5Obj] GGRC-8499 Add “Created by” attribute

src/ggrc-client/js/apps/business-objects.js, src/ggrc-client/js/components/redirects/role-attr-names-provider/role-attr-names-provider.js, src/ggrc-client/js/models/business-models/regulation.js, src/ggrc-client/js/models/business-models/standard.js, src/ggrc-client/js/plugins/tests/object-history-utils_spec.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js, src/ggrc-client/js/plugins/utils/object-history-utils.js, src/ggrc-client/js/templates/directives/info.stache
UI redirection from C to Q.
2. Verify that _pencil_ icon is shown for every attribute.
1. Added `Proposable` mixin to Standard and Regulation models.
2. Created common  info.stache template for Standard and Regulation.
3. Added Change Proposal tab link on Info page.
=> [S&R: Phase 2] GGRC-8485 UI redirection from C to Q

src/ggrc/migrations/versions/20200127_aee19c0a4205_update_send_by_default_to_not_null.py, src/ggrc/models/comment.py, src/ggrc/models/document.py, src/ggrc/models/evidence.py
Fix reviewer comments for PR #10329 
1. Run the docker setup.
2. Connect to ggrcdev and check the column description in all tables.
3. Check the values if any existing in any table.
The migration file has been modified according to the comments of the reviewer.
=> GGRC-5192 Update Commentable objects flag 'send_by_default'

src/ggrc-client/js/bootstrap/modal-ajax.js
Assessment's edit modal is scrolled up after mapping new object
1. Open any Assessment
2. Open Edit modal
3. Scroll down (MAPPED OBJECTS section should be at the top of the page)
4. Map any object
5. Review modal
Review any modal layout not to be broken. 
Call of `arrangeTopModal` and `arrangeBackgroundModals` didn't change `top` style because `headerHeight` has always been set to NaN so as `Number($header.css('padding-top')) is NaN`.  Modal used common `top: 12%` from css styles. 
Updated: removed unused `headerHeight`. For one modal, use common values from css styles. For modal number more than one, `top` value is calculated using `scrollY` value to avoid scroll jumps.
Removed call of `arrangeTopModal` on a modal hide to avoid unneeded repaint.
=> GGRC-8312 Fix issue when Assessment's edit modal is scrolled up after mapping new object

src/ggrc-client/js/components/assessment/assessment-evidence-objects/tests/assessment-evidence-objects_spec.js, src/ggrc-client/js/components/assessment/assessment-mapped-comments/tests/assessment-mapped-comments_spec.js, src/ggrc-client/js/components/assessment/assessment-mapped-objects/tests/assessment-mapped-objects_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-verify/tests/assessments-bulk-verify_spec.js, src/ggrc-client/js/components/assessment/view-models/tests/assessments-bulk-updatable-vm_spec.js, src/ggrc-client/js/components/create-document-button/tests/create-document-button_spec.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js, src/ggrc-client/js/components/related-comments/tests/related-comments_spec.js, src/ggrc-client/js/components/revision-log/tests/revision-log_spec.js
Errors and network requests should not appear during unit tests execution. 
1. Run unit tests
2. Open Karma server in the Chrome and open dev tool
3. Verify that there is no errors in console, no network request
Added stubs to avoid errors and network requests for unit tests
=> GGRC-8374 Add stubs to avoid errors and network requests for unit tests

src/ggrc-client/js/models/business-models/regulation.js, src/ggrc-client/js/models/business-models/standard.js, src/ggrc-client/js/templates/directives/info.stache
Remove 'Assessment Procedure' from Standard and Regulation.
2. Verify that 'Assessment Procedure'  is hidden.
3. Open Advanced Search for Standard or Regulation.
4. Verify that there is no 'Assessment Procedure'  in attributes list. 
1. Removed the attribute from template. 
2. Removed the attribute from the models.
=> [S&R: Phase 2] GGRC-8486 Remove attribute ‘Assessment Procedure’

src/ggrc-client/js/models/business-models/contract.js, src/ggrc-client/js/models/business-models/objective.js, src/ggrc-client/js/models/business-models/policy.js, src/ggrc-client/js/models/business-models/requirement.js, src/ggrc-client/js/models/business-models/threat.js, src/ggrc-client/js/templates/base_objects/object-review-state.stache, src/ggrc-client/js/templates/contracts/info.stache, src/ggrc-client/js/templates/objectives/info.stache, src/ggrc-client/js/templates/policies/info.stache, src/ggrc-client/js/templates/requirements/info.stache, src/ggrc-client/js/templates/threats/info.stache, src/ggrc-client/js_specs/models/object-state_spec.js
**Should be merged to "GGRC-7200".**
Update 'Object review' block for 5 objects
1. Open InfoPage for each model. 'Object review' block should not be shown.
2. Open snapshot. 'Object review' block should be shown.
Add condition to hide  'Object Review' block for snapshots if review_status attribute is not defined.
Change view of 'Object Review' block.
Remove 'Review State' from 'tree_view_options.attr_list'.
=> [5Obj] GGRC-8500 Update Object review block

test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/fast_emails_digest.py, test/selenium/src/lib/page/widget/info_widget.py, test/selenium/src/lib/service/proposal_ui_facade.py, test/selenium/src/tests/test_proposals.py
Confirm that users get emails when proposal applied
=> GGRC-8593 Confirm that users get emails when proposal created

src/ggrc-client/js/models/business-models/regulation.js, src/ggrc-client/js/models/business-models/standard.js, src/ggrc-client/js/templates/directives/info.stache
Add 'Created by' to Standard and Regulation.
2. Verify that 'Created by' is shown.
3. Open Advanced Search for Standard or Regulation.
4. Verify 'Created by' in attributes list.
Added the attribute to template. Added the attribute to the models.
=> [S&R: Phase 2] GGRC-8487 Add new attribute ‘Created by’

src/ggrc-client/js/components/related-objects/related-assessments.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/components/unmap-button/unmap-dropdown-item.js
Actually can-map, can-list are used. can-map, can-list are legacy and the alternatives in latest versions of CanJS are DefineMap, DefineList.
Open the APP and check Tree-View component on all pages (My Work page, All objects, My Assessments, Tree-View in scope objects (in scope Audit, Program, etc.))
=> GGRC-8614 Replace can-map with can-define-map for tree-widget-container component

src/ggrc-client/styles/components/simple-modal/_simple-modal.scss
More info on Related Assessment modal  is not fully visible
1. Open Control with one related assessment.
2. Click Assessment button.
3. Click Show More information on related assessment. 
4. Verify that Show More modal is fully visible. 
Set `min-height` for related assessment modal. (Approved by BA)
=> GGRC-8604 More info menu is not visible on Related Assessments popup

src/ggrc-client/js/components/import-export/templates/csv-import.stache
The following notice should be placed on the Import Objects page:
"Please notice! Import for Controls, Risks, Scope objects, Standards and Regulations is not available in GGRC system anymore. Go to new frontend to perform import there.”
1. Open Import page.
2. Verify the message. 
Updated the message on Import page.
=> [S&R: Phase 2] GGRC-8489 Disable import for Standard and Regulation

test/selenium/src/lib/entities/entities_factory.py
Add timestamp to disabled objects custom attribute external name
=> GGRC-8443 Add timestamp to disabled objects custom attribute external name

test/selenium/src/lib/page/widget/task_group_info_panel.py
`test_add_obj_to_task_group` sometimes fails supposedly due to performing actions with task group info panel before it is fully loaded.
=> GGRC-7504 Fix unstable test_add_obj_to_task_group

src/ggrc-client/js/plugins/utils/tree-view-utils.js
FE error appears when 'Update to the latest version' link is clicked on Control mapped to Asmnt in Tree view on All Objects Dashboard
1. Open All Objects.
2. Click on Assessment tab.
3. Click 'Filter SubTree' via Gear icon
4. Click 'Select All'.
5. Click 'Set Visibility' button.
6. Click 'Expand Tree' via Gear icon.
7. Click on Control.
8. Click 'Update to the latest version' link.
9. Verify that Compare modal is opened without errors
Extend SUB_TREE_FIELDS with  'revisions', 'revision_id' fields that's used to get data from BE.
=> GGRC-8619 FE error appears when 'Update to the latest version' link is clicked on Control mapped to Asmnt in Tree view on All Objects Dashboard

src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Fix long title in Object mapper.
1. Create an Audit with long title
2. Open Issues Tab
3. Click Map button
**Actual**: 'Map existing object or Create and map new object' link was moved down, out of the pop up's header area, see screenshot below.
**Expected**: 'Map existing object or Create and map new object' link is displayed in the pop up's header.
Fix css styles.
=> GGRC-8197 Header of Map Issue pop looks broken when long title for Audit is used

src/ggrc-client/js/components/mapped-counter/mapped-counter.js, src/ggrc-client/js/components/object-mapper/object-mapper.js, src/ggrc-client/js/components/tree/templates/tree-item-extra-info.stache, src/ggrc-client/js/templates/base_objects/extended-info.stache
After map any object to the Task mapping count is not updated without page refresh.
Spinner is not displayed when overdue Task info menu is opened on My Tasks.
Case 1:
1. Open My Tasks page.
2. Open info page of any Task.
3. Map any object to the Task.
4. Close Task info pane.
5. Hover over Task info icon.
6. Verify mappings count.
Case 2:
1. Open My Tasks page.
2. Open any task and add one comment and create one mapping.
3. Go back to My Tasks.
4. Hover over Task info icon.
5. Verify a spinner.
1. Set `isSpinnerVisible` to `true` on load mappings.
2. Dispatched `REFRESH_MAPPED_COUNTER` event on mappings
=> GGRC-8466/GGRC-8469 After map any object to the Task mapping count is not updated without page refresh

test/selenium/conftest.py, test/selenium/src/lib/constants/element.py, test/selenium/src/lib/constants/roles.py, test/selenium/src/lib/element/info_widget_three_bbs.py, test/selenium/src/lib/element/tree_view.py, test/selenium/src/lib/element/tree_view_item.py, test/selenium/src/lib/entities/entities_factory.py, test/selenium/src/lib/entities/entity.py, test/selenium/src/lib/page/widget/generic_widget.py, test/selenium/src/lib/service/rest/template/contract.json, test/selenium/src/lib/service/rest/template/policy.json, test/selenium/src/lib/service/rest_facade.py, test/selenium/src/lib/service/rest_service.py, test/selenium/src/lib/service/webui_service.py
Prepare framework for tests of disabled Requirements, Policies, Contracts
=> GGRC-8607 Prepare framework for tests of disabled Requirements, Policies, Contracts

test/selenium/src/lib/app_entity/workflow_entity.py, test/selenium/src/lib/page/widget/object_modal.py, test/selenium/src/lib/page/widget/workflow_tabs.py, test/selenium/src/lib/page/widget/workflow_tree_widgets.py, test/selenium/src/lib/ui/workflow_ui_facade.py, test/selenium/src/tests/test_workflow_page.py
=> GGRC-8545 Add test checking creating task group and task after workflow activation

src/ggrc/migrations/markdown/directives.py, src/ggrc/migrations/markdown/regulation.py, src/ggrc/migrations/markdown/standard.py, src/ggrc/migrations/versions/20200202_73e92a2a54df_standard_regulation_html_to_markdown.py
For external models we need to clean attributes and comments from tags.
Created converters for Standard and Regulation models. Created migration for migrate comments data into External Comments
=> [S&R: Phase 1] GGRC-8553 Migration html to markdown

src/ggrc/migrations/markdown/directives.py, src/ggrc/migrations/markdown/regulation.py, src/ggrc/migrations/markdown/standard.py, src/ggrc/migrations/versions/20200202_2676dfcbc2a1_standarts_regulations_migrate_comments_.py, src/ggrc/migrations/versions/20200202_73e92a2a54df_standard_regulation_html_to_markdown.py
As Standard and Regulation moved to external app, comments must be moved to External Comments
Created migration for data migration
=> [S&R: Phase 1] GGRC-8551 Migrate comments to external comments

src/ggrc/migrations/markdown/directives.py, src/ggrc/migrations/markdown/regulation.py, src/ggrc/migrations/markdown/standard.py, src/ggrc/migrations/versions/20200202_2676dfcbc2a1_standarts_regulations_migrate_comments_.py, src/ggrc/migrations/versions/20200202_73e92a2a54df_standard_regulation_html_to_markdown.py, src/ggrc/migrations/versions/20200202_943ddd068e02_create_external_directives_table.py, src/ggrc/migrations/versions/20200204_487d915e647e_migrate_standards_regulation_data_to_.py, src/ggrc/models/all_models.py, src/ggrc/models/external_directive.py, test/integration/ggrc/views/test_folder.py, test/unit/ggrc/models/test_slugs.py
For externalisation of Standard and Regulation models data must be move to one table. 
Created model and table ExternalDirective and external_directives. Model was extended with all needed mixins. Created migration for migrate data from directives to external_directives table.
=> [S&R: Phase 1] GGRC-8552 Migrate data to external directive

test/selenium/src/lib/constants/locator.py, test/selenium/src/lib/page/modal/update_object.py, test/selenium/src/lib/page/widget/info_panel.py, test/selenium/src/lib/service/webui_service.py
Fix unstable test test_destructive_update_snapshotable_control_to_latest_ver
=> GGRC-8428 Fix unstable test test_destructive_update_snapshotable_control_to_latest_ver

src/ggrc/templates/notifications/style.html
Incorrect notification rendering for long words
1. Create any object (Key Report)
2. Assign any person to custom role (Assignee)
3. Add a comment, (Notify Contacts) should be ON
4. Open email and look at the notification
Add word-break for notification block
=> GGRC-6758 Add word-break to fix long words rendering

src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Comments pop-up on the Info page of the [Object]: `/directives/directive=[slug]/info?comments=open`
Context page of the [Object]: `/directives/directive=[slug]/info`
Create [Object]' pop-up: `/directives?create=directive`
Change Log page of the [Object]:  `/directives/directive=[slug]/change-log`
Change proposals tab for [Object]:  `/directives/directive=[slug]/proposals`
Links for Create and Map flow: `/[object being mapped]s?create=[object being mapped]`
Links for Map(Unmap) External Directive (Standard, Regulation) to Objects:
IF [Objects] = Scope object (i.e. Access Group): `/questionnaires/[object]=[object.code]/directives?mappingStatus=in_progress,not_in_scope,reviewed&types=[standard| …
=> [S&R: Phase 2] GGRC-8490 Validate and update external urls

src/ggrc-client/js/components/revision-log/revision-page.js, src/ggrc-client/js/components/revision-log/tests/revision-page_spec.js
Assessment template change log doesn't contain LCA changes.
1. Open any Audit e.g https://ggrc-uat.googleplex.com/audits/499#!assessment
2. Create Assessment template with LCA
3. Open Assessment template and add any LCA e.g Text
4. Open created Assessment template
5. Open Assessment template change log tab
6. Expected: LCA displays on change log tab.
Added additional check for LCA on assessment template change log page.
=> GGRC-8511 LCA changes are not displayed in the Assessment template change log

src/ggrc/access_control/list.py, src/ggrc/access_control/role.py, src/ggrc/models/revision.py, test/unit/ggrc/models/test_revision.py
Once we remove the actual ACR, we lose its context (name etc.) and can't show it for Snapshots, for instance.
For instance, create one program, revision for ACL will be created, containing all the acr fields.
Override the log_json method for acl model, to save the acr as an additional field in content
=> GGRC 4361 Log json acr for acl.

src/ggrc-client/js/components/form/fields/multiselect-form-field.js
Multi-select GCA's field is not displayed on create modal when create object from Admin page
1. Login in the app
2. Open Administration page => Custom Attributes tab
3. Add Multiselect GCA field to the any object e.g Program
3. Click on Hamburger menu
4. Open Programs and click Create button
5. Expected: Multi-select dropdown GCA has been rendered.
Added component's import.
=> GGRC-7858 Multi-select field is not displayed on create modal when create object from Admin page

src/ggrc/models/mixins/clonable.py
When Assessment Template is cloned to Audit, LCA doesn't show in Change log.
1. Create or open Audit.
2. Create Assessment Template with LCA.
3. Create or open another Audit.
4. Clone Assessment Template to Audit in step 3.
5. Open Change log for cloned Assessment Template.
**Expected Result:** LCA will show in Change log for cloned Assessment Template.
After cloning CADs they don't add to session. And in step when Revision for cloned Assessment Template is created any information about CADs are not in session. Add flush to session after cloning CADs fix this issue and Revision for cloned Assessment Template is created in right way.
=> QUICK-FIX GGRC-8021 Add CAD to session when cloning object

src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.js, src/ggrc-client/js/components/custom-attributes/custom-attributes-actions.stache, src/ggrc-client/js/components/evidence-item/evidence-item.js, src/ggrc-client/js/components/related-objects/templates/related-urls.stache
1. Delete icon for Related Urls is available on Archived Audit
2. Edit Answers button on Deprecated Assessments should be hidden to avoid user confusion
2. Add any Evidence URL
3. Open 3 dots menu and click Archive Audit
4. Hover over Evidence URL
5. Expected: Trash icon and edit description icon doesn't display.
6. Open any Assessment
7. Move to in Deprecated state
8. Expected: Assessment cannot be edited.
Added additional conditions for rendering actions button for related urls. Restrict edit for assessment in deprecated state, hide `Map` and `Add tab` buttons for deprecated objects.
=> GGRC-8457 Delete icon is available on Archived Audit GGRC-8201 Hide Edit Answers button on Deprecated Assessments

src/ggrc/converters/import_helper.py, src/ggrc/gdrive/errors.py, src/ggrc/gdrive/file_actions.py, src/ggrc/models/exceptions.py, test/integration/ggrc/api_helper.py, test/integration/ggrc/converters/test_import_comprehensive.py, test/integration/ggrc/test_csvs/object_with_dollar_delimiter.csv, test/integration/ggrc/test_csvs/object_with_obscure_delimiter.csv, test/integration/ggrc/test_csvs/object_with_semicolon_delimiter.csv, test/unit/ggrc/converters/test_get_gdrive_file.py
csv file with semicolon (or any other) delimiter can't be imported.
Issue arise because in MacOs Numbers default delimiter is a semicolon.
Create csv file with semicolon delimiter.
In dev: try to import it, import must fail.
In current branch: import should be successfull.
If you try to import file with not comma or semicolon delimiter, import would fail and pop-up message appear.
Add method find_delimiter to import_helper. If the delimiter is correct (comma or semicolon), import continues. If not, exception is raised.
=> GGRC-8324 Add possibility to import csv files with semicolon delimiter

src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js
List of suggested emails appears after @ or + immediately. Expected that will happens only after first character has been typed.
1. Create an assessment on audit page.
2. Open Assessment Info panel.
3. Type in comment box: '+' and one letter.
4. Expected: Suggest's request will be processed after first letter has been typed.
Added additional condition before request.
=> GGRC-7942 The list of suggested emails appears via @ or +

src/ggrc-client/js/components/unified-mapper/mapper-results.js, src/ggrc-client/js/components/unified-mapper/templates/mapper-results.stache, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss
Column's titles are overlapped in Task Bulk Update pop-up.
1. Open My Tasks page.
2. Click on Bulk Update option via 3bb's menu.
3. Verify layout. 
`is-workflow-part` css class should be applied when It is `searchOnly` results.
=> GGRC-8640 Column's titles are overlapped in Task Bulk Update pop-up

src/ggrc-client/js/templates/dashboard/lhn.stache, src/ggrc-client/styles/modules/_side-nav.scss
Triangles are to close with objects titles in LHN menu. 
1. Open LHN.
2. Verify layout. 
Added `margin-right` for icons, removed space around titles.
=> GGRC-8441 Triangles are too close with objects titles in LHN menu

src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown.js, src/ggrc-client/js/components/people-autocomplete-dropdown/people-autocomplete-dropdown.stache, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper.js, src/ggrc-client/js/components/people-autocomplete/people-autocomplete-wrapper/people-autocomplete-wrapper_spec.js, src/ggrc-client/js/components/person-autocomplete-field/person-autocomplete-field.stache
Suggest's request doesn't contain initial email for the opened person.
Precondition: Add `INTEGRATION_SERVICE_URL=mock` to `docker-compose-override.yml`, relaunch app.
1.  Log into GGRC as Administrator
2. Go to admin dashboard.
3. Open People's tab and open edit-modal on any person.
4. Open network tab in dev tools.
5. Type smth in email field.
6. Expected: Suggest's request contain initial email.
Added  logic for saving initial email in people-autocomplete-wrapper.js.
=> GGRC-8652 Improve autosuggestion of emails and prepopulation of 'Name' for People at Administration from HR API

src/ggrc-client/js/components/dashboard-workflows/templates/dashboard-workflows.stache, src/ggrc-client/styles/components/dashboard-workflows/_dashboard-workflows.scss
My Active Workflows tab on My Work page should not be clickable.
1. Login in GGRC app
2. Open My Work page
3. Verify that My Active Workflows tab is not a link
Removed `a` element for the tab, updated the styles.
=> GGRC-8095 My Active Workflows tab on My Work page should not be clickable

src/ggrc-client/js/templates/help/filters-helper-content.stache
From the Filter Help, exclude "search phrase or". 
1. Open All Objects page.
2. Click Help icon near Advanced Search.
2. Verify the text. 
Excluded "search phrase or" from Filter Help.
=> GGRC-8359 Advanced Search doesn't display results when '~' is used in the object's title

src/ggrc-client/js/components/rich-text/rich-text.js
Application generates internal link if link was set without protocol.
1. Open any object with comment field e.g Assessment
2. Enter link name in the comment field and highlight it
3. Click Link icon
4. Set e.g "www.google.com"
5. Click Add button
6. Hover over the link in comment
7. Expected: External link should be displayed
Added link formatter for quill component.
=> GGRC-7920 Application generates internal link if link was set without protocol

src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/components/tree/tree-widget-container.js
Evidence counts are not refreshed when add to Assessment 
1. Open Assessment info page.
2. Add Evidence url.
3. Open Evidence tab.
4. Verify that added Evidence is shown. 
Revert changes from #10469
=> QUICK-FIX Refresh Evidence counts when add to Assessment

src/ggrc-client/js/components/tree/templates/tree-item-attr.stache, src/ggrc-client/js/components/tree/tests/tree-item-attr_spec.js, src/ggrc-client/js/components/tree/tree-item-attr.js, src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js, src/ggrc-client/js/plugins/utils/bulk-update-service.js, src/ggrc/fulltext/attributes.py, src/ggrc/models/assessment.py, src/ggrc/models/assessment_template.py, src/ggrc/models/audit.py, src/ggrc/models/evidence.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/reflection.py, src/ggrc/query/builder.py, test/integration/ggrc/fulltext/test_bg_indexing.py, test/integration/ggrc/fulltext/test_reindex.py, test/integration/ggrc/services/test_query/test_archived.py
Value of some fields like archived/verified on tree-view component displays as true/false.
1. Open any audit page with at least one assessment
2. Open Assessment tab
3. Set the following visible fields for Assessment: Verified, Deprecated and any GCA checkbox.
4. Review
5. Expected: Verified/Deprecated value displays as 'Yes'/'No'.
6. Use advanced search
7. Type verified = yes
8. Expected: It works.
For accepting changes for search use in dev tools console `$.post('/admin/reindex')`
Added converter for boolean values on tree-item-attr
=> GGRC-8022/GGRC-8641 Unify archived and verified values from true/false to yes/no

src/ggrc/migrations/utils/external_comments.py
Remove method for delete comments
=> QUICK-FIX remove method for delete comments

src/ggrc-client/js/components/custom-roles/templates/custom-roles-modal.stache, src/ggrc-client/js/components/people/editable-people-group-header.stache, src/ggrc-client/styles/components/people-group/_people-group.scss, src/ggrc-client/styles/modules/_modal.scss
Attributes with long titles are overlap
1. Log in in GGRC app.
2. Open LHN.
3. Open Scope => Key Reports.
4. Click Create button.
5. Review.
**Actual Result**:  Actual: Attributes with long titles are overlap.
**Expected Result**: Attributes with long titles shouldn't overlap
Show part of long title and add tooltip.
=> GGRC-8625 Attributes with long titles are overlap

src/ggrc/services/common.py, src/ggrc_workflows/models/cycle_task_group.py, src/ggrc_workflows/models/mixins.py, test/integration/ggrc/access_control/acl_propagation/test_wf_admin.py, test/integration/ggrc_workflows/test_api_calls.py, test/unit/ggrc_workflows/models/test_wf_custom_restrictions.py
Global Admin can update Cycle Task Group via API PUT request 
1. Sign in as Global Admin 
2. Create Workflow object with Cycle 
3. Send API PUT request with random Cycle Task Group title to change them
Was result: 200 code of response and title was changed 
New result: 403 code of response and title wasn't changed
Created custom restriction class, which can be applied to the model. In the model  itself, there is a need to override CustomRestriction fields, which need to be applied to current class. 
Custom restriction works and depends on methods itercation with the model and the fields which were sent.
=> GGRC-8289 Custom restriction rule added for the cycle task group.

src/ggrc/access_control/list.py, src/ggrc/access_control/role.py, src/ggrc/models/revision.py, test/unit/ggrc/models/test_revision.py
This reverts commit af0b753b98f68571a68b2aeb6a7f500d12dfcef1.
=> GGRC-4361 revert

src/ggrc-client/js/components/unified-mapper/templates/mapper-results-items-header.stache, src/ggrc-client/js/models/business-models/policy.js, src/ggrc-client/js/templates/assessments/assignable-extended-info.stache, src/ggrc-client/styles/_common.scss, src/ggrc-client/styles/components/template-field/_template-field.scss, src/ggrc-client/styles/components/unified-mapper/_unified-mapper.scss, src/ggrc-client/styles/modules/_import-export.scss, src/ggrc-client/styles/modules/_object-header.scss
Checkboxes are not aligned with the text on the Export page
Last Updated Date is not aligned properly in Unified Mapper
Columns are duplicated on Policies objects tab
Link in Assessments details popup on LHN is broken
Objects and Attributes titles without spaces in long titles are displayed out of the page (popup)
Some items in 3 dots menu are underline on hover
1. Login GGRC
2. Go to Export page
3. Review
4. Expected: Checkboxes is align
1. Open an Audit
2. Add any Snapshot via Unified Mapper modal pop-up
3. In Unified Mapper select more than 5 filters
4. Check the alignment of selected sorting attribute title.
5. Expected: It is align.
1. Open All Objects page
2. Select Policies tab
3. Set visible fields for Policy table to display Kind/Type column
4. Remember Policy object with empty …
=> GGRC-8092/GGRC-8269/GGRC-8570/GGRC-7933/GGRC-8008/GGRC-7830 Styles improvements

bin/containers
`bin/containers run` recreates containers which causes need to reinstall npm packages
Adding `bin/containers start` without --force-recreate, can be used after `bin/containers stop` to get to the same state.
=> QUICK-FIX Add bin/containers start

src/ggrc/services/suggest.py, test/integration/ggrc/services/test_suggest.py
Points to improve:
1. Email field on the New Person pop-up should suggest only those emails that are not used in GGRC yet.
2. Email field on the Edit Person pop-up should suggest only those emails that are not used in GGRC yet PLUS the initial email for the opened person.
On `ggrc-test` was deployed version `serada-ggrc` with changes from this PR.
Added function `_filter_emails` that filter emails from HR API response.
=> GGRC-7680 Improve autosuggestion of emails and prepopulation of 'Name' for People at Administration from HR API

docs/source/contributing/css_and_html.rst
Contribution guidelines in css_and_html.rst were unfinished. Extended the reStructuredText below CSS with HTML guidelines. Retargeted proposed changes to the dev branch according to #10457 
Documentation - formatting and content check.
Wrote the documentation based on [Google HTML Style Rules](https://google.github.io/styleguide/htmlcssguide.html#HTML_Style_Rules)
=> Added contributing guidelines to css_and_html.rst

src/ggrc-client/js/components/action-toolbar-control/action-toolbar-control.js, src/ggrc-client/js/components/assessment/assessment-mapped-comments/assessment-mapped-comments.js, src/ggrc-client/js/components/assessment/assessment-mapped-comments/tests/assessment-mapped-comments_spec.js, src/ggrc-client/js/components/comment/comment-add-button.js, src/ggrc-client/js/components/comment/comment-add-form.js, src/ggrc-client/js/components/comment/comment-data-provider.js, src/ggrc-client/js/components/comment/comments-paging.js, src/ggrc-client/js/components/comment/mapped-comments.js, src/ggrc-client/js/components/comment/tests/comment-data-provider_spec.js, src/ggrc-client/js/components/evidence-item/evidence-item.js, src/ggrc-client/js/components/evidence-item/tests/evidence-item__spec.js, src/ggrc-client/js/components/folder-attachments-list/folder-attachments-list.js, src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js, src/ggrc-client/js/components/gdrive/ggrc-gdrive-picker-launcher.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-picker-launcher_spec.js, src/ggrc-client/js/components/object-list-item/comment-list-item.js, src/ggrc-client/js/components/object-list-item/document-object-list-item.js, src/ggrc-client/js/components/object-list-item/editable-document-object-list-item.js, src/ggrc-client/js/components/object-list-item/tests/comment-list-item_spec.js, src/ggrc-client/js/components/object-list-item/tests/document-object-list-item_spec.js, src/ggrc-client/js/components/related-objects/related-documents.js, src/ggrc-client/js/components/related-objects/related-urls.js, src/ggrc-client/js/components/related-objects/tests/related-documents_spec.js, src/ggrc-client/js/components/related-objects/tests/related-urls_spec.js
Actually can-map, can-list are used. can-map, can-list are legacy and the alternatives in latest versions of CanJS are DefineMap, DefineList.
Need to check:
- comments (comments list, add comments function)
- URLs (add, remove, urls list)
- Files and Folders (add, change, remove, files list, folder)
=> GGRC-8642 Replace can-map with can-define-map for COMMENTS \ URLS \ FILES

src/ggrc-client/js/templates/custom_attribute_definitions/modal-content.stache
Mandatory checkbox blinking.
`{{^is(instance.definition_type, "assessment")}}` passes when definition_type not defined
Please refer to ticket steps.
Add additional `{{#if }}`
=> GGRC-8603 Validate definition_type in cad template

src/ggrc-client/styles/components/people-group/_people-group.scss
Font size is broken People group count on Snapshot comparer page. 
Due to changes in #10693 
1. Open any Snapshot.
2. Click Get the latest version button. 
3. Verify font size for people groups.
Added `font-size` property for `people-group__count` class
=> QUICK-FIX Fix font size for people group count

src/ggrc/models/access_group.py, src/ggrc/models/account_balance.py, src/ggrc/models/data_asset.py, src/ggrc/models/facility.py, src/ggrc/models/key_report.py, src/ggrc/models/market.py, src/ggrc/models/metric.py, src/ggrc/models/org_group.py, src/ggrc/models/product.py, src/ggrc/models/product_group.py, src/ggrc/models/project.py, src/ggrc/models/system.py, src/ggrc/models/technology_environment.py, src/ggrc/models/vendor.py, test/integration/external_app/test_ext_scope_objects.py
Replace "roleable" with "roleable-synchronizable" for scope objects
Run integration test
Send create/put request for scope objects from sync service with acl and validate that records were created
Replease "roleable" mixin for "roleable-synchrnozable" for scope objects
=> GGRC-8759 Replace "roleable" with "roleable-synchronizable" for scope objects

src/ggrc-client/js/components/rich-text/rich-text.js
Cursor will be lost after cutting text from rich-text component via command+x.
1. Open any object with Rich text field
2. Enter any text in the Rich text field
3. Select all text and cut it e.g using command+X buttons
Expected: Cursor is presented in the field and user is able to continue enter text without additional click in the field
Custom handler for 'text-change' event affect quilljs code. Added extra condition before setting content to editor. It helps avoid saving empty value in editor that leads to missing selection range.
=> GGRC-7896 Cursor is disappeared if cut text from the Rich text field

src/ggrc/models/revision.py, src/ggrc/services/common.py, test/integration/ggrc/services/test_revision_history.py, test/unit/ggrc/models/test_revision.py
For each Revision instance on get revisions, content property is called more than once (2 times for "created", 3 times for "modified")
1. Not available on non-local Add a debug output to content property on Revision.
2. Create a Control.
3. Edit any field on it.
4. Open its Change Log tab.
In terminal you will see call count.
Check if content already in flask.g before building. Delete it from flask after request.
=> GGRC-4229: Revision.content property is accessed multiple times for same objects on GET /api/revisions

src/ggrc-client/js/components/assessment/assessment-local-ca.js, src/ggrc-client/js/components/assessment/info-pane/assessment-info-pane.js, src/ggrc-client/js/components/global-custom-attributes/global-custom-attributes.js
Floating message that connection was lost is not appeared after edit LCA, from the user perspective everything looks like that all changes where saved. Error is appeared only inConsole.
1. Open any Assessment with LCA.
2. Turn off internet connection in Chrome Dev tools.
3. Edit any LCA.
4. Verify that the message is shown.
5. Edit any Custom Attribute .
6. Verify that the message is shown.
Added `connectionLostNotifier` for LCA, Global Custom attributes, Assessment Custom attributes.
=> GGRC-8446 Floating message that connection was lost is not appeared when edit LCA in Assessments

src/ggrc-client/js/components/assessment/templates/assessment-people.stache, src/ggrc-client/js/components/custom-roles/custom-roles-wrapper.js, src/ggrc-client/js/components/inner-nav/audit-inner-nav.js, src/ggrc-client/js/components/proposal/apply-decline-proposal.js, src/ggrc-client/js/entrypoints/dashboard/index.js, src/ggrc-client/js/plugins/utils/widgets-utils.js, src/ggrc-client/js/templates/audits/info.stache, src/ggrc-client/js/templates/base_objects/contacts.stache, src/ggrc-client/js/templates/issues/info.stache, src/ggrc-client/js/templates/programs/info.stache
People tab's number is not updated automatically when a new person is added to an object
1. Open GGRC
2. Create any object, e.g. Program
3. Add another user to any custom role
Expected: People tab's number updated.
Added extra wrapper for custom roles where it needed for updating people tab's counts.
=> GGRC-8626 People tab's number is not updated automatically when a new person is added to an object

src/ggrc-client/js/components/add-tab-button/add-tab-button.js, src/ggrc-client/js/components/add-tab-button/add-tab-button.stache, src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.js, src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone.stache, src/ggrc-client/js/components/assessment-template-clone/assessment-template-clone_spec.js, src/ggrc-client/js/components/assessment/assessment-generator-button.js, src/ggrc-client/js/components/assessment/templates/assessment-generator-button.stache, src/ggrc-client/js/components/bulk-update-button/bulk-update-button.js, src/ggrc-client/js/components/bulk-update-button/bulk-update-button.stache, src/ggrc-client/js/components/bulk-update-button/tests/bulk-update-button_spec.js, src/ggrc-client/js/components/gdrive/ggrc-gdrive-folder-picker.js, src/ggrc-client/js/components/gdrive/templates/ggrc-gdrive-folder-picker.stache, src/ggrc-client/js/components/gdrive/tests/ggrc-gdrive-folder-picker_spec.js, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.js, src/ggrc-client/js/components/object-bulk-update/object-bulk-update.stache, src/ggrc-client/js/components/object-bulk-update/tests/object-bulk-update_spec.js, src/ggrc-client/js/components/object-generator/object-generator.js, src/ggrc-client/js/components/object-generator/object-generator.stache, src/ggrc-client/js/components/object-generator/tests/object-generator_spec.js, src/ggrc-client/js/components/object-mapper/object-mapper.js, src/ggrc-client/js/components/object-mapper/object-mapper.stache, src/ggrc-client/js/components/object-mapper/tests/object-mapper_spec.js, src/ggrc-client/js/components/tests/unarchive-link_spec.js, src/ggrc-client/js/components/unarchive-link.js
Unobvious event handling in some places.
1. Bulk-update btn && object-bulk-update
2. Open My tasks tab
3. Click on three-dots menu and click 'Bulk update'
4. Expected: Bulk update modal opened
5. Choose tasks and click update
6. Expected: Update btn works
5. Object mapper
6. Try to map any object to another object.
7. Expected: Close modal btn and map btn works, mapping works
8. Object generator
9. Click 'Autogenerate' btn on audit summary page
10. Try to generate assessment/close modal.
11. Expected: Close modal btn, Generate assessment btn, Autogenerate btn works
12. Click 'Create template' btn on audit summary page
13. Try to clone template
14. Expected: It works
15. ggrc-gdrive-folder-picker
16. Click 'Assign folder' and add folder on object where it possible
17. Remove folder
18. …
=> GGRC-6365 Replace class listeners with canjs events

src/ggrc-client/js/models/custom-attributes/custom-attribute-definition.js, src/ggrc-client/js/models/custom-roles/access-control-role.js, src/ggrc-client/js/plugins/utils/acl-utils.js
Newly created GCR's are appeared only after page refresh.
1. Open Administration page.
2. Open Custom Attributes Tab.
3. Click e.g on Programs.
4. Click + icon and any Attribute title and select any attribute type e.g Text.
5. Click Save & Close button.
6. Open LHN =>.
7. Click Create button.
**Actual Result**: Newly created role is not displayed in the Create new program modal.
**Expected result**: Newly created role is displayed in the Create new program modal.
Add new GCR to global variable after creating.
=> GGRC-8763 Newly created GCR's are appeared only after page refresh

src/ggrc-client/js/plugins/tests/ggrcq-utils_spec.js, src/ggrc-client/js/plugins/utils/ggrcq-utils.js
Wrong URL for scoping objects in "Open in New Front End" link.
Please refer to ticket steps.
Update `getInfoUrl` method in case of scoping object
=> GGRC-8795 Fix Info page for scoping objects

src/ggrc/views/__init__.py, src/ggrc/views/assessment_externalization.py, test/integration/ggrc/views/test_assessment_externalization.py
Implement proof of concept.
Custom assessment copy mechanism.
=> GGRC-8671: [POC] Assessment externalization via custom copy mechanism

src/ggrc-client/js/templates/processes/info.stache, src/ggrc-client/js/templates/products/info.stache, src/ggrc-client/js/templates/systems/info.stache
`info.stache` was not updated for Process, Product and System. Thus they didn't have `Created By` field on UI.
Please check ticket description
Update `info.stache`.
=> GGRC-8811 Add Created By to Process, Product, System

src/ggrc/views/bulk_operations/utils.py, test/integration/ggrc/bulk_operations/test_matrix.py
Actual:
One assessment + many cads = Many assessments row in search response
Expected:
One assessment + many cads = One assessment row in search response
Updated `_prepare_attributes_and_assessments` with `assessments = collections.OrderedDict()` to exclude duplicating assessments
=> [Matrix view] QUICK-FIX many cad duplicate asmts

src/ggrc/migrations/utils/acr_propagation_constants_scope_other_contacts.py, src/ggrc/migrations/versions/20200405_381a58793fba_other_contacts_for_scope_objects.py
Add Other Contacts for Scope objects
Check Other Contacts on Scope objects UI
Add Other Contacts from external service 
Add migration for Other Contact
Update ACR/ACL
=> GGRC-8792 - add other contacts for Scope objects

src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js, src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache, src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js, src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.stache, src/ggrc-client/js/components/tree/templates/tree-actions.stache, src/ggrc-client/js/components/tree/tree-actions.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/plugins/utils/bulk-update-service.js, src/ggrc-client/styles/components/tree/_tree-view.scss
1. Need to update <assessment-tree-actions> component in order to show old “Bulk Complete” button 
2. “Bulk Complete” should be renamed to “Bulk Completion”
3. Add tooltip for “Bulk Completion” button
1. Open My Assessments/Assessments Tab on Audit
2. Verify Bulk Completion button
1. Updated Query request.
2. Moved `setShowBulkCompletion` to one place.
3. Renamed and styled the button.
=> [Matrix view] GGRC-8739 Create “Bulk completion” buttons on Audit & My assessments page

src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/events/event-types.js, src/ggrc-client/js/plugins/utils/bulk-update-service.js
Make additional request for Bulk completion when filter changed.
2. Set any filter (Advanced Search, State Filter, Input filter).
3. Verify that Bulk Completion button is disabled/enabled based on bulk and current filter. 
Used `currentFilter` to make request for Bulk Completion count.
=> [Matrix view] GGRC-8740 Enable/Disable “Bulk completion” buttons

src/ggrc/migrations/versions/20191207_55984900c508_add_ext_mappings_records.py
Sync of Controls on create/update actions is inoperable. The reason is that `external_mappings` table contains inconsistent data (some records in `external_mappings` table point to the wrong records in `custom_attribute_definitions` one) which causes synch errors.
E.g. the following SQL could be used:
```sql
SELECT ecad.definition_type AS "ecad_definition_type",
cad.definition_type AS "cad_definition_type"
FROM external_custom_attribute_definitions AS ecad
JOIN external_mappings AS em
ON ecad.external_id = em.external_id
JOIN custom_attribute_definitions AS cad
ON em.object_id = cad.id
```
If values in `ecad_definition_type` column match ones in `cad_definition_type` column, it means that the data in `external_mappings` is consistent.
The provided SQL, **if executed on GGRC-UAT before the …
=> GGRCIE-8718: Fix inoperable control sync on create/update actions

test/integration/ggrc/services/test_query/test_builder.py, test/unit/ggrc/query/test_builder.py
Check test coverage and write appropriate tests if needed.
Test coverage:
before: 67%
after: 84%
=> [Matrix view] GGRC-8717 Cover Query API methods

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache, src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js, src/ggrc-client/js/components/tree/templates/tree-widget-container.stache, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/events/event-types.js, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/bulk-complete/_bulk-complete.scss
1. Introduce “bulkCompleteModeEnabled” field for tree-widget-container
2. Create <assessments-bulk-complete-container> component
3. Place “Exit bulk completion”, “Save answers”, “Complete” buttons (without functionality)
4. Show the message “Below are listed ...”
2. Click Bulk Completion button. 
3. Verify that bulk complete mode is opened with the elements described above. 
Introduced new component `assessments-bulk-complete-container`.  Added `enableBulkCompleteMode` event to open bulk complete mode.
=> [Matrix view] GGRC-8741 Prepare basic layout for “Bulk Complete” mode

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/views/bulk_operations/bulk_operations.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py, test/integration/ggrc/bulk_operations/test_csvbuilder.py, test/integration/ggrc/smoke_tests/test_bulk_notification.py
- Parse request data that should be updated.
- Update all assessments LCAs using background task.
- Send notification after background job finishes.
- Implement integration tests for Save CADs functionality.
_NOTE: pylint duplicates will be fixed in the next epic ticket_
=> GGRC-8718: [BE] Save CADs functionality (Matrix View)

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/views/bulk_operations/bulk_operations.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py, test/integration/ggrc/bulk_operations/test_csvbuilder.py
- Separate save and complete functionality. Call Save task before Complete.
- Filter assessments that should be completed and should be only save logically - (assessment_ids request attribute will contains list of assessments that should be saved).
- Update data for notifications accordingly.
- Check tests coverage and write appropriate tests if needed.
=> GGRC-8719: [BE] Complete Assessments functionality (Matrix View)

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/converters/base.py, src/ggrc/converters/base_row.py, src/ggrc/notifications/bulk_notifications.py, src/ggrc/settings/default.py, src/ggrc/templates/notifications/bulk_save.html, src/ggrc/templates/notifications/bulk_style.html, src/ggrc/templates/notifications/bulk_verify.html, src/ggrc/views/bulk_operations/bulk_operations.py, src/ggrc/views/converters.py, test/integration/ggrc/smoke_tests/test_bulk_notification.py
we should create new templates with the new styles and texts. We will make this rework based on the templates/notifications/bulk_complete.html template. Here we should also separate the jinja html view file and css styles to the separate files.
=> GGRC-8720: [BE] Update notifications according requirements (Matrix View)

src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.js, src/ggrc-client/js/components/assessment/assessment-tree-actions/assessment-tree-actions.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache, src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js, src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.stache, src/ggrc-client/js/components/tree/templates/tree-widget-container.stache, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/js/events/event-types.js, src/ggrc-client/js/plugins/utils/bulk-update-service.js, src/ggrc-client/js/plugins/utils/current-page-utils.js, src/ggrc-client/styles/components/bulk-complete/_bulk-complete.scss
1. Change the view from usual tree view to “Bulk complete” mode using “bulkCompleteModeEnabled” field
2. Build the request payload to the server in order to get all of the assessments (based on Query API + additional params) (in the scope of <assessments-bulk-complete-container>)
3. Send built filter to the server
4. During the loading of the response, we should show spinner.
Case 1:
2. Click Bulk Completion button.
3. Verify that `search` request was sent to BE, response contains list of assessments and attributes. 
Case 2:
2. Set any filter (State filter, Advanced search).
3. Click Bulk Completion button.
4. Verify that `search` …
=> [Matrix view] GGRC-8742 Enable Bulk Complete mode

src/ggrc/models/system.py
QUICK-FIX remove workflow state from System/Process
=> QUICK-FIX remove workflow state from System/Process

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/views/bulk_operations/utils.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py, test/integration/ggrc/bulk_operations/test_csvbuilder.py, test/integration/ggrc/bulk_operations/test_matrix.py, test/integration/ggrc/services/test_query/test_builder.py
UI need to receive assessment slug data for the bulk complete operations
=> [Matrix view] QUICK-FIX Matrix view search

src/ggrc-client/js/templates/base_objects/info.stache, src/ggrc-client/js/templates/processes/info.stache, src/ggrc-client/js/templates/products/info.stache, src/ggrc-client/js/templates/systems/info.stache
Edit icon doesn't appear for Kind/Type and Effective Date attribute for Scope objects.
1. Open info pane for any Scope object
2. Verify edit icon for Kind/Type and Effective Date
Updated info.stache for Scope objects
=> GGRC-8872 Edit icon doesn't appear for Kind/Type and Effective Date attributes

src/ggrc-client/js/plugins/utils/tree-view-utils.js
"Open in new frontend" link on expanded tree redirects to wrong destination.
1. Open All Objects page
2. Select any Scope object e.g Products
3. Hover over any product that has mapped scope objects => hover over gear icon with triangle
4. Click "Filter Sub tree" option
5. Select all Scope objects and click Set Visibility button
6. Hover over gear icon with triangle on the same object and click Expand tree option
7. Hover over gear icon on any mapped scope object e.g Product
8. Verify "Open Product in new frontend"  link 
Extend SUB_TREE_FIELDS to load 'slug' attribute from BE and generate correct link.
=> GGRC-8864 "Open in new frontend" link on expanded tree redirects to wrong destination

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/views/bulk_operations/bulk_operations.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py, test/unit/ggrc/query/test_builder.py
=> [Matrix view] QUICK-FIX All asmts completed while request for one

src/ggrc/models/hooks/acl/propagation.py, test/integration/ggrc/models/hooks/acl/test_propagation.py
`admin/propagate_acl` job fail due to exceeded soft memory limit on GGRC-QA instance.
_Local test:_
1. For testing use DB dump from GGRC-QA.
2. In Advanced setting Docker set "Memory" to 2 Gb.
3. Run `$.post('/admin/propagate_acl')`
**Expected result:** job will finish successfully.
Also was deployed custom version on GGRC-TEST instance with name serada-ggrc.
Issue was in file `ggrc/models/hooks/acl/propagation.py` in function `_propagate`.
In the request for receiving `user_ids` was passed `child_ids` list. `child_ids` list can have length more than 10 thousand. What led to exceeded soft memory limit.
`_get_child_ids` function was refactored and returns now list instead SQLAlchemy object.
`_propagate` function was refactored too. `child_ids` was splitted into chunks and the `user_ids` …
=> GGRC-8785 GGRC-QA acl propagation failed

src/ggrc-client/js/templates/processes/info.stache, src/ggrc-client/js/templates/systems/info.stache
Edit icon (pencil) should be appeared for Network Zone attribute on Systems and Processes
1. Open Systems or Processes object
2. Hover over Network Zone attribute
3. Expected: Edit icon (pencil) is appeared
"Network Zone" attribute was wrapped in external-attribute component
=> GGRC-8883 Edit icon doesn't appear for Network Zone attribute on Systems and Processes

src/ggrc/bulk_operations/csvbuilder.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py
=> [Matrix view] QUICK-FIX Fix lower case for attribute types

src/ggrc-client/js/components/revision-log/revision-page.js
Logs of 'Network Zone' attr in System/Process & 'Kind/Type' attr in Product are not displayed in Change Log
1. Open System and Process objects on GGRCQ
2. Select an option in 'Network Zone' attr in System/Process 
3. Open those System and Process objects on GGRC
4. Click on the Change Log tab
4. Expected: 'Network Zone' log should be displayed in the Change Log tab
5. Open Product object on GGRCQ
6. Select an option in 'Kind/Type' attr in Product
7. Open a Product object on GGRС
8. Click on the Change Log tab
9. Expected: 'Kind/Type' log should be displayed in the Change Log tab
Changed compare function. Added separate check for this fields.
=> GGRC-8884 Logs of 'Network Zone' attr in System/Process & 'Kind/Type' attr in Product are not displayed in Change Log

src/ggrc-client/js/components/assessment/assessment-tree-actions/tests/assessment-tree-actions_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js, src/ggrc-client/js/components/tree/tests/tree-widget-container_spec.js, src/ggrc-client/js/plugins/tests/utils/bulk-update-service_spec.js
Write unit tests for “Bulk Completion” button functionality
=> [Matrix view] GGRC-8756 Write unit tests for “Bulk Completion” button functionality

src/ggrc/views/bulk_operations/utils.py, test/integration/ggrc/bulk_operations/test_matrix.py
1. /cavs/search should returns assessments in the same order as QueryHelper returns data
2. Map:Person LCAs should return the list of user ids but not only the one user id
=> [Matrix view] QUICK-FIX Add order by ability and many Map:Person attributes values

src/ggrc-client/js/components/dropdown/dropdown-component.js, src/ggrc-client/js/components/dropdown/templates/dropdown-component.stache, src/ggrc-client/js/components/dropdown/tests/dropdown-component_spec.js, src/ggrc-client/js/components/form/fields/dropdown-form-field.js, src/ggrc-client/js/components/form/fields/dropdown-form-field.stache, src/ggrc-client/js/components/inline/readonly-inline-content.stache, test/selenium/src/lib/element/page_elements.py, test/selenium/src/lib/utils/string_utils.py
Long GCA dropdown value is not fully displayed. 
Expected result: show a tooltip
1. Open any Object with Dropdown.
2. Hover any Dropdown CA. 
3. Verify that tooltip is shown.
Add tooltip for `dropdown-component` component
=> GGRC-8866 Long GCA dropdown value is not fully displayed

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-header/assessments-bulk-complete-table-header.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-header/assessments-bulk-complete-table-header.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/tests/assessments-bulk-complete-table_spec.js, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
**Should be merged to "matrix-view".**
Create the layout for assessments grid
2. Click "Bulk Completion" button.
3. Table should be shown.
- assessment title is link 
- mandatory headers with asterisk
- status assessment column like in tree-view
- columns should have fixed width
- horizontal scroll should appear if table doesn't fit the screen width
1. Prepare base structure of assessment fields (in order to be able to render assessment grid)
2. Prepare the layout which will render the list of assessments (scrollable section) with header
3. Prepare the layout for Title (should be a link to an appropriate assessment) and Status columns (without popover)
4. Header of the grid (+ asterisk …
=> [Matrix view] GGRC-8743/8760 Create the layout for assessments grid Part1

src/ggrc-client/js/components/page-header/migrate-banner.js, src/ggrc/migrations/versions/20200507_b8a0d301eb50_create_banner_table.py, src/ggrc/models/all_models.py, src/ggrc/models/banner.py, src/ggrc/templates/layouts/dashboard.haml, src/ggrc/views/__init__.py
Have a mechanism to alert the end-users of old C/Q of the status of migration, and let them know of critical dates coming, or resources they can go to if they have questions.
1. Launch GGRC
2. Open any object's page
3. Expected: Migrate banner shown on the top of the application for every page.
4. Open dev tools
5. Type in console (You must logged as admin)
```
$.ajax({
method: "POST",
contentType: "application/json",
url: "/admin/banner",
data: JSON.stringify({message: "any text", bg_color: "cccccc", font_color: "000000"})
})
```
6. Reload page
7. Expected: Banner's text, font color and background color changed and shown correctly
1. Create database table "banner"
2. Add migrate-banner component to page-header component
=> GGRC-8924/GGRC-8921 Migrate Banner

src/ggrc/converters/column_handlers.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/boolean.py, src/ggrc/migrations/versions/20200507_5b4003f3f6b0_add_migration_attribute.py, src/ggrc/migrations/versions/20200507_b8a0d301eb50_create_banner_table.py, src/ggrc/models/all_models.py, src/ggrc/models/banner.py, src/ggrc/models/directive.py, src/ggrc/models/mixins/__init__.py, src/ggrc/models/objective.py, src/ggrc/models/requirement.py, src/ggrc/models/revision.py, src/ggrc/models/threat.py, src/ggrc/templates/layouts/dashboard.haml, src/ggrc/views/__init__.py, test/integration/ggrc/models/mixins/test_with_migration_flag.py
=> GGRC-8923 Migrate flag

src/ggrc-client/js/components/general-page-header/general-page-header.js, src/ggrc-client/js/components/migrate-checkbox/migrate-checkbox.js, src/ggrc-client/js/components/migrate-checkbox/migrate-checkbox.stache, src/ggrc-client/js/components/migrate-checkbox/tests/migrate-checkbox_spec.js, src/ggrc-client/js/components/revision-log/revision-page.js, src/ggrc-client/js/templates/base_objects/info-pane-utility.stache, src/ggrc-client/js/templates/contracts/modal_content.stache, src/ggrc-client/js/templates/data_assets/modal_content.stache, src/ggrc-client/js/templates/facilities/modal_content.stache, src/ggrc-client/js/templates/markets/modal_content.stache, src/ggrc-client/js/templates/metrics/modal_content.stache, src/ggrc-client/js/templates/objectives/modal_content.stache, src/ggrc-client/js/templates/org_groups/modal_content.stache, src/ggrc-client/js/templates/policies/modal_content.stache, src/ggrc-client/js/templates/processes/modal_content.stache, src/ggrc-client/js/templates/product_groups/modal_content.stache, src/ggrc-client/js/templates/products/modal_content.stache, src/ggrc-client/js/templates/projects/modal_content.stache, src/ggrc-client/js/templates/regulations/modal_content.stache, src/ggrc-client/js/templates/requirements/modal_content.stache, src/ggrc-client/js/templates/standards/modal_content.stache, src/ggrc-client/js/templates/systems/modal_content.stache, src/ggrc-client/js/templates/technology_environments/modal_content.stache, src/ggrc-client/js/templates/threats/modal_content.stache, src/ggrc-client/js/templates/vendors/modal_content.stache, src/ggrc-client/styles/_components.scss, src/ggrc-client/styles/components/migrate-checkbox/_migrate-checkbox.scss
Enable the end-users to positively identify through the UI which objects should be in-scope of this migration.
Migrate checkbox must be created for the following objects:
Standard
Regulations
Requirements
Objectives
Products
Systems
Key Reports
Metrics
Technology Environments
Product Groups
Processes
Contracts
Data Assets
Facilities
Markets
Org Groups
Policies
Projects
Threats
Vendors
1. Launch GGRC
2. Open info-pin for any object from list in issue description
3. Expected: Migrate checkbox shown.
4. Check/uncheck migrate checkbox.
5. Expected: It works.
6. Click on 3bbs menu.
7. Click on Edit button
8. Change state of migrate checkbox and save changes
9. Expected: It works.
10. Open change log tab and review
12. Expected: Changes of …
=> GGRC-8918/GGRC-8920/GGRC-8922 Migrate Flag

src/ggrc-client/js/components/page-header/page-header.js, src/ggrc-client/js/components/page-header/page-header.stache, src/ggrc-client/styles/layout/_content.scss, src/ggrc-client/styles/layout/_header.scss, src/ggrc-client/styles/modules/_header-content.scss
Added missed code after rebase
=> QUICK-FIX Migrate Banner

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/assessments-bulk-complete-popover-content.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/assessments-bulk-complete-popover.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/assessments-bulk-complete-popover-content.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/assessments-bulk-complete-popover.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/popover-related-objects-content.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/popover-related-objects-header.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/tests/assessment-bulk-complete-popover-content_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/tests/assessment-bulk-complete-popover_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache, src/ggrc-client/styles/components/popover-component/_popover-component.scss
1. Place the "!” icon near each title.
2. Send request in order to get all of the objects based on assessment type.
3. Render the list of loaded objects.
4. Show the text in case if there are no mapped snapshots.
5. Cache loaded snapshots in order to not make request once again.
2. Click Bulk Completion button.
3. Verify that "!” icon is shown near an assessment title
4. Hover on  the icon. 
5.Verify that popover with related snapshots is shown.
Introduced new components to show popover.
=> [Matrix view] GGRC-8749 Show popover with snapshots for each assessment

src/ggrc/views/bulk_operations/utils.py, test/integration/ggrc/bulk_operations/test_matrix.py
Matrix Table requires the info about Precondtion CADs info (Evidences and Comments) related to assessments
Request /cavs/search endpoint
- Reused evidences property to get all the evidences related to asmt
- Reused precondition_failed method to get info about missing mandatory info of LCA
=> [BE] Update query /cavs/search/ with Evidence/Comment precondition info

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-header/assessments-bulk-complete-table-header.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/tests/assessments-bulk-complete-table-row_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/tests/assessments-bulk-complete-table_spec.js, src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
**Should be merged to "matrix-view".**
Prepare layout for attributes
2. Click "Bulk Completion" button.
3. Table should be shown.
- "Not applicable" should be shown in case if attribute is not relevant to the assessment
- components corresponding to the attributes types (input, date, person, checkbox, rich-text, dropdown, multiselect) should be shown in cells
- validation icon should be shown
- validation should work (except for dropdown attributes with required info)
-  "Add info" / "Edit info" buttons should be shown
1. Setup layout for each type of the LCAs (show predefined value or an empty)
2. Show “Not applicable” label in case if attribute is not relevant to the assessment
3. …
=> [Matrix view] GGRC-8744/8761 Prepare layout for attributes Part 1

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/tests/assessments-bulk-complete-table-row_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/tests/assessments-bulk-complete-table_spec.js, src/ggrc-client/js/components/required-info-modal/required-info-modal.js, src/ggrc-client/js/components/required-info-modal/required-info-modal.stache, src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
**Should be merged to "matrix-view".**
Set up logic related to validation
2. Click "Bulk Completion" button.
3. Table should be shown.
- validation should work as on Assessment Info Page
- row should be colored blue when each attribute in this row is valid and tick should be shown near assessment title
- 'Save answers' button should be enabled when there is at least one not saved change in the table
- 'Complete(n)' button should be enabled when all attributes in at least one row are valid, n - number of valid rows
Add Required Info modal and update validation logic.
=> [Matrix view] GGRC-8745 Set up logic related to validation

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-completion-button/assessments-bulk-completion-button.js, src/ggrc-client/js/components/tree/tree-widget-container.js, src/ggrc-client/styles/modules/_modal.scss
1. Show warning in case if there are some unsaved answers (using windows.onbeforeunload)
2. Refresh tree-widget-container to exit Bulk completion mode
Case 1:
1. Click Bulk Completion button to open Bulk Completion mode.
2. Click Exit bulk completion button.
3. Verify that Bulk completion mode was hidden.
Case 2:
1. Click Bulk Completion button to open Bulk Completion mode.
2. Modify any answer. 
3. Click Exit bulk completion button.
4. Verify that Confirmation modal is shown
Case 3:
1. Click Bulk Completion button to open Bulk Completion mode.
2. Modify any answer. 
3. Click All Objects link.
4. Verify that Chrome popup is shown.
Added handler for Exit bulk completion button. Added `onbeforeunload` listener for case when user tries …
=> [Matrix view] GGRC-8748 Process “Exit bulk completion”

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/assessments-bulk-complete-table-row.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-table/assessments-bulk-complete-table-row/tests/assessments-bulk-complete-table-row_spec.js
Fix required comment validation
Preparations:
Assessment with dropdown LCA is needed. On Assessment Info page set value which needed URL + comment. Add comment. Now only URL is needed.
1. Open Bulk Complete mode
2. Click 'Add info' button near LCA from.preparations stage. Required Info modal with URL should be shown.
3. Add URL. Click 'Save'. Open Required Info modal. 
**Actual result:** LCA is invalid. Comment and URL are shown in Required Info modal.
**Expected result:** LCA should be valid. Only URL should be shown in Required Info modal.
=> [Matrix view] QUICK-FIX Fix required comment validation

src/ggrc-client/styles/components/assessments-bulk-complete-table/_assessments-bulk-complete-table.scss
**Should be merged to "matrix-view".**
Fix broken styles
1. Open Bulk Complete mode.
2. First column should be 300px, 2nd column - 150px, other - 200px.
3. Borders bottom should be shown and not transparent when scrolling with an open absolute element (dropdown, calendar)
Update column width and border style for assessments-bulk-complete table.
=> [Matrix view] GGRC-8750 Fix broken styles

src/ggrc/bulk_operations/csvbuilder.py, src/ggrc/converters/errors.py, src/ggrc/converters/handlers/custom_attribute.py, src/ggrc/converters/pre_commit_checks.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py, test/integration/ggrc/converters/test_import_assessments.py
User should be able to set person type value to null with import and matrix view
1. Create asmt template with Person type LCA
2. Generate asmt
3. Set Person LCA with any user email
4. Export asmt and set Person LCA with '-' value
5. Import spreadshit
Changed LCA Column Handler
=> [Matrix view] GGRC-9070 Set Person type LCA to null value

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
Default value for LCA with Person type should be `-`
1. Open in Bulk Complete mode any Assessment with already set LCA with Person type
2. Remove person for the LCA
3. Click Save answers button
4. Verify that person is removed from the LCA
Fix default value for LCA with Person type.
=> [Matrix view] QUICK-FIX - Fix default value for LCA with Person type

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/assessments-bulk-complete-popover.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/assessments-bulk-complete-popover-content.stache, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-popover/templates/popover-related-objects-header.stache
Incorrect display names for mapped objects (Access Group, etc) on Bulk Complete mode. 
1. Create assessment with type Access Group.
2. Open Bulk Complete mode.
3. Hover '!'  icon near Assessment title.
4. Verify text on Mapped objects popover.
Use `businessModels` to get display name for assessment type.
=> [Matrix view] QUICK-FIX Fix names for mapped objects popover on Bulk Complete grid

src/ggrc-client/js/components/tree/tree-widget-container.js
Assessment tabs page show Bulk Complete mode when redirect to them. 
1. Open Assessment Template tab.
2. Open Bulk Complete mode.
3. Open Assessment Template tab again.
4. Verify that assessment templates is shown.
`bulkCompleteModeEnabled` attribute should be set to `false` after redirection to any other tabs besides Assessment. Otherwise `bulkCompleteModeEnabled` value is kept for any tabs.
=> [Matrix view] QUICK-FIX Fix redirection from Bulk Complete mode

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js
Text on Bulk Complete Confirmation popup is incorrect.
1. Open Bulk Complete mode.
2. Fill LCAs for any assessment.
3. Click Complete button.
4. Verify text on Bulk Complete Confirmation popup.
Fixed text on Bulk Complete Confirmation popup.
=> [Matrix view] QUICK-FIX Fix text for bulk confirmation popup

src/ggrc/views/bulk_operations/utils.py, test/integration/ggrc/bulk_operations/test_matrix.py
CADs collection doesn't work as expected for the Mutliselect LCA
**multi_choice_options** and **multi_choice_mandatory** fields wasn't tracked.
=> [Matrix view] QUICK-FIX Attributes are not grouped by Options

src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/assessments-bulk-complete-container.js, src/ggrc-client/js/components/assessment/assessments-bulk-complete-container/tests/assessments-bulk-complete-container_spec.js
When BE send 0 assessments for Bulk Complete table, the table is empty. Appropriate message should be shown in case on 0 assessments. 
1. Open My Assessment tabs
2. Unassign for assessments.
3.  Open Bulk Complete mode.
4. Verify that the message is shown on Bulk Complete mode.
Added additional check for empty grid when load Bulk Complete mode.
=> [Matrix view] QUICK-FIX Add additional check for empty grid when load Bulk Complete mode

src/ggrc/converters/handlers/evidence.py, test/integration/ggrc/bulk_operations/test_bulk_operations.py, test/integration/ggrc/converters/test_import_assessments.py
Bulk operations override existing evidence data:
CASE 1: Assessment has evidences -> send request from matrix view without evidences addition -> Assessment **has no** evidences
CASE 2: Assessment has evidence URL1 -> send request from matrix view with URL2 -> URL1 was overrided with URL2
**Expected:** previous changes should be saved
- check if import operation works in a bulk mode
- if operations executes in bulk mode -> skip evidences replacement
=> [Matrix-View] QUICK-FIX Attachments are replaced after "Save answers". Should be added.
